### ISSUE TITLE
Add image upload to post type

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1000]
## Introduction:
This feature should allow users to upload images on to posts

## User Stories:
- Deployment admins should be able to add an ‘image’ field to a post type
- When creating or editing a post with an image field, it should show a file upload element
  - When saved the file should be uploaded to the media API, and the media ID (Note: not the media url) should be saved as a value on the post
- When viewing a post with images, the images should be shown on the post detail page
  - Work with Brandon / Seth on how to display these
- When viewing a post list, post images should show in the list as per http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/home-list.html
- Ideally this should be extensible for other file uploads later

**Comment by rjmackay** [comment]
@jshorland double checking on media uploads: should media/images be a custom field on a post type? or should all posts just have images? (like they have a title and description but optional)

**Comment by jasonmule** [comment]
How to add an image to a post

1. Add an image field to a post type.
2. Add a post and select the post type with the image field.
3. Follow the instructions on the image field to upload the image.
4. After the image is uploaded successfully, save the post type as usual.
