### ISSUE TITLE
Export posts to CSV

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1005]
Deployment admins and other users often want to do further analysis on data in a deployment. The quickest way to enable this is to allow a CSV export of posts data.

User Stories:
- When I am viewing a post list I should be able to click a link/button to export the current data set
  - This export should honor the filters that are currently active
  - This export should honor my user permissions
- This should be available to all users, but limit posts to those they have permission to view
- Ideally the data exported should be in a format we could import again..

**Comment by rjmackay** [comment]
Couple of notes on the client side:

1. Can we add a confirm modal when someone clicks the export button
2. Could we add an 'Settings -> export' view too? this would just have a filter for which post types to include.. but export all posts otherwise.
  - we can skip this for this sprint if your short on time. I'd rather finish everything in the sprint instead.

**Comment by jasonmule** [comment]
Could we add the Settings->export view as a separate task?

**Comment by jasonmule** [comment]
How to export to CSV

1. Go to Posts and select the List view option.
2. Use Search & Filter to filter posts that you want to export.
3. Click the Export button in the bulk actions row (it should be next to the Delete button) to save exported posts in a file. Alternatively, you can choose to open Excel and import the CSV data.
