### ISSUE TITLE
Install: bundled single file install

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1006]
We want to make it easier for OSS users to install the platform themselves. One of the confusions is the need to download and *build* the platform and the client. A single pre built package would make life easier for deployers

- Deployer should be able to download a single zip file with both client and api codebases
- Deployer should be able to install the client without having nodejs, npm or gulp. We should ship the everything pre-built
- Deployer should be able to install the client without having run composer
- We can still expect deployers to edit config files: .env on platform api, and config.js on platform client

**Comment by tuxpiper** [comment]
Creater a docker wrapped script to build platform-client . That will help removing the requirement for installers to have nodejs, npm , gulp.

Next will work on bundling platform with the composer deps

**Comment by tuxpiper** [comment]
Added commit 926390046c66a4b2ea8b5de7d66e0b989ce9087c , another docker wrapped script for bundling composer deps with platform .

Next step, I'd suggest creating a "platform-release" repository, with the scripts for combining the platform and platform-client bundles and instructions to deploy them.
