### ISSUE TITLE
Install: support install into a subdirectory

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1007]
- Deployers should be able to install the API into a subdirectory ie. mydomain.com/ushahidi rather than having to be at the root of the domain
- Deployers should be able to install the client into a subdirectory ie. mydomain.com/ushahidiui rather than having to be at the root of the domain

**Comment by rjmackay** [comment]
@jasonmule assigning this to you. Feel free to delegate to anyone else as needed (including myself).

**Comment by jasonmule** [comment]
@tuxpiper Do you want to take a look at this?

**Comment by tuxpiper** [comment]
Sure, I can take a look

**Comment by tuxpiper** [comment]
As far as I can tell, there is nothing in the code restricting this now. I've got single virtual hosts working locally without any issues. This would be purely a matter of documenting this kind of setup.

I guess the question is.. should we update our docs to recommend this setup, or just add it as an option? How should we make that decision? @rjmackay @aoduor 

Copying my nginx/php-fpm setup here so you can see how simple it is:

```
server {
	listen 80 default_server;
	server_name _;

	index index.html;
	root /var/app/server/www;

	location ~ /(api|oauth)/.* {
		# Forward api requests to fastcgi interface to PHP
		rewrite ^(.*)$ /index.php$1;

		fastcgi_split_path_info ^/(.+\.php)(/.+)$;

		include fastcgi_params.conf;

		fastcgi_param SCRIPT_FILENAME           $fastcgi_script_name;
		fastcgi_param PATH_INFO                 $fastcgi_path_info;
		fastcgi_param HTTP_HOST                 $host;
		fastcgi_param SERVER_NAME               $host;
		fastcgi_intercept_errors                on;
		fastcgi_index                           index.php;
		fastcgi_pass                            api_backend;

		break;
	}

	location / {
		try_files $uri $uri/ @missing;
	}

	# Rewrite 404s back to index.html for pushState support
	# All routing is handled by Angular.
	location @missing {
		rewrite ^ /index.html last;
	}

}
```

The apache config wouldn't be more complicated

**Comment by rjmackay** [comment]
I think the recommended set up should be 2 vhosts - but we should document this as a clear alternative.
Deployers on shared hosts are most likely to be successful with a single zip/tarball they can upload, with a .htaccess ready to go.

**Comment by rjmackay** [comment]
@tuxpiper could you document this and other parts of install from bundled release and add that to the ushahidi.com/support pages?

**Comment by rjmackay** [comment]
@tuxpiper Do you have time to document this on ushahidi.com/support ? or should I reassign?

**Comment by tuxpiper** [comment]
@rjmackay I can work on it this week, I'll complete the doc at https://github.com/ushahidi/platform-release/blob/master/dist/README.release.md and more or less copy to the dotcom support pages

**Comment by tuxpiper** [comment]
Done, instructions here: https://www.ushahidi.com/support/install-ushahidi#installing-zipped-release-bundle
