### ISSUE TITLE
Do users really need to determine field-key?

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1011]
So, i'm assuming that this is what determines how the field is named in the DB. Seeing as this gets automatically filled out as the user types out a field name, i don't see the reason why this needs visibility on the UI. 

Additionally, leaving this for users to edit created an opportunity for creation of duplicate field keys. 

Option 1: Hide this field altogether
Option 2: Make this an non editable field(like what we've done with Field Type

![screenshot](http://i.imgur.com/7lT24pk.png)

Thoughts @rjmackay @willdoran @jasonmule :)?

**Comment by willdoran** [comment]
@aoduor I entirely agree, though it should be noted that you could in theory have a non-unique field name and a unique field-key. Though I'm not sure why you would want to do that. We can just make the field-key a hidden field.

**Comment by rjmackay** [comment]
I think there's a possibility of key collision right now - we need to make sure thats fixed before hiding it.

**Comment by jshorland** [comment]
no longer relevant. Closing.
