### ISSUE TITLE
Error Page Appears Every Time Deployment is Refreshed.

### ISSUE THREAD

**Issue by FIU-Editor** [ushahidi/platform#1013]
Every time our users refresh our deployment, bb.fiu.edu, a "Not Found" page is conveyed. Is this solely an HTML problem or something much deeper?

![image](https://cloud.githubusercontent.com/assets/17600339/14437415/144dec12-ffef-11e5-8844-444c388e064b.png)

Thank you.

**Comment by willdoran** [comment]
@FIU-Editor Hi, that looks like a miss config of the web server. It looks as though it's trying to directly server the files rather than going through the angular setup. Could you share your config?

**Comment by FIU-Editor** [comment]
Sorry for the wait, I have the config file attached. Thank you for your
assistance!

**Comment by willdoran** [comment]
@FIU-Editor thanks for getting back to us - I'm sorry I don't see the config. If you replied via email, I'm not positive github grabbed the attachement.

**Comment by FIU-Editor** [comment]
Nope, it doesn't seem that Github accepts the ".conf" file type. Do you
have an email address to which I can send it to you?

**Comment by willdoran** [comment]
@FIU-Editor yep, you can send it to will@ushahidi.com

**Comment by FIU-Editor** [comment]
Thanks, I just sent it.

**Comment by aoduor** [comment]
Flagging this @willdoran @rjmackay @jasonmule, someone on intercom reached out about this.
