### ISSUE TITLE
User gets reassigned to blank role when custom role is deleted

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1014]
### Expected behaviour

Ideally, perhaps we shouldn't be able to delete custom roles till all users on that role have been reassigned to another custom role, or reassign them to a different role. Open to discussing what the best option here would be
### Actual behaviour

Deleting a custom role renders any user assigned to that custom role on a blank/unassigned role.
### Steps to reproduce the behaviour/error
- Delete a custom role
- Navigate to User management page

**Comment by jshorland** [comment]
- as a user with the permissions to manage users, I want to be warned of how many users and which users will be affected when I delete a custom role
- If I choose to proceed with the deletion, I want to be taken to a screen with the list of users that were affected by the deletion, and I want to be able to assign them to new roles, either in bulk or one by one

**Comment by rowasc** [comment]
Closing in favor of #917 . Referencing for when we fix it so we have more context
