### ISSUE TITLE
Add password verification field when creating new users/adding new passwords

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1015]
At the moment, we only have one text field for input of a new password. Would be great to have an additional password field to ensure that the passwords match.

**Comment by jshorland** [comment]
Thought: I would also add we should re-do this completely to have an email sent to the added user's email address and link directs to create new password.

Needs triage and scoping.

**Comment by rowasc** [comment]
@crcommons I'm kind of confused by this. Is it in the qa backlog + in the migration epic because we fixed it for the migration so we want to track it as part of what we fixed?  

or put in another way: is this a ticket Eve can test now, or is it only implemented in the migration?

**Comment by crcommons** [comment]
@rowasc I have NO idea why I was moving this card around. I didn't even work on it nor do I remember ever seeing it. Apparently I blacked out and decided to play around in Zenhub? But seriously, I'm sorry. I really don't know why I did anything with this issue. I have zero recollection of any of this.

**Comment by crcommons** [comment]
Wait, it's vaguely coming back to me now. I think because we're going to address this issue in the new users components, I added it to JS Migration epic. But I don't really know when or why I moved it through to QA backlog.

**Comment by rowasc** [comment]
HA. That's alright. If you think we will spec this out, maybe move it to "ready for spec" ? If not we should close and open one that is related to js migration

**Comment by crcommons** [comment]
Well, we are definitely adding a second password field in the user/create component, but it'll be some time until we update the sign up component. Also, unclear on if we should implement as Angie suggested or what Jess suggested. Thoughts, @rowasc?
