### ISSUE TITLE
No error message passed to user on attempt to create a new user without assigning custom role

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1016]
### Steps to reproduce the behaviour/error
* Create a new user and leave the "Role" field blank
* Click on save

### Expected behaviour
An alert prompting me to select a role to assign this new user should appear on my screen

### Actual behaviour
The "Save" wheels turn in a never ending loop, without the page submitting. See screenshot below
![screenshot](http://i.imgur.com/gzCvZY8.png)

**Comment by rjmackay** [comment]
@jshorland @aoduor Can you retest on QA?
