### ISSUE TITLE
Default "Admin" role should not be editable or deletable

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1017]
ATM, a user with the right permissions can edit the Admin role/delete this role. Since it currently serves as the "Superadmin" role, i would recommend making it non editable or non deletable.

Thoughts @rjmackay @willdoran @jasonmule

**Comment by willdoran** [comment]
In roles we check to make sure the last admin role can not be destroyed, we could add a similar check to users to ensure that there is always at least one full admin in the system. Would that work?

**Comment by zhalloran** [comment]
The display name and description should be editable to allow for contextual/language differences, but I've submitted a pull request that prevents the deletion of protected roles. The protected roles are currently the "Admin" & "User" roles.

**Comment by jshorland** [comment]
Passed testing. Both admin and user are not delete-able.
