### ISSUE TITLE
Unable to sign up as a new user on deployment without "User" role

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1018]
### Steps to reproduce the behaviour/error
* Delete "User" role on your deployment
* Log out of your deployment
* Attempt to create a new user account by signing up

### Expected behaviour
The admin should either
* Be able to set which custom role he/she would like assigned to any new user signing up on their deployment

OR

* This "User" role should not be editable/ deletable(is that even a word :P). 

In v2 we had the "Superadmin" and "Member" roles as defaults that could not be modified/deleted.

### Actual behaviour
* I was able to create a new user on a deployment with the "User" role
* Registration failed for creation on a deployment without the "User" role

cc @willdoran @rjmackay @jasonmule

**Comment by jshorland** [comment]
Passed testing. Member role is now uneditable and un delete-able, and visitors can successfully sign up to the deployment under that role.
