### ISSUE TITLE
Double check that analytics are functioning properly on deployments

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1019]
### Expected behaviour

Most important metrics to track properly: 
- page views
- uniques
- time on site
### Actual behaviour

Currently seeing analytics that appear to be working correctly in https://citycrime.ushahidi.io/views/map
(see screen shot), but can't access in analytics dashboard when logged in. 
### Steps to reproduce the behaviour/error

![screen shot 2016-04-12 at 11 17 34 am](https://cloud.githubusercontent.com/assets/3224856/14467375/a64dc40a-00a0-11e6-9a35-0e1182d52b4f.png)

**Comment by rjmackay** [comment]
@jshorland we're currently using the same GA profile for ushahidi.com and ushahidi.io
We should probably split: .com, ushahidi.io, deployment.ushahidi.io into their own profiles.
The stats for deployments would still be aggregated as 1 profile though.

**Comment by jshorland** [comment]
@rjmackay is this fixed? can we close?

**Comment by rjmackay** [comment]
Closed in favour of ushahidi/platform#1524
