### ISSUE TITLE
Method of tracking OSS installs

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1020]
### Expected behaviour
- total count of OSS installed instances for DIV reporting metrics

### Actual behaviour
- we currently pull cumulative count of downloads from GithubAPI 
- this count doesn't include clones, and doesn't account for installs that are aborted before successful install
- we currently do a terrible estimation of OSS cumulative download total *2 to approximate. 

There might already be an issue for this mechanism that i'm not seeing? cc: @rjmackay cc: @aoduor

**Comment by aoduor** [comment]
Do we currently actually track OSS installs at all?

**Comment by jshorland** [comment]
Just downloads of the code off of github.

**Comment by jshorland** [comment]
Closing in favor of #834
