### ISSUE TITLE
Notifications are currently broken

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1025]
### Steps to reproduce the behaviour/error
* Log into your deployment
* Select a saved search or collection
* Click on Add notification
* Go to notifications management page

### Expected behaviour
I should see the following screen allowing me to determine how I receive notifications, add new contacts, and turn notifications on and off
![screenshot](http://i.imgur.com/2WHajGz.png)

### Actual behaviour
This is the current screen I get, that throws a "contact" error on trying to toggle the button on and off.
![screenshot](http://i.imgur.com/MSe9iVP.png)

**Comment by rjmackay** [comment]
This doesn't happen to .io users. It only happens on deployments an 'admin' user where 'admin' should actually be an email but isn't..
Can be worked-around by updating your email.
