### ISSUE TITLE
Pre-header text visible in support emails after creating .io deployment

### ISSUE THREAD

**Issue by sebm90** [ushahidi/platform#1028]
![image](https://cloud.githubusercontent.com/assets/5349387/14543854/7f64eefc-0296-11e6-843a-3b319fd06677.png)

**Comment by rjmackay** [comment]
Found where this was.. I missed it when grabbing the template originally

**Comment by rjmackay** [comment]
This should be fixed on mandrill emails, I've fixed it on my branch for switching to mailgun too

**Comment by rjmackay** [comment]
@sebm90 @jshorland could you retest?
