### ISSUE TITLE
Password field in Data sources-> Email config should not display password

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1029]
Seems like it's just a text field at the moment, so it displays my password in plaintext
Expected behavior: 
- When entering the password, use a password field
- By default, do not show the full password when opening the configuration screen. Have a "see password" button, similar to what we do in app/settings/user-settings/user-settings.html when configuring the HDX settings. 

Example from what we do for HDX API 

![Screenshot from 2020-10-12 16-22-36](https://user-images.githubusercontent.com/2434401/95783067-71029b00-0ca7-11eb-8b2c-0978812182fe.png)

And then you click and can still see it

![Screenshot from 2020-10-12 16-25-11](https://user-images.githubusercontent.com/2434401/95783121-87a8f200-0ca7-11eb-98a6-1284d2a3dcaa.png)

---------

Other notes:
Future music, but Ideally, I would prefer to not save a password for their email at all. Having a forwarding address for a ushahidi provided email so we never actually need access to  a user's email would be good and safer for users. ie incoming+rominacsvsms@ushahidiemailserver.io or rominacsvsms@ushahidiemailserver.io directly , and if users really want their own email, we can instruct them to configure their  email account to forward relevant emails to that address that only we can access and doesn't need to be configured at all basically.
Aha! Link: https://ushahiditeam.aha.io/features/PROD-699

**Comment by rjmackay** [comment]
I'm not convinced this is a good idea. Being able to see the password is useful for checking your settings.

**Comment by rowasc** [comment]
<img width="828" alt="Screen Shot 2019-06-09 at 14 55 58" src="https://user-images.githubusercontent.com/2434401/59162399-b832b780-8ac6-11e9-8bb5-e537e8eaf3f8.png">

Still happening .
This has been frustrating when screensharing especially, I think we should fix it.

**Comment by Erioldoesdesign** [comment]
Agreed! a show/hide function would be super helpful and we should hide behind **** or dots by default. We should also probably require 'showing' to be password protected too.

**Comment by vanessa-ariel** [comment]
Hi @Angamanga, can I work on this issue? (:

**Comment by rowasc** [comment]
@vanessa-ariel assigned to you! Thank you. I just edited the spec's expected behavior so it's more clear, LMK what you think/if you have questions.
