### ISSUE TITLE
Add option to clear/remove previously added data source config details

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1030]
Original issue: 
----------
### Expected behaviour

When I delete data source configuration settings, they should be permanently erased
### Actual behaviour

I navigate our of the data source settings page, then come back and find the same details i had earlier erased STILL there.
### Steps to reproduce the behaviour/error
- Add data source details, save and enable
- Delete data source config details leaving all fields blank.
------------
Update: 
this is still happening. While I can disable a datasource, it won't let me save the options as blank or easily delete it.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-698

**Comment by rjmackay** [comment]
@jshorland this is really a feature request. I don't think we should target this for mustang release. Can I drop priority?

**Comment by rjmackay** [comment]
@jshorland I don't think this was built? did you really want to close it?
