### ISSUE TITLE
Secret Key option in smssync configuration shouldn't be a required field

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1031]
### Expected behaviour

I should be able to save changes without a secret key for SMSSync settings
### Actual behaviour

I get an error message prompting me to fill in this field
### Steps to reproduce the behaviour/error

Enable SMSSync service on deployment WITHOUT a secret key.

Or are we now enforcing the use of secret keys for smssync config?

Aha! Link: https://ushahiditeam.aha.io/features/PROD-697

**Comment by jshorland** [comment]
@rjmackay are secret keys required for SMSsync now?

**Comment by rowasc** [comment]
This might be the same as https://github.com/ushahidi/platform/issues/1032
