### ISSUE TITLE
No need for "Secret Value" field in Nexmo Data configuration

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1032]
---------
Original request:

The nexmo platform doesn't currently allow for setting a secret value, but we have this as a field on the configuration page. We should remove it. cc @sebm90 

![screenshot](http://i.imgur.com/hNGOyxA.png)

I'm checking in with their support team to confirm plans for supporting this

----------

Update: while the secret *is* required, we should do a better job of explaining what it means and how too use it since it's not intuitive at all. 
Notes from Will and Angie
> The secret value should I think be named better, it's actually an Ushahidi secret value. Nexmo forwards texts to the ushahidi platform using a callback url that the user configures in the Nexmo dashboard. That secret let's the platform ensure that the texts being sent to it from Nexmo or wherever else are legitimate.

This is where they have to set it up: 
![screenshot](http://i.imgur.com/FY03Fqh.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-696

**Comment by willdoran** [comment]
@aoduor The secret value should I think be named better, it's actually an Ushahidi secret value. Nexmo forwards texts to the ushahidi platform using a callback url that the user configures in the Nexmo dashboard. That secret let's the platform ensure that the texts being sent to it from Nexmo or wherever else are legitimate.

I'm not sure if I explained that clearly.

**Comment by aoduor** [comment]
Ah, so ideally that's what would go here in your Nexmo dashboard?

![screenshot](http://i.imgur.com/FY03Fqh.png)

We should probably add some details on how the user can configure that callback URL

**Comment by willdoran** [comment]
Yep, exactly, and yes we absolutely should. Ideally we could have a short sentence explaining it because it's not intuitive at all.

**Comment by aoduor** [comment]
Yes please :) ![screenshot](http://24.media.tumblr.com/tumblr_m5ooh7WuPL1rxk0pjo1_250.gif). LMK once you have it up/something i can add into our docs :)

**Comment by rowasc** [comment]
Confirmed that this is still happening in v3/v4

**Comment by rowasc** [comment]
This would be a good first issue for folks If we figure out how to properly show the explanation. Tagging so we review it later on.
