### ISSUE TITLE
No way to see current value of "who can see this"

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1037]
### Expected behaviour
I can see value of "who can see this" somewhere on post preview and detail views

### Actual behaviour
I can only see the current value if I open the drop down

### Steps to reproduce the behaviour/error
1. Go to a post detail view
2. Look for current visibility??

**Comment by jshorland** [comment]
Mustang addresses this.

**Comment by rjmackay** [comment]
Close in favor of #1055
