### ISSUE TITLE
Step validation fails when setting 'who can see this' on post detail page

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1042]
### Expected behaviour

Step validation should work as normal

Ideally, if you can't set the post visible to everyone we shouldn't even show the dropdown. since you can't use it.
### Actual behaviour

Steps are treated as incomplete
### Steps to reproduce the behaviour/error

On a post with all stages complete
- Go to a post detail page
- Click on 'who can see this'
- Select 'everyone' to publish
  Error appears, instead of publishing.

**Comment by jshorland** [comment]
Also see #914 which was closed. Related?

**Comment by rjmackay** [comment]
@jshorland I think #914 is more just 'confusing' but not broken.
When trying to set audience on the detail page.. it think it fails even if the stage was complete.
Its still confusing but we can address that along with mustang changes..
