### ISSUE TITLE
Shadrock will need tokens for a training in June

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1043]
Shadrock has a training in June and will need upgrade tokens. Ideally they would be time-bound (free full featured trial perhaps?)

Flagging it now and putting a date on it so we don't forget. I'll add more details in the coming weeks. @Shadrock can you give additional details as to how many you think you'll need, etc?

**Comment by aoduor** [comment]
Can I just say, super excited that we have this getting set up! WOOOO!

**Comment by rjmackay** [comment]
@jshorland I think you can handle this right?

**Comment by Shadrock** [comment]
@jshorland @rjmackay this is no longer an issues so can be closed out. I may need tokens in the future but can follow-up as needed.
