### ISSUE TITLE
Date fields returned as date time fields

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1044]
### Expected behaviour
- Date fields should be returned in the format yyyy-MM-dd
### Actual behaviour
- Date fields are returned in the format yyyy-MM-dd HH:MM
### Steps to reproduce the behaviour/error
- Create a new date entry on a post
- Save post
- View post detail

**Comment by rjmackay** [comment]
Actually think dates should be formatted better than just YYYY-mm-dd even
