### ISSUE TITLE
Mustang: Update post edit view

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1054]
- Update markup to match mustang PL
- Function is very similar to before. Notably:
  - Delete button is now pulled out explicitly at the bottom
  - Cancel / Save is in the top bar
  - Vertical tabs are now horizontal tabs. We might need a new directive for this.
- Ideally 'who can see this' shouldn't save until the post is saved.. resolving ushahidi/platform-client#148

Related bugs:
- https://github.com/ushahidi/platform/issues/957
- https://github.com/ushahidi/platform/issues/319

**Comment by rjmackay** [comment]
@brandonrosage Currently the pattern library is missing any UI for marking steps complete/incomplete when editing. Is that intentional?

**Comment by brandonrosage** [comment]
Steps are represented in the Pattern Library as more narrowly-defined features. As we've discussed in the past, they're treated *not* as open-ended "Steps," but as 'templatized' tasks: Verify and Translate.

So, in the "Post: Edit" layout, for example, each task has a toggle switch for indicating that it's complete:

![image](https://cloud.githubusercontent.com/assets/1136279/15023081/6cb18d48-11f4-11e6-8f72-52a7ea25ab33.png)

![image](https://cloud.githubusercontent.com/assets/1136279/15023103/88890faa-11f4-11e6-92f6-b6c5ab91c214.png)

**Comment by rjmackay** [comment]
@willdoran its probably worth trying the `ng-model-options` directive on post edit forms too - as it might eliminate some of the old logic.
