### ISSUE TITLE
Mustang: timeline mode

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1056]
- Replace post list view with new timeline view
- Function is similar. But adds:
  - Context sidebar
  - Icons to show 'visible to' state
  - Groupings by day ie. 'Today' header
- Include filter mark up but leave wiring to #1049 
- Double check anything that appears to be removed from the UI, this might be an oversight in PL
- Out of scope
  - switch from paginated view, to 'load more' style
  - Share button

**Comment by rjmackay** [comment]
@brandonrosage can you confirm how the 'Today' heading works in the timeline view? do we have a heading per day? or longer timespans as you go further back?

**Comment by brandonrosage** [comment]
The intention is for there to be a few different "scales":

* By day
* By month
* By year

So if the dataset included posts spanning less than two months, it'd include stamps "by day." If they spanned more than two months, but less than two years, stamps would be "by month." And if they spanned more than two years, stamps would be "by year."

But I'm open to discussion on this logic.

**Comment by rjmackay** [comment]
Kinda thinking out loud..

> So if the dataset included posts spanning less than two months, it'd include stamps "by day." If they spanned more than two months, but less than two years, stamps would be "by month." And if they spanned more than two years, stamps would be "by year."

I think what matters is the frequency of posts: is there a post per day? or 10? or only a post per week? .. if the stamps appear between every post its weird, but if they don't appear often enough they're no longer useful.

However.. I can't really figure out the frequency all that easily with the current API. So I'm going to just start showing daily timestamps and see how that works out.
