### ISSUE TITLE
Mustang: Saved searches dropdown

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1060]
- Saved searches menu is now a dropdown from the filter bar
- Out of scope
  - New function: search by keyword

<img width="589" alt="screenshot 2016-05-04 10 22 09" src="https://cloud.githubusercontent.com/assets/7965/15004979/5e9aa1ae-1212-11e6-9243-1a0b9bc28a94.png">

**Comment by rjmackay** [comment]
@brandonrosage The "Create new" button here is new. Previously we created a saved search from the current search params .. if thats still what this intends then I don't think its very clear.

**Comment by brandonrosage** [comment]
@rjmackay The primary path to this is still to simply search, see a summary of your parameters, and optionally select the appended "Save Search" button: 

![image](https://cloud.githubusercontent.com/assets/1136279/15020632/7b13a27e-11e8-11e6-986e-281baa18c1cb.png)

The secondary path -- the "Create new" button within the "Saved Searches" menu -- would help users discover this capability without forcing them to first perform a search: 

![image](https://cloud.githubusercontent.com/assets/1136279/15020936/d658ceba-11e9-11e6-979e-24f7767ca6d9.png)

They could find the dropdown menu, peruse others' Saved Searches, decide they want to create their own, and immediately have a pathway to do it, without having to intuit that they'd have to leave the "Saved Searches" dropdown menu and use other controls to even reveal that functionality.

In either case, selecting the "Create new" or "Save Search" buttons would display the "Create new Saved Search" modal:

![image](https://cloud.githubusercontent.com/assets/1136279/15020780/2a88dc1a-11e9-11e6-9b24-f0f7e05a6fc4.png)

The "filters" tab within it is intended to, A, reiterate the Saved Search's properties, and B, support the raw path of creating a new saved search without first performing a search. It's structure echoes that of the "Filters" dropdown:

![image](https://cloud.githubusercontent.com/assets/1136279/15020836/6d17b79a-11e9-11e6-8c39-7d31b88e40ab.png)
