### ISSUE TITLE
Mustang: Modal, notifications, sliders

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1061]
- Update modals for mustang PL
- Update notification slider
- Update alert modals
- Update plan limit modals
- Update confirm modals

Related bugs:
- https://github.com/ushahidi/platform/issues/300

**Comment by rjmackay** [comment]
@brandonrosage is the slider in mustang still expected to hide automatically after a few seconds? or does it always use a close button instead?

**Comment by brandonrosage** [comment]
Great question. I've revised the *message.js* to, by default, hide messages after five seconds. If the function is called with the 'sustain' parameter set to 'true,' the message won't automatically be hidden.

https://github.com/ushahidi/platform-pattern-library/commit/4172481167b125df768f628636bd23309c622018
