### ISSUE TITLE
Mustang: Update tour and plan change views

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1064]
- Update tour view
- Update plan change view
- Move payments out of a modal and into main content area?

**Comment by rjmackay** [comment]
@middle8media these live in a different codebase. Lets sync up when you're ready to start this and I'll get you set up.

**Comment by middle8media** [comment]
@rjmackay I'm ready to tackle this

**Comment by rjmackay** [comment]
Alright. The tour all lives in the a separate code base here: https://github.com/ushahidi/platform-cloud-interface

- Clone that
- Copy api/.env.example to api/.env
- Copy web/.env.example to web/.env
- `cd api/` and run `composer install`
- `cd web/` and run `composer install`
- In the base of the repo run `vagrant up` and that should build a dev server
- `cd api/` and run 

  ```
  ./artisan migrate:refresh --seed
  ./artisan oauth2:client webapp secret
   ```
- Add to /etc/hosts
  ```
  192.168.34.10 cloud.app api.cloud.app
  ```

.. hopefully that all works and you should finish up with a server running on http://cloud.app/create and http://api.cloud.app/tiers
(Note http://cloud.app/ will just redirect to ushahidi.com)

Its a little complex so if and when you hit issues let me know.
