### ISSUE TITLE
Adjust image size on upload 

### ISSUE THREAD

**Issue by jasonmule** [ushahidi/platform#1067]
### Note for any OSS contributors
- we are at the spec writing stage on this issue, comments welcome. 
- this isn't ready for coding, it's still in the spec stage 

### Writing the spec
Requirements: When a user uploads an image, we should automatically generate one or more lower sized images to serve in the user interface.

It should be possible to configure, through environment values
- Desired max image width (or nothing, if we don't want to change that)
     - used for resizing an uploaded file to display in posts ie : ```Image::make(Input::file('photo'))->resize(400, 400)->save('foo.jpg');```
- Desired compression (or nothing if we don't want to apply any)
    - used to make image into a smaller image by converting to JPEG and then adding compression ( ie this https://stackoverflow.com/questions/31531569/laravel-image-intervention-compression ) 

A few good default images should also be available to load from the client: 
- a small image (ie 150px) to ensure we can display it in the post list in data view or the post popups in the map view
- a medium image we can display when looking at a post detail (opening a post)

Note: refactored old issue about image sizes since we had one already

Aha! Link: https://ushahiditeam.aha.io/features/PROD-695

**Comment by rowasc** [comment]
We still need to define: 
- what would be a good default? do we need to automatically general  -thumb, -medium, -large images as well? I think a -medium size image for the post view and a -thumb sized image for the post card when a post isn't open would be ideal. 
- do we let deployers decide on all sizes or just the max width and then create the rest of the image sizes? I think it'd be ok to make all size options configurable.

need to go out now but leaving a very rough draft above for discussion , in case someone wants to help spec this out

cc @tuxpiper @edwinmnemonic

**Comment by stacytonui** [comment]
Hey, Outreachy applicant here, can you please assign me this issue?

**Comment by rowasc** [comment]
@stacytonui this issue needs to be fully spec'd yet, do you want to help get it to that point? Basically we need more details on how it'll be implemented so before starting to code it you'd need to work with us (through comments here) on defining it. Please note this may involve both backend and frontend changes. 
Thanks!

**Comment by Sunairaa** [comment]
Hey @rowasc and @Angamanga i would love to work on frontend changes.. can you please assign this task to me and share details?

**Comment by rowasc** [comment]
@Sunairaa there's already a ticket assigned to you. Thanks!
