### ISSUE TITLE
Mustang: Update user settings

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1069]
- Update user settings markup

**Comment by willdoran** [comment]
- [ ] Change image_header to deployment_logo
- [ ] Rebuild map settings management in settings-map-directive
- [ ] Change save button for datasources
- [ ] For general settings pattern, add cancel button to reset content on each page
- [ ] Mode context will be created per template

**Comment by rjmackay** [comment]
@willdoran those points are all part of #1063 not this ticket. Feel free to claim that after this one though.

**Comment by willdoran** [comment]
@rjmackay I think there is a split then between the two tickets. I've been working through #1063 with @middle8media and these are elements that have come out of it so far. So we're moving them forward in parallel. I can move them over to #1063 but it might be better to redescribe this ticket to cover directive/functional changes as a result of the template changes. What do you think?

**Comment by willdoran** [comment]
Ah no, nevermind I see the confusion! I'll move it around.
