### ISSUE TITLE
Unable to upload image to post

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1072]
### Expected behaviour
* Clicking on upload should upload my image, and subsequently i should be able to save the post

### Actual behaviour
* Error console returns the following message: Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
* I get an alert saying " Could not locate any media matching [id: 9]"
* On trying to save the post without upload, post saving goes on a never ending loop.

### Steps to reproduce the behaviour/error
* Set up a deployment on staging
* Add image field to post type (set as required)
* Save
* Attempt to create a new post

**Comment by jshorland** [comment]
The same happened for me, but no error was returned on qa.ushahididev.com

Adding screen shot of never ending spinning wheel 

![screen shot 2016-05-11 at 2 36 27 pm](https://cloud.githubusercontent.com/assets/3224856/15197368/f179cc98-1785-11e6-92eb-84e6a90d6779.png)

**Comment by rjmackay** [comment]
Turns out I screwed up the deployment. Now I've run migration properly could you try this again?

**Comment by rjmackay** [comment]
@jshorland make sure this gets a retest??

**Comment by jshorland** [comment]
Confirmed fix. Passes QA.
