### ISSUE TITLE
Padding between Image field and Rename/delete buttons too tight

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1073]
### Expected behaviour
Normal spacing

### Actual behaviour
Spacing is too tight

### Steps to reproduce the behaviour/error
1. login to qa.ushahididev.com
2. navigate to post types
3. select basic post
4. scroll down to fields
5. see screen shot
![screen shot 2016-05-11 at 2 26 10 pm](https://cloud.githubusercontent.com/assets/3224856/15197194/f6323640-1784-11e6-865e-7a3480cb654b.png)

**Comment by rjmackay** [comment]
@jshorland I think this was broken **before** the april sprint? Can we just fix this as part of the mustang sprint?
