### ISSUE TITLE
QA testing: Can't successfully save new post without image on qa.ushahididev.com

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1074]
### Expected behaviour
Add relevant information to form -- NO IMAGE INCLUDED 
Click "save post"
Platform returns confirmation message that post was saved
See post in all posts
### Actual behaviour
Add relevant information to form
Click "save post"
Spinning wheel of infinite doom appears

### Steps to reproduce the behaviour/error
1. login to qa.ushahididev.com
2. click "add post"
3. Select basic post
4. Add all information EXCEPT image
5. Click save post

**Comment by rjmackay** [comment]
Turns out I screwed up the deployment. Now I've run migration properly could you try this again?

**Comment by rjmackay** [comment]
@jshorland please retest with mustang??

**Comment by jshorland** [comment]
done. QA passed.
