### ISSUE TITLE
Process geographical metadata from images (image geotagging)

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1075]
### Expected behaviour

It would be nice if we could process the geographical metadata (geotagging) that sometimes is attached to images and use that as post coordinates (in absence of explicit coordinates provided by the user, probably)

There are several metadata formats out there, but EXIF seems to be the most widely used in digital cameras. IPTC and XMP may be worth taking a look.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-694

**Comment by rjmackay** [comment]
Mentioned in https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/tech/conversations/9014117161

**Comment by micuentadecasa** [comment]
I also think it can be very interesting

**Comment by rowasc** [comment]
oh . Nice. I think this may be interesting to add, but I would suggest we do it as opt-in when the user uploads the image, not default (or at least that we display what we did prominently so the user can make a decision to remove that) 

Tagging for review

**Comment by Erioldoesdesign** [comment]
Oooo yes! this was talked a lot about at Rightscon 2019 BUT CAUTION!

Some users may be put in danger if this info goes public on a deployment without them opting into sharing the image metadata. Also, most people don't know how to turn metadata on images on/off and are largely poorly educated on this whole thing from a data privacy pov.

Deffo wanna scope and look into though!
