### ISSUE TITLE
Create datepicker directive

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1078]
Create a date picker directive to match mustang PL.

**Comment by middle8media** [comment]
@rjmackay the PL uses http://amsul.ca/pickadate.js/ which requires jQuery. I am wondering how to approach this since the client only has JQlite.

**Comment by rjmackay** [comment]
I spent a while trying to make pickadate work with just jqlite and no jquery but got stuck .. it too tied to jquery itself so I'm not really sure what to do there.

**Comment by rjmackay** [comment]
Found an angular fork of pickadate: https://github.com/alongubkin/angular-datepicker
Can you try that? Its not maintained but there are bug fixes on forks if you hit issues.

**Comment by middle8media** [comment]
I will give it a shot
