### ISSUE TITLE
Wire up create post button

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1086]
- this already have directive stub https://github.com/ushahidi/platform-client/blob/develop/app/post/views/add-post-button.directive.js
- populate it from the form endpoint and show a dropdown as per the pattern library
- check @willdoran hasnt already wired on his branch
- link each item to /posts/create/FORMID

**Comment by zhalloran** [comment]
@willdoran Just want to make sure you haven't started work on this.

**Comment by willdoran** [comment]
@zhalloran Nope go for it

**Comment by zhalloran** [comment]
@rjmackay please assign code review for https://github.com/ushahidi/platform-client/commit/5546e83dc8332af85212502e06862e65e277ac4e. I ended up putting an inline style declaration to override the display value in the fab-options class here: https://github.com/ushahidi/platform-client/blob/5546e83dc8332af85212502e06862e65e277ac4e/server/www/templates/posts/views/add-post-button.html#L12.

I'm not thrilled with that solution. Still haven't taken a look at tests yet. Will do so tomorrow if time allows.

**Comment by rjmackay** [comment]
Sure. Generally for code review: create a pull request and assign it to will, myself and jason (since we can now assign all of us)
