### ISSUE TITLE
Settings list shows blank to normal users

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1091]
Should redirect to home if the user has no settings permissions..

**Comment by zhalloran** [comment]
@rjmackay I just put in a check for hasManageSettingsPermission() in the controllers, for some of the controllers, a login popup is displayed after redirect to home. It got me thinking that maybe it should redirect to the login screen instead of the home screen?

**Comment by zhalloran** [comment]
The code is here: https://github.com/ushahidi/platform-client/tree/hot-fix/1091-settings-redirect

**Comment by zhalloran** [comment]
Quick refinement to my redirect suggestion: Redirect to login screen if user is not logged in, redirect to home if user doesn't have permission. Also, do we want to leave the Setting icon in the menu when users don't have permission?

**Comment by zhalloran** [comment]
Um, nvm on the settings button. I literally do not know anything other than what I'm working on at the moment. Taking care of that bug now :)
