### ISSUE TITLE
Email configuration not split into tabs as in Pattern Library

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1096]
### Expected behaviour

While on QA site, my email configuration screen should be split into tabs as shown below.

![screenshot](http://i.imgur.com/FNZKdYzr.png)
### Actual behaviour

QA site displays entire email config on one loooooong page as shown below.

![screenshot](http://i.imgur.com/z0H5Fna.png)
![screenshot](http://i.imgur.com/X3TNahp.png)
### Steps to reproduce the behaviour/error
- Click on Settings, then data sources, and select email config

**Comment by aoduor** [comment]
Quick question on this one: What timeline of implementation are we looking at or this?

**Comment by brandonrosage** [comment]
This is spelled out in #1179, but I've staged layouts for dedicated views of Data sources, including [Email](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources-email.html). That particular example is staged for the scenario where it's not yet configured, and therefore doesn't display any importing settings, yet.

![email configuration](https://cloud.githubusercontent.com/assets/1136279/16529518/0454f876-3f89-11e6-90e1-2e788dd544c0.png)

Those settings are commented out in the layouts' HTML, with annotations regarding the logic to be applied there.
