### ISSUE TITLE
Unable to create new categories

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1098]
### Expected behaviour
I should be able to save and create a new category after adding required details

### Actual behaviour
Screen is non responsive, and error console returns the following

![screenshot](http://i.imgur.com/GDfEqV8.png)

### Steps to reproduce the behaviour/error
* Click on categories from settings page
* Click on add icon
* Add category details and save

**Comment by willdoran** [comment]
This is fixed and in develop. It should go into qa with the next push.

**Comment by rjmackay** [comment]
Assigning to @aoduor and @jshorland to confirm fix. Redeploying as I write.

**Comment by aoduor** [comment]
This is fixed too.
