### ISSUE TITLE
No custom color selection during category creation.

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1099]
Not sure whether this belongs in the PL Repo or here
### Expected behaviour

As a user, i'd like to be able to select custom colors for my categories as opposed to a fixed list of four
### Actual behaviour

On category creation, i'm only presented with four options. Red, Gold, Blue, and Green
### Steps to reproduce the behaviour/error
- Click on settings, then categories
- Click on the add category icon
- attempt to select a category color.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-692

**Comment by willdoran** [comment]
@aoduor the colour picker let's you either pick from a fixed list or enter a hex value for the colour you'd like. Does entering the hex value work for you? Or are you only seeing the default colours?

**Comment by aoduor** [comment]
Oh, so we can add custom hex values? This isn't intuitive for non technical users - most people don't know what hex values match to other colors. Best thing would be to add a color spectrum to select from as we have done in the past, such that when they click on the field, it pops up and they can select a color from there.

@willdoran a little clearer?

**Comment by willdoran** [comment]
Yep, much clearer, let me ping @brandonrosage may be he can comment on what we could add to bridge for users.

**Comment by brandonrosage** [comment]
@aoduor I've re-written this pattern to leverage a plugin, MiniColors, to provide a full-spectrum color picker. I've configured it to display the four suggested "swatches."

Example:
![Color picker](https://d1zjcuqflbd5k.cloudfront.net/files/acc_450437/17aQd?response-content-disposition=inline;%20filename=Screen%20Capture%20on%202016-06-06%20at%2013-58-43.gif&Expires=1465239863&Signature=BWls19EZwTWEi6o0vn91IRYfBFf-CBgSpzg7~xmFPvx9iROJbo7PW8~XFyhsRwTIlwqYZVnBoLLIgz-7ynZlRIlCXHRFjD~-Vh3O05eooDjtJlTGkXvxt2hvriG-kj8SzDChwjun0k-LHSMhKWML1omeOGYgwHuNSk7G~GNNVto_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

@willdoran The plugin is called by `custom-fieldset.js`, which looks for custom fieldsets with the attribute `data-fieldset-type="color"`.

**Comment by aoduor** [comment]
Adding a note in here that this would also be super useful when assigning colors to surveys. cc @jshorland @brandonrosage

**Comment by rowasc** [comment]
Confirming we still don't have this for categories

**Comment by Erioldoesdesign** [comment]
Just noting that as we have the ability to do this for surveys, categories should use the same approach if possible!

**Comment by rowasc** [comment]
Agree. @Erioldoesdesign since you may have an idea already and I want to take full advantage of it😁 , how do you envision using the category colors? I don't see a way to assign category colors anymore, and also I don't see how we would use them right now? - I was convinced this was a thing until I checked 😬
