### ISSUE TITLE
No feedback returned to use when no categories exist on a deployment

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1100]
### Expected behaviour
When no categories exist on a deployment, I would expect a "No categories on this deployment" message visible on the category list page or something.
### Actual behaviour
No message exists, as shown in the image below
![screenshot](http://i.imgur.com/bVN0lvv.png)
### Steps to reproduce the behaviour/error
* Click on settings
* Then click on categories

**Comment by rjmackay** [comment]
Assigning @zhalloran too - whoever gets to it first.

**Comment by zhalloran** [comment]
@rjmackay @willdoran @jasonmule Did someone already get this? This is what I'm seeing on that view now:
<img width="893" alt="screen shot 2016-06-08 at 12 02 45 am" src="https://cloud.githubusercontent.com/assets/446225/15882435/7ad9ae2c-2d0c-11e6-9617-062f9c1c556b.png">

**Comment by zhalloran** [comment]
I see what the issue is now. It's a layout bug. The first time the page renders, the list is in the DOM, but is under the filter bar at the top. looking into it.
