### ISSUE TITLE
Differentiate "Add" and "Edit" Screens

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1101]
### Expected behaviour
When adding e.g a new role/category, i expect the "Add" screen to be different from the "Edit screen" - i.e i shouldn't see a "DELETE THIS ROLE" button if it doesn't even exist already. 

### Actual behaviour
This is the screen i see on the "Add" screen for roles
![screenshot](http://i.imgur.com/ZWgK9il.png)

### Steps to reproduce the behaviour/error
* Click on settings
* Select Roles and attempt to create a new role.

**Comment by willdoran** [comment]
This should be switching depending on mode, I'll check it and fix it.

**Comment by willdoran** [comment]
Ok, this is fixed and in develop, it should go to qa the next time it's pushed'

**Comment by aoduor** [comment]
Looking good! I'll close this out.

**Comment by aoduor** [comment]
Reopening, for the sake of adding new surveys.

See screenshot below @rjmackay 

![screenshot](http://i.imgur.com/hvRuC9H.png)

**Comment by aoduor** [comment]
Aaaaaaaaand Field addition too. 

![screenshot](http://i.imgur.com/tK4hMVW.png)

**Comment by aoduor** [comment]
Some more details on this for the edit field.

![screenshot](http://i.imgur.com/NKygD0r.png)

**Comment by willdoran** [comment]
Should be fixed by [284](https://github.com/ushahidi/platform-client/pull/284)
