### ISSUE TITLE
Animations on dropdowns etc

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1106]
- Add post button animation
- Filters animation
- Anywhere else data-toggle-animate appears

**Comment by jshorland** [comment]
Is this still an issue?? I can't seem to see exactly whether it is or not on QA

**Comment by rowasc** [comment]
Closing as not relevant for the moment since we have bigger issues in filters that might render this unnecessary (and would have to be handled in a redesign of filters/data view)

**Comment by Erioldoesdesign** [comment]
100% agree @rowasc animations are not very accessible too!
