### ISSUE TITLE
Yellow icon lays over number of selected items on category list page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1108]
### Expected behaviour
I should be able to clearly see the number of categories i've selected from this list page.

### Actual behaviour
The yellow icon is lying smack over the number of selected items 
![screenshot](http://i.imgur.com/bDDANDe.png)

### Steps to reproduce the behaviour/error
* Click on category settings
* tick the checkbox adjacent to any category

This is probably something that needs to be fixed on PL, yes? cc @brandonrosage

**Comment by brandonrosage** [comment]
In the PL, any time a listing toolbar is invoked, the "floating action button" is moved out of view: http://d.pr/i/5Drc/5wcML0N7

It does this by disabling the button -- literally adding the `disabled` attribute to the button -- which animates it out of view. *listing.js* handles all the interaction with the listing toolbar, [including the disabling of the "FAB."](https://github.com/ushahidi/platform-pattern-library/blob/mustang/assets/js/custom/listing.js#L27-L42)
