### ISSUE TITLE
Cursor is misplaced on Post Title

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1109]
<img width="923" alt="screen shot 2016-06-07 at 10 32 58 am" src="https://cloud.githubusercontent.com/assets/1618793/15868212/a8729284-2c9b-11e6-9b34-de5baf858452.png">
### Steps to reproduce the behaviour/error
Create a basic post, click on the title, the cursor is in the wrong place

**Comment by jshorland** [comment]
Also, can't save or input any other fields. only title appears.

**Comment by rjmackay** [comment]
@jshorland I've create #1121 and downgraded this. Need to distinguish issues. If the cursor is in the wrong place.. not the end of the world. If we can't create post... kinda a show stopper.
