### ISSUE TITLE
Map zoom is in the wrong location

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1110]
### Steps to reproduce the behaviour/error
Believe is should be in lower left corner

<img width="446" alt="screen shot 2016-06-07 at 10 36 52 am" src="https://cloud.githubusercontent.com/assets/1618793/15868246/d3f0e186-2c9b-11e6-8aa6-2c5ac98ba23e.png">

**Comment by jshorland** [comment]
I’ve logged and we’ve fixed this bug before. Why the reappearance? cc: @rjmackay

**Comment by aoduor** [comment]
This is related to #1108 as well.

**Comment by rjmackay** [comment]
This is a bit weird - it starts in the right place but breaks if you navigate away from map and then back.
