### ISSUE TITLE
Map should not allow dragging outside of bounds

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1112]
### Expected behaviour
When I drag a map to view above the arctic, it should repeat the map back into the antarctic prevent scrolling further 

### Actual behaviour
Map has a N and S boundary where it disappears 

### Steps to reproduce the behaviour/error
View map, click and drag far north or south

<img width="670" alt="screen shot 2016-06-07 at 10 39 49 am" src="https://cloud.githubusercontent.com/assets/1618793/15868352/609554dc-2c9c-11e6-9ad6-0357b2d4bebb.png">

**Comment by rjmackay** [comment]
This is the standard behaviour of Leaflet (and probably all OSM maps) .. we can't change this behaviour

**Comment by rjmackay** [comment]
Actually I lie... we might be able to set max bounds so that map can't scroll that far north/south
