### ISSUE TITLE
Survey creation is not formatted at all

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1114]
<img width="1278" alt="screen shot 2016-06-07 at 10 50 10 am" src="https://cloud.githubusercontent.com/assets/1618793/15868645/9c1cca52-2c9d-11e6-9dab-fc0a7f6df8f0.png">

**Comment by aoduor** [comment]
Hey @caharding, as per @rjmackay's QA doc, this is still in progress. PMing you with the spreadsheet :).

**Comment by caharding** [comment]
Got it hadn't seen this doc

On Tue, Jun 7, 2016 at 10:51 AM, Angela Oduor Lungati <
notifications@github.com> wrote:

> Hey @caharding <https://github.com/caharding>, as per @rjmackay
> <https://github.com/rjmackay>'s QA doc, this is still in progress. PMing
> you with the spreadsheet :).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1114#issuecomment-224360248>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizadP6D-NN6a_ol9sqE6yuusXwjSVWks5qJa-WgaJpZM4IwL4M>
> .
>



-- 
Charlie Harding
Product Director
