### ISSUE TITLE
Post description too long on map

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1115]
### Expected behaviour
Post description should be cut off if longer than X characters

### Actual behaviour
Displays full description text when you click a map icon

### Steps to reproduce the behaviour/error
Click on the Nairobi post about Berkeley on the QA test page

<img width="395" alt="screen shot 2016-06-07 at 10 37 25 am" src="https://cloud.githubusercontent.com/assets/1618793/15869001/28bbdac4-2c9f-11e6-9c9c-2ee2501aa532.png">

**Comment by jshorland** [comment]
Yeah this is icky and creates difficulty exploring posts. Labeling P0.

**Comment by zhalloran** [comment]
@rjmackay I left this alone. After starting work on this, I noticed that @jasonmule had already pushed a branch with a solution.
