### ISSUE TITLE
Add post not working

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1121]
### Expected behaviour
Can fill in fields and save a post

### Actual behaviour
can't save or input any other fields. only title appears.

### Steps to reproduce the behaviour/error
???

Related to #1109

**Comment by willdoran** [comment]
That's very strange it works properly in my local copy of develop, but it looks on qa as though it's missing an injection.

**Comment by willdoran** [comment]
This appears to be working on qa now, did something change? @rjmackay

**Comment by rjmackay** [comment]
@willdoran it was a change when I upgraded angular. You can't have special chars in a input `name` and the key contains `-`
