### ISSUE TITLE
Geo locator button doesn't appear on add post

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1123]
### Expected behaviour
On map, I should see a pin on the left hand side of the map that allows me to click and locate myself to add location to my post instead of typing in a location.

### Actual behaviour
The location button doesn't appear (there is a square, but nothing inside of it). When I click on the empty, I receive an error message that says "Geolocation error: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).."

### Steps to reproduce the behaviour/error
Login to qa.ushahidi.com with admin, admin
click on "add post" and then click "basic post"
Insert details required
On location, look for geo locate button on map. See image attached.
Then, click on empty square where geo-locate should be to receive error message.
![screen shot 2016-06-07 at 9 51 32 pm](https://cloud.githubusercontent.com/assets/3224856/15883220/048464b2-2cfb-11e6-8b0e-6edc8cde93dc.png)

**Comment by jshorland** [comment]
Related, I *think*

I also can't mark structure as complete even after manually selecting a location and filling in all required fields on post structure when adding a basic post. 

The mark as complete toggle button just doesn't work

**Comment by rjmackay** [comment]
Apparently we can't get location unless we're using HTTPS. 
I'll disable it on HTTP, not sure how to fix this icon though :/

**Comment by rjmackay** [comment]
@jshorland closing this - but can you retest completing structure and log a new issue if thats still broken?

**Comment by jshorland** [comment]
Logged at #1147
