### ISSUE TITLE
Mark as complete toggle broken in add post

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1124]
### Expected behaviour
After inputting all required information, I should be able to mark the structure step as complete and change visibility of post.

### Actual behaviour
Toggle button on "mark as complete" doesn't work

### Steps to reproduce the behaviour/error
Login to qa.ushahidi.com
Add basic post
Input all required fields
Try to toggle mark as complete

**Comment by jshorland** [comment]
![image](https://cloud.githubusercontent.com/assets/3224856/15905120/853e023a-2d68-11e6-972b-88a4e85220e8.png)

**Comment by willdoran** [comment]
closing in favour of #1147
