### ISSUE TITLE
Not able to publish post when logged in: "structure not yet marked as complete" error message.

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1126]
### Expected behaviour
Publish Post with title "Shadrock Test Post 2." Post marked as "Everyone can see this." All fields were filled out. 

### Actual behaviour
Was not able to "mark as complete" despite all forms being filled out. Was presented with an error stating that I missed a step in "structure" - see screenshot - and post was apparently, not published. I didn't see any tab, button, or field for the structure step. 
![publish post error screenshot](https://cloud.githubusercontent.com/assets/4574998/15904592/d3678426-2d6e-11e6-959b-8a940f4e5b59.png)

### Steps to reproduce the behaviour/error
Log in. Add basic post. Good luck.

**Comment by jshorland** [comment]
Closing in favor of #1124
