### ISSUE TITLE
UI for adding a post on mobile is confusing & not working

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1132]
### Expected behaviour
Immediately understand how to add a post while using Mustang on a smart phone
### Actual behaviour
Didn't see any "+" symbol in map view. Clicked around for a while before finally clicking the star icon. There I saw the coveted "+" symbol but clicking on it didn't do anything. 

Edit: before submitting this issue I clicked around a few more times and magically found the "There are not posts yet!" prompt with the yellow button saying "ADD THE FIRST POST." The whole interaction with the search field, the star dropdown, and the filter menu is super confusing. The ADD FIRST POST button appears as it's own screen (kind of off to the left) and just looks odd. 
![add post view from mobile](https://cloud.githubusercontent.com/assets/4574998/15906180/feaad93e-2d74-11e6-9809-c0e822e77004.jpg)

### Steps to reproduce the behaviour/error
Bring up qa.ushahidi.com in Safari and stare in blank incomprehension. 

### Device Details
iPhone 5s running iOS 9.3.2
Safari Browser

**Comment by jshorland** [comment]
Fixed. Passes QA. Looks beautiful on mobile
