### ISSUE TITLE
ADD THE FIRST POST UI is super confusing and button / "open" doesn't work for iPhone

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1134]
### Expected behaviour
Click ADD THE FIRST POST button to add post. 
### Actual behaviour
Clicked button but nothing happened. Pressed it for a few seconds in anger and was presented with a confusing menu (see screenshot) which asked me to "Open" things (I thought I was making a post not opening anything) or "Add to reading list" (what's a reading list?) or "Copy" (uber-odd since I didn't have anything to copy). I then clicked "open" and nothing happened again. This time nothing continued to happen despite repeated pressing, cajoling, begging, and threats. Depression set in. Heavy drinking commenced. 
![add open post weird ui on iphone](https://cloud.githubusercontent.com/assets/4574998/15906415/f87f5aa2-2d75-11e6-9b33-dba39c900253.jpg)

### Steps to reproduce the behaviour/error
Go to qa.ushahidi.com on your phone. Aimlessly press the screen until you luck upon the ADD THE FIRST POST button. Click it repeatedly. If you luck upon the associated menu press "open." Hang head in dejection. Cry. 
### Device Details
iPhone 5s running iOS 9.3.2
Safari Browser

**Comment by rjmackay** [comment]
... I think I forgot to wire this at all..

**Comment by rjmackay** [comment]
@willdoran is this fixed along with the collection with no posts issue?
