### ISSUE TITLE
Signing up has warning messages for login

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/platform#1135]
### Expected behaviour
When I create an account, I should see a message about confirming my email address.

### Actual behaviour
I'm told I don't have the correct email address.
<img width="652" alt="screen shot 2016-06-08 at 2 39 53 pm" src="https://cloud.githubusercontent.com/assets/106068/15906574/795ff3d2-2d87-11e6-9c68-567f477717d0.png">

### Steps to reproduce the behaviour/error
Click "Sign Up" and fill in the form, then submit.

**Comment by jshorland** [comment]
I can sign in, but never received an email (5 minutes have passed since signing up for deployment)

**Comment by rjmackay** [comment]
Sorry to be clear: there is no confirmation email (ever). But you shouldn't see any errors after registering.

**Comment by rjmackay** [comment]
and you should be able to login
