### ISSUE TITLE
"More" link on mobile version doesn't do anything. White on gray background is very hard to see.

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1136]
### Expected behaviour
Well... "more" actually. Not sure what, but certainly more than nothing.

### Actual behaviour
The "more" button and associated ellipsis icon turned white, which is not really helpful since it only makes it WAY more hard to see. Suggest making the active link yellow.
![more button confusing background on mobile](https://cloud.githubusercontent.com/assets/4574998/15906803/b2cd735c-2d77-11e6-82a1-46a26834b9dc.jpg)

### Steps to reproduce the behaviour/error
Go to qa.ushahidi.com on a mobile and stare at the difficult to read menu. Then press "more." Meditate on your life decisions. 

### Device Details
iPhone 5s running iOS 9.3.2
Safari Browser

**Comment by rjmackay** [comment]
Fixed this
