### ISSUE TITLE
Map's post popups should include complete summary

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1137]
### Expected behaviour
When clicking a map marker, I expect the post popup ("postcard") to include the same content as its representation in the "Timeline," complete with author, date, visibility, and actions trigger:

![screenshot from PL](https://cloud.githubusercontent.com/assets/1136279/15911272/b665c0e2-2d94-11e6-89b3-9e268f5870ba.png)

### Actual behaviour
When clicking a map marker, the post popup ("postcard") only includes the post's title and description:

![screenshot from client](https://cloud.githubusercontent.com/assets/1136279/15911301/e158ec5c-2d94-11e6-8101-f4281dbb6346.png)

### Steps to reproduce the behaviour/error
Click a map marker

**Comment by rjmackay** [comment]
Done and deployed. Please test

**Comment by jshorland** [comment]
Beautiful! Passes test. 

![screen shot 2016-06-30 at 3 36 12 pm](https://cloud.githubusercontent.com/assets/3224856/16506630/94339c74-3ed8-11e6-89f2-86bc48c245c7.png)
