### ISSUE TITLE
Update post import

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1139]
Update settings: Import screen

**Comment by rjmackay** [comment]
@jasonmule if you start on this - push whatever you have at the end of day. Then it can hand off to @willdoran or me while you sleep :)

**Comment by jasonmule** [comment]
@rjmackay @willdoran Had a discussion with @jshorland and she was of the opinion that we shouldn't release with the last step until we have a better UX spec. It means that the 2nd step would be become the final step for now and that we just need to wire that to send out the mapping to the API.

**Comment by rjmackay** [comment]
@jasonmule I'm happy with that. Can you make that change but keep the next step code in there still? (ie. so the switch back is quick)
