### ISSUE TITLE
Error creating a post (free web version of Ushahidi)

### ISSUE THREAD

**Issue by ACFsitrep** [ushahidi/platform#1141]
Sometimes, when I try to create a post, It's shown an error message with no information.

All the fields are correct. I use to open a new sesion in a diferent tab, I create a new post and I copy/paste all the information, and then I can save the post.
 I Can't understand this behaviour...

### Expected behaviour
To save a post

### Actual behaviour
An errror occurs. It is shown an error message without any information

### Steps to reproduce the behaviour/error
It's not always. I am creating post, and after a while I got the error.

The link to my deployment:  https://sitrep.ushahidi.io

**Comment by aoduor** [comment]
Hi, what's the link to your deployment?

**Comment by ACFsitrep** [comment]
Hi Angela!

Here’s the link…


https://sitrep.ushahidi.io

Thank you!

De: Angela Oduor Lungati [mailto:notifications@github.com]
Enviado el: Thursday, June 09, 2016 12:27 PM
Para: ushahidi/platform
CC: Emergency Pool 1; Author
Asunto: Re: [ushahidi/platform] Error creating a post (free web version of Ushahidi) (#1141)


Hi, what's the link to your deployment?

**Comment by rjmackay** [comment]
We've got a fairly major update coming out next week. Its quite possible that will fix your issue. Can I get you to retest this in a week and let us know if its still a problem?

**Comment by ACFsitrep** [comment]
Hi there, 

Yes, after the major update, I've never had the problem again.

Thank you very much.

I'll proceed to close the issue
