### ISSUE TITLE
No confirmation dialogue provided to user when deleting a custom field

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1143]
### Expected behaviour
When i click on delete field, i expect a confirmation box prompting me to either proceed or dismiss deletion process to show up on my screen

### Actual behaviour
I click on delete, and the field just disappears, with no feedback provided to me as a user

### Steps to reproduce the behaviour/error
* Log into qa.ushahidi.com
* Click on Settings, then Surveys
* Select a task, and click on an existing field
* Scroll to the bottom of the pop up box that appears and click on DELETE FIELD

**Comment by aoduor** [comment]
Looks like the same thing is happening for task deletion too cc @rjmackay @jshorland

**Comment by jasonmule** [comment]
CNR

**Comment by jshorland** [comment]
Could not replicate either. I get full feedback asking me to confirm deletion. Probably fixed in the pre release scramble.

Closing.
