### ISSUE TITLE
Can't save edited post

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1146]
### Expected behaviour
After creating a post for the first time, I should be able to revisit that post and edit it's details when logged in as admin, save the edits, and then be able to see those edits on the saved post. 

### Actual behaviour
When I revisit an already created post and edit it, after changing visibility settings and location, I can't click save. Save button doesn't work?

### Steps to reproduce the behaviour/error
1. login to qa.ushahidi.com
2. navigate to post detail view on any post
3. navigate to "edit post" mode
3. update visibility settings, and 1 custom field
4. attempt to click save

**Comment by jshorland** [comment]
Cancel works though

**Comment by rjmackay** [comment]
@jshorland Can you retest this?

**Comment by jshorland** [comment]
Confirmed fixed. Passes QA.
