### ISSUE TITLE
Mark as complete toggle doesn't work on any step

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1147]
### Expected behaviour
As a logged in admin, I can mark all steps complete after completing all required fields while editing post

### Actual behaviour
It works for the first default "structure" step, but when I added a second step, it doesn't work for that second step. I can't mark it complete and save it no matter what I do

### Steps to reproduce the behaviour/error
1. Login as admin to qa.ushahidi.com
2. add post to "jess's special posts" survey
3. fill in all required fields for structure, mark as complete
4. move to approval step and select "yes" from dropdown field
5. try to toggle "mark as complete"
6. try to save from that step's screen
7. if you go back to structure step, you can save from there.

**Comment by Shadrock** [comment]
I'm having the same problem with http://comrades.ushahidi.com. Just to clarify, this is the toggle for the "Approval" step. Unlike @jshorland, I *cannot* go back to the structure step and save from there. Instead, I get an error message at the top of the screen telling me that "The required step Approval has not yet been marked complete."

**Comment by jshorland** [comment]
@Shadrock Toggle button is broken, but not being able to save from step 1, that's because yours is required to publish and mine isn't. That's actually the system working properly for required steps :-) 
 
Update: I was able to toggle it on step 1, but can no longer do that. Mark as complete doesn't work at all.

**Comment by willdoran** [comment]
@jshorland @Shadrock Hi, I've fixed this now with [235](https://github.com/ushahidi/platform-client/pull/235)

**Comment by willdoran** [comment]
Will push to qa shortly

**Comment by jshorland** [comment]
Confirmed fixed. Passed QA
