### ISSUE TITLE
Date picker appears, but default date is in 1969

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1148]
### Expected behaviour
When I add a date field to a survey, it should appear when adding a post to that survey

### Actual behaviour
See screen shot

### Steps to reproduce the behaviour/error
1. go to qa.ushahidi.com
2. add post to "jess's special posts"
3. See date field

![screen shot 2016-06-09 at 2 09 26 pm](https://cloud.githubusercontent.com/assets/3224856/15946782/3544df5c-2e4d-11e6-8a9a-0c8404265837.png)

**Comment by willdoran** [comment]
@jshorland: this should be fixed by [236](https://github.com/ushahidi/platform-client/pull/236)

**Comment by jshorland** [comment]
Fixed.

Notes from QA: 

If no default is set when creating the field in a survey (which is confusing itself as it's not a date picker, you just have to enter a date free hand), it defaults to january 1969. Should default to the contributor's present date (whoever is adding the post)

**Comment by jshorland** [comment]
passing back to you @rjmackay
