### ISSUE TITLE
Images don't appear in map preview or post detail

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1149]
### Expected behaviour
After adding a post with an image, the image should appear in map preview of post, post detail, and on list view

### Actual behaviour
Image only appears in list view

### Steps to reproduce the behaviour/error
1. go to http://qa.ushahidi.com/posts/153 (image is not there)
2. navigate back to map view and click on the seattle washington pin (image is not there)
3. Then, navigate to list view and see the first post in the list (image is there)

Related: #1137

**Comment by jasonmule** [comment]
Could not reproduce this for post detail. I think we might need to change the layout for map view @rjmackay ?

**Comment by jasonmule** [comment]
This is probably going to get cumbersome loading stuff again and again from various endpoints to compose fields for map popups. Should we re-work the single API endpoint that this pulls data from?
