### ISSUE TITLE
Image size errors when uploading a photo are unclear

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1151]
### Expected behaviour
If photo couldn't upload, understanding why.

### Actual behaviour
Just a blank error was presented to me

### Steps to reproduce the behaviour/error
1. login to qa.ushahidi.com
2. add to "jess's special posts"
3. Try to upload attached image into the image field  (laugh all you want)

Note: i DID successfully upload another image. It's attached to http://qa.ushahidi.com/posts/153

![dsc_0081](https://cloud.githubusercontent.com/assets/3224856/15947122/cc6bb1ca-2e4e-11e6-80b2-82ebae882d6f.JPG)

![screen shot 2016-06-09 at 2 09 03 pm](https://cloud.githubusercontent.com/assets/3224856/15947140/e470e880-2e4e-11e6-861f-6b25cf8ef2a9.png)

**Comment by willdoran** [comment]
This picture perfectly captures the pain of not uploading this picture! Testing now

**Comment by willdoran** [comment]
Ok this is fixed by [238](https://github.com/ushahidi/platform-client/pull/238)

**Comment by jshorland** [comment]
Systems returns error now, but I don't understand the size taxonomy.

When we have time, we should:

1. add help text to the image field that let's users know up front the sizing limitations and
2. Change the help text to be more layman friendly

![screen shot 2016-06-12 at 6 48 57 pm](https://cloud.githubusercontent.com/assets/3224856/15995333/7be5d1f4-30ce-11e6-88bd-1588a200b13b.png)

**Comment by jshorland** [comment]
passing back to you @rjmackay

**Comment by willdoran** [comment]
We should have a translation mapping for the error message, I'll look at this shortly

**Comment by yuchenglin** [comment]
When I upload photos taken by iphone, the same size error would appear. In addition to the friendly help text, wouldn't it limit mobile users? or is it for system consideration? Thanks

**Comment by willdoran** [comment]
@rjmackay @jshorland is there a physical limitation on cloud for the current image size?

**Comment by rjmackay** [comment]
@jshorland is this still high priority or can we bump it off the sprint?

**Comment by jshorland** [comment]
Still high priority. Many complaints and questions about this.
