### ISSUE TITLE
Categories section header appears on forms when there are no categories.

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1155]
**This is for the COMRADES deployment**: http://comrades.ushahidi.com/views/map

### Expected behaviour
Ability to add date to post which features a date field. 

### Actual behaviour
"Date of Activity" text appears but is not followed by a form field. Moreover, the "Categories" text also appears. I did not set categories on the original deployment (https://comrades.ushahidi.io/views/map)
![comrades mustang categories date](https://cloud.githubusercontent.com/assets/4574998/15952662/2247b658-2e80-11e6-8ab6-abd4c19bb9e1.png)

### Steps to reproduce the behaviour/error
Go to http://comrades.ushahidi.com/views/map and click to add a post. It does not matter whether you are logged in as an admin or not logged in at all.

**Comment by jasonmule** [comment]
Possibly needs a modules update?

**Comment by rjmackay** [comment]
@Shadrock can you confirm this is still an issue? I think it should have been fixed by redirecting comrades.ushahidi.io

**Comment by Shadrock** [comment]
@rjmackay I just checked this on comrades.ushahidi.io. I made reports with and without being logged in. In both cases the "Categories" title still appears about a blank space: it has not been fixed. The "Date of Activity" *is* now working correctly.

**Comment by jshorland** [comment]
Fails test on jshorland88.ushahidi.io as well. Moving back to in progress

**Comment by willdoran** [comment]
This should be fixed by [282](https://github.com/ushahidi/platform-client/pull/282)
