### ISSUE TITLE
Unable to delete a user from User Edit Page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1156]
### Expected behaviour
I should be able to click on delete, get a confirmation message and eventually successfully delete a user from the edit page.

### Actual behaviour
Clicking on the delete user button yields no response

### Steps to reproduce the behaviour/error
* Log into qa.ushahidi.com
* Click on settings, then users
* Select a user you'd like to delete
* Once edit page loads, click on delete user

**Comment by willdoran** [comment]
@aoduor this should be fixed by [233](https://github.com/ushahidi/platform-client/pull/233)

**Comment by aoduor** [comment]
No dice on qa.ushahidi.com yet though.
