### ISSUE TITLE
Adding a post from the menus on the left doesn't work

### ISSUE THREAD

**Issue by dexwakhu** [ushahidi/platform#1159]
### Expected behaviour
When you click "add to basic post" or "add to sample post type" etc should pull up a form to add the post
### Actual behaviour
Nothing happens
### Steps to reproduce the behaviour/error
on left hand menu, click drop down arrow on "basic post" and click  "add to basic post"

**Comment by aoduor** [comment]
Hey @dexwakhu, the yellow (+) icon is what you're meant to use to add a post :D.

**Comment by aoduor** [comment]
Tested this as well, +1, unable to add a post from that menu bar.

**Comment by willdoran** [comment]
@rjmackay This doesn't appear to be wired up, is it waiting to be merged?

**Comment by rjmackay** [comment]
Nope. Thats and oversight on my part. Should be quick to wire up though..
