### ISSUE TITLE
Clicking "add the first post" in a collection doesn't work

### ISSUE THREAD

**Issue by dexwakhu** [ushahidi/platform#1160]
<img width="646" alt="screen shot 2016-06-10 at 15 49 34" src="https://cloud.githubusercontent.com/assets/13867411/15964792/024245c8-2f23-11e6-950d-a981f4820d76.png">
### Expected behaviour
Clicking 'Add the first post' should allow you to add a post
### Actual behaviour
nothing happens
### Steps to reproduce the behaviour/error
go to collections > choose a collection > click timeline > try to add the first post

**Comment by willdoran** [comment]
@rjmackay @brandonrosage this needs a ui element to allow the user to select a survey similar to the fab button.

**Comment by willdoran** [comment]
Ok, @brandonrosage has created some new markup and I'm implementing it now.

**Comment by brandonrosage** [comment]
I revised the existing "Map: Collection" layout to [include a message](https://github.com/ushahidi/platform-pattern-library/blob/mustang/pattern-library/5_layouts/map-collection.html#L202-L222) explaining that the Collection has no posts, and how to add them.:

![screenshot from PL](https://cloud.githubusercontent.com/assets/1136279/15977146/a4246a4e-2f1c-11e6-8692-008520f24818.png)

[The message is 'sustaining,'](https://github.com/ushahidi/platform-pattern-library/blob/mustang/pattern-library/5_layouts/map-collection.html#L229) meaning it doesn't disappear automatically, but has a manual "Dismiss" button.
