### ISSUE TITLE
No indication of required fields

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1161]
### Expected behaviour
When there are required fields in a specific task, i expect to see an aterisk, or something to flag that they are required

### Actual behaviour
None of the required fields have any mark/indication on them

### Steps to reproduce the behaviour/error
* Log into qa.ushahidi.com
* Click on Settings, then Surveys
* Select a survey, and a subsequent task in the survey
* Add a new field and mark it as required.

**Comment by jshorland** [comment]
Couldn't replicate -- I see a red asterisk next to required fields in mine

**Comment by aoduor** [comment]
Wierd. I was editing fields on the "Basic" post type and set the "Location" field as required - no dice. No asterisk on post creation.
