### ISSUE TITLE
Unable to save basic post with location

### ISSUE THREAD

**Issue by dexwakhu** [ushahidi/platform#1162]
<img width="1158" alt="screen shot 2016-06-10 at 15 57 30" src="https://cloud.githubusercontent.com/assets/13867411/15965159/dc628e60-2f24-11e6-8ed7-31870e05870c.png">
### Expected behaviour
Clicking save would save the post or bring up error message
### Actual behaviour
Nothing happens
### Steps to reproduce the behaviour/error
Add new post > Select basic post with location > enter title, description, location etc, click save

**Comment by willdoran** [comment]
This appears to be entering an error state but isn't reporting it.

**Comment by willdoran** [comment]
Ok this is legitimate behaviour BUT you should be seeing an error message. The notify service isn't working correctly. I'll fix that now.

**Comment by willdoran** [comment]
@rjmackay I think this is caused by
https://github.com/ushahidi/platform-client/blob/develop/app/common/notifications/notify.service.js#L34
it's missing $promise but it won't work anyway because there are no translation keys for auto generated errors :/ I'll look at adding them to en.json

**Comment by willdoran** [comment]
This should be fixed by [237](https://github.com/ushahidi/platform-client/pull/237)

**Comment by jshorland** [comment]
Fixed and passed QA.
