### ISSUE TITLE
Mark as complete placement

### ISSUE THREAD

**Issue by dexwakhu** [ushahidi/platform#1163]
### Expected behaviour
The mark as complete button is disabled on posts until you enter a description but the description 
### Actual behaviour
The order of the fields/buttons makes it appear like the mark as complete button has an issue whereas this may not necessarily be the case 
<img width="1152" alt="screen shot 2016-06-10 at 16 10 56" src="https://cloud.githubusercontent.com/assets/13867411/15965415/59359288-2f26-11e6-9240-9542aa3c0a83.png">

### Steps to reproduce the behaviour/error
add post > enter title > try toggle "mark us complete" button

**Comment by rjmackay** [comment]
Closing in favour of #1226
