### ISSUE TITLE
"visible to" icon help text hidden in post detail view

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1164]
### Steps to reproduce the behaviour/error
1. login to qa.ushahidi.com
2. navigate to http://qa.ushahidi.com/posts/157
3. hover mouse over visibility to icon

see screen shot
![screen shot 2016-06-10 at 7 03 29 am](https://cloud.githubusercontent.com/assets/3224856/15966839/b0da1646-2ed9-11e6-8fee-e2aea7f4b18e.png)

**Comment by caharding** [comment]
View doesn't exist anymore
