### ISSUE TITLE
Selector buttons have a top shadow

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1167]
### Expected behaviour
Selector buttons shouldn't have a shadow

### Actual behaviour
All the selector buttons are styled with a top shadow

### Steps to reproduce the behaviour/error
Look under any filters section

<img width="231" alt="screen shot 2016-06-10 at 11 07 25 am" src="https://cloud.githubusercontent.com/assets/1618793/15974107/a47d8afa-2efb-11e6-80cf-3ed5ef0bb587.png">

**Comment by rjmackay** [comment]
@brandonrosage I think this is just a minor CSS fix. Probably just fix it on the client branch of the PL
