### ISSUE TITLE
Activity needs to show useful information upon load

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1168]
### Expected behaviour
I want to see graphs that automatically make sense when I load the page - likely Surveys or Posts. The timeframe filter should default to a period in which there are posts

### Actual behaviour
When you visit activity, there are no graphs and it is not clear how to make it work

### Steps to reproduce the behaviour/error
Visit activity and see that nothing shows

<img width="969" alt="screen shot 2016-06-10 at 11 10 35 am" src="https://cloud.githubusercontent.com/assets/1618793/15974181/025b6c1e-2efc-11e6-99f3-2342e69d8d24.png">

**Comment by aoduor** [comment]
I think this is because we don't have much data on the QA deployment for it to pick anything @caharding

**Comment by rjmackay** [comment]
This is a problem.. but its really out of scope for this sprint. Assigning to @jshorland for future triage

**Comment by rjmackay** [comment]
I've defaulted to showing "All time" for now.

**Comment by jshorland** [comment]
Yep, little data is precisely the problem. Defaulting to all time gives more context for now.
