### ISSUE TITLE
Activity "Compare" feature confusing

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1170]
### Expected behaviour
The current selector on the activity graphs says "Compare..." I expect this to simply be a selector of posts/surveys/categories/status. This should default to All Posts. When I make the selection I expect that the text would change to what I selected. Furthermore compare is just confusing. 

### Actual behaviour
No matter what I select, this drop down always says "Compare" it does not tell the user what they are looking at

### Steps to reproduce the behaviour/error
View activity page

<img width="259" alt="screen shot 2016-06-10 at 11 13 05 am" src="https://cloud.githubusercontent.com/assets/1618793/15974347/d73eb62a-2efc-11e6-988a-37df09bf7a7f.png">

**Comment by rjmackay** [comment]
.. could have sworn that worked before. I'll investigate.
