### ISSUE TITLE
Add button to create a saved search from saved search list

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1171]
### Expected behaviour

Clicking on "Create New" should yield something
### Actual behaviour

The button is non responsive
![screenshot](http://i.imgur.com/KGOJSiT.png)
### Steps to reproduce the behaviour/error
- Click on the star on the search bar
- Click on Create New

**Comment by aoduor** [comment]
flagging @willdoran @rjmackay @jasonmule

**Comment by rjmackay** [comment]
I'm going to remove that for this release. Its non-trivial to wire up. Sorry!

**Comment by caharding** [comment]
Is this button broken? If so we should just fix it.
