### ISSUE TITLE
Add links to support docs + how to report a bug

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1172]
We previously had this on the v3.2

![screenshot](http://i.imgur.com/rIejMF5.png)

But I don't see it anywhere on mustang, and it's pretty important.

cc @jshorland @rjmackay

**Comment by rjmackay** [comment]
Yikes. @brandonrosage where could we link these from?

**Comment by aoduor** [comment]
Just to clarify: Documentation should point to ushahidi.com/support and how to report a bug should EITHER link to github issues(https://github.com/ushahidi/platform/issues/new) OR to intercom

**Comment by brandonrosage** [comment]
I just pushed a revision to the PL that re-purposes the "Ushahidi" menu item in the mode bar as "Ushahidi Support." Upon selecting it, it displays a dialog/modal with links to "Documentation," "Report a bug," and "Features."

DEMO: http://d.pr/i/1eq5N/1u95RoQo

/cc @willdoran

**Comment by aoduor** [comment]
LMK once we push this live and i can test :)?

**Comment by jshorland** [comment]
passed qa. 

@brandonrosage any design issues?

**Comment by jshorland** [comment]
Closing. feel free to reopen if design issues exist.
