### ISSUE TITLE
Add "How to add a post" section

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1173]
### Expected behaviour

This seems to be wired up on the PL as shown below.
![screenshot](http://i.imgur.com/B10XsEI.png)
### Actual behaviour

We don't have that available on the left menu bar on qa.ushahidi.com
### Steps to reproduce the behaviour/error

Navigate to the homepage on qa.ushahidi.com

Question: Ideally, in which sections of the settings would this get wired up?

**Comment by aoduor** [comment]
Flagging @brandonrosage @rjmackay @willdoran

**Comment by rjmackay** [comment]
This wasn't in scope for this release. Its clearly important though and will be in the next release.
