### ISSUE TITLE
Add colors to Surveys

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1174]
Here's how Surveys appear on the PL

![screenshot](http://i.imgur.com/PrPLDWV.png)

And how they appear on qa.ushahidi.com
![screenshot](http://i.imgur.com/9MYJ6AO.png)

Is this as expected? @brandonrosage @rjmackay @jshorland

**Comment by willdoran** [comment]
Not yet, surveys don't yet have a colour field but they will in the next release.

**Comment by jshorland** [comment]
Failed acceptance test. Upon creating new surveys, I can't find a color picker and each new survey doesn't automatically assign a unique color automatically. 

Steps to reproduce:
1. login to jshorland88.ushahidi.io (jess@ushahidi.com, password)
2. navigate to Settings --> Surveys
3. Add new Survey --> no color picker
4. Save survey and navigate back to Survey list. See all surveys are associated with the same color red.

**Comment by willdoran** [comment]
That's strange it appears not to have been deployed yet. Color picker has changed in PL to be a gradient picker. I'm going to update the client accordingly but the picker works for me in develop.

**Comment by jshorland** [comment]
Ah -- moving back to testing -- @rjmackay will land and I will retest.

**Comment by rjmackay** [comment]
@willdoran I think we just need to flag **where** to test things.
- If you've just push to develop it'll only appear on ushahididev.com
- If you've tagged and deployed to production. Let Jess know to test on ushahidi.io

**Comment by jshorland** [comment]
@willdoran @rjmackay where should I be testing this?

**Comment by rjmackay** [comment]
Testing: failed.
Map markers are showing up black on ushahididev.com https://www.dropbox.com/s/go28pt6nxg9817j/Screenshot%202016-07-04%2015.25.16.png?dl=0
As you can see the popup is correct though and uses the gold highlight.
