### ISSUE TITLE
Issues running migrations with mysql strict mode

### ISSUE THREAD

**Issue by fegul** [ushahidi/platform#1177]
When attempting to install the platform on Ubuntu Server 16.04, the bin/update command returns:

`[InvalidArgumentException] There was a problem creating the schema table: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'end_time'`

**Comment by rjmackay** [comment]
Thanks for the bug report @fegul. What version of mysql are you running? What version of the code are you running?

**Comment by fegul** [comment]
Hello @rjmackay, not sure how I missed your message. I'm running MySQL 5.7.13 and I'm running `bin/update` in the cloned repo directory which leaves that error message. Just tried it again today.

**Comment by fegul** [comment]
I think this issue might be related to [https://github.com/ushahidi/platform/issues/969](url)

**Comment by fegul** [comment]
Turns out, it was related to that issue.

Used the following guide to retrieve all the SQL modes set, copied the list of modes, opened up mysql config and manually set SQL mode by pasting in the list of modes I had copied before and removed the NO_ZERO_DATE option. Restarted MySQL and migrations worked fine after that.

**Comment by rjmackay** [comment]
It looks like this was caused by phinx itself - we should update to the latest version of phinx

**Comment by rjmackay** [comment]
I believe this was completed in the last release
