### ISSUE TITLE
Export button displays on User Settings page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1183]
### Expected behaviour
This button should only appear on:-
* Map Mode
* Timeline Mode
* Saved Searches
* Collections
* Search Results page

### Actual behaviour
It's showing up on all pages above AND user settings page
![screenshot](http://i.imgur.com/gUs3jOa.png)

### Steps to reproduce the behaviour/error
* Log into qa.ushahidi.com
* Click on settings
* Click on users

**Comment by jshorland** [comment]
Gone! passes QA
