### ISSUE TITLE
No posts showing on map after submitting a post

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1186]
### Expected behaviour
Submit a post and go back to the map

### Actual behaviour
When it goes back to the map, no posts are showing and the default map changed to MapBox away from Humanitarian

### Steps to reproduce the behaviour/error
Submit a post on basic survey
The home page no longer has posts showing on the map

Safari, OSX

**Comment by jshorland** [comment]
I've just started experiencing this issue as well. Not happening last night, but happening this morning.
