### ISSUE TITLE
Mark As Complete doesn't make sense for non-logged in user

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1187]
### Expected behaviour
When I see Mark As Complete, I can't flip the switch b/c it requires me to fill out more fields. But it the required fields are also not visually indicated, so there is no way to know when to flip the switch.

### Actual behaviour
Won't let me flip the switch. If I fill in description, I can then

### Steps to reproduce the behaviour/error
Create basic post
Fill in title
Don't fill in description
Try to flip "complete"
Fill in description
Flip "complete"
Delete description
Required field now pops up - very confusing, why wasn't there an indicator before? 

<img width="714" alt="screen shot 2016-06-13 at 12 05 05 pm" src="https://cloud.githubusercontent.com/assets/1618793/16014426/10a693ec-315f-11e6-935a-5b8a9e8fb21a.png">

**Comment by aoduor** [comment]
Related to #1161. I think this issue may be isolated to the Basic Post survey type, as other have an indication of what fields are required. cc @rjmackay @jshorland

**Comment by rjmackay** [comment]
Not 100% what the fix is here. But I think this is confusing enough to warrant a fix.

**Comment by rjmackay** [comment]
Suggested change:
- Remove 'Mark as complete' entirely. For both admin and non-admin users.
- Remove 'required' stages - no stages required before publishing.

**Comment by caharding** [comment]
Reference this issue #1259 which shows that there is no way to do post verification with the current structure of our deployments

**Comment by willdoran** [comment]
Until we can search/filter on completion is stage completion currently useful other than as meta data?

**Comment by rjmackay** [comment]
I think this is probably covered by #1262

**Comment by rjmackay** [comment]
Closing in favour #1262
