### ISSUE TITLE
Survey settings from survey dropdown doesn't work on Safari

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1189]
### Expected behavior
The survey settings from the survey drop down should link to the associated settings page

### Actual behavior
Just loads a blank screen

### Steps to reproduce the behaviour/error
On homepage click dropdown on "Basic post survey" 
Select Survey Settings
Blank page is created

Logged in on Safari desktop

**Comment by caharding** [comment]
This is also not working on Chrome for me

**Comment by caharding** [comment]
I think we should escalate this to P0 as it fundamentally doesn't work, which is not good for users. Just screwed up a whole solutions client demo I did.

**Comment by rjmackay** [comment]
Agreed. 2 things to fix here:
1. link goes to settings/forms/ID instead of settings/surveys/ID
2. Settings link is visible when not logged in/admin
