### ISSUE TITLE
Search has no button and enter doesn't work on Safari

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1190]
### Expected behavior
When I enter a search, it automatically begins the search based on what I type. Or if I press enter it will then make that search

### Actual behavior
When I enter a search, I then have to go to "Filters" and hit apply

### Steps to reproduce the behaviour/error
Enter a search, press enter... nothing happens

Logged in / Safari / OSX desktop

**Comment by jshorland** [comment]
Can't replicate. The keyword appears as a filter on the left side information bar.

**Comment by caharding** [comment]
Try it on Safari, doesn't work

**Comment by jshorland** [comment]
Replicated on Safari browser.

**Comment by rjmackay** [comment]
As discussed on call: this is also an issue on mobile.
Suggested solutions:
- Show 'suggestions' dropdown when search box is focused. Use that to show a submit button
- Show 'filters' dropdown when search box is focused

**Comment by jshorland** [comment]
Fixed. Closing.
