### ISSUE TITLE
Dropdown dialogue box doesn't go away after hitting OK

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1194]
### Expected behavior
After I delete a saved search, a confirmation dialogue drop down happened. I hit OK and I thought the dialogue would go away

### Actual behavior
I hit OK, and it took me back to the homepage, but the dropdown stays### Steps to reproduce the behaviour/error preventing me from doing another search or filter unless I reload the browser

### Reproduce
Select a saved search
Delete it
Confirm the dialogue drop down

Logged in Safari / OSX Desktop

<img width="1278" alt="screen shot 2016-06-13 at 12 21 43 pm" src="https://cloud.githubusercontent.com/assets/1618793/16014994/b3249a18-3161-11e6-9215-a27bfc0761cd.png">

**Comment by rjmackay** [comment]
I think this was fixed along with post export sliders.

**Comment by jshorland** [comment]
Fixed. Passes QA.

@caharding assigning to you to retest and confirm.
