### ISSUE TITLE
The count box doesn't make sense on Map mode for posts without locations

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1195]
### Expected behavior

I am trying to filter a survey that has posts on the post count, but no pins show on the map. 
### Actual behavior

I need to see some sort of dialogue box telling me why. I only figured out that the survey type didn't have a location associated with it.
### Steps to reproduce the behaviour/error

Filter a survey in map mode with no location type but with a count of posts, see that no pins change

**Comment by brandonrosage** [comment]
Tell me if I'm missing something, but this seems like a purely technical implementation detail: Making sure that number is derived from the number of corresponding posts that appear on the map.

**Comment by caharding** [comment]
This is a complicated issue. Maybe it is just number of posts in the view
that you're looking at. List would have more than map. But this would also
cause confusion. Would prob make sense to visually show that their are
posts that have no location, and you can go see them in list view...

On Wed, Jul 6, 2016 at 10:12 AM, Brandon Rosage <notifications@github.com>
wrote:

> Tell me if I'm missing something, but this seems like a purely technical
> implementation detail: Making sure that number is derived from the number
> of corresponding posts that appear on the map.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1195#issuecomment-230840372>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizaT_9Ue6nTBC4g4rWvI9oAt8M4WwCks5qS-HpgaJpZM4I0gfy>
> .
>



-- 
Charlie Harding
Product Director
