### ISSUE TITLE
Count on "Unknown" posts is broken

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1196]
There is no post count on "Unknown"

**Comment by aoduor** [comment]
Just a quick clarification on this one - i assumed that "unknown" probably refers to posts that haven't been assigned to any survey types(likely for messages coming in from SMS, Email and Twitter) - and we don't have these at the moment?

**Comment by caharding** [comment]
When I filter timeline for these posts, I see that there are some in the
tool on qa.usahidi.com but I don't see a count of them

On Mon, Jun 13, 2016 at 10:48 AM, Angela Oduor Lungati <
notifications@github.com> wrote:

> Just a quick clarification on this one - i assumed that "unknown" probably
> refers to posts that haven't been assigned to any survey types(likely for
> messages coming in from SMS, Email and Twitter) - and we don't have these
> at the moment?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1196#issuecomment-225656279>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizaZuKx0rV0owRe7M9-7pVmhNbaRfkks5qLZfRgaJpZM4I0gw3>
> .
>



-- 
Charlie Harding
Product Director
