### ISSUE TITLE
Need to have "Clear Search" at the bottom of saved search to take you back home

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1197]
### Expected behavior

I expected a "Clear Search" button at the bottom of saved search to take me home, I then pressed the Map mode again and though it would clear the search. 
### Actual behavior

I couldn't figure out how to clear a saved search
### Steps to reproduce the behaviour/error

Select a saved search and try to get out of it!

**Comment by rjmackay** [comment]
- Collections have a "Return to all posts" button.
- Saved searches should have the same thing.
