### ISSUE TITLE
Reset saved search doesn't make sense

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1198]
### Expected behavior

I thought "Reset Search" would clear the search, instead it went back to the saved search
### Steps to reproduce the behaviour/error

Add a clear search underneath

**Comment by rjmackay** [comment]
Would it make more sense to have something like 'undo changes'?? 
Collections also have a "Return to all posts" button which I think should be duplicated on saved searches.

**Comment by caharding** [comment]
I'm actually not sure what Reset Saved Search would do. I'm guessing it
reverts back to the original settings for the saved search? That would make
sense. I also want a way to clear out of the saved search. The link back to
home up top is kinda weird and unexpected.

I also wonder if pressing the map again should reset the view
