### ISSUE TITLE
Distance filter needs an option to enter a field of any distance

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1201]

**Comment by rjmackay** [comment]
@caharding can you add a description? Is this the post filters?

**Comment by caharding** [comment]
Sorry about that.

The location filter on posts only allows for preset distances. Should be
able to enter a custom distance.

On Sun, Jun 19, 2016 at 5:37 PM, Robbie Mackay <notifications@github.com>
wrote:

> @caharding <https://github.com/caharding> can you add a description? Is
> this the post filters?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1201#issuecomment-227030156>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizaWcdAoVcjZ0JeMApu_HDy8T6aQZsks5qNeCzgaJpZM4I0hVr>
> .
>



-- 
Charlie Harding
Product Director
