### ISSUE TITLE
Collections: Add The First Post broken

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1205]
### Expected behavior
I expect to click this button and it asks me to choose a survey

### Actual behavior
Button does nothing

### Steps to reproduce the behaviour/error
Create a new collection or go to a collection with no posts, press button

Logged in / Safari / Max OSx

<img width="821" alt="screen shot 2016-06-13 at 12 58 47 pm" src="https://cloud.githubusercontent.com/assets/1618793/16016056/d2a3724c-3166-11e6-8fa7-6cab81594d53.png">

**Comment by jshorland** [comment]
Duplicate -- being handled by #1160
