### ISSUE TITLE
User creation error with no dialogue

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1206]
### Expected behavior
Create a user and don't assign a role, doesn't 

### Actual behavior
This box should tell me what is wrong

### Steps to reproduce the behaviour/error
Create a new user, don't assign a role, try to save, a dialogue box will drop down without any context

<img width="956" alt="screen shot 2016-06-13 at 1 23 20 pm" src="https://cloud.githubusercontent.com/assets/1618793/16016635/05d4f372-316a-11e6-9a87-7a0cf9dde08d.png">

**Comment by jshorland** [comment]
Passed testing. Add user forces a selection. Default select is "member". I also tried to save with the same email address I had used previously, and it showed a correct and informative error message.
