### ISSUE TITLE
Creating a user did not send that user an email welcoming them to the deployment

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1207]
### Expected behavior

When I create a user, they should get an email that they are part of that deployment
### Actual behavior

No email is sent
### Steps to reproduce the behaviour/error

Create a new user, check their email

**Comment by jshorland** [comment]
@charlie this isn't a bug. This has NEVER been part of add user, but has been a request on our backlog.

**Comment by jshorland** [comment]
Closing in favor of #1421
