### ISSUE TITLE
Email notifications not sending

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1209]
### Steps to reproduce the behaviour/error
Create a saved search about a post, Setup a notification about that search, submit a notification that matches that post - doesn't work

Logged in / Safari / OSX

**Comment by aoduor** [comment]
we should probably confirm if this is for a published or unpublished post? AFAIK, notifications work with published posts.

**Comment by jshorland** [comment]
Double checked on qa.ushahididev.com. no email notifications came to me after adding posts within the saved search criteria.

**Comment by rjmackay** [comment]
@jshorland I'm deploying a fix now. Retest in 10 mins please.

**Comment by jshorland** [comment]
I'm still not receiving an email when I add posts that meet criteria for "my posts" in saved searches.

**Comment by jshorland** [comment]
Reassigning to you, @rjmackay . still not receiving email alerts

**Comment by jshorland** [comment]
Fixed. Wonky fix, but fixed. Closing and opening a new issue to fix properly.
