### ISSUE TITLE
Activity menu should still have Deployment title/image/desc in it

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1210]
### Expected behaviour

Activity menu should still have Deployment title/image/desc in it
### Actual behavior

Activity menu is a description of what you're seeing with a link back to the map
### Steps to reproduce the behaviour/error

<img width="292" alt="screen shot 2016-06-13 at 1 42 26 pm" src="https://cloud.githubusercontent.com/assets/1618793/16017221/ca64efb0-316c-11e6-83c0-b9349c71f7aa.png">

**Comment by rjmackay** [comment]
This isn't a bug. The activity mode is built as per the designs.

**Comment by rjmackay** [comment]
@jshorland @brandonrosage is this something that should change in a future release?

**Comment by brandonrosage** [comment]
You're right, @rjmackay, it's not a bug. The direction was to have "Activity" and "Settings" landing pages display varying mode context content. I was concerned with explaining the differences between those modes, particularly for small-screen users.

But I think @caharding is right here, given our "modes" approach.

So I've [revised the PL](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/activity.html) to reflect a consistent mode context across modes' landing pages (with the exception of the filters, etc.) for a future release.
