### ISSUE TITLE
Why does Activity "Status" have published/draft?

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1211]
This distinction doesn't exist anywhere else in the platform in any clear way. Where I can filter by published / draft?
<img width="959" alt="screen shot 2016-06-13 at 1 46 00 pm" src="https://cloud.githubusercontent.com/assets/1618793/16017300/30798176-316d-11e6-92b3-edb50843895f.png">

**Comment by aoduor** [comment]
isn't this covered in saved searches? @rjmackay recently added a published posts saved search, yes?

**Comment by rjmackay** [comment]
Correct. Ideally this would be split by who it was visible to instead however its not possible to do that due to backend limitiations.
