### ISSUE TITLE
"Edit" post requirements are confusing.

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1212]
**This is for the COMRADES deployment**: http://comrades.ushahidi.com/views/map

### Expected behaviour
That the approval tab (step) would only be available to users with the appropriate roll and that users who aren't logged in wouldn't be able to fill it out. 
### Actual behaviour
Report was made while *not* logged in. I was able to fill out the approval step. This did *not* publish the post, but it did effectively "fill out" the approval step, which requires choosing to "Edit" the post. This is really counter-intuitive to me: why give the approval step at all to somebody who is not logged in? Also, does "Edit post" effectively enough communicate that you can also edit the approval step? 
### Steps to reproduce the behaviour/error
Create post while not logged in and complete approval step. 
Log in. 
View post and accompanying approval step.

**Comment by rjmackay** [comment]
Review after Sprint 8
