### ISSUE TITLE
Post Type count not reflecting posts made using that type

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1214]
**This is for the COMRADES deployment**: http://comrades.ushahidi.com/views/map

### Expected behaviour
That when I chose "Add to COMRADES Activities" from the pull-down menu associated with that post-type, that the post would eventually be reflected in the numeric counter associated with that post type. 
### Actual behaviour
Choose "Add to COMRADES Activities" from the pull-down menu associated with that post-type, filled out post, approved post, set post to "Everybody can see this" and then went to map view. Noticed that the deployment is still showing "0" for that post type even when it appears in Timeline view. 
![post type not displaying](https://cloud.githubusercontent.com/assets/4574998/16024223/98f8368e-31b8-11e6-958b-ef9b4fd129d5.png)

### Steps to reproduce the behaviour/error
Go to http://comrades.ushahidi.com/views/map. Choose "Add to COMRADES Activities" from the pull-down menu associated with that post-type. Complete, approve, and set post to "Everybody can see this." Go back to map or timeline view and look at counter for COMRADES Activities post type.

**Comment by rjmackay** [comment]
I think this is specific to Comrades. Because its using the production API at ushahidi.io it doesn't yet have the API change needed to return those counts properly. This will get fixes as soon as we go live.

**Comment by jshorland** [comment]
I'm still experiencing an issue which might be related:

When I visit adviceni.ushahidi.io, I don't see ANY posts on the map as a non-logged in visitor to the site, but some surveys have post counts on them. I suspect the system is counting the total number of posts, whether visible to me or not. 

Ideally, I want to see the count of posts I can access, which changes whether I'm logged in as an admin, as a limited permission user, or as a non-logged in visitor.

**Comment by jshorland** [comment]
@Shadrock are you still experiencing the issue you described?

**Comment by Shadrock** [comment]
@jshorland I just tested this ([here's the post I used](https://comrades.ushahidi.io/posts/57)) and it appears to be resolved.

**Comment by jshorland** [comment]
Passes QA for the comrades issue. Opening a new issue for post count depending on user
