### ISSUE TITLE
Mobile search bar breaks design when a search is performed

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1216]
Do a search on mobile iOS iPhone 6

![img_3924](https://cloud.githubusercontent.com/assets/1618793/16026424/8b711060-319c-11e6-9dc8-50827986f426.jpg)

**Comment by rjmackay** [comment]
Fixed by #254

**Comment by jshorland** [comment]
I retested on Android. Fixed. Passes QA. 

@caharding can you confirm on ios?
