### ISSUE TITLE
Survey filters aren't clickable on certain areas of the page

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1217]
Everything in the red box, outside of the "checkbox" is not clickable 

Chrome OSX Desktop

<img width="211" alt="screen shot 2016-06-13 at 7 28 30 pm" src="https://cloud.githubusercontent.com/assets/1618793/16026596/9c623510-319d-11e6-957d-f950807f4801.png">

**Comment by rjmackay** [comment]
This is the same as in the PL. Its also how checkboxes normally work? you need to click the checkbox or its label..

**Comment by rjmackay** [comment]
Unless I'm missing something. ALL of the checkbox itself is clickable for me.

**Comment by caharding** [comment]
I want this whole area to be clickable, not just the checkbox, but the
areas outside

On Mon, Jun 13, 2016 at 4:41 PM, Robbie Mackay <notifications@github.com>
wrote:

> Unless I'm missing something. ALL of the checkbox itself is clickable for
> me.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1217#issuecomment-225740290>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizac8xB-_YdDdtPY0DFlZmFa4gDeMOks5qLeqhgaJpZM4I01S4>
> .
>



-- 
Charlie Harding
Product Director

**Comment by brandonrosage** [comment]
@caharding I'm a little confused by this issue. Using Chrome on OS X (and everything else I've tested), the survey name's whole container (with the exception of the dropdown trigger) is a click target for toggling the selection of that filter: http://d.pr/i/NZqm/XRRQsgYS

Are you saying that, on your machine, when you click the survey name, nothing happens?

**Comment by caharding** [comment]
Check the original image I posted. When you hover over the check box
appears. The area left of, above and below the check box are not clickable.
This has messed me up a couple of times.

On Tuesday, June 21, 2016, Brandon Rosage <notifications@github.com> wrote:

> @caharding <https://github.com/caharding> I'm a little confused by this
> issue. Using Chrome on OS X (and everything else I've tested), the survey
> name's whole container (with the exception of the dropdown trigger) is a
> click target for toggling the selection of that filter:
> http://d.pr/i/NZqm/XRRQsgYS
>
> Are you saying that, on your machine, when you click the survey name,
> nothing happens?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1217#issuecomment-227512593>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizab6ZRsjOPKNbpTRvzqb7_kMJkXEgks5qOB-ZgaJpZM4I01S4>
> .
>


-- 
Charlie Harding
Product Director

**Comment by brandonrosage** [comment]
Got it. Sorry for being a moron and making you explain it three times. All fixed.

**Comment by rjmackay** [comment]
@brandonrosage was this just a CSS fix? or do we need to update markup in the client?

**Comment by brandonrosage** [comment]
Just a CSS fix.

**Comment by rjmackay** [comment]
Self assigning to remind me to update production CSS 👍

**Comment by rjmackay** [comment]
@caharding can you retest now?

**Comment by jshorland** [comment]
QA testing: passed. Entire box is clickable.
