### ISSUE TITLE
Collections 

### ISSUE THREAD

**Issue by KLyon42** [ushahidi/platform#1224]
### Expected behaviour
Clicking on collections should, in theory, present a list of created Collections

### Actual behaviour

Typing in the start of the collection's name populates the created object but it doesn't appear until then. 

### Steps to reproduce the behaviour/error

Create a new collection, add posts, then click on the generic Collections menu.  In my experience, it remains blank.

**Comment by willdoran** [comment]
@KLyon42 I'm having trouble reproducing this error, would you mind providing a screenshot of what you see?

**Comment by KLyon42** [comment]
I'd be happy to help.  However, as is currently, I can't actually access
the Collections at all.  I'm using Chrome Version 51.0.2704.84.  Legacy
user, under https://klyon42.ushahidi.io/ .  I can't access Collections from
either the main screen or by going to the Timeline, checkboxing a post,
then clicking on "Add to Collection" either.  Both do nothing, including
when "Inspecting" the code.  Two errors are present under Inspection
however, consistently throughout any page I look at:

Failed to parse SourceMap: https://klyon42.ushahidi.io/css/style.min.css.map
Failed to parse SourceMap: https://klyon42.ushahidi.io/js/bundle.js.map

(Also, Mixed Media warnings are being thrown for http and https being
mixed.  But that's less concerning)


[image: Inline image 1]

Hopefully that helps!  Feel free to let me know if there's any other info I
can provide to troubleshoot from.

Best,
Kenneth Lyon

P.S. On a slightly different note, is a straight list of Posts not
currently an option?  All I'm finding is the chronological Timeline
viewer.  I'm surprised that's not available so if it's meant to be, it's
not.

**Comment by KLyon42** [comment]
Collections now appear to be showing properly.  Thank you.

If taking suggestions though, a Select All under the Timeline as well as a
way to change the Sort therein would be my two biggest ones so far.  Some
otherwise tedious tasks could be avoided by adding those two options.

Regardless, thanks for your efforts!  I'm looking forward to seeing what
opportunities your platform will prove well suited for!

**Comment by rjmackay** [comment]
> If taking suggestions though, a Select All under the Timeline as well as a
way to change the Sort therein would be my two biggest ones so far.  Some
otherwise tedious tasks could be avoided by adding those two options.

If you select an item in the timeline a toolbar should appear with 'select all' .
I'll make a note of the request for 'Sort' order though. Thanks!
