### ISSUE TITLE
appi.ushahidi.io has weird map marker placement

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1225]
the appi.ushahidi.io instance seems to have gotten into some issues (map markers on the home page) after the migration.
![screen shot 2016-06-14 at 5 43 38 pm](https://cloud.githubusercontent.com/assets/3224856/16064609/9603a086-3257-11e6-87e9-0749448cd591.png)

**Comment by rjmackay** [comment]
I'm not clear whats going wrong here? It seems there are shadows in odd places.. but is there something else wrong too?

**Comment by rjmackay** [comment]
The work around is to turn of 'combine nearby reports' in general settings. Some of our styling is breaking the display of the map clusters

**Comment by rjmackay** [comment]
Deploying a bugfix to production right now..

**Comment by rjmackay** [comment]
@jshorland can you let the deployers know we've fixed this?
