### ISSUE TITLE
Can't mark posts as complete

### ISSUE THREAD

**Issue by sebm90** [ushahidi/platform#1226]
### Expected behaviour
When I click the toggle button next to "mark as complete" on a post (on dabanga.ushahidi.io), it should toggle to on:
![image](https://cloud.githubusercontent.com/assets/5349387/16158290/eadc187e-34bc-11e6-8624-2a27f0439b29.png)

### Actual behaviour
The toggle button does not change. This prevents posts from being published.

### Steps to reproduce the behaviour/error
Edit a post.

**Comment by rjmackay** [comment]
You can't complete a post until its required fields are filled in.
We should add an explanation below the toggle. OR just remove 'mark as complete' as suggested in #1187
