### ISSUE TITLE
Error when replying to original author of message

### ISSUE THREAD

**Issue by sebm90** [ushahidi/platform#1227]
### Expected behaviour
A reply can be posted.
![image](https://cloud.githubusercontent.com/assets/5349387/16158367/33c118d2-34bd-11e6-9c69-c50c00e53110.png)

### Actual behaviour
An error is shown "Validation - that the message can not be empty" (even when the message is not empty)

**Comment by rjmackay** [comment]
@sebm90 is there a specific solutions deployment this needs to be pushed to?

**Comment by jshorland** [comment]
@sebm90 can you confirm which deployment this is for?
