### ISSUE TITLE
Unable to create new surveys

### ISSUE THREAD

**Issue by kkuang96** [ushahidi/platform#1228]
### Steps to reproduce the behaviour/error: Settings -> Surveys. Click the yellow plus sign at the top. 

DemoWatch deployment: https://demowatch.ushahidi.io/settings/surveys

![survey page](https://cloud.githubusercontent.com/assets/20007481/16168243/590ea16a-34b6-11e6-85ef-f474525c3a75.jpg)
![survey limit](https://cloud.githubusercontent.com/assets/20007481/16168245/5db1e4ac-34b6-11e6-901a-954c9aa3d38c.jpg)

**Comment by jshorland** [comment]
Hey DemoWatch Team,

I’m going to send this to our dev team to take a look. Sorry for the issue — we’ll get it fixed ASAP.


Jess Shorland
Product manager
jess@ushahidi.com

**Comment by rjmackay** [comment]
Via https://app.intercom.io/a/apps/hl5rfiga/inbox/tech/conversations/5088887006

**Comment by rjmackay** [comment]
Deploying a fix as v3.4.2
