### ISSUE TITLE
Multiple surveys cannot have the same field title

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1236]
### Expected behaviour
I create survey 1 and make a custom field called "Location" and hit save
I create survery 2 and make a custom field called "Location" and hit save
Everything works

### Actual behaviour
I create survey 1 and make a custom field called "Location" and hit save
I create survery 2 and make a custom field called "Location" and hit save
I can't enter location and it doesn't tell me why, instead I get an error that says "the key "location" is not available" which doesn't make any sense and I don't know what that means. 

### Steps to reproduce the behaviour/error
Create two surveys with the same custom field title and key

**Comment by rjmackay** [comment]
This is why we used to expose the `key` field. It looks like that was remove but no one changed the way auto generation happens for keys.

**Comment by willdoran** [comment]
@rjmackay @caharding the key field is still exposed - but key generation should be changed to use something more logical and to check if the generated key is in use.

**Comment by willdoran** [comment]
@rjmackay @caharding @jasonmule I would suggest that we generate a unique hash for the key using [angular-uuid](https://www.npmjs.com/package/angular-uuid) is that reasonable?

**Comment by tuxpiper** [comment]
@rjmackay  @willdoran  @jasonmule  Would this be affecting search queries over form attributes?

In Pheme we have a number of custom form attributes that need to be filterable. We have code that runs queries like this:

`GET /api/v3/posts?status=all&limit=10&values[theme-id]=989&form[]=2&offset=0`

However, the `values[theme-id]` bit seems to be not working anymore after this change (causes code 500 responses). Would we need to lookup the form attribute UUID and substitute `theme-id` for that?

**Comment by jshorland** [comment]
Passed testing. I can now add multiple fields with the same name to multiple surveys.
