### ISSUE TITLE
Steps are called Tasks

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1237]
When editing a survey, I want to add more fields, which I can only do under an area called "Tasks" which makes no sense. I want this back end experience to look much more like the front end. I want custom fields to be a plus sign right under the standard description. I can then input a new Step in between custom fields if I want to go to a second page. 
<img width="740" alt="screen shot 2016-06-21 at 3 57 57 pm" src="https://cloud.githubusercontent.com/assets/1618793/16249167/f9870686-37c8-11e6-8aea-712e68cc796f.png">

**Comment by brandonrosage** [comment]
You're totally right, @caharding.

From a front-end perspective, I'd suggest we demote a post's "Tasks" (much like Comments). This would primarily effect:

* [Settings: Surveys: Edit survey](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-survey-edit.html)
* [Post: Detail](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-detail.html)
* [Post: Add](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-add.html)
* [Post: Edit](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-edit.html)

_Example_:
![screen](https://cloud.githubusercontent.com/assets/1136279/16394407/aa7a89b2-3c7a-11e6-9f0c-09cfc6796ce4.png)

**Comment by rjmackay** [comment]
Now that I've been through the many explanations... this makes a lot of sense. Thanks Brandon!

Minor:
- [Settings: Surveys: Edit survey](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-survey-edit.html) doesn't have a button to "Add task" any more?
- This might be a good moment to add templated tasks too ie. when adding a task present the user with options: "Verify" or "Custom task..."

**Comment by brandonrosage** [comment]
@rjmackay I've addressed both of these needs in a revised ["Edit survey" layout](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-survey-edit.html) that, I think, works whether we're supporting "pre-built" tasks, just "free-form" tasks, or both.

_Example_:
![Tasks: Verify](https://cloud.githubusercontent.com/assets/1136279/16533425/32adfe9c-3f9e-11e6-81e1-0f45b014738b.png)

It should be pretty straightforward. But let me call out a few flows (which are all demonstrated in the layout)...

By default, a survey should have no tasks attached to it. And that state is provided (commented in HTML) in the layout:

![no tasks](https://cloud.githubusercontent.com/assets/1136279/16533399/09d0bdde-3f9e-11e6-849c-7bc7a8411598.png)

When you select "Add task," you get a modal asking you to select either a pre-built task or to create a custom one:

![add task](https://cloud.githubusercontent.com/assets/1136279/16533463/7bdfec42-3f9e-11e6-9d1c-77eec0d0d109.png)

If you select a pre-built one, it closes the modal and adds the task to the "tabs menu" (which now includes a tab that serves as an "Add task" action):

![task added](https://cloud.githubusercontent.com/assets/1136279/16533501/abc54a2e-3f9e-11e6-8f7b-2f3e623b6842.png)

If you select a "custom" task, it displays a second modal, asking for basic configuration options, like "task name":

![add custom task](https://cloud.githubusercontent.com/assets/1136279/16533518/d34dda16-3f9e-11e6-82ac-1688014b365c.png)

After selecting "Save and continue," it closes the modal and adds the task to the "tabs menu," with an open listing prompting you to "Add field":

![custom task added](https://cloud.githubusercontent.com/assets/1136279/16533560/396369c4-3f9f-11e6-9037-4ec749c014e4.png)

How do we look now, y'all?

**Comment by caharding** [comment]
Dig it. On the 2nd image is there a way of keeping the help text separate
from the rest of the header and description? It feels a little awkward
right now.

On Fri, Jul 1, 2016 at 4:22 PM, Brandon Rosage <notifications@github.com>
wrote:

> @rjmackay <https://github.com/rjmackay> I've addressed both of these
> needs in a revised "Edit survey" layout
> <http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-survey-edit.html>
> that, I think, works whether we're supporting "pre-built" tasks, just
> "free-form" tasks, or both.
>
> *Example*:
> [image: Tasks: Verify]
> <https://cloud.githubusercontent.com/assets/1136279/16533425/32adfe9c-3f9e-11e6-81e1-0f45b014738b.png>
>
> It should be pretty straightforward. But let me call out a few flows
> (which are all demonstrated in the layout)...
>
> By default, a survey should have no tasks attached to it. And that state
> is provided (commented in HTML) in the layout:
>
> [image: no tasks]
> <https://cloud.githubusercontent.com/assets/1136279/16533399/09d0bdde-3f9e-11e6-849c-7bc7a8411598.png>
>
> When you select "Add task," you get a modal asking you to select either a
> pre-built task or to create a custom one:
>
> [image: add task]
> <https://cloud.githubusercontent.com/assets/1136279/16533463/7bdfec42-3f9e-11e6-9d1c-77eec0d0d109.png>
>
> If you select a pre-built one, it closes the modal and adds the task to
> the "tabs menu" (which now includes a tab that serves as an "Add task"
> action):
>
> [image: task added]
> <https://cloud.githubusercontent.com/assets/1136279/16533501/abc54a2e-3f9e-11e6-8f7b-2f3e623b6842.png>
>
> If you select a "custom" task, it displays a second modal, asking for
> basic configuration options, like "task name":
>
> [image: add custom task]
> <https://cloud.githubusercontent.com/assets/1136279/16533518/d34dda16-3f9e-11e6-82ac-1688014b365c.png>
>
> After selecting "Save and continue," it closes the modal and adds the task
> to the "tabs menu," with an open listing prompting you to "Add field":
>
> [image: custom task added]
> <https://cloud.githubusercontent.com/assets/1136279/16533560/396369c4-3f9f-11e6-9037-4ec749c014e4.png>
>
> How do we look now, y'all?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1237#issuecomment-230039121>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizadSq0vGxGXSDzjAcAEs__GQ8KKG9ks5qRXbugaJpZM4I7QV_>
> .
>



-- 
Charlie Harding
Product Director

**Comment by rjmackay** [comment]
@brandonrosage is "Show this task to everyone when the post is published" a simple on/off field? or do you anticipate setting it visible to specific roles?

**Comment by brandonrosage** [comment]
@rjmackay Yes: Simple on/off switch. 

When we went to "Post Status" -- and moved visibility settings to Roles' configuration -- I think we married ourselves (in the interest of simplicity and consistency) to the notion that "published" = "visible to everyone."

And, of course, "everyone" is the broadest audience the deployment is configured to reach.

So the control you're referring to is simply asking, "When this task is complete, do you want it to be part of what gets published? Or do you want to ensure only the post fields get published, while the tasks remain visible only to people with permission to review them?" By default, the latter is true.
