### ISSUE TITLE
Choose post status on Import

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1238]
### Expected behaviour
When I import data, it will be automatically viewable to everyone unless I select who it is viewable by

### Actual behaviour
If I mass import data it is only viewable by me and I have to go post by post and change viewability

### Steps to reproduce the behaviour/error
Import data, and see who can view it

**Comment by rjmackay** [comment]
This is actually queued up with the configure posts step. But needs some bugs fixing before it goes live.

**Comment by rjmackay** [comment]
@jshorland I think this probably has to wait till Sprint 8 unless its urgent?

**Comment by rjmackay** [comment]
Closed in favor of #1388
