### ISSUE TITLE
Add visual feedback when adding a post to a collection

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1239]
### Expected behaviour

When I add a post to a collection, I want to get visual feedback that it worked, I have to currently press X
### Actual behaviour

No visual feedback
### Steps to reproduce the behaviour/error

Add a post to a collection
<img width="638" alt="screen shot 2016-06-21 at 4 01 58 pm" src="https://cloud.githubusercontent.com/assets/1618793/16249266/89e9b0c0-37c9-11e6-8031-fca0306da918.png">

**Comment by rjmackay** [comment]
@brandonrosage was there some expected feedback already that we haven't implemented? if not could you suggest a pattern/solution?

**Comment by brandonrosage** [comment]
I think [the "message" pattern](https://github.com/ushahidi/platform-pattern-library/blob/gh-pages/pattern-library/partials/_modals-global.html#L401-L407) is appropriate here, displayed within the modal. A good example of this is when you click "Account settings" i[n the PL](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/map.html), select "Notifications," and remove the "Police encounters needing translation" notification. A confirmation message appears for a duration, with an option to undo during that period.

**Comment by jshorland** [comment]
This has been adjusted. Closing.
