### ISSUE TITLE
I cannot see the save button when creating a collection

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1240]
### Expected behaviour
Save should be easy to see when I'm creating a collection

### Actual behaviour
I have to scroll down the pop up in order to find save

### Steps to reproduce the behaviour/error
Create a collection
Press add new
On small screens you can't see the save button 

<img width="948" alt="screen shot 2016-06-21 at 4 03 53 pm" src="https://cloud.githubusercontent.com/assets/1618793/16249336/e526679e-37c9-11e6-97c5-ae9343ee0937.png">

**Comment by rjmackay** [comment]
@brandonrosage have we screwed up implementing the pattern? or does this need a PL change too?

**Comment by brandonrosage** [comment]
@rjmackay Generally speaking, if a modal requires a save (as in creating or editing something, like a Collection), you'll want to include a `form-field` with the necessary buttons. An example is in the PL, with editing a Saved Search: https://github.com/ushahidi/platform-pattern-library/blob/gh-pages/pattern-library/5_layouts/map-saved.html#L352-L355

**Comment by rjmackay** [comment]
Sorry I wasn't very clear. The modal *has* a `form-field` with save/cancel buttons. However on a small screen they disappear off the bottom of the modal and you must scroll to see them. On chrome at least the scrollbar is more obvious though.. I'm not sure if thats obvious enough that you need to scroll down before you can save?

@caharding which browser was this in?

**Comment by caharding** [comment]
Chrome!

On Mon, Jun 27, 2016 at 7:59 PM, Robbie Mackay <notifications@github.com>
wrote:

> Assigned #1240 <https://github.com/ushahidi/platform/issues/1240> to
> @caharding <https://github.com/caharding>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1240#event-705792490>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABizafwJceSLQ9Qk5ygE4BzyiSyUv-pTks5qQI4EgaJpZM4I7Qpk>
> .
>



-- 
Charlie Harding
Product Director

**Comment by rjmackay** [comment]
<img width="612" alt="screenshot 2016-06-29 13 49 33" src="https://cloud.githubusercontent.com/assets/7965/16438056/5d2ddcd6-3e00-11e6-9a7c-ac364b1fd362.png">

Weird. For me this has a really obvious scrollbar in Chrome.

**Comment by caharding** [comment]
That scroll bar only appears once you start to scroll. There is not a clear
visual indicator of what you're supposed to do on this screen and it is
confusing.

On Tue, Jun 28, 2016 at 6:50 PM, Robbie Mackay <notifications@github.com>
wrote:

> [image: screenshot 2016-06-29 13 49 33]
> <https://cloud.githubusercontent.com/assets/7965/16438056/5d2ddcd6-3e00-11e6-9a7c-ac364b1fd362.png>
>
> Weird. For me this has a really obvious scrollbar in Chrome.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1240#issuecomment-229235052>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizaVG-2toNPZNymacXJQpzDpC_uAiAks5qQc9qgaJpZM4I7Qpk>
> .
>



-- 
Charlie Harding
Product Director

**Comment by brandonrosage** [comment]
I've staged a solution for the modal's actions to stick to the bottom of the modal window, with a translucent background that hints at the overflow content below it:

![modal](https://cloud.githubusercontent.com/assets/1136279/16534959/44b1d2ca-3fa9-11e6-9d9c-51e69cb6ce49.png)

This also addresses the need for a clear action being visible at all times.

On the aforementioned example "Add to Collection," the first modal's heading should be "Add to Collection." And if they choose to "Create collection," the second modal's heading should read "Create Collection."

**Comment by rjmackay** [comment]
You can see the example here: http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/map-collection.html

We just need to wrap save and cancel buttons in a `.modal-actions` container I think
```
<div class="modal-actions">
            <div class="form-field">
                <button type="button" class="button-beta button-flat modal-trigger">Cancel</button>
                <button type="button" class="button-alpha modal-trigger">Save &amp; close</button>
            </div>
        </div>
```

**Comment by brandonrosage** [comment]
Yes, wrap the `.form-field` for modal window actions with `.modal-actions` *and* wrap the rest of the modal window's body content with `.modal-body`. All together, this ensures a smooth scrolling experience, too.

**Comment by jshorland** [comment]
This is working for me in qa.ushahididev.com. @caharding would you mind logging in and double checking that this pattern solves the issue you described?

**Comment by caharding** [comment]
Works for me
