### ISSUE TITLE
Don't show create first post on settings

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1241]
### Expected behaviour
Only show me a create your first post pop up when I'm first browsing to the Map or Timeline. Not on settings. 

### Actual behaviour
When I create a deployment, it requires configuration, but ever settings page I go to shows me the pop up that I haven't create a post yet.

### Steps to reproduce the behaviour/error
Create a new deployment and try making a few surveys. The pop up is all over the place.

**Comment by willdoran** [comment]
The message should be turned off when the user navigates away from the the timeline and map views.

**Comment by willdoran** [comment]
@caharding having reviewed the issue. The slider occurs when the user hits the timeline view, the slider will remain on top when the user navigates to any other page. This is the general behaviour of system messages, we want them to be visible until the user actively engages with them and dismisses them. 

If the user clicks dismiss and navigates to the settings page the slider will not reappear until they visit timeline again. However, if they ignore the message and navigate to a different page it will persist until they either dismiss it or click add post.

Our system messages have some config properties one of which is timeout, so they disappear after a certain amount of time. This messages is set to not disappear until the user either clicks dismiss or adds a post.

Does that seem reasonable?

**Comment by willdoran** [comment]
To clarify a little further the slider messages are system level messages, perhaps this is not totally clear from their placement in the UI, I think the UI trys to balance between calling attention and blocking the user by forcing them to respond to the message.

**Comment by rjmackay** [comment]
Discussed this with @willdoran - I think there's a clear solution to hide the slider when navigating away from the map / timeline view?

**Comment by caharding** [comment]
Works for me

On Mon, Jun 27, 2016 at 7:47 PM, Robbie Mackay <notifications@github.com>
wrote:

> Discussed this with @willdoran <https://github.com/willdoran> - I think
> there's a clear solution to hide the slider when navigating away from the
> map / timeline view?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1241#issuecomment-228933967>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizaQduoxRuR7FnKxu0_Q3i7EM_leH7ks5qQIs4gaJpZM4I7QtQ>
> .
>



-- 
Charlie Harding
Product Director

**Comment by jshorland** [comment]
Passed testing. Closing issue.

**Comment by jshorland** [comment]
@willdoran this may also be an issue of code not landing yet?

**Comment by rjmackay** [comment]
Test on ushahididev.com
Can you also confirm this doesn't interfere with notifications after saving a post, or trying to create a survey when over the limit?

**Comment by rjmackay** [comment]
Should be fixed on ushahidi.io too now
