### ISSUE TITLE
Automatically dismiss a dropdown when you browse to another page

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1242]
### Expected behaviour

When I perform an action which creates a dismissable drop down, the dropdown will be dismissed when I browse to another page
### Actual behaviour

Dropdown takes a few seconds to go away after I browse to another page
### Steps to reproduce the behaviour/error

Submit a post 
Browse elsewhere
The post sticks around too long, such that I can't do my next action like search

**Comment by rjmackay** [comment]
What was the specific case where this happened?

**Comment by caharding** [comment]
Sorry it was everywhere. Creating a post, creating a survey, editing a post
or survey, changing settings.

On Tuesday, June 21, 2016, Robbie Mackay <notifications@github.com> wrote:

> What was the specific case where this happened?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1242#issuecomment-227629559>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizadbV2ZLRDW-5cTZr2WjfQEBN35VIks5qOKNxgaJpZM4I7QzT>
> .
>


-- 
Charlie Harding
Product Director

**Comment by rjmackay** [comment]
@brandonrosage adding you just to confirm this makes sense. ie. that the slider should disappear whenever the user navigates to another page?

**Comment by willdoran** [comment]
@rjmackay @caharding This functionality now exists for notifications. Is there specific messages this should be updated for other than the "add first post".

For saving a new entity the message times out BUT it can't be made to disappear automatically on navigate otherwise it won't appear because it is invoked before the redirect just after the save.

**Comment by caharding** [comment]
I think we need Brandon's input here... Something that may need to be
tested with users.

On Thu, Jun 30, 2016 at 11:45 AM, will <notifications@github.com> wrote:

> @rjmackay <https://github.com/rjmackay> @caharding
> <https://github.com/caharding> This functionality now exists for
> notifications. Is there specific messages this should be updated for other
> than the "add first post".
>
> For saving a new entity the message times out BUT it can't be made to
> disappear automatically on navigate otherwise it won't appear because it is
> invoked before the redirect just after the save.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1242#issuecomment-229752026>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizaSvVV0Paz_UML_dJfIoiZ7Hn_fGoks5qRA6tgaJpZM4I7QzT>
> .
>



-- 
Charlie Harding
Product Director

**Comment by willdoran** [comment]
This is related to [1241](https://github.com/ushahidi/platform/issues/1241)

**Comment by brandonrosage** [comment]
There are many cases, including when successfully adding a post, where the message is intended to appear as the user is being taken to another page. 

In that specific case -- if the user isn't logged in -- the message doesn't appear on the "Add post" screen. They select "Submit" and they're taken back to where they came from (say, "Map" mode), where they'll immediately get a "message" confirming what's happened.

The nature of this particular message, which doesn't require any action, means it should disappear after five seconds. If that is still a problem, I'd suggest the following solution:

_When displaying a message on a view that is effectively "modal"_ -- where its toolbar includes actions to "Save" or "Cancel" -- the message should appear as it currently does, from the top, overlaying everything:

![modal](https://cloud.githubusercontent.com/assets/1136279/16627082/4b31271a-4371-11e6-91aa-4b8f0d9b4aac.png)

_When displaying a message on a view that is not "modal"_ -- where its toolbar includes optional controls and actions, like "search" and "add" -- the message should appear from the bottom:

![not modal](https://cloud.githubusercontent.com/assets/1136279/16627070/37e1e816-4371-11e6-96eb-0ddb702f990e.png)

@caharding Do you think that variation is necessary?

**Comment by caharding** [comment]
Very useful. Top bar alerts are more urgent and system wide, blocking you
from further action, on the bottom they allow you to keep your workflow but
still show you important info.

On Wed, Jul 6, 2016 at 10:02 AM, Brandon Rosage <notifications@github.com>
wrote:

> There are many cases, including when successfully adding a post, where the
> message is intended to appear as the user is being taken to another page.
>
> In that specific case -- if the user isn't logged in -- the message
> doesn't appear on the "Add post" screen. They select "Submit" and they're
> taken back to where they came from (say, "Map" mode), where they'll
> immediately get a "message" confirming what's happened.
>
> The nature of this particular message, which doesn't require any action,
> means it should disappear after five seconds. If that is still a problem,
> I'd suggest the following solution:
>
> *When displaying a message on a view that is effectively "modal"* --
> where its toolbar includes actions to "Save" or "Cancel" -- the message
> should appear as it currently does, from the top, overlaying everything:
>
> [image: modal]
> <https://cloud.githubusercontent.com/assets/1136279/16627082/4b31271a-4371-11e6-91aa-4b8f0d9b4aac.png>
>
> *When displaying a message on a view that is not "modal"* -- where its
> toolbar includes optional controls and actions, like "search" and "add" --
> the message should appear from the bottom:
>
> [image: not modal]
> <https://cloud.githubusercontent.com/assets/1136279/16627070/37e1e816-4371-11e6-96eb-0ddb702f990e.png>
>
> @caharding <https://github.com/caharding> Do you think that variation is
> necessary?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1242#issuecomment-230837745>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizaYXqA70N8zZ5O-bvosNd0H5VFZO6ks5qS9-igaJpZM4I7QzT>
> .
>



-- 
Charlie Harding
Product Director

**Comment by rjmackay** [comment]
@jshorland assigning to you for priority

**Comment by jshorland** [comment]
Thanks @rjmackay -- working on organizing our roadmap today and tomorrow.

**Comment by rjmackay** [comment]
Tech requirements
- Update Slider service and add param to specify top or bottom slider
- We need to add another slider-container to the markup
- Investigate what happens with multiple sliders at once. @brandonrosage whats the desired behaviour with multiple slider notifications?

**Comment by rjmackay** [comment]
@brandonrosage design is done on this. But it could do with an answer on how to handle multiple notifications at once, sometime before it gets into a sprint.

**Comment by brandonrosage** [comment]
No. 1, we should only show one `.message` pattern on a layout at any given time. So if there are multiple to display, the ideal logic would be:

1. Show all "modal" messages before finally showing "non-modal" messages.
2. Otherwise, display each message in the order that the app generated it.

No. 2, in the `develop` branch, I've revised the layout-level styles for messages so that the addition of the class name `.modal` to the `.message` container gives it the proper layout. With that class name, it'll be oriented at the top of the view. Without it, it'll appear at the bottom.
