### ISSUE TITLE
No way to change billing on a plan

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1243]
I entered my credit card to give a Responder demo to a client, now I can't change it. I need a way to be able to update my billing info.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-690

**Comment by rjmackay** [comment]
This goes in with a bunch of other billing features needed. The fastest path to these would be to theme Chargebee payment portal and use that. I need to look into that.

**Comment by caharding** [comment]
@rjmackay I was cross referencing platform with Rollcall to figure out payment method requirements. Seems we don't have a good solution here either.

**Comment by rowasc** [comment]
<img width="747" alt="Screen Shot 2019-06-08 at 22 34 57" src="https://user-images.githubusercontent.com/2434401/59153972-b670e180-8a3d-11e9-8d1d-c3bca460a09f.png">
This looks pretty broken right now, I'm not sure how users unsubscribe without talking with support 🤔 
When I click "sign up" for the free plan it takes me to the demo page and says it can't find the deployment
<img width="1680" alt="Screen Shot 2019-06-08 at 22 37 46" src="https://user-images.githubusercontent.com/2434401/59153982-16678800-8a3e-11e9-97ef-7e2f04dfb630.png">

**Comment by Erioldoesdesign** [comment]
I should take a look at the UX of this one asap when platform work is unfrozen
