### ISSUE TITLE
Default "viewable by" needs to be editable on a survey level

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1244]
A new deployment should have default to post viewable by all people. The viewable by default value should be set by the admin at a per survey level. This also screws up all CSV imports right now.

**Comment by rjmackay** [comment]
Sorry I'm not clear what the request is.
That posts should be publishable by any user by default? That runs counter to expected behaviour by many users who expect to collect posts and review them first before publishing.

**Comment by brandonrosage** [comment]
I think @rjmackay is right. The overwhelming number of customer interviews during our user research included the need for some semblance of a post review workflow. I think we position users for success, too, by building their deployment such that nothing will appear under their "banner" that they didn't know about or approve first. And if they want to turn that protection off, they can -- easily.

Regarding CSV import, this is addressed in [the overall "post status" design solution](https://github.com/ushahidi/platform/issues/1263#issuecomment-228464926), which includes a "Mark all imported posts as..." option during the import process.

**Comment by caharding** [comment]
I believe that the default should be different for our various user
types/plans. Mappers are advocates looking to raise awareness and have only
one survey. To make Ushahidi useful to them, it needs to be easy for things
to be posted so they can see a real benefit. For them the default should be
public. For Responder and Surveyor the approval process may be more
important, and so we should default to requires approval.

This should also change by user type. If an admin submits a post, it should
automatically post (or at least have the option to in settings). This
option should extend to other logged in user types. It simply doesn't make
sense to post, and then review your work, and the approve a draft.

On Mon, Jun 27, 2016 at 1:30 PM, Brandon Rosage <notifications@github.com>
wrote:

> I think @rjmackay <https://github.com/rjmackay> is right. The
> overwhelming number of customer interviews during our user research
> included the need for some semblance of a post review workflow. I think we
> position users for success, too, by building their deployment such that
> nothing will appear under their "banner" that they didn't know about or
> approve first. And if they want to turn that protection off, they can --
> easily.
>
> Regarding CSV import, this is addressed in the overall "post status"
> design solution
> <https://github.com/ushahidi/platform/issues/1263#issuecomment-228464926>,
> which includes a "Mark all imported posts as..." option during the import
> process.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1244#issuecomment-228865805>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizaWNUrYf-H3PWE7-YwgV7VZH36Mgeks5qQDLogaJpZM4I7Q6w>
> .
>



-- 
Charlie Harding
Product Director

**Comment by brandonrosage** [comment]
In response to the second half of your comment, @caharding, my assumption is that, if your role gives you permission to review posts, you'd be able to author a new post and toggle its status on the fly.

**Comment by rjmackay** [comment]
>  if your role gives you permission to review posts, you'd be able to author a new post and toggle its status on the fly.

Definitely. Thats already the case.. the 'visible to' control is shown when creating a post as an admin.

> I believe that the default should be different for our various user types/plans.

This is kinda hard to implement right now. However the [next iteration on Surveys](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-survey-edit.html) turns this into a toggle for each Survey: "Require posts be reviewed before they're published".

I suggest the default remains the same for all plans (require review before publishing) but we implement this toggle in the next sprint, so that deployers *can* set a survey to be auto-approved.
