### ISSUE TITLE
Location of Pin should show an address

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1245]
### Expected behaviour

I created a location by searching an address. When I click on a Pin I want it to show me the address position that I had searched. My solutions client won't sign up without it.
### Actual behaviour

When I'm looking at a post with a location value, and I click on the Pin, it shows me the "key" title. I want to see the address. 
### Steps to reproduce the behaviour/error

Create a post with a location
Click on that post
Click on the pin 

<img width="708" alt="screen shot 2016-06-21 at 4 14 41 pm" src="https://cloud.githubusercontent.com/assets/1618793/16249522/4c0c5346-37cb-11e6-957a-1937f960712e.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-689

**Comment by rjmackay** [comment]
Same as #351

**Comment by jshorland** [comment]
to answer during scoping:
- what if a pin doesn't have an address associated with it? 
- how do we display locations that were typed in as city/state or something broad like that?
