### ISSUE TITLE
Strange notification when I add/delete a category

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1249]
Delete or add a category

<img width="261" alt="screen shot 2016-06-21 at 4 21 51 pm" src="https://cloud.githubusercontent.com/assets/1618793/16249646/5558cc58-37cc-11e6-9c9e-d80650dcca23.png">

**Comment by jshorland** [comment]
Failed testing for add category. Passed testing for delete category

Steps to replicate failure
1. login to jshorland88.ushahidi.io, jess@ushahidi.com, password
2. navigate to settings --> categories --> add category
3. type details in and save category
4. See user notification (screen shot)

**Comment by willdoran** [comment]
This should be fixed by [281](https://github.com/ushahidi/platform-client/pull/281)
