### ISSUE TITLE
Categories should be a multi-select drop down, not a list and retitled as "Tags"

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1250]
When you have a lot of categories it takes up a ton of space on a post. Should be just handled as a multi-select dropdown

<img width="728" alt="screen shot 2016-06-21 at 4 25 00 pm" src="https://cloud.githubusercontent.com/assets/1618793/16249695/bf2695ac-37cc-11e6-94f4-29b91994fe6b.png">

**Comment by jshorland** [comment]
dup;licate. closing.
