### ISSUE TITLE
Default post requirements are in the wrong order

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1251]
I find it really confusing that viewability, steps/tasks, and mark as complete all appear below the title, above description, then categories and then custom fields. Its also confusing that the post type is on the left hand side, and not included on the post at all.

This order doesn't make visual sense and it is very confusing when I'm authoring a post. I want to be able to enter all the post data, and not deal with these "configuration" issues. Needs significant rearrangement

<img width="976" alt="screen shot 2016-06-21 at 4 27 21 pm" src="https://cloud.githubusercontent.com/assets/1618793/16249742/1ce2b3b0-37cd-11e6-9aba-b845fb160cb6.png">

My recommendation

![artboard 1](https://cloud.githubusercontent.com/assets/1618793/16249867/ea41945c-37cd-11e6-99bd-cebd40292685.png)

**Comment by brandonrosage** [comment]
This structure is significantly improved in the latest layout changes to "[Post: Add](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-add.html)" and "[Post: Edit](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-edit.html)."

_"Post: Add" example:_
![image](https://cloud.githubusercontent.com/assets/1136279/16394898/103f83b8-3c7d-11e6-8e62-ff8da85fcd20.png)

Configuration, if there is any, is moved into a 'toolbox' outside the 'form sheet.' In the example above, the user doesn't have permission to configure the post's status or anything, so they simply get a heads up that their post will need to be reviewed before it's published.

One note, though, on your diagram above: We try to maintain a consistency in how posts appear and how they're structured across Map, Timeline, Post Detail, and Post Edit views. Reading or editing, they should look very familiar. Part of that includes abstracting the post's survey into its color "band." And when you focus on a single post, the "mode context" (which is the left column on large screens and the top-most bar on small screens) displays the survey name.

This is why the survey name is not repeated inside the postcard, editable or not. And I think that's still the way to go, unless our users tell us it's not working.

**Comment by caharding** [comment]
Looks great. Only other thing is that Categories should be a multi-select
dropdown to save space.

On Mon, Jun 27, 2016 at 1:48 PM, Brandon Rosage <notifications@github.com>
wrote:

> This structure is significantly improved in the latest layout changes to "Post:
> Add
> <http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-add.html>"
> and "Post: Edit
> <http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-edit.html>
> ."
>
> *"Post: Add" example:*
> [image: image]
> <https://cloud.githubusercontent.com/assets/1136279/16394898/103f83b8-3c7d-11e6-8e62-ff8da85fcd20.png>
>
> Configuration, if there is any, is moved into a 'toolbox' outside the
> 'form sheet.' In the example above, the user doesn't have permission to
> configure the post's status or anything, so they simply get a heads up that
> their post will need to be reviewed before it's published.
>
> One note, though, on your diagram above: We try to maintain a consistency
> in how posts appear and how they're structured across Map, Timeline, Post
> Detail, and Post Edit views. Reading or editing, they should look very
> familiar. Part of that includes abstracting the post's survey into its
> color "band." And when you focus on a single post, the "mode context"
> (which is the left column on large screens and the top-most bar on small
> screens) displays the survey name.
>
> This is why the survey name is not repeated inside the postcard, editable
> or not. And I think that's still the way to go, unless our users tell us
> it's not working.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1251#issuecomment-228870745>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizaaR4fwP8l0GZja2ASTnzWgU95krkks5qQDc2gaJpZM4I7Rph>
> .
>



-- 
Charlie Harding
Product Director

**Comment by caharding** [comment]
Also we'll need to test the discoverability of tasks, now that they are
buried under the post

On Tue, Jun 28, 2016 at 8:54 AM, Charles Harding <charles@ushahidi.com>
wrote:

> Looks great. Only other thing is that Categories should be a multi-select
> dropdown to save space.
>
> On Mon, Jun 27, 2016 at 1:48 PM, Brandon Rosage <notifications@github.com>
> wrote:
>
>> This structure is significantly improved in the latest layout changes to "Post:
>> Add
>> <http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-add.html>"
>> and "Post: Edit
>> <http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-edit.html>
>> ."
>>
>> *"Post: Add" example:*
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/1136279/16394898/103f83b8-3c7d-11e6-8e62-ff8da85fcd20.png>
>>
>> Configuration, if there is any, is moved into a 'toolbox' outside the
>> 'form sheet.' In the example above, the user doesn't have permission to
>> configure the post's status or anything, so they simply get a heads up that
>> their post will need to be reviewed before it's published.
>>
>> One note, though, on your diagram above: We try to maintain a consistency
>> in how posts appear and how they're structured across Map, Timeline, Post
>> Detail, and Post Edit views. Reading or editing, they should look very
>> familiar. Part of that includes abstracting the post's survey into its
>> color "band." And when you focus on a single post, the "mode context"
>> (which is the left column on large screens and the top-most bar on small
>> screens) displays the survey name.
>>
>> This is why the survey name is not repeated inside the postcard, editable
>> or not. And I think that's still the way to go, unless our users tell us
>> it's not working.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ushahidi/platform/issues/1251#issuecomment-228870745>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ABizaaR4fwP8l0GZja2ASTnzWgU95krkks5qQDc2gaJpZM4I7Rph>
>> .
>>
>
>
>
> --
> Charlie Harding
> Product Director
>



-- 
Charlie Harding
Product Director

**Comment by brandonrosage** [comment]
Agreed, @caharding. Although, the more we position Tasks as something you "assign," the more our users will be clicking through to a post's "Translation" task directly from that task assignment (e.g. Task mode, email notification), which would open the post to that position on its detail view.

Deep-linking to posts' tasks is already supported in the PL.
