### ISSUE TITLE
Invoice must be sent when people are charged

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1255]
### Expected behaviour
I entered my credit card into a Responder account during sign up and expect an invoice to be emailed to me immediately for expensing

### Actual behaviour
No invoice was sent 

### Steps to reproduce the behaviour/error
Sign up for Responder, apply Solutions coupon, no invoice sent

**Comment by jshorland** [comment]
Passes QA multiple multiple times. 
Closing.
