### ISSUE TITLE
Plans settings are not positioned correctly on screen

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1258]
<img width="1280" alt="screen shot 2016-06-21 at 5 02 18 pm" src="https://cloud.githubusercontent.com/assets/1618793/16250419/166ee152-37d2-11e6-980f-28ed47cbe4a0.png">

**Comment by rjmackay** [comment]
Probably just need to trigger the correct layout class using the layout-class directive

**Comment by jasonmule** [comment]
@rjmackay Not sure how this appears to be fixed on .io?

**Comment by rjmackay** [comment]
It probably depends which view you came from.. if we're not setting the layout class it'll just hold the previous value.

**Comment by jshorland** [comment]
Confirmed fixed. Plan settings are correctly laid out.
