### ISSUE TITLE
Mark as Complete toggle button confusing to users

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1262]
**This is for the COMRADES deployment**: http://comrades.ushahidi.com/views/map
Notes came from a training with 7 very tech savvy users. 

### Expected behaviour
Users would submit a report by filling out a form and clicking a button. Users expected options for saving a post that was not complete or submitting a completed post. 

### Actual behaviour
The “Mark as complete” toggle confused several users for two reasons: 
* It's placement at the top of the form/survey implied that they should have already done something.
* Users were confused about the difference between toggling the "Mark as complete" and clicking on "Save". In neither case was it clear that they were *submitting* a post. 

### Steps to reproduce the behaviour/error
Go to any deployment. Do not log in. Add a post. 

### Suggested Changes
Change the "Save" button to read "Submit" since this more accurately reflects what is actually happening. Eliminate the "mark as complete" toggle from the form. I'm not exactly sure what function it fills. If all the field are required and completed, then there's no need for an additional step. If they are not filled out, they are prompted to complete fields. If it is absolutely necessary to keep the toggle, place it at the bottom of the form. 

It may be worth adding the functionality to "save" a post that is in progress.

**Comment by brandonrosage** [comment]
My proposed solution to this rests largely on adding two parameters for each optional Task (e.g. Verification):

* Who can see it.
* Who can edit it.

These configurable parameters would ensure that, if the deployers had no intention for its contributors to the Survey to, say, verify their own posts, they'd never be presented with that part of the Survey form to begin with. But it'd also ensure that the deployers could display that verification information (once completed) to its users in "Post: Detail" -- even if they can't edit it during post creation or editing. _(This is also [discussed in the platform-client repo](https://github.com/ushahidi/platform-client/issues/149#issuecomment-228809927))_

Furthermore, going forward, I'd propose we, A, _not_ have any status governing the individual "Post" Task, and B, scrap the "visibility" parameter for a post in favor of "post status" (discussed in detail on Issue #1263). No more toggle switch. Instead, the posts's overall status (Published, Under Review, or Archived) governs who will see the required "Post" task's data after it's saved.

_Editing a post that you have permission to "Verify" and "Translate":_
![post edit](https://cloud.githubusercontent.com/assets/1136279/16387584/0cdd272e-3c5b-11e6-9e18-92604e760401.png)

By extension -- and in support of @Shadrock's suggestion -- if a user was adding a new post to a Survey that required new posts be reviewed before they're published (and the current user didn't have permission to review), the primary action button for the page would read "Submit."

**Comment by Shadrock** [comment]
I read this before Issue #1263, but this is helping me understand that logic even better and I think you're on the right path with this. Thanks for the thorough explanations.

**Comment by rjmackay** [comment]
@brandonrosage Looking at the mocks. Where is the "Who can edit it" for tasks?
We have "Show this task to everyone when the post is published" .. and "Require this task be completed before a post can be published". But I don't see how I would define who can complete a task?

**Comment by brandonrosage** [comment]
@rjmackay Thanks for asking about this. I had thought this through, but I think I arrived at the wrong conclusion. I revisited this this morning, and here's where I landed:

We're careful (and conservative) about how much role-specific configuration we do on a survey-by-survey basis. That's part of the fallout of the "Post Status" decision -- not adding permissions to every last thing.

That said, task completion is a very role-specific type of work. So, setting aside the full layer of "assignment" functionality that will come with a full-blown "Tasks" mode, tasks should have a wall around them, defining who can even complete them.

So, for any given **survey**, here's the role-specific configuration you can do:

* Who can add to this survey
* Who can edit posts to this survey
* Who can complete Task A
* Who can complete Task B

You can see all of these controls in the following screen:

![edit survey](https://cloud.githubusercontent.com/assets/1136279/16624813/d2d5f7e0-4367-11e6-8f66-ef29ca1f175b.png)
