### ISSUE TITLE
Batch approval for posts?

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1264]
**This is for the COMRADES deployment**: http://comrades.ushahidi.com/views/map
Notes come from a training with 7 very tech savvy users. 

### Expected behaviour
Users expected to be able to batch approve posts (e.g. posts from a source that had proven to be reliable).

### Actual behaviour
Users were unable to find a way to batch approve posts. They did like the batch Delete and Add to Collection option in the Timeline view and requested something similar for approvals. 

### Steps to reproduce the behaviour/error
Log in to a deployment. Attempt to batch approve posts.

**Comment by rjmackay** [comment]
I think this is covered by other tasks in Sprint 8. Lets review after that.
