### ISSUE TITLE
Incorrect placement of map icon at certain scale/zoom level

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1267]
**This is for the COMRADES deployment**: http://comrades.ushahidi.com/views/map
Notes come from a training with 7 very tech savvy users. 

### Expected behaviour
Map icon for an individual post (that is _not_ combined with other posts) will remain the same despite the scale (zoom level) at which the post is viewed. 
### Actual behaviour
When viewing the map, _after logging in_ the location of map icon for a specific post changes depending on the zoom level at which it is viewed. This _does not_ seem to happen when user is not logged in. 
### Steps to reproduce the behaviour/error
* Go to http://comrades.ushahidi.com/views/map
* Logon as Jess: 
 * email = jess@ushahidi.com
 * Password = jess123
* Note placement of the map icon for the post in South Africa, which appears to be in the ocean
![comrads misplaced map marker](https://cloud.githubusercontent.com/assets/4574998/16285042/610f96ec-3891-11e6-832c-de003ed1233f.png)
* Zoom in or out of map view and notice map icon jump to correct location. 
* Behaviour can be replicated by refreshing the browser to the original map view.

**Comment by rjmackay** [comment]
This might be fixed on https://comrades.ushahidi.io .. Would it be ok if I redirect comrades.ushahidi.com back to .io?

**Comment by Shadrock** [comment]
@rjmackay that would be fine for me, assuming there's no noticeable change for the user. Really appreciate you guys helping me set all that up.

**Comment by rjmackay** [comment]
Alright. That should redirect now. Let me know if that hasn't fixed this issue.
