### ISSUE TITLE
when i add a single text field to the post - it asks for lat + long

### ISSUE THREAD

**Issue by joemellin** [ushahidi/platform#1271]
### Expected behavior
showing up the text i right
### Actual behaviour
<img width="631" alt="screen shot 2016-06-25 at 5 01 14 pm" src="https://cloud.githubusercontent.com/assets/1232282/16359758/bd3180ea-3af6-11e6-98ea-31bff372bc35.png">
### Steps to reproduce the behaviour/error
add a sentence field to a post and then just put text in it when you create a point on the map

**Comment by rjmackay** [comment]
@joemellin thanks for the bug report. Our dev team will look into it

**Comment by jshorland** [comment]
Another user (mapworks learning, narrativeatlas.ushahidi.io) also submitted the same issue: I am modifying the "survey" and keep getting this error when trying to submit a story.
Have created a field called "Submit a story"  this is a long text field and story title is a short text field.

Validation Error

values.share-your-story must be an array of lat and lon

**Comment by jasonmule** [comment]
Possibly related to #1273 but I can't reproduce this with master at the moment.

**Comment by jshorland** [comment]
I can't replicate this error. At all. Did someone fix? or is it just... gone.

**Comment by rjmackay** [comment]
Fixed
