### ISSUE TITLE
Decimal number validation of custom fields seems to be broken

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1273]
### Expected behaviour
When adding a custom field of decimal type and creating a post where it has a value like "9.21", the value should be accepted.

### Actual behaviour
Decimal values are rejected with the message: "values.<field-name> must be an array of lat and lon"

### Steps to reproduce the behaviour/error
Create custom field, supply values when creating/editing posts

@rjmackay this was working fine (even if it was just a bit too restrictive because it enforced exactly two digits after the decimal point). Apparently it broke after a recent commit to master.

**Comment by jasonmule** [comment]
@tuxpiper I can't reproduce this.  Could you check again?

**Comment by tuxpiper** [comment]
@jasonmule Still getting it, but when I use comma (,) instead of (.) as a separator, this works. Meaning "9,21" is accepted, but "9.21" gives me a validation error.  Is this user locale dependent? It was definitely working with the dot separator before.

Also, I've experimented with a date-time field, and I can't get that to work now either. Getting the error " values.new-date--time-field must be an array of lat and lon" . It's the only custom field in the form.

**Comment by willdoran** [comment]
@tuxpiper I can't reproduce this either though I did notice that our error message is a unhelpful for the decimal when it works correctly so I'll update that. Is there anything in your application/logs/2016/06/ directory? 

If you try to trigger an error on a field, you always get the "values. must be an array of lat and lon"? Do you have a point field on that same post?
