### ISSUE TITLE
CSV imports fail with 500 from api/v3/csv/{num}/import

### ISSUE THREAD

**Issue by citizenkepler** [ushahidi/platform#1279]
### Expected behavior

I would expect for my data to be imported, or if it can't be imported present an error to the user explaining the problem or at least there was a server side problem. 

### Actual behavior

The data is not being imported, and the user is presented with an error banner that does not contain any text.

![screen shot 2016-06-29 at 12 45 12 pm](https://cloud.githubusercontent.com/assets/4239131/16466881/b37c8ce2-3df9-11e6-970c-e18407e62116.jpg)

### Steps to reproduce the behavior/error

Platform-client version 3.2.1 

1) Create CSV from the sample data from https://wiki.ushahidi.com/display/WIKI/CSV+Upload+Guide
2) Goto Settings CSV Import and select any post type and upload the CSV
3) Map Title to Title, and Description to Description. Also map values to any required fields for that post type.
4) Import
5) Observe Method "Options" request to an URL such as http://DOMAIN/api/v3/csv/10/import, sucessfull with a 200 with reply
{
"allowed_privileges": [
"read",
"create",
"search"
]
}
6) Observe Method "POST" request to http://DOMAIN/api/v3/csv/10/import fail with status code 500
7) In the logs (platform/application/logs/YYYY/MM/DD.php) notice an error similar to
EMERGENCY: ErrorException [ 2 ]: The use statement with non-compound name 'ArrayIterator' has no effect ~ APPPATH/classes/Ushahidi/FileReader/CSV.php [ 12 ] in /home/grass/map/platform/vendor/kohana/core/classes/Kohana/Core.php:511

**Comment by rjmackay** [comment]
@citizenkepler have you tried with a more recent version of the platform? I think there are fixes in v3.3 and v3.4

The CSV guide on the wiki is for v2, the docs for v3 are here: https://www.ushahidi.com/support/data-import

**Comment by citizenkepler** [comment]
Hello @rjmackay ,

I have updated the platform (because of the mapquest direct tile issue, and needing to switch to open streets) and I continue to have this issue. I am upto date on master, currently.  

Thanks for looking into this.

**Comment by willdoran** [comment]
@citizenkepler, sorry for delay, I am trying to reproduce this issue, would you be able to share an example of a CSV which is failing for you?

**Comment by rjmackay** [comment]
I'm going to close this and reopen if we strike this again.
