### ISSUE TITLE
Feature: Replace "visible to" with Published/Under review/Archived

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1281]
Changes:
- [x] Update post status display with new icons/text 
- [x] Update post filters to filter by status, not visible to
- [x] Update post edit with control to set status, remove visibility control
- [x] Add "Mark as" dropdown to timeline bulk actions (excluding spam/duplicate)
- [x] Update post actions dropdown to add Put under review/archive/publish options
- [x] Update post detail and post edit layouts
- [x] API: Add "archived" status
- [x] API: Migrate posts already published to specific roles??
  - Run data to see how many this is. 
  - Possibly push all these posts back into draft and add to a collection for admin review.

Background: https://github.com/ushahidi/platform/issues/1263#issuecomment-228464926

----

The idea is basically this: From a user-facing point of view, let's scrap "Who can see this," and instead double down on "Post status." A post that's saved within a deployment is either:

* Published
* Under review
* Archived

Any user needs around the fine-tuned visibility of posts will therefore have to be constrained to Role configuration. This effects, well, a lot of screens. But here's the jist of it:

## Postcards
Anywhere you see a postcard (including as [a map popup](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/map.html), in [the Timeline](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/timeline.html), and [post detail](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-detail.html)), you'll see a consistent email-like treatment of its "status."

Example:
![postcards](https://cloud.githubusercontent.com/assets/1136279/16350397/2018537e-3a24-11e6-889a-a638fa580aff.png)

In the top-left of the postcard, a status indicator is displayed with one of the three status icons. If it's "Under review," it glows yellow (similar to an "unread" indicator), suggesting it requires attention. Otherwise, it's a subtle icon.

If you mouseover it, a short description of the status appears:

![mouseover](https://cloud.githubusercontent.com/assets/1136279/16350516/ae0da940-3a24-11e6-92a0-135f36e6ac63.png)

You can, of course, change a post's status when you edit it. But you can also change its status from:

1. The listing toolbar:
![listing toolbar](https://cloud.githubusercontent.com/assets/1136279/16350541/e42e8274-3a24-11e6-963a-2b316a92309a.png)

2. The post's actions dropdown:
![actions dropdown](https://cloud.githubusercontent.com/assets/1136279/16350552/03f0b2c6-3a25-11e6-89ef-36870917cc8b.png)

The status-related actions available correspond to the post's current status.

## [Map](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/map.html) & [Timeline](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/timeline.html)

The tools we provide for mashing up the data you're looking are naturally affected by this. 
 the toolbar's more exhaustive "Filters" control also includes this feature:

![searchbar](https://cloud.githubusercontent.com/assets/1136279/16350664/be221464-3a25-11e6-8a6a-d94510290801.png)

## [Post edit](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-edit.html)

The example I've staged also assumes the user can edit the post time (and author). But you can see there's a very visible control there for changing the post's status:

![post edit](https://cloud.githubusercontent.com/assets/1136279/16395357/03a0e94c-3c7f-11e6-9927-fc23d7c31402.png)

**Comment by rjmackay** [comment]
@brandonrosage @jshorland what should the default status filter be? show everything? or just published? or published+under review?

**Comment by rjmackay** [comment]
Running stats on number of posts published with custom 'published_to' values.

**Comment by rjmackay** [comment]
@jshorland this is deployed to ushahididev.com - can you test there? it covers a lot of areas of the UI

To test:
- [ ] Post status display matches PL on timeline
- [ ] Post status display matches PL on map
- [ ] Post status display matches PL on post detail
- [ ] Filter by status works
- [ ] post edit set status control works
- [ ] Bulk actions "mark as under review, archived, published" works
- [ ] Individual post actions dropdown  "Put under review/archive/publish" works
- [ ] Post edit sidebar shows created/updated dates

**Comment by jshorland** [comment]
@rjmackay what link to the PL am I using? http://preview.ushahidi.com/platform-pattern-library/master/assets/html/5_layouts/timeline.html this is wrong.

**Comment by jshorland** [comment]
QA FAILED.
QA'd on qa.ushahididev.com, u: jess@ushahidi.com, p: password. testing while logged in as ADMIN.

Filter by status:
- there's some weird behavior here. When I uncheck all three statuses (stati?), there are still posts on the map as well as on list. Is this the way it's supposed to behave?

Bulk actions:
- when I select all on timeline mode and mark all as "under review", they disappear and timeline mode tells me there are no posts in the deployment yet. I then navigated to the map and all the posts were gone, but the post count numbers are still there. I'm logged in as an admin while testing.
- when I select all on timeline mode and mark all as "archived", they appear to change to the published indicator icon instead of archived icon.

Post edit sidebar shows created/updated dates:
- I couldn't test this because I couldn't access any of my posts after bulk action changing them to under review. where did they go?

**Comment by jshorland** [comment]
Assigning back to you, @rjmackay -- failed QA.

**Comment by rjmackay** [comment]
> there's some weird behavior here. When I uncheck all three statuses (stati?), there are still posts on the map as well as on list. Is this the way it's supposed to behave?

With all of our filters, no filter = return anything. The UI doesn't really match this but I'm not sure what it *should* do. Returning an empty list is pointless..

I'll investigate other issues.

**Comment by rjmackay** [comment]
@jshorland can you put these back into "In Development" column when they fail QA?

**Comment by rjmackay** [comment]
> when I select all on timeline mode and mark all as "under review", they disappear and timeline mode tells me there are no posts in the deployment yet. I then navigated to the map and all the posts were gone, but the post count numbers are still there. I'm logged in as an admin while testing.

I can't reproduce this. We refresh the listing after a 'mark all' but its working fine for me.

> when I select all on timeline mode and mark all as "archived", they appear to change to the published indicator icon instead of archived icon.

Can't reproduce this at all

**Comment by rjmackay** [comment]
I'm not 100% clear: who can see archived posts? I'm going to assume *everyone* but we can fix that later if that wasn't desired. @brandonrosage @jshorland

**Comment by brandonrosage** [comment]
@rjmackay My intent is for “Archived” posts’ visibility to be identical to that of posts that are “Under Review.” 

If nothing else, this keeps things simple.

Until we learn of a user need to expose “Archived” posts publicly, I think we should treat them as posts the deployer explicitly wants to “retire” from the outward-facing dataset, without being forced to either delete or demote them back to “Under Review."

**Comment by jshorland** [comment]
Passes QA! Moving to done.
