### ISSUE TITLE
Feature: Add require approval and who can edit controls on surveys settings

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1282]
Changes:
- [x] Add toggle for 'require posts be reviewed before they're published' to survey settings
- [x] Add control for 'who can add to this survey' to survey settings
- [x] API: Add `require_approval` field to Form entity
- [x] API: Add `createable_by` field to Form entity (ie. which roles can add to a survey)

Background: 
https://github.com/ushahidi/platform/issues/1263#issuecomment-228464926
https://github.com/ushahidi/platform/issues/1262#issuecomment-228815980

---

## [Survey settings](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-survey-edit.html)

Part of a survey's definition is who can add posts to it and whether posts requires review before they're published:

![survey settings](https://cloud.githubusercontent.com/assets/1136279/16395394/3b003582-3c7f-11e6-84a7-c530a5e6eab1.png)

**Comment by zhalloran** [comment]
@rjmackay I'd prefer to set the default value for require_approval to false, but...for existing deployments, the default is to require approval (status => draft in posts). Any preference for how to approach this?

**Comment by zhalloran** [comment]
@rjmackay @brandonrosage For who can add to a survey the example has the logged in user, Everyone, or Specific Roles as options. Do we intend to allow the ability to select individual users as well? Also, do we have screens for the role selection action?

**Comment by rjmackay** [comment]
My take is that require_approval should default to `true`. Because thats what we already have and I think also whats expected. I worry we surprise deployers otherwise by letter anonymous posts go public without review.
@jshorland any thought?

Who can add to a survey should only allow roles, not users to be selected. You can look at http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/settings-survey-edit.html to see how the UI should work.

**Comment by zhalloran** [comment]
@rjmackay Perfect. I must have been looking in the wrong branch for the layout. Which branch is this?

**Comment by rjmackay** [comment]
Ah right. We're just sorting out branches in the PL.. there's a `master` and `develop` branch now. This is still in `develop`.

**Comment by rjmackay** [comment]
From discussion with @jshorland. The UI has updated slightly to include a ‘who can edit posts in this survey’ too. But for this iteration we can continue with just the ‘who can add to this survey’ control for this iteration and add who can edit later (probably along with changes to tasks). Make sense?

**Comment by zhalloran** [comment]
@rjmackay Outstanding issues for this ticket:

- Need to complete tests. Test environment is a bit of a mess due to permissions issues. We should tie the tests MySQL creds to the creds for the deployment, maybe?
- Want to return the results of the index collection form GET /forms/:form_id/roles when calling POST or PUT /forms/:form_id/roles

**Comment by zhalloran** [comment]
One last outstanding issue. Want to remove `roles` from the form_role entity when returned via API.

**Comment by zhalloran** [comment]
@rjmackay @brandonrosage I'm working on the Client component for this issue. One question I have: how do we want to handle the case were a user doesn't have permission to add to a survey? Do we also remove their right to see the survey completely (i.e. do we remove their permission to read that survey at the API level)? Or, do we allow them to see that form in lists, but somehow indicate that it's restricted? Or is there something else we should be doing?

**Comment by zhalloran** [comment]
Outstanding issue: Add auto-publish to post creation for surveys that don't require approval.

**Comment by rjmackay** [comment]
> @rjmackay @brandonrosage I'm working on the Client component for this issue. One question I have: how do we want to handle the case were a user doesn't have permission to add to a survey? Do we also remove their right to see the survey completely (i.e. do we remove their permission to read that survey at the API level)? Or, do we allow them to see that form in lists, but somehow indicate that it's restricted? Or is there something else we should be doing?

A user who doesn't have permission to add to a survey still has permission to see posts that are in that survey. So it follows that they need to see that survey in various lists in the client. However they _shouldn't_ see it in the list under the add post button.

<img width="323" alt="screenshot 2016-08-09 15 23 03" src="https://cloud.githubusercontent.com/assets/7965/17503631/7b4881de-5e45-11e6-8193-7dfbabe7d082.png">

Similarly we should hide the 'Add to [Survey]' button in the survey context menus.

**Comment by zhalloran** [comment]
@rjmackay What do you think about adding the survey permissions to the session data in the $rootscope of the client?

**Comment by rjmackay** [comment]
@zhalloran better to avoid adding things to rootScope. Better would be to isolate whatever permissions checks are needed to a service. Also if you just need to cache the forms roles data somewhere the endpoints mostly do that using angularCache.

**Comment by rjmackay** [comment]
I may not be on for long tomorrow. Ping @willdoran if you need more feedback on the client approach.

**Comment by zhalloran** [comment]
@willdoran @rjmackay One other question I forgot: What role do we want to assign to unauthenticated users? My first thought is to assign them the User role in terms of permissions?

**Comment by zhalloran** [comment]
@willdoran @rjmackay What do you think about adding an array of role names to the to the form entity in the API? It would make managing access to add to a survey in the client very clean.

**Comment by rjmackay** [comment]
> @willdoran @rjmackay One other question I forgot: What role do we want to assign to unauthenticated users? My first thought is to assign them the User role in terms of permissions?

I would say they shouldn't have a role. Which probably means the survey needs to be available to `everyone` before they can add to it. 

> What do you think about adding an array of role names to the to the form entity in the API? It would make managing access to add to a survey in the client very clean.
Yes please.

**Comment by zhalloran** [comment]
Hah! I just came to that conclusion myself. Thanks!


On August 9, 2016 at 12:34:48 PM, Robbie Mackay (notifications@github.com)
wrote:

@willdoran <https://github.com/willdoran> @rjmackay
<https://github.com/rjmackay> One other question I forgot: What role do we
want to assign to unauthenticated users? My first thought is to assign them
the User role in terms of permissions?

I would say they shouldn't have a role. Which probably means the survey
needs to be available to everyone before they can add to it.

What do you think about adding an array of role names to the to the form
entity in the API? It would make managing access to add to a survey in the
client very clean.
Yes please.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ushahidi/platform/issues/1282#issuecomment-238665623>,
or mute the thread
