### ISSUE TITLE
Feature: Distinguish between post fields and task fields

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1283]
Changes
- [x] API: Mark "Post" stage as special (maybe `type: post` vs `type: task`)
  - Post stage doesn't have complete/not completed
- [x] API: Add description and visibility for stages
- [x] Split post fields and task fields in survey settings
- [x] Split post fields and task fields in post edit
- [x] Split post fields and task field in post detail
- [x] Remove 'completed' toggle from "Post"
- [ ] API: Add `is_public` field to post stages
- [ ] Add "Show this task to everyone when the post is published" to task settings
- Out of scope: Add display logic for "Show this task to everyone when the post is published"
- Out of scope: "ASSIGN THIS TASK TO..." dropdown

Background: 
https://github.com/ushahidi/platform-client/issues/149#issuecomment-228809927
https://github.com/ushahidi/platform/issues/1262#issuecomment-228815980
https://github.com/ushahidi/platform/issues/1263#issuecomment-228464926
https://github.com/ushahidi/platform/issues/1237#issuecomment-228863359
https://github.com/ushahidi/platform/issues/1237#issuecomment-230039121
https://github.com/ushahidi/platform-client/issues/147

---

**Comment by willdoran** [comment]
Test these changes by on ushahidev:
- Survey Edit
- [ ] Add Post fields
- [ ] Add Tasks
- [ ] Add fields to Task
- [ ] Set "Require this task be completed before a post can be visible to the public"
- [ ] Save survey
- Post Edit/Detail
- [ ] Create Post from Survey with No Tasks - tasks tabs should not be displayed
- [ ] Create Post from Survey with Tasks - task tabs should be displayed
- [ ] Save Post with title and description only - task tabs should not be displayed in Post Detail
- [ ] Edit Post, add values to Task fields - task tabs and values should be displayed in Post Detail
- [ ] Edit Post, with Task where "Require this task be completed before a post can be visible to the public", do not mark Task completed, attempt to save

**Comment by jshorland** [comment]
- Add posts fields has a small design flaw. I'm going to pass the adding of fields, and have opened #1353
- Create post from survey with tasks (tasks show): Failed. I can add the tasks in the survey edit mode, but when I add a post to the survey and save, it takes me to a screen that for some reason only shows the first and last task. I tried typing a really long task name to see what happened, but it looks like there's a scroll bar on tasks, so I don't think that would be the cause. Screenshot attached. However, when I completed the tasks in edit mode and returned to the post detail mode, I saw all of them.

**Comment by jshorland** [comment]
Its now working for me. All pass QA

**Comment by rjmackay** [comment]
@willdoran was `is_public` and "Show this task to everyone when the post is published" implemented as part of this? I know we talked about splitting this while at team meeting. However if we haven't captured that task somewhere else this issue shouldn't be closed yet.
