### ISSUE TITLE
Feature: Change the way we validate posts

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1284]
Depends on  #1283

Current validation
- `Post fields` are only validated the same other tasks.
- Only `complete` stages are validated
- Only enforces validation when post status = published 

ie. validation is a combination of: 
- Is this post published?
- Is this stage completed?
- Is this field valid?

Changes
- [x] Required fields on "post" stage are always validated
- [x] Required fields on tasks are only validated when it is complete?
- [x] Update field validation logic in client: Always validate post fields, only validate task fields when completed. Post status has no impact on validation.
- [x] API: Update post validator
- [x] API: post status should have no impact on validation

Background: 
https://github.com/ushahidi/platform-client/issues/147
https://github.com/ushahidi/platform/issues/1188

**Comment by willdoran** [comment]
Test these changes by on ushahididev:
- Validation
- [ ] Required fields for Post task should always be validated
- [ ] Required fields for a task should only be validated when the task is marked complete
- [ ] It should not be possible to save a post unless all required fields have been filled
- [ ] It should not be possible to publish a post unless required tasks have been marked completed

**Comment by jshorland** [comment]
1. Required fields for post task are not always validated -- fail
2. required fields for a task aren't validated (or are wonky), so i'm not sure if it only validates when task is marked com[lete or not -- fail.
3. i saved a post without all required fields being filled. Fail
4. I was able to click publish on post and i received a message that said "saved post". No indicator that the post was published or not. Fail.
