### ISSUE TITLE
Feature: Embed map

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1285]
- Implement [Map embed view](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/map-embed.html)

**Comment by jshorland** [comment]
related: #474

**Comment by jshorland** [comment]
He's found a way to embed only the survey forms, but also wants a way to embed only the map. Originally wanted to embed the whole site, now only specific objects.

See intercom conversation here: https://app.intercom.io/a/apps/hl5rfiga/inbox/all/conversations/5409633811

Is this possible at this point without significant dev work? @rjmackay @tuxpiper?

**Comment by jshorland** [comment]
Closing in favor of #1387 cc: @brandonrosage
