### ISSUE TITLE
Improve post 'photo' field

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1288]
For posts belonging to a survey with a "Photo' field...

### Expected behaviour
When there's no photo attached to the post, I'd expect there to be an intuitive button "Add photo" (with no caption input):

![add photo](https://cloud.githubusercontent.com/assets/1136279/16631345/48079246-4384-11e6-8114-ede8c2e78891.png)

And when there **_is_** a photo attached to the post, I'd expect the photo to be displayed with appended buttons to "Delete" or "Replace image," and a text input for an optional caption:

![edit photo](https://cloud.githubusercontent.com/assets/1136279/16631313/2721838e-4384-11e6-9cc4-b82cc2e688ee.png)

### Actual behaviour
When there's no photo attached to the post, there's a semi-confusing, default "Choose file" input and a text input for a caption:

![add photo](https://cloud.githubusercontent.com/assets/1136279/16631401/97f40244-4384-11e6-8018-1008478a28e1.png)

And when there **_is_** a photo attached to the post, there's a text link ("Current image"), no image, the default file input (with no clear indication if I'm adding a second photo or replacing the existing one), and a caption text input:

![edit photo](https://cloud.githubusercontent.com/assets/1136279/16631478/f0545664-4384-11e6-834e-698019de357e.png)

### Steps to reproduce the behaviour/error
Add or edit any post belonging to a survey with a "Photo' field.

### Suggested solution
Demonstrated in the Pattern Library's "[Post: Add](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-add.html)" and "[Post: Edit](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-edit.html)" layouts.

**Comment by rjmackay** [comment]
@middle8media any progress on this? do you need dev support on it?

**Comment by middle8media** [comment]
Working on this today. I will keep you posted and reach out as needed.

**Comment by middle8media** [comment]
I have pushed an initial pass at this [here](911f30229b37844463183c693a4799a1a932ca6b). It is not complete, only partially functional.

I have a few suggestions that would require additional functionality.

### Post Add
- display the image after the upload button is clicked and before the save button is clicked, this provides visual feedback to the user that the image was actually uploaded.
- hide the upload button after the image is actually uploaded and before the image is saved
- provide the ability to replace and delete the image before actually saving and have the image reflect both the replacement and deletion.

### Post Edit
- provide the ability to replace and delete the image and have image reflect both the replacement and deletion

**Comment by rjmackay** [comment]
> hide the upload button after the image is actually uploaded and before the image is saved

I'm not clear what the difference between uploaded and saved is here?

Would it work to book some peer programming time with myself or @willdoran to work on this? 
I think most of what you need to display the image should exist so we'll just need to point you at the right data in JS :)

**Comment by middle8media** [comment]
The way I understand it ...

upload actually uploads the image but does not display it.
save does just that, saves the image into the app.

I will reach out to Will for pair coding.

**Comment by jshorland** [comment]
Related #1434

**Comment by willdoran** [comment]
I'm closing this in favour of #1434 as it covers the same criteria.
