### ISSUE TITLE
Post "bundles" don't correspond to Post type colors

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1294]
### Expected behaviour

The bundles of posts have similar colors to the Post types, but they don't correspond. This makes it very difficult to get a quick visual look at what are the most common types of posts in a geographic region. 
### Actual behaviour

Posts are not bundled together by type, and assigned a random color
### Steps to reproduce the behaviour/error

Check out the quakemap site

<img width="797" alt="screen shot 2016-07-18 at 12 11 34 pm" src="https://cloud.githubusercontent.com/assets/1618793/16927190/1bee1c46-4ce1-11e6-9d30-8d783d25e9cc.png">

**Comment by jshorland** [comment]
duplicate. closing.
