### ISSUE TITLE
Can we collapse "Sign Up" into "Login" on the mode bar

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1296]
### Expected behaviour

I would expect that Sign Up would be an option within "Login"
### Actual behaviour

We have two large icons which take up a bunch of screen real estate

**Comment by rjmackay** [comment]
@jshorland I'd normally assign this to @brandonrosage for consideration .. however I'm aware this doesn't reflect any thought on priority or capacity to continue this. Do you want to just icebox this until  we pull it into a sprint for design review?

**Comment by brandonrosage** [comment]
In the event we choose to implement this change, I've staged a solution. It doesn't change the design system -- just the UX that's staged in the PL.

When logged out, the mode bar now displays Collections, Log in, and Ushahidi Support:

![mode bar](https://cloud.githubusercontent.com/assets/1136279/17604447/80cfaf6e-5fdb-11e6-87c2-64cc2043e9b9.png)

Upon selecting "Log in," the modal displays only an email input:

![log in](https://cloud.githubusercontent.com/assets/1136279/17604508/b7d731e4-5fdb-11e6-9d4f-5d6db311a80e.png)

Upon entering a valid email address, the "Next" button will be 'enabled.' Selecting it will check the deployment for an existing user with that address. 

If it finds an existing user, you're offered a second modal for entering their password:

![password](https://cloud.githubusercontent.com/assets/1136279/17604665/6351ab8a-5fdc-11e6-81cf-5574e0152197.png)

If it doesn't find an existing user, you're offered a second modal with the fields necessary to "Sign up," with the email field pre-populated with the address you've already provided:

![sign up](https://cloud.githubusercontent.com/assets/1136279/17604641/49e7906a-5fdc-11e6-821a-eb70a4e595bd.png)

**Comment by rjmackay** [comment]
I think this would confuse me if I were looking to sign up. There's now no visible link to sign up.. I just have to stumble through login to discover it.
