### ISSUE TITLE
Responder xenowatch.ushahidi.io loses incident date when editing posts after CSV import

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1298]
### Expected behaviour
Incident date of the original report (exported from crowdmap) stays the same 

### Actual behaviour
After CSV import, user edits post and loses the original incident date. Waiting for more details, including screenshot. Not sure if this is date picker or importer right now.

### Steps to reproduce the behaviour/error
Waiting for user to respond (xenowatch.ushahidi.io)

**Comment by rjmackay** [comment]
This is an issue with ALL date fields. We lose the existing value when editing
