### ISSUE TITLE
User request: reorder surveys

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1299]
User wants to re-order surveys on home page, rather than the default newest --> oldest. 

Mechanism could be similar to re-ordering fields in a survey.

**Comment by jshorland** [comment]
A second user requested this as well. Adviceni.ushahidi.io

**Comment by tuxpiper** [comment]
@jshorland another request for this from appi.ushahidi.io

**Comment by justinscherer** [comment]
@jrtricafort @caharding this will get handled in the [UI refresh.](https://app.zenhub.com/workspace/o/ushahidi/platform-pattern-library/issues/205)

**Comment by rowasc** [comment]
Closing as this is planned as a part of the UI Refresh

**Comment by Erioldoesdesign** [comment]
This is another piece that get's solved through Seth's magic move interaction thing! It's right at the bottom of this page: http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/2_fragments/
