### ISSUE TITLE
appi.ushahidi.io post pop ups don't work on map

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1300]
### Expected behaviour
I click on a pin on the map
Post summary box pops up in appropriate location in a timely manner

### Actual behaviour
clicking on pins after loading for the first time doesn't initiate any pop up
moving map around, or zooming in on cluster of posts, then clicking on individual pin brings up a summary box, but it's in weird locations and I can't see it.

This DOESN'T happen on the user's other .io deployment, iamnirbhaya.ushahidi.io

### Steps to reproduce the behaviour/error
1. navigate to appi.ushahidi.io
2. click on any individual map marker
3. zoom in to cluster of posts
4. click on individual map marker after zooming in. 

intercom conversation here: https://app.intercom.io/a/apps/hl5rfiga/inbox/all/conversations/5288138674

**Comment by willdoran** [comment]
I think the issue may be related to https and this warning:

Mixed Content: The page at 'https://appi.ushahidi.io/views/map' was loaded over HTTPS, but requested an insecure image 'http://www.gravatar.com/avatar/00000000000000000000000000000000?d=retro'. This content should also be served over HTTPS.
