### ISSUE TITLE
Surveyor izwi.ushahidi.io baselayer is wrong on Twitter posts and new posts

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1302]
### Expected behaviour
Changed default baselayer to street. On post form via twitter and new posts, the map to add location should show default baselayer as street.

### Actual behaviour
The map on the add post form shows as satellite

**Comment by jshorland** [comment]
https://app.intercom.io/a/apps/hl5rfiga/users/5762a5a819f2d02b0f00045a/all-conversations

**Comment by rjmackay** [comment]
Note that to test this you should try both
1. loading https://izwi.ushahidi.io/posts/create/3 directly
and
1. Load the homepage
2. Click on (+) then select a survey

**Comment by jshorland** [comment]
Test 1 going directly to link: passes QA
Test 2 going to homepage, select add to survey through (+): passes QA

**Comment by rjmackay** [comment]
Sorry - did this not get resolved? last comment said it passed QA? If this is a new bug, could we open a new issue?

**Comment by rjmackay** [comment]
@jshorland once you can provide more info, please grab other dev's as needed to resolve this. Don't wait for me to wake up :)

**Comment by jshorland** [comment]
Ok closing this and adding a new issue -- sorry about that.

**Comment by jshorland** [comment]
New issue: #1310
