### ISSUE TITLE
Surveyor izwi.ushahidi.io can't edit Twitter posts properly

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1304]
### Actual behaviour
Twitter is configured correctly and posts are successfully being pulled into the platform, but when she goes to edit them and gets the screen shot attached. 

### Steps to reproduce the behaviour/error
![screenshot 20- 20twitter 20post](https://cloud.githubusercontent.com/assets/3224856/17029119/cfb0a214-4f1e-11e6-8743-3f8427c1d6fa.jpg)

**Comment by rjmackay** [comment]
It looks like they hit a JS error - I've justed test with a twitter message on their deployment but I couldn't reproduce this though :/

**Comment by rjmackay** [comment]
I'm going to add some error logging to production and we'll just have to ask them to let us know as soon as this happens again.

**Comment by jshorland** [comment]
She's still running into an issue:

Mark as complete: Twitter posts still can't be marked as complete, but can be saved to be visible to everyone; for new posts, I still can't save - the mark as complete works on the "verify" step but not on the "post" step.

**Comment by rjmackay** [comment]
This should be fixed. There were validation issues with dates and datetime fields. They will need to add a post title before completing the stage though

**Comment by jshorland** [comment]
Is this pushed? because she said this is fixed.

**Comment by jshorland** [comment]
This is confirmed fixed by the user.
