### ISSUE TITLE
Responder xenowatch.ushahidi.io can't integrate Frontline SMS

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1305]
Using clickatell with FrontlineSMS. Says he only has API key, not a URL as our current integration requires.

**Comment by rjmackay** [comment]
What version of FrontlineSMS are they using? is it local or cloud hosted?
Could we connect direct to clickatell instead?

**Comment by jshorland** [comment]
checking on versioning -- he's in EAT so I suspect it'll be a few hours before response.

**Comment by jshorland** [comment]
They are running the cloud version of Frontline SMS. Do you need other details about this?

**Comment by rjmackay** [comment]
Not sure yet. This might be a good one for @jasonmule or @willdoran to look into too.

We might need to hit up frontline for a test account.. there are also other related github issue to this somewhere..

**Comment by willdoran** [comment]
I messaged them through their site, but is there a direct contact I can ping?

**Comment by willdoran** [comment]
Based on their docs it does look like their api support has changed so we might need to change accordingly.

**Comment by jshorland** [comment]
https://app.intercom.io/a/apps/hl5rfiga/inbox/all/conversations/5409633811

**Comment by rjmackay** [comment]
@willdoran take a look at notes on https://github.com/ushahidi/platform/issues/836 .. note: the creator of that issue works for frontline.

**Comment by willdoran** [comment]
@rjmackay @jshorland  ok, cool, then we will need to update our side to support their api. I have not heard back from the messages I sent FontlineSMS. Should I proceed and start to change our api integration?

**Comment by willdoran** [comment]
FrontlineSMS very kindly got back to me and they said the free tier should work for integration testing but they can upgrade us if we need, they asked for an example payload of what we're sending. Do we want to progress and update ourside to work with their cloud system?

**Comment by willdoran** [comment]
Additionally their docs cover this integration for Ushahidi
https://frontlinecloud.zendesk.com/hc/en-us/articles/208116073-How-can-I-integrate-FrontlineSMS-with-Ushahidi 
which references our 2.x docs

**Comment by rjmackay** [comment]
@willdoran where is this at / whats waiting?

> Do we want to progress and update ourside to work with their cloud system?

Definitely, but I think I already answered this outside of github.

**Comment by rjmackay** [comment]
Deployed to production.
