### ISSUE TITLE
Import categories from CSV

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1308]
- We need to make sure users can map a CSV column to categories

Similar issue https://github.com/ushahidi/platform-client-1000ocean/issues/3
Requested by xenowatch.ushahidi.io (responder user)

**Comment by willdoran** [comment]
@rjmackay did you say there was additional info for this issue?

**Comment by willdoran** [comment]
@jshorland I'm not 100% clear on the goal, are we creating the following:
- [ ] Allow mapping of columns to categories - if yes, can we dictate the format of the columns
- [ ] Create a very basic configuration step that allows setting of categories for imported posts

**Comment by rjmackay** [comment]
The 1000ocean project needs to map CSV columns to categories.
At some point we need to reinstate the 'configure posts' step which allowed setting categories for all posts, thats probably not necessary for this task.

**Comment by tuxpiper** [comment]
This was addressed for a project in https://github.com/ushahidi/platform-client-1000ocean/commit/d62b5085612c6aafd580e72e17d2625e9dc3d769 . The file path needs to be slightly changed in order to be compatible with develop branch here

**Comment by jshorland** [comment]
This is covered by scope in #1366.

**Comment by tuxpiper** [comment]
pushed ushahidi/platform-client@b31f536

**Comment by rjmackay** [comment]
@jshorland this is on develop now. We could skip QA and just test this when we test #1366

**Comment by jshorland** [comment]
oops sorry moving the wrong one. moving back to QA and I'll qa during #1366

**Comment by jshorland** [comment]
After testing #1366, this is fully functional.
