### ISSUE TITLE
Create zero-rated create deployment URL for Surveyor plans (Tech Soup)

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1309]
This is for Tech soup partnership launch. 

Needs to be done by end of 1st week of August. 

- Add zerorate surveyor plan, full price but with coupon
- Check this works with chargebee

**Comment by rjmackay** [comment]
Don't you already have this? Or is this really just a need for a zero-rated surveyor plan? (we already have responder .. though with a few extras)

**Comment by jshorland** [comment]
Sorry, trying to be overly thorough. just zero rated surveyor plan link needs to be created. Responder already exists (I believe)

**Comment by rjmackay** [comment]
Done now. Please test URLs (sent in private channel)

**Comment by jshorland** [comment]
QA passed. I have also notified TEch Soup and had them test as well. Passed their tests too. Closing.
