### ISSUE TITLE
Surveyor izwi.ushahidi.io baselayer is wrong on Twitter posts and new posts

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1310]
### Expected behaviour
Changed default baselayer to street. On post edit form for posts via twitter and unpublished posts, the map to add location should show default baselayer as street.

### Actual behaviour
The map on the edit post form for twitter posts and unpublished posts, it shows as satellite
It doesn't happen on add post to a survey screen via web and via a direct link, though

@willdoran mind grabbing this? if you don't have time feel free to reassign

**Comment by jshorland** [comment]
As a note -- we thought we had originally fixed the issue. I created a new post and saw the streetmap baselayer on the add post form. But user saying it's still happening for newly added posts and posts via twitter (on edit post form)

**Comment by willdoran** [comment]
For newly created posts it is correct in my local for develop. I'll see if I can reproduce it on cloud.

**Comment by willdoran** [comment]
@jshorland Unfortunately, I'm having trouble reproducing the bug, would it be possible for me to see it occurring in a live instance?

**Comment by jshorland** [comment]
The user says this issue is resolved now. Could have been a caching issue for her. Closing.
