### ISSUE TITLE
Surveyor izwi.ushahidi.io wants to embed into another site through iframe

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1315]
She's got the iframe set up on her wordpress site. 

Is this the easiest/fastest approach to do this?

Responder xenowatch.ushahidi.io would like to do the same. 

@willdoran @davidlosada any thoughts on approaches to making these customers happy without dev work and/or compromising the quality of the product?

**Comment by jshorland** [comment]
Two paying customers are very intent on getting this done. They both want full site through iframe and have iframe set up. Instructions on what she needs to do would be helpful as first step, or I can connect devs directly to them to talk them through it intercom? unless we'd like to approach it differently.

**Comment by rjmackay** [comment]
Sorry I thought you were already working on this with @tuxpiper ?

**Comment by rjmackay** [comment]
As a first step they can just add this code somewhere on their site:
```
<iframe src="htttps://xenowatch.ushahidi.io" height="400" width="500">
```
They can modify the height and width numbers as needed for their site. Happy to look at specific issues they have after a first attempt.

**Comment by tuxpiper** [comment]
Sorry, maybe I forgot this if we had only commented the ticket on a call...

**Comment by jshorland** [comment]
I'm going to close this. We need to get back in touch with the user when #1387 #1388 and #1389 are complete.
