### ISSUE TITLE
Build JS in a container and deploy built JS

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1321]
- Currently deployments take down the client temporarily
- We could build JS in a container then deploy that to servers

**Comment by tuxpiper** [comment]
I've got code for this in ushahidi/ansible-platform-client-code#1 . @rjmackay where should we try it first? Is staging a good place?

**Comment by rjmackay** [comment]
Yes test on staging is good. Given that role is shared between ansible-playbooks and platform-cloud-ansible, we should probably test it doesn't break deploys to platform-qa too

**Comment by tuxpiper** [comment]
This is set up in develop branch to deploy into staging now.

One thing I've noticed, I must have fixed an error or undone a hack. Before deploying with this new approach, I was able to access http://tuxpiper.ushahididev.com . Thing is the tuxpiper deployment exists in .io but not in ushahididev.com . Now it's properly failing.

Please let me know if we are comfortable using this in production.

**Comment by rjmackay** [comment]
If this is working for staging I'm happy to move to using it in production
