### ISSUE TITLE
Allow deploying assets (js, css, images, fonnts, locales) to separate CDN endpoint

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1322]
Deploy JS and CSS for platform-client to CDN. Evaluate:
- Costs with current traffic
- Options of HTTP/2 support

Aha! Link: https://ushahiditeam.aha.io/features/PROD-684

**Comment by rjmackay** [comment]
@tuxpiper is the set up we have for rollcall reusable here?

**Comment by tuxpiper** [comment]
It should be, although I'm not sure it's going to be the best option for the coming months while we are deploying several important changes in cloud. At some point, we may need to be able to serve one client version or another, depending on the deployment subdomain.

**Comment by tuxpiper** [comment]
Maybe we could use cdn only for (cachebusted) assets

**Comment by rjmackay** [comment]
@tuxpiper any more thoughts on this? You did some of this for Uchaguzi right?

**Comment by tuxpiper** [comment]
Yes, this was implemented in the Uchaguzi deployment. I think that the solution could easily be ported over to cloud . However, I think there's little win in front loading those changes there now and I would hold on in favour of other, more valuable changes.

One thing that I think would be worth considering, is to have the option to separate between client domain and assets domain. i.e. 

* Client domain ( i.e. mydeployment.ushahidi.io ) - provides index.html, config.js and config.json
* Assets domain ( i.e. assets.ushahidi.io ) - provides the cachebusted js, css, images etc

In that way, we keep the option of having some sort of intelligent load balancing at the front of the client domain, which may dynamically redirect to a maintenance page or other sort of error... while we reap the benefits of moving the bulk of the traffic to a CDN

**Comment by tuxpiper** [comment]
My suggestion in the last comment has become more a necessity, in order to rationally implement security headers ( #1610  )

**Comment by tuxpiper** [comment]
This would make the process of setting security (or other) HTTP client headers much more elegant in SaaS

**Comment by rowasc** [comment]
@tuxpiper would you like to add this to the immediate roadmap?

**Comment by tuxpiper** [comment]
> @tuxpiper would you like to add this to the immediate roadmap? (since it was a P0)

oh yep :+1:  I think it would be a nice thing to take care of off-cycle
