### ISSUE TITLE
Implement separate data sources configuration views

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1323]
Migrating from [another comment thread](https://github.com/ushahidi/platform/issues/1179#issuecomment-229993356)

---

I've updated the PL to assume dedicated views for each Data Source. 
- [Data sources](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources.html)
- [Data sources: Email](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources-email.html)
- [Data sources: Twitter](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources-twitter.html)

_A taste:_
![Twitter](https://cloud.githubusercontent.com/assets/1136279/16528186/c9ee41ae-3f80-11e6-906e-c75e5c4c5181.png)

There's some conditional logic to what appears when, and it's spelled out in HTML comments. But the idea is this...

When you click through to a Data source that isn't configured (like [the Email example](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources-email.html)), it doesn't even show you the import-specific settings, like the toggle switch for turning on automatic imports. It only shows you the configuration stuff, prompting you to set things up and "Connect." Once you successfully connect to the source, the import settings 'form sheet' should appear above, with the option to "turn on" automatic imports.

When you click through to a Data source that _is_ configured (like [the Twitter example](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources-twitter.html)), it shows you all settings, with the continued ability to "update" your configuration.

---

I've also added a "message" to [the "Data sources" layout](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources.html) that suggests what would appear when...
- The user turns on automatic import for a source
- Selects "Done"
- Is directed to the "Data sources" landing page.

In other words, every time they turn on a data source and say "Done," they're returned to the "Data sources" page and told that their deployment is now "automatically importing" from that source.

![data source confirmation](https://cloud.githubusercontent.com/assets/1136279/16528976/c43902d0-3f85-11e6-9d4c-473ff9611fdd.png)

Furthermore, the "Data sources" layout demonstrates what the message would include if the source they had just turned on was configured to **_not_** add those imported posts to a specific survey. In this case, the message goes on to say:

> Because you've chosen to keep these posts' survey unknown for now, we've added an "Unknown" survey to your deployment's list of surveys. You can use this to quickly see any posts that are waiting to be added to a specific survey.

And it includes a button to "Show unknown survey posts," which would take them to a Timeline view with that filter applied.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-683

**Comment by rjmackay** [comment]
@jshorland this exists in the PL but not client. I'm not sure what the priority is. 
If its a long way out I think we should move it out of the main PL branch to avoid confusion..

**Comment by jshorland** [comment]
We should re-visit these designs this with our data source deep dive (figuring out how to make data sources easier, etc) BEFORE we implement in client, which I'm working on this sprint #1292.

**Comment by jshorland** [comment]
Reviving this @rjmackay as we address our data provider integrations this quarter.

**Comment by rowasc** [comment]
I think this might get handled by the UI Refresh. If that's the case we should close in favor of the ui-refresh epic
@Erioldoesdesign  to decide when they have time

**Comment by Erioldoesdesign** [comment]
It actually kind of wouldn't...there would just be a better visual style for the current 'open/collapse' functionality. This should stay so it can become integrated as part of the 'functional improvements' part of the UI refresh!
