### ISSUE TITLE
Feature: Add 'Who can edit this survey' setting

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1325]
Add 'Who can edit posts in this survey" setting in survey settings

API To do:
- [ ] Extend `form_roles` join table to add boolean `can_create` and `can_edit` fields.
  - Make sure existing entries have `can_create` set true
- [ ] Change form to validate/receive/save role permissions
- [ ] Bundle can_create/can_edit with form request response
- [ ] Update form/:formid/roles endpoint to split can_create/edit OR remove this endpoint.

Client to do:
- [ ] Update survey template
- [ ] Update survey edit/create directive
  - Save can_create + can_update through forms endpoint
- [ ] Wire "who can edit posts in this survey" as separate directive/template

Ref: https://github.com/ushahidi/platform/issues/1262#issuecomment-230816366

**Comment by rjmackay** [comment]
'Who can add posts to this survey' was implemented as an additional endpoint.
The approach for this next change needs some consideration.

- For storage
  - we could add an additional join table ie `form_roles_edit` and rename the current `form_roles` to `form_roles_create`
  - *or* we could add an additional `permission` field to `form_roles` to specify either: create or edit access.
- For the API
  - Currently PUT forms/:id/roles take an array of role ids. 
  - We could extend the forms/:id/roles endpoint to allow posting a list of roles which can create and those which can edit ie. 
  ```
  {
    create: [1,2,3]
    edit: [2]
  }
  ```
  - Alternatively we could save into the form_roles table from the `forms/:id` endpoint. This would require take similar fields in the form payload ie.
  ```
  {
    id: 1,
    name: "my form",
    can_create: [1,2,3]
    can_edit: [2]
  }
  ```

Personally I lean towards adding to the Form endpoint - as we already return the `can_create` data in the response, and it removes an extra HTTP requests when saving a survey.

**Comment by rjmackay** [comment]
@willdoran @zhalloran This is still in the spec+sizing stage.
Could you have a read through my previous comment and let me know what isn't clear, and any thoughts on which way to go?

**Comment by zhalloran** [comment]
My preference would be to extend the join table to include additional permissions. This would make it pretty easy to manage survey permissions from a role context if we wanted to (and I suspect we will). Also, we already have the join table and the supporting code in place, so adding boolean fields to that table would not be all that difficult. We could split the baby and change the code so it's attached to the /forms/:id end-point and maintain the join table on the back end. I won't object if that's how you want to implement it, but I do think the join table is the right way to go, especially if we're going to add more admin functionality to support power users.

**Comment by willdoran** [comment]
@rjmackay I would agree with Zack that extending the join table makes sense as it is the expression of the relationship and would make most sense to be controlled via permission.

I would also agree with adding the roles create/edit to the form request because it reduces elements that client is exposed to.

API To do:
- [ ] Extend join table
- [ ] Change form to validate/receive/save role permissions
- [ ] Bundle can_create/can_edit with form request response

Client to do:
- [ ] Update survey template
- [ ] Update survey edit/create directive
- [ ] Wire who can edit as separate directive/template

I would suggest that this is 3 days + 1 day review

**Comment by rjmackay** [comment]
So just to confirm, by "extend join table" you mean adding boolean fields for `can_create` and `can_edit` fields to the `forms_roles` 

Does 20 points sound about right for this?

**Comment by rjmackay** [comment]
What did you mean by 'Update survey template'??

**Comment by zhalloran** [comment]
@rjmackay Yes, I meant adding `can_create` and `can_edit` fields to the `form_roles` table. 20 points sounds reasonable.

**Comment by jshorland** [comment]
This is done, right?
