### ISSUE TITLE
Implement custom role selector for collections and saved searches modal

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1326]
<img width="244" alt="screenshot 2016-08-04 16 27 23" src="https://cloud.githubusercontent.com/assets/7965/17390345/644fb95e-5a60-11e6-9c61-c95964f218ef.png">

**Comment by rjmackay** [comment]
@willdoran can you make a size estimate of this? I think we have a pattern for this in the client already?

**Comment by willdoran** [comment]
@rjmackay 
- [ ] Update UI for custom role selector
- [ ] refactor role selector directive code, if it's not in a great state
- [ ] Wire role selector into collections and savedsearch modals

I would estimate that this would take 1 day + 1 day review

**Comment by Angamanga** [comment]
@willdoran This was fixed in #1412 https://github.com/ushahidi/platform/issues/1412 and #1486 https://github.com/ushahidi/platform/issues/1486

**Comment by jshorland** [comment]
@willdoran Does this need to be QA'd at all, or can we move to done?

**Comment by jshorland** [comment]
I QA'd anyway and this is fixed. Moving to "waiting to deploy". If already deployed, please close!
