### ISSUE TITLE
Could Task tabs be moved to bottom of survey page?

### ISSUE THREAD

**Issue by nickbadams** [ushahidi/platform#1333]
### Expected behaviour

When a user completes a survey task and is at the bottom of the page, it would be nice if the next survey tasks are clearly visible, perhaps even with a pointer directing the user to move on to the next survey task. 
### Actual behaviour

When a user completes a survey task and is at the bottom of the page, she might be confused because there is no apparent next action to take. She is probably most likely to assume she is done and that she should click the big yellow 'Save' button at the top right. But, then, the user would fail to fill out any of the other survey tasks.   :/
### Steps to reproduce the behaviour/error

Fill out any long-ish survey with more than one survey task. You will see what I mean.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-682

**Comment by jshorland** [comment]
Related to tasks scope.
