### ISSUE TITLE
Text Box questions render with line through them

### ISSUE THREAD

**Issue by nickbadams** [ushahidi/platform#1334]
### Expected behaviour
Words of a Text box question should not have a line through them.

### Actual behaviour

They do.

### Steps to reproduce the behaviour/error

Write out a text box question and see how it is displayed in the interface (on Chrome).

**Comment by jshorland** [comment]
@nickbadams I can't seem to reproduce this bug. When I add a text box to a survey, I get a normal display of text. See screenshot. Is there something else that i'm missing to reproduce?

![screen shot 2016-08-21 at 2 08 41 pm](https://cloud.githubusercontent.com/assets/3224856/17838984/e7128966-67a8-11e6-8b98-c2d74ae851d6.png)

**Comment by jshorland** [comment]
@nickbadams is this still an issue for you? if not, I'm going to close as I can't reproduce.
