### ISSUE TITLE
Location question type Obscures great GPS location functionality

### ISSUE THREAD

**Issue by nickbadams** [ushahidi/platform#1337]
### Expected behaviour
User should be able to easily click a button that locates them using their device's GPS. (Would suggest a button that says 'my current location' or something to that effect.

### Actual behaviour
User is encouraged to type in a location, then set a pin on a map. If they are lucky, they might accidentally tap the arrow that locates them using GPS.

### Steps to reproduce the behaviour/error
Fill out a Location field on any survey. Notice how current design seems to suggest that she must enter her location (even her current location) manually.

**Comment by rjmackay** [comment]
This will be covered by #1327
