### ISSUE TITLE
Default map location is confusing

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1339]
Updated ticket: as it is now, the default location is used as the default when the map loads, but then the map automatically uses the location bounds of all posts (which may be entirely different than the user's intention when they set up the default location) to decide what to display. 
We may want to consider the solutions in https://github.com/ushahidi/platform/issues/1339#issuecomment-315663893 as a follow up since we still have this inconsistent behavior.

---------- 

Original report: 
### Expected behaviour

On the Setting -> General page. When I move the map with my cursor I expect the Lat and Long fields below to adjust accordingly. When I zoom in and out on the map, this causes the Zoom number in the field below to change --> I would expect the lat and long fields to do the same.
### Actual behaviour

When I move the Map to a new default location with my cursor, the lat and long fields don't change. I press "save" and the page refreshes, but the default location is back on Kenya based on the unchanged lat and long, instead of the moved map.

The zoom change does save.
### Steps to reproduce the behaviour/error

I have reproduced this using Chrome and Firefox on two different MacBook Airs on two different ushahidi.io deployments (both Mapper and Responder deployments). 

Go to Settings -> General and Attempt to change your default map image with your cursor and press save and see if the default location has changed.

Related/duplicate for reference https://github.com/ushahidi/platform/issues/1736

Aha! Link: https://ushahiditeam.aha.io/features/PROD-680

**Comment by willdoran** [comment]
@natmanning I'm not sure if this is a clear description so let me know and I clarify further:

To reposition a map's default location you need to grab the Blue Pin on the map and move it:
So if you see in picture 1 the default point is in the middle of Eurasia:
<img width="971" alt="screen shot 2016-08-30 at 12 34 14" src="https://cloud.githubusercontent.com/assets/2694405/18097973/411e3516-6eae-11e6-83f0-3cb2eca35006.png">

And in picture 2 I have grabbed the pin and dragged it to Eastern Europe:
<img width="981" alt="screen shot 2016-08-30 at 12 34 28" src="https://cloud.githubusercontent.com/assets/2694405/18098042/828270e4-6eae-11e6-99fb-44d4022b44e9.png">

The Lat Lon below update correctly. I wonder if this a UX issue in that we might not be properly explaining that to change the default location you need to physically move the pin.

**Comment by jshorland** [comment]
This isn't a bug, as @willdoran has explained. This should actually have a location picker --> should share the same location picker as a post. @brandonrosage do you have any strong feelings about this otherwise?

**Comment by brandonrosage** [comment]
Yes, two opinions:

### Location picker
The selecting of a location should always use the "location picker," scoped out in Issue #1327.

### The 'Default location' setting
The "General" setting for "Default location" has always been a little confusing as to _which_ map it was affecting. Historically, the "General" setting for location was about the "Map" view. But, as I've advocated in the past, the "Map" view should be (and now _is_) purely positioned according to the bounds of the dataset -- not a setting. But because this "Default location" setting is still under "General," it's not clear that it's really intended to position all location pickers _wherever_ they're used. 

I'd propose this setting be removed from "General" settings and instead used in the context of each custom location field. In other words, you configure a default location for each location field in a survey. So multiple surveys might each have different default locations.

**Comment by jshorland** [comment]
I LIKE THIS.

**Comment by rjmackay** [comment]
I'm happy with that.. less config UI win. 

What that still leaves a couple of minor questions:
1. what view do we show in the map when you have no located posts? I guess just a full world map?
2. What location do we default to on location fields when they're first created? ie. before the admin sets the locations. Again I guess just full world map?
3. How do we prompt new deployers to configure the default location? given that the default post type has a location field already. Or do we just ignore this?

**Comment by brandonrosage** [comment]
> what view do we show in the map when you have no located posts? I guess just a full world map?

**Yes**, the whole world, as well all as any necessary messages regarding the dataset. For example:

![no posts](https://cloud.githubusercontent.com/assets/1136279/18850518/88aa1b02-83fd-11e6-8ed3-7579885e932b.png)

![posts with no location](https://cloud.githubusercontent.com/assets/1136279/18850529/9ba67a8e-83fd-11e6-95d9-43f36ccef19e.png)

> What location do we default to on location fields when they're first created? ie. before the admin sets the locations. Again I guess just full world map?

**Yes**, the whole world.

> How do we prompt new deployers to configure the default location? given that the default post type has a location field already. Or do we just ignore this?

I don't see a reason to go out of our way to encourage deployers to set a default location. But I'm happy to demonstrate the configuration for a custom location field.

**Comment by brandonrosage** [comment]
@rjmackay Here's a look at the configuration window for a location field:

![Edit location](https://cloud.githubusercontent.com/assets/1136279/19118159/260e5428-8ae1-11e6-8f8a-78504329d567.png)

Noteworthy:

* "Use this location to locate responses" is on by default. But it allows the deployer to do things like collect location data without necessarily mapping the entire post according to it, or to collect multiple location fields and indicate which one to reference in "Map" mode.
* "Use default location area" both turns on a default location for the field and toggles the visibility of a location picker:

![location picker](https://cloud.githubusercontent.com/assets/1136279/19118303/a0f539f4-8ae1-11e6-9544-42138300fd05.png)
_(Forgive the empty map container in the demonstration)_

**Comment by rjmackay** [comment]
Depends on #1327 finishing first

**Comment by Angamanga** [comment]
@jshorland Just want to doublecheck that I have understood the discussion above about what should be done in this issue:
1. Remove the possibility to add a 'default-location' from a deployment
2. Use bounds of the data-set or whole world if no dataset exists yet on map-view
3. Add the possibility to add default location on each location-field
4. Add location-picker when editing the settings for a location-field in a survey
5. Add the 'use this location to locate responses' option when editing the settings for a location-field

**Comment by ryanchristo** [comment]
@Angamanga, @rjmackay Is there a working branch for this issue? I would be happy to help out or start a new branch to see what I can do.

The location picker might be better suited as a common module so it can be used when both editing a post and setting the default location for the survey. Would this be a move in the right direction?

The default value could be used for the saved default location but how would the "Use this location to locate responses" be saved? We would need to filter posts out either before or in the post-view-map directive, which gets posts via the PostEndpoint's geojson method. Would we add something like a "use_geolocation" column to form attributes and then include the column as a property when formatting the geojson response, which could then be filtered out in the post-view-map directive?

**Comment by rjmackay** [comment]
@ryanchristo I don't think there is a working branch already.

- I'd like @jshorland or @justinscherer to confirm that removing default locations is still the best plan... your welcome to get started anyway but you might need to course correct if plans change. 
- I *think* the location picker is in its own directive, but maybe it should move under the `common` modules, rather than `main`. You should definitely be able to share code between this and the location editor on posts.
- I'd suggest the first iteration ignore the `Use this location to locate responses` option, we currently use ANY location and it seems reasonable to continue doing that for now.

**Comment by ryanchristo** [comment]
Ok, sounds good. Thanks!

**Comment by justinscherer** [comment]
This solution make sense to me, intuitively. To fix the zoom issue, we can default the zoom level to something that is "wide" enough to get the contexts of the first few posts. The default zoom level of the map is like the establishing shot at the beginning of a film. It gives the user context if she doesn't already know any deployment details. 

The behaviour would then be:
1. zero posts --> whole world is visible
2. If there's less than (arbitrarily) 10 posts, the default zoom level will be wide enough to (arbitrarily) see the name of the nearest major city. 
3. If number of posts >= 10, fit the zoom to the data points in the deployment.  

Ideally, we would use data to determine the ideal default zoom level. (Caveat: I'm not a data scientist). 
1.  What is the distribution of number of posts in the first week after the first post for 50 "best" deployments? 
2. What is the average geographic distribution of those posts? --> then we go up one zoom level...but I'm not a data scientist...

**Comment by ryanchristo** [comment]
@justinscherer We can set a max zoom for when there are less than 10 posts (users can still zoom in but the max zoom will prevent the auto zoom from going past this value). 

Here's a preview of the zoom levels 0, 5, 10, 15 in that order:

<img width="300" alt="screen shot 2017-07-13 at 1 34 31 pm" src="https://user-images.githubusercontent.com/12519942/28153533-174dd8ba-67d0-11e7-9f15-c141967f5fe5.png"><img width="300" alt="screen shot 2017-07-13 at 1 31 51 pm" src="https://user-images.githubusercontent.com/12519942/28153543-1fb159c8-67d0-11e7-970c-e8a70e4c8f56.png"><img width="300" alt="screen shot 2017-07-13 at 1 32 17 pm" src="https://user-images.githubusercontent.com/12519942/28153549-27e10a1c-67d0-11e7-89ed-9fb9e00d3a0a.png"><img width="300" alt="screen shot 2017-07-13 at 1 32 50 pm" src="https://user-images.githubusercontent.com/12519942/28153555-2f404002-67d0-11e7-86a8-c6f2400429ac.png">

If we decide on a number, this would be quick fix. Let me know and I can make a pull request.

**Comment by justinscherer** [comment]
Let's try zoom level 5 if there are less than 10 posts. Roughly a country-level of zoom.

To clarify: 
- If the user sets a default location and there are less than 10 posts, it will center on that default location at zoom level 5.
- If there is no default location and zero posts, it will show the whole world at zoom level 2.
- If there is no default location and more than zero posts AND less than 10 posts, the map will center on those posts at zoom level 5.

**Comment by ryanchristo** [comment]
I updated ushahidi/platform-client#684 which does the following:

1. Removes the ability to set a default location in general settings while keeping the ability to set the base layer and the ability to combine nearby posts.

<img width="1680" alt="screen shot 2017-07-14 at 9 08 45 am" src="https://user-images.githubusercontent.com/12519942/28195393-1af7ba5e-6874-11e7-9a42-5bf21c2ec67f.png">

2. Adds the location picker to the location attribute settings for a survey when choosing to select a default value.

<img width="1680" alt="screen shot 2017-07-14 at 9 11 15 am" src="https://user-images.githubusercontent.com/12519942/28195462-8b380620-6874-11e7-8509-b28ca59a9555.png">

3. If the location attribute for a survey has a default location value set, a new post will be populated with the default location.

<img width="1680" alt="screen shot 2017-07-14 at 9 11 59 am" src="https://user-images.githubusercontent.com/12519942/28195469-9318a7a0-6874-11e7-8a0f-504e7806a237.png">

4. Sets the default zoom when there are no posts to zoom level 2

<img width="1680" alt="screen shot 2017-07-14 at 8 52 37 am" src="https://user-images.githubusercontent.com/12519942/28195251-59ffdc32-6873-11e7-92c0-002f39585977.png">

5. Sets the max zoom when there are less than 10 posts to zoom level 5

<img width="1680" alt="screen shot 2017-07-14 at 9 04 00 am" src="https://user-images.githubusercontent.com/12519942/28195270-79c17eea-6873-11e7-8256-974579952755.png">

6. Keeps the auto focus when there are 10 or more posts

<img width="1680" alt="screen shot 2017-07-14 at 9 04 09 am" src="https://user-images.githubusercontent.com/12519942/28195271-7b7664d0-6873-11e7-9c2d-07e114644449.png">

This pull request does not include the `Use this location to locate responses` feature. Aside from that, is this what you had in mind? @brandonrosage @jshorland @justinscherer

**Comment by justinscherer** [comment]
> 1. Removes the ability to set a default location in general settings while keeping the ability to set the base layer and the ability to combine nearby posts.
^^ We had a different intention for this one. Allow the default location in General Settings, but don't make it mandatory. 

Otherwise looks good!

**Comment by ryanchristo** [comment]
@justinscherer Thanks! I just want to double check before rebuilding the branch. The original idea was to remove the default location from General Settings https://github.com/ushahidi/platform/issues/1339#issuecomment-249035714 and the decision moving forward is to keep the default location in General Settings but make it optional?

**Comment by rjmackay** [comment]
> Allow the default location in General Settings, but don't make it mandatory.

@justinscherer if we keep default location that leaves us with the same kind of confusing situation - ie. its not clear to a user *why* their default location isn't being used on the map mode.
If we include a default location, I think we should explicitly ask the user to pick between 1. center map on a fixed location or 2. automatically focus map based on their posts.

**Comment by justinscherer** [comment]
>automatically focus map based on their posts.
@rjmackay @ryanchristo Totally understand. Let's go with number 2 ^^ and remove default location from general settings.
