### ISSUE TITLE
Check outdated composer packages.

### ISSUE THREAD

**Issue by fegul** [ushahidi/platform#1340]
When running `bin/update` the following messages appear:

`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

`Package league/url is abandoned, you should avoid using it. Use league/uri instead.`

**Comment by rjmackay** [comment]
We need to do a check of all out of date composer packages.
Some are easy updates, but others will require refactoring.

**Comment by rjmackay** [comment]
Outstanding packages are league/url and guzzle/guzzle, most other packages have been updated.

**Comment by Aspah** [comment]
Thank you! But, how do these packages affect the Ushahidi v.3x installation?

**Comment by rjmackay** [comment]
Installation works just fine with the current set of packages

**Comment by rjmackay** [comment]
We still have guzzle/guzzle because the rackspace flysystem driver requires it. But we no longer depend on it ourselves
