### ISSUE TITLE
Admin can Close/Freeze a Survey to public

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1345]
(Taking from User running Takingplace.ushahidi.io

### Expected behaviour

As an Admin I want to be able to fill out a survey myself with content, and then close that survey to the public but keep the pins on the map.

### Actual behaviour

The crowd might be confused and fill in my "base map" survey by mistake.

### Steps to reproduce the behaviour/error
Set up a deployment

**Comment by rjmackay** [comment]
I think this is resolved now. You can now set 'who can add to this survey' in survey settings

**Comment by rjmackay** [comment]
intercom ref: https://app.intercom.io/a/apps/hl5rfiga/inbox/search/conversations/5673186607
