### ISSUE TITLE
Latitude & Longitude are not validated

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1348]
Steps to reproduce:
- upload csv file of data including lat/lon
- in timeline mode, bulk delete several sets of 10 posts
- navigate away from the timeline after doing so
- navigate back to timeline
result: blank, no posts loading

error: {"errors":[{"status":0,"title":"invalid latitude: 57983","message":"invalid latitude: 57983"}]}

**Comment by zhalloran** [comment]
We've identified the problem. A post was updated with an invalid latitude. We've discovered that points are not validated before being inserted into the post_point table. The error is thrown by Symm\Gisconverter\Decoders\WKT when attempting to decode the point into lat & lon. Might be worth adding a latitude & longitude check to the post_point validator: https://github.com/ushahidi/platform/blob/master/application/classes/Ushahidi/Validator/Post/Point.php
