### ISSUE TITLE
Post from twitter doesn't show entire text if tweet too long

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1351]
From whatisaroad.ushahidi.io

Navigated to timeline view, clicked on post and went post detail screen. Saw this.
![screen shot 2016-08-25 at 1 17 54 pm](https://cloud.githubusercontent.com/assets/3224856/18008926/16310114-6b78-11e6-9c2f-9916bcd5d94b.png)

**Comment by middle8media** [comment]
@rjmackay @willdoran There are inline styles being added to this `<textarea>` and I need to override it but I am having trouble finding how the styles are generated.

I see this https://github.com/ushahidi/platform-client/blob/7aae8c9e1046176587bb3a67d700f14285254f80/server/www/templates/posts/modify/post-value-edit.html#L122

notice the `overflow-x: hidden;` in the file above but `overflow: hidden` (no `-x`) in the browser inspector below

![messages image 2611551406](https://cloud.githubusercontent.com/assets/1033332/18056843/92e8e6f8-6ddb-11e6-88b0-bf23bf34fdd2.png)

changing `overflow-x: hidden;` in the `post-value-edit.html` does not reflect in the browser.

Any help would be appreciated, this is a simple change but something is convoluting it. I am moving on until I hear feedback. Thanks.

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/de6efc48d9d448aaf599a6910cbc4ddb2c24f7ef
