### ISSUE TITLE
Editable post author

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1361]
Migrating from https://github.com/ushahidi/platform/issues/752#issuecomment-239284562

---

When editing a post's author and/or post date, here's what I've staged in the PL:
## Logged out

When you encounter the "Add post" page, you'd see a summary of the metadata:

![logged out](https://cloud.githubusercontent.com/assets/1136279/17603710/18959d44-5fd8-11e6-9046-619a5f6571aa.png)

If you select "Change," the fields for providing author information replace the text-only appearance:

![change author](https://cloud.githubusercontent.com/assets/1136279/17603739/39e924de-5fd8-11e6-8442-4420a73be692.png)

The rest works as you might expect. It's a typical form sheet.
## Logged in

When you encounter the "Add post" page, you'd see a summary of the metadata:

![logged in](https://cloud.githubusercontent.com/assets/1136279/17603838/902c2328-5fd8-11e6-9660-1c63e0ac8bde.png)

When you select "Change," the fields for providing author information _and_ customizing the post date replace their text-only appearance: 

![change author and post date](https://cloud.githubusercontent.com/assets/1136279/17603878/b82db580-5fd8-11e6-91cb-237017c3cee9.png)

If you want to change the author, you can remove the existing "bug," which would change that fieldset's appearance to:

![change author fields](https://cloud.githubusercontent.com/assets/1136279/17603913/e29a9b8a-5fd8-11e6-89ec-b81af518cd16.png)

In this case, because you're logged in, typing into the author "Name" field will perform a search of the deployment's users and return matching results in a dropdown:

![author results](https://cloud.githubusercontent.com/assets/1136279/17603957/1892b5b0-5fd9-11e6-80a9-1f3a3c851760.png)

If you choose to simply type a name and not select an existing user from the list, the form will record your custom author name and (optional) email address. If you choose an existing user from the list, the "name" and "email" fields are replaced by that user's "bug."

Aha! Link: https://ushahiditeam.aha.io/features/PROD-675

**Comment by rjmackay** [comment]
@brandonrosage I think that looks workable but @jshorland suggested we should user test this since its adding a lot of complexity that may or may not be necessary.

**Comment by rjmackay** [comment]
While looking at #1399 I wondered - how does the user editor interact with posts with just an SMS number? or can I set a post to 'anonymous' when editing?

**Comment by jshorland** [comment]
So meta data also gets rid of our need for this right? because you actually edit author and date by clicking those chips themselves.

**Comment by rjmackay** [comment]
No. Meta data changes the UI for getting to user editing and other meta data.. but doesn't remove the work needed to actually allow editing users on the backend, and feedback on the actual UI of the edit user dialog (or fields if this goes in *before* meta data fields)

**Comment by rowasc** [comment]
Note: Probably solved through https://github.com/ushahidi/platform-pattern-library/issues/205
