### ISSUE TITLE
Update markup to fix arrows in data source menu

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1365]
Are they supposed to look like this? They're designed for a giant's thumbs!

![screen shot 2016-09-07 at 3 37 24 pm](https://cloud.githubusercontent.com/assets/3224856/18331080/38b5db72-7511-11e6-8274-77645ca831e3.png)

**Comment by rjmackay** [comment]
Not sure. @brandonrosage updated the data sources in the PL so its no longer in sync http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/settings-data-sources.html

@brandonrosage did those changes break the old data sources styling?

**Comment by brandonrosage** [comment]
I've fixed this in the PL, whose `master` branch currently represents what's intended for Sprint 10 (with a little but of Sprint 11).

![screenshot](https://cloud.githubusercontent.com/assets/1136279/18403035/2443ccec-76a8-11e6-9e7f-38a8d90e1cbd.png)

"Data sources" sample: http://preview.ushahidi.com/platform-pattern-library/master/assets/html/5_layouts/settings-datasources.html

**Comment by rjmackay** [comment]
Needs a dev to update markup + CSS

**Comment by middle8media** [comment]
the markup is up to date, I think we just need to publish the revised PL styles to npm

**Comment by rjmackay** [comment]
Resolved by 2e59f0c

**Comment by jshorland** [comment]
fixed in qa.ushahididev.io. Moving to waiting to deploy.

**Comment by jshorland** [comment]
oops. already in that column.
