### ISSUE TITLE
Store additional info with locations

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1367]
This is a combination of ushahidi/platform#587 ushahidi/platform#600 ushahidi/platform#699 ushahidi/platform#1245 
### Expected behaviour

When editing a post the location editor should capture location name, lat/lon, zoom level and maybe address.
This address or location name should be displayed when viewing the post
### Actual behaviour

Location editor only captures lat lon. When viewing the post we see the 'key' of the location field.
## Solution
- Add label, address, and zoom fields to post_point and update API to save them
- Update location editor to send address info to the API
- Allow user to edit location caption/label
- Show location label when viewing post

Aha! Link: https://ushahiditeam.aha.io/features/PROD-674

**Comment by rowasc** [comment]
Related #1245 #908
