### ISSUE TITLE
Changing map icons based on categories

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1368]
https://github.com/ushahidi/platform-client-1000ocean/issues/8
https://github.com/ushahidi/platform-client-1000ocean/issues/9

**Comment by rjmackay** [comment]
@willdoran is there anything in this task that should go back into platform? or shall we just close it?

**Comment by jshorland** [comment]
we should try to get this into platform if possible, but this will need a better idea of UI for platform. I would suggest we move back to design. @willdoran thoughts?

**Comment by willdoran** [comment]
The major issue with this will be supporting custom sprite files and mixing them into our own. The other changes are actually extremely straightforward. And can be moved directly from 1000ocean

**Comment by rjmackay** [comment]
@willdoran how did you resolve posts with multiple categories? did 1000oceans always use categories for icons? or is it optional? ie. how do we know when to use category icons vs survey icons.

**Comment by willdoran** [comment]
@rjmackay in their setup, they only use their icons. Multiple categories per post is not supported. I didn't have time/it wasn't considered necessary to force single categories per post. Instead only the first category returned is used to determine the post category and I think David told them that it was only one category per post.

I perhaps misunderstood but I thought we would still be marking the posts on the map in terms of their survey type, no?

The most complex bit will be allowing the upload of sprites and then mixing these into our sprite file. The new sprites will also have to conform to the shape and structure of our existing sprites.

**Comment by jshorland** [comment]
Closing in favor of #1436
