### ISSUE TITLE
Inability to receive notifications from saved search

### ISSUE THREAD

**Issue by FIU-Editor** [ushahidi/platform#1375]
### Expected behaviour

We created a new saved search, turned on notifications ("Get Notifications"), and, when testing it, expected to receive email notification of posts within the search. 
### Actual behaviour

When testing this feature, however, neither my colleague nor I were able to receive notifications. Is there something wrong with our process, or is it from the backend? 
### Steps to reproduce the behaviour/error
1. We selected the survey we wanted
2. Clicked "Save Search" 
3. Provided name, description, etc., clicked "Save and Close."
4. Clicked ellipsis button and clicked "Get Notifications"
5. Proceeded to make test posts for the survey included within the Saved Search

Despite this, no email notifications were received; my colleague, having tried yesterday, still has not received a notification either. We'd greatly appreciate help on this issue.

Thanks

Our deployment is: bb.fiu.edu

**Comment by rjmackay** [comment]
@FIU-Editor its likely you need to set up your contacts for your user. 
On your deployment
1. Login
2. click on your Account Settings on the bottom left (this probably has your avatar or photo as a button)
3. Go to 'Notifications' tab
4. Add an email or mobile number you need as contacts. 
5. save (even if you didn't add more numbers)

Let me know if that solves the problem.

**Comment by FIU-Editor** [comment]
Hello,

As you can see, we've done this long before this problem has arisen, and consistently failed to receive notifications from incoming posts:

![image](https://cloud.githubusercontent.com/assets/17600339/18561062/3ecb7c88-7b4c-11e6-8fda-a6e743160cce.png)

Also, this issue seems to be affecting saved searches only; we can receive notifications for collections just fine.

**Comment by willdoran** [comment]
Hi,

In conjunction with the savedsearch notifications the following should be running as a cron job on the platform deployment:
bin/ushahidi notification:savedsearch queue

This will collect updates to the savedsearches and send appropriate emails. Savedsearches are handled a bit differently to collections. Let me know if this resolves the issue or if you need further assistance.

**Comment by willdoran** [comment]
They have contacted me to say that they are changing the person managing their backend and will update us if they are still unable to resolve the issue.
