### ISSUE TITLE
CSV export gives me unreadable column labels

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1376]
### Expected behaviour
My column labels (row 1 in CSV) should match my survey data field labels, or as closely as possible, so I can read my CSV clearly

### Actual behaviour
Sample of Row labels from an export i did from devex.ushahidi.com:

- 007851e9-215a-4a52-9ec1-7d40a2fef645
- 05bde2bd-bd60-4c93-a15e-5991d8ced0cf
- 06a1aeba-126c-4240-a584-749781c6f64f.lat

### Steps to reproduce the behaviour/error
Export full CSV from devex.ushahidi.com and open in excel and/or google sheets.

**Comment by jshorland** [comment]
Notes from @willdoran: Ok so this is a leetle complicated, I think it will take me about 1 day to fix it. We changed from using keys that looked like the names of the fields to using UUIDs, I need to change the mapping when the csv is exported so that it output the value field name instead of the key

THOUGH there is a caveat, the reason we use UUIDs is so that you an name your field whatever you want and not worry about it conflicting with another field on another survey. So in the export you could end up with “Field name that is not unique”, “Field name that is not unique” which might be a little confusing if you are outputting different posts whose survey have non-unique field names. So I’ll have to figure out the best way to do this, I would like to do it so that it prepends the survey name to the field name so it’s clearer. 

Prepending the survey name to the field name is clear. This seems like the best way forward.

**Comment by rjmackay** [comment]
@jshorland are we classing this as a bug? Is it going straight into dev? 
ie. what column does this go in?

**Comment by jshorland** [comment]
I'm not sure how to classify it to be honest @rjmackay -- it's technically not a bug, but a terrible UX and makes CSV completely unreadable. I think we should pop it into "tech spec and sizing", get a size, and put it into waiting for sprint to get it scheduled ASAP. Thoughts?

**Comment by rjmackay** [comment]
I think @willdoran is looking at this within the scope of #1366. 
@willdoran Can you move this into dev if you're already started?

**Comment by jshorland** [comment]
Another user complaint: https://app.intercom.io/a/apps/hl5rfiga/inbox/unassigned/conversations/6089553793

**Comment by willdoran** [comment]
@jshorland This should be available in qa.

**Comment by jshorland** [comment]
@aoduor I've tested several different filter configurations and this seems to be working. Would you test a few times as well?

A few things to note:
- there are several things that are labeled as they are in the backend -- this can be changed, but is another issue. We should deal with that when we work on the backend, not now, as there is risk of breaking everything. (categories = tags, collections = sets, surveys = forms)
- we've been able to differentiate by survey to rid our need for the user to name the field id uniquely themselves. 
- for the moment this really just fixes the attribute column names for other stuff we’d have to change specifically, though, we control the bit where the column heading is written and in the shorter we could create a mapping, for example form_id to survey_id

**Comment by aoduor** [comment]
On http://qa.ushahididev.com, this problem still exists.

I got a column with this heading: New date field.06491e6e-8d3c-4736-b4cb-62f8adaab285

On http://qa.ushahidi.com this works fine, but clicking on "Cancel" doesn't yield any result, and clicking "Ok" doesn't close the pop up box either.

**Comment by willdoran** [comment]
@aoduor "New date field.06491e6e-8d3c-4736-b4cb-62f8adaab285" is actually correct - because the field names are not unique at any level we need to differentiate them to some degree, and the alphanumeric is the attribute UUID.

Hmmm let me see if I can hide the key

**Comment by willdoran** [comment]
@aoduor Ok, I've changed it so that the column names no longer contain the key, note that if for example "test column name" appears as a field name in multiple surveys there will be multiple columns called "test column name" with the values appropriate based on which survey the given post belongs to.

Let me know if this works ok on qa

**Comment by rjmackay** [comment]
This works perfectly for me :)

**Comment by jshorland** [comment]
Passes QA -- let's get this pushed into production ASAP.
