### ISSUE TITLE
homepage error?

### ISSUE THREAD

**Issue by ljh468525** [ushahidi/platform#1377]
I can't see letter behind the black box
How can I solve this ?

**Comment by rjmackay** [comment]
@ljh468525 I'm not sure what you mean. Which black box? What part of the site are you on?
Can you provide a screenshot?

**Comment by jshorland** [comment]
Hey @ljh468525, we're going to close this issue for now. If you are still experiencing the issue and can send a screenshot through, please do and we'll reopen the issue.
