### ISSUE TITLE
Add warnings when updating survey which already has posts

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1378]
### Expected behaviour

When I update a survey which has posts, I should be warned before delete fields/tasks. I should also be notified that editing required fields/tasks will leave posts in an invalid state (ie. will not auto complete tasks)
### Actual behaviour

No warnings.
### Steps to reproduce the behaviour/error

Aha! Link: https://ushahiditeam.aha.io/features/PROD-673

**Comment by codifyit** [comment]
Hi @Angamanga I want to know more about this issue. Can you guide?

**Comment by rowasc** [comment]
Hey @codifyit sorry this was already handled .
