### ISSUE TITLE
I have filled in fields but it says i haven't

### ISSUE THREAD

**Issue by Urfaqadri** [ushahidi/platform#1380]
### Not sure what to do next.

**Comment by willdoran** [comment]
Hi @Urfaqadri, 
I'm trying to recreate the issue. Could I ask did you fill in the Description field?

**Comment by Urfaqadri** [comment]
Yup!

Sent from my BlackBerry 10 smartphone.
From: will
Sent: mi�rcoles, 14 de septiembre de 2016 05:10 p.m.
To: ushahidi/platform
Reply To: ushahidi/platform
Cc: Qadri, Urfa; Mention
Subject: Re: [ushahidi/platform] I have filled in fields but it says i haven't (#1380)



Hi @Urfaqadri<https://github.com/Urfaqadri>,
I'm trying to recreate the issue. Could I ask did you fill in the Description field?

�

**Comment by willdoran** [comment]
@Urfaqadri, Thanks for responding. Interesting, I filled in the Title, Description and the fields marked with an * and the form is saving for me. Could you tell me which fields it tells you to fill in?

**Comment by Urfaqadri** [comment]
It is not aligning on my computer as in the text is half way in the word description etc. I can take a screen shot tomorrow and send

Sent from my BlackBerry 10 smartphone.
From: will
Sent: mi�rcoles, 14 de septiembre de 2016 05:29 p.m.
To: ushahidi/platform
Reply To: ushahidi/platform
Cc: Qadri, Urfa; Mention
Subject: Re: [ushahidi/platform] I have filled in fields but it says i haven't (#1380)



@Urfaqadri<https://github.com/Urfaqadri>, Thanks for responding. Interesting, I filled in the Title, Description and the fields marked with an * and the form is saving for me. Could you tell me which fields it tells you to fill in?

�

**Comment by willdoran** [comment]
Ah, I see, a screenshot would be useful. I will share the issue with our UI team.

**Comment by Urfaqadri** [comment]
[cid:image001.jpg@01D20F33.4D155C80]

**Comment by willdoran** [comment]
@Urfaqadri I'm afraid the image doesn't come through when sent via email. Could you upload it directly to the github issue?

**Comment by willdoran** [comment]
@Urfaqadri, I believe we have a fix for this issue. @tuxpiper should be able to test and deploy it later today. Thanks for your feedback!

**Comment by rjmackay** [comment]
@Urfaqadri @willdoran Is this resolved?

**Comment by Urfaqadri** [comment]
Not that I know of

Sent from my BlackBerry 10 smartphone.
From: Robbie Mackay
Sent: lunes, 19 de septiembre de 2016 10:25 p.m.
To: ushahidi/platform
Reply To: ushahidi/platform
Cc: Qadri, Urfa; Mention
Subject: Re: [ushahidi/platform] I have filled in fields but it says i haven't (#1380)



@Urfaqadri<https://github.com/Urfaqadri> @willdoran<https://github.com/willdoran> Is this resolved?

�

**Comment by tuxpiper** [comment]
Unless I missed what the issue was to begin with... this seems resolved to me. The form elements are clearly aligned and error messages are clearly displayed for missing inputs.

**Comment by Urfaqadri** [comment]
No they are not aligned and I put it all the required elements,

Sent from my BlackBerry 10 smartphone.
From: David Losada
Sent: martes, 20 de septiembre de 2016 12:56 p.m.
To: ushahidi/platform
Reply To: ushahidi/platform
Cc: Qadri, Urfa; Mention
Subject: Re: [ushahidi/platform] I have filled in fields but it says i haven't (#1380)



Unless I missed what the issue was to begin with... this seems resolved to me. The form elements are clearly aligned and error messages are clearly displayed for missing inputs.

�

**Comment by tuxpiper** [comment]
@Urfaqadri aren't you seeing something like the attached screenshot?

![screen shot 2016-09-20 at 18 16 25](https://cloud.githubusercontent.com/assets/467393/18679125/94a0616c-7f5e-11e6-8728-9062d55f3028.png)

If not, you may have to clear your cache.

**Comment by Urfaqadri** [comment]
No, I filled in all the info, per the screen shot I sent.  The title and name of organization line to not line up with the text entered; this means that when I click save, it tells me I don't have anything in those fields.

All of this is moot, I believe, as the due date was last week before I first contacted you.

**Comment by tuxpiper** [comment]
Really sorry that we couldn't be of assistance on time.

Just as @willdoran  said back then, we couldn't see your screenshot as it was filtered by github when processing your email. ( open this URL to see what we can see: https://github.com/ushahidi/platform/issues/1380 ).

If @Urfaqadri  would be willing to send a newly generated screenshot showing how the problem he/she meant to report persists, we could keep looking into this. Otherwise, I suggest we close this issue.

**Comment by jshorland** [comment]
I'm closing the issue.
