### ISSUE TITLE
Configure tasks

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1381]
User stories:
- [ ] As an admin, I want to be able to assign permissions to manage tasks to specific users, which will allow them to create new tasks, delete tasks, and assign tasks. 
- [ ] As a user with permissions to manage tasks, I want to create new tasks
- [ ] As a user with permissions to manage tasks, I want delete tasks
- [ ] As an admin I want to be able to create a description of a task to help educate my users why that task is important like stated in #796 

@brandonrosage @caharding do we need to have task visibility in v1 configuration?

Aha! Link: https://ushahiditeam.aha.io/features/PROD-672

**Comment by brandonrosage** [comment]
Users with permission to create, edit, and delete surveys can (by extension) do the same to their tasks. They can do so one of two ways:

## 1. Editing a survey
When editing a survey, one of its secondary configuration sections is "Tasks," included in the mode context.

![edit survey mode context](https://cloud.githubusercontent.com/assets/1136279/20285794/69add7ea-aa89-11e6-96d3-f0585f17f74a.png)

When selected, that button will navigate the user to a view summarizing the survey's tasks, with the ability to re-order, duplicate, delete, or add to them.

![edit survey tasks](https://cloud.githubusercontent.com/assets/1136279/20285851/a8790abc-aa89-11e6-8fb9-fa5af2ac5096.png)

The "---" actions trigger appended to each task reveals options to "Duplicate" or "Delete."

If the survey doesn't yet have any tasks configured, the view will include placeholder content to help explain the purpose of "tasks."

![no tasks](https://cloud.githubusercontent.com/assets/1136279/20286120/dfbd0446-aa8a-11e6-9d1e-0c90e41a184a.png)

Adding or editing a task reveals an editable "free-form" view; much like the one used to compose a survey:

### Add a task
![add a survey task](https://cloud.githubusercontent.com/assets/1136279/20285928/03af5fa8-aa8a-11e6-8de6-412c9a37843a.png)

### Edit a task
![edit survey task](https://cloud.githubusercontent.com/assets/1136279/20285897/e09838fa-aa89-11e6-8e3d-3fe660b6f3c4.png)

More detail about the configuration of each task is included in the documentation for #1382.

## 2. Settings > Tasks
The "Tasks" list item within the deployment's Settings listing is a simple quick-link to each surveys' tasks. Its intent is to provide a discoverable path to task configuration, without forcing them to go through the survey editing modality.

![Tasks settings](https://cloud.githubusercontent.com/assets/1136279/20286200/2b950d6e-aa8b-11e6-8aea-2c31ee200ee0.png)

Selecting each survey name will navigate the user to that survey's listing of tasks:

![edit survey tasks](https://cloud.githubusercontent.com/assets/1136279/20285851/a8790abc-aa89-11e6-8fb9-fa5af2ac5096.png)

**Comment by brandonrosage** [comment]
@jshorland + @caharding + @rjmackay: This is one of four issues that combine to define the next iteration of "Tasks" for Ushahidi. Those four issues include #1381, #1382, #1383, and #1385.

Though they may not be actively developed in the near term, I'd really like to jump on iterating and testing many of the decisions and assumptions here. So your timely feedback and questions are appreciated. Thanks.

**Comment by jshorland** [comment]
@brandonrosage one thing I found with usaelectionmonitor was the need to build a single workflow and apply it to multiple surveys. Is that feature included in your designs here and I missed it?

**Comment by jshorland** [comment]
@brandonrosage @rjmackay @caharding task privacy settings are going to be necessary. I'd like to try to get them into version 1 of this if possible.

**Comment by rjmackay** [comment]
@brandonrosage sorry about the slow feedback

- What does a new survey look like? does it start blank or with some tasks?
- What does a new deployment look like? Does it start with a default survey + tasks?

**Comment by caharding** [comment]
Something I find confusing is the "add field" to tasks. Feels like a survey form creation. Could we use another word like step or description instead? Want to make sure that Tasks are visually distinct.
