### ISSUE TITLE
Post menu icon not visible in IE 11 on Windows 7

### ISSUE THREAD

**Issue by zhalloran** [ushahidi/platform#1384]
### Expected behaviour

The icon for the menu on posts in map view and timeline view should be visible in IE 11 on Windows 7
### Actual behaviour

The icon is not visible
### Steps to reproduce the behaviour/error

View a post popup or timeline in IE 11 on Windows 7

**Comment by rjmackay** [comment]
@middle8media what actually fixed this? What do we need to change in the client?

**Comment by middle8media** [comment]
I used svg4everybody to fix this issue which requires a js file and two script tags in `_scripts.html`

https://github.com/jonathantneal/svg4everybody

https://github.com/ushahidi/platform-pattern-library/commit/699c6dbe71cb0660266e2359aec9202f343b13f7#diff-b5edb800ce5968498d73755dc833d6f8R6

**Comment by middle8media** [comment]
@rjmackay are we good on this?

**Comment by rjmackay** [comment]
Not really. I'm not sure svg4everybody is a functional solution in AngularJS or not.. either way we'll have investigate a little more. I'm not 100% clear what the fallback method is .. do we fallback to png or object? or both depending on browser?

**Comment by middle8media** [comment]
@rjmackay here is what I read concerning browser and fallback support. FYI. Whether or not we can use this in Angular requires a dev chat. I will run this by @willdoran to get his opinion.

**Browser support**
> _SVG for Everybody adds SVG External Content support to all browsers._ (excluded IE 6-8)

**Fallback Support**
![image](https://cloud.githubusercontent.com/assets/1033332/20850131/c376dc3c-b8a7-11e6-8865-ffb5041bcabd.png)
