### ISSUE TITLE
Add filters for tasks 

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1385]
User stories:
- [ ] As any user, I want to filter all posts by which task they're in
- [ ] As any user, I want to see how many posts are in each task
- [ ] As any user, I want to be able to differentiate tasks belonging to different surveys by color (the color of the task maps to the color of the survey to which it belongs)

*NOTE: if we add visibility controls in task configuration, it will also have implications on this

Aha! Link: https://ushahiditeam.aha.io/features/PROD-669

**Comment by brandonrosage** [comment]
This is all done in "Tasks" mode, where users (with permission) can see posts that have tasks attached to them.

![Tasks mode](https://cloud.githubusercontent.com/assets/1136279/20284113/67d07c14-aa81-11e6-94ba-cf51e9f6ee58.png)

By default, this mode displays all posts that have incomplete tasks assigned to you. Its toolbox includes controls for configuring how the posts are sorted, and showing tasks based on who they're assigned to, whether they're complete, and/or whether their post is published, under review, or archived.

Users can use the "Filters" control to access more fine-grained controls, including survey fields and tasks that the deployers have chosen to "include in filters." This would allow them to show all posts with an incomplete "Verify" task, for example. This same convention would allow them to see how many tasks match those parameters, by way of the total displayed at the top of the list.

**Comment by brandonrosage** [comment]
@jshorland + @caharding + @rjmackay: This is one of four issues that combine to define the next iteration of "Tasks" for Ushahidi. Those four issues include #1381, #1382, #1383, and #1385.

Though they may not be actively developed in the near term, I'd really like to jump on iterating and testing many of the decisions and assumptions here. So your timely feedback and questions are appreciated. Thanks.
