### ISSUE TITLE
Automatically turn"unknown" posts into a default task

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1386]
User stories:
- [ ] As an admin, I want any unknown posts to automatically turn into a default task to structure the post into a survey (WORDY. WOOF)
- [ ] As a user with permissions to manage tasks, I want to assign this default task to a user in "configure tasks" #1381

Aha! Link: https://ushahiditeam.aha.io/features/PROD-668

**Comment by brandonrosage** [comment]
@jshorland I'd argue that admins want _the ability_ to automatically attach the task of assigning a survey to all incoming unknown posts -- but not to just do that automatically in all cases out of the box.

The reasons for this are:

* If they're importing tweets at a high rate, a lot of those are noise that they may never intend to assign to a survey, and rather delete. Without the ability to optionally automate the task, every tweet would be assigned, even if there was no intention to accomplish that task.
* Automated tasks that you can't turn off would be yet _another_ class of task. It'd be ideal to keep this kind of task within the same framework as the others.
