### ISSUE TITLE
Bulk actions on timeline mode

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1390]
In listing toolbar view

As a user with "manage posts" permission, I want to bulk
- [ ] delete
- [ ] change status
- [ ] assign (users with "manage tasks" permission)
- [ ] “Add to Collection” for all selected items (all users)

@brandonrosage do we already have designs for this?

**Comment by brandonrosage** [comment]
@jshorland I've addressed most of what you're referring to in Issue #1023. I'm not sure how you want to organize these related and potentially-overlapping issues. But I see them as very related.

I'll be sure to address the task assignment bit.

**Comment by jshorland** [comment]
Closing in favor of #1023. way to catch my duplication @brandonrosage
