### ISSUE TITLE
Sorting in timeline mode

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1391]
User stories:
- [ ] As any user, I want to sort by post creation date, both ascending and descending
- [ ] As any user, I want to sort by post last modified date, both ascending and descending

**Comment by jshorland** [comment]
Should clear up #458

**Comment by brandonrosage** [comment]
I'd propose the simplest, most consistent treatment for this feature using our existing "toolbox" convention:

![sort by toolbox](https://cloud.githubusercontent.com/assets/1136279/18569279/3e844c58-7b67-11e6-827d-5f75307b650e.png)

This particular "tool" (e.g. Sort by) would be collapsed by default inside the larger "toolbox" (which includes filters for "Post status" and "Date range").

Thoughts, @jshorland?

**Comment by jshorland** [comment]
I like that the proposed solution doesn't add additional complexity or behavior change, but prefer the wording "oldest" and "newest" instead of descending and ascending. 

And do you remember the use case that justified being able to sort by oldest modified date?

**Comment by jshorland** [comment]
Got it — thanks. Looks good.

**Comment by brandonrosage** [comment]
As far as I'm concerned, @jshorland, this is ready for "Tech Spec & Sizing."

**Comment by jshorland** [comment]
It is apparent from Uchaguzi that this is crucial to workflow efficiency.

**Comment by jshorland** [comment]
@justinscherer @willdoran this would be helpful if we have time

**Comment by jshorland** [comment]
cc: @middle8media are there already patterns built for this?

**Comment by middle8media** [comment]
Yes

Custom Select
```
<div class="custom-select">
    <select>
        <option>Post Date</option>
        <option>Option 2</option>
        <option>Option 3</option>
    </select>
</div>
```
Radios
```
<fieldset>
    <div class="form-field radio">
        <label for="colt"><input type="radio" id="colt">Nalle Colt</label>
    </div>
    <div class="form-field radio">
        <label for="vaughan"><input type="radio" id="vaughan">Stevie Ray Vaughan</label>
    </div>
</fieldset>
```

**Comment by jshorland** [comment]
@rjmackay if we have any chance of getting this in... it would be a big improvement for the structuring team

**Comment by jshorland** [comment]
this is done. moving to done.

**Comment by jshorland** [comment]
Just checking in that this is actually getting back into core? cc: @rjmackay

**Comment by rjmackay** [comment]
It should be live on production already
