### ISSUE TITLE
Research out of the box emails

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1395]
Phase 2: Out-of-the-box email; aliases?
- Could be only for paid users
- Dev estimate: medium. Complicated because of configuring external services
- Biz note: we need to figure out cost of this/how to manage the vendor

Aha! Link: https://ushahiditeam.aha.io/features/PROD-666

**Comment by rjmackay** [comment]
FYI our existing email provider does this. Just checked their docs and it looks like inbound email handling is free. We only pay for outbound and are currently well under the limit before we start being charged.
