### ISSUE TITLE
Cannot unassign post from a category

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1400]
### Expected behaviour
1. Given a post assigned to category C1; if I edit the post, remove the assignation to C1 and save, the post should not be assigned to any categories.
2. Given a post assigned to category C1, if I edit the post, and remove the assignation to C1 and assign to category C2, the post should be assigned to category C2 only

### Actual behaviour
1. The post remains assigned to category C1
2. The post becomes assigned to category C1 and C2

### Steps to reproduce the behaviour/error
Directly reproducible from the behavior description

**Comment by rjmackay** [comment]
@jshorland Q on process: this is clearly a bug.. I don't think sizing a bug like this is particularly useful.
Should I drop it straight into Waiting for sprint? or waiting for dev?

**Comment by jshorland** [comment]
Let's drop this straight into waiting for dev, I'd say

**Comment by jshorland** [comment]
works like a dream. Passes QA.

**Comment by tuxpiper** [comment]
Thank you! Applied the fix to the 1000ocean.ushahidi.com deployment.

@Celestine22
