### ISSUE TITLE
sub-domain has already error

### ISSUE THREAD

**Issue by spiral99** [ushahidi/platform#1401]
### Expected behavior

There should be an visual indication on the input form when the sub-domain has already been taken currently there isn't.
### Actual behavior

If a new user inputs a sub-domain that has already been taken on the create deployment there is an output error stating this on the top of the form
### Steps to reproduce the behavior/error

try creating a new deployment enter all of the necessary info which include
YOUR DISPLAY NAME 
YOUR EMAIL 
PASSWORD & DEPLOYMENT NAME 

on the DEPLOYMENT URL enter a pre-existing domain.

**Comment by rjmackay** [comment]
@spiral99 thanks for the bug report. @zhalloran is already working on a fix for this alongside other changes to that form. You should see this fixed in a few weeks.
