### ISSUE TITLE
Bugs in collections UI

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1402]
Migrated from https://github.com/ushahidi/Ushahidi_Web/issues/1453

when I click on collections there is a number of bug-like behaviour including: duplication of collection names, and when clicking on "edit" for the current collection, it takes you to another collection. I am trying to teach a new group of volunteers to use this product so I would be very grateful if you could fix these problems as soon as possible.

Also I've noticed there is a bug with task descriptions not being saved at all even when explicitly clicking on the "save button" in the survey area.

**Comment by rjmackay** [comment]
Deployment URL is palestine-reports.ushahidi.io

**Comment by jshorland** [comment]
I'm going to try to reproduce it, or contact user if i can't

**Comment by rjmackay** [comment]
@daneasterman we're looking into this issue and will post updates here.

**Comment by rjmackay** [comment]
I think this might reproduce:
1. Create a new collection (C2)
2. Navigate to a different colleciton (c1)
3. Click edit - C2 is shown in edit, rather than C1.

**Comment by jshorland** [comment]
same as #1407. Closing in favor of that one.
