### ISSUE TITLE
New lines in deployment description aren't rendered in mode context

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1403]
### Expected behaviour
When I type new lines in to the description field in settings > General, I expect to see them on the sidebar

### Actual behaviour
New lines are only show as spaces, not new lines

### Steps to reproduce the behaviour/error

More info on intercom https://app.intercom.io/a/apps/hl5rfiga/inbox/tech/conversations/5726562662

**Comment by jshorland** [comment]
:-)
