### ISSUE TITLE
QA observations and improvement suggestions.

### ISSUE THREAD

**Issue by spiral99** [ushahidi/platform#1404]
1.     Creating my first basic post I expected the save button to be under the location selection.
2.  As a fist time user i have no idea what the collections section entails maybe a small description     would be suffice.  
3.  A key that show what is displayed on the map may also be helpful to users.
4.  The icons at the bottom left are not intuitive to first time users most user don't expect the login,support and feature icons to be at that location so it may be frustrating for first time users.
5.  Search feature should indicate exactly what can be searched using that feature on the map i tried  to do a location search which didn't work before realizing i could use the filter option for that.
6.  Once you you apply your location within your desired distance filters it would be nice if the area was zoomed into on the map.
7.  Export icon will export filtered posts where exactly are the posts being exported to? as a first time user that's what i was asking myself.
8.  Since Ushahidi is a global platform could there be a language translation feature for users that may not understand English as a first language .
9.  Post description  was a little confusing it gave me the impression that i needed to input some text   to describe the title of my post before proceeding to the body of the post, even the text area is small re-enforcing this impression,so i was actually looking for where to insert the main content of the post.
10. On the publish post feature I have no idea where I am publishing to and to whom.

**Comment by jshorland** [comment]
@brandonrosage this is brian's first pass at testing. Read through and we'll discuss pulling out what we can
