### ISSUE TITLE
Custom icons for Survey types

### ISSUE THREAD

**Issue by kollinsayz** [ushahidi/platform#1406]
### Expected behavior
As in V2, each post would appear as an icon on the map showing the location instead of the Pin.
### Actual behavior
Currently we just have the default location pin :(

**Comment by tuxpiper** [comment]
@jshorland @aoduor  I think this is a +1 to add to #625 and #1368

**Comment by aoduor** [comment]
Thanks for flagging @tuxpiper ;)

**Comment by jshorland** [comment]
@tuxpiper this was done for 1000 oceans, right?

**Comment by tuxpiper** [comment]
That is exactly right @jshorland

**Comment by rjmackay** [comment]
@willdoran @tuxpiper  is this just a matter of pulling the code out of 1000 oceans? or is there some rework needed?

**Comment by tuxpiper** [comment]
I don't think it's just a matter of grabbing the code. Two specific things that were done for 1000oceans:

1. the icons corresponded to categories instead of survey types
2. we could afford the assumption that the icons had already been uploaded

**Comment by willdoran** [comment]
This requires us to integrate custom icons into our sprites dynamically. I don't know how to do that.
But allowing icons to be different on the map per survey is extremely simple and the code can be ported.

**Comment by rjmackay** [comment]
I think this is replaced by https://github.com/ushahidi/platform/issues/1436
