### ISSUE TITLE
P0 Bug Image upload

### ISSUE THREAD

**Issue by KrisKuri** [ushahidi/platform#1408]
Deployment url: https://hillclearinginpenang.ushahidi.io/
### Expected behaviour 
After an image upload , the images should appear as uploaded in the post.

### Actual behaviour
Images disappeared , images don't appear in the post. A number appears in the text field.
### Steps to reproduce the behaviour/error
upload image to a post
save.

**Comment by jshorland** [comment]
@KrisKuri when you log a P0 bug, can you make sure to add the P0 label? Thanks!

**Comment by jshorland** [comment]
@willdoran @zhalloran I can't seem to reproduce this. Can either of you?

**Comment by jshorland** [comment]
https://app.intercom.io/a/apps/hl5rfiga/inbox/all/conversations/6060959927

**Comment by jshorland** [comment]
Another user experiencing problems with image upload: https://app.intercom.io/a/apps/hl5rfiga/inbox/unassigned/conversations/6089553793

**Comment by jshorland** [comment]
Another user experiencing the issue: https://app.intercom.io/a/apps/hl5rfiga/inbox/all/conversations/6046609134

**Comment by willdoran** [comment]
This is not occuring for me on ushahididev.com but it is slow, on the deployment Chris linked to I am getting a fail at the Gateway:
Request URL:https://hillclearinginpenang.api.ushahidi.io/api/v3/media
Request Method:OPTIONS
Status Code:504 Gateway Time-out
Remote Address:104.130.102.242:443

This seems to be a system issue, I'm afraid I'm not sure where to look @rjmackay @zhalloran @tuxpiper would be best suited.

**Comment by tuxpiper** [comment]
I haven't been able to reproduce. I uploaded and created a post with my test kitten jpeg in my .io deployment without any transfer problems.

![test-kitten](https://cloud.githubusercontent.com/assets/467393/18814616/6fd4dd4a-8319-11e6-84ff-0c1952c4138a.jpeg)

Any specific steps to follow? Maybe this was a transient problem?

**Comment by jshorland** [comment]
Hey all, after the server reboot, she says she is able to see her previously uploaded pictures, but not upload NEW pictures. She says she tries to click upload, waits about 5 minutes, clicks save, but then sees nothing on the post.

**Comment by zhalloran** [comment]
It's possible that these new files are oversized. There's a practical limit based on our setup.

**Comment by jshorland** [comment]
A couple of issues:
- we don't have sufficient logging to immediately ID the error
- timeouts on media endpoint
- SSH was failing, couldn't connect to port22 on either API server
- Issues with performance on each of those servers
- all of this indicates it could have been a load issue. Rebooting fixed the error.

Potential solutions:
- completely side step API servers and post directly to CDN storage (probably not worth building out as of today)
- if this continues, it may make sense to look at re-engineering this process
