### ISSUE TITLE
adding new custom posts on the platform.

### ISSUE THREAD

**Issue by spiral99** [ushahidi/platform#1409]
The ability to add new posts in V3 should be easier to access it took me a while to realize that I could add custom posts using the survey feature. I would suggest an icon on the development homepage be added for that.

**Comment by brandonrosage** [comment]
@spiral99 Could you clarify something for me? Are you saying it's difficult to figure out how to add a post to the deployment? Or are you saying it's difficult to figure out how to create a (customized) survey to collect data from people?

**Comment by spiral99** [comment]
Yes adding customized surveys is what I was trying to convey. The moment you create your first deployment the default survey presented is basic post and there is no indication of where and how a user can add a new survey.

**Comment by jshorland** [comment]
Moving to icebox as I think we have solved some of this, and will solve more once free form surveys are built
