### ISSUE TITLE
Speed up survey creation

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1417]
When I create a new Survey field form, the cursor should automatically enter the name field form so I can start typing. Hitting enter should make it save. The default name of the form should not exist, and it should not let you save until you create one.

**Comment by caharding** [comment]
Hitting ESC on keyboard should X out of a new field form

**Comment by jshorland** [comment]
We should find other bahviours like this and fix them all at once.

**Comment by jshorland** [comment]
Closing in favor of #1335
