### ISSUE TITLE
When I click on a pin towards any edge of the map, the pop up is hidden

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1418]
Expected behavior:
the map (or popup) recenters so I can see the pop up

See screenshot
![screen shot 2016-09-28 at 6 58 22 pm](https://cloud.githubusercontent.com/assets/3224856/18938466/93f48216-85ad-11e6-9494-1f7d327046f3.png)

**Comment by jshorland** [comment]
This still seems to be happening sometimes. Should I be doing something differently?

**Comment by rjmackay** [comment]
I'm not sure - there's definitely something buggy going on with our maps :/

**Comment by rjmackay** [comment]
Maybe revisit this along with #1411
