### ISSUE TITLE
Open source deployment not counting posts properly, won't export

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1419]
### Expected behaviour

After @saheleasy adds a basic post to "basic survey", that count should increase and reflect that. 
Clicking export never actually exports. ... buttons forever
### Actual behaviour

Instead, it is appearing in "unknown" count
Exported file should start downloading
### Steps to reproduce the behaviour/error

Add basic post
Submit
See count
click export

http://ushahidi.umt.ly/views/map
I could not replicate this behavior on qa.ushahididev.com

![errorr 205](https://cloud.githubusercontent.com/assets/3224856/18963597/8b6d9ede-862a-11e6-9b85-f96779019212.JPG)

**Comment by jshorland** [comment]
Just FYI -- the open source user is now on ushahidi.io

**Comment by rjmackay** [comment]
@saheleasy it looks like your server is throwing 500 errors for some API requests. My best guess is this is timing out. Can you check your logs in application/logs/ and let us know what errors you're seeing?

**Comment by saheleasy** [comment]
Www.umt.ly/platform/application/logs/2016/09.zip

This is the log folder it contains tow files

**Comment by saheleasy** [comment]
I can give you the access for my cpanel if you think you can fix it for me

**Comment by saheleasy** [comment]
@rjmackay i can give you my access details for my cpanel

**Comment by rjmackay** [comment]
@saheleasy sorry I missed your reply. I can't find that file http://www.umt.ly/platform/application/logs/2016/09.zip doesn't work.

**Comment by rjmackay** [comment]
@saheleasy I'm going to close this out - feel free to reopen or comment if you have further info so I can debug
