### ISSUE TITLE
Adding a user to the platform should send that user an email with a link to reset their password

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1421]
### Expected behaviour

When I add a user to my deployment, that user has no idea they've been added unless I tell them and give them their dummy password I assigned to them. 
### Actual behaviour

An email sends to them with a link to reset their password and then login to the deployment.
### Steps to reproduce the behaviour/error

Add user
do nothing.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-661

**Comment by jshorland** [comment]
Need to scope new flow for this.

**Comment by jshorland** [comment]
As we see more and more orgs coming onto the platform, this is significantly increasing in priority. We MUST get this done soon.

**Comment by jshorland** [comment]
To do next: @jshorland will write user stories here.

**Comment by jshorland** [comment]
@jshorland DO THIS TODAY!

**Comment by jshorland** [comment]
Additionally from previous issues #290:
- Users were surprised that there was no step requiring email confirmation during sign up, and were concerned that anyone could use their email address to create an account.
- I would argue that the user should receive an email and approve a sign up token from it before authorize to access.

**Comment by jshorland** [comment]
User stories:
- as an admin creating my first deployment, I want to receive a confirmation email as a security measure with a link that automatically logs me in when I click it. 
- as a user with the permission to manage users, I want any new user I create to receive an email invitation/confirmation to the deployment with a link to login

**Comment by webong** [comment]
Hello @tuxpiper  @rowasc @Angamanga ... since I have been able to achieve this https://github.com/ushahidi/platform/issues/3110 ... was thinking I could also work on this.

**Comment by rowasc** [comment]
That'd be fantastic. Also thank you so much, #3110 is a life saver <3
