### ISSUE TITLE
Notifications for savedsearch not sending on .io

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1427]
### Expected behaviour
- When a user creates a savedsearch
- Enables notifications for their account
- Set's get notifications for the savedsearch
- Subsequently a new post is added that is covered by the saved search, the user should receive a notification via email
### Actual behaviour
- Currently no notification is received
### Steps to reproduce the behaviour/error
- Issue reports from palestine-reports.ushahidi.io but reproduce on quakemap.ushahidi.io
- Steps are identical to expected behaviour

**Comment by willdoran** [comment]
@zhalloran would you have time to look at this with me? I don't really know what the issue is and I think you got closer.

**Comment by zhalloran** [comment]
@willdoran I checked our SMTP relay provider. There are no records of saved search notifications being sent in the logs. I still believe you need to configure the email for outgoing notifications for it to work. When I have a moment I'll check the postfix logs for anything weird. I didn't see anything the last time I looked.

**Comment by willdoran** [comment]
@zhalloran how do you mean configure email for outgoing notifications? There may be a step I'm missing but both palestine and quakemap had email contacts setup for notifications I think. Were they missing something additional or was the email setup wrong?

**Comment by rjmackay** [comment]
@willdoran notifications use the email data provider.. if thats not set up correctly for outgoing email it can just fail.

**Comment by willdoran** [comment]
@rjmackay ah....that's definitely not documented

**Comment by jshorland** [comment]
Update: I'm definitely getting notifications from ushahididev.com in a more timely manner than before

**Comment by jshorland** [comment]
Update: I'm receiving email notifications in about 20 minutes with my alert that's set up for usaelectionmonitor.ushahidi.io. I am NOT receiving any SMS alerts even though I signed up for them.

**Comment by willdoran** [comment]
@jshorland What provider did you have setup for sms?

**Comment by jshorland** [comment]
Twilio. This is on usaelectionmonitor.ushahidi.io

**Comment by willdoran** [comment]
I think this was a config issue, I think it can be closed @jshorland

**Comment by jshorland** [comment]
I'm going to retest this to be sure. If it's still not fixed, this should be a priority.

**Comment by Angamanga** [comment]
I'll QA this!

**Comment by Angamanga** [comment]
I tested this locally and doesn't get it to work. I have: 
1. Added an emailprovider for email-datasource (both outgoing and incoming)
2.  Added an twilio-account for twilio-datasource
3. Created a saved search and added an email-address and phone number for notifications
4. Created and published a post that matches my saved search
5. Ran the scripts for sending notifications from inside the vagrant:
``` 
./bin/ushahidi savedsearch
./bin/ushahidi notification queue
./bin/ushahidi dataprovider outgoing 
 ```
Getting emails through ``` ./bin/ushahidi dataprovider incoming ``` works. I have checked and double-checked the configs and all credentials and I am pretty sure they are correct.  Am I still missing some configs?

**Comment by Angamanga** [comment]
I tested this on http://qa.ushahididev.com and there I actually got a notification after about 45 mins. I assume this issue is fixed and my problems above was config-related. However, since we all seem to have been a bit confused about the config, we should consider improve the documentation/support-docs for this part? That might be a separate issue though? @willdoran @rjmackay @jshorland

**Comment by rjmackay** [comment]
I'll close this out for now.
