### ISSUE TITLE
Allow HTML in long text and short text field on survey

### ISSUE THREAD

**Issue by chrisdubia** [ushahidi/platform#1430]
Would be great to allow HTML  in the long text and short text field. 

Our users share stories and solutions about global issues and many of their solutions are videos. 
- allow html
- allow iframe embed
- Work on integration with https://ziggeo.com/ as the video would be hosted on their servers.  Open source tool that supports the recording and playing of videos.  Integrates  nicely into a WYSWIG editor and appears as an option for content authoring

**Comment by rjmackay** [comment]
I think we allow markdown right now, not full HTML but some limited markup
