### ISSUE TITLE
Not clear that title and description are required.

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1433]
### Expected behaviour
There should be asterisks beside them by default so I know I have to fill them in.

### Actual behaviour
There are no asterisks, but I can't save my post. 

### Steps to reproduce the behaviour/error
go to ushaverse.ushahidi.io, fill in "home base" survey and leave out the description. Try to save

Can we add asterisks for now? #1335 will provide a more elegant overall solution to not requiring "title" and "description" by default, but users currently don't have any indicator why their posts aren't saving.

**Comment by willdoran** [comment]
@jshorland Not 100% sure when but I remember adding this. It is working for me in qa, it might just be waiting to be deloyed to .io or it might have gone up in the most recent version. Could you retest on .io and on qa?

**Comment by rjmackay** [comment]
Asterisks are already there on production

https://www.dropbox.com/s/mc6d0jfj79syz6t/Screenshot%202016-10-22%2009.58.26.png?dl=0
