### ISSUE TITLE
Image uploading doesn't show progress, and saving post doesn't wait for image to save

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1434]
### Expected behaviour

When I am uploading an image, I can see upload progress, and saving the post also saves the image.
### Actual behaviour

When I upload an image there is no feedback about upload progress.
If I click save while the image is uploading, the post is saved but the image is not.
If I click save without clicking upload, the post is saved but the image is not.
### Steps to reproduce the behaviour/error

Refs #1408

**Comment by rjmackay** [comment]
Solution:
- Provide simple 'loading' style feedback when upload
- Make sure the image is always uploaded when a user hit save on the post

**Comment by willdoran** [comment]
Test these changes by:
- [ ] On a post with an image field, add an image and click save
- [ ] Edit the above post to delete the image, you should be asked to confirm\

After deleting image the following should be tested:
  - [ ] Save post
  - [ ] Add a new image and save post

After creating a post with an image the following should be tested:
  - [ ] Replace current image and cancel
  - [ ] Replace current image and save

Caption:
  - [ ] Test saving an image without a caption then editing and adding one
  - [ ] Test editing a caption only
  - [ ] Test changing image and caption
  - [ ] Test editing caption then clicking cancel

**Comment by jshorland** [comment]
I'm not able to save post after uploading the image. After clicking save, there doesn't appear to be anything happening. I cannot test other changes until I'm able to save the original post.

**Comment by willdoran** [comment]
@jshorland I don't know why but the code was broken. It should be fixed now, and should deploy shortly.

**Comment by jshorland** [comment]
Posts are saving with images correctly. 

- I was asked to confirm, but the message read "are you sure you want to remove this notification" when it should read "are you sure you want to remove this image?" (see gif upload)
- After replacing the photo and saving, it returns me to the post detail where I see a weird "46" under photo. I have no idea what this is or where it came from? (see screen grab upload)
- After editing ONLY the caption (I already had a caption written) and clicking save, I'm taken back to post detail, but it doesn't show the picture or the caption. See second gif upload. 
-----> after going BACK to edit mode, the photo is gone completely
that's it for now. all else looks good.

![screen capture on 2016-10-25 at 19-00-37](https://cloud.githubusercontent.com/assets/3224856/19710935/e1c7d29c-9ae6-11e6-9f7e-b14fe172bff8.gif)
![screen capture on 2016-10-25 at 19-09-25](https://cloud.githubusercontent.com/assets/3224856/19710939/e77df842-9ae6-11e6-8e3a-b4fe91e65550.gif)
![screen shot 2016-10-25 at 7 03 36 pm](https://cloud.githubusercontent.com/assets/3224856/19710944/f378a05c-9ae6-11e6-8433-c1ad51bad625.png)

**Comment by jshorland** [comment]
Punting back to you @willdoran

**Comment by willdoran** [comment]
@jshorland I will look at these in the morning first

**Comment by jshorland** [comment]
All three issues I've listed fixed and pass QA. I'm doing a little more testing around other features and then will move to waiting to deploy as long as no others arise.
