### ISSUE TITLE
Allow changing map icons

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1436]
### Expected behaviour

I can set different map icons for posts, based on a posts survey.. or category. 
### Actual behaviour

Can't set map icons, only color.

Refs ushahidi/platform#1368 

Initially this probably just needs to be icons based on survey, categories have other complications  that are being handled in ushahidi/platform#1397

Aha! Link: https://ushahiditeam.aha.io/features/PROD-660

**Comment by jshorland** [comment]
Moving this back to backlog. We won't be able to to get to it this quarter.

**Comment by jshorland** [comment]
Moving to icebox. this is so low of a priority IMO right now, unless a paying client request pops up for it.

**Comment by Erioldoesdesign** [comment]
Adding in comments from my MOZOL 6 project (finally)

Platform user says this could be useful for outside campaign uses but it's not essential. More useful would be colour coding (which exists but they struggled to discover)
They might be interested in icons that describe the type of offence (speech bubble as hate speech etc.)
They are most interested in this if it helps/encourages other responders understand and write their own responses.

**Comment by shivam2407** [comment]
I can give this a go if no one is working for it.

**Comment by renujain31** [comment]
Hey @rowasc , is this issue still open? I would like to work on this one. But I couldn't see where is this happening. Can someone give me the detailed steps to reproduce. Thanks.

**Comment by rowasc** [comment]
@renujain31 this is still a little far from full spec, would you be interested in https://github.com/ushahidi/platform/issues/3611 instead? It's a full stack issue, but if that's not a problem it'd be a great fix to have. 
This other issue is also quite large but may be interesting to you: https://github.com/ushahidi/platform/issues/600#issuecomment-484030829 (look out this comment in particular as it gives a lot of insight on how to think about the problem)
LMK, I'll assign as long as it's something that's close to spec.
