### ISSUE TITLE
Deleting collections on the platform.

### ISSUE THREAD

**Issue by spiral99** [ushahidi/platform#1438]
### Expected behaviour
There should be a feature to delete collections.
### Actual behaviour
Deleting collections that had initially been created is not possible.
### Steps to reproduce the behaviour/error
![2016-10-13](https://cloud.githubusercontent.com/assets/7393879/19351111/1780f324-9163-11e6-92a9-cdf1b677d04d.png)

**Comment by rjmackay** [comment]
This is actually possible just not from the list view.
If you click on a specific collection, then open the menu ('...' icon) there's a delete button there:

<img width="268" alt="screenshot 2016-10-20 08 25 21" src="https://cloud.githubusercontent.com/assets/7965/19534108/077b43da-969f-11e6-965a-3b19a14ca7b0.png">
