### ISSUE TITLE
Replace post list pagination with 'Load more'

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1441]
- Replace pagination on post-list with 'load more' button as seen in our designs
  http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/timeline.html
- Increase the _page size_ to 20
- Clicking 'load more' should load an additional 20 posts into the view, while leaving the existing posts in the view

**Comment by jshorland** [comment]
@rjmackay Two things:

1. when navigating to post detail from timeline screen with several "load mores" performed, I deleted the post and was auto navigated back to timeline. Is it possible to place me where I was in the timeline BEFORE going to post detail? 
2. After loading more about 17 times, scrolling up was a chore. a quick "back to top" would be helpful

I realize these two might be out of scope of the original issue so happy to create new issues for them and work them into a later sprint.

**Comment by rjmackay** [comment]
1. We can't do this easily. We had the same issue with paging too.. its definitely something we should look into, but not something I can do in a day.

2. I'd rather send that back round to @brandonrosage and get something properly designed for a later sprint.
