### ISSUE TITLE
Importing post should create a new collection

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1444]
### Expected behaviour
- [x] Importing posts should create a new collection, when you click on "See imported posts" you should be taken to the collection
- [x] The confirmation slider on import success should show a "Import new csv button"

**Comment by jshorland** [comment]
Can't see the "import to which survey" selection box: http://d.pr/i/Yzr8

**Comment by rjmackay** [comment]
This works for me. We could improve a little by creating a collection of imported posts, even when the import fails part way through.

**Comment by rjmackay** [comment]
@jshorland I've deployed this to production - it was blocking too much work.
Leaving this ticket here in case you want to do some final checks

I've logged ushahidi/platform#1448 to issues with handling import failures but nothing in there is a new issue, so I didn't think it should delay releasing.

**Comment by jshorland** [comment]
all good. passes QA
