### ISSUE TITLE
Better handling of CSV import failures

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1448]
### Expected behaviour

When I import a CSV and it fails I expect either: 1. the import is rolled back or 2. I am provided a collection containing what _was_ imported
### Actual behaviour

I'm presented an error, and some posts are left imported.. but no collection is created.
### Steps to reproduce the behaviour/error

Related issue https://github.com/ushahidi/platform/issues/2839

Aha! Link: https://ushahiditeam.aha.io/features/PROD-659

**Comment by rjmackay** [comment]
@jshorland not sure what the ideal solution is here. This is really a follow up to #1444

**Comment by jshorland** [comment]
Ideal solution scope:
1. user needs to see which rows had errors and what the error was
2. create collection of successfully imported posts that user can navigate to
3. should try to import the rows after the first error up to 25 errors 

@brandonrosage do we have designs for errors beyond our notifications? If not, we'll need a design for that. it shouldn't involve major changes as we'd like to move this forward relatively quickly.

Other important things to consider:
- timeouts --> what if import is taking too long and it times out?

**Comment by brandonrosage** [comment]
I'd suggest the following solution:

## If the user is viewing the Import progress screen...

![import progress](https://cloud.githubusercontent.com/assets/1136279/19744067/7bc478fa-9b91-11e6-9166-c92bc61a91bb.png)

...and the process encounters an error. The sheet here should be updated with content like the following:

![import error](https://cloud.githubusercontent.com/assets/1136279/19744132/be0b8e74-9b91-11e6-836d-96ca4a3d5984.png)

This would hold the successful records until they had made a choice about whether to keep them or not. If the user elected to "Keep (the records)," an additional button would appear:

![import and keep](https://cloud.githubusercontent.com/assets/1136279/19744151/d80a6246-9b91-11e6-9a02-75712689e25d.png)

Selecting "View 88 imported records," the Collection would be created, populated, and the user would be taken there.

Selecting "Import revised CSV file" would return them to the start of the CSV import process.

## If the user navigated away from the Import progress screen...
...and the process encountered an error in the background, they'd be delivered a message:

![error message](https://cloud.githubusercontent.com/assets/1136279/19744492/5f6c87a4-9b93-11e6-8567-28856edf9d9d.png)

Selecting "Dismiss" would effectively bail on the process, removing whatever could be successfully imported (which is the default behavior, anyway). Selecting "Learn how to fix it" would take the user to the aforementioned "Your import had some problems" detail screen.

-------------

## RE: Timeouts
I think this kind of error would follow the same convention as described above.
