### ISSUE TITLE
Problems Installation on Heroku - API Deployment

### ISSUE THREAD

**Issue by Nesp** [ushahidi/platform#1450]
### Expected behavior
The [manual](http://ushahidi.s3.amazonaws.com/downloads/community_docs/Ushahidi_Platform_v3_Manual.pdf) suggests using a link to create a new Ushahidi platform deployment starting from this [link](https://heroku.com/deploy?template=https://github.com/ushahidi/platform/tree/release). Once created a new name and filled all the information, what should happen is shown in the following figure: 
![image](https://cloud.githubusercontent.com/assets/12881499/19445639/7700364a-9495-11e6-8e95-46828155a151.png)

### Actual behavior
What actually happens is: 
![image](https://cloud.githubusercontent.com/assets/12881499/19445871/6604c210-9496-11e6-9b60-2a76826f34b9.png)

And then the process does not go on with the following items. 

Could you help me, please?

**Comment by jshorland** [comment]
@aoduor the PDF manual currently points to the wrong version of the code. Where does the PDF generate from? I want to make sure we keep it updated at it's source

**Comment by rjmackay** [comment]
@Nesp can you go to https://github.com/ushahidi/platform and click on the 'deploy to heroku' button there? That should deploy the current version of the code, the link in the manual points to an old version.

**Comment by Nesp** [comment]
@jshorland @aoduor  also the instructions on the[ website](https://www.ushahidi.com/support/install-ushahidi#installing-on-heroku)  are maybe not updated

@rjmackay thank you very much, indeed that worked :)

**Comment by aoduor** [comment]
Thanks for the heads up @Nesp @jshorland.

Jess, i'm emailing you the doc link we generate the pdf from

**Comment by rjmackay** [comment]
@Nesp glad that worked. I've fixed our website docs so I'll close this
