### ISSUE TITLE
Image Description Disappears when marker on map is clicked on.

### ISSUE THREAD

**Issue by KrisKuri** [ushahidi/platform#1451]
### Expected behaviour
The image description should appear when the marker on the map is clicked on.

### Actual behaviour
The Image and image title appear,but the image description has stopped appearing.

### Steps to reproduce the behaviour/error
The image description was working a few hours ago, on clicking the image, the description doesn't appear , however it appears in the timeline.
![pastedimage](https://cloud.githubusercontent.com/assets/19805081/19448403/5f2bb548-94aa-11e6-9ab6-2338e48410dc.png)
![image 2](https://cloud.githubusercontent.com/assets/19805081/19448411/65687bd0-94aa-11e6-860d-acddb971026b.JPG)

**Comment by rjmackay** [comment]
This is the result of a styling change in the latest release. Post cards on the map are now fixed height but should 1. show post content above the image and 2. show a 'show complete post' button

<img width="328" alt="screenshot 2016-10-18 10 37 37" src="https://cloud.githubusercontent.com/assets/7965/19456670/063385ea-951f-11e6-8e1c-b9c68367ad97.png">

**Comment by PenangHillsWatch** [comment]
Hi rjmackay,
Thanks for your update on that. However from the user end, I feel that this is a very unusual feature as the photo is cut in half  and there is no tab to show full post in my deployment. Please investigate and if possible can you revert to the original post features? It's much better that way for a user as information is available on one click rather than two clicks as it is now.

**Comment by PenangHillsWatch** [comment]
Hi rjmackay
Any update on the status of this issue? I am eagerly awaiting your reply :) And on a side note are there any other changes from this styling change? One thing you could consider would be changing the colour of pin points according to their categories. Would be a very useful and powerful feature which your users would anticipate.

Regards,
Penang Hills Watch

**Comment by jshorland** [comment]
@brandonrosage this appears broken. Any comments/advice on exactly where it's broken so we can fix quickly? @penanghillswatch has a demo on oct 31 and I'd like to get it fixed and pushed before that.

**Comment by jshorland** [comment]
@penanghillswatch -- Thanks for the feedback on coloring map markers by categories. it's not something that will be dealt with before your demo, to manage expectations, but we are thinking hard about custom pin coloring!

**Comment by willdoran** [comment]
When this is ready for implementation it can be assigned to me and I'll update the client side

**Comment by PenangHillsWatch** [comment]
Hi has there been any update on the issue? I only have less than 72 hours till our launch and would appreciate if something is done the soonest.
Sincerely,
Penang Hills Watch

**Comment by willdoran** [comment]
hi @PenangHillsWatch, I will do my best to get this fixed today

**Comment by willdoran** [comment]
hi @PenangHillsWatch, we believe that this is fixed, and we should be able to push it out in our next release, which will hopefully be today

**Comment by PenangHillsWatch** [comment]
Thank you.That is just what I wanted to hear @willdoran .Please let me know as soon as you do. I am eagerly waiting.

Thank you once again

**Comment by jshorland** [comment]
Fixed. Passes QA.

**Comment by willdoran** [comment]
@PenangHillsWatch this is now deployed
