### ISSUE TITLE
UX design for embeded video on posts

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1452]
### Expected behaviour
- The user should be able to provide a link to a youtube or vimeo video, select its type and save
- The detail page should display the video embed in an iframe
### Actual behaviour
- This is the current version I made for fun: http://d.pr/v/zeqJ

**Comment by rjmackay** [comment]
As mentioned on our call ideally this shouldn't extend the media input type, rather it should extend varchar but have a custom validator and input.

**Comment by willdoran** [comment]
@rjmackay yep, though this ticket is I think for mocking a UI for the video input

**Comment by brandonrosage** [comment]
@willdoran I intend to stage a flow that removes the need to select a service (e.g. YouTube), and instead sniffs the URL you provide and does the rest. If it can't sniff a known service, it'll ask the user to include all the embed HTML. 

I'll do the sniffing in the PL for YouTube and Vimeo. But is that kosher?

**Comment by willdoran** [comment]
At the moment there is a function which converts the URLs given to the
embed format, each one has a slightly different format. Pulling the
source directly out of the URL is a good idea. We can clean them or
provided html before saving it. It's a bit dodgy to allow users to
insert html code. I'll check if we can adequately sanitize it to make it
save. It's a good idea though so I think it's worth trying to get it to
work.

**Comment by rjmackay** [comment]
I'd be very nervous about allowing users to give us the embed HTML. I'd rather we just supported a set list of services and let users know if they URL they provide doesn't match.

**Comment by brandonrosage** [comment]
@jshorland, @willdoran, and @rjmackay: How do y'all feel about [the following UX](http://d.pr/i/UXxV/5LOebrjN)?

![Video embed demo](https://d1zjcuqflbd5k.cloudfront.net/files/acc_450437/UXxV?response-content-disposition=inline;%20filename=Screen%20Capture%20on%202016-10-28%20at%2009-55-01.gif&Expires=1477666918&Signature=Tp43jyqEJ1IA18rQi727B3X2cLViC4W~rPSG9DItgJF1Plhq6aE4bd6ysp31rDo0Z6wBGGv7jQpsDYL8cVkb663PKTFvDEtQVKjoiBZjM95ovs26PhpTb~E5MHM74DaMc0tC253kOJ3aD6La8eLtEGpwQ77giBlU7BI-0jBx95U_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

**Comment by willdoran** [comment]
@brandonrosage wow - this looks amazing :dancing_men:

**Comment by willdoran** [comment]
Test these changes by:
- [ ] Create a new survey
- [ ] Add to this survey a video embed field
- [ ] Save survey
- [ ] Add new post of the above survey type
- [ ] Set the field to junk and attempt to save
- [ ] Set field to youtube url of different types and save
- [ ] Set field to vimeo url of different types and save
- [ ] Attempt to view video on Post detail field
- [ ] Attempt to edit
- [ ] Change url and save

**Comment by jshorland** [comment]
No video embed field to add from "add field" menu

**Comment by willdoran** [comment]
@jshorland The first two are fixed, I think the last one is for @brandonrosage, hopefully I didn't make a mistake in the html.

**Comment by willdoran** [comment]
No wait the last one is totally my fault, fixing now

**Comment by jshorland** [comment]
Confirmed. Passes QA. lets get this shipped.
