### ISSUE TITLE
translations cause weird design flaws

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1461]
After translating to portuguese, the left side icon descriptions bled off their side bar. @brandon this isn't urgent, logging as p2 for now.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-658

**Comment by jshorland** [comment]
![screen shot 2016-10-26 at 7 47 31 am](https://cloud.githubusercontent.com/assets/3224856/19730968/bb00938c-9b50-11e6-91f2-26c91fcf8e5f.png)

**Comment by rjmackay** [comment]
This is probably going to get worse in Arabic, Mandarin or languages with non latin characters too - could we make a point to test those?

**Comment by rowasc** [comment]
<img width="231" alt="Screen Shot 2019-06-07 at 18 29 57" src="https://user-images.githubusercontent.com/2434401/59134640-49cce880-8952-11e9-87b5-b6d89b9e035e.png">
 adding screenshot to verify that this is still happening

**Comment by Erioldoesdesign** [comment]
Yikes. Hopefully this can be solved by the UI refresh with styling...I'm not sure how this CSS structured but the menu bar should be able to be contextual according to the text length...

Let's shelve this until post UI refresh and then see if it still happens.
