### ISSUE TITLE
Add share functionality

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1465]
### Expected behaviour
- Share menu exists in client
- Share menu incorporates export
- Share menu has embedable option
- Implements http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/map.html

**Comment by rjmackay** [comment]
@willdoran I'm seeing JS errors in the console from facebook:
https://sentry.io/ushahidi/platform-client-staging/issues/174672350/

**Comment by jshorland** [comment]
YES! passes QA. moving to waiting to deploy.
