### ISSUE TITLE
Add share for post detail/create

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1466]
### Expected behaviour
- User can share current post detail
- User can share survey create

### Actual behaviour
- Not implemented
### Steps to reproduce the behaviour/error

**Comment by jshorland** [comment]
basic embeds pass QA. Facebook and twitter passes QA.

**Comment by brandonrosage** [comment]
Markup revision: The "Share" button in the toolbar for Post Add should include the class `button-flat`.

**Comment by jshorland** [comment]
thanks, @brandonrosage I'll move this back to QA

**Comment by jshorland** [comment]
button class is correct. passes QA, moving to waiting to deploy.
