### ISSUE TITLE
Survey fields: Don't assume Title & Description

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1469]
Surveys should no longer assume "Title" and "Description" fields. Users should be able to name and configure all fields -- no matter which ordered position they're in -- however they like.

In an effort to lay the foundation for [a larger "Free-form surveys" solution](https://github.com/ushahidi/platform/issues/1335#issuecomment-256446871), we need to scope this one of two ways:

**1. Make surveys fully customizable**
This would call for new surveys to be populated with only one field -- an "Untitled" short text field -- that can be turned into any of the available field types. 

It would also call for any existing surveys with Title and Description fields to treat them as equal citizens: They can be re-ordered and changed into different field types (naturally requiring us to re-format existing values appropriately, and warning deployers of that implication before confirming such a change).

It would also call for the addition of a single toggle switch/checkbox attached to each field that indicated whether that field should be included in "postcards" for that survey.

Finally, it'd call for postcards to honor this flexibility by adopting the logic [outlined in the full "free-form surveys" solution](https://github.com/ushahidi/platform/issues/1335#issuecomment-256446871), where they display the values for fields that are configured to be shown in postcards (using the same order directed by the survey overall).

**2. Just allow users to rename the 'Title' & 'Description' labels**
Their respective field types would remain fixed, as short- and long-text fields. And they'd continue to be fields you couldn't re-order.

-----

Demonstrations of each of the aforementioned field controls aren't yet staged in the PL, but can be very quickly depending on the path the development team chooses to take here.

**Comment by rjmackay** [comment]
@willdoran do you think option 1 is doable in the next 2 weeks? Would option 2 be much better?

**Comment by rjmackay** [comment]
Complications:
- SMS messages have no title
- Data sources
     - Where do we save sms message/email title and subject?
- Searching ?q=blah now needs to search all text/varchar fields
- Converting unknown post to a survey
    - No longer guaranteed to have title + description field
    - Need to map fields between SMS and survey etc. And do this bulk
- Post export
    - No common fields between surveys anymore, but should be fine
- Can I just save a totally empty post now? (ie. not required title + description)

**Comment by rjmackay** [comment]
@brandonrosage @jshorland I talked with @willdoran and it looks like Option 2 is the only thing feasible in our timeline. As we went through it we realised the huge complication is how where does data from SMS/Email go if we don't have fixed title and description fields..

**Comment by brandonrosage** [comment]
Makes sense. I hope [my answer to your question](https://github.com/ushahidi/platform/issues/1335#issuecomment-258284288) about this issue lays out a reasonable solution for Option 1 and beyond.

**Comment by willdoran** [comment]
- [ ] Create a new survey
- [ ] Edit the Title and Description field labels
- [ ] Ensure it saves
- [ ] Create a new post based on this survey and ensure the field labels appear as set
- [ ] Edit an existing survey 
- [ ] Edit the Title and Description field labels
- [ ] Ensure it saves
- [ ] Edit an existing post based on this survey and ensure the field labels appear as set
- [ ] Create a new post based on this survey and ensure the field labels appear as set

**Comment by jshorland** [comment]
BOOM. PASSES QA. let's get this shipped!
