### ISSUE TITLE
Append "Create new survey" button-link to survey filters

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1470]
The "survey filter" pattern should include a "Create new survey" button-link, as seen here:

![Create new survey](https://cloud.githubusercontent.com/assets/1136279/19734465/444b6e16-9b6d-11e6-91a4-935e7d3ed06d.png)

It'd take users to the configuration screen for a new, "Untitled" survey.

It's currently staged in the `f-freeformsurveys` branch of the PL.

SAMPLE: [Timeline layout](http://preview.ushahidi.com/platform-pattern-library/f-freeformsurveys/assets/html/5_layouts/timeline.html)

**Comment by rjmackay** [comment]
Test on  http://qa.147--create-survey-button.ushahidilab.com/

**Comment by jshorland** [comment]
passes QA
