### ISSUE TITLE
Remove "Filter by survey" button from non-embed views

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1472]
### Expected behaviour
On small screens, the "Filter by survey" button should only appear on Map and Timeline _embeds_. And the searchbar should only appear on Map and TImeline non-embed views.

### Actual behaviour
On small screens, the "Filter by survey" button (and the searchbar) is appearing on all Map and Timeline views. Only the searchbar and share buttons should appear on non-embed views.

![image](https://cloud.githubusercontent.com/assets/1136279/19941093/ceb1bd1e-a0fc-11e6-82b0-d125115900ca.png)

### Steps to reproduce the behaviour/error
VIew any deployment's Map on a small screen.

### Solution
Remove the "Filter by survey" button and toolbox from non-embed views.

**Comment by brandonrosage** [comment]
I've also staged a small CSS tweak to improve how search input render in iOS. Please let me know how I can publish that change so that it makes it out in this push.

**Comment by rjmackay** [comment]
@brandonrosage what branch is that on?

**Comment by brandonrosage** [comment]
[`develop`](https://github.com/ushahidi/platform-pattern-library/commit/b29e07db8395b20078666cb1a4d9b508ccbbad93)
