### ISSUE TITLE
SMS Autoresponse should be shown in message thread

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1473]
### Expected behaviour
- SMS auto responses should be shown in message thread

### Actual behaviour
Only manually sent responses show up, auto response doesn't create a message in the backend.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-657

**Comment by rowasc** [comment]
I think we do this now but I'm not entirely sure if it was just for targeted surveys, need to check

**Comment by Erioldoesdesign** [comment]
Do you mean in the 'conversation with author' section?

**Comment by rowasc** [comment]
yes
