### ISSUE TITLE
Login screen pops up every time i click anywhere in the deployment if I'm not logged in

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1475]
### Expected behaviour
If I am just viewing the deployment, I don't want to be annoyed by the login screen. I want to filter and view data without interruptions throughout, with one login screen at the start.

### Actual behaviour
It pops up every time I click on a filter in the deployment. 

### Steps to reproduce the behaviour/error
Navigate to usaelectionmonitor.ushahidi.io
Do not login at first. 
Continue by trying to filter published data.

**Comment by jshorland** [comment]
Additional notes -- i believe this either progressively gets worse the more you're on the site OR it starts happening more and more frequently after you login and then logout and stay logged out. increasing to p0

**Comment by willdoran** [comment]
@jshorland I can't reproduce this locally but I can see it happening on the deployment though ONLY when I click on the timeline. It's pretty strange. Not sure, why. I'll keep looking

**Comment by rjmackay** [comment]
This happens when trying to load the contact associated with twitter or SMS report (I think). I've added a flag to ignore permission errors loading contacts

**Comment by jshorland** [comment]
Currently on usaelectionmonitor.ushahidi.io, the login screen appears whenever i navigate to timeline mode, no matter where i am in the deployment, or how long i've been on the page.

**Comment by jshorland** [comment]
Might be a caching issue -- working properly in incognito mode

**Comment by aoduor** [comment]
Guys - this is still happening :(. 

Try accessing https://brinland.ushahidi.io

**Comment by willdoran** [comment]
I think this only happens in browsers and for deployments someone has been previously logged into. I can't reproduce it with the above example. It may be a persistence of a session token. I think the logic maybe that if you were logged in before, are now logged out then you probably want to log back in.
I can look at changing it so that when you're logged out it only offers login when you click sign in.

**Comment by Angamanga** [comment]
@aoduor is this still happening? I tried to login to brinland but cannot reproduce it there or locally...

**Comment by jshorland** [comment]
@aoduor I'm not replicating this either. Still a problem anywhere that you've seen?

**Comment by jshorland** [comment]
Closing. not an issue anymore.
