### ISSUE TITLE
free trials

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1476]
Had about 50% of SaaS-interested sales leads ask for a free trial of a week or two. Would be great to offer this.

**Comment by jshorland** [comment]
Initial scope: https://docs.google.com/document/d/1n0uk_ljwbNHxUeZDR2BZNccauaHVsXCMhE5ZeyQdxfc/edit# 

@rjmackay mind taking a look when you get a chance? no rush, but would like to get designs and spec tee'd up for Q1

**Comment by rjmackay** [comment]
I've commented on the doc. @jshorland lets discuss once devs move back to platform

**Comment by jshorland** [comment]
We *might* want to include this in our enterprise product.

**Comment by rowasc** [comment]
This was handled through demo (pricing changes 2018) . Closing
