### ISSUE TITLE
After deleting a post from the map mode, it auto directs me back to list mode

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1482]
### Expected behaviour
After I click on a map marker and delete the post related to the map marker, I expect it the system to keep me on the map

### Actual behaviour
After clicking "delete" on the drop down menu on the map marker (while logged in), it immediately directs me to the timeline mode. 

### Steps to reproduce the behaviour/error
Login
click on a map marker's drop down action menu
select "delete"
confirm delete

**Comment by jshorland** [comment]
@rjmackay I'm still getting redirected to list after deleting from map.

**Comment by rjmackay** [comment]
Turns out I broke the test and this didn't deploy. Try again now.

**Comment by jshorland** [comment]
Ok. Passes qa now. Can someone double check on correct branch to make sure?

**Comment by rjmackay** [comment]
> Can someone double check on correct branch to make sure?

Not sure what you mean? I deployed this straight to prod in this case, have done so with a few of the minor fixes.
