### ISSUE TITLE
My saved search saves incorrectly.

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1483]
### Expected behaviour
Once I save a search, returning to the saved search through the saved search menu in the global header should return me to the same filtered view that I saved

### Actual behaviour
After I save the search, it returns me to the wrong filtered view. See gif

### Steps to reproduce the behaviour/error
Select "show only unknown" in surveys in left navigation bar
Save that search
After you click "save search", see the filters that are presented to you

http://d.pr/i/bLmq

**Comment by rjmackay** [comment]
@jshorland I can't reproduce this. Can you give another example or re-record it? d.pr link doesn't work for me

**Comment by rjmackay** [comment]
@jshorland can you provide steps to reproduce this or can we close it?

**Comment by jshorland** [comment]
Can't reproduce again. Closing.
