### ISSUE TITLE
Pagination on saved search not working

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1484]
### Expected behaviour
I've got a listing of 3 pages on my saved search. When i click on the "next" button or any page number indicated on the bottom of my page, it should take me to the next page populated with more content in my saved search.

![screenshot](http://i.imgur.com/RAilrVE.jpg)

### Actual behaviour
Clicking on either page number or the "next/back" buttons takes me to a page saying "Your search didn't match any posts"

### Steps to reproduce the behaviour/error
* Click on a saved search
* Attempt to navigate to another page within the same saved search

**Comment by rjmackay** [comment]
This was related to weird handling of the post status filter. It should be fixed on production now.

**Comment by jshorland** [comment]
Fixed in production. Thanks. Closing the issue.
