### ISSUE TITLE
Remove Conversation with author section from twitter posts

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1485]
### Expected behaviour
This section shouldn't appear for posts that have come in via tweets, since we technically aren't able to respond to tweets directly from the platform
![screenshot](https://drops.azureedge.net/drops/files/acc_531939/yQfh?rscd=inline%3B%20filename%3DScreen%2520Shot%2520on%25202016-11-06%2520at%252014%253A13%253A58.png&rsct=image%2Fpng&se=2016-11-06T11%3A46%3A45Z&sig=qyTl3YSWlKcC2heOMVS4RlC7HUDE9SKHaSFkW8i%2B1U0%3D&sp=r&sr=b&st=2016-11-06T10%3A46%3A45Z&sv=2013-08-15)

### Actual behaviour
This view appears, creating the impression that I can respond to tweets.

### Steps to reproduce the behaviour/error
* Click on unstructured posts saved search
* Select a post from twitter

**Comment by rjmackay** [comment]
I think we need to keep the thread in case someone submits additional info in a follow up section, but we should hide the reply UI

**Comment by jshorland** [comment]
Yes! this is removed from the usaelectionmonitor.ushahidi.com, but remains in SMS and email posts. Passses QA. Moving to closed.
