### ISSUE TITLE
Allow multiple selection of roles when creating a saved search

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1486]
### Expected behaviour
I'd like to be able to limit the audience of saved searches to more than one user role

### Actual behaviour
ATM, i can only select a single role in a dropdown

### Steps to reproduce the behaviour/error
* Set search criteria
* Click on "Save search"
* Add saved search details
* Select audience of your saved search

**Comment by rjmackay** [comment]
@jshorland I don't think this is P0.. nor a bug.

**Comment by rjmackay** [comment]
- This should apply to both saved searches and collections
- The collection view in the pattern library shows how this should look:
http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/map-collection.html
(click on edit in the sidebar)
- This roles control exists in a few places already, so hopefully it can be reused from there

https://github.com/ushahidi/platform/issues/1412 needs almost exactly the same change.

**Comment by Angamanga** [comment]
I have been looking through the code and starting to find my way. There is no separate directives for this in the survey-editor but the code for the functionality is there, so I started writing a directive. That in turn led me to questions about where to put files, and how everything is put together so a client-code-Q&A-skype-session would be good. Is it you @willdoran, @rjmackay or someone else who can guide me through the code?

**Comment by willdoran** [comment]
@Angamanga We can do a complete code walk through tomorrow together during the one on one
