### ISSUE TITLE
`Logo Image becomes unavailable on Heroku Deployment

### ISSUE THREAD

**Issue by Nesp** [ushahidi/platform#1487]
### Expected behaviour
When a new image is set as a logo, it stays there until changed.

### Actual behaviour
The updated logo becomes unavailable after some time
![image](https://cloud.githubusercontent.com/assets/12881499/20039762/cc9876d0-a449-11e6-945c-c218b415748c.png)

### Steps to reproduce the behaviour/error
1. Make an Heroku deployment;
2. update a logo;
3. wait for some hours.

Could you help me with that? :)

Thank you!
Vittorio

**Comment by rjmackay** [comment]
Heroku deployments don't use a CDN by default but have no persistent local storage. You'll need to configure a CDN like S3 or Rackspace Cloudfiles in application/config/cdn.php

**Comment by Nesp** [comment]
ok, thank you!
