### ISSUE TITLE
Member roles receiving error message on login

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1488]
### Expected behaviour
members should be able to login and view all resources available to their permissions 
- account settings
- create/edit/delete saved searches
### Actual behaviour
- logged in members see a Forbidden error

### Steps to reproduce the behaviour/error
- Sign up as member and login to the deployment (USAElectionMonitor.ushahidi.io)

**Comment by jshorland** [comment]
From zack's investigation of the issue:
Well, for whatever reason, my account (and probably everyone else’s) doesn’t have authorization to read a resource that’s loaded on the page. That’s why the page starts to load and then redirects to the forbidden template.

[5:49 PM]  
Here’s the resource: https://usaelectionmonitor.api.ushahidi.io/api/v3/contacts/21

[6:02 PM]  
Zack Halloran	It’s strictly a permissions issues. I’ve raised it in our dev channel. I’m not sure what the proper solution would be in terms of updates to the code, but if this is an issue for us in the near term, we can address this on a per user basis without having to resolve the underlying UX issues.


Zack Halloran	The current issue w/ https://usaelectionmonitor.api.ushahidi.io/api/v3/contacts/21 raises the question of how we should handle a 403 for one object among a list of objects. Right now it’s redirecting the user to a error message template.

[5:58 PM]  
Zack Halloran	@here If a user is not logged in, it throws up a login modal. The issue is related to `search` priveleges for contact entities in the contact authorizer. I’m not sure how we want to “Fix” that as I’m not 100% sure why the auth restrictions are set up the way they are. Does anyone have any thoughts on this? Admins should not have any problem access this page.

**Comment by jshorland** [comment]
Robbie's response: 
 there are a few things on the frontend that blindly request relations, even though they might not have permissions. There is a flag to ignore failures.. but we must have missed setting it somewhere.

[4:20 PM]  
Not sure what the ‘search’ privilege issue is though? Non admins shouldn’t have permission to access contacts, since contacts include phone numbers and emails

[4:25 PM]  
Robbie Mackay	I’m guessing post meta data directive should be doing `ContactEndpoint.get({id: contact.id, ignore403: true});` but is just doing `ContactEndpoint.get({id: contact.id})`

**Comment by jshorland** [comment]
@zhalloran a quick fix would be good, but concerned about continual new member sign ups throughout today and tomorrow. 

If we decide to move forward with the quick fix, can we disable the member sign up and not allow new sign ups? At this point it might be the most pragmatic fix we can do.

**Comment by rjmackay** [comment]
This might actually be resolved by the same change as 1475

**Comment by rjmackay** [comment]
Should be resolved by https://github.com/ushahidi/platform-client/pull/407

**Comment by jshorland** [comment]
I can see the map after logging in with a member account, but not timeline. It says "sorry, you're not allowed to do that"

**Comment by jshorland** [comment]
might be caching issue. working properly in incognito mode
