### ISSUE TITLE
Search related posts doesn't appear to work at all

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1489]

**Comment by rjmackay** [comment]
er.. what? Where do we even have 'related posts'?

**Comment by jshorland** [comment]
Log in the USA election deployment and look at “verification” task. There’s a way to add a “related post” data field, but it doesn’t actually search? At least from all my tests.

**Comment by rjmackay** [comment]
Worked for me? https://www.dropbox.com/s/7t1mfo6un22vgtr/Screenshot%202016-11-09%2013.01.22.png?dl=0

**Comment by rjmackay** [comment]
It has no 'searching' indicator though.. so maybe misleading UX.

**Comment by jshorland** [comment]
This technically works, but needs a little UX work (as you said, robbie). Removing P0

**Comment by aoduor** [comment]
Is there somewhere the UX issue for this has been addressed that we can refer to? I think it's worth leaving it open just to make sure we don't miss it if it hasn't been documented elsewhere?
