### ISSUE TITLE
Combining nearby posts completely negates map marker color differentiation

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1491]

**Comment by rowasc** [comment]
I'm not sure what we can do about this 🤔  Leaving open with the maps tag

**Comment by Erioldoesdesign** [comment]
I think we talked about how we could do this by doing a 50/50 split of colour on map pin. I'm sure there's a UI solution to this. Assigning to myself.

**Comment by rowasc** [comment]
Noting here. I really think this isn't a thing in the map libraries I could find.  I found someone had an idea in one of the enterprise deployments that initially I thought was quite nice, to change the default cluster colors to be something _other_ than the colors users have selected for any surveys... that's pretty simple to do, doesn't require a lot of custom cluster code, doesn't make us change libraries or evaluate the colors based on which surveys are used _within_ a cluster, and probably would help folks who get confused about the marker colors vs the cluster colors....
*But* the problem with this solution of automatically finding unused colors is that it would actually still be quite complex to do correctly and to ensure it doesn't break accessibility even more. We would need to ensure that there's enough contrast for the cluster colors vs the map, that it doesn't look slightly similar to the selected colors which would still confuse users, and do it automatically. 

I'm inclined to close this right now. We can reopen if we have more user requests for it and do some map focused research, I think. I see the rest of the mapping features we are missing as much more likely to be implemented in the next years tbh, and maybe this will come up then again.
Ushahidi folks: feel free to reopen if you disagree.
