### ISSUE TITLE
Faile lto launch http://localhost/platform/httpdocs/

### ISSUE THREAD

**Issue by Chissico** [ushahidi/platform#1492]
### Expected behaviour

launch index.php

### Actual behaviour
{
    "errors": [
        {
            "status": 404,
            "title": "Unable to find a route to match the URI: platform/httpdocs",
            "message": "Unable to find a route to match the URI: platform/httpdocs",
            "class": "Kohana_HTTP_Exception",
            "file": "/var/www/html/platform/vendor/kohana/core/classes/Kohana/Request.php",
            "line": 985,
            "trace": [
                {
                    "file": "/var/www/html/platform/httpdocs/index.php",
                    "line": 38,
                    "function": "execute",
                    "class": "Kohana_Request",
                    "type": "->",
                    "args": []
                }
            ]
        }
    ]
}

### Steps to reproduce the behaviour/e

**Comment by rjmackay** [comment]
If you're deploying in a subfolder I think you'll need to update the `.htaccess` file to add `RewriteBase /platform/httpdocs` or something similar. And edit `base_url` in application/config/init.php
