### ISSUE TITLE
Intercom only shows on login, but not on return to deployment

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1493]
1. Got to deployment
2. Login
Intercom shows
3. Reload page
Still logged in, but no intercom

Aha! Link: https://ushahiditeam.aha.io/features/PROD-656

**Comment by rowasc** [comment]
I don't get an intercom icon at all now when I login

**Comment by Erioldoesdesign** [comment]
Re. intercom I think that's for the best - it kind of gets in the way of the UI.

The only area I think it could be useful is if it shows up on the support section of a deployment which it already is I think: 
<img width="677" alt="Screenshot 2019-07-10 at 11 10 36" src="https://user-images.githubusercontent.com/11681324/60956568-61a5dc80-a303-11e9-9d25-53f27091bfe0.png">
