### ISSUE TITLE
The Title entry box is not obvious n the submission page

### ISSUE THREAD

**Issue by cmurphyUSAID** [ushahidi/platform#1494]
### Expected behaviour
Show a text box for entering the title

### Actual behaviour
The format for the title box is different than the other text entry fields on the page.  It appears ot be a white space with no border amking it bleed into the background.

### Steps to reproduce the behaviour/error

![text entry](https://cloud.githubusercontent.com/assets/7262256/20101784/7311c32a-a591-11e6-8e4b-31b061c13e7d.JPG)

**Comment by brandonrosage** [comment]
Both in response to this issue and the overall move toward free-form fields, I've revised the PL (in `develop`) to demonstrate the "title" field as a generic text input that has no special source order or treatment:

![sample](https://cloud.githubusercontent.com/assets/1136279/22435067/2d712344-e6e4-11e6-8631-f1e52f190f14.png)

The client should apply this same treatment, allowing the short text field to be re-ordered (albeit not deleted, *yet*) and not assume it's the top-most field in the survey.

**Comment by brandonrosage** [comment]
@aoduor, @KrisKuri: Please verify that this solution doesn't undermine or overlook other needs expressed to you by users.

**Comment by aoduor** [comment]
This looks good to me as well..
