### ISSUE TITLE
Map marker not centering on click

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1495]
### Expected behaviour
- When in embed mode, if I click on a map marker I expect the map to reposition so that the popup post card is entirely visible
### Actual behaviour
- Map does not reposition
<img width="812" alt="screen shot 2016-11-08 at 12 18 18" src="https://cloud.githubusercontent.com/assets/2694405/20109305/7c083f10-a5ad-11e6-9ba4-066f10238352.png">

### Steps to reproduce the behaviour/error
- Create a en embed map with the following dimmensions: H=315, W=560
- Click on map marker, observe popup not appearing within the view

**Comment by rjmackay** [comment]
This might be fixed by the map refactor in ushahidi/platform-client#446

**Comment by Angamanga** [comment]
@rjmackay @willdoran This seems to work now, the marker centers in the bottom of the iframe.
