### ISSUE TITLE
Add post needs a cancel button in embed

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1496]
### Expected behaviour
- When I click to add a post and am taken to the submit page, I may want to cancel this action and return to the previous view

### Actual behaviour
- It is possible to do this via the filters menu but it is not intuitively obvious
<img width="966" alt="screen shot 2016-11-08 at 12 21 42" src="https://cloud.githubusercontent.com/assets/2694405/20109410/ef12cdf4-a5ad-11e6-8fea-6a5122aa6bd5.png">

**Comment by jshorland** [comment]
this was fixed by @Angamanga with a back button. closing.
