### ISSUE TITLE
Add post sources to search filter

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1502]
### Expected behaviour
It would be great to be able to filter posts by source. 

### Actual behaviour
Our search filter currently only has 
* Surveys
* Categories
* Status
* Date range
* Location

### Steps to reproduce the behaviour/error
Log onto your deployment and click on the search filter.

**Comment by rowasc** [comment]
<img width="201" alt="Screen Shot 2019-06-09 at 15 48 50" src="https://user-images.githubusercontent.com/2434401/59162825-1ca54500-8ace-11e9-92bd-8eff02d74cf5.png">
This is done , closing 🎉
