### ISSUE TITLE
After changing location of a twitter post, the post appears in two locations, not the updated one

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1503]
### Expected behaviour
If I change the location of a tweet when structuring it as a post, it should update to that location. NOt the original location of the tweet
### Actual behaviour
The post appears with two locations

### Steps to reproduce the behaviour/error
1. login to usaelectionmonitor.ushahidi.io 
2. grab an unstructured tweet
3. try to change the location
4. click save
![screen shot 2016-11-14 at 2 26 46 pm](https://cloud.githubusercontent.com/assets/3224856/20285478/1edbd954-aa90-11e6-9801-4034ae9c4657.png)

**Comment by rjmackay** [comment]
Probably the same as  #1508

**Comment by rjmackay** [comment]
@Angamanga I think you were already looking at this?

**Comment by Angamanga** [comment]
@jshorland Corresponding pr with list for testing: https://github.com/ushahidi/platform-client/pull/461

**Comment by jshorland** [comment]
Again. Sorry this has taken me so long :-/ fail on my part. Passes QA. Let's get this deployed!
