### ISSUE TITLE
"Disappearing" Categories

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1505]
Got this from a user on intercom, and I experienced it to on our US Election Monitor deployment.
"when I want to input categories in the survey, the checkbox for categories sometimes goes missing, and sometimes I need to wait about 5 to 10 minutes and then refresh the page so it will appear again"

The categories intermittently disappear from a survey during submission. 

Caching issue maybe? @rjmackay @willdoran

**Comment by jshorland** [comment]
This is a caching issue. If you immediately refresh after adding a category, the category doesn't appear for a few minutes.

**Comment by Angamanga** [comment]
@jshorland  I added a list for QA in the pr: https://github.com/ushahidi/platform-client/pull/465

**Comment by jshorland** [comment]
@Angamanga what URL should I test this on?

**Comment by Angamanga** [comment]
@jshorland You can test here: http://qa.ushahididev.com

**Comment by jshorland** [comment]
Should be fixed. Let's get this deployed (If it hasn't been already)
