### ISSUE TITLE
Two map pins after changing location

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1508]
### Expected behaviour

When I change the location of a report that has location on it, there is only 1 location (the one i changed it it)

### Actual behaviour

If a post comes in with location (Twitter w/ location turned on for instance), and then I change the location to the location of the content, not where the person was when they submitted, it ends up showing two pins on the Map, both locations.

### Steps to reproduce the behaviour/error

![screen shot 2016-11-16 at 12 27 26 pm](https://cloud.githubusercontent.com/assets/2200987/20364467/1d90ee04-abf8-11e6-876a-6be45911d687.png)

**Comment by willdoran** [comment]
@natmanning are the two pins both there after a page refresh or indeed trying the same view from a different browser? I'm trying to work out if we don't clear the map properly.

**Comment by jshorland** [comment]
@natmanning @willdoran both pins are there after refresh. I tried in a different browser (firefox vs. chrome) and it's there for me as well. @natmanning could you double check these?

**Comment by natmanning** [comment]
yes still there. It seems to be the case when someone submits a post from Twitter w/ their Geolocation turned on, but the post itself is about a different place. After the post structurer/admin moves the point to a new place, it now shows up as both places. 

If you load usaelectionmonitor.ushahdi.io as a viewer (dojn't login) and look at the posts in Sweden, and then open up that post page. You will see it is posted as boht places: 

https://usaelectionmonitor.ushahidi.io/posts/437

**Comment by rjmackay** [comment]
@Angamanga I think you were already looking at this?

**Comment by Angamanga** [comment]
@jshorland Same as #1503, fixed by pr: https://github.com/ushahidi/platform-client/pull/461

**Comment by Angamanga** [comment]
@jshorland You can test this on this post: http://qa.ushahididev.com/posts/5027

**Comment by jshorland** [comment]
Fixed by #1503
