### ISSUE TITLE
Duplicate emails being pulled into platform

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1509]
### Expected behaviour
Each unique email should only be pulled into platform once. 

### Actual behaviour
User xenowatch.ushahidi.io has thousands of duplicate emails being pulled into their platform.

@willdoran  can you write notes as appropriate?

**Comment by willdoran** [comment]
Yep, the main issue with this is the way we are using IMAP, unfortunately at present we end up redownloading what is already in the mail box IF the mail provider doesn't treat access as having been read. So we need to change this, so that we store the UID of the messages we have retrieved, we then each time ask for all the messages with UID > last_uid. We are not a full mail client so we don't take account of any intelligent behaviours such as awareness of deletion.

**Comment by jshorland** [comment]
Still happening. The test deployment I created keeps bringing in the most recent email over and over and over and over

**Comment by jshorland** [comment]
@willdoran can we hand this to @Angamanga to finish up?

**Comment by willdoran** [comment]
Ah yes! I got entirely drawn into rollcall and this fell out of my head. I'll take @Angamanga through the issue and the needed fix.

**Comment by rjmackay** [comment]
@jshorland is it *just* the most recent email? or many recent emails?
I wonder if this is just an off-by-one error ie. we're saving the ID of the last email we brought in, and rather than doing `id > lastid` we're doing `id >= lastid` or something like that.

**Comment by willdoran** [comment]
@rjmackay This is actually an issue with the mail fetcher, if there are no new emails and you ask for emails from last_uid to last_uid + N, then it just returns the last mail again :( Always. So I suggested to @Angamanga that the best way to handle it is to add a check that what's returned doesn't equal the last uid.

**Comment by rjmackay** [comment]
I think @Angamanga fixed this. @jshorland can you retest?

**Comment by Angamanga** [comment]
@rjmackay @jshorland Yes, this was fixed in https://github.com/ushahidi/platform/pull/1536.

**Comment by jshorland** [comment]
Great! I' going to check in with the user who reported this and let them know. I'll close after they confirm fixed. And to double check @Angamanga since this is fixed, their duplicate emails within their deployment should be cleared out, correct?

**Comment by jshorland** [comment]
Fixed. Closing.
