### ISSUE TITLE
When I delete a post - i get sent back to page 1

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1510]
### Expected behaviour

I am on page 3 of my timeline reports and triaging reports. If I delete a post it asks me "are you sure?" and then when I press yes, the post would delete and I would be on page 3 to be able to tackle the next post.

### Actual behaviour

I am on page 3 of my timeline reports and triaging reports. If I delete a post it asks me "are you sure?" and then when I press yes, the post deletes and then it loads me back up on page 1. I then have to click back over to page 3 to get to where I was.

**Comment by rjmackay** [comment]
Solved by data view
