### ISSUE TITLE
invalid error pop ups

### ISSUE THREAD

**Issue by spiral99** [ushahidi/platform#1522]
### Expected behaviour
A user should not be receiving an error pop up after filling in all the required fields 
### Actual behaviour
The error pop up appears even after the all the fields have been filled. It seems as though the front end  JavaScript changes are not being validated.
### Steps to reproduce the behaviour/error
![2016-12-01](https://cloud.githubusercontent.com/assets/7393879/20795838/4f130654-b7e4-11e6-9f7b-e212eee6b1db.png)

**Comment by rjmackay** [comment]
Out of date closing
