### ISSUE TITLE
Keep original map/timeline display status when coming back from viewing/editing a report

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1525]
Reported from community support channel

### Expected behaviour
1. Browsing reports through map or timeline
2. Click on any report to see its details
3. Click on browser back button to return to map/timeline
4. The map or timeline view is in the same state (zoom/scroll position) that it was on step number 2

### Actual behaviour
on 4. The map zoom position is reset , the timeline scroll position is set back to the top and any additionally loaded posts ("Load more" button) have to be loaded again

Does this have technically anything to do with ushahidi/platform#1089 ?

Aha! Link: https://ushahiditeam.aha.io/features/PROD-650

**Comment by ArturoQuintana** [comment]
Hello,
I have the same point of view related to this behavior. 
I would like to preserve the same map state (zoomed position) once I return to the map. The option to keeps the map position is important for users.
