### ISSUE TITLE
Youtube and Vimeo icons have disappeared in product

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1527]
![screen shot 2016-12-09 at 11 48 44 am](https://cloud.githubusercontent.com/assets/3224856/21062382/7b29014a-be05-11e6-8b79-69dc0e0dec47.png)
 @willdoran is this a quickfix?

**Comment by willdoran** [comment]
hmmmm....that's super weird...the images are in the repo for master and production.
@tuxpiper Any idea where they might have gone?

**Comment by willdoran** [comment]
Ok weirdly, I'm getting this for a request for either image:
<div class="alert error"> <p>Sorry, something went wrong. Try reloading the page.</p> </div> 
Which is basically saying it's broken somehow when fetching the image :/

**Comment by willdoran** [comment]
Fixing now

**Comment by Angamanga** [comment]
I'll QA this!

**Comment by Angamanga** [comment]
I can see the images now so this issue is fixed.

**Comment by rjmackay** [comment]
@willdoran can you make sure this is deployed? (not sure what the code changes were?)
