### ISSUE TITLE
Add "you cannot undo this action" warning to delete confirmation pop ups

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1528]
We need to inform the user that deletions CANNOT be undone.

**Comment by jshorland** [comment]
@rjmackay this is a quick user knowledge issue we've seen pop up after they delete something. If we can get this done quickly, would prevent a lot of disappointment/frustration in our users.

**Comment by Angamanga** [comment]
@rjmackay Are you working on this? Else, I can do it.

**Comment by jshorland** [comment]
@aoduor Do you think this adequately solves the issue you described in #1630?

**Comment by aoduor** [comment]
@jshorland i'd really love for this to be specific in mentioning the consequences, in addition to not being able to undo the action. 

i.e Tell me what happens to my data when i delete a field or a survey, AND tell me that this action is cannot be undone :)?

**Comment by jshorland** [comment]
@StaicyG mind QA'ing tomorrow? on qa.ushahididev,com, a message should appear when you try to delete ANYTHING (post, survey, user, user role) that warns you that the action cannot be undone and asks you to confirm.

**Comment by StaicyG** [comment]
@jshorland sure

No message warning that once the delete action is taken it cannot be undone. The confirm delete pop up is the last message that appears after clicking on delete.

words appear jumbled up on some posts in the timeline:
<img width="594" alt="posts_-_internal_qa_and_slack_-_ushahidi" src="https://cloud.githubusercontent.com/assets/25605883/24958892/9d9b0624-1f99-11e7-9274-b0ac00d79348.png">

On clicking on delete button from an individual post the deployment freezes and "are you sure you want to delete" pop up migrates to the bottom of the page as shown below:
<img width="616" alt="test-posting_with_photo_-_internal_qa_and_slack_-_ushahidi" src="https://cloud.githubusercontent.com/assets/25605883/24959337/2c98290a-1f9b-11e7-9fc0-1b2a6ed41b07.png">
Neither cancel button nor delete buttons work

Add photo function:
On clicking edit on an individual post and trying to add photo, the photo does not seem to get saved. It shows the error below with no photo saved:
<img width="930" alt="testing_notifications_-_internal_qa" src="https://cloud.githubusercontent.com/assets/25605883/24959633/f5d9c85a-1f9b-11e7-9b93-56bb1a10ac65.png">

**Comment by jshorland** [comment]
@angamanga italic text should read under the "Are you sure you want to delete this post?" that says "This action cannot be undone. Please proceed with caution."

**Comment by Angamanga** [comment]
:+1: I'll fix this and the issue @StaicyG found!

**Comment by jshorland** [comment]
Passes QA
