### ISSUE TITLE
Payment page has wrong price in recurring billing disclaimer

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1531]
Surveyor disclaimer still identifies it at $199 (the old price) instead of $99. @angamanga If this is a quick fix, mind picking this up as well?

![screen shot 2016-12-15 at 9 36 57 am](https://cloud.githubusercontent.com/assets/3224856/21235062/19a9d562-c2aa-11e6-8f70-76723e081308.png)

**Comment by Angamanga** [comment]
@jshorland I dont manage to get to this disclaimer, how do I find it?

**Comment by jshorland** [comment]
Hmmm try logging into qa.ushahididev.com <http://qa.ushahididev.com/> with u: jess@ushahidi.com <mailto:jess@ushahidi.com>, p: password and going to settings —> plans, then click on Surveyor.

**Comment by Angamanga** [comment]
@jshorland That particular piece of code is from somewhere I don't have access/knowledge about right now, but I'll let you know as soon as I know more! @middle8media @rjmackay Do you have any advice where to fix this?

**Comment by rjmackay** [comment]
@jshorland does this happen on production? or only on QA? I think chargebee's test site might just have the wrong price.

**Comment by jshorland** [comment]
yup. @rjmackay is indeed correct. This only happens in QA, not in production. Sorry everyone. Should have double checked that before putting into an issue. cc: @Angamanga
