### ISSUE TITLE
Install docs cites wrong php version

### ISSUE THREAD

**Issue by NonSecwitter** [ushahidi/platform#1532]
### Expected behaviour
Install with PHP 5.4 should run phinx

### Actual behaviour
stderr: PHP Parse error: syntax error, unexpected '$value' (T_VARIABLE) in /wwwroot/platform/vendor/aws/aws-sdk-php/src/functions.php on line 36

### Steps to reproduce the behaviour/error
CentOS 7
nginx 1.10.2 from epel
mariadb 15.1 Distro 5.5.52
php, php-mysql, php-fpm

run phinx as stated in install instructions

apparently "yield" for generators requires php 5.5 or greater...
http://stackoverflow.com/questions/30580770/installing-aws-php-sdk-unexpected-variables

**Comment by tuxpiper** [comment]
Updated the version on support site.
