### ISSUE TITLE
Sort by embed-source

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1533]
### Expected behaviour

UI category/collection filter capability to filter reports based on input from embeds sources. AKA, if the NYtimes puts a Document Hate form embed on their site, and the Washington Post puts a form embed on their site, can we show Nytimes the reports from their embed, and WP the reports from their embed. 

1) Can we then make that into a UI filter that they can use.

2) Can we also make that a permissions structure?

### Actual behaviour
doesn't exist

### Steps to reproduce the behaviour/error
doesnt exist

Aha! Link: https://ushahiditeam.aha.io/features/PROD-648

**Comment by rowasc** [comment]
@natmanning I'm not sure I understand this issue, any chance you know what it's about? 
Right now you'd embed a form by using an iframe that has the form's url , and in the case of saved searches or collections you also would use the saved search or collection url. 
Not sure if that covers the requirement here or if it's something else .

**Comment by Erioldoesdesign** [comment]
Yeah I'm not sure how technically feasible this is unless you set up a duplicate survey question set just for the NYtimes that asks the same Q's but is specific to NYtime. Or you could do this through categories.

I think what is wanted here is like, the deployment automatically knowing that it comes from NYtimes etc. and adds a 'tag' or 'category' automatically.

**Comment by webong** [comment]
IDEA: The embed javascript can be updated to contain the host page URL.

https://stackoverflow.com/questions/3420004/access-parent-url-from-iframe
