### ISSUE TITLE
Multi-survey form embed?

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1535]
### Expected behaviour
Other sites want to embed our surveys for Document Hate. However, we have created the surveys as 5 distinct groups (harassment, violence, hate speech, protest, other), because it is an engaging way to sort a view the data on the page.

But for someone looking to embed a form, this means they have to embed 5 different forms, which doesn't work.

q1) is there an elegant technical fix that allows someone to embed multiple forms?
q2) or is the solution to make one master Survey, where first question is drop down/check box field "What type of hate crime is this?"

### Steps to reproduce the behaviour/error

Aha! Link: https://ushahiditeam.aha.io/features/PROD-646

**Comment by rowasc** [comment]
@natmanning I think the solution would be *2*, have a dropdown where a user can select the type of crime, or alternatively the person embedding it has to have the dropdown if they want a multi step UI where you first select the type of crime and get the right form.

**Comment by Erioldoesdesign** [comment]
Yeah - I would suggest this is more of a 'how they embed' but @rowasc option of a dropdown to select the survey would work. If we left the embed code 'vanilla' then the org embedding could ad their own styles.

this does require some technical lift on the embedder orgs side though.
