### ISSUE TITLE
Required Fields Prompt is displayed despite them being completed.

### ISSUE THREAD

**Issue by FIU-Editor** [ushahidi/platform#1540]
### Expected behaviour
Post is submitted when all fields with an "*" are completed.

### Actual behaviour
Although all required fields (with an asterisk) are completed as the post is submitted, this still does not occur.
We receive the following message when this occurs:
![ushahidi required fields error](https://cloud.githubusercontent.com/assets/17600339/21364598/868c9d40-c6bf-11e6-8d66-dd1a9529ff09.PNG)

### Steps to reproduce the behaviour/error
1. Visit bb.fiu.edu
2. Complete a post using ONLY the required fields
3. Press "Submit"

Thank you for your assistance :)

**Comment by rjmackay** [comment]
This is out of date. Closing
