### ISSUE TITLE
Checkbox and Radio Button Fields do NOT show the asterisk which indicates that they are required.

### ISSUE THREAD

**Issue by FIU-Editor** [ushahidi/platform#1541]
### Expected behaviour
After clicking the toggle which makes the checkbox or radio field required, and saving the survey, users entering the survey should be able to see the "required" asterisk to determine whether or not such fields are required.
### Actual behaviour
After such actions, users are not able to see the "required" asterisk in fields that have been set as required, causing confusion.
### Steps to reproduce the behaviour/error
1. Create a survey with a checkbox and/or radio button field.
2. Set them as "required"
3. As a user, attempt to add a post.

Thank you for your help :)

**Comment by rowasc** [comment]
Closing, this is resolved. Thanks!
