### ISSUE TITLE
Request: Development which allows users in roles in each state to see and be notified of ONLY posts/surveys in their individual state.

### ISSUE THREAD

**Issue by FIU-Editor** [ushahidi/platform#1542]
For our deployment, we have attempted to create roles based upon state, so that each and every role is notified of and can only see activity in each state, using categories and saved searches. However, this system has had its defects, and we have been hindered from doing this because of the following issues:

1. Notifications intended for one role's state & saved search have been distributed to every role.
2. The overall loftiness of having to create, for instance, 50 categories and 50 saved searches so that each state-specified role can receive their individual notifications.

If any type of guidance could be provided on these issues, it would be greatly appreciated.

Thank you very much

**Comment by rjmackay** [comment]
Would this be best addressed by allowing admins to upload a geographic state boundaries and create saved seaches based on those? or does it need to be even simpler than that?

**Comment by FIU-Editor** [comment]
Would this be a question for developers? Is it possible for boundaries to be coded in the first place, and how difficult would that be? 

As a deployment team, we would ideally like to see states being assigned to categories based upon their borders. What are your thoughts?

Thanks

**Comment by rjmackay** [comment]
> Is it possible for boundaries to be coded in the first place, and how difficult would that be?

Not easily no. Boundaries for different countries come in a range of formats, we couldn't provide them all. If we did we'd likely find many of them were out of date/inaccurate.

The best solution might be to pull boundaries from Open Street Map..
