### ISSUE TITLE
MS Edge location search publishes posts

### ISSUE THREAD

**Issue by djrmf** [ushahidi/platform#1543]
### Expected behaviour
Pressing search in the location section of a post should look up a location on the map 

### Actual behaviour
Pressing the location search button publishes a post, (without any location information)

### Steps to reproduce the behaviour/error
This occurred multiple times when trying this in Microsoft Edge, but did not happen with Firefox.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-644

**Comment by rowasc** [comment]
If anyone doing outreachy is able to test on edge and validate this issue (and wants to work on it) please ping me! It's an old issue so I'm not sure if its still happening (if you reproduce it but can't fix it, lmk as well)

**Comment by Firenz** [comment]
Hi @rowasc, I have access to a Windows 10 with Microsoft Edge browser. 

I'll need to install some things (is not my usual SO for working) before starting to work on this but I think I can handle it!

**Comment by rowasc** [comment]
@Firenz you rock <3 Thank you! assigning.

**Comment by Firenz** [comment]
Today I installed everything to work in my Windows 10 system, so now I'm ready to take on this issue 😄 

However, while I was waiting to things get installed, I tried to reproduce the bug in a [production environment that I already had the link](https://isooko.ushahidi.io/views/map), tried to look for the Search location button in a post but it's nowhere to be seen.

Maybe that feature has been removed? I attach a screenshot of a post showing that there's no such button.
![image](https://user-images.githubusercontent.com/2558299/96477186-7bd4a700-1236-11eb-914c-a5ef35800b01.png)

@rowasc can you help me looking for that button? Meanwhile, I'll be setting up a local deployment of the client, to verify that it really doesn't happen with the actual code.

**Comment by rowasc** [comment]
@Firenz hey! Thank you ! Ok so it should be the search input that comes up when you are trying to add a location to a post (so in edit/add mode, not in view mode)
Like this 
![Screenshot from 2020-10-20 17-39-16](https://user-images.githubusercontent.com/2434401/96641548-447bfe00-12fb-11eb-8153-905ceb718abf.png)

LMK how it goes!

**Comment by Firenz** [comment]
Hey @rowasc, when creating a new post I tried searching for locations, and using my current location, everything worked as expected.
![msedge_7PjXrqHWPC](https://user-images.githubusercontent.com/2558299/97168776-504b4280-1789-11eb-8b6a-50403ea67255.png)

I haven't checked yet if in Edit Mode when the post is already posted and is edited later, it happens, but I don't think the error is going to happen. 

Can we close the issue? or do we have to wait until I check this last thing?
