### ISSUE TITLE
Field level permissions

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1544]
We're working with a client who needs to be able to collect contact info from people submitting posts, but only limit access to this information to an admin.

### Expected behaviour
I should be able to limit who sees responses to a particular field on a survey

### Actual behaviour
There are no options provided for me to limit who sees responses to specific fields on a survey, and when a post is published, all field responses are public.

cc @jshorland @rjmackay

**Comment by jshorland** [comment]
@aoduor mind sharing who the client is and any info on when they would need this by?

**Comment by aoduor** [comment]
Sure @jshorland. This is for Campaign for Tobacco Free Kids. They plan on launching their campaign in early february in about 20 countries.

**Comment by jshorland** [comment]
Perfect. This has been a pretty burning issue with other users as well, and would significantly improve privacy

**Comment by jshorland** [comment]
Duplicate of #1511. Closing.
