### ISSUE TITLE
Email notification "cron job," takes longer than is supposed to.

### ISSUE THREAD

**Issue by FIU-Editor** [ushahidi/platform#1545]
Hello!

Our programmer for our Ushahidi deployment, bb.fiu.edu, recently set the cron job of our email notifications to 5 minutes. Afterward, a colleague and I decided to make a few posts to test whether notifications would arrive at the designated time:

![image](https://cloud.githubusercontent.com/assets/17600339/21903672/c5314822-d8ce-11e6-9f27-1b3a4ed5f588.png)

Now, we have already opted for notifications in the saved search we set up. In addition, we made sure to input the category destined to the saved search for which we signed up for notifications in each post we made. 

As such, we expected to receive notifications 5 minutes after the time we made these posts, the ranges of which are from 1:30 to 1:50.

However, we ended up receiving the notifications a day afterward, as shown in these emails:
![image](https://cloud.githubusercontent.com/assets/17600339/21903882/78825952-d8cf-11e6-8fe4-a47e532f9044.png)

![image](https://cloud.githubusercontent.com/assets/17600339/21903909/8f1ddf38-d8cf-11e6-9786-d888ae7da60d.png)

![image](https://cloud.githubusercontent.com/assets/17600339/21903920/990c142e-d8cf-11e6-867c-726811c5cd8b.png)

Indeed, we did intend for notifications to be sent out 5 minutes after posts were made, but this, instead, took one day.

What's a possible solution to this issue?

Thank you!

**Comment by jshorland** [comment]
@rjmackay @willdoran alerts are delayed in .io as well. Is this a bug?

**Comment by rjmackay** [comment]
Looks like a bug. I'd expect a delay of update to 30 mins, in part because notifications is combination of 3 different tasks running in sequence - so the delay is cumulative. But 1 day if *far* longer than expected.
