### ISSUE TITLE
Set up COMRADES repo / branch

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1549]
I'm not sure if I'm using the right terminology but COMRADES code needs to go into its own place. The notes we have from our last conversation in Basecamp (soon to be dead) are: 

> Although the goal of COMRADES is to expand the platform, it is possible that the consortium will require the inclusion of some technology that we will not want to roll into the platform. For this reason, COMRADES code will be kept on a separate branch - think of it as a custom deployment - so that we can easily respond to the requirements of the grant and integrate features that are appropriate for the platform.

**Comment by jshorland** [comment]
@rjmackay @tuxpiper we need to figure out the best way to house and manage a COMRADES code base. Please advise and move on the best way forward.

**Comment by tuxpiper** [comment]
So we could do this pretty much the way we have been doing other platform custom deployments. 

However, I would like to take the chance to improve our practices :) I'm thinking:

* Hosting in AWS (with shared managed RDS database)
* Use Terraform to provision the resources
* Automatic deployment with Codeship
* Configure errors to go to Sentry
* Save uploads to S3 (instead of local disk)
* SSL with LetsEncrypt out of the box

Nice to have (?)
* Internal metrics (memory, cpu, http requests, 5xx errors... using collectd , statsd , ...?) feeding to CloudWatch
* ~~Use traefik instead of nginx ( https://traefik.io/ )~~

@willdoran @rjmackay thoughts?

**Comment by willdoran** [comment]
@tuxpiper this sound super great, I really like the default setup of S3 and LetsEncrypt!

**Comment by Shadrock** [comment]
@tuxpiper sounds good to me. Any chance this will get done this week? I've got a working meeting next week and would love to introduce the COMRADES consortium to it.

**Comment by tuxpiper** [comment]
Yep @Shadrock , this is my P0 this week.

**Comment by tuxpiper** [comment]
Created 

ushahidi/platform-comrades
ushahidi/platform-client-comrades

thinking that we may want to have a staging environment for comrades, I've set up both develop and master branches. The code for both branches comes from the develop branch of the corresponding upstream repository.

Created pull requests with the customisations @willdoran made

ushahidi/platform-comrades#1
ushahidi/platform-client-comrades#1

**Comment by willdoran** [comment]
@tuxpiper Awesome, thank you so much.

**Comment by Shadrock** [comment]
Is there a deployment associated with these? I just visited both and am not quite clear on how they are to be used by the consortium. Please advise. Could I please get an explanation between the client / non-client repos as well as how they work with develop and master branches? Sorry, but I'm going to need to spell this out very clearly for everyone involved: most of the consortium does not use Github...

**Comment by rjmackay** [comment]
@tuxpiper I'm happy to improve the way we deploy, but lets make sure Shadrock still gets a test deployment for this before the consortium meeting.

My only concern from the bullet points above is splitting deployments across rackspace and AWS, especially given discounts we have on rackspace. However I guess terraform support for RS is still flaky?

**Comment by willdoran** [comment]
@Shadrock 
Sorry only just saw this, add @willdoran to any messages here and I will see them faster, add @tuxpiper for David.

The above repos are the API and Client specific to Comrades. The distinction between Master and Develop is just a development process approach. 
To give a step by step for clarity, I'm going to assume zero knowledge so please ignore the parts that are obvious when you want to explain to the consortium. 

When making a change to the code we do the following:
1. Create a new branch - this is a copy of the code at a point in time - from the Develop branch. The new branch is usually named like so: <issue number>-dash-separated-feature-name. For example, the [API repository](https://github.com/ushahidi/platform-comrades/) has 3 branches Master, Develop and 1550-comrades-yodie-integration. 
2. The Master branch can be considered equivalent to the Production ready version of the code, the Develop branch is code currently being tested awaiting release.
3. When a feature has been completed in its own branch, it is then merged into the Develop branch and tested. 
4. When the Develop branch is considered to be tested and stable it can then be merged into the Master branch.
5. Then a release is created, this is done by what is called tagging. Essentially, the code is copied, bundled up as source code in a tar or zip, and given a release number. For example, this is the release page for the [platform](https://github.com/ushahidi/platform/releases).

At this point, a feature/customisation has been created, tested, the main branch of the repository has been updated and there is a code release. And now there is a bundle of code someone can go and put on a server somewhere.

What happens next is that we have, or will have, both Production and Staging deployments, when work is merged into Develop it will be automatically pushed to the Staging deployment where it can be tested and when work is merged into Master it will be automatically pushed to the Production deployment(@tuxpiper please correct me if I am wrong about which branches link to which).

So when I merge the branch I am currently working on to Develop it should become available to test on the Staging deployment via the backend magic that David L creates.

So Master === Production, Develop === Staging.

There are 3 repositories:
1. [Platform API Comrades](https://github.com/ushahidi/platform-comrades)
  - This is the backend PHP code base that handles interactions with the Database, handles Datasources, and Handles the Webhook jobs
2. [Platform Client Comrades](https://github.com/ushahidi/platform-client-comrades)
  - This is the Angular/Nodejs javascript Client that is responsible for the UX
3. [Comrades Yodie Proxy](https://github.com/ushahidi/comrades-yodie-proxy/)
  - This might need a better name. But this is the PHP application that acts as a proxy between the Comrades Platform deployment and the Yodie service. When a Post is created in the deployment, either via the web client or one of the datasources the Post data is sent to this proxy which then forwards it to the Yodie service. The result it gets from the Yodie service is then sent back to the Platform and the Post is updated.

May be I should create a doc that outlines the development of a feature/customisation from start to finish. That was what I was hoping to walk through in the workshop. 

@Shadrock Does the above help? I can expand further or try to make it clearer as needed.

There will be Staging and Production deployments: @tuxpiper could you link them here:
- [Production](url)
- [Staging](url)

**Comment by Shadrock** [comment]
@willdoran this is perfect. The way you've laid this out, above, is perfect and will likely be useful for the COMRADES devs as well: I don't believe they use Github much so they will likely benefit from a walkthrough or, at least, refresher. 

@tuxpiper Thanks for the help on the repos. I definitely need a deployment spun up in conjunction, however! Would love to see this ASAP since I'm presenting on Monday...

**Comment by tuxpiper** [comment]
@willdoran things are running for the staging, just last mile configurations pending for the yodie proxy. I've sent you details through slack.

For everyone , the URL is 

http://comrades-stg.ushahidi.com  (admin credentials in list pass)

I'm hoping this is enough for the next couple weeks, while I have time to develop a better production deployment (with SSL , autodeploy, and all the items I listed above)

**Comment by willdoran** [comment]
@tuxpiper Super awesome, I can complete the configuration of the yodie proxy, I have some updates to push to the API and I want to add seed data. Thank you very much for your work!

**Comment by tuxpiper** [comment]
@willdoran @Shadrock is the staging site ok for the time being? Or would we need a production site shortly (i.e. in the next couple weeks)?

**Comment by tuxpiper** [comment]
created ushahidi/engineering#75 to improve the engineering quality of this deployment

**Comment by willdoran** [comment]
@tuxpiper I think the integrated system is to be demoable by the end of June and a production environment would be need for then. In the mean time, ideally, the partners will work on their own integrations in their local environments and only push to staging when they want to share with each other.

For me, the only super useful thing in the immediate term would be autodeployment from the repo.

@Shadrock @jshorland do you have opinions?


@Shadrock do you have a different view on the urgency of need for the production deployment?
