### ISSUE TITLE
Allow users to select fields they would like included in downloaded CSV

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1552]
### Expected behaviour
* When downloading a CSV file, it would be useful to be able to have the option of omitting/leaving out certain fields as opposed to downloading the entire field set of data

### Actual behaviour
* Clicking on download simply downloads CSV file with all fields and their data in it.

### Steps to reproduce the behaviour/error
* Click on the export button

This came as a request from CTFK. See below

> Also, instead of the spreadsheet sending an export with the longitude and latitude coordinates, is it possible to download the address instead? There's a concern that if we want to download the data and format it as a petition, the longitude/latitude will not make sense to decision makers; or that as we send information to police departments to follow up and enforce violations, they will not be able to process the long/lat coordinates on their end.

cc @jshorland

**Comment by jshorland** [comment]
@aoduor I'm going to move this into icebox for now since it hasn't arisen in user testing/feedback elsewhere. Most users alter the CSV file in excel after opening.

@rjmackay can you help answer the question about exporting a location as an address instead of lat/long? my understanding from the surface is that there are several problems with storing addresses (or lack thereof)  in our DB

**Comment by caharding** [comment]
I've never seen this done in another tool. Its always the users job to manage their CSV and choose the right fields on their own. It's very easy to run pivot tables and accomplish this in a CSV file with existing spreadsheet/DB tools. The only reason we would do this is if there is a high data cost to us for the downloads and even then we would need to get people to use it. @jshorland I recommend you close this issue.

**Comment by rowasc** [comment]
This is now a feature since COMRADES needed it 🎉  closing 
<img width="1022" alt="Screen Shot 2019-06-09 at 18 34 45" src="https://user-images.githubusercontent.com/2434401/59164592-487ff500-8ae5-11e9-9101-b2a2782f08c1.png">
