### ISSUE TITLE
FIU Open Source: We are not able to get the SMS Data Source to work

### ISSUE THREAD

**Issue by FIU-Editor** [ushahidi/platform#1553]
We have been able to configure the SMS number; however, while incoming text messages are delivered successfully, Ushahidi still does not receive the texts as unstructured posts. 

I have inputted the Phone Number, the Auth Token and the Account SID exactly as inputted by both Twilio and Nexmo, but Ushahidi is still not receiving texts. 

Any pointers?

Thanks

**Comment by rjmackay** [comment]
Closing this as its old. Reopen if you have further info or still have issues.
