### ISSUE TITLE
Make tasks easily replicable across surveys

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1554]
I'm setting up tasks on three different surveys on my deployment, and I have to recreate the same tasks on each survey. it makes me want to cry 

![wailing](https://media4.giphy.com/media/d2lcHJTG5Tscg/200.gif#7)

I'm not sure how this would be done from a design perspective but... this would be super helpful IMO.

### Expected behaviour
* I Should have the option to replicate a task on different surveys

### Actual behaviour
* I have to recreate a task with the same fields across all my surveys

### Steps to reproduce the behaviour/error
* Log in
* Go to survey settings page
* Create a survey with a task
* Save and close, then create a new survey

Aha! Link: https://ushahiditeam.aha.io/features/PROD-643

**Comment by jshorland** [comment]
LOVE THIS — pinging @brandonrosage to keep in his mind as we design tasks further

**Comment by jshorland** [comment]
@brandonrosage i wish there were a way to drag cards on top of one another and create sub tasks, but there's not. So I moved this to the design column as we actively continue to design the "tasks" feature.

**Comment by brandonrosage** [comment]
I've done some work that touches on this issue in the run-up to an upcoming user test of "Tasks" -- #1383.

**Comment by jshorland** [comment]
"duplicate task" is being pushed to production this week with our latest release. closing.

**Comment by aoduor** [comment]
I'm going to flag this again as something we need for Uchaguzi, but i recognise that there's a complete redesign of this happening too.
