### ISSUE TITLE
Create CTFK discount code

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1557]
30% off Responder plan. Needs to be available as both a code and a link. Should be titled "CTFK"

**Comment by aoduor** [comment]
Clarification that it's on both surveyor AND responder :)

**Comment by jshorland** [comment]
@aoduor what's the deadline on this?

**Comment by aoduor** [comment]
@jshorland end of day tomorrow **runs and hides**

**Comment by aoduor** [comment]
Done. Closing. Thanks for the guide @rjmackay
