### ISSUE TITLE
Export button broken

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1558]
### Expected behaviour

Press export, data exports

### Actual behaviour

Press export, nothing happens

### Steps to reproduce the behaviour/error

I am working off of our https://usaelectionmonitor.ushahidi.io/views/map

When i press "export" in the Share button, nothing happens

**Comment by rowasc** [comment]
@jshorland this one seems to be invalid at the moment. 
- the CSV export feature exports data now 
-The specified deployment doesn't exist

**Comment by jshorland** [comment]
Fixed. closing.
