### ISSUE TITLE
Add list of countries or location search option on map settings page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1559]
### Expected behaviour
As an admin, i'd like to be able to select my geographic area of focus from a list, OR the ability to search for a location that my map will span over, and have my map automatically zoom to that location, as opposed to having to drag and drop the pin on the map as my only option

### Actual behaviour
Right now, for example, if my map is centered on kenya, and i want to change it to the US, I have to drag the pin and the map to my desired location

### Steps to reproduce the behaviour/error
* Log into your deployment
* Click on settings, then general settings
* Attempt to change your map location

Aha! Link: https://ushahiditeam.aha.io/features/PROD-642

**Comment by rowasc** [comment]
Ah yea this would be good to improve . 
Tagging with the location theme so we review it later. Leaving gif of how it behaves now for reference , it takes more work than ideally should
![settings-map-pin](https://user-images.githubusercontent.com/2434401/59134484-bb586700-8951-11e9-9a0f-11398c8008b7.gif)

**Comment by Erioldoesdesign** [comment]
Oof. Yeah this isn't good UX...hmm I have thoughts on how to design this but I'd need some time to do that.
