### ISSUE TITLE
Non descript error message when there are no saved searches for me to view

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1561]
### Expected behaviour
If there are no saved searches available on the list for me to pick from, i should get a message saying "No saved searches available" or something?

### Actual behaviour
I get this error on the dropdown list
![screenshot](http://i.imgur.com/eNKODIj.png)

### Steps to reproduce the behaviour/error
* Go to https://testctfk.ushahidi.io/views/map
* Click on saved searches, while not logged in.

**Comment by jshorland** [comment]
@aodour can you tag this as a p0?
