### ISSUE TITLE
CSV Column to Survey field Mapping Not working

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1562]
I successfully uploaded a CSV file but was unable to proceed with import because the platform didn't show me what fields i'm mapping to my CSV columns. See below.

![screenshot](http://i.imgur.com/g5f3YbX.png)

**Comment by pedrofuentes** [comment]
@rjmackay @aoduor any progress on this? we are blocked on uploading information to chileayuda.ushahidi.io from our csv files, thanks.

**Comment by aoduor** [comment]
@pedrofuentes - i've got @willdoran investigating this issue. What browser are you using?

**Comment by willdoran** [comment]
@pedrofuentes I've created an account on your deployment, would you give it admin rights?

**Comment by willdoran** [comment]
@tuxpiper @rjmackay I can confirm this is happening for ctfk.ushahidi.io, it appears to be the csv failing to parse in the api but I can't get further. Would one of you ping me when you are on?

**Comment by pedrofuentes** [comment]
@willdoran now you are an admin

**Comment by willdoran** [comment]
@pedrofuentes thanks I think I have found the problem, will fix as quickly as possible!

**Comment by pedrofuentes** [comment]
Awesome @willdoran ! were you able to fix it?

**Comment by aoduor** [comment]
Ping @willdoran confirming this still isn't working for me :(

**Comment by willdoran** [comment]
@aoduor hmmm nuts, Ok let me double check again

**Comment by willdoran** [comment]
@pedrofuentes It should be fixed and live now, sorry for the delay, can you confirm if the problem is fixed for you?

**Comment by pedrofuentes** [comment]
@willdoran yes I got confirmation that is working, thanks!

**Comment by willdoran** [comment]
@pedrofuentes Wonderful!
