### ISSUE TITLE
Revise HTML structure of toolbar for Map + Timeline

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1563]
The "toolbar" on Map and Timeline views currently inserts some containers for "embed-only" content between the "searchbar" and the non-embed-only "button-group":

![code sample](https://cloud.githubusercontent.com/assets/1136279/22434346/47208698-e6e1-11e6-8dc2-574b195f0f28.png)

Can we please revise the source order of these children to the "toolbar" to:

1. `.fab`
2. `.searchbar`
3. `.button-group[embed-only="false"]`
4. `.toolbox[embed-only="true]`
5. `.button-group[embed-only="true"]`

cc/ @willdoran

**Comment by rjmackay** [comment]
I think this can go straight into backlog

**Comment by rjmackay** [comment]
@middle8media is this something you could look at in the client?

**Comment by middle8media** [comment]
Yes, although I am unsure as to why the order is off and where to go to change it.
