### ISSUE TITLE
"Sorry something went wrong" when creating new deployment

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1564]
### Expected behaviour
I create a deployment, and after the tour and choosing my plan, it sends me to the deployment
### Actual behaviour
After I created the deployment and choose Mapper, it says "Sorry, something went wrong. Try reloading the page" 

I have attempted to reload on multiple browsers, no luck.
### Steps to reproduce the behaviour/error
See if you can go to 
https://equality.ushahidi.io

**Comment by natmanning** [comment]
After about 2 min, the page loaded.

**Comment by Offliner21** [comment]
“Sorry, something went wrong. Try reloading the page.” on client
Hello, I've been having this issue fo days now,
I am running the API and the client on different domains as you see below
I am running the API on my local machine.

![apiconf](https://user-images.githubusercontent.com/6979276/27656877-9bdce380-5c42-11e7-9365-cdb06aaf5a62.png)
![clientconf](https://user-images.githubusercontent.com/6979276/27656878-9be1cb7a-5c42-11e7-9062-391b81f86215.png)

Can anyone help me, please?

**Comment by rjmackay** [comment]
This is a known issue. It just takes a few minutes to deploy
