### ISSUE TITLE
Include 'progress' feedback on 'Export to CSV'

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1565]
**User story**: After choosing to "Export to CSV," I want the deployment to tell me that it's doing so _and_ when it's finished.

cc/ @jshorland, @caharding 

------

I've demonstrated an interaction and pattern in the `develop` branch that addresses this need, [most recently called out by @natmanning in Slack](https://ushahidi.slack.com/archives/platform/p1485466755000003). You can sample it in [Map](http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/timeline.html) and [Timeline](http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/timeline.html) layouts by selecting "Share" and "Export to CSV."

Doing so prepends the `.progress-bar` pattern -- in this specific case -- to the `.toolbar` that the "Share" button is a child of:

![progress example](https://cloud.githubusercontent.com/assets/1136279/22438345/33c935b2-e6f1-11e6-98c3-3260448538b1.png)

When the export is complete and the browser download begins, their deployment should display a non-modal message (at the bottom of the view):

![export complete](https://cloud.githubusercontent.com/assets/1136279/22438562/13a8e7d6-e6f2-11e6-973e-9b9e3e06bd40.png)

**Comment by brandonrosage** [comment]
@aoduor, @KrisKuri: Please use this as a cue to create fresh issues for other actions users perform in Ushahidi that they've expressed don't prompt adequate system feedback from the app. I can then direct how exactly the "progress" pattern(s) should be attached to those actions.

**Comment by aoduor** [comment]
Got it @brandonrosage :)
