### ISSUE TITLE
Empty datasets should use 'message' to provide context

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1566]
### Expected behavior
When encountering a deployment's survey responses (in Map or Timeline mode), including Collections & Saved Searches, and there are no responses to show, messaging about the empty dataset should be delivered in a non-modal "message" pattern:

![Empty Collection](https://cloud.githubusercontent.com/assets/1136279/22475222/e5fd8b7c-e7a3-11e6-9e94-49652c302927.png)

### Actual behavior
When encountering a deployment's survey responses (in Map or Timeline mode), including Collections & Saved Searches, and there are no responses to show, a short message appears within the Timeline:

![Empty Timeline](https://cloud.githubusercontent.com/assets/1136279/22475285/16cda9da-e7a4-11e6-8eca-ae549db16e07.png)

And the Map offers no message.

### Steps to reproduce the behavior/error
View an empty dataset.

**Comment by rjmackay** [comment]
@jshorland I have no idea if this is important. If its worth doing, it could go into UX cleanup
