### ISSUE TITLE
Send survey questions to reporters by SMS or Email

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1568]
Add ability to send survey questions out to reporters by SMS or Email, either as a one off or on a regular schedule (ie. weekly).

This would be helpful for organisations with an established volunteer base who need to be prompted to report.

This surfaced in discussions with IFRC.

**Comment by rjmackay** [comment]
@jshorland this may not be a usecase we want to support at all. But thought I'd log it and we can Icebox or close it if its not relevant.

**Comment by caharding** [comment]
turning this into email and using #493 into the SMS issue, long been open
