### ISSUE TITLE
Custom Pages

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1570]
This feature will allow users to add additional content information to their deployments. It is intended to address the user created pages for v2.

It is currently covered by the following issues:
- [1575](https://github.com/ushahidi/platform/issues/1575)

**Comment by aoduor** [comment]
Refs https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/unassigned/conversations/9910447949

**Comment by aoduor** [comment]
Feedback from intercom user on importance of custom pages

"Thank you but is there a way to get around this? I mean at least in Germany you can't publish a serious website without publishing at least some details about who you are."

**Comment by jshorland** [comment]
Closing in favor of #1575
