### ISSUE TITLE
Campaigns: a deployment 'overview' screen

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1575]
**User story**: I want to tell people who visit my deployment what its purpose is, the story its data might be telling, and what they can do to contribute, using text, images, and video. I want this information to be the first thing they see when arriving at my deployment.

**User story**: A deployer wants to be able to send updates to anyone who subscribes to the deployment which are sent out as notifications via however a user subscribes

**User story**: A deployer wants to be able to set a "goal" of how many posts they are looking to receive

**Comment by brandonrosage** [comment]
For reference, @jshorland, @caharding, and I have contributed design assets to this story, considering a range of scopes.

For example, here's a wireframe for a deployment (called a "campaign," in this context) overview in a larger product shift:

![v4 wireframe](https://cloud.githubusercontent.com/assets/1136279/22602818/6ac868e6-ea0a-11e6-9dfa-4580d98685b2.png)

Here's a mockup of that same idea and scope:

![v4 mockup](https://cloud.githubusercontent.com/assets/1136279/22602875/aa1c04a8-ea0a-11e6-8788-1ed067154f4f.png)

And here's a wireframe of a deployment's overview screen in a much more constrained scope, sharing more DNA with today's product:

![v3 wireframe](https://cloud.githubusercontent.com/assets/1136279/22602943/ec8ee63e-ea0a-11e6-9849-fbe6507506af.png)

**Comment by caharding** [comment]
I really like the simplified version at the bottom. Questions that arise
* Is there another top level menu for browsing between deployments (campaigns)?
* How could someone run the same campaign in multiple places?
* Are surveys and their management done under settings with links to them also in "contribute" and "responses"?

**Comment by brandonrosage** [comment]
> Is there another top level menu for browsing between deployments (campaigns)?

The wireframe at the bottom is intended to be something that doesn't require any engineering beyond the scope of this single feature. So it doesn't assume the ability to manage multiple deployments under a single account or any "Discover"-like functionality.

That said, in my mind, we get there by simply establishing another "layer" behind the campaign for Ushahidi. Visually, similar to this:

![v4 header](https://cloud.githubusercontent.com/assets/1136279/22990049/9267e6e8-f37d-11e6-862b-7cef7149aa39.png)

> How could someone run the same campaign in multiple places?

Could you explain this a bit, @caharding ? I know we've discussed using a survey in multiple campaigns. But I'm not clear what contexts you'd encounter a campaign.

> Are surveys and their management done under settings with links to them also in "contribute" and "responses"?

Yes.

**Comment by caharding** [comment]
@brandonrosage that question is really about how do we deal with an organization that wants to run the same kind of campaign in 7 countries (think UN). Can they duplicate? Can they manage all of them from 1 account? Can they export and mash up data?

**Comment by caharding** [comment]
I think I was confused about how / when this would be implemented, since the top level menu items were top nav rather than left nav. Makes sense to get the simple thing out first.

**Comment by jshorland** [comment]
Should also include contact instructions or form

**Comment by rowasc** [comment]
Closed in favor of https://github.com/ushahidi/platform/issues/1894
