### ISSUE TITLE
Define user migration process

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1580]
- [ ] What will the user migration experience look like?
- [ ] What level of technical skill will migration require?
- [ ] Is the v3 deployment created by the user or automatically by the migration tool
- [ ] What tier would users migrate to?
- [ ] How much support do we offer? Can we give them an migration guide. “Upgrade Day/Week”, specific day day dedicated to support for upgraders, there after upgraders help should help each and we should update documentation.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-632

**Comment by willdoran** [comment]
- Users currently used to interacting via categories not surveys - How do we explain the difference between Survey and Category to user
- Need to extend V2 via patch
- Use deployment owner as .io user
- Get same url on .io
- Do user's have option to migrate self-hosted to self-hosted, or only to cloud? Is latter, how do tiers/costs work?
- If user's take migration to trial of cloud and after trial expires they do not wish to continue then we can give them the option to download all their data as a database dump BUT they will have to go about setting up self hosted v3 themselves.

**Comment by rjmackay** [comment]
Started brain storming this here: https://docs.google.com/document/d/1CWNRWK7exaqGTF1MVSdPaA88nv0S1u42T3QF2hkGhds/edit#

The proposed stages are:
1. Provide a command line importer so we can run imports ourselves for clients/one off requests
    - This will require *some* technical skill, similar to self hosting a deployment
2. Connect that to a 'push button' that imports deployments from Crowdmap classic to Ushahidi.io
    - This shouldn't require any tech skill
    - This will be a one-off process that imports into a brand new deployment, zero options.
    - Target is to migrate into Grassroots or paid plan
