### ISSUE TITLE
survey custom colors on platform aren't appearing on the side of surveys, pop up summary boxes, or cards in timeline view

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1587]
### Expected behaviour
Assigned colors appear on post cards, summary boxes, and on the side of each survey in the map view left side info bar

### Actual behaviour
![screen shot 2017-02-21 at 7 11 51 pm](https://cloud.githubusercontent.com/assets/3224856/23164511/fa5e50fc-f869-11e6-997b-3f9e989c9c56.png)

**Comment by jshorland** [comment]
Fixed. Closing.

**Comment by Angamanga** [comment]
This is deployed so closing.
