### ISSUE TITLE
Change URL of usaelectionmonitor.ushahidi.io

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1593]
can we change this deployment from usaelectionmonitor. to documenthate.ushahidi.io?

**Comment by jshorland** [comment]
@tuxpiper are you able to do this quickly on the backend?

**Comment by tuxpiper** [comment]
@jshorland I wouldn't do a change like this quickly, but rather I'd rather do it in the right setup, with a cup of tea and lounge music. But yea, I can take a look.

**Comment by tuxpiper** [comment]
Done!
