### ISSUE TITLE
Configure six webhooks for Intercom to monitor

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1595]
In order to properly target new deployers for an Intercom-powered on-boarding process (and to send the right message at the right time), we need to be able to monitor a few things in Intercom regarding any given deployment/user:

* User's deployment has a description (true or false)
* User's deployment has a logo (true or false)
* Number of active data sources on user's deployment
* Number of users on user's deployment
* The name of No. 1 survey on user's deployment (we want to see if they've renamed the default survey)
* The date the user's deployment was created

Regarding a deployment's "date created," we really just need some indication that the user's deployment is new, in order to begin a campaign when they first land on their deployment. The assumption with "date created" is that we could compare it to the campaign's start date in order to send the campaign first-thing to all deployments created after that point in time.

**Comment by rjmackay** [comment]
@willdoran you should probably spec this along with the other intercom events issue

**Comment by willdoran** [comment]
This should be done at the same time as [132](https://github.com/ushahidi/platform-client/issues/132)

**Comment by willdoran** [comment]
As opposed to [132](https://github.com/ushahidi/platform-client/issues/132), these should be configured on the API. The following needs to be implemented:

- [ ] Add Intercom Listener
- [ ] Load Intercom Config
- [ ] Add hook at Config update for 
  - [ ] Deployment Logo - send boolean to Intercom
  - [ ] Deployment Description - send boolean to Intercom
- [ ] Add hook at datasource update
  - [ ] Send Number of datasources to Intercom
- [ ] Add survey update/delete hook
  - [ ] If first survey changed - specifically name - send name to Intercom
- [ ] This would ideally come from the cloud creation, but it could equally be a hook on config when first log in is completed. However, the latter might be too late. This requires a little more thought.

**Comment by jshorland** [comment]
@willdoran should i move to dev backlog?

**Comment by rjmackay** [comment]
@will where's this at?
Dale suggested using https://segment.com/ to funnel metrics to various tools.. which could actually work well if we *haven't* already done the intercom work. It'll cost a little but may give us more flexibility for data warehousing later. If we've already started on sending intercom events we can ignore Segment for now.

**Comment by jshorland** [comment]
@will this after mobile banners

**Comment by willdoran** [comment]
@jshorland PR with checklist is here for QA #1718

**Comment by jshorland** [comment]
Passes QA

**Comment by rjmackay** [comment]
Waiting for #1734 to be finished before this is enabled

**Comment by rjmackay** [comment]
@willdoran how do we enable this? I'd like to turn it on in staging and reconfirm its working, then deploy to prod
