### ISSUE TITLE
USH-003 -- Insecure SSL/TLSConfiguration

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1599]
### Expected behaviour
- Use Diffie-Hellman parameters larger than 1024 bits.
### Actual behaviour
- This server supports weak Diffie-Hellman (DH) key exchange parameters
- Ref: USH-003
### Steps to reproduce the behaviour/error

**Comment by tuxpiper** [comment]
Duplicates ushahidi/engineering#37
