### ISSUE TITLE
USH-005 Open Port 22 SSH

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1600]
### Expected behaviour
- Implement a bruteforce protection (for instance fail2ban or log2iptables)
- Create firewall rules who can access SSH. (only internal access for instance)
- Use a different port for SSH. (this will evade automatic portscanners that only scan for SSH on the
default port
- Use portknocking to open the port on demand
### Actual behaviour
- The Nmap scan reveals an open SSH port 22 on ushahidi.com.
### Steps to reproduce the behaviour/error

**Comment by rjmackay** [comment]
@tuxpiper how can I QA this? or is it deployed and we should just close?

**Comment by rjmackay** [comment]
`nmap ushahidi.com` still shows port 22 as open

**Comment by rjmackay** [comment]
This issue was moved to ushahidi/platform-cloud-ansible#33
