### ISSUE TITLE
USH-006 — Path Disclosure Revealed by Stacktrace (Ushahidi.io)

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1601]
### Expected behaviour
- Disable detailed error reporting to users, and catch all uncaught exceptions. Log detailed error messages in
dedicated logfiles which aren't available for Internet users
### Actual behaviour
- Causing an exception in https://ushahidi.io/settings/timeline.html leads to information
leakage about the running code as well as the nature of the triggered error.

**Comment by rjmackay** [comment]
Deployment issue: need to set APP_DEBUG=false on platform-cloud-interface

**Comment by rjmackay** [comment]
This is now fixed.
