### ISSUE TITLE
USH-007 — API Does Not Have a CSRF Protection (X.ushahidi.io)

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1602]
### Expected behaviour
- Implement anti-CSRF tokens to all requests that perform actions to change the application state,
or that add, modify, or delete content. An anti-CSRF token should be a long, randomly-generated
value, unique to each user, so attackers cannot easily brute-force it
- It is important to validate anti-CSRF tokens when the application handles user requests. The
application should both verify that the token exists in the request, check that it matches the user's
current token, and make sure that it hasn't been used before. If one of these checks fails, the
application should reject the request.

### Actual behaviour
- The API does not verify whether a request originates from its own website, or if it was submitted by a user using a form on a malicious website.

**Comment by rjmackay** [comment]
I don't think this makes sense given that requests are always authenticated. If auth was via cookie it would be a concern, but it isn't. They can't pull the oauth token from local storage unless there's already an XSS issues. @willdoran am I missing something?

**Comment by rjmackay** [comment]
> This vulnerability allows an attacker to create a malicious web site that forges a cross-domain request to the vulnerable website. An attacker can execute any function on the website under the user's credentials. However the impact is low because the Bearer token needs to be obtained first for this to work.

I'd actually argue the impact is lower than low. Its just not a bug.

**Comment by willdoran** [comment]
This may have been a based on anonymous form submission. If we want to make sure only our client(s) can perform anonymous form submission CSRF is important. Otherwise it just acts as a deadbolt. Lumen has CSRF through Laravel, I think.

**Comment by rjmackay** [comment]
Most CSRF protection relying on the HTML being generated by the server that receives the HTTP request though. I'm not sure how we'd get the CSRF token from the API into the client in a way that could be replicated cross-site anyway
