### ISSUE TITLE
USH-008 — Persistent Cross Site Scripting in Post Description (X.ushahidi.io)

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1603]
### Expected behaviour
- Filter all client-provided input parameters, and escape all output variables.
- Make use of a whitelist, and prevent certain characters from being inserted if it's not necessary for
the working of the application.

### Actual behaviour
- It is possible to inject Javascript and HTML into pages by modifying the description field of an individual post.

**Comment by rjmackay** [comment]
This issue was moved to ushahidi/platform-cloud-interface#174
