### ISSUE TITLE
USH-012 — Lack of Bruteforce Protection new user.

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1607]
### Expected behaviour
- Captcha
- IP limit or lockout for a certain amount of time
### Actual behaviour
- There is no protection against the automatic creation of useraccounts. It was possible to create 10 accounts in 10 seconds.

### Test script
- Go to a deployment (ie. qa.ushahididev.com)
- In under 1 minute:
    - Register a new user
    - Register a second new user
    - Register a third new user
    - Register a fourth new user
- Assuming this was done quickly, the fourth user should fail

**Comment by rjmackay** [comment]
We have a rate limiter for auth, we should add that to this endpoint.

**Comment by rjmackay** [comment]
Tagged this to cycle 4 since its current in progress

**Comment by rowasc** [comment]
@willdoran what should we do about this ticket?  move to ready for dev to port to kohana?

**Comment by rjmackay** [comment]
It still needs to land to develop. We should fix the conflicts and land it. Then close this issue. Backports are tracked in their own issue.

**Comment by rjmackay** [comment]
I've rebased the existing PR. It just needs tests to run then it can land and go to QA

**Comment by rjmackay** [comment]
@Eve-wanderi I've added a test script. It's possible this might be too hard to test manually - ie. registration is too slow through the UI so you never hit the rate limit. If so let me know and I can try to test directly on the API

**Comment by Eve-wanderi** [comment]
@rjmackay Yea its quite a challenge for me to Do all four Registrations for a new user in less than 1 minute. Since am doing this manually. Could you please assist testing this directly on the API.
