### ISSUE TITLE
USH-014 — No Clickjacking Protection

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1609]
### Overview
The Ushahidi platform allows certain urls to be embed in frames to allow users to frame their deployments on their own pages. However, we should limit this to only that specific url via configuration and update our docs for OSS users.

### Requirements:

- Update configuration to include X-Frame-Options HTTP Response header by default (#2720)
- Update ushahidi.io to include this header for all URLs except explicit embed URL
- Update documentation to include header
  - Be sure to explain the impacts on our ability to embed this site
- Assess and spec: Adding an embed-only entry point (ie. `embed.html`) which doesn't include the rest of the site
  - This is future work. But a good time to spec it

### Acceptance criteria
- [ ] Embed URLs can be used within frames on external pages
- [ ] All other urls for a deployment are blocked in frames on external pages
- [ ] Support docs include section describing webserver config for inclusion of X-Frame-Options header
- [ ] A basic spec and ticket have been created covering allowing only embed.html entry points for frames

Aha! Link: https://ushahiditeam.aha.io/features/PROD-628

**Comment by rjmackay** [comment]
This should be a simple fix.

For client: add this header via nginx config
For cloud ui: add the header via middleware

**Comment by willdoran** [comment]
This breaks embed

**Comment by Brad-Anthony** [comment]
As noted in https://github.com/ushahidi/platform/issues/2715 we would love to disable embeds permanently and securely. I suspect this option will be a part of that solution and should be noted to other users that do not want to have their content on external embeds for security reasons, etc.

**Comment by digitalhuman** [comment]
@willdoran @rjmackay this is an 'easy' fix yeah, but with big impact. It can/will affect functionality in Ushaidi if you implement this as "lets just do it" like I explained to @Brad-Anthony. This area is, in my opinion, a shared responsibility. Every sysadmin should have implemented these security headers by default know, but on compute machines things work a bit different. The risk impact by not having these headers implemented is to high for Ushaidi to ignore and should be implemented by default. In our case (and most likely others) they are stealing credentials. Or at least try to.

As explained in https://github.com/ushahidi/platform/issues/2715 please be careful with "double headers" and Content-Security-Policy. These will break the application if not done correctly. We are now forced to shutdown the server since we are not able to change the web-server settings.

**Comment by rjmackay** [comment]
Requirements:

- Update configuration to include this header by default
- Maybe: Update ushahidi.io to include this header for all URLs except explicit embed URL
- Update documentation to include header
  - Be sure to explain the impacts on our ability to embed this site

- Assess and spec: Adding an embed-only entry point (ie. `embed.html`) which doesn't include the rest of the site
  - This is future work. But a good time to spec it

**Comment by rowasc** [comment]
This should be out of icebox if it's in a cycle. Should it be in "ready for spec"?

**Comment by willdoran** [comment]
@rjmackay can you review?

**Comment by rjmackay** [comment]
Approved

**Comment by willdoran** [comment]
@rjmackay Yeah, that's annoying I had also thought it was a route. Do we need to add another step of changing or at least updating the behaviour to also work with a route? As in leave the check as is but also add an embed route.

**Comment by rjmackay** [comment]
I think a possible interrim solution is:
- Add "X-Frame-Options: DENY" header to any route thats *not* /posts or /view
- In JS, Disable login / password reset / settings routes when embedded.

Thats probably not foolproof but it's unlikely to break any existing embeds, and not super complex. We should definitely figure out adding a separate entry point for embeds in future.. but I don't want to rush it.

**Comment by rjmackay** [comment]
@rowasc This should probably move to Cycle 8

**Comment by tuxpiper** [comment]
Regardless of the solution, any improvement on this will have effects on a lot of people that are iframing platform as a solution to skin it.

I suggest we turn this into a roadmap item, with corresponding rollout and communication plans. There should be nuanced explanations about the vulnerability and the different safe (and unsafe) options that can be taken and how they can be enabled.
