### ISSUE TITLE
USH-016 — SSL Cookie Without Secure Flag Set

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1611]
### Expected behaviour
- Set the Secure flag for all cookies that are being communicated over a secure channel.
### Actual behaviour
- The following cookies were issued by the application and do not have the secure flag set:
  - XSRF-TOKEN
  - laravel_session
 The cookies appear to contain session tokens, which may increase the risk associated with this issue. You should review the contents of the cookies to determine their function.

**Comment by rjmackay** [comment]
This issue was moved to ushahidi/platform-cloud-interface#175
