### ISSUE TITLE
USH-017 — The Session Does Not Expire When the User Logs Out.

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1612]
### Expected behaviour
- Revoke the session when the user logs out.
### Actual behaviour
- The session (Bearer Token is used for this) does not expire when the user logs out. It is possible to close the session and still use the same one to send request until it expires. When a user logs out the session is still available until it expires.

This is probably not worth fixing in Kohana. But should be doable in Lumen.

# Spec

## Overview
Add an API endpoint for destroying an oauth session

### API endpoint definitions

- New endpoint: `POST /oauth/logout` (to match `/oauth/token`
- Implemented purely in Laravel, doesn't need to touch app core
- Empty payload

### New UI behaviour

- When a user logs out, send a POST request to /oauth/logout

## Acceptance criteria / Test script
- Authenticated call to `POST /oauth/logout` returns 204
  - Subsequent calls using the same auth token to any API endpoint should fail
- Unauthenticated call to `POST /oauth/logout` returns 403

- Log in to a deployment
  - Check DB and see new oauth token is created
- Log out
  - See request to /oauth/logout
  - Check DB and see token is revoked or deleted
  - Retry a previous authenticated request and see if fails (only possible if you use a proxy of some form)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-627

**Comment by rjmackay** [comment]
- We should add an endpoint to destroy an oauth session

**Comment by rjmackay** [comment]
This is probably not worth fixing in Kohana. But should be doable in Lumen.

## Overview
Add an API endpoint for destroying an oauth session

## Requirements

### API endpoint definitions

- New endpoint: `POST /oauth/logout` (to match `/oauth/token`
- Implemented purely in Laravel, doesn't need to touch app core
- Empty payload

### New UI behaviour

- When a user logs out, send a POST request to /oauth/logout

## Acceptance criteria / Test script
- Authenticated call to `POST /oauth/logout` returns 204
  - Subsequent calls using the same auth token to any API endpoint should fail
- Unauthenticated call to `POST /oauth/logout` returns 403

- Log in to a deployment
  - Check DB and see new oauth token is created
- Log out
  - See request to /oauth/logout
  - Check DB and see token is revoked or deleted
  - Retry a previous authenticated request and see if fails (only possible if you use a proxy of some form)

**Comment by rowasc** [comment]
@rjmackay this looks good to me, can we move it to the description of the ticket or is there a reason for having it separate  until (I assume) Will reviews it?

**Comment by rjmackay** [comment]
Moved to description. Ready for review now

**Comment by rjmackay** [comment]
It turns out there's a built in passport controller for this. It might not be registered yet because of some awkward lumen/passport interaction.

But we should look at AuthorizedAccessTokenController@destroy in case its usable - usually registered as `DELETE /token/{token_id}`

**Comment by rjmackay** [comment]
@rowasc @jrtricafort could we tentatively schedule this for Cycle 8? It's not worth doing till post-lumen launch

**Comment by tuxpiper** [comment]
The worst case would be an attacker getting hold of both bearer and refresh tokens, and logout being ineffective to invalidate those.

Not entirely sure the GET and DELETE /oauth/tokens routes will do it:

* https://github.com/laravel/passport/issues/839#issuecomment-429371578

Couldn't test, since those routes don't seem to be enabled. Needs research.
