### ISSUE TITLE
USH-018 — Ansible - No Firewall Restrictions SSH

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1613]
### Expected behaviour
- Only allow internal ip-addresses (so ansible can access the server) access to this port. If any support personal should have access to the box they should use login to a special Management Server and connect from there internally.
### Actual behaviour
- The use of port 22 is very common when using ansible but this is open to the rest of the world.
### Steps to reproduce the behaviour/error

**Comment by rjmackay** [comment]
@tuxpiper how can I QA this? or is it deployed and we should just close?

**Comment by rjmackay** [comment]
This issue was moved to ushahidi/platform-cloud-ansible#32
