### ISSUE TITLE
USH-020 — Ansible - Weak Password Mysql

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1615]
### Expected behaviour
- When possible, always encrypt user names and passwords.
- Use strong passwords for all accounts on all environments.
- Use strict separation between environments and make sure not to share user names and
passwords.
### Actual behaviour
- The MySQL password in Ansible is weak.
### Steps to reproduce the behaviour/error

**Comment by tuxpiper** [comment]
Closing since this refers to already deprecated automation code
