### ISSUE TITLE
USH-022 — Role Creation and Permission Assignment

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1617]
### Expected behaviour
- Verify if a user is a paid or non-paid user.
### Actual behaviour
- It is possible to create roles and make permission assignment in the FREE version, that feature only would be available on RESPONDER version. With this request is possible to create the user and then in the platform is possible to make the assignment of permissions.

**Comment by caharding** [comment]
I'm sorry I don't understand this issue as written

**Comment by rowasc** [comment]
@willdoran is this in the right column?

**Comment by willdoran** [comment]
Yeah

**Comment by rowasc** [comment]
ah ok. @willdoran is it blocked by lumen (to deploy)?

**Comment by rjmackay** [comment]
Dropped back to QA to test the rebased version
