### ISSUE TITLE
USH-024 — Retrieve Available Member-roles as an Anonymous User.

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1619]
### Expected behaviour
- Only allow users what they should be able to see and restrict what is out of their scope.
### Actual behaviour
- It is possible to retrieve available member-roles as an anonymous user.

**Comment by rjmackay** [comment]
- Check for user id in RoleAuthorizer
- Check this doesn't break client behaviour

**Comment by rjmackay** [comment]
@willdoran I can't find the commits that fixed this at all. Are you sure it was resolved?

**Comment by willdoran** [comment]
Yeah this was fixed in february it seems
https://github.com/ushahidi/platform/commits/develop/src/Core/Tool/Authorizer/RoleAuthorizer.php?author=willdoran
