### ISSUE TITLE
USH-026 — Retrieve Members With Low Privilege User.

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1621]
### Expected behaviour
- Only allow users what they should be able to see and restrict what is out of their scope.
### Actual behaviour
- It is possible to Retrieve Information Of Members With Low Privileges

**Comment by rjmackay** [comment]
This is by design. We need user info to display user names and avatars in the UI. Closing this

**Comment by rjmackay** [comment]
@willdoran did this end up being fixed anyway?

**Comment by willdoran** [comment]
I think so yes
