### ISSUE TITLE
USH-027 — Ansible - Passwords in Different Files

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1622]
### Expected behaviour
- Do not put your password as plain text, certificates, privatekeys in your git repo, use ansible-vault (http://docs.ansible.com/ansible/playbooks_vault.html) or git-crypt (https://github.com/AGWA/git-crypt) for encrypting.
### Actual behaviour
- The review of the ansible files showed the use of plain passwords in files.
### Steps to reproduce the behaviour/error

**Comment by tuxpiper** [comment]
Closing since this refers to already deprecated automation code
