### ISSUE TITLE
USH-028 — Multiple Oauth2 Requests using Grant_type Client_credentials

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1623]
### Expected behaviour
- Fix bug
### Actual behaviour
- Multiple Oauth2 requests are made when a user logs in as an anonymous user (grant type client_credentials).
- This behaviour is probably a bug, and will cause unnecessary load on the server. It also increases the attack surface, as a lot of tokens are being generated, which all could be mis-used

**Comment by rjmackay** [comment]
I believe this is fixed now.
