### ISSUE TITLE
USH-029 — Vimeo API-key Secure Storage

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1624]
### Expected behaviour
- Upload the vid to your server as intermediary where the upload to vimeo with the API
- Ask users to login with their own Vimio account. (is more of a hassle)
### Actual behaviour
- The Developer of the Mobile Apps asked how to securely storage access tokens needed for API calls.

**Comment by rjmackay** [comment]
> Upload the vid to your server as intermediary where the upload to vimeo with the API

That definitely the best solution, and allows for uploads from the web client eventually

**Comment by rjmackay** [comment]
@jshorland I think this is really mostly relevant if we decide to build video upload into the web client. Does this fit into any of the milestones? if not, maybe icebox. 
Basically the risk here is that someone can grab our vimeo keys from the mobile app and upload whatever they want to our vimeo account.

**Comment by rjmackay** [comment]
@dalezak what operations scopes does the ushahidi app need with Vimeo? A quick check looks like it has more than necessary. Could we get by with only the upload scope?
That would be a quick and easy security win.

**Comment by rowasc** [comment]
This should be out of icebox if it's in a cycle. Where should it go?

**Comment by dalezak** [comment]
@rjmackay @rowasc I believe the Vimeo `Personal access tokens` has the necessary scopes for the mobile app to be able to upload a video and then edit that video making it private so that other users can not see it.

![screenshot 2018-06-20 08 10 39_preview](https://user-images.githubusercontent.com/91811/41663793-7da9db92-7461-11e8-9b4f-1ab489a91346.png)

**Comment by rowasc** [comment]
seeing Dale's response.. should we close this ticket? @dalezak @rjmackay

**Comment by rjmackay** [comment]
My concern is that if the scopes allow listing private videos, and the access token isn't stored securely, then it doesn't matter if the videos are private: Someone with the token can still access them all.

**Comment by dalezak** [comment]
Sadly Vimeo's API is pretty limited 😞 

I tried to create another Access Token for testing using only `public`, `upload` and `edit` however received the error `Invalid scope combination`.  

So it looks like you need to include `public` and `private` to allow other scopes like `upload` and `edit` to be enabled.

Here's description of what each scope does https://developer.vimeo.com/api/authentication#supported-scopes

**Comment by willdoran** [comment]
@rjmackay If we're uploading to AWS, how much space do we have for this? Are we storing video or just using AWS as a proxy?

**Comment by dalezak** [comment]
If we upload to S3, there are probably _two_ options:

**One**, we only use S3 as an upload bucket and then have asynchronous web workers which handles posting that video to Vimeo and eventually updating the Ushahidi post with final Vimeo video URL.

**Two**, we upload to S3 and our backend API handles generating the WEBM, OGV and MP4 video formats (either using FFMPEG or pay for 3rd party service) so the video is playable in all browsers.

**Comment by dalezak** [comment]
FYI, my previous startup was a video interview platform, I wrote all kinds of async workers for stitching and processing videos into all the necessary video web formats using FFMPEG. It was pretty complicated and memory intensive.

**Comment by dalezak** [comment]
If we go the short lived token route, we'll need our API to generate a token from Vimeo prior to the app uploading a video, and then remove the token once the video has been uploaded.

Note, these short lived tokens still runs the risk of providing the same level of access as the current token.

**Comment by willdoran** [comment]
@rjmackay Would it be fair to say that this should include the introduction of some kind of limiter feature even if disabled to prevent infinite video upload?

**Comment by willdoran** [comment]
@dalezak @rjmackay if we even transcode the video when before we upload to S3, we still need a player :( Those things are generally awful and have tons of proprietary crap around codecs.

**Comment by rjmackay** [comment]
> Note, these short lived tokens still runs the risk of providing the same level of access as the current token.

This is the primary reason for looking at AWS. S3 provides much more limited tokens, so we can avoid that risk entirely. Given the transcoding issues, it might be more sensible to have AWS just a temporary store until videos go to vimeo.

**Comment by rjmackay** [comment]
@dalezak what does the mobile app do if the vimeo token is revoked or invalid? How does the failure show to the user?

^ This is a key question. Basically can we revoke the existing token and disable mobile video uploads while we solve this issue. Because otherwise we have an open security hole, and we need to release the audit report soon.

**Comment by rowasc** [comment]
@jrtricafort to sync with Robbie on this

**Comment by jrtricafort** [comment]
@rjmackay I believe @dalezak answered your earlier question in the slack thread. Let's continue the conversation there.

**Comment by rjmackay** [comment]
I plan to revoke the API tokens tomorrow, pending OK from @Celestine22

**Comment by rjmackay** [comment]
API keys have now been revoked

**Comment by Celestine22** [comment]
@rjmackay we have an OK.

**Comment by rowasc** [comment]
@jrtricafort moved this to cycle 8 as we are not going to get to it on time.

**Comment by rowasc** [comment]
Added a ticket to spec the video upload, I don't think this vimeo ticket is still relevant since we are ggoing with a different approach. I linked the new issue #3179 to this one as reference. We should spec it in cycle 8

**Comment by dalezak** [comment]
Vimeo upload has been removed from the mobile app, so this issue is not longer relevant... closing issue.
