### ISSUE TITLE
USH-030 — SSH Server of ushahidi.com Insufficiently Hardened

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1625]
### Expected behaviour
- Disable the key exchange algorithms ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group1-sha1, diffie-hellman-group14-sha1 and diffie-hellman-groupexchange--sha1.
- Disable the server authentication algorithms ssh-dss and ecdsa-sha2-nistp256.
- Disable the encryption algorithms 3des-cbs, arcfour128 and blowfish-cbc.
- Disable the message authentication codes hmac-md5, hmac-md5-96, hmac-sha1, hmac-sha1-96 and umac-64@openssh.com.
### Actual behaviour
- The SSH server listening on ushahidi.com port 22 allows a number of less-secure key exchange algorithms, server authentication algorithms, encryption algorithms and message authentication codes.
### Steps to reproduce the behaviour/error

**Comment by rjmackay** [comment]
@tuxpiper how can I QA this? or is it deployed and we should just close?

**Comment by rjmackay** [comment]
This issue was moved to ushahidi/platform-cloud-ansible#34
