### ISSUE TITLE
shadowhand/email deprecated and removed, breaking setup

### ISSUE THREAD

**Issue by sudheesh001** [ushahidi/platform#1626]
### Actual behaviour

The setup process involves the `composer` process fetching the required modules but it looks like the `shadowhand/email` module has been removed altogether by the owner after deprecation. ushahidi is still dependant on the module, is there an alternative module that we could use to set this up ?

### Expected behaviour

A clean setup process after `bin/update`

### Steps to reproduce the behaviour/error

Run `bin/update`

```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 27 installs, 0 updates, 0 removals
  - Installing shadowhand/email (v2.0.2) Downloading: Failed    Failed to download shadowhand/email from dist: The "https://api.github.com/repos/shadowhand/email/zipball/e2295fa2ddc23b1b2c206f7716128e51f0557008" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing shadowhand/email (v2.0.2) Cloning e2295fa2dd


  [RuntimeException]
  Failed to clone https://github.com/shadowhand/email.git via https, http protocols, aborting.
  - https://github.com/shadowhand/email.git
    Cloning into 'C:\xampp\htdocs\platform\vendor\shadowhand\email'...
    remote: Repository not found.
    fatal: repository 'https://github.com/shadowhand/email.git/' not found
  - http://github.com/shadowhand/email.git
    Cloning into 'C:\xampp\htdocs\platform\vendor\shadowhand\email'...
    remote: Repository not found.
    fatal: repository 'https://github.com/shadowhand/email.git/' not found


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
```

**Comment by tuxpiper** [comment]
Confirmed on my side. Since it's probably affecting everyone, I think this deserves P0 @jshorland

**Comment by jshorland** [comment]
Yep. Add p0 and put in dev backlog please?

iPhone iTypo

**Comment by sudheesh001** [comment]
I found this module after digging through the internet, https://github.com/kierangraham/email 
If this is the module that's been taken down, I wouldn't mind helping you to get an entry into Packagist ! 😄 Would love to help if needed.

**Comment by willdoran** [comment]
@sudheesh001 if you have time and would like to contribute we'd be happy to receive said help :D If you want to submit a PR you can assign me for review and I'll take a look.

**Comment by rjmackay** [comment]
@willdoran I've still got a cached copy of the module I can drop in a repo or compare against the keirangraham one.

**Comment by willdoran** [comment]
@rjmackay awesome, that would be super handy, if you link me I can compare

**Comment by rjmackay** [comment]
@willdoran https://github.com/kierangraham/email is the original kohana email module, rather than the updated version packaged for composer. I've pushed my cached version to https://github.com/rjmackay/shadowhand-email

**Comment by sudheesh001** [comment]
@rjmackay Awesome ! Have you uploaded the entry to packagist so that we can update the composer entry ?

**Comment by sudheesh001** [comment]
@rjmackay I've updated my composer file to contain a reference to https://packagist.org/packages/sudheesh001/email for the breaking `email` and managed to successfully setup the migrations.

**Comment by rjmackay** [comment]
@willdoran did you have time to resolve this? if not I'll take a look this week

**Comment by willdoran** [comment]
@rjmackay No, I didn't get a chance yet. If I do before you're online. I'll update here.

**Comment by rjmackay** [comment]
@sudheesh001 I've fixed this on the master and develop branches now. It uses ushahidi/shadowhand-email

**Comment by chrisveness** [comment]
Having reported this a couple of days ago via the developer community (www.hipchat.com?), I can confirm this is now fixed for me (though I've now hit another problem #1654).

**Comment by sudheesh001** [comment]
Looks like this is fixed, good to close. 👍
