### ISSUE TITLE
It is not possible to add a photo to a post

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#1628]
### Expected behaviour
When choosing a photo, the photo should be added to that post and stay after saving.

### Actual behaviour
After saving a post together with a photo, the new photo is not saved together with the post.

### Steps to reproduce the behaviour/error
1. Create a new post
2. Choose a new photo to be uploaded
3. Save the post
4. Publish/review the post
5. The photo is not there!

**Comment by Angamanga** [comment]
This seems to be two different problems: 1. If trying to upload a photo that is too big, I don't get a warning, it just saves and the photo is not uploaded = post with no photo. I'll try to fix that today. 2. Images cannot be set to required but it is set to required on your survey-type that was bugging yesterday @jshorland. Has it been possible to add the required-option before and now it is removed? @willdoran

**Comment by Angamanga** [comment]
@jshorland this can be tested on qa.ushahididev.com

**Comment by jshorland** [comment]
Passes QA!
