### ISSUE TITLE
API Config Site Returns Non-Encoded Image_Header URL

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#1635]
### Expected behaviour
The `/api/v3/config/site` endpoint is returning non-encoded `image_header`, which is causing some issues in the mobile app.

### Actual behaviour

Some Deployment `image_header` include whitespace in the URL.

### Steps to reproduce the behaviour/error

With a valid `access_token`, hitting https://USAelectionmonitor.api.ushahidi.io/api/v3/config/site returns:

```
"image_header": "https://74ddb495e3f187ded630-0b4c691ea14dad11384ab079da46af4f.ssl.cf2.rackcdn.com/usaelectionmonitor.api.ushahidi.io/5/8/5810e52688ec4-round simple on light.png"
```

Which includes whitespace in the image URL, but probably should instead return

```
https://74ddb495e3f187ded630-0b4c691ea14dad11384ab079da46af4f.ssl.cf2.rackcdn.com/usaelectionmonitor.api.ushahidi.io/5/8/5810e52688ec4-round%20simple%20on%20light.png
```

Perhaps a solution is for the image uploader should sanitize the file URLs before it is saved?

**Comment by rjmackay** [comment]
@crcommons you could look at this as a first issue in the API. This should be a change needed in the Media Formatter class somewhere.  Have a look around, and then I can give you a run through of *how* that various parts fit together

**Comment by rjmackay** [comment]
@dalezak could you test this against a staging deployment? ie. (qa.ushahididev.com)
