### ISSUE TITLE
Include image_url in API's Posts Response

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#1636]
### Expected behaviour
Currently, the API `/posts` endpoint does not return a default image for a post. 

It would ideal, when a post has at least one value that is an image, to include the first image as `image_url` in the `/posts` response.

### Actual behaviour

Since `/posts` does not return an `image_url`, the mobile client needs to download `/api/v3/forms` and `/api/v3/forms/attributes` and `/api/v3/media`, then merge all those results to obtain the image URL to include in the post card for the listing.

**Comment by rowasc** [comment]
Closing in favor of https://github.com/ushahidi/platform/issues/1708 which covers this case as well.
