### ISSUE TITLE
Unavailable subdomains initially shows up as available

### ISSUE THREAD

**Issue by mentalacrobatics** [ushahidi/platform#1639]
### Expected behaviour
During .io registration if a sub domain is unavailable the system should let you know immediately 

### Actual behaviour
During registration the System shows: the url you have chosen is available  but once you submit a new message shows "The subdomain is already taken" 

Screenshot attached

![screenshot 2017-03-14 10 53 41](https://cloud.githubusercontent.com/assets/2631543/23890945/1aeb9064-08a5-11e7-992d-e893963d89bb.png)

**Comment by rjmackay** [comment]
We think this was an issue where 1 server was failing to look up domains, but the other passed. So sometimes it would show available, then others not. We've fixed it and added monitoring to test in future

**Comment by pasichnyi** [comment]
Have the same issue with **urbant** domain name.
