### ISSUE TITLE
Build v1 of ushahidi.com/discover

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1642]
**User story**: I want to be able to find Ushahidi deployments by name and topic, and see what people have been using Ushahidi to do lately.

------

Our first pass at providing a solution to this is to stage a tool at ushahidi.com/discover, with a search input (for searching for deployments by name), as well as three groups deployments:

- **Recommended**: Curated by Ushahidi staff and manually updated (ideally via Craft)
- **Most active**: Deployments with the most combined new survey responses, users, and labels over the course of the past seven days.
- **Recently created**: Reverse-chronological return of the past 10 deployments created on Ushahidi.com

Each group would include up to 10 deployments. 

Deployments are represented as a card, which will open the deployment when clicked.

Search results would return deployments using the same horizontal convention used for the aforementioned groups.

Thus far, I've provided @middle8media with a wireframe to help direct the implementation of the necessary screens for "dotcom" and its design system:

![discover](https://cloud.githubusercontent.com/assets/1136279/23971496/339e5cb6-099c-11e7-9a02-10b36c3a3430.png)

cc/ @jshorland @natmanning

**Comment by middle8media** [comment]
I am currently working on this ... stay tuned.

**Comment by dalezak** [comment]
Looks like https://github.com/ushahidi/platform/issues/1643 might be related to this.

**Comment by brandonrosage** [comment]
Feedback on the current state of the "slider" @middle8media introduced in the dotcom PL:

**The directional controls don't behave as I'd expect**, which is that, when selecting an arrow button, once I've revealed the last item in the row, I'd expect the forward arrow to become disabled. It currently allows me to continue to advance the slider such that it creates empty space.

**The pager controls should be removed**. If they were included, I'd expect each "dot" to represent a group of visible items. And I'd expect the active "dot" to represent the handful of items currently visible. Instead, the current iteration maps dots to individual items. It's more confusing than it is useful.

Quick example of the current iteration and the unexpected behavior: http://d.pr/i/JyeM/EmegxMM0+

**Comment by brandonrosage** [comment]
More feedback: The arrow buttons should adopt one of the existing button styles from the PL.

**Comment by brandonrosage** [comment]
Style feedback:

**The fade should match the background color of the document**; not the cards -- to create the effect that the document is subsuming the cards.

Unless we can more easily style the icon (as we do in the client), **let's just have the directional controls not adopt a button style, and instead be icon triggers**.

I've mocked up both of these suggestions using dev tools:

![browser mock](https://cloud.githubusercontent.com/assets/1136279/24469435/10bf99ae-1481-11e7-9345-1d0132028f65.png)

**Comment by brandonrosage** [comment]
Some feedback on the searchbar:

Now that we can see it in the browser, I think the search control is an opportunity to also implicitly communicate the purpose of the web page. So let's inch toward styling it like a title.

Here's a mockup I did using dev tools on your layout:

![searchbar](https://cloud.githubusercontent.com/assets/1136279/24469926/c821e326-1482-11e7-9ca0-a84fb8a3ab19.png)

One detail I was unable to demonstrate with the available assets was that, with an 'alpha' button treatment on the search button, the icon should be `$color-primary-alpha`.

**Comment by brandonrosage** [comment]
Some feedback on the content box:

1. We should be prepared to display deployment logos using the same style that's used in the client. In short, circular image masks. The current dotcom pattern demonstrates square images.
2. Can we make the whole content box the click target, rather just the deployment's URL? If so, let's use a lighter-color and smaller-font-size treatment on the URL text.

**Comment by middle8media** [comment]
pattern is done. I am just waiting to sync with Will to figure out the best way to handle Craft search and integration

**Comment by jshorland** [comment]
WOO

**Comment by rjmackay** [comment]
So I haven't got all the data + search stuff working on api.ushahidi.io yet - but I think we can happily define the API:
`api.ushahidi.io/deployments?q=searching!` for the search
`api.ushahidi.io/deployments` should return the most recent deployment already
`api.ushahidi.io/deployments?sort=active` ... doesn't work yet but I think I can make this work.

You can already see the structure looks like:
`[{"domain":"api.ushahidi.io","subdomain":"ksushastich","status":"deployed","deployment_name":"Ksusha Stich","tier":"free","links":[{"rel":"self","uri":"\/deployments\/api.ushahidi.io\/ksushastich"}]}]`
https://api.ushahidi.io/deployments/?limit=1

I'm going to add description + image to that so you get:
`[{"domain":"api.ushahidi.io","subdomain":"ksushastich","status":"deployed","deployment_name":"Ksusha Stich","tier":"free","description":"Something!","image":"http://url.for.logo","links":[{"rel":"self","uri":"\/deployments\/api.ushahidi.io\/ksushastich"}]}]`

**Comment by rjmackay** [comment]
I think you could do 'recommended' by having a field in craft cms where they can specify a list of deployment subdomains.. Then a url like: `https://api.ushahidi.io/deployments/api.ushahidi.io/hillclearinginpenang` will load the details
where the last part is the subdomain (yes the URL structure is weird)

**Comment by middle8media** [comment]
@rjmackay Just checking to see how `api.ushahidi.io/deployments?sort=active`, description and image are coming along?

**Comment by middle8media** [comment]
@rjmackay as far as 'recommended' ... I am not sure how this fits into dotcom Craft or how Craft would determine a deployment worthy of recommedation.

So far this 'Discover' page does not even need a data model within Craft.

I am using a Craft plugin that takes advantage of Guzzle https://github.com/davist11/craft-guzzle

`https://api.ushahidi.io/deployments/?limit=9` - displays most recent

`https://api.ushahidi.io/deployments?sort=active/?limit=9` - will display most active once it is set up

`https://api.ushahidi.io/deployments?q` - for now this displays raw json in the browser after search is submitted (I still need to figure out how to consume the api, decode the json and then deliver to the template)

**Comment by jshorland** [comment]
@willdoran would you mind taking a look at @middle8media 's questions here?

**Comment by willdoran** [comment]
@middle8media For the last one, I think you might need a way to take a search term from the user or is that needed for the discover tool. So if they enter "test" and hit search the request would become:

https://api.ushahidi.io/deployments?q=test

It should return results similar to 

https://api.ushahidi.io/deployments/?limit=9

just a lot more of them. You could use a simple form on the page so that the search button sends a submit to the craft guzzle

**Comment by rjmackay** [comment]
> @rjmackay as far as 'recommended' ... I am not sure how this fits into dotcom Craft or how Craft would determine a deployment worthy of recommedation.

Sorry I know very little about craft. I'm assuming you could add a page/data type for 'Discover' that has some kind of custom fields? An admin (ie. Jess) would then have to edit the page to update which deployment were recommended. Does that make sense at all?

**Comment by rjmackay** [comment]
> @rjmackay Just checking to see how api.ushahidi.io/deployments?sort=active, description and image are coming along?

I think its ready, but only on staging right now. I'll have someone review and then push it

**Comment by rjmackay** [comment]
Deployed to production. Scheduled tasks should run in a few minutes and hopefully the API will then return everything you need

**Comment by middle8media** [comment]
I have the API search and display working. I am just waiting for 'image' and 'description' to become available in the API. They are currently 'null' - https://api.ushahidi.io/deployments

I also need to make a few UI tweaks.

**Comment by jshorland** [comment]
to do: look at how github tells users their free plan is discoverable. 
for v2 of this -- opt out feature (should that be feature gated?)

**Comment by middle8media** [comment]
Deployment discoverability is ready for internal testing at https://www.ushahidi.com/discover. Just login with your normal dotcom login to test the UI, search and anything else.

Please file issues or feature requests here - https://github.com/ushahidi/biz/issues
