### ISSUE TITLE
API Deployment Search Should Search Deployment Name

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#1643]
### Expected behaviour
Searching https://api.ushahidi.io/deployments?q=Document%20Hate does not return any results, although there is a map with the name `Document Hate` https://usaelectionmonitor.ushahidi.io/views/map 

### Actual behaviour
However searching https://api.ushahidi.io/deployments?q=USA%20Election does return two results, one of which is the `Document Hate`map https://usaelectionmonitor.ushahidi.io/views/map.

**Comment by rjmackay** [comment]
This is because the deployments API only has the info from deployment creation, and never updates it after that. I'm going to see if I can fix this without too much trouble
