### ISSUE TITLE
OAuth Loses scope Permissions When grant_type is refresh_token

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#1645]
### Expected behaviour
The API `/oauth/token` does not fully support `grant_type:"refresh_token"`, so the mobile client is not able to obtain a new `access_token` with the provided `scope` through this means.

### Actual behaviour
The API `/oauth/token` does return an `access_token` using `refresh_token`, however it does not seem to take the `scope` parameter into account, so upon refreshing the user loses their necessary permissions.

**Comment by rjmackay** [comment]
Context: we need this to enable better log outs, and longer user sessions

**Comment by dalezak** [comment]
Turns out this isn't actually an issue, as discussed in https://github.com/ushahidi/platform-mobile/issues/39.

If you exclude `scope` from the `refresh_token` request, you are able to receive back a valid `access_token`.
