### ISSUE TITLE
Direct posts generated by data sources into buckets named for their source

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1646]
Today, Ushahidi data sources transform their data into posts and assign them to the catch-all "Unknown" bucket, which is appended to the list of surveys in the survey filters and filters dropdown.

I'd propose each data source transform its data into posts and assign them to a bucket of the same name as the data source (e.g. Twitter) dedicated to storing only posts that were generated by that source.

As a result, the survey filter would display these data sources in a separate list, with the heading "Data sources," which would only be visible to deployers:

![survey filters](https://cloud.githubusercontent.com/assets/1136279/24009716/d1fa72ee-0a43-11e7-8054-9bf6991535b8.png)

Similarly, the filters dropdown would have a segment dedicated to "Data sources," with checkboxes for each active source.

**Comment by rjmackay** [comment]
Since we already have the data for this on the backend, I suspect we could do this pretty easily. ie. entirely on the frontend. 

@jshorland should this jump into spec? or scoping first?

**Comment by jshorland** [comment]
I see no problem moving this to spec. And such a necessary filter. Note that this should be filterable in both the side bar and the global filter bar

**Comment by willdoran** [comment]
This is already working in the comrades branch and should be merged

**Comment by Angamanga** [comment]
This issue is related to #1861
