### ISSUE TITLE
Review COMRADES Integration Notes for new tools

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1650]
**Need:** document review (2 pages)
**Due Date:** Would love initial reactions/thoughts by March 24th if possible since I'll be going to the COMRADES working meeting the following week. 
**Related Work:** [issue #1550](https://github.com/ushahidi/platform/issues/1550)

**Details:** The work on the YODIE integration for COMRADES  is going pretty well thanks to Will's hard work. There are a few others coming down the pipe. These other tools are being designed by the Open University, [which has provided an initial description here](https://docs.google.com/document/d/1K8W-HaEiIrJiWjQ4YvbdYgMaTfMMs_6SF0McflLH4sg/edit#heading=h.h9aujt1ihee). There will be more information forthcoming but for now, please look over this description and let me know:

- What other information is needed. 
- Are there any immediate major issues. 
- Let me know who which dev will likely be assigned.

**Comment by Shadrock** [comment]
I know that @willdoran has probably already looked at this (or discussed it to some degree on the "integration telco") but would really like to have @jshorland have a quick peek at it to see if there are any issues.

**Comment by jshorland** [comment]
@Shadrock can I close this? did I never look at this?
