### ISSUE TITLE
Cannot create new deployments because all ushahidi.io sub-urls display as unavailable

### ISSUE THREAD

**Issue by stevenblumenfeld** [ushahidi/platform#1652]

**Comment by willdoran** [comment]
@rjmackay It seems to be having a problem making requests to api.ushahidi.io
https://ushahidi.io/check_subdomain?subdomain=downw

**Comment by willdoran** [comment]
@rjmackay resolved this by restarting nginx/php but there may be a background issue so I'm going to downgrade this and leave it open in case something recurs

**Comment by tuxpiper** [comment]
Suspect DNS resolution within rackspace managed domains . Checking with them.

**Comment by tuxpiper** [comment]
It's all explained here: https://laravel-news.com/dns-resolver-issue  . Including why we had to restart things twice.

**Comment by tuxpiper** [comment]
For good measure, restarted php5-fpm in all places I could remember we have it running. Hopefully this is the end of it by now.
