### ISSUE TITLE
Provide SMPP integration feature / example

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1653]
It looks like SMPP ( https://en.wikipedia.org/wiki/Short_Message_Peer-to-Peer ) is still one of the preferred ways for some telcos to deliver SMS messages for customer-side processing.

It may be useful for deployers that deal with such telcos (i.e. get shortcodes) to have ready to run SMPP gateway code, easily configurable to interact with a Ushahidi platform setup.

Some open source projects that deal with SMPP:

http://jasmin.readthedocs.io/en/latest/
https://github.com/farhadi/node-smpp
https://jsmpp.org/
http://opensmpp.org/

**Comment by ClearLakeHABMap** [comment]
Could some of this be achieved by utilizing the Google Voice API? I know that it has been mentioned in using Google Voice in Python, Java, Ruby, and a few other approaches. Their architecture is stronger now than before and even offers MMS on most big carriers. [https://productforums.google.com/forum/#!topic/voice/OcP6CYmrAJc]
