### ISSUE TITLE
Automated User Guide Generation

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1656]
### Expected behaviour
- Guides with screenshots should not have to be manually created.
- When new features/user flows are added it should be straightforward to define an e2e like test that generates screenshots and markdown
- The markdown should be served to the support site
- This should require only minimal human interaction to double check that the docs are correctly generated
- Tests should be written in tdd form for simplicity
### Steps
- Identify any existing solutions
- If none exist, identify combinations of solutions such as end2end tests + plus phantomjs + phantomjs screenshot funcitonality
- Define process/ansible recipes that will automatically rebuild the user guides on release.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-621

**Comment by tuxpiper** [comment]
@willdoran just checking, do we have a solution for pushing the docs to Craft? Or are we planning to move the support site to a different tech if necessary?

**Comment by willdoran** [comment]
@tuxpiper I don't think we do, I remember about a year ago we were looking into better doc pushing but none of the system were working. But do you mean the support.ushahidi.com docs or a different ones? 

I think the support.ushahidi.com ones are fully manual.

I would argue that we should be as open as possible and consider any change that make the doc system better. I think that if the platform in particular wants to fit as module in other pipelines, like for example Pheme or Comrades, we really need much better quality documentation to facilitate that. I like aspects of the Laravel docs but I don't like that you can't easily get from the general documentation to the API docs. 

In an ideal world you would be able to click through from the abstract here is the set of screenshots to setup datasources all the way down to, here is the api specifically for querying the datasources via the api to here is the link to the actual code in the repo.
