### ISSUE TITLE
Hide 'submit survey response' FAB button when none are accessible to me

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1660]
### Expected behaviour
If there are no surveys that I'm allowed to respond to, the "+" FAB button should not appear.

### Actual behaviour
Though the "Add to..." options are hidden from the survey filters' dropdown menu, the "+" FAB button still appears. When I click it, nothing happens.

### Steps to reproduce the behaviour/error
Visit a deployment, like [Penang Hills Watch](https://hillclearinginpenang.ushahidi.io/views/map), and click the "+" FAB button.

**Comment by jshorland** [comment]
Fixed. Closing.
