### ISSUE TITLE
Support for additional map geometries apart from markers

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1664]
As a user submitting a post, I may be sharing a post that isn't necessarily tied to a single point, but a larger area on a map. I'd like to be able to select a region on a map(polygongs), or a road(lines), or even multiple markers.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-618

**Comment by ClearLakeHABMap** [comment]
This could also be done similar to v2 where a similar logo could be selected for specific points. Perhaps Unicode or emoji support for this?

**Comment by rjmackay** [comment]
@ClearLakeHABMap I think thats unrelated. @aoduor is talking about supporting polygons for map data, not custom icons for map points.

The API supports this, and we display polygons, but we dont' have an editor for inputting them. It hasn't been requested very often (suprisingly, I expected more demand)

**Comment by ClearLakeHABMap** [comment]
@rjmackay Gotcha. I recall using the polygon editor in outlining oil spills but found that it didn't display in the globalized map view the way I expected. I was hoping for overlaps of polygons that would intensify color opacity.
We would certainly use polygons in the current instance of the ClearLakeHAB map to illustrate the spatial data of the HABs as we render them from Sentinel 1 and 2. I have a grant in to build out a bridge between our servers hosting the data and raster to any Ushahidi map as points, but polygons would be much more powerful. I may look into considerations to switch back and forth between polygon and points in the API. Do you know the directory this is in on GitHub?

**Comment by rjmackay** [comment]
@ClearLakeHABMap here's an example of what the data posted to/from the API looks like for polygons: https://github.com/ushahidi/platform/blob/develop/tests/integration/posts.feature#L29
It just uses WKT format
