### ISSUE TITLE
Add Smart App Banners To Deployments

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#1667]
Adding Smart App Banners to each deployment site can allow deep linking into the app, including automatically adding the deployment, viewing a report, or jumping right into a survey.

![smartbanner_2x](https://cloud.githubusercontent.com/assets/91811/24557759/19fe9f62-15f6-11e7-8ae9-9d9bce803106.png)

iOS https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

```
<meta name="apple-itunes-app" content="app-id=1205994516, app-argument=https://dale.ushahidi.io">
```

Android https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/

Once done, I'll implement things in the mobile app https://github.com/ushahidi/platform-mobile/issues/101

**Comment by brandonrosage** [comment]
@dalezak: Can we integrate deep linking without including a "Smart App Banner" to the web client? Must they go together?

**Comment by dalezak** [comment]
@brandonrosage @jshorland Smart Banners and Deep Linking serve different purposes.

*Smart Banners* are used to promote the app, if it has not been installed, linking directly to the App Store or Google Play for download. If its been installed, than shows Open instead of View. Optionally, it can pass additional information, for example the deployment URL which can be used on install. This means we can automatically add that deployment in the app, eliminating the need for them to search for it. Hot stuff eh?

*Deep Linking* requires the app to first be installed, if its not installed then does not do anything. The app already has `ushahidi://` registered, which means we can link to that so open the app, however thats not ideal because if the apps not installed, it behaves as a broken link. 

So a better option is to enable *Universal Links*, where you associate backend URL scheme with the app. So if the user visits https://dale.ushahidi.io in Mobile Safari, it will automatically launch the app instead. https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html#//apple_ref/doc/uid/TP40016308-CH12-SW2

I would recommend we enable *Smart Banners* which also include the deployment URLs so we can automatically add that deployment on install, and also enable *Universal Links* which can open that deployment, report, etc in the app rather than visiting it in Mobile Safari.

**Comment by dalezak** [comment]
@brandonrosage @jshorland Here's a good article outlining both _Smart Banners_ and _Universal Links_

https://medium.com/@ageitgey/everything-you-need-to-know-about-implementing-ios-and-android-mobile-deep-linking-f4348b265b49

**Comment by willdoran** [comment]
Deep links:
- [ ] It seems like I need an appId and to define what should be linked for iOS
- [ ] add /.well-known/apple-app-site-association
- [ ] Do you have the fingerprint or at least the key I need to generate it?
- [ ] add /.well-known/assetlinks.json - I think this should be ok with subdomains as we push all to the same app
- [ ] Host both files on CDN

Banners
- [ ] add meta tag 
- [ ] Add web app manifest json
- [ ] Set icon
- [ ] Add meta tag
- [ ] Add meta tag service
