### ISSUE TITLE
Image upload issues on mobile web

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1669]
We've got android users having trouble with image uploads on mobile web

A user on intercom narrowed this down to users on Android version 4.1.x and lower.

"They get message like "not enough memory" (but mobile gas a lot of free memory), or even worse, once the image uploads, the page reloads."

More info from the user

"With two different LG devices I've had the same problem: the page reloads when I upload an Image and I receive the message: "Impossible to complete the operation. Memory insufficient"

**Comment by niccolov** [comment]
Any news about that? Same problems happens with other mobiles. 
There are 2 kinds of problems:

- in some mobiles if you select camera for the picture you get the error: not enought memory (but the mobile has a lot of free memory, RAM and ROM)
- in some mobiles if you select the photo from the documents, once you choose the photo, the page reload itself :(

Please help us ;)
