### ISSUE TITLE
Email Template "Deployment Ready" Title Off

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/platform#1671]
### Expected behaviour

The title of my new deployment should be inside the simulated browser window.

### Actual behaviour

The title is too large and offset. See image:
<img width="559" alt="screen shot 2017-04-04 at 5 00 54 pm" src="https://cloud.githubusercontent.com/assets/106068/24678552/f02779be-1958-11e7-8bcc-10d08723d0cd.png">

### Steps to reproduce the behaviour/error

Create a new deployment and check the email. I'm using Postbox 5, but this is also being reproduced in the webmail client for Fastmail (Firefox 52).

**Comment by brandonrosage** [comment]
The title of the deployment is not intended to appear within the device(s) mockup. It is, however, intended to be included in the heading of the message:

"Your [deployment name] deployment is ready"

![email](https://cloud.githubusercontent.com/assets/1136279/24875510/e49692b2-1ded-11e7-82c5-d2fe3148f607.png)
