### ISSUE TITLE
bug in HTML in sidebar

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1672]
Little html bug. If you use simple html code inside the description (like add a link to a page/url) it does work when you open the post, but it doesn't inside the timeline. Here an example https://scattonetto.ushahidi.io/views/list
 
But if you enter the single post: https://scattonetto.ushahidi.io/posts/177 the link works fine ;)
<img width="466" alt="schermata 2017-04-05 alle 09 20 27" src="https://cloud.githubusercontent.com/assets/3224856/24721033/e21e3844-19f3-11e7-9d90-6c29a69e81f4.png">

**Comment by jshorland** [comment]
@brandonrosage is this in your wheel house, or should I send directly to devs?

**Comment by jshorland** [comment]
might be fixed by @willdoran 's fixes he's doing today

**Comment by niccolov** [comment]
Hi @jshorland and @willdoran, do you have any news about it? At the moment we still see error in posts with urls :(

**Comment by jshorland** [comment]
Hi @niccolov -- thank you for your patience while we get this fixed! We believe we have a fix for it, and should be able to push it to product early next week after it passes QA testing.

**Comment by niccolov** [comment]
Good to know @jshorland We are waiting to see it online.
At the moment is not yet published right?

Thanks,

Niccolò

**Comment by niccolov** [comment]
@jshorland are we ready to deploy? we are very happy to see it solved ;)
