### ISSUE TITLE
[TOP-3] Configure build of ushahidi/platform-client to allow change of base url

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1673]
The <base> tag in index.html is currently hardcoded to "/" . It would be good if the build process accepted a configuration variable (i.e. BASE_URL) to allow automating the configuration of that.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-617

<sub>[USH-643](https://linear.app/ushahidi/issue/USH-643/configure-build-of-ushahidiplatform-client-to-allow-change-of-base-url)</sub>

**Comment by jshorland** [comment]
YES!

**Comment by tuxpiper** [comment]
This is probably still kind of a nice to have for some people. 

The reality of this kind of setup working may have changed with the new ushahidi/platform-client-mzima . It would be good if someone could try to install it in a subpath, and see if the codebase can now work that way, i.e.:

https://host.example.com/ushahidi 

instead of

https://host.example.com

Given the results of that test, we would re-evaluate.
