### ISSUE TITLE
Missing option to make Image upload field required

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1676]
### Expected behaviour
I should be able to set an Image upload field as required ( as with all other custom field)

### Actual behaviour
Option to set field as required doesn't exist when I select an image upload field

### Steps to reproduce the behaviour/error
* Log into deployment
* Select surveys and attempt to add an image upload field onto your survey.

Refs https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/unassigned/conversations/9192046250

**Comment by niccolov** [comment]
Hi @jshorland any news about that?

**Comment by niccolov** [comment]
Hi @jshorland and @aoduor today we received many posts without image :(
How can we force this to be mandatory on our survey?

**Comment by jshorland** [comment]
Hi @niccolov -- I apologize for our delay! Image field should be able to be made mandatory now. Please confirm on your end?
