### ISSUE TITLE
Make image upload caption field optional

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1677]
One of our users would like the option to omit the caption field on a custom image upload field.

Ref: https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/unassigned/conversations/9192046250

**Comment by rjmackay** [comment]
This needs updates on both client and API
- Media API Validator: Makes caption optional, confirm that DB allows that column to be null
- Client: Make sure angular validation isn't set to require the caption

**Comment by rowasc** [comment]
@rjmackay
This feature requires to have a toggle like the ones we have for description field/required status, right? 
example;
![Screen Shot 2017-08-31 at 10.50.42 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5940898e29d5f5001ab2826d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6457f26b7191a379ef0c2e51415b4cbc30254d58eeb9cb74fce36f34985619e8d9655871c73c19feee831bbd03ec768b4f84e5bb8b19c4fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be54c5da3173e61e677336e0a.png)

**Comment by rjmackay** [comment]
@rowasc good thought. I was assuming we would just make them all optional. But you're probably right.
I'd add it with the test 'Make image caption required', below the existing required toggle. I'm not sure if you'll need to add an extra field on the backend for it, or if it could be saved into one of the existing config fields on form_attributes

**Comment by rowasc** [comment]
@rjmackay ok thanks. 
- Adding it next to the required toggle makes sense, yes. I'll do that 
- I will look into adding the option into the `config` field as we discussed.

**Comment by rowasc** [comment]
@rjmackay @jshorland I'm not sure what should happen when a user had a caption previously in a field and then disables the field's caption 

**Data:** Should we keep the old captions or delete them from the database?  
**UI:** Should we stop displaying captions that were added in the past? or do we show the caption if there was one? 

To me, it sounds like it would be a good idea to stop showing them, but I'm not sure if we want to delete them. 
I think it's generally a bad idea to delete user data that you don't really need to delete and that they aren't explicitly asking to delete, but on the other hand, if we don't delete captions when we disable the field, we set the precedent that we don't necessarily delete things that users delete/disable. 
Ugh.. maybe I'm over-thinking this. Let me know your thoughts.

**Comment by jshorland** [comment]
Great catch.

Data: Definitely keep the old captions. Do not delete.
UI: tell them it will disable captions previously entered, but that they
can re-enable them at any time by turning them back on.

**Comment by rowasc** [comment]
Option 1 (GIF, kind of large to make sure the text is visible so it might take a bit to load): 
![captioncollect](https://user-images.githubusercontent.com/2434401/30112381-8caec5dc-92e7-11e7-8b98-6f080ed5b35f.gif)

**Comment by rowasc** [comment]
Option 2 (GIF, kind of large to make sure the text is visible so it might take a bit to load):
![disablecaption](https://user-images.githubusercontent.com/2434401/30112479-ea3d9566-92e7-11e7-9bcc-17f240300220.gif)

**Comment by rowasc** [comment]
@rjmackay after the code review I started thinking about it and I wasn't so sure about the usability in each option. 
Sending both implementations so @jshorland  has a change to take look and give her feedback. @jshorland , please let me know if the copy should be changed, and which option you prefer. After your feedback we should be ready to merge. 
Thanks!

**Comment by jshorland** [comment]
@rowasc I prefer option 1: it's most consistent with everything else in that the user is turning something "on" rather than disabling. 

Let's change the copy slightly to read: "Include image caption field" and the description to read "This will  disable and hide all existing captions for this field, but you can re-enable them at any time."

**Comment by rowasc** [comment]
perfect, thank you!

**Comment by rowasc** [comment]
@rjmackay this is ready to review/merge , after the adjustments + Jess's feedback
