### ISSUE TITLE
Add ability to add custom descriptive text to top of survey pages

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1678]
One of our users would like to be able to add custom descriptive/help texts for users submitting posts to their deployments, much like what we had on v2 on the top of the report submission page.

Wondering of this could also double up as a user story for the need for custom pages on v3?

cc @jshorland @brandonrosage 

Refs https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/angela@ushahidi.com/conversations/9204361285

**Comment by brandonrosage** [comment]
There is currently a survey description field, which is improved upon in the iteration that's on deck to be even more free-form: 

![add survey](https://cloud.githubusercontent.com/assets/1136279/24875679/88fda76e-1dee-11e7-965b-cd13fed30a74.png)

This is then intended to appear atop each survey response:

![post add](https://cloud.githubusercontent.com/assets/1136279/24875742/b608b19a-1dee-11e7-8636-fd4a24b46bc2.png)

Does this address the need you've described, @aoduor?

**Comment by jshorland** [comment]
note: we should close this if the solution above addresses the issue

**Comment by aoduor** [comment]
It does. Thanks @brandonrosage!

Handheld Sent,

Angela Oduor Lungati,
Director of Community Engagement,
Ushahidi | www.ushahidi.com

**Comment by niccolov** [comment]
Hi @aoduor and @brandonrosage. What do you mean with the latests messages? It means that it will work soon? It will be great!

**Comment by niccolov** [comment]
Hi @aoduor, @brandonrosage and @jshorland I see that the task is closed but I don't see the solution. It is normal? Are you working on it or do I have to make some changes?

Thanks,

Niccolò

**Comment by jshorland** [comment]
@niccolov the development work is done and is just waiting to be pushed to production today. Thanks for your patience as we are working as fast as we can while also balancing other priorities in our pipeline.

**Comment by niccolov** [comment]
thanks @jshorland 

Let me know when the changes are online and how can I fix it. I was asking about the status "closed" just to know the meaning of it.

Thanks again!

**Comment by niccolov** [comment]
Hi @jshorland this modification is not online yet, right?
