### ISSUE TITLE
Support upload of geodata

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1679]
As a user, i'd like to be able to upload geodata on my ushahidi deployment. e.g. Shapefiles, KML/KMZ files.

Refs https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/angela@ushahidi.com/conversations/9101993694

Aha! Link: https://ushahiditeam.aha.io/features/PROD-614

**Comment by ClearLakeHABMap** [comment]
I can see the expected behavior working in Settings>Import but it may also be functional through a process similar to an added field for a Survey. This way we can delegate the role to a member through the survey interface.
