### ISSUE TITLE
Filtering out twitter noise

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1680]
I know this is something we've tried to tackle with third party applications, but i'll still add it here for us to think about ( legacy issue from v2 as well).

We currently pull out ALL tweets corresponding to a hashtag ( retweets included) - which pulls in alot of noise for our users.

Is there anything at all we can do to help identify/sift out retweets on the platform?

Refs https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/unassigned/conversations/9178774211
Our friends from SBTF and Peru have this same issue as well.

Thoughts @jshorland @rjmackay

**Comment by rjmackay** [comment]
I gave this advice to someone on intercom yesterday:

The quickest thing to do is to customize your search term. The 'Twitter search term' field in the data source configuration should accept any search terms that work on twitter itself. Try playing with the twitter advanced search on twitter to create a search string that gives you less noise.

**Comment by jshorland** [comment]
Closing in favor of #975 where we should scope this out
