### ISSUE TITLE
Display meta information about results from ML tools

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1681]
### Expected behaviour
- New posts will be parsed through several machine learning(ML) tools
- After they have been parsed they will have the following new pieces of information:
  1. For each label(eg: Protest, Fire, Violence...etc) we will have an Accuracy Value, this describes how confident the ML tool is that it has correctly labeled the Post.
  2. The text(content) of the post will be annotated by the Yodie tool. The result of this annotation is that a piece of text like:

"Angela Merkel appeared today near the Brandenburg Gate"

would receive the following annotations:

"[Angela Merkel](http://dbpedia.org/page/Angela_Merkel) appeared today near the [Brandenburg Gate](http://dbpedia.org/page/Brandenburg_Gate)" 

This will also have an accuracy value as well.

The goal is that the user can quickly see from glancing at a post the accuracy/confidence for a machine labeled/annotated post. The user should also be able to tell visiually that the post has been run through the ML tools, and also whether or not it has yet been validated/verified by a human user.

At the moment, accuracy is the only meta value, however, later there may be multiple meta values that need to be associated with a label on a post. Accuracy and whether it has been human validated will be the most important and should appear on Post' Cards as well.

**Comment by jshorland** [comment]
This will be easier to do earlier in Q2 if feasible. @brandonrosage can you read through this and see if this is do-able to get done early Q2?

**Comment by brandonrosage** [comment]
The design solution could certainly be staged in April.

I'd posit that an elegant solution might amount to a small pattern that's appended to values and inline text that's being machine-generated or -analyzed.

For example, a machine-generated list of categories might have a small visual indicator attached to it that, A, summarizes its "accuracy," and B, can be clicked on to reveal a popup with more ML metadata (similar to our existing tooltip pattern. In another example, that same visual indicator could be appended to each link that is machine-added to text.

**Comment by brandonrosage** [comment]
I'd propose we consider a broader feature to address this and other related needs: Field- and section-level attribution.

What that'd mean is, when a user completes a field, that field's data is attributed to that user -- they're the author, essentially. If someone changes it, that person is credited.

I acknowledge that this suggests the need for revision history. But I think it's valid in a more limited scope, without it.

So here's how that might work, using a combination of the `status-indicator`, `tooltip`, and `bug` fragment patterns:

![screen capture on 2017-04-24 at 13-29-38](https://cloud.githubusercontent.com/assets/1136279/25486147/d6b244d0-2b25-11e7-9af9-7985ee22936a.gif)

As you can see, this solution parlays nicely into a convention for displaying "machine-learned" metadata, as you can simply show that a field is attributed to that machine ("Robot 5000"). And in the event that more information needs to be revealed (like the "accuracy score" you mentioned), it'd be included in the "bug":

![pasted image at 2017_04_24 01_32 pm](https://cloud.githubusercontent.com/assets/1136279/25486201/096855ea-2b26-11e7-9c2d-e6509f4f323c.png)

**Comment by caharding** [comment]
@Shadrock to further scope if this is needed

**Comment by Shadrock** [comment]
@Erioldoesdesign this issue is related to the discussion we had about CREES (and to less of an extent YODIE), which is the tool that allows incoming posts to be automatically tagged. There was some discussion about giving the user more information about how the post was tagged (e.g. by a machine or by a person) and if there was some level of confidence in the accuracy of the tagging. This thread includes some mock-ups by Brandon that I referenced in the notes for our meeting.

**Comment by caharding** [comment]
@Shadrock can you confirm the deliverable that you need for this issue?

**Comment by caharding** [comment]
Pinging this thread

**Comment by rowasc** [comment]
@Erioldoesdesign hey. Have we progressed on this ticket? Do we know what's needed in desigN?

**Comment by Erioldoesdesign** [comment]
@rowasc Errr not really I've been slammed with various other work. I hope to still analyse this before the end of the cycle on July 8th

**Comment by Shadrock** [comment]
There is overlap here with #1683. Re-posting my comment from that issue - @jrtricafort @willdoran can you comment on whether or not we can close this out? It was originally related to UX for viewing post content that had been annotated or otherwise treated by the AI tools in COMRADES... but I think we're basically expecting to replicate the use of tags the way we did for YODIE & CREES versus really taking things any further.

**Comment by rowasc** [comment]
@jrtricafort do you think we can close this? see Shadrock's comment above

**Comment by rowasc** [comment]
@jrtricafort assigning for you to review

**Comment by jrtricafort** [comment]
@willdoran I think we can close this out, correct? Please verify and close if so.

**Comment by willdoran** [comment]
@Shadrock Changing the UI for displaying the results from the ML tools is no longer required yes?

**Comment by rowasc** [comment]
Closing
