### ISSUE TITLE
CSV Import failing on attempts to import more than 50 entries at a time

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1682]
Feedback from one user on Intercom

"Through trial and error, I discovered that the system imports a CSV file with just 20 entries very well. 50, 100 and 200 entries result in a success notification, but the reports aren't shown in list or map views; "Your search didn't match any posts". 300 entries result in an error message without any text, i.e. just a red exclamation symbol. Uploading only the entries 200-300 results in a sucess notification, so I'm guessing that the system fails differently when the number of imported entries is too high.

It is possible to adjust to these quirks by importing only a limited number of entries in one go, i.e. by splitting the datasets and doing multiple small imports. But we cannot adjust to the system only being capable of importing only around 20 entries, which would result into more than 60 import operations in our case.

I hope you are aware of the import problem and know a way to work around it."

Refs https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/angela@ushahidi.com/conversations/9099309862

**Comment by jshorland** [comment]
To do: @jshorland try to replicate on internal QA deployment

**Comment by jshorland** [comment]
Can't replicate. Closing.
