### ISSUE TITLE
Comrades: Data Filtering

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1683]
### Expected behaviour
- Users should be able to filter Posts based on the following criteria:
  - Is Machine Labeled/Annotated
  - Is User Validated/Verrified
  - Machine Created Labels
  - User Labels

We also need to capture any changes from Machine Labeled/Annotate to validated/verified/improve by user. The goal of recording this change is to be able to supply that information back to the ML tools for error correction/learning.

I think in general this will require us to expose user created fields as filterable. To approach the problem of having the user validate that the label, for example, is relevant to the content of the Post could be solved by using a special verify task which collects information about that can range from text to check boxes or radio buttons.

In some manner there will be essentially two versions of the Post Category, the normal version which works as before and a second with identical labels that is clearly defined as the ML labels. Rather than duplicate the Category field it would be good to add a new field type. "Categories" - which should be displayable as either a radio or checklist, this field would have all the labels available from the normal category but it would only be associated with the Survey in question. It would not have the option to set labels, instead it would take it's labels from the normal category system.

For filtering, it would probably be desirable to Filter by Survey -> Field. Data will be imported to one specific Survey configured by the User.

Also covered in #1681

**Comment by jshorland** [comment]
This will be easier to do earlier in Q2 if feasible. @brandonrosage can you read through this and see if this is do-able to get done early Q2?

**Comment by brandonrosage** [comment]
**Questions**: 

Is "User Validated/Verified" referring to the verification of a specific machine-added item (like a link or category)? Or is referring to the verification of the overall post?

Would the filter controls need to distinguish between categories that a user created (or verified) and categories that a machine created? Or is it simply that they all need to be accounted for in the filter controls, regardless of how they were generated?

> do-able to get done early Q2?

I think so. It seems to me to just be a matter of understand the data model here and demonstrating the effect it'd have on the filter controls.

**Comment by brandonrosage** [comment]
In addition to enabling any field to be included among the filter controls, this would require a filter control for attribution (e.g. "includes data contributed by X").

Also, consider that "verification" (or the act of confirming that certain data is legit) would be possible through "[Tasks](https://github.com/ushahidi/platform/issues/1382#issuecomment-297511346)," which are designed to be "an explicit indication that a field needs to be completed; optionally by a specific person or group of people."

So the "Categories" field, for example, could be assigned to Jane. A machine could contribute data to it, but Jane would have the explicit task of looking that field over and marking it "complete."

**Comment by jshorland** [comment]
@shadrock @willdoran can i close this?

**Comment by Shadrock** [comment]
@jshorland @willdoran actually, I'd say "no." This is part of UI/UX for CREES, which we still needs to go through a few iterations. I'd suggest walking through this with @justinscherer to see if this approach is still helpful and, if not, then we can close it out.

**Comment by justinscherer** [comment]
it's still work that needs to be done. probably along with some wider refactoring on the filter pane.

**Comment by caharding** [comment]
@Shadrock to scope for further investigation if needed

**Comment by Shadrock** [comment]
@jrtricafort @willdoran can you comment on whether or not we can close this out? It was originally related to UX for viewing post content that had been annotated or otherwise treated by the AI tools in COMRADES... but I think we're basically expecting to replicate the use of tags the way we did for YODIE & CREES versus really taking things any further.

**Comment by rowasc** [comment]
@willdoran Can we close this? 
(See Shadrock's message)

**Comment by rowasc** [comment]
Closing after checking with Will
