### ISSUE TITLE
Pull photos from incoming email

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1687]
### Expected behaviour
If I attach a photo to an email and send it to Ushahidi, the photo is included in the post.

### Actual behaviour
If I attach a photo to an email and send it to Ushahidi, the photo is ignored

Aha! Link: https://ushahiditeam.aha.io/features/PROD-612

**Comment by rjmackay** [comment]
https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/tech/conversations/9014117161

**Comment by tuxpiper** [comment]
Should we look at something similar for twitter?

**Comment by jshorland** [comment]
@tuxpiper yes if that's possible
