### ISSUE TITLE
Add new permission for managing categories

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#1688]
Decide if a new permission-type for managing categories is needed? The alternative would be to adjust the permissions for Manage-Post-roles  so they can add categories, update the forms_tags-table and form_attributes-table.

https://cloud.githubusercontent.com/assets/1136279/23771318/2f9fd866-04dc-11e7-8c6f-cbf634f0f394.png

**Comment by jshorland** [comment]
Closing in favor of #1709
