### ISSUE TITLE
Scope better handling of PII for COMRADES

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1692]
## COMRADES
Scope: Auto detection of personally identifiable information: is it possible to have automatic responses to certain inputs?

We'd discussed this previously, but it may be that private form fields that are being rolled out are enough right now. I can check to see if we have any dev resources from the COMRADES partners but *I'll need your confirmation that you want that.* It may be more difficult than it's worth to bring new devs into our workflow.

**Comment by Shadrock** [comment]
Hey @jshorland, I noticed this has been iceboxed - and I think we can even close it - but there is a requirements from COMRADES to include Terms of Service on all deployments. The bottom line is I think they want an "about" page. I get the logic of saying, "but you can just link to other docs or pages in the bit of text we provide next to the map" but for grassroots users in far flung place this may not be feasible. Is there an issue for an about page somewhere?

**Comment by Shadrock** [comment]
^ to be more clear, the ToS is what would serve to spell out a deployment's policy about PII and any other ethics issues.

**Comment by jshorland** [comment]
yes. https://github.com/ushahidi/platform/issues/1575

**Comment by Shadrock** [comment]
Taken care of with field level privacy.
