### ISSUE TITLE
Scope New Data Sources for COMRADES: including current deployment

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1694]
## COMRADES
This issues is two fold: scoping new data sources that a deployment can ingest for posts and piloting a way for a deployment to push out structured humanitarian data to users and alert subscribers if they are not also users (see #1693). 

### Ingesting social media data other than Twitter
Is it possible to somehow integrate FaceBook groups or messenger into an Ushahidi deployment? Lots of people in Nepal access FB on mobiles, and many organizations host FB pages, so some time of integration would go a long ways towards expanding the reach of a deployment. 

I'm specifically thinking of: 

- Making posts to a deployment from FB.
- Some way to efficiently ingest FB data (e.g. the same way we ingest Twitter)
- Reposting elements of a platform to a group

### Pushing Structured "official" data back to users
At the last COMRADES working meeting there was a lot of interest in reversing the typical flow of Ushahidi information from harvesting information from individuals and feeding it up to a responder. What would it look like to report to users or individuals who submit posts with official information? The goal would be to pick one data source and pilot it in [the COMRADES test platform](http://comrades-stg.ushahidi.com/). Specific examples of the type of information I'm talking about are: 

- 3W (or "who what where") data that are regularly published by responders but rarely accessible by local populations in any sort of raw form. [See this example for Nepal](https://data.humdata.org/dataset/nepal-consolidated-3w). 
- Another example might be location of projects and activities from NGOs: see the [Interaction NGO map](https://www.ngoaidmap.org/) as an example.

**Comment by caharding** [comment]
Already addressed with FB Bot. Closing.
