### ISSUE TITLE
Scope Enterprise Ushahidi for COMRADES

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1695]
## COMRADES
Is it possible to have an “Enterprise” Ushahidi (e.g. multiple, federated, Ushahidis under a larger deployment) for COMRADES? The goal would be to deliver sometime in Q4.

**Comment by jshorland** [comment]
Related: #1873

**Comment by jshorland** [comment]
Hierarchy:
Organization
-> admin 1, admin 2, admin 3...
--> user 1, user 2, user 3...
--->"deployment" or "campaign" 1, 2, 3, 4... with some users but not necessarily all
