### ISSUE TITLE
title and description field deletion

### ISSUE THREAD

**Issue by MazenBaroudi** [ushahidi/platform#1697]

**Comment by aoduor** [comment]
Thanks for filing the report @MazenBaroudi 

Refs https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/unassigned/conversations/9255847445

**Comment by MazenBaroudi** [comment]
Problem not solved yet 😞

**Comment by jshorland** [comment]
@mazenbaroudi -- we're continuing to look into it!

**Comment by rjmackay** [comment]
@willdoran can you look into whether we really allowed removing title + description in the API? ... assuming the API side is all fine, then @crcommons can dig into the client side

**Comment by willdoran** [comment]
@rjmackay Yep, will look now, I don't remember us allowing deletion of those fields but will check through the code.

**Comment by willdoran** [comment]
@rjmackay Actually we don't have delete validators at all for form attributes so through the api you can delete whatever you like without injunction. There is no option to delete the 'Title' or 'Description' in the client. Technically, if you were to use the API without the client there is no explicit reason to not delete those two fields since those fields only have special meaning to client but we should probably add deletion validators for Attributes and block deletion of those fields.

I'm unclear the usecase where removing these fields would be desirable.

**Comment by MazenBaroudi** [comment]
@willdoran these fields are probably very helpful in humanitarian deployments 
In other cases such as mine, I am collecting spatial data for research purposes and these two field are very confusing
If there is no technical need for these two field from your side, there will not be a problem to give clients the choice to keep or skip these fields
with regards/Mazen

**Comment by willdoran** [comment]
Hi @MazenBaroudi,

These two fields or at least the title field are important for our client as the title is used as a link anchor between sections, for example, on our timeline view the list of posts link to their detail pages via the title. This does create a structural requirement for the title at least.

I have a couple of questions so I can understand your usecase a bit better if that's ok. Are you deploying the system yourself or are you using one of our cloud deployments? If it's the former, are you using both our client and api? If so then it may be possible for you to fork our client and adjust.

How are/were you deleting the title/description fields? It is possible to rename both of these fields if that would be useful. 

@rjmackay it may be worth us revisiting using title for linking, it might be better to have some kind of icon that is the primary clickable link on post cards or that appears when title is unavailable.

**Comment by rjmackay** [comment]
@willdoran removing them entirely is the key change in the #1335 but thats a big chunk of work since titles are used throughout the API and client. Its a bit further down the roadmap.

**Comment by MazenBaroudi** [comment]
Hi @willdoran,
I am using the cloud deployment. I managed to change the name of the field and its position but that did not help me a lot as I don't have such long open questions in my survey.
here is the link of the survey if that helps:
https://takecareumea.ushahidi.io

Thanks and regards/Mazen

**Comment by willdoran** [comment]
@MazenBaroudi Apologies I was away for the last 15 days. Could you walk me through exactly how you made the changes?

**Comment by willdoran** [comment]
@rjmackay I think that this highlights a more general problem which is that users need to be able to define what appears in the post preview on timeline and elsewhere, and that as I said above we need to stop using certain fields as linkage points.

**Comment by rjmackay** [comment]
Yup, but thats a much bigger chunk of work, and is really the issue attempting to be solved by "free form surveys" in #1335.

I don't think we can resolve this issue separately.
