### ISSUE TITLE
Timeline: Survey filter numbers don't update after delete

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1699]
### Expected behaviour
- Number of posts per survey updates correctly when I delete posts
### Actual behaviour
- Number of posts per survey does not updates correctly when I delete posts

**Comment by willdoran** [comment]
Adding interceptors to each endpoint method response, to broadcast a event that can be listened for by other entities in the app. Therefore, for example, force update of survey filter numbers on post.delete.success

**Comment by willdoran** [comment]
Relies on #1023

**Comment by jshorland** [comment]
Can't reproduce. or at least I think I can't. Deleting.
