### ISSUE TITLE
Deployment logo not saved after session

### ISSUE THREAD

**Issue by ClearLakeHABMap** [ushahidi/platform#1700]
### Expected behaviour
Upload and save a logo for the Settings>General Page reappearing on the next session.

### Actual behaviour
Upload a logo in Settings>General, then save. The logo appears in the main map screen. After logging out and logging back in, the logo is missing and the file in Settings>General shows a broken image file logo.

### Steps to reproduce the behaviour/error
This occurs on each attempt to update the image.

**Comment by jshorland** [comment]
Hi there @ClearLakeHABMap -- are you running a self-hosted open source version, or a deployment hosted by Ushahidi?

**Comment by ClearLakeHABMap** [comment]
I installed a database and client on Heroku and have been working from there. Do you have that run through Ushahidi on the backend? It looks like a large number of resources are on the system I am managing.

**Comment by ClearLakeHABMap** [comment]
It may be an image titling issue. I just tried it with one having only A# and it seems to be sticking. Underscore and % appear to be stopping the stickiness of the pictures?

**Comment by jshorland** [comment]
cc: @tuxpiper any idea what might be happening here?

**Comment by tuxpiper** [comment]
Underscores and % signs are usually taken well by filesystems... I haven't been able to reproduce in my .io deployment.

@ClearLakeHABMap  What was the original file name of your image?

**Comment by ClearLakeHABMap** [comment]
@tuxpiper I can do you one better and shoot you both copies
![clear lake hab map logo](https://cloud.githubusercontent.com/assets/27732679/25187290/71081eb0-24d7-11e7-8c92-4071f473b293.png)
![clearlakehabmaplogo](https://cloud.githubusercontent.com/assets/27732679/25187294/742041c2-24d7-11e7-8324-1b89399a10ab.png)
First one was Clear Lake HAB Map Logo.png, second (see some blur on the black spot) was the exact same without spaces (convert to %20 in upload).

**Comment by ClearLakeHABMap** [comment]
The problem happened again on the same deployment. This is an interesting problem.

![ushahidilogocapture](https://cloud.githubusercontent.com/assets/27732679/25193326/971125d4-24eb-11e7-8c90-8d3065dfde26.JPG)

**Comment by tuxpiper** [comment]
Oh you are running on Heroku, sorry I should have caught this before.

Heroku provides ephemeral filesystems, so locally stored data (like uploaded images) can be lost:  https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem . Are you using a free dyno or did you redeploy / restart anything?

I've just added a note in our documentation about this.

**Comment by ClearLakeHABMap** [comment]
Looking into this deeper, we just finished installing a new platform on a Google Cloud Platform vm instance and still have an issue. The error looking for the resource shows that it is likely an .htaccess problem. My buddy is working on it, but this likely explains the problem with the Heroku instance.

**Comment by tuxpiper** [comment]
I don't think we've tried this on GCP VM , although it shouldn't be much different from doing a setup in a VPS.

Any details about the error that you can provide to us? We could also check the URL if it's live.

**Comment by ClearLakeHABMap** [comment]
Map
http://104.198.4.216

http://104.198.4.216/index.php/media/uploads/5/9/591b441c3f471-clear%20lake%20hab%20map%20logo.jpg
<img width="640" alt="photo issue" src="https://cloud.githubusercontent.com/assets/27732679/26206368/7d2527aa-3b99-11e7-9043-b7ec4c4324ae.png">

**Comment by ccorreia64** [comment]
Did you manage to solve it? I also followed the same steps as indicated  [here](https://forums.ushahidi.com/t/uploaded-images-not-showing-up-on-ushahidi-3/4178/5) and the images are broken, but saved on a disk.

**Comment by ClearLakeHABMap** [comment]
@ccorreia64 EliotLandrum on the forum is working on the project for me. We still have the images on the webserver but are unable to get them to load in the software. We are wondering if it is better to load the system on Apache or NginX.

**Comment by ccorreia64** [comment]
@ClearLakeHABMap  I have the application in a VPS with ubuntu 16.04 and Apache, and I also have the same problem. It should be something of the .htaccess at the root of the app. If I can solve it, I write the solution here.

**Comment by ClearLakeHABMap** [comment]
Wonderful, thank you!

**Comment by diegodorgam** [comment]
@ClearLakeHABMap @ccorreia64 @tuxpiper , any progress here?
I'm running a docker instance with nginx, and having the same problem...

**Comment by ccorreia64** [comment]
@ClearLakeHABMap ,@diegodorgam, I managed it to work in Apache and Ubuntu 16.04 as a developer mode using this [link](https://www.ushahidi.com/support/install-ushahidi#installing-for-development).

The API and client are in separate folders. As the instructions say, I gave permissions to the platform/application/{logs,cache,media/uploads} (platform I renamed it as api).

The vhost of each is as follows:

**Api (api.[DOMAIN].conf)**

    <VirtualHost *:80>

	    ServerAdmin webmaster@localhost
  	    DocumentRoot /var/www/html/api/
  	    ServerName api.[DOMAIN]

  	    ErrorLog ${APACHE_LOG_DIR}/error_api.log
  	    CustomLog ${APACHE_LOG_DIR}/access.log combined

  	    <Directory /var/www/html/api/>
            AllowOverride All
            Require all granted
  	    </Directory>

    </VirtualHost>

**Client (000-default.conf)**

    <VirtualHost *:80>

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/client/server/www/

        ErrorLog ${APACHE_LOG_DIR}/error_client.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <Directory /var/www/html/client/server/www/>
            AllowOverride All
            Require all granted
        </Directory>

    </VirtualHost>

On client folder, I ran the "gulp build" command to generate minimized files from the entire app on client/server/www. Copy the rewrite.htaccess from server to www

**The .htaccess in /var/www/html/api/**

	# Turn on URL rewriting
	RewriteEngine On

	# Set base directory
	RewriteBase /

	# Protect hidden files from being viewed
	<Files .*>
        Order Deny,Allow
        Deny From All
	</Files>

	# Rewrite all other URLs to httpdocs
	RewriteRule .* httpdocs/$0 [PT]

**The .htaccess in /var/www/html/api/httpdocs/**

	# Turn on URL rewriting
	RewriteEngine On

	# Set base directory
	RewriteBase /httpdocs

	# Protect hidden files from being viewed
	<Files .*>
        Order Deny,Allow
        Deny From All
	</Files>

	# Uncomment to force redirection to https site.
	#RewriteCond %{HTTP:X-Forwarded-Proto} =http
	#RewriteRule ^(.*)$ https://%{HTTP_HOST}%{ENV:REWRITEBASE}$1 [R=301,L]

	# Allow any files or directories that exist to be displayed directly
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d

	# Rewrite all other URLs to index.php/URL
	RewriteRule .* index.php/$0 [PT]

With those .htaccess plus the corresponding permissions, the application shows the logo and the images of the reports.

**Comment by jshorland** [comment]
Needs to be added to documentation / forums for open source.

**Comment by rowasc** [comment]
@tuxpiper tagging for awareness  in case something here needs to be added to  the new gitbooks

**Comment by tuxpiper** [comment]
The docs are covering all the necessary permissions etc now. We can close.
