### ISSUE TITLE
Survey Map Search Lock

### ISSUE THREAD

**Issue by ClearLakeHABMap** [ushahidi/platform#1701]
### Expected behaviour
When searching for a location but unable to find it in search, the search screen disappears when you click out of it (white space or otherwise.
### Actual behaviour
The search location pop up/drop down remains open until a found location can be searched for successfully.
### Steps to reproduce the behaviour/error
Search in "Find a location...:" in a survey input, delete all text in the search field, try to click to remove the search box.

**Comment by jshorland** [comment]
Fixed. Closing. Please re-open if still experiencing issues!
