### ISSUE TITLE
Category permissions

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1709]
As a user, i'd like to distinguish permissions of categories in two separate ways:-
 - Who can add to categories
 - Who can view categories

Right now, we have these two bundled up together, which means its all or nothing when it comes to assigning permissions to roles on categories.

cc @jshorland @Nthiga

Aha! Link: https://ushahiditeam.aha.io/features/PROD-609

**Comment by aoduor** [comment]
@Nthiga tagged you since this is for Uchaguzi ;)

**Comment by caharding** [comment]
@aoduor can we please close this in favor of Tasks #613 which will solve the same problem?
