### ISSUE TITLE
Ability to add subcategories

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1710]
I have created a bunch of categories to be used for Uchaguzi workflows, as shown below.

![screenshot](http://i.imgur.com/gcVCF5y.png)

As a user, i'd like to be able to group related categories into subcategories of one encompassing category

**Comment by jshorland** [comment]
This is getting pushed with the new categories feature tomorrow! Wee!

**Comment by aoduor** [comment]
YEEEEEEEHHAAAAAAAWWWWW!

**Comment by rjmackay** [comment]
This is done
