### ISSUE TITLE
Limit roles that can download data via CSV

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1712]
I'd like to be able to limit download of reports to specific audiences, or at least have the option to.

In cases where we're dealing with sensitive data, download via CSV being a publicly available option raises concerns on privacy.

Specifically for Uchaguzi, i think it would be helpful to have this option limited to specific roles on the platform. 

Related to ushahidi/platform#1711 

Thoughts @jshorland @Nthiga

**Comment by jshorland** [comment]
Closing. This will be landed with cycle 0 updates
