### ISSUE TITLE
Redirect me to survey list page after successful creation

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1713]
### Expected behaviour
After i've created a survey, it would be great to send me back to the survey list page, especially if I have to create a few more.

### Actual behaviour
After successful creation of a survey, I remain on the survey editing page, and i have to click on surveys to head back to the list page, which is a teeny bit annoying if i'm creating multiple surveys at a time :)

**Comment by aoduor** [comment]
This *might* also help with duplication, 

( I clicked on save twice, as i was waiting for confirmation of success, and it created my survey twice)

**Comment by niccolov** [comment]
Ping @jshorland @rjmackay @brandonrosage Please pay attention to this... People are getting confused about this :/
