### ISSUE TITLE
Add command to duplicate a survey

### ISSUE THREAD

**Issue by Tropicalrambler** [ushahidi/platform#1717]
Creating each survey one by one or loading it up on the database can be tedious.  I am suggesting a "duplication" feature, accessed by a button that allows you to duplicate an existing survey, which copies all the setting such as Title, Description, fields, color, etc. to a new survey that you can save upon modification (to prevent surveys with the same name).

**Comment by jshorland** [comment]
@tropicalrambler -- we hear you! how frustrating. We have a solution to this in our latest merge that is going through testing now and will be pushed to production this week.

**Comment by jshorland** [comment]
@tropicalrambler -- just following up that this feature has been pushed to the platform. Happy duplicating!
