### ISSUE TITLE
No preview (photo and text) when you share the url of a post in Facebook, Whatsapp or Telegram

### ISSUE THREAD

**Issue by niccolov** [ushahidi/platform#1720]
### Expected behaviour

When I copy and past an url of a webpage on Facebook, Whatsapp or Telegram, normally it generates a preview of the artcile with a picture and a short description

### Actual behaviour

Nothing happens. No preview is shown :(
I attach 2 images that reproduce the strange action.

### Steps to reproduce the behaviour/error

Copy for example this url: https://scattonetto.ushahidi.io/posts/511 and paste it on a chat or on a post on Facebook.

I think that this behaviour is strange and do not "push" people to click on it. The preview is a good way to share content!
![schermata 2017-04-26 alle 13 38 45](https://cloud.githubusercontent.com/assets/27413767/25432772/18fde66e-2a86-11e7-833b-c89d78c031b6.png)
![schermata 2017-04-26 alle 13 38 19](https://cloud.githubusercontent.com/assets/27413767/25432773/18fe82cc-2a86-11e7-9469-e9d6197c5ef5.png)

**Comment by ClearLakeHABMap** [comment]
Even seeing something like this error on SMSSync website
http://smssync.ushahidi.com/contributors/

**Comment by jshorland** [comment]
Duplicate. Closing.
