### ISSUE TITLE
Map should support >30k geo points

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1721]
Currently a geojson request attempts to return all Posts with geo data, this is problematic as the connection will timeout or the code will timeout as the request is too large.

- [ ] Adjust geojson endpoint to fully handle requests by tiles
- [ ] Chunk large data requests
- [ ] Pre-parse DB to ensure that posts are pre grouped rather than needing to return all items and then group them in client

**Comment by rjmackay** [comment]
>  Pre-parse DB to ensure that posts are pre grouped rather than needing to return all items and then group them in client

I would recommend against this TBH. We used to do this in v2, and the biggest pain is that you have to reload the groups for each zoom level, so while the initial load is faster, it requires far more work for each zoom in/out action. If we do want to do this, we should evaluate existing services that can cluster geojson for us.

**Comment by caharding** [comment]
@Shadrock indicated that we don't need this for COMRADES deployments right now. Should we punt to another cycle b/c useful for general platform.

**Comment by rowasc** [comment]
@willdoran @jrtricafort are we really doing this in this cycle? I don't think we have the bandwidth ... unless its a high priority item that falls in comrades/accounts / some other priority I'd say it shouldn't be cycle6 :/

**Comment by rowasc** [comment]
Ah sorry. I just realized it's tagged COMRADES automation. :( 
@willdoran This looks pretty large. We might want to divide into multiple tickets by each of your points in the description?

**Comment by willdoran** [comment]
@rowasc This is already fixed since the posts are loaded in chunks. I don't think this is still an issue.

**Comment by willdoran** [comment]
Can we close it?

**Comment by rowasc** [comment]
Ah, ok that's great, I didn't know :D . Closing then

**Comment by rowasc** [comment]
@eve-wanderi can you make sure this is covered in the regression tests script?
