### ISSUE TITLE
Define and visualize the workflow for survey responses

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1725]
**User story:** I want to be able to define the workflow that my team and I will use to process incoming survey responses. I also want to see incoming survey responses within that workflow, so I can see what stage responses are in within my workflow.

**Comment by ClearLakeHABMap** [comment]
This is an interesting idea. Are you thinking graphically or more like drop carrots/dynamic tabs? Would this include the Tasks?

**Comment by brandonrosage** [comment]
For your review, @jshorland, @natmanning, @caharding, and @rjmackay 

------

[NOTE: I'm going to refer to "posts" as "_responses_"]

I'd propose we leverage the existing "post status" mechanism to articulate (and configure) a response's "stage," since so much of the intent and meaning of those two terms is the same.

Stages, therefore, would be deployment-level entities. a deployment's default, out-of-the-box stages would be:

* Under review
* Published
* Archived

This, of course, honors the existing "post status" configuration, whose language and intent lends itself nicely to what stages are to become.

Each stage has three values:

1. Name
2. Order (it's position within the ordered list of stages)
3. Who can see responses in this stage (two options: "Everyone" or "Users with permission to edit responses")

"Who can see responses in this stage" gives stages the ability to explicitly hide or expose responses from the public. So their stage defines their visibility.

## How this might affect existing patterns

**Postcards**' "status," for example, would now display their stage name with an icon indicating its inherited visibility.

_A response who "stage" is "Published":_

![published](https://cloud.githubusercontent.com/assets/1136279/25505542/d6a182e8-2b67-11e7-84a7-12586a820d0f.png)

_A response whose "stage" is "Under review":_

![under review](https://cloud.githubusercontent.com/assets/1136279/25505560/e91db9fa-2b67-11e7-9500-f927be44b841.png)

By extension, this would also be echoed in "Tasks" mode, where postcards display a little metadata atop the task in question:

![task](https://cloud.githubusercontent.com/assets/1136279/25505725/b951fef6-2b68-11e7-8ed1-7400c5fd189c.png)

**Toolboxes** that offer a control to toggle "Stages" would also adapt to the deployers' configuration of stages. So if they expanded their use stages to include more internal processes, it might look like this:

![toolbox](https://cloud.githubusercontent.com/assets/1136279/25505654/618f7284-2b68-11e7-80bb-1f2f10277b12.png)

## Visualizing workflow using stages

All of a deployment's stages added together makes a workflow. Offering a distinct "workflow" mode fits nicely into Ushahidi's existing approach to modes, which is to display responses in way best conducive to a showcasing a specific part of their definition.

"Map" mode for responses' location data. "Timeline" for responses' submitted date. And, so, "Workflow" for responses' stage within the deployment's workflow.

I'd propose we do that with a Kanban board pattern, using "lanes" for each stage:

_(Forgive that the content of the postcards in the following mockup don't necessarily match their stage)_

![workflow](https://cloud.githubusercontent.com/assets/1136279/25506069/580d2fe2-2b6a-11e7-8b61-c725fb90713e.png)

In this mode, postcards can be dragged and dropped into different lanes to change their stage. Each lane can be scrolled vertically, and the overall board can be scrolled horizontally to reveal any obscured lanes.

In all cases, the last lane is an empty placeholder with a button to "Add stage":

![add stage](https://cloud.githubusercontent.com/assets/1136279/25506073/6628327a-2b6a-11e7-88d0-cee71d740dfd.png)

Selecting the name of a single stage atop its lane collapses the other lanes:

![workflow column](https://cloud.githubusercontent.com/assets/1136279/25506099/92eea4b0-2b6a-11e7-84ba-c51f3934bf42.png)

## Adding and editing stages

You can edit your deployment's stages either via the "Edit stages" button in the toolbar for "Workflow" mode or via Settings > Stages. Its view mimics the visual presentation of the Kanban board, but is editable:

![edit stages](https://cloud.githubusercontent.com/assets/1136279/25506132/c3ab367c-2b6a-11e7-992f-164bebbf605b.png)

You can add a stage via the "Add stage" button that's located in the placeholder lane for both "Workflow" mode and the "Edit stages" view. The view for adding a stage also mimics the Kanban board it'll appear in:

![add stage](https://cloud.githubusercontent.com/assets/1136279/25506194/1263f39e-2b6b-11e7-8ec6-014cd9afc14e.png)

## Configuring a survey to use stages

This approach to stages (replacing "post status) would demand that the current switch control within a survey's settings to "Require responses be reviewed before they're published" be adapted. With this new flexibility, I'd propose this control change to "Default stage for new responses":

![survey settings](https://cloud.githubusercontent.com/assets/1136279/25506282/791fe07a-2b6b-11e7-92cc-ad4f1cc3e2e4.png)

This would naturally allow deployers to control which stage incoming responses were dumped into, thereby directing its default visibility, as well.

**Comment by rjmackay** [comment]
- Does 'who can see responses in this stage' effect who can edit them at all?
- Does this interact with existing tasks at all? (I'm assuming it will interact with some future tasks eventually)

**Comment by ClearLakeHABMap** [comment]
This is really cool @brandonrosage . I would actually implement this immediately in the ecosystem we are developing as it fits the hierarchical report verification system used in my two deployments. 
Also, glad to see the use of this in Austin. The N. Lamar gave it away for me, but later images were confirmation. I left there in 2013 and come back often. I would love to chat more.

**Comment by rowasc** [comment]
I think we might want to close in favor of https://github.com/ushahidi/platform-pattern-library/issues/205 but I"m not sure, tagging to have it as a reference there

**Comment by Erioldoesdesign** [comment]
@rowasc yikes. looking at the UI above that's a lot of information on the screen. I would like to be able to simplify this process and make it less UI heavy. 

Let's close this and look at the problem statement again after UI refresh. I'll create a new Issue under the ushahidi/platform-pattern-library#205 epic.
