### ISSUE TITLE
Photos are not showing up :(

### ISSUE THREAD

**Issue by niccolov** [ushahidi/platform#1728]
![schermata 2017-05-02 alle 12 03 26](https://cloud.githubusercontent.com/assets/27413767/25613882/1f8965f4-2f30-11e7-9035-3c75a052c6f6.png)
![schermata 2017-05-02 alle 12 04 55](https://cloud.githubusercontent.com/assets/27413767/25613886/2303696e-2f30-11e7-9ffc-593adf111237.png)
![schermata 2017-05-02 alle 12 05 06](https://cloud.githubusercontent.com/assets/27413767/25613893/283066a8-2f30-11e7-8a60-eda7de16f868.png)
![schermata 2017-05-02 alle 12 03 37](https://cloud.githubusercontent.com/assets/27413767/25613894/28614804-2f30-11e7-81a7-14653a09aa53.png)

### Expected behaviour

In the timeline, in the map view and inside the post, if the user has upload a photo, it should be shown.

### Actual behaviour

Sometimes the photos appears sometimes no... there is an icon like "missing file".

### Steps to reproduce the behaviour/error

Just go here and have a look: https://scattonetto.ushahidi.io/views/list
You will see many posts without images (I will attach a screenshot) in the timeline and also if you open the post.

If you do a lot of reload sometimes the image appears! Same behavior happens inside the post.
If you look at the code

ERROR: when the image is not showing up the code for the image is:

https://scattonetto.api.ushahidi.io/media/uploads/scattonetto.api.ushahidi.io/5/9/59039bccc29de-photo5773628088683440498.jpg

WORK: when the image shows up, the code for the image is:

https://74ddb495e3f187ded630-0b4c691ea14dad11384ab079da46af4f.ssl.cf2.rackcdn.com/scattonetto.api.ushahidi.io/5/9/59039bccc29de-photo5773628088683440498.jpg

For us the photos are very important! Can you solve it? Could be a server or a cache problem?

Thanks,

Niccolò

**Comment by ClearLakeHABMap** [comment]
We are seeing this too. First on Heroku, and that was supposed to be an expected behavior of that server. Now we see it on our true deployment and it looks like an .htaccess issue from the resource info when we click to see the image that is missing in it's own window. The files are seen on the server in ls -la for the correct media directories.

**Comment by ClearLakeHABMap** [comment]
This is still a major issue for our deployment.

**Comment by jshorland** [comment]
Hi @clearlakeHABmap,

The latest release should include fixes for this. Are you hosted or OSS?

**Comment by ClearLakeHABMap** [comment]
OSS. I can update but it looked you were all working on a few more issues. Ready to pull the trigger.

Jay Colingham, MPH
Environmental Protection Specialist
Water Division - Tribal Office

Email: colingham.jay@epa.gov
Region 9: 1 (415) 972-3562
Research Triangle Park: 1 (919) 541-3122

Addresses:
WTR 3-4
75 Hawthorne St
San Francisco, CA 94105

D320L
109 T.W. Alexander Drive
Durham, NC 27709
