### ISSUE TITLE
It is possible to increase the size of the photos and make it mandatory?

### ISSUE THREAD

**Issue by niccolov** [ushahidi/platform#1729]
### Expected behaviour

On our survey (https://scattonetto.ushahidi.io/views/map) the photos from user are the most important thing togethere with the geodata information. The user should complete the form and publish the photos.

We would like also to make the photo upload mandatory, but in the configuration we don't have this option :(

### Actual behaviour

Many times the photos are not uploaded and is not clear if it is for a size problem or other issue.
I've seen a couple of time a message (but it changed very fast, so I couldn't read it well) about a MB limitation. Is it possible? I've seen thant many new phones "create photos" that are bigger then 10MB. It is impossible for us to ask or teach people to modify it, but is not good to loose reports of people because we don't have the photo :(

The same photo sometimes was not uploaded, but after 2/3/4 attempts we got to upload it. So probably is not related only to the size of the image?

### Steps to reproduce the behaviour/error

This happens manily from mobile phones but sometimes also from web interface.

**Comment by jshorland** [comment]
@niccolov FYI  we're looking into all of these photo issues you've logged!

**Comment by tuxpiper** [comment]
@niccolov we've isolated a configuration problem affecting the photo upload. It was failing only sometimes because the problem was affecting just one of the servers in our farm. The problem has been resolved now.
