### ISSUE TITLE
Improve API and Cloud intercom data capture

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1733]
@rjmackay 
### Expected behaviour
- [x] On deployment create in API, create company object with name and date created
  - [x] Company is named based on subdomain. Needs to be something API will know and can't change
- [x] On create initial admin user push user object with name and associate to company object
- [x] On Admin create in API add new user and associate with company object
- [x] Original Form name changed?
  - [x] Attach data to company not user
  - [x] At the moment identified based on id 1. Form repo should emit entire form object, filter by id should happen in the listener (could happen later since this is purely code organization)
- [x] Datasource number changed
  - [x] Attach data to company not user
  - [ ] Config repo should emit entire form object, counting data sources etc should happen in the listener (could happen later since this is purely code organization)
- [x] Change intercom app token to use non-site config such as 3rd_party
- [ ] ~~Move Listener with src/App~~ ignore this for now
- [ ] Confirm nothing breaks with intercom id isn't configured

**Comment by rjmackay** [comment]
> On deployment create in Cloud Interface, create initial admin user object with name and associate to company object

This could happen in the API by creating intercom users for ALL admin users in a deployment. The deployment scripts use the `bin/ushahidi user create` which in turn users the user repo+usecase so that should capture the initial user too.

**Comment by rjmackay** [comment]
Updated the checklist above.

**Comment by rjmackay** [comment]
@willdoran where did this all end up? Do we need to QA? How do I do that?

**Comment by willdoran** [comment]
I think this already went through QA and was merged about a month ago. I'm not sure why the ticket is still open, I'll check into it.

**Comment by rjmackay** [comment]
@willdoran Probably because we haven't deployed in over a month :( but also because we were still refactoring.

**Comment by rjmackay** [comment]
Has this been enabled in production then?
