### ISSUE TITLE
Vimeo video embeds don't render

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1740]
### Expected behaviour
Video will render

### Actual behaviour
Video not shown, errors in JS console.
It seems vimeo won't let us iframe their videos... maybe the video URL needs a different format?

### Steps to reproduce the behaviour/error
- Upload a video from mobile
- Try to view the post in the browser
See errors in JS console

https://mobileappqa.ushahidi.io/posts/13

**Comment by willdoran** [comment]
@rjmackay I think it's using the wrong format for the vimeo url 
https://developer.vimeo.com/apis/oembed

**Comment by rjmackay** [comment]
Ok. @dalezak  is that enough info to correct it?

**Comment by dalezak** [comment]
I was attaching the unlisted video URL https://vimeo.com/217095139/0662aab2e1 but looks like that can't be used in an IFRAME.

```
Refused to display 'https://vimeo.com/217095139/0662aab2e1' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

https://vimeo.com/api/oembed.json?url=https%3A//vimeo.com/217095139/0662aab2e1

```{
"type": "video",
"version": "1.0",
"provider_name": "Vimeo",
"provider_url": "https://vimeo.com/",
"html": "<iframe src=\"https://player.vimeo.com/video/217095139\" width=\"480\" height=\"360\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>",
"width": 480,
"height": 360,
"video_id": 217095139,
"uri": "/videos/217095139:0662aab2e1"
}```

I'll upload the Player URL instead https://player.vimeo.com/video/217095139 which loads inside an IFRAME.

**Comment by dalezak** [comment]
Looks like the switch to Vimeo's Player URL fixed the problem on the web :+1: 

https://www.dropbox.com/s/6iil5l1hnmo9p10/Screenshot%202017-05-15%2014.52.43.png?dl=0
