### ISSUE TITLE
Email not working

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1745]
This user https://vanderbilt.ushahidi.io/views/map

And replicated on qa.ushahididev.com

Can't get emails to pull into the platform

**Comment by willdoran** [comment]
@jess is this working now?

**Comment by jshorland** [comment]
@willdoran @tuxpiper restarted our job queues I believe, but it looks like there's still issues? Not sure what's happening exactly, but emails aren't coming in to qa.ushahididev.com.

**Comment by tuxpiper** [comment]
Tested again, it works. Btw, I added "@gmail.com" to the usernames in the email dataprovider configuration.
