### ISSUE TITLE
Warn user on big CSV imports

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1749]
The amount of rows that can be imported from a CSV is limited by the execution time allowed to the PHP script. A usual default is 30 seconds.

Here's the suggestion to warn the user if the CSV file is bigger than 100 rows

Aha! Link: https://ushahiditeam.aha.io/features/PROD-605

**Comment by jshorland** [comment]
Is it possible to improve the efficiency of the CSV upload? This is a good right away solution, but longer term, I think we need to improve CSV upload to import more lines of data. Our paying users have consistently run into this issue -- They want to upload large data sets, but can't, and then have to go in and break them up into CSV fils with 250 rows each. 

See:

**Comment by jshorland** [comment]
Putting the above into a separate issue

**Comment by jshorland** [comment]
For now, warning should inform the user of max file size.

**Comment by jshorland** [comment]
We've done a lot around CSV export improvements in the upcoming release from 2chaguzi. @rjmackay you think we can close this now?

**Comment by rjmackay** [comment]
Sadly no, not yet. A big import will still fail until we move CSV processing in to queues.
