### ISSUE TITLE
Duplicate a survey looses attributes on save

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1750]
### Expected behaviour
When I save a duplicate survey the attributes stay there

### Actual behaviour
When I save a duplicate survey the attributes disappear (despite being saved)

### Steps to reproduce the behaviour/error
http://quick.as/PgZHJrZq

**Comment by ryanchristo** [comment]
I love the video! I came across this issue after creating ushahidi/platform#1815 and submitting pull request ushahidi/platform-client#676, which loads the survey data after saving a new survey. This should solve the issue.

**Comment by ryanchristo** [comment]
Also, there is currently an issue (ushahidi/platform#1809) preventing duplicate surveys from being saved, which would need to be fixed in order to test.

**Comment by ryanchristo** [comment]
I also came across issue ushahidi/platform#1713 and submitted pull request ushahidi/platform-client#680, which redirects to the survey list after successfully saving and this would make the above mentioned pull request (ushahidi/platform-client#676) unnecessary. Looks like there are two options here: (1) load the field data after successful save when creating a new survey or (2) redirect to the survey list after successful save (which loads the field data when reopened).

**Comment by rjmackay** [comment]
I think the redirect seems like the better option

**Comment by ryanchristo** [comment]
Agreed.
