### ISSUE TITLE
Auto create categories when upload a CSV file

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1757]
### Expected behaviour
If I upload a CSV file and map a column to a category field, there should be an option to auto create missing categories

### Actual behaviour
No option to auto create categories exists

Aha! Link: https://ushahiditeam.aha.io/features/PROD-602

**Comment by leninpaulino** [comment]
I'll take a look at this one. May come back soon with details about a possible implementation.

**Comment by rowasc** [comment]
That would be amazing thank you @leninpaulino
