### ISSUE TITLE
Styling in category-settings-list is off

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#1759]
The styling of the list of categories in settings is a bit off. The trash bin for child-categories is a few pixels to far to the right.

**Comment by jshorland** [comment]
yeah, this'll drive a perfectionist nuts.

**Comment by middle8media** [comment]
@rjmackay I believe this falls into design/front-end/PL and should be assigned to me ... fix in the PL as opposed to inline styles ... right?

**Comment by crcommons** [comment]
@middle8media I made the changes in the pattern library but still don't have access to push the changes. Waiting for Robbie or David to get back online after travels to help me with this.

**Comment by middle8media** [comment]
@crcommons ok. Feel free to assign a PR to me and let me know if you need any help.

**Comment by rjmackay** [comment]
@crcommons @middle8media it looks like this got lost somewhere? I'm still seeing weird styling on http://qa.ushahididev.com/settings/categories

**Comment by crcommons** [comment]
Justin weighed in on broader styling changes, so I created an entirely new issue in the pattern library. @middle8media is going to work on it since my sass skills aren't great.

**Comment by middle8media** [comment]
https://github.com/ushahidi/platform-pattern-library/issues/141

**Comment by rjmackay** [comment]
@middle8media moving this into backlog, unless you're working on it.
