### ISSUE TITLE
please try to combine both sites

### ISSUE THREAD

**Issue by BlackFerrari** [ushahidi/platform#1762]
### Expected behaviour

there is a site to post donations and people who need help
ill post the link below. 
its better to combine urs and that site. 

### Actual behaviour

its difficult to find who actually want help. sometimes same person have attention while some hidden

### Steps to reproduce the behaviour/error

combine the sites and try to build one place instead two. its difficult to manage donations without common place to manage them. thousands of posts shared in the facebook.

im representing kotelawela defence university computer science 4th year batch . even we started our final exams my people like to help if there is need development of the site.  

appreciate your work.

thank you.

**Comment by BlackFerrari** [comment]
http://reliefsupports.org  link for the mentioned site

**Comment by ClearLakeHABMap** [comment]
Have you tried to using a deployment of the Ushahidi.com website? Your need base may require a paid version of the website, but you could migrate your data into one that accepts data import. Surveyor is the most basic plan that allows this. You may have success installing this deployment and formatting your data in a CSV to import into Ushahidi. You can also link any new entry on your website to an Ushahidi map by setting up a smtp server and allowing it to propagate each new entry to an account that is received by your map deployment.

**Comment by jshorland** [comment]
Hi @blackferrari -- I'd recommend spinning up a new instance of the Ushahidi platform, either our hosted version which takes a few minutes to create (ushahidi.io/create), or through the open source version which takes longer as you'll need to install and set up on your own servers and hosting.
