### ISSUE TITLE
English isn't listed on language picker

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1767]
1. English isn't listed? it's so weird, because it used to be there... You can hit refresh after changing a language and get it back to english, but this is p0 and we should fix ASAP

try to change language back to english on https://mobileappqa.ushahidi.io/views/map

**Comment by Angamanga** [comment]
@tuxpiper @willdoran @rjmackay How/where are the language-files imported in the deployments? Do we import the files from transifex in some way? I get the following error-message when accessing above deployment, and also on qa:
![screen shot 2017-05-31 at 20 31 22](https://cloud.githubusercontent.com/assets/8624777/26647676/59531006-4640-11e7-8103-10d9f548621f.png) English was definitely there before the release so it must have gone missing somewhere in the process? Look at this picture from the blogpost, english is listed: ![screen shot 2017-05-31 at 20 31 22](https://lh4.googleusercontent.com/sdZ45vsLy-Kr2jMRXqg6YWlRyDnA3I2yFnoKZv5clqCl0koCkVCKy3Wc7r6VJVgZmAjF9vO25Z_zngacy4WfmsI5mOXafCB6bM6RfWbBSZDLlwvwyNFrJ4e8ZKD1tXuNoTiHN76v). Any ideas where to start looking?

**Comment by willdoran** [comment]
@Angamanga yep the files are loaded from transifex but I'm not sure in the case of English, that error may be related I'll take a look now.

**Comment by rjmackay** [comment]
I think we *shouldn't* be pulling english from Transifex because its the source language.
We might need to push it into the language manually. 

There's also some madness around having both `en` and `en-US` ... we should really only support one English variant for now

**Comment by rjmackay** [comment]
I'll grab this since its morning my time

**Comment by rjmackay** [comment]
Tested on staging, and now deployed to production
