### ISSUE TITLE
Ability to scroll over / expand small post detail bubbles on the map

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1770]
### Expected behaviour

When the title/description of a field is long-ish , the user would like to have means for scrolling or expanding (in place) the small bubble that appears when the marker is clicked.

### Actual behaviour

<img width="1544" alt="screen shot 2017-06-01 at 13 11 55" src="https://cloud.githubusercontent.com/assets/467393/26677462/6bb8dc9e-46cc-11e7-86bf-39e6cadff324.png">

The bubble is not scrollable or expandable 

### Steps to reproduce the behaviour/error

Click on the marker of any post containing ~>25 words of description

### Links / Context

Related to this sentry conversation, this is a prospective client of .io

https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/255721/conversations/10085352846

**Comment by caharding** [comment]
@jshorland can we close this in favor of fixing this issue in other ways?
