### ISSUE TITLE
Deleted title / description fields from survey still appear on the form

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1771]
### Expected behaviour

Once these fields are deleted from the survey, they shouldn't appear on the survey form.

If the title / description fields are compulsory (because their presence is assumed in other parts of the code), it should not be possible to delete them.

### Actual behaviour

When either title or description are deleted from the survey, they still appear in the form.

### Steps to reproduce the behaviour/error

1. Create a new survey
2. Delete title / description fields
3. Save the survey
4. Click into adding a post to the survey

### Links

https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/255721/conversations/10085352846

**Comment by aoduor** [comment]
@tuxpiper i think this got fixed with the new release. The delete button no longer exists next to the title and description fields.

see ![screenshot](http://i.imgur.com/49dRTMh.png)

**Comment by tuxpiper** [comment]
Totally agree, thx @aoduor !
