### ISSUE TITLE
Privacy Notice to Users

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1772]
We are updating our privacy policy to enable new features on our mobile app and RollCall. For every user who logs into Ushahidi after June 30th (subject to change), 

User Stories
- [x] User will be presented with a pop-up dialogue that disables all other features and says:"We have updated our [Terms and Conditions](https://www.ushahidi.com/terms-of-service) and [Privacy Policy](https://www.ushahidi.com/privacy-policy). Please review these documents carefully and accept the terms in order to continue to use Ushahidi's services." Check with Charlie for updates links. 
- [x] User is presented with a checkbox and "accept and continue" button
- [x] The checkbox must be checked to continue
- [x] User will be presented with this dialogue every time they try to login until they accept

Tech spec:
- [x] Extend user object to include Terms & Conditions boolean
- [x] Allow this boolean to be set via our ansible playbooks - for future events where we want to change T&C
- [x] Add Terms & Conditions module to Client with UX - this can extend the first time login system
- [x] Add Terms & Conditions endpoint to retrieve link to relevant terms and conditions
- [x] Ensure OSS Users are not effected by this
- [x] Users that do not agree to the T&C can not continue to their profile

**Comment by willdoran** [comment]
@caharding @jshorland 
Questions:
1. This is per user right? Not per deployment

Tech spec:
1. Extend user object to include Terms & Conditions boolean
2. Allow this boolean to be set via our ansible playbooks - for future events where we want to change T&C
3. Add Terms & Conditions module to Client with UX - this can extend the first time login system
4. Add Terms & Conditions endpoint to retrieve link to relevant terms and conditions

**Comment by caharding** [comment]
Per user. 

Charles Harding

Product Director

207-720-0713

On Fri, Jun 02, 2017 at 11:56 AM will

<
mailto:will <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/caharding https://github.com/jshorland
Questions:

This is per user right? Not per deployment

Tech spec:

Extend user object to include Terms & Conditions boolean

Allow this boolean to be set via our ansible playbooks - for future events where we want to change T&C

Add Terms & Conditions module to Client with UX - this can extend the first time login system

Add Terms & Conditions endpoint to retrieve link to relevant terms and conditions

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/ushahidi/platform/issues/1772#issuecomment-305880903
, or

**Comment by rjmackay** [comment]
What happens if they don't accept?

**Comment by rjmackay** [comment]
@willdoran an addition on the tech side: make sure this never shows up for OSS users.

**Comment by caharding** [comment]
If they don't accept they can't continue to their profile.

On Mon, Jun 05, 2017 at 12:51 PM Robbie Mackay

<
mailto:Robbie Mackay <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/willdoran
an addition on the tech side: make sure this never shows up for OSS users.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/ushahidi/platform/issues/1772#issuecomment-306284902
, or

**Comment by willdoran** [comment]
@rjmackay @caharding Does this cover it?

Tech spec:
[ ] Extend user object to include Terms & Conditions boolean
[ ] Allow this boolean to be set via our ansible playbooks - for future events where we want to change T&C
[ ] Add Terms & Conditions module to Client with UX - this can extend the first time login system
[ ] Add Terms & Conditions endpoint to retrieve link to relevant terms and conditions
[ ] Ensure OSS Users are not effected by this
[ ] Users that do not agree to the T&C can not continue to their profile

**Comment by caharding** [comment]
Looks right to me

On Mon, Jun 05, 2017 at 1:36 PM will

<
mailto:will <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/rjmackay https://github.com/caharding
Does this cover it?

Tech spec:

[ ] Extend user object to include Terms & Conditions boolean

[ ] Allow this boolean to be set via our ansible playbooks - for future events where we want to change T&C

[ ] Add Terms & Conditions module to Client with UX - this can extend the first time login system

[ ] Add Terms & Conditions endpoint to retrieve link to relevant terms and conditions

[ ] Ensure OSS Users are not effected by this

[ ] Users that do not agree to the T&C can not continue to their profile

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/ushahidi/platform/issues/1772#issuecomment-306297806
, or

**Comment by ClearLakeHABMap** [comment]
I think you both bring up use cases. Some organizations will not be able to manage, hold, or retain personal information without disclosure. There may need to be a setting in the admin settings -> data/users or a new settings tab to toggle between remove past data from users that do not accept, remove PID from users that do not accept, or freeze account access from users that do not accept. The pop up should reflect this to the user clearly based on what is selected. 
Use case can include a number of examples for each. Let me know if you need clarification on why one of the three would be needed.

**Comment by caharding** [comment]
@ClearLakeHABMap can you please explain the use case further? Accounts that don't accept, won't be able to login. To clarify, the existing and new privacy policy both give the account owner ownership of the data submitted to the account.

**Comment by Shadrock** [comment]
In response to @rjmackay and, perhaps, @ClearLakeHABMap I can see valuable distinction between Ushahidi's need for this and a deployers need for this. As @caharding clarified above, this issue relates to Ushahidi - as an organization - updating its privacy policy. However, I could see a use case for offering this _functionality_ to OSS deployers: allowing them to configure a pop-up that spells out whatever privacy/data policy they have set up for their deployment: I have had to do this several times on previous humanitarian crowdsourcing projects.

**Comment by ClearLakeHABMap** [comment]
@caharding : RE: In some situations, when working with US Federal agencies, PII is so important to the internal review board (IRB) that no project can occur without the PII being accepted to exist on a server with their permission. There could be a case where some information can only be accepted if an account is made and the person accepts the terms. If a deployment were to exist and need to be updated with the newest terms, there would be a case for an account to be removed or deactivated for not accepting the newest terms and conditions. This could occur when a grant funded project enters a new grant year with newer security conditions. This year was an example of this happening. We expect this trend to continue. We cannot keep publicly hosted data that has not met consistent terms and conditions online if it has PII. In the ClearLakeHABMap, we have chosen a different approach for now, but may need this protection as more stakeholders get involved.

In other situations, it will be important to simply have the new terms and conditions open upon a new login by a past user. If we want to change the terms to allow forgetfulness to our database, we may see that they should be notified that data will be removed cyclically and all past data should be saved if it has not been already. Here, no account hold or removal is necessary, but a pop-up is.

**Comment by caharding** [comment]
Question: are you suggesting his feature for open source so open source deployments can create their own TOS?

**Comment by Shadrock** [comment]
@caharding Yes.

**Comment by caharding** [comment]
This TOS change only applies to hosted deployments. The open source license applies as he terms of service to all the open source users.

**Comment by ClearLakeHABMap** [comment]
@caharding I believe the benefit would also apply to users of open source deployments as well. Is there a way to enable that tool in the open source version as well?

**Comment by caharding** [comment]
@ClearLakeHABMap thanks for describing your issue. I understand that in the case of some academic settings it may be more convenient to use the Ushahidi OSS tools under your own TOS. However our OSS terms are the OSS license. While it may be permissible within that license to fork the code and build new TOS, the spirit of the license is that users contribute back to the code base. Creating a tool that encourages creating services outside of the OSS license isn't in service of the larger community of users. I hope you can understand. In your case you may want to build a custom plugin with a click to accept that disclose the IRB requirements to your users.

**Comment by rjmackay** [comment]
I think for OSS deployments, and probably for our hosted deployments too it would make sense to provide users submitting info with some kind of TOS/consent info. I'll add a new issue to track that though, as its kind of tangential to this one.

**Comment by ClearLakeHABMap** [comment]
@rjmackay Thanks for understanding my issue. @caharding I don't believe that we are talking about the same thing. Robbie's description strongly fits the need. It presents a user with an understanding of what they are contributing. To deny the initial screen, would be a denial of the terms and conditions of posting. Thereby refusing consent. It helps educate our users. Sometimes, a deployment could be very sensitive and could potentially affect a person's legal rights. We see this with maps that mention health and exposure (as in Fukashima or Deep Water Horizon). Some times, it is not an issue, such as an exit poll for an election. For when it could be problematic for that person's right to know about how their information will be used and shared, the consent would educate them. I feel like this is a major part of the purpose of Ushahidi. We use it to help educate others through witnessing and sharing what we experience. to that, I am super appreciative. Keep up this great work!

**Comment by rjmackay** [comment]
@ClearLakeHABMap If you're got further requirements or comments, could you post them on #1805? Bear in mind that we're a small team, with limited resources - so while you can suggest *all* the features that would exist in the ideal version, its more helpful to either give just the top priority requests, *or* rank your needs by priority so we can triage.

**Comment by ClearLakeHABMap** [comment]
@rjmackay Of course! I definitely understand your limitations. Issues allows people to do a crowdsourced QA that sheds light on issues and their importance as they affect different groups or individual projects. It seems like it is helpful for your team prioritization. Obviously no expectations come from the user side, save for progress and stability of the system as it is now.

Features (High to Low Priority): 
1) a EULA type pop up option where the site can post terms and conditions with an accept or decline.
2) Allow it to scroll for longer agreements.
3) The ability to create future EULA Update pop ups for the map. (Admin can trigger a pop up on next use)
4) Specific EULA type pop ups for members with a log in. (Admin triggers a pop up on next log-in)
5) The EULA offers HTML capacity for adding links, Images, and additional content as needed. Lowest priority, but possibly a good approach to the way the pop up can work.

**Comment by jshorland** [comment]
👍👍👍

**Comment by rjmackay** [comment]
Most of this is done in @crcommons PRs. However we'll need to follow up with a PR that blocks access to data from the API unless the users accepts terms.

I think it might make sense to simply treat them like a non-logged in user until they accept the terms... or we can deny access entirely.

**Comment by rjmackay** [comment]
First iteration deployed to staging for testing

**Comment by rjmackay** [comment]
Deployed to staging. Works for me!

**Comment by caharding** [comment]
Reopening until it goes live on Oct 20
