### ISSUE TITLE
Obfuscating of map coordinates

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1775]
Related to ushahidi/platform#1774 

### Expected behaviour
When location is regarded as PII in a deployment, map coordinates for the post should be obfuscated when provided from the API, so that no one can retrieve the exact locations.

This may be a randomisation within or an assignation to the centroid of a reasonably big geoblock (e.g. in function of the maximum allowed zoom level setting as specified in #1774)

### Actual behaviour
Currently the API provides the exact coordinates as stored along with the post.

**Comment by ClearLakeHABMap** [comment]
PII is incredibly important to our end users and clients. I believe that this could be pivotal in the ability for many clients to adopt the platform.

**Comment by rowasc** [comment]
<img width="659" alt="Screen Shot 2019-06-09 at 19 37 22" src="https://user-images.githubusercontent.com/2434401/59165173-25a60e80-8aee-11e9-99ad-2a0d7a474126.png">
<img width="1125" alt="Screen Shot 2019-06-09 at 19 38 05" src="https://user-images.githubusercontent.com/2434401/59165174-25a60e80-8aee-11e9-8ecf-4db6404cfb6d.png">

I think this should be covered by the anonymization and precision level features. Closing but tagging @tuxpiper to reopen if necessary

**Comment by tuxpiper** [comment]
Agreed :+1:

**Comment by ClearLakeHABMap** [comment]
The map precision level of 2 is at 10km. What would a precision of 4 be? 1? I can see this starting to hinder smaller geographic deployments where the different surveys are more important than the geographic scale. What algo is the randomizer based on? Is it a true random from a physical source (ie Cloudflare) or computer generated? 
A goal of the masking of PII would be to have control to scale the range of randomness based on the variance between sources of PII within the map. If 100 sources live within 1.5km, PII randomness can be assigned to a very tight range. If 10 sources are covered over 100km in range, you may need to have a very wide value set for randomization unless that would defeat the purpose of the map, in which case, one should not use a map for this type of data.

**Comment by tuxpiper** [comment]
Thanks for the input @ClearLakeHABMap 

Apparently a level of 4 would already be giving out a precision of around 100m ... which is well, quite precise in a personal scale, I think.

The function is not a randomiser, because it was deemed important that points in the map would appear stable, and storing randomised coordinates separately seemed... inconvenient. The function pretty much just snaps the coordinates to the nearest intersection point in a grid, drawn accordingly to the precision level. I'm assuming the estimated precision that is shown in Settings > General is calculated assuming locations around the equator, but not quite sure.

This is a pretty crude approach, better approaches (in the shape of issues and/or pull requests of implementations :) ) are more than welcome. I think you are right that this "one size fit all" approach may not work well for deployments that have scopes covering areas with mixed population densities.. such as a lot of counties, states, as well as any country or continent. Dynamic approaches to solve this sound appealing.

I am guessing it's a desirable trait to have the markers in the map appear stable as the map gets reloaded, or more markers are added.... which may make dynamic implementations harder. But curious what other people think about this.

**Comment by Erioldoesdesign** [comment]
@ClearLakeHABMap Hi there,

I'd really like to understand more about your needs for a feature like this so i can better understand how to design the UX/UI. If you have a chance to email/message me that'd be amazing. eriol@ushahidi.com

If not I've assigned this to go in my backlog of issues to improve from a UX pov.
