### ISSUE TITLE
Restart report

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1778]
user should have an option to restart report in the persistent menu

**Comment by Angamanga** [comment]
Existing content of the bot. The persistent menu is in last parts of the document: https://docs.google.com/a/ushahidi.com/document/d/1DIlBYze-NcazKobB0i4PGboc0SFJhr3iDFNCar-qVDU/edit?usp=sharing

**Comment by Angamanga** [comment]
Taken care of in the bot-user-journey so closing this now
