### ISSUE TITLE
Update FB bot language

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1779]
For get started we should add more information “The Uchaguzi bot let’s you report on what you’re seeing in the Kenyan election. Uchaguzi is a collection of _____ that ______.  Click on “report a problem” to answer 4 quick questions to file your report.

**Comment by Angamanga** [comment]
Existing content is here:
https://docs.google.com/a/ushahidi.com/document/d/1DIlBYze-NcazKobB0i4PGboc0SFJhr3iDFNCar-qVDU/edit?usp=sharing

**Comment by Angamanga** [comment]
Taken care of in the bot-user-journey so closing this now
