### ISSUE TITLE
Custom field description not saving

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1787]
### Expected behaviour
When I click on "Show field description", once I enter the help text on this, and update this field, it should save and display the help text. 

### Actual behaviour
Help text entered does not get saved when I update my custom field

### Steps to reproduce the behaviour/error
* Log into your deployment
* Click on settings
* Click on surveys
* Select a survey and create a custom field. Click on "Show field" description, and add help text of your choice
* Click in save

![screenshot](https://uploads.intercomcdn.com/i/o/26020585/a8b51283337683ffa61054d0/Screen+Shot+2017-06-08+at+11.29.52+AM.png)

Refs https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/252111/conversations/10220120800

**Comment by ryanchristo** [comment]
It looks like there was no model hooked up to the input and there is an "instructions" column in the "forms/attributes" table, which would be my best guess for "description". I submitted a pull request (ushahidi/platform-client#677), which fixes the issue as long as "instructions" is the right column.
