### ISSUE TITLE
Assign category as sub categories of another via category list page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1788]
As an admin, I would like to be able to assign multiple categories as a subcategory of another, without having to click on individual categories and edit each one on its own.

Currently, I only have the delete option, as shown below.

![screenshot](http://i.imgur.com/olAsGRw.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-597

**Comment by rowasc** [comment]
Related (but not a duplicate) to https://github.com/ushahidi/platform/issues/2380

**Comment by rowasc** [comment]
@Erioldoesdesign this might be a good one for WSC designers unless you already have something for it? or is it too complicated? -I know nothing!- I know you mentioned you did UT on categories so maybe it's already done, sorry if that's the case
