### ISSUE TITLE
Permissions assigned to a top level category should apply to it's sub categories

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1789]
### Expected behaviour
When I set permissions to a top level category, the same should apply to all it's child categories. e.g, I have a top level category called Verification, with the sub categories "verified" and "unverified". When I set the "Verification" category permissions to viewable, only for specific roles i.e admin and verification teams, i expect that  the "Verified" and "Unverified" category permissions will automaticaly reflect the same

### Actual behaviour
Top level category permissions do not affect the subsequent sub categories. See below

Top level category![screenshot1](http://i.imgur.com/J1FYxTc.png)
Child category![screenshot2](http://i.imgur.com/eWafc6i.png)

**Comment by ryanchristo** [comment]
I submitted pull request ushahidi/platform-client#678, which applies the same permissions to each child category. In the example, the permissions of the parent are being limited. If you are changing the permissions of the parent to "Everyone", should the children also be updated to "Everyone"? It would be a slight adjustment if so. I hope this helps!

**Comment by Angamanga** [comment]
@ryanchristo Thank you very much for your submission! @aoduor @jshorland Should the children always have the same permissions as their parent? In that case, I think we should remove the option to change permission on children completely?

**Comment by jshorland** [comment]
Yep. Remove it.

**Comment by aoduor** [comment]
Yes. Children should have same permissions as parents. Agree with removing it from children UI

**Comment by aoduor** [comment]
Or, instead of removing it, simply have a label indicating its permissions being tied to its parent category?

**Comment by ryanchristo** [comment]
@aoduor @jshorland @Angamanga Would something like this work?

<img width="773" alt="screen shot 2017-06-28 at 8 13 53 am" src="https://user-images.githubusercontent.com/12519942/27616416-e9dcb592-5bd9-11e7-91ee-fa4e6b2f6c40.png">

**Comment by ryanchristo** [comment]
@Angamanga @jshorland @aoduor I updated the pull request (ushahidi/platform-client#678) with a preview of mentioned changes. Let me know if you would like me to adjust the message or anything else. I also made sure that if you edit a child category and change the parent, the child category will be updated with the permissions of the new parent.

**Comment by Angamanga** [comment]
Testing checklist: 
- [] When I change permissions to a category that has child categories, each child category is updated with the same permissions as the parent.
- [] When I edit a child category and change the parent category, the child category is updated with the same permissions as the parent.
- [] When I edit a child category, I am not able to change the permissions and instead I see a message that says the permissions are managed by the parent.
