### ISSUE TITLE
Categories: shouldn't be able to add a child category without also adding the parent category

### ISSUE THREAD

**Issue by erapisardi** [ushahidi/platform#1790]
### Expected behaviour
New categories should be displayed in the post/survey form.

### Actual behaviour
New categories added to the initial set of categories are not displayed  in the post/survey form

### Steps to reproduce the behaviour/error
1. create some categories and sub categories
2. create and publish new post/surveys
3. add new categories not from the post/survey form, but from the settings panel
4. create a new post/survey -> the new categories (point 3.) are not displayed

**Comment by aoduor** [comment]
Confirming that I'm experiencing this same issue.

**Comment by Angamanga** [comment]
@erapisardi @aoduor This is a part of the user-flow that is not intuitive enough. You need to manually add categories to each survey and you do that in settings->surveys->edit a survey->go to the categories-field and choose the new categories there. Then they should appear in the post. Think we need to look into this and find a better way of handling this. @aoduor suggested we keep all handling of categories in the category-settings themselves. We originally had this solution but it was removed. Any thoughts/input on this @rjmackay @willdoran @justinscherer @jshorland?

**Comment by erapisardi** [comment]
Thank you for the suggestion.
This is what I did. But as some new categories are subcategories I modified the new category in the settings panel. The problem is that the category is displayed but the parent category is not.

**Comment by Angamanga** [comment]
@erapisardi Hm, that definitely sounds like a bug, that should not be possible. Can you please check if the child- and parent-categories have the same roles set?

**Comment by aoduor** [comment]
@erapisardi see this .gif below for more details. I had to go in and edit the parent category for it to show.

![screenshot](http://i.imgur.com/mnC8WXS.gif)

**Comment by aoduor** [comment]
@angamanga i filed a separate issue on category permissions and roles, we have an issue on that front as well 
https://github.com/ushahidi/platform/issues/1789

**Comment by erapisardi** [comment]
Thank you!

**Comment by jshorland** [comment]
@Angamanga so the bug here is that you shouldn't be able to add a child category without also adding the parent category, right?

**Comment by jshorland** [comment]
@rjmackay has a fix for this ready to be QA'd: https://github.com/ushahidi/platform-client/pull/661
