### ISSUE TITLE
Top level category checkbox should not remain selected if no subcategories under it are selected

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1791]
### Expected behaviour
If a category has subcategories, I shouldn't be able to select the top level category on its own.

### Actual behaviour
Granted, at the moment, selecting a top level category checks all its subcategories. However, deselecting each of the subcategories *still* leaves the top level category checked.

Proposed solutions
1. Make the top level category checkbox unselectable( is this a word :D?)
2. Deselect the top level category checkbox IF there are no subcategories under it that have been selected,

![screenshot](http://i.imgur.com/4rsuteB.gif)

**Comment by Angamanga** [comment]
@aoduor I think this is the correct behaviour according to Brandons original plan. You are allowed to check a parent without its children, but not a child without its parent. Is this behaviour not good?

**Comment by ClearLakeHABMap** [comment]
@aoduor I understand where you are coming from. There are certain nested behaviors that cannot exist outside of their parent. In other situations, that is not the case. If the interface limits you to only view and review the subcategories, this could be a problem. In many cases, people will not know where to categorize something and expect someone more knowledgeable or experienced to assist. This is a good catch all for those problems. Additionally, there are times that you may want to avoid overly organized categories but retain a few key sub categories. An example could be reports of bullying at schools. We expect to see it at all levels, but perhaps we have a study into early childhood bullying and add a sub category for the grades of 1-3. The rest of the reports that may be just outside that window can be saved to the umbrella category above the other ones. there is probably a better example of this with more nuance, but that was the first one I could think of.

**Comment by jshorland** [comment]
Thanks for the input @clearlakehabmap! @aoduor @Angamanga I'm going to close this issue and put all feedback we've gotten on categories and their behavior into a new issue.

**Comment by Angamanga** [comment]
This was fixed in https://github.com/ushahidi/platform-client/pull/734
