### ISSUE TITLE
Add Lat/Lon fields to location field options

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1795]
There are instances where a user is unable to find the location they're looking for using our geolocation tool BUT have coordinates to the location they want to add.  

As a user, I'd like to be able to add lat/lon information if the location search feature doesn't work for me.

( This is crucial to our workflow for the geolocation team on Uchaguzi )

**Comment by aoduor** [comment]
To be abit clear on how this would work, exactly what we have on the general settings page would suffice methinks! :)

**Comment by jshorland** [comment]
@rjmackay @tuxpiper I thought the location search allowed for lat/lon too?

**Comment by aoduor** [comment]
Team. Flagging this for urgent action.

Location search at the moment does not allow for manual input of lat/lon information.

**Comment by willdoran** [comment]
This is done, might need nicer UX

**Comment by willdoran** [comment]
- [ ] Create post with location
- [ ] you should see lat lon inputs and update button
- [ ] enter lat lon
- [ ] hit update
- [ ] marker should be added and map recentred
- [ ] check that it saves and that it reloads correctly

**Comment by jshorland** [comment]
This looks good to me @willdoran and @rjmackay

**Comment by rjmackay** [comment]
@willdoran the original suggestion from Brandon on this was to accept lat/lon through the location search (http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/post-edit.html).
I'm not sure thats intuitive enough, but I'm not super happy having extra lat/lon fields outside of the location editor. Maybe we could just have the placeholder say 'Search for a location or enter lat/lon' ?? Other ideas? or maybe @middle8media could just clean up the presentation

**Comment by willdoran** [comment]
@rjmackay Yeah, I think an option inside the existing search to enter lat long, or for the search to accept lat,long would seem better. I'm not sure why they can't just translate the lat long via the existing search input.

**Comment by jshorland** [comment]
Just want to check in that this is actually getting back into core? cc: @rjmackay

**Comment by rjmackay** [comment]
I chatted with @Angamanga about this. I'd suggest that if a user enters something that looks like a lat/lon into the location search we show "Lat: X Lon: Y" at the top of the search results. Only issue is it isn't very discoverable

**Comment by rjmackay** [comment]
@Angamanga @rowasc assigning to both of you. Whoever gets to it first can get started

**Comment by aoduor** [comment]
Hmmm. I would argue with adding it exactly as is, as per feedback from users. IMO, it isn't intuitive for me as a user to know that I will be able to search by coordinates on the search bar.

**Comment by Angamanga** [comment]
@justinscherer Do you have any opinions on this? The question is about how to handle lat-lng-input in the location-picker. Either separate fields (like we used on uchaguzi) or adding lat-lag as an option when searching in a visible way in the search-field: 
![screen shot 2017-08-31 at 15 03 55](https://user-images.githubusercontent.com/8624777/29924576-a9a41d4c-8e5d-11e7-98ad-c5b902749352.png)

**Comment by rjmackay** [comment]
Personally I'd be happier if the lat/lon field were just smaller or inside the search dropdown. Right now this makes the location picker take up a huge amount of space, and when you have lots of fields its not clear that the lat/lon fields are joined to the map.

**Comment by justinscherer** [comment]
So the obvious answer here is testing. @rjmackay @jshorland @Angamanga @aoduor 

It's be a simple, 10 minute test.

For both scenarios you have an unstructured message that mentions a location. 

In prototype A you leave it as is with the lat/long 

In prototype B you take away the separate fields and update the helper text in the search bar to say something like: "Search by address, lat long coordinates, or place name"

You time them both and you see which one wins. 

If this is priority, I can whip up simple prototypes fast, just let me know. 

I think 3-5 participants per prototype is sufficient. Things like this are worth testing, IMO, even though they are small, because our poor data groomers have to play with these fields a whole lot.


@jshorland I have a bunch of stuff in the hopper, but if we think this is priority I'll bump it up. let me know.

**Comment by jshorland** [comment]
This is priority now that uchaguzi is happening again.


> On Sep 1, 2017, at 8:08 AM, justinscherer <notifications@zube.io> wrote:
>=20
> justinscherer mentioned you in Card #2863 (ushahidi/platform #1795) Add La=
t/Lon fields to location field options
> So the obvious answer here is testing. @rjmackay @jshorland @Angamanga @ao=
duor
>=20
> It's be a simple, 10 minute test.
>=20
> For both scenarios you have an unstructured message that mentions a locati=
on.
>=20
> In prototype A you leave it as is with the lat/long
>=20
> In prototype B you take away the separate fields and update the helper tex=
t in the search bar to say something like: "Search by address, lat long coor=
dinates, or place name"
>=20
> You time them both and you see which one wins.
>=20
> If this is priority, I can whip up simple prototypes fast, just let me kno=
w.
>=20
> I think 3-5 participants per prototype is sufficient. Things like this are=
 worth testing, IMO, even though they are small, because our poor data groom=
ers have to play with these fields a whole lot.
>=20
> @jshorland I have a bunch of stuff in the hopper, but if we think this is p=
riority I'll bump it up. let me know.
>=20
>=20
>=20
>=20
> You are receiving this notification because you are subscribed to this ite=
m.=20
> You can change your notification settings for this project at https://zube=
.io/ushahidi/platform/edit/notifications

**Comment by rjmackay** [comment]
@jshorland Can you move this back to validate/test if we're testing before building this?

**Comment by jshorland** [comment]
Since we tested the split out fields in the first uchaguzi, I'd recommend we try to test searching in the same location search field on the map?

**Comment by justinscherer** [comment]
This is the treatment I was thinking about
<img width="700" alt="screen shot 2017-09-28 at 8 19 06 am" src="https://user-images.githubusercontent.com/29209303/30953887-c7d6566c-a425-11e7-865a-5a5dc4f36e45.png">

**Comment by jshorland** [comment]
Love that. I'll move it to 2chaguzi sprint and prioritize relatively low
compared to other issues.

**Comment by jshorland** [comment]
Passes QA
