### ISSUE TITLE
[Grammarly] Roving whitespace movement when adding a new category.

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1796]
I don't know how best to describe this, so i'll just show you!

![screenshot](http://i.imgur.com/LOluZI2.gif)

Steps to reproduce
* Log into your deployment
* Click on settings, then categories
* Attempt to create a new category.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-595

**Comment by jshorland** [comment]
Haha weird!

**Comment by Angamanga** [comment]
@aoduor I cannot reproduce this, which browser did you use when this happened?

**Comment by aoduor** [comment]
Google chrome :(

**Comment by rowasc** [comment]
noting this is a grammarly thing, it's happened to me both in platform and other places. I suspect it might have something to do with either angular or our input types / css but it definitely comes because of the plugin

**Comment by Angamanga** [comment]
I finally could reproduce this! It definitely happened after installing Grammarly!

**Comment by rowasc** [comment]
I'm tagging for community task and maybe someone can do some research to fix it (and we can help)

**Comment by emalindahk** [comment]
Hi, I'm Emmah I would like to work on this for my outreachy contribution

**Comment by Angamanga** [comment]
@emalindahk I assigned you to this one: https://github.com/ushahidi/platform/issues/3315

**Comment by emalindahk** [comment]
@Angamanga I cannot reproduce this issue, I'm using Chrome everything seems to be okay.

**Comment by Angamanga** [comment]
@emalindahk You need to have the Grammarly-extension for Chrome installed to see it: https://www.grammarly.com

**Comment by emalindahk** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/12936055/95845148-7cf76700-0d52-11eb-871b-a7ddc444f17b.gif)

**Comment by emalindahk** [comment]
@Angamanga I have the extension, this is what is happening on my chrome

**Comment by Angamanga** [comment]
@emalindahk Hm interesting! Thank you for looking into it. It seems like Grammarly has fixed this issue for us :) Closing this.
