### ISSUE TITLE
Limit assignment of (specific) categories by role.

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1797]
***Original request:***
In the same way that I can limit who responds to a survey, but allow users to view surveys, I'd like to be able to limit who submits responses to a category, but still have people be able to see a post tagged to a category I've selected. e.g setting a post as verified should be handled by someone on a deployment team, however, the public should be allowed to view and differentiate between verified and unverified posts ( i.e see the tag/label). Is this currently possible?

I really hope I've articulated this well. 

---------

- There should be a way to limit which users can assign a category to a post. 
Example:
- User A is allowed to assign "Unverified" and "Verified" categories to any posts. 
- User B is *not* allowed to assign "Unverified" and "Verified" categories to any posts. 
- User B is allowed to assign "Needs triage" categories to any posts.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-594

**Comment by jshorland** [comment]
I understand what you mean. 

At the moment, no.

**Comment by jshorland** [comment]
We might want to think about adding a verified feature into the platform specifically for verification. Seems like tags aren’t *quite* enough
