### ISSUE TITLE
Access Denied When Configuring twitter 

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#1799]
### Expected behaviour
Should have alternative instructions on how to create a a new twitter application.
### Actual behaviour
Instructions don't tell you to sign in before trying to create new twitter application. There is nowhere to sign in on the access denied page. Unclear instructions.
### Steps to reproduce the behaviour/error
First log out of twitter
Then in the platform go to Settings>Data Sources>select "Create a new twitter application"

**Comment by rowasc** [comment]
Related to #3533

**Comment by rowasc** [comment]
Closing in favor of #3553
