### ISSUE TITLE
Category display on Post Edit view

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1800]
### Expected behaviour
- The categories should display within a collapsed box to limit the space taken up

### Actual behaviour
- The categories display as a very long list of checkboxes which pushes other content far down

**Comment by ryanchristo** [comment]
I updated the pull request (ushahidi/platform-client#672) with the ability to select all categories when creating a post and survey and the ability to show/hide the categories list (ushahidi/platform#1800).

I realize the team is on a retreat so no rush getting back to me but looking forward to your input and feedback. Let me know if this is what you had in mind.

**Comment by willdoran** [comment]
@ryanchristo Thanks so much for helping out. We should make it much clearer what our flow is for fixing issues/adding features. The general flow is 
Scoping -> Design -> Tech Spec -> Dev Backlog

Issues tagged with "dev backlog" are generally ready for work. The categories issue needs a little bit of design in terms of the show/hide I will check and see if we have an existing pattern in our Pattern Library that might fit this.

**Comment by ryanchristo** [comment]
@willdoran Apologies for jumping the gun on this one. Thank you for clarifying the workflow!

**Comment by willdoran** [comment]
@ryanchristo, no problem, thank you so much for taking the time to contribute. I'll review and see what I can integrate with what we already have.

**Comment by Angamanga** [comment]
@justinscherer @aoduor Is this userflow ok? 
*Before toggling the categories*
![screen shot 2017-08-15 at 09 59 48](https://user-images.githubusercontent.com/8624777/29307108-c8d93a7c-81a0-11e7-8639-6ada573a764f.png)

*After toggling the categories*
![screen shot 2017-08-15 at 09 59 43](https://user-images.githubusercontent.com/8624777/29307127-ddb3f0e0-81a0-11e7-8e5a-896b705f0d83.png)

**Comment by rjmackay** [comment]
@Angamanga I don't think we should use a toggle checkbox for this since it not enabling/disabling something, rather just a show/hide. Could we use the `custom-fieldset` seen here: http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/2_fragments/
or the overflow pattern used in the timeline filter (where we have a `More` button to expand) ??
