### ISSUE TITLE
Categories: Select all when adding category field to survey

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1801]
### Expected behaviour
- When adding a category field to a survey, there should be an option to select all
- The category list should also display as a collapsed box to limit screen space taken up
### Actual behaviour
- Categories display as one long list and it is necessary to select each individually

**Comment by ryanchristo** [comment]
I would be happy to help build this feature.

I added the ability to select all categories when creating a survey and submitted pull request #672 to ushahidi/platofrm-client.

Let me know if this is what you had in mind and if you would like me to make any changes. Also, were you thinking the collapsed box would include the select all checkbox and look and act similar to "Show field description" above the current categories list?

**Comment by ryanchristo** [comment]
I updated the pull request (ushahidi/platform-client#672) with the ability to select all categories when creating a post (ushahidi/platform#1800) and the ability to show/hide the categories list.

I realize the team is on a retreat so no rush getting back to me but looking forward to your input and feedback. Let me know if this is what you had in mind.
