### ISSUE TITLE
Calendar doesn't display all days in month or navigational arrows

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#1803]
### Expected behaviour
When using filter dates, calendar should display all dates within month and you should be able to move back and forth between months. Dates that are on dark colored lines should have light colored text.

### Actual behaviour
Weeks alternate between light gray and dark gray. Dates are nearly unreadable on dark gray lines. There are no ways to navigate through the calendar. If you x-out of the filter by modal, the calendar stays.

### Steps to reproduce the behaviour/error
Start at deployment home>filter>Select date

<img width="1258" alt="screen shot 2017-06-13 at 11 06 43 am" src="https://user-images.githubusercontent.com/8941223/27089824-8273a4ee-5029-11e7-9b55-15e0ed652182.png">

<img width="1299" alt="screen shot 2017-06-13 at 11 06 49 am" src="https://user-images.githubusercontent.com/8941223/27089835-886a4ca4-5029-11e7-86ab-51e2aa8d6c9b.png">

**Comment by ryanchristo** [comment]
It looks like the issue with the styling was a minor typo. I submitted pull request ushahidi/platform-client#675. The calendar still appearing after exiting the modal is a little more complicated but I will keep an eye out for a solution as I continue to familiarize myself with the project.

Also, I thought I might add that when you click one date field then the other, the calendars stack on top of each other, which would be related to the issue with the calendar still appearing after exiting the modal. The calendar for an individual date field should only be visible when that field is in focus.

**Comment by ryanchristo** [comment]
After further investigation, it looks like the spelling of "klass" was not a typo according to datepicker docs (http://amsul.ca/pickadate.js/date/) but the way it was being used was overriding the styling. I updated pull request ushahidi/platform-client#675.

**Comment by ryanchristo** [comment]
The issue with the calendar remaining after exiting the modal and the calendars overlapping can be solved by increasing the z-index of the picker class in the pattern library. I submitted pull request ushahidi/platform-pattern-library#137. This fixes the issue in combination with ushahidi/platform-client#675.

**Comment by rjmackay** [comment]
Ready to test on qa.ushahididev.com
