### ISSUE TITLE
Smart search

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1804]
I've staged a solution to this that focuses on making the "searchbar" an all-in-one tool for searching, filtering, and summarizing what filters are applied.

searchbar

How it appears depends a lot on the interaction and what's being done. It listens to and reflects what the user does within the "Filters" dropdown. It can be used for text-only filtering or as a summary of what's been configured in the "Filters" dropdown.

Generally speaking, this solution moves all of the search/filter summary out of mode context and into the searchbar.

Here's a short video sample of some interaction: http://d.pr/i/1eBjY/5PAITFKZ

I intend to discuss this at the hit team in Montreal. But I'd appreciate any general feedback on the design solution, @caharding.

**Comment by caharding** [comment]
I love seeing this idea. The video interaction doesn't load though.  

a, pre, code, a:link, body { word-wrap: break-word !important; }

**Comment by jshorland** [comment]
@charlie sorry I didn't want to lose a piece of another issue that we decided not to implement for sake of time, but would like to put into backlog. The droplr brandon originally uploaded is gone. sigh.

**Comment by rowasc** [comment]
:/ I think we've lost the details of this issue since w don't have the video, but it sounds pretty similar to the filters dropdown. For the moment Im closing in favor of the UI refresh tickets to keep the repo tidy https://github.com/ushahidi/platform-pattern-library/issues/205 but if someone has more details please feel free to reopen and add

**Comment by Erioldoesdesign** [comment]
I think I understand what Jess is describing from this so I can make sure it's included in the search/filters/redesign. 👍
