### ISSUE TITLE
Present reporters with TOS or info about what their report is used for.

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1805]
Forked from #1772: 

Allow deployers to configure a modal/display that spells out whatever privacy/data policy they have set up for their deployment.

This should be relatively free form so that it could be a full TOS for some deployments, or it could just be a brief notice: "you data will be used for x, y and z".

For hosted deployments it should always be clear that our TOS applies regardless.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-593

**Comment by ClearLakeHABMap** [comment]
Features (High to Low Priority):

a EULA type pop up option where the site can post terms and conditions with an accept or decline.
Allow it to scroll for longer agreements.
The ability to create future EULA Update pop ups for the map. (Admin can trigger a pop up on next use)
Specific EULA type pop ups for members with a log in. (Admin triggers a pop up on next log-in)
The EULA offers HTML capacity for adding links, Images, and additional content as needed. Lowest priority, but possibly a good approach to the way the pop up can work.

**Comment by Shadrock** [comment]
For an example of what @ClearLakeHABMap might be talking about see [pages 8-9 of this report](https://www.usaid.gov/sites/default/files/documents/2151/USAIDCrowdsourcingCaseStudy.pdf) for a USAID crowdsourcing effort in which the agency _required_ volunteer acknowledgment / sign off of the ToS to address the issues listed in the report. This was achieved by using a pop-up consent/ToS checkbox to all new users/contributors.

**Comment by ClearLakeHABMap** [comment]
@Shadrock That is an example. I believe that with the USEPA, it will likely be a lot more extensive as we also have to consider the impacts of releasing information that may have implications to health. Certainly that data could play a role in a participants future, insurance, and other non-trivial complications.
