### ISSUE TITLE
Incorrect displaying of images

### ISSUE THREAD

**Issue by Yourlogin1** [ushahidi/platform#1806]
### When I upload an imagem I see it in my browser in draft post, but when I publish my post, image doesn`t displaying. I cheked uploads - image is there, but it doesn`t display on site.
Also I would like to know how can I configure ushahidi for NGINX ?

**Comment by ClearLakeHABMap** [comment]
Which version of the map are you using? Is this a new deployment? Is it on a private server or on the Ushahidi.com site?
This issue has been happening to us on our deployment and a number of others. Please look back for past tickets regarding this problem.

**Comment by diegodorgam** [comment]
+1
I'm using a docker-compose install for V3.7

having the same upload images issues

**Comment by diegodorgam** [comment]
hey, anyone? Pretty serious bug this... Any thoughs?
