### ISSUE TITLE
Provide integration with wikirumours / unahakika.org

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1811]
# Una hakika integration

## Una Hakika’s data model and API

https://www.unahakika.org/explore_api

* Rumours have…
	* id
	* text (description)
	* status (unconfirmed, under investigation, confirmed…)
	* date
	* location (lat, long)
	* keywords
	* sightings
		* in turn, sightings have a similar set of properties like rumours
	* findings
	
## Goals
Create a datasource or separate integration app (like comrades-service-proxy or facebook-bot), that…

* Create a platform post for each new rumour
	* Create a survey with fields corresponding the available rumour details
	* Create posts in that survey, one for each new rumour appearing in unahakika
	* Restrict the rumour search with keywords (i.e. “elections”) and/or other available filters
* Update platform posts as their corresponding rumours get updated
	* specially: status, sightings, findings

## Technical details

* the API doesn’t allow to get the latest updates since <timestamp> , we’ll need to get the whole list of rumours every time
* there are no phone numbers or end user contact details  to retrieve

**Comment by caharding** [comment]
Not needed according to Shadrock, closing
