### ISSUE TITLE
Fields are not visible after creating a survey

### ISSUE THREAD

**Issue by ryanchristo** [ushahidi/platform#1815]
### Expected behaviour
- After creating a survey and saving, the survey fields are visible.

### Actual behaviour
- After creating a survey and saving, the survey fields are not visible.

before saving:

<img width="950" alt="screen shot 2017-06-21 at 9 28 11 pm" src="https://user-images.githubusercontent.com/12519942/27417364-a7b43c14-56c8-11e7-9871-e741e41eba03.png">

after saving:

<img width="948" alt="screen shot 2017-06-21 at 9 28 24 pm" src="https://user-images.githubusercontent.com/12519942/27417365-a94cef6c-56c8-11e7-9cd0-bb69baf7aae9.png">

### Steps to reproduce the behaviour/error
- Settings > Surveys > Create
  - add fields and save

**Comment by jshorland** [comment]
Can't replicate. Closing.
