### ISSUE TITLE
'Submitting' placeholder text on "save" not translated

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1817]
### Expected behaviour
- When saving a post the 'Submitting...' spinner text is translated
### Actual behaviour
- When saving a post the 'Submitting...' spinner text is not translated

### Steps to reproduce the behaviour/error
- [x] Switch to a non-english lang
- [x] Create a new post
- [x] Fill in required fields
- [x] Click save
- [ ] The 'Save' text will change to 'Submitting...' but is not translated into the platform language

**Comment by jshorland** [comment]
@willdoran is this a new string of text that needs to be translated in transifex?

**Comment by willdoran** [comment]
@jshorland It's actually two parts, one a new string and two the template might just have a static string. It's a quick fix. I was going to suggest @crcommons look at it, since it covers a couple of things. I want to extend the issue to add "See if this is a pattern of incorrect string setting"

**Comment by jshorland** [comment]
great! moving to dev backlog

**Comment by crcommons** [comment]
This was just an issue with the link to our en.json file not auto-updating in Transifex. I removed the link and added again (more than a few times) and eventually it accepted the link and updated a few hours later. Once new translations come in, this should work properly.
