### ISSUE TITLE
Filter by incident status

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1821]
Filter by custom statuses instead of the normal "draft, published, archived".

**Comment by willdoran** [comment]
@Celestine22 What are the custom statuses to be?

**Comment by rjmackay** [comment]
> pending, open, in-progress, finished

is mentioned in the google sheet. I'll assume thats correct unless otherwise specified

**Comment by rjmackay** [comment]
Assuming this is a custom field, we can filter by passing a query param `values[key]=filtervalue`
Then we just need to add some custom UI specific to this client

**Comment by rjmackay** [comment]
Just tried adding this as a custom field + task... but that makes it editable by the user when they create the post. We might need to hack around that :/

**Comment by rjmackay** [comment]
Given the need to make status private, I'll look at making a change to make all tasks enables only by admins by default.

**Comment by rjmackay** [comment]
@Celestine22 there's a little potential for confusion between our current post 'status' (Published, Under Review, Archived) and the client's status as a custom field. Could you confirm if there's any relationship between which posts are visible to the public, and the posts status?
If there isn't a relationship, do they have any other plan around what will/will not be public?

Basically I'm trying to figure out if we need to keep the filters for publish/under review/archived at all. If we do we might have to tweak terminology to make it less confusing.

**Comment by Celestine22** [comment]
@rjmackay got it! I've asked the client about this! Awaiting feedback! My guess would visibility of posts to the public won't be affected by the posts status. Also we may have to remove some of our default filters to avoid that confusion/redundancy. 

@willdoran I've also asked for a confirmation on whether those are the custom statuses.

**Comment by jshorland** [comment]
These will go in filter box. Remove icons from the status. How they are displayed is detailed in #1825

**Comment by Celestine22** [comment]
@rjmackay visiblity of posts to the public will not be affected by the posts status! Custom status given by client today is (New, In Progress, Resolved) but he says he will confirm internally! Hope this helps!

**Comment by rjmackay** [comment]
This is deployed

**Comment by rjmackay** [comment]
- [ ] Check why filter box jumped
- [ ]  Test filtering actually works on demo site

**Comment by dalezak** [comment]
@rjmackay how was this implemented in the backend? Does the API return a list of available statuses which the mobile app can use?

**Comment by rjmackay** [comment]
See my comment here: https://github.com/ushahidi/platform/issues/1824#issuecomment-316852800

**Comment by rjmackay** [comment]
@dalezak Did this get implemented on mobile?

**Comment by rjmackay** [comment]
This issue was moved to ushahidi/platform-fix-our-environment#29
