### ISSUE TITLE
Editing of posts will be closed to users (you cannot go back and edit your post you submitted) and only available for admins

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1826]
This should be built as an option for platform. weee! configurable setting to not allow people to edit their own posts after submitting.

**Comment by rjmackay** [comment]
@justinscherer I'm thinking about *where* this setting should live. There are a couple of options:

1. In general settings as a simple toggle "Users can edit their own posts"
2. As a permission under Settings > Roles. We currently have various permissions for the default 'Member' role so we could add 'Edit own posts' as an option (enabled by default.
<img width="710" alt="screenshot 2017-07-10 13 21 01" src="https://user-images.githubusercontent.com/7965/27999572-c104d8f0-6572-11e7-9827-8034e44b60c0.png">

I think 2. is probably the most natural. Any contrary opinions?
