### ISSUE TITLE
Needs for reskinning mobile app

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1827]
Justin needs from client: icons (SVGs), Logomarks and wordmarks (svg), any relevant image content(might not go in, though), fonts in all weights, colour palette

ASAP

**Comment by justinscherer** [comment]
Copying over the elements from the slack channel:

Primary colour: #3696B4 
Secondary colour: #274F62 
Text colour: #373A3C 
Background: #FFFFFF 
Secondary background: #EFEFEF 

![icon.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593714fffc98e900201ba2a5/125516c66e82c728ace21e0d46e197952dc0cfeb9ffbb049a15ee4d6730472262d55f22f2380b52ebd142c525f094eac49595616fead9b37b4f46d2ede0356b49b381d66cc2f13aab2831bb608b827894e86b3b4824bd2a5.png)
![splash.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593714fffc98e900201ba2a5/125516c66e82c728ace21e0d46fb849622918bebc3abaf51ab57f5973d047d317c51a77a2181b02de9447957585c4efa41585745f5ab8b7fb4aa2e32db025fb28c341521842f1bbebb8315be05b329894887b7b8834dc1ec2f68.png)

**Comment by justinscherer** [comment]
![splash.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593714fffc98e900201ba2a5/125516c66e82c728ace21e0d46fb849622918bebc3abaf51ab57f5973d047d317c51a77a2181b02de9447957585c4efa41585745f5ab8b7fb4aa2e32db025fb28c341521842f1bbeba8415be05b329894887b4bf8d48c2ed2f68.png)

**Comment by justinscherer** [comment]
The splash image is too big to share here. You can view it here:

https://ushahidi.slack.com/files/justin/F64JWL3BR/splash.png

**Comment by justinscherer** [comment]
App name: Beatona

**Comment by justinscherer** [comment]
As far as I know, these are all the design elements @dalezak needs to get started on the dev work, so I'm moving it out of the design phase and into dev in progress.

**Comment by justinscherer** [comment]
cc @middle8media
