### ISSUE TITLE
email integrations reported to not be working again.

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1829]
I'm not sure what the problem is here, whether its documentation, the fact that it's just difficult to integrate, or if technically it's actually not working. Can we double check that data source jobs are running properly? I'm double checking on QA, but so far it's been 17 minutes and my email has not pulled through.

**Comment by jshorland** [comment]
Email still hasnt' pulled through

**Comment by rjmackay** [comment]
This should be resolved now. Downgrading and labelling for QA
