### ISSUE TITLE
Add ability to create member account on mobile app

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1830]
Will need to include email and phone number per Giscon requirements.

**Comment by justinscherer** [comment]
@Celestine22 @jshorland Am I to understand that we are still adding enrolment to the mobile client?

**Comment by justinscherer** [comment]
Enrolment and authentication flow. 

Need feedback from @dalezak
[GISCON Kuwait enrolment and authentication.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593714fffc98e900201ba2a5/125516c66e82c728ace21e0d46cfbda900adade9a4fca842ad49b0912754287f2401ad3f3084ed2cff436e15070a10e8180b0e00a5a6d739baa47c32d5065ebe957f5566c33845adb9d61cea07ec728d4886b6ea8a4cc8e93477e5df9d532c5c5446dda0006ceacc09da52e449e74754a01a3f61ef75357d40901d733e26.pdf)

**Comment by dalezak** [comment]
At initial glance, it looks good :+1:

**Comment by jshorland** [comment]
That’s correct. There should still be a sign up function, but not forced sign in to submit :-)

**Comment by dalezak** [comment]
Hey @justinscherer, looks like the API has `/api/v3/passwordreset` endpoint, which means I can implement password reset inside the app :+1:

**Comment by dalezak** [comment]
Hmm, although this long code will be tough / impossible to enter into the app 😯

![screenshot 2017-07-06 10 33 58](https://user-images.githubusercontent.com/91811/27921961-b3b31af2-6236-11e7-985d-7eac9e908f07.png)

**Comment by dalezak** [comment]
![simulator screen shot jul 6 2017 12 20 30 pm](https://user-images.githubusercontent.com/91811/27926751-ba68021c-6246-11e7-9636-ab0264926158.png)

**Comment by dalezak** [comment]
![simulator screen shot jul 6 2017 12 20 47 pm](https://user-images.githubusercontent.com/91811/27926761-c2ed4df2-6246-11e7-8c72-508abf70d327.png)
