### ISSUE TITLE
Reset password on mobile

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1831]
ability to reset password on mobile. Needs to trigger an email with reset token.

**Comment by justinscherer** [comment]
The easiest / best solution seems (to me) to be to trigger the web client password recovery flow in a native browser. @rjmackay @dalezak thoughts?

See for context:
[GISCON Kuwait enrolment and authentication.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593714fffc98e900201ba2a5/125516c66e82c728ace21e0d46cfbda900adade9a4fca842ad49b0912754287f2401ad3f3084ed2cff436e15070a10e8180b0e00a5a6d739baa47c32d5065ebe957f5566c33845adb9d61cea07ec728d4886b6ea8a4cc8e93477e5df9d532c5c5446dda0006ceacc09da52e449e74754a01a3f61ef75347b43941c743e26.pdf)

**Comment by dalezak** [comment]
Ya @justin, I think redirect to web client for password reset is a good idea, I'm not even sure whether the API (http://github.ushahidi.org/platform/docs/api/index.html) has a password reset option, does it @rjmackay?

**Comment by dalezak** [comment]
Good news @justinscherer, the API has  a`/api/v3/passwordreset` endpoint, which means I can send the password reset request from the app.

However the confirm code `bIrutYpfEVb5Ba7bMuLkcs5456o60rVz2+A1ZLrWgNg=` is pretty long to enter into the app, so maybe best from that point to confirm and enter the new password in the web app.

**Comment by dalezak** [comment]
![simulator screen shot jul 6 2017 12 09 32 pm](https://user-images.githubusercontent.com/91811/27925985-fcf6a104-6243-11e7-8089-d9c0946d9e35.png)
