### ISSUE TITLE
Grammar mistake in message

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1834]
### Expected behaviour
- You have reached the survey limit for your plan.
### Actual behaviour
- You have reached the surveys limit for your plan.
### Steps to reproduce the behaviour/error
- When trying to add additional surveys Mapper users are told they have reached their "surveys" limits should be "survey" limit based

**Comment by jshorland** [comment]
I'm so annoyed by this. upping to p1.

**Comment by rowasc** [comment]
This no longer exists. Closing
