### ISSUE TITLE
Search location in Posts gives unstable responses

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1835]
### Expected behaviour
- Stable consistent results for text being entered
### Actual behaviour
- When entering an address the initial results are not consistent with results when typing and searching based on results displayed
### Steps to reproduce the behaviour/error
- Attempt to search for postal code 'H2V2K8'
- No results will be returned
- When typing H 2 V 2 K 8 the results returned will be very inconsistent depending on which letter you get to this may be to do with the way the text string is interpreted but we should check.

Part of this inconsistency may be to do with there being no spinner saying that a search is happening. But the results are still off.

<img width="594" alt="screen shot 2017-06-28 at 15 25 45" src="https://user-images.githubusercontent.com/2694405/27656269-5229ddaa-5c16-11e7-8431-3572a9d8e302.png">

<img width="585" alt="screen shot 2017-06-28 at 15 26 08" src="https://user-images.githubusercontent.com/2694405/27656275-5a544344-5c16-11e7-92cc-524309010d73.png">

<img width="603" alt="screen shot 2017-06-28 at 15 26 29" src="https://user-images.githubusercontent.com/2694405/27656284-64e0e01a-5c16-11e7-8947-e823b8ea6706.png">

<img width="594" alt="screen shot 2017-06-28 at 15 26 41" src="https://user-images.githubusercontent.com/2694405/27656289-6a4aed52-5c16-11e7-86ba-cc7f1446e0c7.png">

<img width="596" alt="screen shot 2017-06-28 at 15 26 56" src="https://user-images.githubusercontent.com/2694405/27656299-755ecfba-5c16-11e7-89a3-96a568bf2c3f.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-590

**Comment by Erioldoesdesign** [comment]
Flagging that the folks working on https://keralarescuemap.ushahidi.io/views/map are experiencing trouble with this issue now. Here's some info on what they are experiencing:

> For instance, this is what I get when I search for NIT Calicut which is a major landmark.....
The suggestions are completely irrelevant.

![image](https://user-images.githubusercontent.com/11681324/62860087-fdf24300-bcf6-11e9-9f72-f5b9c6bc2e1f.png)

> These are the suggestions shown for Kochi....As you can see, I have places suggested from Japan 

![image](https://user-images.githubusercontent.com/11681324/62860053-e9ae4600-bcf6-11e9-8531-1feb5b4a824b.png)

They suggest the solution: Suggestions based on an IP lookup should do the trick, if possible

**Comment by kromcuich** [comment]
Confirming the bug present in a public (free) deployment. Address look up is not working in Montreal https://r2r.ushahidi.io 

'use my location' is not accurate for obvious reasons

any suggestions?

**Comment by willdoran** [comment]
I wrote this ticket several years ago. At the time, the design was intended to support Postal Codes as well as places, names, addresses and lat/long. 

The Nominatim free service doesn't support those so it might be worth closing this as no longer relevant.

@kromcuich what address format were you searching for and not able to get results for?

**Comment by willdoran** [comment]
Turns out OSM just doesn't support Canada as a place that has postal codes :D

https://github.com/osm-search/Nominatim/issues/1452

**Comment by rowasc** [comment]
Bumping as Community Task in case someone has the bandwith. It may be that we need to add new providers to solve for this? It seems to be a nominatim issue, so I think a decent course of action may be to have other providers to fill in gaps. This is needed for several reasons in any case, not all providers have all the data. 

https://github.com/ushahidi/platform/issues/3927 David started this issue a couple weeks back to explore using the mapbox geocoder, so tagging as related. 
Thanks @willdoran and @kromcuich
