### ISSUE TITLE
Search location has no working spinner

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1836]
### Expected behaviour
- When searching I expect to hit search before the search takes places
- If the search is live as I type, I expect to see some kind of spinner comfort noise when the search is happening
### Actual behaviour
- When I type search is done live but this is not communicated, thus when the results change because there is a lag in the search it is confusing for the user.

### Steps to reproduce the behaviour/error
- Try to use the search bar by typing

**Comment by ryanchristo** [comment]
@willdoran Would something like this work?

![](http://recordit.co/afxTnu54Ly.gif)

I also added a timeout function in the above example to prevent excessive calls to the api while the user is still typing, therefore only searching for the latest search text a quarter of a second after the keydown event, which still gives it the feel of live loading without getting hung up on other calls.

Let me know if this is what you have in mind. It will conflict with ushahidi/platform-client#684 but it should be easy to integrate if the request is approved.

**Comment by willdoran** [comment]
@ryanchristo thanks very much! I'll review the PR but it looks good.

**Comment by rjmackay** [comment]
@ryanchristo could you update to use the loading button shown here: http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/2_fragments/

**Comment by ryanchristo** [comment]
@rjmackay Updated. I'm not sure when the user would use the "Search" button if the search results are updated when the user types. I noticed the button was not included in [the layout preview](http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/post-add.html#0). I also noticed the icons next to search results were missing and added them in.

Here is what it looks like with the updated branch:

![](http://recordit.co/KUBCYMfomj.gif)

**Comment by rjmackay** [comment]
You're right, the search button doesn't really make sense! I'm not sure what other loading styles we have that'd make sense. You could try using the bouncing loader below 'Search results' and hide it entirely once done? If you want to experiment I'm happy to take suggestions, otherwise your updated version is still an improvement on what we already had so we could land it as is.

**Comment by ryanchristo** [comment]
What about something like this? The loading button would require some additional styling changes but the below example is a simple change to the template. Also, I think the loading button seems a bit strange showing up when not having been a button before.

![](http://recordit.co/dNezM4eHnV.gif)

**Comment by rjmackay** [comment]
That looks perfect. Thanks!
