### ISSUE TITLE
“Sorry, something went wrong. Try reloading the page.” on client

### ISSUE THREAD

**Issue by Offliner21** [ushahidi/platform#1837]
### Expected behaviour

The API should show the Map running already

### Actual behaviour
“Sorry, something went wrong. Try reloading the page.” on client
Hello, I've been having this issue fo days now.
I am running the API and the client on different domains as you see below.
I am running the API on my local machine.

![apiconf](https://user-images.githubusercontent.com/6979276/27656950-f53b2932-5c42-11e7-890b-ec51b74891bb.png)

![clientconf](https://user-images.githubusercontent.com/6979276/27656951-f541ea38-5c42-11e7-9722-005830e565cb.png)

Can anyone help me, please?

**Comment by tuxpiper** [comment]
Hi, we would like to test it out... but http://harrasrevealer.com gives DNS resolution error .

Are all the involved hostnames known to the device where the browser for your tests is running?

**Comment by rjmackay** [comment]
I'm going to close this, but if you have more info feel free to reopen it @offliner21
