### ISSUE TITLE
CSV import duplicated some of my posts

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1843]
### Expected behaviour
I am importing this data: https://docs.google.com/spreadsheets/d/17KqUg5eIEMhfppEI3ZsRqWN87-ofaMgME7D_o2sytSU/edit#gid=0 into deploymentswithlocations.ushahidi.io Should map to 1106 posts. 

Actual behavior
I broke it up into 11 different sheets with ~100 rows and downloaded each sheet as a separate CSV and imported them. My total number of posts is 1316 according to the platform, but the total number of rows in the file is 1106 (not including headers). 

I *think* what might have happened is that when I ran into an error on two of the sheets, it stopped importing, but kept the rows it had already imported and turned them into posts instead of getting rid of those?

### Steps to reproduce the behaviour/error
Download the CSV file of all data and you can find the duplicates by selecting the entire row for "title", selecting "conditional formatting" and highlight duplicates.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-588

**Comment by tuxpiper** [comment]
I think the theory is right, it most probably kept the posts you uploaded the first time.

my 2c:
I'm not sure they should have been deleted though, one could argue that it's a desirable behaviour to keep the rows that successfully imported, despite other failures.

I'm also remembering now that rows imported during a CSV import job are kept in a collection, which makes it easy to delete all of them if so desired.
