### ISSUE TITLE
Categorization of posts from Facebook

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1844]
Open question, not sure how we'll tackle this.

As it stands now, we have different surveys to collect data on different themes e.g voter issues, security issues etc.

Assume we received a post from the Facebook bot, that belong to one of these other surveys, how do we reassign a post from FB to the correct survey?

Is there a way we could force the user to select a survey to submit to from the bot?

**Comment by jshorland** [comment]
@Angamanga @charlie the user currently selects a survey, correct?

**Comment by willdoran** [comment]
@Angamanga could we do the following:

- User selects survey and we store that survey id
- User fills in information the same as now, title, description, image
- When we save the details to the survey we choose the form based on the survey the user selected in the first step?

**Comment by Angamanga** [comment]
@jshorland No, right now it goes to a specific survey. After discussing with @aoduor I am trying to add survey-selection in the bot. It will look something like this:

![screen shot 2017-07-31 at 10 01 43](https://user-images.githubusercontent.com/8624777/28768321-7593fc1e-75d7-11e7-9218-4964cb859666.png)

@justinscherer What do you think about this? I have combined two lists above each other. The choose-button is ugly but is required (possible to change the text in it though). When would be the appropriate point in the flow to add this list? Right before sending the reply?

**Comment by justinscherer** [comment]
It probably makes the most sense at the beginning of the flow. 

BOT: "What kind of issue would you like to report?"
BOT: "<list of survey options>"
USER: <chooses a CTA>
BOT: Great, thanks! <continues with the normal reporting flow...>

By my count there are 7 surveys currently in the Uchaguzi deployment:
- counting and results
- polling station administration
- positive events
- security issues
- voting issues
- staffing issues
- other

This means it would be 3 separate messages...which even if it looked better is not ideal...

It would also help if we had explicit, descriptive sub headings for each CTA so the user knows what we mean by each category.

Does this answer your question @Angamanga
