### ISSUE TITLE
Language drop down option to only show English and Arabic.

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#1845]
### Expected behaviour
When a user click on the language tab, it should give the option of switching between only these 2 languages

**Comment by rjmackay** [comment]
@Celestine22 Given this was an additional request, not originally spec'd, could we move this to one of the later phases?

@jshorland do you think the ability to 'enable' specific languages in a deployment would be useful to all deployers? ie. in core?

**Comment by Celestine22** [comment]
@rjmackay sure? Phase 3 it is!

**Comment by rjmackay** [comment]
For this deployment I'd suggest we just hard code this. Modify the language switcher in the client and filter to just arabic and english, this will not be configurable by a deployment admin

**Comment by rjmackay** [comment]
@dalezak is this a customization for mobile too? How are you deciding which languages are shown in the switcher right now?

**Comment by dalezak** [comment]
Good question! The main Ushahidi app will include all the languages, currently has English, Spanish, French, German, Portuguese, Dutch, etc but will expand to include the same set as web app.

For for whitelabel apps, there is an optional property to specify a sub-set of the languages, so the whitelabel can include shorter list of languages.

**Comment by rjmackay** [comment]
It just occurs to me, I could make this a build-time parameter for the web client too. That way while its not available for .io deployments, it'll be easily available to future custom deploys

**Comment by dalezak** [comment]
If the API returned that data, then the app could use it as well, since the first time the whitelabel app launches, it downloads the deployment config.

**Comment by dalezak** [comment]
FYI, the mobile app has a `appLanguages` whitelabel config variable which lets you specify a subset of the available languages, so the app will only show English and Arabic as language options.

**Comment by rjmackay** [comment]
Doing much the same thing for client, adding an APP_LANGUAGES option to the .env

**Comment by rjmackay** [comment]
English is listed twice!?
