### ISSUE TITLE
The toggle button is unresponsive

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#1846]
### Expected behaviour
The toggle button should switch from green to grey

<img width="900" alt="screen shot 2017-07-03 at 3 43 39 pm" src="https://user-images.githubusercontent.com/8900438/27832224-a3457306-60d6-11e7-9f33-dd7cde8d1a21.png">
### Actual behaviour
This button is stuck at green making this task viewable as a public task. The tasks that posts go through should in a deployment should have the option of being viewed or not viewed in public when published.
Deployment link: https://sfcgguineaewer.ushahidi.io/

**Comment by jshorland** [comment]
Changing this to p0
