### ISSUE TITLE
Tasks should only be editable (and visible when incomplete) by admins/users with manage posts permission

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1848]
### Expected behaviour
When I'm visiting a deployment to submit a survey response, I want to see only the information I'm meant to submit. As a deployment admin/manager, I've created tasks as an internal workflow for my team to triage incoming posts. It's meant to be used internally, and the information MIGHT be displayed to everyone once its complete (or maybe its meant for internal use only). Point is, there's no need for everyone to be able to see the incomplete task. 

### Actual behaviour
I see all these weird sections below the survey form. Do I fill them out? Why are they there? I DON'T UNDERSTAND!

For now, we should implement this for Lovomar deal, and then put back into platform.

**Comment by rjmackay** [comment]
I think this might actually have been a bug. It seems we're currently toggling the visibility of tasks data entry, based on the `Show this task to everyone when published` setting, but its pretty clear that was only meant to effect final visibility when published.

**Comment by rjmackay** [comment]
Tech changes:
- When returning stages - as a normal user - we currently filter out stages without `show_when_published`.
    - This is fine, though should filter down to attributes too.
    - This should also be enforced in the Authorizer, not the repo.
- The client needs to hide all tasks if we don't have manage posts permission
- API needs to reject attribute values for tasks if we don't have manage posts permissions

**Comment by rjmackay** [comment]
@dale so far I've just hidden all tasks from users without 'Manage Posts' permission when creating/editing a post.
I haven't updated the API to reject values for those tasks yet though. I need to sync with Jess when she's back online as its possible this might need to be optional so we can account for existing deployments where tasks are currently visible

**Comment by rjmackay** [comment]
@jshorland as mentioned in Slack. I'm happy to hide these from non-admin users... *but* I'm concerned about how this impacts existing deployments. ie. if they already have tasks they expect normal users to fill in and then we hide them, thats not great

We need to check if many users are using tasks already before this goes into production

**Comment by jshorland** [comment]
Removing uchaguzi tag since it's done there

**Comment by jshorland** [comment]
We added this as a setting. closing.
