### ISSUE TITLE
Re-skinning web app

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1851]

**Comment by justinscherer** [comment]
@jshorland @Celestine22 

Can we have a due date for the re-skinned / forked pattern library for the web client?

**Comment by middle8media** [comment]
I had a chat with @justinscherer. I am up to speed and bringing this to the front burner.

**Comment by jshorland** [comment]
July 18 delivered to Celestine for QA

**Comment by rjmackay** [comment]
@jshorland this should be in Phase 3 if delivery is July 18th right?

**Comment by middle8media** [comment]
I have pushed customizations to the PL [here](https://github.com/ushahidi/platform-pattern-library-fix-our-environment) and I can iterate as needed.

**Comment by middle8media** [comment]
The GISCONkuwait PL is updated [here](https://github.com/ushahidi/platform-pattern-library-fix-our-environment) and reflects custom colors, custom survey icons, custom post status and custom favicon.
