### ISSUE TITLE
Add PATCH to Platform

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1852]
### Expected behaviour
- It is possible to partially update entities via the platform API
- The client API handler service supports PATCH (knows how to send it and handle the response)
- This is done following a known standard that we can refer to (we don't reinvent a patch strategy 😄  ) 
### Actual behaviour
- PATCH is not currently available
### Steps to reproduce the behaviour/error

Aha! Link: https://ushahiditeam.aha.io/features/PROD-587

**Comment by rjmackay** [comment]
@willdoran I'm not clear if this was *required* for Comrades or just nice to have?

**Comment by caharding** [comment]
@willdoran Shadrock and I are confused about what this means. Can you please clarify and let us know if we need to keep it.

**Comment by caharding** [comment]
This should be covered by Lumen branch
