### ISSUE TITLE
Organising data downloaded from different surveys on separate tabs in CSV file

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1857]
As someone looking to analyze data from the Uchaguzi platform, it would be useful if the CSV File has data organized by surveys on separate tabs on the downloaded file.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-586

**Comment by rjmackay** [comment]
CSV's are not excel. CSV's don't have tabs... they're a single flat file of data. The only way to do this would be to download a file per CSV.

The only way to resolve this would be to completely reimplement the export to export to .xls instead.

**Comment by rowasc** [comment]
Since we can't do tabs with CSV, but we now have a way to filter out by survey , I think we probably should close this . 
Tagging @aoduor in case you want to keep it as a different feature (ie maybe having an export to  excel  or export to google sheets feature would work)

**Comment by Erioldoesdesign** [comment]
Hmm is there a way that HDX could help this?

Does Ushahidi Survey CSV -> HDX ->XLS tabbed? Does HDX do XLS?

**Comment by rowasc** [comment]
HDX supports XLS https://data.humdata.org/dataset/afghanistan-natural-disaster-incidents-in-2019 , for instance this has an excel file... but it's *us* generating an XLS and sending it to them (the same way we send them a CSV) , they don't create the excel file for us.

So we would have to support creating excel files with tabs, or google sheets with tabs, and then yea you could link it in other tools like HDX if they support it too .

**Comment by Erioldoesdesign** [comment]
Ahh I understand. No worries. Worth putting waaaaaaay on the back burner then.
