### ISSUE TITLE
UX: Positioning of the submit button

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1858]
Feedback we got from trainees was that it was not intuitive to have the submit button at the top right corner of the post submission page. 

Most users expected to find the button at the end of the long submission page. 

<img width="1604" alt="Screen Shot 2019-06-09 at 20 17 02" src="https://user-images.githubusercontent.com/2434401/59165529-aadff200-8af3-11e9-9bad-6be816a7c5ea.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-585

**Comment by justinscherer** [comment]
Can we mirror the edit mode in the data view and have a submit bar at the bottom as well as the top? 

Example:

![can edit selected log open copy 2](https://user-images.githubusercontent.com/29209303/32299620-d9e4bca2-bf1b-11e7-90c1-c35f3322bebd.png)

**Comment by Sunairaa** [comment]
Hey @Angamanga i am an outreachy candidate can i work on this issue?

**Comment by mariehposa** [comment]
Hi @Angamanga, can I work on this?

**Comment by rowasc** [comment]
@Sunairaa please go ahead.

**Comment by Sunairaa** [comment]
> @Sunairaa please go ahead. 
> 

Thanks for assigning me this task.

**Comment by Sunairaa** [comment]
Hello @rowasc and @Angamanga I have done with this task can you please review my PRs: https://github.com/ushahidi/platform-client/pull/1594 and https://github.com/ushahidi/platform-pattern-library/pull/251
