### ISSUE TITLE
Related post field not working

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1860]
### Expected behaviour
Clicking on search should either 
* Yield results OR
* Prompt me if there are no results based on my search

### Actual behaviour
the search button on the related post field is non responsive, and i don't get any results.

### Steps to reproduce the behaviour/error
* Log into your deployment
* Add a related post field to your survey
* Attempt to submit a post and search for a related post

**Comment by ryanchristo** [comment]
@aoduor It looks like the search button is working but there is no indication that no results were found. Should the error message read and look like the following?

![](http://recordit.co/yUvb4Iyijs.gif)

**Comment by aoduor** [comment]
Oh my, Ryan you're on a roll. YES. This is exactly what we need. 

Handheld Sent,

Angela Oduor Lungati,
Director of Community Engagement,
Ushahidi | www.ushahidi.com

**Comment by ryanchristo** [comment]
Another option for the searching indictor would be the following:

![](http://recordit.co/JkIdILuqOf.gif)

Let me know if this would be the preferred look and I can update the pull request.

**Comment by ryanchristo** [comment]
Another option that would be consistent with the current resolution for ushahidi/platform#1836:

![](http://recordit.co/SbJic0dQir.gif)

**Comment by rjmackay** [comment]
@ryanchristo could you update this to use the bouncing loading button shown here: http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/2_fragments/

**Comment by ryanchristo** [comment]
@rjmackay I ran into an issue with the loading button and the `input-inline` class:

![](http://recordit.co/0lYjaoXoIV.gif)

We could decrease the width of the `input-inline` class in the pattern library, but this would also affect the input for adding options to "Select", "Radio Buttons" and "Checkboxes":

<img width="411" alt="screen shot 2017-07-28 at 2 02 53 pm" src="https://user-images.githubusercontent.com/12519942/28706300-e8c75db6-739d-11e7-90f3-e7423ddafd37.png">

Any other ideas? Let me know if updating the `input-inline` class in the pattern library would be the best option and I can submit a pull request.

**Comment by rjmackay** [comment]
Would it make sense to completely drop the 'Search' label while loading? ie. just show the bouncing dots. Does that solve the size issues?

**Comment by ryanchristo** [comment]
Removing the text and leaving the bouncing dots would work. I also played around with [flexbox](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox) and was able to achieve the following results:

![](http://recordit.co/ZCuE8Rq2DK.gif)

<img width="457" alt="screen shot 2017-07-29 at 12 31 05 pm" src="https://user-images.githubusercontent.com/12519942/28742423-09f1ae62-745a-11e7-8e3f-badf4f334e78.png">

**Comment by ryanchristo** [comment]
I submitted a pull request with the added flex attributes to the `inline-input` class for review. I think removing the text and leaving the bouncing dots would be the best solution otherwise.

**Comment by Celestine22** [comment]
@rjmackay this looks good as below
<img width="626" alt="screen shot 2017-08-07 at 2 08 01 pm" src="https://user-images.githubusercontent.com/8900438/29024254-df46f25e-7b79-11e7-9eed-e728712cf6af.png">
however when there's no related search it doesn't prompt me that there are no results based on my search

**Comment by rjmackay** [comment]
@Celestine22 that looks like the previous code. Could you clear cache and retest? or you might have just caught it before I deployed.
It should look like the video above.

**Comment by Celestine22** [comment]
@rjmackay Actually just done all the above, but it doesn't prompt when their is no related search.

**Comment by jshorland** [comment]
This passes QA for me. SEe below.
[Uploading Screen Shot 2017-08-07 at 1.28.50 PM.png...]

**Comment by jshorland** [comment]
<img width="1308" alt="screen shot 2017-08-07 at 1 28 50 pm" src="https://user-images.githubusercontent.com/3224856/29044546-cca96442-7b74-11e7-9f64-513c1c3cbd71.png">
