### ISSUE TITLE
Display posts by source

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1861]
It would be helpful, to be able to filter posts by their source e.g via web, via sms, via email, via twitter.

Feasibility of adding this to the search filter?

**Comment by willdoran** [comment]
@rjmackay might be able to get this in but it's relatively unlikely

**Comment by rjmackay** [comment]
Should be fairly easy actually - we already have source from the messages table. Through frustratingly no easy way to expand to 'facebook' as a source.

**Comment by Angamanga** [comment]
This was done for Uchaguzi. Opening issue again to integrate into platform-core too.

**Comment by Angamanga** [comment]
@rjmackay Would this be a good time to add this pattern to the platform as well: 
![screen shot 2017-08-31 at 16 30 41](https://user-images.githubusercontent.com/8624777/29928674-c80259b4-8e69-11e7-86aa-312e94c65b92.png)

**Comment by jshorland** [comment]
YES!

**Comment by rjmackay** [comment]
@Angamanga yes. That'd make far more sense. Theres another issue for that #1646 
We should also only show the filter for a data source thats actually enabled.

**Comment by Angamanga** [comment]
@rjmackay This one is also related: https://github.com/ushahidi/platform/issues/1254 I'll look into it tomorrow.

**Comment by Angamanga** [comment]
OK, so a summary of the task:
1. Datasources displayed in the filter and mode-context-bar should only be the ones enabled in the deployment (related to #1254)
2. Nb of posts for each datasource should be displayed in the mode-context-bar in accordance with the styles in the pattern-library

@rjmackay @jshorland  A question, should we still keep the checkboxes for data-sources in the filter-modal like above? Or is this not necessary when they are visible in the mode-context-bar? We removed the categories-filter from the filter-modal when we added them to the survey-filter. I think it makes most sense to only show filtering of the datasources in the mode-context-bar.

**Comment by rjmackay** [comment]
I'd go for just putting it in the mode-context bar to start with. If its easy, keep it in the modal too.

#2035 will have us bringing all the filters into the modal anyway.

**Comment by Angamanga** [comment]
@middle8media In the data-source filter in the modecontext-bar 
![screen shot 2017-08-31 at 16 30 41](https://user-images.githubusercontent.com/8624777/29928674-c80259b4-8e69-11e7-86aa-312e94c65b92.png)
I am wondering how to handle the different sources of sms? Do we want group them together as just 'sms' or do we want to add them as the exact source-name?

**Comment by middle8media** [comment]
@Angamanga this may be a specific dev team question but my instinct says to separate them into their exact source name.

**Comment by rjmackay** [comment]
Hrm. I think most users are likely to just expect to see all SMS in 1 place, and only have a single SMS source at a time. So I'd split them Twitter, SMS, Email, Web.
