### ISSUE TITLE
Locking reports actively being worked on by others

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1863]
This was a question/request from volunteers.

Could we add the ability to lock a post while it's actively being edited by someone else on the team?

PS: It's one of those features we've received requests for from as far as 2013.

**Comment by aoduor** [comment]
Realized this is a dupe of #1936. Will close this in favor of it and add this for more context.

**Comment by jshorland** [comment]
Want to make sure this gets back into core
