### ISSUE TITLE
favicon for GISCON Kuwait web client

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1866]
add a favicon for the GISCON Kuwait web client

**Comment by justinscherer** [comment]
asset here:
![favicon.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593714fffc98e900201ba2a5/125516c66e82c728ace21e0d46ee958c2a818ca7cda5fd53b652fa912a5265296b51f62f21d4e77bba147d0359584dac17585f4cfdf0db29f2a42062c80d55b98e30063e937f03a6aa811eb500be29824682b0b5884bc6e83937aa.png)

**Comment by middle8media** [comment]
done, will push later today.

**Comment by rjmackay** [comment]
Need to update the web client to pull this in
