### ISSUE TITLE
Rename plan levels

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1870]
Find industry-standard names for our pricing tiers and remove ambiguity i pricing model:

e.g. "Free", "Premium", "Enterprise"

TO DO:
- [ ] Change pricing plan page on website to  Mapper->"Free", Responer->"Premium", and >"Enterprise"
- [ ] Change pricing plan page on signup to  Mapper->"Free", Responer->"Premium", and >"Enterprise"
- [ ] Change pricing plan page in settings to  Mapper->"Free", Responer->"Premium", and >"Enterprise"

**Comment by caharding** [comment]
I scoped this out. @jshorland I'll leave to you to assign and prioritize.

**Comment by jrtricafort** [comment]
Closing this issue. This will be replaced by this epic:
https://github.com/ushahidi/platform-cloud-interface/issues/319
