### ISSUE TITLE
Deployment cover  changes through the lifecycle of a deployment

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1877]
A deployment's cover page should change state before it is active, while it is active, and after it has ceased to be active.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-575

**Comment by rowasc** [comment]
What's a deployment's cover page? I don't understand this ticket
@Erioldoesdesign any idea what this was about?

**Comment by Erioldoesdesign** [comment]
@rowasc I have a feeling this is about the dashboard piece of work that never ended up getting merged in? Carolyn and @Angamanga worked on the dashboard

**Comment by rowasc** [comment]
aaaaaah yes that would make total sense.  Tagged ! thanks @Erioldoesdesign
