### ISSUE TITLE
parent/child categoreis

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1879]
Replace the parent/child categories model we have with a less ambiguous less over-engineered solution.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-573

**Comment by rjmackay** [comment]
@jshorland @justinscherer I'd argue this should happen sooner rather than later. The current survey->parent category->child category model is confusing for devs working on it, and assume moreso for the users.

**Comment by justinscherer** [comment]
@rjmackay I'm with you on this one. @jshorland and I are going to discuss spec'ing this as part of the 2chaguzi updates.

**Comment by rjmackay** [comment]
FYI there's also #2007 for a summary of other categories issues. They're mostly minor and just addressing inconsistencies in how we handle categories even within the current model
