### ISSUE TITLE
Double input passwords

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1880]
Users should have to input passwords twice during onboarding to reduce the risk of users making typos during password creation.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-572

**Comment by Angamanga** [comment]
@codifyit check out this issue instead!

**Comment by codifyit** [comment]
Sure!

**Comment by rowasc** [comment]
@codifyit assigned!

**Comment by codifyit** [comment]
Hi@rowasc I have veen looking at the code of platform-client but I can't seem to locate the relevant piece of code. Can you please point me in the right direction?
I am looking to understand the code

**Comment by codifyit** [comment]
Hey @rowasc ok that makes sense! I felt so lost , lol. Sure, let me check it out
