### ISSUE TITLE
tappable/clickable items should appear tappable without a hover state

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1883]
Currently, editable fields and tappable links do not appear as if a user can interact with them. This is a major usability/accessibility issue.

**Comment by justinscherer** [comment]
![Screen Shot 2017-07-14 at 2.30.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593714fffc98e900201ba2a5/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f76b7191a37af1112b4f5b575ecc3c4a4356bcbbd671f3e57862804e0ee8856c5e20c56817faea8418bc01ec208b4784bfee8818d2f42f67b6d5db1063474f4dcbed5727a29f41c95df64be14b51a615366be2712431.png)

**Comment by rowasc** [comment]
Closing as duplicate https://github.com/ushahidi/platform/issues/2379
