### ISSUE TITLE
label all icons

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1884]
Anything other than really old, standard icons (e.g. "+" for add, hamburger menus, "x" for close, etc. ) need to have labels or refactored to be buttons or text links.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-57

**Comment by rowasc** [comment]
#4028 linking it to this as well

**Comment by vanessa-ariel** [comment]
Hello @Angamanga , can I work on this issue? I am an outreachy applicant (:

**Comment by Angamanga** [comment]
@vanessa-ariel This one needs designs before its ready to work on, please check here for other issues: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22
