### ISSUE TITLE
undo/redo pattern

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1886]
At a bare minimum, every time a user submits new information to the system, a consistent undo affordance (e.g. regret bar from Material Design) should be present.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-568

**Comment by rjmackay** [comment]
Not sure why this ended in In Development already. This needs to tech speccing love.

**Comment by Angamanga** [comment]
@sorry, the commits above is me writing the wrong issue-nb! No development here yet.
