### ISSUE TITLE
label support and give it a better icon

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1890]
label support and give it a better icon 

related to issue ushahidi/platform#1884

icon does not represent support, but rather ushahidi in general, this increases the ambiguity of the CTA.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-564

**Comment by rowasc** [comment]
Need to decide icon and then this would be a nice first-time-issue
cc  @Angamanga

**Comment by rowasc** [comment]
@Erioldoesdesign do you have an icon in mind for support?  
<img width="215" alt="Screen Shot 2019-09-20 at 00 13 24" src="https://user-images.githubusercontent.com/2434401/65296650-7c82a180-db3b-11e9-9c76-b0ae1adfbcbf.png">
