### ISSUE TITLE
Deployment "cover page" or "overview screen"

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1894]
As a Deployer I want to create and configure a splash page for my deployment in under 5 minutes so that I can effectively communicate the "pitch" of my deployment to stakeholders.

See relevant feedback here https://github.com/ushahidi/platform/issues/1723 
Related (duplicate?) issue here https://github.com/ushahidi/platform/issues/1575

Aha! Link: https://ushahiditeam.aha.io/features/PROD-560

**Comment by jshorland** [comment]
@justinscherer I'll leave it to you whether you'd like to use #1575 or this issue. Please close whichever one you don't want to use.

**Comment by jshorland** [comment]
This may be relevant to ceasefire deal
