### ISSUE TITLE
Bot sends direct URL link instead of bubbles

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1906]
Replace link to deployment with a Chat Bubble link

![screenshot 2017-07-14 18 43 28](https://user-images.githubusercontent.com/1618793/28235527-6b1f5aa0-68c4-11e7-846a-f111af7e43c6.png)

**Comment by Angamanga** [comment]
Fixed in https://github.com/ushahidi/platform-facebook-bot/issues/4
