### ISSUE TITLE
Bot does not encourage feedback.

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1907]
Allow a user to send feedback which the Uchaguzi team can respond to 
![screenshot 2017-07-14 18 44 28](https://user-images.githubusercontent.com/1618793/28235536-847c7a82-68c4-11e7-9967-2d88c0efd4b0.png)

**Comment by Angamanga** [comment]
@caharding @justinscherer Not sure if I understand the issue here? Feedback on what? The bot? Uchaguzi?

**Comment by justinscherer** [comment]
@Angamanga both, I think is the intention here. It's not a bad idea.

What do you think of adding a persistent menu option: "Leave feedback" which triggers a message: "How can we make your experience of Uchaguzi better?"
and then we can send the response to a repository of feedback somewhere?

@jshorland @aoduor any ideas about a useful place for that repository?

After they respond we say: 

"Thanks so much for your feedback. We sent it to the team."

"What do you want to do next? 
<cta>Leave more feedback</cta>
<cta>Submit a new report</cta>
