### ISSUE TITLE
Bot does not have at least 3 distinct and alternating failure messages.

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1908]
Rotate the failure message between these 3 texts:

1. "I am sorry, I didn't understand that."
2. "Sorry, I'm just a bot built for reporting, so my vocabulary is pretty limited."
3. "Oh my, I'm not programmed to understand what you're saying. Sorry!"

![screenshot 2017-07-14 18 46 25](https://user-images.githubusercontent.com/1618793/28235563-341b53f0-68c5-11e7-94cb-3ba12407fc68.png)

**Comment by Angamanga** [comment]
Fixed in https://github.com/ushahidi/platform-facebook-bot/issues/4
