### ISSUE TITLE
Bot does not have minimum personality.

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1909]
Suggested replies:

- What's your name: "I'm the Uchaguzi reporting bot. Ready to get started?"
- How old are you: "I'm not that old, so I can only do a few things. Ready to get started reporting?"
- What can you do: "I can help you report what you see during the Kenyan election. Ready to get started?"

![screenshot 2017-07-14 18 50 31](https://user-images.githubusercontent.com/1618793/28235571-57b7d338-68c5-11e7-95f1-e524df8c117d.png)

**Comment by Angamanga** [comment]
Fixed in https://github.com/ushahidi/platform-facebook-bot/issues/4
