### ISSUE TITLE
Bot does not use Share buttons in conversation or web view

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1912]
Use Share Button in both conversation and web view
![screenshot 2017-07-14 18 58 48](https://user-images.githubusercontent.com/1618793/28235618-852e3914-68c6-11e7-91ef-4925189500de.png)

**Comment by Angamanga** [comment]
@justinscherer I am adding a share-button but need content that will be displayed in the  messenger-window of the user that the bot is shared to. It has to be a 'generic template' (https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template) with an image_url and text. Do you have any suggestions? I am thinking of using the Uchaguzi-logo but need help with a catchy text. One for when the user has reported and one for just the bot itself...

**Comment by justinscherer** [comment]
Uchaguzi logo will work for the image. 

For share text:
<h1>Uchaguzi</h1>
<p>Helping Kenya have a free, fair, peaceful and credible general election</p>

For the person who sent the share: "Nice job! What do you want to do next?" (and then show the same options as we show after they post a report.)

@Nthiga @aoduor ^^ does this share text sound right?

**Comment by Angamanga** [comment]
@justinscherer This is what the actual userflow will look like when sharing, right now I have only added it to after a user has posted a report:

**When user has submitted a post:**
![img_1836](https://user-images.githubusercontent.com/8624777/28620100-cec9c93c-720b-11e7-9922-31f4242c7ba1.PNG)


**When user is taken to the share-screen:**
![img_1837](https://user-images.githubusercontent.com/8624777/28620104-d0935c06-720b-11e7-98ff-de6a753919f7.PNG)


**What it looks like for the user who got the share:**
![shared](https://user-images.githubusercontent.com/8624777/28620222-4ffdb4aa-720c-11e7-9045-6bdc74606951.png)

**Comment by Angamanga** [comment]
@justinscherer @willdoran Another question, I need a link to the logo, right now when I tested I used a logo-link from GitHub, do we have any repo to put logos like this to be able to host/use them? I am thinking about the pattern-library but that isn't that more general for the platform?

**Comment by justinscherer** [comment]
Looks good @Angamanga 

Logos you can find here:
/Dropbox (Ushahidi)/Design/Logos

**Comment by Angamanga** [comment]
Fixed in https://github.com/ushahidi/platform-facebook-bot/issues/4
