### ISSUE TITLE
Instructions are not visible for title and description attributes

### ISSUE THREAD

**Issue by ryanchristo** [ushahidi/platform#1917]
### Expected behaviour
- When I add instructions to the `title` and `description` attributes, I see the instructions in the post form when I am creating or editing a post.

### Actual behaviour
- When I add instructions to the `title` and `description` attributes, I do not see the instructions in the post form when I am creating or editing a post.

### Steps to reproduce the behaviour/error
1. create or edit a survey
2. edit `title` or `description` attribute
3. toggle `Show field description option`
4. add instructions and save the survey
5. create or edit a post for the survey

**Comment by aoduor** [comment]
How soon do we expect this up :)? Have the same issue on Uchaguzi
