### ISSUE TITLE
Translate categories

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1922]
-  Add a translations table the backend to store the translated text
- Accept and return translations via existing API endpoints. Structure something like:
```
           {
                "parent_id":null,
                "tag":"Boxes",
                "slug":"boxes",
                "description":"Is this a box? Awesome",
                "type":"category",
                "priority":1,
                "color":"00ff00",
                "role": [],
                "translations": {
                      "en": { "tag": "Arabic for boxes"}
                }
            }
```
- Update Tags endpoint to use translations depending on current language
- UI might need to reload when switching languages, to ensure we don't miss translating any already loaded content
- Add 'Arabic name' to category settings UI

**Comment by Celestine22** [comment]
No need to translate categories! We will have 3 surveys (Air, Land, Water) with multiple categories/sub categories under each! @rjmackay @dalezak @willdoran

**Comment by rjmackay** [comment]
Very rough UI for editing tags:
<img width="884" alt="screenshot 2017-07-26 11 13 16" src="https://user-images.githubusercontent.com/7965/28597708-8cab81b6-71f3-11e7-8d34-23e3d758fb19.png">

**Comment by rjmackay** [comment]
@justinscherer any thoughts on simple improvements to the edit UI for translations?
Original categories editing UI is here: http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/settings-category-edit.html

My rough version is above. I'm only dealing with Arabic and English right now... if this goes back into core we'd have to cope with more (and probably give users a way to limit which languages they show too)

**Comment by justinscherer** [comment]
This is super interesting. 

The most flexible way to do this would be to allow our users to "add" whichever languages they want. If, for example, we need to do a legally compliant deployment in a country with 4 or 40 official languages, it should technically be possible. 

For the example above, the Arabic copy on the config page should also be in Arabic, and it should be displayed right-left. 

I also REALLY want to refactor the styling of the form fields overall, and they need some work for accessibility purposes. There are a few items coming up in the product backlog that will impact this. 

My initial thought is that we make it good enough for the client for now (follow existing styling, except with duplicated fields and AR fields are in AR and display right-left), and we add multiple language support "properly" when we refactor our config forms more generally. Given timelines, we're probably not going to have time to do the whole job as part of the client's scope. 

@jshorland thoughts on this approach?^^

Opened #1933

**Comment by rjmackay** [comment]
> The most flexible way to do this would be to allow our users to "add" whichever languages they want.

Absolutely. I imagine this being a site wide setting where you enable/disable whatever languages you need.

> For the example above, the Arabic copy on the config page should also be in Arabic, and it should be displayed right-left.

They can switch the entire UI into Arabic if they like, but we only show 1 language at a time, not a mix of the two. Maybe thats the wrong approach though?

> My initial thought is that we make it good enough for the client for now (follow existing styling, except with duplicated fields and AR fields are in AR and display right-left), and we add multiple language support "properly" when we refactor our config forms more generally. Given timelines, we're probably not going to have time to do the whole job as part of the client's scope.

Definitely. I've built the backend to support many languages already, but the making the frontend flexible is harder.

I'll see if I can switch a single text field RTL, and label it in Arabic too.
