### ISSUE TITLE
Add Dale To Apple and Google App Accounts

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#1927]
To be able to publish the iOS and Android apps, dalezak@gmail.com will need to be added to the following sites so I can create the app profiles and upload the binaries.

*iTunes Connect* https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/users_roles 

*Apple Developer Team* https://developer.apple.com/account/#/people/

*Google Play Console* https://play.google.com/apps/publish

**Comment by rjmackay** [comment]
This issue was moved to ushahidi/platform-fix-our-environment#24
