### ISSUE TITLE
Mixed Use Of Underscore And Dash in JSON Data

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#1928]
### Expected behaviour
There should be a consistent format for representing JSON data. For example, always use underscores as opposed to dashes in key names.

### Actual behaviour
*Dashes*
```
"data-providers": {
   "smssync": true,
   "twitter": true,
   "frontlinesms": true,
   "email": true,
   "twilio": true,
   "nexmo": true
}
```
```
"data-import": {
   "enabled": true
}
```
*Underscores*
```
"allowed_privileges": [
   "read",
   "search"
]
```
```
"limits": {
   "posts": true,
   "forms": true,
   "admin_users": true
}
```
### Steps to reproduce the behaviour/error
View JSON data from /api/v3/config and other endpoints.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-550

**Comment by AriannaLanz** [comment]
I'm going to take a look at this :)
