### ISSUE TITLE
"Proper" multilingual support

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1933]
This initially came up as part of the Lovomar deal. We need to be able to support multiple languages. 

As a deployer, I want to be able to configure a deployment in multiple languages using those languages

As a reporter/tourist, I should only see the target language I have chosen in the language dropdown. 

For example, if I choose Mandarin, I should not see **any** English text **anywhere** in the product.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-549

**Comment by rowasc** [comment]
I've migrated Robbie's [code](https://github.com/ushahidi/platform/pull/1929/files) to lumen in the  `translations-to-lumen` branch. 
We can pick this up when we start working on translations. It needs client side work to be effective and needs to be tested but it seems pretty advanced 🤷‍♀ 
Closing the old translations' PR .

**Comment by tuxpiper** [comment]
> We can pick this up when we start working on translations. It needs client side work to be effective and needs to be tested but it seems pretty advanced 🤷‍♀

I think there would actually be value in releasing an API solution first. People out there developing their frontends and apps could benefit from this, without waiting for the official client to catch up.

**Comment by rowasc** [comment]
Ah true 👍 good catch
There is still some work in the backend too, but it's more advanced there. I'll figure out where it can fall in the roadmap, leaning towards "as soon as we are done with other WIP" because it's fresh in my brain right now from making this into a lumen thing ha

**Comment by tuxpiper** [comment]
> There is still some work in the backend too, but it's more advanced there. 

Yes and docs to update as well :) We should also probably put some extra effort on the automated tests too.

**Comment by rowasc** [comment]
Yea, right now it seems to only test tags 😬
