### ISSUE TITLE
Lock Reports while being edited

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1936]
It's critical to be able to lock reports while they're currently being edited, as there is a HUGE risk of overwriting changes between users of different teams, within uchaguzi. 

We have a manual work around to ensure that members of the same team are not working on the same report, but no way to ensure that members of different teams are not editing the same report. 

This is fairly urgent.

Had a chat with @rjmackay about building this in on slack.

Let us know?

**Comment by rjmackay** [comment]
Would make sense to look at edit logs with this: https://github.com/ushahidi/platform/issues/1864

**Comment by jshorland** [comment]
When a report is taken into edit mode by a user, that post should not be able to be edited by another user. 

Any other user who tries to edit the post at the same time should receive a message that the post is currently being edited by someone else. 

There should also be a timeout in case someone accidentally leaves a post open in edit mode. @rjmackay @aoduor I can't seem to find the discussion in slack where this was discussed. Could you add any details you can to this issue ASAP?
