### ISSUE TITLE
Login-popup covers survey-list when opening deep link /views/create

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#1939]
### Expected behaviour
Open /views/create
The survey-list shows up

### Actual behaviour
- [ ] If you have been logged in before and that session has expired,  the login-popup covers the survey-modal

### Steps to reproduce the behaviour/error
1. Go to /views/create
2. The log-in popup covers the survey list if you have been logged in before and the session has expired

**Comment by rjmackay** [comment]
I think this is resolved by better token expiry handling in develop now
