### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1941]
PROBLEM: Kuwait deal needed custom icons for surveys. It was a heavy lift. We should make this resellable. We built this already 3 times and need to do it in a scalable way. 

- [ ] Enterprise users can go to survey settings and set a custom icon based on a list of pre-set icons and colors
- [ ] Icon updates on the survey icon
- [ ] Posts in map view are the icon of the survey
- [ ] List view shows the color and icon as well

Aha! Link: https://ushahiditeam.aha.io/features/PROD-548

**Comment by Erioldoesdesign** [comment]
Adding in comments from my MOZOL 6 project (finally)

Platform user says this could be useful for outside campaign uses but it's not essential. More useful would be colour coding (which exists but they struggled to discover)
They might be interested in icons that describe the type of offence (speech bubble as hate speech etc.)
They are most interested in this if it helps/encourages other responders understand and write their own responses.

**Comment by Angamanga** [comment]
@Jenniline if you want to work on this issue as well, go ahead 👍

**Comment by rowasc** [comment]
Related issues (color and icons both) :
#1436 
#1437 
#1099
#1437 
#1942
