### ISSUE TITLE
Custom colors 

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1942]
PROBLEM: Kuwait deal wanted custom deployment colors which required significant development time.

- [ ] User should be able to set settings of Primary, Secondary, maybe Tertiary colors
- [ ] They should be able to pick colors from a color picker
- [ ] Those colors should update the app based on what sections @justinscherer thinks we should change
- [ ] Feature should be gated to only enterprise users

Aha! Link: https://ushahiditeam.aha.io/features/PROD-547

**Comment by middle8media** [comment]
I have thought about this in the past and look forward to diving in.

**Comment by middle8media** [comment]
@caharding @justinscherer 

This should become core once we complete [this](https://github.com/ushahidi/platform-fix-our-environment/issues/50)

**Comment by justinscherer** [comment]
We will probably need to build some kind of configuration UI in Settings to make these changes, as well.

**Comment by middle8media** [comment]
@justinscherer we already have a color picker under "Configure" [here](http://preview.ushahidi.com/platform-pattern-library/master/assets/html/5_layouts/settings-survey-edit.html)
