### ISSUE TITLE
Representation of trusted reporters

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1944]
We have a predefined list of reporters who will be sharing information on Uchaguzi, who we need to be able to identify as trusted reporters on the platform. 

Refs: https://github.com/ushahidi/biz/issues/601

**Comment by jshorland** [comment]
here are codes: https://docs.google.com/document/u/1/d/1Lc2z7nas8m3S02V4zNvMKnJvWQUXMHDCovJOJotyO84/edit?usp=sharing

**Comment by aoduor** [comment]
@jshorland @willdoran automatic coding def can't happen, but is there any way to flag/odentify who a trusted reporter is on the UI? Forwarding you a list via email

**Comment by jshorland** [comment]
I'm going to close this in favor of #1572. Just trying to consolidate.
