### ISSUE TITLE
Tasks shouldn't be visible to non-logged in users on survey form

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1945]
See #1848 too. That was specifically for Lovomar so I've created another issue for UCHAGUZI. 

Expected behaviour
When I'm visiting a deployment to submit a survey response, I want to see only the information I'm meant to submit. As a deployment admin/manager, I've created tasks as an internal workflow for my team to triage incoming posts. It's meant to be used internally, and the information MIGHT be displayed to everyone once its complete (or maybe its meant for internal use only). Point is, there's no need for everyone to be able to see the incomplete task.

Actual behaviour
I see all these weird sections below the survey form. Do I fill them out? Why are they there? I DON'T UNDERSTAND!

**Comment by rjmackay** [comment]
Duplicate of https://github.com/ushahidi/platform/issues/1848 ?

**Comment by jshorland** [comment]
Done. closing.
