### ISSUE TITLE
White labelling web client

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1947]
### Expected behaviour
We should be able to quickly white label the web client, particularly changing colours and maybe icons. This should be build time configuration.

### Actual behaviour
We first have to white label the pattern library, then build that and install it into the web client. Then commit that change and deploy it.

Any icon changes are tricky hacks.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-545

**Comment by middle8media** [comment]
https://github.com/ushahidi/platform/issues/1941
https://github.com/ushahidi/platform/issues/1942
