### ISSUE TITLE
Invalid Time Stamps

### ISSUE THREAD

**Issue by dexwakhu** [ushahidi/platform#1952]
Time stamps appear on the platform for a time in the future

**Comment by dexwakhu** [comment]
![Screen Shot 2017-08-05 at 17.22.03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5892dafedfd7da1a00517efd/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454f66b7191a379e80c2953415f4dbe5d4a1f06a3a3dc78e2a436628f595fecd0395c21c06b43aabf811fe901ba288a46d7b4e89850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec859ff4fe24954ad17336af43b.png)

**Comment by aoduor** [comment]
O_o!

**Comment by jshorland** [comment]
ahhh i can't seem to replicate this in sandbox. I've tried changing the post date to a time in the future and it throws an error and won't let me do it (as it should have). Where did that post come from?

**Comment by dexwakhu** [comment]
These were created on the live deployment by our infonet partners that were posting media reports on election campaigns. Not sure how they managed to do this

**Comment by jshorland** [comment]
I'm going to keep this in the "new issues' column for now in case we are able to replicate it. or someone else manages to do it.

**Comment by jshorland** [comment]
IT'S HAPPENED AGAIN. HOW ARE THEY DOING THIS?!?
![Screen Shot 2017-08-08 at 4.23.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d11d8e01ae881900114dda/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454fb6b7191a37cf110284f5d575ecc3c4a4356bcbbd671f3e57862804e0ee8856c5e20c56817faea8418bc01ec208b4784bfee8818d2f42f67b6d5db1063474f4dcbed5727a49c42c952f74ee14f57a7173061ee753f7555d9.png)

**Comment by rjmackay** [comment]
Pretty sure this was fixed.
