### ISSUE TITLE
Uchaguzi favicon missing

### ISSUE THREAD

**Issue by dexwakhu** [ushahidi/platform#1954]
Can we add a favicon on the Uchaguzi site please?

**Comment by middle8media** [comment]
@justinscherer do you have this, this should be as simple as uploading the `favicon.io` to the server.

**Comment by gitudaniel** [comment]
@middle8media just sent in a pull request fixing this issue. Kindly review and give feedback

**Comment by middle8media** [comment]
@gitudaniel can you link me to the PR? I don't see it [here](https://github.com/ushahidi/platform/pulls)

**Comment by middle8media** [comment]
This will take effect on our next push to production.
