### ISSUE TITLE
Limit rights to editing saved searches/collections to roles

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1956]
### Expected behaviour
I'd like to limit the ability to alter my existing saved searches to specific roles

### Actual behaviour
Right now, any logged in users who can view saved searches are able to edit it. (I had two of my saved searches that are crucial to the uchaguzi workflow broken by an unintended edit)

**Comment by aoduor** [comment]
Related to https://github.com/ushahidi/platform/issues/1859

**Comment by aoduor** [comment]
And to https://github.com/ushahidi/platform/issues/1711

**Comment by willdoran** [comment]
This is done: to test it

- [ ] Create saved search
- [ ] set edit role to admin only
- [ ] set visibility to everyone
- [ ] save
- [ ] Log out 
- [ ] Log in as member
- [ ] go to savedsearch
- [ ] change the filters
- [ ] look for the edit button, you shouldn't see it or the options menu
- [ ] look for the reset/update savedsearch, you should see neither

**Comment by jshorland** [comment]
@rjmackay I QA'd this twice. Good to go.
