### ISSUE TITLE
Users with manage posts permission cannot access SMS conversation

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#1959]
<img width="727" alt="screen shot 2017-08-07 at 10 21 20 am" src="https://user-images.githubusercontent.com/8900438/29016243-59c66836-7b5a-11e7-825c-0987f8afb991.png">
### Expected behaviour
There should be a button/function that allows conversation with author and its missing for all posts.
@tuxpiper please unbreak this now

**Comment by aoduor** [comment]
Logged in as an admin, and I can see this box,so it looks like it's been limited to admin roles. We need to open this up to anyone who can manage posts.

URGENT.

**Comment by rjmackay** [comment]
Hrm. That might be standard that you can't reply until you've chosen a survey... though I realize that doesn't totally make sense. @kamaulynder let me know how you get on with this

**Comment by Celestine22** [comment]
@aoduor did you test with an unstructured post? @rjmackay thank you!

**Comment by rjmackay** [comment]
@Celestine22 was this seen on production or sandbox?

**Comment by aoduor** [comment]
Production. @Celestine22 yes I did.

**Comment by aoduor** [comment]
the conversation box always appears for me even when i haven't selected a survey

**Comment by Celestine22** [comment]
In that case could we have structuring and geolocation team upgraded with that permission? Or what's a work away around this? @rjmackay

**Comment by rjmackay** [comment]
It looks like there isn't a permission for this explicitly. Messages are locked to purely admins. Would adding something like a "Manage messages" permission work? This would allow sending and viewing messages, and I guess needs to allow viewing contacts too.

**Comment by Celestine22** [comment]
That would will definitely work if manage messages means responding @rjmackay

**Comment by jshorland** [comment]
@kamaulynder you ready for me to test this?

**Comment by willdoran** [comment]
@kamaulynder Did this get merged?

**Comment by rjmackay** [comment]
It did. https://github.com/ushahidi/platform/pull/1983

However I think we need to review the new permissions before landing in develop... there was some confusion about what a 'manage messages' permission actually did so naming is probably not great.

**Comment by rjmackay** [comment]
@jshorland Should this just be available to anyone with "Manage posts" or should we use an additional permission as-per-uchaguzi?
