### ISSUE TITLE
After editting a post in my saved searches, clicking a step back resets the saved search

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#1960]
@rjmackay @tuxpiper when I go back to the timelines view after finishing editing a post, I have to click again on my saved search to be able to view posts that I'm working, can we fix saved searches until a user resets?

**Comment by tuxpiper** [comment]
I think this is an issue with keeping browser status in the client. I may be wrong but I think it's significant error to fix.

**Comment by rjmackay** [comment]
Yea. Its pretty fiddly to fix. Theres actually a long standing PR to address some of the issues around clearing a saved search https://github.com/ushahidi/platform-client/pull/413 but I don't think that resolves this specifically

**Comment by Celestine22** [comment]
Very significant, especially for the structuring team that has to process many incoming posts at a time.

**Comment by rjmackay** [comment]
I've merged that other fix. There might be a way to make a saved search more sticky beyond that.

**Comment by Celestine22** [comment]
#1985 linking to this, @kamaulynder can you help fix this?
