### ISSUE TITLE
Hide archived posts from users

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#1967]
Saved search for sms email and twitter correspond to the unknown survey, it currently shows 872 posts that have been archived, but none under review, could we hide this figure for archived posts just to avoid confusing folks
<img width="675" alt="screen shot 2017-08-07 at 3 19 12 pm" src="https://user-images.githubusercontent.com/8900438/29026396-3bcc7c92-7b84-11e7-9d5e-13ab5243cd4f.png">

**Comment by tuxpiper** [comment]
I think this could be an overall product change. In general, archived posts shouldn't count towards stats? @jshorland

**Comment by Celestine22** [comment]
The 872 highlighted are all archived, any chance that can be hidden in stats? @tuxpiper

**Comment by jshorland** [comment]
@tuxpiper I agree with you re: product change, but I'd like to focus on getting it right for uchaguzi for now and then worry about cleaning code and writing proper tests to get it back into platform next week.

**Comment by Celestine22** [comment]
Thanks @jshorland

**Comment by jshorland** [comment]
@willdoran And this.

**Comment by willdoran** [comment]
@jshorland very unlikely this will get done today

**Comment by aoduor** [comment]
Hey folks. Flagging that this would be helpful.

**Comment by rjmackay** [comment]
I think the correct solution for this in core is to apply the current filters to the totals too? ie. if we're only viewing published posts, only include those in the total.
This probably needs to exclude form and category filters, but all others should apply.
