### ISSUE TITLE
Export function for CSV, file not coherent

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#1968]
Selected below posts to export
<img width="717" alt="screen shot 2017-08-07 at 3 23 50 pm" src="https://user-images.githubusercontent.com/8900438/29026626-58b44a0a-7b85-11e7-8515-6483ea235a44.png">
file received is as below:

**Comment by tuxpiper** [comment]
I don't think there's support for exporting specific posts (although, maybe if they are put in a collection first?)

In any case, I'm noticing that, regardless the set of filters active at the moment, the feature seems to be always generating the same CSV file.

Needs investigation

**Comment by jshorland** [comment]
CSV export appears to work correctly for me.

I:
- filtered by published posts
- exported CSV
- received the file screenshotted below which appears to be 100% correct

<img width="1440" alt="screen shot 2017-08-07 at 8 19 20 am" src="https://user-images.githubusercontent.com/3224856/29033220-27be9022-7b49-11e7-8f7b-e05ef48df74c.png">

**Comment by jshorland** [comment]
Dropping this lower in priority to p2 compared to other issues with uchaguzi. We can manually clean data if anyone needs it.

**Comment by jshorland** [comment]
Important to know though: 

Who will be using CSV export, for what, and when?

**Comment by Celestine22** [comment]
Analysis and research team will be using this, for data analysis and viz, for published posts

**Comment by jshorland** [comment]
The only way I can think to make this more coherent would be:
- replace category ID numbers with the names 

Otherwise, exporting via CSV doesn't allow for tab separation, and we have data across multiple surveys so every field for each of those surveys has to be included.

**Comment by aoduor** [comment]
Related to https://github.com/ushahidi/platform/issues/1857 and https://github.com/ushahidi/platform/issues/1808

**Comment by aoduor** [comment]
maybe organise the fields in the CSV file in order of how they appear on platform

**Comment by Celestine22** [comment]
@jshorland is it possible to organize it like this 👇 
<img width="873" alt="screen shot 2017-08-07 at 7 03 14 pm" src="https://user-images.githubusercontent.com/8900438/29035099-248138d8-7ba3-11e7-8fdf-e255a9e06850.png">

**Comment by jshorland** [comment]
ideal scope right now:
- return names of categories, saved searches, collections, survey
- transform lat/lon into county, city, state, country

Possible? @willdoran

**Comment by willdoran** [comment]
ok the names is done

**Comment by willdoran** [comment]
geo coding is done but needs another few mins to be clean

**Comment by jshorland** [comment]
Moving to @rjmackay

**Comment by diegodorgam** [comment]
Hey persons, 
 not sure if should report this here, or maybe open another issue, but I got an error very related to this, only that in my case the CSV file brings the fields out of order, and it doesn't export the activities fields, at least not all of them.

So, my survey has 8 activities to be filled, each fied is identified with the activity number in front of it's name, eg: `1.2 street`.

When I try to export to CSV, some fields of activities 1, 2, 3 and 4 are shown, not all, and the others don't come in the file.
<img width="538" alt="captura de tela 2017-08-10 as 15 15 14" src="https://user-images.githubusercontent.com/12052193/29185215-f4dc3b94-7dde-11e7-8cd2-c00483e83a22.png">

this is the file that csv exporting produces:
[ToNaRede-2017-08-10.csv.zip](https://github.com/ushahidi/platform/files/1215900/ToNaRede-2017-08-10.csv.zip)

So I kind found my way to export data directly from mysql, using the following sql statement:  

```sql
USE ushahidi;
SET @sql_dt = NULL;
SET @@group_concat_max_len = 32000;
SELECT
  GROUP_CONCAT(DISTINCT
    CONCAT(
		CASE type
			WHEN 'datetime' THEN '( select d.value from post_datetime d where d.post_id=p.id and d.form_attribute_id='
			WHEN 'varchar' THEN '( select d.value from post_varchar d where d.post_id=p.id and d.form_attribute_id='
			WHEN 'decimal' THEN '( select d.value from posts_decimal d where d.post_id=p.id and d.form_attribute_id='
			WHEN 'text' THEN '( select d.value from post_text d where d.post_id=p.id and d.form_attribute_id='
			WHEN 'int' THEN '( select d.value from post_int d where d.post_id=p.id and d.form_attribute_id='
			WHEN 'relation' THEN '( select d.value from post_relation d where d.post_id=p.id and d.form_attribute_id='
      WHEN 'point' THEN '( select d.value from post_point d where d.post_id=p.id and d.form_attribute_id='
      WHEN 'markdown' THEN '( select d.value from post_markdown d where d.post_id=p.id and d.form_attribute_id='
      WHEN 'geometry' THEN '( select d.value from post_geometry d where d.post_id=p.id and d.form_attribute_id='
		END,
      id,
      ' limit 1) AS `',
      label,
      '`'
    )
  ) INTO @sql_dt
FROM
(
  SELECT a.id,a.label,a.type,a.priority,b.form_id,b.priority stage_priority
	FROM ushahidi.form_attributes a
	INNER JOIN form_stages b on a.form_stage_id=b.id
	WHERE b.form_id=4
	ORDER BY stage_priority ASC, priority ASC
) dt_fields;

SET @esql = CONCAT(
  'SELECT p.form_id pesquisa_id, f.name pesquisa, p.id post_id, p.status, p.post_date, p.title titulo, p.content descricao, ',
  @sql_dt,
  ' FROM posts p LEFT JOIN forms f ON p.form_id=f.id;');

PREPARE stmt FROM @esql;

EXECUTE stmt;
```

this produces the following file, wich is the file that I would need to get from CSV exporting:
[pesquisas.csv.zip](https://github.com/ushahidi/platform/files/1215912/pesquisas.csv.zip)

still have somethings to improve, but is just a quicky workarround. 

Is there, by any chance, a way to fix that csv exporting function, or maybe help me to find a way to do so? I'm struggling to find where it is, so maybe I could prepare some pull request...

Any ideas are welcome.

Thanks in advance.

**Comment by diegodorgam** [comment]
@jshorland @rjmackay any insights?

**Comment by jshorland** [comment]
@diegodorgam thanks for letting us know. Are you using hosted or open source, and if open source, which version of the software are you running? 

Also, would you mind sharing the URL of your deployment so I can try to replicate the error?

**Comment by diegodorgam** [comment]
I'm using an OpenSource install done with Docker, from platform-release repo @jshorland , there Ushahidi is in version 3.7.

The URL is https://mapa.tonarede.org.br

**Comment by rjmackay** [comment]
I'm going to close this an open a new issue to cover the outstanding issues
