### ISSUE TITLE
Show cumulative total per saved search

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#1969]
A popup or some kind of script-generated total would be brilliant, at the moment, you have to keep clicking on the Load More icon to check for more posts.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-541

**Comment by tuxpiper** [comment]
Is this only relevant to saved searches, or going through posts in the timeline view in general? Would this be useful only in the timeline view?

In that case, maybe it would help to have something similar to

"Showing posts 1-20 of 1000 matches"

both at the top and the bottom of the list?

I'm wondering what @jshorland , @justinscherer and @middle8media think about this.

**Comment by Celestine22** [comment]
This would be relevant to the timeline view in general @tuxpiper

**Comment by tuxpiper** [comment]
or... "XXX more posts available for display" next to the "Load More" button

**Comment by Celestine22** [comment]
The first one makes "urgent" sense, however if we could have both, even more brilliant

**Comment by jshorland** [comment]
What is easiest? this is definitely something that should go back into product, but again, let's focus on making this possible for Uchaguzi for right now. @tuxpiper

**Comment by willdoran** [comment]
@jshorland this is unlikely to get done today
