### ISSUE TITLE
CSV export not working correctly

### ISSUE THREAD

**Issue by larsbromley** [ushahidi/platform#1970]
The CSV export on https://uchaguzi.or.ke/views/map is not producing nicely structured CSV data. Instead, the data is very confused / garbled, with repetitive field headers and end-of-line errors. And, it seems the filters are not applied. To see this, click 'Share' and 'Export to CSV' and look at the results.

**Comment by Celestine22** [comment]
#1968 linked to this

**Comment by jshorland** [comment]
Duplicate. Closing in favor of #1968
