### ISSUE TITLE
Unbreaking edit lock isn't available for admin

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1971]
### Expected behaviour
I should see the edit icon as a logged in admin, click the edit icon, and receive a message that I can override the edit lock. 
### Actual behaviour
As a logged in admin, I see no edit icon. 
### Steps to reproduce the behaviour/error
Login as admin to uchaguzi.or.ke
Open a post in edit mode
Open the same post in edit mode in another tab
See no edit icon

**Comment by jshorland** [comment]
@willdoran When QA'ing on sandbox.uchaguzi.or.ke, I can't get edit mode to appear for any of the posts and there's a client side bug on post width (it's too small). Logging this issue separately!
![grpauh](https://user-images.githubusercontent.com/3224856/29032555-a8f61c30-7b46-11e7-9e19-c3daf6ef5194.gif)

**Comment by willdoran** [comment]
@jshorland should be fixed can you retest on sandbox?
