### ISSUE TITLE
I still see delete button and can delete posts (I think?) when post is in edit mode elsewhere

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1972]
### Expected behaviour
As a logged in admin, I shouldn't see the delete button when post is open in edit mode elsewhere unless I select "edit" and then override the edit lock. OR I can still see delete and receive the same message I receive when I override edit lock -- "This post is currently being edited elsewhere. As an administrator, you may choose to override the current edits and delete the post. Any changes made during the current edit session will be lost. Are you sure you want to delete the post?"

WHICHEVER IS EASIER.

### Actual behaviour
As a logged in admin, I see the delete button, and when I click the delete button, I don't receive any special messages. I haven't actually clicked delete because I don't want to on the live deployment. 

### Steps to reproduce the behaviour/error
login as admin
Open a post in edit mode
Open the same post in a new tab in edit mode
See delete button -- you can click, but do not confirm

**Comment by willdoran** [comment]
@jshorland can you retest on sandbox?

**Comment by jshorland** [comment]
Delete does in fact disappear. passes QA.
