### ISSUE TITLE
Edit mode completely disappears on some posts and I can't get it back

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1973]
### Expected behaviour
As a logged in admin, When I open a draft post in edit mode, and then navigate OUT of edit mode (no matter which was I navigate out), that post should have the option to re-enter edit mode. 

### Actual behaviour
This is specifically for posts that aren't fully filled out for required fields and tasks. I receive the proper message that I can't re-publish until I finish everything, but I can never seem to get the edit button to reappear once I exit the edit mode (whether I exit by closing a tab, navigating back, logging out or logging back in)

### Steps to reproduce the behaviour/error
login as an admin and try to find a post that shows that "can't publish until everything is filled out" message. 
I used this one: https://uchaguzi.or.ke/posts/792
And cannot, for the life of me, figure out how to get the edit icon back.

**Comment by willdoran** [comment]
@jshorland this should be fixed can you test on sandbox?

**Comment by jshorland** [comment]
@willdoran an issue with this (I should have been more thorough in my initial logging. apologies for that). 

When I'm logged in as a user with "manage posts" permission, but NOT an administrator, the post with the conditions described above remains locked, even though it is not open anywhere else in edit mode (and i'm logged out of my admin account and logged in with my "publisher" account)

Steps to reproduce:
- login to sandbox with admin account
- find post that is published but overrided the validation to be published (probably because of CSV import)
- go into edit mode on that post
- you should receive the notification that the post has incomplete things and you can't re-publish until you fix those
- Click cancel on edit mode and navigate back to either map or timeline
- log out of admin account
- log into account with "manage posts" permission, but one that isn't an administrator (e.g. structuring, publishing, verification)
- Try to go into edit mode on the post you originally selected as the logged in admin
- you receive a notification that someone else is editing the post and you can't edit until they are done or it times out in 2 hours. 

Expected:
- even if the post is put back into draft because the admin started to edit the post and the validation was turned back on, if that post goes back into draft and the admin closes out of edit mode, any other user with "manage posts" permission should be able to enter edit mode on the post.

**Comment by willdoran** [comment]
@jshorland above is working for me now

**Comment by jshorland** [comment]
Confirmed fixed. At first, I logged in as an admin and had to break the edit lock. I suspect someone had the same post open in edit mode before me. I then logged out and logged back in as a non-admin user with manage post permissions and was able to access the edit mode exactly as I expected to since I had logged out of my admin session.
