### ISSUE TITLE
CSV is broken

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1975]
### Expected behaviour
When I navigate to uchaguzi.or.ke as a logged in admin and export all data with no filters selected, I should get ALL posts

### Actual behaviour
I get 20 rows of data -- I think it might be giving me only published?

### Steps to reproduce the behaviour/error
1. login to uchaguzi.or.ke as an admin
2. don't mess with filters AT ALL (you should be seeing all posts with locations on the map which is centered in KE)
3. go to share --> export
4. open the exported CSV file 
5. there are only 20 posts.

**Comment by willdoran** [comment]
This is failing to include the filters from client, will fix now

**Comment by willdoran** [comment]
@jshorland I believe this is fixed

**Comment by jshorland** [comment]
PASSES QA.
