### ISSUE TITLE
Share menu style is broken

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1977]
### Expected behaviour
- Share menu displays correctly
### Actual behaviour
- Share menu does not display correctly
<img width="1102" alt="screen shot 2017-08-07 at 14 55 47" src="https://user-images.githubusercontent.com/2694405/29041391-ad2a313a-7b80-11e7-9d59-da1175bccf84.png">

### Steps to reproduce the behaviour/error
- On timeline view, click share menu

**Comment by jshorland** [comment]
This still looks broken to me?
