### ISSUE TITLE
Uchaguzi Password Reset e-mail is missing a button.

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1978]
### Expected behaviour
Read text for Uchaguzi password reset that indicates pushing a button and see the button indicated. See screenshot below. 
### Actual behaviour
Read the text, look for button, don't see one. 
### Steps to reproduce the behaviour/error
Reset password. 
<img width="635" alt="uchaguzi password reset" src="https://user-images.githubusercontent.com/4574998/29041946-2f930f84-7b72-11e7-86f0-6add2012d57b.png">

**Comment by rjmackay** [comment]
I think this is a configuration issue. Need to set client url in the site config or API environment vars.

**Comment by rjmackay** [comment]
Should be fixed on prod now

**Comment by jshorland** [comment]
fixed on production!
