### ISSUE TITLE
Uchaguzi Support not linked to Uchaguzi deployment

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1980]
### Expected behaviour
Find more information or support page while viewing the deployment (https://uchaguzi.or.ke/views/map).
### Actual behaviour
Cannot find a URL that links to https://www.ushahidi.com/uchaguzi-support/ in the text describing the deployment. And the Ushahidi logo in the bottom of the screen links to *[Ushahidi support](https://www.ushahidi.com/support)* and not *[Uchaguzi Support](https://www.ushahidi.com/uchaguzi-support/)*.
### Steps to reproduce the behaviour/error
See screenshot below.
![uchaguzi_documentation_issue](https://user-images.githubusercontent.com/4574998/29042944-5e989b2e-7b76-11e7-948b-7c083ede1842.png)

**Comment by jshorland** [comment]
@middle8media can you fix this with the uchaguzi support?

**Comment by jshorland** [comment]
Support icon now linking to uchaguzi.or.ke homepage? Should link to https://www.ushahidi.com/uchaguzi-support

**Comment by middle8media** [comment]
**Deployment Description:**
Uchaguzi support URL and general URL support is in [production](https://uchaguzi.or.ke/views/list).

This is fixed for now, but to display the links correctly it requires html in the deployment description. I am working on a built in solution.

@will [support link correction](https://github.com/ushahidi/platform-client/commit/275d7c98fb6545abc9e16e54c0103fee9f217d2f) is ready to merge into master.
