### ISSUE TITLE
Go back to our saved search page automatically 

### ISSUE THREAD

**Issue by Junemg** [ushahidi/platform#1985]

**Comment by jshorland** [comment]
Ideally it also reverts back to the same place in the timeline of the saved search

**Comment by jshorland** [comment]
@rjmackay this is killing our teams' efficiency. Can you work on this after you wrap up the deploy?

**Comment by rjmackay** [comment]
Closing this. Reopen if further improvement is needed

**Comment by rjmackay** [comment]
I'm not sure this should go back to core. The fixes for #1960 are generic, but redirecting to the saved search or home after saving a post is slightly unexpected for users in a normal deployment
