### ISSUE TITLE
Post locking functionality not working

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#1986]
### Expected behaviour
A post should;
1. Hide the edit button when a user is editing it
2. Completely not allow 2 users to work on it at the same time.
### Actual behaviour
1. It is not hiding the button
2. It's allowing myself and colleague to edit it at the same time
### Steps to reproduce the behaviour/error
1. Click on edit post.
2. Tell other user to click on edit the same post.
3. Other user get permission to edit the same post.

Scenario 2:
1. Click on edit post.
2. Enter the post to add survey.
3. See alert that another user is editing the same post.
4. Continue to click on edit button.
5. Platform still allows you to edit.

@tuxpiper @rjmackay @kamaulynder please look into this.

**Comment by rjmackay** [comment]
Looking in to this

**Comment by rjmackay** [comment]
I can't make this happen on the sandbox. Will attempt to reproduce on production
