### ISSUE TITLE
Enable google geocoding of addresses / landmarks

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1988]
### Expected behaviour
Administrator should be able to switch the site to be using google geocoding (instead of OSM nominatim). Google has proved to still have a better edge on some places.

( Or should we consider the option of querying both services and smartly merging results? Maybe in a further development)

In the Uchaguzi 2017 case , using nominatim has been holding back the geolocation team significantly, to the point of becoming the bottleneck for publishing posts.

### Actual behaviour
Only nominatim is being used

**Comment by Shadrock** [comment]
Interesting. I agree that Google may have an edge in some places: but certainly not others (e.g. Kibera). There are loads of comparison tools that clearly allow you to see where various map features exist with both Google and OSM (bearing in mind that you are only seeing a sub-set of the actual database).
