### ISSUE TITLE
Bulk actions in structuring posts

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1989]
### Expected behaviour
Structuting team needs to be able to select multiple reports at a time to push to geolocation team
![pasted image at 2017_08_08 01_26 pm](https://user-images.githubusercontent.com/3224856/29074729-314d2cf4-7c05-11e7-9814-b0bbf2009d75.png)

Original note from Erik
erik [3:26 AM] 
Hi everyone.  We’re already getting underwater in the situation room.  There are now 2,000 reports in just SMS/Email that need to be structured.  However, after looking through this I’ve realized that a good number of these in fact DON’T need to go into a survey.  They just need to be “approved” AND “geolocated”.  

So, the process should be:
1. structuring team looks at posts with the saved search “Unstructured posts from SMS/email”
2a. person selects one that needs structuring and goes into it (current process)
2b. person stays on that page, and selects multiple locations that don’t need to be structured, only geolocated.  Submits multiple at one time to geolocation.
3. Geolocation - locates location
4. Publishing team looks at it and publishes.  (NOTE: publishing team also needs to be able to select multiple reports to “publish” at a single click).

### Actual behaviour
Currently you have to do one at a time, assign them to a survey, and then save. 

### Steps to reproduce the behaviour/error

Aha! Link: https://ushahiditeam.aha.io/features/PROD-540

**Comment by jshorland** [comment]
to do: scope out so we understand implications and risks of this in case we absolutely have to implement.

**Comment by jshorland** [comment]
@willdoran @justinscherer this would be helpful if we have time.

**Comment by jshorland** [comment]
As a logged in post structurer, I want to bulk assign multiple unstructured posts to a survey, bulk apply any necessary tags to them (in this case, needs geolocation), and pass them onto the next team in the workflow (in this case, geolocation).

As a logged in post structurer, as I am performing the actions above, I don't want anyone else to screw this up by editing the posts i've selected at the same time 

Issues: 
- what about unfilled fields that are required? Title, description, location. Description is there, but you'd still have to manually fill out location of all of them. Still impeded efficiency. 
---> potential solution: could fill out title with description text and default location values (issue with that is there are character limits on title. we'll likely hit errors while performing the bulk action)
---> auto fill default values for required fields. The issue with this is that the geolocation team now bears the burden of reviewing and structuring that data.

**Comment by rowasc** [comment]
<img width="625" alt="Screen Shot 2019-06-09 at 22 32 34" src="https://user-images.githubusercontent.com/2434401/59167214-83deeb80-8b06-11e9-8345-d54c9dd339fa.png">
Confirming that tthis is still pending. .While we can assign status, we can't assign to surveys from bulk actions

**Comment by Erioldoesdesign** [comment]
V important feature but would likely need documentation to help folks learn how to use it clearly
