### ISSUE TITLE
Change edit post lock timeout from 2hrs to 10 minutes and update the message that appears when someone tries to edit a post already in edit mode

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1990]
### Expected behaviour
2 hours is too long to have as the timeout period of an edit lock on a post, should be 10 minutes cc: @aoduor 
### Actual behaviour
takes 2 hours and if someone closes the tab instead of navigating out of the post, it takes 2 full hours to time out and the other teams are just waiting around

**Comment by Angamanga** [comment]
Adding this together with #1886

**Comment by willdoran** [comment]
This is in now.

**Comment by jshorland** [comment]
woo. closing.
