### ISSUE TITLE
Bug with task completion validation

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1991]
@jess could you try the following to sanity check for me
- For a survey with a required stage
- On a post for that survey
- Mark the stage complete
- Save
- Publish the post

jess [29 minutes ago] 
@will This post belonged to a survey with geolocation required. I marked the task as complete and published. Confirmed that the post is published and showing up in both map and timeline, and within the proper saved searches. https://sandbox.uchaguzi.or.ke/posts/1188

jess [28 minutes ago] 
@will

jess [28 minutes ago] 
update

will [28 minutes ago] 
cool

jess [28 minutes ago] 
i logged BACK into sandbox as an admin and went to the post that I had published. Took it to edit mode. Received this error

jess [27 minutes ago] 
This post is currently in an invalid state. You'll need to complete all required tasks before you can re-publish this post. You can either complete the necessary tasks or give your post a different status, like "under review."

jess [27 minutes ago] 
but i DID complete all required tasks before publishing

will [27 minutes ago] 
ah

will [27 minutes ago] 
ok lemme take a look

will [20 minutes ago] 
Yep that’s a bug fixing now

will [< 1 minute ago] 
Ok I fixed it by disabling that message because it’s not working, i can look at fixing it later, could you make it its own issue and assign me? @jess

jess [< 1 minute ago] 
yes

**Comment by rjmackay** [comment]
Looks like this is a race condition where the check runs before the post is fully rendered. Adding a quick fix.
