### ISSUE TITLE
Unstructured Posts Form edit should be on Edit not Detail

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1992]
### Expected behaviour
- When visiting an unstructured post, I should not see the set form section
- When I click edit I should be presented the select form option
### Actual behaviour
- When visiting an unstructured post, I should see the set form section
- When I click edit I am not presented the select form option

**Comment by rjmackay** [comment]
@jshorland is this still relevant?

**Comment by rjmackay** [comment]
Fixed in data view.
