### ISSUE TITLE
Filter modal footer obscures some elements

### ISSUE THREAD

**Issue by gitudaniel** [ushahidi/platform#1994]
### Expected behaviour
All fields should be visible and clickable
### Actual behaviour
Some fields in the filters dropdown are barely visible and not clickable.

### Steps to reproduce the behaviour/error
Go to the Ushahidi platform client, click on filters and scroll down. You will see something like this
![Screenshot from 2020-10-08 14-00-07](https://user-images.githubusercontent.com/2434401/95490570-c3258280-096e-11eb-8b30-331383027352.png)

Instead, the dropdown footer should come *after* the fields, not on top of them
Aha! Link: https://ushahiditeam.aha.io/features/PROD-539

**Comment by onyeepeace** [comment]
Hello @rowasc, what needs to be done with this? I am an Outreachy intern and I will like to work on it. I opened up uchaguzi.or.ke on firefox in windows and the radio buttons are clickable. Was it fixed previously or it has a different problem?

**Comment by rowasc** [comment]
Hey. I just edited the description to make it more generally applicable. Does it make sense now? (Thanks for letting us know)
cc @Angamanga tagging Anna for follow up about any specific implementation details

**Comment by onyeepeace** [comment]
Yes, it is clear now. I will reach out if I need anything again.

**Comment by onyeepeace** [comment]
@rowasc I am in need of some help. How do I access the css file for this issue. I could inspect it in my browser and I have seen what's wrong. I am now stuck at working on the css file. The css file that points to it is in the node modules. I know I shouldn't edit the node modules. Do I create a css file to target the issue? or what do I do? Please I need some help.

**Comment by onyeepeace** [comment]
@Angamanga @rowasc I have made a pull request on the platform-pattern-library https://github.com/ushahidi/platform-pattern-library/pull/244 to fix this issue. Please kindly review. Thanks.

**Comment by Angamanga** [comment]
@onyeepeace Thank you! I will review shortly!

**Comment by onyeepeace** [comment]
@Angamanga Okay, great. Thanks.
