### ISSUE TITLE
Deleting location in filter modal gives new longitude and latitude coordinates

### ISSUE THREAD

**Issue by gitudaniel** [ushahidi/platform#1995]
### Expected behaviour
On deleting a location in the location field the field should remain empty
### Actual behaviour
Deleting the location produces new longitude and latitude coordinates
### Steps to reproduce the behaviour/error
On uchaquzi.or.ke click on filters and enter a location like Nairobi, Kenya
Press and hold the backspace button to clear the field.
You should see new latitude and longitude coordinates appear.

**Comment by jshorland** [comment]
I can't reproduce this. Closing.
