### ISSUE TITLE
Saved search should update Survey report count

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1997]
### Expected behaviour
When I use a saved to filter a Deployment, I expect the count of reports in the survey section to update

### Actual behaviour
The count of reports in a survey stays the same when I use saved search. There is no way for me to count the total # of reports based on my filtering criteria

### Steps to reproduce the behaviour/error
Open Uchaguzi.or.ke
Select saved search: unpublished web
Survey totals don't update

<img width="1009" alt="screenshot 2017-08-08 12 41 30" src="https://user-images.githubusercontent.com/1618793/29091292-560a30d2-7c37-11e7-887f-848018e52fc5.png">

**Comment by jshorland** [comment]
related: #1967

**Comment by aoduor** [comment]
Hey folks. Flagging that this would be helpful.

**Comment by Angamanga** [comment]
@aoduor I started working with this today but other stuff came between and I am not finished, a few things left which i will sort out tomorrow FIRST THING!
