### ISSUE TITLE
Incident date and time field is updating to the closest date and time of whoever is editing the post

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2001]
### Expected behaviour
It should stay as it was when it was originally submitted unless manually changed by editor
### Actual behaviour
It auto updates to the date/time of whoever is editing it
### Steps to reproduce the behaviour/error
Take a post in unstructured from several hours ago
Put it into edit mode
See incident date field

**Comment by rjmackay** [comment]
I couldn't reproduce this with a normal post. However an unstructured post won't have an 'incident date' so it makes sense that it gets set to your current date/time.

Can you confirm if this was the incident date custom field? or the 'post date' which is editable on the right hand side?

**Comment by jshorland** [comment]
Ahh I see . It was in fact the incident date custom field. That makes so much more sense now

**Comment by jshorland** [comment]
closing.
