### ISSUE TITLE
Category selection not saving

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#2002]
### Expected behaviour
In my saved searches for example for unverfied posts, when I edit a post and unselect unverfied and then select verified, and save, this post should move from unverified saved search, to verified saved search.
### Actual behaviour
The post is not saving the category selection.
### Steps to reproduce the behaviour/error
1. Open unverified posts saved search.
2. Select a post to edit.
3. Unselect "unverfied post" category.
4. Select "verified post" category.
5. Save post.
6. Refresh unverfied posts saved search.
7. You will see the same post.

**Comment by Angamanga** [comment]
This could not be reproduced and is working fine on Uchaguzi as well as locally. Confirmed with @Celestine22. Closing the issue
