### ISSUE TITLE
More than one Photo per Post

### ISSUE THREAD

**Issue by Junemg** [ushahidi/platform#2003]

**Comment by willdoran** [comment]
This is something I've wanted for a long long time, there is no technical reason not to be able to do this. We are only lacking UX mock ups to show how multiple images/videos would be displayed/entered on a Post.

@justinscherer @middle8media ?

**Comment by justinscherer** [comment]
@jshorland Where does this fit into our prioritization?

**Comment by jshorland** [comment]
I'm going to talk to @willdoran and @Angamanga today to see if it's possible to get this in, but it is the lowest priority as of now.

**Comment by willdoran** [comment]
This would be a lowest priority but if there is design for it, and we get through the other stuff we can do it.

**Comment by jshorland** [comment]
low. very low.

**Comment by middle8media** [comment]
@justinscherer this should be pretty simple to code out in the PL, but we need to sync on the design.

**Comment by justinscherer** [comment]
Photos on Twitter posts aren't working at all right now. That problem takes precedence over this one. Can't find the issue to reference.

**Comment by Erioldoesdesign** [comment]
@rowasc Consider the design side of this ticket for hacktoberfest/Google code in?

**Comment by rowasc** [comment]
@Erioldoesdesign that would be great yes!

**Comment by rowasc** [comment]
@Erioldoesdesign can you create a design ticket for it and reference from this one? 
This is something I'd love to have at some point so if someone can provide assistance on design it'd be awesome.

**Comment by tuxpiper** [comment]
Close as duplicate of #3319 , which has more conversation / info
