### ISSUE TITLE
Improve UX for mapped vs unmapped posts

### ISSUE THREAD

**Issue by dexwakhu** [ushahidi/platform#2005]
The total number of published posts has not been increasing despite additional posts being published. Furthermore when not logged in, the total number displayed varies despite all categories being selected.

### Notes
- Confirmed this has failed QA on Uchaguzi deployment 
- This didn't happen on http://qa.ushahididev.com/views/map.  Angie noted that this might be due to all posts having a location there, but not in uchaguzi. It might also be a case of the bug being fixed but uchaguzi not being up to date

## Current behavior in uchaguzi

- [ ] Displayed Posts on the map show a total of 47
- [ ] Categories on the left side add up to  54 ( Counting and Results Posts)

![image](https://user-images.githubusercontent.com/36038029/41849106-70c431fe-7888-11e8-9ed6-5c286d3222dd.png)

## Expected behavior:

- [ ] Displayed Posts on the map show a total of 47
- [ ] Categories on the left side add up to 47 ( Counting and Results Posts)

**Comment by dexwakhu** [comment]
Sample the two screenshots taken within a span of a couple of minutes. One shows 1365 posts and the other has been at 1400 since yesterday. Adding up the numbers per the categories on the left gives a figure of 1,849.
![Screen Shot 2017-08-11 at 00.31.36.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5892dafedfd7da1a00517efd/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455f26b7191a378ef0c2850415c48be5d4a1f06a3a3dc78e2a436628f595fecd0395c21c06b43aabf811fe901ba288a46d7b4e89850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec85af24be04451ad163164f43b.png)
![Screen Shot 2017-08-11 at 00.39.58.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5892dafedfd7da1a00517efd/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455f26b7191a378ef0c2858415a46be5d4a1f06a3a3dc78e2a436628f595fecd0395c21c06b43aabf811fe901ba288a46d7b4e89850d2aa6c7bb3d4d216744b470a83ed5b35a0934acd58f44fe14c5cac103567e4647b.png)

**Comment by rjmackay** [comment]
This could be due to inclusion of archived posts, or posts under review. Can you double check if you were logged in/out for both of these?

**Comment by dexwakhu** [comment]
Logged out for both of those for sure. When logged in, the number is 2800.

**Comment by willdoran** [comment]
The display for these numbers is broken, it doesn't update on change or delete. I've marked this as a bug.

**Comment by rjmackay** [comment]
Is this still an issue? https://github.com/ushahidi/platform-client/pull/726 should have resolved most of it. and I think https://github.com/ushahidi/platform/issues/2031 documents the remaining issue.

**Comment by dexwakhu** [comment]
​Just tried it and get two different counts of total published posts - 1436
in one instance and 1600 in another (wasn't logged in on either).

**Comment by crcommons** [comment]
@dexwakhu Can you try clearing your cache/local storage and then checking?

**Comment by aoduor** [comment]
@dexwakhu just a heads up that these aren't on uchaguzi.or.ke, and are on sandbox.uchaguzi.or.ke

**Comment by rowasc** [comment]
some data for future reference: 
- Expire date in Carolyn's Declan's and David's browser are wrong (August 8, September 21, Oct 12). Mine is fine so far .

**Comment by rjmackay** [comment]
This is unrelated to caching. The posts/stats endpoint is never cached. I need to retest and check when this happens

**Comment by caharding** [comment]
@rjmackay did you ever retest this, we need to prioritize for next Cycle

**Comment by rjmackay** [comment]
No I don't think this was ever retested and tracked down. Lots has changed since then so it'd be good to have this QA'd again

**Comment by caharding** [comment]
Added to QA Backlog for this cycle

**Comment by crcommons** [comment]
@rjmackay Are you retesting this cycle?

**Comment by rjmackay** [comment]
No. I have zero plans to work on this task.

**Comment by rowasc** [comment]
@Eve-wanderi can you confirm this was tested and passed/not passed? -as discussed earlier today, need to re-test-

**Comment by Eve-wanderi** [comment]
Find attached video.

[Video_6_22_2018_17_00_05_wmv.zip](https://github.com/ushahidi/platform/files/2127919/Video_6_22_2018_17_00_05_wmv.zip)

**Comment by rowasc** [comment]
@Eve-wanderi can you verify if clustering is enabled in uchaguzi?

**Comment by aoduor** [comment]
Flagging that when posts don’t have location info assigned to them, they will not show up on map mode either, but counter may match when on data mode. 

Could this be the reason why?

Angela Oduor Lungati,
Director of Community Engagement, 
Ushahidi | www.ushahidi.com <http://www.ushahidi.com/>
Twitter: @AngieNicoleOD <https://twitter.com/AngieNicoleOD> | @Ushahidi <https://twitter.com/ushahidi>
Skype: ngelzy

**Comment by rowasc** [comment]
@aoduor ohhh. Maybe, nice catch . I can check it when we work on it . Thanks!

**Comment by rowasc** [comment]
@aoduor if that's the case, would we want to show the totals counting only the posts with location, or the "real" totals?

**Comment by Eve-wanderi** [comment]
@rowasc Did a test like 5mins ago Clustering does not show. Regardless if am logged in or logged out.

![image](https://user-images.githubusercontent.com/36038029/41981726-49f5d20c-7a32-11e8-8d03-3b863d056460.png)

**Comment by aoduor** [comment]
> @aoduor if that's the case, would we want to show the totals counting only the posts with location, or the "real" totals?
@rowasc i'm torn on this one. I'm leaning heavily to it but worry about how to make sure user is aware of this when they're on data view as well(overkill) ? I might also be overthinking it. So let's got with, yes. show "real" totals.

@Eve-wanderi i think someone's likely just turned off clustering on it? it's been enabled from day 1. Confirm via the general settings page perhaps?

**Comment by jrtricafort** [comment]
Hey @aoduor @rowasc @Eve-wanderi I'm jumping on this ticket a bit late and want to get a better understanding of it. A few questions and comments:

1) Is this issue impacting only the Uchaguzi deployment? Or also are we also seeing it in core production for all .io?

2) @Eve-wanderi Regarding clustering, that was me. I turned off clustering on Uchaguzi while giving an Uchaguzi demo yesterday. My apologies for forgetting to turn it back on afterwards. I just turned clustering back on.

3) @aoduor Let's chat about whether or not to show Posts With Location vs. showing All Posts. I worked on a similar problem for a different product before, and think I can be helpful in figuring out a good path (and if it involves an enhancement to Map Mode or Data Mode). But first I'd love to understand our users' needs on this a bit more. I'll set up time on our calendars to discuss tomorrow. @rowasc We'll get back to you.

**Comment by aoduor** [comment]
Cool.

**Comment by Eve-wanderi** [comment]
@aoduor thanks for the heads up @jrtricafort okay noted!

**Comment by rowasc** [comment]
Assigned to @jrtricafort to ffollow up

**Comment by jrtricafort** [comment]
Moved to Cycle 7

**Comment by rowasc** [comment]
@jrtricafort super cool thanks

**Comment by crcommons** [comment]
@jrtricafort What is the solution for this? I'm not sure what to spec because we haven't yet defined what we want to display.

**Comment by jrtricafort** [comment]
@rowasc @crcommons 
Spoke with @aoduor about this today and we came up with a solution. It will actually be a front-end enhancement to the Map, and will require Design. Not a top priority for Design right now, so I'm going to move this out of this cycle to revisit in next cycle for design. But I'll add the scope details below in another comment and loop in Justin so he can start thinking about it. 

No dev work needed on this currently.

**Comment by jrtricafort** [comment]
@justinscherer This is the issue I was chatting w you about. 
Question: Can we display total number of posts in the map view? We currently show mapped (per survey type) and unmapped (in a line of text). Can we show the sum? 

For example, a more elegant version of this:
"There are 300 total posts. 254 mapped and 46 unmapped."

**Comment by justinscherer** [comment]
We already show this information:

<img width="980" alt="screen shot 2018-08-01 at 5 13 49 pm" src="https://user-images.githubusercontent.com/29209303/43553857-5313866c-95ae-11e8-8094-635dab670d39.png">

> "There are 22 posts not shown here because they don't include location information."

**Comment by rowasc** [comment]
Closing per Justin's comment above.
