### ISSUE TITLE
Image Fields Validation Error `The field 3-7 imagem teste must be a digit, Given: changed`

### ISSUE THREAD

**Issue by diegodorgam** [ushahidi/platform#2006]
### Expected behaviour
Save the survey with image fields on it

### Actual behaviour
Getting a Validation Error: The field 3-7 imagem teste must be a digit, Given: changed
`3-7 imagem teste` is the label of the field.
<img width="768" alt="captura de tela 2017-08-11 as 14 04 39" src="https://user-images.githubusercontent.com/12052193/29224839-57a58370-7ea2-11e7-802a-780bcb17a257.png">
This is only happening in one survey, one big survey with lots of activities and fields. 
When I create another survey, the image field works fine.

### Steps to reproduce the behaviour/error
It's worth mention that I've changed the order of the form stages in mysql, and changed the form_attributes table, adjusting some fields to the right form_stage_id, and all those worked fine. 

Other fields saves fine also, only the image fields are getting validation error, both those wich were created  before the changes and those new image fields created after the changes.

Checking on validator, found https://github.com/ushahidi/platform/blob/4f15e48da3f48013578a1793aad9df4e1a2ee246/application/classes/Ushahidi/Validator/Post/Media.php with the code:
```php
use Ushahidi\Core\Entity\MediaRepository;
class Ushahidi_Validator_Post_Media extends Ushahidi_Validator_Post_ValueValidator
{
	protected $media_repo;
	public function __construct(MediaRepository $media_repo)
	{
		$this->repo = $media_repo;
	}
	protected function validate($value)
	{
		if (!Valid::digit($value)) {
			return 'digit';
		}
		if (! $this->repo->exists($value)) {
			return 'exists';
		}
	}
}
```

Don't know what might be happening, I'm struggling to find out what this `digit` is...
Any thoughts?

**Comment by rjmackay** [comment]
This is live now on ushahidi.io and is in the current master branch
@diegodorgam let @tuxpiper know if you need help getting this into your deployment

**Comment by Desmond-S** [comment]
@rjmackay Hi what changes I had to do in the PHP files for this to take effect as am facing the same issue. Can you please guide me on this?

**Comment by tuxpiper** [comment]
@Desmond-S it was a change in the javascript source files (you will need to rebuild after you apply the changes). The diffs are here https://github.com/ushahidi/platform-client/pull/749

If you didn't download and build the source code but just got single file with everything pre-built , maybe you can try to update to the latest release here: https://github.com/ushahidi/platform-release/releases/download/v3.7.2-rc.2/ushahidi-platform-release-v3.7.2-rc.2.tar.gz

**Comment by Desmond-S** [comment]
Is it possible just to upload/update only files related to this instead of updating everything?

**Comment by tuxpiper** [comment]
It depends @Desmond-S , what do you have now to start with? Source files, or obscured and packed javascript? Which version?

**Comment by Desmond-S** [comment]
I used the platform release(php version) So If I could update the php/js files related to that it would help

**Comment by tuxpiper** [comment]
You may try overwriting the frontend files only (right inside the html folder) and leaving the backend (inside the html/platform) folder untouched. The frontend is distributed as a sort of monolith (for faster loading times), so there's no way to upgrade this sort of distribution selectively.

Just to be clear, this is totally unsupported by us. Depending on your current version things may break, because of frontend and backend being too different.

**Comment by Desmond-S** [comment]
How can I upgrade it to the latest version with all the changes, if I just copy all the downloaded files under html to the server will it work fine or we might face any issues. I tried that and changed the .env file. But so many errors popped up. Can you please guide me on this?

**Comment by tuxpiper** [comment]
@Desmond-S please refer to these instructions: https://www.ushahidi.com/support/upgrading-ushahidi#updating-your-deployment-to-the-latest-version . I hope they are useful.

Shall you have any further difficulties, please join our community chat at https://gitter.im/ushahidi/Community
