### ISSUE TITLE
Enforce category-permissions in the api

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2010]
### Expected behaviour
A child-category should always have the same permission as its parent. It should not be possible to save a child with different permission as its parent.

### Actual behaviour
There is no enforcement of this rule in the api, only in the client. A child and a parent can have different permissions.

**Comment by Angamanga** [comment]
Related to: https://github.com/ushahidi/platform/issues/1789

**Comment by rowasc** [comment]
@Angamanga closing in favor of https://github.com/ushahidi/platform/issues/2408
