### ISSUE TITLE
Missing survey fields on Android and iOS

### ISSUE THREAD

**Issue by dukedanny** [ushahidi/platform#2019]
### Expected behaviour
Fields created on Web on the .io deployment are supposed to show up when one adds/refreshes the deployment on the Android & iOS apps.
<img width="942" alt="sparkedwomen" src="https://user-images.githubusercontent.com/437728/29411779-ec850fe0-835e-11e7-8a43-5eeb0e594bc7.png">

### Actual behaviour
The survey fields appear cropped with some fields lacking.
![image uploaded from ios](https://user-images.githubusercontent.com/437728/29411807-01452000-835f-11e7-94c6-afeca6b91627.jpg)
![screenshot_20170816-130729](https://user-images.githubusercontent.com/437728/29411813-072fd10e-835f-11e7-99c2-6fbfc0716b0d.png)

### Steps to reproduce the behaviour/error
Add a deployment (Sparked Women in this case) to the mobile app > Respond to survey > Select the baseline survey.

**Comment by rjmackay** [comment]
@dalezak can you check this and confirm the bug if possible?
@dukedanny whats the URL of the deployment?

**Comment by dukedanny** [comment]
@rjmackay The URL is https://sparkedwomen.ushahidi.io

**Comment by dalezak** [comment]
Hi @dukedanny, I was able to track down the problem, looks like it's related to the _Are you in school?_ question being _required_. There's a bug in the radio button input control checking if it has a value or not. 

I'll submit an app update with a fix but in the meantime, can you try changing that question to being optional?

**Comment by dukedanny** [comment]
Thank you @dalezak. Making the radio button optional fixed the issue on my android app view.

**Comment by dalezak** [comment]
This will patched in upcoming `1.5` release of the app... closing issue.
