### ISSUE TITLE
Block API access for users who haven't accepted TOS

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2020]
### Expected behaviour
Users who don't accept TOS can't access any data

### Actual behaviour
Users who don't accept TOS are block from frontend, but not backend

### Notes

- It might make sense to simply treat them like a non-logged in user until they accept the terms
- Or we can deny access entirely.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-534

**Comment by rjmackay** [comment]
Refs #1772

**Comment by rjmackay** [comment]
@willdoran any thoughts on how best to manage this?

**Comment by jshorland** [comment]
@willdoran do you know if this is still relevant??
