### ISSUE TITLE
Don't make initial admin user agree to Terms Of Service

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2026]
### Expected behaviour
When I create a deployment I should not be prompted to agree to terms of service, because I already agreed to them in ushahidi.io/create

### Actual behaviour
I am asked to agree to terms of service *again* on my first login

### Steps to reproduce the behaviour/error

Refs https://github.com/ushahidi/platform/issues/1772

**Comment by jshorland** [comment]
@rjmackay clarifying question: do you mean that initial admin that have already created a deployment before this change goes into effect would not need to agree to the ToS?

**Comment by rjmackay** [comment]
AFTER. Those who already created a deployment need to be prompted, since the terms have changed. But new deployment agree to terms during creation.

**Comment by rjmackay** [comment]
Passes QA!
