### ISSUE TITLE
CSV file should include ALL survey fields even if empty

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2027]
### Expected behaviour
CSV file should include ALL survey fields even if empty

### Actual behaviour
CSV file only includes survey fields that have values

### Steps to reproduce the behaviour/error

Aha! Link: https://ushahiditeam.aha.io/features/PROD-533

**Comment by rjmackay** [comment]
Ref https://github.com/ushahidi/platform/issues/1968

**Comment by diegodorgam** [comment]
hey guys, @rjmackay @Angamanga ,

any updates here on this issue?

**Comment by diegodorgam** [comment]
this one seems to be ready, right @rjmackay ?

**Comment by rjmackay** [comment]
I don't believe this was worked on. @rowasc can clarify it it was covered by other PRs, but I don't think so.

**Comment by rowasc** [comment]
@rjmackay correct, we have not implemented this feature .

**Comment by rowasc** [comment]
Flagging that this one isn't clear because we've been asked to do the opposite as well. Tagging with Data export to review
