### ISSUE TITLE
Improving our filtering

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2035]
I've been playing around with other tools that use filters (airbnb, intercom, chargebee, etc) and here's my suggestion for how our filtering system SHOULD work (I have put this entirely into new issue # so we can go ahead and push this fix and then address the rest of the issues separately):

When I open the filter modal, I want to see ALL things I can filter by, INCLUDING surveys and categories. Currently, surveys and categories are only filterable in the context modal, and though this may seem like a redundancy, I might be creating a complex saved search and I don't want to filter in two places as a user. It's more work for me. put them all in the filter modal, and keep surveys/categories in the context bar as well.

When I click a filter anywhere, I want it to update as I click/unclick. Why? Based on conversations with @justinscherer, we are trying to move to a more efficient way of viewing data in either map or list view instead of clicking back and forth inefficiently. From a similar efficiency perspective, the day may come when a user sees data as they filter it (right now, it's in the background of the filter modal). As a user creating a set of filters to drill down on my data, I want to preview how those filters affect what I'm seeing as I do the action of filtering itself. Then, once I hit "apply", I know for sure that that filter set is what I want to see instead of moving back and forth between a filter modal and data to try to get it just right. (This was inspired by my usage of Airbnb filters and being really annoyed that it didn't update as I clicked a filter on or off, only when i clicked "apply", and then my filters would disappear and I'd have to reopen and hope I got my filtering right the next time).

When I click "clear filters" I just want them all to clear. As a user, i've most likely spent a good amount of time drilling into and browsing my data in a filtered view, and probably clicked on several paths/levels of filters during that journey. "CLEAR" to me means clearing ALL of it. This is where to @justinscherer's point, an "UNDO" action would be helpful. To me, undo means undo'ing my most recent action, and "clear" means undoing all of it.

**Comment by rjmackay** [comment]
Ok cool. We should probably resolve how categories and survey filters interact soon too, then make that consistent between the modal and the context bar.
