### ISSUE TITLE
User's logins,failed_attempts, last_login, last_attempt are not being saved.

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2036]
Actual behavior:
- logins,failed_attempts, last_login, last_attempt are not being saved in the user table.
Expected behavior: 
- logins,failed_attempts, last_login, last_attempt should be saved

Aha! Link: https://ushahiditeam.aha.io/features/PROD-530

**Comment by jshorland** [comment]
@rjmackay I've prioritized this as P2 for now -- but i might be wrong? any negative consequences to this besides the obvious of not seeing issues with login?

**Comment by rjmackay** [comment]
P2 should be fine. It'd be useful data to have for future metrics. Easier to fix once Lumen integration lands
