### ISSUE TITLE
Provide embedded map view with no UI elements

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#2037]
(from: https://git.hacklab.com.br/relacionais/ushahidi/issues/1 )

### Expected behaviour
When embedded in wide browser containers, there should be the option not to display the UI elements for survey selection, header, filtering etc.

### Actual behaviour
The only option is to have the map embedded with all surrounding UI elements.

**Comment by diegodorgam** [comment]
the view should be something like this:
![captura de tela 2017-09-05 as 12 47 27](https://user-images.githubusercontent.com/12052193/30070043-a4cc842e-9238-11e7-893c-990d75149bff.png)

but in full width view, so we can put it embeded in a website.

**Comment by Angamanga** [comment]
> The view should contain the markers, ushahidi logo, zoom controls, openstreetmaps signature and just it =)

@diegodorgam In the photo, there is a filter-button too, do you want that included in the embed as well?

**Comment by diegodorgam** [comment]
not needed @Angamanga

**Comment by diegodorgam** [comment]
Hi @Angamanga 

any update here?

**Comment by Angamanga** [comment]
@diegodorgam: Its in code review, you can see the code here: https://github.com/ushahidi/platform-client/pull/754

**Comment by diegodorgam** [comment]
great @Angamanga, nice work, it seems to be merged already!
How can we use it?

**Comment by tuxpiper** [comment]
Hi @diegodorgam , we will issue a new rc release shortly

**Comment by diegodorgam** [comment]
great @tuxpiper @Angamanga !

It worked perfectly, it's already in dev environment at https://dev.tonarede.org.br/

Thks!

**Comment by Angamanga** [comment]
@diegodorgam So nice to hear! :+1:

**Comment by diegodorgam** [comment]
Hi @Angamanga @tuxpiper 

I'm so really sorry to come back to this issue, but I've made a mistake, my client wants to add the search filter to the embedded viz. 
I know I've said that we wouldn't need that, and I've made a mistake.
Could We reopen this issue to implement the same viz with the search filter?
thks in advance...

**Comment by tuxpiper** [comment]
Hi @diegodorgam 

we're pretty focused on the re-run of the kenyan elections and preparing a bunch of features for it, so it will take us a little to get back to this and see how hard it would be to do.

Meanwhile, is there any specific way your client would like the search bar to appear? Would it be like the standard narrow view, but without the top and bottom bars?

<img width="1006" alt="screen shot 2017-10-18 at 13 59 00" src="https://user-images.githubusercontent.com/467393/31717547-b022d1fc-b40c-11e7-87dc-5debbe1abd77.png">
