### ISSUE TITLE
It's not possible for users without permission to view posts "In review" to view their own posts and edit them before they are published

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2042]
### Expected behaviour
As a member or any other user WITHOUT "manage posts" permission, I should be able to still find and edit my own posts. 

### Actual behaviour
If i delete the default "my posts" saved search, I can't find my posts ANYWHERE. It's so confusing!

My suggestion would be to add a permanent link to "my posts" somewhere. But where makes the most sense? At the moment, my initial thought is to put it in as a permanent filter when I'm logged in. @rjmackay is this possible?

Aha! Link: https://ushahiditeam.aha.io/features/PROD-528

**Comment by jshorland** [comment]
cc: @Celestine22 @natmanning here's the issue that would affect dentaquest at the moment. For the moment, make sure the "my posts" default saved search stays there and they can find their posts and edit them through that, EVEN IF they don't have the manage posts permission.

**Comment by rowasc** [comment]
This still happens, if you reload the page your post is gone since it's under review :( .

**Comment by rowasc** [comment]
update after more tests : 
- while I have a "my posts" saved search with admin I don't have it with the "member" role user. 
- If I reload the page my post is gone, but if I after I reload the page I click "clear filters", it comes back 🤔 

So now it might be something about filters, not sure.

**Comment by Erioldoesdesign** [comment]
Waltzing in suggesting that this could/should live under the user profile. However! if a user hasn't got a profile then perhaps it can be the top most post in data view or have a special pin type on the map.

I think this is important not only from a 'technical pov' but also from a ux pov. Lots of deployment owners would want this to be better if they knew it was a bit broken.
