### ISSUE TITLE
CSV Export is not using the same filters applied by the user in the client. 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2045]
See ushahidi/platform#2044 for the specific example from which this ticket was created. Most likely that it's all the same issue.
Nat also reported this in ushahidi/platform#2048 with DocumentHate 

### Steps
Precondition: the deployment has posts 
## Steps to reproduce: 
- Go to timeline view, set any filters. 
- Click Share
- Select "Export"
- Download CSV file. 

### Expected behaviour
Set a filter, Export CSV, and the CSV will only have the data in the filter

### Actual behaviour
The CSV export has all the data, not the filtered amounts

**Comment by rowasc** [comment]
More info: The CSV export request is sending only the `format: csv` parameter, and no specific filters. 
ie: {hostname}/api/v3/posts/export?format=csv

**Comment by rowasc** [comment]
@jshorland @tuxpiper this is ready for testing.

**Comment by Shadrock** [comment]
Hey guys: this has come up again for COMRADES and is a somewhat major issue for the evaluations.  This from the COMRADES partner running the evaluations: 
> can they export all the report to CSV / Excel? It seem when we click 'share' -> CSV we get empty lists

My guess is that it's about 3-day job and I would really like for it to get prioritized soon. I know that both @willdoran is aware of it but want to make sure that @jshorland is aware and can prioritize / schedule as necessary.

**Comment by jshorland** [comment]
@willdoran @rjmackay maybe will tackles this once he gets back from Nairobi?=


Sent from my iPhone

> On Dec 1, 2017, at 1:58 AM, Shadrock Roberts <notifications@zube.io> wrote=
:
>=20
> Shadrock Roberts mentioned you in Card #3333 (ushahidi/platform #2045) CSV=
 Export is not using the same filters applied by the user in the client.=20
> Hey guys: this has come up again for COMRADES and is a somewhat major issu=
e for the evaluations. This from the COMRADES partner running the evaluation=
s:
>=20
> can they export all the report to CSV / Excel? It seem when we click 'shar=
e' -> CSV we get empty lists
>=20
> My guess is that it's about 3-day job and I would really like for it to ge=
t prioritized soon. I know that both @willdoran is aware of it but want to m=
ake sure that @jshorland is aware and can prioritize / schedule as necessary=
.
>=20
>=20
>=20
>=20
> You are receiving this notification because you are subscribed to this ite=
m.=20
> You can change your notification settings for this project at https://zube=
.io/ushahidi/platform/edit/notifications

**Comment by rjmackay** [comment]
Yup. That would make sense - assuming this is *actually* the same issue and just a case of migrating the same fix onto Comrades deployments. If its a deeper issue we need to estimate effort and evaluate.

**Comment by rowasc** [comment]
@jshorland as I understand it, this issue was about a problem where comrades branches were not up to date with platform-client develop/master branch (not the specific filter issues, but a more general filter issue where filters were just ignored completely, which we fixed back in Sept. ) 
I think @willdoran had merged things back, so it should be closed already
