### ISSUE TITLE
Should post counts in survey filter be effected by category filtering?

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2047]
### Expected behaviour
Not sure

### Actual behaviour
Post counts for survey filters are effected by other filters (ie. status) but not by categories.

### Background

> We fixed the issue where totals didn't update *at all* based on other features, but we excluded categories. Because they're children of the survey, I didn't think it made sense that the total for a survey would change when the category filter changes. However now I'm less sure.
> 
> Its confusing because the totals are visible even for a survey/source thats excluded from the current results.

Refs ushahidi/platform#1967 ushahidi/platform#1997

**Comment by rowasc** [comment]
@jshorland what is the expected behavior in this ticket? 
Thanks
