### ISSUE TITLE
CSV Export Filter not working

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#2048]
### Expected behaviour
Set a filter, Export CSV, and the CSV will only have the data in the filter

### Actual behaviour
The CSV export has all the data, not the filtered amounts

### Steps to reproduce the behaviour/error
Doing this on DocumentHate. Set a filter, and then export CSV, and see if it exports all data or the filtered amounts

**Comment by jshorland** [comment]
Closing this issue in favor of #2045
