### ISSUE TITLE
Can't submit survey response while VPN is active on iOS

### ISSUE THREAD

**Issue by CR0CKER** [ushahidi/platform#2055]
### Expected behaviour
Mobile app should submit survey responses while VPN is on, which is the only option for users in China since Ushahidi is blocked by the GFW.

### Actual behaviour
Mobile app gives an error message when trying to submit a response while VPN is turned on. Other apps are working fine, so it's not a bad data connection.

### Steps to reproduce the behaviour/error
Turn on VPN, try to submit an anonymous response to an open/unprotected survey while in China.

![img_1854](https://user-images.githubusercontent.com/6056387/30305389-3d9bbde8-97a5-11e7-8f94-e2ed71331cbc.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-526

**Comment by rjmackay** [comment]
@dalezak any idea why this might happen?

**Comment by dalezak** [comment]
Hmm, that's interesting, I'd need to test it locally to see why that's happening.

**Comment by rowasc** [comment]
@dalezak do you remember if you were able to reproduce this issue? (or can you still reproduce it? )
