### ISSUE TITLE
Confusing import notification - shows user a success message when it's not importing any fields because of a formatting issue

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2056]
Note: remove the .txt file extension before using each file. 

### Expected behaviour
If the CSV format is not correct, users should see and error.
### Actual behaviour
If the CSV has more columns in the header than in the content rows, it fails to import, but it shows a "successful" import of zero items. 
### Steps to reproduce the behaviour/error
- [ ] Go to Settings -> Import 
- [ ] Upload [thisfails.csv.txt](https://github.com/ushahidi/platform/files/1297460/thisfails.csv.txt)
 and select any survey to import it to.
- [ ] Map the required fields to fields in the CSV  (ie:  Title-> Name, Description-> Previously used names)
- [ ] Finish import. 
- It will show you a success message but it won't import anything. We probably want to make it more obvious to the user. 
![screen shot 2017-09-12 at 6 17 53 pm](https://user-images.githubusercontent.com/2434401/30348993-ac5d8468-97e7-11e7-8ac6-470c7ef513f9.png)

`Using this file, the import works fine.`
[thisworks.csv.txt](https://github.com/ushahidi/platform/files/1297459/thisworks.csv.txt)

**Comment by aoduor** [comment]
Also confirming that one of our users is experiencing this same issue. Opened up his CSV file and couldn't detect the line endings. Recreated my own CSV from it and it worked out fine. 

So guessing there's two issues here:
1. Formatting issues with certain CSV files
2. Confusing import notification

**Comment by caharding** [comment]
@jrtricafort thinking this is a won't fix yeah?

**Comment by rowasc** [comment]
This could not be confirmed so I'm closing but linking to #1448 as related to explaining why an import failed so users can take action
