### ISSUE TITLE
Allow setting the display language through the URL

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#2062]
### Expected behaviour
As a deployer, developer or embedder, I would like the platform client to accept a query parameter or URL fragment that sets the language to be displayed to the user opening that URL.

Use case scenario example:

* On my content management system site, I've got English and Arabic sections.
* On the English side of my site, I would like my users to be led to an English version of my Ushahidi platform deployment (link/embed to http://my.deployment.com/?lang=en-us )
* On the Arabic side, to the Arabic version of the platform (link/embed to http://my.deployment.com/?lang=ar-ar)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-525

**Comment by Celestine22** [comment]
This is RAD! Would be good to have thing in our roadmap

**Comment by Angamanga** [comment]
I am leaning towards archive here.
