### ISSUE TITLE
As a platform manager, I want to be able to add "other" with free text as an option for a response

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2064]
### Expected behaviour
If i'm asking a multiple choice, radio, or checkbox question, I often want to give them the option to select "other" and provide free text as to what that other is.

### Actual behaviour
I have to add "other" as an option, and then add ANOTHER question after that if I want them to expand on/give more details about "other"

### Steps to reproduce the behaviour/error

Aha! Link: https://ushahiditeam.aha.io/features/PROD-524

**Comment by justinscherer** [comment]
@jrtricafort @caharding this will get handled in the [UI refresh.](https://app.zenhub.com/workspace/o/ushahidi/platform-pattern-library/issues/205)
