### ISSUE TITLE
Ability to search different categories from multiple surveys instead of individual searches per survey

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#2066]
### Expected behaviour
I should be able to filter different categories from different surveys at a time
### Actual behaviour
I can only filter categories per survey which is limiting

@rjmackay @jshorland @willdoran I know this was implemented on Uchaguzi, any chance we are pushing this back to platform, Enterprise clients biggest concerns happens to be this right now when creating saved searches.

**Comment by rowasc** [comment]
<img width="447" alt="Screen Shot 2019-06-09 at 23 15 04" src="https://user-images.githubusercontent.com/2434401/59168516-6f9ded00-8b0c-11e9-8e94-b56a97c58fb0.png">
Closing. This is available now since we ported back the filters dropdown after uchaguzi .
