### ISSUE TITLE
Privacy Policy Mobile

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2068]
@dalezak on Oct 20th we need all mobile users to click to accept a new privacy policy as they will on desktop in issue #1772 

- [ ] User logs in
- [ ] User is presented with a dialogue that says we have changed our privacy policy and it must be clicked to accepted, user can also click on privacy policy to read it
- [ ] User's reponse is logged as it is in #1772

**Comment by rjmackay** [comment]
@dalezak did you see this? Was this done?

**Comment by jshorland** [comment]
@dalezak we can close this now, right?

**Comment by dalezak** [comment]
Yup, fixed in https://github.com/ushahidi/platform-mobile/issues/161... closing issue.
