### ISSUE TITLE
When changing default language to arabic, the entire deployment breaks

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2074]
### Expected behaviour
Changing to arabic should change the translated text within the deployment to arabic, as it would with any other language switch. 

### Actual behaviour
everything goes crazy. it seems like the formatting goes nuts and its a huge logo. 

### Steps to reproduce the behaviour/error
login as admin to qa.ushahididev.com
go to settings --> general
change default language to arabic
reload
Also happening here as reported by user on intercom: 
https://iafhrbasra.ushahidi.io/views/map

**Comment by jshorland** [comment]
hmmm doesn't appear to be happening in qa anymore. It's just not translating at all.

**Comment by rjmackay** [comment]
This should be fixed in production now.
