### ISSUE TITLE
Better integration with spreadsheets or multiple data sources

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#2076]
### Expected behaviour
As a deployer I want to:

1. update my deployment with posts submitted via a Google spreadsheet; an Excel file in a shared Dropbox Folder; or something similar; and
2. update my deployment from _multiple_ spreadsheets that may exist in a variety of places online. I may be using one Google form/sheet for my own organization but may also want to incorporate data in another spreadsheet from a source like [HDX](https://data.humdata.org/) or a local organization's Excel file. 

### Actual behaviour
I can upload a .csv or I can download a .csv. I have no idea how to configure an API for my deployment. 

### Justification
Spreadsheets are the de facto data format of humanitarian and development data. Many well-intentioned and very smart people have pitched me products only to be stymied by this simple yet unrelenting fact. But, hey, why take my word for it? 

- [HDX can live-link to and preview files stored in any Dropbox folder and even preview them if they are in CSV or XLS format](https://data.humdata.org/faq).
- [Humanitarian consultants assume and build services based on the use of spreadsheets](https://sarapis.org/introducing-data-models-for-humanitarian-services/). 
- [The Humanitarian Exchange Language was built to work in spreadsheets because, after a lengthy review, that's what users told them](http://hxlstandard.org/questions/approach/). 
- [It's common to see Excel tips and tricks as a critical part of training for even "technical" humanitarian staff](https://www.humanitarianresponse.info/en/applications/tools/category/training). [Here's an example of the Red Cross training people on how to use spreadsheets](https://medium.com/@mjwhansen/six-things-i-learned-building-the-harvey-geocod-io-twitter-rescue-requests-map-2c78127664a3) by incorporating Hurricane Harvey data.

Then, of course, you have many recent examples of online volunteers putting together quick, flexible, and highly successful crowdsourcing efforts precisely _because you don't need to train people on how to use it._ Team Rubicon shared data with responders using spreadsheets ([news article here](http://money.cnn.com/2017/08/28/technology/volunteers-harvey-rescue-apps/index.html)); Google forms and sheets were used to great effect during Hurricane Harvey ([news article here](https://www.washingtonpost.com/national/texans-do-it-ourselves-rescue-effort-defines-hurricane-harvey/2017/09/02/f41bb8ee-8f2f-11e7-8df5-c2e5cf46c1e2_story.html?utm_term=.4184703d2055)); Twitter is littered with different groups that use spreadsheets as a way to share information ([one example here](https://twitter.com/dianelyssa/status/902684786107482113)).

Aha! Link: https://ushahiditeam.aha.io/features/PROD-520

**Comment by Shadrock** [comment]
As I was writing this, someone put together a [spreadsheet of rescued persons for the Mexico earthquake](https://docs.google.com/spreadsheets/d/1-wQmdIyu0CWtvuz2CLLUiGaBmV-t1mtgEM8d_tWn0sQ/edit#gid=0).

**Comment by caharding** [comment]
Shadrock, I have a question about this. CSV is a standardized form of spreadsheet. Any Google or Excel sheet can be exported easily saved as a CSV to then import into Ushahidi.

We don't include Excel and Google import methods b/c it requires frequent updating to enable all different versions of these documents. Microsoft makes such frequent updates to Excel, that it is very difficult to stay current with them. 

I saw this was tagged for Cycle 3. Is this expected to be completed?
