### ISSUE TITLE
2chauzi Facebook Bot

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2080]
Minor feature improvements would make major user enhancements on the bot. This is the minimum scope that I would recommend for 2chaguzi. I'll open an additional issue for other bot issues to be prioritized. 

- [ ] Remove block to getting started, update into text to: “Hello! Welcome to Uchaguzi Citizen Reporter. Uchaguzi’s aim is to help Kenya have a free, fair, peaceful, and credible general election. Keep an eye on the vote and submit any reports of issues that impact the election. In a few words, describe what you would like to report.”
- [ ] FB bot should not hit rate limit as a single user
- [ ] Reports from Facebook should be tagged as “via Facebook Messenger”
- [ ] Remove survey mapping from bot
- [ ] Gather report after 30m timeout, even if the user doesn’t hit submit, after which a new report will be started if they begin chat again
- [ ] Language switching to Swahili

References ushahidi/platform#1702

**Comment by jshorland** [comment]
Why is this closed? Can I reopen?

**Comment by jshorland** [comment]
@Angamanga would you be able to provide an estimate of level of effort/time to implement these baseline changes? Do you think you could get it done before elections on the 26th?

**Comment by Angamanga** [comment]
@willdoran Could we look at this together and estimate time/effort today?

**Comment by willdoran** [comment]
@Angamanga Does the fb bot have translation setup?

**Comment by Angamanga** [comment]
@willdoran there are translations and the db-table with answers is prepared to handle other languages but I have not implemented the switcher...

**Comment by willdoran** [comment]
@Angamanga OK cool
so I would add implement translations to this list
The first 4 seem straightforward, the 5th one needs confirmation of how it can be done. 
But I would estimate a total of 3-4 days if the 5th has a defined pattern. But you'd need to check on how the 5th can be implemented and add days depending on how complex it might be.

**Comment by caharding** [comment]
@jshorland is this going to be getting into 2chaguzi? Would be helpful to know expectations. Should update FB too. Thanks
