### ISSUE TITLE
2chaguzi Facebook Bot Improvements

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2081]
This epic includes
- participate in research within Comrades for chatbots
- write user-documentation for both devs and users of the bot (requirement for Comrades)
- testing that auth does not fail when sending reports from bot to platform (this can be tested once Lumen is landed)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-519

**Comment by caharding** [comment]
Dupilcate #2080 closing

**Comment by jshorland** [comment]
This will be handled AFTER the massive layout changes and data grooming improvements

**Comment by caharding** [comment]
Rate limiting is a platform authorization issue which will be fixed by Lumen

**Comment by rowasc** [comment]
@willdoran do you know if any of the changes we are backporting to kohana going to solve this? 
`testing that auth does not fail when sending reports from bot to platform (this can be tested once Lumen is landed)`

**Comment by willdoran** [comment]
@rowasc This should be retested, though I'm not sure if we have a set up that can be used for test. @Angamanga do we have a working facebot somewhere?
