### ISSUE TITLE
The creation of `timeAgo` translation within PostListDirective leads to various date display problems

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2084]
As discussed with @willdoran , there are two versions of localized dates being displayed in the /views/list timeline.

This leads to (1) a possible mismatch of dates displayed, and due to relying on this directive to translate dates, (2) this also complicates the refresh of the component upon a language change.

The post-metadata.directive relies on using moment.js locales to construct dates, however, the PostViewList version is assembled using the Transifex `nav.today` translation tag, as seen here:

In post-view-list.directive.js:
```
return _.groupBy(posts, function (post) {
            var postDate = moment(post.post_date);
            if (now.isSame(postDate, 'd')) {
                return $translate.instant('nav.today');
            } else if (yesterday.isSame(postDate, 'd')) {
                return $translate.instant('nav.yesterday');
            } else {
                return postDate.fromNow();
            }
        });`
```

This issue is to consider creating a component or block that separates the formatting of a date from the process of grouping posts.

**Comment by willdoran** [comment]
@kinstelli I think a simple solution will be to change the output html in post-view-list.html

We should probably group by date or timestamp in the directive then translate in the actual html.

**Comment by kinstelli** [comment]
@willdoran  - I totally agree. I rewrote the function above to just return raw dates, for angular-moment's *am-time-ago* to interpret. That approach mostly works, but it needed tweaks to ensure that the posts are grouped by day, rather than minute-by-minute (i.e., stripping the time portion from the date). I still want to figure out how to configure *am-time-ago* to only show day info, rather than hourly differences ('today' rather than a misleading '12 hours ago'), if that's possible. I'll post a WIP PR when I have the chance for a concrete example.

Meanwhile, moment.js is still stubbornly refusing to change locales consistently (I'll post this as a  separate issue). This still, unfortunately, breaks some of the immediate-priority languages. Several open issues on moment.js' repo describe very similar problems, but proposed workarounds mostly involve loading all locale files up-front, rather than dynamically. I'm not sure if that's too much overhead, but these are tiny files, so maybe it's negligible.

**Comment by willdoran** [comment]
@kinstelli Is there a PR for this I should look at?

**Comment by rjmackay** [comment]
I think this is irrelevant with data view?
