### ISSUE TITLE
Several sources of mixed content

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#2086]
Some external URLs are hardcoded to http://... causing mixed content errors when platform is hosted in a https domain

i.e.

```
angular.js:3663 Mixed Content: The page at 'https://tuxpiper.ushahidi.io/posts/create/9' was loaded over HTTPS, but requested an insecure image 'http://www.gravatar.com/avatar/%7B%7B%20post.user.gravatar%20%7C%7C%20'00000000000000000000000000000000'%20%7D%7D?d=retro&s=40'. This content should also be served over HTTPS.
```

**Comment by tuxpiper** [comment]
on top of gravatar , we have lorempixel and openstreetmap tiles

**Comment by tuxpiper** [comment]
We issued a hotfix for the http:// links to resources , but we may want to do a full scan and decide what to do with those where https:// is hardcoded

From ushahidi/platform-client#761

> there are 2 other places where gravatar is used, not relative (but https)
> app/common/directives/mode-bar/mode-bar.html
> and
> app/settings/users/users.html.

**Comment by rjmackay** [comment]
Gravatar didn't support https last I checked

**Comment by tuxpiper** [comment]
We are no longer getting mixed content source warnings and wherever we have hardcoded https , that's probably fine. I think it's safe to close this.
