### ISSUE TITLE
local storage client cache doesn't always expire

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#2088]
Today I've had an instance where I was being misled to think that a deployment was empty, when it fact it had over 500 posts.

A few hours ago the deployment had two empty surveys . Overnight, the owner deleted those surveys and created a new one. My local cache still remembered those two original surveys and kept ignoring the new one. Nothing would change its mind.

Peeking into local storage, I could see that the cache object expiration time was already well past, but for some reason the cache layer in the client was failing to invalidate it.

Cleaning local storage fixed the issue.

I tried to reproduce elsewhere to no avail, so I'm not sure what causes this behaviour.

**Comment by tuxpiper** [comment]
This is still happening 3 weeks later !

This is https://mexico.ushahidi.io in my usual browser session:

![screen shot 2017-10-17 at 10 08 18](https://user-images.githubusercontent.com/467393/31653524-2814aed2-b323-11e7-8cfd-ad95eb594db0.png)

it's showing surveys that were deleted more than 3 weeks ago.

This is what the site looks like on an incognito session:
<img width="1441" alt="screen shot 2017-10-17 at 10 10 10" src="https://user-images.githubusercontent.com/467393/31653595-67686df8-b323-11e7-948a-48eff1edb9fb.png">

I'm wondering how many people are being affected by this.

**Comment by tuxpiper** [comment]
Here's a glimpse into the local storage contents:

```
ls.accessToken:"25tRBYDriDmMCWCDt56a589bhrdtty591PGHvNPv"
ls.language:"en"
ush-caches.attrCache.keys:[]
ush-caches.formCache.data.https://mexico.api.ushahidi.io/api/v3/forms:{"key":"https://mexico.api.ushahidi.io/api/v3/forms","value":[200," {\"count\":2,\"results\":[{\"id\":1,\"url\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/forms\\/1\",\"parent_id\":null,\"name\":\"Se necesita...\",\"description\":\"Formato de solictud de ayuda\",\"color\":\"#5BAA00\",\"type\":\"report\",\"disabled\":false,\"created\":\"2017-09-22T17:51:02+00:00\",\"updated\":\"2017-09-22T18:32:58+00:00\",\"hide_author\":false,\"require_approval\":true,\"everyone_can_create\":true,\"can_create\":[],\"tags\":[{\"id\":1,\"url\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/tags\\/1\"}],\"allowed_privileges\":[\"read\",\"search\"]},{\"id\":2,\"url\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/forms\\/2\",\"parent_id\":null,\"name\":\"...se ofrece\",\"description\":\"\\u00bfC\\u00f3mo puedes ayudar?\",\"color\":\"#5BAA00\",\"type\":\"report\",\"disabled\":false,\"created\":\"2017-09-22T18:54:54+00:00\",\"updated\":null,\"hide_author\":false,\"require_approval\":true,\"everyone_can_create\":true,\"can_create\":[],\"tags\":[{\"id\":1,\"url\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/tags\\/1\"}],\"allowed_privileges\":[\"read\",\"search\"]}],\"limit\":null,\"offset\":0,\"order\":\"asc\",\"orderby\":\"id\",\"curr\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/forms?orderby=id&order=asc&offset=0\",\"next\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/forms?orderby=id&order=asc&offset=0\",\"prev\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/forms?orderby=id&order=asc&offset=0\",\"total_count\":2}",{"content-type":"application/json"},"OK","complete"],"created":1506160803612,"accessed":1508736096573,"expires":1506161703612}
ush-caches.formCache.keys:[]
ush-caches.roleCache.keys:[]
ush-caches.stageCache.keys:[]
ush-caches.tagCache.data.https://mexico.api.ushahidi.io/api/v3/tags:{"key":"https://mexico.api.ushahidi.io/api/v3/tags","value":[200," {\"count\":1,\"results\":[{\"id\":1,\"url\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/tags\\/1\",\"parent_id\":null,\"tag\":\"Derrumbe\",\"slug\":\"derrumbe\",\"type\":\"category\",\"color\":null,\"icon\":\"tag\",\"description\":null,\"priority\":99,\"created\":\"2017-09-22T17:52:57+00:00\",\"role\":null,\"children\":[],\"allowed_privileges\":[\"read\",\"search\"]}],\"limit\":null,\"offset\":0,\"order\":\"asc\",\"orderby\":\"id\",\"curr\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/tags?orderby=id&order=asc&offset=0\",\"next\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/tags?orderby=id&order=asc&offset=0\",\"prev\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/tags?orderby=id&order=asc&offset=0\",\"total_count\":1}",{"content-type":"application/json"},"OK","complete"],"created":1506160803668,"accessed":1508736096565,"expires":1506161703668}
ush-caches.tagCache.keys:[]
ush-caches.userCache.data.https://mexico.api.ushahidi.io/api/v3/users:{"key":"https://mexico.api.ushahidi.io/api/v3/users","value":[200," {\"count\":3,\"results\":[{\"id\":2,\"url\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/users\\/2\",\"realname\":\"Alex Lopez\",\"allowed_privileges\":[\"read\",\"search\",\"register\"]},{\"id\":3,\"url\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/users\\/3\",\"realname\":\"xico\",\"allowed_privileges\":[\"read\",\"search\",\"register\"]},{\"id\":4,\"url\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/users\\/4\",\"realname\":\"xico\",\"allowed_privileges\":[\"read\",\"search\",\"register\"]}],\"limit\":null,\"offset\":0,\"order\":\"asc\",\"orderby\":\"id\",\"curr\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/users?orderby=id&order=asc&offset=0\",\"next\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/users?orderby=id&order=asc&offset=0\",\"prev\":\"https:\\/\\/mexico.api.ushahidi.io\\/api\\/v3\\/users?orderby=id&order=asc&offset=0\",\"total_count\":3}",{"content-type":"application/json"},"OK","complete"],"created":1506160803664,"accessed":1508736096563,"expires":1506161703664}
ush-caches.userCache.keys:[]
```

**Comment by rowasc** [comment]
Writing down notes as I check the code so we can discuss where and when it should be fresh vs cached. 

General notes: 
-         cache.removeAll(); is used in : `FormEndpoint.queryFresh = function () { `  . I'm not sure if that's correct? Need to dig a bit into that... it might be OK since the cache actually references the forms cache not the whole cache. 


Forms Endpoint cache is not used a lot, except for this 3 places: 
- function loadForm(form) { in post-card.directive.js
- this.requestsFiltersData = function () { in filter-transformers.service.js
- $scope.form = FormEndpoint.get({ id: post.form.id }, function (form) {     in post-edit.controller.js
`I really don't think we should  use the cached version in edit. I think we really should make sure the structure is correct at edit and create times or we might end up asking the user to fill in the form and it's not the correct form. For most scenarios I think we can use the cached versions if available, so this needs to be reviewed for a lot of places where we call queryFresh or getFresh`
