### ISSUE TITLE
Can't create categories with special (i.e. 'á') or non-latin characters

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#2089]
Creating a category containing anything other plain latin characters and digits causes the following error:

> Validation Error slug must contain only numbers, letters and dashes

At this point, most non-English users have to resort to workarounds (such as creating the category with plain digits and numbers first, then rename it to whatever they originally intended)

It seems that we don't do a lot of handling for slugs in general (see #758) , but for some reason the validator is being more restrictive on tag slugs than it is on say.. post or survey slugs.

**Comment by rowasc** [comment]
<img width="1201" alt="Screen Shot 2019-06-10 at 21 54 11" src="https://user-images.githubusercontent.com/2434401/59235958-5f4c4780-8bca-11e9-9650-2cd8a75d7a48.png">
<img width="666" alt="Screen Shot 2019-06-10 at 21 54 57" src="https://user-images.githubusercontent.com/2434401/59235964-6b380980-8bca-11e9-8bb3-e005ef458c70.png">
Confirmed this no longer happens
