### ISSUE TITLE
Improving search and filtering for 2chaguzi

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2091]
- [x] Sort appears first, followed by filter with saved searches and the rest of the filter fields appear as normal below these
- [x] Add option to see unlocked posts at top of list
- [x] clicking "clear filters" reverts to default search/filter state
- [x] clicking "apply filters" applies new filters (filters do not apply as you turn them on and off)
- [x] any new filters a user creates will be counted in the small, yellow on-state in the sort and filter button on the global nav bar
- [x] number of posts that apply to filters are shown in post card pane on data view
- [x] search/filter/sort parameters appear as meta data pattern in the sort and filter dropdown box and can be removed by clicking X on the meta data pattern
- [x] Save search button appears under the active search/filter/sort parameters metadata patterns. When clicked, the normal save search dialogue modal opens

Questions:
- Does "reverts to default" mean for savedsearch that it reverts to its default filters?
- Filter by data sources should it be added to filters?

**Comment by jshorland** [comment]
Designs
![filtering.and.sorting.png](https://zube.io/files/ushahidi/a93a36b216071e6f250d123a01c38eb9.png)

**Comment by rowasc** [comment]
@jshorland Jess,   I see surveys are included in the search panel now. Are we including the data sources here as well? If we include them, should we use checkboxes as in the surveys? 
<img width="194" alt="screen shot 2017-09-28 at 3 57 18 pm" src="https://user-images.githubusercontent.com/2434401/30985127-be176928-a465-11e7-9616-c8e6c1a3437a.png">


Thanks!

**Comment by rowasc** [comment]
@jshorland question: this search panel can be accessed from any tab right? 
<for now, I'm assuming Yes, just want to confirm in case I'm wrong>

**Comment by rowasc** [comment]
ie: If I am on the map view I can also open the search panel .

**Comment by jshorland** [comment]
Are we including the data sources here as well? If we include them, should
we use checkboxes as in the surveys?
- yes. Data sources should be included in the search panel. Use checkboxes
as in the surveys. See uchaguzi.or.ke as it's currently built

this search panel can be accessed from any tab right?
- yes! exactly

**Comment by rowasc** [comment]
@jshorland thanks, Jess. Does the mode bar change its behavior with this feature? For instance if a user selects location in the search panel while being on the map, do we continue showing that "Location" tag in the mode bar? 
<img width="321" alt="screen shot 2017-09-29 at 10 29 16 am" src="https://user-images.githubusercontent.com/2434401/31018060-11c6426a-a501-11e7-9326-227824770cd0.png">

Thanks

**Comment by rowasc** [comment]
@jshorland another question  in addition to the one about location: 
The designs is showing a select box for Saved Search that says "Select one", but then the active filters show two "tags" with saved searches (My Posts and Needs Escalation). 
What is the correct behavior there?

**Comment by rowasc** [comment]
@jshorland @willdoran 
some other notes , related to the questions
- I think there's a problem if we have both the search panel and the mode bar enabled at the same time. Users could try to select conflicting filters, especially since the search filters are not applied as you go (only when you click `apply filters`). 
- I think saved searches should be something we can only select by 1 at a time, as in the design that shows "select one" and not with multiple saved searches like the design that shows two selected saved searches . This is also because they could have conflicting filters in the saved search and the user wouldn't really know it. (Thanks @Angamanga for bringing that up)

**Comment by willdoran** [comment]
@rowasc I agree for 2.

For 1, I think you are right. @jshorland @justinscherer is there a design reason that the filters can't auto apply? I actually really like it when filters apply immediately in an interface but perhaps there are UX reasons why most people think that's wrong :)

**Comment by jshorland** [comment]
Feedback:

1. Does the mode bar change its behavior with this feature? For instance if a user selects location in the search panel while being on the map, do we continue showing that "Location" tag in the mode bar?
- I don't think filters displaying in the mode bar should go away for now -- while it gives people context for what filters are "on" and "off" without having to re-open the search panel, your point about conflicting filters is noted and probably correct. I personally prefer when filters are auto applied instead of having to click "apply filters" (this is actually my biggest annoyance with filtering on airbnb at the moment), but I defer to @justinscherer on that interaction. 

2. The designs are showing a select box for Saved Search that says "Select one", but then the active filters show two "tags" with saved searches (My Posts and Needs Escalation).
What is the correct behavior there? 
- good question, and I agree. @justinscherer I like only having people choose 1 saved search at a time. Can we move forward with that?

**Comment by rowasc** [comment]
@jshorland @justinscherer another question
<img width="227" alt="screen shot 2017-10-02 at 2 24 59 pm" src="https://user-images.githubusercontent.com/2434401/31090288-885f15b8-a77d-11e7-97ae-97688787496f.png">

 If we click "Show only" and then open the search panel while being on the map, do we retain the show only filter? With the way the datasources filter will be shown (checkboxes as it's currently in uchaguzi) we don't have a "Show only" filter in the search panel. So I'm not sure what to do about that.

**Comment by jshorland** [comment]
If show only is clicked, the filter for only that source or survey (you have the option to show only for surveys too) would carry over and be marked "on" within the search panel.

**Comment by rowasc** [comment]
@jshorland ah ok makes sense. Thanks

**Comment by justinscherer** [comment]
> Does the mode bar change its behavior with this feature? For instance if a user selects location in the search panel while being on the map, do we continue showing that "Location" tag in the mode bar?

Ideally, the changes would only apply to the new timeline ("data") view. Which means the search/filter on map view would work the same as currently, and we would love with the inconsistency for a little while.the node bar wouldn't change.  But I wasn't sure how connected the search components are across views. 

>  is there a design reason that the filters can't auto apply? 

Couple reasons: first, there's no way to do is accessibly that I've ever seen. E.g. how does a blind person with a screen reader know that changes are being automatically applied in the background? Also: if the system is not super quick in the query responses, the disconnected loading in the background can actually be distracting. Ultimately it depends on the kind of data you're filtering. Worth testing other options in the future. For now, keep the manual apply button. 

>  The designs are showing a select box for Saved Search that says "Select one", but then the active filters show two "tags" with saved searches (My Posts and Needs Escalation).
What is the correct behavior there?

Only one saved search at a time (otherwise you start having a situation where you can combine them into meta saved searches and it gets messier than it already is) . The tags in the mock-ups were an oversight. Nice catch.

**Comment by rowasc** [comment]
@justinscherer great, thanks, Justin. 
- Ideally, the changes would only apply to the new timeline ("data") view.
This also means that when I switch tabs the filters should be reset. Right?

**Comment by rowasc** [comment]
tabs-> views (from map to data, from data view to map)

**Comment by jshorland** [comment]
@rowasc I think keeping current functionality the same is ok -- in which when you switch views (timeline --> map) the filters DON'T clear unless someone manually chooses to clear them. So, the filters would appear in the mode bar in map mode if they've turned them on in timeline (data) mode, and vice versa.

**Comment by justinscherer** [comment]
I agree with @jshorland on this one.

**Comment by Angamanga** [comment]
@justinscherer Does this dropdown trigger the date-picker:
![screen shot 2017-10-03 at 22 54 30](https://user-images.githubusercontent.com/8624777/31148771-0d035d40-a88e-11e7-9e79-236d51ed0068.png)

**Comment by Angamanga** [comment]
@justinscherer Aha, no, never mind, now I get it, its a dropdown with different sorting-options!

**Comment by rowasc** [comment]
@middle8media @jshorland let me know when you decide what the best way to go about surveys filters is, or If we need to meet to review it / brainstorm in more detail 
Thanks!

**Comment by jshorland** [comment]
@Romina-Suarez survey filters should appear in the filter box, even on map mode (so they would appear in the context mode bar as well as the filter box)

**Comment by rowasc** [comment]
@jshorland Yes.  I mean the issue where you need "negative" survey filters because when you deselect one, you are effectively selecting all minus that one so you see all of them and it can be problematic in the UI

**Comment by jshorland** [comment]
OHHHH sorry. I'll leave that to @middle8media

**Comment by rowasc** [comment]
<img width="463" alt="screen shot 2017-10-03 at 1 48 49 pm" src="https://user-images.githubusercontent.com/2434401/31192871-d10fe8f4-a918-11e7-9ff7-2045a1a339f6.png">

**Comment by rowasc** [comment]
<img width="469" alt="screen shot 2017-10-03 at 1 44 17 pm" src="https://user-images.githubusercontent.com/2434401/31192969-162f2198-a919-11e7-809c-047536689bc6.png">
Sorry, this is the image from yesterday , not the previous one (but still, kind of the same thing applies there)

**Comment by rowasc** [comment]
Test Checklist: UI
    - [ ] I see the "Star" button where I can open the saved search list modal . 
    - [ ] I see the search bar where I can write queries
    - [ ] I see the Sort & Filter toggle dropdown button. 
        - [ ] The button has the number of active filters applied. This number represented the count of the filters which differ from the default value. 
    - [ ] this is the order in which filters are shown: 
        - [ ] Sorting options - Order By (updated, created, post date) . Default: created
        - [ ] Sort order - Desc/Asc ( Newest first, Oldest first) . Default: Asc
        - [ ] Sort order - Unlocked on top . Default: true
        - [ ] *Logged in* - Filter Saved Search - Default: none
        - [ ] Filter Status - Default: all
        - [ ] Filter Category - Default: all
        - [ ] Filter Survey - Default: all
        - [ ] Filter Source - Default: all
        - [ ] Filter Date - Default: all
        - [ ] Filter Location - Default: all

**Comment by rowasc** [comment]
Test Checklist: UI
- [ ] I see the "Star" button where I can open the saved search list modal . 
- [ ] I see the search bar where I can write queries
- [ ] I see the Sort & Filter toggle dropdown button. 
    - [ ] The button has the number of active filters applied. This number represented the count of the filters which differ from the default value. 
- [ ] this is the order in which filters are shown: 
    - [ ] Sorting options - Order By (updated, created, post date) . Default: created
    - [ ] Sort order - Desc/Asc ( Newest first, Oldest first) . Default: Asc
    - [ ] Sort order - Unlocked on top . Default: true
    - [ ] *Logged in* - Filter Saved Search - Default: none
    - [ ] Filter Status - Default: all
    - [ ] Filter Category - Default: all
    - [ ] Filter Survey - Default: all
    - [ ] Filter Source - Default: all
    - [ ] Filter Date - Default: all
    - [ ] Filter Location - Default: all

**Reactive filters:** filters and sorting options which are applied as you select them. 

**Non-Reactive filters:** filters and sorting options which are applied only after clicking Apply Filters. 

Test checklist - Map View
- [ ] Reactive filters are enabled: 
    - When I change any filter, I see the loading bar getting the updated posts. 
    - When I add filters, the post list/map is updated. 
    - When I remove filters, the post list/map is updated. 
    - Devs can also check: When I change any filter, I see the network calling get /posts. 

- [ ] Reactive filters are disabled: 
    - When I change any filter, I don't see the loading bar appear.
    - When I add filters, the post list/map is not updated. 
    - When I add remove filters, the post list/map is not updated. 
    - Devs can also check: When I change any filter, I don't see the network calling get /posts.

**Comment by rowasc** [comment]
@willdoran @jshorland  I added a rough checklist for testing. Not very detailed, but I think it's a good blueprint for testing.
If you find anything missing please feel free to add.

**Comment by jshorland** [comment]
BOOM. passes QA.
