### ISSUE TITLE
Load more reports in data mode

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2092]
Load more reports in data mode
- [x] system automatically checks for new reports that satisfy the users’ active sort/filter settings every <x> minutes
- [x] the “see new reports” bar will appear and/or refresh at that time interval indicating how many new reports are available
- [ ] The entire new post bar is tappable
- [ ] clicking see new reports bar triggers a loading pattern as new reports load (the … pattern)
- [ ] new reports load on top in the same sort order as the rest of the report list <— BUT WHAT IF REPORTS ARE SORTED OLDEST FIRST?

**Comment by jshorland** [comment]
Fails. When the load more button appears and I click it, if I'm not already at the top of the list, it now doesn't take me to the top of the list automatically and load posts. I have to manually scroll to the top and then click the button again. 

cc: @rowasc this is the issue I mentioned in #2178 
![screen capture on 2017-10-19 at 10-43-34 1](https://user-images.githubusercontent.com/3224856/31786184-7a16d31e-b4bc-11e7-8e11-31352a9a8b3d.gif)

**Comment by willdoran** [comment]
It seems as though the Post Cards are capturing the click.

**Comment by willdoran** [comment]
This appears to be a Pattern Library issue, I am woefully under skilled to diagnose this :(

**Comment by willdoran** [comment]
For the moment, I'm going to ask @Angamanga and @middle8media as Carolyn and I don't know how to fix it.

**Comment by crcommons** [comment]
Here's a clue... the element is recognized in a different place in the DOM than where it is visually. 
<img width="487" alt="screen shot 2017-10-19 at 5 14 28 pm" src="https://user-images.githubusercontent.com/8941223/31794677-1e477658-b4f1-11e7-9b70-979d6588a0c4.png">

**Comment by Angamanga** [comment]
new pr here: https://github.com/ushahidi/platform-client/pull/856

**Comment by crcommons** [comment]
Core functionality for this works! Moving to done, but opened new issue regarding reverse chronological order https://github.com/ushahidi/platform/issues/2210

**Comment by jshorland** [comment]
BOOM! this is fixed. passes QA.
