### ISSUE TITLE
Add FB Bot to all COMRADES deployments

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#2093]
COMRADES needs the FB Bot (whatever the current version is) added to the repo so that we can perform some user testing with it. We will also need a walkthrough of how it's used and how it can be linked to / interact with the [COMRADES Facebook page](https://www.facebook.com/comradesproject/).

### Due Date
October 31st. We have a simulation exercise in November.

**Comment by Shadrock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pre-COMRADES Ush eval material](https://trello.com/c/oex8sVO3/204-pre-comrades-ush-eval-material)

**Comment by jshorland** [comment]
Nice -- let me get the team through 2chaguzi work and then we'll get this
done.

**Comment by Shadrock** [comment]
As part of evaluations for this round, we need to actually set up 4 deployments of COMRADES: see #2117.

**Comment by Angamanga** [comment]
The deployment to connect the fb-bot to is: https://comrades-stg.ushahidi.com/views/map

**Comment by rjmackay** [comment]
Any updates on this?
