### ISSUE TITLE
Add new category "on the fly" on the survey form itself forces a refresh to see the category. This makes people lose any edits they've made on the post, especially while structuring

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2095]
It's not a huge blocker, but it's annoying. It *should* show the category in the list of categories in the category survey field as soon as you click the save button when adding a new category. Instead, it throws a success message slider at the bottom of the screen, and you have to refresh the page to see the new category you added.

**Comment by caharding** [comment]
Not fixing in favor of JS rewrite

**Comment by rowasc** [comment]
Confirmed this is no longer happening. closing

**Comment by rowasc** [comment]
![categoriesJun-10-2019 22-01-55](https://user-images.githubusercontent.com/2434401/59236201-7475a600-8bcb-11e9-81f9-b616e600858d.gif)
