### ISSUE TITLE
Review CSV Export fields

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2097]
Current we do not include: 
- Twitter handles
- Sms numbers
- Email addresses, Author real name, user_id

Admins should be able to export that information if it is available

Ticket created to separate issues found in testing of CSV fields. Original/Reference: 
https://github.com/ushahidi/platform-client/pull/753#issuecomment-332842142

**Comment by rowasc** [comment]
@jshorland I assume this is part of 2chaguzi, right? 
I'll get back to this as soon as we are done with filters work, so I don't become a blocker. This should be simple.

**Comment by rowasc** [comment]
reference: by filters work I mean platform/2091

**Comment by jshorland** [comment]
2chaguzi that should go back into core as well :-) and sounds good

**Comment by jshorland** [comment]
@rowasc was this implemented yet?

**Comment by rowasc** [comment]
Yes, 
@willdoran added contact fields which should cover most of this. 
(Will, correct me if I'm wrong) 
@jshorland

**Comment by jshorland** [comment]
Ok I'm going to move to testing for now.

**Comment by willdoran** [comment]
@jshorland @rowasc Yep those should be available now, let me know if they don't appear. You will also get phone numbers now as well, those display weird in excel just fyi, you have to tell the column to format them correctly.

**Comment by jshorland** [comment]
Ok I'm going to leave this in testing until we get the CSV issues fixed and
I'll just retest to double check!

**Comment by jshorland** [comment]
Depends on fixing other CSV issues

**Comment by rjmackay** [comment]
@rowasc whats the status on this? Its in 'needs QA' but I'm not clear if something was actually merged/deployed for it?

**Comment by rowasc** [comment]
@rjmackay Will sent a fix a couple weeks ago.

 It needs QA but we needed the other CSV issues ( because at that point Jess couldn't even see an export) to be tested fully.  Right now, perf isn't even decent but at least from uchaguzi  and other datasets like it , data can be exported to test it.
Jess mentioned she would retest once we have the other improvements.

**Comment by willdoran** [comment]
For the current version this passes QA, in that it returns the elements above. I'm going to move it to ready to deploy. Further CSV issues should fall under the CSV epic.
