### ISSUE TITLE
Pattern Library - create a full width and "loading on click" button

### ISSUE THREAD

**Issue by middle8media** [ushahidi/platform#2098]
**load.more.reports.pdf**
[load.more.reports.pdf](https://github.com/ushahidi/platform/files/1344277/load.more.reports.pdf)
1. Create a new button that displays full width. This should be under the "Basics" buttons.
2. Create another button that displays text as normal, then "loads" when clicked. This should be a replacement of or a variation of the "Fragments / Button, Loading "

**Comment by Angamanga** [comment]
@middle8media Is nb 1 corresponding to this one: 
![screen shot 2017-09-29 at 15 59 21](https://user-images.githubusercontent.com/8624777/31019197-39bd7e90-a52f-11e7-8cd1-0ba1a9be46be.png)
and nb 2 to this one:
![screen shot 2017-09-29 at 16 00 09](https://user-images.githubusercontent.com/8624777/31019227-4ad4aa28-a52f-11e7-802f-b048598d53f7.png)

**Comment by middle8media** [comment]
@Angamanga yes
