### ISSUE TITLE
Pattern Library - New Layout-D Toolbar

### ISSUE THREAD

**Issue by middle8media** [ushahidi/platform#2101]
`layout-d` has a new filter and sort `toolbar` which combines elements from the mode-context bar and the existing filter/sort.

https://camo.githubusercontent.com/4f086e872eeb72151ca1d8fb5e5693c0825e9e7b/68747470733a2f2f7a7562652e696f2f66696c65732f75736861686964692f61393361333662323136303731653666323530643132336130316333386562392e706e67

**Comment by Angamanga** [comment]
Should the toolbar/search-filter be used in map-view as well (I think that would make sense) ?
![screen shot 2017-10-03 at 13 42 16](https://user-images.githubusercontent.com/8624777/31123564-c0fa84b6-a840-11e7-98a7-4207a34ee800.png)

**Comment by middle8media** [comment]
You will be modifying the current search/sort/filter pattern to create an “alt” or “secondary” toolbar, specifying it to `layout-d`. Then the dropdown will be a mix of mode context and the current sort/filter.

**Comment by jshorland** [comment]
@Angamanga @middle8media this is implemented now correct? I can close?

**Comment by middle8media** [comment]
@jshorland as far as I know yes.
