### ISSUE TITLE
Pattern Library - Layout-D Bulk Actions

### ISSUE THREAD

**Issue by middle8media** [ushahidi/platform#2102]
1. Revise/create the `layout-d` bulk actions pattern from this workflow pdf
[layout.and.behaviour.screen.flow.desktop.pdf](https://github.com/ushahidi/platform/files/1352519/layout.and.behaviour.screen.flow.desktop.pdf)

![image](https://user-images.githubusercontent.com/1033332/31130514-9bd31006-a825-11e7-86bc-7bb623410e59.png)

![image](https://user-images.githubusercontent.com/1033332/31130526-a6b87c36-a825-11e7-98fd-b5104fcdf43c.png)

The bulk actions bar already exists in core, but it needs to be added as a pattern in the PL and included in the layout.

2. Add a bulk-actions layout under [layout-d](http://preview.ushahidi.com/platform-pattern-library/master/assets/html/5_layouts/#pl-pattern-layout-d) 

[These](https://github.com/ushahidi/platform-pattern-library/commit/1d4e8bcbc562d4fbca6a48524ae15b6f32f667d8) will need to go back into core for checkbox functionality

**Comment by middle8media** [comment]
Can this be closed?

**Comment by crcommons** [comment]
Moved it to done.
