### ISSUE TITLE
Pagination not available in /settings/users . I cannot see all users in the settings/users page as an admin

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2104]
### Expected behaviour
I can see all users, paginated. 
### Actual behaviour
I can only see 10 users. 
UI: No pagination available. 
Request: no "next" field in the response to generate pagination
### Steps to reproduce the behaviour/error
Login as an admin and visit http://qa.ushahididev.com/settings/users

<img width="953" alt="screen shot 2017-10-04 at 11 31 11 am" src="https://user-images.githubusercontent.com/2434401/31181466-c6a665d0-a8f7-11e7-9aab-8fff002a0347.png">
<img width="998" alt="screen shot 2017-10-04 at 11 33 03 am" src="https://user-images.githubusercontent.com/2434401/31181488-d4afd382-a8f7-11e7-9d2c-9504c7434409.png">

**Comment by rowasc** [comment]
cc @jshorland  please prioritize. 
Thanks

**Comment by jshorland** [comment]
Related #2213, #2218
