### ISSUE TITLE
No specific UI feedback on "Display name" missing while creating a new user, except for save button being disabled

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2105]
### Expected behaviour
- I see an error/warning letting me know that I have to fill in the display name. 
- Error text:  "Display name is required" (ie: like all other required fields)

It should look like this: 
<img width="1440" alt="Image of the display name and error correctly shown" src="https://user-images.githubusercontent.com/39872794/54884353-e58fa200-4e95-11e9-8d8c-e2bc19262537.png">

### Actual behaviour
I don't see an error or warning unless I edit the display name field and delete the content. 
### Steps to reproduce the behaviour/error
- Login as an admin
- Go to settings/users
- Click on + to add a user. 
- Fill in email and password. 
- - The save button is disabled, but I don't know why.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-515

**Comment by rowasc** [comment]
<img width="1440" alt="screen shot 2017-10-04 at 11 38 37 am" src="https://user-images.githubusercontent.com/2434401/31182023-2376dd52-a8f9-11e7-84d0-bf79fc2e2180.png">
Not a blocker, but it's really confusing if you don't realize the display name is there and required.

**Comment by rowasc** [comment]
cc @jshorland probably low priority considering all things, but still a weird behavior, I think

**Comment by NidhiKJha** [comment]
This issue appears to have been fixed.
It issue should be closed.
![Screenshot from 2019-03-25 00-34-54](https://user-images.githubusercontent.com/39872794/54884353-e58fa200-4e95-11e9-8d8c-e2bc19262537.png)

**Comment by rowasc** [comment]
Thanks, @NidhiKJha for checking this :) 
I think this is only fixed in the JS rewrite branches. Sadly It's still happening in master (production)  . 
<img width="1383" alt="Screen Shot 2019-06-10 at 22 05 47" src="https://user-images.githubusercontent.com/2434401/59236310-ed74fd80-8bcb-11e9-9608-1291a9359333.png">

**Comment by Erioldoesdesign** [comment]
Would love to see this in prod :)

**Comment by rowasc** [comment]
This issue is still open to be fixed (noting for future contributors) . thanks 🎉

**Comment by noone0212** [comment]
Hello @rowasc , Can I work on this issue? Will be my first bug to work upon!
Also what files should I see to get started with solving the issue?

**Comment by rowasc** [comment]
Hi, thanks for reaching out. Yes you can totally work on this , thank you so much. 
- The code for the user settings section can be found in ./app/settings/users
You may want to look at the users-edit file in that dir for this specific issue. I think probably the best solution is that if the form itself is dirty/has changed and that field is empty, we indicate that field (name) is missing. The way it works right now the user is totally stuck without any clue of what's happening 😬 

Another thing that would be useful is showing an asterisk for required fields as we do for posts. 
<img width="235" alt="Screen Shot 2020-02-25 at 15 59 02" src="https://user-images.githubusercontent.com/2434401/75278020-e89ebb00-57e7-11ea-9c99-f0a8e10c12b0.png">

cc @Angamanga FYI

**Comment by rowasc** [comment]
@Obadha2 this needs QA (in steve)
Thanks!

**Comment by Obadha2** [comment]
@rowasc while all required fields are highlighted, there's no feedback if "Display Name" is missing. There's no response when user clicks Save.
Doesn't pass QA.

**Comment by Angamanga** [comment]
@rowasc @Obadha2 This one is a bit tricky:
1. All the fields are required in order to activate the save-button. 
2. When adding a new user, the display-name is empty
3. The validation only check touched fields, since we don't want to show an ugly error-label before the user starts typing
So if the user doesn't add anything to display-name, the label cannot be seen. If the user adds something and then deletes it, THEN the error-label is shown. 

This fix is a good start since it at least shows an asterisk on the required fields. We could add a new issue about activating/disabling the save-button (probably happens in more places too). We really want to move away from that anyway since its not accessible 🎉.

**Comment by rowasc** [comment]
alright. Then I think this improvement can go live provided a new ticket is created for the more accessible solution, as Anna mentions. I think disabling the button is not the best idea without providing feedback, so we will discuss that in the new ticket.

**Comment by Angamanga** [comment]
@rowasc Yes, lets keep it open, I will take a look at and spec it further today!
