### ISSUE TITLE
Filtering by clicking the data source checkbox in the context mode bar doesn’t work

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2107]
- Scroll to the separate data source buckets in the context mode bar in list view (or map view)
- Try filtering out posts via email by using the checkbox on the data source bucket
- Nothing happens
- When filtering like this, it should behave exactly as survey filtering. When the checkbox is de-selected, the data source box should become greyed out and should filter all posts out from that data source

![Screen Capture on 2017-10-04 at 07-24-23.gif](https://zube.io/files/ushahidi/5c4b86faf1714d2874d4008d9480b443.gif)

**Comment by rjmackay** [comment]
Confirmed. This still happens right now :(

**Comment by Angamanga** [comment]
Can be tested on qa.ushahididev.com

Testing checklist:
- [ ] go to map-view
- [ ] checkboxes for data-sources should be checked
- [ ] deselect one checkbox
- [ ] posts from that data-source should be removed from the map
- [ ] the filter should not be selected in the filter- dropdow nor be visible as a bug-icon in the top of the dropdown
- [ ] select the checkbox again
- [ ] post should appear
- [ ] the filter should be checked in the filter-dropdown

**Comment by willdoran** [comment]
Two steps fail QA for me:

- [ ] the filter should not be selected in the filter- dropdow nor be visible as a bug-icon in the top of the dropdown
The bug icon is removed BUT the source is still checked

![Screen Shot 2017-11-16 at 13.55.18.png](https://zube.io/files/ushahidi/3e48e93b983ff20be96c3a491b2ab24d.png)

**Comment by rjmackay** [comment]
Needs to merge another PR to develop before this is ready to test

**Comment by Angamanga** [comment]
This now passes QA
