### ISSUE TITLE
[CSV Export - Queues] - Make previous/pending exported files available to download

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2109]
Problem description: If we have CSV exports based on a queue mechanism, we need to give the users a way to get their file after it is generated by the backend. We need a solution for all users, not only those that have a way to be notified. 

`This is the minimum suggested solution that we can go for, as a way to test this new functionality.`

- Add a screen where we list the CSV files that we have ready to download/downloaded already in the past. 
- This should be a very simple list, using what we already have available in the pattern library 

=================
Suggested fields: 
Date | File Link | Filters used | Total rows

**Comment by rowasc** [comment]
cc @willdoran @jshorland as discussed in slack, this is a minimum requirement for being able to have exports for big datasets.

**Comment by jshorland** [comment]
@Romina-Suarez do you think we need to get this into 2chaguzi?

**Comment by rowasc** [comment]
@jshorland Yes, I do. Not for training phase, but if we implement some kind of queue for CSV downloads (which I think we should ) , we need this in 2chaguzi .

**Comment by willdoran** [comment]
Suggestions:
- Add filtering support to export CLI
- Create table where we can store the export query
- Add Export Job that will work the same as notifications
- Add sed command to knit together finished files
- Update table of available files when Job finishes
- Jobs can be run by the same cron that runs the notificatons/dataprovider jobs

**Comment by rowasc** [comment]
- We need to cleanup every x time too

**Comment by rowasc** [comment]
@willdoran closing this in favor of https://github.com/ushahidi/platform/issues/2121 to avoid more overhead
