### ISSUE TITLE
Integrate YODIE and CREES into comrades test deployments

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#2117]
### The Need
COMRADES will be setting up some simulations for different use cases. We will need deployments that have the full set of COMRADES features (CREES, YODIE, FB BOT) as they are now (e.g. Alpha). 

### Questions to resolve

- Not sure exactly how many we will need yet. 
- We *will* likely need a few of them to have pre-populated data (to come from COMRADES).
- Do these each be separate repos?

**Comment by Shadrock** [comment]
Ok, we need 4 separate COMRADES deployments with the full functionality so far (ie. CREES and YODIE), by Friday Nov 24th.

**Comment by Shadrock** [comment]
URLs can be "comrades_test1, comrades_test2, etc..."

**Comment by Shadrock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [COMRADES Eval - Kenny](https://trello.com/c/oex8sVO3/204-comrades-eval-kenny)

**Comment by jshorland** [comment]
@tuxpiper can you do this by Wednesday of next week? (November 15). Four carbon copies of the comrades set up for now. We're going to then start getting facebook bot into them

**Comment by tuxpiper** [comment]
Let's look into it. Which code/branch of each component should go into each URL?

**Comment by jshorland** [comment]
cc: @willdoran i'm sorry to bug you but @tuxpiper is asking questions I don't know the answer to. See discussion below. Can you help guide him to set up 4 exact replicas of the comrades deployment?

**Comment by tuxpiper** [comment]
I've deployed and sent access details in #comrades 

I haven't deployed the facebook bot yet, I suspect we will have to collect/configure the following details first:

  FACEBOOK_ACCESS_TOKEN
  FACEBOOK_VERIFY_TOKEN
  FACEBOOK_SECRET
  PLATFORM_USERNAME
  PLATFORM_PASSWORD
  PLATFORM_FORM_ID
  FACEBOOK_PAGE_URL
  LOGO

Let me know those deets for each deployment and I will get it done!

**Comment by Shadrock** [comment]
@tuxpiper we'd also need to a FB page to connect a bot to, correct? Also, I believe we'd need to change the FB Bot script to mirror the "post types"(still hate that phrase) / categories in the deployment. Is this correct?

**Comment by Shadrock** [comment]
[](url)

**Comment by tuxpiper** [comment]
I hereby invoke @Angamanga 's powers to guide us through the facebook bot installation.

I never completed the course :(

**Comment by Shadrock** [comment]
Realizing that I will probably need to create sensible post type/categories for the COMRADES deployments OR create a stand-alone post type/category for FB Bot posts.

**Comment by Shadrock** [comment]
Realizing we have two different issues here regarding FB bot: 

- See if we can get a FB bot for one of the **_test_** deployments (would require getting category info from Kenny).
- Config. FB bot for the primary [COMRADES deployment](https://comrades-stg.ushahidi.com/views/map) (requires new post type/categories  _or_ a stand-alone post type/category for FB Bot posts).

Does this sound right?

**Comment by jshorland** [comment]
ah got it. Yes, those two are differentiated. Thanks

On Thu, Nov 16, 2017 at 10:00 AM, Shadrock Roberts <notifications@github.com

**Comment by willdoran** [comment]
@tuxpiper Can we mark this closed since we are reusing the config?

**Comment by tuxpiper** [comment]
@Shadrock @jshorland anything else to do here? facebook bot?

**Comment by willdoran** [comment]
Done
