### ISSUE TITLE
Saved Search/Collection default view selector should include Data 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2122]
### Expected behaviour
When I create a Saved Search or Collection, I am shown a dropdown to select what the default view should be. The list should include Map and Data. 

### Actual behaviour
When I create a Saved Search or Collection, I am shown a dropdown to select what the default view should be. The list includes Map and Timeline right now.

### Steps to reproduce the behaviour/error
Try to create a saved search or collection. Open the dropdown to select the default view. 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain): Develop branch

related ushahidi/platform#2135

**Comment by rowasc** [comment]
this should be fine now.

**Comment by jshorland** [comment]
ba da bing ba da boom. it's fixed.
