### ISSUE TITLE
Replace Timeline with Data view everywhere.

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2124]
### Expected behaviour
- [x] I don't see an option to select timeline
- [x] I don't see an option to select in saved search modal
- [x] I don't see an option to select in collections modal
- [x] I don't have a way to access timeline view.
- [ ] There is a mobile data view - See https://github.com/ushahidi/platform/issues/2125
##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain):  2chaguzi/everywhere

**Comment by jshorland** [comment]
Related: ushahidi/platform#2131
