### ISSUE TITLE
Data mode - mobile 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2125]
### Expected behaviour
Mobile: When I select a post in the data view, it should be shown instead of the list with a way to go back to the list. 
In web it should behave the way it does right now in data view. 
### Actual behaviour
Mobile: When I select a post in the data view, it is shown below the list. 
@jshorland please add details as needed
@middle8media can you take a look at this? 
Thanks

**Comment by willdoran** [comment]
- For now, we will use the existing detail/edit views - redirecting when we pass the scale.

**Comment by jshorland** [comment]
Looks good! When clicking on a post card in mobile, it takes me to post-detail!
