### ISSUE TITLE
Post Lock Sorting

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2128]
### Expected behaviour
- It should be possible to order Posts by Locked/Unlocked
### Actual behaviour
- Currently, Lock ordering is not possible
##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rjmackay** [comment]
@aoduor was this an issue in practice? ie. did users find it hard to identify unlocked posts to work on next?
