### ISSUE TITLE
Deployment setup for Redis

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2129]
### Expected behaviour
- Redis should be deployable via Platform Enterprise
- Websocket Nodejs server should be deployable via Platform Enterprise
### Actual behaviour
- Currently they are not
##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rjmackay** [comment]
Whats the status with this? Was this deployed / used for Uchaguzi? Is this essential before we do an ushahidi.io release?

**Comment by rjmackay** [comment]
cc @willdoran @tuxpiper Whats the status with this? Was this deployed / used for Uchaguzi? Is this essential before we do an ushahidi.io release?

**Comment by willdoran** [comment]
@rjmackay All parts of this are built except for a deployment script for the nodejs server. There is about another 8 hours to make the feature fully available. It is currently disabled via a feature flag. I decided not to move it forward during 2chaguzi because there was no time. I would rather wait until Platform has generally stabilised and include it in the next release after the upcoming one.

**Comment by tuxpiper** [comment]
as an alternative, we have a deployment ready for openshift.

**Comment by jshorland** [comment]
@willdoran  i'm going to move this into icebox. Feel free to move back to product backlog and assign an epic.

**Comment by rowasc** [comment]
I'm not sure if we need to do something in this ticket. Assigning to @tuxpiper for review who might have more context on what's needed (if anything).

**Comment by tuxpiper** [comment]
We never materialized the websockets service (not sure what the ticket for that was) . So in that context, this ticket should have the same fate.

**Comment by tuxpiper** [comment]
Ah this is the related issue @rowasc : https://github.com/ushahidi/platform/issues/2448

**Comment by rowasc** [comment]
ahhh. 
OK 2448 would be really good to do since we're polling these export statuses right now and it's bad. I guess it might be worth keeping them open in that case and just link them together with the Data Export theme

**Comment by rowasc** [comment]
or actually I can make one ticket with both off them so the full context is together , @tuxpiper lmk if you agree

**Comment by tuxpiper** [comment]
I hereby state that I have no objection to the union of tickets #2129 and #2488 and that their paths shall be united in blissful union, through triaging, development and qa , unless they are prematurely and tragically separated by one falling out of scope. Amen.

**Comment by rowasc** [comment]
I now feel empowered to close this issue thanks to David's declaration.
