### ISSUE TITLE
Reset password link in email is non responsive

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2133]
### Expected behaviour
When I get an email to reset my password, i should be able to click on the reset password link an get redirected to a page to input a new password

### Actual behaviour
The blue reset button is non responsive, and I have to copy and past the token directly from the email, onto the reset password page. 

### Steps to reproduce the behaviour/error
*Attempt to recover password from any deployment

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by tuxpiper** [comment]
There is a nice blue reset button now in Uchaguzi sandbox

**Comment by willdoran** [comment]
@tuxpiper awesome thank you so much

**Comment by jshorland** [comment]
fixed!
