### ISSUE TITLE
UX: Search filter

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2134]
This is more of a question than anything else.
I noticed that we're putting search criteria in two places
1. On the search bar at the top
![screenshot](https://i.imgur.com/NHVPuhZ.png)

2. On the left hand menu bar
![screenshot](https://i.imgur.com/bKeQ2Gh.png)

- Wondering if we can make a decision on one place for this to live, as opposed to both
- Concerned that when we have alot of search criteria on the search bar at the top
-- that ends up being the focus of the search bar than selecting what I intend to look for
-- we end up having alot of unused space when we scroll down the search bar. see below
![screen capture on 2017-10-12 at 10-55-04](https://user-images.githubusercontent.com/721918/31485340-2b338510-af3c-11e7-96e9-76ace0643a36.gif)

- The search criteria don't match on both sections i.e i have a different list on the search bar, and a different list on the search bar for the same view of data

Aha! Link: https://ushahiditeam.aha.io/features/PROD-509

**Comment by rowasc** [comment]
@aoduor sorry I  had missed this. About the search criteria not being the same, I seem to get the same criteria in both (except that the drop-down has many more filters visible by default ?) . Can you give me an example? Thanks! 
@jshorland Can you look at the questions, I'm not sure about that. Thanks

**Comment by justinscherer** [comment]
@aoduor to your original point, search/filter criteria should live with searching/filtering mechanisms in the future, not in the left bar. But the solution needs to consider the very important secondary use of the survey checkboxes in the left hand bar: they work as a legend for the issues in map view, as well as filtering posts... 

this needs a refactor, I agree, when we re-assess map view.

**Comment by justinscherer** [comment]
> The search criteria don't match on both sections i.e i have a different list on the search bar, and a different list on the search bar for the same view of data

^ This is worth fixing. The two areas should match for now.

@jshorland unless we are planning on refactoring all of map view during "UX cleanup" I wouldn't worry about the information being duplicated for now.

**Comment by rjmackay** [comment]
@Justin-Scherer I think this is resolved by ushahidi/platform#2276 now? 

I don't understand whats going on with this:
> The search criteria don't match on both sections i.e i have a different list on the search bar, and a different list on the search bar for the same view of data

Does that need to be resolved somewhere too?

**Comment by justinscherer** [comment]
@rjmackay Let me try to re-word it. 

The search filter criteria in mode-context bar in map view should match the criteria in the filter pane.  <--this is worth fixing.

**Comment by rjmackay** [comment]
Isn't the difference just that the mode context doesn't show filters for forms, categories and source because those are already effectively shown by the filter UI in the mode context?
Or are there other issues?

**Comment by justinscherer** [comment]
> Isn't the difference just that the mode context doesn't show filters for forms, categories and source because those are already effectively shown by the filter UI in the mode context?
Or are there other issues?

No, you're right. Some inconsistencies between the "bugs" is inevitable.

**Comment by rowasc** [comment]
While we no longer have the dropdown "bug icons" in the map view's sidebar, we still have the survey filters and data source filter in the sidebar..which is still kind of confusing. leaving open in case we want to review it / act on this but I'm guessing it'll depend on the UI rewritee

**Comment by Erioldoesdesign** [comment]
This a a big ole ball of design UX string that I'm sure I'll unpick sometime...
