### ISSUE TITLE
Switch all saved searches/collections with default view as "timeline" to "data"

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2135]
### Expected behaviour
While in a saved search, when I select a post to edit, the post detail view should open up on a pane to the right. 

### Actual behaviour
I get redirected to a new page altogether

### Steps to reproduce the behaviour/error
* Log into deployment e.g sandbox.uchaguzi.or.ke
* Select a saved search e.g posts from sms, email, twitter
* Select a post to structure

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
This should be OK now.
