### ISSUE TITLE
Checkboxes in search and filter dropdown in data view have styling issues

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2136]
![Screen Shot 2017-10-12 at 8.00.58 AM.png](https://zube.io/files/ushahidi/6a09af6c7fd5c0ab228af801a78df886.png)

**Comment by jshorland** [comment]
I think this is happening to all checkboxes, not just in search and filter drop down

**Comment by rowasc** [comment]
@jshorland yes, confirmed that all checkboxes pretty much everywhere are broken :/

**Comment by kinstelli** [comment]
For what it's worth, things in this list and on Post edit look better if I change ```margin:``` to 2px and ```margin-right:``` to 0px on the ```input[type="checkbox"]```. 

But does anyone happen to be aware of checkboxes that *don't* currently have this styling issue? 
@jshorland @rowasc 
Before we make/request a change to the CSS, it seems worth making sure this doesn't break something that *is* working.
