### ISSUE TITLE
left pane and right pane do not scroll separately in data mode

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2137]
I should be able to scroll down the left pane list of posts while still seeing the right pane post edit
![Screen Capture on 2017-10-12 at 08-08-39.gif](https://zube.io/files/ushahidi/dd1ac3b788cee4f32328391b4a50df11.gif)

**Comment by crcommons** [comment]
@middle8media Just moved this to QA: Confirm Fixed!
