### ISSUE TITLE
Post action drop down box goes behind next post in left pane list of post cards

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2139]
Styling issue

![Screen Shot 2017-10-12 at 8.30.37 AM.png](https://zube.io/files/ushahidi/c98571122783b342dc53a010abcae058.png)

**Comment by crcommons** [comment]
When the post is selected, the dropdown still goes behind.
<img width="471" alt="screen shot 2017-10-16 at 10 40 58 am" src="https://user-images.githubusercontent.com/8941223/31617977-b074cd5e-b25e-11e7-928b-b082deedea3d.png">

**Comment by crcommons** [comment]
Looked into this with no luck. I feel like I've tried everything. @middle8media @Angamanga Let me know if you want to pair on this. Perhaps 2 or 3 heads are better than one.

**Comment by Angamanga** [comment]
Pr here: https://github.com/ushahidi/platform-pattern-library/pull/159

**Comment by jshorland** [comment]
Still an issue in Sandbox when the post card is "selected" (aka indented and the post detail is shown on right pane.
