### ISSUE TITLE
I don't think keyword search is working at all

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2140]
![Screen Capture on 2017-10-12 at 08-36-22.gif](https://zube.io/files/ushahidi/e618525bfaeb04fbfa61f01a356c6f2e.gif)

**Comment by rowasc** [comment]
@jshorland Just checked this. It's happening with the "search all " button outside of the dropdown, but in the search all INSIDE the dropdown it works. I'll fix it for the other one now. Sorry I missed that.

**Comment by rowasc** [comment]
@jshorland even then I think the UI is just really weird, but I also can't think of a good solution TBH.  I am not sure users will totally understand how the search all works in combination with the apply filters.

**Comment by rowasc** [comment]
@jshorland this should be working now in QA
