### ISSUE TITLE
There's no way to create a new post from /data mode

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2141]
I should be able to get to create new post from my data mode (see media monitoring team use case https://docs.google.com/document/d/1nSNLwAi5zKH2ZDDg_nu37sPRC95H3qTBT09IXQowy-k/edit#)

At the moment, there's no way to enter create new from data mode.

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/46f9559c0c0c9543cdf0cdeefe2144ae073344e5
