### ISSUE TITLE
Contextual menu "..."  appears under the post card list. 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2143]
### Expected behaviour
Contextual menu  "..."  appears over the post card list
### Actual behaviour
Contextual menu  "..."  appears under the post card list. 
### Steps to reproduce the behaviour/error
Click on the "... " menu from the list. 
<img width="462" alt="screen shot 2017-10-12 at 4 28 36 pm" src="https://user-images.githubusercontent.com/2434401/31515127-6b21b0ba-af6a-11e7-83a3-44e24bb40fd2.png">

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain): http://sandbox.uchaguzi.or.ke

Related: ushahidi/platform#2139

**Comment by Angamanga** [comment]
@middle8media Can we have a look at this together? I have tried to figure it out but I cannot...

**Comment by Angamanga** [comment]
Pr here: https://github.com/ushahidi/platform-pattern-library/pull/159

**Comment by crcommons** [comment]
This is still broken. Sad day.

**Comment by middle8media** [comment]
I know. This is a tough bug. @Angamanga is aware.
