### ISSUE TITLE
Help text on location field overlaps on user input

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2146]
### Expected behaviour
It'd like to 

- be able to dismiss the help text OR
- have the help text not appear over the text field where my input should go
- opt into seeing the help text or not. Right now it's extremely arbitrary

### Actual behaviour
See below. What you can't see is that I was actually putting in lat/lon values BEHIND the black help text the entire time.
![screen capture on 2017-10-13 at 11-43-33](https://user-images.githubusercontent.com/721918/31537816-27ceea06-b00c-11e7-8863-1a33036a1303.gif)

### Steps to reproduce the behaviour/error
Try to add input on a location field

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment]
confirmed fixed in sandbox.uchaguzi.or.ke
