### ISSUE TITLE
URL when in post edit/view mode should reference post ID

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2147]
#Expected Behaviour
I think it would be a great idea to have the URL reference post ID when viewing or editing a post, even though we aren't reloading the page.

Something that we can easily do?

#Actual Behavior 
Currently, this is all we see

<img width="993" alt="screen shot 2017-10-13 at 12 25 29" src="https://user-images.githubusercontent.com/721918/31539642-de081a18-b011-11e7-9956-7dcc72dda57f.png">

**Comment by rowasc** [comment]
@aoduor agree . I think we could do it fairly easily. Might need a bit of refactoring on the data view ,but I'll check

**Comment by rowasc** [comment]
Starting on this one now while I also try to pin point the edit bug

**Comment by rowasc** [comment]
@aoduor so I am wondering what should we do if the user enters the page with the id. Of course, show the post, but : 
Option 1: should we show it in the side like if you clicked it in the data mode ?
Option 2: should we should it in the post detail screen directly?

Option 1: 
Simple, already working :) 


This is a short gif of what I implemented for `option 1.` I think it gives us a good set of features (being able to share a post by url by copy-pasting from the browser bar + being able to see it on its own)  without being super complex like the other option
![gifdatamodeclick](https://user-images.githubusercontent.com/2434401/31629081-f9a6dd9e-b288-11e7-9b48-50c628917410.gif)
What do you think? 



Option 2: 
Not so simple, more things to consider. My concern with not showing it in the post detail screen is that you would have to deal with the sorting options to be able to render it in an accurate way (so, if I select a post that normally is on the "page" 20, I should see posts around it that are on the same page ) 
*page => "group of posts that fit within the limit of post n .... post n+20 " / what load more does .

**Comment by jshorland** [comment]
I don't see any change cc: @rowasc See gif below

![screen capture on 2017-10-19 at 10-30-42](https://user-images.githubusercontent.com/3224856/31785023-a39b8602-b4b8-11e7-8fee-7d43e45ca8cb.gif)

**Comment by rowasc** [comment]
Ready in sandbox.
