### ISSUE TITLE
User list layout with bulk actions is broken.

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2148]
### Expected behaviour
I should see available actions when I select a user
### Actual behaviour
I see part of the actions menu but I don't see it all, so I can't take any action.
<img width="1440" alt="screen shot 2017-10-13 at 10 24 49 am" src="https://user-images.githubusercontent.com/2434401/31548345-e0ba13a8-b000-11e7-8391-a650acfd847f.png">

### Steps to reproduce the behaviour/error
- [ ] Go to the user list. 
- [ ] Select a user. 
- [ ] You will not see the entire actions menu.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
re:  github.com/ushahidi/platform#2120

**Comment by jshorland** [comment]
FIXED in sandbox.uchaguzi
