### ISSUE TITLE
Survey-fields does not appear when not logged in

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2152]
### Expected behaviour
When I go to a survey as not logged in, all fields I have have permissions to see should be visible

### Actual behaviour
If I create a survey 'normal' fields and a internal task, no fields except title and description are visible when trying to submit a post. This only happens when the survey is created with internal tasks. If creating a survey and adding internal tasks later on in edit-mode, it does not happen.

### Steps to reproduce the behaviour/error
- [ ] Create a survey with internal tasks
- [ ] Log out
- [ ] Add a post, only title and description is visible

##### Where
- [x ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ x] Ushahidi's QA environment
- [ ] Other (explain): sandbox.uchaguzi.or.ke

**Comment by jshorland** [comment]
When Logged out, I still only see Title and Description field for "anna testing" survey.
<img width="1275" alt="screen shot 2017-10-19 at 10 50 30 am" src="https://user-images.githubusercontent.com/3224856/31785871-658a82a2-b4bb-11e7-8c0a-e48d02ec0923.png">
