### ISSUE TITLE
Reset password button not showing up on email

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2155]
### Expected behaviour
I get an email like in the normal product, with a "Reset your password" button

### Actual behaviour
I get an email with all the standard text and a token, but no button 

### Steps to reproduce the behaviour/error
Try to reset your password. 
Check your email.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): uchaguzi sandbox

**Comment by aoduor** [comment]
Related to #2133

**Comment by tuxpiper** [comment]
Should be fixed along with #2133

**Comment by jshorland** [comment]
Fixed. Passes QA
