### ISSUE TITLE
So difficult to get out of collections or saved search view

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2156]
### Expected behaviour
When I navigate to the data view of a collection or saved search, there should be a way for me to exit the saved search or collection easily. 

### Actual behaviour

IN QA (after list-view completely removed)

Navigate to a collection or saved search. you will then be redirected to the data view of that collection/saved search. In order to get out of it, you have to go to 'map' and then select 'Return to all posts'. This is too many steps!! Also very not obvious to the user. We need a better way to get out of these views.

<img width="548" alt="screen shot 2017-10-16 at 11 19 06 am" src="https://user-images.githubusercontent.com/8941223/31619916-dea2f0a2-b263-11e7-8518-061bf3f8e309.png">

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [X] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by justinscherer** [comment]
@crcommons - agree that's kinda terrible, experience-wise.

Is this possible? User navigates to data view, user opens the search/filter pane, user clears filters, data list shows all posts?

This is how I imagined it would work, but I may have missed something.

**Comment by crcommons** [comment]
I just feel like it doesn't make sense. I feel like I'm navigating away from the saved search, but in fact I'm just moving around within the saved search. I would expect most users to think of highest level navigation buttons to take them to the highest levels of the app. You can definitely just clear the filters, but seems like we should use the nav buttons to navigate within the saved search or collection.

**Comment by rowasc** [comment]
My 2 cents: when I started working on the app (like my very first ticket), I was sure I had broken the navigation at one point because I didn't understand this part about saved searches.  I'd expect our regular user to be even more confused. So I agree that we might need to rethink this, having an `super obvious` visual cue that I'm inside a different navigation, or something like that would help. Then again, I know zero things about UX, so take it with a grain of salt.

**Comment by rowasc** [comment]
@justinscherer also I realize this is the classic "make it shine" request :) haha

**Comment by crcommons** [comment]
Also, when you clear the filter, it doesn't change the URL, so the app still thinks you're in a saved search

**Comment by crcommons** [comment]
Here's a droplr for it https://d.pr/i/Bajvno

**Comment by jshorland** [comment]
yes yes yes. this is SO much better. passes QA.
