### ISSUE TITLE
Lock styling is off when bulk actions is selected

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2157]
### Expected behaviour
Lock icon should stay in-line with other elements, like this (but with checkbox)
<img width="428" alt="screen shot 2017-10-13 at 3 23 53 pm" src="https://user-images.githubusercontent.com/8941223/31620047-34379d06-b264-11e7-9c25-379f3265b3aa.png">

### Actual behaviour

Lock styling gets thrown off when bulk actions selected.
<img width="481" alt="screen shot 2017-10-13 at 3 22 49 pm" src="https://user-images.githubusercontent.com/8941223/31620071-45d6e724-b264-11e7-8740-a91bec26aa8f.png">

### Steps to reproduce the behaviour/error
Navigate to Data view
select bulk actions

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [X] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/a23468ded06d6391a6c12d9f16392c3088710bcc

notice the html changes
