### ISSUE TITLE
See New Posts Button disappears when you scroll to bottom of page

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2158]
### Expected behaviour

"See New Post" button should remain below site header/searchbar no matter where you scroll on page.

It should always be positioned like this: 
<img width="481" alt="screen shot 2017-10-16 at 11 57 22 am" src="https://user-images.githubusercontent.com/8941223/31622046-4b9ca5e0-b269-11e7-9a24-74e36f6577cf.png">

### Actual behaviour
The button gets pushed up under the header, like this:
<img width="488" alt="screen shot 2017-10-16 at 11 57 47 am" src="https://user-images.githubusercontent.com/8941223/31622066-5ca45874-b269-11e7-9e3d-25423620c751.png">

### Steps to reproduce the behaviour/error

Change ng-show to ng-hide on div with class "button-group" that contains See New Posts button.
Scroll to bottom of page

##### Where
- [X] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [X] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [X] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/94f6e291ad7f793729e059a90ec0c23b6453dd5c
