### ISSUE TITLE
message slider/notification styling is off

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2161]
### Expected behaviour
Slider should be full width of screen
### Actual behaviour
<img width="1357" alt="screen shot 2017-10-16 at 12 08 32 pm" src="https://user-images.githubusercontent.com/8941223/31622605-e5889258-b26a-11e7-8929-6ec021e9caed.png">

### Steps to reproduce the behaviour/error
When you unlock a post, the error/success message will appear at the bottom. 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/c29b3d4f2d10e019425dc71afd9c4954f59e8391
