### ISSUE TITLE
Post not publishing from edit page

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2162]
### Expected behaviour
- When I change status of the Post and click save I expect it to save
### Actual behaviour
- When I change the status of the Post and click save I get the message:
"You haven’t made any changes"

### Steps to reproduce the behaviour/error
- Choose edit on a Post
- Select a new status
- Click save.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by willdoran** [comment]
Validation is fundamentally broken on Post edit. The ng-form model is not wiring to the sub elements, in particular, it fails to detect any changes to any sub directives post toolbox or location or media etc.

I'm going to investigate alternatives, if there are none I'm going to look at building a service handles state as gross as that is.

**Comment by jshorland** [comment]
fixed. passes QA.
