### ISSUE TITLE
n of x results is not working correctly.

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2165]
### Expected behaviour
When there are only 9 posts, I see "10 of 9 reports" instead of 9 of 9 reports
### Actual behaviour
When there are only 9 posts, I see "9 of 9 reports" 
### Steps to reproduce the behaviour/error
Go to data view with 9 reports. 
<img width="801" alt="screen shot 2017-10-16 at 5 50 19 pm" src="https://user-images.githubusercontent.com/2434401/31634661-b0008642-b29a-11e7-8467-68e5790e8bb0.png">

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rjmackay** [comment]
@rowasc I haven't see this happen. How do we reproduce it?

**Comment by rowasc** [comment]
:(  Not sure yet of specific steps except. We have seen it with 18 of 20 too. We might want to leave this just in the backlog with low priority until we find a good set of reproducible steps.

**Comment by kinstelli** [comment]
I'm also not able to duplicate this on QA or locally. Per @rjmackay, I'd vote to close it.
