### ISSUE TITLE
Can't scroll in views smaller than 1024px

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2166]
### Expected behaviour
I should be able to scroll

### Actual behaviour
I can't scroll

### Steps to reproduce the behaviour/error
Resize browser to less than 1024px in data view and try to scroll. If you remove overflow:hidden from layout-d, scrolling works.

##### Where
- [X] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [X] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [X] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/1132f7bce960ab431ccf05b455a1323194a9e7e5
