### ISSUE TITLE
Create Post button covers Help Button and stays in view when "bulk Actions" selected

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2167]
### Expected behaviour
"Create Post" button should not cover other buttons. It should also be completely hidden when bulk actions active (<1024 px)
### Actual behaviour
It covers the help button and when bulk actions is selected, it goes grey and slides half-way up the DOM, but not out of site
<img width="394" alt="screen shot 2017-10-16 at 9 33 04 pm" src="https://user-images.githubusercontent.com/8941223/31643135-c9e6108c-b2bc-11e7-81ca-464116561601.png">

### Steps to reproduce the behaviour/error
In QA, go to data view, resize browser to <1024px. Select bulk actions.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [X] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by middle8media** [comment]
partial fix via https://github.com/ushahidi/platform-pattern-library/commit/1bd424971e985f50338a398abbe680c5f71985ca

I still need to fix the Intercom button position issue

**Comment by jshorland** [comment]
Can't replicate this in sandbox anymore. closing.
