### ISSUE TITLE
Search bar should be full width

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2168]
### Expected behaviour
Search bar should be full width
### Actual behaviour
Search bar is very small because of 'Create Post' button
<img width="489" alt="screen shot 2017-10-16 at 9 33 14 pm" src="https://user-images.githubusercontent.com/8941223/31643210-4f2e36f2-b2bd-11e7-8136-120f01d8fad2.png">

### Steps to reproduce the behaviour/error
navigate to data view

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [X] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [X] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/7b259b767eb0bd24f1ebd6998ab6c765affaa7ed
