### ISSUE TITLE
Share button missing on map view

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2169]
See this on qa.ushahididev.com

<img width="1430" alt="screen shot 2017-10-17 at 10 38 45" src="https://user-images.githubusercontent.com/721918/31652344-710a88f6-b327-11e7-9ce1-7b266c97747f.png">

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
Ready in QA Env.

**Comment by jshorland** [comment]
This is fixed for me!
