### ISSUE TITLE
Warning message for required fields is not appearing consistently

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2170]
### Expected behaviour
When I don't add a value to a required form-field, there should be a warning-message below that field after clicking 'submit' or 'save'.

### Actual behaviour
-the warning-message appears randomly, sometimes it appears, sometimes not
### Steps to reproduce the behaviour/error
- [ ] Go to add-post 
- [ ] Select a survey with required fields
- [ ] Click submit
- [ ] No or only a few warning-messages appear
- [ ] add title or description
- [ ] No or only a few (other?) warning-messages appear

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
@Angamanga I think this might be related to the validation issue that Will mentioned in the handover thread ?
