### ISSUE TITLE
"conversation with author" remains the thread with the first post you click on in data mode, even after you click on another post

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2175]
### Expected behaviour
When I move from one post to another, I want to see the "conversation with author" and location for the post i've clicked on.

### Actual behaviour
The conversation thread with author and location stays as the one associated with the first post I click. It doesn't change. 

This happens with threads from email, twitter, and SMS. 

### Steps to reproduce the behaviour/error
![screen capture on 2017-10-17 at 23-30-30](https://user-images.githubusercontent.com/3224856/31703859-5f79989a-b393-11e7-88e0-62c80ed0b94c.gif)

##### Where
sandbox.uchaguzi.or.ke

**Comment by jshorland** [comment]
The location issue is fixed. I still can't see any change to the conversation with author feature. The conversation history from the first post I click "sticks" to each post.

**Comment by jshorland** [comment]
Oh whoa ok I think my first comment was wrong. I found some weird behavior. Best way to show it is through a gif I think. It changes the _content_ of the conversation with author history, but sometimes it keeps the previous post's author info. cc @kinstelli Maybe this is just a silly caching issue? Also, this is on sandbox.uchaguzi.or.ke


https://d.pr/i/L3pQO6?authComplete=true&cloneComplete=true

**Comment by kinstelli** [comment]
That is definitely weird. Investigating...

**Comment by jshorland** [comment]
Tested here and it passed! http://qa.2175-reload-message-authors.ushahidilab.com/views/map
