### ISSUE TITLE
Load More button should disappear if 100% of posts are shown

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2176]
### Expected behaviour
If there are no more posts to load, "Load More" should disappear
### Actual behaviour
Load more is still there even when there are no more posts to get.

### Steps to reproduce the behaviour/error
Run locally so there are fewer posts. Load all posts and see that it is still there.

##### Where
- [X] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment]
Fixed. Passes QA. There's a new issue with load more though. Mentioned on #2178
