### ISSUE TITLE
Filters Dropdown styles are  not correct, and it should close on outside click

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2177]
### Expected behaviour
- The dropdown styles match the PL
- The dropdown is closed when clicking outside the dropdown.
### Actual behaviour
- The dropdown styles do not match the PL
- The dropdown is not closed when clicking outside the dropdown.

### Steps to reproduce the behaviour/error
Open the filters dropdown.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain):  sandbox

**Comment by rowasc** [comment]
@jshorland I think this is a P1?

**Comment by jshorland** [comment]
this looks good. passes QA (except for the checkbox issue, but that's already a separate issue).
