### ISSUE TITLE
Load more posts sets an offset that makes the search not work 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2178]
### Expected behaviour
Click load posts. 
Search in the search bar. 
You should get the first set of posts that match your filters 
### Actual behaviour

Click load posts. 
Search in the search bar. 
You will not get all the results, instead you will get results starting from the offset of the load new posts feature (so if you were in the first "page" you will get results from the second one when you should be getting from the first again if you did a clean search) 
##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain): sandbox

**Comment by rowasc** [comment]
@jshorland this is a P1 or a P0 I think.. It becomes a blocker if the user tries to use the load new posts and then uses the search, since they won't get results unless there are more than the offset (and if they get them, it will be the wrong results anyway)

**Comment by jshorland** [comment]
This seems to work, but I think there might be a new issue cc: @rowasc When load more button appears, I click, but it doesn't automatically take me to the new posts at the top when I click it. I have to scroll all the way to the top, and THEN click the show posts. only then will they appear. 

![screen capture on 2017-10-19 at 10-43-34](https://user-images.githubusercontent.com/3224856/31785582-74af2fd6-b4ba-11e7-81b4-c24cebe5d0fc.gif)

**Comment by jshorland** [comment]
Let me know if you'd like me to open a new issue, but i'm also fine if you just want to fix it within this one.

**Comment by rowasc** [comment]
Ah, ok yes that would be best in a different ticket. Thanks for finding this!
