### ISSUE TITLE
See new posts uses the post date of the last post in the list instead of the date from when you loaded the page

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2179]
### Expected behaviour
You should "see new posts" that were created since you loaded the page, not all new posts created after the last post you see . 
### Actual behaviour
You see "new posts" appear but it's just getting  new posts created after the last post you see 

### Steps to reproduce the behaviour/error
Wait 30 seconds. You will see the " new posts" button even if none were created in the interval.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain):

**Comment by rowasc** [comment]
@jshorland this is a P1 I think.

**Comment by jshorland** [comment]
Fixed!
