### ISSUE TITLE
When you click on (x) button on a 'checkbox' filter, all of them are removed, not only the one you clicked.

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2183]
### Expected behaviour
Only the filter I want to remove is removed
### Actual behaviour
The filter I want to remove is removed, but in the case of checkboxes that means all of them are gone from the filters list instead of only the one selected. 

### Steps to reproduce the behaviour/error
- Apply survey filters. 
- Remove one of the surveys with the x in the bug button .
- All the surveys will be removed from the filter instead of just the one you tried to remove.

GIF: 
![filterscheckboxes](https://user-images.githubusercontent.com/2434401/31753595-e69ea4c6-b467-11e7-855a-472f1dc885f3.gif)

Screenshots: 
<img width="647" alt="screen shot 2017-10-19 at 12 50 06 am" src="https://user-images.githubusercontent.com/2434401/31753529-892ca130-b467-11e7-8e95-c86673742f93.png">

<img width="731" alt="screen shot 2017-10-19 at 12 50 14 am" src="https://user-images.githubusercontent.com/2434401/31753528-8903dc5a-b467-11e7-8c18-fcbb137a2652.png">

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain):

**Comment by rowasc** [comment]
@jshorland @aoduor please review

**Comment by jshorland** [comment]
@willdoran is this closed, or should I test?

**Comment by rowasc** [comment]
@jshorland this is not closed AFAIK. I was waiting on feedback on this feature :[

**Comment by willdoran** [comment]
@rowasc @jshorland sorry my bad, I thought this was done. I've reopened it.

**Comment by jshorland** [comment]
This looks done to me! passes QA in sandbox.uchaguzi.or.ke

**Comment by rowasc** [comment]
@jshorland Maybe the behavior is not what I think it should be, but for me it's doing the same as in the GIF, which looks a bit weird. This is not fixed IMO 
what do you see?

**Comment by justinscherer** [comment]
parent/child categories are fundamentally broken on a deep, deep level. I don't think there's an easy fix for it.

**Comment by willdoran** [comment]
This passes QA for me
