### ISSUE TITLE
Clicking on a post without a map makes map disappear for posts that should have them

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2184]
### Expected behaviour
If you click on a post in the data view that contains a map, then click on a post without a map, then click back to the original post. Map is gone.

### Actual behaviour
If you click on a post in the data view that contains a map, then click on a post without a map, then click back to the original post. Map should be displayed.

### Steps to reproduce the behaviour/error
If you click on a post in the data view that contains a map, then click on a post without a map, then click back to the original post. Map is gone.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
Just in case,  If you do that, and go to the map itself (map mode) you get `Error: Map container is being reused by another instance`  (but the map shows up) 
I saw the error in sandbox earlier but until you reported it I wasn't sure of the steps to do it so I was waiting to be able to reproduce it. Nice catch . ! !

**Comment by kinstelli** [comment]
Thank you, I'm also seeing that. I think that message appears even if you start at Map view, which is strange.

I just wrote a fix for the specific issue described above, to make it work ASAP, but I think I should open another one for this ```Error: Map container is being reused by another instance``` issue. 

There's stuff I don't understand about how Leaflet maps are supposed to be cleanly created, refreshed, or destroyed, so I'm not sure I'm doing the right thing in the Data view when the post is changed.

**Comment by rowasc** [comment]
UH, interesting. When I open the map view directly I don't get the error.

**Comment by rowasc** [comment]
Seeing the fix, there seems to be a new error now in the console when you switch posts?

**Comment by kinstelli** [comment]
Hmm, I'm seeing that now, too, but wasn't locally. I'll investigate.
