### ISSUE TITLE
Refactor Post directives to cohere and remove redundant code

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2187]
### Expected behaviour
- Post is managed by a single directive
### Actual behaviour
- Post is split into two sets of directives those for Dataview and single view

These should be refactored into a single coherent directive.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rjmackay** [comment]
Closing in favour of ushahidi/platform#2116
