### ISSUE TITLE
move current uchaguzi deployment to a different URL and make sure data and config remains the same

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2190]

**Comment by willdoran** [comment]
@tuxpiper Would you mind taking a look at this.

I believe though @aoduor could correct me, that the current prod should remain the same just minus the Post data.

**Comment by tuxpiper** [comment]
Done.

The previous posts are at https://aug2017.uchaguzi.or.ke . It's using the same version of the code that is running now on uchaguzi.or.ke 

No code updates done on uchaguzi.or.ke . The posts are cleared there.
