### ISSUE TITLE
Categories get cut off in the list of categories and in the survey itself

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2192]
### Expected behaviour
If I name a category and save it, I should be able to see the entirety of text after I save it. 

### Actual behaviour
The displayed text is cut off in the list of categories and on the survey form itself where i've added a category field

### Steps to reproduce the behaviour/error
See the last two questions in this survey form: https://oh2020-network.ushahidi.io/posts/create/13

##### Where
https://oh2020-network.ushahidi.io/views/map

**Comment by rjmackay** [comment]
I think this is just the limit on the length of tags in the db. It should be throwing an error when saving though, not just silently truncating tags.

**Comment by kinstelli** [comment]
I was about to post the same thing, so I'm just confirming: there's a varchar(50) for that column. Everything is getting truncrated.

**Comment by jshorland** [comment]
I'd prefer to change the limit rather than throw an error. This is for a
paying customer and since we can't yet filter by custom fields, i have to
use categories as my fall back.

**Comment by rjmackay** [comment]
Ok. We need to do both, otherwise we'll just be truncating at a higher limit.

**Comment by jshorland** [comment]
oh i see what you mean. Sounds good.

**Comment by jshorland** [comment]
@rjmackay this needs to be fixed across all deployments, not just 2chaguzi. urgent for a paying client.

**Comment by rjmackay** [comment]
@jshorland its merged already. But I'm not sure if everything else was stable enough to do a production deployment??
