### ISSUE TITLE
Validation error notification appears on "Do you want to leave this report" modal

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2193]
### Expected behaviour
I see the errors after the modal is closed
### Actual behaviour
I see the errors on top of the modal
### Steps to reproduce the behaviour/error
Edit a post in data mode, remove a required field's content
Try Change to a different post
When you see the modal asking you if you want to leave, hit Save. 
You will see the validation error on top of the modal.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
Related to https://github.com/ushahidi/platform/issues/2186

**Comment by rjmackay** [comment]
Related to https://github.com/ushahidi/platform/issues/2198 too?
