### ISSUE TITLE
Remove double 'lock' icons

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2197]
### Expected behaviour
Lock icon only means one thing

### Actual behaviour
We use lock icons to represent both a 'locked' post and an 'under review' post

I'd suggest we remove icons from the under review/published/archived status. And only show a lock icon on locked posts.

**Comment by willdoran** [comment]
@justinscherer I think this is a simple fix if just removing the icons is the right solution.

**Comment by justinscherer** [comment]
@willdoran 

> I think this is a simple fix if just removing the icons is the right solution.

yup. let's do that.

**Comment by willdoran** [comment]
@justinscherer We need a replacement icon for the "draft"/"under review" state, it breaks the UI if we don't have an icon.

**Comment by justinscherer** [comment]
@willdoran 

> We need a replacement icon for the "draft"/"under review" state, it breaks the UI if we don't have an icon.

This is why I hate leaning so hard on unlabeled icons.

Use the "pencil" icon in iconic. 

[pencil.svg.zip](https://github.com/ushahidi/platform/files/1412348/pencil.svg.zip)

**Comment by jshorland** [comment]
In my opinion, this is pretty low priority as it only applies to uchaguzi management users who have been extensively trained. Definitely agree we should get it done, but marking it as p3 for now.

**Comment by rjmackay** [comment]
The only place we still need an icon for this is in the post-actions drop down. Unfortunately we're already using the pencil for edit there:

![Screenshot 2017-11-17 15.27.18.png](https://zube.io/files/ushahidi/e2a94de8daaecf9fdc1bd86d4e08a36a.png)

**Comment by rjmackay** [comment]
@justinscherer maybe we could use the `document` label from iconic?
I really want to kill status icons entirely. They have labels everywhere now anyway.

**Comment by justinscherer** [comment]
Sure, document icon for under review. 

We need to overhaul the use of icons in our design system. It's a mess.
