### ISSUE TITLE
Cannot cancel edit-mode on unstructured-post

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2203]
### Expected behaviour
When I go to an unstructured post and click edit, 
- I want to be able to click 'cancel' and get to detail-mode if I have not made any changes,
- I want to be able to click 'cancel' or navigate away and then on 'Continue without saving changes' in the modal if I have made changes on title and description to get where I want to go.

### Actual behaviour
Nothing happens when clicking on cancel/continue without saving changes if I am on an unstructured post and have not chosen a survey.
I get this error message in the console:

![screen shot 2017-10-23 at 16 10 07](https://user-images.githubusercontent.com/8624777/31893779-b4c3a566-b80c-11e7-9414-1e7db2cf4088.png)

### Steps to reproduce the behaviour/error
In dataview-> select an unstructured post
Select 'edit'
Click on cancel-> nothing happens

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): uchaguzi.or.ke

**Comment by Angamanga** [comment]
Related to #2212

**Comment by crcommons** [comment]
@rowasc I close the other issue. Use this one instead.

**Comment by rowasc** [comment]
@willdoran I'm not sure sure how locks should work with unstructured posts. I sent a "fix" but I would appreciate your review on the morning since it looks a bit weird. https://github.com/ushahidi/platform-client/pull/871

**Comment by jshorland** [comment]
FIXED! passes QA on sandbox.uchaguzi.or.ke
