### ISSUE TITLE
Video-link-preview shows uchaguzi-embedded map

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2205]
### Expected behaviour
When I remove a video-link from a post and click save, that field should be empty.

### Actual behaviour
When I remove a video-link from the video-field and click save, the embedded map of the current deployment is visible.
![screen shot 2017-10-23 at 16 15 57](https://user-images.githubusercontent.com/8624777/31894174-ec0b1d32-b80d-11e7-8c37-fb66c157792b.png)

### Steps to reproduce the behaviour/error
- Save a post with a video-link.
- Remove the video and click save
- Embedded map is now visible.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): uchaguzi.or.ke

**Comment by jshorland** [comment]
Congrats on the weirdest bug discovery yet @Angamanga!

**Comment by jshorland** [comment]
I'm putting this as P2 at the moment because there were 0 videos in the first round of uchaguzi, so I think this will be an edge edge edge case.

**Comment by jshorland** [comment]
This isn't a thing anymore after the most recent deploy. Moving to passes QA.
