### ISSUE TITLE
Go to editmode from one post to another is not working

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2206]
### Expected behaviour
When I am in edit-mode on one post and select 'edit' in the ...-dropdown for another-post, the edit-mode for the new post should be visible (after the continue-without-saving-modal if changes was made).

### Actual behaviour
When in edit-view on one post and selecting 'edit' in the ...-dropdown for another post, the detail-view appears, not the edit-view.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
This was not implemented. Only the view mode "next" is implemented at the moment. But it should be done sooner rather than later since it improves usablity a lot

**Comment by willdoran** [comment]
I'm gonna call this a bug for the sake of labelling but put it in triage

**Comment by willdoran** [comment]
I can't reproduce that bit BUT I see something worse:
- [ ] Go to data view timeline
  - [ ] Select Post, click edit
  - [ ] Click the ... menu on a different post
    - [ ] Click edit
    - The original post remains selected but is overwritten with the second post's data

**Comment by Angamanga** [comment]
Passes QA (followed list inhttps://github.com/ushahidi/platform-client/pull/877) @willdoran what you described above happened to me once now when testing. After clearing cache once more, and testing in other browsers too, I am not able to reproduce it so I hope it was old code cached in my browser.

**Comment by willdoran** [comment]
@Angamanga , this should be gone completely, I found the code and removed the bug, so if it's happening again it might be caused by something different.
