### ISSUE TITLE
Mobile view of post from data mode takes a long time to load and there's no loading bar

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2208]
### Expected behaviour
When I click on a post card in mobile, I see a loading bar if it is still loading things, and I am taken to the full detail page for posts. 
- Stretch goal:  It would be ideal to cancel the post list requests when we are asked to go to a post detail in mobile. Check if feasible in a quick fix. 
### Actual behaviour
When I click on a post card in mobile,nothing happens for a long time and it looks like it doesn't work (in reality it eventually loads the post card)
### Steps to reproduce the behaviour/error
Click on a post card in data mode (while on mobile viewports) 
Wait ... wait ... keep waiting. 
Eventually the post loads but at that point you would have lost your patience and left because it looks like it's broken/like nothing happens
##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain): sandbox uchaguzi

**Comment by rowasc** [comment]
@jshorland as usual, please feel free to prioritize. This looks bad enough that I think a P1 would be reasonable , but it might be higher/lower.

**Comment by justinscherer** [comment]
@rowasc 

We can use the "three dots jumping in the middle of the page" loading indicator for this because it's a change of view. 

If it was trying to indicate that the view is loading new components or a change of state (i.e. not navigating to a different view), then I would use the barber shop strip thingy instead.

**Comment by rowasc** [comment]
ok, super cool, doing that now. Thanks

**Comment by jshorland** [comment]
I see the three dots jumping in the middle of the page when loading a post. And posts that are "structured" and assigned to a survey work just fine. However, when I select a post that doesn't yet belong to a survey, the three dots jumping never end. it's been ~4 minutes now, and I'm still seeing the three dots jumping on mobile. 

https://sandbox.uchaguzi.or.ke/posts/5826 <-- I tried on this one.

**Comment by jshorland** [comment]
Badabingbadaboom. passes QA.
