### ISSUE TITLE
Search/ filter pane should be bigger and have a sticky apply/clear filters button at the bottom

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2209]
### Expected behaviour
The search filter panel should be at least 30% longer by default in desktop. The bar at the bottom of the pane with "Apply Filters" and "Clear filters" should "stick" to the bottom of the pane and always remain visible when the pane is open. 
### Actual behaviour
<img width="1189" alt="screen shot 2017-10-23 at 1 07 21 pm" src="https://user-images.githubusercontent.com/29209303/31902752-f6ddba18-b7f3-11e7-9e0c-bdd6c33837ba.png">

### Steps to reproduce the behaviour/error
Open sort/filter pane in desktop.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment]
The reason I prioritized this as p1 is because our entire goal with this round was to make it faster for people to triage through posts. This was one of the most time consuming actions I had to take while testing because I had to scroll all the way to the bottom of the filter box to clear filters or apply.

**Comment by jshorland** [comment]
Retested and this is in fact an issue that still exists in sandbox.uchaguzi.or.ke

**Comment by rjmackay** [comment]
Replaced by ushahidi/platform#2267  ushahidi/platform#2268
