### ISSUE TITLE
"See New Posts" button adds posts even when in reverse chronological order 

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2210]
### Expected behaviour
When filtering posts by "Oldest First", you should not see the "See New Posts" button.
### Actual behaviour
We check for new posts and add them to the top of the list, even if in reverse chronological order.
### Steps to reproduce the behaviour/error
Filter posts in Data view by "Oldest First"
Then in another tab, add a new post
wait ~30 seconds for "See new posts" button to appear

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [X] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment]
fixed by ushahidi/platform-client#870 and passes QA
