### ISSUE TITLE
Clearing filters does not get you out of a saved search

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2211]
### Expected behaviour
When you clear the filters when in a saved search, the url should update to normal data or map view
### Actual behaviour
The URL stays the same (.../savedsearches/2/data) and makes it nearly impossible to get out of the saved search.

http://d.pr/i/vi27Db

### Steps to reproduce the behaviour/error
Select a saved search
clear filters in filter dropdown
try to navigate back to normal data/map view

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by Angamanga** [comment]
@crcommons I _think_ this is intended behaviour, even though it is confusing... the only way to get out of the saved-search is from the mode-context-bar in the map-view. Before in the timeline, you could get out of the saved-search from the mode-context-bar there too...

**Comment by crcommons** [comment]
Yesterday, @justinscherer said that clearing filters should get you out of the saved search, in this conversation. https://github.com/ushahidi/platform/issues/2156

Sorry.... should have linked this issue before.

**Comment by jshorland** [comment]
so. much. better. passes QA.
