### ISSUE TITLE
Upper Cancel Button Broken in Data Edit Mode

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2212]
### Expected behaviour
When I click the cancel button, it should cancel the post editing
### Actual behaviour
When I click the cancel button (In the top right corner), nothing happens.

Droplr below
https://d.pr/i/1wnlwV
### Steps to reproduce the behaviour/error
Select a post
Select edit 
Select upper cancel button

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
I will get on this in the next hour, should be a fast fix. Probably broke last friday while we were working on the alert. Thanks!

**Comment by crcommons** [comment]
This is a repeat. Just realized that anna logged this too. Going to delete.

**Comment by rowasc** [comment]
ah ok I didn't realize it was  the same!  thanks
