### ISSUE TITLE
Pagination missing on user list page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2213]
### Expected behaviour
I have more than 10 user assigned to a role i'm filtering by. I should be able to see a "next" button and an indication of how many more pages of users i will view.

### Actual behaviour
issss gooooooone :(

<img width="830" alt="screen shot 2017-10-24 at 00 16 46" src="https://user-images.githubusercontent.com/721918/31913814-04a7701e-b851-11e7-84ff-7c59f3fd3c7e.png">

### Steps to reproduce the behaviour/error
* log into uchaguzi.or.ke
* click on settings, then users
* Filter by role "team leads"

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): uchaguzi.or.ke

**Comment by rowasc** [comment]
checking this.@aoduor as a workaround if you need to look up a user right now, the search is working  
<img width="1191" alt="screen shot 2017-10-23 at 7 04 24 pm" src="https://user-images.githubusercontent.com/2434401/31915471-035c3360-b825-11e7-9dfe-a0f4523e9016.png">

**Comment by rowasc** [comment]
This was broken when we changed angular bootstrap versions a few weeks ago :( I'm figuring out the upgrade path now

**Comment by rowasc** [comment]
FYI @jshorland this happens in all paginations that I'm aware of. It's a global issue.

**Comment by rjmackay** [comment]
@rowasc should this be in progress? You were working on it right?

**Comment by rowasc** [comment]
ah yes, on it . Thanks @rjmackay

**Comment by jshorland** [comment]
FIXED! passes QA
