### ISSUE TITLE
Cannot export posts after selecting an individual post

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2214]
### Expected behaviour
I can export posts to CSV

### Actual behaviour
I can only export posts at the initial load of the data view. 
If I open a specific post, I can no longer export posts

### Steps to reproduce the behaviour/error
- Go to https://sandbox.uchaguzi.or.ke/views/data
- Click 'share' - see export to csv option
- Click on a specific post
- Click 'share' - no export to csv option available

##### Where
- [x] Other (explain): https://sandbox.uchaguzi.or.ke/views/data

**Comment by jshorland** [comment]
Also see #2238

**Comment by rowasc** [comment]
ctx: The problem here is that post ID is not treated as a filter so it's not being added to the CSV filters.

**Comment by tuxpiper** [comment]
:+1: just had a run-in with this issue myself . I think I would still expect to be able to export all the filtered posts to CSV, since the list is still displaying in the data view.

**Comment by jshorland** [comment]
Fixed by @rowasc in CSV filter cycle

**Comment by rowasc** [comment]
@jshorland this issue AFAIK is not valid. We don't allow exporting just a selected post (when you click on the post itself), unless that's the output of the filters. Does that make sense? 
The expectation as I understand is that we export the filtered data, not that a single selected post (when you click on a post in the data mode) is exported .
LMK if this is incorrect. Thanks
