### ISSUE TITLE
Values not saved when editing a post.

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2215]
### Expected behaviour
Changes should be saved

### Actual behaviour
No errors shown, but changes not saved

### Steps to reproduce the behaviour/error
- Load data view
- Select 'mapless post' https://sandbox.uchaguzi.or.ke/posts/5198
- Add a value for 'short text'
- Save
... data not saved. 

##### Where
Uchaguzi sandbox

**Comment by rjmackay** [comment]
- This doesn't happen if you go direct from the post detail page, to the standalone post edit and edit there
- It only works on a post that doesn't have any post values yet (ie. no value in the custom fields, only title + description)

**Comment by rjmackay** [comment]
The fix didn't resolve the issue, probably because the steps to test weren't sufficient:

- [ ] go to post-data-view
- [ ] select a post with *all custom fields empty* (ie. it can have title + description but nothing else)
- [ ] choose to edit, add values in the empty fields
- [ ] save
- [ ] values should be saved and visible in the post-detail-view

**Comment by jshorland** [comment]
all of my data is being saved now. Passes QA
