### ISSUE TITLE
settings/categories page: is there a need for pagination there, or a load more button/something else? 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2218]
### Expected behaviour
Not sure.Is there a need for pagination in the settings/categories page , or a load more button/something else? 
### Actual behaviour
There is no pagination or load more button
##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by justinscherer** [comment]
@rowasc can you drop a screencap of what you're talking about in here for a bit more context?

**Comment by jshorland** [comment]
@justinscherer @rowasc We are missing pagination across ALL settings pages -- Users, Categories, Roles (though to be fair, there aren't enough roles to require pagination, but it probably would affect it if there were).

**Comment by jshorland** [comment]
Related #2213, #2104
