### ISSUE TITLE
Terms of service doesn't respond to clicking accept 

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2220]
### Expected behavior
Once I click accept and continue on the updated terms of service notification, it should go away and I should never see it again

### Actual behavior
It doesn't respond to me clicking it. It stays in place. But if I reload the screen it seems to go away (I haven't been able to get it to pop back up so I'm assuming it worked?)

### Steps to reproduce the behaviour/error
Go to a deployment you haven't logged into since new terms of service pop up was pushed (oct 20). Login 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by crcommons** [comment]
@jshorland Can you confirm that the problem is when you have to agree to the terms of service before you attempt to log in? But when you attempt to log in and then agree to the terms of service, it works fine.

**Comment by crcommons** [comment]
I can't reproduce this locally :(

**Comment by rjmackay** [comment]
Fixed and deployed
