### ISSUE TITLE
search/filter bar styling broken in mobile -- functionality still works.

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2221]
### Expected behaviour
Search will be minimum tappable width, and the search/filter button will align in mobile viewports
### Actual behaviour
![screencap](https://user-images.githubusercontent.com/29209303/31943639-4f20bbb4-b897-11e7-8645-fdc58ac64648.png)

### Steps to reproduce the behaviour/error

load any view in mobile
##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment]
Yes, definitely still a thing after reconfirming in sandbox.
