### ISSUE TITLE
After a bad login attempt, then successful login, user is redirected to forbidden page 

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2222]
### Expected behaviour
After any successful login, a user should be routed to the home page or the URL that he/she was attempting to access
### Actual behaviour
After a bad login attempt, then successful login, user is redirected to forbidden page 
### Steps to reproduce the behaviour/error
Try to log in with the incorrect password, then log in with the correct password. You should be re-directed to the forbidden page.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): Uchaguzi.or.ke

**Comment by jshorland** [comment]
Yep. Still a thing after reconfirming in sandbox.uchaguzi.or.ke

**Comment by jshorland** [comment]
This is SO. MUCH. BETTER. passes QA for me.

**Comment by jshorland** [comment]
ughhh i just got this again. if it keeps recurring, i might log a new issue
