### ISSUE TITLE
Uchaguzi website taking too long to load

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2223]
Complaint from user on Analysis and research team.
@Angamanga and Myself also experienced this

# Steps to reproduce
* visit uchaguzi.or.ke homepage 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain):  Uchaguzi website

**Comment by jshorland** [comment]
@aodour this might be because we're pushing a lot of fixes and it's in the midst of updating? ccx: @tuxpiper

**Comment by aoduor** [comment]
Narrowed this down to this specific view

https://uchaguzi.or.ke/views/data

Accessing a specific saved search works, but this one takes forever to load.

**Comment by aoduor** [comment]
and i'm making this high priority, it's making it difficult for analysis team to work.

**Comment by rjmackay** [comment]
I think this is fixed. Reopen if its an issue again
