### ISSUE TITLE
Lock API Endpoint should reject with 401 not 403

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2224]
### Expected behaviour
- Lock reject expired token requests with 401
### Actual behaviour
- Lock reject expired token requests with 403
##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-506

**Comment by jshorland** [comment]
I have no idea how to confirm if this is still an issue or not. @willdoran if we get this far, we'll deal with it then.

**Comment by rjmackay** [comment]
@willdoran does this cause other issues? or is it just a semantics issue?

**Comment by willdoran** [comment]
@rjmackay It is partly the response being incorrect but it is an aspect of a broader problem related to sequential failing of requests and how it was handled by the auth interceptor. Since that issue is patched by checking expiry this is not pressing right now.

**Comment by rjmackay** [comment]
Ok. I'll remove this for now. If its an issue we're likely to see it while wrangling with lumen routing
