### ISSUE TITLE
User with team lead permissions getting "Access denied" error message

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2225]
### Expected behaviour
* Once logged in, he should be able to view posts on map and data views

### Actual behaviour
* He gets redirected to the forbidden page

### Steps to reproduce the behaviour/error
* Log into uchaguzi.or.ke ( with team leads access)
* Attempt to navigate to map view

Browser: Chrome, Safari and Firefox

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): Uchaguzi.or.ke

**Comment by willdoran** [comment]
Possibly related to [2222](https://github.com/ushahidi/platform/issues/2222) @tuxpiper @crcommons ?

**Comment by aoduor** [comment]
Got another user with the same issue. 

Permissions: Analysis and research

**Comment by aoduor** [comment]
Another one with publishing rights,
this is officially a P0 bug

**Comment by crcommons** [comment]
@aoduor If they refresh or try to navigate away, can they access the app or are they forbidden everywhere?

**Comment by aoduor** [comment]
@crcommons it happens everywhere for them :(

**Comment by crcommons** [comment]
ok. @willdoran I don't think it's related to #2222 because that is just about routing, rather than about permissions.

**Comment by crcommons** [comment]
This is real. Tested after deploying new changes. Now doesn't work in sandbox or uchaguzi branches.

**Comment by aoduor** [comment]
Any luck? Got volunteers completely unable to access anything. :(
