### ISSUE TITLE
Manually Placing Pin on map throws validation error

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#2226]
### Expected behaviour
When structuring a post, choose the location manually on the map and click the map to add your pin. Manually enter the location name in the "Refine Location Name" field provided. Go through remaining steps and save post. 

### Actual behaviour
Going through the above results in a validation error "attribute Location is required." See screenshot below. 
![uchaguzi location error](https://user-images.githubusercontent.com/4574998/31948867-98873118-b8e0-11e7-8b36-2012938ab7ad.png)

### Steps to reproduce the behaviour/error
Log into to [2chaguzi deployment](https://uchaguzi.or.ke) as an admin, choose unstructured post from saved searches, manually select location for post, go through steps listed above and attempt to save post. 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [X] Other (explain): Uchaguzi

**Comment by aoduor** [comment]
@Angamanga remember this one? :)

**Comment by Shadrock** [comment]
I should have added that the post I was trying to structure is 32793. I've had to cancel out of it, so you can select the same post to test.

**Comment by crcommons** [comment]
This appears to be working with the most recent merge to Uchaguzi

**Comment by jshorland** [comment]
Confirmed that this is NOT happening anymore.

**Comment by kinstelli** [comment]
![locationerror](https://user-images.githubusercontent.com/6600708/31969770-854c4426-b8db-11e7-8599-8dac7429a494.gif)


I'm afraid I just saw this happen on production.

**Comment by kinstelli** [comment]
And possibly related, this weird validation error is happening on sandbox. I'll post this as another issue.

![weirdvalidationerror](https://user-images.githubusercontent.com/6600708/31969984-2d76182a-b8dc-11e7-88bc-167f8bd3475b.gif)

**Comment by jshorland** [comment]
NOOOOO. ugh ok. thanks for re-checking that.

**Comment by kinstelli** [comment]
FWIW, here is the request payload for a similar attempt. It's weird that nothing is in values. 
Does anyone else see the same thing?

<img width="513" alt="screen shot 2017-10-24 at 5 16 37 pm" src="https://user-images.githubusercontent.com/6600708/31971242-8eb77e7c-b8e0-11e7-962f-ebe58d04363d.png">

**Comment by rjmackay** [comment]
Looking into this with #2215

**Comment by jshorland** [comment]
OK! this hasn't happened to me in manually dropping or moving a pin on location field for 6 posts. I'm saying it passes QA.
