### ISSUE TITLE
Archived posts not moving out of my view

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2227]
### Expected behaviour
When I archive a post from the '...' view, it should disappear from my current view.

### Actual behaviour
The archived posts persists :/

### Steps to reproduce the behaviour/error
* Log in to uchaguzi.or.ke
* Select unpublished posts from twitter saved search
* Archive a few posts

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): uchaguzi.or.ke

**Comment by aoduor** [comment]
Actually, none of the posts i work on end up moving out of my view as is expected i.e

I'm looking at a saved search for unstructured posts, i just structured one, and it's still in my saved search view. see

<img width="1113" alt="screen shot 2017-10-24 at 17 41 23" src="https://user-images.githubusercontent.com/721918/31949672-95c39136-b8e2-11e7-9ff0-e8d675838910.png">

**Comment by Shadrock** [comment]
Still an issue for me as well.

**Comment by Angamanga** [comment]
Followed test-list in https://github.com/ushahidi/platform-client/pull/883. Posts clear out of the way when changing something and then hit save in edit mode. Changing status in the '...' does not clear out the posts. But I'll add that as a separate issue.

**Comment by Angamanga** [comment]
Actually, moving this back to dev, but prs above are good to go!

**Comment by Angamanga** [comment]
Works fine in sandbox, followed checklist in https://github.com/ushahidi/platform-client/pull/889
