### ISSUE TITLE
Post Edit Validation changes to image field not detected

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2228]
### Expected behaviour
- When I make input a value to the edit field on Post, I expect to be able to save the post
### Actual behaviour
- Changes to the Image field type are not detected
### Steps to reproduce the behaviour/error
- Save a post that has an edit field
- Edit the post, change only the edit field
- Attempt to save, you will not be allowed to save

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment]
@willdoran what is an "edit" field? are you sure this is a p1 and not a p0? if this affects any posts with image fields, it should be a p0 since images were quite important in the last uchaguzi and could potentially be crucial in this one.

**Comment by willdoran** [comment]
@jshorland a field on Post to edit, fixed the description, yep changed to p0

**Comment by jshorland** [comment]
great!

**Comment by rowasc** [comment]
This is awful. The form is just not detected as $dirty when you change media. The only thing I can think of is just forcing it as dirty  when we have a media change, which is ugly ugly ugly.

**Comment by rowasc** [comment]
Oh by the way, the reason it works on the other form (full size editor) is we don't check against dirty there.

**Comment by rjmackay** [comment]
> This is awful. The form is just not detected as $dirty when you change media. The only thing I can think of is just forcing it as dirty when we have a media change, which is ugly ugly ugly.

@rowasc You can hook into ngModel and then form dirty checks should work. The location editor does that and it seems to work.
