### ISSUE TITLE
Location field not accepting pasted lat / longs (won't display pin)

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#2229]
### Expected behaviour
When structuring a post, use Google maps to find a location not included in OSM database (or so I thought but more on that in another issue): copy lat/long from Google. Paste lat/long info and hit 'return.' *Pin should appear on map*

### Actual behaviour
Going through the steps above yields no results. The SEARCH RESULTS section of drop-down info box simply displays "No matching results" and no pin appears on the map. See screenshot below.
![uchaguzi location error](https://user-images.githubusercontent.com/4574998/31949854-f71b13fa-b8e2-11e7-9396-4ce912102046.png)

### Steps to reproduce the behaviour/error
Log into to [2chaguzi deployment](https://uchaguzi.or.ke) as an admin, choose unstructured post from saved searches, paste lot/long information from source of your choice, go through steps listed above, and attempt to save post. 

This *may* be related to other issues I've had with using the geolocation feature: esp. ushahidi/platform#2226 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [X] Other (explain): Uchaguzi

**Comment by Shadrock** [comment]
Note: I was also having a problem of features that are known to exist and Google and OSM not appearing in the Ushahidi location search. I went back to recreate it, after getting kicked out and having to log back in, and that problem seemed to have disappeared. Is it possible that this one is related and was just a one-time thing?

**Comment by jshorland** [comment]
clsoing.
