### ISSUE TITLE
Post Edit fields/inputs sometimes don't load

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2230]
### Expected behaviour
All the post fields should load
### Actual behaviour
Not all the post fields load consistently. Title and content load fine every time but the attributes don't . 
### Steps to reproduce the behaviour/error
Click on a card , click edit. You might or might not run into the issue, since it's pretty random . For me it happens 2/3 of the times, so it should be easy to get it to happen. 
More info: I get a 404 on the post's lock when it fails to load the fields. Something to keep in mind while debugging. 
More info:this is all in the same post. It's not that some posts fail and some don't . 
##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): local, sandbox

**Comment by rowasc** [comment]
<img width="1398" alt="screen shot 2017-10-24 at 3 30 58 pm" src="https://user-images.githubusercontent.com/2434401/31961198-6833ae0c-b8d0-11e7-9a7d-ea212b875308.png">
<img width="1347" alt="screen shot 2017-10-24 at 3 32 18 pm" src="https://user-images.githubusercontent.com/2434401/31961231-8cf71f76-b8d0-11e7-94fc-dc4fc2290c89.png">

**Comment by rowasc** [comment]
This is a major blocker for users and even developer since it's very hard to even test / debug other related things when you run into this issue.

**Comment by rowasc** [comment]
@jshorland please prioritize. Thanks!

**Comment by rowasc** [comment]
I'm thinking the locks arent working either (not well) and when this fails I get the lock 404 on put. So maybe related to that.

**Comment by rowasc** [comment]
we send the post lock in $q.all but we don't handle the possibility of not having a lock to send our PUT to. 🤕 so it does not load the fields and it does not tell you anything either because we have no failure handler or chaining or anything that would account for it

**Comment by rowasc** [comment]
I think this no longer happens on sandbox, but I'm going to be looking at this and see if I can see it happening again.  

In the frontend, you never should `not` get a lock because it's created/replaced on the getLock() .  I will discuss with Will tomorrow when we have some time if it's somethign we want to show an error for, in the case where it could fail since we can just chain it and then send the $q.all but I'm not sure it's the correct way to go about it

**Comment by jshorland** [comment]
Can't replicate. closing.
