### ISSUE TITLE
You shouldn't be able to create a saved search with no active filters

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2233]
### Expected behaviour
"Create saved search" button should not be visible when there are no active filters. 
### Actual behaviour
<img width="1676" alt="screen shot 2017-10-24 at 3 29 21 pm" src="https://user-images.githubusercontent.com/29209303/31963920-5d587b48-b8d0-11e7-9594-c37508d5a460.png">

### Steps to reproduce the behaviour/error
clear filters and open the sort/filter menu

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rjmackay** [comment]
Dupe of ushahidi/platform#2269
