### ISSUE TITLE
checkbox/ellipsis/metadata on postcard not aligned properly

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2235]
### Expected behaviour
All items should be vertically centre aligned. 

### Actual behaviour
![group](https://user-images.githubusercontent.com/29209303/31964379-d527a076-b8d1-11e7-8e34-9e7404fcf7e3.png)

### Steps to reproduce the behaviour/error

go to data view, click "bulk actions" to show checkboxes.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-505

**Comment by Angamanga** [comment]
@bimbolabuari Please go ahead. I *think* the change has to be made in the pattern-library but it can also be a case of fixing the html-structure in the platform-client. Check here if you haven't already: https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/setting-up-the-pattern-library-for-development.

**Comment by bimbolabuari** [comment]
Thanks @Angamanga, Working on it
