### ISSUE TITLE
Validation error on "May we contact you for more details on this report?"

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2237]
### Expected behaviour
After editing an unstructured post on sandbox, fill out required fields, and save the post. Should be able to successfully save the post.

### Actual behaviour
After editing an unstructured post on sandbox, I tried to save the post, and got a validation error for the "May we contact you for more details on this report?" field, even though it had a value listed.

See GIF attached below.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): 
Uchaguzi sandbox

![weirdvalidationerror](https://user-images.githubusercontent.com/6600708/31970261-0815a1e4-b8dd-11e7-9b98-5e4f078858af.gif)

**Comment by kinstelli** [comment]
Does it make sense that the 'post.values' array would be empty in the request payload?

<img width="513" alt="screen shot 2017-10-24 at 5 16 37 pm" src="https://user-images.githubusercontent.com/6600708/31970863-306d80f6-b8df-11e7-81d0-b934fafb1119.png">

**Comment by kinstelli** [comment]
Looks related to #2226

**Comment by jshorland** [comment]
Tested with 6 posts going through structuring process in addition to editing posts that already were structured, and I never received this error. Passes QA.

**Comment by aoduor** [comment]
@jshorland we experienced this bug on the live site, and I have experienced it as well in the past. @Shadrock and @Angamanga too. This seems to be happening intermittently
