### ISSUE TITLE
Cannot unselect a post

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2238]
### Expected behaviour
Once I select a post on the left pane post card list, i should be able to click again and de-select the post so I see only the left side pane of post cards and no post detail.

### Actual behaviour
If I click on the card again or outside of the card, I can't get it to de select. 

### Steps to reproduce the behaviour/error
go to data
select post card
try to de select it so you only see the post card list again

Aha! Link: https://ushahiditeam.aha.io/features/PROD-504

**Comment by jshorland** [comment]
woo! passes QA.

**Comment by tuxpiper** [comment]
@rjmackay  @jshorland  I don't think I can deselect a post in the view data now (applies to ushahidi.io )

**Comment by jshorland** [comment]
Yup. Correct. Lowering to p3 though.

**Comment by OluyemisiA** [comment]
Hello @Angamanga,
I'm from outreachy, can I be assigned to this?

**Comment by Angamanga** [comment]
@OluyemisiA Absolutely! Please go ahead!

**Comment by OluyemisiA** [comment]
Thank you @Angamanga. 
I will get right on it

**Comment by Angamanga** [comment]
@OluyemisiA This needs changes in the Platform-client. Have you managed to set it up? Otherwise, start here: https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives#platform-api-backend-install-guides and here: https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/setting-up-the-platform-client

**Comment by OluyemisiA** [comment]
Hi @Angamanga, I have set up the backend but the backend url for platform-client as the one in the tutorial did not work for me for some reason. The error I'm getting is attached below
![browser](https://user-images.githubusercontent.com/67320238/96747970-dc8feb00-13c0-11eb-8b05-ba97eb0a786b.png)

**Comment by Angamanga** [comment]
@OluyemisiA Which url do you use for your BACKEND_URL in the .env file?

**Comment by OluyemisiA** [comment]
I used this URL http://wsc2019.api.ushahidi.io/.
Unless I mistyped it.

**Comment by Angamanga** [comment]
@OluyemisiA Ok, make sure you did not mistype it, and also use https instead of http. Then restart the development server in the platform-client (`npm run watch`).

**Comment by OluyemisiA** [comment]
Okay. I will try that now. Thank you @Angamanga

**Comment by OluyemisiA** [comment]
@Angamanga I changed the backend url to "https://wsc2019.api.ushahidi.io/"and when I open localhost:3000 I get this message "Deployment no found". I checked the /api/v3/config path, the status code is a 404, however, pasting the url directly into my browser I get the json object.

**Comment by OluyemisiA** [comment]
Hi @Angamanga 
I have successfully set up my local environment. Could you please tell the exact file in platform-client that needs to be updated?

**Comment by OluyemisiA** [comment]
@Angamanga Please take a look at my PR for this issue. 
Thank you

**Comment by tuxpiper** [comment]
@all-contributors please add @OluyemisiA for code

**Comment by tuxpiper** [comment]
@all-contributors please add @OluyemisiA for code

**Comment by tuxpiper** [comment]
@all-contributors please add @OluyemisiA for code
