### ISSUE TITLE
Selecting a saved search from the drop down within search and filters drop down doesn't seem to actually apply the filters

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2239]
### Expected behaviour
When I create a saved search and then try to access that saved search form within the search and filters drop down, I should be shown posts that apply to that saved search. 

### Actual behaviour
The data view just stays the same and doesn't filter the posts. however, if I navigate back to map mode and then back to data it shows me the right saved search (see here: https://d.pr/i/VIFuZx). Also if I click on the saved search from the "star" menu of saved searches, it works. 
![screen capture on 2017-10-24 at 15-28-26](https://user-images.githubusercontent.com/3224856/31971323-2620a43e-b8d0-11e7-81ab-4a067077574e.gif)

### Steps to reproduce the behaviour/error
https://sandbox.uchaguzi.or.ke/savedsearches/32 <-- try to access this saved search by filtering in the search and filter drop down in data mode

**Comment by jshorland** [comment]
Bumping up to p0

**Comment by jshorland** [comment]
We need to fix this before we address #2232

**Comment by rowasc** [comment]
@kinstelli 
@crcommons I think this can be fixed along with https://github.com/ushahidi/platform/issues/2246#issuecomment-339392510 since part of this needs to be done for 2246. LMK if we need to discuss/check anything here.

**Comment by rowasc** [comment]
Working on this with @crcommons

**Comment by jshorland** [comment]
done and done, y'all. passes QA.

**Comment by crcommons** [comment]
It appears that the defaults for categories aren't working correctly. In sandbox, it shows ALL posts when only some of the categories are selected (only some are automatically selected by default). Then only a few posts show when you attempt to change filters by category. 
![Screen Shot 2017-11-01 at 1.31.52 PM.png](https://zube.io/files/ushahidi/71ba58817bfe98ea9117b2b20f2cf3f5.png)

Also, if i log in as a user and select a saved search, then log out and log back in as a different user, the saved search persists HOWEVER the saved search is not actually selected in the dropdown.

**Comment by rowasc** [comment]
ok so something interesting. When I first log in, I see the weird behavior you just reported in the screenshot. When I reload the page, it's no longer broken? :O (this is without having selected a saved search at all.. )

**Comment by rowasc** [comment]
OK did it again, now I see them all checked.. ! 👎

**Comment by rowasc** [comment]
@crcommons it's also always the same tags/categories that get randomly checked when the others dont.. :o

**Comment by crcommons** [comment]
Also, when you don't have ALL sub-categories selected, then the parent category should not be selected. Written another way... when you select a parent category, it should select all sub-categories.

**Comment by rowasc** [comment]
we get 19 categories from the tags request, so that at least is correct. 
>Also, when you don't have ALL sub-categories selected, then the parent category should not be selected. Written another way... when you select a parent category, it should select all sub-categories.

I thought there was an agreement that it was acceptable because otherwise we needed even more refactoring than we had, and we wanted to send this to 2chaguzi ASAP. But since we're also stabilizing for core now I'm not sure.

**Comment by crcommons** [comment]
Also, just generally speaking, filters by categories isn't working correctly. For example, I searched for posts that 'Need Translation' and are not 'Translated' but got incorrect results:

![Screen Shot 2017-11-01 at 2.08.22 PM.png](https://zube.io/files/ushahidi/8f22f7348f1ccf5956afc087b3185963.png)

**Comment by rowasc** [comment]
OK now I'm just confused as to how we got to pass QA of this twice ?   =/
Going to look into everything, everything, and come back =/

**Comment by rowasc** [comment]
update: the checklist I put together was pretty bad in retrospective.

**Comment by crcommons** [comment]
Well, when the feature has this many bugs, it's hard to write a checklist that actually gets everything.

**Comment by rowasc** [comment]
@crcommons when you got that strange filtering issue where you found posts not matching the filter "Need Translation", did you have the categories in your applied filters bug icons? I can't make it happen :(

**Comment by crcommons** [comment]
Yep, bug icons are all there:

![Screen Shot 2017-11-01 at 2.25.10 PM.png](https://zube.io/files/ushahidi/c6bc879716ecf7f0efa5d2960e3f96f9.png)

**Comment by rowasc** [comment]
@crcommons ah.. right `Translation` shouldn't be in the bug icons either, because it's not selected in the first pic. I was able to reproduce the error that basically sends the parent even when it shouldnt (in the network panel) but It's not consistently happening =(. Still trying to figure this out

**Comment by rowasc** [comment]
Can't reproduce still. Maybe we can jump on a call. Still trying :/

**Comment by rowasc** [comment]
This looks consistent with the default tags being set and compared between logout and login (notes from call)
