### ISSUE TITLE
Filtering data sources to only those enabled doesn't work for non-admins

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2242]
### Expected behaviour
Data sources filter only shows enabled sources, and that works for everyone

### Actual behaviour
For non admins (ie. custom roles) trying to load config/data-provider API throws a 403 and breaks everything 

Ref ushahidi/platform#2225 - pushed a workaround for Uchaguzi, but needs a long term fix.

**Comment by rowasc** [comment]
Filtering by data source as a non logged in user works now.
Filtering by data source as a member user works now.
Filtering by data source as user without MANAGE POSTS permissions works now.
Closing
