### ISSUE TITLE
Include subcategories in search filter

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2243]
Just noticed that i only have top level categories in the search filter at the top, which isn't quite ideal at the moment, especially if i need to create new saved searches by sub category. Could we add these in?
<img width="212" alt="screen shot 2017-10-25 at 12 03 03" src="https://user-images.githubusercontent.com/721918/31990068-b5a94866-b97c-11e7-906a-8a72cde9cb17.png">

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): Uchaguzi.or.ke

**Comment by rjmackay** [comment]
@aoduor I think these are visible in the filter now? At least I see them. Closing, reopen if its an issue
