### ISSUE TITLE
Display linked content from tweets in Data view

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#2244]
### Expected behaviour
Quickly and easily see whether Tweets (or other incoming data types) contain relevant content without need to copy/paste links into a new tab. 

When attempting to structure posts from Twitter, I come across numerous Tweets that only contain hashtags and a URL. A diligent analyst/volunteer cannot make any decision about whether or not there is pertinent content in the post without first following a URL. (see example below)
![content relevance](https://user-images.githubusercontent.com/4574998/31990181-050e01b2-b97d-11e7-9994-ce88185184c2.png)
After copying/pasting link into new tab I discover that the post does not, in fact, contain any relevant information. I weep bitter tears at the lost time this has caused me. 
<img width="619" alt="screen shot 2017-10-25 at 12 00 01 pm" src="https://user-images.githubusercontent.com/4574998/31990254-3847f2ae-b97d-11e7-83b9-1b33dc473eb8.png">

### Desired behaviour
At a minimum, having a clickable link for any URL in a post (that opens the URL in a new tab or window) would be nice. Ideally, the content of the URL would be displayed somehow so I could decide whether or not to immediately archive the post or not.

### Steps to reproduce the behaviour/error
Log into deployment, search for unstructured posts from Twitter, search for those containing only hashtags and URLs, clench fists, and curse at the sky. 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [X] Other (explain): Uchaguzi

**Comment by rowasc** [comment]
<img width="769" alt="Screen Shot 2019-06-10 at 22 32 37" src="https://user-images.githubusercontent.com/2434401/59237191-adb01500-8bcf-11e9-999b-6c652d860a55.png">
This can't happen now because we display the tweet embedded instead of pulling data . Closing 🎉
