### ISSUE TITLE
Error when editing a post

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#2245]
### Steps to reproduce the behaviour/error

Click on edit post. Lables for title and description appear like this 👇 
<img width="632" alt="screen shot 2017-10-25 at 3 22 10 pm" src="https://user-images.githubusercontent.com/8900438/31998418-7b97cd3e-b998-11e7-840e-f829e8d0032c.png">

**Comment by jshorland** [comment]
I haven't been able to replicate this anywhere yet.

**Comment by jshorland** [comment]
@Celestine22 is this still happening for you? if so, where (what URL?)

**Comment by rowasc** [comment]
@Celestine22 is this still an issue? If not we should close it.

**Comment by rjmackay** [comment]
I suspect this was something going wrong during a deployment, or simply connectivity issue causing the app never to finish initializing. Closing. Reopen if it happens again
