### ISSUE TITLE
Unable to edit saved search filters

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2246]
### Expected behaviour
I need to be able to update search filters and criteria that makes up a saved search. Use case

e.g. in August, as we progressed, we had to deprioritize a couple of surveys and prioritize sensitive categories/surveys. Being able to update this made it easier for teams to work on what they needed to work on fast

### Actual behaviour
The much i can do now is delete a saved search, no updates to search criteria etc. unless i create a saved search from scratch.

### Steps to reproduce the behaviour/error
* Log into uchaguzi.or.ke
* Attempt to edit a saved search

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain):

**Comment by jshorland** [comment]
Super important. Trying to deal with this in https://github.com/ushahidi/platform/issues/2232

@aoduor for now, if you filter by a saved search from within the "star" icon menu and then switch to map view, you can edit the saved search filters as you normally would from there.

**Comment by jshorland** [comment]
If we can fix this, we can get rid of the star icon. #2232

**Comment by justinscherer** [comment]
@aoduor 

(Very) quick mockup of proposed interim solution.

<img width="1005" alt="screen shot 2017-10-25 at 12 29 56 pm" src="https://user-images.githubusercontent.com/29209303/32011012-7fd15814-b981-11e7-93e7-883347e2d697.png">

**Comment by justinscherer** [comment]
It goes without saying that the permissions for modifying saved searches should not change.

**Comment by rowasc** [comment]
👍 sounds good thanks. 

@crcommons @kinstelli @jshorland please confirm when you read/verify this 

@crcommons @kinstelli not sure if you are going to be doing the implementation,  I'm still finishing up CSV things but if you want to huddle on implementation details or anything just ping me , I have some time.

**Comment by kinstelli** [comment]
I'm looking into what would need to change to implement this, as I'm still unfamiliar with that part of the client code.

But looking at the API, (and maybe this is only news to me) updating the savedsearch just appears to be a matter of sending a new filter object in a PUT request. Here's an example of what such a filter object looks like for a savedsearch with an ID of 4:
```
{"id":4,
"filter":{ "q": "more complex update",
		                "date_after": "",
		                "date_before": "",
		                "status": [
		                    "published",
		                    "draft"
		                ],
		                "published_to": "",
		                "center_point": "",
		                "has_location": "all",
		                "within_km": "1",
		                "current_stage": [],
		                "tags": [],
		                "saved_search": "",
		                "orderby": "created",
		                "order": "desc",
		                "order_unlocked_on_top": "true",
		                "form": [
		                    1,
		                    3,
		                    4,
		                    5,
		                    6,
		                    7,
		                    8,
		                    9,
		                    10
		                ],
		                "set": [],
		                "user": false,
		                "source": [
		                    "twitter",
		                    "web",
		                    "email"
		                ],
		                "reactToQEnabled": false,
		                "reactToFilters": true
		            }
				}
```

**Comment by rowasc** [comment]
@kinstelli yes, that's correct. Keep in mind the update should work from the client even now, but only as long as we are actually doing the right thing and not sending a saved search as a filter, which is what I THINK is happening. 
In any case, you are correct that it's just a normal put with filters to the savedsearch obj

**Comment by kinstelli** [comment]
If a saved search is selected, then yes, we're just sending the number of that saved search along with any new filters and sorting options. I'm not clear about what takes precedence if one of those filters conflicts or overlaps with an existing filter in the saved search. 

For example, if a saved search is for a date range, but I specify an additional date range in my search, then currently it looks like the most restrictive _Intersect_ of posts is returned:
```
 date_after:2017-10-01T05:00:00.000Z
date_before:2017-10-25T05:00:00.000Z
form[]:1
form[]:2
form[]:3
form[]:4
form[]:none
has_location:all
limit:20
order:desc
order_unlocked_on_top:true
orderby:created
saved_search:8
source[]:sms
source[]:twitter
source[]:web
source[]:email
status[]:published
status[]:draft
```

The way I understand this modified dialog could work would be -- when someone selects a saved search, we grab the existing filter of that saved search , then populate the search form to reflect the filter as it's currently defined with all of its filter attributes.

A user could then just hit search, or modify that search in-place, or also choose to update the saved search with any updated params via the 'Update Saved Search' button. 

Am I understanding that correctly, @jshorland, @justinscherer, @rowasc ?

**Comment by rowasc** [comment]
@kinstelli no, so you wouldn't/shouldn't be able to do that (savedsearch + extra filters ) for the reason you describe. 
So yes, you understand it correctly

**Comment by crcommons** [comment]
If we wanted the user to be able to modify that search in-place, we would need to make a totally new search, not update the saved search. The saved search should be immutable from the search bar dropdown. But we should be able to add to a saved search in that one search. And admins/saved search owner (and whoever has editing rights) should be able to edit a saved search

**Comment by rowasc** [comment]
> The saved search should be immutable from the search bar dropdown
@crcommons I'm not sure I follow.
New design/UX sets it so that you can modify a saved search as far as I understand it, after you select one.

**Comment by crcommons** [comment]
You should be creating a new search that includes everything from the saved search plus/minus whatever changes you make. But you shouldn't be able to actually edit the saved search itself.

**Comment by kinstelli** [comment]
My apologies if I'm using confusing terminology, but here's how I imagine things could work:

1. In the sort/filter dropdown, if a user selects a saved search, then our code queries that saved search for its filter details. For each attribute defined in that savedsearch's filter, we populate the pulldown filter menu form to reflect the filter settings of that saved search. (Currently the filter of a saved search aren't visible, which is a little confusing to me.)

2. A user can either leave those settings as they are, or tweak those settings and perform a search.

3. If the user has permissions to edit a saved search, then they can also see a button that says "Update Saved Search".

4. If they have edited the filter dropdown menu with new filter details, and then press the "Update Saved Search" button, then we send an update/PUT to the existing savedsearch with the current state of the sort/filter form.

Does this seem right?

**Comment by crcommons** [comment]
that seems right to me! And also make sure that the user still has the ability to create a new saved search too.

**Comment by rowasc** [comment]
Yes, that's exactly right. 
I think we were all thinking the same and saying it in different ways 🤣

**Comment by rowasc** [comment]
Working on this with @crcommons

**Comment by crcommons** [comment]
UPDATE:

We will not include a bug/bubble thing for the saved search when it is active. Instead we will list out each filter within the saved search. If a user adds/removes individual filters, then he/she will have the option to save as a new saved search and/or update the existing saved search (WITH APPROPRIATE PERMISSIONS).

**Comment by rowasc** [comment]
Thanks for the quick turnaround on this info ! Ok updating that.

**Comment by rjmackay** [comment]
Catching up. I think this approach makes sense. It'll need some work on the post-filter state handling... since previously we just push the filters from a saved search into post-filters and didn't identify which filters were from the saved search or not.
There are existing directives for the saved search update/create buttons that might *just work* or come close.

**Comment by jshorland** [comment]
boom. Fixed. Passes QA.
