### ISSUE TITLE
New treatment for change status box in edit mode

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2249]
### Expected behaviour
Status box should not hover as a separate box in the top right corner of the data view
### Actual behaviour
Box floats over the post details in the top right corner in edit mode.
### Steps to reproduce the behaviour/error
Select a postcard, select edit.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-502

**Comment by rjmackay** [comment]
@justinscherer could you add designs or links to the design for how this *should* work?

**Comment by justinscherer** [comment]
> @justinscherer could you add designs or links to the design for how this should work?
 
Not sure. I need to think about it in the context of workflow management initially designed for 2chaguzi. It's fine to leave it for now, but when we develop a proper workflow management solution, we can refactor.
