### ISSUE TITLE
Update saved search button should only be displayed when the search has filters other than the original saved search filters

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2254]
### Expected behaviour
Update saved search button should only be displayed when the search has filters other than the original saved search filters

### Actual behaviour
Update saved search button is displayed as long as you have permissions to edit the search and selected a saved search

### Steps to reproduce the behaviour/error
Select a saved search. You will see the button even with no changes made . 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): local branch, not yet merged. Soon in develop.

**Comment by justinscherer** [comment]
See #2276

**Comment by rowasc** [comment]
So if the user wants to change the saved search name, where will they do it? (I might be missing parts of this ticket? )

**Comment by rowasc** [comment]
I realized I created this originally because at some point we discussed it last week, but I still have the question. I really don't know if this is something we can do, but I might be missing something else.

**Comment by justinscherer** [comment]
If you select "Save search" with the new filters, a new name field is the first thing you see in the modal.

**Comment by rowasc** [comment]
Right, but you would never be able to update the saved search's name without also changing its filters

**Comment by justinscherer** [comment]
> Right, but you would never be able to update the saved search's name without also changing its filters

I can live with this limitation.

**Comment by rowasc** [comment]
ok. Good. Just wanted to make sure access to the modal options such as name, description, default view, etc was not super important. Thanks!

**Comment by rjmackay** [comment]
@justinscherer should we still have the update search/save search buttons in the sidebar on the map view? or only in filters now?

If we want to keep it, it'll take a little extra work to make them behave the same as the save/update buttons in the dropdown up

**Comment by justinscherer** [comment]
> should we still have the update search/save search buttons in the sidebar on the map view? or only in filters now?

The initial idea was to leave map view alone and let it be inconsistent for now and log it as tech debt. The very fact that the same CTA exists in two places on that view is UX debt, imo. That being said, if it's not too much, the duplicated CTAs would ideally work the same way at the very least. To answer your question: I think it's worth doing.

**Comment by Angamanga** [comment]
Passes qa!
