### ISSUE TITLE
Location search forces wrong lat/long

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#2256]
### Expected behaviour
When structuring a post, use Google maps to find a location; copy lat/long from Google; paste lat/long info and hit 'return.' Pin should appear on map

### Actual behaviour
Going through the steps above yields an incorrect location will *not accept* the lat/long you have pasted in. The SEARCH RESULTS section of drop-down info box forces you to select incorect location. See screenshots below.

### Steps to reproduce the behaviour/error
Sign onto deployment and either choose new post or select post that needs geolocation. The follow the steps: 
1: Select lat/long from Google (or mapping program of your choice). Here I'm using Wajir Airport. Note where the pin is in relation to Wajir town. 
![wajir airport 1](https://user-images.githubusercontent.com/4574998/32052875-359194c6-ba62-11e7-8e33-2f4ef7f7b87d.png)

2: Go to the map location search and paste in your lat/long. Note that you are prompted/forced to select a given location.
![wajir airport 2](https://user-images.githubusercontent.com/4574998/32052967-6c8e4a78-ba62-11e7-9df2-93c182b01655.png)

3: Accept given location and then visually inspect where the pin is compared to where is should be. In the three observed cases of this bug, the given location is often miles from where it should be (in this case up to 50km). 
![wajir airport 3](https://user-images.githubusercontent.com/4574998/32052998-8edd08a8-ba62-11e7-90af-49ffd2b86698.png)

####Notes
Maybe related to #2229. I have experienced this on a Mac using Chrome. Two others have experienced this using Explorer on PCs. 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [X] Other (explain): Uchaguzi

Aha! Link: https://ushahiditeam.aha.io/features/PROD-501

**Comment by kkoxenberners** [comment]
See  #2257 
https://github.com/ushahidi/platform/issues/2257

Proposed reverting to giving lat, long box(es) entry priority - i.e., no look-up from names or roads in database if coordinates entered
