### ISSUE TITLE
Add back Lat/Lon fields to location field

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2257]
This is a direct request from the geolocation team. On a scale of 1-5, they have labelled this a 4.

"can we not return to  priority for lat, long entry as in previous versions? (edited)

angela [3:55 PM] 
@brendan_oh you mean return the lat/lon field values back?

brendan_oh
[3:55 PM] 
that IS what geolocation should be determined by

[3:56] 
yep!!! :slightly_smiling_face:"

####Expected behaviour
Searching by lat/lon values should place the point on the exact location matching the coordinates

####Actual behaviour
Searching by lat/lon values is not accurately placing point on the specificed location, and insteads defaults to the nearest road.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): uchaguzi.or.ke

**Comment by kkoxenberners** [comment]
any progress here?

**Comment by kkoxenberners** [comment]
ah, sorry - hadn't updated
Thanks!

**Comment by Angamanga** [comment]
Passes QA in sandbox!!

**Comment by katieellenpickett** [comment]
Can you push the update please?
