### ISSUE TITLE
No open in new tab option; not being able to see post url when hovering over post headings

### ISSUE THREAD

**Issue by kkoxenberners** [ushahidi/platform#2258]
Tech/usability comments:
bit annoying not being able to see the number of a post in data list when hover over heading elements,
plus no option with right-click (am in Windows, Firefox)
to open in new tab - surely can be restored?

### Expected behaviour
Option to open post/report in new tab when right click on post heading in data list;
seeing post url when hover over heading

### Actual behaviour
Not being able to do this

### Steps to reproduce the behaviour/error
Data list e.g., https://uchaguzi.or.ke/savedsearches/10

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): https://uchaguzi.or.ke

Aha! Link: https://ushahiditeam.aha.io/features/PROD-500

**Comment by rowasc** [comment]
@justinscherer @jshorland FYI

**Comment by kkoxenberners** [comment]
Thanks @rowasc

**Comment by rjmackay** [comment]
@rowasc this might be something to keep in might when we redo the data panes using ui-router
refs ushahidi/platform#2201

**Comment by rowasc** [comment]
Note while triaging: 
While in new versions of platform (with UIRouter) we allow going directly to a post through its url (from the browser) and the url changes as you navigate through posts in the data view, we don't have a right-click option to open in a new tab yet.
