### ISSUE TITLE
Discrepancy between actual tweet and tweet on platform

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2259]
I suspect this is an issue with structuring. We do need to see the change log if so, but I'm keeping an eye out for any other similar issues and will escalate if they occur:

Put under review from being published: https://uchaguzi.or.ke/posts/34967 Uchaguzi 2017 post "Utterly depressing situation in Mathare. Three dozen officers, tons of security, no voters. Teargas being fired nearby. #ElectionsBoycottKE it is.... https://t.co/Sa8O4qwHGf" The tweet states, "Utterly depressing situation in Mathare. Three dozen officers, tons of security, no voters. Teargas being fired nearby." @channel this is a problem.

**Comment by rowasc** [comment]
Note: This is no longer possible in .io deployments because of changes in how we handle twitter (but might still be available in the uchaguzi deployment)  . 
Once #3368   is done we can close this
