### ISSUE TITLE
double check the designs of all messages

### ISSUE THREAD

**Issue by sethburtonhall** [ushahidi/platform#2261]
I need to finish the design of this message, aka add relevant icon and double check content layout.

![image](https://user-images.githubusercontent.com/1033332/32069812-48e72fc2-ba58-11e7-9af7-454c562841a8.png)

**Comment by jshorland** [comment]
I'm going to take this on and will log new issues for anything I find and close this issue once I'm finished.

**Comment by middle8media** [comment]
Thank you @jshorland. That is a big help! Assign me to any of these issues.
