### ISSUE TITLE
Cannot update saved search from map view

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2263]
### Expected behaviour
I should be able to edit saved searches from the map context. 

### Actual behaviour
I've been trying to edit the geolocation team's saved search to no avail.
The update search button is non responsive.

### Steps to reproduce the behaviour/error
click on a saved search, switch view to map, try to change search filter

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by Angamanga** [comment]
It actually updates, but it doesn't notify you at all when its done so you get the impression that nothing happens. Looking into it...

**Comment by jshorland** [comment]
this looks good! passes qa
