### ISSUE TITLE
Map jumps around when loading map view

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2265]
### Expected behaviour
The map doesn't move around every time we get the next batch of items (GET `/geojson` query to the backend). Instead, it starts centered in a default location and then does a single re-focus even when we have all items loaded. 

### Actual behaviour
The map loads a few posts, refocusses, loads a few posts, refocusses. The interface moves like a malfunctioning robot. 

### Steps to reproduce the behaviour/error
Log in, go to map view in a site with many location posts (if you change the `limit` parameter in the geojson query to be low, you can probably simulate this locally without needing to create a lot of data)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-495

**Comment by tuxpiper** [comment]
Proposing for the upcoming sprint.

I think we could take of this together with some other flow-control issues we are having with how many query batches we fire at the same time.

**Comment by tuxpiper** [comment]
Didn't have the chance to set up a test environment good for this.

However, it was handpicked for deployment in Uchaguzi. I think the way the map "zooms out" as more markers are added to it is a great improvement in behavior.
