### ISSUE TITLE
FAB should go in the bottom right corner on data view

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2266]
### Expected behaviour
![filters on](https://user-images.githubusercontent.com/29209303/32292322-5ae44938-bf05-11e7-904c-4b94bd891b56.png)

### Actual behaviour
<img width="1669" alt="screen shot 2017-11-01 at 1 01 32 pm" src="https://user-images.githubusercontent.com/29209303/32292179-e3e82070-bf04-11e7-8be2-98e0d6766552.png">

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
@justinscherer where is this happening? Sandbox? 2chaguzi prod? (haven't seen it happen so I'm not sure :/)

**Comment by justinscherer** [comment]
@rowasc 
Prod.

**Comment by justinscherer** [comment]
related to ushahidi/platform-client#441

**Comment by crcommons** [comment]
What does the view look like when there is a post selected? Also, is this confusing to users since you add a post in a totally different spot in map view?

**Comment by justinscherer** [comment]
>What does the view look like when there is a post selected?

Floating action buttons float: https://material.io/guidelines/components/buttons-floating-action-button.html
So it would float over the content in the post. 

> Also, is this confusing to users since you add a post in a totally different spot in map view? 
I've done about 10 ad-hoc tests on the big, unlabeled yellow FAB in map view. They've all guessed wrong when I asked them what they think it's for. So the FAB is a crap experience. Plus, FABs are typically in the bottom right corner, so it's actually more specific with the material-design-ism. 

But to your point, yes. Yet another inconsistency between map and data view. But I can live with it given how much it cleans up the layout of the top left of the page.

**Comment by Angamanga** [comment]
This is merged to pattern-library but need to wait for new release to be tested in client

**Comment by Angamanga** [comment]
Can be tested on qa.ushahididev.com
Testing-checklist:
- [ ] Go to data-view
- [ ] The FAB-button should be on the bottom right corner
- [ ] Check smaller and bigger screen-sizes, it should behave the same

**Comment by willdoran** [comment]
This passes QA for me.
