### ISSUE TITLE
Filter pane and postcard list area should be the same width as filter pane

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2267]
### Expected behaviour
![filter open member](https://user-images.githubusercontent.com/29209303/32292453-e056878e-bf05-11e7-8c53-086e5c1ebba8.png)

### Actual behaviour
<img width="1189" alt="screen shot 2017-10-23 at 1 07 21 pm" src="https://user-images.githubusercontent.com/29209303/32292440-da75926a-bf05-11e7-8ad4-dcaa67fc5838.png">

### Steps to reproduce the behaviour/error
Open filter pane

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by Angamanga** [comment]
This is merged to pattern-library but need to wait for new pl-release to be tested

**Comment by Angamanga** [comment]
Can be tested on qa.ushahididev.com
Testing-checklist:
- [ ] Go to data-view
- [ ] Open the filter-dropdown
- [ ] The height of the dropdown should be the same as the window
- [ ] The width of the dropdown should be the same as the filter-pane
- [ ] The buttons should stay at bottom when scrolling the filters
- [ ] Repeat on map-view, it should behave the same
- [ ] Repeat on smaller screen-sizes, it should behave the same

**Comment by willdoran** [comment]
This passes QA for me.
