### ISSUE TITLE
"Apply Filters" and "Clear Filters" buttons should "stick" to the bottom of the filter pane

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2268]
### Expected behaviour
![filter open w sticky buttons](https://user-images.githubusercontent.com/29209303/32292606-449b491e-bf06-11e7-84cd-d8959f24143b.png)

### Actual behaviour
<img width="1676" alt="screen shot 2017-10-24 at 3 29 21 pm" src="https://user-images.githubusercontent.com/29209303/32292550-1fe77b1a-bf06-11e7-924f-b41286377055.png">

### Steps to reproduce the behaviour/error
open filter pane

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by Angamanga** [comment]
This is merged but waiting for a new pl-release to be tested.

**Comment by Angamanga** [comment]
Can be tested on qa.ushahididev.com
Testing-checklist: 
- [ ] Go to data-view
- [ ] Open the filter-dropdown
- [ ] The "Apply-filters" and "Clear Filters" buttons should stick to the bottom of the filter
- [ ] The buttons should stay at bottom when scrolling the filters
- [ ] Repeat on map-view, it should behave the same
- [ ] Repeat on smaller screen-sizes, it should behave the same

**Comment by willdoran** [comment]
This passes QA for me.
