### ISSUE TITLE
"Save search" CTA in filter pane only exists when active filters exist, and should be on the right side, not the left

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2269]
### Expected behaviour
![filter open with filters active](https://user-images.githubusercontent.com/29209303/32292685-7bd6ab76-bf06-11e7-9f2c-bde5392217db.png)

### Actual behaviour

<img width="1671" alt="screen shot 2017-11-01 at 1 13 49 pm" src="https://user-images.githubusercontent.com/29209303/32292703-863f9064-bf06-11e7-9603-a78d54dbcf2f.png">
### Steps to reproduce the behaviour/error
open filter pane

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
@jshorland if I have a saved search selected, I should only see the UPDATE button, not the save button, right?

**Comment by justinscherer** [comment]
@rowasc yes.

**Comment by rowasc** [comment]
Great, thanks @justinscherer

**Comment by Angamanga** [comment]
Passes QA!
