### ISSUE TITLE
"See new post" bar should stick to the top bar and be styled like a postcard

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2270]
### Expected behaviour
![new reports available scrolled](https://user-images.githubusercontent.com/29209303/32292878-125570be-bf07-11e7-98fc-6bb803d5a303.png)

### Actual behaviour
<img width="1668" alt="screen shot 2017-10-26 at 8 34 42 am" src="https://user-images.githubusercontent.com/29209303/32292896-20e9ccce-bf07-11e7-90b1-ad5fe37aa180.png">

### Steps to reproduce the behaviour/error

open data view, wait for new reports to become available.
##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by Angamanga** [comment]
Can be tested on qa.ushahididev.com.
Testing-checklist:
- [ ] Go to dataview in one tab
- [ ] Add a new post from another tab
- [ ] Wait for the 'load new posts' button to appear in the first tab
- [ ] The button should be white and have the same margins and shadows as the postcards below
- [ ] The button should remain at the same place when scrolling down
- [ ] The button should behave like this for all screen-sizes

**Comment by willdoran** [comment]
This passes QA for me.
