### ISSUE TITLE
Long, single word report titles break the postcard layout

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2271]
### Expected behaviour
![card inactive](https://user-images.githubusercontent.com/29209303/32293001-6e70661a-bf07-11e7-9722-1d451a709473.png)

### Actual behaviour
<img width="705" alt="screen shot 2017-10-26 at 8 44 43 am" src="https://user-images.githubusercontent.com/29209303/32292956-478b14a0-bf07-11e7-9bad-241be95eb0cd.png">

### Steps to reproduce the behaviour/error
find a post with a really long, 1-word title.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-494

**Comment by kinstelli** [comment]
Copied comments from #2272 for reference to line-clamping specification:
>> What should the rules be for wrapping/ellipses-ing the title text? Should there be a relative width cutoff, or maybe a total number of characters?
> 2 lines then ellipses before the chevron. It should never wrap more than once before being truncated.

**Comment by rowasc** [comment]
related ticket https://github.com/ushahidi/platform/issues/2272 can be done after fixing this one (so if you request this issue, you can also claim the related one)

**Comment by Firenz** [comment]
Hello @rowasc @Angamanga, can you assign me this issue? I think I can fix it.

**Comment by Angamanga** [comment]
@Firenz Yes, please go ahead! I think it needs to be fixed in the pattern-library. Check the setup here if you haven't already: https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/setting-up-the-pattern-library-for-development

**Comment by Firenz** [comment]
@Angamanga I just made the PR, check it whenever you can, please :relaxed:
