### ISSUE TITLE
Postcards should have chevrons after the titles

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2272]
### Expected behaviour
![image](https://user-images.githubusercontent.com/29209303/32293060-9cb9f86a-bf07-11e7-8cd7-a307373d3cbf.png)

### Actual behaviour
<img width="705" alt="screen shot 2017-10-26 at 8 44 43 am" src="https://user-images.githubusercontent.com/29209303/32293068-a4fd6fb6-bf07-11e7-907f-c60b163e6b2f.png">

### Steps to reproduce the behaviour/error
go to data view, look at postcards

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-493

**Comment by Angamanga** [comment]
@Justin-Scherer What should the chevron do? Does it replace the '...' symbol?

**Comment by justinscherer** [comment]
@Angamanga it's just a visual indicator of tappability. It's appended to the end of the title. Otherwise, there's no way for a user (especially in mobile) to tell that the card is tappable. The titles look like neither links nor buttons. 

The "..." stays there, because it has a bunch of menu items underneath it.

**Comment by kinstelli** [comment]
@Justin-Scherer -- What should the rules be for wrapping/ellipses-ing the title text? Should there be a relative width cutoff, or maybe a total number of characters? 

Also, should the chevron only appear on smaller screens, or all screens?

**Comment by justinscherer** [comment]
@kinstelli 
> What should the rules be for wrapping/ellipses-ing the title text? Should there be a relative width cutoff, or maybe a total number of characters?

2 lines then ellipses before the chevron. It should never wrap more than once before being truncated. 

>Also, should the chevron only appear on smaller screens, or all screens?

All screens. The chevron there as a visual indicator of tapability. It's an accessibilty requirement because we're not using standard link styles.

**Comment by kinstelli** [comment]
@justinscherer -- Should these chevrons be right-aligned? Should they just appended to the right of the title, or on the top line of the title if it wraps? (related to: ushahidi/platform/issues#2271 )

Also, assuming I'm using the `chevron-right` icon, should it be scaled relative to the title text size?



<img width="464" alt="screen shot 2017-11-23 at 3 34 34 pm" src="https://user-images.githubusercontent.com/6600708/33188996-3257a5b2-d064-11e7-89aa-a986dad39a29.png">

**Comment by justinscherer** [comment]
@kinstelli make the chevron 9x12px align it to the baseline of the text, so that if you were to draw a line on the bottom of the text, the chevron would be sitting on the same line. That should "visually" vertically centre-align the chevrons with the lower case letters and make them look like just another glyph in the font. 

Leave 12px of space between the last letter in the title and the left of the chevron. 

Have a look at the `index.html` file in here and click around to find spacing. It's not pixel perfect, but it's close.

[data view.zip](https://github.com/ushahidi/platform/files/1502101/data.view.zip)
