### ISSUE TITLE
Filter counter should disappear if there are no filters active

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2274]
### Expected behaviour
![image](https://user-images.githubusercontent.com/29209303/32293394-9081d38c-bf08-11e7-9400-6a90fe218074.png)

^^when no filters are active

### Actual behaviour
<img width="920" alt="screen shot 2017-11-01 at 1 27 25 pm" src="https://user-images.githubusercontent.com/29209303/32293375-8444e898-bf08-11e7-8e4c-6ebc3ce102b9.png">

### Steps to reproduce the behaviour/error
load map or data view

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
Won't fix. We want to think more about making thing consistent and how it affects user flows before we merge a solution since it's a bit confusing to see them dissapear and come back :/
