### ISSUE TITLE
Remove the weird on-state box from every form field

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2275]
### Expected behaviour
<img width="590" alt="screen shot 2017-11-01 at 1 32 34 pm" src="https://user-images.githubusercontent.com/29209303/32293607-49d03202-bf09-11e7-9886-87e359ff7034.png">

^^on-state with no weird box around it. The interface does not randomly "jump" 20px every time a user clicks a field.

### Actual behaviour
<img width="1021" alt="screen shot 2017-11-01 at 1 30 41 pm" src="https://user-images.githubusercontent.com/29209303/32293572-2f6a3e30-bf09-11e7-9e26-5cd153d240d2.png">

^^ there's a weird box aroudn the input field that activates for some reason every time you click it. 

### Steps to reproduce the behaviour/error

click any field in edit mode.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by Angamanga** [comment]
Merged to develop, testing-checklist: 
- [] Go to data-view
- [] Select a post and start editing
- [] Click on any text-input-box
- [] You should not see this white box around the input-box:
<img width="1021" alt="screen shot 2017-11-01 at 1 30 41 pm" src="https://user-images.githubusercontent.com/29209303/32293572-2f6a3e30-bf09-11e7-9e26-5cd153d240d2.png">
- [ ] The box should still be highlighted around the input-field:
<img width="590" alt="screen shot 2017-11-01 at 1 32 34 pm" src="https://user-images.githubusercontent.com/29209303/32293607-49d03202-bf09-11e7-9886-87e359ff7034.png">

**Comment by willdoran** [comment]
This passes QA for me.
