### ISSUE TITLE
There's a random hover state for the time metadata

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2277]
### Expected behaviour
hover state on postcard should show full date and time
### Actual behaviour
<img width="529" alt="screen shot 2017-11-01 at 2 06 41 pm" src="https://user-images.githubusercontent.com/29209303/32295138-04aee808-bf0e-11e7-8562-752ae93d124a.png">

### Steps to reproduce the behaviour/error
hover cursor over time metadata in postcard

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rjmackay** [comment]
Thats broken. The hover state is supposed to show the full date + time of the event (similar to times shown on github).
If you want to replace that hover state, is there somewhere else we can present that info?

**Comment by justinscherer** [comment]
> The hover state is supposed to show the full date + time of the event (similar to times shown on github).

Ok that makes sense. I just couldn't figure out what it was trying to show me. It should remain, but show the full date and time, then.

**Comment by rowasc** [comment]
other examples for dates before today. Still broken. 

<img width="580" alt="Screen Shot 2019-06-10 at 22 57 49" src="https://user-images.githubusercontent.com/2434401/59238169-3aa89d80-8bd3-11e9-8919-40862144bfc1.png">
<img width="744" alt="Screen Shot 2019-06-10 at 22 58 22" src="https://user-images.githubusercontent.com/2434401/59238179-45fbc900-8bd3-11e9-833e-44304184c9f8.png">


This is likely a good first issue for someone familiar with AngularJS

**Comment by Erioldoesdesign** [comment]
This styling isn't very accessible...it'd be nice to design something that is accessible...

**Comment by rowasc** [comment]
@Erioldoesdesign should we open this up for W/S/C OSS design contributors or did you start working on it ?

**Comment by AlanaFarkas** [comment]
Hi, 

I'd like to pick this ticket up!

**Comment by rowasc** [comment]
awesome, thank you. !
