### ISSUE TITLE
Bulk Archive does not archive all my posts

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2279]
I selected 362 posts out of 390 to archive from a saved search

### Expected behaviour
On refreshing my page, i expect to see only 28 posts available in my view

### Actual behaviour
I got 118 posts in my view AFTER bulk archiving

### Steps to reproduce the behaviour/error
Log into your deployment
Select a saved search with a siginificant number of posts ( preferably over 300 if possible :D)
Attempt to bulk archive a significant number of posts.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): https://uchaguzi.or.ke

Aha! Link: https://ushahiditeam.aha.io/features/PROD-492

**Comment by aoduor** [comment]
Okay, chalked this up to impatience on user side( I did the same thing with about 700 posts and just waited for them to clear out of my screen view. Took about a minute). Lesson here is we should manage the user's expectation i.e Because performing bulk actions on a large number of posts will take time, we should issue a notice or warning that it's going to take a while, OR issue a notice once bulk actions have successfully completed.

**Comment by rjmackay** [comment]
Yea. This is because the way to do bulk actions is horrible. We run each action individually, ie they all get a single HTTP request. This was supposed to be fixed a year ago but the work on it stalled :( Refs #1023

**Comment by rowasc** [comment]
<img width="939" alt="Screen Shot 2019-06-09 at 14 53 29" src="https://user-images.githubusercontent.com/2434401/59162385-60944c00-8ac6-11e9-82cf-9c72985e5510.png">
Closing as we have bulk actions in data view now and infinite scrolling instead of a  number of posts to view
Can reopen if needed
