### ISSUE TITLE
Chinese language should say "Mandarin"

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#2280]
### Expected behaviour
When I change languages on the front-end, it lists the language as "Chinese"

### Actual behaviour
Technically is should be listed as "Mandarin"

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-490

**Comment by kinstelli** [comment]
Is there a designated person who’s been administering Transifex stuff? It looks like those strings come dynamically from the set of Transifex translations for our projects, but it also looks like there’s no way to update a language’s name or other details once a language has been added — we can only add/delete languages, even through the API.

A few people online suggested cloning the translation set to another name, then deleting or disabling the old one, but I don’t know enough about what this might break if we wanted to do that.
