### ISSUE TITLE
Lock styling is off when bulk actions is selected

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2284]
Steps to reproduce:

Select bulk action and then view post card that is locked. 
![Screen Shot 2017-10-13 at 3.22.49 PM.png](https://zube.io/files/ushahidi/ef1638a8d20d272d2f340c68a2d62d1c.png)

Should look like this:

![Screen Shot 2017-10-13 at 3.23.53 PM.png](https://zube.io/files/ushahidi/84c745974b64d9f5011ef3f5756e317d.png)

**Comment by rowasc** [comment]
<img width="544" alt="Screen Shot 2019-06-10 at 23 05 13" src="https://user-images.githubusercontent.com/2434401/59238374-43e63a00-8bd4-11e9-896b-16f654dfc2dd.png">
The lock is aligned with the post card header now instead of crashing with the checkbox  👍 
closing
