### ISSUE TITLE
Improve analytics on activity page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2287]
Going to try my best to describe my experience with cranking out numbers for 2chaguzi.

**What I needed**
As the "manager" of the Uchaguzi deployment, there's a couple of things that I needed to be aware of during the lifetime of the deployment, and after it's completion. 

I needed to know the following

1. Where was my data coming from ( a break down of all my data by it's sources, inclusive of the mobile apps )
2. How much of the data I was receiving is viable/relevant to my theme ( and broken down by source as well )
3. How my teams were doing in terms of processing incoming data ( as a whole and broken down by source) i.e rates of 
- Structuring data
- Publishing data
- Archiving data
4. How my activity this time round compared to the previous deployment 

To get this, I needed the following raw numbers
1. Total number of posts by source
(and broken down by source)
2. Total number of posts archived
3. Total Number of posts structured/unstructured
4. Total Number of posts published/unpublished

Based on the above, I was then able to compute
(broken down by source)
1. Viable posts
2. Structuring rates ( against the total number of posts vs total number of viable posts)
3. Publishing rates ( against the total number of posts vs total number of viable posts)
4. My team's rate of publishing posts that have already been structured ( to see if one team may possibly have been slowing the other down) 

**How did I get what I needed?**
The activity page gives me the following info ( mostly through visuals - which is great, but didn't help me with what i needed to get.)
- Total number of posts received over time by
-- Category
-- Survey
-- Status

- Total number of posts received by volume, according to 
-- Category
-- Survey
-- Status
I had one of two options
1. Download the full dataset via CSV, use a series of filters to get my raw numbers
_Problem: CSV file was too huge, and it wouldn't filter according to set search criteria_
2. Ask @tuxpiper to perform a single DB query that would return all the data i needed all at once in a matter of seconds
_This is the option i went with :)_
Sample dataset returned
`data_provider structured  status  count
NULL    1    archived    73
NULL    1    draft    9
NULL    1    published    482
email    0    draft    1
smssync    1    archived    171
smssync    1    draft    404
smssync    1    published    809
smssync    0    archived    4685
twitter    1    archived    41
twitter    1    draft    156
twitter    1    published    117
twitter    0    archived    2140
twitter    0    draft    1034
twitter    0    published    1`

**Takeaways**

- Analytics need to also give deployers insights into how their teams are doing in terms of processing/data management
- We need to make it easier to discover some of these numbers right away from the UI
- We currently have no way of breaking down what was received from web into what came in from the bot or our mobile apps from the UI

Opening up the floor to everyone else to see if you have any thoughts to add into this.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-487

**Comment by jshorland** [comment]
So good -- thank you @aoduor !! i'm sure we'll have some follow up questions for you soon.

**Comment by willdoran** [comment]
@aoduor This was hugely insightful and useful.

I believe that there are a number of pieces of data that we can expose in a simple form that would allow further analysis. There are more abstract elements like determining parts that are "viable/relevant to my theme", which I think would be better considered once we get a basic version out. 

Honestly, this can't happen until we stablise a number of pieces but it is hugely important to me because i feel it's A) Key to using the platform B) Well within existing capabilities. 

My suggestion is that we treat this as an Epic and that we can do the work of splitting it into phases and pieces of work.

**Comment by jshorland** [comment]
Agreed @willdoran. I'm going to keep it as it is in one issue for now and
start breaking down scope in the same issue. Then we can schedule into Q1
or Q2 based on dependency work and priorities.

**Comment by aoduor** [comment]
Here's a link to the spreadsheet with the stats: https://docs.google.com/spreadsheets/d/1EZChSy8h4ZMfSXvnMuA2dIqhfjz1UWYUAbjMyp1_lc0/edit#gid=1961140243
