### ISSUE TITLE
Disable ability to download data for non logged in users

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2288]
Data privacy concerns :).

Self explanatory :).

- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): uchaguzi.or.ke

**Comment by jshorland** [comment]
This is being completed within the CSV improvement dev cycle.
