### ISSUE TITLE
Intercom button perfectly covers add post button

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2290]
### Expected behaviour
- Intercom button should not cover Add Post button
### Actual behaviour
<img width="1680" alt="screen shot 2017-11-16 at 13 58 46" src="https://user-images.githubusercontent.com/2694405/32910122-68b03572-cad6-11e7-9f39-338ea8a50c4b.png">

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by crcommons** [comment]
@justinscherer Where should we put the intercom button?

**Comment by willdoran** [comment]
Suggestion is to add this to the support menu modal

**Comment by justinscherer** [comment]
Floating action buttons are a pain. 

Off the top of my head, we can put it on the support modal. Here:

![Screen Shot 2017-11-16 at 4.27.55 PM.png](https://zube.io/files/ushahidi/e0f2b29638c90c0e9d031d4377e4cdb7.png)

Same styling as the other items, but put it on the bottom of the list. Headline: "Contact us" Description: "Contact Ushahidi's support team." 

@aoduor can you think of a better description than that?

**Comment by willdoran** [comment]
I changed this but I've not committed it since it appears that intercom is disabled in Prod, is that correct @jshorland?

**Comment by rjmackay** [comment]
@willdoran intercom is enabled in prod, but only for logged in users

**Comment by willdoran** [comment]
@rjmackay OK great, I'll push for review this morning!

**Comment by Angamanga** [comment]
This is still happening in production when logged in. @willdoran did you have a pr for the change somewhere?

**Comment by willdoran** [comment]
Nope, this needs to be fixed in PL. I've pinged Seth on it.
