### ISSUE TITLE
Setting required fields in a survey causes error on attempt to structure a post.

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2292]
### Expected behaviour
When I attempt to assign an unstructured post to a survey, I should be redirected to the post edit page

### Actual behaviour
Assigning a post to a survey with required fields pops up an error message.

(only way to get around this is making all required fields on a survey unrequired. Tested this on some dreams deployments)

See this screenshot from a user.

![img_22112017_171403_0](https://user-images.githubusercontent.com/721918/33126371-5160d6d8-cf95-11e7-9c98-f15d87d1ffc8.png)

### Steps to reproduce the behaviour/error
* Set up a deployment
* Create a survey and set a few required fields
* Set up twitter/sms as a data source
* Attempt to structure a post

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution ( Several Ushahidi .io deployments ). User complaint on https://ecc.ushahidi.io/views/map from the community support channel
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment]
huh... I can't seem to replicate this on deployments now. it should have gotten fixed in the latest release. @aoduor would you mind trying to replicate this as well? and if it's fixed please close this.
