### ISSUE TITLE
"Search all for 'test'" button appears at the top of the filters dropdown

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2293]
![Screenshot 2017-11-23 13.39.18.png](https://zube.io/files/ushahidi/8fa5044e8aeb2daf4dd9f70871a70368.png)

This is a bit weird. I'm not sure if
1. The button just shouldn't be there?
2. It should, but clicking in the text search box should show the full filters dropdown too?

Currently it shows a different dropdown with *only* this button
<img width="684" alt="screenshot 2017-11-23 14 01 06" src="https://user-images.githubusercontent.com/7965/33155612-c7fb5eaa-d056-11e7-8860-ea6ec43e6dd8.png">

**Comment by justinscherer** [comment]
Hey @rjmackay "search all" is the default behaviour to "activate" the search. You can't save a search that hasn't been activated yet, and once it's been activated, the "Search all for..." button should disappear. So those two buttons should never appear at the same time. 

When the search is active and the the search results are being shown on the view below the dropdown, the "Search all for _____" button should disappear. 

In your examples above, in the first image, the "search all for adsf" button shouldn't be there, it should be there in the second image, but the dropdown is too big. 

Does that help?

**Comment by rjmackay** [comment]
Hrm. Kinda. I might need to demo it to better explain. I found the interaction of having 2 different dropdowns to be weird, and I'm not sure if we wanted to keep that behaviour.

Steps:
1. Open the filter dropdown
2. Add some filters
3. Click into the 'Search' text box to add a search string
.. Dropdown is closed
4. Start typing
.. Dropdown opens with *only* "Search for all..."

- I was wondering if they should really just be a single dropdown? Its weird to get thrown out of one, into the other.
- If we did combine them, the main filter dropdown already has an 'Apply filters' button - so do we still need to show the 'Search for all...' button at all?

Separate from that I'll log the issue with showing 'Save search' before we've applied the filters.

**Comment by justinscherer** [comment]
> I was wondering if they should really just be a single dropdown? Its weird to get thrown out of one, into the other.

Yes, single dropdown. Sorry, I assumed that was already the case. 

> If we did combine them, the main filter dropdown already has an 'Apply filters' button - so do we still need to show the 'Search for all...' button at all?

Nice catch. We wouldn't need the "Search all for..." CTA in that case. Can we change the text to read "Apply" instead of apply filters, then it would cover both the filtering and searching use cases.

**Comment by rjmackay** [comment]
Ah right - so I found the reason why there were originally 2 dropdowns. This was actually the designed, but not implemented behaviour for when typing:
![Screenshot 2017-11-24 11.06.12.png](https://zube.io/files/ushahidi/5ed218b6ad67862725a105e7f5ed5405.png)

I'll go ahead an combine the dropdowns. If we want to add auto suggest when typing later we can always split the dropdown again.

**Comment by rowasc** [comment]
@justinscherer @rjmackay by reading this it's not clear to me, sorry: are we supposed to be sending a new http request every time the user hits a key? That used to not be that way (which I think is why we had the button) . 
In data this doesn't happen because the filters don't get applied automatically but in map it can be a problem.

**Comment by rjmackay** [comment]
@justinscherer 
To make sure its clear. The previous behaviour was that:
- We only searched a text string after the user pressed "Search all for..." even on the map view.

While combining the dropdowns I changed this to:
- Apply the text filter as you type (though with a delay, so it doesn't search for every key press)
This more closely matches all the other filters. Otherwise its odd that - on the map view - most filters apply instantly but the text search does not.
However if I'm wrong I can revert some of the changes.

**Comment by justinscherer** [comment]
> While combining the dropdowns I changed this to: 
Apply the text filter as you type (though with a delay, so it doesn't search for every key press)
This more closely matches all the other filters. Otherwise its odd that - on the map view - most filters apply instantly but the text search does not.
However if I'm wrong I can revert some of the changes.

This works. Thanks, @rjmackay
