### ISSUE TITLE
filters-searchbar directive should be agnostic, not tied to postfilters

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2295]
### Expected behaviour
filters searchbar is used in many views. It shouldn't be tied to the PostFilters service at all

### Actual behaviour
filters-searchbar has weird post specific code in it

**Comment by rowasc** [comment]
Robbie already fixed this , closing https://github.com/ushahidi/platform-client/commit/cc8c60e80fce3a706c4a073907a0190640088c82
