### ISSUE TITLE
Clearing text filter refreshes search results, even if it hadn't yet been applied

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2296]
### Expected behaviour
If I clear the text filter but it hadn't been a applied, the field should clear but posts shouldn't reload

### Actual behaviour
Post reload

### Steps to reproduce the behaviour/error

Aha! Link: https://ushahiditeam.aha.io/features/PROD-485

**Comment by rowasc** [comment]
Not happening anymore
