### ISSUE TITLE
Don't allow saving a search that hasn't yet been applied

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2297]
From [#2293 (ushahidi/platform-client#467)](https://zube.io/ushahidi/platform/c/2293) 
> You can't save a search that hasn't been activated yet, and once it's been activated

I think we missed this in the requirements for [#2276 (ushahidi/platform-cloud-interface#115)](https://zube.io/ushahidi/platform/c/2276) 

Changes
- Don't show save/update search etc until a search is applied

Need to clarify:
- Should filter 'bugs' show up at all before a search is applied?

Aha! Link: https://ushahiditeam.aha.io/features/PROD-484

**Comment by rjmackay** [comment]
We're going to have to do this in a future release since we missed this in our initial requirements, and it requires some significant changes to how we track what is/isn't yet applied

**Comment by rowasc** [comment]
@Angamanga I think we were working on this in another ticket no?

**Comment by Angamanga** [comment]
Hm, yes, it is related to this one: https://github.com/ushahidi/platform/issues/4031

**Comment by rowasc** [comment]
Ok, I'll close this one so we don't get confused
