### ISSUE TITLE
I should be able to see that I'm in a collection when I'm in data mode

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2299]
### Expected behaviour
Show the bug icon like we do for saved searches but without filters since it's a collection?
### Actual behaviour
I have no visual clues that I'm in a collection . 
### Steps to reproduce the behaviour/error
Select a collection in data mode.
You will have no visual clues that you are inside a collection.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
cc @rjmackay @justinscherer @jshorland

**Comment by rjmackay** [comment]
I'd definitely suggest a 'Collection: xyz' bug, since a collection behaves like a filter.
Ideally showing that on both the map and data views for consistency.
