### ISSUE TITLE
Empty slider at bottom of modals

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2300]
### Expected behaviour
Slider is not in DOM unless it has content

### Actual behaviour
Slider is just below the fold, you can tab to it.

### Steps to reproduce the behaviour/error
Open a platform deployment
Click on login
Click in the email field
Hit tab a few times....
...Despair...
Sorry. I mean: see an empty slider and dismiss button

Aha! Link: https://ushahiditeam.aha.io/features/PROD-483

**Comment by Angamanga** [comment]
A start of solution is found here: https://github.com/ushahidi/platform-client/pull/1492
