### ISSUE TITLE
Layout for main dashboard view

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2302]
- Create layout for main dashboard view and project card patterns in pattern library
- Map can be a placeholder and assumed to use leaflet
- Sparklines can be a placeholder and assume we'll use an existing JS library

https://xd.adobe.com/view/1b2751c6-fa51-4f52-947b-be70ace0e8a1/screen/3ee21248-958b-46b3-bd8d-e7fcb5e594a0/Dashboard-Normal-Browser

**Comment by justinscherer** [comment]
I updated the links to the prototype and design spec to reflect changes to the "Upgrade" use case

**Comment by rjmackay** [comment]
@Angamanga is this done?

**Comment by Angamanga** [comment]
http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/md-list.html

**Comment by Angamanga** [comment]
Waiting for new pl-tag.

**Comment by Angamanga** [comment]
Correct positioning of dropdowns for the layout are in this pr: https://github.com/ushahidi/platform-pattern-library/pull/169
