### ISSUE TITLE
Pattern for New Project form

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2304]
Patterns for New Project form and flow in dashboard
- New project form: https://xd.adobe.com/view/1b2751c6-fa51-4f52-947b-be70ace0e8a1/screen/70a9e9f6-1ea1-41c5-b67c-9dd3b3636cc1/New-Project-Empty
- New project success screen: https://xd.adobe.com/view/1b2751c6-fa51-4f52-947b-be70ace0e8a1/screen/a75179bb-9aad-458d-9023-c0c87dca17ca/New-Project-created (might just be a variation on the project card?)
- Error pattern https://xd.adobe.com/view/1b2751c6-fa51-4f52-947b-be70ace0e8a1/screen/ce7dbe7f-b912-4608-b9b7-90f9a96b2ba2/New-Project-Error
  - Should already exist, but double check it all works

**Comment by rjmackay** [comment]
@Angamanga is this done?

**Comment by Angamanga** [comment]
New project-form: http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/md-create.html

New project success screen: http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/md-new.html

Error pattern: @middle8media

**Comment by Angamanga** [comment]
Waiting for new pl-tag.

**Comment by Angamanga** [comment]
error-state in this pr: https://github.com/ushahidi/platform-pattern-library/pull/169, the rest is fixed
