### ISSUE TITLE
Pattern for archive project flow

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2305]
- Archive confirmation card: https://xd.adobe.com/view/1b2751c6-fa51-4f52-947b-be70ace0e8a1/screen/6150545c-635c-41a0-86d3-0ede6dc1380e/Archive-project-
- Confirmation slider already exists
- ... menu should already be possible I think?

**Comment by rjmackay** [comment]
@Angamanga is this done?

**Comment by Angamanga** [comment]
Pattern is here:
http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/md-archive.html

**Comment by Angamanga** [comment]
Waiting for new pl-tag.
