### ISSUE TITLE
When deselecting a parent-category, but keeping the children in the filter-dropdown, there is no way of seeing and deselecting those children in the mode-context-bar

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2308]
### Expected behaviour
When I deselect a parent-category in the filter-dropdown, the child-category should still be visible in the mode-context-bar-filters
### Actual behaviour
The children is not visible, but is still selected
### Steps to reproduce the behaviour/error
- Go to map-view
- Select a couple of child-categories in the filter-dropdown, make sure that their parents are deselected
- Look at the mode-context-bar, only the parents, deselected, is visible, no children.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rjmackay** [comment]
Styling is a bit janky - but I've made the children always visible in the mode-context filters
