### ISSUE TITLE
Error when saving surveys on .io deployment

### ISSUE THREAD

**Issue by dukedanny** [ushahidi/platform#2311]
### Expected behaviour
User should be able to save new fields when they create a survey. 

### Actual behaviour
I get the error below

![unnamed](https://user-images.githubusercontent.com/437728/33362555-fe3d1936-d4ed-11e7-931a-15b01ee6a237.png)

### Steps to reproduce the behaviour/error
Open deployment
Logged in as admin
Create survey
Add field to survey
Save field

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by justinscherer** [comment]
> Steps to reproduce the behaviour/error

I wasn't able to reproduce. EXAMPLE, PLEASE IGNORE THIS COMMENT.

**Comment by jshorland** [comment]
Duplicate. Closing in favor of #2306

**Comment by jshorland** [comment]
@dukedanny can you comment any additional context we need on #2306
