### ISSUE TITLE
Everytime I click on this button, I get an error message. 

### ISSUE THREAD

**Issue by ifender** [ushahidi/platform#2312]
### Expected behaviour
When I click on the add button, a table should pop up. 

### Actual behaviour
When the add button  is clicked, I get a 404 error message. 

### Steps to reproduce the behaviour/error
Log on to the deployment as an admin and try clicking the add table button. 

##### Where
Demo site : http://dreamsdemo.ushahidi.io/

- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment]
What is "add table" -- can you give me a screen shot?

**Comment by ifender** [comment]
Here's the screenshot
![dscf0591](https://user-images.githubusercontent.com/25202020/33362999-79458d6a-d4ef-11e7-8912-0860f1945578.JPG)

**Comment by Shadrock** [comment]
What a wonderful table.

**Comment by jshorland** [comment]
I think we'll table this issue for now.

On Wed, Nov 29, 2017 at 10:26 AM, Shadrock Roberts <notifications@github.com

**Comment by Shadrock** [comment]
That's it, we're closed!
