### ISSUE TITLE
UNABLE TO DOWNLOAD SPECIFIC SURVEYS ON CSV

### ISSUE THREAD

**Issue by Hazellaura** [ushahidi/platform#2313]
### Expected behaviour
I would like to be able to download data from one survey at a time in a CSV file. For example, I would like to download only the security issues data or the voting issues data alone. 

### Actual behaviour
When I try to download one data set from one survey for example only security issue, it downloads into CSV the complete data set from all the surveys. So I end up with an excel template with over 500 data points instead of only 100 from one survey. 

### Steps to reproduce the behaviour/error
1. I logged on to the Uchaguzi deployment 
2. I selected only the security issues survey from the side bar 
3. Limited the search parameters to:
-Published and draft posts, 
-Posts from SMS, Twitter and the Web 
-Posts that had come in from the repeat election day 26th of October to the 2nd of November 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): Uchaguzi

**Comment by jshorland** [comment]
Well that's annoying. This should have a fix with the release we are pushing this week. I'm going to make sure we've fixed it in QA and let you know when it's fixed.

**Comment by Ani0610** [comment]
@Hazellaura  check my issue it will help you.
[https://github.com/Ani0610/Download-csv-file/issues/2](url)
