### ISSUE TITLE
text missing from postcard statuses in mobile

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2314]
### Expected behaviour
The little circles in the top left corner of postcards should have text in them. 
### Actual behaviour
<img width="725" alt="screen shot 2017-11-29 at 10 43 52 am" src="https://user-images.githubusercontent.com/29209303/33363628-420583f2-d4f2-11e7-8aae-137ceee9a09f.png">

### Steps to reproduce the behaviour/error
Go to data view in a mobile-sized viewport

### How it looks now
It has a circle but no label
![Screenshot from 2020-10-10 19-29-04](https://user-images.githubusercontent.com/2434401/95666323-e303a480-0b2e-11eb-903f-b5fa7421f160.png)

### How it should be
It has a label (rough example, we need to adjust padding probably a lot better than I did)
![Screenshot from 2020-10-10 19-28-56](https://user-images.githubusercontent.com/2434401/95666324-e303a480-0b2e-11eb-9f0b-ddcfd5b60ab0.png)

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-480

**Comment by sethburtonhall** [comment]
@justinscherer reminder on what specifically should be in the circle?

**Comment by justinscherer** [comment]
status: Published, under review, etc.

**Comment by emalindahk** [comment]
Hi, I'm Emmah I would like to work on this for my outreachy contribution

**Comment by Sunairaa** [comment]
Hi @Angamanga is this issue still available can I work on this? i am an outreachy candidate and would love to contribution on it
.

**Comment by rowasc** [comment]
@emalindahk please go ahead!
