### ISSUE TITLE
Number in yellow circle beside search field doesn't correspond to number of filters enacted

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2316]
### Expected behaviour
1 saved search enacted should show up as 1 filter applied in yellow circle
### Actual behaviour
It is an arbitrary number, in this case 3. 

<img width="1668" alt="screen shot 2017-11-29 at 10 48 43 am" src="https://user-images.githubusercontent.com/29209303/33363843-256f0960-d4f3-11e7-8ef3-235508945c70.png">

### Steps to reproduce the behaviour/error
Create a saved search, apply it, update it. 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
Note:
The number represents the filters applied in the saved search, as the saved search is only a filter collection, and it changes when the user adds/removes filters for updating the saved search

**Comment by rowasc** [comment]
Closing . See my comment above.
