### ISSUE TITLE
Reset password is hard to find when logged in.

### ISSUE THREAD

**Issue by ifender** [ushahidi/platform#2317]
### Expected behaviour

I expect to see the settings button where I can reset password.

### Actual behaviour
Looked around and I could not see where to do it.

### Steps to reproduce the behaviour/error
Log in as an admin, then looked on the left hand side for settings, and I could not find it.
Also, I tried clicking on a few buttons on the lower left hand side, and I was kicked out. Had to delete **forbidden** on the URL to get back in.
![posts ushahidi internal qa](https://user-images.githubusercontent.com/25202020/33363862-3139f5a2-d4f3-11e7-93ee-85e884eddf06.png)

On the screenshot above, I clicked on the part highlighted in red, and I was kicked out. 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-479

**Comment by jshorland** [comment]
Resetting password happens on your user account -- unfortunately it's extremely hard to find.

**Comment by rowasc** [comment]
@CeciliaHinga can you make sure we add some docs on how to do it? Here's a screenshot of how to do it in user settings when logged in 

<img width="660" alt="Screen Shot 2020-01-02 at 17 35 06" src="https://user-images.githubusercontent.com/2434401/71691478-441f7000-2d86-11ea-9b13-86667365fd4a.png">
and the other way is "forgot password" before logging in
