### ISSUE TITLE
Applied filter bugs do not wrap in a rational way

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2318]
### Expected behaviour
Saved searches should be on one line with the filter bugs below it. The bugs below it should fill the horizontal line before they wrap.

### Actual behaviour
<img width="1668" alt="screen shot 2017-11-29 at 10 48 43 am" src="https://user-images.githubusercontent.com/29209303/33363937-6ee8b5f0-d4f3-11e7-8e60-2a4442ffcbea.png">

^^Why is 
"Status: under review" on it's own line?

### Steps to reproduce the behaviour/error
Apply a saved search with a bunch of criteria in it. 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-478

**Comment by rowasc** [comment]
This is grouping things by what type of filter it is, that's why they are separated In lines

**Comment by Erioldoesdesign** [comment]
Errr makes sense when it's explained but I'd eat my hat if any users are able to tell that...

This part is a bit of a challenge for most users. The tree diagram is helpful, but also there's no clear indication on what happens to filters 'down the line' if you remove a 'top filter'

In general...this need a goooooood look at.
