### ISSUE TITLE
"Clear Filters" CTA should have an opaque background and the font should be bold

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2319]
### Expected behaviour
Use the "beta button" style so that the button becomes much more readable.
http://preview.ushahidi.com/platform-pattern-library/master/assets/html/2_fragments/\

``.ltr-namespace .button-beta {
    color: #373E46;
    background-color: #FAFAFA;
}``

### Actual behaviour
`` .ltr-namespace .button-link {
    color: #373E46;
    font-weight: normal;
    font-size: 1em;
    letter-spacing: normal;
    background-color: transparent;
    box-shadow: none;
}``

<img width="962" alt="screen shot 2017-11-29 at 10 55 15 am" src="https://user-images.githubusercontent.com/29209303/33364184-5fa4b124-d4f4-11e7-8b52-ee8e498f17f7.png">

### Steps to reproduce the behaviour/error
Open filter pane

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by caharding** [comment]
@justinscherer can I close in favor of UI refresh https://app.zenhub.com/workspace/o/ushahidi/platform-pattern-library/issues/205

**Comment by sethburtonhall** [comment]
closing in favor of app.zenhub.com/workspace/o/ushahidi/platform-pattern-library/issues/205
