### ISSUE TITLE
could not switch twos while editing

### ISSUE THREAD

**Issue by Alengai** [ushahidi/platform#2320]
### Expected behaviour
I can be able to switch editing on different tweets 
### Actual behaviour
I couldn’t directly switch to another tweet 
### Steps to reproduce the behaviour/error
- I was trying to structure a tweet post 6680 on ushahididev.com
- I clicked on another tweet but it didn’t display immediately 
- on the left hand side the tweet was selected but the data was still the same 
<img width="1359" alt="screen shot 2017-11-29 at 10 54 05" src="https://user-images.githubusercontent.com/28722642/33364080-ee2ec426-d4f3-11e7-98a0-851fd98be8ef.png">

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by Shadrock** [comment]
Great bug @Alengai !

**Comment by jshorland** [comment]
Nice catch. @Angamanga would you mind double checking this in QA before we push to production?

**Comment by Angamanga** [comment]
@jshorland Yep, checking now!

**Comment by Angamanga** [comment]
@jshorland Yes it is happening. Only on unstructured posts before a survey is selected. But it is happening.
