### ISSUE TITLE
Filter-bar is changing size to almost full-screen in map-view

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2321]
### Expected behaviour
- In map-view, the filter-bar should stay the same size when the dropdown is active/ input field is focused

### Actual behaviour
- It changes width to almost the entire width of the screen.

### Steps to reproduce the behaviour/error
- Go to map-view
- Click on filter-dropdown
- See the bar change width
- Compare with behaviour in data-view

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-477

**Comment by rjmackay** [comment]
I might have got this wrong, but I changed this intentionally to match the behaviour in the pattern library.
@justinscherer should the filters bar expand to full width when opened? Should this happen on both map and data view? or just map view?

**Comment by justinscherer** [comment]
> @justinscherer should the filters bar expand to full width when opened? Should this happen on both map and data view? or just map view?

I'm having a hard time picturing this for some reason. Full-width of what? Can you send a screencap?

**Comment by lalidiaz** [comment]
I am Outreachy applicant , may I try to solve this one please?

**Comment by rowasc** [comment]
@Angamanga is this something we want to do?

**Comment by Angamanga** [comment]
Lets close it.
