### ISSUE TITLE
Switching between collection and saved-searches

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2322]
### Expected behaviour
Switching between collection in data-mode and saved-search and then back again should update the filters and the url.

### Actual behaviour
Url and filters are not always changed when switching from saved search to collection in data-view. Happens very randomly

### Steps to reproduce the behaviour/error
1. In data view, select a saved-search (i selected Test 3 in qa)
2. Select a collection with data-view as default
3. url is updated to collections
4. correct posts are not displayed
5. filters are not updated.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-476

**Comment by rowasc** [comment]
I don't think this is a blocker. I'd argue that we probably should drop the URLs for collections and saved searches except for an initial redirect if the user goes to them from an old link, tho. But that would make the sprint drag on for a couple more days of testing too
