### ISSUE TITLE
Incorrect Timestamp on .io deployment

### ISSUE THREAD

**Issue by dukedanny** [ushahidi/platform#2325]
### Expected behaviour

- Submit a post via SMS to deployment
- Post is received on platform
- Timestamp shown is the precise time the post was sent. 

### Actual behaviour

- Incorrect timestamp showing approximately 7 minutes later than when post was submitted

![image](https://user-images.githubusercontent.com/437728/33418452-f07fc612-d5b6-11e7-8bef-1288782ff020.png)

### Steps to reproduce the behaviour/error

- Submit a post to the platform via SMS
- Check timestamp

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by caharding** [comment]
@willdoran can you see if it is reproduceable and still an issue?

**Comment by rowasc** [comment]
closing as this is not in the post card anymore
