### ISSUE TITLE
Whoops error on refreshing page

### ISSUE THREAD

**Issue by Hazellaura** [ushahidi/platform#2326]
### Expected behaviour
 I wanted to go to the timeline page and view data.  

### Actual behaviour
I was unable to go to the data page. After the .io there was 404 error that said "Oops the page cannot be accessed".

### Steps to reproduce the behaviour/error
1. We logged into the BHESP deployment and we had the old timeline view 
2. on refreshing the page we could see data mode but received an "whooops" error. 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

![ushahidi bar hostess empowerment and support program 1](https://user-images.githubusercontent.com/25499815/33418930-4809bb98-d5b9-11e7-9a1e-3af17010b4b2.png)

**Comment by jshorland** [comment]
I don't *think* people are going to encounter this much, but i think /timeline should redirect to /data
