### ISSUE TITLE
Data view sorts by creation time, not post time

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#2329]
This is not buggy or deviant behaviour per-se , just checking with @justinscherer and @jshorland  if this change in behaviour is intentional .

It does have some side effects in specific cases though (see Steps to reproduce below)

### Expected behaviour
When opening the timeline view, the posts used to be by default sorted by **post time** , in descending order.

It may be expected that this behaviour to be preserved in the new release.

### Actual behaviour
The data view is now sorting posts by **creation time** by default. 

### Steps to reproduce the behaviour/error
In most cases post time equals creation time. However, not always.

The difference between creation date and post date is specially visible in deployments containing imported data. An example of this is https://mappingmediafreedom.ushahidi.io

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [x] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-474

**Comment by tuxpiper** [comment]
Flagging with "Client Request", since most probably the client paying for Mapping Media Freedom will ask what's going on with that sorting.

**Comment by Celestine22** [comment]
@tuxpiper thanks for flagging this, are you writing a script to update this sorting.

**Comment by tuxpiper** [comment]
@Celestine22  yes, I can update the timestamps in the database, but I'm not doing it yet. Waiting for @justinscherer and @jshorland to acknowledge they have seen this issue.

**Comment by Celestine22** [comment]
okay! Assigned them just to get an ack!

**Comment by jshorland** [comment]
@rjmackay I don’t remember this being intentional at all. What changed and why?

**Comment by rjmackay** [comment]
@jshorland somewhere during the Uchaguzi/data view build - probably when moving the sorting options in the filters dropdown - the default sort field has been changed from `post_date` to `created date`. I think it should change back to `post_date`. We will however have to double check that doesn't effect the behaviour of the 'X new posts' bar...

**Comment by jshorland** [comment]
ahhh this makes sense now. I believe the reason it was changed was the new "new post" alert. We have to do it by CREATION instead of POST because people need to be alerted of new messages as soon as they come in, not as soon as they are turned into a post

**Comment by tuxpiper** [comment]
I was sure there was a good reason for it :)

This may only be relevant to scenarios where we are bulk importing old data, and as such I think it should be contemplated what "post creation time" means in that context.

**Comment by justinscherer** [comment]
> ahhh this makes sense now. I believe the reason it was changed was the new "new post" alert. We have to do it by CREATION instead of POST because people need to be alerted of new messages as soon as they come in, not as soon as they are turned into a post

+1

**Comment by rjmackay** [comment]
I think its probably correct that the `created` timestamp is used to get things in the right order when new posts come in.

However just for clarity: Post_date has nothing to do with when a message is turned in to a post. Rather it defaults to same as the created time. The only instances where post_date is different is when someone edits it manually.
