### ISSUE TITLE
Export Graphs from Activity View

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#2330]
### Desire
As a user, I need to show my boss basic "analysis." I find the various graphs in activity view useful, but I need to put them in other support materials such as PowerPoint slide or download the data in such a way that I can quickly get the same graph in Excel and then tinker with it. 

I want to right-click on the graph and have the ability to export it as a JPEG or PDF. I also want the option to export a .csv of the filtered data that will give me the same graph in Excel, because when I download the whole .csv I'm not quite good enough with Excel to recreate the graph I'm viewing.

A more advanced user may want to embed the graphs on a web page.

### Actual behaviour
I right-click on the graph and do not get any of those options. 

##### Screenshot
<img width="1084" alt="uchaguzi activity view graph" src="https://user-images.githubusercontent.com/4574998/33476083-b28a144e-d691-11e7-9eaf-5b08a892a783.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-473

**Comment by CeciliaHinga** [comment]
@Angamanga @tuxpiper more with the activity view data
