### ISSUE TITLE
Plan setting is COMPLETELY gone from .io deployments

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2331]
### Expected behaviour
"plan" should be listed as a menu item under Settings. it should take you to the plans page where you can update your plan settings (card details, plan type, etc). 

### Actual behaviour
it's not listed in the menu. 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment]
I suspect this is because we didn't have it in the uchaguzi deployment?

**Comment by rowasc** [comment]
Ups, forgot to close this. DONE and released.
