### ISSUE TITLE
Styling of category-list in mobile is off

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2333]
### Expected behaviour
- on small screens checkboxes and text are aligned within each category-field in the category-list

### Actual behaviour
![screen shot 2017-12-01 at 14 55 51](https://user-images.githubusercontent.com/8624777/33485736-cbe38d60-d6a7-11e7-8248-e044563e4d51.png)

### Steps to reproduce the behaviour/error
- go to settings/categories on a small screen
- look at the styling

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by caharding** [comment]
@justinscherer confirm this will be fixed in UI cleanup so I can close

**Comment by justinscherer** [comment]
confirmed.
