### ISSUE TITLE
WebHooks migration - working fine in MySQL 5.5 but not in 5.7

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2334]
### Expected behaviour
Webhooks table has updated and created field as NULL with default 0, as defined in the migration CreateWebhookTable 
created    int(11)    NO        0    
updated    int(11)    NO        0    

### Actual behaviour
Webhooks table has updated and created field as NOT NULL. 

  `created` int(11) NOT NULL DEFAULT '0',
  `updated` int(11) NOT NULL DEFAULT '0',
##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [] Other (explain):

**Comment by rowasc** [comment]
@tuxpiper

**Comment by tuxpiper** [comment]
@rowasc apparently, it was simple typo, added an additional migration to correct
