### ISSUE TITLE
Dashboard enhancement: "refresh button"

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2336]
Data is not real time on the multiple deployments dashboard. We need to show users how up-to-date the data is, and give them a CTA to refresh the data. 

Unclear whether there should be individual refresh for each deployment or one for the whole view. I'll work on the design when this is back up in the queue. 

@jshorland if you could give me a rough deadline (assuming we want to build the feature), it would be helpful.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-472

**Comment by jshorland** [comment]
yes, we should do this. Rough deadline = Jan 12 (before we get to team meeting)
