### ISSUE TITLE
Reset password link in email leads to 404 error "whoops that doesn't exist"

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2337]
### Expected behaviour
Clicking on the reset password button in the reset password email should lead me to the reset password flow. 

### Actual behaviour
I go through reset password, enter my email, check my email for the reset password email from ushahidi, click on the link in the email, and it gives me a 404 error. 

### Steps to reproduce the behaviour/error
1. while not logged into a deployment to which you have a user account, click login, and click forgot password. 
2. enter your email. 
3. check your email inbox for the reset password email. 
4. click on the reset password button within the email. 
5. See 404 error
![screen capture on 2017-12-04 at 11-52-36](https://user-images.githubusercontent.com/3224856/33544087-6fb6a244-d8ea-11e7-9451-29887c93bba9.gif)

@tuxpiper i'm told you might know how to fix this very quickly?

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x ] Ushahidi.io / SaaS solution (crisisdemo.ushahidi.io)
- [ x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by tuxpiper** [comment]
The error seems to be in client URL routing. Any /forgotpassword/confirm/xyz URL is considered not found . @Angamanga can you help?

**Comment by tuxpiper** [comment]
The fix @Angamanga pushed has been deployed to ushahidi.io and it is working well for me. Thank you!

**Comment by jshorland** [comment]
Boom. Thanks, y'all!

**Comment by jshorland** [comment]
Fixed. Closing.
