### ISSUE TITLE
Edit survey view: title field doesn't look like an input field

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2339]
## Problem
During user tests, user jump straight to the description field on the survey edit page instead of the title field because the title field doesn't look like a normal input field. 

## Solution

We should change the styling to match the other fields in this view.

<img width="1329" alt="screen shot 2017-12-05 at 11 31 53 am" src="https://user-images.githubusercontent.com/29209303/33597285-f36115a0-d9af-11e7-870f-df96084f8213.png">

## Notes 
To fix this, you need to use the https://github.com/ushahidi/platform-client repo. This field lives in the survey-editor.html file (description field)

**Comment by justinscherer** [comment]
@jrtricafort @caharding this will get handled in the [UI refresh.](https://app.zenhub.com/workspace/o/ushahidi/platform-pattern-library/issues/205)

**Comment by m-sameer** [comment]
Please review my [PR](https://github.com/ushahidi/platform-client/pull/1284). :smile:
