### ISSUE TITLE
When refreshing any page in /settings, it takes you back to map

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2340]
### Expected behaviour
When i refresh any page i'm in in settings, it should keep me on that particular page, but refreshed.

### Actual behaviour
Any page including /settings i refresh on, it takes me back to map

### Steps to reproduce the behaviour/error
1. login to a deployment as admin
2. navigate to /settings (or any of the pages within settings)
3. refresh the page
4. see it navigate you back to map

This does not happen on /data or /activity

This is a p1 because to get around the logout issue, you'll be working on a long survey and you need to save the survey periodically so you don't lose your work in what seems like a random logout. After clicking "save" on the survey edit page, it takes you to the survey list, but the new survey you've created isn't actually there. You have to refresh before it appears. but when I refresh, it takes me to map. 

See gif. 
https://d.pr/i/NplIzv (it was too big to upload)

- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by crcommons** [comment]
Somehow this was fixed in the last cycle unintentionally.
