### ISSUE TITLE
User can add a Survey field with no Label set

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2341]
### Expected behaviour
- I shouldn't be able to click Add&Close when editing a Survey field if there is no label set
### Actual behaviour
- I am able to edit a field then click Add&Close when the label is blank

### Steps to reproduce the behaviour/error
- [ ] Got to Settings->Surveys
- [ ] Add or Edit a Survey
- [ ] Add or Edit a field
- [ ] Delete or do not set the Name
- [ ] Click Add & Close
- [ ] User is not warned that they must set a Name

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [x] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-471

**Comment by caharding** [comment]
Fix: add Name* validation requirement when creating a new Field

**Comment by rowasc** [comment]
Fixed / not happening naymore
