### ISSUE TITLE
On Survey Field Edit Add&Close should be Update&Close

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2342]
### Expected behaviour
- I should see the correct naming on buttons and modal titles when editing a Survey field
- When editing a Survey field it should read Update & Close
### Actual behaviour
- When editing a Survey field it says Add & Close for both button and modal title text
### Steps to reproduce the behaviour/error
- [ ] Go to Settings -> Surveys
- [ ] Edit or create a Survey
- [ ] Edit or Create then Edit a Survey field
- [ ] Title and Button text is Add field and Add & Close, respectively, when it should be Update Field and Update & Close, respectively.

<img width="521" alt="screen shot 2017-12-05 at 14 41 34" src="https://user-images.githubusercontent.com/2694405/33605407-aa4febaa-d9ca-11e7-8a13-ea2bf0447f04.png">

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [x] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain):

**Comment by komalsdg** [comment]
@Angamanga I am outreachy applicant. I would like to work on this issue.

**Comment by Angamanga** [comment]
@komalsdg Go ahead 🎉 And please reach out if you need guidance or wonder about something!

**Comment by komalsdg** [comment]
Thank you. For sure.

**Comment by thirunjuguna** [comment]
@komalsdg  what's the status of this issue,can I take over ?

**Comment by komalsdg** [comment]
@thirunjuguna u can take over. I was not able to do it due to time constraint. Thank You.

**Comment by rowasc** [comment]
This works as expected. Closing 🎉  thank you 
<img width="559" alt="Screen Shot 2019-06-10 at 23 42 37" src="https://user-images.githubusercontent.com/2434401/59239869-73e40c00-8bd9-11e9-9889-2cb62dae6f33.png">
