### ISSUE TITLE
Filter pane does not scroll to the top when it is closed and re-opened

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2347]
### Expected behaviour
Open filter pane, scroll, apply a filter. filter pane closes, re-open filter pane, filterpane is scrolled to the top. 
### Actual behaviour
Open filter pane, scroll, apply a filter. filter pane closes, re-open filter pane, filterpane is NOT scrolled to the top. It is at the same scroll location as it was when I applied the filters and closed the filter pane.
### Steps to reproduce the behaviour/error
Open filter pane, scroll, apply a filter. filter pane closes, re-open filter pane

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-468

**Comment by rowasc** [comment]
Demo of current behavior for reference. 
![Jun-10-2019 23-50-53fp](https://user-images.githubusercontent.com/2434401/59240385-a2aeb200-8bda-11e9-8669-2febe31260ea.gif)

**Comment by Erioldoesdesign** [comment]
I actually don't think this is bad in the circumstance that: You haven't navigated to another 'thing' clicked a post in the map/data list, shared data etc.

The filter panel *should* reset to the top *if* you 'complete' your action but *not* if you almost immediately reopen it.

So, the 'back to top' functionality should be based on time not in filter panel and 'has something else been interacted with'

/my two cents

**Comment by vanessa-ariel** [comment]
Hi @Angamanga, can I be assigned to this issue?

**Comment by rowasc** [comment]
hey @vanessa-ariel I assigned #1029 instead. Thanks

**Comment by Angamanga** [comment]
@Dev-Som check out this issue instead!

**Comment by Dev-Som** [comment]
@Angamanga Thanks, I'll start working on it.

**Comment by rowasc** [comment]
@Dev-Som assigned! Thanks
