### ISSUE TITLE
I don't think downgrading plans in the deployment is actually working?

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2349]
@rjmackay is it possible for you to help me test if this is an actual issue? i don't want to wait a month to try and test it myself (see if recharges me)

If this actually exists, it's a serious p0 that's causing angry angry people to yell at us in intercom.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rjmackay** [comment]
@jshorland what have you done to test this so far?

**Comment by rjmackay** [comment]
So many issues...
1. Created a new deployment
2. Paid for surveyor during sign up
!! Deployment wasn't built for a while... stuck waiting for data providers to run
3. Log in
4. Go to plans
!! Shows my plan as 'free'
5. Manually force a 'configure' to get the correct tier.
6. Go to plans again
7. Pick 'Mapper'
8. Enter password
9. "Your all set"
10. Check chargebee and it appears to have downgraded just fine.

**Comment by jshorland** [comment]
huh. Ok. I'm going to close this for now. seems to be working :-/
