### ISSUE TITLE
Data Source Integration with Frontline SMS - Enterprise Client

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#2350]
### Expected behaviour
Our Enterprise client #proejctXenowatch needs to use Frontline SMS as a data source for this deployment : https://xenowatch.ushahidi.io/views/map
To make all this happen, this is the current progress;
- They have opened an account with Clickatel that will give them a short code toll free number.

- They have opened a frontline SMS account so that messages from Clickatel can pipe through Frontline SMS.

We now need a way to channel messages from Frontline SMS to the platform, and work with the client to achieve this. What are the next steps needs/requirements needed to achieve this?

**Comment by Angamanga** [comment]
@Celestine22 We need to set up frontlineSMS as a datasource in the settings ( settings->datasources->frontlineSMS in their deployment ). Do you know if they have followed the instructions here: https://www.ushahidi.com/support/data-sources#frontlinesms to get the api-key from frontlineSMS?

**Comment by Celestine22** [comment]
We need a dev to follow these instructions to integrate with platform, I have their account dets and can DM you, will that help?

**Comment by Angamanga** [comment]
@Celestine22 I can try :)

**Comment by Celestine22** [comment]
ok DM'ing you :)

**Comment by Angamanga** [comment]
@Celestine22 the integration is set up now, there seem to be a delay to get the sms-messages to Clickatell but once there they gets forwarded to the deployment!
