### ISSUE TITLE
Organization Deployments - Stats API

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2353]
## API - request for sparkline chart
Requires authorization    

    GET {subdomain.domain}/api/v3/posts/stats?group_by=&timeline=1&timeline_attribute=created&created_after=2017-12-01T03:00:00.000Z

Query values detail: 

- group_by: send empty to get posts without any grouping (some options available are "tags", "status")
- timeline: `1` (group by date, for the timeline charts) 
- timeline_attribute: `created` (post create date will be used to group) 
- created_after: send today's date -30 days for the sparkline's "last 30 days" requirement. Format UTC string

### API Response

`
  {
    "totals": [
        {
            "key": "all",
            "values": [
                {
                    "label": 1354579200,
                    "total": 1,
                    "cumulative_total": 1
                },
                {
                    "label": 1355702400,
                    "total": 1,
                    "cumulative_total": 2
                },
                {
                    "label": 1362700800,
                    "total": 1,
                    "cumulative_total": 3
                },
                {
                    "label": 1363996800,
                    "total": 1,
                    "cumulative_total": 4
                },
                {
                    "label": 1372982400,
                    "total": 1,
                    "cumulative_total": 5
                },
                {
                    "label": 1373760000,
                    "total": 1,
                    "cumulative_total": 6
                },
                {
                    "label": 1377993600,
                    "total": 1,
                    "cumulative_total": 7
                },
                {
                    "label": 1384732800,
                    "total": 1,
                    "cumulative_total": 8
                },
                {
                    "label": 1403136000,
                    "total": 1,
                    "cumulative_total": 9
                },
                {
                    "label": 1411862400,
                    "total": 1,
                    "cumulative_total": 10
                },
                {
                    "label": 1411948800,
                    "total": 8,
                    "cumulative_total": 18
                }
            ]
        }
    ],
    "group_by": "",
    "group_by_attribute_key": null,
    "timeline_attribute": "created",
    "time_interval": 86400
}
`

## API - request for reports total - grouped by status

    GET /api/v3/posts/stats?group_by=status&created_after=2017-1-01T03:00:00.000Z

Query string values: 
- group_by: status. Sending "status" will make the API return an array of stats per status. 
- created_after: send today's date -30 days for the "last 30 days" requirement. Format UTC string

### API Response
`  
{
    "totals": [
        {
            "key": "status",
            "values": [
                {
                    "label": "published",
                    "total": 18,
                    "id": null,
                    "type": "web"
                },
                {
                    "label": "draft",
                    "total": 4,
                    "id": null,
                    "type": "web"
                }
            ]
        }
    ],
    "group_by": "status",
    "group_by_attribute_key": null,
    "timeline_attribute": null
}
`

## Notes: 
- This API should live in platform-api but depends on platform-cloud-interface to provide deployment and organizations data before it is used. 
- High-level diagram of the steps to get stats (does not include Authentication and Authorization)
![stats-api.png](https://zube.io/files/ushahidi/d1cc1fc1035077e0aff6eb6444aafec4.png)

**Comment by rjmackay** [comment]
You could already do something like

`GET {subdomain.domain}/api/v3/posts/stats?created_after=timestamp&group_by=status&timeline=1&timeline_attribute=created`

I think that should give the right info, though possibly with some gaps because of the way it pulls the data, but we use this to generate line charts on the activity view

**Comment by rowasc** [comment]
@rjmackay thanks Robbie. 
Just checked, and with that query + adding "day_total" to the formatter, that  would help create the line chart with minimal effort from the backend, I think . There's also the option of not grouping :tada: 
I will do some tests  and leave it documented here so we can do the charts easily, but it's looking good and simple . Thanks!

**Comment by rowasc** [comment]
@kinstelli I'll move this to in-review and send to you  while you check that this would work for the sparkline and stats. It seems to have everything it needs but maybe you find some issues and want to adjust it . LMK!
