### ISSUE TITLE
Organization Deployments - Getting Access Tokens for deployments

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2354]
### Repo

https://github.com/ushahidi/platform-dashboard
https://github.com/ushahidi/platform
https://github.com/ushahidi/platform-client

## Notes

- for the v1 of the dashboard, we will require that all deployments created for an organization (grouped in the new organizations' dashboard feature) share an OrgAdmin user that will exist in the dashboard database and the platform database for each deployment. This is going to be a requirement until the proper auth is designed and developed. It will be enforced programmatically and through the user flows 

- When the user logs in, we fetch all their deployment access tokens and save them to local storage​ so we can fetch data from the deployment's API
- This assumes we can do parallel requests like we did for maps experiments, and that the page would continue rendering and getting other data as the tokens come in
### Initial auth flow

![authdeployments.png](https://zube.io/files/ushahidi/2a2c843c3ab65a062d9f5849dae5cafc.png)

**Comment by rowasc** [comment]
Copying from meatlof doc. 
@kinstelli @rjmackay 
@justinscherer @jshorland 
We have been talking about authentication a lot this last week and one of the things we need to make sure of is that the user cannot change the password of his org admin in the deployment, and that the org admin needs a user IN the deployment with the exact credentials (so when we create a deployment to an org, we will need to have the same user added to each deployment). 
A couple things that came up: 
- need to prevent org admins from changing their password in a deployment, because then it would not refresh in the other deployments or the organization dashboard itself. We think a way to solve this would be to like to the org admin password change screen from the deployment, when we detect it's an org admin the one trying to change the password
- need to figure this out for mobile, too. So probably in the mobile app the same flow would apply
- need to figure apply the same logic to reset password in deployments, for organization admins (meaning they should be taken to a different screen in the dashboard and not the deployment reset password screen). 

This would all be for the initial version, and this requirement of sharing user credentials for that user in dashboard + each deployment would go away when we figure out a better authentication and authorization mechanism, but we don't want to delay the release of this or do a terrible job at a new authentication mechanism so this is (so far) the idea most likely to work out for the initial prototype. 

Thoughts? Concerns? ideas? Also, I can call you and we can discuss this in more detail whenever you have some time.

**Comment by rowasc** [comment]
@justinscherer @jshorland also, it's probably way more easy to get on a call for this because it's a bunch of technical stuff .

**Comment by kinstelli** [comment]
3936 basically includes the solution for ushahidi/platform-cloud-interface#192, which was quietly hiding at the bottom of the sprint board.
