### ISSUE TITLE
Improve Data List When Empty

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#2355]
An empty data list like in https://xenowatch.ushahidi.io/views/data is really quite barren and unappealing.

![screenshot 2017-12-12 11 01 41_preview](https://user-images.githubusercontent.com/91811/33899194-5f6b4452-df30-11e7-9272-3cf4362400ac.png)

Even increasing the font size, text color and padding of the message would help a lot.

<img width="360" alt="screenshot_2017-12-12_11 21 36_720" src="https://user-images.githubusercontent.com/91811/33899259-8f402364-df30-11e7-9f6f-02b2726df04f.png">

**Comment by dalezak** [comment]
The message `0 of 0 reports` should probably be hidden when there are no items?

**Comment by caharding** [comment]
@middle8media is it possible to make a quick fix on this without new logic required by another dev?

**Comment by middle8media** [comment]
@caharding I can change the styling but the `0 for 0 reports` will need to be hidden programmatically by the devs. Will do this asap.

**Comment by middle8media** [comment]
fixed via above commit in `develop`
