### ISSUE TITLE
Selected Card In Data View Does Not Display The Survey Color

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#2356]
### Expected behaviour
The selected card in the data view, should display the correct survey color on the left side of the card.

### Actual behaviour
The selected card always just shows the default grey color instead.

### Expected behaviour
![screenshot 2017-12-12 12 31 17_preview](https://user-images.githubusercontent.com/91811/33902328-4ca57630-df3a-11e7-9671-8f6cd36b846a.png)

### Steps to reproduce the behaviour/error

- Set the color in your survey settings 
    - Settings 
    - Survey 
    - select your survey 
    - click the `Configure` tab and scroll to the bottom. You will see a color picker that you can change <img width="955" alt="Screen Shot 2019-11-15 at 15 53 25" src="https://user-images.githubusercontent.com/2434401/68967999-415dc100-07c0-11ea-8e9b-c18ab1d3e751.png">
    - go to the data view. (If there are no posts for that survey, create one. )
    - See the lists of posts. You will see the color you selected on the selected card border in the list.
    - Click the card/post. You will see the post details. The color in the detail view will be grey instead of your selected color

Example: 
<img width="1400" alt="Screen Shot 2019-11-15 at 15 52 28" src="https://user-images.githubusercontent.com/2434401/68968009-4ae72900-07c0-11ea-9d70-c9e1d645b31a.png">

### Tips for solving
Change backgroundColor to background-color in the post-detail-data.html file where we use the post-band

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [X] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-467

**Comment by komalsdg** [comment]
Hi, @dalezak I am an outreachy applicant and would like to work on this issue.

**Comment by NidhiKJha** [comment]
Cannot reproduce. The cards don't show any colors in the current code.

**Comment by Angamanga** [comment]
@Obadha2 Can you QA in Steve Buscemi please? 
Testing checklist:
- [ ] Make sure your surveys is configured with colors (go to settings->survey->select survey->configure)
- [ ] Add a post to a survey with colors
- [ ] Go to dataview
- [ ] Select the post
- [ ] the selected post on the right hand view should have the correct color-band for that post
- [ ] select another post from another survey
- [ ] the selected post on the right hand view should have the correct color-band for that post

**Comment by Obadha2** [comment]
QA'd, passes. 👍
