### ISSUE TITLE
Improve The Blank Right Side of Data List View

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#2357]
Since the data list view does not pre-select the latest card, the whole right section of the page is completely blank.

<img width="512" alt="screenshot_2017-12-12_10 33 18_1024" src="https://user-images.githubusercontent.com/91811/33902831-e7392664-df3b-11e7-9b68-d37c87c586ee.png">

Either pre-selecting the latest card or even displaying some kind of statistics would be a lot better than having all that empty space.

<img width="512" alt="screenshot_2017-12-12_10 51 20_1024" src="https://user-images.githubusercontent.com/91811/33902834-ea9843e4-df3b-11e7-9f1f-27748106ff7e.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-466

**Comment by caharding** [comment]
@justinscherer as you designed this mode do you think we should make any changes?

**Comment by justinscherer** [comment]
> "do you think we should make any changes?"
No question it could be improved. Not sure how high priority it is at the moment, to be honest. @Erioldoesdesign What do you think about a light, nice illustration for the background.

**Comment by caharding** [comment]
I think this would probably be better addressed in the UI/UX design debt for Cycle 5
