### ISSUE TITLE
COMRADES deployment is down

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#2358]
## Expected behaviour
Go to [https://comrades-stg.ushahidi.com](https://comrades-stg.ushahidi.com) and see my deployment. 
### Actual behaviour
When entering the URL, I am first presented with a message that warns me my connection is not secure (see screenshot below).
<img width="986" alt="comrades error msg" src="https://user-images.githubusercontent.com/4574998/33906411-15d84b3c-df3f-11e7-9ed5-fc67033f851a.png">
If I choose to proceed, I then get the error page with a red bar in the upper left corner which reads, "Sorry, something went wrong. Try reloading the page."

I have tested this on Chrome, Firefox, and Safari with the same results. 
### Steps to reproduce the behaviour/error
Visit: [https://comrades-stg.ushahidi.com/](https://comrades-stg.ushahidi.com. )

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [X] Other (explain): COMRADES repo.

**Comment by jshorland** [comment]
@rjmackay ??

**Comment by tuxpiper** [comment]
Unfortunately, the ansible letsencrypt module doesn't take care of setting up automatic renewals.

It's already captured in https://github.com/ushahidi/engineering/issues/120

**Comment by jshorland** [comment]
Is comrades back up? if so, i'd recommend closing this.

**Comment by Shadrock** [comment]
COMRADES is back up and it looks like the auto-renewal issue is already captured elsewhere. I'm happy to close this.
