### ISSUE TITLE
Data sources should be able to save emoji

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2362]
### Expected behaviour
When I receive an emoji messages they should be saved successfully

### Actual behaviour
Emoji messages cause an SQL error
`Incorrect string value: '\xF0\x9F\x91\x8D' for column 'content' at row 1 [ INSERT INTO `posts` (`slug`, `content`, `created`, `post_date`) VALUES ('-5a308545b542c', '👍', 1513129285, '2017-12-13 01:41:25') ]`

### Steps to reproduce the behaviour/error
- Set up SMSSync
- Send yourself an emoji message
- Sync it to platform

Aha! Link: https://ushahiditeam.aha.io/features/PROD-464

**Comment by ptandler** [comment]
You even don't need to use SMS, just open Ushahidi on your mobile (or PC with Emoji input) and type an emoji into an text field and submit.

Should actually not be too hard to tell the DB to store UTF8 strings ... one might think ... :smirk: 
I might have a look into this in case I'll have some free time.
