### ISSUE TITLE
Responder plans are not permitting more than 2 admin users

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2363]
### Expected behaviour
On the responder plan, I should have up to 25 admin users per our plans page. 

### Actual behaviour
I currently have 2 admin accounts, and when I try to upgrade any other user to an admin, I get an error message that says I've reached the max for my plan and I need to upgrade.

I then created a new user role that had all permissions (same as admin) and was able to upgrade accounts to THAT user role, but not the out of the box admin role.

### Steps to reproduce the behaviour/error
1. login to a responder plan on .io
2. Try to create more than 2 admin users

![screen capture on 2017-12-13 at 06-16-34](https://user-images.githubusercontent.com/3224856/33943268-7c20e168-dfcd-11e7-8a56-063fcae130ee.gif)

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rjmackay** [comment]
@willdoran what was the root cause? ie. is there a longer term fix needed?
