### ISSUE TITLE
Data model diagram

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2369]
@rjmackay asked me to create a diagram of our data model as I see it now to discuss at the retreat.

![diagram](https://user-images.githubusercontent.com/29209303/34419109-3fe617d8-ebbf-11e7-96ad-b4386da0e34e.png)

Also in PDF form:
[diagram.pdf](https://github.com/ushahidi/platform/files/1591799/diagram.pdf)

I tried to represent all the things data can "be" in the platform and how they relate to each-other. 
Square things are user-configurable. Circular things are not. 

Please let me know if I've forgotten or misconstrued anything. 

may be of interest to @kinstelli @jshorland @willdoran @aoduor

**Comment by rjmackay** [comment]
@justinscherer I'm struggling to understand the diagram a little
What are all the extra dots under 'report data' in the report circle? Is that showing the multiple fields of a report (some configure and some not?)

The list of statuses seems a little muddled. In the backend we have status:published/unpublished/archived, lock:locked/unlocked, and structured/unstructured. I guess though for a user they're easily confused - which is sorta the point.

**Comment by justinscherer** [comment]
>  Is that showing the multiple fields of a report (some configure and some not?)

Yep, exactly. 

> The list of statuses seems a little muddled.

Yeah, the main point I wanted to make by visualizing it that way was to show that there are a bunch of statuses, some of which cane be changed when something is unstructured, but that can't be changed as easily once something is structured and published. Others are programatically changed, or static.

**Comment by willdoran** [comment]
Looking at this image, I feel my eyesight has become more blurred than it was before.

**Comment by justinscherer** [comment]
> Looking at this image, I feel my eyesight has become more blurred than it was before.

Imagine how our users feel... lol

**Comment by rowasc** [comment]
tagging you for awareness that this exists in case either of you feel this should go into the new gitbooks  or some other asset @Erioldoesdesign  @Angamanga 
This was a retreat activity so I'm closing the issue.

**Comment by Erioldoesdesign** [comment]
pretty sure we did another version of this for the first part of the DIAL grant for documentation...also I don't really 'get' Justin's diagram. It's too pretty.
