### ISSUE TITLE
Dashboard UI Bugs / design debt

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2370]
### Expected behaviour
- [ ] Corner radiuses on cards are wrong/missing, should be 2px 
- [ ] drop shadows on cards are wrong, should follow PL
- [ ] spark line has wrong styling. Should be #444444  and 2px with rounded back end and an open circle with the same stroke styling on the front end. 
- [ ] chevrons should be to the right of card title, not the left
- [ ] there is 10px or so of blank white space at the bottom of some card for some reason, shouldn't be there. 
- [ ] In cases where there is only one day of data. That day should be a spike and all other days should be a "flat line" at the bottom of the sparkgraph
- [ ] double check the vertical spacing in the section of the card
- [ ] small squares in the data legend should be 6px x 6px with 2px corner radiuses. 
- [ ] the bar graph looks awful at 100%. If the data for the bar graph is 100% for any of the three categories, remove the bar graph completely and just leave the legend. 
- [ ] we need to work on the page's loading states, use the standard three dancing dots loader in the middle of the page for now. 
- [ ] We really need to validate that those spark lines are actually telling us anything. My hunch is that they are, unfortunately, not telling us jack...
- [ ] bar graph should have 2px corner radiuses.

**Comment by kinstelli** [comment]
I split some of the component specific issues into separate cards.
Sparkline stuff is here: https://zube.io/ushahidi/platform/c/4039
Bar chart stuff is here: https://zube.io/ushahidi/platform/c/4040

**Comment by crcommons** [comment]
Archiving this card since we split these up into different issues
