### ISSUE TITLE
Enhance on-state for active cards

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2371]
When a card becomes active on a low-resolution monitor, it can be difficult to tell which card is active. 

Enhance the selected state with a visual cue of some kind. 

Design TBD

**Comment by rowasc** [comment]
I believe this is what we do already by moving the card and having the space different right? Not sure if this is deprecated or if we still need to act on it 🤔 
<img width="419" alt="Screen Shot 2019-06-11 at 00 00 04" src="https://user-images.githubusercontent.com/2434401/59240905-f40b7100-8bdb-11e9-9334-0a7091f55d07.png">
Image only to show the indentation when there's a selected post card.

**Comment by Erioldoesdesign** [comment]
This is actually covered in one of the platform UI refresh tickets...lemme find it... aha! https://app.zenhub.com/workspaces/platform-combined-565f65d4bd1f5c92203300e8/issues/ushahidi/platform/2641

**Comment by Erioldoesdesign** [comment]
closing~~~~
