### ISSUE TITLE
Do not hide surveys, categories behind a "more" dropdown

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2372]
More dropdown isn't terribly accessible because it's small and is kinda styled like a drop down. It's easy to miss, and this was validated in user testing. Automatically expand and show all surveys and categories. Remove the "More" functionality completely. 
<img width="1622" alt="screen shot 2018-01-02 at 3 33 46 pm" src="https://user-images.githubusercontent.com/29209303/34502821-8e619d6c-efd2-11e7-8384-dcd997b91117.png">
<img width="261" alt="screen shot 2018-01-02 at 3 33 39 pm" src="https://user-images.githubusercontent.com/29209303/34502822-9001af22-efd2-11e7-8497-27802bc18703.png">

**Comment by rowasc** [comment]
@Erioldoesdesign I did this and I'm sending a PR since it was a 2min fix, checking with you in case you don't want this change and want me to throw it away instead of merging it (either is fine :) ) or If you want some change for it
Gif showing the change here
![no-overlflow](https://user-images.githubusercontent.com/2434401/59153486-c504cc00-8a30-11e9-9221-289261c67272.gif)

**Comment by Erioldoesdesign** [comment]
@rowasc this is awesome! the more buttons were quite awful!

The only problem I can foresee is for deployments like Uchaguzi with a huge amount of filter options this will be a mega scroll...but there's a better way of handling that that is not more buttons hiding options and more like an intelligent search/filter type-able field like what was described in another issue.

**Comment by Erioldoesdesign** [comment]
Closing~~~

**Comment by rowasc** [comment]
@Obadha2 please verify this in Steve-buscemi when you are back ? Thanks 🎉

**Comment by Obadha2** [comment]
@rowasc The more button is still present in steve-buscemi under Status, Categories and Surveys.

**Comment by rowasc** [comment]
sorry @Obadha2 I misclicked 😬 can you try again in the morning?

**Comment by rowasc** [comment]
Passed :) No `more` button present
