### ISSUE TITLE
"Clear filters" should say "Restore Defaults"

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2373]
## Description:
The clear filters button doesn't actually clear filter in the filter pane, it restores the defaults. 

<img width="660" alt="screen shot 2018-10-05 at 6 28 58 pm" src="https://user-images.githubusercontent.com/2434401/46561108-8f6d7900-c8cc-11e8-970b-9e03411c1971.png">

## Current Behavior
It says "Clear filters"

## Current Behavior
It should say "Restore Defaults"

Notes :
We can assess later if we need a true "clear all" function.

**Comment by gowrimanoharir** [comment]
Hi, I would like to pick this up.

**Comment by siddhishree** [comment]
Hello, I would like to work on this issue.

**Comment by SolKuczala** [comment]
@justinscherer where is that error? on which URL?

**Comment by karunagoyalk** [comment]
@justinscherer I have looked into it! Can I work on this?
