### ISSUE TITLE
Filter actions bar should be opaque

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2374]
## Context
It's hard to read the buttons when there's text behind them. 
opacity should be 100%
## current behaviour

<img width="977" alt="screen shot 2018-01-02 at 3 41 27 pm" src="https://user-images.githubusercontent.com/29209303/34503007-8507bf84-efd3-11e7-86ef-3a69b84e3d68.png">

## implementation
- This needs to be fixed in the pattern library (https://github.com/ushahidi/platform-pattern-library/) 

- CSS Path:
```
#bootstrap-app > ui-view > ui-view > div > main > post-toolbar > div > form > filters-dropdown > div.form-field.filter-actions 
```

Aha! Link: https://ushahiditeam.aha.io/features/PROD-463

**Comment by caharding** [comment]
@justinscherer are you OK fixing this in the JS Framework update instead of now?

**Comment by rowasc** [comment]
@Obadha2 this needs QA (in steve)
Thanks!

**Comment by Obadha2** [comment]
QA'd, passes. 👍
