### ISSUE TITLE
Platform should be more "connection resilient"

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2375]
Right now, if a connection drops in the middle of config or some other task, the platform throws a weird error and the user needs to refresh and re-log-in to continue. 

We can do better. New designs TBD.

**Comment by rowasc** [comment]
https://github.com/ushahidi/platform/issues/3556 
Related. 

@Erioldoesdesign was there a design for this already? If not, should we close in favor of https://github.com/ushahidi/platform/issues/389 and https://github.com/ushahidi/platform/issues/3556
? 
thanks 🙌

**Comment by Erioldoesdesign** [comment]
Yep - close in favour of more detailed tickets listed 🙌

**Comment by Erioldoesdesign** [comment]
Also no designs that I know of...
