### ISSUE TITLE
Title fields should look like the rest of the fields on a config form

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2378]
<img width="1676" alt="screen shot 2018-01-02 at 4 02 46 pm" src="https://user-images.githubusercontent.com/29209303/34503637-c8e6b4c8-efd6-11e7-8568-6b8b9e75bb06.png">

### Expected behaviour
The title field in the above image should look the same as the description field. 

### Actual behaviour
People can't tell that giant light grey bar is an input field. This has been validated in so, so many user tests.

**Comment by aoduor** [comment]
Hi @m-sameer - great stuff. Tagging @Erioldoesdesign and @Angamanga for help here.

**Comment by Angamanga** [comment]
Hi @m-sameer and welcome! Relevant code can be found here:  https://github.com/ushahidi/platform-client/blob/develop/app/settings/categories/categories-edit.html. Please let us know if you need any more directions!
