### ISSUE TITLE
Creating child categories is not usable

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2380]
### Expected behaviour
Child categories should be created and managed **within** the parent category.

### Actual behaviour
you have to create them separately and assign them to a parent, which users have had a hard time with. 
<img width="1670" alt="screen shot 2018-01-02 at 4 17 28 pm" src="https://user-images.githubusercontent.com/29209303/34503938-880f543a-efd8-11e7-8bb9-005c6db27e1b.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-460

**Comment by Erioldoesdesign** [comment]
In UT, the terminology 'child and parent' is jargon/tech speak too.
