### ISSUE TITLE
Our global navigation doesn't scale and isn't accessible

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2382]
### Actual behaviour
Currently, our global nav can only handle an "M" width of 5.5

<img width="1316" alt="screen shot 2018-01-02 at 4 24 31 pm" src="https://user-images.githubusercontent.com/29209303/34504115-96840758-efd9-11e7-8c59-885ffa45ff70.png">

This becomes particularly problematic in langauges like German

<img width="1069" alt="screen shot 2018-01-02 at 4 26 42 pm" src="https://user-images.githubusercontent.com/29209303/34504134-be339ca0-efd9-11e7-8136-46507e778774.png">

### Solution

We need a way to have our global navigation items :
- [ ] Labelled for screen readers and the intellectually impaired
- [ ] not dependent on iconography (There is not representative graphic interpretation of "collection" for example, so we use a weird grid of squares)
- [ ] capable of supporting labels with an M width of up to </arbitrary-number>

**Comment by ptandler** [comment]
For German I fixed the size of the mode-bar by introducing `$mode-bar-width: 85px;` in _settings.scss and replaced `$lg-spacing*2` and some occurrences of `64px` with this variable. Not a universal solution, but enough for now in our context :smirk:

If I've some spare time, I could extract these changes and create a PR - if you want.
