### ISSUE TITLE
Language selector is a dropdown hidden in a dropdown

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2383]
Another unnecessary click

### Expected behaviour
Instead of having a toggle to see/not see the language dropdown, we should just have a label "Language" without the function to hide it.

This is how it is now, which requires an extra click just to see a dropdown..
Off

<img width="289" alt="Screen Shot 2019-08-16 at 04 56 26" src="https://user-images.githubusercontent.com/2434401/63152513-69cbf880-bfe2-11e9-8480-88524ae10f3c.png">

On after click 
<img width="292" alt="Screen Shot 2019-08-16 at 04 56 31" src="https://user-images.githubusercontent.com/2434401/63152541-7cdec880-bfe2-11e9-8829-a2941d7d2d9b.png">

## Fixing this issue
This can be fixed in app/main/posts/views/mode-context-form-filter.html, in the last section of the file (Language). Leaving just the h6 that says Language and the <language-switch> in the last "tool" wrapper should fix this issue

## General implementation notes
- Fix in https://github.com/ushahidi/platform-client repo
- Hint :bulb: The code handling users can be found here: https://github.com/ushahidi/platform-client/tree/develop/app/main/posts/views/mode-context-form-filter.html
- When you are done, 🔀 Start a Pull Request. 
- 🏁 When done Ask in comments for a review :)

**Comment by rowasc** [comment]
@Angamanga should I remove the pattern library tag here or is it something that also needs changes in the PL that I'm not seeing?

**Comment by c3ho** [comment]
@Angamanga Is the following better? I removed the svg and the toggle, so only the dropdown is clickable now.
![image](https://user-images.githubusercontent.com/18711727/67452463-4b413980-f5f1-11e9-95ee-8f42a0397310.png)

**Comment by rowasc** [comment]
@allcontributors add c3ho for code

Thanks @c3ho ! 

@Obadha2 please review this in steve-buscemi tomorrow? 
Thanks!

**Comment by rowasc** [comment]
Noting that this worked as expected but we found a pre-existing issue that we should address soon. https://github.com/ushahidi/platform/issues/3799 just linking for reference of where it was found . 
Sending this to production in the next release.
