### ISSUE TITLE
Should have cancel when modifying saved searches

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2385]
### Expected behaviour
There should be a "cancel" button beside the "Update search" CTA in case a user accidentally deletes a bug. 
### Actual behaviour
<img width="1397" alt="screen shot 2018-01-02 at 4 37 26 pm" src="https://user-images.githubusercontent.com/29209303/34504350-625b980e-efdb-11e7-8d98-7a8dde426aec.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-456

**Comment by rowasc** [comment]
@Angamanga I'm closing this as saved searches have changed in how they are handled and it would introduce more complexity than we can cope with right now.
