### ISSUE TITLE
Export CSV from Data mode

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2389]
### Expected behaviour
We need a way to export CSV nicely from data mode. 
### Actual behaviour

<img width="1606" alt="screen shot 2018-01-02 at 4 50 18 pm" src="https://user-images.githubusercontent.com/29209303/34504686-53598ae4-efdd-11e7-9c8a-079d2c936005.png">

**Comment by jshorland** [comment]
Fixed and will be landed with cycle 0 release
