### ISSUE TITLE
Add support for hydrating related models in API responses

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2391]
- Add support a JSONAPI-style `?include` param in the API http://jsonapi.org/format/#fetching-includes
- API changes should be additive to avoid breaking older clients

**Comment by willdoran** [comment]
By additive do we mean versioned? Our API is going to be versioned right?

**Comment by rowasc** [comment]
Closing in favor of https://github.com/ushahidi/platform/issues/2392 and what'll come out of it
