### ISSUE TITLE
Global navigation on-state gets lost when navigating to a settings page. 

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2394]
### Expected behaviour
Global navigation item "Settings" should be highlighted in yellow when I go to the a settings page
### Actual behaviour
<img width="1680" alt="screen shot 2018-01-10 at 11 02 12 am" src="https://user-images.githubusercontent.com/29209303/34787833-ed0e2258-f5f5-11e7-89e3-d52186fe354d.png">

### Steps to reproduce the behaviour/error
- Click on any link in the settings-menu, see the settings-item turn grey.

### Hints on fixing this issue:
Hint 1 💡 : The navigation-items turn yellow when the active class is set to the element. The html for the mode-bar is here:
https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/mode-bar/mode-bar.html#L42

Hint 2 💡 : `ui-sref-active="active"` adds the class 'active' to the `<li>` element, but only for the route /settings. Not the subroutes like "/settings/surveys". 

Hint 3 💡 : `$state.includes('settings')` gives us the information we want instead, this could be combined with ng-class to add the class 'active'. Check for example here: https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/mode-bar/mode-bar.html#L1

Hint 4 💡 : $state needs to be injected to the directive and added to the $scope-variable in order to use it in the template:
https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/mode-bar/mode-bar.directive.js#L9
https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/mode-bar/mode-bar.directive.js#L18
https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/mode-bar/mode-bar.directive.js#L31

Aha! Link: https://ushahiditeam.aha.io/features/PROD-451

**Comment by whytejas** [comment]
@justinscherer  @rowasc Hi Romina, I'm an Outreachy applicant. 

I'd like to work on this as a contribution if it's still open. I assume it falls under the "Content disclaimer + work in platform" project#1 ?

**Comment by rowasc** [comment]
@whytejas hey. Thank you for reaching out. Yes you can work on this. Since content disclaimer will inevitably touch on settings work this is a good fit yea

**Comment by whytejas** [comment]
> @whytejas hey. Thank you for reaching out. Yes you can work on this. Since content disclaimer will inevitably touch on settings work this is a good fit yea

Thanks, I'm going to give this a shot!

**Comment by whytejas** [comment]
@justinscherer I'm new to Ushahidi , could you please help me reproduce this issue? 

To begin with, I've got the Platform API (Backend) and Platform Client (frontend) setup locally. I also  setup the Pattern Library for development since this looks like it might touch on the CSS. 

However, the local Platform client does not even have the mentioned "Settings" tab (and gear icon) in the sidebar.  Am I looking in the right place?

**Comment by renujain31** [comment]
Hey, I was checking for this issue but as said by @whytejas, I couldn't find the Settings tab in the sidebar. Does we need to have an admin role for that or something? Would like to solve this issue.

**Comment by Riju19** [comment]
Hi, I'm an outreachy applicant. I would like to work on this issue.

**Comment by Somaru-chan** [comment]
@Angamanga Hi Anna. Are there more issues for first-timers like this one? I'm an Outreachy applicant interested in contributing to this project, if possible.

**Comment by Angamanga** [comment]
@renujain31 Yes, you need to login as an admin to find the settings-link. In your local dev-environment both username and password is "admin".

**Comment by Angamanga** [comment]
@Riju19  and @Somaru-chan Please go ahead. @renujain31 I have assigned you to this issue: https://github.com/ushahidi/platform/issues/3994

**Comment by Somaru-chan** [comment]
@Angamanga Thanks. I'll start working on it right away.

**Comment by Somaru-chan** [comment]
@Angamanga I have made a PR for this issue. Waiting for your review whenever possible. Thanks!

**Comment by Angamanga** [comment]
@Somaru-chan Thank you! I will review shortly!

**Comment by tuxpiper** [comment]
@all-contributors please add @Somaru-chan for code
