### ISSUE TITLE
LDAP user account support?

### ISSUE THREAD

**Issue by poVoq** [ushahidi/platform#2395]
Any way to use a OpenLDAP directory for user accounts?

Maybe this would be an easy way to implement it if not yet available:
https://github.com/Adldap2/Adldap2-Kohana
?

Thanks!

Aha! Link: https://ushahiditeam.aha.io/features/PROD-450

**Comment by rowasc** [comment]
This is not a feature we have at the moment. Keeping it open to be considered in future iterations
