### ISSUE TITLE
Epic: Improved Data Export 

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2396]
### Summary
CSV export is a highly desired feature, but often does not work as the user expects, and does not offer the configurability that various types of users need for it to fulfill its value proposition. As a result of several user feedback sessions, bug reports, and numerous support tickets on intercom about CSV export, we discovered that we need to improve the feature to better serve users’ needs. 

[Epic spec](https://docs.google.com/document/d/1tWETG2_NuloqO5bS18b3yDxBRkQIzptSgUxMOjHkei4/edit#)
[Prototype](https://invis.io/RZFGBTBSC3W)
[Design rationale](https://docs.google.com/document/d/12uX615xKjL_kJCIJb2qBh-iF0DcQ7ZlfZldy5m4-pAY/edit#)
[Testing plan](https://docs.google.com/document/d/1i7otkXPs-Skxyl50NIvdwkUT6cLYCnURWRHCuL4o2Ss/edit?usp=sharing)
[Testing results(TBD)]()

**Comment by Shadrock** [comment]
Wondering to what degree this should connect with the API work that @willdoran and I will be doing for the HDX integration...  not sure if that's strictly required, but I thought I'd mention it.

**Comment by willdoran** [comment]
Yes, that is true. 

This is intended to be built, I believe, in a way that is agnostic to a degree of the output format. 

The HDX integration would extend off of this but represent a slightly different module. The work done on what actual data is output and that it is actually understandable and usable would fall under  The Improved Data Export but also the Data Model working group which is currently delayed.

We will have a sync meeting next week between Design and Devs. I will make sure you are tagged when the write up of that meeting is done so you can read notes though HDX won't be directly included in that discussion I will add a note to explain how this work will facilitate that work.

**Comment by rowasc** [comment]
Adding the link to the POOF we are doing on the more technical side for the export to not be limited to small datasets so we don't lose the reference. 

 https://docs.google.com/document/d/1eGw8THfq9ms3kG1kxdMiRv-5GSHRj4SHjQtFrGeHeGA/edit#
