### ISSUE TITLE
HDX Integration

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2397]
As part of the COMRADES project, the COMRADES platform will integrate with the Humanitarian Data Exchange (HDX) and support the Humanitarian Exchange Language (HXL). 

[EPIC Overview Document](https://docs.google.com/document/d/1GWQRkM0cPF1-3GOIz4uhSsGJClt9U1QPD_WdGw80UYs/edit) 
//This document contains useful background info on what is HDX/HXL, and the workflows/user stories we expect from COMRADES users with this integration.

[EPIC Scope for HDX Integration v0 and v1](https://docs.google.com/spreadsheets/d/1w-4euXYUleDFrRAcXaxQ2N1BimxQp3cFcH8xFjzAppc/edit?ts=5ad9acc1#gid=2113011469) //This is a work in progress to capture feature components and delivery dates for v0 (May 21) and v1 (June 22).

Useful external links. These are all publicly accessible:
[HXL Postcard](http://hxlstandard.org/standard/1_1beta/postcards/) - handy reference to HXL taxonomy.
[HXL Examples](https://tools.humdata.org/examples/hxl/) - sample datasets with HXL tag translations.
[HXL Homepage](http://hxlstandard.org/)

**Comment by Shadrock** [comment]
I've done my best to write up an ["Epic" document here](https://docs.google.com/document/d/1GWQRkM0cPF1-3GOIz4uhSsGJClt9U1QPD_WdGw80UYs/edit?usp=sharing). This document will be the central point of truth for all things related to our work with HDX (it may become multiple docs within a folder if needed). We will be having a kick-off meeting with HDX shortly, after which time I expect we can start generating issues. Please advise if I need to add/clarify the doc: edit permissions are open for edits, comments, etc.

**Comment by caharding** [comment]
Next action is for @Erioldoesdesign to review this issue for design scoping so we can get back to @Shadrock @caharding  on anticipated timeline for design

**Comment by rowasc** [comment]
Closing, this was delivered (since we can open a new HDX epic if new work is to be done in the future  and scope it )
