### ISSUE TITLE
EPIC: CSV Export

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2399]
CSV export is a highly desired feature but often does not work as the user expects, and does not offer the configurability that various types of users need for it to fulfill its value proposition. 
As a result of several user feedback sessions, bug reports, and numerous support tickets on Intercom about CSV export, we discovered that we need to improve the feature to better serve users’ needs. 

## Types of users
We have found three key types of users that most value the CSV export feature, but use it very differently:
- `Visitors`: they are `logged in` users in deployments who want to extract publicly available data. These are often researchers/students who want to use the data to academically refute or validate hypotheses. 
- `Deployment managers` who need to configure privacy settings, manage their team, and report up to management/funders. They value fast, straightforward export process that gives them the data they need to help them decide how to manage their resources for the project, and/or create reports on key impact/success metrics for funders. Examples of questions they might be trying to answer include: 
- `Monitoring and evaluation analysts` who conduct complex statistical analysis in third party tools (Stata, R, etc). Similar to the visitor’s use case, but specifically needs to be able to access all data within a deployment and conduct significant statistical analysis to prove or disprove 

## Design prototype reference 
[DEPRECATED!!!] https://invis.io/RZFGBTBSC3W 

[ACTIVE/UP TO DATE] https://xd.adobe.com/view/fe480c43-df79-4387-b38a-22396df4e8de/

# Notes from Justin after user testing - IMPORTANT: 
*Let's leave CSV export in the "Share" button for now (even though we've had feedback that it doesn't belong there...)* 

### Reference documentation
- CSV Spec started here . Will be view/comment only from today https://docs.google.com/document/d/1tWETG2_NuloqO5bS18b3yDxBRkQIzptSgUxMOjHkei4/edit  

- There is some work being done around performance here https://github.com/ushahidi/platform/issues/2421 here. 

### Source of truth: 
GITHUB ! the docs are a reference, for the sake of knowing where things started.

**Comment by rowasc** [comment]
@kinstelli updated this to mentioned that visitors is actually logged in users, not anonymous users. LMK if there are questions.

**Comment by Eve-wanderi** [comment]
Export Functionality works however, i have a few concerns.
1.  The report is not user friendly. There are multiple columns that do not have data can these columns be automatically deleted so that once users export the file they dont have to see these empty columns.
