### ISSUE TITLE
As a deployment manager and deployment visitor, I expect the CSV column headers to match what I see in a deployment

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2400]
### Acceptance criteria
- [ ] I can see a human-readable column name. 
- [ ] The column name is represented as in the deployment: ie: I should see categories represented as "Category" instead of "Tag"

### Test script
As Deployment Manager
- [x] Deployment manager downloads a CSV export
- [x] All headers of CSV file match the field names as the user sees them in the client

As Deployment Visitor
- [ ] Deployment visitor downloads a CSV export
- [ ] All headers of CSV file match the field names as the user sees them in the client

### Spec
Since there are two kinds of fields: platform-defined fields and user-defined fields, each of which have a human-readable name, we'll need to make sure that the exporter can access both sets of human-readable names.

- [ ] A lookup index must exist on the API that maps server-side field names to names currently displayed in client
- [ ] Export code must lookup column human-readable name for fields from DB
	- [ ] Export script looks up a human-readable name for platform-delivered fields 
	- [ ] Export script looks up a human-readable name for user-defined fields
	

Note: this is a merge of #2402, which differed only by role.

Natural language translations / i18n feature has been moved to #2463.

**Comment by rowasc** [comment]
@willdoran since you are working on values, I think you should tag yourself here to avoid duplication of work and have a better view of it

**Comment by willdoran** [comment]
@kinstelli called out possible overlap in #2402

**Comment by kinstelli** [comment]
This ticket is the same as #2402, with the exception of role.

**Comment by StaicyG** [comment]
@rowasc                        

I am not able to view column titles from the CSV exports as shown below:
[Uploading... Screen Shot 2018-04-03 at 2.38.47 PM.png ]

**Comment by kinstelli** [comment]
@StaicyG  _ Can you try this again, since we've recently changed the data on the server?

**Comment by StaicyG** [comment]
@kinstelli 
The CSV file has a lot of columns with confusing titles that do not necessarily match which the field names on the platform.

**Comment by kinstelli** [comment]
This looks like it's just not working as spec'd. Marking it as a bug.

**Comment by rowasc** [comment]
@kinstelli can you add details? 
thanks

**Comment by kinstelli** [comment]
Copying what Staicy left on another ticket, which includes some examples:

---
The data on the CSV file seems to be jumbled up, some "title names" fall under the contact column, some fall under "sets" column some fall under "content" column.
There is no column for "date" and "date and time" as indicated from the test script
no column named "image" or "video" : the ones that are there are link0 and link1. This makes it hard to tell apart the video link from the photo link
Data from checkboxes not showing on the CSV file
There is no task column as indicated from the test script

The data on the CSV is not easy to understand for users who are not well acquainted with the code and the string names used in the code

**Comment by rowasc** [comment]
Moving to in-development since it's the same as the headings ticket

**Comment by StaicyG** [comment]
@rowasc @kinstelli 

Failed QA test. I don't seem to get passed "Export in progress" for both "Export All Data" and " Selected Fields"

**Comment by StaicyG** [comment]
@kinstelli 
I was doing the tests here: (https://annatest1000.ushahidi.io/)
Out of about 7 csv export requests only 2 CSV files were downloaded and it took a period of about an hour, an hour and a half

**Comment by StaicyG** [comment]
@rowasc @kinstelli 
Test environment: http://csvexportsforever.v3-qa.ush.zone
Test 1: Deployment Manager. 
CSV passed QA test for "Export All Data"
Column names are not visible for "Select Fields" CSV downloaded file

Test 2: Please clarify who the deployment visitor is

**Comment by StaicyG** [comment]
@rowasc @kinstelli 

update after retest: when requesting for "Export Select Fields", I get the error illustrated in the screen shot below and no CSV file gets downloaded:
![Screen Shot 2018-04-20 at 10.31.25 PM.png](https://images.zenhubusercontent.com/5a8e72064b5806bc2bc7edf1/d3ea3a3f-5f69-41fe-b5c9-eb0551d0dfb0)

After requesting for a 2nd time, CSV file downloads with title names

**Comment by crcommons** [comment]
Duplicate issue created. See #2838 for reference
