### ISSUE TITLE
As a deployment manager, I expect the CSV column headers to match what I see in a deployment

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2402]
### Acceptance criteria
- [ ] I can see a human-readable column name. 
- [ ] The column name is represented as in the deployment: ie: I should see categories represented as "Category" instead of "Tag"

### Test script
- [ ] Deployment manager downloads a CSV export
- [ ] All headers of CSV file match the field names as the user sees them in the client
- [ ] All headers of CSV file match the language that is currently used by the user

### Spec
Since there are two kinds of fields: platform-defined fields and user-defined fields, each of which have a human-readable name, we'll need to make sure that the exporter can access both sets of human-readable names.

- [ ] A lookup index must exist on the API that maps server-side field names to names currently displayed in client
- [ ] A server-side map of translations must exist to map to the human-readable field names of platform-delivered fields to translated local languages
- [ ] Export code must lookup column human-readable name for fields from DB
	- [ ] Export script looks up a human-readable name for platform-delivered fields 
	- [ ] Export script looks up a human-readable name for user-defined fields
	- [ ] Export script looks up a language translation for each human-readable name and maps that to a natural language translation

Note: this is just a different persona from #2400 at the moment, but they might diverge as we learn more. One of them will have the bulk of the work when we get to development, the other just implement for a specific persona/role and test for it

**Comment by rowasc** [comment]
@kinstelli 
FWIW, adding a list of things that we will want to answer here: 
- document each field type.
- the format for each field type that we currently have
- timezone format/which timezone is represented in the csv export
- do we remove headers if there is no content for them?

**Comment by kinstelli** [comment]
• i18n for column names might be tricky, too, since translations are all client-side.

**Comment by rowasc** [comment]
@willdoran since you are working on values, I think you should tag yourself here to avoid duplication of work and have a better view of it

**Comment by willdoran** [comment]
@kinstelli For the outputting of the values as CSV columns we will need to extend the Post formatter to handle each type, at the moment it relies on Client to understand that - we will have to be careful not to break this for mobile/client. This is called out under #2403. 

I think this one is slightly different and might need its own special formatter for column names. The worst ones are going to be tag, select, radio and checkbox.

**Comment by kinstelli** [comment]
@rowasc, @Erioldoesdesign, and @justinscherer -- I'm following up on some questions/concerns that Romina posted above. 

Some of these seem more relevant to exported values more than the column headers, so I might move these to that card, but obviously these must still be answered before we do development, regardless. 

I'll split these into separate comments for formatting sanity:

**Comment by kinstelli** [comment]
* document each field type
*  the format for each field type that we currently have 
    * I'm not sure I understand what this would mean. Does this mean including descriptive data in the CSV per each field type? Or are we thinking that the UI should display this information prior to export?*

**Comment by kinstelli** [comment]
*  timezone format/which timezone is represented in the csv export

*I see three options: either default to the timezone of the user, default to UTC, or let the user choose at the moment of export. Any opinions on which, or are there maybe better options?*

**Comment by kinstelli** [comment]
- do we remove headers if there is no content for them?

 I don't think we should do this, for a few reasons: 
1. From the user's perspective, there's a big difference between knowing that an entire column is empty, versus wondering why it's not appearing. In other words, we shouldn't omit a CSV column without being clear that we are omitting it.
2. If the user is comparing exports over time, particularly using some kind of external data tool, it's entirely possible that one time period of results has data and one doesn't. It could potentially be a real pain to match up data sets if one column is simply missing.
3. Practically speaking, I don't think there's a way to know that a field has no content without doing a full query on the entire data set, so there's not an easy way to let the user know prior to export that we might choose to omit it. I also don't see a clear way to let the user know in the CSV that something was omitted because it was empty....although, I suppose they could be informed when they return to download their generated CSV.

**Comment by justinscherer** [comment]
> I'm not sure I understand what this would mean. Does this mean including descriptive data in the CSV per each field type? Or are we thinking that the UI should display this information prior to export?

no, it's just a UI tweak where we append the format of the data to the end of the field name. e.g. "Field 1 (image)", "Field 2 (text)" etc.

> I see three options: either default to the timezone of the user, default to UTC, or let the user choose at the moment of export. Any opinions on which, or are there maybe better options?

Use UTC and label it as such. 

> do we remove headers if there is no content for them?
I don't think we should do this, for a few reasons...

I agree, leave re-named headers in there when there's no content.

**Comment by rowasc** [comment]
@kinstelli on my side, `document each field type` was part of the "TODO list" the person spec'ing this needed to do, to be certain they didn't miss a field type's formatting requirement. 
See this as a reference https://github.com/ushahidi/platform/issues/2403

**Comment by rowasc** [comment]
Here's an example export of my deployment with 2 posts. One if a basic post with just categories, title, description. The other is a post with ALL the fields we support. 
(had to change extension because github doesn't let me upload .csv ) 


[csv-2018-02-02 copy.txt](https://github.com/ushahidi/platform/files/1690469/csv-2018-02-02.copy.txt)

@kinstelli sending this in case it helps

**Comment by rowasc** [comment]
@willdoran @kinstelli I did this survey with all field types and found just 1 Number (Number) and no radios. I kind of remember going through this but maybe you know why that is. 

  Example export of a deployment with 1 basic survey with categories and a survey that has ALL the fields we support https://docs.google.com/spreadsheets/d/1vbehDuc8dh468ai7gBSMISFFqR5_5wpbJyC_HyWGBTQ/edit#gid=0
All the field types I had, listed here:
 Checkbox: Text of the option selected
 Select: Text of the option selected
 Video: URL provided
 Image: Image ID 
 Short text: text
 Long text: text
 Number: number
 Location: lat/lon each in a different field
 Date: 2018-02-02 00:48:20
 Date & time: example 2018-02-03 00:48:20
 Related Post: ID of post
 Markdown: raw text
 Categories: category name in value
