### ISSUE TITLE
As a deployment manager or visitor (logged in) I expect the CSV column values to match what I see in a deployment

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2403]
### Acceptance criteria 
- [ ] I can see a human-readable column value that is consistent to what I see in a deployment. 
    - [ ] Ie: If I’m being shown the gender of a person, it should be in the same format as seen in the deployment

### Spec
- Platform API:
  - [ ] Extend Post Formatter to provide per field formatting for all field types
    - Currently unhandled field types:
      - [ ] Checkbox: No changes - text of selected checkboxes.
      - [ ] Radio:  text of selected option 
      - [ ] Select: No changes - text of selected option
      - [ ] Video: No changes - Video URL
      - [ ] Image: Changes - Image URL
      - [ ] Related Post: IDs, separated by comma. 1 column only (per related posts field) as in categories
      - [ ] Markdown: No changes
      - [ ] Categories: Changes -  1 single category column per category field, instead of a column per category, comma separated. 
      - [ ] Location: No changes
      - [ ] Date: Changes - should be a date, not date+time. Timezone UTC
      - [ ] Date Time: Changes - Timezone UTC
      

### Test
- [ ] Field formatting should be correct based on field type for:
  - [ ] Checkbox: text of selected checkboxes.
  - [ ] Radio:  text of selected option 
  - [ ] Select: text of selected option
  - [ ] Video: Video URL
  - [ ] Image: Changes - Image URL
  - [ ] Related Post: IDs, separated by comma. 1 column only (per related posts field) as in categories
  - [ ] Markdown: markdown
  - [x] Categories: 1 single category column per category field, instead of a column per category, comma separated. 
  - [x] Location: 1 column for lat, one for lon. 
  - [ ] Date: Changes - should be a date, not date+time. Timezone UTC
  - [ ] Date Time: Changes - Timezone UTC
  - [ ] Short text
  - [ ] Long text
  - [ ] Number (Decimal)
  - [ ] Number (Integer)

- [ ] Posts exported are limited based on User's permissions
- [ ] Related Post data is limited based on User's permissions
  - [ ] Tag restrictions are respected
  - [ ] Task/Stage restrictions are respected
  - [ ] Field level restrictions are respected
  - [ ] Related Post permission are respected
  - [ ] Author information(email, real name) restriction is respected
- [ ] The feature can be used by everyone who is logged in (Admins, Logged in users and other roles that are "logged in" )

**Comment by rowasc** [comment]
> Field formatting should be correct based on field type for:

defining "correct" with this doc between Will/Angie/Hazel/Romina/Mark (pending questions doc)

https://docs.google.com/document/d/1fgGutCF2CnFdqTeu3AWomEeooCuXOYQFSNUOoeK5sGw/edit 

All info to be moved here on MONDAY by @rowasc so there are no external doc dependencies

**Comment by rowasc** [comment]
Aside from that missing info, it looks great.

**Comment by crcommons** [comment]
I was asked to take a look at this issue... Unfortunately I don't totally understand it. I get the general idea of what we're trying to do, but perhaps because I've never looked at Post Formatter before, it doesn't make a ton of sense.

**Comment by rowasc** [comment]
@crcommons Thanks for giving it a look. I feel that the details we need to add are what's stopping this from being clear from a non-backend POV. But let me ask you, to be sure. 
Would it help if it was framed as "The values should be formatted following this rules:

- Date fields should be UTC and formatted as YYYY-MM-DD HH:MM:SS 
- DateTime fields should be UTC and formatted as YYYY-MM-DD
-  Checkbox fields should be expressed with the checkbox text, not the index 
- Images should be an URL 
" 

(obviously missing fields here)

**Comment by rowasc** [comment]
FYI working on finishing this spec with the feedback we have

**Comment by rowasc** [comment]
@willdoran would appreciate your feedback on the "All the questions " doc now that Angie gave hers too

**Comment by rowasc** [comment]
Adding what still needs to be decided: 
- timezone for dates: do we go for user-timezone from browser, or not?
- images: do we have them in the export, or not?  
- related posts: 1 column for all the related posts, as for categories?
- related posts: should we use ID + Title as the value?

**Comment by rowasc** [comment]
>timezone for dates: do we go for user-timezone from browser, or not?
New ticket for timezone selection added. Go with UTC for this iteration.
https://github.com/ushahidi/platform/issues/2465

**Comment by rowasc** [comment]
>images: do we have them in the export, or not?

YES
> related posts: 1 column for all the related posts, as for categories?
Yes. Comma separated IDs. 

>  related posts: should we use ID + Title as the value?
not yet. Lets wait for user testing

**Comment by rowasc** [comment]
@willdoran only blocker to go to ready for Dev is that I'm not sure how to use a radio button/can't find it. If you can check that and update where I tagged you in the description, we will be ready for dev

**Comment by willdoran** [comment]
They are represented in the code as varchar, same as select and checkbox

**Comment by rowasc** [comment]
Yep, sorry. Found it

**Comment by rowasc** [comment]
https://docs.google.com/spreadsheets/d/1a5oWvexADUQISqlHW4sv2IRY-PqU3CBygswmuqW9MjA/edit?usp=sharing
@aoduor @jshorland @Hazellaura @willdoran @Erioldoesdesign @justinscherer is there any field here that we absolutely should remove? right now it follows the guidelines in the spec but I could remove fields or tweak things tomorrow if there's feedback. 
(also, please LMK if I should add someone else here? ) Remove the .txt extension to be able to use this.

**Comment by rowasc** [comment]
After talking with Jess, I think we should remove: 
lock
locale
parent_id

@willdoran do you know if type,  contact_id, and message_id are ever useful? We think those could go as well but I'm not sure if it's something that would be used ever because we don't export unstructured posts.

**Comment by willdoran** [comment]
nope, they aren't but we do want to include the contact info. I thought we were for uchaguzi but I can't see it now

**Comment by rowasc** [comment]
Will remove lock, locale, parent_id and published to then. 
About contact info: 
@willdoran realized that we do. When running with the test dataset I see contact info correctly added 👍 
Thanks

**Comment by rowasc** [comment]
removed. PR updated

**Comment by StaicyG** [comment]
@rowasc 
I tried opening data mode to compare the information there with the data in CSV and I received the error below:
![Screen Shot 2018-04-03 at 2.31.50 PM.png](https://images.zenhubusercontent.com/5a8e72064b5806bc2bc7edf1/4db9e984-cc8c-4022-b4cf-dbc6fa963f1d)

and yet when you look at map view, there seems to be quite a number of posts made to the different surveys as shown below:
![Screen Shot 2018-04-03 at 2.32.05 PM.png](https://images.zenhubusercontent.com/5a8e72064b5806bc2bc7edf1/f6bdbc79-d602-48a2-9c15-b2fd8cf58ca2)

2. The CSV does not have a title for each column

**Comment by kinstelli** [comment]
@StaicyG - Sorry about that, the data was messed up on the csv QA server, but it should have been fixed as of this morning. I'm sending this back to Testing column.

**Comment by StaicyG** [comment]
@kinstelli 

The data on the CSV file seems to be jumbled up, some "title names" fall under the contact column, some fall under "sets" column some fall under "content" column.
There is no column for "date" and "date and time" as indicated from the test script
no column named "image" or "video" : the ones that are there are link0 and link1. This makes it hard to tell apart the video link from the photo link
Data from checkboxes not showing on the CSV file
There is no task column as indicated from the test script 

The data on the CSV is not easy to understand for users who are not well acquainted with the code and the string names used in the code

**Comment by rowasc** [comment]
@StaicyG thanks for your feedback, I really appreciate that you found these issues. 

A couple things:
`About Date&Time `

Those are data types (all the test script items are just data types, they may or may not exist in a specific csv, it depends on the data set in the surveys)

-  Date: Changes - should be a date, not date+time. Timezone UTC
-  Date Time: Changes - Timezone UTC
That said, you can check that Post_Date, Updated and Created are correctly formatted when available 

`About Media`
Media appears if there's data for it. But It should still be a field even if there's no data so the csv is consistent. I'll look into that. 


`About the scrambled data`
That's going to be solved today as soon as I push the new fixes. Thank you 💯 for finding it, it's a huge issue. I'll ping you as soon as it's released 

`In general, about the missing fields (ie task column) `
If a form does not have a field, it won't appear. It should appear if there's no data, but not if the field does not exist. I'll check this in any case to make sure there's a problem or not and address it ASAP

**Comment by rowasc** [comment]
@StaicyG also, about the data mode: I'm not really sure how to reproduce that, but can you report it in a separate ticket? It's not related to CSV and we should prioritize it accordingly. Thanks!

**Comment by crcommons** [comment]
@kinstelli To make a new ticket for bugs.
