### ISSUE TITLE
As a deployment manager, I want to be able to select which fields within my filtered data set to export. 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2405]
Proposed view of field selections:
 ![Screen Shot 2018-02-01 at 3.56.02 PM.png](https://images.zenhubusercontent.com/5a629a264b5806bc2bc37fde/2c35e719-1687-4b01-88a7-f00af89bb003)

### Demo script

- [x] Deployment manager requests an export of data and chooses **Select fields** button
- [x] A **Select fields for export...** screen appears, along with a list of all human-readable field names for each available survey type
- [x] Deployment manager is able to select individual checkboxes
- [x] If Deployment manager selects **Select all...** checkbox for a survey
    - [x] all checkboxes are selected for that survey
- [x] If all survey fields are checked:
    - [x] the **Select all...** checkbox remains checked

- [x] Deployment manager selects **Export Selected Fields**
- [x] An export process is started
- [x] Upon completed of export, a CSV file is available for download
- [x] The resulting CSV file contains the fields selected for export
- [x] The resulting CSV file does not contain any extra fields

### Spec
- [ ] From the **Select fields for export...** screen, we will need to collect and store a selected set of field names for each requested survey export
- [ ] The user selected field names must map directly to data fields in the DB
- [ ] The export script must be modified to accept a set of fields that will ultimately be included in the CSV export

**Comment by kinstelli** [comment]
Concerns / Questions ( @justinscherer and @Erioldoesdesign ):
 
- The list of field names for each survey is potentially very long. Is a single column of checkboxes sufficient, or should this wrap into multiple columns? Could it be shown in a container that scrolls? 

- Should the selected set of fields be persisted/stored somewhere on the platform? 
For example, if the user selects one export with a selected set of fields, and a hour later requests another export, should the selected field checkboxes remained checked?

And if so, should they persist across the entire deployment, or -- if there are multiple deployment managers -- should that selected set of fields be stored individually for each manager?

- If a user selects multiple surveys for export, should those be combined into one CSV file, or should each survey be a separate CSV file?

**Comment by justinscherer** [comment]
> The list of field names for each survey is potentially very long. Is a single column of checkboxes sufficient, or should this wrap into multiple columns? Could it be shown in a container that scrolls?

Single column is fine for now. Agree it'll get super long in some cases, but I really don't have nay data to support it. A big one-column list is the most scalable for mobile, as well. 

> Should the selected set of fields be persisted/stored somewhere on the platform?

Nope. Every export starts from scratch. 

> If a user selects multiple surveys for export, should those be combined into one CSV file, or should each survey be a separate CSV file?

Would love an A/B on this to make a proper call. Ultimately, I have no idea what a data worker would expect. So I would say leave it as one sheet for now for purely arbitrary reasons.

**Comment by kinstelli** [comment]
@justinscherer - Awesome. Thank you.

**Comment by rowasc** [comment]
@kinstelli Mark this looks good. Ready for dev'd it. =)

**Comment by Angamanga** [comment]
@kinstelli Are you working on this one? Else I'll grab it, fixing the styles anyway and its kind of connected to this one https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2429

**Comment by Angamanga** [comment]
@Erioldoesdesign @justinscherer Would it be ok to make the survey-name clickable and then show the field-names with checkboxes like this:   

This would mean asking the server for the survey-fields once the user clicks on the fields  improve the performance of the page, getting all the fields for all surveys in a deployments requires a lot of requests to the api and will make the page slow :/

**Comment by justinscherer** [comment]
@Angamanga How much slower are we talking? I appreciate the desire to limit the call son this one, I'd rather not do it this way for a few reasons:

1. the 16px lato semibold doesn't look tappable, there's no way for a user to discover that it's tappable without hovering over it. This is an endemic problem that we need to fix all over the place, mind you, but making this feature dependent on an inaccessible, mobile-unfriendly, and less-than-ideally-usable link style 

2. it would add unnecessary clicks

3. it would function as an accordion, but doesn't look like a normative accordion. 

Is it possible to do some kind of asynchronous load that would allow the the page to load and the user to use at least some of the fields before loading all of them?

**Comment by Angamanga** [comment]
Demo is here: https://drive.google.com/file/d/1aJr6x4JOpZ3J5XIRkzxWEJR8kX-TujJH/view?usp=sharing

I went with @justinscherers arguments above and did not implement the clicks to get the fields, so far it doesnt seem to slow down the page too much and the fields are loaded as they come back from the server + its indicated that the page is loading with a loading-bar.

**Comment by justinscherer** [comment]
Can we bump up the vertical spacing between the survey headers in the field selection list?

<img width="218" alt="screen shot 2018-02-26 at 10 41 38 am" src="https://user-images.githubusercontent.com/29209303/36685797-aca8baaa-1ae1-11e8-9f9e-33bb3d119f76.png">

**Comment by kinstelli** [comment]
While QAing this, I did the following:
On `http://csvexportsforever.v3-qa.ush.zone/settings/data-export`
 I chose Settings->Export Data -> Select Fields

Under a new survey called `Test Survey with various field types`, I chose `Select All`.

This generated a new record in `export_job`, with the following data related to the query:

`filters`: `NULL`
`fields`: `NULL`
`header_rows`: `[{"label":"Post ID","key":"id","type":"integer","input":"number","form_id":0,"form_stage_id":0,"form_stage_priority":0,"priority":1},{"label":"Created (UTC)","key":"created","type":"datetime","input":"native","form_id":0,"form_stage_id":0,"form_stage_priority":0,"priority":2},{"label":"Updated (UTC)","key":"updated","type":"datetime","input":"native","form_id":0,"form_stage_id":0,"form_stage_priority":0,"priority":3},{"label":"Post Date (UTC)","key":"post_date","type":"datetime","input":"native","form_id":0,"form_stage_id":0,"form_stage_priority":0,"priority":4},{"label":"Contact ID","key":"contact_id","type":"integer","input":"number","form_id":0,"form_stage_id":0,"form_stage_priority":0,"priority":5},{"label":"Contact","key":"contact","type":"text","input":"text","form_id":0,"form_stage_id":0,"form_stage_priority":0,"priority":6},{"label":"Sets","key":"sets","type":"sets","input":"text","form_id":0,"form_stage_id":0,"form_stage_priority":0,"priority":7},{"id":"31","key":"test_varchar_targeted_survey_2","label":"Test varchar Targeted Survey","instructions":null,"input":"text","type":"varchar","required":"1","default":null,"priority":"1","options":"","cardinality":"1","config":null,"form_stage_id":"9","response_private":"1","description":null,"form_stage_priority":"0","form_id":"9"},{"id":"4","key":"description","label":"Description","instructions":null,"input":"textarea","type":"description","required":"0","default":null,"priority":"0","options":"","cardinality":"1","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"17","key":"title","label":"Title","instructions":null,"input":"text","type":"title","required":"0","default":null,"priority":"0","options":"","cardinality":"1","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"25","key":"markdown","label":"Test markdown","instructions":null,"input":"text","type":"markdown","required":"0","default":null,"priority":"0","options":"","cardinality":"1","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"1","key":"test_varchar","label":"Test varchar","instructions":null,"input":"text","type":"varchar","required":"0","default":null,"priority":"1","options":"","cardinality":"1","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"2","key":"test_point","label":"Test point","instructions":null,"input":"location","type":"point","required":"0","default":null,"priority":"1","options":"","cardinality":"1","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"3","key":"full_name","label":"Full Name","instructions":null,"input":"text","type":"varchar","required":"0","default":null,"priority":"1","options":"","cardinality":"1","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"5","key":"date_of_birth","label":"Date of birth","instructions":null,"input":"date","type":"datetime","required":"0","default":null,"priority":"3","options":"","cardinality":"1","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"26","key":"tags1","label":"Categories","instructions":null,"input":"tags","type":"tags","required":"0","default":null,"priority":"3","options":"[12]","cardinality":"0","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"27","key":"tags2","label":"Categories","instructions":null,"input":"tags","type":"tags","required":"0","default":null,"priority":"3","options":"[\"1\",\"2\",\"3\",\"5\"]","cardinality":"0","config":null,"form_stage_id":"4","response_private":"0","description":null,"form_stage_priority":"99","form_id":"4"},{"id":"6","key":"missing_date","label":"Missing date","instructions":null,"input":"date","type":"datetime","required":"0","default":null,"priority":"4","options":"","cardinality":"1","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"7","key":"last_location","label":"Last Location","instructions":null,"input":"text","type":"varchar","required":"1","default":null,"priority":"5","options":"","cardinality":"1","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"8","key":"last_location_point","label":"Last Location (point)","instructions":null,"input":"location","type":"point","required":"0","default":null,"priority":"5","options":"","cardinality":"0","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"9","key":"geometry_test","label":"Geometry test","instructions":null,"input":"text","type":"geometry","required":"0","default":null,"priority":"5","options":"","cardinality":"1","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"10","key":"missing_status","label":"Status","instructions":null,"input":"select","type":"varchar","required":"0","default":null,"priority":"5","options":"[\"information_sought\",\"is_note_author\",\"believed_alive\",\"believed_missing\",\"believed_dead\"]","cardinality":"0","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"12","key":"second_point","label":"Second Point","instructions":null,"input":"location","type":"point","required":"0","default":null,"priority":"5","options":"","cardinality":"1","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"15","key":"possible_actions","label":"Possible actions","instructions":null,"input":"checkbox","type":"varchar","required":"0","default":null,"priority":"5","options":"[\"ground_search\",\"medical_evacuation\"]","cardinality":"0","config":"[]","form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"13","key":"person_status","label":"Person Status","instructions":null,"input":"select","type":"varchar","required":"0","default":null,"priority":"5","options":"[\"information_sought\",\"is_note_author\",\"believed_alive\",\"believed_missing\",\"believed_dead\"]","cardinality":"0","config":null,"form_stage_id":"2","response_private":"0","description":null,"form_stage_priority":"99","form_id":"2"},{"id":"11","key":"links","label":"Links","instructions":null,"input":"text","type":"varchar","required":"0","default":null,"priority":"7","options":null,"cardinality":"0","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"},{"id":"14","key":"media_test","label":"Media Test","instructions":null,"input":"upload","type":"media","required":"0","default":null,"priority":"7","options":null,"cardinality":"1","config":null,"form_stage_id":"1","response_private":"0","description":null,"form_stage_priority":"99","form_id":"1"}] |`


I believe that fields and filters are meant to reflect the fields chosen in the **Select Fields** step, but these are not being populated.

**Comment by Angamanga** [comment]
Fix is merged so can be QAd again!

**Comment by rowasc** [comment]
cc @StaicyG this can be re-tested 🎉

**Comment by kinstelli** [comment]
@StaicyG  - Are you testing this on the QA server? 
Do the CSVs that are eventually generated actually match the fields requested?

**Comment by StaicyG** [comment]
@kinstelli 
Question 1:Anna had requested me to test this on .io (https://annatest1000.ushahidi.io/)
Question 2: Yes the one that eventually downloaded matched the fields requested

**Comment by StaicyG** [comment]
@Angamanga @kinstelli 
Qa environment: http://csvexportsforever.v3-qa.ush.zone

Passed QA test. 

Point to note: the CSV file doesn't contain title name for the different column (I am not sure if that was intentional so just thought to flag that)
