### ISSUE TITLE
As a deployment manager, I want to be able to export the filtered data set from my charts and graphs on my activity screen. 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2406]
- [ ] Data will be filtered to be the posts represented in the activity screen
- [ ] All (available/allowed) headers will still be available in the export 

### Demo script - interpretation 1
[ ] - deployment manager goes to activity screen 
[ ] - deployment manager selects a date range, 
[ ] - deployment manager hits the share button
[ ] - platform immediately initiates a CSV export constrained only by the date ranges selected in the Activity view. 
[ ] - *Compare...* selections are ignored.

### Demo script - interpretation 2
[ ] - deployment manager goes to activity screen 
[ ] - deployment manager selects a date range, 
[ ] - deployment manager hits the share button
[ ] - client redirects user to the filters screen where the date ranges are auto-populated from the Activity date ranges. 
[ ] - deployment manager can continue to make revisions to the export criteria before choosing to export
[ ] - *Compare...* selections are ignored.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-449

**Comment by kinstelli** [comment]
@Erioldoesdesign  and @justinscherer --
I'm looking to clarify the user's experience of this feature as it's written, and I'm seeing both scripts described above as possible interpretations.

I'm also concerned about the implications of *Compare...* menus.
From this Activity screen, the user might think it's possible to export some sort of CSV that is just a comparison breakdown as seen in the charts and graphs. Is that what we want to provide?

**Comment by justinscherer** [comment]
Oooo, good catch on this one. I didn't do a design for Activity at all. Slipped my mind. My bad. Since we're not changing the CSV export on the data view or map view, I would mark this out of scope for now pending the nod from @jshorland . If we decide to do it anyway, we can include a share button just like the other views. 

Ignore the compare menus.

**Comment by rowasc** [comment]
@jshorland I suggest we drop this to product backlog while we decide, per Justin's comment. 
@kinstelli you can send it back to Cycle Backlog while we are finishing up all the other specs

**Comment by rowasc** [comment]
Note: sent a slack to Jess so she finds it easily

**Comment by jshorland** [comment]
Out of scope for this iteration.
