### ISSUE TITLE
Improving search and filters

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2407]
The behavior of the categories are still unclear and needs to be consistent across the app. The behavior for creating, using and filtering for categories is probably not always clear to the user and the behavior of the code might not align with how the user would think it behaves.

### Reference documentation
- Categories Spec started here . Will be view/comment only from today https://docs.google.com/document/d/1H-hGmn4LcoDnAyL51_mW2cpTGfZNPwutr_WLORKG3Ww/edit

### Source of truth: 
GITHUB ! the docs are a reference, for the sake of knowing where things started.
## Goals for this EPIC in Cycle 0 
- To make the filters work, so CSV export can happen and be consistent/useful

## Work order suggested

https://github.com/ushahidi/platform/issues/2408
https://github.com/ushahidi/platform/issues/2409 [TBD]
https://github.com/ushahidi/platform/issues/2436
https://github.com/ushahidi/platform/issues/2437 [ not sure about what this is, @Angamanga  ? I added from the doc but I don't know how to hide categories ]

**Comment by rowasc** [comment]
@Angamanga please let me know when you sync about survey + categories interaction with @Erioldoesdesign

**Comment by rowasc** [comment]
[[Feb 1 2018] Day 2 (Thursday) status report on categories.pdf](https://github.com/ushahidi/platform/files/1686458/Feb.1.2018.Day.2.Thursday.status.report.on.categories.pdf)
Adding the status report for me to keep track. No need to follow up on the epic

**Comment by jshorland** [comment]
updated title to reflect a broader epic

**Comment by rowasc** [comment]
Closing as all child issues were done
