### ISSUE TITLE
Creating a category should not allow child categories to have different permissions than their parent categories

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2408]
### Current behavior:
- The child does not always have the same permissions as the parent in the API, but does according to the client https://github.com/ushahidi/platform/issues/2010)
- A category that has children cannot be a child itself
- A newly created category doesn't automatically get assigned to a survey, that always happens in the survey-editor

### Intended behavior (changes)
- [ ] A child should always have the same permissions as the parent in both the API and the Client

### To take into account when developing
some children *might* already have different permissions than its parent since we enforced this in the client a while after we added the feature with parent/child-categories.

### Demo script
Client demo:  just to show that it's the same as before.
- [x] Pre-requisite: Logged in, in creation page for a category. Example: http://qa.ushahididev.com/settings/categories/create
- [x] `Who can see this category?` shows the permissions are managed by the parent category, if in a child category ( Permissions for this category are managed by the parent category.). 
- [x] `Who can see this category?` shows the normal input for selecting permissions, if it's a parent category. 
<img width="933" alt="screen shot 2018-01-31 at 4 44 28 pm" src="https://user-images.githubusercontent.com/2434401/35643770-0893dd90-06a6-11e8-9fc5-3645296059b9.png">

Backend demo: to show the fixes

- [x] With postman or some other client, get an access token for a user with permissions to create new categories. 
- [x] Send a post request to http://qa.api.ushahididev.com/api/v3/tags to create a new tag. The body should include the parent id and the role should be different than the one in the parent. 
- [x] The server should respond with an error

**Comment by rowasc** [comment]
@Angamanga I'm switching Mark for myself. Sorry =)

**Comment by rowasc** [comment]
@Angamanga sending to you for Spec-review. Since it's backend, I only added the current behavior screenshot

**Comment by Angamanga** [comment]
@rowasc We need to discuss and make a decision about this first: https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2408

**Comment by Angamanga** [comment]
Behaviour-suggestion to be discussed with @aoduor and @Erioldoesdesign before decision about behaviour can made:

1. parent-categories can have less strict permission than its parents
2. child-categories can have more strict permissions than its parents, but not less strict ones

This helps if some children should be hidden and some not.
Usecase: As a deployment-manager, I want to be able to hide some child-categories to some users but keep other child-categories visible to all users even if those children have the same parent.

**Comment by Angamanga** [comment]
Notes from @aoduor to integrate while spec'ing (copied from https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2412, applies to this issue too)
On Default permissions, recommendation:

If it's a child category, assign it default permissions of it's parent.
If it's top level, make it public ( bonus points if we can allow user to select permission on creation, but this is probably too much, lol)
Notes from Justin: we will keep the same UI, specific behavior differences to be discussed with Eriol.

**Comment by rowasc** [comment]
@Angamanga not sure I follow point 1. Also some info about 2
1:
>parent-categories can have less strict permission than its parents
 
1. Parent categories don't have parents. We have 1 level (Parent->children)

2:
>child-categories can have more strict permissions than its parents, but not less strict ones
2. I don't think we have support for this. Our permissions are not a hierarchy in the database. 
As a reference:
+----+----------------------+-----------------------------------+
| id | name                 | description                       |
+----+----------------------+-----------------------------------+
|  1 | Manage Users         | Manage users                      |
|  2 | Manage Posts         | Manage posts                      |
|  3 | Manage Settings      | Manage general settings           |
|  4 | Bulk Data Import     | Import data from external sources |
|  5 | Edit their own posts | Edit their own posts              |
+----+----------------------+-----------------------------------+

You either have the permission or you don't, essentially.
Same with roles: 

mysql> select * from roles;
+-------+--------------+-------------------+----+-----------+
| name  | display_name | description       | id | protected |
+-------+--------------+-------------------+----+-----------+
| admin | Admin        | Administrator     |  1 |         1 |
| user  | Member       | Registered member |  2 |         1 |
+-------+--------------+-------------------+----+-----------+
You are one or the other, but they are not referenced in a way that you know "Oh, this is a lower permission than this other role/permission". 

Except for admin, which implies that the user has all permissions the way it's usually configured, and the way we check for roles. 

----------------------------

Regarding @aoduor  feedback:

 
On Default permissions, recommendation:

> If it's a child category, assign it default permissions of it's parent.

Child categories don't have managed permissions in the client. The problem is that the backend lets you do silly things like ignore that limitation =) So absolutely, we need to fix the backend so it doesn't let you change the child category permissions from the API.


>If it's top level, make it public ( bonus points if we can allow user to select permission on creation, but this is probably too much, lol)
I believe this is a good way to go about it. About the bonus point, yeah, too much until we polish things up =) we let them select roles, tho, which is still useful.

**Comment by Angamanga** [comment]
@rowasc I wrote the wrong thing in 1. I meant parent-categories can have less strict permission than its children. However, right now, for the CSV-export lets go with the solution described in the issue. I am moving the suggested behaviour to a new issue for future reference. Spec is now fine, moving to ready for dev

**Comment by aoduor** [comment]
@rowasc @Angamanga i must have missed this

> A child should always have the same permissions as the parent in both the API and the Client

In my mind, a child CAN have different permissions from it's parent, as long as the parent is public. if the parent is hidden, all its children should be hidden as well.

Using fruits example

- Fruit
-- Apple
-- Avocadoes
-- Grapes
-- Melons

I might have a user group that has declared allergies to avocados and grapes. I can hide avocados and grapes for them, and only allow them to view apples and melons. 

However, if I have no fruits available for breakfast today, and I'll remove all the fruits from the menu, and none should be visible at all. Makes sense?

**Comment by Erioldoesdesign** [comment]
^^^ I see Angela's logic above and it is sound and has relevance to use cases I can imagine.

What I would like to study further (at a later date) is cases where users who can't see hidden children categories (or even parent categories), try to create a duplicate parent/child.
Not sure whether this would even be possible in the current structure but for sure want accurate errors/validation messaging if someone tries to do this. This might not be relevant to this particular ticket.

_child-categories can have more strict permissions than its parents, but not less strict ones_
So we can't do this?

**Comment by rowasc** [comment]
@aoduor Yes, I don't disagree with the idea of that. But I disagree that we have to do it for CSV. It's a change in our permission system that we should avoid at this stage since our categories are in need of a re-do essentially. Can I move it to the product backlog and write a story for this particular case? 
Essentially this ticket is supposed to fix the issue where the client and the server have different logic (Yes, broken :( ) and make a mess of our categories selection, so we need it for CSV to work properly.

**Comment by aoduor** [comment]
I'm cool with this.

**Comment by rowasc** [comment]
creeating it now. Thanks

**Comment by rowasc** [comment]
https://github.com/ushahidi/platform/issues/2453
ah Anna already started one :) YAY Anna.

**Comment by rowasc** [comment]
Demo here https://drive.google.com/open?id=18bIXB9pdknkuOVD9ODblX0-4WUF4W4oi
@Angamanga @jshorland

**Comment by jshorland** [comment]
Looks good to me
