### ISSUE TITLE
Survey Share URL is Incorrect

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#2431]
### Expected behaviour
The Share URL for a Survey should point to the Form for submitting a response to that Survey, for example https://dale.ushahidi.io/posts/create/1.

### Actual behaviour
The Share URL on https://dale.ushahidi.io/settings/surveys/edit/1, points to the current URL inside of Settings.

### Steps to reproduce the behaviour/error
Visit the Share tab for a Survey, notice the incorrect URL.

#### Testing checklist:
- Go to settings-survey and select a survey (not a targeted survey)
- Click on "share"-tab
- [x] The address in the box "Your survey's web address" should be in the format /posts/create/{{survey-id}}

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by crcommons** [comment]
I did not fix this... if it's no longer an issue, it was either someone else or it was a ghost @caharding

**Comment by crcommons** [comment]
@Angamanga Test script here too, please :)

**Comment by Angamanga** [comment]
@crcommons Test-script added. This is merged to develop, not production

**Comment by Eve-wanderi** [comment]
Confirmed this has now been fixed. Share URL does not point to the one in settings.


![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/f8e3fcd9-07c4-47de-b146-c481ba2322c8)
