### ISSUE TITLE
Category-filters in the mode-context-bar in map

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2435]
## Need to be done:
- [ ] Remove category-filters from the mode-context-bar in the map
- [ ] Remove category-filters from the Pattern Library (or retire them to somewhere else in the pl)

### Test Script: Mode bar does not include category filters
- [x]  go to the map-view
- [x] look at the survey-filter
- [x] a category-filter should not be presented under the surveys that have categories
- [x] go to the filter-dropdown 
- [x] Category-filters should be available (researched further in https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2412)

### Test Script: bug connected to survey-category-filters in mode-context-bar does not remain:

- [x] Un-select a category in the filter-dropdown
- [x] Un-select all surveys except for one in mode-context-bar
- [x] Make sure that the filters for categories are still unaffected
- [x] Select a few more surveys in mode-context-bar
- [x] Make sure categories are still unaffected

**Comment by rowasc** [comment]
Next step: @Angamanga to sync up with @Erioldoesdesign on what happens when you select a survey/category in terms of ux/things that get highlighted

**Comment by crcommons** [comment]
I really think this should be LOW LOW LOW LOW LOW LOW priority for now. Like @justinscherer said, we should pick one thing and do it really well. Later we can add additional functionality to filtering once we've tested.

**Comment by Angamanga** [comment]
@Erioldoesdesign discussed this today and our conclusion is that this feature is messy and confusing right now and requires a lot of expert-knowledge about the platform to understand whats going on. Lets remove this feature from the UI right now and allow filtering only in the filter-dropdown. We can revisit this once either users complain the feature is gone or when we do a bigger overhaul of the categories later this year. This was also the conclusion I made from the discussion in https://docs.google.com/document/d/1H-hGmn4LcoDnAyL51_mW2cpTGfZNPwutr_WLORKG3Ww/edit

**Comment by rowasc** [comment]
@Angamanga thank you Anna and @Erioldoesdesign for figuring this one out. This makes me happy. It's either removing it or fixing it, and fixing it 100% is a mess until we do a serious overhaul of it. We cannot be with CSV export filtering unless we make category filters actually behave, and this makes things simpler. 
Thank you . 🙌

**Comment by rowasc** [comment]
@Angamanga did you discuss removing the survey filter? I realize now that the script accounts for survey filters in modebar.

**Comment by rowasc** [comment]
@Angamanga totally OK if that's how it is. Just making sure I understand. I might have closed a ticket that needs to revive now :)

**Comment by rowasc** [comment]
Yup confimed.

**Comment by rowasc** [comment]
OLD DISCUSSION BELOW (just for reference)
## Todays behaviour:
*In mode-context-bar in map-view*
- Categories can only be filtered for one survey at a time
- All other surveys gets deselected when a category is selected/deselected in one survey
  - Its unclear whats filtered if you select another survey as well after they are being deselected by previous step ^^
- A child can be selected without its parent

![Categories.gif](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/ed75ff2e-c55b-49dc-ad7d-1883f016d72e)

## Discussion from the doc TDLR:
- the reasoning behind adding them to the survey filter was to accomodate users who wanted the same kind of realtime interaction with posts on the map by survey, but by category as well. Something we need to test perhaps?
- need to be user tested again
- should we simply remove this feature for now and come back to it later or is it needed for the backend for export to work?

**Comment by rowasc** [comment]
Reviewed, this is good. I don't think there are open questions. 

@Angamanga

**Comment by rowasc** [comment]
@Erioldoesdesign YESSSSS . 💯

**Comment by rowasc** [comment]
@Angamanga did you run this demo?

**Comment by rowasc** [comment]
@Angamanga this is deployed in http://cycle-zero-dev.lab2.ushahidilabs.com/ . After you send the demo, you can move it to testing pipeline. Thanks!

**Comment by Angamanga** [comment]
@jshorland Demo of this is here: https://drive.google.com/file/d/1tYOjd0KbL7UsOq6FW78KY_O1d_PBgLn-/view?usp=sharing

**Comment by jshorland** [comment]
Looks good @angamanga!
