### ISSUE TITLE
If a parent category is hidden, all its children should be hidden.

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2437]
### Expected behavior

- If a parent category is hidden, all children should be hidden

### Actual behavior
???

**Comment by rowasc** [comment]
@Angamanga I can't remember how the hide categories worked, or where to do it :( do you?

**Comment by Angamanga** [comment]
@rowasc I think this is a duplicate of https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2408? There is no current functionality to hide/show categories in another way right now (except from hide the whole category-field to some users)

**Comment by rowasc** [comment]
@Angamanga ugh thanks I assumed I was just being silly and not finding the feature. Closing.
