### ISSUE TITLE
When I unselect a survey in the mode bar, it shouldn't unselect all the categories

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2440]
### Expected behavior
- Only the categories used in that survey are unselected in the drop-down filters and mode bar.
### Actual behavior (inconsistent)
- Sometimes, no category is unselected in the drop-down.
- Sometimes, every category is unselected in the drop-down.
- Sometimes, it works as expected.

**Comment by rowasc** [comment]
@Erioldoesdesign @Angamanga this is pretty important since it makes exporting harder when it happens. Need to find out exact steps since I only saw it once today. @Angamanga ideas welcome

**Comment by Angamanga** [comment]
Ugh! I really want to get rid of the categories in the mode-bar for now. The behaviour needs a lot of work and testing before it makes sense and I dont see us doing that in this cycle?

**Comment by rowasc** [comment]
+100 . 
@Angamanga closing per https://github.com/ushahidi/platform/issues/2435
This is no longer relevant if we are removing it.

**Comment by rowasc** [comment]
@Angamanga realized that the survey filters are still alive and kicking in the modebar. So we need to reopen this.

**Comment by Angamanga** [comment]
Covered as a point in testing in #2435 Closing this...
