### ISSUE TITLE
Adding a post: when you add a category on the fly, it should show in the list of categories in that current post

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2441]
# Current behavior:
- When you add a category while adding a post, it is created but it's not shown in the list of categories for post creation.

<img width="1186" alt="screen shot 2018-01-31 at 5 14 14 pm" src="https://user-images.githubusercontent.com/2434401/35645307-2ee27e58-06aa-11e8-8764-fef2817bf661.png">

# Expected behavior
- When you add a category while adding a post, it is shown in the category list for post creation

# Testing script 
Notes: run this once logged in, and once while being logged out.
- [ ] Click on the + to add a new post. Example url http://qa.ushahididev.com/posts/create/5 
- [ ] Write a new category name and click on the tick icon to create it. 
- [ ] The category should be shown in the list

**Comment by rowasc** [comment]
@Angamanga this is a good candidate to be dropped from the Cycle. It's not something that blocks CSV export from functioning correctly. 
cc @Erioldoesdesign

**Comment by Angamanga** [comment]
@rowasc I agree!

**Comment by Angamanga** [comment]
@jshorland @rowasc Discussed this with @Erioldoesdesign today and we agree, this is a completely different feature with its own quirks and questions which doesnt affect the CSV-export so lets leave it as is now and throw it out of this cycle.

**Comment by rowasc** [comment]
👍 moving to product backlog for further refinement at some point. THanks @Angamanga

**Comment by rowasc** [comment]
@jshorland adding you for refinement / prioritization in a new cycle at some point

**Comment by rowasc** [comment]
This was solved.Clsoing
