### ISSUE TITLE
Implement async comms using Redis and Websocket

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2448]
In order to return the Data Export file to the user asynchronously we need a mechanism to pass events from the API to the client to provide notification to the User. Keeping a connection alive is impractical as we have no idea how long an export will take to complete and could easily timeout. We also need to communicate any errors to the end User that occur and how to proceed.

We have already create a Redis -Websocket comms channel for API Client, this is currently available but is disabled behind a feature flag. This will need to be extended to incorporate a more general comms use case, tested to ensure stability and wired to the Data Export Process system.

### Spec
- Redis websocket adapter
  - [ ] Extend to allow generic events to be passed

- Data Export Process system
  - [ ] Add functionality to send events to redis-websocket comms channel

- Client
  - [ ] Add event to handle inbound event of type Data Export

- Deployment
  - [ ] Redis should be deployable for both enterprise and .io deployments
  - [ ] Websocket Nodejs server should be deployable for both enterprise and .io deployments

### Test
- [ ] Redis is deployed correctly and stable
- [ ] Websocket adapter is deployed correctly and stable
- [ ] Event sent from Redis via websocket to Client arrives as expected
- [ ] Event sent from Data Process system to Redis arrives as expected
- [ ] Event sent from Data Process system to Client arrives as expected

Aha! Link: https://ushahiditeam.aha.io/features/PROD-438

**Comment by rowasc** [comment]
@willdoran I think it's enough detail.  It defines what needs to happen . You can move it to Ready for Dev
