### ISSUE TITLE
Data export enhancements user testing

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2449]
## Testing plan
[Testing Plan](https://drive.google.com/open?id=1i7otkXPs-Skxyl50NIvdwkUT6cLYCnURWRHCuL4o2Ss)
[Prototype for testing](https://invis.io/RZFGBTBSC3W)

## Testing documentation
[Test one](https://drive.google.com/open?id=1fT2yKZ99lDMBauH6u-EHoLOCwCEnArPUyk7nxMyhtN8)
[Test two & three](https://drive.google.com/open?id=1vwr0PuoujjVA97NuGbLdgLcs3LmAJnA9uDZHR144i1I)
[Test four](https://drive.google.com/open?id=1nQzcv_b_5eTodXLKxjKGJrQDmRLEqExRwJcgXROTIuU)

## Testing results

1. Participants expected data export functions to be located either a) as a "Bulk Action" in Data Mode or b) in the Settings menu because it tends to be a catch all and that's where data import currently lives. Bulk actions is not set up for this kind of action right now. 
*Suggestion: We refactor "Bulk Actions" soon and move data export functionality from "Share"*

2. Participants only expressed interest in CSV because it is "basic" and that's what they use day-to-day. They typically expressed incredulity at the need to select file format from a dropdown within the filter pane.

3. Generally speaking, there's too much going on simultaneously in the filter pane to have such a targeted task live there. 

4. Users tended to act cautiously and perform a lot of "double-checking" behaviour. As a result, we added some extra feedback mechanisms in the final designs (e.g. ).

5. Selecting survey fields was not an issue. 

6. Participants felt "sketch" about placing a potentially confidential CSV export function beside social sharing. *Recommendation: We remove data export from Social sharing menu.*

## Updated designs

[Design spec](https://xd.adobe.com/spec/cc984a36-398d-4eb5-8f0a-270d756b0c27/#)
[Clickable Prototype](https://xd.adobe.com/view/fe480c43-df79-4387-b38a-22396df4e8de/)

**Comment by rowasc** [comment]
@Erioldoesdesign this should be in the DONE pipeline, right?

**Comment by Erioldoesdesign** [comment]
@rowasc Yes, testing is complete :)

**Comment by rowasc** [comment]
Moved, thanks!
