### ISSUE TITLE
Revised data export designs

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2450]
## Design documentation
[Revised Prototype](https://xd.adobe.com/view/fe480c43-df79-4387-b38a-22396df4e8de/)
[Revised spec doc (*required Adobe login. sorry...*)](https://xd.adobe.com/spec/cc984a36-398d-4eb5-8f0a-270d756b0c27/#)

### For reference
[Previous iteration](https://invis.io/RZFGBTBSC3W)
User testing results #2449

**Comment by rowasc** [comment]
@justinscherer @Erioldoesdesign was looking at the design and realized there's a few things I don't still understand/need to confirm
To confirm:
- There is no longer an export button in share modal. All logged in users will go to settings directly when they have to export the CSV. Correct?
- Users (all) can select the fields to export each time they export a CSV. Right?
Question:
- Hows does it work with filters, and how does it work from map, data, and from the activity page?
Thanks

**Comment by justinscherer** [comment]
> There is no longer an export button in share modal. All logged in users will go to settings directly when they have to export the CSV. Correct?

nope we leave the export button in the share button as-is on every relevant page for now.

**Comment by willdoran** [comment]
@justinscherer 
- Does Data Export from the settings menu take no account of filters?
- Is Data Export still in the Filter menu or is allowing to filter data exports dropped?

**Comment by justinscherer** [comment]
> Does Data Export from the settings menu take no account of filters?

correct.

> Is Data Export still in the Filter menu or is allowing to filter data exports dropped?

It is not in the filter menu. It remains in "Share", which takes into account filters. This is how the partners were trained to use it. Re: user testing, it didn't make sense to move it from one confusing place to another equally confusing place, neither of which match user expectations. 

> If it's not dropped can they only select fields in the Settings menu version?

It is dropped. And yes, that's correct. You can only select fields int he settings menu.

**Comment by Angamanga** [comment]
@justinscherer @rowasc What is needed to be done in this issue? Can I close it?

**Comment by rowasc** [comment]
This was a reference ticket for designs so we can close it.
