### ISSUE TITLE
Targeted surveys designs

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2451]
Working files should be located here:
**Dropbox (Ushahidi)/Ushahidi Platform/Design/Targeted surveys**

Collaborative docs should be located [here](https://drive.google.com/drive/folders/1W476-F1yOpIHXN3eLenRoZlS9RuaYPdU?usp=sharing).

*Initial designs due:* **19 February 2018**

## Initial designs

[Prototype](https://xd.adobe.com/view/f9cfe17d-55fa-42e1-bb90-3bc67f0956a9)
[Design spec](https://xd.adobe.com/spec/ddad4025-b2a8-4d17-aeef-946283d18b7a) 

## High-level flows
1. Create an open survey with one new question and one custom task. 
2. Send a new targeted survey to a group of contacts

User testing in #2478 

### Background
The goal is to make the survey creation, edit flows more usable, as well as adding a "targeted surveys" option where users can send surveys as SMS messages to contacts. 

DREAMS partners had a terrible time using the current survey creation flow during site visits and during trainings. If you want a rant about how bad our current survey creation flow is, ping me on Slack ;-)

The same folks also need to be able to send their own SMS surveys because their target beneficiaries are overwhelmingly on feature phones and they currently have to go directly through Daniel to send them any messages. 

Survey creation is the **FIRST THING** a new user does when they use Ushahidi for the first time. It is an essential configuration and worth improving. 

### Challenges 
Our current survey create flow is immensely complicated, and has complex survey building sub-flows, as well as task creation/management, and sub-surveys within tasks, and a whole slew of random settings and permissions scattered throughout. Every time I use it I find something new, which is not good...

### Information architecture

I used a our "stepper" module and broke down the entire survey creation process into 5 discreet steps with clear progress gates between them. This solves a problem with the current tool, where a user can save a half-completed survey and miss a whole bunch of important features/settings. 

This also gives the process of survey creation much more coherence. 

### Language

I humanized a lot of the copy e.g.:
- "Field" --> "question"
- "User" --> "person"

### Tasks

Tasks should be a checklist. I kept task creation the same as question creation in structure for consistency. I got rid of the sub-survey management within each task and replaced it with the ability to style in markdown in the task description, as well as the eventual addition of a change log feature, which removes the need for pre-structured mini surveys within each task. The non-modular information architecture of this feature means that we can't touch survey creation without touching tasks, unfortunately... Eventually, tasks should be managed as a global setting, like roles. 

### Contact management
Contact management by itself requires a major refactor to be able to handle groups of thousands of contacts. I recommend we tackle those enhancements soon after we're done with the targeted survey ability. Until then, users will have to add contacts to a targeted survey one at a time from a very long list.

**Comment by willdoran** [comment]
@Erioldoesdesign Can we move these to done?
