### ISSUE TITLE
Different permissions for parent and child-categories

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2453]
Behaviour-suggestion to be discussed with @aoduor and @Erioldoesdesign before decision about behaviour can made:

1. parent-categories can have less strict permission than its children (i.e a parent can have 'show to everyone' and its children can have 'show to specific users') but not the other way around. 
2. if a parent has 'show to specific users', the children must have the same permission

Usecase: As a deployment-manager, I want to be able to hide some child-categories to some users but keep other child-categories visible to all users even if those children have the same parent.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-437

**Comment by rowasc** [comment]
Citing @aoduor  comment in 2408: 
------
Using fruits example

Fruit
-- Apple
-- Avocadoes
-- Grapes
-- Melons
I might have a user group that has declared allergies to avocados and grapes. I can hide avocados and grapes for them, and only allow them to view apples and melons.

However, if I have no fruits available for breakfast today, and I'll remove all the fruits from the menu, and none should be visible at all. Makes sense?

**Comment by caharding** [comment]
I don't understand the real world user need on this ticket

**Comment by rowasc** [comment]
@Angamanga do you recall if we have any real-world requests for this?  I think it makes category management really complex and unless we have data on it being needed, it's something that would introduce a lot of complexity without strong user research data to back it up.

**Comment by Angamanga** [comment]
@rowasc No I don't remember. I think it came up in relation to Dreams and I discussed it with Angie at the time...

**Comment by aoduor** [comment]
This came from our experience with Uchaguzi in previous years as well.
