### ISSUE TITLE
No category-field should be visible if the user doesnt have permissions to see any of the categories in it

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2455]
### Current behaviour
If a user tries to add to a survey with a category-field where there are no categories visible for that user, the field-heading + a select-all option is visible

![Screen Shot 2018-02-01 at 10.05.11.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/9eb44742-5d89-48bd-ba02-691b54fbcf73)

### Steps to reproduce the behaviour/error
1. make sure you are logged out try adding a post to a survey with a category-field where all the categories are limited to for example admins
2. You see the field-heading and the select-all option only.

### Expected behaviour
If a user tries to add to a survey with a category-field where there are no categories visible for that user, the field should not be visible at all.

## Fixing this issue
_I think_ checking if categories.length is >0 in the first div of app/common/directives/category-selector.html should fix this issue, but I haven't tried it. 

## Implementation notes
- Fix in https://github.com/ushahidi/platform-client repo
- Hint :bulb: The code handling the category selector can be found here: https://github.com/ushahidi/platform-client/tree/develop/app/common/directives/category-selector.html 

- When you are done, 🔀 Start a Pull Request. There are two ways how you can start a pull request:

   1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

   2. You can also[ edit files directly in your browser](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) and open a pull request from there.

- 🏁 When done Ask in comments for a review :)

## Want to work on this issue?🙋 
Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Ping @rowasc if you need help with this issue!

**Comment by KManiKumarReddy** [comment]
@rowasc Can I work on this?

**Comment by Guzzler** [comment]
I would like to give a shot at this issue. will open a PR soon

**Comment by Angamanga** [comment]
@all-contributors please add @Guzzler for code

**Comment by rowasc** [comment]
hey @Obadha2 did you manage to test this? I'd like to release on monday but want to make sure we are OK with it

**Comment by CeciliaHinga** [comment]
@Angamanga Is the expected behavior for this as you have explained on the issue what you meant? That if there no categories there should not be a category field type present on the list?If so, i do not have any categories on my deployment and i can still see the category field type
