### ISSUE TITLE
Styling of parent/child-categories in posts and filter-dropdown

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2458]
### Expected behaviour
In the UI-, a parent-category should stand out compared to its children, for example by
have different font styling. e.g. bold and 1em font size bigger

### Actual behaviour
The parent and the children looks the same (with a little indentation for children)
This applies for both filter-dropdown and when adding a post

### Steps to reproduce the behaviour/error
1. go to a survey with a category-field with both parent and child categories
2. look at the styling
3. go to the filter-dropdown
4. look at the styling for parent/child-categories

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-436

**Comment by Erioldoesdesign** [comment]
This is likely to be covered in our UI refactor. Most likely the forms one: https://github.com/ushahidi/platform/issues/2655

**Comment by rowasc** [comment]
Confirmed this is still happening.

**Comment by Erioldoesdesign** [comment]
I have notes, usertesting and sketches on this...somewhere...
