### ISSUE TITLE
Hitting refresh in the browser always sends you to the map if you are in the "Settings" section

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#2460]
### Expected behaviour
When logged in, I'd expect hitting _Refresh_ in the browser would reload the current page I'm visiting.

### Actual behaviour
Hitting refreshing, actually redirects you to back to the Map View, oops!

### Steps to reproduce the behaviour/error

- Log into a deployment, and visit Settings > Categories
- Hit Refresh in your browser
- You will be redirected to Map View

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [X] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-434

**Comment by rowasc** [comment]
Confirmed in QA.
