### ISSUE TITLE
Tweak UI-components on dashboard

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2464]
To be able to deploy and demo:
- inactivate 'add new project'-button
- Remove 'more'-button on modebar in mobile and add login-button/support instead

Testing-checklist
- [ ] Go to dashboard
- [ ] Login
- [ ] Click on 'add new project'-button
- [ ] nothing should happen
- [ ] make sure screen is less than 1023 px
- [ ] look at mode-bar
- [ ] it should be placed on bottom of the screen and contain 'login/logout'-button and support-button

**Comment by rowasc** [comment]
@Angamanga is this going to be done in the cycle? Should it go to ready for dev?

**Comment by Angamanga** [comment]
@rowasc Yes there are two small changes, the rest is moved to product backlog.

**Comment by rowasc** [comment]
@Angamanga did this happen ?  should we ask @crcommons for help?

**Comment by Angamanga** [comment]
Pr for more-button here: https://github.com/ushahidi/platform-dashboard/pull/44
