### ISSUE TITLE
CSV Fields user testing.

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2466]
The continue improving our CSV export, we want to do some user testing for each field type, around the idea of "What are people using it for" or "What do we want to get out of the CSV when we export" 

All of our field types listed here:

 Checkbox
 Select
 Video
 Image
 Short text
 Long text
 Number
 Location
 Date
 Date & time
 Related Posts
 Markdown
 Categories

Aha! Link: https://ushahiditeam.aha.io/features/PROD-431

**Comment by rowasc** [comment]
@Erioldoesdesign adding this so we start planning some user testing around CSV Fields to happen soon. Angie and I spoke today, and we would like to know how exactly each field should behave or what exactly we expect the CSV to do for people 

@aoduor please add anything you feel is relevant to this convo. Thanks!

**Comment by akshayamadhuri** [comment]
https://ushahiditeam.aha.io/features/PROD-431  there is no signup option here

**Comment by Razeetech** [comment]
Good morning, I am an outreachy applicant and i would love to contribute to this project
