### ISSUE TITLE
Blank space between heading and map on embeds

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2468]
### Expected behaviour
- When I navigate from the map to a post and then back again, I see the same view on the map as I saw when I started. 
- The map fills the whole screen, no blank space
### Actual behaviour
When I navigate from map to a post and than back to map again on small screens, the map is zoomed out to world-view and there is a blank space between the map and the header.
![Screen Shot 2018-02-08 at 13.49.20.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/f5cbe1f7-6318-445c-a632-60d862e972cd)

### Test/QA-checklist
- Look at any deployment in embed-mode, easiest is to paste this into a text-file and open the file in the browser: ``` <iframe width="560" height="315" src="https://annatest1000.ushahidi.io/views/map" frameborder="0" allowfullscreen></iframe> ```
- [ ] No white-space between map and mode-bar should be visible
- Test this with many different sizes and click around. Map should always cover its full width + height

####Solution/todo for this issue
- [ ] In the Pattern-library, we need to set the top-position to 0 here: https://github.com/ushahidi/platform-pattern-library/blob/develop/assets/sass/5_layouts/_layout-embed.scss#L110
- [ ] Publish a new tag for PL when this change is done
- [ ] Use this new tag in the client

##### Where
- [x ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by Angamanga** [comment]
I found this when working with #2454, but since its an existing bug and not new, I add it as a new issue to not steal time from current cycle.

**Comment by rowasc** [comment]
:/ This is happening to me in the first load while setting the map in an iframe

**Comment by caharding** [comment]
Would like Dev to investigate for 30m, if there is not a clear potential solution, we will move to next cycle

**Comment by Angamanga** [comment]
This can be QAd on any .io site now.

**Comment by crcommons** [comment]
@Angamanga and here too, please!

**Comment by Angamanga** [comment]
@crcommons Fixed checklist, this is deployed to QA.

**Comment by Eve-wanderi** [comment]
Confirmed fixed.
