### ISSUE TITLE
CSV DOWNLOAD ISSUES 

### ISSUE THREAD

**Issue by Hazellaura** [ushahidi/platform#2470]
###On the ACWICT tab-That when I click select all on the posts I want to download, and then click on share files and then click on the cvs export tab, all the selected reports will be exported into excel. 

##### ACWICT Deployment
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution

**Comment by jshorland** [comment]
cc: @rowasc @Angamanga. I can't seem to reproduce on uchaguzi deployment, or on qa.ushahididev.com -- can either of you reproduce this?

**Comment by jshorland** [comment]
Also -- thank you for filing this @Hazellaura !!!! 🎊

**Comment by aoduor** [comment]
YAAAAAAAAASSSSSSS!

**Comment by jshorland** [comment]
@rowasc i still can't reproduce this, but i'm assuming it's getting fixed in the CSV cycle 0?

**Comment by rowasc** [comment]
Closing, CSV Export workflow was changed entirely and the rows fixed after this in other tickets
