### ISSUE TITLE
User should be able to see a list of CSV files that are available and ready for download

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2471]
### Details
- Files for an entire deployment are available on an external site, such as AWS or other filesystem.
- Once they've been generated, they should remain available for a period of time (how long? one month?)
- There should be a designed view for this list
- User should be able to request removal

### Spec
- [ ] Design is needed for this page

- [ ] Client: A client component should request available list from platform API
- [ ] Client: should provide an ordered list of available files
- [ ] Client: Should have a confirmation dialog for deletion
- [ ] API should have an endpoint to GET a list of all available files, along with created datetimes
- [ ] API should provide a POST link to allow for file deletion
- [ ] API should have a connection to the relevant filesystem(s) to collect the list of files
- [ ] API should pass through the download

### Concerns / Open Questions:
- [ ] Permissions -- does API have exclusive access to this filesystem? Does it provide a direct URL to the user?

### User Script
- [ ] User navigates to this view, either after an alert happens on the client, or directly via a menu item
- [ ] In this view, there is an ordered list of files, complete with the date and time in UTC that they were generated
- [ ] A user can click on a file to request immediate download
    - [ ] The file is sent to their browser for user to save, etc
- [ ] A user can also click on a file to request immediate removal
    - [ ] An "are you sure?" dialog box appears to confirm
    - [ ] The file is removed from the filesystem, and the full screen of files is refreshed

**Comment by rowasc** [comment]
This feature (list exports to download them at a later date) was done in another ticket, as part of the CSV Export UI refactor.
