### ISSUE TITLE
Child categories should use parent permissions by default when created from the Add Post or Edit

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2473]
Dependency: ability to  create child category from add post screen  https://github.com/ushahidi/platform/issues/2474 
Child categories use parent permissions by default when created from the Add Post or Edit Post screen
- [ ] Open the "Add new post"  screen as an admin. 
- [ ] Fill out required info
- [ ] Create a new category under a parent (make sure the parent category can only be seen as admin).
- [ ] Select only the newly created child category for this post. 
- [ ] Save the post (draft/in-review)
- [ ] Select only the newly created child category as a filter
- [ ] You should see the post you just linked to that category in the list
- [ ] You should see no other posts since you only linked the category to the post you created it with.
- [ ] Publish the post
- [ ] Logout
- [ ] In the filters drop-down, you should not see the parent or the children category since they are admin-only.

**Comment by jshorland** [comment]
This is done, yes? closing. reopen if wrong.

**Comment by rowasc** [comment]
yes, this was done last cycle 👍
