### ISSUE TITLE
Share - CSV Export should be available in all views where the share button is visible

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2475]
# Test script:
 ### I see the CSV export button when I open the data view
- [x] Open the data view
- [x] Click on the "Share" button
- [x] Verify that you see a CSV Export button in the share modal with the text "Export filtered data" 

 ### I see the CSV export button when I open the map view
- [x] Open the map view
- [x] Click on the "Share" button
- [x] Verify that you see a CSV Export button in the share modal with the text "Export filtered data" 

 ### I see the CSV export button when I open the data view and select a post
- [x] Open the data view
- [x] Select a post
- [x] Click on the "Share" button
- [x] Verify that you see a CSV Export button in the share modal with the text "Export filtered data" 

 ### I see the CSV export button when I open the data view and select a set of filters
- [x] Open the data view
- [x] Select a filter (ie: a category)
- [x] Click on the "Share" button
- [x] Verify that you see a CSV Export button in the share modal with the text "Export filtered data"

**Comment by rowasc** [comment]
Test script Reviewed by Jess

**Comment by jshorland** [comment]
yup all good

**Comment by rowasc** [comment]
Demo here 
https://drive.google.com/file/d/1rb2g7Gs_q7MNa3LP9pOUpEEUawkTlxeg/view?usp=sharing

**Comment by jshorland** [comment]
Looks good, romina

**Comment by jshorland** [comment]
Passes QA
