### ISSUE TITLE
Refactor notification styles

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2484]
[User testing](#2478) has shown us that out "snackbar" notification style is often being missed because the colour blends in with the chrome of the platform, the text is too small, has confusing icons, is ugly, and is in the wrong place.

I suggest we combine this aesthetic refactor with a broader feature set of notifications for field staff, a robust undo function, and

Aha! Link: https://ushahiditeam.aha.io/features/PROD-429

**Comment by lalidiaz** [comment]
I am Outreachy applicant , may I work on this one please? I will try my best 🙌

**Comment by rowasc** [comment]
mmmm this definitely needs a bit of triage, I'm not even sure what we should do 
@Angamanga is this something you understand/could help define? 
@lalidiaz I assigned you a different issue that you can work on , in the meantime

**Comment by Angamanga** [comment]
@rowasc This one definitely needs design and some of testing before it can be worked on.

**Comment by rowasc** [comment]
@Angamanga thanks Anna. Ok yea this feels larger than I'd be comfortable with (even with the fantastic offer by Eriol to help). Let's hold it.
