### ISSUE TITLE
Error on attempts to duplicate survey

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2485]
### Expected behaviour
I should be able to successfully save a duplicated survey.

### Actual behaviour
When i click in duplicate, and try to save my new duplicate survey, I get this error message.

<img width="823" alt="screen shot 2018-02-20 at 11 00 54" src="https://user-images.githubusercontent.com/721918/36413091-f66376b6-162d-11e8-94d4-d21ab68f41a1.png">

Funny thing though, as much as this is what gets returned to me, the survey gets saved. 

### Steps to reproduce the behaviour/error
- Log in
- Click on settings -> surveys
- Duplicate a survey
- Attempt to save your duplicate survey

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

##### Test-checklist
This pull request makes the following changes:

In the default survey that is added to a deployment, the input is set to 'varchar'. This is not accepted by the validator, and all other title-fields are set to 'text'.
This pr adds a migration to update the set input = "text" for all form_attributes of type = "title".

Test checklist:

- Run migrations

- Go to db

- [ ]  input should be "text" for all form_attributes of type="title

- Go to client -> settings->surveys, click on "Duplicate survey" for the basic survey

- Add a title and save

- [ ]  You should be able to save the new, duplicated survey and not get an error-message

- [ ] repeat on another survey as well, you should be able to save the new duplicated survey and not get an error-message

  I certify that I ran my checklist

**Comment by jshorland** [comment]
P0. broken.

**Comment by Angamanga** [comment]
This can now be tested on http://targetedsurveytesting.v3-qa.ush.zone

**Comment by crcommons** [comment]
@Angamanga could you add a test script, please! thanks!

**Comment by Angamanga** [comment]
@crcommons Yep, checklist added! this is also deployed to production

**Comment by Eve-wanderi** [comment]
@Angamanga                        Got a few issues on this.

1. Duplicate surveys are not visible on the Data mode: Once i duplicate a survey i cannot view this survey on data mode.
2. When i duplicate a survey and try to change the role i get an error message. (See screenshots below) if users cannot change the roles for duplicate surveys could we change the validation message to a more user friendly message?

![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/d944aa3b-58c9-41ce-a24a-eafcaebc5fd3)

**Comment by Angamanga** [comment]
Ohh @Eve-wanderi Did you try to duplicate a targeted-survey by any chance? That should not be possible, we should probably remove the delete/duplicate-button from the survey-list. Good catch. I also think the role-error is connected to targeted surveys :/

**Comment by Eve-wanderi** [comment]
Yes this was a targeted-survey. Let me re-try with a normal survey and see if i will face the same issue.

**Comment by crcommons** [comment]
FYI - I added this issue for removing the functionality to duplicate a targeted survey #2863

**Comment by crcommons** [comment]
Passed QA
