### ISSUE TITLE
Custom headers within a survey

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2488]
Flagging that this would be a nice to have :). 

As a user/deployer, i'd like to be able to segment sections in my survey according to theme etc ( something as simple as a header for the fields that are related to each other. 

See this?

<img width="373" alt="screen shot 2018-02-21 at 11 50 22" src="https://user-images.githubusercontent.com/721918/36470867-6f3167fe-16fd-11e8-851d-4d29294a2529.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-428

**Comment by aoduor** [comment]
Though, wondering if we could use tasks to do this right now... random thought.

**Comment by justinscherer** [comment]
This is 100% usability best practice, especially when forms get very long. 
**but...**
This is really only a viable feature on web-based survey responses, which are far and away the least used way to submit replies to a survey, so I'm going to recommend icing this for now.
