### ISSUE TITLE
Create io deployment for ISOOKO

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#2490]
Please set up a Responder .io deployement for ISOOKO. This should be along the lines of https://comrades.ushahidi.io. We do not need a separate repo just yet, but probably will in the future. For now, however, a responder plan is all we need to begin some basic training and experimentation with the team.

**Comment by jshorland** [comment]
@Shadrock  isooko.ushahidi.io --> do you need any set up done within the deployment itself?
