### ISSUE TITLE
Navigating into a collection somewhat breaks further navigation

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#2492]
### Actual behaviour

From the map view, after navigating into a collection: 
![2018-02-22 11 54 38](https://user-images.githubusercontent.com/467393/36534867-2e2948a0-17c8-11e8-8699-4a5bb6d4b734.gif)

a number of buggy behaviors can be found:

1. Selecting another collection doesn't update the map
![2018-02-22 11 56 02](https://user-images.githubusercontent.com/467393/36534889-44d5dea6-17c8-11e8-82a9-fdd1134830ab.gif)

2. Clicking on "Return to all posts..." doesn't update the map
![2018-02-22 11 57 38](https://user-images.githubusercontent.com/467393/36534911-52022788-17c8-11e8-9a33-28ccddc7e13a.gif)

3. Clicking on "Map" results in an infinite loading bar
![2018-02-22 11 59 00](https://user-images.githubusercontent.com/467393/36534966-751dda00-17c8-11e8-8123-7d80a433a220.gif)

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by crcommons** [comment]
Here's a handy demo of the changes
[Uploading... collections-bug.gif ]

**Comment by crcommons** [comment]
![collections-bug](https://user-images.githubusercontent.com/8941223/36606444-f8ec93e0-1880-11e8-9de0-d22dace72776.gif)
Here's a demo of the changes

**Comment by crcommons** [comment]
This is on pause because there is still a bug that Romina pointed out in her testing. And now I'm sick and haven't been able to continue on it. Will try to add to next cycle and continue when I can.
