### ISSUE TITLE
If a user miss the notification that an export-job is done, there is no way to see it again

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2498]
Adding this here since I thought about it and discussed with @willdoran during developing the notifications for CSV-exports and it might become a problem for the users.

There is currently no way for the users to see the history of their exports and if they miss a notification, there is no way for them to see know that the download is complete.

The same happens if the user logs out and then logs in again and the job is done while the user was logged out. There is no way to get hold of that download right now and the user would have to restart the export again. Could probably be solved through a download-history with the csv-urls listed or something similar?

**Comment by rowasc** [comment]
@Angamanga https://github.com/ushahidi/platform/issues/2582 we implemented and added this ticket, so I'm closing this one . Reopen if needed.
