### ISSUE TITLE
Update plans and pricing model

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2512]
User needs pricing plans that clearly differentiate features.

Final plan moving foward - 12/7: https://docs.google.com/spreadsheets/d/1ReOfNuw2UgLvY5EwfhjNwrprS9HA4R4KaLOClKU66u8/edit#gid=628174120

Update 20180607 - Spec is being updated by Katy and Nat. Juan will update here. This should be done in Q3 2018.

Tentative:
Cycle 6 - Design
Cycle 7 - Development

**Comment by jrtricafort** [comment]
Closing this epic. This has been superceded by this new epic: https://github.com/ushahidi/platform-cloud-interface/issues/318
