### ISSUE TITLE
Add HXL field to Survey Attributes on Survey Creation/Survey Edit

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2515]
### Overview
In order to allow mapping of Ushahidi data to HDX data structure the Platform Survey Attributes entity must support mapping to HXL hashtags.

### Requirements
- [ ] Can set HXL entity mapping for Survey Attribute

Aha! Link: https://ushahiditeam.aha.io/features/PROD-424

**Comment by rowasc** [comment]
@willdoran this is a feature that won't be needed until much later. Right now while we do map of fields to tags, it's not at a global "this field is always this tag" level. 

@caharding is moving to Product Backlog the correct thing here? leaving it up to you
