### ISSUE TITLE
[API] Return available HXL tags and attributes for each survey field

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2516]
### Overview
In order to include the HXL hashtag as part of the output CSV data the Post Exporter must retrieve this field from the database when retrieving Attribute information and make it available when collecting column name data.

### Requirements
- [ ] HXL tashtag field must be retrieved and available to Post Exporter

### Important notes: 
This will be available per export, not as a global field=>hxl_tag=>hxl_attributes configuration

**Comment by rowasc** [comment]
We will need to spec this closer to the start date of CSV downloads with HDX.
Updating HDX API comes first at this point (this might change)

**Comment by jrtricafort** [comment]
@crcommons assigning you since this is Ready for Spec. Let me know if that makes sense?

**Comment by rowasc** [comment]
This is now in #2809.  Closing
