### ISSUE TITLE
Add SMS Beta Feature Flag to API

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2523]
### Overview
The SMS feature will not be available to the entirety of .io, instead it will be feature flag limited to only the DREAMS partner deployments. There are around 15 of these, the full list should be retrieved from the DREAMS PEOs.

Unlike other feature flags which are simple enable/disable toggles this flag will need to understand which deployment it is currently on and whether that deployment is allowed to use the Beta Feature.

We should define this system so that it is resusable and augmentable, it should be possible to edit deployments participation in a Beta feature. We should also define how a feature leaves Beta and what happens(feature flag checks are removed or converted into simple enable/disable toggles).

### Requirements
- [ ] A Beta feature can be defined for all .io
- [ ] A list of deployments that have access to the Beta Feature can be defined and edited
- [ ] The Platform Client and API will take account of whether the feature is enabled or disabled and behave accordingly
- [ ] A beta feature flag can be converted to a standard feature flag
- [ ] The beta feature flag creation/edition can be controlled via a Cloud API endpoint and/or an ansible playbook

### Simple Approach
- [ ] Define new playbook in [Platform Cloud Ansible](https://github.com/ushahidi/platform-cloud-ansible) called Platform-Feature-Manager or extend existing Playbook
- [ ] Define Task to call Platform API feature CLI
- [ ] Define variables describing feature-name and deployments to set flag on
- [ ] Add feature flipper CLI to Platform API
- [ ] Add feature check inside Platform API to check if current Deployment Subdomain is in deployments list. If it is set Targeted Survey feature flag to true else ignore

### Test script

**Comment by rowasc** [comment]
https://docs.google.com/spreadsheets/d/1cxzOJdR58x3EI6hDSCGnay7lPB0S62-MfwNokt3-jRU/edit#gid=1663680881
This list has all the deployments that need to be included, right? 
@dexwakhu 

@willdoran thinking we should add a separate ticket to actually enable the flag so it doesn't get lost?

**Comment by rowasc** [comment]
to discuss: 
> The beta feature flag creation/edition can be controlled via a Cloud API endpoint and/or an ansible playbook
I feel a playbook may be technically better/easier to manage (fewer security concerns, for instance) at the dev level for this kind of thing, but I think also makes it harder if we ever want to provide a way for non-devs to enable beta flags in some deployments.  It's a tradeoff. 
Having an endpoint for it would make it relatively simple to provide a way for the support team, for instance, to manage this without needing to contact a dev for it (ie with a simple postman call), and it'd give us a way to hook it to a mgmt dashboard down the line so anyone internally can use it.  

IDK. The ansible approach is probably best right now but the API endpoint approach might have more benefits later.
