### ISSUE TITLE
Targeted Survey API - (From creation of survey to queueing of messages)

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2531]
### Overview
The Targeted Survey will differ from existing Surveys in a number of crucial ways. 
1. The Targeted Survey will generate or update a set of Contacts based on the recipients specified by the User on Targeted Survey Creation
2. The Targeted Survey will automatically create a Post associated with each of the Contacts to which new inbound messages will be attached
3. Targeted Surveys will generate the first outbound messages, corresponding to the first survey question, upon their creation
4. When a response is received it will cause a Message to be created that is associated with the appropriate Post
5. The next question will be converted into an SMS and sent to the recipient
6. We repeat steps 4 and 5 until all questions have been asked

There is existing data model and API elements for each of these moving parts and we want to limit the number of changes to Surveys. Ideally, the changes we make would be logical extensions to the existing data model rather than rough additions of random fields to entities. 

There is an outstanding question of how a Targeted Survey is "closed" by that I mean, how do I state that the inbound messages from a Contact associated with a Targeted Survey either generate new Posts or are associated with a different Targeted Survey. We will be captured by a concept of a current Targeted Survey to which a Contact can be associated.

Ultimately, Users will be able to select recipients of Targeted Surveys from existing Contacts and Groups so we should build with that expansion in mind.

Outbound SMS will not be sent automatically rather they will be queued in the DB to be sent platform job queue, this is the existing behaviour. We will need to wrap the message sending functionality to allow for multiple messages to be generated at once.

### Requirements
- [ ] Upon creation of a new survey record (aka form, in the database)
   - [x] A set of contact records are upserted, related to this form_id
   - [x] A new set of Post records are inserted, related to this form_id
   - [x] A new set of messages are inserted, related to this form_id and contact_id, and marked as ready for delivery via SMS 
   - [ ] Any set of questions that depend on the first question should be inserted, related to this form_id, to each contact_id, and somehow marked as waiting for a response to the previous message before they can be sent. [@willdoran I think this is no longer valid? ]

### Dependencies 
- [ ] A table for storing targeted survey_ids, contact_ids, (and probably current_field_id), since the only current association between contacts and surveys (i.e. contacts to messages to posts to form_attributes to form_stages to forms) is fragile and unwieldy. (See #2606)

**Comment by willdoran** [comment]
- Post requires Title/Description - auto generate based on some combination of contact and survey name? 
- To restrict submission to forms we can set everyone_can_create to false

**Comment by kinstelli** [comment]
Is there currently a field in the DB that might designate that when each message is waiting for a response to a particular message? I assume this is something that should be added.

**Comment by willdoran** [comment]
@kinstelli Yep we need to add this to go along with the Current Survey Id for the Contact we Should add Current Question ID

**Comment by willdoran** [comment]
- We can look at speccing a state table for contact and survey?

**Comment by rowasc** [comment]
@willdoran When a response is received it will cause a Message to be created that is associated with the appropriate Post
from our chat today this is no longer true, right?
cc @kinstelli

**Comment by rowasc** [comment]
@kinstelli @willdoran 
we should spec the endpoints the client will have to call.
About the survey itself, it's most likely a new endpoint I think? 
q2: should we maybe have a separate endpoint for the contacts? ie : POST /api/v3/forms/:id/contacts that gets the list of contacts separately?

**Comment by willdoran** [comment]
@rowasc No a message would still be created for a new inbound SMS just not a new Post. I believe, unless I have misunderstood completely.

I think we would use the existing survey end point, the only difference is that we set everyone_can_create to false and we need a way to differentiate the surveys, so perhaps a flag?

When would we need to get the list of contacts? I am not against that just not sure why.

**Comment by rowasc** [comment]
>I think we would use the existing survey end point, the only difference is that we set everyone_can_create to false and we need a way to differentiate the surveys, so perhaps a flag?


AH! OK that makes sense. Sorry, I kind of assumed it'd be a new one. 
>When would we need to get the list of contacts? I am not against that just not sure why.

I believe it'd be a second request that's sent when the user hits submit, just to handle it separately iff validation fails maybe? but I'm not sure

**Comment by rowasc** [comment]
dividing in a few different tickets that can be worked on independently. (added as references / dependencies as they are created)

**Comment by rowasc** [comment]
Thinking of the state table or contact / survey/ question. Thinking we need: 
`contact_id`, `question_id` , `status`... where status would start off as "PENDING" then move to "QUEUED" once the job-queue picks it up then "DELIVERED" once it gets sent? 
Then when we receive a response the new entry would be created when the message is created? 
  
@kinstelli @willdoran thoughts?

**Comment by kinstelli** [comment]
@rowasc -- in response to your thoughts on the data table, I realized that message records do have a status (currently 'pending' and 'sent'), which might be fine, except that we might add a few more states for outgoing messages, like `'awaiting reply'` (similar to `sent` but means that there are child questions that depend on this), and `'done'`.

What we might need, however, is a table (called `targeted_survey_questions` here) to store which questions for a targeted survey depend on a response to another question. While I was thinking through the incoming message flow, I had to think about the whole system, and I believe this schema (it's only got relevant fields displayed) might include everything we need.

I copied it into #2532 as well, but please feel free to critique this, or tell me that something doesn't make sense. (But who knows, it's 11pm and I'm drinking caffeine.).

#### Schema
![SMS End-toEnd Processes - DB Schema.png](https://images.zenhubusercontent.com/5a629a264b5806bc2bc37fde/1144e6f5-698c-46c3-8ae8-71c28c543638)

#### Message creation
![SMS End-toEnd Processes - Survey and Message Creation.png](https://images.zenhubusercontent.com/5a629a264b5806bc2bc37fde/bd724b7c-4a2d-472f-bf8f-099122c682ee)

**Comment by rowasc** [comment]
@kinstelli I guess I'm having trouble understanding why we need to mark the dependencies separately, considering there's an existing "priority" field for survey attributes?

**Comment by kinstelli** [comment]
@rowasc - No, you're absolutely right, I don't know why I thought we'd add a table here. Best reason of all to not work when I'm not feeling well. Removed it.
