### ISSUE TITLE
SMS Datasource Inbound Message handling

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2532]
### Overview
Currently when a new SMS arrives at the platform it will generate a Message and Post entity automatically. This leads to confusion when the User is using the "Conversation with author" feature to communicate via SMS as a new Post will be created for each inbound message when the expected behaviour would be that the new SMS are simply appended to the existing conversation.

In future, if a Post already exists and is associated with the inbound message's sender then no new post should be created only a new message which should be associated with the existing Post.

For Targeted Surveys inbound messages that are associated with an existing Contact which is in turn associated with a Targeted Survey should not create a new Post but rather should only create messages that are associated with the existing Post.

As well as associating the Contact with a Survey we must also keep track of the current question they are answering. 

If there are more questions, the next SMS question will be sent once a response has been received..

Inbound messages not associated with an existing contact that is associated with a Targeted Survey should follow the existing pattern of behaviour and create a new Post/Message not connected to an existing Survey unless one has been specified for that datasource.

Contacts will only be associated with one targeted survey at a time, so there will be a concept of a "current" targeted survey for a contact.

### Requirements
- [ ] Message statuses should exist that reflect whether or not they are waiting for a response to a previous Post or message

### Process
- [x] Upon receipt of an SMS message the API is contacted by the SMS provider and given the contact and the message
- [x] The API then should determine if a Post already exists for this contact, based on whether this Contact has an associated Survey and whether a Message/Post already exists for this Contact
- [x] If a Post record does not exist for this contact, then one is created
- [x] A new Message record is created to reference this Post.
- [x] If another question exists that has been awaiting a response from this contact, then this next question should be marked as ready to be delivered.

### Flowchart
![SMS End-toEnd Processes - Receipt of SMS Responses (1).png](https://images.zenhubusercontent.com/5a629a264b5806bc2bc37fde/648af3d7-1e12-4b54-b439-30a2545b60eb)

### Test script [wip]

Test : A new post and message are created if receiving an SMS from a new contact
- [x] Receive an SMS with a contact + message. The contact should not have previous posts for an active targeted  survey
- [x] There should be a new Post created for the contact
- [x] There should be a new Message created and associated with the new post

Test: An SMS from a pre-existing contact (for a survey) does not result in a new post
- [x] Receive an SMS with a contact + message. The contact should have a previous post for an active targeted survey
- [x] There should NOT be a new Post created from the SMS
- [x] There should be a new Message created that references the pre-existing post of the contact

Test: The next survey question is marked as "Ready to be delivered" after receiving a response from a contact 
- [x] Pre requisite: there is another question to send to the contact. 
- [x] Receive an SMS with a contact + message. The contact should have a previous post for an active targeted survey
- [x] There should NOT be a new Post created from the SMS

The details of the message generationg process (generating a new message for the contact and setting it to 'pending') will be handled by ticket #2620

Edge case to test:
- [ ] Someone responds with a long text to each of our SMS providers -- does this create multiple new messages?

**Comment by kinstelli** [comment]
I added some requirements, but they're just a draft. I could stand some review by @willdoran or anyone else at this point.

**Comment by willdoran** [comment]
Not sure diagram is 100% right, made small change to Process, the logic should look at the contact and see if they have Current Survey Id on set and then if there is a Post grab it otherwise it's completely right.

**Comment by rowasc** [comment]
@kinstelli two small comments about diagram: 
- shouldn't "Lookup post" action happen before the "does a post exist matching inbound author" decision? 
- there should be a step to set up the message status, right? 

Other than that, it looks great with the process + test script diagram and should be straightforward to follow it for implementation

**Comment by kinstelli** [comment]
@rowasc Okay, that's easy enough to update -- although now I realize I don't know what the discrete message statuses should be at each stage. Apologies if that is already clear somewhere, but I don't see it in our specs.

**Comment by rowasc** [comment]
no I don't think we have the status names defined. @kinstelli

**Comment by kinstelli** [comment]
updated flowchart image but omitted details of the exact status string until we decide that.

**Comment by kinstelli** [comment]
@willdoran , @rowasc  -- I was trying to think through the statuses of messages from creation to receipt of SMS from the user. I drafted a few updates regarding schema and the flow. Let me know if these make any sense, and please feel free to critique these as necessary.

**Comment by kinstelli** [comment]
@willdoran  - does this seem Ready for Dev?

**Comment by willdoran** [comment]
I think so

**Comment by rowasc** [comment]
@kinstelli I'm ending my day in a bit, can you follow up on SMS testing for this one? thanks!

**Comment by caharding** [comment]
@willdoran Q about this, when a Reporter sends an SMS report (not survey) and then there is a thread of communication between the Deployer and the Reporter about that message, is the current outcome that those messages both appear in the original post messaging thread and creates a new post every time? 

If so this is a nasty bug that we need to find a solution to and we should open a new issue.

**Comment by rowasc** [comment]
@caharding I'm pretending to be Will until Apr 23. 

Current behavior (pre-sms release):
- All messages are shown in a thread when you click a post related to that contact. 
- A new post is created every time a contact sends a message

Expected new behavior (SMS release): 

- All messages are shown in a thread
- When a user sends a message (first time):
---- A new post is created. (example: POST ID=12)
---- A new message is created (example: Message id 1), it references the post we created (post id=12)
- When the same user sends a message:
---- A new message is created (example: Message id 2), it references the initial post (post id=12)

That's related to this part: "In future, if a Post already exists and is associated with the inbound message's sender then no new post should be created only a new message which should be associated with the existing Post." 

#notwill

**Comment by kinstelli** [comment]
@caharding 

Is Issue #2764 meant to be the issue that emerged from the conversation in this ticket? If so, I'd like to close this ticket, which is generally complete, in favor of that ticket which contains a specific bug.

**Comment by caharding** [comment]
Yes closing
