### ISSUE TITLE
SMS Datasource config supports cost per SMS

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2533]
### Overview
In order for the Targeted Survey Creation wizard to correctly calculate the costs of the sending of SMS to the defined recipients we need to have a concept of cost associated with the SMS datasources

Initially, this value will be set by the user when they are configure the data source, however, ultimately we want to intelligently retrieve this information from the datasource depending on which provider(s) the user has defined: nexmo, twillio, frontlinesms etc

Note: it is not clear what currency will be used but the feature should take account of the fact that we will ultimately want to allow the user to define the currency they are working in. For the DREAMS feature we will assume the cost is in USD.

### Requirements
- [ ] Datasource type can store cost value per sms

### Dependencies
- 

### Test script
- [ ] User can set a per SMS cost value in the SMS Datasource configs
- [ ] They can save this value

Aha! Link: https://ushahiditeam.aha.io/features/PROD-421

**Comment by kinstelli** [comment]
Does anyone have strong opinions on where this data should live? 

My guess is that this should be in the `config` table, but I'm not sure if it deserves its own `config_key`, along with a currency, or if we ought to embed it into each data provider's JSON details (since, in theory, this cost might vary per provider), though I assume this is much more complicated.

@rjmackay , @willdoran ??

**Comment by willdoran** [comment]
Yeah, I'm not positive where it should go, it could in the short term not be user set but instead just be in a .env somewhere.

**Comment by rjmackay** [comment]
@kinstelli keeping it in config makes sense. The way we configure data providers need a rework eventually but right now config is the appropriate place

**Comment by kinstelli** [comment]
Per discussion on #2534, I think we're going to avoid estimating costs to the user for now, and instead just provide a general warning about potential costs incurred.
