### ISSUE TITLE
Datasource UI supports SMS cost config

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2534]
### Overview
In order for the Targeted Survey Creation wizard to correctly calculate the costs of the sending of SMS to the defined recipients we need to have a concept of cost associated with the SMS datasources

Initially, this value will be set by the user when they are configure the data source, however, ultimately we want to intelligently retrieve this information from the datasource depending on which on the user has defined nexmo, twillio, frontlinesms etc

Note: it is not clear what currency will be used but the feature should take account of the fact that we will ultimately want to allow the user to define the currency they are working in. For the DREAMS feature we will assume the cost is in USD.

Note II: field needs to be added on the backend before client work can proceed. All fields for each data source are served up from the API.

### Requirements
If the Targeted surveys-feature-flag is turned on...                    
- [ ] User can set a per SMS cost value in the SMS Datasource configs
- [ ] They can save this value
- [ ] Should be required

### Dependencies
- #2533 

### Test script
- If the targeted surveys-flag is turned on:
- [ ] User can set a per SMS cost value in the SMS Datasource configs
- [ ] They can save this value

Aha! Link: https://ushahiditeam.aha.io/features/PROD-420

**Comment by rowasc** [comment]
@willdoran I can't find the design for this. Do we have one?

**Comment by willdoran** [comment]
No there is none

**Comment by rowasc** [comment]
AH, ok thanks

**Comment by rowasc** [comment]
<img width="655" alt="screen shot 2018-02-28 at 6 13 39 pm" src="https://user-images.githubusercontent.com/2434401/36813385-245bee0a-1cb3-11e8-9d5f-c5c0acf7b8cf.png">

@justinscherer @Erioldoesdesign can you LMK if the field would be set like this, or if the order of the fields should be different? also, if you have suggestions for the label and description of the SMS cost field that'd be great. 

Thanks

**Comment by justinscherer** [comment]
@rowasc 

> "can you LMK if the field would be set like this, or if the order of the fields should be different? "

I'm not sure if I understand your question.

**Comment by rowasc** [comment]
@justinscherer sorry, rephrasing. 
- Where should the SMS Cost field be placed? (for example, should it be the last field in the form?)
- What's the text that we need to use for the placeholder, label, and description of the field?

**Comment by willdoran** [comment]
- Note also that we may need to take account of the staleness of the cost? When was it last updated?

**Comment by willdoran** [comment]
- Should be required?

**Comment by willdoran** [comment]
Should be required, we with note staleness for future changes.

**Comment by justinscherer** [comment]
I really don't like that the user has too input the SMS cost. Where would they find that information. 

Is there another way to derive a conservative estimate of cost? Can be a tiny bit vague like: "This may cost up to $XX.XX?"

**Comment by Angamanga** [comment]
There is a stub for this in the Targeted survey, but the actual field needs to be added to the datasources in client.

**Comment by kinstelli** [comment]
@rowasc @Angamanga @crcommons @justinscherer @willdoran 

Does anyone have concerns about just hardcoding the SMS cost for the primary customer and pushing this to a lower priority (and potentially to a future cycle) -- at least until we decide how much control we want to users to have over this information?

**Comment by justinscherer** [comment]
> "Does anyone have concerns about just hardcoding the SMS cost for the primary customer and pushing this to a lower priority (and potentially to a future cycle) -- at least until we decide how much control we want to users to have over this information?"

We could hardcode something like this for now: "We will send `(numquestions)` questions to `(numrecipients)` people via SMS for a total of `(numquestions * numrecipients)` messages. your telecommunications provider will charge you for each message. Please be careful about the costs you will incur by sending this survey. This action cannot be undone.

**Comment by Angamanga** [comment]
@kinstelli I agree with @justinscherers option. A plus there is that way don't make any estimates based on the users input that later could turn out wrong with the result that the actual cost would be much higher than what we present...

**Comment by kinstelli** [comment]
Ooops, I think my cough suppressant was controlling my mind when I wrote that. Sorry. I didn't really mean hardcoding -- I meant that we'd just include this as a deployment configuration on the backend, but not provide a way for them to change it in the UI, at least not yet.

That said, I do like this approach better. Can we consider this postponed until future UX research is done, and I'll add a ticket that includes something like the text you've provided?
@justinscherer

**Comment by justinscherer** [comment]
> "Can we consider this postponed until future UX research is done, and I'll add a ticket that includes something like the text you've provided?"

^^ What warning will we be showing in this case?

**Comment by crcommons** [comment]
@kinstelli Wondering about this too. Right now we just have "This could cost up to USD $." and am not sure what amount or calculation to put in.

**Comment by kinstelli** [comment]
@justinscherer, @crcommons - 

In hindsight, I like Justin's suggestion better than taking on the liability of SMS costs, especially since the model of pricing might not always be a constant cost per SMS message.
Should we stick with something like the following?

---
"We will send (numquestions) questions to (numrecipients) people via SMS for a total of (numquestions * numrecipients) messages. your telecommunications provider will charge you for each message. Please be careful about the costs you will incur by sending this survey. This action cannot be undone."

**Comment by justinscherer** [comment]
Looks good. Thanks all.
