### ISSUE TITLE
SMS Datasources Outbound Message handling

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2535]
### Overview
We will need to provide a means to generate many outbound messages at once upon Targeted Survey creation for the first question. And then for subsequent question until all questions have been asked. This will need to wrap the current datasource send functionality.

This specification picks up where #2531 leaves off -- messages have been created, but they need to be picked up by a queue and forwarded to the SMS provider in question.

### Requirements
- [ ] A process needs to pick up all messages from the database
- [ ] Ensure that outbound messages are in a format that the SMS provider can accept

Phone numbers should be validated. See #2595

### Test script - (backend only)

 Check that the correct messages are set to be delivered to contacts
- [x] In Platform DB, set several messages to 'outbound', complete with message content, contact_id.
- [x] Initiate the task worker, ensure that these are picked up and ready to be delivered
- [x] Ensure that only messages that have been set to 'outbound' are picked up
- [x] Ensure that only messages with valid contents are collected to be sent

**Comment by rowasc** [comment]
is this basically using the queue system for sending all the SMSs to the phone numbers the user selected?

**Comment by willdoran** [comment]
@rowasc Not quite the existing queue will handle the sending, that aspect is already setup and works. We need to figure out how we're going to run a process that creates potentially thousands of new Messages + Posts in one go.

**Comment by kinstelli** [comment]
Is there a process in place for marking messages like this as 'failed to be sent', if there are errors?

**Comment by willdoran** [comment]
@kinstelli                         Yes, the data provider will mark them as such depending on the response from the External system, however, there is more than one system between us and the message getting anywhere so it can pass the first stage and still fail and we won't know. But for your question, yes, yes there is.

**Comment by kinstelli** [comment]
I'm trying to think through what else we need to close this out, and I realize I'm stuck on the following open questions. Tagging @willdoran (who might have the most insights into this, though maybe not the time to answer):

1. Which parts of these requirements already exist? Does the platform-job-queue already interface with a SMS provider?
2. How do we know which SMS provider will be responsible for sending what messages? Are we able to (or should we be able to) direct different messages to different providers, based on various parameters? 
3. Are there different data or data format requirements for each of these providers?
4. Does this introduce scaling issues that we don't currently handle?

**Comment by kinstelli** [comment]
@willdoran   - I realize we're probably missing a step here: 

This process should also send an update back to platform to mark it as 'sent'.
Does that currently happen, or do we need to add this? 

And if it doesn't, then I'm not sure the platform API has a way to receive these updates. That might need to be an added ticket.

**Comment by willdoran** [comment]
@kinstelli Yes, but we're going to load test it today to make sure and identify any issues that might crop up and mitigate, I'll up date the ticket after the tests!

**Comment by kinstelli** [comment]
@willdoran - Can I close this? I think we've done as much testing as we can.
