### ISSUE TITLE
Related Posts Buttons Have No Icons or Labels

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#2538]
### Expected behaviour
For the Related Post control, the add button would have a `+` icon or `Add` label and the remove button would have a `X` icon or `Remove` label, so users know what each button does.

### Actual behaviour
Neither the add or remove buttons have any kind of icon or labels, so it's really confusing what either of them actually do.

### Steps to reproduce the behaviour/error
![screenshot 2018-02-27 15 04 53_preview](https://user-images.githubusercontent.com/91811/36757105-50e0c7b2-1bd6-11e8-8f19-629eed752754.png)

#### Is is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [X] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-418

**Comment by Angamanga** [comment]
@justinscherer @Erioldoesdesign There is no designs for this but would something like this work?

 ![Screen Shot 2018-04-09 at 10.39.24.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/e5266ecf-21bb-4898-b792-5d1bad485bb0)

![Screen Shot 2018-04-09 at 10.39.18.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/6a27f1cd-0fb2-40af-8d58-4adef94d7038)

**Comment by justinscherer** [comment]
@Angamanga 
> "There is no designs for this but would something like this work?"

Can we re-use a searchbox module from elsewhere in the platform?

**Comment by Angamanga** [comment]
@justinscherer Like the filter-search-dropdown? I think thats the only one we got? Or the box with a dropdown in the location-picker

**Comment by justinscherer** [comment]
> "Like the filter-search-dropdown?"

^^ would that work?

**Comment by caharding** [comment]
@justinscherer something worth fixing or wait till UI refresh?

**Comment by rowasc** [comment]
@Angamanga  @justinscherer thinking of flagging this for google code in. Is it something we would want to do with the image Anna posted to keep it simple? 
The other search boxes (filters dropdown, location selection)  don't have the "Add" behavior or show a list right after them :/

**Comment by Angamanga** [comment]
@rowasc The location-picker does though, but it would require more work than "just" adding the + signs as in my image.
