### ISSUE TITLE
Methodology of Migration: JS Framework

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2540]
- [ ] Complete a deliverable doc: https://docs.google.com/document/d/1ZlbHMZtxzkruo2IzMyBsHNSenqeIibrT8G0UccmYBfU/edit
 - which answers the following questions: 
   - What is the best process to migrate the app to React? (e.g. side-by-side independent apps; running react/angular together and moving piece by piece)
   - At a high level, how will we do this migration? (roadmap/plan)

**Comment by kinstelli** [comment]
I'm starting to collect my notes here, in case anyone wants to share their notes here. 
I'm hoping to keep this as skimmable as possible, in outline form, and with only a few comments.

https://docs.google.com/document/d/17OGHVoNDKMdU0i9pL0iqpXz8Z9_8T7QJBbO_tq2EDFo/edit?usp=sharing

**Comment by Angamanga** [comment]
@kinstelli @rjmackay I started preparing a deliverable-doc here: https://docs.google.com/document/d/1m_cUxvZ1Cdqoo6dCVEr-ZjjA7-1HlXe-RHWI7zerFCs/edit

**Comment by rjmackay** [comment]
- So I did a quick build with preact + https://github.com/coatue-oss/react2angular + a single react component running inside angular.
    - Code is here https://github.com/ushahidi/platform-client/compare/develop...experiment/react-angular
    - It adds maybe 200k raw, but only 20k once uglified... if that.
    - *Conclusion*: running react inside angular is a really minimal hit to page weight.

- I also looked at https://github.com/coatue-oss/react2angular and https://github.com/bcherny/ngimport
    - Once we get to a tipping point of react implementation, we could plausibly rewrite our core (routes, state, etc) in react/agnostic JS and then use react2angular to mount the remaining angular routes into react, instead of the reverse.
    - We should look at using ngimport to break free from the angular DI layer soon rather than later

Aside: we should really investigate lazy loading some modules within angular to reduce the page weight anyway.

**Comment by rjmackay** [comment]
I also ran a visualizer over our routes as a quick answer to 'What are our top level components?'

<img width="1213" alt="screenshot 2018-04-06 12 14 32" src="https://user-images.githubusercontent.com/7965/38401750-bc0de5cc-39ab-11e8-9761-303e55933834.png">
 
As discussed:
- Settings views are standalone, along with a few others: activity, login, register
- Map and Data are sort of separate 
    - But Map redirect to data view for post edit/edit/etc

Grudging conclusion: It'll probably be hard to split of anything other than settings into a separate app.

We *should* be lazy loading all of settings to reduce the page weight, but thats unrelated to how we migrate frameworks.
