### ISSUE TITLE
Enable the SMS feature-flag in DREAMS deployments 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2542]
After doing the actual work of creating the feature flag and releasing we need to enable it in the deployments to be used. 

https://docs.google.com/spreadsheets/d/1cxzOJdR58x3EI6hDSCGnay7lPB0S62-MfwNokt3-jRU/edit#gid=1663680881

External dependency (doc) added because it's not confirmed. 

Test script: 
- For each deployment in the list, check that the SMS Enhancements feature flag is enabled.

**Comment by kinstelli** [comment]
@willdoran @rowasc - I'm assuming this is complete, right?
For now I moved this to cycle 3, but I believe we had to have done this before deployment, I just wanted to double check there's not a missing piece not documented here.

**Comment by caharding** [comment]
@rowasc can you confirm this is complete?
