### ISSUE TITLE
Redundant/confusing fields in email data source setup

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2552]
### Expected behaviour
There should only be necessary/required fields in email data source setup and docs should match; 

### Actual behaviour
Platform includes:
- Outgoing user name
- Outgoing password
- Email sender name
- Outgoing Username

But the docs only describe 3 of those:
- Outgoing user name: Enter the email address you want to use to send emails. E.g sample@youremail.com
- Outgoing password: Enter the password of the email account inserted above.
- Email sender name: This is what appears in the “from” field in outgoing emails.

We either need to remove one of the required fields or clarify what it means, because I don't understand it at all!

### Steps to reproduce the behaviour/error
See docs: https://www.ushahidi.com/support/data-sources
And see fields when you go to settings/datasources and scroll to the bottom

#### Is is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [x] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
@aoduor this is good to keep in mind for our user-facing docs for dial :D  I was also kind of confused the first time I setup email tbh

**Comment by StaicyG** [comment]
@rowasc @aoduor I am a bit confused, what exactly should we be documenting here? Am sorry I don't have context to the situation around this documentation task

**Comment by rowasc** [comment]
@StaicyG we need to document the specific details of how a datasource is setup in platform , and what they do

**Comment by aoduor** [comment]
making a note to sync w/ @StaicyG on this.

**Comment by aoduor** [comment]
Noticing that we got rid of outgoing email set up, so what @StaicyG will do in this case, is edit our email docs, and remove any references to outgoing email set up cc @rowasc

**Comment by aoduor** [comment]
ping @StaicyG based on our catch up, we good to close this yet?

**Comment by StaicyG** [comment]
It's done. Just need to upload the changes on the live doc to update.
