### ISSUE TITLE
Setting the "Post date" on edit has no effect

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#2559]
### Expected behaviour
Editing the post date should persist

### Actual behaviour
Editing the post date doesn't persist

![2018-03-02 13 30 36](https://user-images.githubusercontent.com/467393/36899177-3a39a9ee-1e1e-11e8-8f0a-85dd0d7cbbcc.gif)

#### Is is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

#### Test checklist
- Go to any post and click on 'edit'
- select a new post-date in the date-box in edit-mode
- save
- [ ] New date should be reflected in the post-metadata-header above the title, both on the post, in the post-list and in the post-popup in the map

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by tuxpiper** [comment]
@caharding could we add this to the next cycle?

**Comment by Celestine22** [comment]
@caharding @tuxpiper when is the expected release date for this? our customer would need this bug fixed and I need a timeline to feedback with.

**Comment by caharding** [comment]
Devs are tackling this bug next, hopefully early this week

**Comment by Celestine22** [comment]
Thanks @caharding

**Comment by Celestine22** [comment]
@Angamanga @tuxpiper when should I test for this? I will update our customer after that. Please let me know, thanks.

**Comment by tuxpiper** [comment]
I haven't seen any pull request relative to this, so I don't think anything got deployed yet @Celestine22

**Comment by Angamanga** [comment]
@tuxpiper @Celestine22 Its in review, not merged or deployed yet.

**Comment by Celestine22** [comment]
@kinstelli this is closed but has not been deployed. I would need to test this before we close it, so I'll re-open it for easy tracking.

**Comment by Angamanga** [comment]
@Celestine22 This can be tested on http://targetedsurveytesting.v3-qa.ush.zone now

**Comment by crcommons** [comment]
@Angamanga What's the status of this ticket? Has it been deployed to production or is it still in QA  or QA backlog?

**Comment by tuxpiper** [comment]
@crcommons  Looks like the x-ref ticket https://github.com/ushahidi/account-management/issues/12 was closed satisfactorily . I think this can be closed

**Comment by Angamanga** [comment]
@crcommons This is deployed to production. Added test-checklist ✅

**Comment by Eve-wanderi** [comment]
Tested this on http://targetedsurveytesting.v3-qa.ush.zone/posts/613 and can confirm this now works as expected.
