### ISSUE TITLE
Provide API endpoints for count of responses and total recipients for each survey

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2561]
[screen_shot_2018-03-05_at_3.36.21_pm_1024.png](https://images.zenhubusercontent.com/5a629a264b5806bc2bc37fde/51a04d92-5ed2-478c-b6f8-fa7dd1b3f602)

Per @justinscherer 's design shown here, the API should provide a count of
- total number of incoming SMS messages for all reports/questions(?) in the survey 

In order to provide user a quick glance of how many respondents have replied to any questions from the survey.

### Requirements:
- [ ] API provide an endpoint that returns a count for a targeted survey of:
- [ ] Total number of recipients for a survey
- [ ] Total number of responses to a survey

- [ ] This response should be consumable by the client

@justinscherer  This does not differentiate between number of responses to a particular question, correct?

**Comment by justinscherer** [comment]
> "This does not differentiate between number of responses to a particular question, correct?"

^^ Yep, correct.

**Comment by rowasc** [comment]
@crcommons  I'm stealing this from Mark so you can work on it. I'll be pairing and helping you out as needed .

**Comment by rowasc** [comment]
Merged in cycle2-sms-api

**Comment by rowasc** [comment]
@crcommons same as other API tasks. Do you think I should keep them until client passes?
