### ISSUE TITLE
Provide a count of recipients and responses on the Targeted Survey details screen, after the survey has been published

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2562]
*WAITING TO FIGURE OUT WHAT WE WILL RETURN FROM API TO DETERMINE HOW WE DISPLAY DATA*

if we can't return stats per question, we will adjust to something like in issue #2681

In order to provide easy reporting for survey admins, we will create a display of the current count of messages sent for each survey question and the total number of responses. When a user clicks on a targeted survey on the survey-list, a summary + number of messages sent/replies received should be shown (Note design is out of date)

#### Requirements
- [x] Within the Targeted Survey window, we display:
- [x] A list of each question number followed by N messages are being processed. N messages have been sent. N responses have been received. 
- [x] When clicking on a targeted-survey in the survey list, above view is displayed

#### Test script
- [x] Deploy a survey with a known count of recipients, including at least one test number
- [x] Once deployed, view the sent survey; the survey should display the count of pending messages as 1
- [ ] An SMS should be received by this test number
- [ ] Refresh the sent survey view; Once the message has been received, the count of pending should be 0 and sent should be 1
- [ ] Send a response to a associated survey SMS
- [ ] Refresh the sent survey view; Once a response is sent, the count of pending should be 1, sent should be 1 and received should be 1

**Comment by willdoran** [comment]
This looks good, I think it can go to ready for dev

**Comment by Angamanga** [comment]
waiting for API to be able to:
- differentiate targeted survey and 'normal survey' when clicking in the survey-list
- get the stats for sent sms'es and responses

**Comment by Angamanga** [comment]
Left to do after api is done: Add the real count of recipients and responses

**Comment by crcommons** [comment]
Closed #2681 in favor of this issue

**Comment by Eve-wanderi** [comment]
Confirmed Fix.

![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/8d773548-07a4-4730-9afa-6054f5da529e)
