### ISSUE TITLE
How to check for feature-flag in client

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2564]
### Overview
This is a documentation-issue for how to check the feature-flag for targeted surveys:

To check if the feature-flag for targeted surveys is enabled, do like this:

1. import Features-service to the directive/controller
2. Add the function ```Features.loadFeatures().then(function () {
                $scope.targetedSurveysEnabled = Features.isFeatureEnabled('targeted-surveys');
            });```
3. Add the check in the html: `ng-show="targetedSurveysEnabled"`

NOTE: The name of the feature-flag might change while working with 

### Requirements
- [ ] Ensure that Targeted Survey link is only visible when feature flag returned from API is enabled
- [ ] Ensure that Targeted Survey route is inaccessible when the feature flag is disabled.

### Dependencies
- #2523
- #2525 

Test Script:
- [x] Test script for #2525 passes.

**Comment by kinstelli** [comment]
Closing this, as test script for #2525 passes, and 2525 is also closed and deployed.
