### ISSUE TITLE
Add drag/drop-functionality to PL and client

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2565]
In the new targeted survey-wizard, we need drag/drop functionality for changing order for the questions, (designs here: https://xd.adobe.com/view/a9b0da01-2589-465d-ab05-db3a178d6a6f/screen/11ae2c63-c67b-45db-b21e-8254fa572a78/New-Survey-choose-audience-targeted-2-questions-ad/?fullscreen). 

TODO:
- Find suitable drag/drop-library for PL/client
- Implement it in PL/client

**Comment by middle8media** [comment]
@Angamanga https://github.com/ushahidi/platform-pattern-library/tree/f-drag-and-drop under Fragments/Other
