### ISSUE TITLE
reroute targeted survey page if feature flag is not enabled

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2567]
### Requirements 
- When feature flag is enabled, visiting /settings/surveys/targeted-survey/create should work 
- When disabled, /settings/surveys/targeted-survey/create should reroute to settings/surveys/create
- add test for this
### Test Script
- [x] user can visit target survey create page directly e.g. localhost:3000/settings/surveys/targeted-survey/create and not be redirected when feature flag is enabled
- [ ] user cannot access page directly or through platform if feature flag is disabled

**Comment by Angamanga** [comment]
This is stubbed out in the UI but needs the real flag to be working + change the stub to actual check for flag.

**Comment by kinstelli** [comment]
@Angamanga , @crcommons - this is implemented, correct?

**Comment by crcommons** [comment]
@kinstelli It actually just reroutes to map view, which is totally fine. I just didn't want it to 404 or something like that.
