### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2569]
USERS
- User wants to be able to see all the other users in their org
- User wants to be able add new users to their org
- User wants to be able to limit access to certain data in their org
- User wants to be able to see all issues authored by another person in their org
- User wants to be able to see all assignments to people in their org

Justin described a new user model in the SMS Surveys Scope: https://docs.google.com/document/d/1uUkSG0NsoDTxIkKfmVG6oSX5u1rVOVvAuOoY_E0VaTQ/edit# #2419

**Comment by rowasc** [comment]
Closing this in favor of the higher level epic https://github.com/ushahidi/platform/issues/2283
