### ISSUE TITLE
Messaging: Close The Feedback Loop

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2570]
MOONSHOT GLOBAL recommended the next step in our software should be that we implement report back tools that allow deployers to speak with their beneficiaries. Example: after an earthquake a responded needs to be able to ask Qs of a person who submitted a report for help to coordinate logistics and support services. 

CURRENT STATE: 
- we would like to be able to have both post creation via SMS and messaging over SMS and need a solution, but today they are tied together, creating lots of strange problems
- When a user sends an SMS it both creates a post and a threaded message on other posts. We need to fix this. 
- the problem is that our user model #2569 and messaging #2570 is really a hack and we've opened issues for to address both 

FUTURE STATE:
USER = DEPLOYER 
- SMS can be used as a method of capturing a post and/or replying to deployer about an existing post. This is probably handled by having different phone numbers for each message. 
- User wants to be able to communicate back to someone who has filled in a survey
- User wants to see a list of ongoing communications with a Contact
- User wants an inbox of all messages that allows them to see all things pending
- User wants to be able to archive / close messages 
- User wants to be able to re-open messages

This issue is expanded upon in the SMS Surveys EPIC: https://docs.google.com/document/d/1uUkSG0NsoDTxIkKfmVG6oSX5u1rVOVvAuOoY_E0VaTQ/edit#

Aha! Link: https://ushahiditeam.aha.io/features/PROD-412

**Comment by rowasc** [comment]
> SMS can be used as a method of capturing a post and/or replying to deployer about an existing post
@willdoran could we solve this with a different message type that is not added to a post automatically + adding post/thread_id as a param somehow when we send and receive messages? 
@caharding 
 >User wants an inbox of all messages that allows them to see all things pending
I think this idea is great. It needs to be fully spec'd and I don't have the answer for "how do we accomplish this" right now. It would be a different way of handling messages than what we have now. Some messages would be linked to posts and some would be in a different sort of thread maybe, with the option to upgrade them to posts? 
>User wants to be able to re-open messages
What would they accomplish with this? Is this a way to reopen a thread of messages to continue the communication with a person in an organized way?
>User wants to be able to archive / close messages
This would be for threads of messages too, right?

**Comment by caharding** [comment]
All good questions, will return to them when scope later in the quarter.

**Comment by willdoran** [comment]
@rowasc 
> > SMS can be used as a method of capturing a post and/or replying to deployer about an existing post

> @willdoran could we solve this with a different message type that is not added to a post automatically + adding post/thread_id as a param somehow when we send and receive messages? 
 
Not totally sure I follow, what is the usecase/flow?
