### ISSUE TITLE
FB Bot Research

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2573]

**Comment by Shadrock** [comment]
This is a place-holder issue to hold 10% time for @Angamanga to continue with some FB bot research during the April and early May cycle [as outlined in the roadmap](https://docs.google.com/spreadsheets/d/1eMB83Dp-iC5aQNP4MykFAA0ekEHKKcvPunfJeHKXlbQ/edit#gid=1205873777). This will be largely research, writing possible scripts for the bot, and documentation work. There will be relatively little coding: but we wanted to be sure and preserve the time!

**Comment by Shadrock** [comment]
Quick note that the initial paper that @Angamanga and I wrote with our colleagues Lara has been submitted to the first [Conference on Computing and Sustainable Societies](https://acmcompass.org/). Should have an answer on acceptance soon.

**Comment by Shadrock** [comment]
It looks like this cycle will likely be scoping for the next or the one after.

**Comment by caharding** [comment]
@Shadrock can you clarify if there when you mean scoping for the next, does that mean next cycle will require coding of new elements of the bot? We should open an issue if there is eng work beyon d research that we will need to do.

**Comment by Shadrock** [comment]
I'm closing this issue. There may be a bit of additional research time around chat bots for COMRADES but there will not be any further coding on the bot and, at this time, no research time is needed.
