### ISSUE TITLE
JS Framework Rewrite (Carolyn lead)

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2574]
This is the epic to link together all of the work and issues relating to the rewrite from Angular to React.

**Comment by caharding** [comment]
Adding this work all to spec in current Cycle. That OK?

**Comment by rowasc** [comment]
Closing as nothing is linked here .  Tagging with the rewrite label so we find the issues easily https://github.com/ushahidi/platform/labels/Theme%3A%20JS%20Framework%20rewrite
