### ISSUE TITLE
Verify Replacement libraries for 1st component

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2577]
## Requirements
Each package/library used in angular component should be mapped to a new react package/library

## Definition of done
- [ ] Table of existing package and libraries used in existing angular component
- [ ] Corresponding React-compatible library identified

**Comment by crcommons** [comment]
@crcommons  @kinstelli Tagging you here solely because you had originally signed up for this one and want to keep a record. You don't need to reassign yourself.

**Comment by kinstelli** [comment]
Started a doc here, fwiw. https://docs.google.com/document/d/1VB8mi8vwryPu_KKBWqNG3hBK3pSnUgt2zJBBin8Ls7E/edit?usp=sharing

**Comment by crcommons** [comment]
Note to address RTL and i18N

**Comment by crcommons** [comment]
Only two packages to migrate for this component:

https://docs.google.com/spreadsheets/d/1Lz8-qCb89EOdYsXKWlwW0tSeujCy5d5558vvdP_riJM/edit?usp=sharing
