### ISSUE TITLE
Integrate Accessibility

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2578]
- Accessibility adjusted html-templates should come from the PL
- We potentially need to do some focus-managing in the client, find out where that is needed, which components etc

**Comment by crcommons** [comment]
@Angamanga Tagging you here solely because you had originally signed up for this one and want to keep a record. You don't need to reassign yourself.

**Comment by rowasc** [comment]
Closing as duplicate of https://github.com/ushahidi/platform/issues/2506
