### ISSUE TITLE
Terms of service dialog styling broken

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2583]
### Expected behaviour
- The dialog appears in the form expect

### Actual behaviour
- The dialog looks like this at the moment
![Screen Shot 2018-03-09 at 14.18.32.png](https://images.zenhubusercontent.com/5a6a44264b5806bc2bc4546d/81af31ce-5fb3-41a4-a3a7-d84bbf1cbf07)

### Steps to reproduce the behaviour/error
- Sign up to a deployment on qa 
- Login
- You will see the dialog

#### Is is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rjmackay** [comment]
@willdoran I've deployed. Can you verify this deployed correctly?
