### ISSUE TITLE
Unlock Post not correctly checking perms on logout

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2585]
### Expected behaviour
- [ ] Only users that have permission to lock posts should unlock posts on logout

### Actual behaviour
- [ ] All users are trying to unlock posts irrespective of perm level

### Steps to reproduce the behaviour/error
- [ ] Signup as a new user
- [ ] Login
- [ ] Open Console
- [ ] Logout, you will see errors in Console and you will be redirected to the access denied page

#### Is is ready for development when
- [x] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [x] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [x] Has all designs and UI assets available
- [x] Has all (probable) dependencies identified
- [x] Is estimated by the team
- [x] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [x] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rjmackay** [comment]
@willdoran I've deployed. Can you verify this deployed correctly?
