### ISSUE TITLE
Create component map for 1st migrated component

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2587]
## Requirements
Create a visual map/tree of components relating to first to-be-migrated component to React. Components should be represented by nodes in tree and connect to related parents/sibling/child components at least by 1 level. It's not necessary to map all components in a whole sections, just components nearby.

## Definition of done
- [ ] Visual component tree completed
- [ ] Parent, sibling, and child components should be included
- [ ] Feedback solicited
- [ ] Feedback integrated

**Comment by crcommons** [comment]
@kinstelli @crcommons Tagging you here solely because you had originally signed up for this one and want to keep a record. You don't need to reassign yourself.

**Comment by rowasc** [comment]
@crcommons this would be Done, right?
