### ISSUE TITLE
10/4 Migration Roadmap

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2588]
- Sync with 10/4 about how we can interweave our migration so that it is of benefit to them
- This will also involve discussion of react switch

**Comment by crcommons** [comment]
@willdoran Tagging you here solely because you had originally signed up for this one and want to keep a record. You don't need to reassign yourself.

**Comment by caharding** [comment]
Who wants to lead this convo my next TenFour call Wed at 730am PST? @crcommons @willdoran

**Comment by crcommons** [comment]
We gave David and Linda a heads up about what we're working on already. They're good for now. We want to hold off on this conversation until we have more to share, in cycle 4 @caharding

**Comment by caharding** [comment]
Great, will punt till then

**Comment by crcommons** [comment]
Closing this issue because 10/4 is migrating to ionic.
