### ISSUE TITLE
Survey API - Contacts validation 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2595]
- [ ] Get rules from sms providers 
- [ ] Sanitize the phone numbers before saving to Contacts or sending to SMS provider
- [ ] Ensure that all numbers are valid numbers for the survey country - https://github.com/giggsey/libphonenumber-for-php should check for validity of number by country. We are also doing this on the frontend.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-410

**Comment by rowasc** [comment]
@crcommons as discussed this was removed as validation will happen on the client to avoid multiple unnecessary queries, but I'd like to keep it in the backlog to be able to figure out a workaround at some point if we want it. I'm not sure but is flagging as Follow up correct here?

**Comment by crcommons** [comment]
@rowasc Right, thank you!
