### ISSUE TITLE
Forgot password link doesn't work in private deployments

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#2608]
### Expected behaviour
- In a private deployment
- when I request for a password reset
- and I receive an email with the details
- when I click the link in the email
- I should be taken to the password reset form

### Actual behaviour
- I am taken to the login form

![2018-03-20 12 40 13](https://user-images.githubusercontent.com/467393/37652503-09b09d4c-2c3c-11e8-8bec-646d3ec4861f.gif)

### Steps to reproduce the behaviour/error
1. Create deployment
2. Configure it to set it private
3. Ask password reset
4. Click link found in email

#### Is is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [x] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by tuxpiper** [comment]
This affects a deployment that we've done for a client

**Comment by jrtricafort** [comment]
Checked in with @tuxpiper and @Celestine22 . This appears to not be an issue anymore, and we do not know which deployment originally reported this to double check. Closing this for now unless more information surfaces.
