### ISSUE TITLE
Walkthrough lumen branch with devs

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2610]
Walkthrough lumen branch with devs and record walkthrough.

**Comment by caharding** [comment]
@rjmackay do we have a meeting set up for this walkthrough?

**Comment by caharding** [comment]
@rjmackay is this complete or scheduled?

**Comment by rjmackay** [comment]
Done. Here's the video https://www.dropbox.com/s/nc89bjpnc6ozj0u/lumen-walkthrough.mp4?dl=0
