### ISSUE TITLE
Perform an accessibility-audit

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2611]
Perform an accessibility audit of Platform-client to get an idea what needs to be adjusted to reach the accessibility-standards (https://www.wuhcag.com/wcag-checklist/). Either ourselves or with the help of a tool (for example SiteImprove) or a consultant (if budget exists)

Steps:
1. Can we make it ourselves?
2. If not, find tool or consultant
2. If so, go through the checklist and perform the audit
3. Add findings as issues

Time estimate: 10 % of total time for @Angamanga and @middle8media

**Comment by middle8media** [comment]
My vote is to work with a consultant. I had an initial consultation with SiteImprove (a cloud based accessibility product) where they walked through their product dashboard. I took notes and they are sending a product demonstration video as well. I can do a deep dive when the time comes, but I think SiteImprove has huge value to our products and organization. It will help us meet accessibility standards in a thorough and efficient manner.

**Comment by Angamanga** [comment]
@middle8media Thanks! Do you have any idea about the cost? @caharding do we have budget for this? It would increase the chances of delivering accessible html-templates in time for the js-migration.

**Comment by middle8media** [comment]
@Angamanga I am writing up notes and details to present to @caharding. Will keep everyone posted.

**Comment by caharding** [comment]
@middle8media can we close this issue?

**Comment by Angamanga** [comment]
@caharding yes, closing it.
