### ISSUE TITLE
Lexer Error: Unexpected next character at columns 0-0 [ش] in expression [شكل]

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2621]
### Expected behaviour
No errors when changing languages

### Actual behaviour
Lots of lexer errors. This is caused because translators have translated the variable names within the translations. ie.
`Hide {{form}}` has been translated to `إخفاء{{شكل}}` rather than leave the variable as is: `إخفاء{{form}}`

#### Is is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-407

**Comment by rowasc** [comment]
This needs to be validated to verify it's still happening.
