### ISSUE TITLE
The old Post Detail/Edit views should be expunged from the code base

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2622]
### Overview

These views are redundant and should be refactored out.

### Dependencies
- The initial Post creation code is dependent on this view but should be refactored
- Legacy deployments use these views so we should create an internal redirect to capture that
http://abaaraha.org/urgent-needs-baahida/

#### Is is ready for development when
- [x] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [x] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [x] Has all designs and UI assets available
- [x] Has all (probable) dependencies identified
- [x] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [x] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by willdoran** [comment]
Legacy users need this code :(

**Comment by rowasc** [comment]
The single view is no longer available in the codebase. Closing
