### ISSUE TITLE
Formatting of error messages broken on Post Edit views

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2623]
### Expected behaviour
- Errors display correctly beneath fields

### Actual behaviour
- Errors cause Labels of subsequent fields to move 
<img width="1118" alt="screen shot 2018-03-23 at 13 44 55" src="https://user-images.githubusercontent.com/2694405/37845314-8dfd9648-2ea0-11e8-8d88-8e7899de9dd2.png">

### Steps to reproduce the behaviour/error
- Create a new Post
- Enter a single character for the title and click on the next field

#### Is is ready for development when
- [x] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [x] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [x] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [x] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by caharding** [comment]
@justinscherer can you provide a design recommendation solution. I suggest either: 
a) append spacing to accommodate error
b) place error to the right of the fields

**Comment by justinscherer** [comment]
> a) append spacing to accommodate error

 ^This is the correct solution [per the PL](http://preview.ushahidi.com/platform-pattern-library/master/assets/html/2_fragments/). We're missing the vertical spacing between fields. 

Assigning Seth to look at this.

**Comment by middle8media** [comment]
This is fixed.

http://localhost:8000/assets/html/4_blocks/#pl-pattern-survey
