### ISSUE TITLE
Perform css-performance-audit 

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2627]
Perform a css-performance audit to identify areas where we lack and could improve.
#Todo#
1. Make a first audit with lighthouse on production-build to get first idea of where we lack and what selectors are not used. Evaluate results.
2. Is all css needed everywhere? (no its not), identify which parts can be divided and loaded later on when users enter that part (for example settings/data-view and so on
3. Also, make a test with purify to identify unused selectors (could it be useful for us? Don't know yet) https://github.com/purifycss/purifycss

**Comment by crcommons** [comment]
Awesome! Can your deliverable include recommendations how to make recommended do it and when we can/should or is it going to be ? I just want to make sure changes that should be made during the setup actually happen.

**Comment by Angamanga** [comment]
@crcommons I added a specific issue for the recommendation: https://github.com/ushahidi/platform/issues/2629
