### ISSUE TITLE
User Management / Contacts Initial Spec

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2631]
### Overview
Construct a thorough high level initial spec for the Contacts UX Design in order to identify potential issues, time costs and complexity.

#### Cleint
- [ ] User view list changes
  - [ ] Basic PL style changes
  - [ ] Naming scheme change Users to People
  - [ ] Add person integrated into People list view
  - [ ] Add import contact template
  - [ ] Wire import contacts to import API
    - [ ] Reuse existing import wizard from Post Importer
- [ ] Edit view list changes
  - [ ] Basic style and layout changes
- [ ] Add/Edit Person
  - [ ] Contacts become editable

#### API
- [ ] Small change to user endpoint to permit update/addition of contacts
- [ ] Import Contacts
  - [ ] Update Import API
    - [ ] Create Import Job creation listener
- [ ] Provide bulk person creation??? <- should wait for lumen

#### Job Queue system
- [ ] Extend Export Queue subsystem
  - [ ] Add import queuing
- [ ] Update Ansible deploy scripts
- [ ] Update Platform Job Queue

### Time estimates
- Client work: 24 hours
- API work: 40 hours
- Job Queue system: 40 hours

These can happen in parallel

### Dependencies
- The client changes do not need to wait for the client improvements
- **The API changes should not be undertaken until or during the lumen landing**.

https://xd.adobe.com/view/13b2b22a-7cde-4ea5-b893-6026d291500c/

A work in progress for this PR can be found in the `contact-importer` branch https://github.com/ushahidi/platform/pull/2360

Aha! Link: https://ushahiditeam.aha.io/features/PROD-406

**Comment by caharding** [comment]
@justinscherer FYI here is a quick tech spec on estimated effort to do the first lift of a People mode. But I think we're waiting on a design revision based on the feedback session before we can give this a more thorough spec.

**Comment by rowasc** [comment]
#2568 related epic
