### ISSUE TITLE
Unable to edit collection from Data Mode

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2638]
### Expected behaviour
I should be able to find an edit button somewhere on this page to edit my collections

### Actual behaviour
I can only create new collections from data mode

### Steps to reproduce the behaviour/error
*Log in
* Create a new collection and set default viewing mode to data
* Navigate to said collection
* Try to edit

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-405

**Comment by rowasc** [comment]
@Eve-wanderi could you verify this issue with Angie and add complete reproduction steps? Thanks

**Comment by rowasc** [comment]
verified this is still happening. The collections list button is visible but the actual edit button and relevant collection actions are only on map view. I think we could add an "EDIT" button like the one we have for saved searches, when we fix this
<img width="734" alt="screen shot 2018-10-04 at 9 47 39 pm" src="https://user-images.githubusercontent.com/2434401/46510410-267bf780-c81f-11e8-813a-89a3aac7fedc.png">
