### ISSUE TITLE
Atoms - typography

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2639]
## Summary

These are the [currently existing font rules from settings.scss](https://github.com/ushahidi/platform-pattern-library/blob/develop/assets/sass/_settings.scss#L138-L142)

```
$base-font-family: 'Lato', "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
$base-font-color: $black;
$sub-base-font-color: $black;
$body-font-weight: normal;
$body-font-style: normal;
$bold: 800;

$base-font-size: 14px;
$base-line-height: 1.266666667;
$small-font-size: em(14);
```

## Analysis:

- The bones of what we have is completely adequate. Our main font and font stack can stay the same for now. 
- Reliance on allcaps (buttons, labels) to show tappability (less accessible, harder to read)
- 12px, tiny italics
- contrast ratios on backgrounds
- No tappable style
- leading too tight on paragraphs
- drop shadows on text
- too many type styles working against one another in Map view, postcards. e.g. there are 8 distinct font styles just in the mode context bar on map view. For contrast, Slack's entire main desktop interface has 6. 
- vertical spacing inconsistent and creates ambiguity between labels and the things they label

## Solution 

Most of the typography is being done on the organism/template level it seems, and so we won't be able to get the changes we want by changing the global rules won't cascade throughout the app. We'll have to address most of the typography on a component by component basis.

I will recommend some global rules, though, to address the points above:
- Remove all allcaps from the app, if possible
- Nothing smaller than 14px 
- drop italics from helper text
- Obviously minimum contrast should be 4.5:1
- Disabled text can be #D0D0D0 on #FFFFFF
- `line-height: $font-size + 6;`
- remove all drop shadows on text 
- Labels should be closer to the the things they label than the things above them. 
- Increase our `$bold` to `900` with `letter-spacing: 0.2px;` and use it globally to signal tappability. 
- we also have a `$link-blue` at our disposal now: #0000E0

**Comment by Erioldoesdesign** [comment]
Found this that was interesting: http://www.bdadyslexia.org.uk/common/ckeditor/filemanager/userfiles/About_Us/policies/Dyslexia_Style_Guide.pdf

**Comment by Angamanga** [comment]
@sethburtonhall Not sure what to link for QA here? Maybe just click around in the different layout-g pages?

**Comment by sethburtonhall** [comment]
@Angamanga This was a general revision that populated across the app. The code lives [here](https://github.com/ushahidi/platform-pattern-library/blob/ui-refresh/assets/sass/_settings.scss#L95-L104) which can be tested throughout the PL.

**Comment by Erioldoesdesign** [comment]
Testing in Chrome Version 67.0.3396.87

FE QA notes:

- Across the whole PL there are still instances of 'uppercase' or 'allcaps' we need to change these to a sentence case format (capitalised first letter of a sentence/ sequence of words)

- Noticed the $bold: is at 800 and not 900. I'm pretty sure these are both the same though.

- Not sure where to check for the letter spacing and line height

- h6's are at 10px in some places:
![Screen Shot 2018-06-22 at 15.16.43.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/5cd3829a-c2e0-4f03-af8f-cc81d0804812)

- Where is 'blockquote' used in the platform? If it's used as any kind of helper text it needs to be changed to 'normal'

**Comment by justinscherer** [comment]
A note on `font-weight` after speaking with @Angamanga @sethburtonhall and @Erioldoesdesign 

Our base weight will remain as regular(400)
We will change our H3 weight from `semibold` to `bold(700)'
Our link style will still be `black(900)`

This will let us use the Google Fonts hosted version of Lato and not force our users to download it from us.

**Comment by sethburtonhall** [comment]
@Erioldoesdesign 

I have integrated this feedback and moved issue back to Design QA pipeline for final review.

**Comment by justinscherer** [comment]
Can I have a link to QA this @sethburtonhall ?

**Comment by sethburtonhall** [comment]
http://preview.ushahidi.com/platform-pattern-library/ui-refresh/

and 

https://github.com/ushahidi/platform-pattern-library/blob/ui-refresh/assets/sass/_settings.scss#L95-L104
