### ISSUE TITLE
Atom -> Form fields

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2640]
# Analysis of current state

Look here to see [what we currently have in the PL](http://preview.ushahidi.com/platform-pattern-library/master/assets/html/2_fragments/) 

![Screen Shot 2018-04-05 at 10.52.13 AM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/7a930c14-de53-42e7-80a6-3974066ec490)
![Screen Shot 2018-04-05 at 10.52.18 AM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/37573970-2938-4574-9ca1-e01559320cbb)
![Screen Shot 2018-04-05 at 10.52.28 AM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/5bb2fd15-849c-4a8b-84ed-d3ef7950f223)
![Screen Shot 2018-04-05 at 10.52.34 AM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/bcc75f28-7d9b-48fe-84d1-fd5006290fd9)
![Screen Shot 2018-04-05 at 10.53.13 AM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/4f5ca264-174e-4b56-8fed-a0747a5b805b)

### Problems
- zero state has internal drop shadows which add visual noise
- zero sate outlines don't contrast enough with background
- focus-state has yellow drop shadows which are ugly and do not show the on-state to visually impaired users
- Helper text breaks up the information hierarchy of label --> field --> helper text because it is above field. 
- Error bars do not pass contrast with background, are 14px italic which is hard to read

## Proposal 

Make all input fields look the same. No more special input field styles for titles and descriptions on cards. 

![input fields 5 April 2018.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/3c529f07-8767-4edf-afae-f1c0ed7edc6c)

### Rationale

- Kept the semibold labels. 
- Colours reflect changes in [#148](https://app.zenhub.com/workspace/o/ushahidi/platform-pattern-library/issues/148)
- Outlines, placeholders, error states all pass colour contrast
- no more tiny italics
- Zero state to focus state transition no longer relies on drop shadows. Instead corner radiuses change from 2 -> 5 and the weight of the field outline gets bumped up 1px. This is to frame the inputted information in a stronger way. 
- Helper text happens below the field so it doesn't break up the information hierarchy. An affordance for linking from helper text was created. 
- Error or alert states on field trigger the field label to become the "tappable" style i.e. Lato Heavy with 0.2px letter spacing. This signals to the user that there is still some interaction required with that element.  
- Tightened up vertical spacing a bit to reduce the size of forms and to more strongly associate labels with fields. 
- increased indentation and interior space of fields themselves to give inputted text a bit of room to breathe. 

[working file here](https://www.dropbox.com/s/u9sl4d5gasrqkyi/input%20fields%20exploration.sketch?dl=0)

**Comment by Erioldoesdesign** [comment]
Oh we also have the green outline: ![Screen Shot 2018-04-10 at 17.40.54.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/fdc1a077-e899-43cb-9d31-f21591e6c0b7)

Probs best to axe this style? idk leaving it to you :)

**Comment by justinscherer** [comment]
> "Probs best to axe this style? idk leaving it to you :)"

yep!

**Comment by Erioldoesdesign** [comment]
![Screen Shot 2018-04-12 at 12.30.30.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/09c94b35-9d3f-4c7a-976c-603bb8169be5)

I also found this weird style the other day....

**Comment by justinscherer** [comment]
That's the `$highlight` colour variable...

**Comment by caharding** [comment]
Can we also reduce space between fields? Not sure where to make that comment.

**Comment by justinscherer** [comment]
> "Can we also reduce space between fields? Not sure where to make that comment."

@caharding It's related to Spacing variables (#2643) . The problem now isn't that our variables are too big but that we're using the wrong ones. Definitely something to address in Forms (#2655).

**Comment by Angamanga** [comment]
@Erioldoesdesign @justinscherer Link to QA: 
- http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/1_atoms/#pl-pattern-forms
- http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/2_molecules/#pl-pattern-forms
- http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/3_organisms/#pl-pattern-forms

**Comment by Erioldoesdesign** [comment]
Testing in Chrome Version 67.0.3396.87

FE QA notes:

- Zero state form field border in PL is currently #1E232A and should be #777777

- Focus state of form field border is 1px in PL and should be 2px

- The error field style still includes a (x) red icon. It's not in designs but also, I anticipate some users trying to click this as it resembles our 'close' button style. Let's remove it all-together if we can. 

 - The warning field label's '!' icon is currently black in the PL and it should be grey #777777

- I think I mentioned on a separate ticket but the inner square on the checkbox needs shrinking. lets go for 1px shrinkage and see how that is.

- Form field success has a green outline. There are no designs for this but the green is so dark that the difference doesn't feel relevant at 1px. Increase the border to 2px for legibility (also mimics our undo 'success' box style.

- The form fields in the organisms page does not increase it's border to 2px when I'm typing in it.


Things for Design to look at more:

There are some styles for text inputs that aren't 'boxed' I'm wondering @justinscherer if we can replace these instances with our regular form fields?:

![Screen Shot 2018-06-23 at 15.06.12.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/de21280b-0638-4790-8457-940bbf02b51a)

I'm also not sure what this is supposed to do: 

![Screen Shot 2018-06-23 at 15.08.02.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/a47f4346-e405-4975-9f70-08ff0ac1cc01)

@justinscherer Did you look into the weird thing that the long text input field does where you can grab the bottom right corner and drag it larger? Can we think about nixing this as it's proper weird.

**Comment by justinscherer** [comment]
> Can we think about nixing this as it's proper weird

yep, let's cut it. A long-text input box is just a double-high input field in terms of styling.

**Comment by justinscherer** [comment]
disabled styles for everything are here:

Dropbox (Ushahidi)/Ushahidi Platform/Design/Spring 2018 UI refresh/input fields/"input fields exploration"

**Comment by justinscherer** [comment]
> There are some styles for text inputs that aren't 'boxed'

yeah, replace them with the normal ones.

**Comment by sethburtonhall** [comment]
@Erioldoesdesign I have integrated your feedback, moving back into Design QA for approval.

Keep me posted on the "non-boxed" adapt fields

> There are some styles for text inputs that aren't 'boxed' I'm wondering @justinscherer if we can replace these instances with our regular form fields?:

**Comment by justinscherer** [comment]
QA

zero state for input fields should have a border radius of `2px`. 

focus-state for input fields should have `2px` border width and a `5px` border-radius

placeholder text should be `#777777` 

unclicked checkbox should have a `1px` border of `#777777` with `2px` border-radius. Clicked checkbox shoul dhave a 2px border of #1e232a` and a `2px` border radius

sets of checkboxes should have a vertical space between each checkbox/radio of `21px` and 21px between then and their label

disabled checkboxes/radios are `#d0d0d0`

off-state for toggles should have a circle of `#777777` with no border

dropboxes should have 21 px padding on both left and right of placeholder text and 13px between the top/bottom of text and the border of the box. box border should have 2px radius

**Comment by Erioldoesdesign** [comment]
Good stuff! purrrrfect~ closing ticket
