### ISSUE TITLE
Atom -> containers

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2641]
## Analysis

**Benefits of cards in Ushahidi right now:**
1. They are easy ways to structure information
2. They force down our information density with padding between content and the edge of a card and between the cards themselves. 

**Problems:**
1. From Material Design - “The use of cards isn’t recommended when “a user is not directly comparing images or text.” https://medium.theuxblog.com/when-card-ui-design-doesnt-work-f4343118d108
2. We have almost zero image content in the platform outside maps. 
3. Users repeatedly complain that our UI feels baggy and there’s too much vertical spacing being eaten up between useful pieces of information
4. Cards make sense in a media or news context, they don’t make sense in denser, data-heavy programs. 
5. re: Eriol's work below, some cards are clickable and some aren't which isn't accessible. 

## Solution
1. We need to convert lists of cards into plain old lists 
2. A card on a grey background is unnecessary for, say a form
3. Lean harder on good type, spacing, and information hierarchy to group content
4. We need a modal container (#2662) and a modeless container and a list style (#2800). 
5. Modal containers can look mostly like what we already have. (#2662) 
6. Modeless containers should be flat on a background on White. Lists should be made up of tappable items on any container background. 
5. Judicious use of things like key-lines and spacing and typography can separate containers. 
6. A container should never be a tappable target. The tappable content should be the thing inside the card. 

**Before**
![Screen Shot 2018-04-19 at 4.32.56 PM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/a730cb8c-1a4d-476f-addf-068a92efcd60)

**After**
![containers.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/ee98ff25-34c9-4023-a5c7-fa6e52700f7f)

---
**Before**
![Screen Shot 2018-04-19 at 4.37.46 PM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/45c3ee4d-62ea-40d6-b607-f147268c896a)

**After**
![settings.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/25228987-d6f4-4322-aa00-d4009238e193)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-404

**Comment by caharding** [comment]
I personally find this style to be not attractive. Can we not just comply with standards set up with Material Design or elsewhere on the Web? I'd prefer  

https://material.io/guidelines/components/cards.html

Other points of reference
https://designmodo.com/web-design-cards/
https://www.smashingmagazine.com/2016/10/designing-card-based-user-interfaces/
https://www.webdesignerdepot.com/2017/01/50-creative-card-ui-designs/

**Comment by justinscherer** [comment]
I took another look at these after Charlie's feedback and a convo Eriol and I had the other day. I re-evaluated the usage of cards in our UI. Updated the ticket accordingly.

**Comment by justinscherer** [comment]
Eriol's original work

Working file folder link: https://www.dropbox.com/s/nq4j8pm1g6ubh6m/other-card-like-modules.png?dl=0

## Analysis
- There are lots of things which could be classed as 'containers'
- They look slightly different
- Main offender is the 'card with shadow'
- Some of the styles are user chosen so we have limited ability to force accessible colours here (setting a colour for a survey) unless we limit the user choice.
- There's currently no way for a user to immediately tell that a card is clickable until you click around an discover it yourself, even then there no confirmation that it's a 'correct' action and kind of looks buggy too the way the card tabs to the right.
- It's not immediately clear that your now viewing that card in the 'main window' there's also no clear way to 'close' it (no functional way exists to close either) and you must now click through cards to view them 'larger'

![Screen Shot 2018-04-06 at 16.24.19.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/873ff4f0-bdb2-4651-849d-65c5f1087509)

## Proposals
- Added a 1px solid border around the whole card element.

- With the border, there's some complexity with the background colour being #F1F1F4 so the minimum accessible colour in the new brand palette (https://github.com/ushahidi/platform-pattern-library/issues/148) against that is #373E46 but that's the brand grey so I went for standard black

- I've not kept rounded corners on cards here, as a shallow radius was not visibly distinct anyway and I don't want them to be styled like big form fields/hollow buttons. If we think there's merit in keeping a radius on these I'm happy to change.

- The main problem was trying to clearly and inclusively indicate that this is a clickable element without relying on shadows/colours and minimising any new front end/design elements. I've added in sort of 'button' in the bottom right that changes state from 'View >' to 'Viewing <' the hope here is that users will feel more secure in that initial first click and be able to orientate themselves as to which 'card' they're viewing in the larger window. (I'm not sure how big an addition/change this is though)

![Screen Shot 2018-04-09 at 23.34.42.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/94b0c54f-a112-416d-a96c-edc8c616f2bd)

![Screen Shot 2018-04-09 at 23.34.52.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/47fe4471-5cd7-44e2-9493-04eacdbb98d1)


- There are other elements that sort of had the same styles as cards that I've applied a similar treatment of a 1px border to them as well as 1px black lines as 'hr' content dividers.

- With the plans module, I removed the very slight variations on the brand yellow at the top and made it the single brand yellow.

- There are still some inaccessible/non-inclusive style colours like in the table with a light grey for the title cell, but i relied on larger, bold text here to communicate hierarchy so this atom may be blocked by/ dependant on typography atom.

![Screen Shot 2018-04-09 at 23.35.15.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/c4bfacdb-8004-4cf3-a99c-e504f3615c13)


![Screen Shot 2018-04-09 at 23.35.26.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/2f034b88-71c2-4223-9b35-214eded46a94)

## Rationale
- Improved contrast of colours against backgrounds
- Not relying on shadows/colours to indicate clickable state and what is 'active'/being viewed.
- Use clear language and symbols to indicate states
- Guide users instinctive actions and help them feel confident the system is working as it should.

**Comment by caharding** [comment]
Agreed that in most cases we want to use lists, not cards, as detailed in material design but I think there is a need for different kinds of frameworks for different kinds of info:

- Lists with no separation: lists of information like survey form fields do not need separation as they are continuous
- Lists with line separation: data in data view will need visual separation
- Cards: probably just used on Map View but we need some kind of card that overlays
- Modal: other pop ups, like confirm delete, that should take the same styling as cards

I highly recommend referring to the new Intercom design update. They have a Left Nav, a Secondary Left Nav, and a Lot of Data and it all looks great. 

[Uploading... Screenshot 2018-04-19 16.37.40.png ]

**Comment by caharding** [comment]
Also your Survey Before and After shows Sruvey and then Settings, confused... but that might be the German

**Comment by Erioldoesdesign** [comment]
Is the best links to test this these @sethburtonhall ?

http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/activity.html

http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/1_atoms/#pl-pattern-containers

http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/data.html

http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/data-edit.html

**Comment by Erioldoesdesign** [comment]
This LGTM but @justinscherer Would love to get your opinion on the following before closing this ticket.

When you have cards in data view and you have one selected so it indents, to follow the style of the fields that have a 1px border when zero state and a 2px, thicker border when 'focus' or active, do you think that when you have selected a card and it is indented 'active' it should also have a thicker 2px border? 

I think it should but it is doubling back on the designs a bit!

Assigning back to design for the answer to the above Q before sending to FE again.

**Comment by sethburtonhall** [comment]
I also forgot "View" and "Viewing" tabs. I'll pick it back up tomorrow.
