### ISSUE TITLE
Atom -> Loaders and progress indicators

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2642]
# Loading indicators

## What we have
- Bouncing balls on first load
- bouncing balls inside buttons
- Yellow barbershop stripe on the top of elements

## What we need
- Branded first load screen instead of generic bouncing balls
- Lazy loading (elements load in order and you don’t have to wait for an entire page)
- The barbershop spinning thing is ugly as sin. We need something clean and obvious to replace it. 
- A determinate (i.e. progress) loader (all our current ones are indeterminate)
- A load-state that makes it clear that you can’t action the page while it’s going (e.g. greyed out content)

## Inspiration
*LinkedIn* does a terrific job of this:
1. Indeterminate loader with logo
2. Loads a wireframe
3. Load live elements as they’re available (lazy loading) <-something like this would be particulrily great for our map tiles. 
[LinkedIn Loading480p.zip](https://github.com/ushahidi/platform/files/1925011/LinkedIn.Loading480p.zip)

[Best Practices For Animated Progress Indicators — Smashing Magazine](https://www.smashingmagazine.com/2016/12/best-practices-for-animated-progress-indicators/)

*Slack* Also does a terrific job at this:
1. Branded, indeterminate loader with a “connecting to Slack” message
2. Having quotes when they open up the app for the first time
[slack loading480p.zip](https://github.com/ushahidi/platform/files/1925012/slack.loading480p.zip)

## Solution
![first load](https://user-images.githubusercontent.com/29209303/38946793-c917a6ae-42f7-11e8-9d9d-50d3432a6ef7.png)

*1 basic indeterminate loading style*
![generic indeterminate](https://user-images.githubusercontent.com/29209303/38946760-b2cd3148-42f7-11e8-902e-061d3dbc97fc.png)

The small yellow bar would cycle through the lighter bar behind left to right every second or so. We can play around with stretching and other animation fanciness during implementation. 

*1 basic determinate loading style*
It goes in the same place as our current loader and would transition left to right with a [quadratic easing curve like this](http://easings.net/#easeInCubic)
![generic determinate](https://user-images.githubusercontent.com/29209303/38946824-e0c3159a-42f7-11e8-9486-d3186888a2f4.png)

[This prototype](https://xd.adobe.com/view/c587b8e1-5e51-4091-7fa0-9053ff20d4e6-b3b6/) shows what they would look like on first load and a dark first-load alternative. 

These are the basic components, specific examples of the loaders may require additional text, etc. to explain what is loading and why. 

## Rationale
- I copied LinkedIn's indeterminate loader and first loading screen and wireframe loading treatment and subbed in our branding. They do a good job. No need to re-invent the wheel on this one. 
- Our determinate loader is super basic and as universally re-purposeable as our current one (it can stick to the top of any module, basically), but has less visual clutter. It will actually make our UI _feel_ faster because we'll speed it up towards the end. 
- Lazy loading and the wireframe screens are best practice for any UI with a whole bunch of modules that may load at different speeds. This way, the user can gain benefit from part of the page's content without having to wait for the whole thing to load. This is especially good in low-bandwidth environments. 
- Accessibility wise, I don't think loaders have any WCAG 2.0 requirements, but we should check on them.

**Comment by caharding** [comment]
Love this

**Comment by Erioldoesdesign** [comment]
Soooo I found another weird thing that technically could be classed as a loader?

![button-loader](https://user-images.githubusercontent.com/11681324/39251450-3bb4aac4-489b-11e8-82ed-64823e810642.gif)

**Comment by justinscherer** [comment]
That's definitely a loader. In the case of something like this, we could do a determinate loader on top of the button. I have an example for this in my mocks, but I didn't upload it for some reason.

**Comment by Angamanga** [comment]
@Erioldoesdesign @justinscherer Link to QA:
- http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/1_atoms/#pl-pattern-progress

**Comment by Erioldoesdesign** [comment]
Testing in Chrome Version 67.0.3396.87

FE QA notes:

- So I think in the animation, when the yellow bar reaches the centre of the grey bar it goes slightly faster and then fills the entire second (right-hand) half of the grey bar quicker than it did the first half here's a gif of what I see:

![loaders.gif](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/0fdd975d-68d5-4695-af9b-85738d53c8b0)

I think we want the slow start and increases speed towards the mid point but that doesn't change size.

@justinscherer would need to confirm this as I sure the animation type is in his mind.

Accessibility/inclusivity hat on: I think the speed is correct, but I don't think we want this effect where the yellow bar grows in size. I find it a little dizzying after watching it a few times and any folks with migraine conditions/nausea conditions struggle with animations that don't have a consistent speed and change size rapidly.

**Comment by sethburtonhall** [comment]
@Erioldoesdesign I agree and will definitely be adjusting the animation.

@justinscherer Did you have anything particular in mind?

**Comment by justinscherer** [comment]
fine with me

**Comment by Erioldoesdesign** [comment]
Note to self @Erioldoesdesign : Still needs further Design QA

**Comment by Erioldoesdesign** [comment]
@sethburtonhall The new animation (to me) is perfect! Closing this ticket and I'm stoked with how this looks here: http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/1_atoms/#pl-pattern-loaders

<3
