### ISSUE TITLE
Atom -> Map base layers

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2645]
## Solution

You can view a live, interactive version of the map on [Mapbox](https://api.mapbox.com/styles/v1/justinscherer/cjfxzqkmr2fbr2snwc0wimn5z.html?fresh=true&title=true&access_token=pk.eyJ1IjoianVzdGluc2NoZXJlciIsImEiOiJjamU3b3ZvYWgwNGt6MnhtOTR2M20wdHh5In0.ppiP-r4swli62CbnKdFR-w#11.9/-1.298625/36.824637/0
)

### Rationale
I used brand colours and fonts and tweaked the relative prominence of various geolayers based on Mapbox's "Dark" style

I explicitly designed this base layer for election monitoring use cases, which lead me to emphasize:
1. City/state names
2. Province/state boundaries
3. Major highways to give a sense of the shape of a city or area
4. I would have added prominent visual cues for polling stations and electoral district layers if I had the data. 
5. Above all, the data points in the system. 

I de-emphasized things like:
1. Buildings
2. Minor streets/roads
3. parks, airports, water, etc. 

The result is a base map that is relatively dark (like our brand), with data points that stand out with bright points of colour. They are diffuse and large at lower zoom levels to mimic the effect of a heatmap. As you zoom in, the points become more distinct. The POI indicators, filtering, colour coding, etc. will be handled in other tickets. These are WIPs right now. 

### Examples

I used the geocoordinates from Uchaguzi to layer over WIP POIs on the base map

<img width="1289" alt="screen shot 2018-04-17 at 3 00 11 pm" src="https://user-images.githubusercontent.com/29209303/38899600-97d5cb2c-4255-11e8-8cba-201e812c8de3.png">

<img width="1289" alt="screen shot 2018-04-17 at 3 00 29 pm" src="https://user-images.githubusercontent.com/29209303/38899509-50c7f548-4255-11e8-90a2-3b8bd77c8379.png">

Here's what it looks like beside our new nav

![map](https://user-images.githubusercontent.com/29209303/38899544-5fa10c62-4255-11e8-8a66-4db468a0c0a5.png)

### Futuremusic

Eventually we should have base maps for all of our primary use cases (election monitoring, crisis response, humanitarian, health, in addition to the generic ones we already have)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-403

**Comment by justinscherer** [comment]
### WIP Notes

# Map tiles
The main questions we have to start with are:
1. What is the Map View for?
	1. A way to get a quick sense of how a deployment is going. 
	2. Something to show the engagement with a deployment
	3. A way to visualize the state a crisis/response
	4. Spark interest and reward exploration

2. Who is it for?
	1. Tourists, mostly, in its current form
		1. Primary mode is exploration, not analysis, so it should invite exploration. Which assumes a level of visual density that is a bit lower than you would normally have. 
		2. Assume a time frame of, say, 3-10 minutes, panning and zooming and licking through half a dozen POIs (validate with testing)
	2. Something deployers can take screenshots of and paste into decks or embed into their site
3. We can start to think about use-case specific maps. For example: in an earthquake, you might need to see buildings more than, say, neighbourhoods. Environmental monitoring deployments should highlight natural landscapes, and maybe, industrial properties. A pothole monitoring deployment should focus on roads. We could serve a default map for each main use case in an ideal world. If you’r looking at election monitoring, you would want to see, like, electoral districts, maybe in a chloropleth format. 

## Current issues
1. Our maps don’t align at all with our brand
2. They are off the shelf, general purpose maps and so definitely highlight some layers that aren’t super important for our use cases. For example: roads and buildings.
3. POI colours are random and ugly
4. POIs cluster in a way that reduces the visual complexity, but also hides engagement in a way, and has a weird spiral when a bunch of POIs are in one place. 
5. Map jumps around on first load
6. Zoom levels are inconsistent. 
7. Our filters are massive, legend and about space are crammed together
8. Filtering happens in a bunch of spaces simultaneously on map view. 

## Goals
1. Branded maps (just by looking at the maps, you should intuitively feel that it’s from us)
2. Better POIs
3. Cluster POIs in a way that doesn’t remove so much of the complexity. The problem wth groping all of them as one POI is that it makes very active deployments look the same as not so active ones. 
4. Separate filtering from About content
5. Filter in one place
6. Spark interest and reward exploration for novice, tourist-type users
7. The goal of the map is to sit behind your data and give a sense of density of phenomena in a certain area. 


## Think about a perfect map for election monitoring
### Hierarchy
1. POIs
2. Polling stations
3. Election districts
4. Cities
5. Major roads
6. Provinces / States /etc
7. Regions
8. Countries

Question: How much granularity do you need in the road networks?
Probably no buildings

**Comment by caharding** [comment]
Once this is complete, you should break out a ticket on platform repo with your wishlist features. 

Also, would be good to consider a dark/light alternative.
