### ISSUE TITLE
Molecule -> Navigation

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2648]
## Analysis

1. Our current nav is not scalable (e.g. languages like German make the labels too wide and break the pattern
2. Unlabelled icons (not accessible) and icons are not the representational view of what they are representing (not usable). Also we use colour change only for on-states (also not accessible). 
2.5. Icon labels are microscopic...
3. Breadcrumbs in mode-context are great, but it's unclear how well-used they are. 
4. Support is a tiny Ush logo which doesn’t make sense
5. Should link out to .COM somewhere so that our global nav can generate .COM and eventually sales leads
6. Dashboard —> überglobal navigation breaks our model basically. 
7. In mobile works pretty well. Probably keep the mobile styles.
8. Avatar is so, so tiny
9. Collections shouldn't be a global navigation category

## Inspiration

Garmin Connect has a similar, but much more complex navigation than platform. They have an automatically expanding/collapsing interaction which isn't super accessible/usable if you're not used to it. 

![Screen Shot 2018-04-16 at 10.54.22 AM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/f0186a55-8b37-4ec6-ae76-28881188d3ca)![Screen Shot 2018-04-16 at 10.54.35 AM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/238feda1-b26b-49b3-aa96-719ca71dda01)

![Screen Shot 2018-04-16 at 10.54.22 AM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/137562a7-8cea-4cc1-b895-d021ce4248fa)

### Iterations

![iteratinos.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/60a69c72-0090-4115-a7db-d79baeaddb6a)

## Solution

![winner.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/ff9aea09-4d6e-438d-81a1-a423475e5eb3)

### Rationale

1. A wider global nav to have labelled icons in a way that's scalable for many languages. We have the horizontal real-estate so that we don't need to worry about an expanding/collapsing interaction. 
2. Darker black background looks punchier on the blue-grey background. 
3. Small vertical bar to show on-state in addition to colours for accessibility
4. Initially was playing around with the deployment logo/name in the global nav, to eventually link to the deployment's about page and give better real estate. 
5. Killed the tiny avatar. Plus they aren't very widely used, I suspect. Happy to be proven wrong with some analytics on that one. 
6. Used type and spacing to differentiate between primary and secondary items instead of having the secondary items float at the bottom of the page. 
7. Added a "Made by Ushahidi" link-out to .COM. Could remove for some custom deployments, potentially. 
8. Typography inherits the "clickable" styling from [#2639](https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2639)
9. Swapped out the avatar for an icon and made a sensible "Support" icon that isn't an Ush logo

**Comment by justinscherer** [comment]
NB: We can use a blocked our colour gradient in the backgrounds from left to right to indicate hierarchy at some point.

**Comment by jrtricafort** [comment]
@justinscherer This is awesome! I was passing by here from your slack link and was curious- With the removal of the avatar, will certain customers still have a way of adding their branding, or is that being removed?

**Comment by justinscherer** [comment]
@jrtricafort 

> "will certain customers still have a way of adding their branding, or is that being removed?"

^^ Absolutely they'll still have branding there. I was referring to the user avatar in the secondary nav at the very bottom. We will for sure need to keep the ability to upload logos. Keep an eye out for that one in #2664

**Comment by Angamanga** [comment]
@Erioldoesdesign @justinscherer Link to QA:  http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/4_templates/#pl-pattern-mode-bar

**Comment by Erioldoesdesign** [comment]
Testing in Chrome Version 67.0.3396.87

FE QA notes:

- I noticed that the nav text ('Map' 'Data' etc...) seemed a little too low compared to the centre/mid-point of the icon it's related to:

![Screen Shot 2018-06-22 at 15.48.12.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/dbcaeb87-aa33-4522-b1b4-4ac0bba78848)

I made a small edit to the 'top' element to get this:

![Screen Shot 2018-06-22 at 15.49.45.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/f6f48baf-c027-41c9-9b1c-802975909478)

![Screen Shot 2018-06-22 at 15.47.55.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/9e6c330d-2848-4726-a26d-3c2cad8de85f)

If you download and cycle rapidly between the two images you can see the difference. Also I'm not sure if this change breaks things elsewhere but it illustrates my point :)

**Comment by justinscherer** [comment]
Nice catch @Erioldoesdesign . They should be vertically centre-aligned with a tappable background of 55px high for the main items and 34px for the secondary items.

**Comment by sethburtonhall** [comment]
@Erioldoesdesign I have integrated your feedback and moved issues back to Design QA pipeline. Thank you!!

**Comment by justinscherer** [comment]
Made by Ushahidi type should have a 55px invisible, tappable background around it and be 21px away from the top and bottom of that box. 

The nav items should also have invisible, tappable backgrounds that touch one another, `55px` high for the main nav items and `34px` high for the minor items

![Screen Shot 2018-06-28 at 10.32.08 AM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/4a5a825b-ab56-4525-9d49-57742347a25b)![Screen Shot 2018-06-28 at 10.32.00 AM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/5ffbfe09-dcb1-4a0e-8656-33a54ba27833)

`Letter-spacing` on all nav items should be `0.2px`

**Comment by Erioldoesdesign** [comment]
This sounds picky because it's like 1px but:
![Screen Shot 2018-08-07 at 15.58.46.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/e73f3a9b-e1fd-4af5-96bf-e1b200da43c0)

Height is supposed to be 55px...unless the 1px more breaks the layout I say keep it as 56px @justinscherer

**Comment by justinscherer** [comment]
> "unless the 1px more breaks the layout I say keep it as 56px"

As long as it's consistently 56, no worries.

**Comment by Erioldoesdesign** [comment]
Sweet. @sethburtonhall See above re. consistency of 56px ^^^ 


Closing ticket
