### ISSUE TITLE
Organism -> Forms

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2655]
A form is the logical combination of 

- Input fields #2640, #2740, etc.
- Containers #2641
- Spacing Variables #2643
- Type #2639
- Buttons #2699
- and Navigation #2648

If we put those things together as they currently stand, it looks something like this:

![containers.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/bbc97940-6159-4c11-96d3-69052bbee1da)

![settings.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/8a520b32-0e20-4620-afed-e6a52d31285d)

One thing to note. We have these continue and cancel buttons in the top right corner of the screen everywhere, I assume as a way to avoid the problem of having your continue/cancel buttons getting buried at the bottom of super long forms. And all our forms are very long pretty much. The problem with this is that the top right save violates the F-Pattern reading style. Basically the CTAs don't feel like a part of the form and the user gets to the bottom and feels lost. 

As a solve for this I floated the buttons at the bottom of the form, like this:

![forms - long form.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/a33683f4-c631-4ec5-912d-5366bac07186)

**Comment by Angamanga** [comment]
@Erioldoesdesign @justinscherer Link to QA: 
- http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/3_organisms/#pl-pattern-forms

**Comment by Erioldoesdesign** [comment]
Testing in Chrome Version 67.0.3396.87

FE QA notes:

The main thing I'm testing here is the spacing between titles, form fields and buttons. Everything looks good on the test link :)

It would be great to have a 'layout' of a set of survey fields to test this at a later date though!
