### ISSUE TITLE
Organism -> Search/Filter/Sort

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2657]
## Analysis

Our current search/filter/sort component has gone through a lot of surgery over the last 6 months and the scars are showing. Beyond some pesky UI bugs that we haven't fixed yet, the need to include CTAs for saving searches and the sheer number and variability and logic of things to filter by has made this component a complete mess to use. 

We **desperately** need to iron out our data model and the experience of Collections, saved searches, parent/children categories, and surveys, HXL tags. A different issue for a different day...

It's also not clear what our search actually searches for...

^^on some level, all of these data constructions are doing the same thing. 

## Inspiration

I fully stole a lot of how these filters work from AirBnB

<img width="1128" alt="screen shot 2018-04-24 at 4 37 44 pm" src="https://user-images.githubusercontent.com/29209303/39217565-dce864ee-47dd-11e8-974e-726e3da546f7.png">
<img width="1203" alt="screen shot 2018-04-24 at 4 37 52 pm" src="https://user-images.githubusercontent.com/29209303/39217566-deb92a10-47dd-11e8-8f5b-a33a51dfe245.png">

## Solution
**Zero state**
![zero state](https://user-images.githubusercontent.com/29209303/39217584-f02fecac-47dd-11e8-9ffe-8b195cd99cd9.png)

**Sort open**
![sort open](https://user-images.githubusercontent.com/29209303/39217681-5720c422-47de-11e8-9a5f-2153e643c5fe.png)

**Sort on**
![sort on](https://user-images.githubusercontent.com/29209303/39217683-5a772472-47de-11e8-8c62-84fbf75d7ad1.png)

**Filter open**
![filter open](https://user-images.githubusercontent.com/29209303/39217687-5f7dfdce-47de-11e8-8769-81ea966db865.png)

**Filter on**
![filter on](https://user-images.githubusercontent.com/29209303/39217690-635c0102-47de-11e8-829c-e6dd3eb1a721.png)

## Rationale

Ultimately this inherits most of the styles from #2655 and #2789 
I stole the idea of baking it into an anchored modal window and having different modal sizes for sort/filter from AirBnB as seen above. 

Part of the trouble we have now is that the search/sort/filter mechanism is embedded in the top bar and doesn't feel like it directly controls the data being displayed. To mitigate this, I baked it into a data list #2665  

I made creative use of our button styles to achieve on/active states, which I also stole.

**Comment by crcommons** [comment]
@justinscherer @Erioldoesdesign Does the search run the query after each letter is typed or should we put a 1 (or 2, 3...) second delay on the query or should there be a button to search once you've finished typing?

**Comment by crcommons** [comment]
Also, is there a reason the apply and cancel buttons are different for filter and sort?

**Comment by Angamanga** [comment]
@Erioldoesdesign @justinscherer Link to QA:
http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/3_organisms/#pl-pattern-filters (something appears to have happened to the input-box so you might want to wait to qa this)

**Comment by Erioldoesdesign** [comment]
Testing in Chrome Version 67.0.3396.87

FE QA notes:

- In the 'zero state' (default search state) the search magnifying glass icon is currently #1E232A in the PL code and in the design files it is #777777 (a dark grey. This is our lightest accessible grey on a white background)
The magnifying glass should change to #1E232A for the 'focus' or 'open' state.

- The copy on the buttons/links is all caps ('SORT' 'SAVED SEARCH') and should be sentence case ('Sort' 'Saved search') for legibility. (remove text-transform: uppercase?)

- The 'focus' or 'open' state and the 'submitted' or 'on' state should have text at #1E232A (text that is being typed into the search field)
- The border should be 2px for the 'focus' or 'open' state and the 'submitted' or 'on' state

- The 'submitted' or 'on' state list of 'Sample...' requires more padding on the left:
You can see that the list starts about a third in from the left of the 'sort' button.
![Screen Shot 2018-06-22 at 12.21.22.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/5a332cb4-6183-4b94-855c-eb40471eff0a)

- The copy is currently #1E232A and should be #777777 at all times:
![Screen Shot 2018-06-22 at 12.25.17.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/e7232e97-73b6-493b-8886-14a0139b49db)

 ~- The 'focus' or 'open' state 'Cancel' and 'Apply' buttons are in the outlined and solid style in the PL. The designs show a grey 'Cancel' text in #777777 and a blue link in #0000E0 'Apply' in the bottom left and right of the drop down checkbox list:~
![Screen Shot 2018-06-22 at 12.36.30.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/40edd3d1-d366-4057-a0af-bb72a7e53b28)

^^^ Justin's designs actually show two different styles of these buttons you can see in the designs above. I think the button style is better that the grey link text/ blue link text version so no changes here but goo to flag the design inconsistency (sorry Justin!)

- The squares in the checkboxes look a little too big. I played with the css and got this:

Original:
![Screen Shot 2018-06-22 at 12.46.31.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/9a493770-ef83-42ed-8b14-a97925e4187f)
![Screen Shot 2018-06-22 at 12.47.04.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/81319f77-9b84-4edd-8631-b7a0598429d2)

My edits:
![Screen Shot 2018-06-22 at 12.46.22.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/6122d014-ee8d-4dc3-a45f-13b647aafc8b)
![Screen Shot 2018-06-22 at 12.46.15.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/5f03fbc5-d4ea-497d-ab9e-52521a5c2aeb)

This css I did may break things elsewhere so worth checking over from FE. Illustrates the need for smaller 'black box' inside checkboxes though.

- The 'Filter open' state's titles a litter too far away for their checkboxes. I got the list checkboxes closer by editing the margin-bottom on the '.ltr-namespace fieldset legend' element (to 10px)

Also the sort/filter list appears in one long vertical. In the designs there are two vertical columns of a maximum of 4 checkboxes (either parent category or child category) per column. 
@justinscherer This may become a design problem if we have 1 parent category with more than 3 child categories and the 4th child category might align to the left column in the code structure. 
For now, let's keep 1 long column vertical list to eliminate this potential visual dissonance.


THIS IS GREAT WORK. I hope my QA notes aren't too heavy and are clear and understandable :heartemoji:

**Comment by sethburtonhall** [comment]
This is great @Erioldoesdesign!! Thank you. There are so many states with this component and it helps to have a QA. As you noticed, I made some "executive" decisions that I meant to communicate (default buttons instead of "gray" and "purple" left and right buttons for better consistency, one long column of checkboxes for better scaling). Your notes are very thorough and clear. I will comb through these and make the changes.

**Comment by Erioldoesdesign** [comment]
@crcommons omg I didn't answer your questions...sorry!

> Does the search run the query after each letter is typed or should we put a 1 (or 2, 3...) second delay on the query or should there be a button to search once you've finished typing?

I would go with after each letter is typed with a delay. It's a typical and expected user journey now for most users. Though, question: for users with slow connections, are we adding to the load time?


> Is there a reason the apply and cancel buttons are different for filter and sort?
> How do you remove the search, sort, and filters?
> If the query fails, which UI do we use to display the error

I picked up on the different filter/sort buttons in the design. I think that was just a design file error. We get UI 'blindness' sometimes and miss these things!

I would say the user would delete the text in the search bar (it should stay active) and the search results should reset. Either that or we need a 'clear search' button/text link This is one for @justinscherer to have a think about.

Good point! so if there are no results for a search term? We need to display text that says as much. Another consideration for @justinscherer I would say.

(Sorry to load you up with @ mention's Justin...)

**Comment by crcommons** [comment]
@Erioldoesdesign If we have a delayed query, it would affect slow connections in that it would fire off requests to the API whenever a user paused while typing. So I would recommend a search button perhaps. 

We definitely need some way to clear the filters and sort, and need to decide how to clear the search (depending on which search implementation we use).

**Comment by justinscherer** [comment]
> I picked up on the different filter/sort buttons in the design. I think that was just a design file error. We get UI 'blindness' sometimes and miss these things!

great catch. Let's keep the link style for the CTAs in both sort and filter windows. 

>I would say the user would delete the text in the search bar (it should stay active) and the search results should reset. Either that or we need a 'clear search' button/text link

When the user submits a query and the results are listed, clicking on the text in the search bar will highlight all of the text. They can then delete it as they wish.

>Good point! so if there are no results for a search term? We need to display text that says as much. 

Nice catch. Lets say "We didn't find anything that matches your search." in 14px Lato regular in `#1e232a`

**Comment by justinscherer** [comment]
> great catch. Let's keep the link style for the CTAs in both sort and filter windows.

@sethburtonhall talked me out of this one. Let's use buttons. Sorry for the flip-flop

**Comment by sethburtonhall** [comment]
@Erioldoesdesign I talked with @justinscherer and we are staying with the current button styles on filter/sort open, the version in the PL not the mock.

Moving back into Design QA pipeline for final approval.

**Comment by crcommons** [comment]
@justinscherer So if a user has selected a variety of sorts, filters, and a search, they'll have to go through and remove each one individually? There won't be a way to clear the search completely?

**Comment by justinscherer** [comment]
> So if a user has selected a variety of sorts, filters, and a search, they'll have to go through and remove each one individually? There won't be a way to clear the search completely?

Great point. The "Cancel" should be a "Clear all" and clicking outside the box or on the sort/filter boxes would do what "Cancel" does...i.e. closes the filter/sort pane without making any changes.

**Comment by justinscherer** [comment]
QA:

`border-radius` on checkboxes should only be `2px`

left and right padding between the text and the inside edges of all buttons should be `34px`

checkboxes should have `21px` of vertical spacing between them

border of open sort pane should be `#777777`, not `#1e232a`

checkboxes and buttons should all be `21px` spaced from the edges of the box

unclicked checkboxes have a 1px border of `#777777` clicked checkboxes have a 2px border of `#1e232a` 

min height for the open sort/filter box is 225px

border radius of open filter pane is 2px not 3px

**Comment by justinscherer** [comment]
In the results list, the leading on the detail text for each row item should be `font-size + 6px` so in this case, `20px`

**Comment by justinscherer** [comment]
Filters with lists of checkboxes/radios of more than 4 items should display them in two columns. ![Screen Shot 2018-06-28 at 10.47.00 AM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/8768cc7f-cddc-41a2-b177-542a1f0c1f99)should

**Comment by sethburtonhall** [comment]
Made all revisions except two column checkbox/radio. I am still working on this but I wanted to highlight @Erioldoesdesign's comment from above to make sure.

> Also the sort/filter list appears in one long vertical. In the designs there are two vertical columns of a maximum of 4 checkboxes (either parent category or child category) per column.
@justinscherer This may become a design problem if we have 1 parent category with more than 3 child categories and the 4th child category might align to the left column in the code structure.
For now, let's keep 1 long column vertical list to eliminate this potential visual dissonance.

**Comment by justinscherer** [comment]
@Erioldoesdesign 
re:
> This may become a design problem if we have 1 parent category with more than 3 child categories and the 4th child category might align to the left column in the code structure.
For now, let's keep 1 long column vertical list to eliminate this potential visual dissonance.

You're right about this. However, I think the benefit of not having eternal 1 column lists outweighs the risk of losing the indent when there's a parent with a tonne of children. The many children use case feels like an edge case to me, but of course I have zero data or testing to back that up...

What do you think?

**Comment by Erioldoesdesign** [comment]
Definitely keen to not have an eternal single column. Perhaps there's something code-wise that can override the layout if this were to occur? Like a rule that always has child categories display in the same 'column' as the parent and then the next parent would carry on the 2-column format? 

Sounds a bit complicated but not impossible to my rudimentary understanding of code!

**Comment by justinscherer** [comment]
> "a rule that always has child categories display in the same 'column' as the parent and then the next parent would carry on the 2-column format?"

Sounds good to me. Let's see what @sethburtonhall and/or @Angamanga says when they're back.

**Comment by Erioldoesdesign** [comment]
Everything looks good here to me apart from this issue around double/two column checkbox list in the expanded filter dropdown...

@sethburtonhall Can you take a look at my comment above and see if you can have a dig around to find a potential "rule that always has child categories display in the same 'column' as the parent and then the next parent would carry on the 2-column format"

If it's a no then I believe Justin still wants the 2-column view.

**Comment by Erioldoesdesign** [comment]
Updating this ticket with a comment from our design sync today in that we're going with a *single column of checkboxes* for sort and filter as the 2-column, max 4 items proved difficult to layout with anomalies for checkbox lists of uneven numbers.

Moving back into ready for FE because I believe Seth is currently working on what we discussed

**Comment by sethburtonhall** [comment]
This is ready for QA [here](http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/3_organisms/#pl-pattern-filters)

**Comment by Erioldoesdesign** [comment]
This looks fly. Closing this ticket :D
