### ISSUE TITLE
Organism -> modals

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2662]
## Analysis

We currently have 2 modal styles in the pattern library, neither of which are used consistently in production. Modal windows are a fairly standard piece of UI, so I will just apply existing styles to a floating container on a translucent, dark background overlaying a page's content. 

My primary issue with modals in our platform is that they are used inconsistently in the information architecture. The use case that makes sense the most for a modal window is when you need to focus a user's attention on a specific, detailed aspect of the UI. It's a way to "dive deeper" into elements at the primary, secondary, or tertiary level of information hierarchy. However, we have several global-looking navigation items that trigger modal windows and modal windows (e.g. filter pane) that trigger other, differently styled modal windows. 

## Solution

![basic modal.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/09c7793d-2510-444a-807e-e0ad2e6c676b)

**Rationale**
The styling is very basic. I used a 75% transparency of our black #1E232A for the background. Used a plain white card, got rid of the dropshadows, tweaked the spacing, and got rid of the heavy outline for the "close" CTA in the top right corner. An "X" in the top right corner of a view is normative enough these days as a close affordance that we don't need to label it for accessibility.

**Rules for modal windows and navigation:**
1. Modal windows shouldn't open other modal windows
2. Modal windows shouldn't have multi-page flows in them
3. Modal windows shouldn't be triggered by global navigation items
4. Tapping away from a modal window should close the modal window
5. Modal windows should contain a close button for mobile

These rules are going to complicate: saved searches, collections, user settings, and support.

**Comment by Angamanga** [comment]
@Erioldoesdesign @justinscherer Link to QA: http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/4_templates/#pl-pattern-modal

**Comment by Erioldoesdesign** [comment]
Testing in Chrome Version 67.0.3396.87

FE QA notes:

- In the designs the modal shadow details are as follows: 
Shadow colour: #000000 
50% transparency/opacity
Y=2 
Blur=4

My CSS fiddle here:
![Screen Shot 2018-06-22 at 14.28.03.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/8b8e65e6-8d37-4eb4-93ab-b45679eaeb5e)

**Comment by Erioldoesdesign** [comment]
Looks good to me :thumbsupemoji:
