### ISSUE TITLE
organism -> data list

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2665]
This is a slight upgrade from #2800 where the analysis rests for this issue. I needed about 20 iterations on the initial list I was using for secondary navigation in settings. 

<img width="1666" alt="screen shot 2018-04-24 at 4 11 14 pm" src="https://user-images.githubusercontent.com/29209303/39216809-646449be-47da-11e8-833b-620c504cd02b.png">

## Inspiration

I stole pretty shamelessly for this issue from such data list luminaries as

**Github**
<img width="1092" alt="screen shot 2018-04-23 at 2 09 04 pm" src="https://user-images.githubusercontent.com/29209303/39216836-84350a8a-47da-11e8-8ebd-32737249bdeb.png">

**Wealthsimple**
<img width="871" alt="screen shot 2018-04-23 at 2 12 06 pm" src="https://user-images.githubusercontent.com/29209303/39216844-8bc81846-47da-11e8-84ad-e2dc878312c3.png">

**Twitter**
<img width="302" alt="screen shot 2018-04-23 at 2 12 55 pm" src="https://user-images.githubusercontent.com/29209303/39216855-9e43b07a-47da-11e8-89cc-f3fd31760f28.png">

**feedly**
<img width="1310" alt="screen shot 2018-04-23 at 2 13 58 pm" src="https://user-images.githubusercontent.com/29209303/39216864-a9de1d08-47da-11e8-9a41-1648a2079b68.png">
<img width="853" alt="screen shot 2018-04-23 at 2 14 13 pm" src="https://user-images.githubusercontent.com/29209303/39216869-af893788-47da-11e8-80f7-45a9419953f9.png">
<img width="270" alt="screen shot 2018-04-23 at 2 15 06 pm" src="https://user-images.githubusercontent.com/29209303/39216871-b3750b74-47da-11e8-83cf-1caa179ab1e4.png">

And my personal favourite **Bear Writer**
<img width="486" alt="screen shot 2018-04-23 at 2 26 17 pm" src="https://user-images.githubusercontent.com/29209303/39216882-c09463b8-47da-11e8-98d2-f09daec81a69.png">

## Solution

**Solution in a vacuum**
![winner copy](https://user-images.githubusercontent.com/29209303/39216917-e5814c04-47da-11e8-88d0-19c35f623198.png)

**Solution in context**
![winner in context](https://user-images.githubusercontent.com/29209303/39216928-ed587060-47da-11e8-8f2b-a46732fd4007.png)

## Rationale

Almost every good data list I found used horizontal lines to differentiate itms and a skinny bar on the left side to denote "selected". The horizontal lines actually let you compress the amount of space you need for each item. The density for noise tradeoff was worth it. 

The tap target for each element is the title/main content, which is a max of 2 lines long before truncating and the secondary content associated with a list item (if there is any) goes below it in #777 and wraps twice before getting truncated. 

The multi-select feature will be a shift-click in web/desktop and a tap and hold x2 in mobile. Keep an eye out for these in Bulk Actions (#2766 )

I found a nice, bright, contrasty purple that jives with our branded dark blue for the accent colour #2618B1 , but I'm not 100% on it yet...

**Comment by Angamanga** [comment]
@Erioldoesdesign @justinscherer Link to QA: 
- http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/3_organisms/#pattern-sample-24

**Comment by Erioldoesdesign** [comment]
Testing in Chrome Version 67.0.3396.87

FE QA notes:

-  On the example 'list with selected' The purple bar for the selected item looks too low and should span the height of the 'cell' of the list information:

![Screen Shot 2018-06-23 at 15.38.09.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/72fba1bf-bcb0-4069-bded-5aedfed76b88)

![Screen Shot 2018-06-23 at 15.38.06.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/3510971c-8d88-4b29-a07a-42bf584278e9)

I found that by changing the 'top' to -14px I got the visual I wanted:

![Screen Shot 2018-06-23 at 15.37.57.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/640ad623-e9e0-44f9-bd01-9936689f60e9)

![Screen Shot 2018-06-23 at 15.37.52.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/fb4d3fc2-0985-41d7-96d3-fec7725dd8ac)

This isn't the case with the examples lower down 'list with multiple selected' and 'data list' so may just be an error for that one example.

- The copy in in list item "A sentence or less" is currently #1E232A and should be #777777 at all times.

- Padding in the 'selected list' looks a little big:

![Screen Shot 2018-06-23 at 15.52.05.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/cfd7351a-4098-44d7-b0d0-cd50f1e66efe)

Fiddling with css I got:

![Screen Shot 2018-06-23 at 15.51.57.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/f168a6a9-d2c9-410a-92a4-9206346ebbf8)

![Screen Shot 2018-06-23 at 15.51.54.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/01344360-efab-48bc-99d5-e747c891fcab)


Note for design:
@justinscherer In your design files you have the purple bar butt up against the primary nav bar. As a result it gets a little lost (contrast wise and could look a bit buggy to some folks?)

I actually prefer the positioning that exists in the PL right now where it's a little further away from the white container box. What do you think eh?

**Comment by justinscherer** [comment]
> "I actually prefer the positioning that exists in the PL right now where it's a little further away from the white container box. What do you think eh?"

I agree. Let's add 8px to the left of the bar between it and the nav.

**Comment by Erioldoesdesign** [comment]
Still getting the 'blue bar' a little to low from the top:

PL:
![Screen Shot 2018-07-10 at 23.31.27.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/72027dc4-53a0-49fc-a63a-c2007e88a8be)


vs design:

![Screen Shot 2018-07-10 at 23.33.22.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/692f453c-81be-482c-845d-4e7b6dd4b30b)

Do you see the top of the blue bar is aligned with the grey top line and the grey bottom line?

**Comment by sethburtonhall** [comment]
Thanks @Erioldoesdesign. This is fixed and can be seen [here](http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/2_molecules/#pl-pattern-list-items) and [here](http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/settings.html). It was an easy fix, so I am closing.
