### ISSUE TITLE
Template -=> Settings and settings sub-pages

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2669]

**Comment by justinscherer** [comment]
Got a start on these today. Will obviously need to break them out into sub sections for implementation. 

![containers.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/6b341851-51e6-495a-b4a7-561de61d67d3)

![forms - long form.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/26722a45-d18b-429f-80f2-a773c1e946f5)

![settings.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/5007aced-4c99-4237-9351-d0f2ded6ec27)

**Comment by caharding** [comment]
I really feel like settings could be improved with icons. I find it hard to
scan settings visually.
-- 
Charlie Harding
Product Director

**Comment by justinscherer** [comment]
> "One thing, is the background white to bright white?"

Good question. I'm toying with alternatives to pure white as a background colour. Problem is that off-whites often feel "dingy". The bright white hasn't been too bad so far because we don't use any pure blacks.

**Comment by justinscherer** [comment]
> "I really feel like settings could be improved with icons. I find it hard to
scan settings visually."

I can see that. This is super minimal. The problem with icons is that you need to find representational icons for things like "Webhooks" and "General" <- these icons don't exist. It also means that every new settings category we ever introduce also needs icons. 

I can work on scannability a bit more, though.

**Comment by caharding** [comment]
I think my aversion to pure white is only when it takes up the majority of
the screen.

**Comment by Angamanga** [comment]
@Erioldoesdesign @justinscherer Link to QA:
Links to settings and settings-sub-pages made so far:
http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/#pl-pattern-layout-g

**Comment by Erioldoesdesign** [comment]
Testing in Chrome Version 67.0.3396.87

FE QA notes:

Looking at: http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/settings.html

- The copy under the headings is #1E232A should be #777777 (think that'kk be covered in typography ticket)

- The h3's need more space above them for the top of the page/browser and/or the hr/line that is directly above them:

PL view:
![Screen Shot 2018-06-23 at 16.02.08.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/670f48d1-7446-469f-8a11-3e70332d1bda)

Design file:
![Screen Shot 2018-06-23 at 16.02.18.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/b03a342a-0256-48be-895d-fb07f7270944)

I'm finding a few layout snafus but I feel like most of this will be remedied as more UI work is done. It's mostly where buttons, lines, text are too close to each other (collapsing?) or the bottom of the browser window:

![Screen Shot 2018-06-23 at 16.05.55.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/cbeacecb-bc77-47bc-89c2-cbe7f7f5e424)

![Screen Shot 2018-06-23 at 16.06.03.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/759b2949-9197-489d-a6d3-eae338f8c85b)

![Screen Shot 2018-06-23 at 16.06.12.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/c93dd255-0ecb-464b-a15e-f9a7286d16b5)

**Comment by justinscherer** [comment]
@Erioldoesdesign were there any design updates based on this QA?

**Comment by Erioldoesdesign** [comment]
Looking through the Layout G links mostly as the links in other layouts still need other orbiting UI tickets to assess the overall 'look'

http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/settings-people-add.html

^^^ noticed the phone number field title collapsing(?) backwards

All the other pages look awesome! the spacing looks great and no errors. Almost ready to close this one :)

**Comment by sethburtonhall** [comment]
Thanks, @Erioldoesdesign, good catch. This was a quick fix. Closing.
