### ISSUE TITLE
Add feature in dataproviders to update a platform message status upon successful send or failure

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2674]
#### Requirements 

- [ ] When a message is sent to SMS provider, we need a way to update Platform with the new message status

Note: We are doing something similar with CSVs, where we send a callback to the platform:
[See this example.](https://github.com/ushahidi/platform-job-queue/blob/3e8aacc0c44d897f7a23063cc892303feb92b9a5/dataproviders.py#L106)

However, given the large bulk nature of this update, it might be easier to do this in SQL, rather than a series of PUT statements.

**Comment by rowasc** [comment]
@willdoran said this is done
Please close @kinstelli

**Comment by kinstelli** [comment]
@willdoran  - I'm just confirming, is this just marking messages as 'sent'? 
Is it updating several at once, or one-by-one?

**Comment by willdoran** [comment]
@kinstelli This is handled already by the dataprovider job that runs on the api side, so once platform-job-queue fires the dataprovider outgoing command the message status is updated as part of that process.

**Comment by kinstelli** [comment]
Nope, that's all I was asking.

**Comment by rowasc** [comment]
@kinstelli @crcommons this issue is just a technical task. I believe we might want to either keep them open until the dependency closes or close it after tested/reviewed by dev

**Comment by crcommons** [comment]
@rowasc API issues that have a paired/related client issue(s) should remain in testing or QA backlog and only move on when the client work can be moved with it. Does that make sense? Is that what you were asking about?

**Comment by rowasc** [comment]
yup cool thank you @crcommons

**Comment by kinstelli** [comment]
Closing this, since this has been working per deployments and is already deployed.
