### ISSUE TITLE
Map shows 'undefined' message while loading deployment information

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#2682]
### Expected behaviour
Everything works perfectly, and is super awesome!

### Actual behaviour
While loading deployment information, an `undefined` message is displayed in the top left corner of the site.

### Steps to reproduce the behaviour/error
Visit https://dale.ushahidi.io and watch the top left corner of the page.

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [X] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-386

**Comment by rowasc** [comment]
Closing as this is no longer happening 🎉

**Comment by rowasc** [comment]
Reopened, it actually happened when throttling 😭
