### ISSUE TITLE
Ensure that a count of sent messages is available to the client

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2683]
### Requirements
- [ ] Include a count of sent and received messages, per survey -- see client requirements at #2681 
- [ ] There is an endpoint at `/forms/:formId/stats/` where some stats information is already provided. If possible, this data should be included there.

Per #2681 , the API should provide this data:

"total_messages_sent": 2113,
"total_messages_pending": 887,

**Comment by crcommons** [comment]
@kinstelli If possible, we should return this data with the form/stats api call we're already doing.  We're calling "/forms/:formId/stats/".

**Comment by kinstelli** [comment]
Sounds good, @crcommons. Adding it to spec.

**Comment by kinstelli** [comment]
Per #2681 , the API should provide this data:
```
"total_messages_sent": 2113,
"total_messages_pending": 887,
```

If possible, API could also include something like this:
```
"message_stats": [
    "1": [ "sent": 123, "pending": "77", "responses": 11],
    "2": [ "sent": 123, "pending": "77", "responses": 231],
]
```

**Comment by rowasc** [comment]
excellent. @kinstelli the "1", "2" indexes are the form attributes?

**Comment by kinstelli** [comment]
Yes, sorry if that wasn't clear.

Incidentally, I've been trying out an SQL statement for this, but haven't completely solve it. If it helps, here's what I've got so far:
```
SELECT count(messages.status), messages.status, direction
FROM messages 
WHERE post_id in (select post_id FROM targeted_survey_state WHERE form_id = 1)
GROUP BY status, direction
```

**Comment by rowasc** [comment]
super cool. Thanks.I'll get on this  today. Should be super easy

**Comment by rowasc** [comment]
@crcommons what should we do about API tasks? I think I might keep them until client passes? right now we are not well set up for Stacy/Eve to run API QA . 
Ideally we could have a postman setup for them but looking for the middle solution atm
