### ISSUE TITLE
Find a state management approach for react and angular

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2692]

**Comment by crcommons** [comment]
@rjmackay I was planning to look into it. But if you both have the extra time and have an idea of where to start, I'm happy to let you look into it.

**Comment by rjmackay** [comment]
I think that probably right. Where possible we should try to plug the same state into angular components - there are a few angular redux plugins.

It's possible that some bits of state and angular services might need to work together ie.
- We might fetch data from the API with endpoint services, then save it into the state
- Or we could migrate API handling to new react style services, and then rebuild endpoints to just pull from state instead of the API

I'm not at all clear how that'd work out yet. It'll probably depend a lot of the size and complexity of what you're migrating.
