### ISSUE TITLE
Atoms -> Checkboxes

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2698]
## Analysis

Our current check boxes are fine except for a few minor things:
- The boxes are too small to be tapped comfortably
- the boxes rely on inset drop-shadows for visibility
- the outlines don't contrast enough on white
- they don't have a pattern for errors, et al. 
- the checkmark icon is very small and a bit difficult to see

## Proposal
![checkboxes.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/c663147a-535e-4738-918b-4969a2f48d9b)

## Rationale

Keep what's there more or less, except
1. lose the drop shadows
2. align colours with the new colour variables and to increase contrast
3. Make the tap targets bigger
4. Indent the checkboxes themselves under the label to show info hierarchy a bit better
5. copy over the error style from #2640
6. Use a small box on the inside with the assumption that folks look at the shape of the tap target rather than the content of the on-state to determine the difference between a checkbox and a radio button.
7. the thick black outline is analogous with #2640 as a way to signal something that's "on"

Aha! Link: https://ushahiditeam.aha.io/features/PROD-384

**Comment by Erioldoesdesign** [comment]
omg I love these

**Comment by Angamanga** [comment]
@justinscherer should there be any focus-ring around the checkbox? I think it needs it to be accessible?

**Comment by justinscherer** [comment]
good catch. Is there a browser default for it? 

If not, use a #777777 dashed border 1px wide with 8px between the focus border and the border of the checkbox.

**Comment by Angamanga** [comment]
@justinscherer should it really be 8px between the focus-border and the checkbox-border? It looks a bit wide?


8px between:  
![Screen Shot 2018-05-28 at 10.12.32.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/a26847c1-3722-4641-9295-b8f96a4e028c)                

2px between:  
![Screen Shot 2018-05-28 at 10.14.14.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/a36d89f7-0365-4f79-810b-d0e2c86c3faf)

**Comment by justinscherer** [comment]
you're right, 2px is better.
