### ISSUE TITLE
atoms -> dropdowns

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2700]
These ones were fairly straightforward. Dropdowns just inherited the styles from [other form fields (#2640)](https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2640) and [spacing variables (#2643)](https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2643). 

This meant getting rid of dropshadows and carrying over the chevron icon we use currently. 

## Solution

![droppdowns.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/c0b8b049-6d9e-43e9-a178-cd71c55e23e6)

nothing super surprising here

**Comment by Erioldoesdesign** [comment]
Just an FYI - I sort of noticed that drop downs (which I presume you're working on right now) and containers have a very similar style basis.

I'm uploading my container work now but it'd be good to see where there's overlap on these two atoms

**Comment by Angamanga** [comment]
@Erioldoesdesign @justinscherer Link to QA: 
- http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/2_molecules/#pattern-sample-19

**Comment by justinscherer** [comment]
Sorry, I'm a bit lost on this one. Why are there checkboxes inside a dropdown? Also: the vertical spacing here is way too tight. Should be 21px between each checkbox.

**Comment by Erioldoesdesign** [comment]
@justinscherer because of the sort & filter search/menu/drop down I would suspect.

Agreed on the spacing though!...can't believe I overlooked that...

**Comment by justinscherer** [comment]
> because of the sort & filter search/menu/drop down I would suspect.

Ah! That's funny. I never really thought of those as dropdowns. But I guess they do much the same thing.

**Comment by sethburtonhall** [comment]
Thanks @Erioldoesdesign 

The icon display issue on local is a bug. I'm glad it works in the live environment.

**Comment by Erioldoesdesign** [comment]
Note to self @Erioldoesdesign : This still needs further design QA

**Comment by Erioldoesdesign** [comment]
Looks great to me on this PL link: http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/2_molecules/#pattern-sample-19

I would flag though that the example is a drop down with checkbox elements and the designs show an example with text options without checkboxes. These are in a bold font so I can conclude that list items within a dropdown that isn't a radio/checkbox etc. should be bold text style. @sethburtonhall more of an FYI to keep an eye on for further design QA.

Closing this ticket :)
