### ISSUE TITLE
atom -> date picker

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2701]
Aha! Link: https://ushahiditeam.aha.io/features/PROD-382

**Comment by justinscherer** [comment]
copy airbnb

no shame. 

![Screen Shot 2018-04-24 at 4.24.56 PM.png](https://images.zenhubusercontent.com/5a661d504b5806bc2bc3c395/48d83e40-84e4-4df6-a26c-a4a2cc4d3c99)

**Comment by Erioldoesdesign** [comment]
@crcommons @rowasc Is there any scope in this refresh to not have the 'overlaid' time picker/date picker?

I feel like if we can stop the date/time pickers from pushing users into a (sort of) modal then we can have a really quick usability/accessibility win and make this interaction a lot better for general users too!

**Comment by crcommons** [comment]
@Erioldoesdesign I think it should be fine to not have the overload date picker. However, isn't that screenshot from airbnb a modal of sorts?

**Comment by Erioldoesdesign** [comment]
@crcommons I was getting a bit mixed up with the time picker piece of work! I'd also like to figure out how to make calendar picker better too but it'll probably still be some kind of pop-over/modal but with some way of it being more tab/accessibility friendly!
