### ISSUE TITLE
Test that Pattern Library Documentation works 

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2703]
### Expected behaviour
Developers want to be able to update the pattern library 

### Actual behaviour
Seth has updated the documentation, but we need to stress test it. 

http://preview.ushahidi.com/platform-pattern-library/master/assets/html/front-end-guidelines/introduction.html

### Steps to reproduce the behaviour/error
Read documentation and test implementing a small change
#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by rowasc** [comment]
Related to the PL docs issue you are working on next week :) @Angamanga

**Comment by rowasc** [comment]
Testing the docs from a new user perspective can be a code-in or community task after they are done.

**Comment by rowasc** [comment]
Anna already checked this during SIVICO. closing
