### ISSUE TITLE
Update `lumen` branch with changes from `develop`

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2714]
Probably in a couple of stages:
-  [ ] Merge `master` into lumen
-  [ ] Merge `develop` or SMS release into lumen

**Comment by rjmackay** [comment]
@caharding I've repurposed this issue. I don't think an audit is necessary... I've kept the lumen branch from diverging too far from core. The missing bits are mostly from the last couple of cycles and should all be picked up by merging branches.
