### ISSUE TITLE
Add description to Settings "Make this deployment private"

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#2716]
### Expected behaviour
The Setting `Make this deployment private` would have an explanation letting the user know what that option does to the deployment, perhaps a similar description like below the API Key.

### Actual behaviour
The Settings > General simply says `Make this deployment private` without any explanation what that actually does.

![screenshot 2018-04-10 09 41 03_preview](https://user-images.githubusercontent.com/91811/38567465-86ecbf3a-3ca3-11e8-9e53-fca0419215b9.png)

### Steps to reproduce the behaviour/error
Visit Settings > General on any deployment

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain): 

### How to fix

- Add a `<p>` like the one used in the settings.api_key_desc `<p>` within the API key section of the settings page. You will find this in the file "app/settings/site/settings-editor.html" . This is part of the code in the [platform-client](https://github.com/ushahidi/platform-client) repository.
    - for the translate key of the <p> , add a "settings.site_private_desc" key and then add the key in the "app/common/locales/en.json." file after the "settings.site_private" key. 
    - the "settings.site_private_desc key" should read "Enabling this option makes your deployment and it’s data only accessible to registered users with the correct privileges, who must sign in for access"
- Test the feature :) You can find it by accessing the Settings->General page in your deployment as an administrator 🎉 
- Send a pull request in the platform-client repository 

## Want to work on this issue?🙋 
Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Ping @rowasc if you need help with this issue!

**Comment by jessicaweberdev** [comment]
Will work on this issue!

**Comment by jessicaweberdev** [comment]
<img width="697" alt="Screen Shot 2019-08-18 at 14 58 10" src="https://user-images.githubusercontent.com/28212184/63230917-e5879a00-c1c8-11e9-8f6e-e62c83dd1d85.png">

Descriptive text has been added to "Make this deployment private" checkmark

**Comment by rowasc** [comment]
🎉 You're the best.  thanks @jessicaweberdev 

@Obadha2 could you verify this in steve-buscemi while you test my changes tomorrow, too?

**Comment by rowasc** [comment]
Released
