### ISSUE TITLE
Strict-Transport-Security

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2718]
### Overview

 - This is intended to prevent MiTM attacks when a request on HTTP is bounced back to the browser to redirect to HTTPS. If an attacker is reading outbound HTTP requests or inbound HTTPS redirects on a network they can intercept the TLS connection to the remote server and pose as the victim while passing packets along to the victim in vanilla HTTP. [Here's how to do it](https://scotthelme.co.uk/wifi-pineapple-karma-sslstrip/).

  - This change requires the addition of 
`Strict-Transport-Security: max-age=31536000 to our headers`
Max age should not be 0 as this is disabled rather than infinite. It describes how long the User Agent should consider our policy valid. The setting essentially enforces TLS use. It will prevent any use of HTTP to access our hosted sites. [Complete description](https://scotthelme.co.uk/hsts-the-missing-link-in-tls/).

  - It's worth noting that in a number of countries the use of encryption is entirely illegal, these laws are generally designed as a potential means to enact censorship. When implementing this feature we should be mindful of users who may need to disseminate Posts to individuals in environments of significant censorship, though it would probably be inadvisable in those contexts for users to access such content without the use obfuscation technology.<sup>[1](#footnote1)</sup><sup>,</sup><sup>[2](#footnote2)</sup>

  - Howto
    - [Apache](https://raymii.org/s/tutorials/HTTP_Strict_Transport_Security_for_Apache_NGINX_and_Lighttpd.html)
    - [Nginx](https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/)

<a name="footnote1">1</a>: [The Zone 9 Bloggers are Free: but Ethiopia Still Thinks Digital Security is Terrorism](https://www.eff.org/deeplinks/2015/10/zone-9-bloggers-are-free-ethiopia-still-thinks-encryption-terrorism)
<a name="footnote2">2</a>: [https://www.eff.org/deeplinks/2016/12/crypto-state-law-end-2016](https://www.eff.org/deeplinks/2016/12/crypto-state-law-end-2016)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-379

**Comment by tuxpiper** [comment]
Related for SaaS implementation: https://aws.amazon.com/blogs/networking-and-content-delivery/adding-http-security-headers-using-lambdaedge-and-amazon-cloudfront/
