### ISSUE TITLE
Content-Security-Policy

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2719]
### Overview

  - This allows us to lock the content that the browser will load in relation to our site to a whitelisted set.
  - Requires audit of all current external libs/sources that we rely on and then extensive UI testing to ensure that behaviour is as expected

Aha! Link: https://ushahiditeam.aha.io/features/PROD-378

**Comment by digitalhuman** [comment]
Not only UI testing, really end-to-end as well as functional. This is also not something you can automated sadly. You need to keep track of all changes third parties make. It can break the application. I would advice to pick up this ticket when all the rest is finished and done. You don't want to delay a release by this item.
