### ISSUE TITLE
X-XSS-Protection

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2721]
### Overview

  - sets the configuration for the cross-site scripting filter built into most browsers. 
  - Howto
    - Recommended value 
`X-XSS-Protection: 1; mode=block`
    - Default: Use the recommended value. Browsers will attempt to sanitize by default, but it'd be best to block if an attack is possible/detected .
    - For ushahidi hosted deployments, default to BLOCK
    - Docs: a blog post explaining this and the other "new" security features
    - Docs: a highlighted note in our technical docs for OSS deployers to be aware of this

**Comment by willdoran** [comment]
related to #1610

**Comment by tuxpiper** [comment]
Duplicates #1610
