### ISSUE TITLE
Referrer-Policy

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2723]
### Overview

  - a new header that allows a site to control how much information the browser includes with navigations away from a document and should be set by all sit. This allows some control over information passed to linked site by browser, it is not enforceable in anyway and is defeated by almost all analytics systems or just having facebook or gmail open :/
  - Howto
    - Recommend we do not implement this at present but review it and write it up for docs
    - Docs: a blog post explaining this and the other "new" security features
    - Docs: a highlighted section to explain the default and links to the options for OSS deployers

Aha! Link: https://ushahiditeam.aha.io/features/PROD-375

**Comment by Jenniline** [comment]
@willdoran I am an Outreachy applicant and I will like to work on this issue. Please, can I have more information on how to go about this?

**Comment by tuxpiper** [comment]
I think this is a hosting concern, and I'm not sure we would even be able to issue a blanket recommendation.

For ushahidi.io , I think it would make sense to have a "Referrer-Policy: origin" value
