### ISSUE TITLE
SMSSync not working 

### ISSUE THREAD

**Issue by gsvlopez** [ushahidi/platform#2725]
### Expected behaviour
SMS option works when testing 
### Actual behaviour
SMS messages do not come through after trying several times and making sure that all steps have been followed with SMSSync (I tried reaching out to the team through Intercom but have not received a response)
### Steps to reproduce the behaviour/error
SMSSync instructions online for Ushahidi Data Sources and use of Android phone with Iraqi sim card
#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [x] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by tuxpiper** [comment]
@gsvlopez This has been so long, sorry!  One thing I know of is  that if the deployment is set to private (requires logging in to see) , then SMSSync or any other push data sources won't work.

Was that the case?

**Comment by tuxpiper** [comment]
Closing this by now
