### ISSUE TITLE
Modebar for mapper-plan is off

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2726]
### Expected behaviour
I expect the modebar on small screens when on a mapper-plan to stretch out to the full width of the screen.
### Actual behaviour
Modebar is empty and leaving a whitespace where the activity-button should be.

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by rowasc** [comment]
mapper does not exist anymore .closing
