### ISSUE TITLE
Create final targets for M&E Plan results framework

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2733]

**Comment by jrtricafort** [comment]
@crcommons doing this prior to Hit team

**Comment by rowasc** [comment]
@crcommons we should sync on this before EOW , right?

**Comment by crcommons** [comment]
@rowasc Yes, we need this to be complete before any code gets pushed to production. Let's get something on the calendar.

**Comment by rowasc** [comment]
excellent sending invite, you can change it if it doesn't fit your schedule.

**Comment by crcommons** [comment]
Ugh, it's so close to being done. It's a 2+ because Google Analytics doesn't actually measure the last few metrics for us.

**Comment by rowasc** [comment]
Closing as its deprecated.
