### ISSUE TITLE
QA Lumen refactor

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2736]
Because Lumen touched every bit of the API, we need to do some general QA of platform.

**Comment by rjmackay** [comment]
@Eve-wanderi I think you looked at this in February - doing general QA on qa.ushahididev.com after our API refactor.
How far did you get? Were there any significant issues? Any estimate of how long you would need to do it again? (ie. a general QA pass over major platform features)

**Comment by caharding** [comment]
@Eve-wanderi is this complete?

**Comment by rjmackay** [comment]
@caharding I don't think this *can* be complete since the lumen work was only ready a few days ago. I can and should start now though

**Comment by rjmackay** [comment]
@Eve-wanderi I don't know if you've been creating test cases as you went already, but I think it would be really valuable to the team if you could write test cases for some of the major features in platform while you do this, ie. so we can use them for testing during other refactors or background changes. If that takes an extra day or so I think it would be worth it. What do you think?

**Comment by rjmackay** [comment]
This can be QA'd on https://qa.ushahididev.com

**Comment by Eve-wanderi** [comment]
@rjmackay   Yes i can create the test-cases for this since this is what  i will be using to do regression tests. I will Create the testscripts on https://ushahidi.ontestpad.com/project/1/folder/f8/

 However, i have a blocker since i currently cannot access https://qa.ushahididev.com

I get this error.
![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/d1d2a47b-01be-4303-a79b-6fb2057f1026)

**Comment by rjmackay** [comment]
Ok for now just use http not https - I'll see if I can figure out how to replace the SSL cert soon

**Comment by rjmackay** [comment]
FYI: CSV exports are currently broken. Hopefully I'll fix it before the end of my day though

**Comment by rjmackay** [comment]
Ok CSV exports should now work.

**Comment by Eve-wanderi** [comment]
Okay thanks.

**Comment by rjmackay** [comment]
This passed QA right?
