### ISSUE TITLE
Update production to PHP7

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2737]
Lumen relies on PHP 7+
Staging has been updated, but production servers will need to be rebuilt with PHP7

**Comment by rjmackay** [comment]
@tuxpiper do you think you could migrate the production servers to PHP7 in the next cycle?
If we are going to be able to deploy lumen to production we'll need to do this.

**Comment by tuxpiper** [comment]
Sure that sounds like a good plan . Hopefully we'll get it done without downtime or much queue interruption

**Comment by tuxpiper** [comment]
This is done
