### ISSUE TITLE
RetrieveColumnNameData - Tech debt

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2739]
### Expected behaviour
RetrieveColumnNameData should not require us to iterate through all records to get the data as this is really inefficient and not necessary. 
https://github.com/ushahidi/platform/pull/2730#discussion-diff-181270812R167
### Actual behaviour
We need to request the data per item.
See discussion https://github.com/ushahidi/platform/pull/2730#discussion_r181270812

**Comment by caharding** [comment]
@rowasc is this part of an existing EPIC or feature?
