### ISSUE TITLE
Write user-documentation for Facebook bot

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2740]
- Write documentation for a fb-user can use the bot to add a post to the platform
- Send documentation to Shadrock to send it to Comrades

**Comment by Shadrock** [comment]
Just a note to say, that some documentation for the FB bot can be found on [pages 21-23 of the second report to the EU for the COMRADES project](https://drive.google.com/open?id=1gXpCl-gr6A3vFpQXq6kegLalsX4Tnb_b). This information may be reusable or provide a starting point.

**Comment by Shadrock** [comment]
Hey @Angamanga, I'd love to close this out. Has this been finished? If so can you please point me to the doc?

**Comment by rowasc** [comment]
@Shadrock can I close this? It's the documentation in the config setup manual doc, right?

**Comment by Shadrock** [comment]
Yes @rowasc, this can be closed out: doing that now!
