### ISSUE TITLE
Write technical documentation for fb-bot

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2741]
- Write detailed documentation for how to set up the bot for a developer
- Send to Shadrock to send to Comrades

**Comment by Shadrock** [comment]
Hey @Angamanga, I'd love to close this out. Has this been finished? If so can you please point me to the doc?

**Comment by rowasc** [comment]
bumping. @Angamanga @Shadrock should we close it? do we need to add anything else?

**Comment by rowasc** [comment]
awesome, thank you. @Angamanga 

@Shadrock let us know if you need any modifications

**Comment by rowasc** [comment]
The final COMRADES report was delivered, closing
