### ISSUE TITLE
Provide text alternatives for non-text content

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2744]
Step one, in the Pattern-library:
- Add a text alternative to all of images.
- Add a text alternative to audio and video (a succinct description of the topic).
- Add a name to all controls (such as ‘Search’ or ‘Submit’).

https://www.wuhcag.com/non-text-content/

**Comment by middle8media** [comment]
this is completed in accessibility

https://github.com/ushahidi/platform-pattern-library/commit/421d3a2a0df6fc9af2b95acbde384bc6fdaa4a66

https://github.com/ushahidi/platform-pattern-library/commit/75cf795b5aa673c99d5099fdc7ef4da4027445e0
