### ISSUE TITLE
Make all content available from keyboard-only

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2745]
In pattern-library:
Make sure all content on all layouts are accessible with the keyboard only. Fix those places that are not possible to reach.

In the client:
When integrating the new html, make sure click-events are possible to perform with keyboard as well.

Resources:
https://www.wuhcag.com/keyboard/
https://www.wuhcag.com/no-keyboard-trap/

**Comment by rowasc** [comment]
@Angamanga @sethburtonhall is this in the correct pipeline ? (Ready for Dev) Do we need to divide this  into smaller issues?

**Comment by Angamanga** [comment]
Moving to ready for spec
