### ISSUE TITLE
Reordering questions sometimes creates incorrect form_attribute priorities

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2754]
### Test/QA-checklist

Testing checklist:
1. Go to settings->survey->new survey->new targeted survey
2. Add a number of questions, remember the order
3. Reorder the questions, remember the order
4. Edit a question
Note, step 3 and 4 could be done in any order and how many time you would like, the outcome should still be: 
-  [ ] Click on continue, the list of questions should still be same as after the last reordering
- Publish survey
- [ ] Check the db, the priority should match the order of the questions

### Expected behaviour
- Reordering targeted survey questions should result in questions being sent in the newly created order.

### Actual behaviour
- Reordering targeted survey questions result in some questions being sent out of order. The display of questions in subsequent steps is inconsistent.

Here is the reordered set of questions, noting the original order (I forgot to update the `still fourth question` to say `previously fourth question`):
<img width="570" alt="screen shot 2018-04-16 at 11 49 43 am" src="https://user-images.githubusercontent.com/6600708/38824181-00ae5346-416e-11e8-9c3d-b1d83fe89e7b.png">

Here is the order of the questions after proceeding to the next UI step:
<img width="392" alt="screen shot 2018-04-16 at 11 49 49 am" src="https://user-images.githubusercontent.com/6600708/38824142-e7631ebc-416d-11e8-9919-b916b686124a.png">

Here are the priorities as set in the DB after reordering. Note that there are two items with priority 6 and no questions with priority 4:
<img width="440" alt="screen shot 2018-04-16 at 11 54 43 am" src="https://user-images.githubusercontent.com/6600708/38824094-c9b3deba-416d-11e8-9c88-e512a70fdfdc.png">

### Steps to reproduce the behaviour/error
- Create a targeted survey
- Create several questions
- Reorder the questions, proceed to the the next step
- Note the new order of the questions displayed in the UI
- Proceed to send the survey to at least one contacts
- Send a response to the platform via Postman/API (tested with `http://targetedsurveytesting.api.v3-qa.ush.zone/sms/testservice` with attributes: `secret`, `message`, `from`)
- Note the order of the questions that were sent

#### Where does this issue happen?
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by kinstelli** [comment]
I just tried this again and was able to reproduce it. 

I don't know what was different, except that I re-sorted some questions a few times and renamed the question to add their new expected order.

Here is some output from each of the POST calls to forms/x/attributes using devtools:

<img width="305" alt="screen shot 2018-04-16 at 2 43 50 pm" src="https://user-images.githubusercontent.com/6600708/38831432-064c86d0-4185-11e8-8385-6b121f4a7c77.png">
<img width="319" alt="screen shot 2018-04-16 at 2 44 09 pm" src="https://user-images.githubusercontent.com/6600708/38831486-2c2bf192-4185-11e8-921b-e4c7d8c733e7.png">
<img width="273" alt="screen shot 2018-04-16 at 2 44 14 pm" src="https://user-images.githubusercontent.com/6600708/38831441-0b8c3f78-4185-11e8-8165-c7c44a0ef24c.png">
<img width="325" alt="screen shot 2018-04-16 at 2 43 59 pm" src="https://user-images.githubusercontent.com/6600708/38831435-078d2c48-4185-11e8-8559-64cf2ad47252.png">
<img width="312" alt="screen shot 2018-04-16 at 2 44 04 pm" src="https://user-images.githubusercontent.com/6600708/38831439-097c4124-4185-11e8-9770-e7b50f79d6fa.png">

and the db priorities for this form:
<img width="433" alt="screen shot 2018-04-16 at 2 50 31 pm" src="https://user-images.githubusercontent.com/6600708/38831618-94df78e4-4185-11e8-9d21-26fd61ca6417.png">

**Comment by Angamanga** [comment]
@crcommons This is merged to develop!

**Comment by kinstelli** [comment]
@Angamanga, @crcommons 

I tried and tried to break this. I even went back and forth between survey stages, but reordering and renumbering questions didn't break anything. 
So it appears to be fixed to me. Here was my most recent attempt:

```
mysql> select form_stage_id, priority, label from form_attributes order by form_stage_id, priority;

+---------------+----------+-------------------------------------------------------------------+
| form_stage_id | priority | label                                                             |
+---------------+----------+-------------------------------------------------------------------+
...
|            82 |        1 | Originally Question 4, Now Question 1                             |
|            82 |        2 | Originally Question 1, Now Question 2                             |
|            82 |        3 | Originally Question 2, Now Question 3                             |
|            82 |        4 | Originally Question 5, Now Question 4                             |
|            82 |        5 | Originally Question 3, Now Question 5                             |
|            82 |        6 | Originally Question 6, Now Question 6                             |
+---------------+----------+-------------------------------------------------------------------+
