### ISSUE TITLE
SMS Surveys v2

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2757]
EXPAND UPON ORIGINAL SCOPE. Make sure to grab issues that were marked out scope: https://docs.google.com/document/d/1uUkSG0NsoDTxIkKfmVG6oSX5u1rVOVvAuOoY_E0VaTQ/edit#heading=h.68p54zclhue3
- User wants to be able to send survey's via SMS to a list of contacts
- User wants to be able to respond to send SMS surveys that have more than one question (As built in MVP)
- User wants to be able to have skip logic embedded in SMS surveys 
- User would like to see the cost of an SMS survey automatically calculated with the final price
- This issue is an expansion of #2419 that was protoyped for DREAMS, which we would like to release to all users.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-369

**Comment by jrtricafort** [comment]
@caharding I changed the label to distinguish it from the other SMS epic. Feel free to change it to something else that's more descriptive.

**Comment by rowasc** [comment]
@caharding 
>User wants to be able to respond to send SMS surveys that have more than one question

I might be interpreting this the wrong way, but targeted surveys CAN have more than one question in the current release(the one we send today), and it system sends the next one after the user responds.

**Comment by caharding** [comment]
Yes, already built, just clarified in issue
