### ISSUE TITLE
Users should be able to send messages to the platform after they are done with a targeted survey

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2768]
### Expected behaviour
- When a user is in a targeted survey and finishes the survey, they should be able to continue sending messages to the platform outside of it.

### Actual behaviour
- When a user is in a targeted survey and finishes the survey, they can't add messages to the platform because of a bug that causes them to be rejected.

### Steps to reproduce the behaviour/error
- Create a targeted survey with a contact
- Finish the survey (respond to all questions)
- Send a new message from that contact
- Your message won't be accepted (saved)

#### Test Script

- [x] Finish a survey with a contact (respond to all messages)
- [x] Send a new message
- [x] The message should not be associated with the targeted survey

#### Where does this issue happen?
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain): release/cycle-3-sms-csv

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by caharding** [comment]
@rowasc should this be closed with the pull request you made yesterday?

**Comment by Eve-wanderi** [comment]
Cant test this since i currently cannot respond via SMS to a Targeted Survey.

**Comment by kinstelli** [comment]
After fix for #2844, this seems to be working, as well, at least via Twilio.
<img width="534" alt="screen shot 2018-04-27 at 2 51 11 pm" src="https://user-images.githubusercontent.com/6600708/39382391-e9314208-4a2a-11e8-9b9b-f4a55d3ddd3c.png">


And here is the database side for this interaction. Note the post_id is changed when any new messages are sent after the survey is complete.
```
+---------+------------------------------------------------------+------------+-----------+---------------+---------+
| post_id | substring(message,1,50)                              | created    | direction | data_provider | status  |
+---------+------------------------------------------------------+------------+-----------+---------------+---------+
...
|     621 | April 27, Survey 1, Question 1. Did you get this?    | 1524855735 | outgoing  | twilio        | sent    |
|     621 | Hello Question 1, Yes, I received this.              | 1524856228 | incoming  | twilio        | pending |
|     621 | April 27, Survey 1, Question 2. Did you get this?    | 1524856228 | outgoing  | twilio        | sent    |
|     621 | Hello, yes, I got this, Question 2                   | 1524856821 | incoming  | twilio        | pending |
|     621 | April 27, Survey 1, Question 3. Did you get this?    | 1524856821 | outgoing  | twilio        | sent    |
|     621 | I did get Question 3, thank you.                     | 1524857421 | incoming  | twilio        | pending |
|     621 | April 27, Survey 1, Question 4. Did you get this?    | 1524857421 | outgoing  | twilio        | sent    |
|     621 | Yes, thanks for sending question 4                   | 1524858019 | incoming  | twilio        | pending |
|     621 | April 27, Survey 1, Question 5. Final Question. Di   | 1524858019 | outgoing  | twilio        | sent    |
|     621 | Woo! Hi! Yes, I got question 5.                      | 1524858623 | incoming  | twilio        | pending |
|     622 | Now I’m just going to keep sending message to you.   | 1524858642 | incoming  | twilio        | pending |
|     623 | I don’t know what we have to talk about, because I   | 1524858657 | incoming  | twilio        | pending |
|     624 | But I’m just going to keep sending messages          | 1524858664 | incoming  | twilio        | pending |
+---------+------------------------------------------------------+------------+-----------+---------------+---------+

Please re-test @Eve-wanderi.

**Comment by crcommons** [comment]
Passed QA

**Comment by aoduor** [comment]
Hey folks - just tried testing this out on a  deployment linked to Africaistalking and frontline, it didn't send em out :(. was testing with @jrtricafort @Celestine22

**Comment by aoduor** [comment]
sorry folks, wrong issue. :)
