### ISSUE TITLE
Bug: Export with sortBy + filters fails

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2778]
Description: 
- We do not need the orderBy that comes from filters to select post ids. This caused an exception in some filtering queries that came in

Current behavior: if you add filters the export does not get done (stays pending) because it fails to fetch the list of post ids for headers
Expected behavior: if you use filters the export is generated using the filters. 

Test checklist:
- [x] start an Export  job with filters selected from data mode
- [ ] A CSV should be generated according to your filters 
- [x] start an Export job from settings/export without filters.
- [ ] A CSV should be generated without filters
- [ ] I certify that I ran my checklist

**Comment by caharding** [comment]
@StaicyG can you test that this is working?

**Comment by DafneCalvo** [comment]
I tried to export with filter and the export stays pending again. I am not good at programming and I do not know how to solve it :-S

**Comment by crcommons** [comment]
@StaicyG Are you currently testing this? If not, can you do the following once you're done testing?             

Issues passes QA by passing testing script by QA person 
if an Issue doesn’t pass QA: moved back to Ready for Development by the QA; original Dev should be notified by QA;
If an Issue passes QA: moved to Waiting to Deploy by QA

**Comment by Eve-wanderi** [comment]
Will pick up testing for this.

**Comment by DafneCalvo** [comment]
Hi:

Now I can export, but the category of the name of the community does not export on the CSV.

**Comment by crcommons** [comment]
@DafneCalvo can you provide a little more detail? Are you missing an entire field in your export or are you missing post data for a specific field? Can you also provide your deployment url and the steps you took when exporting to CSV? We will try to reproduce on our end. Thanks!

**Comment by DafneCalvo** [comment]
@crcommons I missing an entire field, concretely "¿Cuál es el nombre de la organización?" (The name of the organization that complete the post).

1. I visit my map (https://resistenciasdigitales.ushahidi.io)
2. I go to data (https://resistenciasdigitales.ushahidi.io/views/data)
3. I click on "Share" and then in "Export filtered data".
4. I visit Setting and then Export data
5. I click on Export history and then in the last CSV Export
6. In that CSV appears the question of the field ("¿Cuál es el nombre de la organización?") I wrote on the survey but not the answers on the different posts

Thanks,

**Comment by crcommons** [comment]
@DafneCalvo Thanks! This is so helpful. I have one more request:

Can you export without filters and let me know if you experience the same issue?

**Comment by DafneCalvo** [comment]
@crcommons I think I do not have that option. When I click on "Share" I only have the option "Export filtered data", although I do not use not filter on the Data.

**Comment by DafneCalvo** [comment]
Thanks! @crcommons

**Comment by crcommons** [comment]
Passed QA
