### ISSUE TITLE
Filters don't work properly with CSV Exports 

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2781]
Is this a filters issue or a csv issue?

### Expected behaviour
When I export to a csv from the data or map view with filters on, the correct data should be in the csv
### Actual behaviour
- not all correct posts are included
- not all post information is included
### Steps to reproduce the behaviour/error
- [ ] Go to data mode
- [ ] filter data down to a number of posts you know you can easily reference (i.e. don't set filters so there are hundreds or thousands of posts that match the filter)
- [ ] share then export data
- [ ] compare exported data with filtered data
#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by caharding** [comment]
Can you please add additional Spec. What is missing? Is it random? 

Do we know if this is likely to create a problem for the DREAMS partners based off your assessment.

**Comment by rjmackay** [comment]
@crcommons any chance you could retest with this branch: https://github.com/ushahidi/platform/pull/2785
I think its likely the fix is related to us failing to properly apply user permissions

**Comment by crcommons** [comment]
@rjmackay It appears that filters are working now, but data is missing from the filtered results. Specifically title and description in the test I ran.

**Comment by jrtricafort** [comment]
@jrtricafort to confirm if this can still be repro'd or if its fixed.

**Comment by rowasc** [comment]
@jrtricafort were you able to repro this?

**Comment by jrtricafort** [comment]
I was not. DREAMS is also reporting that CSV export from Data Mode->Filter is working as expected. Let's close this and reopen if it pops back up.
