### ISSUE TITLE
Organism -> survey creation

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2788]

**Comment by Angamanga** [comment]
@Erioldoesdesign @justinscherer Link to QA:
- http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/settings-surveys.html
- http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/settings-surveys-view.html
- http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/settings-surveys-edit.html

**Comment by Erioldoesdesign** [comment]
Testing in Chrome Version 67.0.3396.87

FE QA notes:

http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/settings-surveys.html

- Survey button has no space between it and the hr/line below:

![Screen Shot 2018-06-23 at 16.42.57.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/f83222b3-f208-4de5-8b13-b31bb4cdc396)

- Copy is #1E232A and should be #777777

http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/settings-surveys-edit.html

- Numbers are off centre:

![Screen Shot 2018-06-23 at 16.46.15.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/760282d2-bd64-4462-a744-7bba62ac31a6)

![Screen Shot 2018-06-23 at 16.46.18.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/4aef433c-7f85-4574-ba6d-9f66d0bedf4e)

- Input labels are not 'bold' (at 600 in the code, should be at 700/800) and there needs to be a few more pixels spacing between the titles and the input boxes:

![Screen Shot 2018-06-23 at 16.47.43.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/9027560e-4f0f-4a3f-bd9c-746d6f8fdbd3)

http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/settings-surveys-view.html

- Labels aren't bold (as above need to be at 700/800)

![Screen Shot 2018-06-23 at 16.50.17.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/9b0bc10e-0e5b-44cd-9c14-5fcd9120fa52)

- These labels:

![Screen Shot 2018-06-23 at 16.51.27.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/093164b3-7d72-4923-88a1-f450250142fd)

Shouldn't be bold! (confusing lol)

Designs:

![Screen Shot 2018-06-23 at 16.51.31.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/12437a0f-5b01-4a42-bcca-c05d638a652b)

**Comment by Erioldoesdesign** [comment]
Looks great! closing this ticket :D

**Comment by rowasc** [comment]
Ref https://github.com/ushahidi/platform/issues/1335
