### ISSUE TITLE
Show 'loading' status on List View on homepage

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#279]
When I click on list view on homepage, it takes a while(about 30 seconds) for the page to populate - with no indication to the user that this is what is happening in the background.

Steps to reproduce
1. Log in
2. Click on "List" View

Expected outcome
- Page populates with a list of all posts added

Actual outcome 
- Page loads different sections of the UI periodically first, then shows a small blank white space with a page number on it, before loading posts a few seconds later(creates the impression there may be no posts)

![screenshot](http://i.imgur.com/K0K1yEP.png)

Recommendation: Maybe add a "Loading" icon just to indicate that this action is going on in the background to avoid confusion/panic on the user's part :)? 

Side note: This may actually be a result of slow connection - perhaps we need some optimization?

**Comment by jshorland** [comment]
Can't reproduce, but good point about optimization
