### ISSUE TITLE
Bug-icons for filters in the filter-dropdown are only visible when logged in

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2794]
### Expected behaviour
Bug-icons for filters should be visible to everybody

![screen shot 2018-04-20 at 09 45 25](https://user-images.githubusercontent.com/8624777/39037087-c174790c-447f-11e8-8c5d-6d996268eaa2.png)
### Actual behaviour
Bug-icons for filters are only visible when logged in
![screen shot 2018-04-20 at 09 46 22](https://user-images.githubusercontent.com/8624777/39037112-cdc3dd1a-447f-11e8-9585-c5270409daf6.png)

### Steps to reproduce the behaviour/error
- Select a number of filters as not logged in. No bug-icons visible
- Log in
- Select a number of filters. Bug-icons visible

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-357

**Comment by caharding** [comment]
What is a bug icon?

**Comment by Angamanga** [comment]
@caharding Updated description with screenshots 👍

**Comment by richard-hutchings** [comment]
Hi @Angamanga ,i'm an outreachy applicant.
if no one is assigned to this can i have shot at it.

**Comment by Angamanga** [comment]
Welcome @richard-hutchings! Please go ahead and work on this issue. You can always reach out if you need guidance. Thank you for your interest in Ushahidi 🎉

**Comment by richard-hutchings** [comment]
Hi @Angamanga , thanks. i have cloned the code, and checked out the platform. would you have an idea which folder/ file  would be my best place to start?

**Comment by Angamanga** [comment]
@richard-hutchings The filter-system is found in this folder: https://github.com/ushahidi/platform-client/tree/develop/app/main/posts/views/filters and the part with the bug-icons should be in this directive and template: https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/views/filters/active-search-filters.directive.js and https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/views/filters/active-search-filters.html

You can always reach out if you need more guidance!

**Comment by richard-hutchings** [comment]
hi @Angamanga Do you know how i can view the UI on this? I don't seem to be able to view the bug problem in Ushahidi platform, the filter boxes seem to work without being logged in.

**Comment by Angamanga** [comment]
Could you send a short video so I can see what is going on? When I am not logged in, it looks like this:
https://recordit.co/EVZKY7kz9G

And when I am logged in (with admin-permissions) it looks like this: 
https://recordit.co/jwXjPSjvtx


So no black-icons which shows what filters are being used when logged out, only when logged in. The filters however, always seem to work.

**Comment by himil-vasava** [comment]
@Angamanga So in short we have to enable these bug-icons for any user(role-member, admin) which was previously enabled for only admin ?

**Comment by Angamanga** [comment]
@himil-vasava It is this div that should be visible to everyone (even not logged in): https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/views/filters/active-search-filters.html#L35. The saved-search button is working as expected. I am not entirely sure why it does not appear, it may be a bug in the directive that affects the uiFilters-variable. The directive can be found here: https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/views/filters/active-search-filters.directive.js

**Comment by Angamanga** [comment]
NOTE: This issue is a side-effect of this issue: https://github.com/ushahidi/platform/issues/2794. When the request fails, the watch-function does not get activated... Removing from community-tasks for now.

**Comment by renujain31** [comment]
I guess this bug still exists! Can I work on this one?

**Comment by rowasc** [comment]
hey @renujain31 I think Anna is working on this? @Angamanga

**Comment by renujain31** [comment]
I have already filed a PR(after discussion with Anna in #4075) which would solve this issue. [Link to PR](https://github.com/ushahidi/platform-client/pull/1549)

**Comment by rowasc** [comment]
oh, awesome. Ok holding for Anna's review then :tada:
