### ISSUE TITLE
Phone numbers should be formatted for use by SMS provider (either as they're saved or before they're sent to SMS provider)

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2795]
### Expected behavior
- The phone numbers sent to SMS provider should either accept a variety of formats, or else it should be clear from the UI which formats they will accept.

### Actual behavior
- Even though the country code was already chosen in the UI, I was only able to send to a US number via Twilio using the formats:
`18885551212` and `1-888-555-1212`   (in the US, this corresponds to: 1 - country dialing code, 888 - area code, 555 - exchange )
The format `8885551212` got a 'failed' result.

### Steps to reproduce the behaviour/error
- configure twilio as dataprovider
- send a message with a targeted survey to phone numbers in various formats

### Proposed fixes:
- Consider breaking this down into sub-issues!
- If number doesn't start with the country_code (this might be trickier than it sounds), then prepend each number with the country code. This could happen on client or backend.
- Strip punctuation from contact number before saving it to contact, this could also happen on client or backend.
AND
- Ensure that phone numbers are correctly formatted for each SMS plugin before being sent out.

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by kinstelli** [comment]
@crcommons  , @Angamanga  - Looking at this again, I wonder if we're maybe just not prepending the country code to the numbers when it's selected in the UI?

**Comment by crcommons** [comment]
@kinstelli We're sending an array of the contact numbers without the country code, then the country-code separately to the DB. 

'''
{
formId: id, 
contacts: $scope.textBoxNumbers, 
country_code: $scope.selectedCountry.country_code
}
'''

I believe you need to prepend the country code on the backend.

**Comment by kinstelli** [comment]
Thanks for clarifying!

Ugh -- a side effect of nonstandardized phone numbers: incoming responses are only matched to outgoing questions if the number format is exactly the same.

In other words, sending to 1-312-555-8888 will be received by that number, but Twilio (for example) replies with 13125558888, so it won't be matched up to the original contact.

Maybe we should at least scrape unnecessary punctuation from outbound messages.

**Comment by crcommons** [comment]
@kinstelli Can you update this issue with the intended fix (i.e. cleaning the number when it comes back from data provider, right?)?

**Comment by kinstelli** [comment]
@crcommons - I updated the issue description with what I _think_ should fix this, but there are three individual pieces, the last of which should probably spawn its own issue.

**Comment by rowasc** [comment]
@willdoran  @kinstelli @crcommons I thought we had agreed on removing validation ( and therefore manipulation) of the contact number in the backend to speed it up?  

If we want to prepend the country code in the backend it has to also run validation and check the format.

**Comment by kinstelli** [comment]
@rowasc - True. We did. I think it might make more sense to prepend the country code to the number _before_ we send it to the API, because of the complexity of doing this on the backend.

**Comment by rowasc** [comment]
@Angamanga yes. I think it varies by provider tho. 
@kinstelli  you might want to add details here about the specific issues for each

**Comment by kinstelli** [comment]
Added PR here that should fix the client part of this issue:
https://github.com/ushahidi/platform-client/pull/1116

**Comment by Eve-wanderi** [comment]
Confirmed the numbers are being Formatted.

![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/1d5bb8f0-2c55-404b-ad88-7cab76157889)
