### ISSUE TITLE
Data providers should allow for no autoresponse to be set, especially for targeted surveys

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2796]
### Expected behaviour
- I'd like to send an SMS that doesn't autorespond to every message, because subsequent messages are probably sufficient

### Actual behaviour
- I can't leave this `autoresponse` setting blank in the Twilio config (not sure if that's a requirement of the Twilio API)
- All of my SMS messages reply with an autoresponse

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by crcommons** [comment]
@kinstelli This seems like a P2. Is that accurate?

**Comment by kinstelli** [comment]
@crcommons - Yes, probably true.
