### ISSUE TITLE
When someone’s card fails, they are NOT automatically kicked off plan.

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2798]
### Expected behaviour
If a credit card payment fails, a deployment should be frozen and the deployer notified. When they try to access their deployment, they should have to enter payment details. If a non admin tries to login, they should be told to tell their admin

### Actual behaviour
When someone’s card fails, they are NOT automatically kicked off plan. There are a number of people using Surveyor who are not paying.

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by rjmackay** [comment]
I think this may be resolved now? I updated settings in Chargebee that were incorrectly set.
