### ISSUE TITLE
Improve unclear user errors when adding field to post type

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#280]
Via @ehersman 

"When I create a Post Type and do location, it asks me for a key. I don't know what that is or means. 

![screenshot](http://i.imgur.com/ZlVeHtl.png)

The whole post type firm field selection and creation process is a bit hard to understand. "

**Comment by jshorland** [comment]
I *believe* this was fixed. Assigning to myself to double check.

**Comment by jshorland** [comment]
Closing. Fixed and no longer relevant.
