### ISSUE TITLE
[Platform Client] HDX Feature Flag

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2804]
### HDX Feature Flag
- To prevent this feature from going out to the general public before it's ready, we need to make sure we have a feature flag for it.
- Other HDX Platform-client Development work will not start without this ticket.

- Test script (flag=FALSE): 
    - When the flag is FALSE, go to the CSV Export tool.
    - You should not see any HDX or HXL references.
    - When the flag is FALSE, go to the user data source configuration for HDX
    - You should not be able to directly access the data source config for HDX.
   	 - You should not be able to find a link to access the data source config for HDX.
    - When the flag is FALSE, the feature's new API calls should not run. This may be done with a helper service that does not run the request if the flag is false.

- Test script (flag=TRUE):
    - When the flag is TRUE, go to the CSV Export tool.
    - You should see the HDX export tool buttons
    - When the flag is TRUE, go to the user data source configuration for HDX
    - You should be able to directly access the data source config for HDX.
   	 - You should be able to find a link to access the data source config for HDX.

- Client considerations: always assume that a flag is off by default while the data is retrieved from the Features API.
- Deploy this as soon as it's done.

## Dependency: 
https://github.com/ushahidi/platform/issues/2815

**Comment by rowasc** [comment]
@Angamanga can you review?

**Comment by jrtricafort** [comment]
Marking this as part of the HDX v0 Epic (in scope for v0). @rowasc Let me know if that's incorrect.

**Comment by Angamanga** [comment]
@rowasc Whats the status of this issue? Is it in development? Or could you deassign yourself until it is?

**Comment by rowasc** [comment]
@Angamanga should go back to you.

**Comment by Angamanga** [comment]
Dev to test this issue

**Comment by rowasc** [comment]
Blocked by testing in #2983.
