### ISSUE TITLE
Undelivered email from reset my password

### ISSUE THREAD

**Issue by francbartoli** [ushahidi/platform#281]
Entering username/email in the *forgotten your password?* the user is landed to the *reset password* but email with temporary token is not delivered.

**Comment by francbartoli** [comment]
I close it as it is to be added on heroku

**Comment by murdoch** [comment]
@francbartoli what do you mean by 'it has to be added on heroku'? I ask because I'm having the same problem, not getting the reset password email.

**Comment by francbartoli** [comment]
@murdoch actually I don't remember quite well but it's likely they were going to migrate the live instance to heroku and I expected that resolved the issue in the meanwhile.

**Comment by murdoch** [comment]
Thanks @francbartoli - I opened an issue, I'll get to the bottom of it. Cheers
