### ISSUE TITLE
HDX Export - Send to CSV

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#2812]
After mapping HXL fields during export (#2519), user can send to CSV, which will include the HXL fields as additional headers.

Aside from a button to send to CSV, this issue is mainly an export/backend task. Most of the designs should be covered in #2519.

**Comment by jrtricafort** [comment]
Moved back to Scoping since Eriol and Juan are confirming comparative prioritization of this versus "Send to HDX via API" #2814.

**Comment by Erioldoesdesign** [comment]
Here's the design prototype screen from the 'export to CSV' modal onwards: https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/20ecc9ee-fef4-4e23-8c68-05bf26ad3a9b/Data-export-HDX-single-survey-29?fullscreen

**Comment by jrtricafort** [comment]
@rowasc @willdoran This is done. It was originally scoped as part of v1 but we did it as  part of v0. Alright if I close?  ;)
