### ISSUE TITLE
Add HDX Designs to Pattern Library

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#2816]
HDX - Add HDX designs from #2397 to Pattern Library.

Prototype: 
https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/?fullscreen

**Comment by jrtricafort** [comment]
@caharding I don't really know how to write up the scope for this one. Could you take a stab at filling this out?

**Comment by caharding** [comment]
Going to pass to @Erioldoesdesign to map write out this ticket in a bit more detail just outlining each screen once they are finalized.

**Comment by Erioldoesdesign** [comment]
@Angamanga I'm guessing that breaking out individual FE tickets would be useful here?

I can go ahead and add each as an item in the main description here but I have a feeling we'll split into individual tickets!

**Comment by Angamanga** [comment]
@Erioldoesdesign Thats fine to start with, I have tomorrow set out for speccing/breaking-out-issues ✂️ ✂️ ✂️

**Comment by caharding** [comment]
@Angamanga just checking that this is completely broken down now

**Comment by Angamanga** [comment]
@caharding Yes it is!
