### ISSUE TITLE
[Platform Client] HXL Export - Prevent duplicate attributes

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2818]
### Description: 
 - A way for dropdown menus to ‘know’ when a previous ‘attribute’ has been used and ‘grey-out’ the option so it cannot be selected twice.

**Comment by jrtricafort** [comment]
@rowasc What stage should this be in currently? Ready for Design?

**Comment by rowasc** [comment]
Ready for spec. Moving

**Comment by Angamanga** [comment]
@rowasc Does this mean each field can only have an attribute each? Or is it one attribute per survey? Or export?

**Comment by rowasc** [comment]
@Angamanga this would be that a single attribute should not be used more than once per tag.

**Comment by Angamanga** [comment]
Closing this issue, its covered in this issue https://app.zenhub.com/workspace/o/ushahidi/platform-client/issues/1120
