### ISSUE TITLE
Members are authorized to edit post types

### ISSUE THREAD

**Issue by francbartoli** [ushahidi/platform#282]
When logon as member the user is allowed to *edit post type* from **Add Post** but receives an *Access Denied* when he/she attempts to save changes.
From an authorization perspective the user should not see the link of editing post types, should just allowed to choose the post type to be used

**Comment by rjmackay** [comment]
- Need to hide 'edit post type' menu in settings if users aren't authorized to edit
- Hide from 'Add post' screen too
- Confirm other settings menu items are hidden as appropriate too

**Comment by rjmackay** [comment]
Fixed by https://github.com/ushahidi/platform-client/commit/97b41e55b4c2e2c700a726159dec6291d286e2a5
