### ISSUE TITLE
Incoming Messages for Targeted Surveys are not being filtered based on the Keywords.

### ISSUE THREAD

**Issue by Eve-wanderi** [ushahidi/platform#2825]
### Expected behaviour

Using the SMSsync Integrations If a user adds in Keywords e.g "Ushahidi" all incoming messages to the platform should be filtered or disabled so that users can only see messages with the world ushahidi.

### Actual behaviour
Currently all messages are being sent to the platform regardless if user has added the keyword.

### Steps to reproduce the behavior/error
1. Add in configurations for SMSsync 
2.Add in a keyword i.e this will work to only show messages with that keyword.
3. Send a text message to yourself without including this keyword in your text.
4. Log into the platform i.e http://targetedsurveytesting.v3-qa.ush.zone/views/data
5. Click on the data view and confirm if you can see this text message.

#### Where does this issue happen?
http://targetedsurveytesting.v3-qa.ush.zone/views/data

See screenshots below.
![Messages.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/8253256d-6cc4-4fb3-832e-d98f59e3bc48)

![Screenshot_2018-04-23-17-53-04-80.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/dd1c1e1d-97b4-4dc4-a115-15960f7cb8d9)

**Comment by justinscherer** [comment]
I have no idea where this came from @kinstelli . @Eve-wanderi can you clarify where this came from?

**Comment by kinstelli** [comment]
I'm not sure this makes sense to implement. I think this will actually be counterproductive to targeted surveys. Any thoughts @jrtricafort, @caharding ?

**Comment by caharding** [comment]
This is a problem with SMSsync not the platform. SMSsync should only route messages with a given keyword. @rjmackay think we should reach out to Henry?

**Comment by jrtricafort** [comment]
Closed won't fix
