### ISSUE TITLE
Resolve Routing in Migration Branch

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2826]
### Requirements
- implement a <Link> component that allows us to swap it out for react-router in the future
- Route component?

**Comment by Angamanga** [comment]
@crcommons Whats the status of this issue? Is it in development?

**Comment by crcommons** [comment]
Note: As long as we migrate from the smallest components upward, we won't need to change any routing except <Link>, which is done. Once we have migrated a section that has sub-routes, we can implement React-Router in that section of the code (all sub components will be migrated at this point, so we won't have to worry about how to route to angular components other than through clicks/links).
