### ISSUE TITLE
Unable to send a Targeted survey via sms from the platform

### ISSUE THREAD

**Issue by Eve-wanderi** [ushahidi/platform#2827]
### Expected behaviour
When a user creates a targeted survey from the platform and sends this to valid numbers. Recipients should receive this survey via sms.

### Actual behaviour
Platform does not send out the survey to the recipients. 

### Steps to reproduce the behaviour/error

Prerequisite **Ensure SMSsync is enabled from your phone** 
1. log into the  Test Server
URL: http://targetedsurveytesting.v3-qa.ush.zone
User: qa@ushahidi.com
Password: testing
2. Go to settings>Surveys> New Survey> Send a targeted Survey vis SMS
3. Fill in  the name of the survey
4.Fill in your target audience i.e ensure you use valid phone numbers.
5.Add your Questions.
6.Publish your survey.          
                     
![outgoing messages](https://user-images.githubusercontent.com/36038029/39145492-83e00a2e-473c-11e8-8ac8-6ec8b1615163.png)

**Comment by kinstelli** [comment]
@Eve-wanderi - Can you try this with the country code as part of the phone number? I had issues with this last week, but if I include the country code, it seems to work fine.

**Comment by Eve-wanderi** [comment]
Yaap this works when i put the country code. Though we should let users know the format they'l use even if its through a validation message since most users will assume they dont have to add in the country code.

**Comment by kinstelli** [comment]
@Eve-wanderi  - Okay, then this is the same as #2795 - but thank you for looking into it with another provider. I wasn't able to test elsewhere.

**Comment by Eve-wanderi** [comment]
Yes that is the same.. Ur welcome Guess we can close this now.
