### ISSUE TITLE
Install/Set up react-intl

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2828]
### Requirements
- follow set up https://github.com/yahoo/react-intl and https://medium.freecodecamp.org/internationalization-in-react-7264738274a0
- attempt to make it so that existing translations don't need to be re-translated/duplicated
  - either by compiling different files into one or using existing files
- Come up with recommendations on pluralization, dates, numbers, etc...

**Comment by rowasc** [comment]
:/ I am not sure what to spec here.
