### ISSUE TITLE
Push DREAMS features to all deployments

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2831]
Make sure the DREAMS CSV and SMS features went to every deployments on this list including the test deployment https://dreamsic.ushahidi.io/ @declan isn't seeing it there https://docs.google.com/spreadsheets/d/1cxzOJdR58x3EI6hDSCGnay7lPB0S62-MfwNokt3-jRU/edit#gid=1663680881

**Comment by rowasc** [comment]
@caharding
DONE. 

Note: this deployment wasn't in the list the day we deployed (at least, checking the history, it doesn't look like it), so I didn't add it to the script initially.  

Is there any other new deployment or any other deployment that is not seeing the changes but should?


@dexwakhu can you check if it's on now? Please clear cache just in case.

**Comment by dexwakhu** [comment]
Thanks Romina. Hate to have you do this again but we added some deployments
in Uganda:

https://superwoman.ushahidi.io/
https://mcu.ushahidi.io
https://wvu.ushahidi.io/

**Comment by rowasc** [comment]
no worries. Solved. Can you check? @dexwakhu

**Comment by dexwakhu** [comment]
Super, thanks.
