### ISSUE TITLE
Data Import failure handling improvements

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2839]
### Expected behaviour
In the event that I have a CSV file to import that has, say, 1500 posts, and i've got one record that fails to upload for one reason or the other e.g inability to assign a post to multiple categories/field options ( see #2593), I'd rather have the importer skip the records it can't upload, upload everything else for me, and them notify me **_at the end_** with details why certain records failed to upload.

**_OR_**
Notify me of the failed upload immediately, and then cancel the import altogether. 

### Actual behaviour
I'm trying to upload 1500 posts, it seems to be failing at record 50/1500. It successfully uploads 50 posts, and then stops there, giving me this failure notice

![screen shot 2018-04-25 at 16 37 02](https://user-images.githubusercontent.com/721918/39249629-beb3a19e-48a7-11e8-98ef-73b98fdc2dcc.png)
 
And then remaining on this screen here, despite the failure to continue uploading
![screen shot 2018-04-25 at 16 34 20](https://user-images.githubusercontent.com/721918/39249113-96309c5a-48a6-11e8-9158-a946dcd30424.png)

Been more than 30 minutes since i started this upload - it hasn't moved. Left me all like...

![hanging](http://forgifs.com/gallery/d/227964-2/High-five-left-hanging.gif)

### Steps to reproduce the behaviour/error
You can ping me directly to give you the files to test.

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by caharding** [comment]
@kinstelli do you know if this was added in our CSV improvements? Or needs to still be speced?

**Comment by kinstelli** [comment]
@caharding - I haven’t seen this, so i think it still needs spec’ing and doing.

**Comment by kinstelli** [comment]
Note that this is for imports not exports

**Comment by caharding** [comment]
Ahh good point. Added it to the improved CSV epic for prioritization later.

**Comment by rowasc** [comment]
Closing in favor of #1448 , referenced it in the issue description so we have this context too
