### ISSUE TITLE
Unable to create categories right after creating one

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#284]
Steps to reproduce
1. Log in as an admin user
2. Click on settings, and then categories
3. Create a new category and save it

Expected outcome
 - I should get a prompt about successful category creation and redirected back to the category list page

Actual outcome
- I get no prompt, and remain on the same page with a huge white blank space in the middle as follows
![screenshot](http://i.imgur.com/wK27Hu3.png)

**Comment by willdoran** [comment]
Incorrect redirect post save - fixed.
