### ISSUE TITLE
[Platform Client] HDX Export configuration settings

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2840]
### Description
The user needs to add metadata to their dataset before uploading it to HDX

DESIGNS:  https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/1c15cc61-5a2e-4dbe-8018-a7bd2b559d40/Data-export-CSV-landing-page-HDX-single-survey-20/?fullscreen

### QA-checklist
*Assumes HDX featureflag is ON*
- Go to settings-> data-export-> HDX-view
- Select a number of fields and assign tags and attributes
- Click on "upload to HDX"
- [ ] Modal should appear, click on Upload to HDX
- [ ] The detailed metadata-screen should appear (https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/1c15cc61-5a2e-4dbe-8018-a7bd2b559d40/Data-export-CSV-landing-page-HDX-single-survey-20/?fullscreen)
- [x] The source is preloaded with the name of the deployment
- [x] The organization is loaded with all the user's organizations
- [ ] The License list is loaded from the backend
- [ ] The maintainer is a text field, not a dropdown as in the designs
- Select 'private' mode
- Add a title, source and select organisation
- Add the maintainer 'angamanga'
- Select a license
- Click on 'upload to hdx'
- [ ] you should be moved to the "in progress" screen and a notification should be displayed: https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/7dac3889-0383-4c74-b670-1bb7223460f2/Data-export-CSV-landing-page-HDX-single-survey-19

Design ticket: https://github.com/ushahidi/platform/issues/2811

Platform API: https://github.com/ushahidi/platform/issues/2841

**Comment by Angamanga** [comment]
Questions
@Erioldoesdesign or @rowasc What should be in the dropdowns for metadata? Does the user add that themselves or do we fetch it from somewhere?![Screen Shot 2018-04-28 at 16.53.17.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/39aa9ab4-9f5b-4637-87fb-3c0b5e8d1c1d)

Where should the link "Read more about licences" point to?

**Comment by Erioldoesdesign** [comment]
Pretty sure we fetch this default but it's then able to be changed via drop down

**Comment by rowasc** [comment]
Correct. The client only fetches this and the user can change the default

**Comment by Angamanga** [comment]
@rowasc Could you please review?

**Comment by rowasc** [comment]
@Angamanga after " The detailed metadata-screen should appear [link]" I would add 
- The source is preloaded with the name of the deployment
- The organization is loaded with all the user's organizations
- The License list is loaded from the backend
- The maintainer is a text field where we load the username in HDX , fetched from the API. The user is free to change this to another value.

**Comment by Angamanga** [comment]
@rowasc Thanks, added that so moving to "ready for dev"

**Comment by Eve-wanderi** [comment]
Can we change this Error message?  to show "You need to select some fields to export "

![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/1466847f-Error6482-4ec9-a104-113b39ac178a)

**Comment by Eve-wanderi** [comment]
@rowasc   Yes we can change it to that. Retested and can confirm the issues have now been fixed. However i still feel like we need to increase the time for issue number 3 dont think users will mange to read all that information within few seconds.

**Comment by rowasc** [comment]
@Eve-wanderi great. Thanks. I opened https://github.com/ushahidi/platform/issues/3026 to track the error message that disappears too quickly. Please add the steps to reproduce in that issue.
