### ISSUE TITLE
Retest categories permissions after refactor

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2846]
A landed a small refactor in https://github.com/ushahidi/platform/pull/2738

Test checklist:
- [x] Pre-requisite: Logged in, in creation page for a category. Example: http://csvexportsforever.v3-qa.ush.zone/settings/categories/create
- [x] Create a category and set `Who can see this category?` to Admin
- [x] Create a child category and check `Who can see this category?` shows permissions are managed by parent
- [ ] Both categories saved correctly
- [ ] Create a category and set `Who can see this category?` to everyone
- [ ] Create a child category and check `Who can see this category?` shows permissions are managed by parent
- [ ] Both categories saved correctly
- [ ] On post data view, in filters: restricted categories are visible when logged in as admin
- [ ] On post data view, in filters:  restricted categories are not visible when logged out
- [ ] Add categories to a surveys category fields
- [ ] Open the post create page for that survey: restricted categories are visible when logged in as admin
- [ ] Open the post create page for that survey:  restricted categories are not visible when logged out

**Comment by rjmackay** [comment]
@Eve-wanderi @aoduor this should be deployed now. Could someone QA please?

**Comment by Eve-wanderi** [comment]
When adding a Child category and i select a Parent on the field for "This category is a child to field" i get an error "Role must match the parent category". Yet there is nowhere i have selected the roles for this child Category Please  see attached screenshot.


![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/117264b9-3a5f-492e-8d63-4ff2dac33ab5)
