### ISSUE TITLE
mysqli::__construct(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by evchristelis** [ushahidi/platform#2847]
I tried to follow the "Installing the API" instructions and when I reach http://192.168.33.110/ I get a json response but not the a successful one.
`{
    "errors": [
        {
            "status": 2,
            "title": "mysqli::__construct(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO)",
            "message": "mysqli::__construct(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO)",
            "class": "Database_Exception",
            "file": "/home/vagrant/Code/platform-api/application/classes/Database/MySQLi.php",
            "line": 59,
            "trace": [
                {
                    "file": "/home/vagrant/Code/platform-api/application/classes/Database/MySQLi.php",
                    "line": 138,
                    "function": "connect",
                    "class": "Database_MySQLi",
                    "type": "->",
                    "args": []
                },
                {
                    "file": "/home/vagrant/Code/platform-api/vendor/ohanzee/database/src/Database/Query.php",
                    "line": 251,
                    "function": "query",
                    "class": "Database_MySQLi",
                    "type": "->",
                    "args": [
                        1,
                        "SELECT `users`.* FROM `users` WHERE `users`.`id` IS NULL LIMIT 1",
                        false,
                        []
                    ]
                },
                {
                    "file": "/home/vagrant/Code/platform-api/application/classes/Ushahidi/Repository.php",
                    "line": 192,
                    "function": "execute",
                    "class": "Database_Query",
                    "type": "->",
                    "args": [
                        {
                            "last_query": null
                        }
                    ]
                },
                {
                    "file": "/home/vagrant/Code/platform-api/application/classes/Ushahidi/Repository.php",
                    "line": 69,
                    "function": "selectOne",
                    "class": "Ushahidi_Repository",
                    "type": "->",
                    "args": [
                        {
                            "users.id": null
                        }
                    ]
                },
                {
                    "file": "/home/vagrant/Code/platform-api/src/App/Tools/KohanaSession.php",
                    "line": 45,
                    "function": "get",
                    "class": "Ushahidi_Repository",
                    "type": "->",
                    "args": [
                        null
                    ]
                },
                {
                    "file": "/home/vagrant/Code/platform-api/application/classes/Controller/Api/Index.php",
                    "line": 62,
                    "function": "getUser",
                    "class": "Ushahidi\\App\\Tools\\KohanaSession",
                    "type": "->",
                    "args": []
                },
                {
                    "file": "/home/vagrant/Code/platform-api/vendor/kohana/core/classes/Kohana/Controller.php",
                    "line": 84,
                    "function": "action_get_index_collection",
                    "class": "Controller_Api_Index",
                    "type": "->",
                    "args": []
                },
                {
                    "function": "execute",
                    "class": "Kohana_Controller",
                    "type": "->",
                    "args": []
                },
                {
                    "file": "/home/vagrant/Code/platform-api/vendor/kohana/core/classes/Kohana/Request/Client/Internal.php",
                    "line": 97,
                    "function": "invoke",
                    "class": "ReflectionMethod",
                    "type": "->",
                    "args": [
                        {
                            "request": {},
                            "response": {}
                        }
                    ]
                },
                {
                    "file": "/home/vagrant/Code/platform-api/vendor/kohana/core/classes/Kohana/Request/Client.php",
                    "line": 114,
                    "function": "execute_request",
                    "class": "Kohana_Request_Client_Internal",
                    "type": "->",
                    "args": [
                        {},
                        {}
                    ]
                },
                {
                    "file": "/home/vagrant/Code/platform-api/vendor/kohana/core/classes/Kohana/Request.php",
                    "line": 997,
                    "function": "execute",
                    "class": "Kohana_Request_Client",
                    "type": "->",
                    "args": [
                        {}
                    ]
                },
                {
                    "file": "/home/vagrant/Code/platform-api/httpdocs/index.php",
                    "line": 38,
                    "function": "execute",
                    "class": "Kohana_Request",
                    "type": "->",
                    "args": []
                }
            ]
        }
    ]
}`
I am deploying on ubuntu 16.04 LTS x64.

Local setup with Vagrant (https://www.ushahidi.com/support/install-ushahidi#installing-for-development)

**EDIT**
I have manually added the database credentials to the file /application/classes/Database/MySQLi.php and now I get another error
`{
  "errors": [
    {
      "status": "Fatal Error",
      "title": "Uncaught TypeError: Argument 1 passed to Kohana_Kohana_Exception::handler() must be an instance of Exception, instance of ParseError given in /home/vagrant/Code/platform-api/vendor/kohana/core/classes/Kohana/Kohana/Exception.php:84\nStack trace:\n#0 [internal function]: Kohana_Kohana_Exception::handler(Object(ParseError))\n#1 {main}\n  thrown",
      "message": "Uncaught TypeError: Argument 1 passed to Kohana_Kohana_Exception::handler() must be an instance of Exception, instance of ParseError given in /home/vagrant/Code/platform-api/vendor/kohana/core/classes/Kohana/Kohana/Exception.php:84\nStack trace:\n#0 [internal function]: Kohana_Kohana_Exception::handler(Object(ParseError))\n#1 {main}\n  thrown",
      "class": "ErrorException",
      "file": "/home/vagrant/Code/platform-api/vendor/kohana/core/classes/Kohana/Kohana/Exception.php",
      "line": 84,
      "trace": [
        {
          "function": "shutdown_handler",
          "type": "::",
          "class": "Kohana_Core",
          "file": "/home/vagrant/Code/platform-api/vendor/kohana/core/classes/Kohana/Core.php",
          "line": 0,
          "params": [],
          "args": []
        }
      ]
    }
  ]
}`

**EDIT#2**
When I try to run the composer migrate I get 

Script

 phinx migrate -c application/phinx.php handling the migrate event returned with an error

                                                                               
  [RuntimeException]                                                           
  Error Output: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Ko  
  hana_Kohana_Exception::handler() must be an instance of Exception, instance  
   of ParseError given in /var/www/html/isooko/vendor/kohana/core/classes/Koh  
  ana/Kohana/Exception.php:84                                                  
  Stack trace:                                                                 
  #0 [internal function]: Kohana_Kohana_Exception::handler(Object(ParseError)  
  )                                                                            
  #1 {main}                                                                    
    thrown in /var/www/html/isooko/vendor/kohana/core/classes/Kohana/Kohana/E  
  xception.php on line 84

**Comment by rowasc** [comment]
Hi. 
For the database configuration, you should not need to edit application/classes/Database/MySQLi , the correct way to configure it is to use the .env file that you copied from .env.default and change the settings there, specifically the keys starting with DB_ . 

For the `Uncaught TypeError: Argument 1 passed to Kohana_Kohana_Exception::handler() must be an instance of Exception, instance of ParseError ` error, can you let us know what version of PHP you are using?

**Comment by evchristelis** [comment]
Hello @rowasc ,
I know I shouldn't edit the application/classes/Database/MySQLi but I tried in order to make the platform bypass the problem. Initially, I have edited the .env file with my DB configuration. I am using php 7.0.

**Comment by rowasc** [comment]
Hi. I apologize as your last comment didn't get a timely response, and that's on me. 

We have updated our documentation and it should be easier to follow now for various installation methods
https://app.gitbook.com/@ushahidi/s/platform-developer-documentation/ but please let us know here or in our gitter channe https://gitter.im/ushahidi/Communityl if you run into issues following it and we'll try our best to help.

Thanks
Romina
