### ISSUE TITLE
CSV Doesn't Download After > 1 hour

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2852]
### Expected behaviour
CSV exports should happen within an hour
### Actual behaviour
User attempted to export to CSV. Checked back 4 hours later and they were still in progress. Checked back the following day and they were still in progress.
![in-progress-export-csv.png](https://images.zenhubusercontent.com/5a7084ec4b5806bc2bc4e02b/76ac8ce9-e921-4f12-9a88-8dd9da1bfed3)
### Steps to reproduce the behaviour/error
Deployment 1
- Deployment is https://acdc.ushahidi.io/views/map
- Need to find out tier still
- Status is "in progress"

Deployment 2
#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by kinstelli** [comment]
@crcommons - This appears to be a similar issue to the previous one, where the signature wasn't being computed correctly due to the domain format. Any new CSV exports should work for them now.

**Comment by crcommons** [comment]
Checking with deployment to be sure it works. Will update issue depending on their answer

**Comment by crcommons** [comment]
Closing issue because CSV exports now work. They're now experiencing the issue in #2838.
