### ISSUE TITLE
Display CSV Export expected wait time in UI

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#2853]
**Context:**
Currently, wait times for CSV are opaque for users. They click "export to CSV" and expect to immediately receive the CSV download link. However, our wait times are much longer than they expect (up to ~1 hour for basic, 5-7 minutes for premium). 

**Rationale:**
While we work to improve those times, we should also communicate the wait times to the users in some way, so they know what to expect. This will reduce surprise frustration and help improve signal-noise ratio on actual CSV bug reports.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-353

**Comment by jrtricafort** [comment]
Tagging @justinscherer here for UX input/copy guidance.

**Comment by justinscherer** [comment]
Two different messages. One for paid, one for unpaid. 

**Paid**
![settings export export all in progress w- notification paid](https://user-images.githubusercontent.com/29209303/39327941-d6d83b7c-4956-11e8-98ca-1e04c41946db.png)


**Unpaid**

![settings export export all in progress w- notification unpaid](https://user-images.githubusercontent.com/29209303/39327945-dc211a04-4956-11e8-930c-968cc43066ad.png)


On a separate note, an hour is probably too long, regardless of how much they pay us and I don't know if we should differentiate between paid/unpaid for the speed of the feature.

**Comment by jrtricafort** [comment]
Assigning to @crcommons for prioritization input. This looks like a low-lift enhancement to partially address UX related some recent CSV export bugs.

**Comment by crcommons** [comment]
I agree it's a p2. I'll have anna take a look tomorrow if she has a chance.

**Comment by Angamanga** [comment]
@crcommons I am moving this back to ready for spec, ok?
