### ISSUE TITLE
[Platform Client] Buttons for export to csv and to hdx

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2854]
### Description
Add buttons to the hdx-export-screen that:
1. Starts a "normal" csv-export with selected fields
2. Starts an upload to hdx
3. Cancels the tagging

#Test-script
*Assumes hdx-feature-flag is on*
- Go to settings->data-export->hdx-export
- [ ] There should be 3 buttons in the end of the table, all enabled
-  Click upload-button without any fields selected
-  [ ] A warning should be displayed https://drive.google.com/open?id=1jOcCBxFDkrGKKs04MppkDocjPNBGpzSP
- Click on export-button without any fields selected
-  [ ] A warning should be displayed https://drive.google.com/open?id=1jOcCBxFDkrGKKs04MppkDocjPNBGpzSP
- Assign tags to a number of fields
- Click on "Export to csv"
- [ ] A confirm-modal should be visible (doesnt need to do anything at this stage, it is its own issue)
- Click on 'go back and check' in the modal
- Click on "Upload to HDX"
- [ ] A confirm-modal should be visible (doesnt need to do anything at this stage, it is its own issue)
- Click on 'go back and check' in the modal
- Click on cancel 
- [ ] You should return to initial export choice screen with the 'Export all, select fields and assign tags etc..' buttons

**Comment by Angamanga** [comment]
Questions:

@Erioldoesdesign 
- What should be the default state of the buttons before any fields are selected? Disabled? Or give a warning-label that the user has to select fields?
- What should happen when I click on the "cancel"-button? Should I return to the initial data-export-screen? (https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/9528cb6c-dcb2-43ef-aa90-0dd0842cff6a/Data-export-CSV-landing-page-HDX)

**Comment by Erioldoesdesign** [comment]
@Angamanga The buttons should give an error if:

- No fields have been selected (assigning 1 tag will automatically check that field to be 'exported' so that action will check that field.
So this error: https://drive.google.com/open?id=1jOcCBxFDkrGKKs04MppkDocjPNBGpzSP

No disabled state - so users who choose to scroll and check out button options first can do so before doing any data tagging etc.

- Cancel is return to initial export choice screen with the 'Export all, select fields and assign tags etc..' buttons

**Comment by Angamanga** [comment]
Thanks! @Eve-wanderi Could you double-check the QA-checklist, is anything missing you would like to have there?

**Comment by Angamanga** [comment]
@rowasc Could you please review?

**Comment by rowasc** [comment]
@Angamanga I'm confused . How do we let the user download normal CSV files if we give them a warning for not selecting anything in HDX?

**Comment by Angamanga** [comment]
@rowasc Its just a warning, not a blocker to assign tags/attributes. But the warning is needed since it would suck if someone works through the fields and has forgotten to add the api-key and need to do it all again :/

**Comment by Angamanga** [comment]
@rowasc oh wait I was in the wrong screen in my head. Yes, you are true, the warning should not be there for csv-export

**Comment by Angamanga** [comment]
@rowasc hehe, third comment, no it makes sense. They still have to select and assign fields with hdx. The 'normal' field-export is done in another view. This one is only for hdx-fields. If they dont select anything, they won't have anything to export.

**Comment by Angamanga** [comment]
@Eve-wanderi Ready for QA :)

**Comment by Eve-wanderi** [comment]
Unfortunately i am seeing a diffrent error message from the one reuested in the Requirement.

When i click on the option for upload to a HDX Account without filling in any details i get this error

![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/023c05a8-e895-41e2-880f-196549087727)

However from the Requirements this is the error i should get.

https://drive.google.com/open?id=1jOcCBxFDkrGKKs04MppkDocjPNBGpzSP

**Comment by Eve-wanderi** [comment]
Confirmed this is now fixed.

![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/2038ef01-4aa9-409c-926a-3e1e1c43bfb6)
