### ISSUE TITLE
[Platform Client] Add a notification-window when upload has started

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2856]
### Description
Once the user has selected and tagged their fields, added metadata and selected upload to HDX, the user is moved to the export-screen with this screen: https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/7dac3889-0383-4c74-b670-1bb7223460f2/Data-export-CSV-landing-page-HDX-single-survey-19

### QA-checklist
Pre-requisite: complete all steps to generate an HXL export.
- Click the "Submit to HDX account" button in the details page
- [ ] A notification bar should appear, letting the user know that we are uploading the file.

**Comment by Angamanga** [comment]
@rowasc Could you please review?

**Comment by rowasc** [comment]
@Angamanga I'd add a simple qa checklist
- Pre-requisite: complete all steps to generate an HXL export.
- Click the "Submit to HDX account" button in the details page
- [ ] A notification bar should appear, letting the user know that we are uploading the file.

**Comment by Angamanga** [comment]
@rowasc Thanks! Added so moving to ready for dev.

**Comment by Angamanga** [comment]
@Eve-wanderi Ready for QA :)

**Comment by Angamanga** [comment]
Closing this in favour of #2840
