### ISSUE TITLE
HDX User Permission Requirements

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#2858]
In addition to putting the HDX Integration features behind a feature flag (#2815) we should also restrict all HDX-related features to users who have the following permissions:

+Manage Posts
+Manage Settings
+Bulk Data Import

This issue covers both API and Client work, unless otherwise stated.

### Test script with HXL feature flag enabled:
Without an authorization token
- [ ] Request all/any endpoints under /hxl
    - [ ] Should result in `401: unauthorized` 
With an authorization token for a user without the permissions `Manage Posts`, `Manage Settings` or `Bulk Data Import`: 
- [ ] Request all/any endpoints under /hxl
    - [ ] Should result in `403: forbidden` 
With an authorization token with the correct permissions: 
- [ ] Requests to /hxl should result in a status code according to the action (200 OK, 201 created, 422 for validation errors, etc)

### Endpoints to test (wip list)
- [ ] /hxl
- [ ] /hxl/licenses

**Comment by jrtricafort** [comment]
Moved to Ready for Spec because this issue does not require design, and scoping is completed in description above.

**Comment by rowasc** [comment]
Moving to `in development`. This will be open/in development while we move forward with other endpoints and can test accordingly.

**Comment by rjmackay** [comment]
@rowasc I generally err towards fewer permissions for simplicity. If the naming doesn't make sense, just rename it to "Data import and export" / `DATA_IMPORT_EXPORT`

**Comment by rowasc** [comment]
ok cool, will do.
