### ISSUE TITLE
Create post and Save buttons

### ISSUE THREAD

**Issue by julianar** [ushahidi/platform#286]
shouldn't the 'create post' also save it? finding that the second step to 'save' introduces additional friction.  "yeah, that save button needs to be moved somewhere a little more visible
we've had a couple of guys here with us point out the same issue
you need to scroll up a little, its a small button the right hand bar"

**Comment by aoduor** [comment]
More feedback from Nekesa on the same:

"Add post' at the bottom of the new post page is confusing as it does not all one to add the current post but takes me to a new post. Please relabel or remove. God is watching you."

**Comment by sebm90** [comment]
Linda gave the same feedback.

**Comment by aoduor** [comment]
More feedback from David Kimaru

"When I add the links, at the bottom of the page, I have to scroll up to get the ‘Save’ button. In fact, I confused the ‘Add’ button with the save button. I guess the text for adding another link can be changed to something like ‘Add another link’ do that it is clear that one is adding a link and not the post.
On the footer of that page, there is ‘Add Post’ that is confusing. It does not allow users to save what they have just entered, but instead it is giving the option of creating a new post. I would suggest:
	Remove the button,
	Make it save the post
	Change the wording to ‘Create a new post’ or something similar"

**Comment by sebm90** [comment]
Other users also suggested removing the "Add post" buttons when the user gets to the "Add post" page.

**Comment by rjmackay** [comment]
There is a design for how this should work in the pattern library: sidebar is supposed to scroll with  the page. Need to recreate this in the client.
