### ISSUE TITLE
Only allow survey duplications for regular surveys, not targeted surveys

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2863]
### Expected behaviour
When I navigate to a targeted survey, I should not see the button to duplicate the survey
### Actual behaviour
When I navigate to a targeted survey, I can attempt to duplicate a survey but it fails
### Steps to reproduce the behaviour/error
Navigate to a targeted survey, attempt to duplicate
#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-352

**Comment by rowasc** [comment]
@Angamanga I'm untagging this from the Community Task group since targeted surveys are an enterprise feature that's not yet well documented for the OSS community.. Please feel free to overrule me if you disagree 😄
