### ISSUE TITLE
Write technical documentation for CREES & YODIE

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#2865]
## Task
COMRADES requires documentation for both CREES and YODIE (it is also required for the FB Bot but that is covered in issues [2741](https://github.com/ushahidi/platform/issues/2741) and [2740](https://github.com/ushahidi/platform/issues/2740)). 

The audience could roughly be described as "power user" but the documentation shouldn't be uber-complex. The goal will be to give a potential user of the COMRADES platform, a straightforward set of instructions for how to configure the features. Assume that they will download the code and need to connect all the pieces on a local machine. 

## Resources 
There are some existing resources that can be re-used or drawn from as documentation. 

- CREES is already fairly well documented: see the [CREES website](https://evhart.github.io/crees/); the [Googlesheets plugin](https://chrome.google.com/webstore/detail/crisis-event-extraction-s/jekdamaeeejebcccbgleijlfamjcbilc?hl=en); or [pages 17-18 of the first report to the EU for the COMRADES project](https://drive.google.com/open?id=0B0fInrbWAUMsSjdUbVc0MFBmVTQ) (link is for internal GDrive).
- YODIE documentation can also be found in the first report to the EU for COMRADES (pages 15-17). Additional documentation on the YODIE service can be found on the [informational website maintained by the University of Sheffield](https://gate.ac.uk/applications/yodie.html). 
- See also the ["technical documentation" folder on the internal GDrive](https://drive.google.com/drive/u/1/folders/0B0fInrbWAUMsWk41NjBUSVhKdDA), which contains a variety of early documents and notes around establishing both YODIE and CREES.

### Timeline
I would like to see this done by end of May. Early June is doable.

**Comment by Shadrock** [comment]
Would love an update on this so we can close it out.

**Comment by Shadrock** [comment]
Bump on this. @willdoran I believe you've written these up. If you can point me to them, I can close this out.

**Comment by jrtricafort** [comment]
@willdoran to follow up here.

**Comment by willdoran** [comment]
@jrtricafort Shared files with @Shadrock he'll review.

**Comment by rowasc** [comment]
sent to "In review " column for @Shadrock  to confirm (this is a new setup to be able to track progress on non technical tasks or docs that need review)

**Comment by rowasc** [comment]
closing since these COMRADES docs were delivered
@Shadrock feel free to reopen if necessary :)
