### ISSUE TITLE
Incoming messages are always set to default 'pending' in messages table.

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2866]
### Expected behaviour
- Incoming messages should say 'received' in the messages table
### Actual behaviour
- Incoming messages always say 'pending' in the messages table. 

*Note: this is the default value for that table column, per the DDL.*

This doesn't break any functionality, but it makes debugging a little confusing.

### Steps to reproduce the behaviour/error
- Send an incoming message, either via Postman, or via an actual message to a configured SMS provider.
- Note in the database that this message is set to 'pending'

#### Where does this issue happen?
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [x] Ushahidi's QA environment

**Comment by prondubuisi** [comment]
Hello @rowasc is this still an issue? If it is can you help with a direct link to set up the platform locally so I can Work on it

**Comment by rowasc** [comment]
uh,  I think it got solved in the last merge and I forgot to tag it. Sorry ! 
https://github.com/ushahidi/platform/issues/3221 Maybe this one could be a good start instead? 

https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/vagrant-setup this is the setup guide :)
