### ISSUE TITLE
Confusing behaviour of private/hidden/public fields in tasks

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2868]
For background, here's the the "bug" that was previously reported by a user. Turned out to  not actually a bug but a UX misunderstanding, which we have captured here. https://github.com/ushahidi/account-management/issues/15

Its not clear to the users what is actually happening when selecting the switches in tasks. I experimented  with this and it made no real sense. This is what happens to the survey when different combinations of the switches are on/off:

![screen shot 2018-04-27 at 15 06 09](https://user-images.githubusercontent.com/8624777/39364276-bb310d18-4a2d-11e8-83bc-3962e4efb5a5.png)

*When switching "this task is for internal use only" and "show this to everyone when published" is turned off*
- When I add a post as a logged in admin, I see the task
- When I add a post as a logged out user, I don't see the task nor its fields
- After publishing a post, a logged out user does not see the task nor the values

*When switching "this task is for internal use only" is turned on and "show this to everyone when published" is turned off*
- When I add a post as a logged in admin, I see the task
- When I add a post as a logged out user, I don't see the task nor its fields
- After publishing a post, a logged out user does not see the task nor the values
 
*When switching "this task is for internal use only" and "show this to everyone when published" is turned on*
- When I add a post as a logged in admin, I see the task
- When I add a post as a logged out user, I dont see the task nor its fields
- After publishing a post, a logged out user I see the task and the values when looking at a post in data-view

*When switching "this task is for internal use only" is turned off and "show this to everyone when published" is turned on*
- When I add a post as a logged in admin, I see the task
- When I add a post as a logged out user, I see the task and its fields
- After publishing a post, a logged out user I see the task and the values when looking at a post in data-view
- This is the only way of making it possible for not-logged-in users to fill in the fields belonging to a task, still, all values are visible to everybody.

To make it possible for a not-logged in user to add to the task-values when responding to a survey and at the same time NOT see the published values from other users, I had to go into each field and make the responses private. But the users still see an alert saying "This task will be visible when post is published."

![screen shot 2018-04-27 at 15 11 05](https://user-images.githubusercontent.com/8624777/39364307-d0047dc4-4a2d-11e8-96b1-15d243ccc438.png)

This came up when working with https://github.com/ushahidi/account-management/issues/15.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-351

**Comment by crcommons** [comment]
@justinscherer @Erioldoesdesign I wanted to flag this new issue for you.

**Comment by jrtricafort** [comment]
Tagging @justinscherer just for awareness.
This still needs to be triaged.
