### ISSUE TITLE
Calendar dropdown in Create Post view is unstyled

### ISSUE THREAD

**Issue by sebm90** [ushahidi/platform#287]
![image](https://cloud.githubusercontent.com/assets/5349387/9247475/ef7388e4-41bb-11e5-823f-dee2c6288b1c.png)

**Comment by aoduor** [comment]
Some additional information on this. It would be helpful to have the calendar highlight today's date, and the time to default to server timezone time.

**Comment by jshorland** [comment]
This is fixed in mustang. closing.
