### ISSUE TITLE
CSV should be feature flagged when ported to Lumen Branch

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2870]
### Expected behaviour
- CSV feature is feature flagged so that it can be disabled 

### Actual behaviour
- CSV is not feature flagged in master but should be when porting feature to Lumen

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by jrtricafort** [comment]
@willdoran should this be part of the CSV Epic or Lumen Epic?

**Comment by willdoran** [comment]
@jrtricafort I think Lumen, I've add it to that one.

**Comment by jrtricafort** [comment]
Excellent. Is the scope for this issue to feature flag the entire CSV export feature? Or just the new changes that were implemented recently (i.e. have "old CSV export" enabled for anyone who doesn't require "new CSV export"). By "new CSV export" I mean the work captured here: https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2399

**Comment by willdoran** [comment]
@jrtricafort Yes I think that is a good definition, I believe Lumen should the "old" csv and the "new" should be the one feature flagged.

**Comment by jrtricafort** [comment]
@willdoran I think @rjmackay said that CSV has actually already been ported to Lumen, but it might be too late (?) to feature flag this and restore old code.

Questions for us on this issue:
- Is this something we need to prioritize for this cycle or no? If so, what priority level is this? CSV Stabilization has been marked as a P2 in our Cycle Planning.
- Is this something we can even do?

**Comment by rjmackay** [comment]
The existing CSV export code has been ported to lumen pretty much as-is, so it still relies on an external service. We removed the previous CSV export APIs. So if we feature flag CSV we would be disabling CSV export entirely for users who previously had that features (even if it broke sometimes).

I'm not sure if thats what was intended? or if the intention was to switch to the old CSV API when the flag was disabled? (not really possible anymore) or if we're talking about feature flagging the refactor in #2787?

**Comment by jrtricafort** [comment]
> or if the intention was to switch to the old CSV API when the flag was disabled? (not really possible anymore) 

I believe that was the intention, but @willdoran can probably clarify better than I can.

**Comment by willdoran** [comment]
@rjmackay @jrtricafort If the previous version is gone then we can't do much unless we want to restore the old endpoint. If we intend to fix the behaviour in a future release so that it is available more readily for FOSS users then we can revisit at that time but this can be closed.
