### ISSUE TITLE
When sharing deployment map links externally, image and description should appear on social media

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#2871]
### Expected behaviour
User shares link to their deployment map on social media, image and description appear.
### Actual behaviour
User shares link to their deployment map on social media, but image and description do not appear. In browser Developer Tools, Meta tags do not appear to be filled out correctly.

(https://images.zenhubusercontent.com/5ac5411e4b5806bc2bcdb0c4/95fc1081-4b80-46cb-bfa2-d1f47d716363)![Screen Shot 2018-04-30 at 12.39.37 PM.png]

(https://images.zenhubusercontent.com/5ac5411e4b5806bc2bcdb0c4/d380b05b-11d7-460f-a474-634033212494)

Example: https://twitter.com/IranProtestsMap/status/1002272182649720832

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**From customer: Iran Protests Deployment**
There is also another bug that I did not reported. Meta tags in Ushahidi web application
is not filled correctly. It seems that HTML Meta tags&#39; placeholders are not filled
properly.
Because of this issue when sharing a link in any social media, image and description is
not loaded, makes the link ineffective.![Screen Shot 2018-04-30 at 12.39.31 PM.png]
See screenshots above.

**Comment by willdoran** [comment]
@jrtricafort is this explicitly a link to a post? Could you share an example link?

**Comment by jrtricafort** [comment]
@willdoran Example provided in the description above and also here: https://twitter.com/IranProtestsMap/status/1002272182649720832

Spoke w @rowasc - the cause of this problem is how we generate our site using JS. To fix this, a most likely solution would involve using some sort of Pre-Renderer. It is nontrivial.

**Comment by jrtricafort** [comment]
Moving to Icebox because requires Server-Side rendering, which we would like but not happening soon.

**Comment by rowasc** [comment]
#3011 
#3012 
Related to these other two issues. Closing as duplicate.
