### ISSUE TITLE
[Platform API] Return HDX license list

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2873]
## TASKS
- [ ] Add a list of available licenses to the platform API from here https://data.humdata.org/about/license 
- [ ] New endpoint: /hxl/licenses to return the static list of licenses that HDX supports. 
```
    "results": {
            {
                "code": "cc by-sa". 
                "name": "Creative Commons Attribution-ShareAlike ",
                "link": "http://...", 
            },
            {
                "code": "cc by-sa". 
                "name": "Creative Commons Attribution-ShareAlike ",
                "link": "http://...", 
            }
    }
```

Acceptance criteria: 
- Postman collection demonstrating usage

**Comment by rowasc** [comment]
@kinstelli  @willdoran Can you review?

**Comment by willdoran** [comment]
@rowasc Will we pass through a request to HDX side or do we have to hardcode?

**Comment by rowasc** [comment]
@willdoran sadly we have to hardcode, there's no api for it

**Comment by rjmackay** [comment]
@rowasc how / where in the UI is this set? Are we setting this per export or per deployment?
Because it seems to me that data licensing is kind of a deployment wide concern. Though maybe its too late to change now

**Comment by rjmackay** [comment]
Ok. We should flag that for a future HDX iteration as something to test/check. ie. do deployment owners want to be able to restrict the license on their data/prevent relicensing?

**Comment by jrtricafort** [comment]
@rjmackay I heard that we may want to revisit the Permission requirements to export to HDX. This can be flexible, I just want to understand what our rationale is before making any changes. Definitely want to weigh whatever is 1) technically most sensible and 2) best user experience. @rowasc is starting a slack channel for us to discuss more in depth.
