### ISSUE TITLE
[Platform API] Export history list should include HXL tags for HXL exports

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2875]
TODO: 

When the client requests the export history

Test script: 
- [ ] Open the csv export screen (/settings/data-export)
- [ ] Click on the "History" tab
- [ ] You should only see exports that have not expired. 
- [ ] Pending exports should not have an expiration date
- [ ] The export jobs have a Job ID, a created date, a status, and a user-friendly expiration date 
- [ ] Each HXL Export has the HXL tags assigned by the user in it
- [ ] The export jobs should be sorted in reverse chronological order

Test script 2: request export
- [ ] Open the csv export screen (/settings/data-export)
- [ ] Click on the "History" tab
- [ ] You should only see exports that have not expired. 
- [ ] Click on the "Export tab" and request an HXL Export
- [ ] Click on the history tab
- [ ] You should see all exports that you saw in step 3 (all non-expired exports) + the export job you requested
- [ ] Each HXL Export has the HXL tags assigned by the user in it
- [ ] Wait until the export job finishes (around ~5 minutes) 
- [ ] Check the history tab. You should see the new export change its status to "Finished" 
- [ ] The new HXL Export has the HXL tags assigned by the user in it

Modifications: 
- [ ] Add `hxl_tags` to the /exports/jobs result 
- [ ] `hxl_tags` field  format
```
          {
            "tag_id": 0,
            "tag_name": "string",
            "tag_description": "string",
            "hxl_attributes": [
              {
                "description": "string",
                "name": "string",
                "id": 0
              }
            ]
          }
```

Aha! Link: https://ushahiditeam.aha.io/features/PROD-350

**Comment by rowasc** [comment]
@kinstelli  @willdoran Can you review?

**Comment by willdoran** [comment]
@rowasc Approved, spec cover behaviour

**Comment by jrtricafort** [comment]
@rowasc We actually may be able to descope this entirely. I'll include in our discussion w Shadrock.
