### ISSUE TITLE
Users find the concept of "Post Types" confusing

### ISSUE THREAD

**Issue by sebm90** [ushahidi/platform#288]
The difference between post types and categories is not clear.

**Comment by francbartoli** [comment]
@sebm90 I think this is very clear within the community of Ushahidi users. Probably the lack of relations between "Post Types" and "Categories" is a misunderstanding for people.

IMHO "Categories" should apply only on certain "Post Types"

**Comment by aoduor** [comment]
Some additional information on this from David Kimaru of BRCK

"It would be helpful if users are informed that they need to select the type of the post

On the same page, when one clicks the button ‘Add Post’ and assuming that they have not selected the post, they need to get the information that they need to select the type."

**Comment by aoduor** [comment]
I think we probably need to do a better job of explaining this with tooltips perhaps?

Post types essentially are what we used to refer to as Custom forms in Ushahidi version 2

**Comment by jshorland** [comment]
I'm closing this in favor of mustang design changes and category research happening on basecamp.
