### ISSUE TITLE
Update install documentation for lumen branch

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2888]
Update install documentation for lumen

**Comment by rowasc** [comment]
@rjmackay do you need me to write this and test it? I have some steps in a doc from when we set it up

**Comment by rjmackay** [comment]
@rowasc that would be amazing. There are existing docs here: https://www.ushahidi.com/support/install-ushahidi

@aoduor was authoring some other docs but I forget where those live, so check in on that too.

**Comment by rowasc** [comment]
ok super cool, I'll pick this up during cycle6 :D

**Comment by rowasc** [comment]
eh so I never re-added this to a cycle. Sorry, it got lost at some point in the placeholder. 
@jrtricafort I need to add this for cycle 8 , ffor myself.

**Comment by rowasc** [comment]
Sent updates for Angie, but we're doing this as part off the 2nd stage of docs/comms

**Comment by aoduor** [comment]
Update: Will get these up on craft asap.

**Comment by rowasc** [comment]
Update: I will be able to finish the install docs on monday, need to wrap up some other tickets today
