### ISSUE TITLE
Time field editing doesn't respond as expected

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#289]
Steps to reproduce
1. Create a post
2. Scroll down to date/time field
3. Attempt to edit time to 13:15

Expected outcome
- The hour and minute fields should populate with "13" and "15" respectively

Actual outcome
- The hour and minute fields append only add one number, and not both. However, they respond to clicking on the arrows at the top and bottom.

Recommendation: maybe make this field uneditable and have the user use the scroll buttons to make their time change?

**Comment by aoduor** [comment]
More information from another user - Eric Asiago

"There’s also an issue with the dates on a post. They keep running ahead."

**Comment by willdoran** [comment]
Ok, this does indeed appear to be fixed by the new datepicker :)
