### ISSUE TITLE
Data Missing from CSV Exports

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2894]
### Expected behaviour
When I export to CSV, all columns I expect are there, but data is missing from some columns
### Actual behaviour
I expect all data to be included in download
### Steps to reproduce the behaviour/error
I haven't been able to reproduce on QA (It's probably happening but there's just way too much data to know if we're missing any) But here are the steps to reproduce from a customer:

Here are the steps she provided to reproduce the bug:

- I visit my map (https://resistenciasdigitales.ushahidi.io)
- I go to data (https://resistenciasdigitales.ushahidi.io/views/data)
- I click on "Share" and then in "Export filtered data". --Note that the data is not filtered
- I visit Setting and then Export data
- I click on Export history and then in the last CSV Export
- In that CSV appears the question of the field ("¿Cuál es el nombre de la organización?") I wrote on the survey but not the answers on the different posts

It was reported in github in issue #2838

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by crcommons** [comment]
![imagen](https://user-images.githubusercontent.com/36405677/39522523-c8c756e2-4e12-11e8-8c3b-b46d445e04ac.png)

**Comment by Angamanga** [comment]
@willdoran Who needs to do QA for this?
