### ISSUE TITLE
Ob_clean in CSV formatter should be preceded by ob_get_length

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2900]
### Expected behaviour
We don't get a warning/error when running the exporter in lumen branch

### Actual behaviour
We get an error when running the exporter  in lumen branch
  `ob_clean(): failed to delete buffer. No buffer to delete  `
#### Where does this issue happen?
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain):  lumen

**Comment by rjmackay** [comment]
I'm assuming this only happens for an empty CSV?

**Comment by rowasc** [comment]
@rjmackay no, I think it was a side effect on the lumen branch since it didn't happen in develop before. 
Closing as fixed.
