### ISSUE TITLE
Ensure Platform Servers Support IPv6

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#2904]
Looks like platform servers currently do not support IPv6, which as we recently discovered with TenFour can result in app updates getting rejected from Apple.

http://ipv6-test.com/validate.php >> https://dale.ushahidi.io

![screenshot 2018-05-03 11 26 38_preview](https://user-images.githubusercontent.com/91811/39592808-1cb4649a-4ec5-11e8-845c-6e611f2b9e11.png)

**Comment by dalezak** [comment]
**Supporting IPv6-only Networks**
> Starting June 1, 2016, all apps submitted to the App Store must support IPv6-only networking. A majority of apps will not require any changes as IPv6 is already supported by NSURLSession and CFNetwork APIs. However, if your app utilizes IPv4-specific APIs or hard-coded IP addresses, you will need to make changes. Be sure to test for IPv6 compatibility before submitting your app to the App Store for review.

https://developer.apple.com/support/ipv6/

**Comment by tuxpiper** [comment]
added necessary DNS records for production

**Comment by dalezak** [comment]
![screenshot 2018-05-03 15 41 36_preview](https://user-images.githubusercontent.com/91811/39604231-84c74598-4ee8-11e8-82f6-401b816abfae.png)

Nice work @tuxpiper 👍
