### ISSUE TITLE
Create list of industry standard best practices

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2905]
- As a Dev team, we have a lot of ideas of what can and should be incorporated into the rewrite to get our code up to industry standards, so we're attempting to put them all in one document so that we can figure out how and when to incorporate them into the rewrite.

Consolidate all ideas here:

https://drive.google.com/open?id=1ChXGCuASdDYcVwE_c_G1-jMlKILdFSyUg0ksQIaumvs

**Comment by rowasc** [comment]
We do not need to continue with this since we are following existing standards by google and the modifications are noted in the spreadsheet in this ticket already

cc @crcommons per our discussion
