### ISSUE TITLE
Add hdx-tags to export-history

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2913]
#### Description
List all tags and attributes that was part of an export in export-history

*Designs:* https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/d204535d-c71b-4c3e-ab55-df51d1bdc949/HDX-Export-history

#### TODO:
1. Get all tags and attributes from where <-- check from where, are they covered by the export-jobs request? Or do we get them from another end-point
2. Add a new sub-title and list the tags and attributes in bug-icons

#### QA-checklist:
- Go to data-export->HDX-export
- Assign some fields with hdx-tags and attributes, remember which fields, tags and attributes
- Export CSV
- Go to export-history
- [ ] There should be a sub-title with a list of the tags and attribute for the made export
- [ ] The same tags and attributes should be listed as the ones you assigned the fields with

Aha! Link: https://ushahiditeam.aha.io/features/PROD-347

**Comment by willdoran** [comment]
@Angamanga I'd estimate this as a 2 does that make sense?
