### ISSUE TITLE
mcrypt is discontinued form PHP 7.2

### ISSUE THREAD

**Issue by nirabpudasaini** [ushahidi/platform#2916]
### Expected behaviour
Should be able to download and install the platform

### Actual behaviour
Installing the php mcrypt mod is not possible with Ubuntu 18.04 and php 7.2

### Steps to reproduce the behaviour/error
On a fresh install of Ubuntu 18.04 install PHP, nginx and Mysql. Then try installing the php mod mcrypt and it will not be available.

#### Where does this issue happen?
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)

#### It is ready for development when
- [ ] Has all (probable) dependencies identified
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by angelrr7702** [comment]
It still present this problem .. php mcrypt no supported because it is not maintained and there are some security issue relate to it. what the ushahidi community have in mind to fix these issue ?

**Comment by rowasc** [comment]
Hi.Now that we did the lumen upgrade and are using php7.1  we were able to remove this platform dependency. It hasn't hit the release branches yet but it's merged in `develop` if anyone wants to give it a try . 

https://github.com/ushahidi/platform/pull/3303

Re PHP version: We are currently supporting php 7.0 - 7.1 ,

**Comment by rowasc** [comment]
The new release will not have this anymore.  Merged in develop https://github.com/ushahidi/platform/blob/develop/composer.json . 
Moving to waiting to deploy so I generate the release packagge.

**Comment by rowasc** [comment]
Closing as this was merged .
