### ISSUE TITLE
Provide list of deployments that will have HDX Feature Flag enabled

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#2918]
These deployments will have HDX Feature Flag enabled:
 - https://comrades-stg.ushahidi.com/views/map

**Comment by jrtricafort** [comment]
@Shadrock just tagging you here for awareness. Let me know if there's any other deployments that need HDX turned on besides COMRADES deployment pasted above.

**Comment by rowasc** [comment]
Thanks Juan!
