### ISSUE TITLE
[Platform API] HXL Meta Data Table

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2936]
### Overview
In order to capture user entered HXL Meta data we will create a new Entity and associated Table HXL Meta Data. This table should be associated with an Export Job. Currently, it is not intended that this information will be reused but in future it may be the case that it will be split between reusable fields, however, this is not not designed and does not require current consideration.

### UX Ref
<img width="1191" alt="screen shot 2018-05-11 at 4 17 10 pm" src="https://user-images.githubusercontent.com/2434401/39942723-c739be3e-5536-11e8-9036-7e697c8ad62d.png">

### Requirements
Table: hxl_meta_data

1. Fields:
 - private: `'boolean', ['default' => true]`
 - dataset_title: 
                `'text',
                ['null' => false, 'limit' => 255,]`
 - license_id: foreign_key 
               `'license_id', 'hxl_license', 'id'`
 - export_job_id: foreign_key 
               `'export_job_id', 'export_job', 'id'`
 - user_id: foreign_key
                `'user_id', 'users', 'id'`
 - organisation: 
                `'text',
                ['null' => false, 'limit' => 255,]
  - source:
                `'text',
                ['null' => false, 'limit' => 255,]
  - maintainer:
                `'text',
                ['null' => false, 'limit' => 255,]
 - created: `'integer', ['default' => 0]`
 - updated: `'integer', ['default' => 0])`

*Comments:*
> The user id is available on the export_job but inclusion here is intended to avoid a future situation where we may wish to either reuse the information or access it from another interface. The user is the logical centrum around which this data balances

**Comment by willdoran** [comment]
@rowasc changed this slightly, can you recheck

**Comment by rowasc** [comment]
APPROVED .

**Comment by kinstelli** [comment]
~Sorry, but where are Source, Organization, Maintainer, and License stored for each export job?~

REVIEWED. APPROVED.

**Comment by rowasc** [comment]
@willdoran @kinstelli not urgent, but is `hxl_metadata` the table name?  I didn't notice it until now but it's not there in the ticket

**Comment by willdoran** [comment]
@rowasc good question
hxl_meta_data?

**Comment by willdoran** [comment]
We should make a standard format for table definitions to catch those things
