### ISSUE TITLE
[Platform API] HXL Meta Data Endpoint

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2937]
### Overview
The HXL Meta Data entity will should be createable via the API for completeness

### Requirements
1. Validation
  - private: 
     - boolean
     - required
  - dataset_title: 
     - text
     - required
     - length: varchar 255
  - organisation: 
     - text
     - required
     - length: varchar 255
  - source: 
     - text
     - required
     - length: varchar 255
  - maintainer: 
     - text
     - required
     - length: varchar 255
  - license_id: 
     - license id must exist
     - required
  - export_job_id: 
     - export_job id must exist
     - required
  - user_id: 
     - user id must exist
     - required
2. Authorisation
  - Only owners are allowed to change
  - All users can search 
3. Formatting 
  - Uses standard entity formater
4. Usecase
  - Create
5. Verbs
 - POST < store>

**Comment by rowasc** [comment]
@willdoran is there a reason we allow a text_medium for title? I think it might be too much.  How about a varchar with maybe 256? This is the title that users in HDX will see when they look for datasets so I think it's reasonable to keep it short .


In addition to this, we might want to save organization that the dataset belongs to, as well as a resource id that can be associated to the dataset.

**Comment by willdoran** [comment]
@rowasc Updated spec

**Comment by kinstelli** [comment]
@willdoran  Is there other info besides organization that we potentially need in this endpoint? 
Does this store to the HXL specific table?
Also, is this just a POST endpoint?

**Comment by rowasc** [comment]
@willdoran hey sorry I still don't see `organization` there , but maybe it was missed in the comment. Can you confirm if we will have it or if you think we dont need to / why?

**Comment by rowasc** [comment]
ah
>In that table there would be hdx_organistion:value and the other reusable settings

So this is technically correct, we do save defaults there for when the user does a new export, but that's just a default, not the value that matches the dataset itself. To make this clear: organization is a value that can change for each user. For instance, I'm part of Ushahidi and Comrades in hdx.

**Comment by willdoran** [comment]
ah!!! I didn't realise, fixed can you recheck

**Comment by rowasc** [comment]
APPROVED

**Comment by kinstelli** [comment]
Can we include the verbs of this endpoint in the spec? :)

**Comment by rowasc** [comment]
I'd support that :D @willdoran  @kinstelli

**Comment by rowasc** [comment]
APPROVED

**Comment by kinstelli** [comment]
Okay, POST is great. APPROVED post-hoc.

**Comment by rjmackay** [comment]
Noting some context here, because I had great trouble understanding *why* this endpoint was read only.

> It’s an endpoint to save what the user requested for their export (ie. to which organisation to upload, which title to use) , we don’t show [the metadata] to them at the moment/at least not v0

^ It's important to capture intent in our specs. Even if its repeating other existing specs
