### ISSUE TITLE
[Platform API] Extend Export Endpoint, Entity and Table to accept optional HXL mappings

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2938]
### Overview
In future users will be able to optionally include HXL mappings, in addition an include_hxl flag. Since there will now be two distinct destination for the export we will capture those as two flags. 

`send_to_browser` and `send_to_hdx`, the rationale for these two setting is as follows:
1. A single text field would require text logic comparison which requires hardcoding or knowledge of contents
2. It is probable that in future as Platform is connected to a wider ecosystem of other platforms the target/destination options will increase. In that circumstance, writing a migration from a text field to a foreign key would involve much more significant overhead than migrating a pair of boolean fields, however, if this expands beyond these two it should become an independent related entity.
3. The distinction between exports is not type it is target/destination we need to capture that information
4. It is possible that at some point the user may be able to send to multiple targets at once, for this reason at least and only one of these must be true - in the future it may be that both can be true but for now only one.

The endpoint will receive an optional value containing mappings between form_attributes and HXL_Tags, HXL_Attributes. Currently, we will need to create a link table for the form_attributes and the HXL Tags/Attributes as well as a storage field on the export job for the HXL row so it will only be computed once.

### Requirements
1. Extend Export Job table to include the following fields:
  - include_hxl: boolean, default: false
  - send_to_browser: boolean, default: false
  - send_to_hdx: boolean, default: false
  - hxl_heading_row: json, null: true

2. Extend Export Job Validation
Fields:
  -  send_to_hdx 
    - must be true **if** send_to_browser is false
  -  send_to_browser 
    - must be true **if** send_to_hdx is false
  - include_hxl: boolen required only if send_to_hdx is true
Notes: The new fields validation should only run if the hdx feature flag is TRUE

3. Migrate existing Export Jobs
 - For existing Export Jobs the send_to_browser field must be set to true for completenes and so that existing export jobs pass validation.

4. Create form_attribute_hxl_attribute_tag  link table
- form_attribute_id: foreign key, form_attribute_id, form_attributes, id
- hxl_attribute_id: foreign key, hxl_attribute_id, hxl_attributes, id
- hxl_tag_id: foreign key, hxl_tag_id, hxl_tags, id
- export_job_id: foreign key export_job_id, export_job, id

**Comment by willdoran** [comment]
@rowasc @kinstelli Please consider the naming scheme of the table fields and confirm you are ok with them while reviewing.

**Comment by kinstelli** [comment]
@willdoran I posted this to the other ticket, but I deleted it and moved it here :) 

Since the process of sending the job to HDX is potentially fragile, we ought to have a field to store whether it got sent -- and ideally, (assuming HDX is nice about sending success/failure responses), a success/failure about whether HDX received it. 

I'm not sure if HDX responds with other important data, like a reference ID, or last updated date, or something similar, but if we're going to send updates to the same data in the future, then we might need to reference this info if someone sends a future update of the same query.  (I'm not sure if this is in another spec somewhere, but allowing a user to reference old exports so they can send updated versions of the same query will probably be necessary, if it's not already spelled-out in the spec).

**Comment by willdoran** [comment]
@kinstelli @rowasc 
> ending the job to HDX is potentially fragile

Do the current statuses we have cover this or should we add hdx_failed, hdx_succeeded or can we infer that from the destination + status.

> if HDX responds with other important data,

This is important, @rowasc do you know if we cover this? and if we don't how would we raise it up to @jrtricafort?

**Comment by kinstelli** [comment]
@willdoran  - Now I'm thinking that if HDX sends back a reference id on success, (Not sure because I can't find their docs right now... _Where are you hiding, HDX API docs?_), this might be sufficient to prove success/failure of an upload, as well as serving as the basis for referencing this in the future.

**Comment by rowasc** [comment]
@kinstelli that sounds good. 
We might need to extend our status. 
This is a typical response (success) for a resource being created
```
{
    "help": "http://data.humdata.org/api/3/action/help_show?name=resource_create",
    "success": true,
    "result": {
        "cache_last_updated": null,
        "package_id": "48385d74-b714-47d1-95c3-8e96bcceb658",
        "datastore_active": false,
        "id": "cf7907a1-54aa-4c04-867e-927a5da0df86",
        "size": null,
        "revision_last_updated": "2018-05-12T16:24:49.761236",
        "state": "active",
        "hash": "",
        "description": "",
        "format": "CSV",
        "hdx_rel_url": "http://9c6ce555783b33ede9e5-bcb451e57babffefd4392ded05701cc9.r73.cf2.rackcdn.com/hdx/countrylatlons.csv",
        "tracking_summary": {
            "total": 0,
            "recent": 0
        },
        "mimetype_inner": null,
        "url_type": "api",
        "mimetype": null,
        "cache_url": null,
        "name": "package-csv-lat-lon",
        "created": "2018-05-12T16:24:49.856759",
        "url": "http://9c6ce555783b33ede9e5-bcb451e57babffefd4392ded05701cc9.r73.cf2.rackcdn.com/hdx/countrylatlons.csv",
        "last_modified": null,
        "position": 3,
        "revision_id": "a922b47c-78aa-44f7-8d2e-3a85e6286a5e",
        "resource_type": "csv"
    }
}
```

I'm thinking We need to save the `package_id` for a resource to be able to add to them

**Comment by rowasc** [comment]
@willdoran Create form_attribute_hxl_attribute_tag link table is missing a reference to the export_id I think?

**Comment by willdoran** [comment]
@rowasc Will add now

**Comment by rowasc** [comment]
@willdoran  @kinstelli  sorry I’m a bit confused. Should we have hxl_heading_row even when we also have the `form_attribute_hxl_attribute_tag` table ?

**Comment by willdoran** [comment]
@rowasc Sorry I should have been more clear, we need to store the computer hxl row for the export once right? So that we can reuse it for subsequent chunks? or do we not?

**Comment by rowasc** [comment]
ahhh. Yea no that's completely correct. We `could` recalculate it since we know what maps to what.. but that would be awful. 
Makes sense .

**Comment by rowasc** [comment]
@willdoran ok sorry second dumb question: `hxl_mappings: json not required` is this needed now that we have form_attribute_hxl_attribute_tag ?

not having a bright day  over here

**Comment by willdoran** [comment]
@rowasc good catch, fixed

**Comment by rowasc** [comment]
@willdoran @kinstelli I believe the validations are needed here, but to be clear those would be enforced in the validator's code not at the table level  (same thing we do for targeted_surveys when we check that  `everyone_can_create` and `targeted_survey`  are both true for it to work and validat ethat)

**Comment by kinstelli** [comment]
Ok. @willdoran  Reviewed:Approved.

**Comment by willdoran** [comment]
@kinstelli good catch on migration, should we set the send_to_browser to true for existing rows in the DB for completenes?

**Comment by rowasc** [comment]
>For existing Export Jobs the send_to_browser field must be set to true for completenes and so that existing export jobs pass validation.

Nice addition. Thanks. 


APPROVED

**Comment by kinstelli** [comment]
Yes. Reviewed. APPROVED.

**Comment by rowasc** [comment]
@kinstelli @willdoran I think should we check the feature flag ('hxl') for validation. Otherwise, we will break export jobs when the HDX flag is off. 
Does that sound sane? I know we only want to deploy to comrades initially but still

**Comment by kinstelli** [comment]
I'm cool with feature flagging all the things.

**Comment by willdoran** [comment]
@rowasc Yes, good catch, can you update the spec with that

**Comment by rowasc** [comment]
updated!

**Comment by rowasc** [comment]
@willdoran @kinstelli One more thing. We need to require include_hxl to be true when send_to_hdx is true. The hxl tags are required for datasets when you are creating them, so if we don't receive include_hxl, we are just generating junk because it would mean the client does not intend to add the hxl headers that we will then use to generate the 'tags' field on HDX uploads

**Comment by kinstelli** [comment]
Yep, @rowasc, that's another good catch.

**Comment by willdoran** [comment]
@rowasc good catch will add

**Comment by jrtricafort** [comment]
@willdoran Since this is for the future, can I move this to the HDX v1 Epic instead of v0?

**Comment by willdoran** [comment]
@jrtricafort This one is done, closing
