### ISSUE TITLE
[Platform Export Broker] Update final success status

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2943]
### Overview

Export Broker should explicitly return a status indicating that its success is having saved the file to the CDN.

### Requirements
- [x] Change `SUCCESS` to `EXPORTED_TO_CDN` for status returned to Platform API on completion of save of export file to CDN

**Comment by willdoran** [comment]
@kinstelli can you review?

**Comment by kinstelli** [comment]
APPROVED.
