### ISSUE TITLE
[Platform API] HXL Meta Data Endpoint - READ 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2969]
### Overview
The HXL Meta Data endpoint will have a `show` method in the controller that matches the 
`GET /hxl/metadata/:job_id` request

This is needed so the client can check if a metadata object exists before they let the user create one, and to show the data the user has set up in their metadata screen if they have. 

### Requirements
1. Routing:
    - `GET /hxl/metadata/:job_id` routes to `show` method.
    - Since jobs and metadata are a 1:1 relation, we use the job id rather than a metadata id.
    - Return a 404 if there's not metadata yet, *not an empty result*
2. Authorisation (reuse authorizer from create)
    - Only owners are allowed to create
    - ~All users~ Only owners can search/read
3. Formatting 
    - Uses standard entity formater
4. Usecase
    - ReadHXLMetaData
    - Override getEntity logic to fetch meta data based on job id, not metadata id
5. Verbs
    - GET <show> 

## Semantic corrections to existing POST endpoint

Meta data is a 1:1 relation with export jobs:
1. Metadata doesn't need a primary key, only the job id
2. Create could, and possibly should, be a `PUT /hxl/metadata/:job_id` (to match GET)

**Comment by rjmackay** [comment]
If HXL metadata is a child of the job, the URL should be `GET /hxl/job/:id/metadata`.
The write endpoint should change to `POST /hxl/job/:id/metadata` too

Other spec points:
- Permissions: Same authorizer, allow only owner +admin access?
- Data structure: I assume thats straight forward/same as whatever we returned after create?
