### ISSUE TITLE
Uploading data to HDX results in blank error, data not uploaded

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#2976]
### Expected behaviour
After I tag fields and click "Submit to HDX" I should get confirmation that the CSV was created and then be able to view the data in the HDX portal.

### Actual behaviour
After I tag fields and click "Submit to HDX" I get this screen for about 10 seconds:
![Screen Shot 2018-05-21 at 11.38.43 AM.png](https://images.zenhubusercontent.com/5ac5411e4b5806bc2bcdb0c4/e20b617c-4ccb-4e94-9f66-3c0ce18a7d26)
Then I get this screen - a blank error message where the CSV progress notification used to be. Also, when I try to find the data in HDX it is not there
![Screen Shot 2018-05-21 at 11.00.54 AM.png](https://images.zenhubusercontent.com/5ac5411e4b5806bc2bcdb0c4/f878d7a2-1d71-41d9-af39-372e17b85f66)

Export history shows CSV exports failing:
![Screen Shot 2018-05-21 at 11.48.06 AM.png](https://images.zenhubusercontent.com/5ac5411e4b5806bc2bcdb0c4/40d2a206-4480-41ab-90b4-ed4660946307)

Interestingly:
- When I just do a regular CSV export (with no HDX upload) the CSV export works correctly.
- **When I do CSV export with HXL tags (but not HDX upload),  the CSV export appears to work correctly but then when I open the resulting CSV file, I don't see any of the HXL tags I added. I think this may be a related bug. Linking here:**  https://github.com/ushahidi/platform/issues/2977

### Steps to reproduce the behaviour/error
1. Log into https://comrades-hdx.ushahidi.com/
2. Configure API key to your HDX account. 
3. "Export and tag data" -> "Assign tags" -> assign the tags
4. Click "Upload to HDX account"
4. Fill in metadata fields and click Submit to HDX
5. Wait and watch the notification bar turn into the blank error.

#### Where does this issue happen?
https://comrades-hdx.ushahidi.com/

**Comment by willdoran** [comment]
I'm pretty sure this is fixed but will retest
