### ISSUE TITLE
CSV files from HXL tag+export do not appear to include the actual HXL tags

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#2977]
### Expected behaviour
After I add HXL tags and export to CSV, I should see those tags in the resulting CSV file.

### Actual behaviour
After I add HXL tags and export to CSV, I do not see those tags in the resulting CSV file. See attached screenshot of entire csv output. This looks different from what Romina demo'd last week, which included the tags in a separate column. 
![Screen Shot 2018-05-21 at 12.06.54 PM.png](https://images.zenhubusercontent.com/5ac5411e4b5806bc2bcdb0c4/cfb38562-37c0-4303-89bd-2cf6ebecb769)

### Steps to reproduce the behaviour/error
1. Log into https://comrades-hdx.ushahidi.com/
2. Configure API key to your HDX account.
3. "Export and tag data" -> "Assign tags" -> assign the fields
4. Click "Export to CSV"
5. Wait for the export to complete, then open the CSV file. See lack of HXL tags.

#### Where does this issue happen?
https://comrades-hdx.ushahidi.com/

**Comment by willdoran** [comment]
Fixed. Re-testing export to hdx.
