### ISSUE TITLE
Filter option switches when filter is applied 

### ISSUE THREAD

**Issue by sebm90** [ushahidi/platform#298]
1. Go to All Posts page
2. Enter a search term in the right hand column and submit
3. Choose any option in the "Status" dropdown
4. Click the "Apply Button"

Expected behaviour:
The option selected in the "Status" dropdown should remain the same after the filter is applied

Actual result:
The option selected in the "Status" dropdown changes

**Comment by rjmackay** [comment]
@sebm90 I'm not 100% clear on the issue.. could you post some screenshots?
