### ISSUE TITLE
Test Export to CSV when HDX flag is set to disabled

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2983]
### Test
- [x] With HDX feature flag set to off
- [x] Ensure that the "Configure HDX API" Settings menu item is not visible to the user
- [x] Ensure that the "ASSIGN TAGS AND ATTRIBUTES" button is not present on the Data Export view
- [x] Ensure that Export ALL Data returns a CSV with all the Data from the Platform instance
- [x] Ensure that "SELECT FIELDS" allows selection of Surveys and FIelds
- [x] Ensure that selected fields and surveys are returned correctly as a CSV

**Comment by willdoran** [comment]
@Eve-wanderi when you have completed all other QA let me know and I will disable the HDX feature to allow testing of the above.

**Comment by Eve-wanderi** [comment]
Did some tests on this below are the issues i encountered.  

1.Configure HDX API" Settings menu item is still visible to the user even when HDX flag is disabled.

![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/aba22f6d-b673-4c9a-acca-80603826ade9)

2. When i change the Api Key i am able to see options for Start Tagging Data. ( However when i click on the option its inactive)

Settings>Configure HDX API>Change API Key>Save> Start Tagging data.

![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/203ff606-e4ee-42c5-9f7b-2c6bf5c7e60c)

![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/df77701c-c8d6-43dd-9a63-2fb1261a04db)

**Comment by rowasc** [comment]
@willdoran did you disable HDX? I see that Eve tested it but I'm not sure if you disabled it or if this was tested with the flag "ON" by mistake

**Comment by willdoran** [comment]
ok thanks @Eve-wanderi

**Comment by rowasc** [comment]
@Eve-wanderi can you please re-test ? Thanks!

**Comment by Eve-wanderi** [comment]
Re-tested and can confirm that the Configure  HDX Option is not visible if HDX flag is disabled.

![image](https://user-images.githubusercontent.com/36038029/40802842-73d39910-651f-11e8-80b4-97cbda016536.png)

![image](https://user-images.githubusercontent.com/36038029/40802869-82ef6c12-651f-11e8-864f-ac8bd5a95ff9.png)

**Comment by Eve-wanderi** [comment]
I was also able to export the data as CSV with the selected fields in the survey.

**Comment by rowasc** [comment]
Moving to Waiting to Deploy then
