### ISSUE TITLE
[Platform API] Move Maintainer field to User Settings

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2986]
### Overview
The maintainer field should be moved to be closely linked with the API key.

### Requirements
- [x] Maintainer field is removed HXL Meta Data table
- [x] Maintainer field is removed from HXL Meta Data entity and Validation
- [x] Maintainer field is renamed as hdx_user_id 
- [x] hdx_user_id is substituted throughout API
- [x] hdx_user_id is now retrieved from User settings.

## Acceptance criteria / Test script
- [x] hdx_user_id is returned correctly from User settings

**Comment by rowasc** [comment]
@jrtricafort I think this should be part of cycle 6, as not doing it raises a requirement to ask the user to re-validate their user id when generating an HDX export, which is more complex than just moving this to the correct screen. 
We still  need to improve our export validation but this is an 'easy' improvement that would make it way more usable and allow users to make mistakes without having to re-map their export . 
cc @willdoran

**Comment by jrtricafort** [comment]
Agreed, added. to Cycle 6.

**Comment by rowasc** [comment]
@willdoran we should add that the server will validate the API Key against HDX  (so far I figured out that if I do a /user_show for a user and it returns the API key + all data, it means it is the same user) and return an error if they don't match

**Comment by willdoran** [comment]
@rowasc Can you review please?

**Comment by rowasc** [comment]
@willdoran APPROVED.
