### ISSUE TITLE
Prototype/implement form validation

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2991]
- [ ] research form validation options
- [ ] get input/buy-in from the team
- [ ] implement validator into UserForm
- Validations
  - [ ] Email: should be email
  - [ ] Password: should be at least 7 characters long
  - [ ] realname: should be at least 1 character long? no numbers?
  - [ ] role: should be one of the role options
  - [ ] should run onChange
  - [ ] submit should be disabled until validations all pass

**Comment by rowasc** [comment]
@crcommons is this ticket happening somewhere else (ie user create) ? should we close or keep it ? is it in the right column?

**Comment by crcommons** [comment]
@rowasc Closed it because we're now addressing validation in users components.
