### ISSUE TITLE
Merge develop (lumen compat) into react branch

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2994]
- [ ] use with lumen backend
- [ ] Run tests

**Comment by rowasc** [comment]
I think this ticket should be closed as  we don't have an action that can be done after it, it was "just" the merge and we are not QAing a merge, we are going to QA the migration itself
. @jrtricafort @crcommons toughts?

**Comment by crcommons** [comment]
@rowasc Agreed!

**Comment by rowasc** [comment]
Closing then. 👍
