### ISSUE TITLE
Review and transfer key points from retro docs/trello into a the Super Retro Trello

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2998]
### Overview
- [ ] Review all existing retro documents
- [ ] Review all retro trello boards
- [ ] Collect most voted for points
- [ ] Ignore redundant points
- [ ] Group points into a the new Trello board

**Comment by jrtricafort** [comment]
Done. https://trello.com/b/P1ri8Wm5/super-retro-0-dev-process-this-is-a-curated-selection-of-process-related-retro-cards-from-cycle-0-cycle-4
