### ISSUE TITLE
Define style guide expected that team can use

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2999]
### Overview
Create short guide describing clearly the core standards to adhere to when producing the document. Intended to reduce strain on editor and avoid basic mistakes.

**Comment by crcommons** [comment]
Here's a rough draft. https://docs.google.com/document/d/1P4IByZRpYXqY-LZZB0LFmLr6clcS7SIAJyS_VJFPsl4/edit?usp=sharing
