### ISSUE TITLE
settings/users (aka people) Migration

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3003]
Note we'll want to update any issues for users/create + create issues for users/edit and user list

(Document folder: https://drive.google.com/open?id=1FQcHivNUyuDhdhbs3RiDTo-lGl13JzXq )

1. API -> State Interactions 
https://docs.google.com/spreadsheets/d/1ZHCExmiDQbrdMHJAU0YJl5_HAzuBG9ZUYjK3TakPlPk/edit?usp=drive_web&ouid=113225898055453652609

2. Libraries
https://docs.google.com/spreadsheets/d/1Lz8-qCb89EOdYsXKWlwW0tSeujCy5d5558vvdP_riJM/edit#gid=0

3. Angular services (Ushahidi and 3rd party)
https://docs.google.com/spreadsheets/d/1nRiAnqW0zPzhUsposwV7quN4debvDpB7w6sjl5GUD_c/edit#gid=0

4. Component map/tree
https://www.lucidchart.com/invitations/accept/ba959cbf-d01e-4695-a707-e6140ae45b51

5. Routes
    - #3043
    - usersContainer will need to handle routing to subcomponents 

6. Endpoints
   - Get user by ID #3042
    - Get users #3044
    - Query users #3045
    - delete users #3055
    - tests
7. actions 
    - #3048
8. reducers (state!)
    - #3052
9. Interface behavior requirements
- user/create #2990 
- user/list #3054
- user/edit #3056

10 .  Cached data

Designs:
https://xd.adobe.com/view/e8878276-4282-4a3c-59e9-3a9fa771fc90-9eb6/

NOTE: Should have two password fields (enter password and confirm password)

**Comment by rowasc** [comment]
@crcommons `user/delete` should also be listed under `Interface behavior requirements`, right?

**Comment by crcommons** [comment]
@rowasc I suppose it depends on how we're defining interfaces. I wouldn't consider delete users it's own interface, but rather a small subcomponent of the edit interface.

**Comment by jrtricafort** [comment]
@rowasc I added the note about two password fields in the description here. Let me know if there is a better place for that.
