### ISSUE TITLE
categories migration

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3004]
# Categories Epic

## Overview
- As an admin, I should be able to see a list of my categories
- As an admin, I should be able edit categories
- As an admin I should be able to delete categories
- Ad an admin I should be able to add new categories and sub-categories
    - sub categories should have the same permissions as parent categories

Follow the categories designs: https://xd.adobe.com/view/e8878276-4282-4a3c-59e9-3a9fa771fc90-9eb6/

## Who is it for? Who are the users?
All deployment administrators or users with "manage settings".

## What privacy impacts does it have?
Nil

### Who will this be deployed to?
This will be deployed to all users.

Bonus: Maintain the original categories view behind a build or runtime feature flag

### What documentation needs to change?

- Update category settings docs with new screenshots
- Functionality should be unchanged, but needs to be verified

## Test script

TBD

### Who will test this?
Eve

### Where will this be deployed and tested?
- Deployed to staging prior to release
- Individual PRs can be tested through branch deployments - because this is UI only.

## Deployment

*Does this deploy new services?* No
*Do the new services have health checks?* NA
*Can this be feature flagged and deployed disabled?* Yes. We can at the least use a build flag to switch new / old views.

## Dependencies
- React base branch

**Comment by rowasc** [comment]
@jrtricafort I think we should drop this from cycle 5, as we will not get to it
