### ISSUE TITLE
Modal for confirmation/errors/notifications

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3005]
## Overview
When I save something, get an error, etc... I will see a notification in the form of a modal; it may require some interaction or may disappear after a set time

## Requirements/User interface behaviors
- When a user attempts an action (like deleting a user), a confirmation modal appears with action buttons (delete and cancel). like this -> https://xd.adobe.com/view/e8878276-4282-4a3c-59e9-3a9fa771fc90-9eb6/screen/2b5fe737-5472-40c1-8703-ef744cc8deb0/settings-categories-are-you-sure-delete-
  - the action button (delete) should complete the desired action
  - the cancel button should close the modal 
- When a user gets an error (like when trying to save a user, but server responds with error), a notification modal appears and displays the error and some buttons?
  - If user is not authenticated, route them to login
  - else, we display the error and ask the user to try again later; There is a "x" to close and clear error from state; It is modeless

### Component tree
- ModalComponent (new) will be a common component

### State tree
Potentially with error modals, closing the modal would clear the error from state (depending on how we do error handling)

## Acceptance criteria / Test script
- should be tested within the context of editing or creating users

**Comment by crcommons** [comment]
@justinscherer @Erioldoesdesign Let's make a final decision on all of this as soon as possible (Monday, perhaps?). This is going to be a blocker for editing and creating a person.

**Comment by Erioldoesdesign** [comment]
@crcommons I think this is the same conversation around whether we use some kind of inline error validation for this (a new style as far as where to position it within the hierarchy of the dependant page info) or we re-purpose the undo module in a red/error state (a 'new' adapted style).

I'm leaning towards purposing the undo style in an error red as it seems to appear at the top of the page/overlays the page content so we can be sure users won't miss that their 'action' received an error.

**Comment by crcommons** [comment]
@Erioldoesdesign That sounds good to me. @justinscherer Do you agree?

Also, do we need a success version of the modal in green as well? For example, when a user edits a person and the update is successful, how do we indicate success?

**Comment by crcommons** [comment]
@rowasc Can you provide some input on how to handle various errors (when we would want to let the user retry or not)?

**Comment by rowasc** [comment]
@rjmackay @crcommons my reaction is that 4xx errors should not have a retry option, while errors for potentially valid requests that the server fails to process (5xx) and maybe more specifically 503s/500/502 could potentially have a retry. In this case, it can be important to differentiate and let the client know of permanent vs temporary states, I suppose, but initially, we could assume some 5xx errors are good retry candidates.

A 4xx would usually be a 422/400/404/403 in our current API and none of those are good candidates for a retry without the user changing something, in my opinion. 

Maybe we just don't want a retry option, but if we want one, I think this is how it should be.

**Comment by rjmackay** [comment]
> 4xx errors should not have a retry option

Agreed. In general 4xx errors should provide enough feedback to give the user useful information ie. what fields failed validation, or if its a 403/401 that they need to log in, or don't have permissions.

> potentially valid requests that the server fails to process (5xx) and maybe more specifically 503s/500/502 could potentially have a retry

That would make sense. A 500 is usually going to be a bug, or server failure. I think the only other status we use is 503  for maintenance or upgrades, so its quite possible retrying could fix the issue.
It would probably be enough though to just say 'Try again' and then drop the user back to the form they were working in, with the unsaved data right?

**Comment by rowasc** [comment]
Yea, I think that might be the safest way to do this without over complicating it. 
"{error }, please try again.".. and just take them to the form with the data as they entered it.

**Comment by rowasc** [comment]
@Erioldoesdesign excellent, thanks. @crcommons I think this answers it then, we should move on without a retry, and just have visual feedback of what went wrong (I suppose it's enough with the error message + validation errors placed on fields if there's a validation issue)

**Comment by crcommons** [comment]
Got it. Issue is updated.

**Comment by justinscherer** [comment]
Agree with @Erioldoesdesign use the modeless undo module with updated styling. and yes, in that case we'd need a success version, too. It functions as a form-level notification, whereas inline is a field-level notification (NB: not always an error) 

Note: the error version will have a red "x" icon instead of a green checkmark icon.

**Comment by justinscherer** [comment]
Are there any further actions on this for me @crcommons ?
