### ISSUE TITLE
Edit a survey migration

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3007]
As a user, I should be able to create and edit a survey. A survey must have a name but not necessarily have a description. As I complete each step of the survey, my answers will persist and I will move forward in the survey flow. Surveys should have a multitude of options for inputs. Those options will be presented to me in a modal. I should be able to add as many questions as I want and adding a question will be presented to me in a modal. I should be able to re-order my questions by dragging and dropping. From the survey edit page, I should also be able to get a sharable link to my survey, export survey data, and, embed my survey.

Designs: https://xd.adobe.com/view/e8878276-4282-4a3c-59e9-3a9fa771fc90-9eb6/

**Comment by rowasc** [comment]
@jrtricafort I think we should drop this from cycle 5, as we will not get to it
