### ISSUE TITLE
Migrate Post and Filter Data to Redux Store

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3008]
We can't begin migrating more complex, interconnected sections of Platform without ensuring we're getting consistent data all over. We can’t begin to migrate things like filters, map-view, data-view, collections, etc… until we get posts stored in redux. So we’ll ensure that each call to query posts or get geojson is saved to the store. Currently those endpoints are being called in 4 directives: post-view-map, activity-timeline, post-relation, and post-view-data, which is a reasonable amount to migrate without having to make changes throughout the entire application.  We also need to migrate filters so we can use the filters on each call made to the API. 

We will need to research if we’ll adjust angular directives to pull from the store or not and how to do this.

**Comment by jrtricafort** [comment]
cc @willdoran 
Discuss this on first day of Montreal Hit Team
