### ISSUE TITLE
Handle HTTP errors - Discuss, decide

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3009]
We do not currently have a method for handling errors (aside from when a user unsuccessfully tries to create or update).

Example Scenario: If I want to create a new user, I have to GET the list of roles for the deployment which dynamically loads in the create user form. If that request fails, what do we do? 

- [ ] Discuss scenarios where we need error handling
- [ ] Decide how to approach them programmatically
- [ ] Decide how to handle them in the UI

**Comment by rowasc** [comment]
Discussion happened. 
output (from Carolyn)
*Errors when requesting data from the API:*
- if unusable, semi-complete data (like getting roles for create user form), send user to 404 with explicit error message (we still need to design and build the 404)
- if the page is still usable (like the user data doesn’t load for a post), lazy-load data forever
*Erros when saving data:*
- First, check on submit and give error status on inputs
- if you receive a server error, send user to 404 page with explicit error message
- if user is not authenticated (timeout), go to login
*If a user tries to visit a URL that doesn’t exist:*
-  send the user to 404 page
*Input/Field errors should be checked on blur*
