### ISSUE TITLE
Confusing error on Save Search view

### ISSUE THREAD

**Issue by sebm90** [ushahidi/platform#301]
Steps to reproduce:
1. Apply a search on the default view
2. Click "Save Search"
3. Select "Chart" as the Default View
4. Click "Save Search"

Expected behaviour:
The search is saved

Actual result:
An error appears: "Validation error: 'view must be one of the available options''"

**Comment by willdoran** [comment]
This is linked to the choice options on platform not matching those on the client. I've changed that.
