### ISSUE TITLE
Improve Facebook Sharing Information

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#3011]
It doesn't look like deployments or reports have very good meta information, which means the site isn't included very useful information when people share to Facebook.

Best Practises https://developers.facebook.com/docs/sharing/best-practices/

Example https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fdale.ushahidi.io%2Fviews%2Fdata

Aha! Link: https://ushahiditeam.aha.io/features/PROD-338

**Comment by Angamanga** [comment]
Related to https://github.com/ushahidi/platform/issues/4216
