### ISSUE TITLE
Improve Twitter Card Share Information

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#3012]
It doesn't look like we've provided any Twitter Card meta information, which means reports are not including much/any useful information when shared to Twitter.

Twitter Validator https://cards-dev.twitter.com/validator >> https://dale.ushahidi.io/posts/108

![screenshot 2018-05-27 19 01 28_preview](https://user-images.githubusercontent.com/91811/40592798-826ffbe0-61e0-11e8-9843-786fad051ccd.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-337

**Comment by rowasc** [comment]
note: This will require some server side rendering setup to work for all different platforms according to the research we did last year

**Comment by Angamanga** [comment]
Related to https://github.com/ushahidi/platform/issues/4216
