### ISSUE TITLE
[Platform Client] Auto-tick "include" checkbox

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#3013]
### Overview
On the Export Tagging screen, a survey field row that has at least one hxl tag assigned should have the checkbox for the field automatically 'ticked' when the tag has been added.

### Requirements
- [ ] A survey field row that has at least one hxl tag assigned should have the checkbox for the field automatically 'ticked' when the tag has been added

**Comment by willdoran** [comment]
@rowasc I think this is redundant because you can't set a tag until you select the row. What do you think?

**Comment by rowasc** [comment]
@willdoran Yea... I think this is still relevant, but only if we stop forcing people to click the checkbox before. 
@Erioldoesdesign the intended design was that if you selected a tag, the checkbox would be selected automatically, right?

**Comment by Erioldoesdesign** [comment]
@rowasc Yep that's right :)

There was almost a 50/50 split with user testers that went for the checkbox first and users who when for the dropdown first. Be good to allow for both 'flows'

**Comment by rowasc** [comment]
@Erioldoesdesign makes sense . Thank you!
