### ISSUE TITLE
For Lumen branch: Allow Farsi in Category titles without error message

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3014]
_**Note: Will fixed this issue for non-Lumen branches. This ticket is to make sure we fix it in the Lumen branch as well. Since this has been previously fixed, this is Ready for Dev.**_
Previous fix: https://github.com/ushahidi/account-management/issues/22#issuecomment-389797184

### Expected behaviour
I am able to create or edit categories with Farsi in the title.

### Actual behaviour
When I try to create or edit categories with Farsi in the title, upon clicking Save I get this error message: "Validation Error: slug must contain only numbers, letters and dashes".

### Steps to reproduce the behaviour/error
1. Log into a Lumen-branch deployment such as https://comrades-hdx.ushahidi.com
2. Go to Settings->Categories->Create New Category
3. Put a Farsi character like "خط" in the title
4. See this error message:

<img width="545" alt="screen shot 2018-05-28 at 4 04 27 pm" src="https://user-images.githubusercontent.com/37776843/40631365-d55cf2a8-6290-11e8-8b61-d40f7c205218.png">

#### Where does this issue happen?
- Ushahidi deployments on current Lumen branch (as of 2018 May 28). Example: https://comrades-hdx.ushahidi.com

**Comment by rowasc** [comment]
<img width="456" alt="Screen Shot 2019-06-11 at 12 53 32" src="https://user-images.githubusercontent.com/2434401/59287401-f73c4680-8c47-11e9-9479-221e8d480ec3.png">
![Uploading Screen Shot 2019-06-11 at 12.53.37.png…]()
This works now 🎉
