### ISSUE TITLE
Create tests for session.js

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3018]
The session service has been migrated from angular to vanilla JS so that it can be used in both react and angular. Now all the tests are broken. Tests need to be migrated to jest. Tests are currently commented out.

**Spec**
- [x] Mock localStorage data (already done)
Write tests for:
- [ ] If no data is in LocalStorage, then getSessionData returns empty session data
- [ ] If data is in localStorage , then getSessionData returns the session data with the stored values from localStorage
- [ ] Without any values initially stored in localStorage, assert that after calling setSessionData, keys and values are stored in the session
- [ ] Without any initial values in localStorage, assert after calling setSessionData, key and value are then stored in localStorage
- [ ] GetDataEntry: If some values are stored in localStorage before injecting the Session service, assert that getting an individual data entry returns correct values
- [ ] GetDataEntries: When some values are stored in localStorage before injecting the Session service, assert that getting several data entries returns correct values
- [ ] Clearing session data leaves only the intial keys with undefined values stored in the Session
- [ ] Clearing session data removes all keys and values from localStorage

**Comment by rowasc** [comment]
I think this is ready for dev, no? @crcommons

**Comment by crcommons** [comment]
@rowasc it needs to be reviewed and get an estimate

**Comment by rowasc** [comment]
Right... my point was that I would approve it. Apologies for the confusing question.  I think since it's just the test, a 2 would be fair. What do you think?

**Comment by crcommons** [comment]
Agreed on a 2. Will add estimate and move to ready for dev
