### ISSUE TITLE
Add tests for roles actions

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3019]
- Tests to be written
- [x] creates HANDLE_REQUEST_FAILURE when GET roles fails
- [x] creates RECEIVE_ROLES when we GET roles successfully
- [x] When a GET request for roles succeeds, create REQUEST_ROLES and RECEIVE_ROLES with roles object
- [x] When a GET request for roles fail, create REQUEST_ROLES and HANDLE_REQUEST_FAILURE with error object

**Comment by crcommons** [comment]
Carolyn, Mark, Romina voted and agreed on an estimate of 1

**Comment by rowasc** [comment]
APPROVED

**Comment by kinstelli** [comment]
Spec APPROVED

**Comment by crcommons** [comment]
APPROVED

**Comment by crcommons** [comment]
Closing as there isn't any QA required.
