### ISSUE TITLE
Continue migrating authentication-interceptor to axios interceptors

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3020]
## Spec todos
- [x] walk people through the interceptor
- [x] find out what's missing

- [x] define which tests need to be written

## Parts TODO
- [ ] response interceptor TODO 
    - [ ] error handler
        - [ ] If we get 400 or 401 AND we were logged in (loginStatus=true), throw the unauthorized event
        - [ ] If we get 400 or 401 AND we were NOT logged in, and it's an ignorable request, just let it go through (resolve)
        - [ ] If we get 400 or 401 AND we were NOT logged in, implement concurrentGetClientCredsToken function that checks and only requests the new token if there are no ongoing requests .     
        - [ ] if we get a 403 and it's not ignorable: trigger forbidden event and reject promise
        - [ ] if we get a 403 and it's ignorable: reject promise
    - [ ] success handler
        - [ ] Migration of getClientCredstoken. Login is handled in another phase but we need to handle it for annonymous tokens. We will use axis to add the token to requests (post, get , etc). 
             - [ ] using the CONST values for token has a dependency with #3023
    - [ ] pull the ongoing request to a service so both angular and react have access with their interceptors

For reference: Documentation on axios interceptors: https://github.com/axios/axios#interceptors

### Write Tests (ALL the tests we current have for authentication interceptor)
- [ ] Should add the authorization token header
- [ ] without an accessToken stored in the Session service… should send the request without an authorization header
- [ ] should add the annonymous tokens to the request header
- [ ] should ignore failure if ignore 403 is set. 
- [ ] for non api requests it should not add the authorization header
- [ ] response error handler tests for 401
- [ ] response error handler tests for 'logged out' 
- [ ] retry request after getting a new token
- [ ] non 401 error : should not broadcast an event over the rootscope

## Manual test cases
- [ ] I can successfully login to the platform with an admin and access settings. 
- [ ] I get an error if I try to login with incorrect credentials
- [ ] If (logged in ) I go to /settings/user/create I can see a list of roles in the roles dropdown

**Comment by jrtricafort** [comment]
@crcommons Need more detail. Make sure to spec in pairs+.

**Comment by rowasc** [comment]
We did an initial estimate and agree on 5 (Carolyn, Mark, Romina)

**Comment by rowasc** [comment]
APPROVED

**Comment by kinstelli** [comment]
APPROVED

**Comment by crcommons** [comment]
APPROVED

**Comment by rjmackay** [comment]
> throw the unauthorized event

Are we anticipating throwing angular events here? or triggering redux actions? or both?

Could this task also include documenting the existing flow? I think @tuxpiper made a diagram at some stage, maybe we could update it.

**Comment by tuxpiper** [comment]
@rjmackay  I made a rather quick and dirty attempt, it would be really good to review it. I've shared it in Lucidchart with everyone I could find having an account in there

**Comment by rjmackay** [comment]
Here's the published link to the lucid chart https://www.lucidchart.com/documents/view/4b6f2372-a4bd-4139-b09b-74be0567d4ba
I think that'll work for anyone to view
