### ISSUE TITLE
Handle proptypes in temporary migration connect component

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3021]
### Expected behaviour
I should not need to define props of each component in connectWithStore that uses it

Component >> https://github.com/ushahidi/platform-client/blob/c81e0a281d5474413bd03a69bf457eaa2617ccbd/app/react/react-transition/connectWithStore.jsx

Context on connectWithStore > https://github.com/reduxjs/react-redux/issues/390
### Actual behaviour
I get errors in the console like this: 

````
Warning: Failed prop type: The prop 'isLoadingRoles' is marked as required in 'ConnectedComponentWithStore', but its value is 'undefined'.
    in ConnectedComponentWithStore
````
### Steps to reproduce the behaviour/error
Navigate to settings/users/create and look in console

### Spec
- [ ] Research how to send components to connectWithStore without connectWithStore needing the prop-types of the passed in the component. 
- [ ] Implement

#### Where does this issue happen?
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes the purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by rowasc** [comment]
Assigning myself to research and then come back to this with @crcommons @kinstelli

**Comment by rowasc** [comment]
Closing as Robbie finished this
