### ISSUE TITLE
Migrate CONST in a way that is usable to Angular and React

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3023]
Const file:
- [ ] should provide access to window.ushahidi like this: `window.ushahidi = window.ushahidi || {};`
- [ ] these constants come from window (see app.js)
  - [ ] BACKEND_URL: backendUrl,
  - [ ] API_URL: apiUrl,
  - [ ] INTERCOM_APP_ID: intercomAppId,
  - [ ] APP_STORE_ID: appStoreId,
  - [ ] MAPBOX_API_KEY:
            window.ushahidi.mapboxApiKey ||    "pk.eyJ1IjoidXNoYWhpZGkiLCJhIjoiY2lxaXUzeHBvMDdndmZ0bmVmOWoyMzN6NiJ9.CX56ZmZJv0aUsxvH5huJBw", // Default OSS mapbox api key
  - [ ] EXPORT_POLLING_INTERVAL:
            window.ushahidi.export_polling_interval || 30000
  - [ ] TOS_RELEASE_DATE: new Date(window.ushahidi.tosReleaseDate).toJSON()
            ? new Date(window.ushahidi.tosReleaseDate)
            : false, // Date in UTC
  - [ ] PLATFORM_WEBSOCKET_REDIS_ADAPTER_URL: platform_websocket_redis_adapter_url, 
- [ ] These are hard coded
  - [ ] DEFAULT_LOCALE: "en_US",
  - [ ] OAUTH_CLIENT_ID: "ushahidiui",
        OAUTH_CLIENT_SECRET: "35e7f0bca957836d05ca0492211b0ac707671261",
- [ ] These are defined in app.js
  - [ ] CLAIMED_ANONYMOUS_SCOPES: claimedAnonymousScopes,
  - [ ] CLAIMED_USER_SCOPES: claimedAnonymousScopes.concat("dataproviders"),
       
Usage:
- [ ] export const file
- [ ] import const file into app.js
- [ ] require const file in app.constant (angular modules will continue using CONST and react components and vanilla JS files will access constants by directly importing them

**Comment by rowasc** [comment]
@crcommons do you think we need to spec this more?

**Comment by crcommons** [comment]
@rowasc No, it just needs to be reviewed.

**Comment by rowasc** [comment]
@crcommons I think this ticket is the one we paired on. Can we finish review+estimate in the morning>?
