### ISSUE TITLE
Cleanup where some config values are stored -- whether in const, .env, or elsewhere

### ISSUE THREAD

**Issue by kinstella** [ushahidi/platform#3024]
Currently, it's unclear why some values are hardcoded, some are stored in .env, some are copied to CONST, and some are defined throughout the Angular codebase.

After migration to React, we should clean this up and decide if we can streamline this or better organize it.

(This was discussed with @crcommons and @rowasc when spec'ing  #3023, so I'm only tagging them here in case they would like to clarify this)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-335

**Comment by rowasc** [comment]
@crcommons @kinstelli moving this out of cycle 5 since it was not planned, but leaving it linked to the JS epic.
