### ISSUE TITLE
The "It looks like you haven't configured your HDX API" message appears for a second every time you load the HDX export screen 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3026]
Current behavior: 
- Load the HDX/ Export and tag data screen AFTER having configured your API key for HDX
- Before the "Export all data" / Select fields button load, you will see the "It looks like you haven't configured your  Humanitarian Data Exchange..." message appear. Then it will disappear quickly

Expected behavior 1: 

- [ ] Load the HDX/ Export and tag data screen AFTER having configured your API key for HDX
- [ ]  The "It looks like you haven't configured your  Humanitarian Data Exchange..." message should not appear. 
- [ ]  The export buttons should appear. 

Expected behavior 2: 

- [ ] Load the HDX/ Export and tag data screen without having your HDX API key configured
- [ ] The "It looks like you haven't configured your  Humanitarian Data Exchange..." message should appear

See screenshot: 
<img width="980" alt="screen shot 2018-06-22 at 3 12 23 pm" src="https://user-images.githubusercontent.com/2434401/41792305-ceaf5606-762e-11e8-8297-f548ee4df985.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-334

**Comment by jrtricafort** [comment]
@rowasc Can you and @Eve-wanderi discuss this? If it can't be reproduced, I suggest we descope this.

**Comment by rowasc** [comment]
@Eve-wanderi this needs to be re-tested in the https://comrades-hdx.ushahidi.com/  environment.

**Comment by Eve-wanderi** [comment]
This issue still Persists 
Steps:
1. Click on Settings
2. Click on export and Tag Data.

There is a message that pops-up on the screen for like 3 seconds so users cannot read what the message is.

**Comment by rowasc** [comment]
@Eve-wanderi this instructions are not enough to actually have anything happen, I just get to the export page if I follow those steps . Please add all the reproduction steps, or a gif/video if that's easier.

**Comment by Eve-wanderi** [comment]
Please find attached video.

[Video_6_22_2018_17_00_05_wmv.zip](https://github.com/ushahidi/platform/files/2128251/Video_6_22_2018_17_00_05_wmv.zip)

**Comment by rowasc** [comment]
@jrtricafort I think this could be a P1-P2. It's not an error that's happening, its a screen that is shown when it shouldn't. Updated title and description to match what's happening. It should be pretty easy to solve but at least it's not an error.

@Eve-wanderi thanks for the video.

**Comment by rowasc** [comment]
@jrtricafort can you review and prioritize? If this is something we could move to cycle 7, that'd be great. But if not, at least knowing the priority would help me organize my work

**Comment by jrtricafort** [comment]
@rowasc P2

**Comment by jrtricafort** [comment]
@rowasc Not moving to Cycle 7 yet. If this doesn't happen in Cycle 6, we can consider moving to 7 or iceboxing.

@Eve-wanderi Really nice find, and thanks for the great report!
