### ISSUE TITLE
When uploading HDX Data system does not inform users upload is in progress.

### ISSUE THREAD

**Issue by Eve-wanderi** [ushahidi/platform#3028]
### Expected behaviour
When uploading HDX Data system should inform users upload is in progress. i.e Have a progress bar or icon showing users the upload is ongoing.

### Steps to reproduce the behaviour/error
When uploading HDX Data system does not inform users upload is in progress.

#### Where does this issue happen?
- https://comrades-hdx.ushahidi.com/settings/hdx-details

![image](https://user-images.githubusercontent.com/36038029/40726628-c8d95ee6-642e-11e8-8039-339453defeb1.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-333

**Comment by jrtricafort** [comment]
@rowasc @willdoran  I think we should descope this. Agree?

**Comment by rowasc** [comment]
YEP, we should 
Deassigning
