### ISSUE TITLE
Selecting a post in the collections map view does not direct you to the selected post on data view

### ISSUE THREAD

**Issue by StaicyG** [ushahidi/platform#3033]
## Requirements
When I select a post to see details while in a collection, I should be routed to the data view with that post selected

## Acceptance criteria
- navigate to a collection
- select a post
- click the post again to go to detail view
- [ ] confirm you are routed to the data view with the post selected

##### Expected behaviour
When you click on a post on map view, it should show some information about the post and when you click on the post again, it should direct you to data mode showing more information about the post.

##### Actual behaviour
This issue is in collections map view. 
When you click on the following collection map view.

https://iranprotests.ushahidi.io/collections/154/map

Click on any location icons, it doesn't matter which

Then click on the pop up window for that event. You will be directed to the general collection data view rather than the data view for that specific event 
https://iranprotests.ushahidi.io/collections/154/data

##### Steps to reproduce the behaviour/error
This can be reproduced in an .io deployment

Selected a post from collections map view as below screenshot:
[Uploading... Screen Shot 2018-05-31 at 5.35.37 PM.png ]

Then selected the same post again expecting to go to data mode and view more information about the post. Instead I have been directed to general data mode view without highlighting the specific post I selected as illustrated below:
![Screen Shot 2018-05-31 at 5.05.34 PM.png]

##### Where does this issue happen?

- [x] Ushahidi.io / SaaS solution 

### Notes 
This works as expected if you are not in a collection. (issue is specific to posts inside a collection while in collection map view)

**Comment by jrtricafort** [comment]
Thanks @StaicyG adding this to bug backlog to consider for possible next cycles.
@rowasc tagging you for general awareness here, but no action needed at this time.

**Comment by crcommons** [comment]
@rowasc I'm estimating this at a 2 because it's a really small change but it's known that collections routing is a disaster and thus could cause problems. LMK what you think.

**Comment by Eve-wanderi** [comment]
Confirmed Passed QA.

**Comment by rowasc** [comment]
@Eve-wanderi moved to waiting to deploy. Please remember to move things once they pass/fail . Thankks
