### ISSUE TITLE
Make message sending button more logical

### ISSUE THREAD

**Issue by dukedanny** [ushahidi/platform#3034]
### Expected behaviour
When a user is sending out a message from platform, the click action should be displayed as SEND.
<img width="473" alt="message" src="https://user-images.githubusercontent.com/437728/40789328-d8254154-64fa-11e8-8e4c-1b4ad10d0d33.png">

### Actual behaviour
When a user is sending out a message from platform, the click action is displayed as SAVE.
<img width="473" alt="message" src="https://user-images.githubusercontent.com/437728/40789234-9828c468-64fa-11e8-8d87-e582ba00023c.png">

### Steps to reproduce the behaviour/error
 Data View > Click any report (_or post or message_) > Send New Message > **Save**

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [x] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [x] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by jrtricafort** [comment]
@justinscherer @Erioldoesdesign does this require a Dev or is this just Design?

**Comment by justinscherer** [comment]
Requires dev, they control the interface copy.

**Comment by jrtricafort** [comment]
Ok. @justinscherer are you good with the spec for this being a one-word change of "Save" -> "Send"? This sounds reasonable to me. If so, I'll queue it up as an issue to do next cycle.

Tagging @rowasc - this should hopefully be a quick 1-point enhancement

**Comment by rowasc** [comment]
Excellent. Yea, 1pointer @jrtricafort

**Comment by Erioldoesdesign** [comment]
@jrtricafort @rowasc  Just confirming that changing the button copy from "Save" to "Send" is the right course of action from Design POV

**Comment by jrtricafort** [comment]
Awesome, thanks @Erioldoesdesign 

@rowasc I'm going to add this to Cycle 6 as a 1-pointer as defined above.

**Comment by rowasc** [comment]
@Eve-wanderi please review

**Comment by Eve-wanderi** [comment]
Confirmed text changed.

![image](https://user-images.githubusercontent.com/36038029/43519719-347ffcc2-9599-11e8-9f23-8ce51f80cc21.png)
