### ISSUE TITLE
refactor reducers to not use switch statements

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3035]
Switch statements and verbose and ugly and unnecessary! So let's use another pattern to generate reducers. The redux documentation has some thoughts on generating reducers here: https://redux.js.org/recipes/reducing-boilerplate#generating-reducers

We could use this library: https://www.npmjs.com/package/redux-create-reducer or write it ourselves.

After refactoring, make sure to update the pattern documentation: https://docs.google.com/document/d/1i_rRSVmJrVJELiO-UljP1uZXvUPkwv093Tz5C5Aoqbc/edit?usp=sharing

**Comment by rowasc** [comment]
Closing as Robbie already did this
