### ISSUE TITLE
Migrate caching 

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#3036]
Writing a placeholder issue for spec'ing this cross-cutting concern, whether or not this gets included within this or another cycle.

Also, there are a few 3rd party libraries for React/Redux that could handle some of this.

**Comment by rowasc** [comment]
This sounds like it will get handled in another cycle, I don't see us adding more things to the current one unless we remove something else. Not saying it isn't important, just saying that if this is something we absolutely want to do this cycle, we need to pick something that will be leaving, too. 
cc @willdoran  @jrtricafort
