### ISSUE TITLE
Cannot save a targeted survey post in the data view 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3038]
**Describe the bug**
I can't edit targeted survey responses in the data view. 

**To Reproduce**
1. Go to https://ush-sales-demo.ushahidi.io/posts/2
2. Click on edit
3. Try to edit the post and save
4. Nothing happens. You will a JS error in the chrome console
<img width="1617" alt="screen shot 2018-06-01 at 1 32 06 pm" src="https://user-images.githubusercontent.com/2434401/40852306-67b6a4ca-65a0-11e8-99d8-51aaddfb0bac.png">

**Expected behavior**
1. Go to https://ush-sales-demo.ushahidi.io/posts/2
2. Edit the post and save
3. The post changes and is saved 

**Screenshots**

**URL / Environment where this happened**
Production.  https://ush-sales-demo.ushahidi.io/posts/2

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 66

**Smartphone (please complete the following information):**
No

**Comment by rowasc** [comment]
@jrtricafort assigning you to prioritize

**Comment by jrtricafort** [comment]
Discussed w @willdoran - this is p0 since our understanding is that anyone using Targeted SMS is experiencing this, and it blocks the manual data structuring workflow.

**Comment by rowasc** [comment]
@jrtricafort assigned to cycle so I can track points later

**Comment by rowasc** [comment]
@willdoran should we move this to QA Backlog for Eve to re-test?

**Comment by rowasc** [comment]
Closed as this is in production  already
