### ISSUE TITLE
Routing for usersContainer

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#3043]
Routing to UsersContainer will be handled by react2Angular, but routing within usersContainer will be handled internally, based on the route passed to UsersContainer

Spec
- [ ] add users container component to settings module
- [ ] In settings.routes.js: adjust settings.users, settings.users.create, settings.users.edit to point to usersContainer
- [ ] handle programmatic routing in UsersContainer in a way that is compatible with how we will use React Router
    - [ ] handle routing to UserContainer
    - [ ] handle routing to UsersListContainer
    - [ ] handle routing to UserForm 'edit' mode
    - [ ] handle routing to UserForm 'create' mode

**Comment by crcommons** [comment]
Carolyn & Mark voted on 3 estimate. Note that research may change how we want to handle programmatic routing and new issues may be needed for that. Spec is APPROVED!
