### ISSUE TITLE
Infinite Scroll on lists

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3047]
## Overview
When the user scrolls near the bottom of a list, load the next 10 items.
Make sure the items do not hang out in the dom forever, rendering only DOM nodes that the user is able to see or might soon see

## Requirements
- Find library for infinite scroll add it to users (https://github.com/seatgeek/react-infinite )

### State tree
No

### User interface behaviors
When the user scrolls near the bottom of a list, load the next 10 items.

### New libraries added
TBD on which library to use...
Considering Waypoint for triggering the load event: https://github.com/brigade/react-waypoint
Experimented with https://github.com/seatgeek/react-infinite, but not sure it's the right fit

## Acceptance criteria / Test script
Apply this acceptance criteria to any ticket that references infinite scroll as a requirement (ie user list on settings)

### Less than 10 items
- Load a list with less than 10 items. 
- Scroll to the bottom of the list. 
- [ ] Nothing should happen

### Exactly 10 items
- Load a list 
- Scroll to the bottom of the list. 
- [ ] Nothing should happen

### Between 10 and 20 items
- Load a list 
- Scroll to the bottom of the list. 
- [ ]  The remaining items should  appear 

### Between 20 items and 30 items
- Load a list  
- Scroll to the bottom of the list. 
- [ ]  The next 10 items should  appear 
- Scroll to the bottom of the updated list. 
- [ ]  The remaining items should  appear 
- Scroll to the bottom of the updated list. 
- [ ] nothing should happen.

### Checking that nodes are not hanging around

- [ ] Have at least 40 items (TBD on max number of nodes in the DOM at 1 time)
- Load a list 
- Scroll to the bottom of the list (repeat until done/no more items)
- [ ]  The next 10 items should  appear 
- [ ] As new items appear, the same number of items should disappear from the top down (inspect in the DOM)

### Checking that nodes are restored

- [ ] Have at least 40 items
- Load a list 
- Scroll to the bottom of the list (repeat until done/no more items)
- [ ]  The next 10 items should  appear 
- [ ] Check that the first 10 items no longer appear in the dom (with the browser tool)
- Scroll up
- [ ] Ensure that the top items are loaded in the correct order

**Comment by rowasc** [comment]
I think https://github.com/seatgeek/react-infinite might work for us since they specifically mention and address the problem of leaving dom nodes hanging around and messing up the page performance.

**Comment by rowasc** [comment]
@willdoran can you help me review/improve this spec? Not sure what else to add here

**Comment by rowasc** [comment]
@crcommons can you review ?

**Comment by rowasc** [comment]
@crcommons Mostly I'm trying to ensure that when you scroll past a certain amount of items/pages, the first set of items is no longer in the dom (and will have to be re-loaded) . I need to re-check the threshold where that happens again just in case, but the rationale is that you need to be able to g through pagination and NOT have everything still showing up in the dom and slowing things down. 

re state: agree, I'm not entirely sure . I'll send it backk to spec
