### ISSUE TITLE
UI: Categories and font on Bar Chart

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/platform#305]
Clicked on the Bar Chart view. The table has a number of UI issues. In the type and category views:
1. The text description font is too small to read. 
2. the categories on the left side are cut off. I am assuming that it should read "positive or negative reports"

The same issue occurs with a different view. 
Firefox, OS

 
<img width="1020" alt="screen shot 2015-08-13 at 3 28 33 pm" src="https://cloud.githubusercontent.com/assets/1216707/9249694/17e47586-41d0-11e5-8b08-b9ab7cd27ce2.png">

 
<img width="1020" alt="screen shot 2015-08-13 at 3 23 17 pm" src="https://cloud.githubusercontent.com/assets/1216707/9249638/908d1ade-41cf-11e5-9cd5-fd95234c09c0.png">

**Comment by rjmackay** [comment]
cc @vbhv

**Comment by vbhv** [comment]
Thanks @heatherleson . Also recorded in phabricator:
https://phabricator.ushahidi.com/T1774

**Comment by jshorland** [comment]
Should be fixed alongside mustang patterns.

**Comment by rjmackay** [comment]
Not 100% we can fix this with mustang..

**Comment by rjmackay** [comment]
I think we fixed styling on this a while ago.
