### ISSUE TITLE
[Platform Client] Remove text from Targeted Survey questionexample

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#3051]
**Describe the bug**
On the targeted survey question creation step, the modal contains example question text which includes "Your response is free", this text is misleading and should be removed

**To Reproduce**
1. Go to Settings, Surveys, Create Survey, new targeted survey
2. Progress to the Add question step(step 3)
3. Add a question
4. The example text in the question input field should be changed

**Expected behavior**
Remove misleading phrase

**Screenshots**

**URL / Environment where this happened**
[e.g http://qa.ushahidi.io/post/create]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context to solve it**
To solve this bug, we need to change the placeholder text in the language files in this repo https://github.com/ushahidi/platform-client . To test, set the "targeted-surveys" enabled flag to `true` , and with the client pointing to the platform-api you should see the targeted surveys in the "Create new survey" page

Aha! Link: https://ushahiditeam.aha.io/features/PROD-330

**Comment by a-santos** [comment]
Can I take this?
