### ISSUE TITLE
Create a UI and behavior for People List

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3054]
## Overview
Describe the output of this ticket. Include *why* this feature/improvement is being made.

### Requirements; Create a PeopleList container that:
- [x] Gets users and can query for users
  - [ ] create an endpoint, mock it, test it.
- [x] Checks if current user has access to the list of people. If not, redirects to map view (check).
- [x] displays the Add people header based on the route
- [x] has a button that routes you to users/create
- [x] contains a filter component https://github.com/ushahidi/platform/issues/3065
- [x] contains a component that maps the list of users with their roles
    - [x] displays them alphabetically 
    - [x] each user should route to users/edit and pass down the user information and the roles
    - [ ] Delete functionality . https://github.com/ushahidi/platform/issues/3062
    - [ ] Change Role functionality https://github.com/ushahidi/platform/issues/3063 
- [ ] Implement https://github.com/ushahidi/platform/issues/3064 
- [ ] Implement https://github.com/ushahidi/platform/issues/3047 

### New UI routes and views
Add route /settings/users 
Add user list view

### Component tree
https://www.lucidchart.com/documents/edit/9e4ee737-e89e-41a1-976e-90acd9b248bc/0?shared=true&

### State tree
e.g. new data being added to state, and related actions and reducers. Should include example payloads.

### User interface behaviors
- [ ] When the page loads and the current user is allowed the see the people list: 
    - [ ] for each person, show their name and role.
    - [ ] the list of people should be sorted alphabetically
    - [ ] each person item should link to the person/edit page
    - [ ] there is an Add People header
- [ ] When the page loads and the current user is NOT allowed the see the people list: 
    - [ ] the current user is redirected to the map view (this depends on authorization ticket ) 
    - the people array is reset to the initial state.
## Dependencies
 https://github.com/ushahidi/platform/issues/3065
https://github.com/ushahidi/platform/issues/3062
 https://github.com/ushahidi/platform/issues/3063 
 https://github.com/ushahidi/platform/issues/3064
 https://github.com/ushahidi/platform/issues/3047

**Comment by rowasc** [comment]
@Angamanga i think this should be a 3. What do you think(we didn't estimate initially, but better late than never :( )

**Comment by rowasc** [comment]
(without counting the external tickets we linked from here)
