### ISSUE TITLE
Create UI and behavior for people edit 

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3056]
A user should be able to select user (person) and edit their data. When navigating to users/:id, a user should see:

- [x] A header that says "Edit Contact"
#### A form that 
- [x] displays the following inputs with user data filled in:
  - [x] Name
  - [x] email
  - [x] role
- [x] displays loading component until user data has been fetched from API
- [ ] disables buttons until form is validated (synchronous validation)
- [x] allows you to edit the above data and save it
- [ ] updates the form with updated user data after saving, displays a success modal, (and stays on the edit page - anti-pattern?)
- [ ] allows you to cancel which should 
  - [x] revert the fields to the user as they currently exist
  - [x] stays on the user edit form and 
  - [ ] returns the save button to disabled

- [ ] validate form
-----
- [ ] if saving a user errors, then display modal with error message
- [ ] if getting user errors, then route to 404 with error message
#### Technical considerations
- For async errors
  - create an errors reducer and provide it the error and the previously called action name
  - To handle errors in components, conditionally render or route based on if error is present and action matches the action that was called
  - Do not save error state to local storage
  - If error is handled through modal, clear error state on close
- For UI errors
  - add error boundaries from react https://reactjs.org/docs/error-boundaries.html
--------
### Test Scripts
- go to the QA deployment and navigate to settings -> people and select a person
- [ ] the user form should appear with the user data filled in correctly
- [ ] the "Save" and "Cancel" buttons should be disabled
- make an edit
- click cancel
- [ ] a confirmation modal should appear (You will lose the changes you've made. Are you sure you want to cancel?)
- click Yes
- [ ] the form should revert to the original data
- [ ] buttons should be disabled again
- redo the above actions, except click No
- [ ] the modal should close and the form should keep your changes
------
- go to the QA deployment and navigate to settings -> people and select a person
- make an edit to each field;
- click save
- [ ] you see a confirmation that the user was saved correctly and stay on the edit page???
-------
- go to the QA deployment and navigate to settings -> people and select a person
- edit email so that it's not an email ex) test123@gmail
- edit name so it's blank
- click save
-  [ ] you should see the error states appear for each field
------
- go to the QA deployment and navigate to settings -> people and select a person
- refresh; 
- [ ] you should see correct user data in each field

**Comment by kinstelli** [comment]
This spec mostly looks good, but before we put this in ready for dev,  we should probably clarify any of the items that have question marks:
- "if saving results in an error, redirect to 404 with explicit error message (should we stay on page with edited data????)"
- "if saving errors...?"

And I could have sworn we decided against this, but I could just be confused after all of our discussions: "disables buttons until form is validated (synchronous validation)", or if we're now following the same patterns as

**Comment by crcommons** [comment]
You can see in the designs that we are supposed to keep buttons disables for the /edit view, but not the /create view. https://xd.adobe.com/view/e8878276-4282-4a3c-59e9-3a9fa771fc90-9eb6/screen/dbd984f9-6fdf-4f06-9c6f-697c70390467/settings-people-Lauren-Ipsum

Will look into error states

**Comment by Erioldoesdesign** [comment]
(added in from slack convo)

In what scenarios would a user get an 'error' here though?

I can see a few different things that I would want to be inline/validation errors on the fields e.g.

1. User doesn't include a @ or .com in an email
2. User doesn't type in a minimum amount of digits for a phone number for that country code
3. User doesn't include correct info for twitter and/or facebook (@ or facebook.name)

Or sometimes these forms try to detect 'junk' info like strings of 'skbdkbksbsjhebjhdvjhxuiwiww'

404's should really only happen if the whole system 'falls down' so like, the place we save info to (database? servers?) isn't working and the whole deployment/.io is down.

**Comment by Erioldoesdesign** [comment]
@justinscherer We had a slack conversation around this and settled on inline validation/errors and 404 page when server falls down (and users lose any edits) because I'm pretty sure we want to attempt to depreciate the snackbar/pop-up notification thingy.

**Comment by crcommons** [comment]
@Erioldoesdesign @justinscherer 
- Should the cancel button be enabled on page load and if you click it, it would take you back to the people list? Or does it stay disabled until you make a change
- if you make an edit, and then click cancel, should it automatically revert the edits or should it have a confirmation modal saying that you will lose your changes?
- It seems like an anit-pattern to me that when you click save, it doesn't just go back to the people list after a successful save. Flagging this for reconsideration. Let me know what you think.

**Comment by Erioldoesdesign** [comment]
Disabled till you make a change. Cancel 'clears' the form from my perspective. and to get back to the people list you would use a breadcrumb or the browser back button. There's a question here then, as to whether this button should be labelled 'Clear changes' or something like that rathe rather cancel. What do you think @justinscherer ?

> Should the cancel button be enabled on page load and if you click it, it would take you back to the people list? Or does it stay disabled until you make a change

I think a confirmation modal is good as the user has made changes and then navigating away and you want to be sure this is intentional. Yes to a confirmation modal with a 'Return to editing/Discard changes' kind of button copy.

> if you make an edit, and then click cancel, should it automatically revert the edits or should it have a confirmation modal saying that you will lose your changes?

Agreed, I think I remember a conversation where we talked about it going back to the people list and there being a UI indication that a user's details have been updated successfully...I think @justinscherer will know this off the top of his head better than me!

> It seems like an anit-pattern to me that when you click save, it doesn't just go back to the people list after a successful save. Flagging this for reconsideration. Let me know what you think.

**Comment by justinscherer** [comment]
The reason it was designed to stay on the person details page instead of jumping to the people list is that you might want to change multiple things and save them between each task. Change name, change password, for example. Generally, I'm not in favour of confirming forms and stuff to navigate you to a new view unless it's a stepper-type situation. I agree that there should be a confirmation that changes are made, though. 

happy to be over-ruled on this one, @Erioldoesdesign if you think i'm offbase here.

**Comment by Erioldoesdesign** [comment]
So these are the users that will take time to update the form in 'sections' and not all in one go. This makes sense, I can see use cases for someone starting an edit, wanting to check on the correct info for another field, saving and then coming back to continue the edits.

I would say let's go with your original process and user test it as I don't think either is a 'bad' experience and doesn't stop either users from completing their tasks so test and confirm hypothesis :)
