### ISSUE TITLE
Integrate 2 new web services with COMRADES

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#3057]
## Overview
The output of this Epic will be the integration of two additional web services to the [COMRADES platform](https://github.com/ushahidi/platform-comrades). This requirement is spelled out in the proposal in work package 3, "Content Informativeness and Validity Assessment", which can be found on [pages 47-50 of the COMRADES proposal](https://drive.google.com/open?id=0B0fInrbWAUMsNDR0MDMwcGUzTGs). It is preferable that these new features would use the "[webhooks](https://github.com/ushahidi/comrades-service-proxy)" created by Will that have allowed both YODIE and CREES to be integrated with relative ease. There should be relatively little design work to be done for these features and I have a few ideas how the UI could be handled for them. 

## Who is it for? Who are the users?
The new services, much like the existing YODIE and CREES services, aim to reduce the amount of manual effort required to turn in incoming post into an actionable piece of information. The new features will examine the content of posts and annotate them in some way to indicate the relative "validity" or "informativeness" of a post. 

## What privacy impacts does it have?
- To my knowledge this does _not_ change affect personal data nor expose any data that was previously private. 
- This integration will send data to new services.

## Requirements
Need to be scoped. 
### Who will this be deployed to?
This should be deployed to the COMRADES repo. It's possible (and desirable) that this feature would be rolled into core. However, the sustainability of the services upon which this integration would depend is a risk factor. This will likely remain a prototype but has potential for future functionality.

### What documentation needs to change?
The COMRADES repo will eventually house all documentation. This will require a user-facing set of documentation for how to set up these services should a user want to download the COMRADES code and try using these services with their own deployment. 

## Deployment

*Does this deploy new services?*
*Do the new services have health checks?*
*Can this be feature flagged and deployed disabled?*

**Comment by Shadrock** [comment]
@jrtricafort I wasn't sure about all of the fields that were suggested in creating this Epic, so I've left some of them blank. The next logical step for me is to have a call with the University of Sheffield, which is the one hosting the services to be integrated. Let me know how you'd like to proceed.

**Comment by jrtricafort** [comment]
@willdoran Looping you in on this. Let's discuss this week.

**Comment by jrtricafort** [comment]
Connected with @willdoran , capturing notes

For @Shadrock 
-Yes, we can set up a call with them next week.
-When does the integration need to happen?                       

Questions for University of Sheffield
-Is there an adapter involved?
-We need documentation for those two integrations

If this is straightforward, Will estimates ~1 day dev work.

**Comment by jrtricafort** [comment]
Scoping in Cycle 6, but not developing.

**Comment by rowasc** [comment]
Coordinating a call

**Comment by jrtricafort** [comment]
@Shadrock Has set up a call week of July 16. @willdoran will represent platform team. @jrtricafort is optional to attend.

**Comment by Shadrock** [comment]
**Summary & Action Items from Sheffield / Ushahidi call on July 18th.** 
@jrtricafort @willdoran @rowasc [Detailed notes here on Drive](https://docs.google.com/document/d/1Vv_r-8B0ZPaV4exsGrjl56aMZF1YCGGNrdAGE68F49Y/edit).  

The services discussed will be applications on Sheffield's [GATE website](https://gate.ac.uk/): accessible via rest APIs that are similar in nature to YODIE. In general, we foresee a fairly straightforward process for integration without any major red flags. 

The "EMINA" services on informativeness and actionability are being wrapped up now ([actionability repo is here](https://github.com/GateNLP/emina/tree/master/actionability)) and together, can be considered one process: if a post is not informative, there is therefore no actions to be taken. 
- Ian will finish the work on informativeness and send an e-mail to Ushahidi next week with links to the service and an API description with details such as hot to access, any limitations (such as quotas), and what it returns (Ahmet mentioned that he would send information on the codes).
- Ushahidi will then begin scoping the work for the next appropriate development cycle and follow-up as needed.
- Ideally we would like to complete this work in time for the September evaluations of the COMRADES platform. 

There is one additional service (or is it two?) around Tweet veracity and source credibility. The work is still being done on this by Sheffield and they hope to have a working service by August and will reach out to Ushahidi when this is finished. 
- We do *not* expect to have this service ready for September evaluations: it will remain an untested prototype. 

I will likely schedule a follow-up call as Ushahidi begins this work to answer any follow-up questions we may have and update Sheffield on the process. *Please let me know if I missed anything.*

**Comment by jrtricafort** [comment]
Thanks for the recap @Shadrock . @willdoran @rowasc It sounds like the complexity will be relatively similar to the YODIE integration. How many Story Points does that translate to?

**Comment by rowasc** [comment]
Reference to our ticket for testing the service https://github.com/ushahidi/platform-cloud-interface/issues/341 


@jrtricafort not sure about points yet

**Comment by jrtricafort** [comment]
@rowasc Let's create a new issue to track the Veracity Integration. It can be a child epic of this epic (and once it is closed out, this parent epic can be closed out as well). We already closed out Emina right?

**Comment by rowasc** [comment]
I have one already let me link it sorry https://github.com/ushahidi/platform-cloud-interface/issues/370

**Comment by rowasc** [comment]
Closing as this was delivered to comrades. 
cc @Shadrock
