### ISSUE TITLE
Select items in a list

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3060]
## Overview
When a user has the option for bulk edits on a list (e.g. people), they should have the ability to select many items or one item in that list and be able to perform actions on those items.  

## Requirements/UI Behavior
- A list should have fixed button at the bottom that says "Select Many"
- Clicking the select many should allow the items in the list to be selected and opens a help tip 
- Clicking an item selects it and increases the Select count at the bottom and adds the action options at the bottom (for people, delete and role change)
- Shift+click will allow you to select consecutive items in a list
- ctrl+click will allow you to deselect an item

### New UI routes and views
This will be added to the people list view (and later to other list views)

### Component tree
- SelectComponent(new) will take action components as props and they will be child components of the selectComponent
- Changes will need to be made to the list view to allow them to be clickable
### State tree
- The state indicated which items in the list are selected should likely remain in local state

## Acceptance criteria / Test script
- go to settings->users(people)
- select "Select Many"
- [ ] the quick tip should appear
- [ ] The "select many" should now read: "0 Selected"
- close the quick tip
- click a person card
- [ ] the selected count should increment by 1
- [ ] the roles change and delete users options should appear
- shift+click to select many people
- [ ] the select should show the number of people selected
- ctrl+click to remove some items
- [ ] the select should update accordingly
- cmd+click to select additional people 
- [ ] the select should update accordinly

**Comment by rowasc** [comment]
@Erioldoesdesign @jrtricafort @crcommons since we are blocked on this ticket until design confirms how this should work, can we come up with an alternative so that users delete/bulk is not blocked ? 
or @Erioldoesdesign do you think this will be decided soon?

**Comment by Erioldoesdesign** [comment]
@rowasc Of all the Plat UI tickets this is the only one I don't feel comfortable making a decision on without @justinscherer around...only because at the end of the Hit Team he said he knew how he wanted to change/amend this.

I'e had a quick look through files for a newest version and can't find one in the dropbox. This will have to wait till Monday I'm afraid :(

**Comment by rowasc** [comment]
@Erioldoesdesign that's alright. Monday/Tuesday would be great  . If it's not possible just let us know :)

**Comment by justinscherer** [comment]
I'm on it today.

**Comment by justinscherer** [comment]
Here's a quick prototype to unblock this:

https://xd.adobe.com/view/df0747b4-7640-404f-6d3c-6af8f7a9db9c-a936/

I'll explain things in comments on the ptype. 

Design specs:

https://xd.adobe.com/spec/2110a313-afd9-4e50-6966-bf094ebfd5a8-5721/

**Comment by rowasc** [comment]
@Angamanga @sethburtonhall do you think you could implement this (the UI), this week? Anna, maybe its worth doing directly in the new components? Not sure 

@justinscherer this looks pretty easy to use. Thankk you for the detailed protoype

**Comment by sethburtonhall** [comment]
@rowasc @Angamanga  most of this view has already been coded. I can code the rest tomorrow and I think it would be great to jump in and add this to the React CL.

**Comment by rowasc** [comment]
@sethburtonhall that's awesome. Thank you! Yea, having it in react cl would be great 🎉

**Comment by rowasc** [comment]
"When a user has the option for bulk edits on a list (e.g. people), they should have the ability to select many items or one item in that list and be able to perform actions on those items. Shift + Click or"
 should be
"When a user has the option for bulk edits on a list (e.g. people), they should have the ability to select many items or one item in that list and be able to perform actions on those items."

right? 
Other than that, this looks ready for dev. I'd probably estimate a ~5 or 8 since it's a reusable component

**Comment by crcommons** [comment]
@rowasc Fixed it... 

I would say an 8 because the functionality is new and unknown plus the reusability. Happy to be convinced of a 5 though.

**Comment by rowasc** [comment]
alright, approving and moving it with 8. We can adjust next cycle if we feel we are overestimating consistently.
