### ISSUE TITLE
Change role for a person (settings/users) from the people list

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3063]
## Overview
Ctrl+Shift shows a "Change Role" option above delete users button at the bottom that is a drop-down and bulk changes the role of selected options

## Requirements/User Interface Behavior
- A user should select a person using the select behavior  https://github.com/ushahidi/platform/issues/3060
- After select event, show a button - "Change Role". The button is at the bottom of the list or is fixed on the bottom if the list is long.
- After clicking "Change Role", a confirmation modal should appear. The modal contains:
  - a dropdown to select the role, with the default option being "Select a role"
  - a "Save" button, which updates the role for each selected user and displays the updated role in the card for each person in the people list
    - a loading state should show for each person card until the save is successful; The updated user will show as each user update succeeds (one at a time);
  - a "Cancel" button which closes the modal, but keeps the users selected
  - "Save" button should be disabled until a role is selected
- if there is an error when saving, the users will remain selected and the error modal will appear

### New UI routes and views
- settings/users

### Component tree
- PeopleList (existing) -> PersonCard (existing) -> Modal (new)

### State tree
- When a user is updated, we will need to update each user in the people state list

## Acceptance criteria / Test script
- [ ] select one user; a Change Role button should appear at bottom of the list;
- [ ] select button; a confirmation modal should appear
- [ ] change the role using the dropdown;
- [ ] select "Save"; a loading state should appear while the save completes
- [ ] the loading state should disappear and the roles should be updated for the user
- [ ] refresh; user have the correct role
----
- [ ] select one user; a Change Role button should appear at bottom of the list;
- [ ] select button; a confirmation modal should appear
- [ ] change the role using the dropdown;
- [ ] select "Save"; a loading state should appear while the save completes
- [ ] the loading state should disappear and the roles should be updated for the user
- [ ] refresh; user have the correct role
-------
- [ ] select one user; a Change Role button should appear at bottom of the list;
- [ ] select the change role button; a confirmation modal should appear
- [ ] select cancel, the confirmation modal should disappear and you should see the list with the user(s) still selected

**Comment by rowasc** [comment]
@Erioldoesdesign am I correct that the edit role being an action triggered by the shift click? Can we have some designs for this (I know the actual shift click is probably hard/impossible in  the adobe previews you give us, but at least having the context buttons for the action would be great)

**Comment by Erioldoesdesign** [comment]
Resolved shift/click in https://app.zenhub.com/workspace/o/ushahidi/platform/issues/3060
