### ISSUE TITLE
Settings Hint component for people list

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3064]
## Overview
A component that displays in the any settings list component that tells the users how to bulk edit/delete. 

## Requirements/User interface behaviors
- When a user visits settings/users and selects "Select Many", a hint will appear within the list that describes how to bulk edit users (see design here: https://xd.adobe.com/view/df0747b4-7640-404f-6d3c-6af8f7a9db9c-a936/screen/a2d503ba-8066-4f9f-b8a5-2a8932a558a5/settings-people-select-many)
- The user should see the hint until they have clicked the 'X' (we should display it as long as we haven't indicated the user has dismissed it in local storage)
- When the user selects the 'x' the hint should disappear and we should store something in local storage that indicates the user has dismissed the hint

### New UI routes and views
- settings/users
### Component tree
- PeopleList(existing) -> Hint (new)

### State tree
No effects to state, however we will store data in local storage

## Acceptance criteria / Test script
- [ ] go to settings -> people; see that there is a hint displayed within the people list
- [ ] refresh; see that the hint is still there
- [ ] select 'x' to close the hint; hint should disappear
- [ ] refresh; hint should NOT display
------
- [ ] clear local storage
- [ ] go to settings -> people; see that there is a hint displayed within the people list

**Comment by crcommons** [comment]
TBD on review and estimate until design decides on shift+click

**Comment by rowasc** [comment]
APPROVED . 2 points estimate.
