### ISSUE TITLE
Ushahidi.io user unable to access their deployment.

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3068]
Repro Steps:

1) Go to https://ornet.ushahidi.io

2) See this error message:
![image.png](https://images.zenhubusercontent.com/5ac5411e4b5806bc2bcdb0c4/dc76a886-e8a7-4b66-bba5-c4e21c5b31ec)

Here is the original conversation, reported from an end user via @aoduor from Ushahidi's Facebook page.
![image.png](https://images.zenhubusercontent.com/5ac5411e4b5806bc2bcdb0c4/06eafbb3-fc94-451f-a563-843639258d6c)

**Comment by jrtricafort** [comment]
@aoduor it sounds like we can close this now, is that correct? Can you confirm with the user that they can now access their deployment from this link? https://ormet.ushahidi.io/

I think we had a typo in a previous version of the link we were using to test.

It also sounds like this was a new deployment that might have not been live yet at the time the user was trying to access it. Is that correct @aoduor @tuxpiper ?

**Comment by aoduor** [comment]
Yes. Correct on both fronts. I'll close out.

User confirmed being able to access.

Thank you both.
