### ISSUE TITLE
Support for COMRADES platform evaluations in September

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#3069]
## Overview
The output of this Epic will be a few deployments that are spun up with all COMRADES features available (including the "multiple deployments" view - #2799 - which seems to have fallen off the radar) for a COMRADES simulation and evaluation at some point in September. Another output will also be a schedule of support for the deployers. 

## Who is it for? Who are the users?
This is for TU Delft (a COMRADES partner) who is conducting evaluations of the platforms by using them in simulations. We have done this once with them already (Robbie, David, and Will all acted as support to fix bugs, etc.). 

## What privacy impacts does it have?
This will not have privacy impacts. 

### Who will this be deployed to?
e.g. will it be feature flagged? will it go to just once deployment?

## Deployment

*Does this deploy new services?*
*Do the new services have health checks?*
*Can this be feature flagged and deployed disabled?*

**Comment by jrtricafort** [comment]
@willdoran Looping you in on this. Let's discuss here this week.
@Shadrock Flagging that Multiple Deployments is not production ready and I don't think we'll be able to get in place for this.

**Comment by jrtricafort** [comment]
As for the actual support during the evaluations in September, we can provide developer support for this, we just need to know more of the specifics (i.e. schedule) how the evaluations will be run and on how the feedback will be provided.

**Comment by rjmackay** [comment]
We can easily add some more deployments to the existing dashboard, or replace the ones that are there. I'm not sure if there are more requirements than that.

**Comment by jrtricafort** [comment]
@Shadrock @willdoran  I caught up with @rjmackay and got some more context here about Multiple Deployments. I may have been misunderstanding this earlier, so you can disregard my previous comment on it. It sounds like we don't even need to deploy another Multiple Deployments dashboard-- we can use the existing one and add new deployments to it (Lumen shouldn't break this).

**Comment by jrtricafort** [comment]
@Shadrock Can you provide an update here regarding what is needed, and when?

**Comment by Shadrock** [comment]
@jrtricafort reaching back to COMRADES folks... haven't heard anything further on this, but will keep bugging them.

**Comment by Shadrock** [comment]
@rowasc Ok... this is finally happening. In November. And on short notice... apologies for that. To close this issue out I need: 

- [ ] A demo version of the COMRADES platform. Can we use the URL: https://comrades-test5.ushahidi.com? This version should have all integrations _except_ the FB bot. 
- [ ] A hosted version of Ushahidi Basic (I think that's what we're calling it now) with a one year license that will be used by the Humanitarian Openstreetmap Team in Indonesia. They're partnering with us on some COMRADES stuff. I've asked them to set up a demo deployment that we can upgrade. Please advise if they should do this differently. 

### Timeline
Bascially, ASAP. They want to get testing going on November 5th. Is it possible to hit this date with the COMRADES test deployment?

**Comment by rowasc** [comment]
- Hosted ushahidi: yes that approach is fine. Once they are setup ping us to upgrade it
- this would be like comrades-stg but without FB BOT right? If yes, thats fine, I will do it tomorrow and ping you if anything goes wrong, I just need to rearrange my plan for the day and if I need to I will switch my days off so we make it .

**Comment by Shadrock** [comment]
Thanks so much @rowasc: I owe you one. 
> this would be like comrades-stg but without FB BOT right?

Correct.

**Comment by rowasc** [comment]
Updating since I only did it in slack
-.The test server is up. Need to do some tests tomorrow to be safe but it looks fine.:tada:

**Comment by Shadrock** [comment]
We got everything we needed on this. Thanks all.
