### ISSUE TITLE
Upgrade to higher Testpad Account

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3076]
Paraphrasing from @rowasc :

We keep hititng our limit on Testpad, which blocks Eve. We should get a subscription with a higher limit ASAP. Otherwise, test-pad does not serve its purpose very well

**Comment by rowasc** [comment]
@jrtricafort @rjmackay I think now that we reorganized testpad we can drop the priority to P1 and see what we want to do about it without feeling so rushed .

**Comment by jrtricafort** [comment]
@rowasc Done

**Comment by rowasc** [comment]
This is working out fine for our current needs. Unassigning and setting up the consider tag.

**Comment by rowasc** [comment]
Closing. I'll reopen if we ever need to do it
