### ISSUE TITLE
SupportDocs: User Roles - New Permission for "Manage Collections and Saved Searches"

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3077]
Existing SupportDocs page: https://www.ushahidi.com/support/custom-roles#add-a-role

There is a new enhancement to Role Permissions: https://github.com/ushahidi/platform/issues/2491

As such, we have to make changes to our documentation. We will also use this opportunity to further clarify how Collections work (i.e. Collection ownership)

-clarify that Admin can NOT be edited
-add Manage Collections paragraph (allows users to add/remove posts, and also edit/delete anybody's Colections regardless of ownership)
-edit Manage Posts paragraph (users can only add/remove posts to Collections that they own)
-add to Manage Posts paragraph (users can edit/delete Collections that they own)

Juan will sync with Angie/Staicie to review this.

**Comment by jrtricafort** [comment]
@aoduor @StaicyG Flagging that this is ready for documentation. I will add some more specific language to the scope of the definition above. Recommending this as a candidate to consider for the Documentation Sprint next week.

**Comment by rowasc** [comment]
Hey @aoduor @StaicyG @jrtricafort    is this happening during cycle 7? just checking in case we need to move it out

**Comment by aoduor** [comment]
Yup. It is! thanks for flagging.

**Comment by rowasc** [comment]
@StaicyG should I move this to In Development? Do you need access to a QA env to review/get context on the changes? (QA environment can be the same one you used for the other doc task last week, if that's the case)

**Comment by StaicyG** [comment]
Yes, please assist me with QA credentials for me to test it out. Will move this to development.

**Comment by jrtricafort** [comment]
Update-  @rowasc sent the QA credentials a couple weeks ago. @StaicyG @aoduor what's the status of this?

**Comment by StaicyG** [comment]
@jrtricafort finalising on it

**Comment by rowasc** [comment]
@aoduor @StaicyG was this published? do you need a review?
(sorry last week was lumen week so I basically lost track of this)

**Comment by aoduor** [comment]
dropped off radar with Lumen last week too. Keep an eye out by wednesday?

**Comment by aoduor** [comment]
Never mind. Updated: https://www.ushahidi.com/support/custom-roles#add-a-role

Closing.
