### ISSUE TITLE
Enable targeted SMS feature for new DREAMS partner

### ISSUE THREAD

**Issue by dukedanny** [ushahidi/platform#3079]
Regular dev request.

Please enable the targeted SMS feature for our new DREAMS partner RHSP. 

URL: https://rhsp.ushahidi.io/

**Comment by jrtricafort** [comment]
@rowasc @kinstelli This is just a simple feature flag on our end, right?

@dukedanny What country will this be? Once we set up the Targeted SMS feature on the platform for them, you can setup the SMS configurations, correct?

**Comment by jrtricafort** [comment]
Moved to Cycle 5, Ready for Spec.

**Comment by dukedanny** [comment]
@jrtricafort This is for Uganda. Yes, I actually have the SMS configurations already set up for the deployment.

**Comment by kinstelli** [comment]
@jrtricafort - yes, I think so. I believe I can do this in a few minutes

**Comment by kinstelli** [comment]
@dukedanny - Okay, this appears to be complete, at least as far as Platform is concerned. I'm not sure what SMS providers they will want to use, of course, but let me know if you need to coordinate testing.

**Comment by jrtricafort** [comment]
@dukedanny let me know if this is set up now for you and if we can close this.

**Comment by dukedanny** [comment]
@jrtricafort I confirm that I've been able to test the targeted SMS feature with success on this deployment. Thanks for the support @kinstelli

**Comment by jrtricafort** [comment]
Great, thanks @dukedanny and @kinstelli !
