### ISSUE TITLE
Lat & Lon columns for location fields in CSV files with HXL tags should have different HXL tag+attributes

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3083]
## Overview
When you map a "#geo+lat" or "#geo+lon+lat" or r "#geo+lat"  to a location field, that will be assigned to both lat and lon, and there's no way to assign the correct attributes to each. This is incorrect as each column should be mapped to the correct attribute. We will make the assumption that when a user adds a +lat or lon to a #geo tag, they are adding both and want a correct export with the tags aligned to the columns in the csv in the format: 
`Location.lat | Location.lon`
`#geo+lat`|`#geo+lon`

## Requirements
- The geo+lat and geo+lon should be assigned the correct columns in a csv with location fields. It's still unclear how we achieve this

## Current behavior
If I have a field "Location", the CSV represents it as two columns: 

`Location.lat | Location.lon`

In the ui, it's represented as a single field, Location.

## Expected behavior (CSV)
For a location field with lat/lon, the csv should be represented as
`Location.lat | Location.lon`
`#geo+lat`|`#geo+lon`

## Expected behavior (UI)

- [ ] User checks 'Location field'
- [ ] Chooses #geo as the HXL tag
- [ ] Attribute drop-down becomes 'active' (not greyed out)
- [ ] User chooses +lon as the 1st attribute.
- [ ] A second attribute drop-down populated with +lat is automatically added. The tag preview is populated with the 'two' tag&attribute previews shown in the above screenshot. (#geo+lat and #geo+lon)

**Comment by rowasc** [comment]
@willdoran @shadrock @Erioldoesdesign I think we should discuss this as it came up during our demo (when HDX was demo-ed to Shadrock) and it looks pretty bad. 
From a user perspective, I'm not so sure of what's the correct thing to do. Ideas? Thoughts? 
IMO this should be considered for cycle 6

**Comment by Erioldoesdesign** [comment]
@rowasc I'm syncing with Hazel on this tonight and @Shadrock has an action from our last HDX demo/meeting to do the task of 'Format your ideal CSV using some existing deployment data' and design team will take this (and Hazels version too) to put together recommendations and talking points around this.

So we'll be waiting on these 'ideal CSV's' for the more in-depth work around CSV optimisations but we can for sure address the lat+lon column case described in this ticket :)

**Comment by Erioldoesdesign** [comment]
Here are the designs I showed on the call:

Currently we smush lat & lon together into a combined attribute:

![Data export - HDX single survey – Lat-Lon Geo - combined.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/98239eec-7b47-4caa-b2ca-bb2f4c85a8bb)

My proposal would be that lat and lon are always display like this for a location field that has the #geo HXL tag assigned to it:

![Data export - HDX single survey – Lat-Lon Geo - single.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/369d0241-94db-48ba-b103-8f2f1f549283)

It may not be a perfect user journey but what I'd like to do is force lat & lon to always be chosen if one is.

So the journey is:
1. User checks 'Location field'
2. Choses #geo as the HXL tag
3. Attribute drop down becomes 'active' (not greyed out) 
3. Choses +lon as the 1st attribute. 
4. A second attribute drop down populated with +lat is automatically added. The tag preview is populated with the 'two' tag&attribute previews shown in the above screenshot. (#geo+lat and #geo+lon)

These will now populate lat & lon in two separate columns in the spreadsheet.

If the user adds in a third attribute drop down (#geo can also be used with +elevation). The tag preview will populate a new #geo+elevation (so there would be three 'tag previews')

**Comment by rowasc** [comment]
@Erioldoesdesign this is really nice and not overly complex, I think. Thankk you! I'll update the spec

**Comment by rowasc** [comment]
@willdoran can you review? This is a pretty simple change in the API and the UI uses pre-existing components so I think it should be a 3, but CSV is really annoying so maybe a 5 makes more sense. 
What do you think?

**Comment by willdoran** [comment]
approved, it looks fine

**Comment by willdoran** [comment]
@rowasc this looks like a 5?

**Comment by rowasc** [comment]
@Eve-wanderi can you test? 
passed for me .

**Comment by Eve-wanderi** [comment]
@rowasc  this passed QA. However this only happens if the #geo is selected as the Attribute Tag if user selects #Meta this is not the case.

![Lat Lon.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/fb7304cc-414a-4b47-98a2-570c8f229799)

**Comment by rowasc** [comment]
@Eve-wanderi yep, meta does not apply herel, thanks

**Comment by Eve-wanderi** [comment]
Okay this Passed for me as well. Ready for Production
