### ISSUE TITLE
<Icon> component for react migration

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3084]
## Overview
To be able to add svg Icons in the client for the react app in a way consistent to react, we need a react component that has the available/used SVG icons, receives the icon name and returns the component. 
This blog post is pretty complete and explains this process in detail https://medium.com/@david.gilbertson/icons-as-react-components-de3e33cb8792

## Requirements
Add a new <Icon /> component that receives the icon and returns the SVG for rendering it.
### Schema changes
e.g. new tables or tables to be modified.

### API endpoint definitions
e.g. new endpoints or endpoints to be modified. Should include example payloads

### New UI routes and views
e.g. Which routes are being added or modified, and top level views effected.

### Component tree
e.g. heirarchical tree of new UI components being added, or which components are being modified

### State tree
e.g. new data being added to state, and related actions and reducers. Should include example payloads.

### User interface behaviors
e.g. When I click "save" I see a confirmation popup.

## Acceptance criteria / Test script
If a UI exists, include user test scripts.
If no UI exists, specify postmans calls or similar.

**Comment by sethburtonhall** [comment]
I think we can close this. Right @Angamanga?

**Comment by rowasc** [comment]
Keeping this iceboxed for now. but if it's actually closed, please close it @Angamanga

**Comment by Angamanga** [comment]
CLose close!
