### ISSUE TITLE
Platform sends out responses to SMS messages multiple times

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3085]
**Describe the bug**
User was sending a response to a text message received on a DREAMS deployment via data view. User sent a single response message "How did you find the training" to respondent. The respondent received this message from Ushahidi user more than 30 times. 

**To Reproduce**
1. Log into any ushahidi.io deployment
2. Select an unstructured message from SMS
3. Scroll down and click on "Send new message"
4. Check on # of responses sent to respondent.

**Expected behavior**
Respondent should receive one text message response from the Ushahidi user.

**Screenshots**

**URL / Environment where this happened**
Ushahidi.io
https://rhsp.ushahidi.io

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser: Safari

**Additional context**
Nothing more to add here.

**Comment by jrtricafort** [comment]
@aoduor @dukedanny What is the SMS setup for this deployment? Can you provide the configuration details?

**Comment by dukedanny** [comment]
I've checked Africa's Talking. From the log, it appears the message was billed once, however the text went out multiple times. Its an error on their end. I'll share in the DREAMS channel the outcome of their investigation. This issue can be closed on platform. 

<img width="1068" alt="investigation" src="https://user-images.githubusercontent.com/437728/41606646-d643ad34-73ec-11e8-851c-45300e57d40e.png">

**Comment by rowasc** [comment]
@jrtricafort looks like we can close it then?

**Comment by aoduor** [comment]
Thanks for handling this with speed everyone.
