### ISSUE TITLE
Unable to Name Saved Searches 

### ISSUE THREAD

**Issue by Hazellaura** [ushahidi/platform#3086]
**Describe the bug**
We were trying to create new saved searches. We were able to filter and select the specific search but were unable to complete the process by naming the saved search and saving it. 

**To Reproduce**
1. Go to the sort and filter menu via the map view. 
2. Click on a key word to search e.g. District name and then filter out any other fields or categories you would like to filter e.g. the name of the survey or the status of the report. 
3. Scroll up to save search to name and save the saved search.
4. See error- you cannot assign a name to the saved search and therefore you cannot save the search. It does not allow to give the saved search a name. It is as though the keyboard freezes off even after you log back in, 

**Expected behavior**
I expect to be able to sort and filter the information that I need and then to be able to save the search. I expect that when the pop up on where to name the saved search appears, that I can assign a name to the saved search as well as a description and then to save the search. 

## Test checklist

Testing checklist:
Test 1 - create a saved search: 
- [ ] Go to the sort and filter menu 
- [ ] Add any filter (for example, a category filter)
- [ ] Click the save search button in the filters menu 
- [ ] Create your saved search. Add a name and description

- [ ] You should be able to edit it successfully. 
Test 2 - select and edit a saved search: 
- [ ] Go to the sort and filter menu 
- [ ] Select a saved search
- [ ] Click the edit button
- [ ] change the name of the saved search in the edit modal
- [ ] change the description of the saved search in the edit modal
- [ ] You should be able to save it successfully. 

**Screenshots**

**URL / Environment where this happened**
https://rhsp.ushahidi.io/views/data

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jrtricafort** [comment]
@aoduor @Hazellaura Can you provide (via a private channel like LastPass) information on how to log into this deployment? We need a support@ account or admin@ account to be able to test. Or please upgrade my juan@ account so it has admin access.

**Comment by jrtricafort** [comment]
Marked as P0.

Tag @rowasc and @willdoran . Let's get Dev attention on this as well. Contact me if we need clarity on what should get deprioritized so that this can be supported. Please reach out to Hazel or me if you need a login.

I was able to repro this.

**Comment by rowasc** [comment]
@Eve-wanderi this is probably going to go as a hotfix in the morning, can you check my test checklist ? When it's deployed I'll ping you for a test run . :)

**Comment by jrtricafort** [comment]
@rowasc Can we go ahead and push this as a hotfix so it can unblock the Uganda training?

**Comment by rowasc** [comment]
Yep, just waiting for code review, then I'll retest and push to prod as hotfix

**Comment by rowasc** [comment]
@willdoran I think this is a 1 (forgot to estimate yesterday :( ) . . Do you agree?

**Comment by rowasc** [comment]
Ready in ushahidi.io
 @Hazellaura

**Comment by jrtricafort** [comment]
@Hazellaura @aoduor Fix has been pushed. Can you let us know once you've confirmed this is working again?

**Comment by aoduor** [comment]
Working.

**Comment by rowasc** [comment]
@Eve-wanderi can you add this to the test scripts for future regressions?

**Comment by Hazellaura** [comment]
Thank you guys @rowasc @jrtricafort @willdoran
