### ISSUE TITLE
Invalid or expired reset token error while trying to set my new password

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3087]
**Describe the bug**
When I try to reset my password by clicking the link in the reset password email, I get an error "Invalid or expired reset token". 

**To Reproduce**
1. Go to a ushahidi.io deployment 
2. Click on the Login button
3. In the login modal, click on "forgot your password? "
4. In the "Forgot your password" modal, set your email and hit the "RESET MY PASSWORD" button.
5. Wait for the password reset email. When you get the email, click on the "Reset your password" button. 
6. In the Reset password modal, try to setup your new password. 
7. you will receive an error "Invalid or expired reset token" 

**Expected behavior**

1. Go to a ushahidi.io deployment 
2. Click on the Login button
3. In the login modal, click on "forgot your password? "
4. In the "Forgot your password" modal, set your email and hit the "RESET MY PASSWORD" button.
5. Wait for the password reset email. When you get the email, click on the "Reset your password" button. 
6. In the Reset password modal, try to setup your new password. 
**7. You should be able to reset your password and login with it**

**Expected behavior 2**

1. Go to a ushahidi.io deployment 
2. Click on the Login button
3. In the login modal, click on "forgot your password? "
4. In the "Forgot your password" modal, set your email and hit the "RESET MY PASSWORD" button. Stay in the confirm modal.
5. Wait for the password reset email. When you get the email, copy the token manually into the confirmation modal's "Password reset token" field and setup your new password. 
**6. You should be able to reset your password and login with it**

**Screenshots**
<img width="565" alt="screen shot 2018-06-19 at 11 17 57 am" src="https://user-images.githubusercontent.com/2434401/41603063-982e8c42-73b2-11e8-9ac2-f1ec09f8f09f.png">

**URL / Environment where this happened**
https://juantest.ushahidi.io/

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser : Chrome
 - Version: 67
**Additional context**

**Comment by rowasc** [comment]
@jrtricafort I found this while trying to reproduce another issue. Can you prioritize?

**Comment by jrtricafort** [comment]
@rowasc If this bug is currently live in the production environment and reproducible in all Forgot Password cases, then this is a p0 since there is no workaround.

**Comment by jrtricafort** [comment]
However, because of the Training blockage, #3086 and #3805 should still take priority (order) over this.

**Comment by rowasc** [comment]
Since this seeems to be a problem with the url encode/decode , I'd say it's a 1.

**Comment by kinstelli** [comment]
Yeah, it smells like a urlencode/decode issue, which would be a 1.

**Comment by rowasc** [comment]
@Eve-wanderi can you please verify this in the production environment (https://rominacsvsms.ushahidi.io/) ? Thanks

**Comment by rowasc** [comment]
Verified in production deployment. Closing

**Comment by rowasc** [comment]
This is inconsistent, the decode should have happened in the client to avoid issues when we send the non encoded value from the confirm modal (manual) or an http request directly from curl/postman/etc

**Comment by rowasc** [comment]
Found issues for this ticket ,  sent PR . This was found while testing https://github.com/ushahidi/platform/issues/1606

**Comment by rjmackay** [comment]
@rowasc testing on current master this seems to break all password resets. We're already decoding the URL in the client side, but now we're decoding again on the API and it's breaking. I can't see the client sending a urlencoded password to the API at all on master

I'm going to retest on production, but probably revert this in master.
