### ISSUE TITLE
Document, reflect upon, and fix tech debt, anti-patterns, best practices in JS Migration

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3089]
It's too difficult to know exactly how to do everything correctly the first time, so we'll need to address tech debt, anti-patterns, and poor practices before we move further into the JS migration beyond users. 

We'll document areas to discuss, research, reflect upon here: https://docs.google.com/document/d/1qs6mpANKDwr9x7a89Ei9IXHq4ejIpKffqANCjq1cLLU/edit?usp=sharing

Then we'll discuss at the end up cycle 6 and create issues to work on in cycle 7.

**Comment by rowasc** [comment]
Closing but tagging with framework rewrite and docs so we can still find the information
