### ISSUE TITLE
UI: Timeline Chart missing lines

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/platform#309]
Clicked on Timeline for Categories.
The Graph for "positive reports" appears to be missing the line. 
The font is too small. 

Firefox, OS
<img width="1036" alt="screen shot 2015-08-13 at 3 33 45 pm" src="https://cloud.githubusercontent.com/assets/1216707/9249790/c2fdf3ca-41d0-11e5-8aae-d2fc73f93d83.png">

**Comment by rjmackay** [comment]
@vbhv

**Comment by jshorland** [comment]
Should be fixed alongside mustang design implementations

**Comment by rjmackay** [comment]
Need steps to reproduce

**Comment by jshorland** [comment]
I'm closing this -- I can't reproduce it.
