### ISSUE TITLE
API Changes to Enable Custom Payment Plans

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3090]
To accommodate custom or nonstandard payment plans, we need to make changes to the API.
## Current behavior
- We map plans in chargebee directly to tiers in the cloud API and DB.
- Feature limits are defined in Tiers (with overrides for each deployment)
- We can easily create new plans in chargebee, but without a matching plan in the cloud DB they don't get any paid features enabled

## Possible solutions

- Split feature limits from the tiers themselves, and add a mapping between tier and features in DB.
    - That would make it faster to add several tier with the same feature limits.
    - We'd still have to add new tier to for each plan.
- OR we could use the JSON metadata in the chargebee plan to specify feature limits or groups of feature limits.
    - This might be more flexible. But it's potentially error prone (ie. if someone saves the wrong JSON in chargebee it could break the plan for everyone)

**Comment by rjmackay** [comment]
I'll leave the detail of this till we have the overall payments spec. The basic issue back is this:

- We map plans in chargebee directly to tiers in the cloud API and DB.
- Feature limits are defined in Tiers (with overrides for each deployment)
- We can easily create new plans in chargebee, but without a matching plan in the cloud DB they don't get any paid features enabled

A couple of ways we could solve this:
- Split feature limits from the tiers themselves, and add a mapping between tier and features in DB.
    - That would make it faster to add several tier with the same feature limits.
    - We'd still have to add new tier to for each plan.
- OR we could use the JSON metadata in the chargebee plan to specify feature limits or groups of feature limits.
    - This might be more flexible. But it's potentially error prone (ie. if someone saves the wrong JSON in chargebee it could break the plan for everyone)

**Comment by rowasc** [comment]
@jrtricafort why do we need this? I'm not sure I understand since we don't do feature limits for paid customers in the new pricing version

**Comment by jrtricafort** [comment]
@rowasc There will be some feature limits. Currently the only feature limit is Targeted Surveys, but in the future this could expand to more feature flags. Does that help clarify?

**Comment by rowasc** [comment]
I don't think this is still a valid ticket going forward. Tagging with Pricing (SaaS) in case it's useful to identify later and closing
