### ISSUE TITLE
Migrate styles from PL/ui-refresh-branch to Component-library

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3094]
## TODO:
Move already styled components (including layouts) that belongs to the PeopleList into the component-library.

Designs: https://xd.adobe.com/view/e8878276-4282-4a3c-59e9-3a9fa771fc90-9eb6/screen/2381c9ed-0371-4e4b-8afb-22bfb1ffb7c5/settings-people

**Comment by sethburtonhall** [comment]
@Angamanga, can this be closed? If not, maybe we can work together to close tomorrow.
