### ISSUE TITLE
Import fonts into component-library

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3095]
## TODO: 
- Decide on where to get the fonts from? Downloading them ourselves or google-fonts? Current fonts we are using seem to be depreciated/old and google/other places use other naming for the Lato-fonts 
- Import the fonts into the component-library and use them

**Comment by sethburtonhall** [comment]
@Angamanga can we work together to close this tomorrow?

**Comment by Angamanga** [comment]
@sethburtonhall I *think* we could close this but lets look at it when you are online!
