### ISSUE TITLE
Fix error-label style

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3099]
The error-label in form-fields are misplaced for dropdowns:
![Screen Shot 2018-06-21 at 10.17.17.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/2ebf33d5-a2c4-4f20-b5c2-1ef52c25694b)

![Screen Shot 2018-06-21 at 10.22.17.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/3a2a0571-fbb2-4cc8-b918-99b2faca5ef8)

Html used: 
``` 
<div class="form-field error">
    <label>Select control</label>
    <div class="custom-select">
        <select>
            <option>Option 1</option>
            <option>Option 2</option>
        </select>
    </div>
    <span class="error">ooops something went wrong</span>    
</div>
```

**Comment by rowasc** [comment]
@sethburtonhall is this something you can check?

**Comment by Erioldoesdesign** [comment]
This looks good to me in the PL positioning wise.

I would say that an error state (red border) is a kind of focus state for the field and therefore the border radius of the drop down error state should be 5px not the default 2px. As detailed in #2640

Here's the PL one:

![Screen Shot 2018-07-10 at 22.46.20.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/ff745d78-75dc-4529-b618-5dbb074e2692)

vs the sketch file version of a input form field error state (the drop down error state should follow the same rule):

![Screen Shot 2018-07-10 at 22.35.27.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/d6dad2cd-1af2-4f22-a344-909d2ac22f96)

**Comment by sethburtonhall** [comment]
Yes, except that I still need to integrate @Erioldoesdesign's latest QA feedback above.

**Comment by sethburtonhall** [comment]
Thanks, @Erioldoesdesign. Small and quick change. Closing.
