### ISSUE TITLE
ISOOKO - Workshop framework outline

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform#3100]
Off the back of the ISOOKO Hague meeting. Design is to start working on the workshop framework/outline.

WIP framework here: https://docs.google.com/document/d/11Xgp_5Y1oNez9KjIr86wwVQ--4fwUkw-kuh4SB5pPmc/edit?usp=sharing

**Comment by rowasc** [comment]
@Erioldoesdesign @jrtricafort should this move to cycle 9? I don't see it in the plan/roadmap  doc for cycle 8, checking just in case I'm missing something

**Comment by jrtricafort** [comment]
@Erioldoesdesign are you anticipating working on ISOOKO Workshop framework this cycle?

**Comment by Erioldoesdesign** [comment]
@rowasc @jrtricafort I think so. Probably only a 5 pointer though as we're trying to close out on this workshop framework

**Comment by jrtricafort** [comment]
Got it, thanks.

**Comment by rowasc** [comment]
@Erioldoesdesign is this done?

**Comment by Shadrock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ISOOKO workshop Draft Doc](https://trello.com/c/wmgUjGts/17-isooko-workshop-draft-doc)

**Comment by Erioldoesdesign** [comment]
FYI this is being tracked here: https://trello.com/c/wmgUjGts/17-isooko-workshop-draft-doc

It's so almost finished I can taste it!

**Comment by rowasc** [comment]
@Erioldoesdesign is this done?  should we close it?

**Comment by rowasc** [comment]
Cool! closing . I dont' have access to the trello so I wasn't sure :) thanks!
