### ISSUE TITLE
Replace "reports" with "posts"

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3105]
### Requirements
There should be no instances of the word "reports." Instead all instances should refer to "posts"

### Acceptance criteria
- Navigate to data view 
- [ ] see that the list refers to "posts"

**Describe the enhancement**
When we moved to v3, we renamed the primary object in the platform from "Reports" to "Posts". However, throughout the platform there are still some cases where we call them "Reports". These should be changed to consistently be called "Posts"

Example:
![image](https://user-images.githubusercontent.com/37776843/41789171-65667df8-761c-11e8-97dc-ddb689c23bb8.png)

List of all places where "Reports" is used:
- Data Mode list
- There might be more. Juan to find this out during Scoping.

**Comment by rowasc** [comment]
@crcommons do we need to spec this any more? It's literally just changing some text so I'd say 1point.. right?

**Comment by crcommons** [comment]
@rowasc Agreed. Adding estimation now.

Also, I could have sworn this said posts before and we were asked to change it to reports.

**Comment by rowasc** [comment]
@crcommons everything passed except for the text in Datasources that says 'In order to receive reports by email, please input your email account settings below' . Can you check?

**Comment by rowasc** [comment]
@crcommons from the code it looks as if the text comes from a db option but I can't find it :/ still looking at it

**Comment by rowasc** [comment]
@crcommons sorry for spamming. Yes, it's coming from the backend in the /dataproviders endpoint

**Comment by crcommons** [comment]
@rowasc Moving back to "In development" and will work on API change for this today or tomorrow.

**Comment by crcommons** [comment]
@rowasc Just confirming I need to implement this in lumen and kohana?

**Comment by rowasc** [comment]
@crcommons I think lumen-only might be OK since it's text change in an admin-only place of the app and we are launching lumen soon anyway (so absolutely not a P0-P1).  @jtricarfort correct me if I'm wrong

**Comment by crcommons** [comment]
@jrtricafort @rowasc did we decide if this can wait until lumen is in production?

**Comment by rowasc** [comment]
@crcommons we are going to release it before lumen goes live

**Comment by Eve-wanderi** [comment]
Confirmed i checked and reports have been replaced with Post. Passed QA.
