### ISSUE TITLE
Delete a user in user/edit

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3107]
## Overview
Create a component within the edit person view that allows you to delete that person

## Requirements/User interface behaviors
- [ ] create a separate component for deleting a user
- [ ] has a delete button that displays a confirmation modal
  - [ ] the confirmation modal should have a delete button that deletes the user and a cancel button that takes you back to the edit page
  - [ ] after deleting the user, you should be routed to the list page
  - [ ] you should see a red line around the user and they should disappear from the list
- [ ] if there's an error when trying to delete, then display error modal and stay on current page
### Component tree
- PersonEditForm -> DeletePerson(new)

### State tree
- this should remove the user from the people list in state after you have been re-routed to the people list page

## Acceptance criteria / Test script
- go to settings -> people -> select a person
- go to the delete section and click delete
- [ ] a modal should appear 
- click cancel
- [ ] you should be taken back to the edit page
-----
- go to settings -> people -> select a person
- go to the delete section and click delete
- [ ] a modal should appear 
- click delete 
- [ ] you should be redirected to the list of people
- [ ] you should see an animation around the person who was supposed to be deleted and then that person should be removed from the list

**Comment by rowasc** [comment]
@crcommons this looks ok. Do we need a loading component while deleting? 
I'd estimate this at ~2

**Comment by crcommons** [comment]
@rowasc I actually think this should be a 3+. I'm not sure how we're going to do redirect after deleting the user and then removing the user from the list in simple way.

**Comment by rowasc** [comment]
Alright super fair then. Would 3 be OK or do you feel strongly that this is a 5?

**Comment by crcommons** [comment]
I feel like it's a 5 because it's complex and I don't know how we're going to do it.

**Comment by rowasc** [comment]
oh. OK That's way higher than I expected, but I'll agree because I just don't have a (super) strong opinion. lets go with 5

**Comment by rowasc** [comment]
APPROVED with 5, btw

**Comment by Erioldoesdesign** [comment]
@crcommons re. error when deleting a person - Ah this is more tricky... so the user journey is:

Individual person (or multiple selected people) -> click a delete button -> Get a modal 'Are you sure?...' -> Click delete button in modal -> Error -> ???

So I would say that in both instances it should go back to the Individual person (or multiple selected people) state. We either need some kind of inline error validation that says: We could not delete this person / these people or we use the undo functions in a red error colour. Thoughts @justinscherer ?

**Comment by justinscherer** [comment]
Yeah, we use the modeless "undo" module with the error styling (red outline instead of green, red "x" icon instead of green checkmark), and stay on the view where the user first tried to delete the person (person details in this case, or the people list if they try to do it as a bulk action)
