### ISSUE TITLE
HDX Datasets should be created and validated when the user requests an export job

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3108]
## Overview
This needs to be done to allow the user to fix validation errors at the metadata screen. 

## Requirements
- When the request to create new export job metadata is made, platform-api will send a request to HDX to create the dataset. 
    - If there are validation errors, we will respond with the errors and the client will display them in the UI
-  A loading state will be shown in the metadata screen while we verify the data
- If there is a validation error, the user will see it after they hit "Submit" in the metadata screen and will be able to fix it.

### User interface behaviors
- When I click Send to HDX in the HDX metadata screen (https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/1c15cc61-5a2e-4dbe-8018-a7bd2b559d40/Data-export-CSV-landing-page-HDX-single-survey-20/?fullscreen) , a loading state appears. 
- If there are validation issues for my dataset, I can fix them and submit again.

## Acceptance criteria / Test script
Test that the correct configuration still creates an export job: 
- [ ] Create a new HDX export job. In the metadata screen where you configure dataset title, license, etc, fill in all the data correctly. 
- [ ] Click on the send to HDX / submit button
- [ ] A new export job should be created that can be seen in the export job history (list)
- [ ] After ~5 minutes, a dataset with a resource is shown in my hdx account

Test that validation errors are displayed and I can fix them
- [ ] Create a new HDX export job. In the metadata screen, add a dataset title that already exists outside of your organization. 
       - NOTE for testing: To do this, you need to first have created a dataset in *another organization* with a slug like orgname-dataset-title (ie: ushahidi-dataset-title), where orgname matches your organization. Otherwise it won't match because we prepend the orgname to the title to generate the slug. 
- [ ] You should receive an error that tells you the dataset title is already in use
- [ ] Edit the dataset title to something unique 
- [ ] Try again
 - [ ] Your export jobshould be created if there were no other errors.
- [ ] After ~5 minutes, a dataset with a resource is shown in your hdx account

## Dependencies

Aha! Link: https://ushahiditeam.aha.io/features/PROD-324

**Comment by rowasc** [comment]
@willdoran I realized we don't need new set of UI changes. We can do the HDX request when the user submits right at the point where we create the hxl_metadata entry for the job and give feedback there. 
https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/1c15cc61-5a2e-4dbe-8018-a7bd2b559d40/Data-export-CSV-landing-page-HDX-single-survey-20/?fullscreen

**Comment by rowasc** [comment]
@willdoran can you review?  I think this is probably an 8, since I need to change how we handle the metadata creation and HDX creation of datasets, and probably some light refactors of the "library" as well as adding new tests. It also includes small UI changes for showing validation from the server

**Comment by willdoran** [comment]
@rowasc I think an 8 would make sense given the number of moving parts.
