### ISSUE TITLE
A user should be able to choose if they want to update or create a dataset in HDX

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3109]
## Overview
Right now if a user selects a dataset title that already exists, we assume they want to update it. 
We should provide the option to select an existing dataset to update or to create a new one with a new title.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-323

**Comment by rowasc** [comment]
@willdoran Added this so it doesn't get lost

@jrtricafort @Shadrock @Erioldoesdesign is this a priority ? We discussed adding this with Will today and it would make sense to me, but I don't know if it's something we want to do now or in another cycle

**Comment by jrtricafort** [comment]
@rowasc @Shadrock @Erioldoesdesign I don't believe that this should be included in the v1 scope. Let's discuss on slack HDX channel or in a sync if you disagree.

**Comment by Erioldoesdesign** [comment]
Agreed that this is not priority for HDX v1. Moving it to my '[HDX Future Features and Wish List](https://docs.google.com/document/d/1NCdqNi8t1eiiKR_RwQj2JzVkXV21uZ09LNyLtshUXqo/edit?usp=sharing)' WIP document to keep until we get further funding to develop this feature.
