### ISSUE TITLE
Send email to user any time their password is changed.

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3110]
Anytime a user's password is changed, they should receive an email letting them know that this has occurred.

**Comment by Erioldoesdesign** [comment]
LGTM

'Courtesy' sounds bit formal to me? but that's more because I'm used to brand tone of voices that are more conversational. I think @aoduor would be a good person to approve tone of voice for comms.

**Comment by tuxpiper** [comment]
It would probably make sense to tackle this together with #1421

**Comment by webong** [comment]
Hello @tuxpiper @Angamanga ... I just made a PR that solves this use-case here https://github.com/ushahidi/platform/pull/3863 ... Would appreciate, if you could review this for me, thanks.

**Comment by Angamanga** [comment]
@webong Thank you for your contribution! We will review shortly. 🎉

**Comment by Angamanga** [comment]
@Obadha2 Could you QA in Steve Buscemi? 
Testing-checklist:
1. Login to your deployment
2. Change your password
- [ ] You should receive an email to your registered email informing you that your password was changed

**Comment by Obadha2** [comment]
QA'd, passes. 👍
