### ISSUE TITLE
 Cleanup SendHXLUsecase and HXLInterface to have useful logs 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3113]
## Overview
Right now SendHXLUsecase and HXLInterface have a lot of debug-like logs from when we released it. Remove them and keep only useful & clean log entries. 

Based on the checklist of HDX tech debt from #2984 . 

## Requirements
- Log::debug entries without params or useful information should not be in SendHXLUsecase

## Acceptance criteria
- If something goes wrong and I read the logs, It should be easy to understand them and I should have context about what happened (no plain "error" debug logs)

**Comment by rowasc** [comment]
@willdoran this is a cleanup task from v0. I think it's 1 point. Can you review? I'm not sure I can add more detail, it's just cleaning up logs from the release

**Comment by willdoran** [comment]
We don't have a good idea of what logs should look like but your description is good in a general sense.

I'd estimate this as a 2, @rowasc do you agree?

**Comment by rowasc** [comment]
Alright. I thought maybe 1 but a 2 might just be OK if we think there'd be a lot of back and forth while doing it
Adding 2 as estimate and moving
