### ISSUE TITLE
Improve Formatting of CSV Exports ("CSV Exports v3")

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3119]
## Overview
[need to add more here]
One example of a "bug" that actually turned out to be a UX issue with CSV Export Formatting
https://github.com/ushahidi/account-management/issues/new/choose
There is also feedback from HDX experience to be added here.

## What privacy impacts does it have?
- Does it change the personal data we collect?
- Does it expose data that was previously private?
- Does it send data to new services? or change how we process it?
- If privacy impacts are high risk, consider completing an impact assessment per GDPR (https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/accountability-and-governance/data-protection-impact-assessments/)

### Who will this be deployed to?
e.g. will it be feature flagged? will it go to just once deployment?

## Deployment

*Does this deploy new services?*
*Do the new services have health checks?*
*Can this be feature flagged and deployed disabled?*

## Dependencies

Aha! Link: https://ushahiditeam.aha.io/features/PROD-322

**Comment by Hazellaura** [comment]
Hello team, just seeing this messages now, time difference and all @jrtricafort seems similar to the issues that I was speaking about in the call. Let me download a more filtered CSV from one survey and see if the multiple duplicate columns remain the same and then log what i find in.
