### ISSUE TITLE
Report submission failure after limiting submissions to specific role

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3129]
**Describe the bug**
For background, this is an issue that was reported by an intercom user on this conversation below.

ref https://app.intercom.io/a/apps/hl5rfiga/inbox/inbox/252111/conversations/17310391010 

User has a set of different roles defined on his deployment e.g admin, data clerk, member, etc.
User also has one survey on his deployment, and has limited submissions to the data clerk role *only* (via survey configuration tab)

User logs in as an admin onto his deployment, and attempts to submit a post, and it fails - the submit button just freezes on "submitting", and does not return any error message.
![submit](https://user-images.githubusercontent.com/721918/42282507-6a5fc6ba-7faf-11e8-81d9-64eab9780e26.png)
See below for browser console
![console](https://user-images.githubusercontent.com/721918/42282520-70ebf8aa-7faf-11e8-96f3-5ec359d5cb36.png)

**Where was the bug observed**
I tested this on the user's deployment as well as my own individual deployment on ushahidi.io

**To Reproduce**
1. Log into any ushahidi.io deployment as an admin
2. Create additional roles aside from your default "Admin" and "Member" role.
3. Create a new survey
4. Configure your survey to only receive submissions from your custom roles created in step 2 above
5. Attempt to add a post to your survey, while logged in as an admin
6. See error.

**Expected behavior**

_**The desired behavior is that we prevent the user from getting to a state where they are logged in as admin but can't submit reports to a survey that they themselves created (as admin).**_

1. Survey submissions should always be available to admins no matter what, and this should be represented in the UX for transparency to the user. To do this, when configuring your survey, and limiting submissions by role, the admin role should always be checked, and should be disabled for unchecking (grayed out)

This is an alternate solution, which we should not do: 
2. If we allow for admins not being able to submit survey responses, the "add to survey" button on ,ap and data mode should be disabled for them i.e they should not get as far as the survey submission page in the first place

**Is there a workaround? What is it.**
Right now, ask the user to select the admin role on the survey configuration page to allow him submit posts.

**Screenshots**
I've added them into my bug description.

**URL / Environment where this happened**
https://ushdocsangie.ushahidi.io
https://zimbabwecitizensmovement.ushahidi.io/

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**
Not applicanle

**Desktop Hardware Details (please complete the following information):**
 - OS: [e.g. iOS] : MacOS( for me)
 - Browser [e.g. chrome, safari] : Chrome (for me)
 - Version [e.g. 22] i dunno!

**Smartphone Hardware Details (please complete the following information):**

**Additional context**
Nothing to add.

**Comment by jrtricafort** [comment]
Thanks @aoduor . Yes let's proceed with letting the user know of the workaround, and that admin is really intended to have access to all permissions, since that's the definition of admin we provide here:

https://www.ushahidi.com/support/custom-roles#add-a-role
> The default “Admin” role allows for full control over ALL functionality on your deployment

Because of the intended use of Admin and the workaround, I don't think this is high priority right now, but I have added a tag to consider this for a future cycle, to improve the error state and properly provide an error message.

**Comment by aoduor** [comment]
ping @jrtricafort - customer has flagged this issue once again and asked for resolution as quickly as possible.

**Comment by jrtricafort** [comment]
Conencted with @aoduor and will check with engineering to get a complexity estimate of this solution path (which Angie posted in the description above):
>1. Survey submissions should always be available to admins no matter what, and this should be represented in the UX for transparency to the user. To do this, when configuring your survey, and limiting submissions by role, the admin role should always be checked, and should be disabled for unchecking (grayed out)

@rowasc @kinstelli @willdoran Would one of you be able to do a quick complexity estimate for this UX fix?

The desired behavior is that we prevent the user from getting to a state where they are logged in as admin but can't submit reports to a survey that they themselves created (as admin).

**Comment by jrtricafort** [comment]
Connected with @kinstelli and he agrees this implementation scope makes sense, initial estimate of 3 points.

@rowasc Let's discuss if we can fit this in Cycle 9.

**Comment by Angamanga** [comment]
@rowasc @aoduor I am unable to reproduce this locally, in which deployment did it happen?

**Comment by aoduor** [comment]
hey @Angamanga :). It happened on one of my ushahidi.io deployments, and a user's deployment.

https://ushdocsangie.ushahidi.io
https://zimbabwecitizensmovement.ushahidi.io/

Try creating two different roles, assign submission of posts to that survey to only one role, and the log in as an admin and try again.

**Comment by Angamanga** [comment]
@aoduor I still cannot reproduce this, have tried on https://ushdocsangie.ushahidi.io. Could you please try again too, I might be not reproducing it correctly?

However, I think the suggested UI-solution makes sense anyway, the admin should be checked and greyed out. @rowasc @jrtricafort

**Comment by rowasc** [comment]
@Angamanga agree with the solution. Maybe you can have a quick sync with Angie to reproduce it in the morning?

**Comment by Angamanga** [comment]
Testing checklist:
- Log in as an admin
- [ ] Create a new role and assign a new user with that role
- Go to settings-> surveys-> select a survey
- Click on configuration-tab
- Click on "Specific roles" in "Who can contribute to this survey
- [ ] The admin-option should be greyed out and selected
- Select on the newly created role and save the survey
-  As an admin, try submitting a post to the survey
- [ ] The post should save as normal
- Log out and login as the new member with the new role
- Submit a post to the survey
- [ ] The post should save as normal

**Comment by crcommons** [comment]
@rowasc Passed QA

**Comment by rowasc** [comment]
@Angamanga can you check in prod when you have a minute? (It's released)

**Comment by rowasc** [comment]
@Eve-wanderi can you retest this on rominacsvsms.ushahidi.io ?
Testing checklist:
- Log in as an admin
- [x] Create a new role and assign a new user with that role
- Go to settings-> surveys-> select a survey
- Click on configuration-tab
- Click on "Specific roles" in "Who can contribute to this survey
- [x] The admin-option should be greyed out and selected
- Select on the newly created role and save the survey
-  As an admin, try submitting a post to the survey
- [x] The post should save as normal
- Log out and login as the new member with the new role
- Submit a post to the survey
- [x] The post should save as normal
