### ISSUE TITLE
Wireframes and draft software specification for ISOOKO platform

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#3131]
## Overview
The EU requires a document that outlines “Wireframes and draft software specification for platform” to be delivered **by August 15th**. Report is described on[ page 52 of the proposal](https://drive.google.com/open?id=1AG6PN77WdJ6_R6NHdoKouyNZyzPeQs7s). These types of reports are considered first drafts and can be somewhat nebulous, but need to present some documentation about what we are envisioning for ISOOKO. [For COMRADES Robbie, Will, and I submitted the same deliverable based mostly on Ushahidi's API](https://drive.google.com/open?id=1m61qgMb12Fqs164dRCEsgV-8skUJ-2-3), since the work was essentially around connecting Ushahidi to external services.

At present, the idea is to work with the other technical partner in the project, DOTSOFT, to develop a simple database and accompanying dashboard that can ingest information from: an Ushahidi deployment, BRCK or MOJA network, and leave open the option of ingesting data from other sources via API. This concept is largely being pushed by DOTSOFT and other consortium partners whose role it is to monitor and evaluate the project. We can propose other options if we like, but for right now I’d really just like to submit a basic spec for this to the EU and make changes later if required. 

DOTSOFT is helping to write the deliverable and has requested a call with Ushahidi to help answer some basic questions around how these pieces might fit together. The immediate questions are when can we schedule this call and who should be on it. I’ll set up a template for the report in the next day or two. 

## Who is it for? Who are the users?
This report is largely a bureaucratic checkbox for the EU. However, our partner DOTSOFT will be using it as a basis for their work around a dashboard to ingest Ushahidi and BRCK/MOJA data. It should also provide enough basic information about Ushahidi that we can cut/paste it into future documents of this sort (which are always required with these grants). 

## What privacy impacts does it have?
- Does it change the personal data we collect?
- Does it expose data that was previously private?
- Does it send data to new services? or change how we process it?
- If privacy impacts are high risk, consider completing an impact assessment per GDPR (https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/accountability-and-governance/data-protection-impact-assessments/)

### Who will this be deployed to?
e.g. will it be feature flagged? will it go to just once deployment?

## Deployment

*Does this deploy new services?*
*Do the new services have health checks?*
*Can this be feature flagged and deployed disabled?*

**Comment by jrtricafort** [comment]
Recapping that @willdoran will support this meeting as a technical representative.

**Comment by Shadrock** [comment]
@willdoran @jrtricafort We now have a draft for the specification for this deliverable. [It's in this Google document on the ISOOKO team drive](https://docs.google.com/document/d/1-HryxbVVPIMOGqc2fCG6EFrrnWu0tOVyrK2Gmm_Bqs0/edit#). A majority of the architecture and API documentation was first compiled for COMRADES. This was done by @rjmackay, I believe. We need to review Section 3, "Ushahidi Platform Architecture and Design" to ensure the existing text is still accurate. I'm also going to need some help from @natmanning to get technical documentation from BRCK regarding - at a minimum - what the BRCK/MOJA data model is and how their API is structured.

**Comment by jrtricafort** [comment]
@willdoran @rowasc This will likely have to go in Cycle 8 depending on the due date @Shadrock provides. Can we do a high-level point estimate for this to see what may need to get bumped or added for the other things we've planned this cycle?

**Comment by jrtricafort** [comment]
added to CYcle 8 for now

**Comment by Erioldoesdesign** [comment]
Assigned self for the wireframe aspect of this work

**Comment by Shadrock** [comment]
@willdoran @kinstelli bump on this.

**Comment by jrtricafort** [comment]
@rowasc This currently has three asignees, is that correct?

**Comment by rowasc** [comment]
@willdoran is leading this and @kinstelli is also working on it, so they should be assigned. Not sure if Shadrock should be assigned.

**Comment by Shadrock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wireframes & Software Report](https://trello.com/c/4e0ZdWAQ/1-wireframes-software-report)

**Comment by Erioldoesdesign** [comment]
Starting looking into wireframes for the first round of feedback from Dotsoft/ the consortium here: https://wireframe.cc/pro/pp/4f893d1be184868

Its seems to me the main actions are:
- Setting up a way for Ushahidi platform/s to be pulled into the dashboard to be displayed (Via API?)
      - Displaying posts, categories, collections, saved searches, users & roles.
- Same way to pull in MOJA/BRCK data 
- Same way to pull in another kind of data via an API and display it

I see this dashboard initially as a way to view/hide this data, maybe make certain data sets take up more space on the screen (dragging the 'windows') and then having a link in the menu which is around setting up the 'other API' once the Ushahidi and MOJA/BRCK data pull-ins have been configured.

Clicking on a post/data type would make it full screen viewable.

I expect they might also want a way to change the deployment that's being pulled in. 

Are they expecting to be able to export or manipulate what is on the dashboard in anyway?

Anyways, it's a decent start to this

**Comment by Shadrock** [comment]
Trying to add a bit more info here for @Erioldoesdesign. Might also be helpful for @willdoran & @kinstelli who are adding some diagrams and text. The wireframes are ultimately _aspirational_, so whatever you put together should be relatively basic and will probably be based on our best guesses. Your initial frames posted above look like a good start to me and your assumptions about the main actions are correct. 

Another option might be to base this off the "multiple deployments" view we had going earlier this year. (Do we still have wireframes / mockups for that?). It's entirely possible that we'd want to simply add a "MOJA view" into v3. I think it would be good to provide a 'shallow view' of a few different possibilities (e.g. only 1-2 screens deep), rather than trying to work all the way through one option. But, again, only if that would be easier to do. If it's faster to just pick one idea and work through it... then carry on! 

**Specific answers to questions above:** 

> I expect they might also want a way to change the deployment that's being pulled in.

Yes, probably, although if this would take a lot more time to design, then I can just reference it with text. 
> Are they expecting to be able to export or manipulate what is on the dashboard in anyway?

Probably but, again, we don't really have a good thought about what this would mean so, for now, I wouldn't worry about it. I can always mention it in the text... _"Depending on the outcomes from the user design workshops in Rwanda and Kenya it's possible that we'll add..."_ etc.

**Comment by Erioldoesdesign** [comment]
Here's the flat image of multiple deployment work that I'm pretty sure Justin did:

<img width="436" alt="screen shot 2018-08-15 at 16 09 06" src="https://user-images.githubusercontent.com/11681324/44155619-b18aba7e-a0a5-11e8-8dca-d8a86092562b.png">

I'm pretty sure I can riff off this and include the 'Moja view' and also add an 'other data view'

What I would say is time consuming is doing page designs for how to set up API's and data sources etc. So I'll just screenshot the current ones in Platform but they'll need some write up next to it.

I'll get some updated design up today 👍

**Comment by Erioldoesdesign** [comment]
Sup! @Shadrock 

So I've updated the wireframes over at: https://wireframe.cc/pro/pp/4f893d1be184868

In the top left you can swap between different pages. They are still vague (because they need to be due to not really knowing how the dashboard would need to be used post workshops)

I also did these:

![isooko-wf-dash-1](https://user-images.githubusercontent.com/11681324/44173477-f3976c00-a0d7-11e8-9b0d-48ace3f70b18.png)

![isooko-wf-dash-2](https://user-images.githubusercontent.com/11681324/44173479-f72af300-a0d7-11e8-8841-6586377df5f3.png)

I riffed off Justin's old multi-deployment dashboard ideas. It's useful as it shows more of our current UI styling and brand but functionally, I don't know whether it achieves more or the same as the plainer wireframes.

Let's find time to jump on a call to talk through these if there's more you want to dictate. I want to make sure we're getting this right for Isooko while still not giving too many design hours to this due to it not being as high a priority as other Isooko tasks (<< an assumption on my part)

**Comment by Shadrock** [comment]
@Erioldoesdesign these look great! I would love for you to drop both the wireframes and these mock-ups into the doc along with some text to explain them. The text can be as long or as short as you like and doesn't need to be formatted or written in any specific way. I just need the basic idea behind the wireframe or mock up. I'll add context and polish the text. I'll tag you in the doc so you know which section to drop these into.

**Comment by Erioldoesdesign** [comment]
Phew! I'm glad they meet the brief. Adding to the doc you linked me on in an email this morning and please do edit any of my text to make better sense if it doesn't :)

**Comment by Shadrock** [comment]
Thanks for everyone's hard work on this: I'm happy to close this issue out!
