### ISSUE TITLE
Port platform/3080 to lumen  

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3132]
## Porting platform/3080 to lumen 
https://github.com/ushahidi/platform/pull/3130#partial-pull-merging
## Overview

Export should correctly take account of fields/surveys selected only when exporting data

## Requirements
- Only selected fields and surveys should appear in exported data

## Acceptance criteria
- Go to the Settings->Data Export view
- Select a survey and a subset of fields to export
- [x] Ensure that only the selected survey(s) and field(s) are present in the exported CSV

#Acceptance criteria 2
- [x] Go to the Settings->Data Export view
- [x] Select a subset of fields for 1 survey (only 1 survey)
- [x] Select "select all" for that survey
- [x]  Ensure that all the fields for that survey are present in the exported CSV

#Acceptance criteria 3
- [x] Go to the Settings->Data Export view
- [x] Select a all fields for 1 survey (only 1 survey)
- [x] Unselect 1 or 2 fields for that survey
- [x]  Ensure that all (and only) the fields selected for that survey are present in the exported CSV

**Describe the bug**
The export function form the settings tab in the deployment downloads a full data set despite selecting particular fields to export 

**To Reproduce**
1. Go to ‘dreamsic.ushahidi.io'
2. Click on ’settings tab, then to the export data tab and select fields to export. Select Siaya County Government - Council Health Management Team Database, click select all and click on the export selected fields
4. See error - it will download a full dataset for all surveys in this deployment. this will take about 25 minutes 

**Expected behavior**
The exported dataset is supposed to only include the Siaya County Government - Council Health Management Team Database.
This process is supposed to take no more than three minutes 

**Screenshots**
<img width="707" alt="screen shot 2018-06-14 at 11 02 30" src="https://user-images.githubusercontent.com/28722642/41399433-02e0d52a-6fc3-11e8-887a-90896ad5a706.png">

**URL / Environment where this happened**
https://dreamsic.ushahidi.io

**Additional context**
I tried to export the data using the select and filter option and this worked well. It exported the data I had sorted and filtered in two minutes

**Comment by rowasc** [comment]
@willdoran @crcommons since this is porting an existing feature, what do you think about the spec? is it enough? 
I'd estimate around 2 points since the feature itself was simple, but maybe a 3 would be appropiate if we consider that QAing it is really terrible and time consuming

**Comment by willdoran** [comment]
agree

**Comment by rowasc** [comment]
@Eve-wanderi please test in qa.ushahididev.com
Thanks

**Comment by Eve-wanderi** [comment]
@rowasc this passed QA.

**Comment by rowasc** [comment]
Closing as this issue will be released with lumen , added to the lumen release
