### ISSUE TITLE
Show all report details in 1 screen, avoid scrolling

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/platform#314]
The reports are hard to view. It would be more helpful to have all the report details in one screen rather than forcing the user to scroll. We need to make quick decisions about the content. 

Report - http://demo.platform.ushahidi.com/posts/11471
Firefox OS
<img width="1202" alt="screen shot 2015-08-13 at 3 54 19 pm" src="https://cloud.githubusercontent.com/assets/1216707/9250175/a22a3a66-41d3-11e5-8b51-10415ea6db79.png">

[2015-08-13, 3:49:01 PM] Heather Leson: seeing a report as one unit is hard because you have to scroll so much
[2015-08-13, 3:49:18 PM] Heather Leson: not really a bug but I would prefer to see all the items in one space to make decisons

**Comment by rjmackay** [comment]
Assigned to Brandon for input to future designs.

**Comment by rjmackay** [comment]
I think this is stale now. Closing
