### ISSUE TITLE
CSV export fails if multiple exports are requested in a short period of time 

### ISSUE THREAD

**Issue by Eve-wanderi** [ushahidi/platform#3143]
**Describe the bug**
If there are multiple users or the same user are trying to do many CSV exports, some of the exports fail. It's not clear yet if the exports are always just failing or if some are marked as success but blank (need details from Eve) 

**Where was the bug observed**
http://csvexportsforever.v3-qa.ush.zone/settings/data-export

**To Reproduce**

1.  Go to the Settings->Data Export view
2.   Select a subset of fields for 1 survey (only 1 survey)
3.   Select "select all" for that survey
4. Start the export. 
5. Repeat steps 1-4 with the same user, at least 3 times in a short period of time (~5 minutes) 

**Expected behavior**
If there are multiple requests for a CSV export they should all complete.

**Is there a workaround? What is it.**
No

**URL / Environment where this happened**
http://csvexportsforever.v3-qa.ush.zone/settings/data-export

**Desktop Hardware Details (please complete the following information):**
 - OS: [Windoes 10]
 - Browser [chrome]
 - Version [Version 66.0.3359.139 (Official Build) (64-bit

**Screenshots**

![image](https://user-images.githubusercontent.com/36038029/42384520-e09a42bc-8142-11e8-9c48-5d14535a31a5.png)
 

**Additional context**
- [ ] Not sure if this happens with multiple users or only if you use the same user multiple times

**Comment by rowasc** [comment]
@Eve-wanderi this needs to be separated into two issues. 
- If some CSVs are blank, then that's one issue which needs to have steps to reproduce it as consistently as possible. In addition to this, It'd help me if you could also note which specific users you utilized for testing this (send them in slack) so I can check the logs. 
- If the CSVs take too long, that is a completely separate issue (create a new one for this)

Thanks!
Romina

**Comment by rowasc** [comment]
BTW I just confirmed that if a single user requests 4 or 5 exports one after the other (I did it in a span of ~3 minutes or so), some of the exports fail .. not really sure why :(* 
 But I'm not able to get an empty CSV, still not sure how to make that one happen.

**Comment by rowasc** [comment]
I just added more clarification to this ticket and I'll create the extra time ticket since it's past Eve's EOD

**Comment by rowasc** [comment]
@jrtricafort tagging for follow up + prioritization

**Comment by rowasc** [comment]
@Eve-wanderi can you re-test? I think this is solved now
