### ISSUE TITLE
Copy subset of production deployments to a test environment

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#3153]
0. Log in to job box: `ssh ubuntu@ansible-jump-staging.aws.ushahidi.com
`
    0. Start a byobu session by running `byobu`
    0. Activate virtualenv `. ~/py3/bin/activate`
1. Disable job queue (specifically celery beat) on target environment
    `ansible-playbook -i hosts.aws -l env_harbinger aws.queue-worker-disable.yml`
2. Run export from production (use something like random order + 10% limit)
    `ansible-playbook -i hosts/rackspace_prod -l platform-cloud-interface-1-php7 cloud-deployment-snapshot.yml -e "deployments_exportlist_options='-l 10% -r'"  -vv`
3. Import snapshot with: overwrite env, import tiers enabled, private deployments enabled and scrubber enabled
    `ansible-playbook -i hosts.aws -l env_harbinger cloud-deployment-restore.yml -e "snapshot_name='rackspace_prod...'" -vv -e on_duplicate=overwrite -e scrub_deployment_data=True -e overwrite_env=True -e make_deployments_private=True`
4. Confirm data was scrubbed, including emails and data provider settings
5. Re-enable job queue.

NB: Run these steps on the jump box, not from a local machine

Run with:
- Random 10% of deployments (run this more than once?)
- Top 5% by priority (ie. largest deployments)

Metrics to record:
- How long does it take overall?
- How long to snapshot?
- How long to restore?
- How large were deployments on average?
- Most time consuming steps? ie. is in importing the DB? Or migration runs? (if possible)

**Comment by kinstelli** [comment]
Related: I pushed a commit to add `profile_tasks` to ansible.cfg in 302-snapshot-restore. There are a few profilers available for Ansible, but this seems the most straightforward.

**Comment by willdoran** [comment]
@rjmackay This list looks good to start off with as it covers the main bases.

**Comment by rjmackay** [comment]
Tests so far:

- Simple sequential export 5%, paid and large deployments first. 1:25
- Batched export. Batch size 20, 5%, paid and large deployments first. 1:04

We need to run more tests with random batches, and different batch sizes. I want to try and batch the restore process first though
