### ISSUE TITLE
Remove "elevation" as a tag option

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3157]
Because the Ushahidi data model doesn't have a good native concept of elevation, we should remove it as an HXL tag for now (for now = HDX v1).

### Acceptance criteria 
Open the HDX export screen 
- [ ] Select #geo as a tag in a location type field
- [ ] Check the available attributes. You should not see elevation as an option

## Details
- [ ] Remove elevation as an hxl attribute in the database

**Comment by rowasc** [comment]
@willdoran ah, as a solid 1 line ticket, I think this spec is complete :D can you review? it's 1 point

**Comment by willdoran** [comment]
yep approved :D

**Comment by rowasc** [comment]
Verified in qa
