### ISSUE TITLE
HDX v1 feature writeup (what’s done/isn’t done)

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3158]
1-pager describing what is/isn't included with HDX v1.

Include list of known bugs, what level of testing this has gone through (i.e. QA but not daily workflows yet)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-313

**Comment by rowasc** [comment]
@jrtricafort is this still needed?

**Comment by rowasc** [comment]
@jrtricafort is this still needed?

Do we need to add it to cycle 8 ?

**Comment by jrtricafort** [comment]
@rowasc Yes we should add this to Cycle 8.

**Comment by rowasc** [comment]
I don't know if this was ever done . Should document it so tagging it with docs
