### ISSUE TITLE
Sort Collections by reverse-chronological order by default

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3159]
### Requirements
When I view the list of collection, they should automatically be sorted in reverse chronological order (most recent at the top)

### Acceptance criteria
- select the collections icon (be sure there are multiple collections and you know when they were created)
- [ ] confirm collections are in reverse chronological order

### Bug report details
Enhancement requested from our Iran Protest deployment:

**Current Behavior**
Collections are sorted in chronological order (oldest at top).

**New Behavior**
Default auto-sort to reverse chronological order (most recent at top)

**Something we could do later, but are not doing as part of this issue**
Allow user to sort in chronological or reverse chronological order (button to flip back and forth).

**Original request/justification from user:**
>Here I would like to explain more about what problem we face using the collection list. 
Each new collection which is added to the list will go down the collection list. We create a collection for each day. For example " Friday, May 11, 2018" That is to help visitors to see what happened in Iran in that particular date. That is a very good feature. Now we have 133 collections which is a lot. It is difficult to explore new collections since a user should go down the list of collections when he/she wants to view a new collection (for example yesterday collection "Thursday, May 10, 2018" ). It was ideal in our case that we could set default sort order of collections to descending from newly created to the older ones. It was even better if visitors could toggle the sort order Desc/Asc.

**Comment by jrtricafort** [comment]
@Added to Cycle 7 and assigning to @willdoran as requested.

cc @rowasc

**Comment by jrtricafort** [comment]
cc @justinscherer - check out the original message from the user above. This is an interesting workaround use of Collections. It looks to me like there's actually a "hidden" feature request here for something like a timeline filter / date filter on the map. Totally sensible usecase. I've seen several other apps that do this well and we could capture it as a potential feature for the roadmap.

**Comment by crcommons** [comment]
@jrtricafort are we planning to add sorting functionality to put the collection in reverse or chronological order? Or are we just making the change to default the list to reverse chron. order?

**Comment by willdoran** [comment]
@crcommons It's just changing the sort not making it a choice

**Comment by jrtricafort** [comment]
@crcommons @willdoran I'd like to just change the default list to reverse chron sort.

I think having a sort-flipping option would be cool in the future. If it is actually easier to do so now, then we can do it now. But if it adds more than 1-3 points to this issue, then we should table that issue for a future cycle.

**Comment by jrtricafort** [comment]
@crcommons Exciting to hear that this is almost ready! Let me know when it's released to production and I'll update our IP partners, they'll be happy to see this!

**Comment by crcommons** [comment]
@jrtricafort, actually @willdoran is working on this one. Not sure of the status. But flagging for him so he can give you a heads up.

**Comment by Eve-wanderi** [comment]
Passed for me as well.
