### ISSUE TITLE
Activity missing content stream

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/platform#316]
I clicked on "activity" hoping to see all the various posts and edits etc or some kind of over all view". It was blank.

What is the purpose of activity? Maybe tooltips would help navigation? We are all from different languages. 
Firefox, OS
<img width="1204" alt="screen shot 2015-08-13 at 4 13 18 pm" src="https://cloud.githubusercontent.com/assets/1216707/9250528/71c5d3f0-41d6-11e5-8fc6-aff8fc6ac1b2.png">

**Comment by rjmackay** [comment]
#382 will hide activity for now. This will be implemented later
