### ISSUE TITLE
Renew enterprise deployments certificates automatically

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3171]
**Which user group(s) are the primary audience for this feature/enhancement.**
Developers working at Ushahidi (staff).

**Is your feature request related to a problem? Please describe.**
There is a script (nginx) that we can run to renew a certificate when it expires, but there is no auto-renewal for some certificates.  

**Describe the solution you'd like**
Renew certificates automatically

**Describe alternatives you've considered**
Renew certificates automatically?

**Additional context**
https://ushahidi.slack.com/archives/CABNM2QQ7/p1532112267000091

**Comment by rowasc** [comment]
@jrtricafort to prioritize. I think this should be treated as a P0/P1 since it affects the stability of the platform

**Comment by jrtricafort** [comment]
@rowasc Agree that it's high prioritization. What's the points estimate? Are you proposing to add to this cycle or take up in Cycle 8?

**Comment by rowasc** [comment]
Cycle 8 should be OK @jrtricafort

**Comment by rowasc** [comment]
@tuxpiper and @willdoran might have an idea so we can plan according to a rough estimate (it's likely that the estimate will change once we spec, but at least to know during planning)

**Comment by tuxpiper** [comment]
Unfortunately the current setup doesn't lend itself to renew the certificates easily. I expected more from the official ansible letsencrypt module. The whole thing depends on running the ansible playbooks every time, which means a lot of dependencies.

It would probably much easier to switch to an ansible role installing and managing certbot and a cron job for renewal : https://github.com/geerlingguy/ansible-role-certbot

**Comment by rowasc** [comment]
@tuxpiper that looks promising. We will need to spec this next cycle and figure out if ansible-role-certbot would solve our problems.

**Comment by rowasc** [comment]
@tuxpiper @rjmackay I think I should move this to cycle 9 to handle after lumen is done, right?

**Comment by rowasc** [comment]
@tuxpiper @rjmackay bumping. Can this be done in cycle 9?

**Comment by tuxpiper** [comment]
I would suggest here to solve the issue using AWS, so we don't depend on Letsencrypt for the certificates.

1. We could create a single AWS application load balancer for all our enterprise deployments. The application load balancer integrates with AWS Certificate Manager (free, auto-renewed certificates) and its configuration is modular.

2. For each enterprise deployment, we ..
    1. Request a certificate in ACM (manually created)
    2. add the following configuration modules to the load balancer (via terraform):
         a. A listener certificate ( https://www.terraform.io/docs/providers/aws/r/lb_listener_certificate.html ) matching the deployment's hostname
         b. A target group ( https://www.terraform.io/docs/providers/aws/r/lb_target_group.html ) attached to the deployment's instance/s ( https://www.terraform.io/docs/providers/aws/r/lb_target_group_attachment.html )
         c. A listener rule matching the deployment's hostname ( https://www.terraform.io/docs/providers/aws/r/lb_listener_rule.html )

**Comment by rowasc** [comment]
@tuxpiper sounds pretty good. Maybe after the enterprise deployments are in AWS would be the ideal time to do this?

**Comment by tuxpiper** [comment]
I'll actually will get this done along with ushahidi/platform-enterprise-playbooks#13 and ushahidi/platform-enterprise-playbooks#16 . The automatic renovation of certificates will be part of the whole terraform setup of the enterprise deployments product.

**Comment by rowasc** [comment]
AHH ok. Sounds great. @tuxpiper thanks

**Comment by tuxpiper** [comment]
Enterprise deployments on AWS have this now. For those deployments not on AWS, the answer would be to expedite their migration :)
