### ISSUE TITLE
Columns in the HXL row of a CSV for HDX (humdata.org) are being picked up by the map view

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3172]
**Describe the bug**
The preview map feature of HDX is taking the HXL tags as valid data for a map .

**Where was the bug observed**
data.humdata.org and demo-data.humdata.org
https://comrades-stg.ushahidi.com
https://comrades-hdx.ushahidi.com

**To Reproduce**
1. Create an HDX Upload that has location data. The location input should have #geo +lat and #geo +lon assiged. 
2. When the HDX upload is done, check the preview tag in HDX and assign location fields (lat/lon) to render the points in the map
3. The HXL tags row will be considered a valid data point by the map

**Expected behavior**
HXL Tags should not be considered data that a map can render.

**Is there a workaround? What is it.**
No.

**Screenshots**
<img width="697" alt="screen shot 2018-07-23 at 3 31 05 pm" src="https://user-images.githubusercontent.com/2434401/43100372-855cc094-8e9b-11e8-8c87-9acdc352abd2.png">

**URL / Environment where this happened**
https://comrades-stg.ushahidi.com
https://comrades-hdx.ushahidi.com

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**
Configure HDX to use demo-data.humdata.org or data.humdata.org 

**Desktop Hardware Details (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome (latest)
 - Version: 67

**Additional context**
While the HDX preview feature works after we generate a dataset from comrades-stg, the HXL row in the dataset is being considered as part of the data, so when the map preview renders, one of the map points is using #geo+lon and #geo+lat (the tags themselves) to render the point instead of the values below the tags.

It's harder to spot in large datasets, [this is an example dataset](https://data.humdata.org/dataset/ushahidi-lat-lon-and-meta/resource/dd0a02b7-e8a9-433a-9b5c-dfd23ba79cc6) that I created, it has only 2 rows with lat/lon so it's easy to see the error.  I added a screenshot of me clicking the point that fails. When I click that point in the map, it shows hxl tags instead of a lat/lon value for location.lat and location.lon. The dataset was generated from comrades-stg.ushahidi.com.
<img width="697" alt="screen shot 2018-07-23 at 3 31 05 pm" src="https://user-images.githubusercontent.com/2434401/43100372-855cc094-8e9b-11e8-8c87-9acdc352abd2.png">

**Comment by mcarans** [comment]
The preview feature on HDX uses the standard CKAN preview right now which is not HXL aware eg. see https://data.humdata.org/dataset/fts-requirements-and-funding-data-for-afghanistan/resource/45dc4269-405a-433d-9011-d1ae23d624a5

**Comment by rowasc** [comment]
Thanks, @mcarans . 
@jrtricafort sending this to the icebox pipeline for the moment

**Comment by rowasc** [comment]
Closing , wont-fix
