### ISSUE TITLE
Obfuscation Feature - External Announcement and BD Collateral

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3176]
For the anonymization feature, we will need external content on this new feature so that it can be included in the proposal template, corp caps doc, and in a blog post.

**Comment by rowasc** [comment]
Do you know who will implement this in cycle 8? Is it something you or Katy have to do?

**Comment by jrtricafort** [comment]
@rowasc This is on me to provide material to Katy. My goal is to have this done by end of this cycle8.

**Comment by jrtricafort** [comment]
@rowasc Moving this to cycle 9, see above comment.

@rowasc @willdoran Is there a test environment where this is available to use, while we wait for it to go up on prod? That would be useful for Angie as she does the writeup.

@aoduor Following up on our conversation, assigning this to you for with target date end of next week (August 24). This is not on prod yet we can get a test environment for you to learn it. Here is the parent epic which has more detailed background on specifications for this feature.
https://github.com/ushahidi/platform/issues/2684

**Comment by aoduor** [comment]
@jrtricafort might be worth reviewing the documentation @StaicyG and I have reworked to see if that content will be useful, and what else we would need to add? See slack for doc link

**Comment by rowasc** [comment]
Thanks @aoduor @StaicyG ! 
@jrtricafort assigning to you "In review"  per @aoduor comment.

**Comment by jrtricafort** [comment]
Thanks @aoduor @StaicyG reviewing today.

**Comment by jrtricafort** [comment]
@aoduor Reviewed and made some minor changes to the first two sentences. This is good to go!

cc @rowasc

**Comment by rowasc** [comment]
Excellent. @aoduor is this something you could add as a draft and then publish on the day of the release?

**Comment by aoduor** [comment]
@rowasc sorry, catching back up on this. To be clear, all we're doing is making edits as per Juan's suggestion to the first sentences and then publish as is, yes?

**Comment by rowasc** [comment]
actually, @Eve-wanderi could you do a quick test run for this feature based on the documentation Angie posted? You can use rominacsvsms.ushahidi.io to try it out. 
yes @aoduor after Eve gives the 👍 let's publish it.

**Comment by rowasc** [comment]
@Eve-wanderi can you let us know the results? Thanks

**Comment by Eve-wanderi** [comment]
@rowasc Tested this and dint encounter any Issues. Passed QA,

**Comment by rowasc** [comment]
@aoduor @jrtricafort this can go live then. See Eve's message above.

**Comment by rowasc** [comment]
@jrtricafort @aoduor assigning to you so you can close it once it's done (wasn't sure who was doing it , sorry for double assignment)

**Comment by jrtricafort** [comment]
@rowasc I believe this is done and we don't have plans for additional comms. Closing now.
