### ISSUE TITLE
Update lumen to (latest?) version in platform-cloud-interface and review develop-dashboard

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3177]
- Update lumen in platform-cloud-interface
- Review and decide if changes from `develop-dashboard` can be brought back into `develop`, and which ones.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-310

**Comment by rowasc** [comment]
@rjmackay @jrtricafort not spec'd , but adding this so we don't forget about it and prioritize it into a cycle soon. I think it should probably happen after we finish the lumen epic for platform so I am setting it up to be considered for cycle 9

**Comment by rowasc** [comment]
@rjmackay we don't need this for lumen, right?

**Comment by rowasc** [comment]
ah right. thanks @rjmackay 

@jrtricafort this isn't a blocker to get lumen out... but it's still really important so we don't have to constantly switch between Lumen 5.5 vs 5.1 features. 

 I think we should wait until lumen is out and do it then (ideally still this cycle).

**Comment by rowasc** [comment]
@rjmackay now that lumen is out, can you start on this or should I move it to cycle 10?

**Comment by rjmackay** [comment]
@rowasc Move it to cycle 10, although we might decide not to do it now if we're going into maintenance mode. I don't think I'm going to be very productive this week till I kick this cold

**Comment by rowasc** [comment]
ok makes sense. Thank you.
