### ISSUE TITLE
Implement video upload in Platform

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3179]
**Describe the feature**
- [ ] We need to implement video upload handling in platform API. 
- [ ] we need to change the mobile app to handle that.
- [ ] we need to change the client to handle it. 

**Additional context**
- See this https://github.com/ushahidi/platform/issues/1624

### this needs a spec

Aha! Link: https://ushahiditeam.aha.io/features/PROD-309

**Comment by RachealN** [comment]
@tuxpiper, I would like to work on this issue, please assign it to me

**Comment by tuxpiper** [comment]
sure thing @RachealN 👍

Please update the issue from time to time with your progress

**Comment by RachealN** [comment]
I have been looking into this issue, the specs are not quite clear
I checked this #1624, there is a long debate on how this should be approached and done and at the same time, closed the whole thing. I really don't understand at the point on how I should approach it.
Could you please provide more detailed specs on how this should be approached?

**Comment by RachealN** [comment]
@tuxpiper @webong @Angamanga and @rowasc 
Decided to work on this issue and this is how I intend to approach it
- [ ] Add migrations for video uploads
- [ ] Add Models and this includes rules and validations
- [ ] Add Factories 
- [ ] Add seeders
- [ ] Video upload controller, Integrating Video uploads with Vimeo to platform API with the following functionalities below
- create/ upload videos
- preview the uploaded video
- update video
- delete video

- [ ] Write the Unit tests for all added functionalities(create, update and delete )

**Comment by stacytonui** [comment]
is this issue still open? I'd like to work on it

**Comment by rowasc** [comment]
Hey, no this isn't yet available to be picked up. Please check https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22+milestone%3A%22Hacktoberfest+%22 for unclaimed issues
