### ISSUE TITLE
Add translations for Maintenance Mode

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3186]
### Overview
Maintenance mode error messages return from the API need to be translated according to browser language or deployment language

Current strings:
- {deploymentName}/Deployment not found
- {deploymentName}/Deployment is not ready
- {deploymentName}/Deployment is down for maintenance

Aha! Link: https://ushahiditeam.aha.io/features/PROD-306

**Comment by willdoran** [comment]
Anna did some work on this but it's might actually need to be ported from Kohana to Lumen. Basically
- we should translate API messages in the client
- we can translate them in the API instead
- We need to sync the API language files with transifex
- We need to re-implement some handling around translating data source options in lumen

**Comment by willdoran** [comment]
These might need to be ported to lumen
https://github.com/ushahidi/platform/pull/2860
https://github.com/ushahidi/platform/pull/3061

**Comment by willdoran** [comment]
@rjmackay is availalble as a reference to talk through good and bad of existing approach and concerns when porting for whoever is scoping this.
