### ISSUE TITLE
Enterprise page on dotcom is down

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3187]
**Describe the bug**
When I click on the Enterprise page on dotcom, I get a 404 error.

**Where was the bug observed**
https://www.ushahidi.com/enterprise

Reported by @katymoney27 

![image](https://user-images.githubusercontent.com/37776843/43490653-826ab094-94ef-11e8-804f-b72938d2c753.png)

**Comment by jrtricafort** [comment]
Could this be related to this issue? 
https://github.com/ushahidi/platform-cloud-interface/issues/313

In that issue, we had the URL changed from "/enterprise" to "/enterprise-partnerships"

When I go to /enterprise I get the 404
![image](https://user-images.githubusercontent.com/37776843/43490647-80422f36-94ef-11e8-8d60-45b0c017d1e0.png)


When I go to /enterprise-partnerships I get this internal server error:
![image](https://user-images.githubusercontent.com/37776843/43490631-7817d234-94ef-11e8-8094-31e589e9fb4e.png)

**Comment by sethburtonhall** [comment]
@katymoney27 and @jrtricafort OK, so I accidentally pushed a bunch of "Enterprise Revamp" code that was meant to stay in the staging environment until testing was complete. Instead of struggling to reverse this, which would have taken longer, I decided to integrate the revamp changes. Please review content on https://www.ushahidi.com/enterprise-partnerships and let me know of any changes.

**Comment by jrtricafort** [comment]
@sethburtonhall I'll let @katymoney27 confirm whether or not it is okay for these new changes to be on production already. If it's not ready to be public for some reason, then we will need to roll this back and revert it.

Also @sethburtonhall we need to make the old /enterprise link redirect to /enterprise-partnerships. This was specified in the description criteria for this issue: https://github.com/ushahidi/platform-cloud-interface/issues/313

The use case here is that there may be emails or other communications that reference the old link-- we don't want those links to be broken.

**Comment by sethburtonhall** [comment]
The "Enterprise" page is up and the revamp is on standby waiting to go into production. Sorry for the mix-up.

**Comment by rjmackay** [comment]
I believe the original page is now back up

**Comment by rowasc** [comment]
@jrtricafort closing as the page is up again. Thanks @sethburtonhall  !

**Comment by jrtricafort** [comment]
Thanks @sethburtonhall !

**Comment by rowasc** [comment]
@sethburtonhall did something change? https://www.ushahidi.com/enterprise-partnerships seems to be down again with a 404

**Comment by sethburtonhall** [comment]
ushahidi.com/enterprise-partnerships will be the new link once we go live with the revamp. I rolled back my error and we are now back to ushahidi.com/enterprise

**Comment by rowasc** [comment]
Thanks Seth. Sorry I bugged you on your day off, I didn't remember until 30 minutes ago :/
