### ISSUE TITLE
Comrades-Stg reset password email is not being sent

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3188]
**Describe the bug**
The password reset email is not being sent from the comrades-stg site. 

**Where was the bug observed**
https://comrades-stg.ushahidi.com

**To Reproduce**
1. Go to https://comrades-stg.ushahidi.com/
2. Request a password reset token for your user
3. You will not receive a password reset email

**Expected behavior**
3. You will receive a password reset email

**Is there a workaround? What is it.**
Asking someone with admin access to change the password

**Desktop Hardware Details (please complete the following information):**
 - OS: Any

**Additional context**
This is likely an issue in the setup of the server. It does not happen in production

**Comment by jrtricafort** [comment]
@rowasc Is the password reset not being sent for any production deployments? Or just comrades-stg?

**Comment by rowasc** [comment]
just comrades-stg @jtricafort

**Comment by rowasc** [comment]
argh this is happening again 
@tuxpiper do you remember the fix for this? I remember it was something when deploying the app, think it was an env var that didn't get set up when running the ansible scripts  but not sure.

**Comment by tuxpiper** [comment]
I didn't remember it , but you pretty much did 👍 : There wasn't a setting for the originating email address of those automated emails. I have just set a variable and a default

**Comment by rowasc** [comment]
Thanks @tuxpiper !
