### ISSUE TITLE
Research section of about page is broken 

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#3191]
<img width="977" alt="screenshot 2018-08-07 16 01 47" src="https://user-images.githubusercontent.com/1618793/43806999-4fb5ec10-9a5b-11e8-949d-ca72002f19e2.png">

**Comment by rowasc** [comment]
@jrtricafort tagging so you can check this when you are back tomorrow

**Comment by sethburtonhall** [comment]
@caharding This is not down for me. Can you refresh and check again?

**Comment by rowasc** [comment]
@caharding this is working now , closing
