### ISSUE TITLE
New Users do not get an email once they are added to a deployment.

### ISSUE THREAD

**Issue by Eve-wanderi** [ushahidi/platform#3195]
**Describe the bug**
New users do not get an email once added to a deployment.

**Where was the bug observed**
https://lumen.passage.ush.zone/settings/users

**To Reproduce**
1. Go to 'https://lumen.passage.ush.zone/settings/users'
2.Click on settings.
3.Click on users and add a new user

**Expected behavior**
New users should get an email notifying them that they have been added to X deployment.

**Is there a workaround? What is it.**
NO

**Screenshots**

**URL / Environment where this happened**
https://lumen.passage.ush.zone/settings/users

**Additional context**

**Comment by rowasc** [comment]
@jrtricafort to prioritize and tag. I don't believe this is a regression, it's not something we have ever done in production as far as I know, but it's kind of annoying and wrong that we don't let people know 

cc @Eve-wanderi if this is something that is documented anywhere as a feature, or if this is something that is currently working in production, please let us know and we will assign it to cycle 8  as part of the effort to bring lumen to production

**Comment by tuxpiper** [comment]
Closing a duplicate of #1421 , which has a fuller convo . Priority passed over to that ticket.
