### ISSUE TITLE
[Platform Client] Add Account Freeze State & Deployment End State

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#3199]
### Requirements
- Ensure that correct demo bar messages are displayed to users based on the criteria defined in [#329](https://github.com/ushahidi/platform-cloud-interface/issues/329)
- Add logic to check for current number of Posts
- Add logic to check for current expiration status
- Restrict operations based on current status of demo deployement
  - If expired, user should only be able to access the plans page to upgrade
  - Visitors should not be able to access any content
- For Demo deployments publishing is always required for posts to become public. A user in the demo period cannot turn off this option.

### Acceptance Criteria
- As a user of a Demo deployment that has not expired and has < 25 Posts
  - I can perform all operations as normal
- As a user of a Demo deployment that has not expired and has > 25 Posts
  - I can perform all operations as normal BUT only on the earliest 25 Posts
- As a user with Survey edit permission I can not access or set that publishing is always required for Posts to become public
  - This is enabled always
- As a user of a Demo deployment that has expired
  - I can only visit the plans page and upgrade
- As a visitor to a Demo deployment that has not expired
  - I can perform all operations as normal
- As a visitor to a Demo deployment that has not expired and has > 25 posts
  - I can only see a [view](https://xd.adobe.com/view/babf344f-ced8-4ca7-46c8-531b05b75f22-cc8e/screen/7feff3e2-340c-4ea3-ab40-7e29af47efb9/tourist-view/) showing me that the deployment has expired 
- As a visitor to a Demo deployment that has expired
  - I can see only this [view](https://xd.adobe.com/view/babf344f-ced8-4ca7-46c8-531b05b75f22-cc8e/screen/7feff3e2-340c-4ea3-ab40-7e29af47efb9/tourist-view/) BUT the message should explain that the deployment has expired rather than that it has more than 25 posts

**Comment by rowasc** [comment]
@willdoran  [export view for visitors](https://xd.adobe.com/view/babf344f-ced8-4ca7-46c8-531b05b75f22-cc8e/screen/7feff3e2-340c-4ea3-ab40-7e29af47efb9/tourist-view/) I'm not sure this link is correct since it shows the map and the demo bar, but I cannot find the view you mention that tells the user the deployment expired.

**Comment by willdoran** [comment]
@rowasc updated

**Comment by rowasc** [comment]
cool . moved to ready for dev

**Comment by Angamanga** [comment]
@willdoran The PL-tag for the demo-bar is: v3.11.0-rc.6  and the html can be found here:
http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/2_fragments/#pl-pattern-messages
