### ISSUE TITLE
UX: Visibility of Edit button on report for ordinary user

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#320]
So far, a user has to click on "Options" to find the edit button on the posts lists page.

This needs to move somewhere more visible.

**Comment by jshorland** [comment]
Still true. Assigning to @brandonrosage for future consideration.

**Comment by brandonrosage** [comment]
How about immediate consideration, @jshorland? 

I've revised the PL's handling of "postcard" actions. Note that the first two postcards in the [Timeline](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/timeline.html) layout, for example, are editable to the user. So they see that action without requiring interaction (on larger screens). But the third postcard is not editable to the user. So they just get a group of dropdown actions.

The logic for these structural differences is highlighted in HTML comments within the layout.

cc/ @rjmackay

**Comment by jshorland** [comment]
Passes QA. 

Edit button appears on post.
When clicked, takes me to edit mode.
I am able to edit all fields and change post status, and save.
