### ISSUE TITLE
[Platform Cloud Ansible] Add Account Freeze State & Deployment End State

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#3200]
### Requirements
- [ ] Provide ability to remove expired deployments that have expired > 6 months ago
- [ ] Provide job that is scheduled to run frequently that removes expired deployments

### Acceptance Criteria
- Can remove deployments that have expired

**Comment by rowasc** [comment]
I think this is correct. 
Moving to ready for dev

**Comment by willdoran** [comment]
@jrtricafort How long do you think we should wait before expunging old demo deployments? I have 6 months written down but may be something more like 1 month or 3?

**Comment by jrtricafort** [comment]
@willdoran I think I answered this in slack but let's do 6 months.

**Comment by rowasc** [comment]
Closing, pricing has been released
