### ISSUE TITLE
[Passage Env] Unable to export data. (Admin and Other Roles with export rights)

### ISSUE THREAD

**Issue by Eve-wanderi** [ushahidi/platform#3202]
**Describe the bug**
Unable to export CSV files all files showing status as pending.

**Where was the bug observed**
https://lumen.passage.ush.zone/settings/data-export

**To Reproduce**
1. Go to 'https://lumen.passage.ush.zone/settings/data-export'
2. Log in as 'Admin.'  
3. Click on 'settings'
4. Scroll down to 'export' and select all fields.

**Expected behavior**
Export files should export

**Is there a workaround? What is it.**
No.

**Screenshots**
![export](https://user-images.githubusercontent.com/36038029/43951233-488a4fc0-9c9b-11e8-84d0-57202633bc77.png)

![export](https://user-images.githubusercontent.com/36038029/43951853-e9823e32-9c9c-11e8-9b89-51c280697383.png)

**URL / Environment where this happened**
[e.g http://qa.ushahidi.io/post/create]

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**

**Desktop Hardware Details (please complete the following information):**

**Smartphone Hardware Details (please complete the following information):**

**Additional context**

**Comment by rowasc** [comment]
@kinstelli  can you check this ? Otherwise I can pick it up on wednesday

**Comment by kinstelli** [comment]
So far, all I've learned is that we're getting a lot of `Illuminate\Database\QueryException: PDOStatement::execute(): MySQL server has gone away` errors from the exporter log. This log only goes back to this morning, so I'm not sure if there could have been other issues prior to this.

@tuxpiper - I'm trying to connect to the DB from various passage machines using the config creds in exporter, but I'm getting a permission denied error for this user.

**Comment by tuxpiper** [comment]
@kinstelli what were you trying exactly? I was able to connect with 

`mysql  -h platcloud-passage.cdcy2axpb6yz.eu-west-1.rds.amazonaws.com -u cloud -p platform_export` and the password found in export_platcloud_harbinger_0:/var/www/export/config/database.php
