### ISSUE TITLE
[Passage env] Unable to Import data. (Role with import rights)

### ISSUE THREAD

**Issue by Eve-wanderi** [ushahidi/platform#3203]
**Describe the bug**
Users who have the Import Rights functionality cannot import files.

**Where was the bug observed**
- https://lumen.passage.ush.zone/settings/data-import
- Ushahidi.io deployments 

**To Reproduce**
1. Go to 'https://lumen.passage.ush.zone/settings/data-import'
2. Log in as 'Role: import export' 
3. Click on 'import'
4. Import file

**Expected behavior**
If user has right to import and export they should be able to import even if they are not Admin.

**Is there a workaround? What is it.**
Give user Admin rights

**Screenshots**
![import as member roles](https://user-images.githubusercontent.com/36038029/43954933-f1a6b8c2-9ca6-11e8-8cc6-cf2bafa23576.png)

**URL / Environment where this happened**
https://lumen.passage.ush.zone/settings/data-import
https://rominacsvsms.ushahidi.io/

**Desktop Hardware Details (please complete the following information):**

**Smartphone Hardware Details (please complete the following information):**

**Additional context**

**Comment by rowasc** [comment]
This issue is reported https://github.com/ushahidi/platform/issues/3194 as a pre-existing issue in the ushahidi.io deployments and should not be considered a lumen bug.
