### ISSUE TITLE
Can't perform bulk actions on admin interface

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#321]
Admin has to open individual reports to publish.

Not sure if "Mark as" is supposed to be used for this? ATM clicking on it doesn't do anything.

**Comment by rjmackay** [comment]
Suggested solution: add a 'publish to..' button to bulk actions.
This should match the publish button when editing individual posts.

**Comment by jshorland** [comment]
In listing toolbar view
- [ ] delete
- [ ] change status
- [ ] assign
- [ ] or “Add to Collection” for all selected items

**Comment by jshorland** [comment]
Actually closing this and opening new issue to reduce any potential confusion. Closing this in favor of #1390
