### ISSUE TITLE
Making Pricing Changes Live

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#3213]
### Steps
- [x] Ensure Lumen has been released to Prod and is stable
- [x] Run `plans:chargebee` to push new plans into chargebee
- [x] Push changes to sign up pages so that users sign up to new plans
- [ ] Run `deployment:tiers` command to change deployments onto new plan
- [ ] Remove old tiers in DB and plans in chargebee

**Comment by rowasc** [comment]
Pending

- [ ]  Run deployment:tiers command to change deployments onto new plan
- [ ]  Remove old tiers in DB and plans in chargebee
