### ISSUE TITLE
Deleting a parent category makes its children become parents instead of deleting them

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3221]
**Describe the bug**
When I click on "delete" for a category with children, I expect the child categories to be deleted. Instead, the child categories appear to become parents. 

**Where was the bug observed**
https://rominacsvsms.ushahidi.io/
https://isooko-stg.ushahidi.com

**To Reproduce**
1. Go to Settings->Categories (I tried this logged in as admin)
2. Create a parent category
3. Add a child to the parent category you created
4. Go to the categories list
4. Delete the parent category
5. The child category will become a parent. 

**Expected behavior**
5. The child category will be deleted

**Is there a workaround? What is it.**
Select all the children of the parent category and delete them

**Desktop Hardware Details (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 68.0.3440.106

Aha! Link: https://ushahiditeam.aha.io/features/PROD-303

**Comment by rowasc** [comment]
@jrtricafort found this today. Assigning to you for prioritization

**Comment by e-stephane** [comment]
Hello @rowasc @Angamanga, i will like to start working on this issue.

**Comment by rowasc** [comment]
@e-stephane awesome, thank you ! Looking forward to your contributions!

**Comment by helen-ndip** [comment]
@rowasc @Angamanga  is this issue still available to work on? I would like to take on it.

**Comment by renujain31** [comment]
Hey can I work on this? @rowasc @Angamanga

**Comment by rowasc** [comment]
@helen-ndip you can, altough it's likely this involves backend development (and debugging) as well, is that okay? 
If yes, go ahead and I'll assign it.

**Comment by helen-ndip** [comment]
> @helen-ndip you can, altough it's likely this involves backend development (and debugging) as well, is that okay?
> If yes, go ahead and I'll assign it.

Thanks I will.

**Comment by Angamanga** [comment]
Removing community-task label since the behaviour is clearly specified and decided on yet
