### ISSUE TITLE
Imports in Ushahidi is too slow, can be sped up 40-50x by avoiding validations and even more with schema changes

### ISSUE THREAD

**Issue by r-tock** [ushahidi/platform#3229]
Filed via email. Logging for posterity

Hi Will,

The patch was basically 2 lines being commented out. But it made the job run 40x faster, the reason is simple, in MySQL when you are reading after a write you are doing pointer walks on pages in the innodb transaction log, but this means that large imports slows down. Problem here was you were doing it in a tight loop for every post entity.

My recommendation is if you really needed the verification, do that in batch outside the loop with a single sql query. Then do batch inserts with no checks in the loop.

But given CLI import for us meant we didn't care about checking roles and permissions, we could ignore and that solved our usecase, we saw our MySQL instance hitting 1700 IOPS during the import process instead or 50-100 IOPS previously.

The second problem I saw with ushahidi is write amplification. Since every attribute is a row. For 1 post the system is inserting 50 rows. This is a longer term suggestion -- If you need another 50x improvement, you will have to remodel the data and keep all the fields denormalized. MariaDB and even Postgres has JSON columns, which you can use to store the attributes directly on the posts table, so you end up doing 1 insert.

Is there a way you can send me get the first solution patched and pushed quickly to our hosted instance, we are asking volunteers to use it instead of our patched version because we want to hand the site over to the Kerala government.

Robin

```diff --git a/src/Core/Usecase/ImportUsecase.php b/src/Core/Usecase/ImportUsecase.php
index 33e36c1..393d022 100644
--- a/src/Core/Usecase/ImportUsecase.php
+++ b/src/Core/Usecase/ImportUsecase.php
@@ -116,10 +116,10 @@ class ImportUsecase implements Usecase
                                $entity->setState(['status' => 'draft']);
                        }
                        // ... verify that the entity can be created by the current user
-                       $this->verifyCreateAuth($entity);
+                       // $this->verifyCreateAuth($entity);

                        // ... verify that the entity is in a valid state
-                       $this->verifyValid($entity);
+                       // $this->verifyValid($entity);

                        // ... persist the new entity
                        $id = $this->repo->create($entity);```

**Comment by willdoran** [comment]
Thanks hopefully this is resolved by the beta patch

**Comment by r-tock** [comment]
Will should I open another one for write amplification issue. it is not a short-term fix, but a more longer term design evolution of ushahidi?
