### ISSUE TITLE
After publishing a post only to Members it doesn't appear to a member user

### ISSUE THREAD

**Issue by francbartoli** [ushahidi/platform#323]
After an admin role publishes a post with an authorization strategy *Publish to Member* the post doesn't appear from the list when a member user has logged in.

**Comment by jasonmule** [comment]
Could not reproduce

**Comment by francbartoli** [comment]
Try this to reproduce:

* Login with *member A*, create a post and *Publish as Draft* then logout
* Login with an admin and *Publish to Member* then logout
* Login with  *member B* and search for that post along the list of those visible

**Comment by jasonmule** [comment]
Thanks @francbartoli. Has this happened for you again?

**Comment by francbartoli** [comment]
@jasonmule didn't try again after the testing day. Has this code changed?

**Comment by rjmackay** [comment]
@francbartoli I can't reproduce this. I published this post http://dev.platform.ushahidi.com/posts/1295 to members and I can see it when logged in as a member. Could you retest on http://dev.platform.ushahidi.com ? it runs the latest master codebase

**Comment by francbartoli** [comment]
@rjmackay tried again and I'm not facing that anymore
