### ISSUE TITLE
In Beta Android App, location is not getting auto populated

### ISSUE THREAD

**Issue by robin-anil** [ushahidi/platform#3231]
Found while testing the fix for https://github.com/ushahidi/platform/issues/3230

<img width="606" alt="screen shot 2018-08-23 at 4 58 35 pm" src="https://user-images.githubusercontent.com/11711723/44554793-f0b00300-a6f7-11e8-9f36-450cf53f0755.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-302

**Comment by dalezak** [comment]
If the user _has not allowed_ Location for the app, then this is appropriate behaviour. In this case the app shows these fields so the user can still manually enter their location.

If the user _has allowed_ Location for the app, then it might be related the native location plugin sometimes returning a single item rather than an array of results, this might be related.

**Comment by dalezak** [comment]
@r-tock just to confirm, did the previous version showed the location map, but the beta build alway shows the location fields instead?

**Comment by r-tock** [comment]
Right, according to the tester, the live version showed the map, but the beta build always shows the field instead.

**Comment by dalezak** [comment]
Ok, thank you, that helps 👍

**Comment by ajitsen** [comment]
https://github.com/ushahidi/platform/issues/3231#issuecomment-415613712 

> If the user has allowed Location for the app, then it might be related the native location plugin sometimes returning a single item rather than an array of results, this might be related.

I have android app,  which does not detect location,  and the Location field is not editable . 

![screenshot_20180825-005916](https://user-images.githubusercontent.com/1100651/44604078-67d1be00-a802-11e8-87cf-d166f3a95720.png)

Location Permission given to Ushahidi 
![screenshot_20180825-010211](https://user-images.githubusercontent.com/1100651/44604155-9bace380-a802-11e8-81aa-d7a30b9fc928.png)

**Comment by rowasc** [comment]
@Eve-wanderi  could you confirm if this issue is still happening in the latest mobile build Dale sent (1.12.3)?

**Comment by rowasc** [comment]
This is still happening to me in version 1.13
