### ISSUE TITLE
Survey view does not order the field as created

### ISSUE THREAD

**Issue by r-tock** [ushahidi/platform#3232]
Example https://keralarescuemap.ushahidi.io/posts/977

**Comment by willdoran** [comment]
I think it probably is, I thought it was fixed in the past but I guess not, I'll look tomorrow.

**Comment by rowasc** [comment]
FYI @Obadha2 Using this issue to track the sorting bug . I'll ping you once the fix is deployed  in qa environments

**Comment by rowasc** [comment]
Closed as this was released https://www.ushahidi.com/blog/2019/07/04/latest-release-bugfix-sorting-fields-in-ushahidi Thanks
