### ISSUE TITLE
System Design Issue: Lack of data locality slows down ushahidi

### ISSUE THREAD

**Issue by robin-anil** [ushahidi/platform#3234]
Original issue https://github.com/ushahidi/platform/issues/3229

Ushahidi 's normalized schema causes write amplification. Since every attribute is a row. For 1 post the system is inserting 50 rows if there are 50 fields.  Each of those writes is writing to different pages, which means you are doing 50 IOPS. If you have data locality you end up doing single digit page writes.

There are two suggestions, there could be other more native means of solving this

If you need another 50x improvement, you will have to remodel the data and keep all the fields denormalized. MariaDB and even Postgres have JSON columns, which you can use to store the attributes directly on the posts table, so you end up doing 1 insert.

If you need to support more databases than MariaDB and Postgres, A cheap way of doing this is to keep the fields as serialized protocol buffers which is compact. Mass column updates become slightly more difficult as you lose SQL ability to see inside the serialized block, and a search stack needs to be built for handling multi-field search. But the flip side is protos are lot more compact and helps with scale.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-301

**Comment by bobinson** [comment]
+1
