### ISSUE TITLE
[Mobile App] After logging in, 'Log In' is shown on screen

### ISSUE THREAD

**Issue by ntsreejith** [ushahidi/platform#3237]
**Describe the bug**
Android Mobile AppKeralaRescue Property Damage Assessment - After successfully logging in  also, following two lines are shown  "Log In",  "Sign Up"

**Where was the bug observed**
Android Mobile AppKeralaRescue Property Damage Assessment

**To Reproduce**
1. Install Keralarescue mobile app in  Android
2. Sign up using  email ID  
3. Login using email ID and password (Screen shot-1 and 2)
4. The page will show following  (Screen shot-3)
       View Resonses
       Log In
       Sign Up

**Expected behavior**
Instead of Log in and Signup, only _Log Out_ should be shown

**Is there a workaround? What is it.**
Go back to the phone home page, come again to the App.  It would have changed to View Respones and Logout  (Screen shot-4)

**Screenshots**
Added

**URL / Environment where this happened**
Android 

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details 
NA

**Desktop Hardware Details (please complete the following information):**
 - NA

**Smartphone Hardware Details (please complete the following information):**
 - Redmi note4
 - Android
 - stock browser
 - Version Android 7.0 NRD90M
![screenshot-4](https://user-images.githubusercontent.com/42038063/44602497-6b167b00-a7fd-11e8-9cfb-dde14b633df8.png)
![screenshot-2](https://user-images.githubusercontent.com/42038063/44602500-6baf1180-a7fd-11e8-8189-f21de2677272.png)
![screenshot-3](https://user-images.githubusercontent.com/42038063/44602502-6c47a800-a7fd-11e8-94fb-d026a09c1e29.png)
![screenshot-1](https://user-images.githubusercontent.com/42038063/44602505-6ce03e80-a7fd-11e8-9a92-b23cc0fa6c0f.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-300

**Comment by dalezak** [comment]
@rowasc this is fixed in the `1.12.2` build from other client work.

**Comment by rowasc** [comment]
Awesome. Let me set it as "waiting to release "

**Comment by dalezak** [comment]
Placed into `In Review`, will move into `QA Backlog` once the `1.12.3` beta build is ready for testing.

**Comment by rowasc** [comment]
@dalezak what is "In review" used for in this scenario?

**Comment by dalezak** [comment]
Unfortunately there's a not a state between `In Development` and `QA Backlog` to specify that the work has been done but waiting to include the change in the next beta build for testing, so just put it `In Review`.

**Comment by rowasc** [comment]
I think that's fine, we could add another pipeline if you feel you need it at some point.  I just wanted to know  . 👍

**Comment by rowasc** [comment]
@Eve-wanderi could you test this and close if it's done?

**Comment by rowasc** [comment]
@Eve-wanderi could you test this and close if it's done?

**Comment by rowasc** [comment]
Still happening for me in v1.13
