### ISSUE TITLE
Survey - Residential Property Damage Assessment - Type of Agriculture(Crop)

### ISSUE THREAD

**Issue by ntsreejith** [ushahidi/platform#3238]
**Which user group(s) are the primary audience for this feature/enhancement.**
Surveyors who do the damage assessment

Specify key workflows (e.g. crisis, elections)
Specify key use cases (program/data workers, incident management, advocacy/storytelling)

**Is your feature request related to a problem? Please describe.**
Currently there is no option to segregate different type of agriculture and loss.  This will be helpful for Government to aggregate at District or State level to find out the damage for respective type of crop,
Monetary loss for various crops will be different. It is better to capture what type of crop and extend of loss.
For example ..  Paddy 50 cents, Coffee 100 cents, Plantain - 40 cents

**Describe the solution you'd like**
Similar to the 'Damage to the vehicles' section which has Number and Types of Vehicles. Similar to that, crop type and how many cents each crop type

**Describe alternatives you've considered**
Total land area and calculated monetary loss combining all crops

**Additional context**
NA

Aha! Link: https://ushahiditeam.aha.io/features/PROD-299

**Comment by jrtricafort** [comment]
Thank you for your feedback. This enhancement request has been added to product backlog for future consideration.
