### ISSUE TITLE
"  Sorry, something went wrong. Try reloading the page." fresh install.

### ISSUE THREAD

**Issue by theauditor** [ushahidi/platform#3240]
Did a fresh install but I am getting this error. Unable to find the reason.

The issue seems to be occurring due to 404 on platform/api/v3/config. However I am unable to find solution to fix the same.

Nginx config
```

server {
	listen 80;

	#
	root /home/ubuntu/usha/html;

	# Force encoding.
	charset utf-8;
	override_charset on;


server_name erp.wanderingbuffalo.me;

error_log /var/log/nginx/error.log;


	location /platform {
		fastcgi_param   QUERY_STRING            $query_string;
		fastcgi_param   REQUEST_METHOD          $request_method;
		fastcgi_param   CONTENT_TYPE            $content_type;
		fastcgi_param   CONTENT_LENGTH          $content_length;

		fastcgi_split_path_info					^(/platform/)(.*)$;

		fastcgi_param   SCRIPT_FILENAME         $document_root/platform/httpdocs/index.php;
		fastcgi_param   SCRIPT_NAME             $fastcgi_script_name;
		fastcgi_param   PATH_INFO               $fastcgi_path_info;
		fastcgi_param   PATH_TRANSLATED         $document_root$fastcgi_path_info;
		fastcgi_param   REQUEST_URI             $request_uri;
		fastcgi_param   DOCUMENT_URI            $document_uri;
		fastcgi_param   DOCUMENT_ROOT           $document_root;
		fastcgi_param   SERVER_PROTOCOL         $server_protocol;

		fastcgi_param   GATEWAY_INTERFACE       CGI/1.1;
		fastcgi_param   SERVER_SOFTWARE         nginx/$nginx_version;


include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
	

}

	location / {
		try_files $uri /index.html;
	}
}

```

Response header

`

Connection | keep-alive
-- | --

`

**Comment by rowasc** [comment]
Hi @theauditor . Were you able to resolve this?

**Comment by theauditor** [comment]
No, Could not.

*Blaise M  Crowly*
*"vi veri veniversum vivus vici"*
*www.xincoz.com <http://www.xincoz.com>  *

**Comment by josejuansanchez** [comment]
@theauditor I have the same issue. Do you have any idea about how to solve it? Thanks.

**Comment by theauditor** [comment]
Tried all I could find online. No luck. Most off the issues and solutions posted online has no connection with this current problem am facing. 
Having followed and retried with install instructions again and again I have been unable to get results. 

On October 16, 2018 5:15:38 PM GMT+05:30, "José Juan Sánchez" <notifications@github.com> wrote:
>@theauditor I have the same issue. Do you have any idea about how to
>solve it? Thanks.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ushahidi/platform/issues/3240#issuecomment-430206099

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rowasc** [comment]
@theauditor @josejuansanchez would you mind posting what the server returns if you call the platform api directly, and the logs from that action?
(the logs can be in application/logs if you are using a v3.x.x release, or in storage/logs if you are in v4.x.x/develop)

**Comment by rowasc** [comment]
oh sorry misread the issue.
@theauditor @josejuansanchez the 404 in /api/v3/config points to a misconfiguration in nginx, can you review that the platform directories  you are referencing in nginx are available and have the correct permissions?

**Comment by theauditor** [comment]
It kept returning 404 on direct all.
I set all the permissions to 777 to test and still faced the issue. 
Will try and post the directory tree, but Dont think there is an issue there. 

Kind of confused. The chance exist that o may have screwed up something on my side. Let me try a fresh install and see. 

On October 16, 2018 6:15:31 PM GMT+05:30, Romina Suarez <notifications@github.com> wrote:
>oh sorry misread the issue.
>@theauditor @josejuansanchez the 404 in /api/v3/config points to a
>misconfiguration in nginx, can you review that the platform directories
>you are referencing in nginx are available and have the correct
>permissions?
> 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ushahidi/platform/issues/3240#issuecomment-430223071

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rowasc** [comment]
@theauditor great. Thanks. If there's a 404, it's 99% chance that there's something wrong in that setup. A suggestion for debugging it is that you add a simple PHP script in the httpdocs directory and verify that it gives you a 404 too (in $document_root/platform/httpdocs/hello.php ) , 
You can even do it in a separate directory structure if you want to rule out problems with the platform dir configuration specifically , and go from there

**Comment by theauditor** [comment]
Will do and get back. :)

On October 16, 2018 6:38:30 PM GMT+05:30, Romina Suarez <notifications@github.com> wrote:
>@theauditor great. Thanks. If there's a 404, it's 99% chance that
>there's something wrong in that setup. A suggestion for debugging it is
>that you add a simple PHP script in the httpdocs directory and verify
>that it gives you a 404 too (in
>$document_root/platform/httpdocs/hello.php ) , 
>You can even do it in a separate directory structure if you want to
>rule out problems with the platform dir configuration specifically ,
>and go from there 
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ushahidi/platform/issues/3240#issuecomment-430230445

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rowasc** [comment]
@josejuansanchez that's great info , thanks for sharing 💯 . Were you using the platform-release or the platform repository? Would you like to open a PR with what you had to change for it work in apache 2.4 ?

**Comment by rowasc** [comment]
Thank you for using Ushahidi Platform. I'm closing this issue due to a lack of activity. Please comment in this issue or in our gitter community https://gitter.im/ushahidi/Community if you need any more support and we'll be happy to help.
