### ISSUE TITLE
Unable to see responses submitted while users are Offline.

### ISSUE THREAD

**Issue by Eve-wanderi** [ushahidi/platform#3242]
**Describe the bug**
Unable to see responses submitted while users are Offline this cuts across Mobile Apps i.e Sivico,Xenowatch  for both Android and IOS.

**Where was the bug observed**
This cuts across  Mobile Apps tested i.e Xenowatch,Sivico

**To Reproduce**
1. Go to 'Ushahidi.'
2.Search for xenowatch
3.Turn off your wifi/data bundles
4.Post a response.
5.Turn on your wifi/data bundles and sync data
6.Go to view responses and check if the post submitted in 4 is available.

**Expected behavior**
When a user posts a report while offline then goes back online they should see the submitted post while offline.

**Is there a workaround? What is it.**
No

**Screenshots**

**URL / Environment where this happened**

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**

**Desktop Hardware Details (please complete the following information):**

**Smartphone Hardware Details (please complete the following information):**
 - Device: [e.g. iPhone SE]
 - Device: [samsung 8+]
 - OS: [Android Oreo]

**Additional context**
**This works for Platform Mobile App version 1.12.2 tested on rominacsvssms.ushahidi.io**

Aha! Link: https://ushahiditeam.aha.io/features/PROD-298

**Comment by rowasc** [comment]
@dalezak could you give an estimate for this?
Reference on estimates can be found here https://docs.google.com/document/d/1Au0XOdUiSTpb8f-h7AAU9wPO-tuH-1kaS__fC_XzhB8/edit#heading=h.ut3ch6itelth (the getting a baseline section might be the most relevant

Since we don't have other devs in mobile, I can act as a sounding board (but in the end, it'll just be your estimate)

**Comment by rowasc** [comment]
@dalezak bumping. What's the status on this?

**Comment by dalezak** [comment]
@Eve-wanderi could the issue be that the report needs to be approved on the backend (for example still in draft), before they appear back in the app? /cc @rowasc

**Comment by dalezak** [comment]
Perhaps a duplicate to https://github.com/ushahidi/platform/issues/3239

**Comment by rowasc** [comment]
users who are not logged in should not see drafts. @Eve-wanderi is that the problem you were running into?

**Comment by rowasc** [comment]
Bumping. @Eve-wanderi

**Comment by Eve-wanderi** [comment]
@dalezak  No the report did not need any approval to be viewed it wasnt a draft. We can sync up to replicate this.

**Comment by rowasc** [comment]
@rowasc to sync up with @Eve-wanderi next week on our 1-1

**Comment by tuxpiper** [comment]
I'm suspecting this was a known problem with geocoding failing while saving the post or doing the sync. It has been addressed since.
