### ISSUE TITLE
COMRADES UI makes distinct "categories" unreadable, needs to specify source Service 

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#3244]
**Describe the bug**
When viewing a post in data mode the "Categories" section, which contains returns from the services of CREES (#2572) and EMINA (#3057), the values - from each service - are presented as a single string of text separated by commas. This makes it nearly impossible to understand which "tags" are related to which service. See screenshot below
<img width="1230" alt="comrades_problem_ui" src="https://user-images.githubusercontent.com/4574998/44752255-b79cd780-aad7-11e8-8450-b944c49924b6.png">

**Where was the bug observed**
This is in the [COMRADES deployment](https://comrades-stg.ushahidi.com). The specific post [presented in the screenshots is post #37](https://comrades-stg.ushahidi.com/posts/37). 

**To Reproduce**
1. Go to https://comrades-stg.ushahidi.com
2. View posts in data mode.

**Expected behavior**
As a user, I need to be able quickly and easily to understand which tags are returned from which service to better understand what I'm looking at. I've quickly mocked up two possible solutions: _these are not prescriptive_ and are only intended to help design and engineering understand the problem better. 

*Possible solution 1*
This shows each services "tag" with associated returns under the main "categories" heading (as an aside, why is this section labeled "categories"? this is probably its own bug because I believe each service used to have its own title). 
<img width="1193" alt="comrades_suggested_ui_1" src="https://user-images.githubusercontent.com/4574998/44752665-ecf5f500-aad8-11e8-9b29-68d4b2874a38.png">

*Possible solution 2*
This shows each service as its own "category" which is, I believe, how data mode used to look.  
<img width="1193" alt="comrades_suggested_ui_2" src="https://user-images.githubusercontent.com/4574998/44752771-45c58d80-aad9-11e8-9476-8b5bcff4d672.png">

**Additional context**
It's worth noting that the EMINA (veracity/validity) service also returns a value (0-1) that describes how sure the service is that the return is accurate. For example, a return of "valid, 0.98" would mean that the return of "valid" is highly accurate. If, on the other hand, the return was "valid, 0.59" then the return is likely questionable. I would _like_ (this is a "nice to have") to at least make some headway on providing a specific tag/icon to show this. The COMRADES partners have explicitly discussed this as important because of the severe lack of trust that the deployment would have if a return of low accuracy is returned and the level of accuracy isn't communicated to the user. Some initial mock-ups and thoughts on this were produced by Brandon, Jess, and others when the project started: see issue #1681

**Comment by Shadrock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [COMRADES services UI github write up.](https://trello.com/c/G5G9uYFY/328-comrades-services-ui-github-write-up)

**Comment by jrtricafort** [comment]
@Shadrock I discussed this w @rowasc , here's our plan:

I think we should address this as two separate issues, both of which we are planning to do this cycle:

1. Make categories readable by adding a specification in the UI to tell the user where/from which service the category tag came from (CREES, EMINA, VERACITY, etc). We can implement this fix, accordingly to the suggestion screenshot that @willdoran sent in the comment above, this cycle. Let's track this on this issue that we're on here: https://github.com/ushahidi/platform/issues/3244 

2. Add "validity score" to the UI as well, for tags that come from services that include a valditiy score. @Shadrock - Our understanding is that VERACITY (not EMINA, not CREES, not YODIE) is the only COMRADES service that includes a validity score. Please let us know if that's incorrect (i.e. if Emina offers up a validity score-- we don't think it does currently). As such, we will plan to include the validity score in the UI, and we will track that work on this issue, as part of the VERACITY integration, which we are doing this cycle also: https://github.com/ushahidi/platform-cloud-interface/issues/370

**Comment by rowasc** [comment]
@jrtricafort EMINA=> I think the EMINA service refers to veracity ( re-reading Shadrock's message). But yea, as far as I know only Veracity has the accuracy value. 
@Shadrock I can work on veracity and the UI changes this week if we figure out how to implement the UI . It's my main priority outside of "cleanup lumen" . Let me know in https://github.com/ushahidi/platform-cloud-interface/issues/370 if you can mock up something or describe how it should look, and then I'll ping you to demo the UI quickly and continue integrating

**Comment by Shadrock** [comment]
Thanks @jrtricafort @willdoran @rowasc. This all sounds good to me. To be clear, I'll refer to the (now) two distinct issues as described by Juan above: 

1. Making categories readable by adding a specification in the UI to tell the user where/from which service the category tag came from sounds great. Will's example suggests that this is already possible so perhaps I just missed this or the COMRADES deployment (or this particular survey) is currently not configured correctly. In any event, Will's screenshot above would completely resolve this issue for me: all I need is clarity on what categories belong to which service. Perhaps I could do another walkthrough with somebody to make sure I understand this set up well.
2. With regards to the veracity/validity service: the terms we're using hear might be a bit confusing because at least one of the "services" is actually composed of two services. In any event, there is only one service I'm aware of that returns a result for veracity (I'll defer to the devs on this, but am happy to go back through my emails and notes to verify). 

Let me know if there's anything else I can do to help move this along.

**Comment by jrtricafort** [comment]
@Shadrock Regarding #1, yes it's something that we would need to configure, but should be able to do shortly.

Regarding #2, yes thanks for the clarification. I think we're on the same page regarding what needs to be done. The two-in-one services thing I think was confusing me. We can just be cognizant of that language going forward.

**Comment by rowasc** [comment]
Solved for comrades. This was buggy when categories were being added from the services in comrades-service-proxy. 

I will clean things up before I send the fix for `develop` and probably feature flag some stuff that we did for veracity too. 
This will be closed once I demo it to @Shadrock and we review if there's any changes to make there

**Comment by rowasc** [comment]
Closing this was done
