### ISSUE TITLE
Follow up on issues found with dataproviders 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3247]
Reference issue: https://github.com/ushahidi/account-management/issues/43

Comment from @kinstelli  on follow up: 
## My recommended follow-ups on this so far:

- We should figure out why savedsearch takes so long to run.

- We should update dataproviders.py so that if any of these individual CLI subprocesses take a very long time, they don't interfere with other tasks, like exporting data. I'm not sure if that means splitting some of these into individual celery tasks, or if there's a way we can spawn multiple processes -- but it's probably an architecture discussion worth debating .

**Comment by rowasc** [comment]
Moving to cycle 10 as we do not have the resources for it now

**Comment by tuxpiper** [comment]
I've pushed a PR ( https://github.com/ushahidi/platform-job-queue/pull/58 ) for this item :

> We should update dataproviders.py so that if any of these individual CLI subprocesses take a very long time, they don't interfere with other tasks, like exporting data. I'm not sure if that means splitting some of these into individual celery tasks, or if there's *a way we can spawn multiple processes* -- but it's probably an architecture discussion worth debating .

It's something that has been annoying me for a while

**Comment by rowasc** [comment]
Awesome. Let's prepare a release to go out after pricing/DREAMS surveys just to be safe that we won't impact them :D 

cc @willdoran let me know if you disagree and want to release earlier

**Comment by willdoran** [comment]
@rowasc Agree completely

**Comment by tuxpiper** [comment]
So it looks like my fix got deployed to production and nothing exploded 🎉 

Do we still have this to check in this issue?
> We should figure out why savedsearch takes so long to run.

**Comment by rowasc** [comment]
I will lower the priority on the savedsearches part  since we have a lot of other things going on right now. Clsoing this issue and linking a new one about saved searches perf.

**Comment by rowasc** [comment]
Actually Robbie already explained 
> I think it literally runs every saved search query, then inserts entries in post_sets table for every post that matched, but wasn't already in there. ie. it's really inefficient and would be much better handled through listeners when creating a new post to just compare if that post matches any searches w/notifications

I don't think we have the time to do this right now, but I'll create an issue to avoid losing this
