### ISSUE TITLE
Video uploads are not working on mobile

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3248]
**Describe the bug**
Video uploads are not working on mobile
**Where was the bug observed**
Deployment on platcloud-prod.ush.zone

**To Reproduce**
1. Add a survey with a field type video
2. Try to submit a response to the survey with the mobile app
3. You will get a "problem posting your response" error
4. Delete your video from the post
5. Re-submit
6. This will work

**Expected behavior**
1. You don't have an option to upload videos in mobile

**Is there a workaround? What is it.**
Not posting a video

**URL / Environment where this happened**
Deployment on platcloud-prod.ush.zone

**Smartphone Hardware Details (please complete the following information):**
 - Device: Samsung S9+
 - OS: Android
- Ushahidi mobile app 
 - Version 8.0.0

**Additional context**

**Comment by dalezak** [comment]
Ya, that would be the reason 😞 

The super fancy and awesome video upload I implemented got disabled with the security fixes.

**Comment by dalezak** [comment]
_Sigh_, on a personal note, it's super sad to remove that video upload... 😢

**Comment by dalezak** [comment]
@rowasc the video upload functionality has been removed, instead the user can only include URL to an existing YouTube Vimeo video.

This change can be tested in the next build `1.12.3` once it is ready.

**Comment by rowasc** [comment]
Awesome. I'll send to "qa backlog " for Eve . Can you start a milestone with the stuff that we need to test for the 1.12.3 release?

**Comment by Eve-wanderi** [comment]
@rowasc  Confirmed this passed QA.

**Comment by dalezak** [comment]
This was fixed with https://github.com/ushahidi/platform-sivico/issues/52.... closing issue.
