### ISSUE TITLE
Public posts still require authentication

### ISSUE THREAD

**Issue by francbartoli** [ushahidi/platform#325]
When navigating the list of posts by an unauthenticated user the login page is triggered

**Comment by jasonmule** [comment]
Could not reproduce

**Comment by rjmackay** [comment]
@francbartoli did this happen multiple times? any chance it was just your session timing out?
Auth tokens are relatively short lived

**Comment by francbartoli** [comment]
It did happen after a logout from an authn member session.

Il giorno 17/ago/2015, alle ore 22:24, Robbie Mackay <notifications@github.com> ha scritto:

**Comment by rjmackay** [comment]
Ok thanks. That's useful.. we might be accidentally requesting private data from the auth'd session after the token has cleared.. that'd be likely to redirect to a login.

**Comment by rjmackay** [comment]
Can't reproduce this either. I'm going to close for now. 
I have some planned improvements to handling updating/clearing data from a session, hopefully that might help fix this if its an intermittent bug.

**Comment by vbhv** [comment]
You can try the steps as described in #409 to try and reproduce
