### ISSUE TITLE
Field type "Related posts" does not show any posts in mobile

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3250]
## Task for cycle 10 for @Eve-wanderi 
- Verify this feature works as expected if there are posts available in the same survey type in the app
- If it doesn't work, ping us

**Describe the bug**
Field type "Related posts" does not show any posts in mobile. It shows a popup but it doesn't have options or a way to search. 
**Where was the bug observed**
Mobile app . Deployment on platcloud-prod.ush.zone

**To Reproduce**
1. Go to a survey with a "Related posts" field
2. Try to submit a report with a post selected in the related posts field 
3. You will not see any posts

**Expected behavior**
3. You should see a way to select posts

**Is there a workaround? What is it.**
Using the web

**Smartphone Hardware Details (please complete the following information):**
- Device: Samsung S9+
- OS: Android
- Ushahidi mobile app
- Version 8.0.0

Aha! Link: https://ushahiditeam.aha.io/features/PROD-296

**Comment by dalezak** [comment]
@rowasc this might be a bug or maybe just a limitation in the app.
 
The app only shows currently downloaded reports as potential related post option. 

So if there are no other posts in the app, then there is nothing to show in the list.
