### ISSUE TITLE
I can see posts that were previously published but were put "In review" after I saw them

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3251]
**Describe the bug**
I can see drafts and archived posts that I created from the ushahidi app after I log out
**Where was the bug observed**
- Deployment on platcloud-prod.ush.zone

- Rominacsvssms.ushahidi.io (PROD, with kohana)

**To Reproduce**
1. In the mobile app, go to "View responses". Look for the first post.
2. In the web, put the first post (or any really) in the "In review " status 
3. In the mobile app, reload the responses list
4. You will see posts that are drafts even when you are not logged in 

**Expected behavior**
4. Drafts should not be visible for non logged in users

**Is there a workaround? What is it.**
No

**Smartphone Hardware Details (please complete the following information):**
- Device: Samsung S9+
- OS: Android
- Ushahidi mobile app
- Version 8.0.0

**Additional context**
When I use the filters, it seems to work ok (ie filters our by status and surveys), but not when I'm in the normal view responses list . The api returns correctly (drafts are not in the response for non-logged in users_ . at least when I checked on the web

Aha! Link: https://ushahiditeam.aha.io/features/PROD-295

**Comment by dalezak** [comment]
Hmm, @rowasc this is a tricky problem to solve, not sure whether there is a simple solution.

- the user is logged out of the app 
- the app makes a request to the API for most recent posts
- those posts are stored in the local database
- the post is put `in review` on the website
- the app requests recent posts, the `in review` post is excluded from results
- the app has the old version of post stored locally, with no way to know it's been put `in review`

Note, this issue can also happen when deleted posts. 

For previous products I've built, I've added `/deletes` endpoint which returns a list ids that have been deleted, telling the app to _purge those local objects_. 

The only other workaround is a complex comparison of what's returned from the API vs what's being stored locally, which is fairly problematic and error prone.

So perhaps this is an issue we choose not to fix? //cc @willdoran @rjmackay
