### ISSUE TITLE
Survey fields are not updated in mobile when they are updated in the web (even after I refresh)

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3252]
**Describe the bug**
Survey fields are not updated in mobile when they are updated in the web (even after I refresh)
**Where was the bug observed**
https://rominacsvssms.ushahidi.io/views/map

**To Reproduce**
1. Go to a deployment in the mobile app
2. Open one of the surveys available to submit a response. Check the form there with all the fields it has.
3. In the web, go to the same survey as an admin and add one more field
4. In the mobile app, you will not see your new field even after refreshing the "page"

**Expected behavior**
4. In the mobile app, you should see the new field

**Is there a workaround? What is it.**
Not sure. Maybe clearing storage?
**Smartphone Hardware Details (please complete the following information):**
- Device: Samsung S9+
- OS: Android
- Ushahidi mobile app
- Version 8.0.0

Aha! Link: https://ushahiditeam.aha.io/features/PROD-294

**Comment by dalezak** [comment]
I don't believe this is a bug @rowasc, just a limitation in the app.

The _Surveys_, _Stages_ and _Attributes_ are _only_ loaded from the **Deployment Details** screen, so if you pull down to refresh they should get refreshed in the app.

So currently the **Report Listing** does _not_ load _Surveys_ since it's already doing a large number of network requests to obtain all the data needed for Posts, such as _Users_, _Images_, etc.

**Comment by dalezak** [comment]
@rowasc I _think_ the only way for us to _fix_ this, is to also re-download all _Surveys_, _Stages_ and _Attributes_ from the API when refreshing the Response List.

This however is really gonna increase the time it takes to get reports, especially on slow internet connections.

**Comment by dalezak** [comment]
This is another issue I'm not sure whether we want to fix or not?

To fix the issue, we'd need to also re-download _Surveys_, _Stages_ and _Attributes_ on the _Report Listing_ screen as well, which would increase the time it takes to download all the data from the API.

Thoughts @rowasc @willdoran @rjmackay?

**Comment by rowasc** [comment]
@dalezak I thinkk it might be reasonable to pull down the data when you click on the deployment name from the list of deployments, but its really up to @jrtricafort . I think this is probably a P2 and we can wait until next cycle to consider it since surveys don't change that often.

**Comment by dalezak** [comment]
Just to recap @rowasc, currently this is what we load on pull down to refresh:

**Side Menu**
- Deployments from database

**Deployment Details**
- Surveys from API
- Stages from API
- Attributes from API
- Tags from API
- Collections from API

**Report Listing**
- Posts from API
- Users from API
- Media from API

**Comment by rjmackay** [comment]
Is there any indicator we can use to check if a survey changed before refreshing it? ie. has the Surveys 'updated' timestamp?
