### ISSUE TITLE
"relate two surveys" does not work

### ISSUE THREAD

**Issue by sajith** [ushahidi/platform#3253]
When creating a survey, came across the option to "relate two surveys" but cannot find any documentation on what this actually does. 

When this field is added to the survey, it shows up as a "search bar" with a "Search" button.  

The search do not bring up anything, even after trying different search terms and combinations of them.

(I am reporting this for someone else who do not have a Github account.  Please bear with me in case I am not able to clarify things immediately.  Hopefully nothing is lost in transmission...)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-293

**Comment by sajith** [comment]
@rowasc Looks like I need to clarify.  This isn't really a question. :-) 

This was brought up with Ushahidi support, and they agreed that this looks like a bug and asked to file an issue here.

**Comment by aoduor** [comment]
hey @rowasc  - i can confirm that I tested this out with the user on intercom. The feature doesn't work as expected. The search field does not return any results. Something worth looking into.

**Comment by Angamanga** [comment]
Solved here: https://github.com/ushahidi/platform/issues/4078, closing
