### ISSUE TITLE
Unable to Post Responses while Offline.

### ISSUE THREAD

**Issue by Eve-wanderi** [ushahidi/platform#3257]
**Describe the bug**
If a user is offline they cannot Post responses get an errror unable to post response.

**Where was the bug observed**
Mobile App (https://rominacsvsms.ushahidi.io)

**To Reproduce**
 **Make sure your offline.**
1. Go to 'https://rominacsvsms.ushahidi.io' mobile App.
2. Log in as 'Admin' (Please note if certain user permissions, like Admin or Manage Data, are required to reproduce this bug. Also include if there is a support@ or admin@ account for this deployment. If not, contact the platform slack channel with further instructions.)
3. Click on ' Submit Survey Response'
4. Scroll down to 'Basic Post.'
5. Fill in all details.
6. Submit the Posts.
7. Go back online and sync the data then check if you can see the post you submitted while offline.

Case 2.
Make sure your not logged in
1. Go to 'https://rominacsvsms.ushahidi.io' mobile App.
2.. Click on ' Submit Survey Response'
4. Scroll down to 'Basic Post.'
5. Fill in all details.
6. Submit the Posts.
7. Go back online and sync the data then check if you can see the post you submitted while offline.

**Expected behavior**
Posts submitted offline should be visible once user goes online and sync the data.

**Is there a workaround? What is it.**
No

**Screenshots**

**URL / Environment where this happened**
[e.g https://rominacsvsms.ushahidi.io' mobile App.

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**

**Smartphone Hardware Details (please complete the following information):**
 - Device: [Samsung S8+]
 - OS: [Android]
 - Version [Version 8.0.0]

**Additional context**

**Comment by dalezak** [comment]
Might be related issue to https://github.com/ushahidi/platform/issues/3254#issuecomment-417441829

**Comment by dalezak** [comment]
I believe this is also related to https://github.com/ushahidi/platform/issues/3254, assigning to you @rowasc to fix on the backend.

**Comment by dalezak** [comment]
The fix mentioned here https://github.com/ushahidi/platform/issues/3254#issuecomment-417521423, should resolve this issue.

**Comment by rjmackay** [comment]
This should be fixed now I think?

**Comment by dalezak** [comment]
As [mentioned above](https://github.com/ushahidi/platform/issues/3257#issuecomment-417524697), this has been fixed on the backend... closing issue.
