### ISSUE TITLE
Changing the authorization policy to "Publish to Admin" doesn't apply accordingly 

### ISSUE THREAD

**Issue by francbartoli** [ushahidi/platform#326]
* Create a post from a member role and publish as "Draft"
* Logon as Admin and "*Publish as Member*" that post then logout
* Logon as Member and I continue to be able to edit the post then logout
* Logon as Admin and change the policy to "*Publish as Admin*" then logout
* Logon as the Member user who created the post I still continue to see the post and being able to edit it too
* Logon as Members who didn't create the post they don't see it as expected

Is it a bug or behavior?

**Comment by rjmackay** [comment]
This is actually the desired behaviour:
- A posts creator can always edit the post
- Only admins should see a post thats "Published to Admin"
