### ISSUE TITLE
User search in /settings/users is not working

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3264]
**Describe the bug**
I don't see any users when I search by their real name, email or part of their email 

**Where was the bug observed**
Include Deployment and page URL (e.g. "https://test.ushahidi.io/views/map")

**To Reproduce**
1. Go to Settings -> Users as an admin
2. Use the search bar to search for users (search for an existing user)
3. You won't see any results

**Expected behavior**
3. You should see the user that matches the email

**Is there a workaround? What is it.**
Looking in the list to find a user without search

**URL / Environment where this happened**
http://rominacsvsms.ushahidi.io/

**Desktop Hardware Details (please complete the following information):**
 - OS: OSX
 - Browser : Chrome
 - Version: 68.0.3440.106

**Comment by bobinson** [comment]
Fixing this can be of great help as we have volunteers registering and assigning roles to them is very difficult right now.

**Comment by rowasc** [comment]
Thanks @bobinson for your feedback..  I think I have a fix that works with emails and usernames as expected, but it needs some QA still (mostly to make sure there's no unexpected issues) . I've asked @Obadha2 and @tuxpiper to take a look and I'll try to schedule the release for Monday in my afternoon if it all looks good for them too.
Thank you for your patience.

**Comment by rowasc** [comment]
Hey @Obadha2 we deployed this today thanks to @tuxpiper who reviewed the code 🎉 . Could you test in Steve-buscemi when you come online? 
Sadly I need to run out to the hospital to deal with a family emergency right now  :( so I'm not releasing today as I originally planned, but any updates on how the testing goes would be great.
 
Thank you all for your patience and help as we fix this issue.

**Comment by rowasc** [comment]
We just released this. Closing!  I was able to search/find my users in my deployment (phew).
Let us know how it goes if you try it? 
Thanks! 

Separate note: While doing testing for this specific fix, @Obadha2 discovered other pre-existing bugs in the same  area (filters & user filters) we are hoping to tackle soon. 

https://github.com/ushahidi/platform/issues/3649 UX issue that I'm aware of
and I think there were another few UX things he noticed weren't right
 @Obadha2 can you link them up when you start working tomorrow?

**Comment by Obadha2** [comment]
#3656
