### ISSUE TITLE
There is no way to sort for users  in the list of users

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3265]
## Want to work on this issue?🙋 
Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

## Describe the bug
There is no way to sort users in the user list

## To Reproduce
1. Go to Settings->User as an admin
2. You won't have a way to sort users

## Expected behavior
Users should be sortable. 

**Context**
I think this may not be a bug, but i'm reporting it because it was part of the original regressions

**Comment by c3ho** [comment]
Hi, first-time contributor. Can I try to work on this issue?

**Comment by rowasc** [comment]
Totally. Tag @Angamanga or @rowasc if you get stuck :) Sorry for the delay!

**Comment by c3ho** [comment]
@rowasc any particular sort methods for the users you wanted?

**Comment by sparshkrjha** [comment]
@rowasc @Angamanga Can I also work on this issue?

**Comment by Angamanga** [comment]
@sparshkrjha Yes please go ahead :) Thank you for your interest in contributing!

**Comment by Angamanga** [comment]
@sparshkrjha How is it going? Please let me know if you need any guidance with this!

**Comment by himil-vasava** [comment]
@Angamanga @rowasc Can I work on this issue?

**Comment by Angamanga** [comment]
@himil-vasava Yes, please go ahead :) Thank you!

**Comment by himil-vasava** [comment]
@Angamanga should i create a dropdown for sorting and have two options in it - alphabetical and roles ?

**Comment by Angamanga** [comment]
@himil-vasava Yes that sounds good 👍

**Comment by himil-vasava** [comment]
@Angamanga In what priority the roles should be sorted?

**Comment by himil-vasava** [comment]
@Angamanga could you please elaborate on sorting according to roles.

**Comment by Angamanga** [comment]
@himil-vasava Roles is hard to sort, but we can filter them with checkboxes, i.e. if you select a specific role, only those users should be visible. Something like this:
![Screenshot 2020-04-22 at 09 18 29](https://user-images.githubusercontent.com/8624777/79952138-3e0ae780-847a-11ea-8788-8540efbd64db.png)

**Comment by himil-vasava** [comment]
@Angamanga I thik that feature is already there
![Screenshot from 2020-04-22 12-57-22](https://user-images.githubusercontent.com/55590415/79952996-d9ab5080-8498-11ea-92c5-2ac0eb7c0cb7.png)

**Comment by Angamanga** [comment]
@himil-vasava Ah, just add alphabetical sort then :)

**Comment by himil-vasava** [comment]
@Angamanga could you please help me by telling what i am doing wrong here in the pull request
