### ISSUE TITLE
The list of categories is in reverse chronological order instead of alphabetical

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3266]
**Describe the bug**
The list of categories is in reverse chronological order instead of alphabetical

**Where was the bug observed**
rominacsvsms.ushahidi.com

**To Reproduce**
1. Go to Settings -> Categories as admin
2. The list of categories will not be sorted alphabetically

**Expected behavior**
2. The list of categories will be sorted alphabetically

**Comment by willdoran** [comment]
@rowasc This is correct, I think, this is the change we made a while ago.

**Comment by rowasc** [comment]
closing
