### ISSUE TITLE
Map modebar filters are not working , except for "Show only" survey filter

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3267]
**Describe the bug**
Selecting only some surveys and datasources does not filter the data in the map correctly.

<img width="1114" alt="map" src="https://user-images.githubusercontent.com/2434401/44933908-43fe0300-ad41-11e8-8b5c-892991212935.png">

**Where was the bug observed**
https://rominacsvsms.ushahidi.io/views/map

**To Reproduce**
1. Go to Map
2. Select only web and one survey
3. You will still see results from other surveys/datasources

**Desktop Hardware Details (please complete the following information):**
 - OS: OSX
 - Browser : Chrome
 - Version: 68.0.3440.106

Aha! Link: https://ushahiditeam.aha.io/features/PROD-291

**Comment by rowasc** [comment]
@jrtricafort P1?

**Comment by jrtricafort** [comment]
@rowasc This is a Lumen regression or existing bug?

**Comment by rowasc** [comment]
Looks like its a regression, it was passing before.

**Comment by jrtricafort** [comment]
p1
