### ISSUE TITLE
Twitter, sms and email stats are wrong in the activity view's crowdsourced data panel

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3268]
**Describe the bug**
- Twitter posts should counted in the twitter column
- SMS posts should counted in the SMS column
- Email posts should counted in the email column
- Total activity name is incorrect and total activity does not include unstructured posts in total

**Where was the bug observed**
"https://rominacsvsms.ushahidi.io/

**To Reproduce**
1. Go to Activity as admin
2. Check the "Crowdsourced survey" panel 
3. SMS, EMAIL and TWITTER are all 0 

**Expected behavior**
Your SMS, EMAIL and TWITTER counts should match the correct count / values of posts from each source. 

**Screenshots**
<img width="733" alt="screen shot 2018-08-31 at 5 20 02 pm" src="https://user-images.githubusercontent.com/2434401/44934150-24b3a580-ad42-11e8-94c7-4542b81ccc46.png">
**Desktop Hardware Details (please complete the following information):**
 - OS: OSX
 - Browser : Chrome
 - Version: 68.0.3440.106

**Comment by rowasc** [comment]
Adding to cycle 9 as part of lumen cleanup

**Comment by rowasc** [comment]
Confirmed this is broken .

**Comment by jrtricafort** [comment]
@rowasc @crcommons Great catch. Yes, P1 is correct, especially since we will be reporting stats this month. 
For context, was this a regression introduced by Lumen migration?

**Comment by rowasc** [comment]
@jrtricafort  
yea... I think I may have introduced this while porting it , since in the original release I checked it live and everything :|

**Comment by crcommons** [comment]
Tested in QA and it passed.

**Comment by rowasc** [comment]
Awesome. I can take another look and release today :D 
Can you send me credentials for the deployment you used?

**Comment by rowasc** [comment]
I'm actually going to release this in the morning because I can't do another late day, but it passed  and it can go live

**Comment by rowasc** [comment]
Released
