### ISSUE TITLE
Notifications for posts added to a collection are not being sent

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3269]
**Describe the bug**
I didn't receive notifications when a post was added to a collection I was subscribed to

**Where was the bug observed**
rominacsvsms.ushahidi.io

**To Reproduce**
1. Go to the collections list. 
2. Click a collection. It will take you to the map view . 
3. Click the "3 dots"  button for the collection in the mode bar. 
4. Click the "notifications" button to turn them on.
5. Add a post to the collection

**Expected behavior**
5. You should receive a notification

**Is there a workaround? What is it.**
no

**Screenshots**
<img width="212" alt="screen shot 2018-08-31 at 5 24 47 pm" src="https://user-images.githubusercontent.com/2434401/44934401-0ac69280-ad43-11e8-9daf-e88503e62c22.png">

**Comment by rowasc** [comment]
Note: email datasource was configured for this deployment .

**Comment by rowasc** [comment]
@jrtricafort

**Comment by jrtricafort** [comment]
@rowasc This is a Lumen regression or existing bug?

**Comment by rowasc** [comment]
Regression, it was passing

**Comment by jrtricafort** [comment]
p1

**Comment by rjmackay** [comment]
@rowasc What user and deployment was this tested with?
If the user doesn't have an contacts with the `can_notify` flag set, then their notifications are ignored. It's a weird behaviour, but not new.

**Comment by rjmackay** [comment]
Ah. It looks suspiciously like messages are queued as `incoming` not `outgoing`. It looks suspiciously like this might been the case in the old code too, but it might have been getting fixed somewhere else in the data flow.

**Comment by rowasc** [comment]
>If the user doesn't have an contacts with the can_notify flag set, then their notifications are ignored. It's a weird behaviour, but not new.
I don't know if my user had that flag. It's `romina+csvdeployment@ushahidi.com`
