### ISSUE TITLE
Targeted survey has wrong direction and is sending TItle/Desc as questions to users

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3275]
**Describe the bug**
Targeted surveys are creating Title and Desc as messages that are sent to users
The first outgoing message is set as incoming.

**Where was the bug observed**
Locally  - develop
**To test it works (expected behavior)**
-  Create a targeted survey. Verify that the first message is created with 'direction=outgoing'

 - Respond to the all the survey questions. Verify that no messages other than the ones you created are sent (title and description should be ignored).

-  Verify that the survey is marked as "SURVEY FINISHED" in targeted_survey_state table when you are done responding to all questions

**Additional context**
I found this bug while checking targeted surveys locally for another reason

**Comment by rowasc** [comment]
@jrtricafort added this to cycle 9 as lumen cleanup

**Comment by jrtricafort** [comment]
@rowasc Is this related to https://github.com/ushahidi/platform/issues/3277

**Comment by rowasc** [comment]
No. But #3272 is related to #3277 (duplicate actually)

**Comment by rowasc** [comment]
Mark tested it today, and I tested yesterday. 
Released fix today
