### ISSUE TITLE
Error message unclear: Failed to validate posts entity: Stage "Required Task" is required before publishing

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#3276]
**Describe the bug**
I tried to Publish a new report I just posted on the web, and got the error
```
Failed to validate posts entity: Stage "Required Task" is required before publishing
```
It is unclear that the reason that the post could not be published is that it has a required task remaining. UX needs to be adjusted for clarity/usability

**Where was the bug observed**
https://dale.ushahidi.io/posts/138

**To Reproduce**
1. Select an unpublished post that also has an uncompleted task that is required to be completed for publishing
2. As an admin, attempt to publish the post
3. An unclear error should appear

**Expected behavior**
Unclear. Needs UX design changes.

**Screenshots**
![unspecified](https://user-images.githubusercontent.com/91811/45064474-39a97500-b071-11e8-83be-bd1339eb013e.png)

**URL / Environment where this happened**
https://dale.ushahidi.io/posts/138

**Desktop Hardware Details (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version 68.0.3440.106

**Comment by crcommons** [comment]
@jrtricafort I just updated this issue now that we've clarified it was happening because of UX confusion. Tagging you to prioritize/triage.

**Comment by jrtricafort** [comment]
@crcommons @rowasc This isn't high priority unless reported by one of our end users. P3 - won't fix.
