### ISSUE TITLE
Partner Not able to respond to messages from AGYW 

### ISSUE THREAD

**Issue by Nthiga** [ushahidi/platform#3277]
@rowasc @jrtricafort One of the DREAMS Partners has reported not being able to respond to messages on platform. The deployment url is amurt.ushahidi.io 

I have recreated the issue and still get the same view on my end

Expected Beviour: When partner clicks on message on platform they are able to see the respond "send new message" Tab through which they can initiate conversation with the AGYW 

Current Scenario: "Send New Message tab" unaccessible See Image below 

![image](https://user-images.githubusercontent.com/26707984/45090110-10dbbb00-b117-11e8-9850-3414f3fa1d8a.png)

**Comment by jrtricafort** [comment]
Update from @rowasc : we have a fix and pushed it to QA for testing. @Nthiga we'll update you when it is available for you to test and for the user.

**Comment by rowasc** [comment]
messages from before the fix went live are not available for contacting the user… at least until we figure out a retroactive way to do it. New messages can be tested/used to contact users now in production

**Comment by jrtricafort** [comment]
@rowasc So does that mean messages from the past week + messages from prior to the Lumen migration are unable to respond to? At least until we figure out the retroactive fix, that is.

**Comment by rowasc** [comment]
Yes @jrtricafort .

**Comment by rowasc** [comment]
OK we're deploying a migration to fix this now. It'll probably take a few hours to run but this should be fixed by the time @Nthiga starts working tomorrow

**Comment by rowasc** [comment]
<img width="598" alt="screen shot 2018-09-06 at 9 47 29 am" src="https://user-images.githubusercontent.com/2434401/45158540-a54b2980-b1ba-11e8-967c-e30bef05a8bd.png">
The retroactive fix was deployed last night.

**Comment by rowasc** [comment]
Monica and I met today, the messages are being sent and received. Closing
