### ISSUE TITLE
Nav and Header default sizing, pushes useful information and features below the fold

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#328]
<img width="1280" alt="screen shot 2015-08-13 at 9 05 43 am" src="https://cloud.githubusercontent.com/assets/1618793/9254876/c068e27c-419a-11e5-8543-c89c30a72fa4.png">

**Comment by rjmackay** [comment]
- We're missing a transition at the moment which is supposed to shrink the header as you scroll, and also shrink it on non-home views.
I'm going to close this out for now. The current state is already better than when this was logged and I'm sure further issue will come up in testing
