### ISSUE TITLE
redirect to forbidden on login after create

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3281]
**Describe the bug**
When I create a new deployment and after I am taken through the waiting area, I see my deployment and the login modal. When I login, I am redirected to the forbidden page, rather than the map view. Also, when I upgrade my plan and then am taken back to my deployment, it routes me to the forbidden page.

**Where was the bug observed**
https://carolyn.sad-charlie.ush.zone/

**To Reproduce**
1. Create a new deployment
2. Go through the new deployment instructions 
3. When the login modal appears, login
4. you will be redirected to /forbidden

**Expected behavior**
After login, I should be taken to the map view

**URL / Environment where this happened**
https://carolyn.sad-charlie.ush.zone/

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 67.0.3396.99

Aha! Link: https://ushahiditeam.aha.io/features/PROD-289

**Comment by crcommons** [comment]
@jrtricafort New bug I found today. Tagging you for triage.

**Comment by rowasc** [comment]
Oh, I've seen this for a while now (meaning, it's not a regression). https://github.com/ushahidi/platform/issues/2306 it's related to this one. 

I'd say it's a P2 since there's a workaround but I agree that it's super confusing for people

**Comment by tuxpiper** [comment]
Superseded by #4549
