### ISSUE TITLE
Crowdsourced posts view does not appear when you reload /activity

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3283]
**Describe the bug**
Crowdsourced posts view does not appear when you reload /activity
**Where was the bug observed**
rominacsvsms.ushahidi.io

**To Reproduce**
1. Go to a sad-charlie or production environment
2. Login as admin
3. Click on 'activity'
4. Check that you see the crowdsourced stats view
5. Reload the page. You will no longer see the crowdsourced stats view

**Expected behavior**
5. Reload the page. You should see the crowdsourced stats view

**Is there a workaround? What is it.**
Click on activity instead of reloading the /activity page

**Desktop Hardware Details (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 68

Aha! Link: https://ushahiditeam.aha.io/features/PROD-288

**Comment by rowasc** [comment]
@crcommons can you take a look ?

**Comment by rowasc** [comment]
(Added 1 point estimate, if you disagree please change it :D )

**Comment by crcommons** [comment]
@rowasc Oddly this is failing in production, but I can't reproduce locally. Will investigate further.

**Comment by rowasc** [comment]
Ahhhh. Maybe an nginx thing. 
@tuxpiper could you take a look when you get a chance?

**Comment by tuxpiper** [comment]
I have reproduced it, but I don't see anything wrong with the requests or the responses going through nginx . I did notice that after reloading , a lot less requests to the stats endpoints are generated by the client.

It also doesn't load correctly if I open the /activity route of the client in a new tab. Maybe some sort of race condition in the client?

**Comment by rowasc** [comment]
mmm. Maybe. I'll try to reproduce it locally. Thank you for taking a look
