### ISSUE TITLE
Demo banner covering plans link on settings page

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#3290]
**Describe the bug**

**Where was the bug observed**
https://testfinal1.steve-buscemi.ush.zone/views/map

**To Reproduce**
1. Go to Settings page on a demo deployment
2. The Plans link on the settings page is behind the demo banner and can't be clicked

**Screenshots**
<img width="1680" alt="screen shot 2018-09-13 at 13 19 10" src="https://user-images.githubusercontent.com/2694405/45504671-80c1f500-b758-11e8-99a9-b8431e60252c.png">

**Comment by Angamanga** [comment]
@rowasc @willdoran Added a fix for this to the branch `3199-add-freeze-state-and-end-state`

**Comment by rowasc** [comment]
assigned to Will to confirm it worked :D thanks
