### ISSUE TITLE
Export Feature Not Working: amurt.ushahidi.io 

### ISSUE THREAD

**Issue by Nthiga** [ushahidi/platform#3294]
**Describe the bug**
Export feature not working; cant download any data

**Where was the bug observed**
amurt.ushahidi.io 

**To Reproduce**
1. Go to 'amurt.ushahidi.io'
2. Log in as '...' (Admin)
3. Click on 'settings'
4. Scroll down to 'Export'
5. See error

**Expected behavior**
Download CSV 

**Is there a workaround? What is it.**
Ensure that CSV can be downloaded

**Screenshots**
![image](https://user-images.githubusercontent.com/26707984/45620675-56d53f00-ba86-11e8-916f-0e808b8fb6c7.png)

**URL / Environment where this happened**
[e.g http://qa.ushahidi.io/post/create]

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**

**Desktop Hardware Details (please complete the following information):**

**Smartphone Hardware Details (please complete the following information):**

**Additional context**

**Comment by rowasc** [comment]
@dexwakhu @Nthiga this should be working now. 
Thanks to @kinstelli @tuxpiper for jumping in to help here.

@kinstelli can you tag David for review when you push the .env fix ?

**Comment by rowasc** [comment]
@kinstelli @tuxpiper could you confirm this can be closed (was the .ENV change enough or did we need something else) ?

**Comment by kinstelli** [comment]
@rowasc - Thanks for following up. Yeah, @tuxpiper pushed a definitive fix to the ansible scripts, so I believe this is complete.

**Comment by rowasc** [comment]
Alright thanks @kinstelli ! Closing
