### ISSUE TITLE
Retry not working when a job fails in the export job queue

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3295]
**Describe the bug**
When a job fails in the export jobs queue, it should retry the export chunk the number of times specified (3 in this scenario).
RIght now if an export chunk fails, it just fails and does not retry.

**Where was the bug observed**
amurt.ushahidi.io
rominacsvsms.ushahidi.io
Notes: 
- I have not seen this in sad-charlie, but it might happen if there's a failed chunk. 
- Note that this cannot be reproduced in production unless the timeout for exports is set lower than what we have it now (ie 8s). This should be reproduced locally or in QA to verify if it is some config being set incorrectly or a problem in the code.

**To Reproduce**
1. Go to a deployment and start an export. Important: make sure the chunks will be considered FAILED by lowering the timeout in the lumen_export_queues repo to 1s. 
2. Check that when a chunk fails, it won't be retried 

Internal slack thread: https://ushahidi.slack.com/archives/C03UU507R/p1537183988000100
Original issue for context on what was happening https://github.com/ushahidi/platform/issues/3294

Aha! Link: https://ushahiditeam.aha.io/features/PROD-287

**Comment by rjmackay** [comment]
If this proves hard to repro, would it be better to test a properly queued version of CSV exports (that works with multisite this time)?

**Comment by rowasc** [comment]
Do you mean migrating the lumen_queues codebase to the platform codebase?

**Comment by rowasc** [comment]
Ah, I found this old ticket that we discussed doing when migrating the exports to the platform repo. Sending it in case you want to check it out after multisite is done
