### ISSUE TITLE
Edit collection UX spacing bug

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#330]
In edit collection "This collection is featured" is misaligned and set.delete_collection should not appear

<img width="588" alt="screen shot 2015-08-13 at 9 16 59 am" src="https://cloud.githubusercontent.com/assets/1618793/9255122/2519bb82-419c-11e5-93ea-f300e8076f61.png">

**Comment by jshorland** [comment]
This was fixed a long time ago. Closing.
