### ISSUE TITLE
Support for HumanitarianID OpenID Connect

### ISSUE THREAD

**Issue by poVoq** [ushahidi/platform#3300]
**Which user group(s) are the primary audience for this feature/enhancement.**
Humanitarian Aid Workers
Specify key workflows (e.g. crisis, elections): crisis, emergencies
Specify key use cases (program/data workers, incident management, advocacy/storytelling): field reporting, data-sharing

**Is your feature request related to a problem? Please describe.**
One less login to deal with & easier to convince others to join the platform.

**Describe the solution you'd like**
Support for external logins via OpenID Connect. This can be google/twitter/facebook, but especially https://humanitarian.id
See: https://github.com/UN-OCHA/hid_api/wiki/Integrating-with-HID-via-OAuth

Should be fairly easy with NodeJS Passport or PhP Hybridauth3 to implement (there is an implementation for Hybridauth2)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-285

**Comment by rowasc** [comment]
This is not a feature we have at the moment. Keeping it open, to be considered in future iterations.
