### ISSUE TITLE
Clean up outdated libraries in pattern-libraries

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3301]
There are a lot of outdated libraries in the pattern libraries for 
- Platform
- Tenfour
- Dotcom

We need to update or replace the ones that are outdated, especially the ones with vulnerability-warnings and the ones that stops the build (mainly Tenfour and Dotcom).

**Comment by Angamanga** [comment]
Update on this issue:
- Tenfour is done
- Dotcom is done but not merged yet because I want to discuss it with Seth  
- Working with Platform right now

**Comment by rowasc** [comment]
@Angamanga can you add an update for this issue when you're back? Thanks

**Comment by Angamanga** [comment]
@rowasc Tenfour and dotcom is done, pattern-library for platform-client is still not done. Will try to finish this week so we can close this.
