### ISSUE TITLE
Settings => General page - not all fields show a validation error when they are invalid

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3304]
**Describe the bug**
Some fields like Contact Email Address and default lat/lon values do not show anything to the user if they have invalid values. This is confusing and prevents the user from saving the page until they solve the issue, but they don't have feedback about what's wrong.

**Where was the bug observed**
- Development branch (locally)
- Community support channel where a user reported that they cannot save the settings 

**To Reproduce**
1. Go to Settings -> General
2. In the Contact Email Address field, write an invalid email like `hello` 
3. You won't see any error messages and the save button will be disabled.

**Expected behavior**

1. Go to Settings -> General
2. In the Contact Email Address field, write an invalid email like `hello` 
3. You see a validation error message for the field
4. The save button is disabled until the error is fixed

**Is there a workaround? What is it.**
Just fixing the errors, but since the user doesn't know the validation rules this might be confusing/tricky to do.

**Screenshots**
<img width="826" alt="screen shot 2018-09-27 at 2 57 33 pm" src="https://user-images.githubusercontent.com/2434401/46164952-b5a86e80-c265-11e8-91af-4139f2b3ede4.png">

# Implementation Notes
- This is part of this repo : https://github.com/ushahidi/platform-client

## Want to work on this issue?🙋 
Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

**Comment by Jenniline** [comment]
@rowasc @Angamanga  I will like to work on this, can I?

**Comment by Angamanga** [comment]
@Jenniline Absolutely, go ahead and please reach out if you need guidance! 🎉

**Comment by Jenniline** [comment]
ok. I am not certain about the branch where the issue is on and where to find the platform Comrades for this issue can I have the directions to this, please?

**Comment by Angamanga** [comment]
@Jenniline Ah, i see it's confusing, its just an example-screenshot from a deployment that is called platform Comrades. You find this view in settings->general :)

**Comment by himil-vasava** [comment]
Can I work on this issue?

**Comment by Angamanga** [comment]
@himil-vasava Yes, please go ahead! Ping me if you run into any problems or need guidance! 👍 🎉

**Comment by himil-vasava** [comment]
@Angamanga Is it okay now ?
![Screenshot from 2020-02-06 01-41-06](https://user-images.githubusercontent.com/55590415/73879279-2dd36b00-4882-11ea-87f8-e7131af13704.png)

**Comment by Angamanga** [comment]
@obadha Could you QA in Steve Buscemi?
Testing-checklist: 
- Go to settings->General
- Type in an email-address that has the wrong format in the "Contact email address"-field
- [ ] There should be an error-label saying "This email address is invalid"
- Type a correct email-address
- [ ] The error-label should disappear

**Comment by Obadha2** [comment]
QA'd, passes. 👍
