### ISSUE TITLE
Unable to use iOS application to login to backend server

### ISSUE THREAD

**Issue by simmytruong** [ushahidi/platform#3306]
Hi,

I am trying to make my own Docker image and I follow up the instruction at:
http://ushahidi.s3.amazonaws.com/downloads/community_docs/Ushahidi_Platform_v3_Manual.pdf
and refer the https://github.com/ushahidi/platform-release/releases/download/v3.12.3/ushahidi-platform-release-v3.12.3.tar.gz

Rigt now, I can bring up my ushahidi_client and ushahidi_platform to work in the same docker container since I can use web browser to login to my site without any problem.

But there is a problem when I use my iPhone to install ushahidi application to add the backend url, and I encounter the issue:
![issue](https://user-images.githubusercontent.com/35060602/46254686-24333980-c4bd-11e8-8774-c92771ed5000.png)

This is my setup:
- client root dir: /var/www/html
- backend root dir: /var/www/html/platform/httpdocs
- I am using apache to host native codes
- I put the config.json under /var/www/html/platform/httpdocs
- I can use a browser like chrome to go to http://myushahidi.domain.com without issue
- But my backend is placing at http://myushahidi.domain.com/platform, if I use this backend url for my iphone, it will display the error as the image

Please help to have an advice

Aha! Link: https://ushahiditeam.aha.io/features/PROD-284

**Comment by rowasc** [comment]
Hi, sorry I was trying to check-in on this issue internally and didn't get back to you yesterday (which is why I self-assigned it) 

@dalezak mentioned this looks like a CORS issue related to a native http plugin we were using , and that the new mobile app version should resolve this once it goes live 
@dalezak could you ping @simmytruong to re-test when the release is out?

**Comment by simmytruong** [comment]
hi @rowasc Thanks for your update. I am exciting if we can have a release to fix this CORS issue on both iOS and Android.

Thanks,

**Comment by simmytruong** [comment]
![issue](https://user-images.githubusercontent.com/35060602/46518773-2bcd5680-c8a0-11e8-85da-0a82dae4e026.png)
FYI, it is really a CORS issue. Please help to fix soon. Thanks

**Comment by rowasc** [comment]
Thanks @simmytruong for your patience.
@dalezak just updated the app. 
For android it should be already available, but for iOS it depends on their approval process, so he will let us know once it's approved and available in the iOS app store.

**Comment by simmytruong** [comment]
great thanks @rowasc and @dalezak

**Comment by simmytruong** [comment]
hi, I have just upgrade the iOS application to the latest version since last minutes ago.

When I added my site, it displays:

"Problem logging in - An unknown error has occurred" Seems that it is not a CORS issue any more. But no information returns. May you please give an advice?

Thanks,

**Comment by rowasc** [comment]
@simmytruong apologies for the delay in answering. 
Can you tell us what you see in the application/logs folder, specifically in the file for today/when the error happened ? Any errors there that can be useful in debugging this?

**Comment by simmytruong** [comment]
hi @rowasc 

Thanks for your update. I will send you the logs soon when I bring up my docker up again. 
For easy troubleshoot, I would like you to reproduce my case, it is pretty simple by:
- Download https://github.com/ushahidi/platform-release/archive/v4.0.0.tar.gz
- Unzip and then you go the extract folder, and type docker-compose up.
- This will bring up dockers with nginx http webserver.
- After that, you can use your iOS application to point to the server and will see the error.

**Comment by simmytruong** [comment]
hi @rowasc 

When I check the nginx logs, I can see this message:
"XXX.XXX.XXX.XXX - - [09/Oct/2018:03:13:12 +0000] "GET /config.json HTTP/1.1" 200 290 "-" "Ushahidi/1.12 (iPhone; iOS 12.0; Scale/3.00)""

that means the iOS can get the config.json file. But somehow, it still displays the issue as I mentioned above: "Problem logging in - An unknown error has occurred"

And when I curl to my site:

curl -vvv XXX.XXX.XXX.XXX/config.json
*   Trying XXX.XXX.XXX.XXX...
* Connected to XXX.XXX.XXX.XXX (XXX.XXX.XXX.XXX) port 80 (#0)
> GET /config.json HTTP/1.1
> Host: XXX.XXX.XXX.XXX
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.10.3
< Date: Tue, 09 Oct 2018 03:15:35 GMT
< Content-Type: application/json
< Content-Length: 290
< Last-Modified: Mon, 08 Oct 2018 23:21:12 GMT
< Connection: keep-alive
< ETag: "5bbbe668-122"
< X-XSS-Protection: 1; mode=block
< Accept-Ranges: bytes
< 
{
"client_id": "ushahidiui",
"client_secret": "35e7f0bca957836d05ca0492211b0ac707671261",
"backend_url": "/",
"google_analytics_id": "",
"intercom_app_id": "",
"mapbox_api_key": "pk.eyJ1IjoidXNoYWhpZGkiLCJhIjoiY2lxaXRrbmF5MDdxNmZubmUyN2p6bms5biJ9.o7pmKDIN1EtwMBp1VIzITQ",
"raven_url": ""
}
* Connection #0 to host ttriet.ddns.net left intact

**Comment by tuxpiper** [comment]
Verified that it works, *as long as* the `SITE_URL` environment variable is appropriately set, as is documented now.
