### ISSUE TITLE
Runtime problems with MySQL 8.0

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3308]
**Describe the bug**
There seem to be problems running the API with MySQL 8.0 as the backend

**Where was the bug observed**
We received a report in community chat with this error example (values edited)::

```
FUNCTION db_astil.GeomFromText does not exist [ INSERT INTO `post_point` (`value`, `form_attribute_id`, `post_id`, `created`) VALUES (GeomFromText('POINT(xxx yyy)'), a, b, ccc) ]
```

Another member of community chat confirmed the problem on their side

**To Reproduce**

TBD, but apparently the geometry functions have something to do with this.

**Expected behavior**
Fatal errors shouldn't happen

**Is there a workaround? What is it.**
No. The only way around it is to use a  supported mysql version (>5.6 .. <8)

**Screenshots**

**URL / Environment where this happened**
Community members own installations

## Dev notes
https://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html

Per MySQL docs, they deprecated it around 5.7, planned to remove it and did the removal in 8.0

https://dev.mysql.com/doc/refman/8.0/en/gis-wkt-functions.html#function_st-geomcollfromtext this doc looks like the alternative in 8.0 is ST_GeomFromText
It'd be useful to check and test the change so we can support 8.0 in the future

https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html this are the notes where they document removing the Geom* functions in favor of ST_Geom

Aha! Link: https://ushahiditeam.aha.io/features/PROD-283

**Comment by rowasc** [comment]
https://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html

Per MySQL docs, they planned to deprecate this and apparently did so.

https://dev.mysql.com/doc/refman/8.0/en/gis-wkt-functions.html#function_st-geomcollfromtext this doc looks like the alternative in 8.0 is ST_GeomFromText
It'd be useful to check  and test the change so we can support 8.0 in the future

**Comment by bimbolabuari** [comment]
@rowasc @Angamanga, I would love to work on this

**Comment by tuxpiper** [comment]
I believe #4432 fixed this
