### ISSUE TITLE
ISOOKO Test Deployments: How can users in Kigali Rwanda send feedback on survey questions/topics to an Ushahidi Deployment

### ISSUE THREAD

**Issue by Nthiga** [ushahidi/platform#3313]
## Overview
SMS/USSD Integration for Users in Rwanda - ISOOKO workshop test (Would love to discuss this further to assess suitability and viability bearing in mind ongoing work around Ushahidi - BRCK integration). This would also be useful in engaging Youth groups Between October 15-26th. 

Hold Ups
- There are some assumptions on requirements from a  user perspective: haven't met target groups and Aegis hasn't been exactly useful
- Would this be worth pursuing as we look at BRCK-Ushahidi integration in the long run? 

## Who is it for? Who are the users?
ISOOKO Consortium team (secondary users), Youth in Kigali (Primary users) 

## What privacy impacts does it have?
- Does it change the personal data we collect?
- Does it expose data that was previously private?
- Does it send data to new services? or change how we process it?
- If privacy impacts are high risk, consider completing an impact assessment per GDPR (https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/accountability-and-governance/data-protection-impact-assessments/)

## Requirements

- Need an SMS tool such as Frontline 
- Need an aggregator such as AfricasTalking 

- USSD Integration

- Two test deployments already created: https://isookoyouth.ushahidi.io/views/map and https://isooko.ushahidi.io/views/map for general Demo

### Who will this be deployed to?
For a start to Youth groups in Kigali and Aegis Trust Team 

### What documentation needs to change?
Could discuss this further 

### Who will test this?
Monica 
### Where will this be deployed and tested?
Kigali Rwanda 

## Deployment
https://isookoyouth.ushahidi.io/views/map and https://isooko.ushahidi.io/views/map 
*Does this deploy new services?*
Pilot Ushahidi in Kigali
*Do the new services have health checks?*
*Can this be feature flagged and deployed disabled?*

**Comment by rowasc** [comment]
checked with @Nthiga  : The ticket is no longer valid. Closing
