### ISSUE TITLE
Saved search modal title does not support html character codes.

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3315]
**Describe the bug**
I get  `Actualizar B&uacute;squeda` instead of `Actualizar Búsqueda` 

<img width="464" alt="screen shot 2018-10-05 at 6 19 47 pm" src="https://user-images.githubusercontent.com/2434401/46560769-51bc2080-c8cb-11e8-925e-6462f0294902.png">

**Where was the bug observed**
Production environment.

**To Reproduce**
0. Have Spanish selected as the language in your deployment
1. Go to the filters dropdown, select a saved search
2. Change something in the saved search (ie add a filter)
3. Click on "ACTUALIZAR BÚSQUEDA" (yellow button) 
4. You will see `Actualizar B&uacute;squeda` as the modal title 
**Expected behavior**
4. You should see  `Actualizar Búsqueda`  as the modal title 

## Want to work on this issue?🙋 
Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Aha! Link: https://ushahiditeam.aha.io/features/PROD-281

**Comment by dlarner3194** [comment]
I can take this one

**Comment by rowasc** [comment]
Thanks @dlarner3194 , let us know if you need any assistance

**Comment by rowasc** [comment]
@dlarner3194 hey, how is it going? Do you need some support here? 
please feel free to reach out in this issue or https://gitter.im/ushahidi/Community
Thanks!
cc @Angamanga

**Comment by Jenniline** [comment]
@rowasc I will like to work on this. Can I?

**Comment by NidhiKJha** [comment]
@Angamanga 
From what I have researched online, this is an issue of utf-8 support that needs to be enabled in php. I cannot locate the correct files that host these settings. Please point me to them.

**Comment by tuxpiper** [comment]
I believe the issue doesn't have its root cause in the backend code or setup.

It looks like it's a matter of how html character entities (i.e. "\&uacute;" -> "ú" or "\&amp;" -> "&" ) present in translation files are rendered by angular .

**Comment by emalindahk** [comment]
Hi, I'm Emmah I would like to work on this for my outreachy contribution

**Comment by Angamanga** [comment]
@emalindahk Please go ahead :)

**Comment by emalindahk** [comment]
@Angamanga & @rowasc  I have worked on the issue, kindly review it [](https://github.com/ushahidi/platform-client/pull/1590) 

![actualizar](https://user-images.githubusercontent.com/12936055/96555890-fcd88080-12c0-11eb-9a10-8abaf1ef0322.png)

![Screenshot 2020-10-20 at 10 41 13](https://user-images.githubusercontent.com/12936055/96555914-05c95200-12c1-11eb-89bf-0658feebfbc5.png)

**Comment by emalindahk** [comment]
The issue was `translate`  missing on `<span class="label" translate>`

**Comment by rowasc** [comment]
@emalindahk oh this is great thank you!   Make sure the pull request has a link to the ticket. Thanks

**Comment by Angamanga** [comment]
@tuxpiper Fixed
