### ISSUE TITLE
Metrics Pull - "Posts" and "Monthly Deployment Creation" for Q2 and Q3 2018

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3318]
Data request. Need to fill out this metrics doc again. Specifically the Posts tab and the Monthly Deployment creation tabs for Q2 and Q3 2018.

https://docs.google.com/spreadsheets/u/1/d/1mehBmLZOmwb0zpIt9EF1dIHtPSEH-GH1vmTghj8O8O0/edit

Deadline is October 12.

Sync'd with @rowasc We think we can do this without heavy excel work required. Romina will take a look and will let @jrtricafort know if we need any excel support.

**Comment by rowasc** [comment]
Closing this was delivered
