### ISSUE TITLE
More than one photo per post - Design

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform#3319]
## Want to work on this issue?🙋 
Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

## Description
Linked to issue #2003 

As a user I can currently only load one photo to a post when replying to a Ushahidi survey. I'd like to be able to use the single 'Add images' button to upload several photos (maximum 10 per form field) on one post and be ale to scroll across them like one can on instagram.

What the section looks like now:

![screen shot 2018-08-20 at 11 11 06](https://user-images.githubusercontent.com/11681324/46630265-a239b500-cb3b-11e8-84f8-eb3e8acdefa1.png)

![screen shot 2018-08-20 at 11 11 31](https://user-images.githubusercontent.com/11681324/46630306-c5646480-cb3b-11e8-981d-d973427ee30b.png)

Reference images from whatsapp:
![screenshot_20180817-170824](https://user-images.githubusercontent.com/11681324/46630675-c649c600-cb3c-11e8-8d37-c5ecda921198.png)

Reference image from photos app
![intro](https://user-images.githubusercontent.com/11681324/46630669-c0ec7b80-cb3c-11e8-8821-77c25b7fb5a5.jpg)

*Hints 💡 *
1. create a survey that has an image-field to be able to debug and explore the code (go to settings->survey->create survey-> add field-> select image
2. add a few posts for connected to this survey 
After that you can explore the code to figure out what files are connected to this issue:
3. the files that are connected to surveys are in this folder: https://github.com/ushahidi/platform-client/tree/develop/app/settings/surveys
4. the files that are connected to displaying posts are here: https://github.com/ushahidi/platform-client/tree/develop/app/main/posts/views
5. the files that are connected to editing/creating posts are here: https://github.com/ushahidi/platform-client/tree/develop/app/main/posts/modify
6. the file that are connected to loading and displaying images are here: https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/detail/post-media-value.directive.js

**Comment by karunagoyalk** [comment]
@Erioldoesdesign I would like to go ahead with this issue!

**Comment by Erioldoesdesign** [comment]
@karunagoyalk Great news! Have you got an instance of Ushahidi Platform working locally? I can support with the Front End QA and making sure your implementation looks and functions how we want it to but people like @Angamanga @tuxpiper and @rowasc can help you get set up if you haven't already.

Also check out our Readme and docs to get set up :)
https://github.com/ushahidi/platform/blob/develop/README.md
https://ushahidi.gitbook.io/ushahidi-oss-home/

**Comment by Jenniline** [comment]
@Erioldoesdesign I will like to work on this. Just need more details

**Comment by tuxpiper** [comment]
If I recall correctly, the backend API is already capable, at least on paper, to store several images per post.

So this is an issue that needs mostly work in the frontend . The post viewing, creation and edition views need to be adjusted to be able to handle several images.

Hope this information helps.

**Comment by Erioldoesdesign** [comment]
@karunagoyalk and @Jenniline Please see tuxpipers comment above on how to go about tackling this issue :) If you need anything else, we have a community gitter and ways you can chat with the team outside of Github comments.

**Comment by karunagoyalk** [comment]
@Jenniline hey! As I am already working on this issue, Can you please look some other issue?

**Comment by tuxpiper** [comment]
@karunagoyalk unfortunately we only have so many issues to offer for outreachy applicants. But in any case, I think there is no reason why @Jenniline's work should interfere with your work .

At the same time, we understand that you are doing this as part of a competitive internship application.

We will make sure not to publicize your progress or findings. If you would like a private Q&A with a mentor we can arrange that (just request it, being clear that you'd want the conversation be private). 

You can still contribute to the public conversation when you prefer. Naturally from our side, public information and updates about the task will be provided to all interested parties just the same.

**Comment by karunagoyalk** [comment]
@tuxpiper Sorry about that, As I am new to open source ,was not having much idea ,how this works!

**Comment by tuxpiper** [comment]
No worries @karunagoyalk ! Honestly, we are also new with Outreachy . We'll figure things out , anything you need don't hesitate to reach out! :+1:

**Comment by karunagoyalk** [comment]
@Erioldoesdesign Can you please help me? Like which file to proceed for this implementation?

**Comment by karunagoyalk** [comment]
@Erioldoesdesign Can you please help me? Like which file to proceed for this implementation?

**Comment by Erioldoesdesign** [comment]
@karunagoyalk Do you mean a design file to work from?

**Comment by karunagoyalk** [comment]
@Erioldoesdesign Yes please!

**Comment by karunagoyalk** [comment]
@Erioldoesdesign please tell me about the design file?

**Comment by Erioldoesdesign** [comment]
@karunagoyalk There is not a design file for this. What I would like you to do is combine the style of whatsapp with how it is currently on the Ushahidi platform. Try to use the images provided in the issue before you have a design made for you by us. It is important for Front-end coders to work with examples and not always with 'pixel-perfect' designs.

If you struggle, I can support but please, have a go at the issue before design spends time creating something for you.

**Comment by karunagoyalk** [comment]
@Erioldoesdesign hey! I actually want to ask, in which code file I have to do changes for this issue, like there are so many code files and folders for this application!

**Comment by Erioldoesdesign** [comment]
Ah I see! Best person to ask for that is @Angamanga

**Comment by karunagoyalk** [comment]
@Angamanga hey! Can you please help me? I want to know about the file in which I have to do the changes for this issue

**Comment by karunagoyalk** [comment]
@Angamanga @tuxpiper please help me!

**Comment by Angamanga** [comment]
Hi there @karunagoyalk. I suggest you
1. create a survey that has an image-field to be able to debug and explore the code (go to settings->survey->create survey-> add field-> select image
2. add a few posts for connected to this survey 
After that you can explore the code to figure out what files are connected to this issue:
3. the files that are connected to surveys are in this folder: https://github.com/ushahidi/platform-client/tree/develop/app/settings/surveys
4. the files that are connected to displaying posts are here: https://github.com/ushahidi/platform-client/tree/develop/app/main/posts/views
5. the files that are connected to editing/creating posts are here: https://github.com/ushahidi/platform-client/tree/develop/app/main/posts/modify
6. the file that are connected to loading and displaying images are here: https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/detail/post-media-value.directive.js

Good luck and reach out if you get stuck!

**Comment by rowasc** [comment]
Hey folks. Checking in on this issue. Did you start on it @karunagoyalk or should we keep it open for other folks to contribute? Let us know if you need assistance. Thanks! 👍

**Comment by AishaSaman** [comment]
Hello I am an outreachy internship applicant and want to work on this issue. 
Does this issue is about design part only or also includes storing multiple images at the backend also?

**Comment by Angamanga** [comment]
@AishaSaman I assigned you to this issue: https://github.com/ushahidi/platform/issues/1889
