### ISSUE TITLE
Resize the youtube and vimeo logos so they aren't blurry in survey creation

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform#3320]
As a user, when responding to a survey that has a field available for video URL, I see a YouTube logo and Vimeo logo that are blurred. I want to see non-blurry logos for each of these.

Suggest either resizing/locating larger logos and replacing existing files
or
Editing current CSS styling to fit the natural image size
or 
Substitute with Font Awesome Icons.

![Screen Shot 2018-10-08 at 22.00.58.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/495b364a-3708-4e62-b5ca-987f86cc4b93)

QA on multiple devices/browsers please

**Comment by sky1911** [comment]
Why don't you use Font Awesome icons for this?

**Comment by Erioldoesdesign** [comment]
@sky1911 Oh! great suggestion. 100% in favour of substituting for font awesome icons but would need to be QA'd on lots of different devices for my peace of mind :)

**Comment by rowasc** [comment]
@Angamanga  I see font-awesome is already added in the PL but it's not being applied correctly when I use the FA classes, probably some bug?

(following up from our slack convo, see Skky1911's and Eriol's comment above)

**Comment by sky1911** [comment]
@rowasc maybe you're using the classes from FA 5.0 (newest version) and the FA embedded on the website is an older version.

**Comment by rowasc** [comment]
@actuallyakash very likely. If you try it and figure it out let us know :)

**Comment by Angamanga** [comment]
@rowasc @actuallyakash Sorry I didn't follow up on this. The font-awesome font files are left over from a while ago. We no longer use it but its worth a try. (Otherwise we should really remove it, but will watch this and see how it goes first).

**Comment by SolKuczala** [comment]
Can I ask where is the survey on 'platform'?

**Comment by Erioldoesdesign** [comment]
Hi @actuallyakash did you end up looking at this issue? It looks like @SolKuczala is interested in picking it up :) No worries if you didn't look at it.

@SolKuczala you can find the youtube logo if a survey has enabled a submission of a video link. If you click the (+) yellow circle with a plus in the top left corner of the map you can 'add to a survey'

If you use my test deployment here: https://lgbthistoryswuk.ushahidi.io/views/map

You may need to sign up for an account with that deployment

Then click the (+) circle with a plus

Choose 'LGBTQ Memories' from the survey list

Then scroll down and you should see the logos

Here's a direct link that may work to send you to that specific page: https://lgbthistoryswuk.ushahidi.io/posts/create/2

**Comment by SolKuczala** [comment]
Great, I'll look into it,👍

**Comment by AmalHanif** [comment]
I will Edit current CSS styling to fit the natural image size. kindly review.

**Comment by Erioldoesdesign** [comment]
@SolKuczala Did you look into this issue? If you found a solution then I want to notify other contributors that the issue is taken :)

**Comment by AmalHanif** [comment]
If we edited class **wordmark-replace** , 39x17 instead of 50x20 . this fixed the blurred logos. But its also effects on other places where we use the _wordmark_. Are this change is good to change?

**Comment by Erioldoesdesign** [comment]
@AmalHanif let's ask @Angamanga she's our front-end expert :) 

Ideally we wouldn't have a styling change affect other places it's used and we'd look at extending this style so we can fix this particular instance.

**Comment by SolKuczala** [comment]
If amalhanif has the solution  already, go ahead. I had a problem trying to find the  source code  for that page and maybe it'll take me little longer.

**Comment by Angamanga** [comment]
@AmalHanif Hi there! Thank you for investigating this issue! I would try to find other logos in larger format or svg as a start, instead of changing the css for this. What happens if you remove the class all together? Does it affect the size at all?

**Comment by AmalHanif** [comment]
we need to display inline from this class so we can't remove the class.

**Comment by Angamanga** [comment]
@AmalHanif Ah, I see, changing the css is straight forward but means you have to work in our pattern library (which of course you are welcome to do!!). If you are interested in that, please start looking here: https://docs.ushahidi.com/platform-developer-documentation/changing-ui-styles-introduction-to-the-pattern-library. Reach out if you need any guidance, I will be watching this today since I know its the last day to submit Outreachy-applications :)

**Comment by NidhiKJha** [comment]
@Angamanga @Erioldoesdesign I have submitted a Pull request that solves this issue. Please review it and give me feedback. Thank You!
