### ISSUE TITLE
Disable the text link 'Bulk Actions' when there are no posts in a list

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform#3321]
As a user I don't want to have unnecessary call to action buttons when there is no content that will be affected by the action/function.

When there are no posts in a deployment the 'Bulk Actions' text link should not be clickable and should be in a 'disabled' state.

The 'Bulk Actions' link should still be viewable but clearly not able to be clicked to expand the bulk actions 'menu':

![Screen Shot 2018-02-17 at 22.35.59.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/020945cb-dcf0-41de-978d-fe48a52f4715)

**Comment by Erioldoesdesign** [comment]
@rowasc Do you think it's too complex?

**Comment by rowasc** [comment]
@Erioldoesdesign this looks like a good first-time-contributor issue

Note: For anyone checking this out/deciding if you want to pick it up:
I think it can be toggled using the `$scope.totalItems > 0 ` as the condition for the link to be disabled/enabled. It's in the post-view-data.html and post-view-data.directive.js files

**Comment by mikestratton** [comment]
I will work on this if no one else has picked it up yet.

**Comment by sinneruy** [comment]
Starting on this one, if no one is working on it yet.

**Comment by rowasc** [comment]
This will go to QA once sad-charlie is free . 
Assigning to myself for release
