### ISSUE TITLE
[Demo accounts] Add post button on data view is covered by "Upgrade now" banner

### ISSUE THREAD

**Issue by sinneruy** [ushahidi/platform#3323]
# Problem
Add post button on data view is covered by "Upgrade now" banner.

# Steps to reproduce the behavior:
1. Go to https://hacktoberfesttest.ushahidi.io/views/data
2. Log in as any role that can add posts.
3. Add post button is below the "upgrade now" banner.

 - OS:  Windows 10 pro
 - Browser FF dev edition 63.0b11 (64-bit) / Chrome 69.0.3497.100

# Workaround
- Add from `map` view

**Comment by rowasc** [comment]
@Erioldoesdesign @justinscherer what should we do about the add post button here? 
<img width="1441" alt="screen shot 2018-10-09 at 4 34 52 pm" src="https://user-images.githubusercontent.com/2434401/46693812-47f32f80-cbe1-11e8-8c34-0d61e5e51766.png">

Thanks @sinneruy for the bug report :)

**Comment by rowasc** [comment]
Pinging @sethburtonhall since he might know what to do here

**Comment by justinscherer** [comment]
Nice catch. Shift the button 24px above the banner. Should solve it.

**Comment by sethburtonhall** [comment]
@justinscherer we will have to accommodate for various screen sizes which is fine, but there may be a need for logic to change display based on whether demo bar is true or false

**Comment by Erioldoesdesign** [comment]
Is there a z-index on the add post button? If so would be bringing it forward 'layer' wise be a simple fix?

It has a drop shadow so shouldn't blend into the yellow of the banner. Thoughts? 

(also pro moving it too but as Seth says, it might be wonky on different sizes)

**Comment by sethburtonhall** [comment]
@Angamanga has a good solution [here](https://github.com/ushahidi/platform-client/pull/1270)

**Comment by Erioldoesdesign** [comment]
@sethburtonhall I much prefer this solution. Thorough and will make for neat code/structure :)
