### ISSUE TITLE
post-view-data Total items is not updated correctly when there is 0 post left

### ISSUE THREAD

**Issue by sinneruy** [ushahidi/platform#3324]
**Describe the bug**
Total items is not updated correctly when there is 0 post left after deleting posts using the bulk action.

**Where was the bug observed**
https://test.ushahidi.io/views/data

**To Reproduce**
1. Go to /views/data
2. Log in as Admin
3. Click on bulk actions
4. Select all the posts
5. Press Delete and confirm
6. The posts count shows 0 of 20 posts and the "Bulk actions" stays enabled.

**Expected behavior**
The posts count should show 0 of 0 and the "Bulk actions" button should be disabled.

**Screenshots**
![firefox_2018-10-09_18-29-40](https://user-images.githubusercontent.com/1594608/46699815-52b5c080-cbf1-11e8-93c0-509538f9a0bc.png)

**URL / Environment where this happened**
https://hacktoberfesttest.ushahidi.io/views/data

**Desktop Hardware Details (please complete the following information):**
 - OS: Windows 10 pro
 - Browser FF dev edition 63.0b11 (64-bit) / Chrome 69.0.3497.100

**Comment by rowasc** [comment]
@sinneruy is working on this one, tagging

**Comment by rowasc** [comment]
@Angamanga sending in case you can find a bit of time to review this week. I can retest it. 
I _think_ it looks good, but there might be a reason we did the totalItems assignment to the itemsPerPage instead of setting it to zero from the beggining. 
Anyway.. lmk what you think.
