### ISSUE TITLE
When you delete a post in dataview, the total number of posts is not updated

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3326]
**Problem**
If I delete a post in dataview the total number of posts displayed on the top still remains the same (for example, before deleting: "20 of 20 posts". After deleting: "19 of 20 posts"

**Reproduce the bug**
1. Go to dataview, note how many posts are displayed in top of the list.
2. Delete one post
3. Note how many posts are displayed in the top of the list.

## Implementation notes
- Fix in https://github.com/ushahidi/platform-client repo
- Hint :bulb: The data-view files can be found here: https://github.com/ushahidi/platform-client/tree/develop/app/main/posts/views
- When you are done, 🔀 Start a Pull Request. There are two ways how you can start a pull request:

   1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

   2. You can also[ edit files directly in your browser](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) and open a pull request from there.

- 🏁 When done Ask in comments for a review :)

## Want to work on this issue?🙋 
Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

**Comment by fabsar** [comment]
Hey! I am Sargam, an outreachy applicant. I would like to go ahead with this issue. Thanks:)

**Comment by Angamanga** [comment]
@fabsar Please go ahead! Just comment here if you need guidance!

**Comment by fabsar** [comment]
hey! I was setting up the environment all this time. Since it's done now, Can you help me get started with the issue? Like where do i look for the code of the dataview section. Thanks!

**Comment by Angamanga** [comment]
@fabsar You find the all the post-view sections here: https://github.com/ushahidi/platform-client/tree/develop/app/main/posts/views and the data-view more specifically here: https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/views/post-view-data.directive.js.

**Comment by fabsar** [comment]
okay thanks a lot!

**Comment by tharveypa** [comment]
@fabsar is this issue available, or are you still working? Thanks

**Comment by rowasc** [comment]
Hi. @fabsar  is this issue available, or are you still working? let us know if you need some help. 
Thanks!

**Comment by AlanaFarkas** [comment]
I cannot replicate this issue locally, has this been fixed?

**Comment by rowasc** [comment]
I was able to repro. 
I had 21 posts, deleted one. Then the count is showing "19 of 21 posts" 🤔  
<img width="730" alt="Screen Shot 2019-11-15 at 14 49 43" src="https://user-images.githubusercontent.com/2434401/68964088-3ce0da80-07b7-11ea-9018-d20ff631ad06.png">

**Comment by rowasc** [comment]
Slightly better image sequence, sorry: 
2 of 2 posts (correct)
<img width="639" alt="Screen Shot 2019-11-15 at 14 51 35" src="https://user-images.githubusercontent.com/2434401/68964173-787ba480-07b7-11ea-977c-c6086c18573d.png">

*Deleted 1 (Count: 1 of 2. Incorrect)* <- this is the error 
<img width="580" alt="Screen Shot 2019-11-15 at 14 51 38" src="https://user-images.githubusercontent.com/2434401/68964172-77e30e00-07b7-11ea-961b-be2dc1a059b2.png">

Clicked data view again/reloaded (1 of 1 - correct again) 
<img width="638" alt="Screen Shot 2019-11-15 at 14 51 42" src="https://user-images.githubusercontent.com/2434401/68964170-77e30e00-07b7-11ea-9684-d47c18d9b82b.png">

**Comment by AlanaFarkas** [comment]
Just open a PR for this, here: https://github.com/ushahidi/platform-client/pull/1365

**Comment by rohit645** [comment]
I am able to replicate this issue locally, @rowasc    can i work on this issue?

**Comment by Angamanga** [comment]
@rohit645 Thank you for your interest in contributing, please go ahead and work on this and don't hesitate to reach out if you need further guidance!

**Comment by Angamanga** [comment]
@rohit645 How is it going, are you still working on this? Please let me know if you need any guidance!

**Comment by rohit645** [comment]
@Angamanga, I am trying to figure it out. I will be in touch shortly.

**Comment by Angamanga** [comment]
@Obadha2 Could you QA in Steve Buscemi?
Test-checklist:
1. Go to dataview, note how many posts are displayed in top of the list.
2. Delete one post
- [ ]  Note how many posts are displayed in the top of the list, it should be the total posts minus 1

**Comment by Obadha2** [comment]
QA'd, passes. 👍
