### ISSUE TITLE
Closing the edit collection menu saves changes

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#333]
Reproduce: Click on a collection, click edit collection, edit description field, click close/x button. The description will have changed. 

Expected result: click x, no changes are saved 

<img width="590" alt="screen shot 2015-08-13 at 9 25 05 am" src="https://cloud.githubusercontent.com/assets/1618793/9255318/51522b0c-419d-11e5-9bc0-9df64fad551d.png">

**Comment by willdoran** [comment]
This is not actually saving but it is updating the description live on the page, which is a nice feature but it should be cleared when the modal dialogue is closed. I'll fix that now.

**Comment by rjmackay** [comment]
@willdoran if the easiest fix is just to clone the collection object before editing, we can do that even if it breaks the live editing of the details on the page.

**Comment by willdoran** [comment]
Yeah that is one option but unfortunately the form itself would still contain the edited version. 

I was going to suggest a modal close listener that collection and savedsearch et al could subscribe to,

so on close the modal directive would broadcast("event:modal:closed"), what do you think?

**Comment by rjmackay** [comment]
Could you just watch isOpen and clone the object each time the modal is opened?

**Comment by willdoran** [comment]
Yep, I think that would work as well.

**Comment by willdoran** [comment]
Fixed by adding $watch and cloned object, will propagate changes to savedsearch too now
