### ISSUE TITLE
Block export of Tweet fields and Tweet contact info

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#3331]
When exporting data whose source is Twitter only the Tweet and User IDs should be exported. ALl other data - including Post Description and Geolocation should not be included.

@rowasc @jrtricafort I feel we need a better description of what exactly we are going to do here. It depends to a certain extent on whether we can determine which Post fields are likely to contain tweet information - we can make the assertion that Description and Contact fields will always be at issue but location field may be more difficult. Particularly if it was subsequently editted. Unwinding this requires more thought and relies on how we deal with the data inside existing DBs we may not be able to do this retroactively and perhaps this issue should only relate to future data exports?

# Implementation
The most sensible way to implement this would be to add a migration which scrubs on twitter info:

- Add new migrations
- Update posts where messages.data_source = 'twitter' AND posts.content = messages.message and delete posts.content. 
- Latitude and longitude should be wiped for unstructured posts.  
- Update messages and delete message content if type = twitter
- Update contacts and wipe twitter usernames.
- Because this could be implemented as a simple SQL statement it should run fairly quickly.
- Refactor CSV export to support twitter user_id and datasource id , and not export content when it's a tweet

**Comment by rowasc** [comment]
@willdoran  I think the extra problem here is deciding what happens in the scenario where we had a tweet, then a user converted it to a post and added more content. Do we prevent users from adding that content? Do we prevent users from converting tweets to posts with other fields, in an effort to avoid having a copy-paste problem where the user decides to bring in the content of the tweet to another field?

**Comment by willdoran** [comment]
@rowasc Yeah, I think that's valid. I honestly do not foresee being able to remove that data nor do we likely have the right to. I think we should however, make an attempt to remove the author information and to insert a tweet field to hold the info

**Comment by willdoran** [comment]
It's worth pointing out that we can check Post against the Messages which will contain the original information and then allow us to scrub the data.

**Comment by rjmackay** [comment]
To grab the count of messages the post has the tweet unchanged
```
select count(*) from posts join messages on (messages.post_id = posts.id) where messages.data_source = 'twitter' AND posts.content = messages.`message`;
```

**Comment by rjmackay** [comment]
The most sensible way to implement this would be to add a migration which scrubs on twitter info:

- Add new migrations
    - Update posts `where messages.data_source = 'twitter' AND posts.content = messages.message` and delete posts.content.
    - Update messages and delete message content if type = twitter
    - *maybe* Update contacts and wipe twitter contacts?
    - Because this could be implemented as a simple SQL statement it should run fairly quickly.

**Comment by willdoran** [comment]
@jrtricafort @aoduor Hey guys, I just want to make sure you're aware, the change we will be pushing will be removing obvious stored data, the tweet ids will be retained but this is the most effective update we can do. It will prevent data that should never have been stored from being retained.
