### ISSUE TITLE
Add Tweet field to Survey to display Tweets when no description present for Post

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#3333]
In order, to more directly associate a Post with a Tweet I suggest that we add a new Survey Field type: Tweet.

When this field is on a Survey and a Post of that Survey type is generated from a Tweet, this field will hold the Tweet ID.

When displayed on view it will show the Tweet in Tweet format. When in edit mode it will display the editable URL for the Tweet.

When a Post is displayed in slimmed down view, such as on map or data view, if no Description is present for a Post and it has an origin of Twitter then the Tweet field if populated will be displayed.

**Comment by rjmackay** [comment]
The original Tweet ID is already tracked through the messages table, I don't think we should duplicate this info, but we should return it in the posts payload

**Comment by rjmackay** [comment]
@willdoran are you happy if I close this? I think its covered by #3334

**Comment by rowasc** [comment]
Agree with tihs (discussed with Will as well). Closing
