### ISSUE TITLE
Write a blog post about hacktoberfest

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3343]

**Comment by Erioldoesdesign** [comment]
We can use the photo from the Civic Tech Hack event on this post and talk a little bit about that event? I'm not sure if any/many issues were progressed from that but it'd be worth drawing attention to the partnership.

**Comment by aoduor** [comment]
End of year update on how we did on OSS this quarter, talk about Hacktoberfest, Google code in etc.

Publish by Friday 21st Dec?

**Comment by aoduor** [comment]
Added i shpeal in the newsletter. Closing, unless we need a proper breakdown.
