### ISSUE TITLE
Add new post type not centered on screen, scroll broken

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#335]
What I try to create a new post type, the popup form is above the fold, not centered on my screen. I shouldn't be able to scroll the blacked out screen here, only the pop up, which should be centered

Step to reproduce: setting, edit post types, scroll down the page, add a new post type, scroll up and down the page

<img width="1277" alt="screen shot 2015-08-13 at 9 29 56 am" src="https://cloud.githubusercontent.com/assets/1618793/9255435/32c63934-419e-11e5-848e-f398bbda7b6c.png">

**Comment by rjmackay** [comment]
Reframing this: When a modal opens we should scroll to the top of the modal.. or place the modal at the top of the current view.

**Comment by sophshep** [comment]
Assigning to brandon since he has done the bulk of the modal js & css

**Comment by rjmackay** [comment]
I was actually just going to fix this directly in the client. Do you think its important to have the exact behaviour in the pattern library as well?

**Comment by brandonrosage** [comment]
@rjmackay The solution for this is already built into the *modal.js* script we wrote: https://github.com/ushahidi/platform-pattern-library/blob/gh-pages/assets/js/custom/modal.js#L15-L20

Note that, when a modal is toggled, the logic checks to see if it's opening or closing. It's opening, modalYpos() runs to ensure the window is 40px from the top of the window's current scroll position.

You can demo its behavior by:

* Visiting http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/setup-add.html
* Closing the modal.
* Scrolling down.
* Selecting the "Add your first post" button.

**Comment by rjmackay** [comment]
Thanks Brandon. I'll replicate that in the client JS..
