### ISSUE TITLE
The fab-button has wrong margin in data-view on non-demo-deployments

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3355]
The fab-button has the adjusted margin for demo-deployments on non-demo-deployments:
![Screen Shot 2018-10-25 at 18.13.07.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/5cae7f93-9cef-4454-bebb-b0b9ab23e513)

Hint: Check css-selector and https://github.com/ushahidi/platform-client/blob/develop/app/common/global/event-handlers.js#L15-L23

**Comment by rowasc** [comment]
Assigning a P1 as this is not a "can't use the site" thing but certainly annoying and not good usability. 
@Angamanga could you check this out tomorrow if you find some time? thanks!

**Comment by rowasc** [comment]
Closing as this was fixed
