### ISSUE TITLE
Add new field spacing broken

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#336]
Padding on "Add New Field" options is broken. All boxes should be the same height and width
 
<img width="593" alt="screen shot 2015-08-13 at 9 33 39 am" src="https://cloud.githubusercontent.com/assets/1618793/9255475/7527a8f8-419e-11e5-9ea4-f875252e62d6.png">

**Comment by rjmackay** [comment]
This will be resolved in mustang updates. Particularly #773
