### ISSUE TITLE
COMRADES web resources for program close-out.

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#3373]
## Overview
The output of this epic will be a complete set of assets needed to close out the COMRADES program. Specifically there will be: a configuration manual, single Github repo with detail read-me page, and a single web page that corrals all these into a single point of access for users/viewers. 

## Who is it for? Who are the users?
The COMRADES project has created a variety of outputs that need to be corralled together in a single web page. The consortium seems somewhat fixated on a scrolling, parallax page for this, but I am happy to entertain other ideas. The primary audience for the web page will be EU reviewers, followed by potential users who will typically have very high technical capacity and comfortably read English. The goal is to give the viewer a brief overview of what COMRADES is; provide them with access to some form of demonstration; and quickly find supporting information (documentation, individual pieces of technology, training). 

Previous attempts to create this have been undertaken and resulted in a mockup; draft list of content; and some photographs. [Those can be found in this Gdrive folder](https://drive.google.com/drive/u/1/folders/1fCpVUK36m1C4nebC0P-02pe4J-s4HLpe). 

## What privacy impacts does it have?
None. These are public facing materials to describe project outputs and present them in some sort of sensible narrative. 

## What are the constituent pieces of this epic?
- Create the required "web page" or adapt an existing web asset to serve as a the landing page for EU reviewers and potential users to find out more about the platform and link to supporting information.
- Finish establishing [comrades-stg](https://comrades-stg.ushahidi.com) as the "Demo COMRADES deployment" that is populated with data. (already in issue #3067) 
- Design / layout the COMRADES manual, which exists in draft form as the "[COMRADES Config manual](https://docs.google.com/document/d/1Ofi4sKFyUSqASKulOPHOEdApLEV5mjb__JPMZJ7Rm4M/edit)."
- Consolidate the [various COMRADES repos](https://github.com/ushahidi?utf8=%E2%9C%93&q=comrades&type=&language=) and update the README page with all necessary links and documentation (the README is Shadrock's responsibility). 

## Requirements for the "web page"
Here is a list of primary material (other websites) that the page should link to: 
- A COMRADES repo: right now there are three: 
https://github.com/ushahidi/platform-client-comrades
https://github.com/ushahidi/platform-comrades
https://github.com/ushahidi/comrades-service-proxy. 
- The ["Demo" COMRADES deployment ](https://comrades-stg.ushahidi.com/views/map)that is being run from the repo. This deployment will be viewable by the public, but will not be open for adding new posts. 
- A designed version of the "[COMRADES Config manual](https://docs.google.com/document/d/1Ofi4sKFyUSqASKulOPHOEdApLEV5mjb__JPMZJ7Rm4M/edit)."
- [The COMRADES project web site](https://www.comrades-project.eu/.), which is important as a repository for project reports and academic papers that would dig much deeper into the features for those interested (e.g. what algorithms are used, how accurate they are, etc.)  
- The constituent pieces that make up COMRADES: Ushahidi; [CREES (Crisis Event Extraction Service)](https://evhart.github.io/crees/); [YODIE](https://cloud.gate.ac.uk/shopfront/displayItem/yodie-en) (along with any documentation); [Rumor / Veracity clarifier](https://cloud.gate.ac.uk/shopfront/displayItem/rumour-veracity) (along with any documentation); [FB Bot](https://github.com/ushahidi/platform-facebook-bot); and YouTube videos, which could be embedded as opposed to linked content. The consortium wants to create (and in one case has) videos for various aspects of the COMRADES platform. [Here’s an example](https://www.youtube.com/watch?v=KRugR_7wGOM). 

## Possible Solutions for the "web page"
- The project website could be repurposed for this instead of creating a new web page (this would require coordinating with Gov2U). 
- Could use Github pages and attach this to the repo

## Timeline
- By **December 1st** - clean up/condense repos; update README, populate comrades-stg with Uchaguzi demo data. Change URL to just “comrades” without the “stg.”
- By **January 1st** - Complete “web page” and layout configuration manual.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-275

**Comment by Shadrock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [COMRADES demo deployment](https://trello.com/c/6cijIgb7/316-comrades-demo-deployment)

**Comment by Shadrock** [comment]
Some very good news on this @jrtricafort @willdoran... I think I've been able to get the "web page" aspect of this taken off our plate: I need to confirm in the next week or so, but it looks like our primary responsabilities will be in establishing the demo, writing up a clear readme page for the repo, and then laying out the COMRADES user manual.

**Comment by jrtricafort** [comment]
That is excellent news, @Shadrock ! Thanks so much for managing all of this, and definitely keep us posted. We'll support all the necessary closeout activity, but if we can get it done faster with a shorter list of items, even better!
