### ISSUE TITLE
Add Delete Step within Edit Step page

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#338]
When I'm editing a post step, there is no way to delete that whole step. Add the delete step button here, and then take the user back to the Post Type overview 

<img width="1052" alt="screen shot 2015-08-13 at 9 39 23 am" src="https://cloud.githubusercontent.com/assets/1618793/9255597/49deb3f2-419f-11e5-993e-61726d94de0d.png">

**Comment by rjmackay** [comment]
Clarification: Delete button should be added as per edit post type page (below the field list) and/or in the post step settings (similar to collection editing)

**Comment by sophshep** [comment]
Cross-referencing #341 where we are discussing the same thing. I am starting to think we should take all delete functionality out of the modal/settings and have it as a link next to the settings link.
