### ISSUE TITLE
Docs: Open Source License Overview

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3383]
https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/license-overview

Details coming up shortly.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-274

**Comment by tuxpiper** [comment]
@aoduor that link doesn't seem to be working anymore since it was pointing at a draft ... but searching for "license" doesn't seem to bring up good results either.

Was there content already in the link that you pasted? Or are we still to generate this?
