### ISSUE TITLE
Docs: Setting up the pattern library

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3388]
Move over pattern library documentation to gitbook.

Gitbook link: https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/getting-started/setting-up-the-pattern-library-for-development

**Comment by aoduor** [comment]
Needs to be broken down into two different issues.

@rowasc completed migration of one section of this. Angie to confirm

**Comment by Angamanga** [comment]
I added a new issue here for the rest of the pl-docs here: https://github.com/ushahidi/platform/issues/3461. @rowasc I'll review the things you have added and then we can close this issue.

**Comment by Angamanga** [comment]
@rowasc I think we should add the section about how to use the changed styles in the platform-client if the user decides to change the styles in the PL too? I think it belongs here: https://ushahidi.gitbook.io/platform-developer-documentation/changing-ui-styles-introduction-to-the-pattern-library? Or is it added somewhere and I don't find it?

**Comment by rowasc** [comment]
Yea I believe that's a good idea. I think I covered a little bit of that but more docs about it would be great yeah

**Comment by Angamanga** [comment]
@rowasc I'll sort it! 🎉
