### ISSUE TITLE
Don't bury Step Name and Required checkbox in an additional settings pop up

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#339]
What happened: when I click on edit step, I want to edit the name of that step, I have to click "post step settings" to edit the name,

Expected: Since I am already in an "edit" stage, I want to be able to edit name and requirements field without an additional pop up

Steps to reproduce: create a post type, add structure, edit structure 

<img width="1067" alt="screen shot 2015-08-13 at 9 42 53 am" src="https://cloud.githubusercontent.com/assets/1618793/9255700/e4e67790-419f-11e5-876c-970116c865a3.png">

**Comment by rjmackay** [comment]
@sophshep thoughts?
