### ISSUE TITLE
Docs: Tech Stack overview

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3391]
Migrate existing overview docs (which i can't seem to find anymore)

Gitbook link: https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/tech-stack-overview

**Comment by rowasc** [comment]
I already migrated what we had, but we didn't have much. I'll start documenting the API today

**Comment by rowasc** [comment]
ah. Small bump. We need an integration with `nomnoml` for the diagrams (or switching to another tool that integrates with gitbook well) @tuxpiper I found one but it's for gitbook 1.0 :(

**Comment by tuxpiper** [comment]
@rowasc 

For a direct gitbook integration, we will have to advocate with the gitbook folks for an integration that would suit our needs, and then it's up to them to do it or not ... so far, people written a couple feature proposals:

https://gitbook.canny.io/feature-requests/p/support-for-making-diagrams-eg-gliffy-mermaid
https://gitbook.canny.io/feature-requests/p/integration-drawio

Maybe it's more feasible to patch something together on our own. I.e. something that renders the diagrams, from whatever source, as image files in github , and uses gitbook's github integration for updating the gitbook.

**Comment by rowasc** [comment]
yea, I think so .I can just pastte them I guess?

**Comment by aoduor** [comment]
Need to break this down further into bit sized chunks

**Comment by aoduor** [comment]
First section of this is complete.
