### ISSUE TITLE
Docs: Database Description

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3392]
This effort should include 

- [x] Schema Diagram
- [x] Tables overview ( summary of what each DB table holds)
- [ ] Table details ( Explanation of what each field holds)

Gitbook link: https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/tech-stack-overview/database

Reference point, Ushahidi v2 db docs: https://wiki.ushahidi.com/display/WIKI/Database+Description

**Comment by Angamanga** [comment]
Check Comrades docs

**Comment by Angamanga** [comment]
Db-schema: https://github.com/ushahidi/platform/blob/develop/docs/schema.svg

**Comment by tuxpiper** [comment]
@Angamanga do you happen to know how that svg was generated?

**Comment by aoduor** [comment]
@Angamanga -> Tables Overview
@tuxpiper -> Database schema
@aoduor -> to help @tuxpiper and @Angamanga on Table details 💃

**Comment by tuxpiper** [comment]
Is it right that we can close this now given the contents here? : https://docs.ushahidi.com/platform-developer-documentation/tech-stack-overview/database

**Comment by Angamanga** [comment]
Yep! Closing
