### ISSUE TITLE
Docs: Dev process Documentation

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3394]
- [ ] Coding standards: https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/development-process/coding-standards
- [ ] Issue tracking: https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/development-process/issue-tracking
- [ ] Roadmap: https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/development-process/roadmap

**Comment by Angamanga** [comment]
Add from process-docs. Describe process we used during spring.

**Comment by Angamanga** [comment]
Draft in progress here https://ushahidi.gitbook.io/platform-developer-documentation/~/edit/drafts/-LWA1Or-JXpEkbUvZtYM/getting-started/development-process

**Comment by Angamanga** [comment]
Merged draft to master-doc so closing this issue.
