### ISSUE TITLE
Docs: QA and Testing Process

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3395]
- [ ] Overview: https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/qa-and-testing
- [ ] Writing Tests: https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/qa-and-testing/adding-manual-test-suites
- [ ] Running Tests: https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/qa-and-testing/running-manual-tests

**Comment by Angamanga** [comment]
TODO:
- Describe what test we use and where we store it (Testpad)
- Testpad-link, can we open it up to the public?
- Do we want to get help with testing from the community?

**Comment by Angamanga** [comment]
Section is merged to master here: https://ushahidi.gitbook.io/platform-developer-documentation/getting-started/qa-and-testing. Closing this issue.
