### ISSUE TITLE
Docs: Open Source Design Process

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3396]
We may not be able to get to this within the scope of DIAL, but still making note for us to discuss. cc @justinscherer @Erioldoesdesign and anyone else interested.

**Comment by aoduor** [comment]
This is a much longer term project, that we should probably roll into longer time beyond the scope of this DIAL grant. 

Minimum effort for now, link to @justinscherer and @Erioldoesdesign's amazing work on Mozilla open leaders. 

Should also link to design jam articles from the Designit work last year.

**Comment by aoduor** [comment]
@Erioldoesdesign will handle on Thursday this week.

**Comment by justinscherer** [comment]
Sounds good!

**Comment by Erioldoesdesign** [comment]
hey here's a thought @rowasc and @aoduor, this could be included as a heading in FAQ's for now and developed further in the next round of funding/changes?

https://ushahidi.gitbook.io/platform-developer-documentation/frequently-asked-questions

**Comment by Erioldoesdesign** [comment]
https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LXO47CFPnfqKXxJLyvo/primary/contributing-or-getting-involved/contributing-documentation/open-source-design

Page is ready for review!
