### ISSUE TITLE
Docs: Contributing code to Ushahidi

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3397]
Migrate existing docs here: https://www.ushahidi.com/support/add-code-to-ushahidi to Gitbook: https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/contributing-or-getting-involved

**Comment by Angamanga** [comment]
@StaicyG I am starting on this one.
