### ISSUE TITLE
Docs: Upgrading from version 2 to version 3 of Ushahidi

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3398]
Let's start documenting the manual process we have developed in the past, even as we talk of automating this.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-273

**Comment by tuxpiper** [comment]
Assigning myself to take a look at https://github.com/ushahidi/platform/pull/3466 , run some tests and document

**Comment by tuxpiper** [comment]
related to #3418

**Comment by tuxpiper** [comment]
self ping @tuxpiper

**Comment by tuxpiper** [comment]
Document draft (WIP) here: https://app.gitbook.com/@ushahidi/s/platform-developer-documentation/~/drafts/-MF-AphZ1Bm7xEHnWBPo/@drafts
