### ISSUE TITLE
Docs: Upgrading from version 3 to version 4 of Ushahidi

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3399]
Ongoing here: https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/upgrading-from-v3.x.x-to-v4.x.x

**Comment by jrtricafort** [comment]
@aoduor What is Version 4 of Ushahidi?

**Comment by aoduor** [comment]
I think, basically, everything that came before Lumen qualifies as v3 - so this is focused on migration from that to Lumen..

**Comment by Angamanga** [comment]
Added the stuff from old docs, but do we need to add further description about v4?

**Comment by tuxpiper** [comment]
I would love to work on this, we have people already asking for an upgrade guide. 

@rowasc could you please help with looking up the changes necessary for the CSV export to work? I've been looking at commits but quickly lost myself.

**Comment by Angamanga** [comment]
@tuxpiper I added the release-docs from the lumen-release but this pr still needs to get merged before closing: https://github.com/ushahidi/platform/pull/3463. Could you take a look, I tried to resolve the conflicts but I am not sure whats actually the latest version of the text?

**Comment by tuxpiper** [comment]
The changes proposed by the PR would prevail. Let's hold on until we know when we will release the associated code before merging it.

**Comment by Angamanga** [comment]
:+1 : Removing this from milestone 3 in the meantime.

**Comment by aoduor** [comment]
This is done. Clooooosing 💃

**Comment by aoduor** [comment]
Making a note to create a new issue for migration from v4.0 to the next release: cc @Angamanga
