### ISSUE TITLE
Reordering Steps does not work

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#340]
The up and down arrows on step structure doesn't change the order of the steps

Recreate: settings / post types / select a post with multiple steps / click arrow up & down buttons

<img width="1076" alt="screen shot 2015-08-13 at 9 46 45 am" src="https://cloud.githubusercontent.com/assets/1618793/9255771/4bc66600-41a0-11e5-96a7-35f7a537e31e.png">

**Comment by hollycorbett** [comment]
Picking this up now
