### ISSUE TITLE
Docs: Dev FAQs

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3400]
Gitbook link: https://ushahidi.gitbook.io/platform-developer-documentation/~/drafts/-LRHaCHVnWnuxoItpF9_/primary/frequently-asked-questions

**Comment by StaicyG** [comment]
@tuxpiper I have kinda finished some of the questions here. Please have a look and let me know what you think.

**Comment by tuxpiper** [comment]
This looks pretty good to me @StaicyG ! I suggest let's just add something at the bottom asking to join the developer channel in case there is a question not found in the doc

**Comment by StaicyG** [comment]
Great! Thanks for the feedback @tuxpiper all done!

**Comment by tuxpiper** [comment]
I think this is good to go! Shall we close?

**Comment by aoduor** [comment]
Closing... can reopen if needed :).
