### ISSUE TITLE
Vids: Setting up your dev environment

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3401]
- [x] Write up a video script based on existing documentation
- [ ] Identify best placed individual to do voice over + comp screen walkthrough
- [ ] Record video tutorial
- [ ] Publish

**Comment by tuxpiper** [comment]
Related to:
- https://ushahidi.gitbook.io/platform-developer-documentation/getting-started/setup_alternatives/vagrant-setup
- https://ushahidi.gitbook.io/platform-developer-documentation/getting-started/setup_alternatives/setting-up-the-platform-client

**Comment by aoduor** [comment]
This should include set up for
- The API
- The client

**Comment by aoduor** [comment]
@StaicyG @CeciliaHinga @tuxpiper how are we doing here?
