### ISSUE TITLE
Review Open Source Survey Results

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3404]
Review feedback on https://bit.ly/UshahidiOpenSourceSurvey2018 to identify 

- Contributor segments
- Challenges
- Recommendations

**Comment by Erioldoesdesign** [comment]
I can help with this <3

**Comment by aoduor** [comment]
Got our draft here: https://docs.google.com/document/d/1JG-eyVm3Md95eP9-sRLlj5JPedIAEhdKe_pkRbiSTNA/edit#heading=h.39xp0dpd98d2
