### ISSUE TITLE
Docs: Contributing to ushahidi documentation instructions

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3406]
Adding this in as well, as it's become a clear need over the last few weeks with more and more interest in contributing to docs.

**Comment by tuxpiper** [comment]
## Anonymous / casual contributors

There is no anonymous access in gitbook that allows editing documents right from their interface. Guest contributors can edit through github and create pull requests.

Gitbook streamlines the process for editing existing pages through github.

The process for creating new pages via Github may be more involved.

## Other contributors

For contributors that are planning to work on more extensive parts of the documentation (than editing a single existing page), we may want to devise a process where such contributors apply for and obtain gitbook access

**Comment by aoduor** [comment]
Nicely done. Closing.
