### ISSUE TITLE
Delete post type should not be at the bottom of the page 

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#341]
Move the delete option up on the page when in the Edit Post Type menu

<img width="1050" alt="screen shot 2015-08-13 at 9 48 50 am" src="https://cloud.githubusercontent.com/assets/1618793/9255814/9e447976-41a0-11e5-99c4-3f018b61550e.png">

**Comment by rjmackay** [comment]
@sophshep what do you think about moving this?

**Comment by sophshep** [comment]
To match the UX of how we treat deleting collections and other groupings of things, the delete button should be within the "post type settings" modal.

What do you both think? Is that too hidden? If so, I'm fine making it its own link that comes after "post type settings" with the same style (blue icon of bin & blue link that says "delete post type".

If we make this change though, let's make it globally.

**Comment by rjmackay** [comment]
We had https://github.com/ushahidi/platform/issues/313 logging confusion trying to delete a collection too.
- I think hiding the delete button under settings is probably too confusing for most people. More so on post types when we're already editing.
- On collections it was ok-ish to hide it under 'edit collection' but I think the 'Settings' label confused people too. 
- Its a small change to show the delete button next to settings, with a potentially large win.
  - do we have space to show it easily on mobile too? if so I say we just put it next to settings.

**Comment by sophshep** [comment]
Yes, on mobile it will just stack. Let's do it.

**Comment by rjmackay** [comment]
@willdoran I think this is done right? can you close this out if it is..

**Comment by willdoran** [comment]
Yes, it is.
