### ISSUE TITLE
SMSSync works generally, but 'Test Configuration' doesn't work with GET [m-Sheria] 

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#3416]
It's possible to use SMSSync to forward SMS messages along to platform. 
However, the 'Test Configuration' button doesn't work, and returns an error.

This appears to be because the test is done via GET, which platform will reject, despite the fact that SMS endpoint is configured for POST.

One solution for this: allow GET to be a valid method for SMS in SMSSync.

**Comment by ijrad** [comment]
@kinstelli Hi, please which mobile app version are you using to send sms to ushahidi platform?
