### ISSUE TITLE
Import v2 tables into v3 DB as-is to ensure no data is lost

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#3419]
- As a deployer I need to know I will not lose any data when migrating to v3
- As Ushahidi staff, I need to know I will have all v2 data available in future in case some data is lost

Approach:

- Grab a list of tables from the DB
- Grab the schema for each one and create a new table in our v3 DB names `v2_TABLENAME`
- Copy all the data, maybe through `INSERT INTO ... SELECT`

Aha! Link: https://ushahiditeam.aha.io/features/PROD-269

**Comment by rjmackay** [comment]
- As a deployer I need to know I will not lose any data when migrating to v3
- As Ushahidi staff, I need to know I will have all v2 data available in future in case some data is lost

**Comment by willdoran** [comment]
Yes, I think essentially having something that looks like a dump makes sense, in a sense it's a little like a revision system.
