### ISSUE TITLE
Step structure UI should appear on the "Edit Post Type" page 

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#342]
The UI for Step structure does not appear when you click "edit post type" but then appears when you click on an individual step. The UX should be consistent. 

<img width="1277" alt="screen shot 2015-08-13 at 9 50 46 am" src="https://cloud.githubusercontent.com/assets/1618793/9255880/00cd18f0-41a1-11e5-9e70-b02990acd4de.png">
<img width="1280" alt="screen shot 2015-08-13 at 9 50 55 am" src="https://cloud.githubusercontent.com/assets/1618793/9255881/00cd153a-41a1-11e5-817d-128487f66315.png">

**Comment by rjmackay** [comment]
I don't think that makes sense since then we'd be showing the list of steps twice on the post type page.
cc @sophshep

**Comment by sophshep** [comment]
I think this is similar to an issue i made here: #772

Either way, I am going to close this for now since @brandonrosage and I are planning on getting together on Friday to totally rethink this flow.
