### ISSUE TITLE
Where does the built js in dotcom comes from?

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3441]
**TODO**
Where does the js in https://github.com/ushahidi/dotcom-craft-cms/tree/master/public/js come from. Especially app.js? Where is it built? Is it ever built? I tried to add new js but had to do it as a separate file.

Figure out where it comes from and see if its up to date and find out the best way to add new js to dotcom for the future.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-258

**Comment by rowasc** [comment]
Probably an important thing to do after the other high priority work you have for cloud :)
