### ISSUE TITLE
User unable to proceed after selecting free plan for new deployment.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3447]
**Describe the bug**
Unable to select plan and proceed to opening newly created deployment. 

**Where was the bug observed**
Right after creating new deployment, following tutorial and selecting Free plan.
https://ushahidi.io/tour/plans

**To Reproduce**
1. Go to ushahidi.io/tour#plans
2. Log in as (newly created) user.
3. Click on Sign Up for free plan (Ushahidi Demo).
4. New page open with error message (See attached screenshot).

**Expected behavior**
On selecting plan, should redirect user to their profile or give more information. Nothing should go wrong.

**Screenshots**
![screenshot from 2018-12-07 16-49-59](https://user-images.githubusercontent.com/38259840/49654414-c38a2500-fa48-11e8-997f-d05f7249da4a.png)

**URL / Environment where this happened**
https://ushahidi.io/tour/plans

**Desktop Hardware Details (please complete the following information):**
 - OS: [Ubuntu 18.04 LTS]
 - Browser [Chrome]
 - Version [ 71.0.3578.80 (Official Build) (64-bit)]

**Additional context**
Page had been sitting idle for several minutes from logging in. Perhaps account expiry due to inactivity?

**Comment by rowasc** [comment]
This is fixed now, I was able to create a free plan deployment a few days ago
