### ISSUE TITLE
New user unable to access Platform

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3448]
**Describe the bug**
After new user signs up on the platform, they are unable to access their deployment page when they type out the url on browser's address bar.

**Where was the bug observed**
https://walter-qa.ushahidi.io/

**To Reproduce**
1. Go to https://ushahidi.io/create
2. Create new deployment.
3. On new tab, type out url of new deployment created.
4. See error as seen in attached screenshot.

**Expected behavior**
On typing out the url, user should be taken to deployment page.

**Is there a workaround? What is it.**
None, thus far. User can however still access their deployment on the tab where deployment was created! 

**Screenshots**
![screenshot from 2018-12-07 18-40-51](https://user-images.githubusercontent.com/38259840/49657051-d05e4700-fa4f-11e8-93c5-4fcd4532dcaf.png)

**URL / Environment where this happened**
https://walter-qa.ushahidi.io/

**Desktop Hardware Details**
 - OS: [Ubuntu 18.04 LTS]
 - Browser [Chrome]
 - Version [ 71.0.3578.80 (Official Build) (64-bit)]

**Comment by rowasc** [comment]
@jrtricafort I believe this might be a P0.

- looks horrible
- prevents users from knowing what's going on
- I think deployment creation itself is broken with this. I've been waiting for a new deployment for 30 minutes with no luck, and Walter's deployment is still down after days

**Comment by rowasc** [comment]
Solved. >Closing
