### ISSUE TITLE
Not clear how to add multiple posts to a collection 

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#345]
It isn't clear how to add multiple posts to a collection. When I select multiple posts in list view and click add to collection on a single post, it isn't clear to me if it will add all the posts to a collection or just that one. There is also no notification or UI  change, so I don't know that something happened. 

Reproduce: View posts, select multiple posts, add to collection

![screen shot 2015-08-13 at 10 09 11 am](https://cloud.githubusercontent.com/assets/1618793/9256305/a6e6cbbc-41a3-11e5-99ea-33884c8ebfee.png)

**Comment by rjmackay** [comment]
Changes needed:
- Provide feedback when post added to collection
- Provide an 'add to collection' button in bulk actions
