### ISSUE TITLE
Move users email to contacts

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#3457]
To make the data model more like TenFour and more useful to importing from v2, we want to move all contact info into the contacts table. We also need to enable adding names to contacts - who may not be users that ever log in.

Schema changes:
- Remove user.email
- Add user.person_type to differentiate between full users (with roles, and passwords) and contacts

Repo changes:
- Update functions that do lookups by email to look in contacts instead
- Update create/update to insert contacts at the same time we create/update the user
- Update validators to validate user.contacts

Frontend changes:
- Update frontend to send email as part of user.contacts
- Update frontend to use user API instead of contacts where possible

Testing:
- Add tests for every function that's modified.
- Existing behat tests should pass
- Behat sample data will need to be updated

Aha! Link: https://ushahiditeam.aha.io/features/PROD-251

**Comment by rowasc** [comment]
I'm not super convinced that we should do this right now with a lot going on, anyway 🤔 may need to untag .
@tuxpiper we may need to reconsider this change because of the v2 importer changes that may come from it, what do you think?

**Comment by RachealN** [comment]
While waiting for detailed specs for this issue #3179 and resolved, I will be working on this issue for now

**Comment by RachealN** [comment]
@rowasc, Assign this issue to me. Thanks

**Comment by rowasc** [comment]
@RachealN thats not possible at the time, see my comment above. If you pick another one I will assign it.
