### ISSUE TITLE
Toggle on Data Sources does not work

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#347]
Settings / Data Sources/ "Click a toggle"

When you toggle a data source the toggle doesn't flip to green 

![screen shot 2015-08-13 at 5 38 15 pm](https://cloud.githubusercontent.com/assets/1618793/9265031/33ac6f1e-41e2-11e5-9d03-9c59d41dabe5.png)

**Comment by jshorland** [comment]
This is an issue where we need better communication to the user as to what they need to do to be able to turn it on. assigning to @sophsephard

**Comment by sophshep** [comment]
The issue with this is that it's unclear that the toggle is disabled when a user has not entered adequate set-up info. I've updated [the pattern in the pattern library](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/data-sources.html) to look like this: 

![image](https://cloud.githubusercontent.com/assets/527589/10650400/e4a95464-780e-11e5-8717-66744d4fc9db.png)

If a data source has not been set up/configured yet, there is no toggle present, and the main button to expand it says "set up". 

Within the set-up fields, the "Save Data Source" button should be disabled until a user has entered all required fields. When they select "Save Data Source" then the toggle should be shown as on/green. Now that it's set up, a user can turn it on and off via the toggle.

**Comment by jshorland** [comment]
this looks awesome, Sophie. Thank you.

**Comment by aoduor** [comment]
Additionally, I noticed that the toggle menu doesn't work for options not available on a certain upgrade path too - we should enable that, or find a way to make it clear from the onset that "this data source is not available under this plan"

And yes, @sophshep that looks awesome!
