### ISSUE TITLE
Docs: consider hosting gitbooks under our own domains

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3472]
Gitbook allows us to host each gitbook under its own subdomain of our choice.

For instance, the platform developer gitbook could be under platform-dev.docs.ushahidi.com

The platform developer manual could be under platform-manual.docs.ushahidi.com

Unfortunately there is no way to do docs.ushahidi.com/platform-dev  or docs.ushahidi.com/platform-manual .. which would feel a bit cleaner to me

**Comment by Jenniline** [comment]
Hi, @tuxpiper I will like to work on this. Can I?

**Comment by tuxpiper** [comment]
Thank you @Jenniline  . Unfortunately,  this is more of an administration task ,  requiring administrator access to the resources that we manage.

It's probably a bit confusing that it's sitting here on the open source repository, sorry about that!

**Comment by tuxpiper** [comment]
Hosted at https://docs.ushahidi.com now
