### ISSUE TITLE
Add section about open design in "Get in touch with us"

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3473]
Copied from old section:
I'd like to help with a section on how designers can contributes (via Justin's MozOL project) and Int dev/Activists can contribute (via my MozOL project)

**Comment by Jenniline** [comment]
@Angamanga am Jenniline an Outreachy applicant can I work on this issue?
I also need more details about this.

**Comment by Angamanga** [comment]
Hi @Jenniline, unfortunately not, this issue needs work from us at Ushahidi first.

**Comment by Angamanga** [comment]
This was done in the dev-hub work so closing.
