### ISSUE TITLE
Attach GIS shp and KML,KMZ files to Ushahidi v3 Deployment Map

### ISSUE THREAD

**Issue by ginamaff** [ushahidi/platform#3474]
As a user, i'd like to be able to upload geodata on my ushahidi deployment. e.g. Shapefiles, KML/KMZ files. This makes the data visualization better specifically on location

Aha! Link: https://ushahiditeam.aha.io/features/PROD-250

**Comment by Brad-Anthony** [comment]
I'll second that. This would really up the ante in terms of analysis capability without requiring users to have/use technically demanding GIS platforms.

**Comment by ClearLakeHABMap** [comment]
This feature was brought up in the past and I would add that another mechanism that could be helpful would be to subscribe to a hosted KML/KMZ file to load the updated version. Generally, we can publish these files through Google Earth/ArcGIS and update them regularly. If the solution drew the file in and projected it to the deployment map, we would always have an updated version.

**Comment by HealZim22** [comment]
We have raised an issue with ushahidi not able to upload GIS shape files on a deployment to make the visualization better on location.  up to now there isn't a solution. adding this feature will be best thing ever happen for my project... any progress so far?
