### ISSUE TITLE
Bristol Meetup 11.02.2019

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3476]
~Confirmed date: Feb 4th~
Confirmed date: Feb 11th
Time: 12.30 - 14.00 GMT
Open Source tech with South West International Development workers
Need
- Keen to know if they can tell people if they can come with general open source questions? YES. 

- Demo issues/ Updated roadmap with some issues people can jump into.

- Identify point people online to support Eriol remotely on community channel/hangout? 

- @Erioldoesdesign to develop a framework for what we need to have that ready.

**Comment by Erioldoesdesign** [comment]
Started a doc to figure out answers to above questions: https://docs.google.com/document/d/18-ahhCI2xBmyfO3HuTMVI5Abv5Il-KmdClb_uV_CGl0/edit?usp=sharing

**Comment by aoduor** [comment]
Let's use this existing meetup planning doc we have for DIAL?

https://docs.google.com/document/d/1hGSUdd-JaTkLxoybsWh8we7Nul-SWyUjm8Q2i1vJwVM/edit#

**Comment by Erioldoesdesign** [comment]
DONE!
