### ISSUE TITLE
CSV exports of media contain wrong URLs when CDN enabled

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3481]
**Describe the bug**
When exporting a CSV files off surveys containing media (images), the URLs for those images can be wrong, depending on software configuration.

When Platform is configured to use object storage and CDN, the URLs for accessing the images correspond to a different domain, and the CSV export process is ignoring that. See steps to reproduce and expected behaviour for a practical example.

**Where was the bug observed**
Any .io Ushahidi deployment is affected

**To Reproduce**
1. Go to a ushahidi.io deployment, with images and where you have membership.
2. Export a CSV containing posts with images
3. Open the CSV
4. Observe how the links to the images are of the form: https://deployment-name.api.ushahidi.io/xxx/yyyy/file_name.ext
5. Try to open any of those links and you will get a failure screen

**Expected behavior**
Working links to downloads on Ushahidi.io should actually start with: https://74ddb495e3f187ded630-0b4c691ea14dad11384ab079da46af4f.ssl.cf2.rackcdn.com/deployment-name.api.ushahidi.io (followed by the /xxx/yyyy/file_name.ext patterned part)

**Is there a workaround? What is it.**
The only way to work around the bug is to manually edit the URLs in the CSV by following the pattern described above.

**Screenshots**

**URL / Environment where this happened**
* ushahidi.io

any environment configured to use object storage and a CDN for media serving (as opposed to local disk) is probably affected

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**

**Desktop Hardware Details (please complete the following information):**
non relevant

**Smartphone Hardware Details (please complete the following information):**
non relevant

**Additional context**

Aha! Link: https://ushahiditeam.aha.io/features/PROD-248

**Comment by rowasc** [comment]
@tuxpiper nice catch.  
@jrtricafort could you prioritize? Thanks. 
I *thinkk* this is likely a simple fix to add the CDN URL to image fields in CSV (I mean, I might be wrong :) ) but let me know what/when you think we should tackle this.

**Comment by tuxpiper** [comment]
I just checked that the initial report about this behaviour, was relative to one of our social impact licensed deployments in ushahidi.io

**Comment by tuxpiper** [comment]
This has been fixed in a recent release
