### ISSUE TITLE
Heroku install fails

### ISSUE THREAD

**Issue by j-rewerts** [ushahidi/platform#3483]
When using the Heroku click to deploy button on the readme, it fails with the following message:
```
In MysqlAdapter.php line 115:
                                                                                      
There was a problem connecting to the database: SQLSTATE[HY000] [2002] No such file or directory 
```

**Steps to reproduce the behavior:**
1. Go to [this](https://github.com/ushahidi/platform) URL.
1. Click the Heroku click to deploy button.
1. Input your Heroku deployment name.
1. Click "Deploy app"

**Expected behavior**
The app should deploy properly.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-247

**Comment by jesseorndorff** [comment]
Same issue here.
