### ISSUE TITLE
Google Summer of Code 2019: Ushahidi Project Ideas.

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3484]
### **GSoC Contacts**

- Angela Oduor Lungati: angela@ushahidi.com 
- Staicy Gitau: staicy@ushahidi.com 
- David Losada: davidlosada@ushahidi.com 
- Anna Iosif: anna@ushahidi.com 
- Eriol Fox: eriol@ushahidi.com

**For all projects, we recommend the following steps to get started:**
1. Set up the Platform dev-environment (instructions are here: https://ushahidi.gitbook.io/platform-developer-documentation/getting-started/setting-up-your-development-environment, most of us use the Vagrant setup)
2. Play around with the platform, login, change settings, add posts and surveys. There is a user-manual to be found here: https://ushahidi.gitbook.io/ushahidi-platform-user-manual/
3. Grab one of the issues marked with the label good-first-issue here: https://github.com/ushahidi/platform/labels/good-first-issue. All issues for both the Platform-API (https://github.com/ushahidi/platform) and for the web-client (https://github.com/ushahidi/platform-client) are stored there.

### **Project 1**
**Project Title:** Ushahidi Platform JS React Migration
**Description:** This involves work to modernize Ushahidi’s frontend and improve performance for low-bandwidth users. The goal of this migration is to

- Improve usability in low bandwidth settings (which in turn, will improve usability for all users);
- Improve ability for developers to build and deploy new code.

Extensive research was conducted by the Ushahidi team, and we settled on React JS. This project is a continuation of work that was started on migrating to the new JS framework
**Skills:** Javascript
**Difficulty level:** Intermediate
**Related readings/links**

- Blog post: https://www.ushahidi.com/blog/2018/03/21/a-javascript-journey-1
- Github repository: https://github.com/ushahidi/platform-client/tree/epic/js-rewrite-2547
- JS Migration github issues: Link TBD

**Potential Mentors:** Anna Iosif, Eriol Fox & Justin Scherer

### **Project 2**
**Project Title:** Voice Integration into Ushahidi platform
**Description:** Currently, the Ushahidi platform supports data collection via SMS, Email, Twitter and smartphone apps. This project would involve integrating voice as a means of collecting data on the Ushahidi platform
**Skills:** PHP, capable of working with Ushahidi API
**Difficulty level:** Difficult
**Related readings:** 

- Github repository: https://github.com/ushahidi/platform 

**Potential Mentors:** David Losada, Anna Iosif

### **Project 3**
**Project Title:** Ushahidi Platform Data Exchange
**Description:** Establish standards for exchange (import & export) of survey definitions and posts across instances of the Ushahidi Platform. Implement tools based on this standard, for users and developers to share and port their data, as well as their collection methods, with others.
**Skills:** PHP, data modelling, data streaming, serialisation/deserialisation
**Difficulty level:** Medium
**Related readings:**
https://ushahidi.gitbook.io/ushahidi-oss-home/proposals-projects/architecture/ushahidi-platform-exchange-format 
**Potential Mentors:** David Losada

### **Project 4**
**Project Title:** Ushahidi platform USSD Integration
**Description:** USSD, which stands for Unstructured Supplementary Services Data, is a protocol that allows for the transmission of information via a GSM network. Users enter a USSD string and press call to send the message. A typical USSD message starts with a * followed by digits which indicate an action to be performed or are parameters. Each group of numbers is separated by a *, and the message is terminated with a #. For example, in Kenya, to find out what your airtime balance is on Safaricom, a user will dial *144#. Unlike SMS, USSD messages create a real-time connection during a session, that remains open, allowing a two-way exchange of a sequence of data.

This project will involve developing an application that allows for users to send in reports to ushahidi deployments via USSD on Ushahidi v3. 

**Skills:** Mobile dev, PHP, capable of working with Ushahidi API
**Difficulty level:** Medium
**Related readings:** 

- Blog post: https://www.ushahidi.com/blog/2013/10/03/ushahidi-via-ussd 
- Github repository: https://github.com/ushahidi/platform
- Simon de Haan’s github repository: https://github.com/smn/go-ushahidi 
- Video demo: https://www.youtube.com/watch?v=RS54RzNUpLs 

**Potential Mentors**: Staicy Gitau, Angela Oduor Lungati, David Losada

### **Project 5**
**Project Title:** Working closely with Deployment owners. Follow on from MozOL6 : Working openly and encouraging contribution from international development workers, activists and volunteers 

**Description:** In late 2018 work was done by a UX designer at Ushahidi through the Mozilla Open Leaders 6 program to better integrate direct feedback from grassroots deployment owners to Github issues/features that could directly impact the work they do in their sectors/communities.

As a result several issues/tickets were flagged as important to the deployment owner Bristol Women’s Voice: Street Harassment map

This project would entail working on issues related to this work tagged with Community Feedback (as well as Good First Issue and Community Task)

**Skills:** Front-end, Design, Mobile dev, PHP, capable of working with Ushahidi API
**Difficulty level:** Medium - Difficult
**Related readings:** 
- Github repository: https://github.com/ushahidi/platform
- MOZOL6 project: https://github.com/MozillaFestival/open-leaders-6/issues/32
- MOZOL6 idontcode repository where non-coders can learn how to contribute insight to Ushahidi platform issues: https://github.com/Erioldoesdesign/Idontcode-at-Ushahidi

**Potential Mentors: Eriol Fox**

### Outreachy-applicants ### 
For Outreachy-applicants wanting to make contributions as part of the application, we suggest looking through our issues in Platform: https://github.com/ushahidi/platform/issues. Look especially for issues that are labelled "good-first-issue" or "Community Task" but if you find anything interesting you want to work on, please reach out and ask!

To set up your dev-environment, start reading through our docs: https://ushahidi.gitbook.io/platform-developer-documentation/ and especially https://ushahidi.gitbook.io/platform-developer-documentation/getting-started/setting-up-your-development-environment.

**Comment by ridhishjain** [comment]
This idea-list is of 2019. Is there any update regarding 2020? 
Is there any new issue for 2020 list because the main sub-organization page [(of 2020)](https://hub.osc.dial.community/t/google-summer-of-code-2020-dial-open-source-center/920) leads directly to here

**Comment by tuxpiper** [comment]
There's a fresh new batch here @ridhishjain : https://hub.osc.dial.community/t/gsoc-2020-ideas-ushahidi/1026

Going to close this issue for now  :)
