### ISSUE TITLE
Field visual is confusing users and preventing them from completing core field inputs

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform#3486]
All users of platform have problems inputting data into fields that look like this:

<img width="805" alt="Screenshot 2019-03-25 at 10 43 58" src="https://user-images.githubusercontent.com/11681324/54928828-ea327580-4eea-11e9-826d-a77b46ebe73c.png">

Recently it has caused intercom support messages.

If we can change to the standard input devices (ahead of Platform UI refresh project) then this will increase usability for general users and reduce support inquiries.

<img width="1280" alt="Screenshot 2019-03-25 at 09 43 39" src="https://user-images.githubusercontent.com/11681324/54928880-0a623480-4eeb-11e9-9ac1-fea243d456c4.png">

## Reproduce the issue
- Go to Settings -> Users
- Click on "Add new user"
- The problematic input-field is seen on top of the page

## Implementation notes
- Fix in https://github.com/ushahidi/platform-client repo
- Hint :bulb: The code handling users can be found here: https://github.com/ushahidi/platform-client/tree/develop/app/settings/users
- When you are done, 🔀 Start a Pull Request. There are two ways how you can start a pull request:

   1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

   2. You can also[ edit files directly in your browser](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) and open a pull request from there.

- 🏁 When done Ask in comments for a review :)

## Want to work on this issue?🙋 
Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

**Comment by clsoar** [comment]
Is this task open for assignment?

**Comment by Erioldoesdesign** [comment]
@clsoar Yep it sure is! :) 

Do you need any further support or assistance with getting started?

**Comment by clsoar** [comment]
@Erioldoesdesign I will read through the Outreachy getting started info and let you know if I need more help with it.

**Comment by clsoar** [comment]
Can't seem to get the development environment setup. Asked in the gitter forum, but those suggestions didn't work either.

**Comment by Erioldoesdesign** [comment]
@clsoar It's worth asking again in the community gitter forum. A Ushahidi dev might be able to offer more help

**Comment by rowasc** [comment]
Hi @clsoar , checking in...were you able to setup your environment? Do you need help ? 
Thanks!

**Comment by rowasc** [comment]
ah, this was merged already (it was fixed for surveys and it was applied to all the forms) . Closing!
