### ISSUE TITLE
Enhance developer documentation and reference material

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3487]
**Activities**
Build a dedicated developer hub/resources page inclusive of FAQs, security and privacy best practices.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-246

**Comment by Angamanga** [comment]
Consolidate new and all existing resources in a developer hub for ease of access and reference. This would also include building FAQs and educational content such as 101 videos, code samples, and tutorials. 
There will be a specific focus on the developing tutorials and best practices around privacy and security concerns facing our users.

**Comment by RuthAtem** [comment]
Hi, is this issue available? if yes will like to work on it
