### ISSUE TITLE
Move user-manual to gitbook

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3491]
Aha! Link: https://ushahiditeam.aha.io/features/PROD-242

**Comment by Angamanga** [comment]
Belongs to epic https://github.com/ushahidi/platform/issues/3487

**Comment by Angamanga** [comment]
@CeciliaHinga Do you have any idea if this is done or are there parts on .com that needs to be moved over to gitbooks?

**Comment by CeciliaHinga** [comment]
For this exact ticket, we have content on the support page that is not on gitbook, but we are unsure of the best place for them to be. More discussion is needed.

For #3487 I believe this ticket is about the developer doc, you are best suited to confirm this @Angamanga
