### ISSUE TITLE
Provide enhanced manual installation experience

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3493]
## Overview
Assist the manual installation process with step by step validation routines and guidance, and useful error messages.

This will consist of four sub components:

1. platform-client: a few gulp tests for the contents of the .env (and config.json?) files before building (#3549)
2. platform-client: a "Frontend End-to-End validator" web application, that will load in the deployers browser, run all verifications (including API availability) and indicate next steps needed. This will be the most visible component. (#3494)
3. platform: an "Environment verification" PHP page/script , without dependencies, to aid verification of the API serving environment (PHP version, extensions availability, web server configuration) (#3548)
4. platform: a Composer pre-installation hook that verifies Lumen configuration (.env file, database availability, etc.) (#3550)

## Who is it for? Who are the users?
Open Source deployers

## What privacy impacts does it have?
- Does it change the personal data we collect?
No
- Does it expose data that was previously private?
No
- Does it send data to new services? or change how we process it?
Not clear. One possibility is providing deployers with an easy way to report their deployment success / error to a chatroom or intercom. This would always be opt-in and collect nothing else apart from URL (and chat screen name, possibly)
- If privacy impacts are high risk, consider completing an impact assessment per GDPR (https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/accountability-and-governance/data-protection-impact-assessments/)

## Requirements
Provide helper tools that can be used by OSS deployers to:

Obtain a Web and CLI - based feedback for deployers, providing validation and feedback of aspects correctly configured and aspects not correctly configured. If something is not working well, provide guidance on what the next steps should be.

### Who will this be deployed to?
Deployers of Open Source

### What documentation needs to change?
Installation documentation will need to refer to these tools, but we should 

### Who will test this?
TBD

### Where will this be deployed and tested?
TBD

## Dependencies
The point is that these components should have as little dependencies as possible, so they can work in most circumstances.

**Comment by rowasc** [comment]
@tuxpiper I think this should be closed since it'd be the verify composer script? reopen if you disagree :)
