### ISSUE TITLE
Frontend E2E Helper – test API reachability

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3495]
Add logic in the Frontend E2E validator so that:

* BACKEND_URL (or maybe retrieve from config.json ?) are parsed to obtain the URL for the API
* Requests for `/` and `/api/v3/config` are sent and verified
   * Return HTTP status 200
   * Header Content-Type: application/json present
   * Any other checks on content

Aha! Link: https://ushahiditeam.aha.io/features/PROD-240

**Comment by Angamanga** [comment]
@rowasc This is in the `installer-helper` branch, right?

**Comment by rowasc** [comment]
yes :) @Angamanga
