### ISSUE TITLE
Collect contact details from non-logged in users when creating a post

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#350]
"on the ""add a post"" form, the ""enter your contact details"" subheading is misaligned:

http://cl.ly/image/2E002Q3y421v"

**Comment by jshorland** [comment]
I can't replicate this. Can anyone else?

**Comment by willdoran** [comment]
I don't see this either but I'm wondering if this functionality still exists? Was this for guest posting?

**Comment by rjmackay** [comment]
This should appear for non-logged in users. I think we've lost the functionality entirely.. though it was kinda half baked.

I think it'd be good to put back in - otherwise we never have contact details for a post from non logged in users. @jshorland what do you think?

**Comment by willdoran** [comment]
@jshorland @rjmackay *bump*

**Comment by jshorland** [comment]
Agreed. we should put it back in as optional. Where are these stored and retrievable for admin?

**Comment by rjmackay** [comment]
... I don't know if we ever built the admin side. They're stored with each
post, so it should be easy enough to show them alongside a posts detail
view.

On Thu, Mar 24, 2016 at 2:12 AM, Jess Shorland <notifications@github.com>
wrote:

> Agreed. we should put it back in as optional. Where are these stored and
> retrievable for admin?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/issues/350#issuecomment-200339317>
>



-- 
Robbie Mackay

Head of engineering
Ushahidi Inc
m: +64 27 576 2243
e: robbie@ushahidi.com
skype: robbie.mackay
