### ISSUE TITLE
Frontend E2E Helper – API endpoints compliancy tests

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3501]
* Test all these endpoints:
  * `/api/v3/config`
  * POST `/oauth/token`
    * because there's no way for this to know valid credentials, it is expected for this to fail, so we should test for the proper failure
  * `/api/v3/tags`
  * `/api/v3/forms`
  * `/api/v3/features`
  * `/api/v3/map`

Aha! Link: https://ushahiditeam.aha.io/features/PROD-239

**Comment by Angamanga** [comment]
@rowasc @tuxpiper What do we want to check here? If the endpoints reply? Do we want to check the response-strucutre at all?

**Comment by rowasc** [comment]
Reply for sure, and structure would be very nice yes.
