### ISSUE TITLE
Frontend E2E Helper – routing compliancy test

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3502]
Ensure that the server providing the frontend is correctly setup for Angular routing:

* Non-existing files should respond with a 200 and the contents of index.html

Aha! Link: https://ushahiditeam.aha.io/features/PROD-238

**Comment by rowasc** [comment]
>Non-existing files should respond with a 200 and the contents of index.html
would this be non existing frontend files?  . Is this testing that the web server itself is setup correctly?

**Comment by tuxpiper** [comment]
> > Non-existing files should respond with a 200 and the contents of index.html
> 
> would this be non existing frontend files? . Is this testing that the web server itself is setup correctly?

@rowasc , yes this is testing web server configuration. The reason is handling angular routing correctly.
