### ISSUE TITLE
Confusing map popups on post detail map

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#351]
## Expected result:
Map popup on a post detail page should show useful information

## Actual result
Map popup shows the `key` of the survey attribute for the location

<img width="840" alt="screenshot 2016-06-21 09 19 59" src="https://cloud.githubusercontent.com/assets/7965/16210695/8709e7ae-3791-11e6-86f5-161331a00edc.png">

## Steps to reproduce

- Open a post with a location
- Click on the map marker
- See popup open

**Comment by jshorland** [comment]
Is this still a thing @rjmackay? Can't seem to recreate this.

**Comment by rjmackay** [comment]
Yea it is. Only on the map on post detail pages. We're using the posts attribute key instead of some kind of sane label.

**Comment by rjmackay** [comment]
Closing in favor of #1245
