### ISSUE TITLE
Advertise it in different channels. Which channels? and when

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3517]
Which channels are we reaching out to? Identify and reach out!

Update:

Advertised at BelFOSS event 12.04.2019

Need to create a schedule of what comms go out when.

**Comment by Erioldoesdesign** [comment]
Advertise on Mozfest slack?

**Comment by Erioldoesdesign** [comment]
@StaicyG 

Can we collaborate on comms plan for hackathon plz? 

Twitter schedule
Facebook schedule
etc. etc.
