### ISSUE TITLE
Create advertising material/content/texts

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3518]
- Gitbook page
- Emails?
- Tweet/instagram/other channels?

Update:

Assets for various social media done and live here:

https://drive.google.com/open?id=1FaxuPdQdQTI9KJMsjgYfVLN4GDeKlMx5

comms lan TBC

**Comment by Angamanga** [comment]
Meetup-events, social-media banner,

**Comment by Erioldoesdesign** [comment]
Assets all here: https://drive.google.com/open?id=1FaxuPdQdQTI9KJMsjgYfVLN4GDeKlMx5
