### ISSUE TITLE
Schwag for hackathon

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3524]
Incentives? Schwag? T-shirts? 
"I successfully installed the Ushahidi-platform"-pins? Other things?

Here's the cost spreadsheet: 
https://docs.google.com/spreadsheets/d/1hB9ft5liSgitdKHyLxpaMbBoZdbgyVHfJCaJXDGHI44/edit?usp=sharing

Eriol is speaking to June re. costs left to allocate to schwag & postage.

Designs here: https://drive.google.com/drive/folders/1-0kEeqDSsHOH2MuhgdWNNAfObFyZIu7s?usp=sharing

**Comment by Erioldoesdesign** [comment]
Needing the budget for this!
