### ISSUE TITLE
No puedo acceder como usuario 

### ISSUE THREAD

**Issue by ninojohan** [ushahidi/platform#3532]
https://monitor.observatoriopazvalle.gov.co/views/map en este link intento acceder como mi usuario y contraseña registrado  y no me permite hacerlo. POr favor Help necesito ayuda con dicho problema.
Muchas gracias

**Comment by rowasc** [comment]
Hola, Este es un sitio no manejado por Ushahidi.io, es un sistema donde instalaron Ushahidi open source con su propio código modificado.El sistema de login parece que ha sido modificado para hacer login con Auth0 por lo que lo mejor seria contactar a quien lo mantiene para averiguar como usarlo. 
Gracias
 Romina

 @tuxpiper te copio por si tenés alguna idea de quien maneja el sitio o cómo ayudar a @ninojohan

**Comment by tuxpiper** [comment]
Correcto, no gestionamos este sitio y no podemos hacer mucho para ayudar directamente.

En todo caso, parece que esta organización: http://observatoriopazvalle.gov.co/contacto/   es la encargada de la gestión del sitio y quizás sí que podrían ayudar.

Saludos cordiales
