### ISSUE TITLE
Research Twillios voice-api

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3536]
TODO:
- [ ]  read up on Twilio-documentation to find out:
 - [ ] What audio-formats does it provide?
 - [ ] Is it possible to get hold of the audio-file (through for example a webhook or requesting the data)
 - [ ] What is needed for us to talk to the api?
- [ ] Document findings in project plan (https://docs.google.com/document/d/1O3lGKnS0-Xptf_47FYj93NmSx3aCjCZxXTxfA4j8RHQ/edit)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-225

**Comment by UdokaVrede** [comment]
Hi can I work on this for my outreachy contribution

**Comment by hyounes4560** [comment]
Hello, Outreachy Applicant here, can I work on this? @rowasc @Angamanga  Thanks

**Comment by Angamanga** [comment]
@UdokaVrede @hyounes4560 This issue is outdated so closing it now. Please check this link if you find something else to work on: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22

**Comment by UdokaVrede** [comment]
Alright thanks
