### ISSUE TITLE
Posts are successful even when there's no correspoding form.

### ISSUE THREAD

**Issue by Timtech4u** [ushahidi/platform#3543]
**Describe the bug** I am able to make posts to the `api/v3/posts` endpoint even when there's no corresponding form.

**Where was the bug observed** Bug was found on the _api/v3/posts_ endpoint, I made a post request using the API without having any survey(forms) and it was successful.

**To Reproduce** Steps to reproduce the behavior: 1. Make a POST request to the following endpoint `<domain_url>/api/v3/posts` 2. Send an empty request body, or send an invalid character with the request (ie use “ quotation marks instead of " in your JSON) 3. Check the _Data_ on your Ushahid Platform, you'll see the submitted posts as mine below:

**Screenshots** [https://user-images.githubusercontent.com/11256481/58759588-51d8f280-8524-11e9-93d6-43bae49216dc.png](https://user-images.githubusercontent.com/11256481/58759588-51d8f280-8524-11e9-93d6-43bae49216dc.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-223

**Comment by AriannaLanz** [comment]
Looking at this one!

**Comment by rowasc** [comment]
HA. I was just trying to repro this in case you needed help... *fun fact*:  This can only be reproduced by either sending an invalid character (notice the difference between " and “ ) OR sending an empty body in the request. It's not related to the form ID itself but to  fact that the validation is being skipped/ passing essentially if the body is empty (!!!!!)
