### ISSUE TITLE
Client pre-build checks

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3549]
Add a routine in the build process that checks:

* If the .env file exists, whether the file is readable and has no formatting errors
* Whether the BACKEND_URL variable is set. This can be because it's provided via the .env file, or directly in the environment variables of the process
* Whether the TX_USERNAME and TX_PASSWORD variables (Transifex credentials) are set.

## Console outputs (better if we make this coloured so that they stand out in the output)

* Error, if no BACKEND_URL is available
* Info, prominently displaying the BACKEND_URL that the build is being made for
* Warning, if no Transifex credential variables are set, clarifying that only English language will be available, and if a multi-language interface is required, a Transifex account is necessary.

## Expert mode:

* If the env variable USH_DISABLE_CHECKS is set, skip all this

## Implementation approach:

I see two alternatives here,

1. A program separate from gulp, that is invoked via npm by a specific hook
2. Additional step in the gulp chain

**Comment by rowasc** [comment]
I think it might be worth doing a multi-value DISABLE_CHECKS . 
So you can disable verifications at a more granular level. 
Example of how this would look like (based on the initial work for this) . It's easy to disable ALL, but allows you to decide if you just don't want to check network for instance but still want to check the rest. The use case for this is if you don't have the backend yet for example but want to ensure the rest is ok, or if you don't want to see the TRANSIFEX warnings but want the rest of the checks. 

<img width="1259" alt="Screen Shot 2019-07-23 at 10 44 23" src="https://user-images.githubusercontent.com/2434401/61692739-daab2800-ad36-11e9-9f0b-01c5086eedcc.png">

random:that babel/register error is annoying and it's been there forever. Trying to find why its happening

**Comment by tuxpiper** [comment]
I like this 👍

**Comment by tuxpiper** [comment]
Can we say this is ready for review @rowasc ? We should move the issue to the appropriate column

**Comment by rowasc** [comment]
Yea I think this should be enough for this ticket, but I believe @Angamanga  worked on top of it and added compliance checks , so we probably want to wait to merge until that part is done

**Comment by Angamanga** [comment]
@rowasc @tuxpiper Yes, lets wait, planning to be done today with this
