### ISSUE TITLE
API pre-install hook – check presence and contents of .env file

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3552]

**Comment by tuxpiper** [comment]
* Parse .env for correct format
* Ensure the following are set:
    * `APP_KEY`
    * `CACHE_DRIVER`
    * `QUEUE_DRIVER`
* If MAINTENANCE_MODE is set, print a warning

**Comment by rowasc** [comment]
lets sync once you are back from vacation :) 
started some prototypey things for this in the `installer-helper` branch 
<img width="1369" alt="Screen Shot 2019-08-04 at 12 06 42" src="https://user-images.githubusercontent.com/2434401/62425368-6bc3bc80-b6b0-11e9-9eb0-8121355cc0da.png">

**Comment by tuxpiper** [comment]
I had something like this in my local, but your progress looks better @rowasc  :+1: I'll discard what I had

**Comment by rowasc** [comment]
ah alright. Should I continue with the other backend API tickets or do you have some WIP I should look into?

**Comment by rowasc** [comment]
Closing since we merged the helper 🎉
