### ISSUE TITLE
Switching languages: settings save button remains in the last language used until page is reloaded

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3555]
**Describe the bug**
I changed from Arabic to English and the Save button in settings is not in English until I reload the page. The same happened with English to Spanish

**Where was the bug observed**
https://rominacsvsms.ushahidi.io/settings/general

**To Reproduce**
As an admin: 
1. Go to Settings -> General . Change language to Spanish (or some other language that isn't the current site's language)
2. The save button is still in English, not Spanish
Note that when you reload the page, it's fixed.

**Expected behavior**
4. The Save button is in Spanish 

**Is there a workaround? What is it.**
Reload the page after the change and the save button is now in English

**Screenshots**
<img width="1678" alt="Screen Shot 2019-06-07 at 18 38 22" src="https://user-images.githubusercontent.com/2434401/59134960-92d16c80-8953-11e9-891d-41e13b71b908.png">

**Desktop Hardware Details (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 75.0.3770.80 (Official Build) (64-bit)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-217

**Comment by Angamanga** [comment]
@rowasc @Erioldoesdesign Doing the last fix on this (same pr as Romina started), but am a bit confused, should the language switch immediately or after save? Also, if an admin already selected a language in map-view, should that language persist for that particular user, or should it change if that user goes to general-view and select a new language? 🤔

**Comment by Erioldoesdesign** [comment]
Hmm a few questions here that really, will be best guesses.

- Yes I think the language should change before you hit (english) 'Save'.
(Though note: there will be people that switch by mistake and might not know say...the Russian, Korean etc. for 'save' and therefor get stuck in a language they don't know.) The fix here is for the save button to have an icon alongside the text. Floppy disk is still the accepted 'save icon' though most younger people have no idea what that is anymore.

- Deployment owner has 'set' a language. This should be the language the deployment is seen in to avoid mis-translations of language. There's then an effort for the person who may want to take say, Arabic to English to use either a browser extension or another tool to translate. Essentially what we don't want here is for the deployment owner or Ushahidi to be responsible for potentially incorrect translations and for that responsibility to be on the user needing translation.
This isn't 'User easy/friendly' per say but I'm prioritising the deployment owners rights to set a language over 'tourists of deployments'

Have I answered @Angamanga ?

**Comment by Angamanga** [comment]
@Erioldoesdesign Yes, mostly. For nb 2, there is a way for all users to select their preferred language in the map-view, do you think we should remove that? (I guess that becomes a whole other issue though). My question for this was:
1. The admin setting up the deployment set their preferred language for themselves in the map-view then
2. goes to the general-view and set the language for the deployment
3. if the user-selected language in map-view for that admin is different from the language they set for the deployment, which one should the user then see when selecting a language in the general-view? That was my question :) Its a bit tricky to explain, I can talk you through it as well if that's easier...

**Comment by Angamanga** [comment]
@Erioldoesdesign Also, do you know if we have access to other icon-sets that include the floppy-disk? It's not included in the ones we have in the pattern-library :/
