### ISSUE TITLE
Cache form submissions/changes when users are offline and send them when they come back online

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3556]
When a user is offline we should ask them if they'd like to queue the requests for when they are back online and send them then.

- User goes offline
- Show a warning https://github.com/ushahidi/platform/issues/389
- If they try to submit a form (or they execute other POST/PUT actions), show a popup that asks them if they'd like to queue it for later
- When users come back online, send the requests
    - When resources are all created show a popup or something else that lets them know the successful completion of this actions. 
   - If we fail to create or edit resources, let them know so they can act on this informaion

I think this should wait until we make the API more friendly, especially submitting posts and creating surveys. Once these actions don't depend on many requests it'll be much simpler to "explain" to users what exactly failed in a request ("the form could not be created" instead of potentially "this attribute of your form wasn't submitted correctly" which is not something a user would understand or be able to act on )

Aha! Link: https://ushahiditeam.aha.io/features/PROD-216

**Comment by Erioldoesdesign** [comment]
I think there needs to be a wider 'offline working' conversation around platform that happens soon. So many users are either without stable connections or have to choose what to do when they have one that it's kind of a critical feature for Ushahidi to stay competitive against tools like Kobo toolbox etc.

**Comment by rowasc** [comment]
Yea, offline features are going to be important.  The mobile app has some offline support, but the web doesn't have any.
