### ISSUE TITLE
Review API docs in gitbooks for completeness

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3558]
Review that our https://docs.ushahidi.com/platform-developer-documentation/tech-stack-overview/api-documentation covers all the required endpoints and add anything missing

Aha! Link: https://ushahiditeam.aha.io/features/PROD-215

**Comment by anje123** [comment]
@rowasc  the page could not be found. i think you mean this https://docs.ushahidi.com/platform-developer-documentation/tech-stack/api-documentation
