### ISSUE TITLE
Feature: Add new Field upload file is missing (was in ushahidi2)

### ISSUE THREAD

**Issue by ahmed-aly-aut** [ushahidi/platform#3564]
![screenshot_8](https://cloud.githubusercontent.com/assets/2486446/12293511/5dcb2404-b9f4-11e5-9181-768e7d14fc77.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-716

**Comment by Erioldoesdesign** [comment]
Curious to know what kind of fields were added in v2 that aren't present in the roster of v3 fields? and for what purposes.
