### ISSUE TITLE
Bring the test environment up [platform]

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3569]
https://ushahidi.slack.com/archives/C03UU507R/p1559938300001700?thread_ts=1553274953.005500&cid=C03UU507R

Opening a ticket to track this work of bringing the test environment (one of them) back up.

**Comment by rowasc** [comment]
This is required for ISOOKO, we have a deadline coming up next month and need to get this tested way ahead of time in case there are adjustments we need to make .

**Comment by rowasc** [comment]
@tuxpiper assigning a ticket for the test environments we discussed in slack. Can you let me know if you have a general idea of when you'll be able to work on this so I can plan Walter's time?. Thanks! 
cc @Nthiga @Obadha2 for awareness since Monica is leading the project and Walter is took the lead on QA and implementation for this deliverable.

**Comment by tuxpiper** [comment]
@rowasc I think I'll take care of this tomorrow / Saturday

Any particular branches that we need to deploy for a start? Or just "develop" across the board?

**Comment by rowasc** [comment]
Thank you 🙌  
Develop is fine , and I can just switch the branch if I need to afterwards, right?

**Comment by tuxpiper** [comment]
>  Develop is fine , and I can just switch the branch if I need to afterwards, right?
Yes, you should be able to do that in the deployment director rules repo

**Comment by tuxpiper** [comment]
ah, one more Q @rowasc, this is for Isooko but it needs all the cloud platform stuff?

**Comment by rowasc** [comment]
ah. mmmm.... this is in isooko.ushahidi.io, so a release  to prod will impact all deployments , which is OK since it's a generic bug (not sure if that helps?) . 
I'd just bring up the test environment with cloud stuff probably so we have it to continue testing platform post-isooko as well (when we all come back)

**Comment by tuxpiper** [comment]
everything well here @rowasc ? Can we close?

**Comment by rowasc** [comment]
thanks @tuxpiper this worked 🎉
