### ISSUE TITLE
Deployment creation error should be user friendly

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3570]
**Describe the bug**
When I create a new deployment , while the deployment is created I should get a message that says something like "Deployment is being created" instead of a database error

**Where was the bug observed**
Creating a new deployment in production (Ushahidi.io)

**To Reproduce**
1. Go to ushahidi.io and create a new deployment
2. See the error with a database  message

**Expected behavior**
2.. See a "deployment is being created" message that lets the user know something good is happening. 

**Is there a workaround? What is it.**
No, but the deployment will be created, so it'll work but its confusing and ugly.. 
**Screenshots**
![bug](https://user-images.githubusercontent.com/2434401/59856668-c5189c00-934d-11e9-82b7-a671bcff698e.png)

**Additional context**
https://ushahidi.slack.com/archives/C024G437R/p1561005746000800

Aha! Link: https://ushahiditeam.aha.io/features/PROD-212

**Comment by StaicyG** [comment]
https://app.intercom.io/a/apps/hl5rfiga/inbox/inbox/unassigned/conversations/22538882198

**Comment by StaicyG** [comment]
https://app.intercom.io/a/apps/hl5rfiga/inbox/inbox/465263/conversations/22472263625

**Comment by Erioldoesdesign** [comment]
"deployment is being created" is good prompt text but what action do they need to take next?

Wait 10 minutes? (receive an email when it's ready? can we tell when it's ready?)
Refresh the browser?
Close the window, go back to Ushahidi.com and login via login button? (what i did to solve this!)
All of the above?

Lets give the user the best/fastest series of actions to get them to their deployment

**Comment by rowasc** [comment]
Yea that's a good point. 
There's nothing they can do except wait right now , so I guess we need to tell them that?

**Comment by Erioldoesdesign** [comment]
@rowasc indeed! Would you like to provide some more official designs/copy etc.?

**Comment by rowasc** [comment]
yes totally.
