### ISSUE TITLE
Changing the default location via clicking on the map in /settings/map-settings

### ISSUE THREAD

**Issue by gausam** [ushahidi/platform#3573]
### Expected behaviour

Taking experience from other sites with maps, I clicked on my desired default location on the map expecting the market to then move there. It was after some fumbling that I discovered the only way to move the marker is by dragging it. I don't have a problem with that of course, but maybe even some text somewhere telling the user to drag the marker would be of help - because several other people could be used to clicking and having markers drop there (like on GMaps)
### Steps to reproduce the behaviour/error
- Navigate to /settings/map-settings and click on a location on the map where the marker isn't.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-700

**Comment by Erioldoesdesign** [comment]
We should consider supporting both these interactions and should put this through usertesting to observe the ratio of interaction, as well as, of course, including contextual helper text. 👍

**Comment by rowasc** [comment]
This works this way now.

**Comment by rowasc** [comment]
@allcontributors add  gausam for bug
