### ISSUE TITLE
Improve validation error messages

### ISSUE THREAD

**Issue by samtheson** [ushahidi/platform#3574]
### Expected behaviour

The messages must be more legible for non-technical users
### Actual behaviour

![js error](https://cloud.githubusercontent.com/assets/958800/14130535/e4058516-f633-11e5-9403-a3205c2bde93.png)
### Steps to reproduce the behaviour/error
- For the above, add a required date field to a step
- Then trigger validation by selecting another value in the `Who can see this dropown` ([why?](https://github.com/ushahidi/platform-client/issues/148))

**Comment by rowasc** [comment]
Closing since we are already handing validation (and this refers to old versions of platform) . There are however some specific validation issues to be handled (ie CSV imports) in other tickets

**Comment by samtheson** [comment]
SGTM Romina 👋

**Comment by Erioldoesdesign** [comment]
Error messaging as a whole should be reviewed in an epic at some point...
