### ISSUE TITLE
[Test environment] Unable to enter credit card details

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#3580]
**Describe the bug**
Fields on credit card information form are unresponsive when user clicks on them in an attempt to enter their credit card details. 

**Where was the bug observed**
Deployment - isooko-test
URL - isooko.steve-buscemi.ush.zone 
Test Environment - steve-buscemi

**To Reproduce**
1. Log into a deployment you've created.
2. Navigate to settings, then plans.
3. Click on Sign Up under the Ushahidi Basic tab.
4. This will ask you to re-enter your password. Do so.
5. A page is brought up with a payment information form containing credit card fields.
6. Try clicking on any of the fields, no response.
7. User is unable to type or enter any data in the fields.
8. If user clicks on Continue without having input card details, they see an error message "Could not process payment: Cannot change the subscription as there is no valid card on file"

**Expected behavior**
Credit card fields should be responsive. User should be able to click on and enter their details.

**Is there a workaround? What is it.**
None.

**Screenshots**
![Screenshot from 2019-06-27 16-34-37](https://user-images.githubusercontent.com/38259840/60343106-e74c9280-99bb-11e9-8fee-500718e1d820.png)

**URL / Environment where this happened**
isooko.steve-buscemi.ush.zone

**Desktop Hardware Details (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Google chrome
 - Version 75.0.3770.100

Aha! Link: https://ushahiditeam.aha.io/features/PROD-209

**Comment by rowasc** [comment]
@Obadha2 would you mind checking if this can be repro'd in production? Thanks

**Comment by Obadha2** [comment]
@rowasc This does not happen on prod.

**Comment by rowasc** [comment]
oh; Wow maybe it's a PL issue  with the deploy. Ok I'll just add it as something for checking next week then since it doesn't really affect our changes this week phew.
thanks

**Comment by Obadha2** [comment]
Yeah I thought this had been created. @rowasc

**Comment by rowasc** [comment]
ah alright , I'll triage this and prioritize when it's more clear when I should get to it since the situation changed internally and I need to decide that still. Thanks!
