### ISSUE TITLE
Any ride-sharing crashes in China?

### ISSUE THREAD

**Issue by mhuiying** [ushahidi/platform#3581]
If one could look into the Chinese news, there must be more ride-sharing crashes.

**Comment by rowasc** [comment]
Hi there, thank you for getting in touch.
If you are looking to gather data on ride-sharing crashes, please feel free to start a deployment with [Ushahidi Platform's SaaS service](http://ushahidi.io/create), or by installing the platform in your own environment following [one of our installation guides](https://app.gitbook.com/@ushahidi/s/platform-developer-documentation/getting-started)  

I'm going to be closing this issue for the moment as this is not a bug report, feature request or question about the Ushahidi platform. 

Please join us in http://gitter.im/ushahidi/Community or comment in this issue to reopen it if you require assistance. We'd love to see what you create or assist with any further questions. 

- Romina
