### ISSUE TITLE
Developer FAQs

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3582]

**Comment by Angamanga** [comment]
@rowasc I started a FAQ here: https://app.gitbook.com/@ushahidi/s/platform-developer-documentation/~/drafts/-LiSTOcFX8mTI-sF51yV/primary/

**Comment by rowasc** [comment]
https://app.gitbook.com/@ushahidi/s/platform-developer-documentation/~/drafts/-LiSTOcFX8mTI-sF51yV/primary/frequently-asked-questions

added answers to all the pending questions ! LMK what you think :D @Angamanga

**Comment by Angamanga** [comment]
Thaaank you @rowasc!! Looks good! I will restructure the questions a bit and then we can check this off for now, we just need to remember to add more questions when we get them...

**Comment by rowasc** [comment]
@Angamanga is there a FAQ that is not for developers? 
We just run into an issue with @Erioldoesdesign where they could not create deployments because of some chrome extension interfering with the website and it might be good to add that to a general "know issues" FAQ, I think?
