### ISSUE TITLE
Platform coding standards

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3587]
*Todo*
- Go through our linter-files. Does anything need update? Can we throw out some old linting-files?
- Link to the linterfiles in the docs
- Guides/links to guides on how to setup linters for popular editors

**Comment by rowasc** [comment]
document how to setup the linters for most popular editors

**Comment by Angamanga** [comment]
Step 1: Translated our linters to an eslint-file

**Comment by rowasc** [comment]
awesome.Thanks Anna ! 
Should we remove the old linter configs then?

**Comment by Angamanga** [comment]
Nah, I think we can keep them too in case someone has configured their editors. And its used by the pre-commit-hook. I just wanted to provide an eslint config too since its more common nowadays....
