### ISSUE TITLE
Design process documentation

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3592]
Eriol: This will be a reasonably simple piece of documentation for now and largely will link to the Open Design processes/methodology. It'll most likely be a step by step recommendation on how to design a feature and an improvement for platform.

This could also be very good for onboarding any designers on staff :)

This can get much more complex in future grants/tickets though.

**Comment by Erioldoesdesign** [comment]
Also covering this in the Open Design work here: https://github.com/ushahidi/opendesign/issues/112

**Comment by Erioldoesdesign** [comment]
Draft, needs headings and sections and screenshots and also, proofreading for design jargon and copy clarity.

### Ushahidi Design process

Ushahidi has a design process that aims to include user voices as the key component for design insight. As such, all design work relating to a Ushahidi product must have sound user rationale or direct user voices. The ultimate aim of design within Ushahidi is to listen, interpret, facilitate and raise voices of users directly operating the software with the direct responsibility in improving the usability, accessibility, visual design, brand recognition, interaction and purpose of that feature through the medium of design.

Designs and prototypes created in design tooling by there nature are as accurate to the coded experience as possible. There is a likelihood that some pixels may shift, some colours may by a hex code out or a form element may have a slight difference. Unless explicitly detailed as a design decision, the patterns existing in the Ushahidi  (and other Ushahidi related properties) Pattern libraries are to be the true and accurate construction elements of an Ushahidi interface.

[Pattern library link here]

[Pending, a working file 'sticker sheet' of Ushahidi platform]

Depending on the complexity of the issue needing design work there are approximately three approaches Ushahidi takes to design.

1. Dev design
2. Light design
3. Heavy design

## Dev design
In certain circumstances, 1st draft of UI or design layout can be done by the development team using existing patterns, brand guidelines, and relevant frameworks. This allows for an agile approach to development where a feature or product needs to be live and useable quickly. 

This 'dev design' will be able to gather live user feedback and be a 'living testable product'. Design is then responsible for monitoring, tracking and developing any design changes that would improve this 'dev design' for users. Where able, producing a user test script (link to example) and conducting in-person or remote user testing on the 'dev design' will help to move the feature/product forward in usability.

The developers at Ushahidi should be empowered to make appropriate design choices when working on a feature. For example, if design dictates a certain layout for a form element and the existing pattern for the form element is slightly different, unless the change to the element is trivial in terms of dev time or the specific design has usability/accessibility impact using the existing pattern for the element is acceptable.

[Screenshot of pattern library, Ionic framework, and any dev design work from the past]

## Light design

Light design describes a feature or issue which is a small element, interaction or UX challenge. Typically not part of a larger series of screen flows these design tasks should not take an extended period of time to complete and can typically be completed using design knowledge, existing user behavior knowledge and good design practice [link good design practice in a separate issue/section]

Light design may or may not include user testing. Usertesting should be completed if there is a strong difference in design opinion on how to execute the design. User testing and insight should be impartial and test as accurately as possible for a user-initiated solution.

Light design can also benefit from live testing or in the future A/B testing.

tbc....


## Heavy design

This is like for reals the big stuff (coming back to this at a later date.

**Comment by Erioldoesdesign** [comment]
Moving this into Gitbooks!

**Comment by Erioldoesdesign** [comment]
This is all under review ATM 💐

**Comment by Erioldoesdesign** [comment]
Reviewed and merged into gitbooks! closing <3
