### ISSUE TITLE
Sample design code and wireframes 

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3593]
Anna & Eriol talked about using HDX as the good practice example here as it has a really comprehensive and robust set of prototypes, processes, usertesting and dev/design collaboration as well as a clear path for improvement tickets.

**Comment by Erioldoesdesign** [comment]
Tagging  @rowasc just as an FYI that we're using HDX as our example for this :) no actions. Just FYI

**Comment by Erioldoesdesign** [comment]
This is completed in the gitbooks and in a separate issue (sorry I should have put it here really!)
https://github.com/ushahidi/platform/issues/3680
