### ISSUE TITLE
Sample code for different configuration eg. SMSsync?

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3594]

**Comment by rowasc** [comment]
sample code? wait I don't think I follow here . I thought this was about documenting how to setup SMS . Can you expand? :( sorry

**Comment by Angamanga** [comment]
@StaicyG @Erioldoesdesign I don't remember what we discussed about sample-code (although I remember it made total sense :D ). Was it setup-config? Or something else more code-related?

**Comment by Erioldoesdesign** [comment]
@Angamanga ...I actually...don't remember? 😅 oh dear.

I think we just wanted to have things people could copy/paste into their environment to try something out? was that it? Kind of like the lowest effort sandbox...
