### ISSUE TITLE
Tutorial videos 

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3595]
Eriol: These are general tutorial videos for Platform.

I think theres a really good opportunity to work with https://advocacyassembly.org/en/ to publish these videos on their platform too

**Comment by rowasc** [comment]
@Obadha2 when you are done with the QA docs, could you do the video tutorial for setting up platform in *linux* (ie over an Ubuntu install)? 
Ask @Angamanga for the correct script to use . 
Thanks !!!
