### ISSUE TITLE
Add versioning to gitbooks

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3596]

**Comment by Erioldoesdesign** [comment]
Is this something perhaps @tuxpiper could look into 🤔

**Comment by tuxpiper** [comment]
Actually we figured this out with @Angamanga , there is a way right in the gitbook UI for creating a new release.

This is what it looks like today:

![2019-07-09 10 40 37](https://user-images.githubusercontent.com/467393/60873112-1c67a900-a236-11e9-86ab-8e558c1743f8.gif)

**Comment by Erioldoesdesign** [comment]
Awesome! We can close this ticket but I suggest we add an agenda item on a DIAL call to cover it to be sure everyone knows how to do it :)
