### ISSUE TITLE
Launch DevHub

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3598]
Todo:
- Do a comms-plan and make some noise about devhub!

**Comment by Erioldoesdesign** [comment]
Eriol is looking after some of this while Anna is on Vacay 💖

**Comment by rowasc** [comment]
can we close this one ?

**Comment by Angamanga** [comment]
@rowasc No I would like to keep it until we have done some communication and noise about it.

**Comment by Erioldoesdesign** [comment]
@Angamanga what can I do to support this? Can I provide some Adobe XD templates for social media banners that will help not just this kind of promo but hopefully more promo in the future? 

(also would be great open source design issues ;))

**Comment by Angamanga** [comment]
@Erioldoesdesign Not sure if more promo is happening for the devhub... but those kind of banners would be great to have + if they can be open source design-issues = 🎉 🎉 !!

**Comment by Angamanga** [comment]
@Erioldoesdesign We could close this and create new issues for os-design?

**Comment by Erioldoesdesign** [comment]
@Angamanga sounds like a plan! ❤️

**Comment by Angamanga** [comment]
@Erioldoesdesign <3 Closing!
