### ISSUE TITLE
Design and where to place frontpage/landingpage

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3599]
Eriol: This is largely the Information Architecture of the devhub I believe as well a possible banner template/format for pages and any styling that can be achieved easily in gitbooks.

**Comment by Erioldoesdesign** [comment]
WIP design prototype is here:

https://xd.adobe.com/view/39c8d206-dc39-4bb5-7230-549f51ecf47d-4ff9/?fullscreen


As ai work on this I'll update the file/link :)

**Comment by Erioldoesdesign** [comment]
@Angamanga So you can see on the prototype link currently a proposed IA re-structure with some renaming of pages and section headings: https://xd.adobe.com/view/39c8d206-dc39-4bb5-7230-549f51ecf47d-4ff9/?fullscreen

Designs for a 'homepage' with rectangle modules would work by linking to these new sections from a homepage but I would say for now, let's avoid some of the logic based pages where we ask people to click a statement to be better directed to a section that's relevant to them. That is pretty above and beyond for this I think? 

if you want to do this though, let me know but I think working through this will take a few days and quite a few new pages of docs to better direct people.

**Comment by Angamanga** [comment]
Thaank you! Focusing on this today 🎉

**Comment by Angamanga** [comment]
@Erioldoesdesign The new structure is to be found here: https://app.gitbook.com/@ushahidi/s/platform-developer-documentation/~/drafts/-Lo0vWqSwJqUJH72L4p9/primary/ (hope it shows up, otherwise its a draft in our gitbook/developers docs). For the boxes, I would love to try out a few of them, at least some on the front-page, we could try with more general ones for contribution and installation:
- I'm interested in installing and hosting the Ushahidi Platform
- I'm interested in contributing code to the platform
- I'm interested in doing QA
- I'm interested in design (or contributing with design?)
- I'm interested in writing docs
(oops they became a whole list 😬 ) Is it doable you think? It gives a bit more life to the docs in general? + the banner "Welcome to the Ushahidi dev hub"?

**Comment by Erioldoesdesign** [comment]
For sure Anna! Here are the image files: https://drive.google.com/drive/folders/1rV1Mmxoyjz-U7u9Z9W0Hr6B0IwdY__Nf?usp=sharing


The structure is looking so good! I think I made a mistake in hiding the Design documentation in a drop-down arrow in the structure so I think design docs need to go like this:

<img width="481" alt="Screenshot 2019-09-05 at 18 03 45" src="https://user-images.githubusercontent.com/11681324/64363010-85d22100-d007-11e9-92bb-532136695d64.png">

So the only 'hidden' thing is the design example templates.

**Comment by Erioldoesdesign** [comment]
Updated prototypes link:https://xd.adobe.com/view/39c8d206-dc39-4bb5-7230-549f51ecf47d-4ff9/?fullscreen

also all the banner .pngs: https://drive.google.com/drive/folders/1zte3-51GB1qlDYT4RfqAlFO9yMvi05IP?usp=sharing
