### ISSUE TITLE
Delete confirmation appears when user submits a response to a survey.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3604]
**Describe the bug**
When user hits save to submit response to a survey, Delete confirmation is seen momentarily. The entry is submitted and saved successfully, but this can be a bit confusing for the user.

**Where was the bug observed**
Deployment - https://isooko.ushahidi.io/views/map

**To Reproduce**
1. Go to submitting a response to a survey on Platform. (Data -> + button -> Select a Survey to submit a response)
2. Fill in the fields on the form. Hit Submit.
3. Observe closely as the Delete confirmation appears momentarily at the bottom of the page.

**Expected behavior**
Delete confirmation should not appear at any point during submitting a response process.

**Screenshots**
![Screenshot from 2019-07-04 12-47-12](https://user-images.githubusercontent.com/38259840/60809745-0ef9e280-a194-11e9-967a-3babda627ef9.png)

**Desktop Hardware Details (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 75.0.3770.100

**Additional context**
I had to zoom my browser in to 50% to be able to see this on a 1280 x 720 resolution screen.

**Comment by Angamanga** [comment]
@Obadha2 Could you QA in Steve Buscemi?
Testing-checklist:
1. Go to submitting a response to a survey on Platform. (Data -> + button -> Select a Survey to submit a response)
2. Fill in the fields on the form. Hit Submit.
- [ ] Observe closely, the Delete confirmation should not appear momentarily at the bottom of the page.

**Comment by Obadha2** [comment]
QA'd, passes. :+1:
