### ISSUE TITLE
Can't type (URL) into video field, can only copy-paste.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3613]
**Describe the bug**
The video field on surveys only allows user to copy-paste, they can not type in.

**Where was the bug observed**
https://test-deployment.steve-buscemi.ush.zone/ 
https://rominacsvsms.ushahidi.io/

**To Reproduce**
1. Go to a survey that has a video field in the form.
2. Click + to add a response to the survey.
3. Scroll to the video field, and attempt to type into it.
4. Note that after the first character has been typed in, user is notified that it does not match a YouTube or Vimeo URL format.
5. User can copy-paste a URL into the field.

**Expected behavior**
User should be able to type in more than one character in the video field, in the off chance that a user decides they want to type in instead of copy-pasting.

**Is there a workaround? What is it.**
Have your URL ready, paste it into the video field.

**Desktop Hardware Details (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome browser
 - Version: Version 75.0.3770.142

**Comment by noone0212** [comment]
Hi @rowasc! Can I work on this issue?

**Comment by rowasc** [comment]
absolutely, thank you @noone0212 !

**Comment by rowasc** [comment]
@Obadha2 this needs QA (in steve)
Thanks!

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Comment by Obadha2** [comment]
@rowasc There's an issue where some of the guiding or hinting text is missing.....It says
"Enter a ...... or ........ video URL"
See screenshot for more information:
<img width="1159" alt="Screenshot 2020-04-01 at 10 30 17 AM" src="https://user-images.githubusercontent.com/38259840/78110673-14731900-7404-11ea-9377-804898ef6824.png">
PS: This is happening in prod, too.

**Comment by rowasc** [comment]
oooo :( Ok thanks. Will schedule fixes!

**Comment by rowasc** [comment]
Fixed by Anna
