### ISSUE TITLE
Custom Icons for Map Markers

### ISSUE THREAD

**Issue by yuchenglin** [ushahidi/platform#3618]
I want to add a feature about displaying custom markers to distinguish different users or ... based on `/platform` getting from db. 
Are there vector icon library and marker design which are decided to adopt?
Thanks!

Aha! Link: https://ushahiditeam.aha.io/features/PROD-693

**Comment by Erioldoesdesign** [comment]
@rowasc I'm pretty sure this is a dupe...we have a ticket for something like this elsewhere done by Charlie. It has some detailed user research insight in the ticket comments too....

Here: https://github.com/ushahidi/platform/issues/1941

What do you think?

Theres also this?

https://github.com/ushahidi/platform/issues/1436
