### ISSUE TITLE
Add unit tests to user profile update

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3625]
This should cover Session update after the user saves the profile

**Comment by individual-it** [comment]
@rowasc I could work on that if the issue is still current. Could you point me to the classes/functions that you want to get tested?

**Comment by rowasc** [comment]
@individual-it thanks so much!
https://github.com/ushahidi/platform-client/blob/develop/app/common/user-profile/user-profile.directive.js I think this flow was what triggered this ticket (it's been too long 😬 ) 
Essentially the update when users change their account details

**Comment by individual-it** [comment]
@rowasc PR with tests in https://github.com/ushahidi/platform-client/pull/1472
