### ISSUE TITLE
Styles for saved-search-filter-dropdown-bug icons is broken on rtl

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3635]
### Expected behaviour
Styling for saved searches in the filter-dropdown on rtl-mode should look like saved-searches on ltr-mode but in the opposite way.
![Screen Shot 2018-04-18 at 11.12.58.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/956bee7d-9fe1-4e88-a2ac-1d7e11785ee9)

### Actual behaviour
Styles are messed up
![screen shot 2018-04-20 at 09 49 20](https://user-images.githubusercontent.com/8624777/39037283-48a03df8-4480-11e8-9aca-01fe36ab02bc.png)

### Steps to reproduce the behaviour/error
Add a couple of category-filters with child-categories. Look at the bug-icons

Aha! Link: https://ushahiditeam.aha.io/features/PROD-364

**Comment by CeciliaHinga** [comment]
Is the error, having both the child and parent category appearing?
