### ISSUE TITLE
Action dropdown on post-detailed is cut off by the post-list in data-view on rtl

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3638]
### Expected behaviour
The whole action dropdown should be visible when clicking ... on a post

### Actual behaviour
![Screen Shot 2018-04-18 at 12.00.58.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/59a087b5-ab59-408c-8fe5-ad69220d356f)
### Steps to reproduce the behaviour/error

Aha! Link: https://ushahiditeam.aha.io/features/PROD-361

**Comment by lalidiaz** [comment]
Hi, I am Outreachy applicant... may I work on this please?

**Comment by Angamanga** [comment]
@lalidiaz This issue need triage and is not open for the community, so in this case, no. However you can check the other tickets in the community-task, hacktoberfest and outreachy labels. Thank you!

**Comment by rowasc** [comment]
hmmm yea I think this isn't happening anymore, I can't repro at all. CLosing!

**Comment by rowasc** [comment]
I could repro it. Ok tagging for community and assigning @lalidiaz ! Thank you 
Make sure you test with a RTL language (ie Arabic ) or it won't happen to you :)

**Comment by Angamanga** [comment]
@lalidiaz This might require changes in the css. Our css lives in the pattern-library, check out how to set it up here: https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/setting-up-the-pattern-library-for-development
