### ISSUE TITLE
Setting time in post-edit in posts is buggy

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3640]
### Expected behaviour
The time set on a date-time field in a survey is showing the same time as the user selected.

### Actual behaviour
The time is converted to UTC and displays as UTC but there is no mentioning of it and it is confusing and it looks like the wrong time is displayed to the user.  This only affects date-time-fields in a survey, not the post-date box where you can set the date for a post

#### Does not affect times set in this box:
![Screen Shot 2018-04-23 at 14.20.06.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/d3daa379-ff69-4a5c-b505-82a0d6fa2bd6). 

#### Only this box:
![bug.gif](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/eca16018-8a51-4731-b3f8-67b8d3f9f1ab)/

### For internal use
Aha! Link: https://ushahiditeam.aha.io/features/PROD-356

**Comment by husar** [comment]
Hello, i would like to work on this issue if it is still open. Please assign it on me.

**Comment by rindy22** [comment]
Hello, i would like to work on this issue if it is still open. Please assign it on me.

**Comment by Angamanga** [comment]
@rindy22 Yes it is still available! Please go ahead and reach out if you get stuck or need any clarifications! Thank you for your interest! 🎉

**Comment by UdokaVrede** [comment]
Hi is this still available

**Comment by Angamanga** [comment]
@UdokaVrede Hi there! Please go ahead, we have not had time to write further instructions on this issue, so if you need guidance, let me know :)

**Comment by Angamanga** [comment]
@UdokaVrede Hi there! Please go ahead, we have not had time to write further instructions on this issue, so if you need guidance, let me know :)

**Comment by UdokaVrede** [comment]
The steps to reproduce these error leads to this page, Am I to sign in, how please

**Comment by Angamanga** [comment]
@UdokaVrede Ahh, that link is internal so you don't need to worry about that one. Sorry for the confusion, it happened to appear right under the "Steps to reproduce". Adding steps now :)

**Comment by UdokaVrede** [comment]
Alright awaiting the steps, thanks

**Comment by Angamanga** [comment]
Closing in favour of https://github.com/ushahidi/platform/issues/4162
