### ISSUE TITLE
See new posts-button is off on rtl

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3642]
### Expected behaviour
New-posts button should cover the whole column in rtl-layout
### Actual behaviour
![Screen Shot 2018-04-18 at 12.06.38.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/6593bc6d-b808-4959-844c-b90f823ffbf5)

### Steps to reproduce the behaviour/error

Aha! Link: https://ushahiditeam.aha.io/features/PROD-359

**Comment by hyounes4560** [comment]
Can I claim this task? @rowasc Thank you

**Comment by Naimaoye** [comment]
Hi @rowasc , can I claim this task for my outreachy contribution?

**Comment by treasurechristain** [comment]
Can I work on this issue for my outreachy contribution. I'm Amadikwa Joy N

**Comment by Angamanga** [comment]
@hyounes4560 Please go ahead :). For this you will need to set up the pattern-library since it probably requires changes to the css. You can find the docs here: https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/setting-up-the-pattern-library-for-development.
