### ISSUE TITLE
Adjust html for checkboxes and radiobuttons

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3643]
## TODO
The new checkboxes and radio-buttons requires the label to be situated below the input-element. Go through the client-code and make sure this is the case everywhere.

HTML is here: 
- https://github.com/ushahidi/platform-pattern-library/blob/ui-refresh/assets/templates/partials/_Checkbox.hbs
- https://github.com/ushahidi/platform-pattern-library/blob/ui-refresh/assets/templates/partials/_Radiobutton.hbs

Corresponding design-issue: 

- https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2698 
- https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2699

Aha! Link: https://ushahiditeam.aha.io/features/PROD-332

**Comment by rowasc** [comment]
@Angamanga lets check in on this one

**Comment by UdokaVrede** [comment]
If this is open I would like to take it up @rowasc

**Comment by rowasc** [comment]
Hey @UdokaVrede this one seems to be blocked and needs triage. https://github.com/ushahidi/platform/issues?q=is%3Aopen+label%3A%22Community+Task%22+milestone%3A%22Hacktoberfest+%22 please check this list and check for unclaimed issues
Thanks

**Comment by Angamanga** [comment]
@rowasc This is related to the js-migration/ui-refresh, guess we can close it?

**Comment by rowasc** [comment]
Yea lets close
