### ISSUE TITLE
Add api-translations to transifex

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3644]
### Expected behaviour
Translations in the api should be downloaded from transifex

### Actual behaviour
Translations in the api is hardcoded in the api: https://github.com/ushahidi/platform/tree/master/application/i18n
(only spanish is present right now)

### Steps to reproduce the behaviour/error

Aha! Link: https://ushahiditeam.aha.io/features/PROD-336

**Comment by tuxpiper** [comment]
This is currently only partially solved. Last I checked, we had trouble with Transifex working with nested structures (i.e. "post.validate", is in PHP:

```
"post" => array(
  "validate" => "Validation error!"
);
```

Lumen is happy with it, but Transifex can't parse
