### ISSUE TITLE
drafting Current Platform roadmap documentation

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3645]
Outline of documentation on current roadmap process 

# Where to find the roadmap

- We add to our roadmap and modify it on a rolling basis based on the projects we have commited to doing for different grant projects or customer requests, prioritized bugs, and feature requests from the community. As we introduce more open roadmap planning strategies to our workflows, you will be able to access our near term roadmap aggregated in a public location. 

- You can find the next features that we are considering adding to our roadmap with the tag [consider for upcoming cycle](https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22consider+for+upcoming+cycle%22)

- You can find the features we are working on by filtering with the tag https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Stage%3A+In+progress%22

# How a new item gets accepted into the roadmap
- We evaluate new features in collaboration with engineering, product, design, support and other functions in Ushahidi. 
- Ushahidi staff triage issues as they come in. These are general guidelines to ensure your feature request or bug report will be understood properly and can be acted upon:
    - Follow the issue submission guidelines. We provide complete issue templates for Bug reports and Feature requests, [which you can find here ](https://github.com/ushahidi/platform/issues/new/choose). 
    - You may receive follow up questions from the team doing triage and prioritization, which you are encouraged to respond to. This will ensure the person triaging the issue can understand the scope of work and needs fully. 
    - It helps to have a concise description, from a first-person point of view, of what the problem you are facing and need to solve is.
- It's also worth noting that not all parts of the system are equally funded at any given point for feature development, and that reality also influences when a feature can be prioritized to be worked on by Ushahidi staff. Funding for a specific goal (ie improve data triage process so that people can work more efficiently in an emergency) means our focus will generally be in a handful of improvements related to that goal. 

# How the decision to prioritize one issue over another is made
- For bugs, it comes down to how critical it is, if it's in the critical path to a function, and how common it is that someone would run into it trying to execute a function. For instance triage issues tend to be prioritized higher than issues in the webhook setup flows, since triage is a much more common action than webhook setup. This is also weighed with the time necessary to fix an issue, the team available to fix it, and the budget available for it. 
- For features, we prioritize what we want to see in the platform next with the help of all the Ushahidi team, their inputs as they interact with users, and user testing.
- Alignment to Ushahidi platform goals, resource limits, and needs of users: it's important for us to work on things that align closely with our mission. That means we will often have to say no to things that fall outside the scope or intent of the product. For instance: while a calendar might sound great, we cannot really make a calendar from scratch because it's outside of the scope of our product and what we do best, plus we just don't have the resources to maintain it... however:  we could integrate with one if there was enough evidence that it is needed. When requesting a new feature, we recommend providing the problem you are trying to solve so that together we can try to come to a solution that fits the Ushahidi Platform's scope.

# Next steps
We are working on improving how we prioritize move issues into them our roadmap. The next steps on this are first internal discussions with Ushahidi staff on what we believe are the rules of engagement on roadmap decisions,  initial documentation about the new roadmap decision making structure, and after initial docs, and requests for comments from the community. As we adjust our workflows to become more open and transparent for everyone, we want to hear from you, and will be opening up our process for comments in the near future.

**Comment by Erioldoesdesign** [comment]
I think given the imminent future of how we all want to change/modify/improve/adapt the product roadmap I think this works really well and serves the needs of DIAL. 

It's also clear, short and concise :D

Maybe...my only suggestion is...a TBC we're working on how we can bring more of the community into roadmap dicussion/planning etc. and a way for those interested to flag their interest?

**Comment by rowasc** [comment]
thanks Eriol 🎉  Yea, that's a good idea! Added a short paragraph about it 😬 lmk what you think/feel free to edit.

**Comment by tuxpiper** [comment]
Under "How a new item gets accepted into the roadmap" :

maybe we could mention that when submitting a feature request, it helps to send along a concise description, from a first-person point of view, of how that feature would work. Also, again as a first-person, some reasoning of why the feature would be valuable .

**Comment by tuxpiper** [comment]
I think I would :heart: to somehow factor in the process, an open discussion of the realities of budgeting from ours side: be clear about the features Ushahidi has been fortunate enough to fully allocate resources for, those who we estimate are only partially funded from our side and those which we are not able to support with our resources atm

**Comment by rowasc** [comment]
>Under "How a new item gets accepted into the roadmap" :
Added your suggestion there, lmk if it works? 

---------

Re funding: Yes, that sounds like a good idea. I think at this point we may want to be very general about it, but still bring it up and be open that not all features are equally funded and the reality that some issues are just really hard to get resources for, except from core funding.

Would it help to add some context on what team size we are working with, especially around product, design, engineering?  

Maybe a  "Why is my feature not prioritized" section could cover this (and also explain sometimes we just have to make unpopular decisions in what we can and cannot add to the product.. ) 

ie: "while a calendar might sound great, we cannot really make a calendar from scratch because it's really outside of the scope of our product and what we do best, but we could integrate with one if there was enough evidence that is needed" (chose a calendar because it came to mind but it could be anything basically)

**Comment by tuxpiper** [comment]
At some point it may also be open and encouraging to have a purely technical gate-keeping process for what constitutes a feature that *could* be in the roadmap (regardless of resources), i.e.:

- The feature has solid technical and functional requirements
- There is a sound study of the impact of the feature on the whole product and it is deemed acceptable
- The user experience impact is well understood
- The security impact is well understood
- ... etc ...

In this way, there would be clear flags indicating which big chunks of work are fine to work on by true heroes :heart: in their hard-earned free time. I know it's not exactly easy for such thing to happen  ...  but in general, I also think that laying this down explicitly is a hallmark of good technical practices.

**Comment by rowasc** [comment]
If I understand correctly the points you listed are something that people would post at any point to justify the work they did is merge-able?  or are you suggesting they post this ahead of time and have a discussion and then work on it if there's an agreement that it could be valuable? 
(I don't want to jump and answer without being sure)

**Comment by rowasc** [comment]
Ah wait, your list is actually about what _we_ would use as technical gatekeeping basically?

**Comment by tuxpiper** [comment]
Yes general technical gatekeeping, before anyone jumps into spending lots of time on something ... Any feature in the roadmap should have this technical and product-related groundwork detailed in the open , regardless of who proposed the feature or who is going to work on it.

**Comment by tuxpiper** [comment]
That also means that the roadmap may not be 100% filtered by the resources of our organization, but more fundamentally by higher-level overarching technical criteria that we all can share.

**Comment by rowasc** [comment]
Ah ok thanks. I think I agree with most of this re technical requirements and the balance of filtering through level of readiness not just wishes, but also have a few concerns/things I'd like to discuss in detail around the implementation. Would you mind if we move this part of the conversation into the future roadmap issue https://github.com/ushahidi/platform/issues/3584 (or a related issue that links to that one) ? I think it fits that ticket better since we are now moving into "planning how we want to work" territory a bit more than I'd like for this one.

**Comment by tuxpiper** [comment]
Oh yea, absolutely . I agree this stuff goes for a bit later, with a tidier house . Sorry I didn't remember that we have two roadmap issues.

**Comment by rowasc** [comment]
that's alright. Thanks David <3

**Comment by rowasc** [comment]
Moved to https://github.com/ushahidi/platform/issues/3688 which is related to https://github.com/ushahidi/platform/issues/3584

**Comment by rowasc** [comment]
added the mention to funding. 
Could you review? 
Thanks <3

**Comment by tuxpiper** [comment]
Sounds good :+1:  I'm wondering if there would be a more suitable place other than the roadmap itself to list the priority areas .. but I also think we will be seeing about how to organize the information displayed in due time.

**Comment by Angamanga** [comment]
@rowasc I saw this now and it looks 👌 . Could this live in gitbooks rather than as an issue?

**Comment by rowasc** [comment]
Yea this can be in gitbooks, thanks Anna!
