### ISSUE TITLE
Publish official docker images

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3651]
Make docker an officially supported approach for (production) deployment

**Which user group(s) are the primary audience for this feature/enhancement.**
Open source deployers

**Is your feature request related to a problem? Please describe.**
Currently there's no environment independent well documented method of installing platform. Docker deployments would nicely fill that gap.

**Describe the solution you'd like**
1. Automated and tagged image creation of platform, platform-client and platform-release
2. Sample docker-compose.yml file for dependencies
3. Documentation in docs.ushahidi.com
4. Continuous Integration to test the proposed solution works and doesn't get broken

**Additional context**
We do have working images , they need to become officially supported, documented and have test coverage

Aha! Link: https://ushahiditeam.aha.io/features/PROD-196

**Comment by tuxpiper** [comment]
Related to #3653

**Comment by sgofferj** [comment]
What happened to this if I may ask. I'm on the fence for trying Ushahidi out but only if I can run it on premises. And a manual install is simply an outdated approach and a nightmare to maintain...

I haven't found any documentation for setting up a test or production system with docker.

**Comment by tuxpiper** [comment]
Partially, but I think we've got it mostly done @sgofferj , pending maybe the last check for docs and release monitoring. i.e. I see the docker hub pushing automation needs a review.

Head over to https://github.com/ushahidi/platform-release for some example docker compose files that use the prebuilt tarballs. Those should be working fine.
