### ISSUE TITLE
Getting "master" branch up to date

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3654]
- [x] Test user creation flow
- [x] Test user update flow
- [x] Test export (to ensure the export is generated)
- [x] Test SMS Sync integration
- [x] Test survey creation, survey edit, post submission , post view (data and map) and post edit
- [x] Check that the validations for survey creation, datasources and posts still work as they do in prod
- [x] Confirm that web hooks work (this can be done by adding a small external service, let me know if you need help)
- [x] Test receiving and sending SMS 
- [x] Test twitter integration works
- [x]  Test data import flow.

**Comment by rowasc** [comment]
@Obadha2 this should be tested in Steve Buscemi tomorrow  (you can continue in the same smoke test you had started since the code is the same, we just need the validation for this specific features I listed) 
Thanks!

**Comment by Obadha2** [comment]
@rowasc seems the SMS Sync application is not available. 
![Screenshot_20190815-184454__01](https://user-images.githubusercontent.com/38259840/63107095-fb108000-bf8c-11e9-9b4a-c151ca73b73a.jpg)

**Comment by rowasc** [comment]
- Commenting to say that SMS Sync is being used to test from the APK available we had since it was the version we had built already (solved internally).
- Also adding  for @Obadha2 
     - [ ] Test data import flow. Note: you might find bugs that are already reported, we are looking for any *new* issues that may have been introduced in this last merge

**Comment by rowasc** [comment]
@Obadha2 please update the issue and close it  , thanks!

**Comment by Obadha2** [comment]
All items pass QA. :+1:
