### ISSUE TITLE
User search - X button does not clear contents in search field.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3656]
**Describe the bug**
On the Users page, after typing into the search bar, the content persists when the X button on the search bar is clicked.

**To Reproduce**
1. Go to Settings, then Users
2. Type into the search field
3. Click on the X on the left side of the search field
<img width="689" alt="Screen Shot 2019-08-17 at 17 06 20" src="https://user-images.githubusercontent.com/2434401/63216807-65eac400-c111-11e9-98f8-5934d9fac0d4.png">
4. The content that had been typed in is not cleared.
<img width="762" alt="Screen Shot 2019-08-17 at 17 06 23" src="https://user-images.githubusercontent.com/2434401/63216813-726f1c80-c111-11e9-9945-61077352593e.png">

**Expected behavior**
The X should clear the contents in the search field and show all Users.

**Is there a workaround? What is it.**
Clear the content in the search field manually

**Screenshots**

**Desktop Hardware Details (please complete the following information):**
- OS: Ubuntu 18.04.3 LTS
- Browser: Chrome
- Version: 76.0.3809.100 (Official Build) (64-bit)

**Comment by husar** [comment]
Hello, i would like to work on this issue if it is still open. Can you assign it on me?

**Comment by rowasc** [comment]
Hi. Of course. Thank you @husar ! 🎉 

cc @Angamanga for awareness

**Comment by husar** [comment]
I cant install project because missed class Memcached. Please help me beacuse i cant work!

**Comment by husar** [comment]
![Snímka](https://user-images.githubusercontent.com/44474224/67431504-b6d0da00-f5e4-11e9-9de3-04654ac6b62c.PNG)

**Comment by husar** [comment]
Is this project functional beacuse I got this only
![image](https://user-images.githubusercontent.com/44474224/67567339-040a9400-f72a-11e9-91d8-f697ace00530.png) and didnt see some controlers and functional route in web.php

**Comment by husar** [comment]
Is this project functional beacuse I got this only 
![image](https://user-images.githubusercontent.com/44474224/67567542-5fd51d00-f72a-11e9-9ea8-e2012cd42cab.png) and didnt see any controllers and functional route in web.php

**Comment by rowasc** [comment]
yea, it is. That screenshot leads me to think there is some setup issue. 
What setup guide are you using? if using XAMPP, make sure you are setting up the htaccess files and virtualhost correctly per this guide
https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/xampp#configure-the-platform-httpdocs-htaccess-file

**Comment by husar** [comment]
Ok, so a try to follow this instructions and if i try localhost it gives me this like in this guide: 
![image](https://user-images.githubusercontent.com/44474224/67639973-0a9a3680-f8f7-11e9-9a6f-ef4adf799ce6.png)
and if i try go to public folder for example it gives me this: 
![image](https://user-images.githubusercontent.com/44474224/67639983-31f10380-f8f7-11e9-8ddd-adc75a90064e.png)

**Comment by rowasc** [comment]
excellent, the first image in localhost is correct since it is the default API response. You may want to do an edit in your hosts file to use something like `127.0.0.1 api.ushahidi` so it's easier/more intuitive to connect from the client. 

The next step is setting up the platform client itself and pointing to that API

**Comment by husar** [comment]
OK finally it works!!! thanks :D :D ..... but i have another problem: i can't log in for open userpage

**Comment by ritesh-pandey** [comment]
@husar Are you working on this?

**Comment by himil-vasava** [comment]
I have made some changes due to which now: 

<b>Before clicking X button : </b>

![Screenshot from 2020-02-13 23-32-41](https://user-images.githubusercontent.com/55590415/74464226-2c74f480-4eb9-11ea-9286-8cd6df7689ea.png)

<b>After clicking X button : </b>

![Screenshot from 2020-02-13 23-34-09](https://user-images.githubusercontent.com/55590415/74464338-5e865680-4eb9-11ea-90f8-139cb9f59b56.png)

So is it okay now or do I have to make some changes in it ? @rowasc  @Angamanga

**Comment by Angamanga** [comment]
@himil-vasava That looks good! Could you test the solution doing the same operations a few times? I remember it behaving different the second and third time clicking the x-icon for some reason.

**Comment by himil-vasava** [comment]
@Angamanga yeah actually I faced that problem after clicking it two or three times

**Comment by rowasc** [comment]
@Obadha2 can you test ? Thanks

**Comment by Obadha2** [comment]
@rowasc now, the clear content feature works, but the search feature appears to not work in some instances.

**Comment by rowasc** [comment]
ooof. Can you describe how to break it? thanks for finding it

**Comment by Obadha2** [comment]
K the search feature is broken. 
On performing a search, results just don't show up 40-60% of the times. It's a bit weird because there doesn't seem to be a pattern for reproducing it. It'll work in some instances, in some instances it does not. 

Logged [here](https://github.com/ushahidi/platform/issues/3936) as a separate issue.

**Comment by rowasc** [comment]
Closing this in favor of https://github.com/ushahidi/platform/issues/3936 since the original issue is done but new ones appeared.
