### ISSUE TITLE
Test our documentation for installation of development environment with Vagrant

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3661]
# Intro 📖 
We are continuously working with our documentation to provide a good and smooth experience when setting up the platform. In this ticket, we are asking for help to improve our documentation for installation of development environment.

# Task ✏️ 
- Go to https://docs.ushahidi.com/platform-developer-documentation/getting-started/setup_alternatives/vagrant-setup
- Follow the instructions and try to install the platform
- Document and write comments about the installation-process as comments below, it could be for example: 
  - Confusing instructions
  - Errors you get that is not mentioned in the documentation
  - Do you get stuck somewhere and don't manage to get past a point in the documentation? Where is that?
  - Do you have to do things that is not mentioned in the documentation to make it work? Where and what did you do?
  - Anything else that comes to mind, suggestions, comments etc when reading through the docs.

Thank you for your time and help 🎉 🙏 🙇‍♀

Aha! Link: https://ushahiditeam.aha.io/features/PROD-190

**Comment by jnhooper** [comment]
Is there a reason to use vagrant locally instead of having docker setup for development purposes? It looks like there's already work done for deploying with docker right?
