### ISSUE TITLE
Migration to enable HDX integration for everyone 🎉 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3666]
**Which user group(s) are the primary audience for this feature/enhancement.**
Free, Basic and Enterprise deployment users who wish to export their data into HDX (humdata.org) 

**Is your feature request related to a problem? Please describe.**
The problem is that HDX is not enabled for most deployments and it should be, per our latest internal discussions on the roadmap 

**Describe the solution you'd like**
- A migration in the database (`./phinx migrate create HDXEnabled`)    that sets the config_key hxl to enabled.
- Migrations can be found in https://github.com/ushahidi/platform/tree/develop migrations/ (for reference)
- To execute and test your new migration you need to have finished the platform backend installation since the database is needed for it, then run `./phinx migrate`
- To test this, access Settings -> Data Export, you should see a button to configure the deployment with HDX. ping `@`rowasc if you need assistance :) 

*Field values:* 
group_name -> features
config_key ->  hxl
config_value -> {"enabled":1}

This would make it immediately available for all admins upon executing the migration.

# Working on this issue
- You need to setup the platform api for this issue. See our docs here : https://docs.ushahidi.com/platform-developer-documentation/getting-started/setup_alternatives/vagrant-setup 
- 👩‍💻 when you finish writing the migration and testing the change locally, please open a new pull request. 
- 🏁 Ask for a review :) 

## Want to work on this issue?🙋 
Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Aha! Link: https://ushahiditeam.aha.io/features/PROD-185

**Comment by rowasc** [comment]
I was going to do this but it's a nice starter ticket so leaving it here until next week in case someone wants it :)

**Comment by rowasc** [comment]
UPDATE: opened PR to enable but I found some issues during testing today (locally) that I need to address before merge. 
https://github.com/ushahidi/platform/pull/3767

**Comment by Obadha2** [comment]
Updated test checklist:
- [ ]  I can setup my API key and userrname for HDX
- [ ]  I can change my API key and username
- [ ]  On initial set up, application navigates to export page
- [ ]  I can navigate to attached links for HDX home, tag assist and cheat sheet
- [ ]  After saving id and API key, can follow Start Tagging Data button
- [ ]  Export all data downloads all available data
- [ ]  Select fields lists all surveys and their fields for users to select specific fields to export
- [ ]  I can select tags only (and it generates the CSV+HXL file correctly with the correct tags)
- [ ]  I can select tags and attributes (and it generates the CSV+HXL file correctly with the correct tags)
- [ ]  Tag preview section shows me selected tags and attributes
- [ ]  Attributes can only be selected based on selected tags
- [ ]  Each attribute can only be selected once
**Dataset title & desc page**
- [ ]  Privacy option is compulsory
- [ ]  Data set title is compulsory field
- [ ]  Source is compulsory field
- [ ]  Organisation field is compulsory field
- [ ]  License is compulsory field
- [ ]  Confirmation message when upload is complete
- [ ]  Uploaded dataset can be seen on humdata
- [ ]  Dataset uploaded to humdata can be downloaded
- [ ]  Dataset matches downloaded xls file from export data
- [ ] Export history on platform has details of exports including Export Number, State, Date creation, and Expiry.

**Comment by Obadha2** [comment]
In addition to existing issues, I picked up on the following:
- On export page, HXL tags and HXL attributes links are dead. they both lead to a 404 error.
<img width="1829" alt="Screenshot 2020-03-06 at 5 23 07 PM" src="https://user-images.githubusercontent.com/38259840/76092005-b5221480-5fcf-11ea-862d-276ca5c505dc.png">

**Comment by rowasc** [comment]
@Obadha2 thanks for catching that! I'll schedule a fix ASAP
