### ISSUE TITLE
End-to-end installer helper – run checks against API gateway checker

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3671]
1. Check if the gateway checker is actually enabled
  * if it is enabled `https://<api>/?gwcheck=1` should return 200
     - other checks may be run
  * if it is disabled `https://<api>/?gwcheck=1` will return 204 and header `X-Ushahidi-Platform-GWCheck: off`
     - no other tests of this sort are run

2. Check if the Authorization header is received by the backend

3. Check that the path to API operations is correctly received

4. Check that the clock in the server is (approximately) correct

Finally: if all tests are passed, show a reminder to turn disable the gateway checker in the backend (run `composer gwcheck:disable`)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-184

**Comment by rowasc** [comment]
@tuxpiper this should be closed, I think?
