### ISSUE TITLE
SMS Sync issue - SMS sent out from the platform are not delivered to recipient phone number.

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#3677]
**Describe the bug**
After SMS Sync is set up, users are able to send messages to the platform from their SMS inbox, but when a reply to that message is sent from the platform, the reply is not delivered to the recipient's inbox.

**Where was the bug observed**
https://test-deployment.steve-buscemi.ush.zone/views/data
Note from Walter: This happens in prod too. Messages sent out from prod are not received in the SMS inbox of the number that sent the message first. @rowasc

**To Reproduce**
1. Send an SMS to a phone number that has SMS Sync set up, configured and enabled.
2. Refresh platform after a few minutes, the message should have arrived in the data section.
3. Click on Send New Message and send a message as a reply to the received message.
4. This message shows as sent on Platform, but it is not delivered in the number of the person that sent the first message.

**Expected behavior**
Messages sent from the platform (as replies) should be received in the recipient's SMS inbox.

**Configuration Details**
SMS Sync URL: https://test-deployment.api.steve-buscemi.ush.zone/sms/smssync

**Additional context**
The number where the SMS Sync is set up is a Safaricom number, while the number that sends the messages and we expect the messages from platform be delivered to is an Airtel number. Numbers will be provided upon request.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-182

**Comment by rowasc** [comment]
Could you review this in prod to figure out if it's a regression or a pre existing issue? 
Thank you

**Comment by Obadha2** [comment]
This happens in prod too. Messages sent out from prod are not received in the SMS inbox of the number that sent the message first. @rowasc

**Comment by rowasc** [comment]
yikes yikes. Ok it might be configuration but I'll check it out on Monday. Thank you <3

**Comment by rowasc** [comment]
@all-contributors please add @Obadha2 for bug

**Comment by ijrad** [comment]
@Obadha2 Hi, please which mobile app version are you using to send sms to ushahidi platform?
