### ISSUE TITLE
Differentiate what ‘Save’ does and what ‘Publish’ does.

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#368]
Feedback from David Kimaru.
Differentiate what ‘Save’ does and what ‘Publish’ does."""

**Comment by rjmackay** [comment]
Assigning to Sophie for UX review

**Comment by sophshep** [comment]
I'm not sure where the publish button he's referring to is? Is it the "publish as" dropdown?

**Comment by rjmackay** [comment]
I think they meant it wasn't obvious what the 'Save' button does, vs 'Publish to..' dropdown. 
But I'm also guessing.

**Comment by sophshep** [comment]
Note to self: create a button that has the "who sees this" built into the save button so they feel more related and like one action

**Comment by rjmackay** [comment]
Another thing to consider: how do I publish to multiple roles? I've already had at least one person ask about that..

**Comment by sophshep** [comment]
I've added this pattern and it's visible on: http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/create-post.html

But I'm not 100% satisfied with the style, so leaving it open for myself to come back to later on.

Note: if the post is already published, the button should say `save`

**Comment by sophshep** [comment]
Rethinking this using the dropdown select patter in this issue: https://github.com/ushahidi/platform/issues/754
