### ISSUE TITLE
Decision making for feature readiness

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3688]
related to https://github.com/ushahidi/platform/issues/3584 

We are having a discussion about how we will decide that a feature is ok to work on.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-179

**Comment by rowasc** [comment]
At some point it may also be open and encouraging to have a purely technical gate-keeping process for what constitutes a feature that *could* be in the roadmap (regardless of resources), i.e.:

- The feature has solid technical and functional requirements
- There is a sound study of the impact of the feature on the whole product and it is deemed acceptable
- The user experience impact is well understood
- The security impact is well understood
- ... etc ...

In this way, there would be clear flags indicating which big chunks of work are fine to work on by true heroes :heart: in their hard-earned free time. I know it's not exactly easy for such thing to happen  ...  but in general, I also think that laying this down explicitly is a hallmark of good technical practices.

This may be more suitable for #3584

_Originally posted by @tuxpiper in https://github.com/ushahidi/platform/issues/3645#issuecomment-528042226_

**Comment by rowasc** [comment]
If I understand correctly the points you listed are something that people would post at any point to justify the work they did is merge-able?  or are you suggesting they post this ahead of time and have a discussion and then work on it if there's an agreement that it could be valuable? 
(I don't want to jump and answer without being sure)

_Originally posted by @rowasc in https://github.com/ushahidi/platform/issues/3645#issuecomment-528045037_

**Comment by rowasc** [comment]
Ah wait, your list is actually about what _we_ would use as technical gatekeeping basically?

_Originally posted by @rowasc in https://github.com/ushahidi/platform/issues/3645#issuecomment-528046741_

**Comment by rowasc** [comment]
Yes general technical gatekeeping, before anyone jumps into spending lots of time on something ... Any feature in the roadmap should have this technical and product-related groundwork detailed in the open , regardless of who proposed the feature or who is going to work on it.

_Originally posted by @tuxpiper in https://github.com/ushahidi/platform/issues/3645#issuecomment-528047184_

**Comment by rowasc** [comment]
That also means that the roadmap may not be 100% filtered by the resources of our organization, but more fundamentally by higher-level overarching technical criteria that we all can share.

_Originally posted by @tuxpiper in https://github.com/ushahidi/platform/issues/3645#issuecomment-528048036_

**Comment by rowasc** [comment]
Ah ok thanks. I think I agree with most of this re technical requirements and the balance of filtering through level of readiness not just wishes, but also have a few concerns/things I'd like to discuss in detail around the implementation. Would you mind if we move this part of the conversation into the future roadmap issue https://github.com/ushahidi/platform/issues/3584 (or a related issue that links to that one) ? I think it fits that ticket better since we are now moving into "planning how we want to work" territory a bit more than I'd like for this one.

_Originally posted by @rowasc in https://github.com/ushahidi/platform/issues/3645#issuecomment-528053060_

**Comment by rowasc** [comment]
this would fit a "request for comments" process, I think?

**Comment by rowasc** [comment]
It would benefit from "We understand everyone's background is different, and an initial request for a feature does not need to fit this entire criterion. It is enough to follow the basic criteria requirements in our Feature Request template to submit an idea for consideration. 
After an idea is submitted, we will go through the following process to assess readiness: 
[insert criteria ]
"

Note on language change suggested: I suggest we just call these readiness criteria (or a more standard term than this) to enable us and our community to have an inclusive and collaborative mindset as we discuss and run through this tasks. 

(I only thought of this now TBH as I was re reading our interaction :) )

**Comment by tuxpiper** [comment]
> Note on language change suggested: I suggest we just call these readiness criteria (or a more standard term than this) to enable us and our community to have an inclusive and collaborative mindset as we discuss and run through this tasks.

yep :+1: I'm a notorious gearhead but not everyone needs to be :) Plus probably only half of the criteria or less would be purely engineering concerns
