### ISSUE TITLE
Time input needs to be 24 hr format OR show am/pm

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#372]
Time has no 24hour input format and there is no way of telling/inputing a.m or p.m format either. To reproduce this issues click "create post" and view time entry options.	

I should expect the bare minimum a drop down for time entry that has an increase and decrease option, and ability to input 24hour clock or not.

**Comment by rjmackay** [comment]
Hopefully being fixed by @willdoran's datepicker fixes?

**Comment by willdoran** [comment]
Yep also in
