### ISSUE TITLE
Wrong intercom link if intercomAppId is not set

### ISSUE THREAD

**Issue by trendspotter** [ushahidi/platform#3769]
### Expected behaviour
Intercom link under Ushahidi support menu should be hidden when `intercomAppId` is not set in `config.js`.

### Actual behaviour
When `intercomAppId` is not set in `config.js` or is set to empty string, displayed *Intercom* menu item leads to bogus address `@intercom-mail.com`

### Steps to reproduce the behaviour/error
1. Install Ushahidi 3.12.3.
2. Don't fill any value for `intercomAppId` in `config.js`.
3. Login to Ushahidi.
4. Click on Ushahidi support menu item (bottom left).
5. Observe address in *Intercom* link.

**Comment by rowasc** [comment]
@all-contributors please add @trendspotter for bug

**Comment by ritesh-pandey** [comment]
Is the issue available as `community task`?

Will this patch fix the issue?
```
-    <dt class="list-item" ng-show="loggedin"><a id="intercom_custom_launcher" href="mailto:{{intercomAppId}}@intercom-mail.com" target="_blank" translate>app.intercom.intercom</a></dt>
+    <dt class="list-item" ng-show="loggedin && intercomAppId"><a id="intercom_custom_launcher" href="mailto:{{intercomAppId}}@intercom-mail.com" target="_blank" translate>app.intercom.intercom</a></dt>
```

We need to show intercom launcher link only if `interecomAppId` is present.

**Comment by Angamanga** [comment]
@ritesh-pandey Thank you for reaching out, yes this is available as a community task 🎉  Your solution is correct, in addition, you would probably need to do the same check for the row below as well: https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/mode-bar/support-links.html#L14

**Comment by Angamanga** [comment]
@all-contributors please add @ritesh-pandey for code
