### ISSUE TITLE
On editing Data, page stuck on saving user enters Decimal in Integer field and tries to save.

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#3777]
**Describe the bug**
When user tries to submit a response to a survey (on web) and they provide a decimal value in the integer field, and they click on Save, the user is notified of the error, but the save action appears to continue forever.

**Where was the bug observed**
msheria-stg.ushahidi.com
Happens in production, and steve-buscemi.ush environments too.

**To Reproduce**
1. Submit a response to a survey that has an integer field. Enter a valid integer.
2. Note that the response is submitted successfully.
3. Click Edit to edit the response.
4. In the Integer field, enter a decimal number.
4. Click Save to persist the changes.
5. Pop-up warns that Integer field has invalid value.
6. Note that the pop-up has the message repeated. (See screenshot)
7. Click Dismiss on the pop-up without waiting too long. 
8. The Saving buttons are inactive and user is unable to Save.
9. User has to navigate away and come back for the button to be active.

**Expected behavior**
Once user sees and Dismisses the notification of invalid value, Save button should be active and they should be able to interact with it.

**Is there a workaround? What is it.**
Reload the page, or navigate away and back.

**Screenshots**
![Error message repeated](https://user-images.githubusercontent.com/38259840/65762835-9d925600-e12a-11e9-9105-33578eddd31c.png)

![Save button inactive](https://user-images.githubusercontent.com/38259840/65762870-b6027080-e12a-11e9-92b0-71566b4e324d.png)

**URL / Environment where this happened**
https://msheria-stg.ushahidi.com/posts/3/edit

**Desktop Hardware Details (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version 77.0.3865.90 (Official Build) (64-bit)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-174

**Comment by noone0212** [comment]
May I work on this?

**Comment by rowasc** [comment]
@noone0212 yes, absolutely. Thank you !

**Comment by rowasc** [comment]
https://github.com/ushahidi/platform/issues/3943 this one may also be related
