### ISSUE TITLE
Add `hacktoberfest` labels to issues

### ISSUE THREAD

**Issue by Timtech4u** [ushahidi/platform#3778]
This issue is meant to serve as a reminder to add the `hacktoberfest` labels to issues that could be worked on during the [Hacktoberfest season](https://hacktoberfest.digitalocean.com/).

cc: @tuxpiper

**Comment by rowasc** [comment]
Thanks Tim! you are the best ! 
I just went ahead and labeled the good-first-issue and first-timers-only tickets with `hacktoberfest` :)

**Comment by rowasc** [comment]
@all-contributors please add @Timtech4u for docs, bug, code

(note: Trying to ensure Tim gets added with `code` due to the USSD work as well)
