### ISSUE TITLE
Timeline and barchart views have truncated labels

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#378]
Timeline and bar chart views on the homepage, when user selects this, the X-axis is labelled "chart timelines" or something, I cannot seem to figure the full label because of trancation.

cc @vbhv

**Comment by rjmackay** [comment]
@vbhv have you already logged this in Phab?

**Comment by vbhv** [comment]
Yes, I'm linking to the phab task from this reported issue which has more details. I'll close this one.
https://github.com/ushahidi/platform/issues/305
