### ISSUE TITLE
Verifier: add a verification that checks the storage/passport/oauth-* files exist

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3783]
**Important information to work on this issue**
- If you are not familiar with the installation helper, please read [this guide before starting work on this issue].(https://docs.ushahidi.com/platform-developer-documentation/development-and-code/installation-helper)
- **Codebase affected**  - Backend : https://github.com/ushahidi/platform/ 
- **Set up the platform** following one of [this guides](https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives).

**Describe the bug**
Right now if a user's composer install didn't add the storage/passport files, they run into an issue instead of the verifier letting them know of the problem

**Where was the bug observed**
Community support

**To Reproduce**
Delete the storage/passport/oauth* files and run `composer verify` 
It will look like it works but the API does not actually work 

**Expected behavior**
`composer verify` reports issues and helps solve them

Aha! Link: https://ushahiditeam.aha.io/features/PROD-171

**Comment by rowasc** [comment]
@tuxpiper @Angamanga FYI

**Comment by rowasc** [comment]
@all-contributors please add jlucianolzz for testing 

thanks for testing our docs 🎉

**Comment by SaifurRahmanMohsin** [comment]
Shouldn't this be closed since #3810 addresses this?

**Comment by tuxpiper** [comment]
Indeed! Thank you @SaifurRahmanMohsin !
