### ISSUE TITLE
[Ubuntu+Chrome] Language options under change language not visible.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3799]
**Describe the bug**
On chrome browser, the language options are not visible. Instead, user sees a white screen where there should be the list of languages that can be selected. Language options can still be selected, just not visible.

**Where was the bug observed**
Test environment - https://test-deployment.steve-buscemi.ush.zone/views/data
Prod Environment - https://isooko.ushahidi.io/views/map

**To Reproduce**
1. Go to a deployment.
2. Navigate to map view "...../views/map"
3. Scroll to Language option.
4. Click on Select Language to reveal list of languages.
5. Observe that only a white space is seen where there should be a list of language options.
6. Hovering over the options shows each individual option as you hover over it.
7. Options can still be selected. 

**Expected behavior**
On clicking Select Language, the options should all be visible.

**Is there a workaround? What is it.**
Hover over the options individually revealing each one. Options can still be selected.

**Screenshots**
![Language options not visible](https://user-images.githubusercontent.com/38259840/68021554-9ca89300-fc99-11e9-8355-b1dff481c8c3.png)

**URL / Environment where this happened**
Happened in both test and prod environments.

**Desktop Hardware Details (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Browser: Chrome
 - Version 78.0.3904.70 (Official Build) (64-bit)

**Additional context**
Only happens on chrome. Other browsers work fine.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-169

**Comment by Firenz** [comment]
I think I can fix the issue, please @rowasc assign it to me 😊

**Comment by rowasc** [comment]
@Firenz absolutely. I see you sent a PR already :)

**Comment by tuxpiper** [comment]
Confirmed closed
