### ISSUE TITLE
Language Options: Drop-down should show selected langauge. 

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#3800]
**Which user group(s) are the primary audience for this feature/enhancement.**
This is a feature that would be applicable for all deployments and use cases.

**Is your feature request related to a problem? Please describe.**
This feature makes it quicker to notice what language is currently in use, and makes for a cleaner User Interface.

**Describe the solution you'd like**
On the dropdown, what is seen is "Select Language". We should instead show what language has been selected in the list. Clicking the dropdown should then reveal the options, with current option in use selected.

**Screenshot**
![Drop-down does not show selected language](https://user-images.githubusercontent.com/38259840/68105063-60ba3b80-feee-11e9-9848-acda2d5e3512.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-168

**Comment by Qay-Tekkie** [comment]
@Obadha2 can I work on this issue? I'm an Outreachy Applicant.

**Comment by rowasc** [comment]
@Qay-Tekkie yes of course, let us know if you need assistance. Thank you!
