### ISSUE TITLE
Create awareness about the CLI Migration tool/services in DotCom

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3802]
## Overview
We are working on a v2-v3 migration tool. Initially we will do a CLI to evaluate usage and needs, we would like to be able to collect emails/info on deployers who are interested in the service to reach out to them. _To generate awareness of [the form where people can sign up](https://github.com/ushahidi/platform/issues/3801) and the service_, we may consider a sticky top bar announcing this changes (or maybe it's some other solution, this is on Eriol's design magic to solve)

## Who is it for? Who are the users?
- Deployers who own a v2 deployment and may be interested in the migration service.

## What privacy impacts does it have?
- Does it change the personal data we collect? -> No. 
- Does it expose data that was previously private? - NO
- Does it send data to new services? or change how we process it? - No
- If privacy impacts are high risk, consider completing an impact assessment per GDPR (https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/accountability-and-governance/data-protection-impact-assessments/) - No

### Who will this be deployed to?
Everyone.

### What documentation needs to change?
Maybe add some info in dotcom about this. 
We already published the roadmap item here https://docs.ushahidi.com/platform-developer-documentation/roadmap/v2-v3+-migration-tool

## Test script
TBD
### Who will test this?
Walter
### Where will this be deployed and tested?
DotCom?
## Deployment

*Does this deploy new services?* -No, it's a module in dotcom
*Do the new services have health checks?* - No
*Can this be feature flagged and deployed disabled?* - No, it is not deployment specific

## Dependencies
Dotcom
https://github.com/ushahidi/platform/issues/3801

Aha! Link: https://ushahiditeam.aha.io/features/PROD-166

**Comment by Erioldoesdesign** [comment]
@Angamanga for awareness of the connecting issue re. v2-v3 design+FE.

Part of this work is (hopefully!) a 'Sticky' banner across all v2 hosted deployments that directs to the dotcom page to register their interest in migrating.

**Comment by Erioldoesdesign** [comment]
![v2-v3-Banner](https://user-images.githubusercontent.com/11681324/71895296-9840a080-3148-11ea-96b1-d92751ac9812.png)
@Angamanga 

Thoughts?

You'll need to grab individual assets from the .xd file which we can go through in our skill share meeting :)

**Comment by Erioldoesdesign** [comment]
@Angamanga here's where the .xd file is: https://drive.google.com/open?id=1VmF6KMIaelDe-lf1zysPzmOgT6h2qgFa
