### ISSUE TITLE
`bug` class name is not intuitive

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3805]
The `bug` class name is not intuitive. It sounds like we are displaying an error or that we were fixing a bug and forgot to rename it. We should look into better naming for it , I think?

Aha! Link: https://ushahiditeam.aha.io/features/PROD-164

**Comment by rowasc** [comment]
@Angamanga @Erioldoesdesign  could we find a better name for this? 💃 😬 It still confuses me and someone in the hackathon reminded me of this class name and now I'm confused about it again :D  at this point I was just resigned to live with BUT WE COULD CHANGE IT 💥 (maybe??)
🎉 
http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/1_basics/#pl-pattern-bugs

**Comment by Angamanga** [comment]
@rowasc I would love to change it!!
