### ISSUE TITLE
Broken link on Ushahidi Getting Started page

### ISSUE THREAD

**Issue by stewartweiss** [ushahidi/platform#3807]
On the web page,
https://www.ushahidi.com/support/install-ushahidi
the pop up window has a link 
"Getting started" guide for developers
in which "Getting Started" is a hyperlink to a page, with the URL
https://docs.ushahidi.com/platform-developer-documentation/getting-started
which when clicked results in
Page not found. Sorry, but the page you were looking for could not be found.
This happens using Firefox 70.01 on Ubuntu 18.04.

**Comment by rowasc** [comment]
Oh noes. Thank you for reporting. Fixed it now. 🎉

**Comment by rowasc** [comment]
@all-contributors please add @stewartweiss for docs

**Comment by stewartweiss** [comment]
Thanks for the quick fix and for keeping me in the loop.
