### ISSUE TITLE
Updating our client-build-system

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3812]
## Overview
The version of Gulp we are using is outdated and we have many security-alerts because of this. Updating to v4 would remove some of our security-alerts.

This epic includes:
- Upgrade to Gulp v4 in our current environment with our current settings and fix where things are breaking (Very useful guide here that covers what is breaking for us: https://www.sitepoint.com/how-to-migrate-to-gulp-4/) (https://github.com/ushahidi/platform/issues/3813)
- Remove run-sequence plugin, not needed for Gulp 4 (https://github.com/ushahidi/platform/issues/3813)
- Upgrade Karma to latest version (https://github.com/ushahidi/platform/issues/3814)
- Remove jscs and use eslint/prettier instead (would remove some of our vulnerabilities(~½ week) (https://github.com/ushahidi/platform/issues/3815)
- Update to Webpack v4 to avoid running into the webpack version we are using becoming outdated.
- At the same time, look over our configs and use Webpack where we can (for example for dev-server, running Karma, etc etc, we would reduce the number of libraries/plugins we are using and it decouples us from Gulp

## Who is it for? Who are the users?
- Our open source users
- Ourselves when developing

**Comment by Angamanga** [comment]
@all-contributors please add @individual-it for code

**Comment by tuxpiper** [comment]
@Angamanga  this was done and released, correct?

**Comment by Angamanga** [comment]
@tuxpiper Yes yes!
