### ISSUE TITLE
Cancel-button in the bottom of the edit-post-page is not working

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3828]
**Describe the bug**
When clicking on the cancel-button in the bottom of the edit-post-page, nothing is happening

**Where was the bug observed**
Local environment with Vagrant.

**To Reproduce**
1. Go to data-view
2. Log in as admin or manage-posts
3. Click a post and select Edit
4. Scroll down to the bottom of the edit-view
5. Click cancel
6. Nothing happens

**Expected behavior**
The editmode should cancel and go back to post-view (or show a modal asking if the user really wants to leave if changes are made)

**Is there a workaround? What is it.**
Click on the cancel-button in the upper-right corner

**Screenshots**
![Screenshot 2019-12-18 at 12 01 53](https://user-images.githubusercontent.com/8624777/71080869-48e10300-218e-11ea-81ca-26ff55e5010e.png)

**URL / Environment where this happened**
localhost:3000

**Desktop Hardware Details (please complete the following information):**
 - Browser [chrome]

Aha! Link: https://ushahiditeam.aha.io/features/PROD-160

**Comment by bismitaguha** [comment]
@Angamanga @rowasc can I work on this issue?

**Comment by rowasc** [comment]
absolutely, thank you so much for checking! @bismitaguha assigning it to you

**Comment by rohit645** [comment]
@rowasc Can I work on this issue?

**Comment by rohit645** [comment]
@rowasc Can I work on this issue?

**Comment by Angamanga** [comment]
@bismitaguha Are you still working on this issue?

**Comment by Erioldoesdesign** [comment]
I would love for the cancel button colour contrast to be fixed some day...maybe using #222222 for the text colour and #8E9297 for the background.
<img width="171" alt="Screenshot 2020-02-22 at 10 00 15" src="https://user-images.githubusercontent.com/11681324/75089556-3b634300-555a-11ea-819e-f9c9db3102ef.png">

**Comment by Angamanga** [comment]
@Obadha2 Could you QA in Steve Buscemi please? Testing-checklist:
- As logged in, go to dataview and select a post
- Click on edit
- Make a change
- Click on cancel in the bottom of the edit page
- [ ] An dialog-box should appear
- Click on "Continue without saving"
- [ ] You should leave edit-mode and the post should still be selected
- Click on edit
- Make a change
- Click on cancel in the bottom of the edit page
- Click on "Save" in the dialoge
- [ ] The post should save
- [ ] You should leave the edit-mode and the post should still be selected

**Comment by Obadha2** [comment]
QA'd, passes. 👍

**Comment by tuxpiper** [comment]
@all-contributors please add @himil-vasava for code

**Comment by GunjanRajTiwari** [comment]
Is this issue solved?
If not can I work on it?

**Comment by Angamanga** [comment]
@GunjanRajTiwari This one is unfortunately already solved, closing it. Take a look at the issues in the "Ready for development" here: https://github.com/ushahidi/platform/projects/11. Ping me in any issue you want to work on! 🎉 🎉
