### ISSUE TITLE
Need translation for placeholder when adding name for a new role

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3835]
**Describe the bug**
When creating a new role, the placeholder for "Name" is not translated, it only displays the translation-string (role.name)

**Where was the bug observed**
https://annatest1000.ushahidi.io/settings/roles/create

**To Reproduce**
1. Log in as an admin or user with manage-users permissions
2. Go to 'settings'->'roles'->click on '+'
3. The name is not translated:
![Screenshot 2020-01-28 at 13 10 27](https://user-images.githubusercontent.com/8624777/73263571-256b9800-41d1-11ea-9ba1-eea3673bee0e.png)

**Expected behavior**
The role should display "Name" (or the translated equivalent if the deployment is another language and there is a translation for that string)
**Is there a workaround? What is it.**
no

**Additional context**
This bug comes can be fixed here: https://github.com/ushahidi/platform-client/blob/develop/app/settings/roles/roles-edit.html#L45. Look at other translated placeholders and use the same pattern here.

**Comment by alti21** [comment]
Hi can I try to fix this issue?

**Comment by himil-vasava** [comment]
Should it just display "Name" like this?
![Screenshot from 2020-02-04 14-35-50](https://user-images.githubusercontent.com/55590415/73729820-be635b80-475b-11ea-838e-88c4682c1582.png)

**Comment by Angamanga** [comment]
@alti21 Yes please go ahead if not @himil-vasava has fixed it already? @himil-vasava are you working on this? You are correct, it should display "Name", but the world should not be hardcoded, it needs to be translated using the "role.name" (You can see another placeholder being translated here: https://github.com/ushahidi/platform-client/blob/develop/app/settings/site/settings-editor.html#L55)

**Comment by himil-vasava** [comment]
Yes I want to work on it and currently I am trying to solve it.

**Comment by himil-vasava** [comment]
I have made a pull request regarding it as now "Name" displays correctly.

**Comment by Angamanga** [comment]
@all-contributors please add @himil-vasava for code
