### ISSUE TITLE
Error-message when trying to create new role is not making sense

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3836]
**Describe the bug**
When trying to save a new role, and no Name or associated permissions is added, the error-message that appears is not informative:

![Screenshot 2020-01-28 at 13 11 40](https://user-images.githubusercontent.com/8624777/73264186-7334d000-41d2-11ea-8977-3ce32424f3fb.png)

**Where was the bug observed**
https://annatest1000.ushahidi.io/settings/roles/create

**To Reproduce**

1. Login as admin
2. Go to settings-> Roles-> create a new role
3. Do not fill in name or role
4. Click on save

**Comment by rowasc** [comment]
https://github.com/ushahidi/platform/pull/3837 got bored waiting for tests to run and fixed this one.. I think ? 😬

**Comment by Angamanga** [comment]
@Obadha2 Could you QA in Steve Buscemi?
Testing-checklist:
1. Login as admin
2. Go to settings-> Roles-> create a new role
3. Do not fill in name or role
4. Click on save
- [ ] The error-message should look something like this: 
![Screenshot 2020-03-16 at 10 56 45](https://user-images.githubusercontent.com/8624777/76744651-df649680-6774-11ea-891c-2263af866f33.png)

**Comment by Obadha2** [comment]
QA'd. While this passes, could we have "name must not be empty" appear just once, instead of twice? @Angamanga

**Comment by Angamanga** [comment]
I think there is a reason for that I don't remember (even if it is pretty confusing). Do you remember @rowasc ?

**Comment by rowasc** [comment]
yea... I think it's just a bad UI , it happens for other fffields too
