### ISSUE TITLE
Dropdown closes momentarily when `esc` button is pressed and shows up again.

### ISSUE THREAD

**Issue by rohit645** [ushahidi/platform#3846]
**Describe the bug**
As we click on the search bar of platform-client window, a dropdown menu pops out, (if we click anywhere outside it, dropdown list closes as expected). But if we click `ESC` key dropdown list closed momentarily and then pops up again. Similar bug is observed at post data view.

**Where was the bug observed**
At Local environment with vagrant (Platform-client).
(http://localhost:3000/views/map)
(http://localhost:3000/views/data)

**To Reproduce**
1. Go to 'map'.
2. Click on the Search Bar on the top of the window.
3. Now press `esc` key.
4. See error.

**Expected behavior**
The Dropdown menu should be closed down.

**Screenshots**
*At views/map*

![Screenshot from 2020-02-12 01-49-18](https://user-images.githubusercontent.com/33249010/74275511-007f3500-4d3a-11ea-82e9-47a3e43ceaa3.png)

*At views/data*

![Screenshot from 2020-02-12 01-49-10](https://user-images.githubusercontent.com/33249010/74275518-0248f880-4d3a-11ea-9f76-74c340ecbd93.png)

**URL / Environment where this happened**
[e.g http://localhost:3000/views/map]

**Comment by tuxpiper** [comment]
@all-contributors please add @rohit645 for bug, code
