### ISSUE TITLE
Creating a survey having integer field => does not give error message after entering a decimal number in the default value of integer field

### ISSUE THREAD

**Issue by himil-vasava** [ushahidi/platform#3847]
**Describe the bug**
When user creates a new survey and adds an integer field to it, if a decimal number is added in its default value and saved then no error message is displayed and the survey is saved. Although, its default value is converted into an integer.

**Where was the bug observed**

http://localhost:3000/settings/surveys/create

**To Reproduce**
1. Create a new survey.
2. Add an integer field and in its default value enter any decimal number such as 2.4 and save it.

3. Then while creating a post of that survey its default value shown would be its converted equivalent into integer.

**Expected behavior**
While entering a decimal number in default value of integer field, a error message would be displayed and the survey would not be saved.

**Screenshots**

Adding a decimal number in default value:

![Screenshot from 2020-02-17 01-58-23](https://user-images.githubusercontent.com/55590415/74612183-0c4b6c80-5129-11ea-997e-98ac95569012.png)

While creating a post the default value has been converted:

![Screenshot from 2020-02-17 02-02-09](https://user-images.githubusercontent.com/55590415/74612269-c216bb00-5129-11ea-9171-5de81ad8e9e7.png)

**URL / Environment where this happened**
Local development environment

**Desktop Hardware Details :**
 - OS: Ubuntu
 - Browser: Firefox

Aha! Link: https://ushahiditeam.aha.io/features/PROD-155

**Comment by individual-it** [comment]
Looks like that field is not validated at all, you can put anything in there

**Comment by himil-vasava** [comment]
Yes @individual-it it needs to be validated
