### ISSUE TITLE
Reset Zoom feature in map.

### ISSUE THREAD

**Issue by rohit645** [ushahidi/platform#3848]
**Feature/enhancement targeted for**
Platform-client

**Description of Enhancement**
As the user interacts with the world map and keeps on zooming in the map, the user has to click `-` Button many times to get to the default map view. This can be avoided by adding a reset zoom button on the map.

**Related Screenshot**

![Screenshot from 2020-02-19 22-49-04](https://user-images.githubusercontent.com/33249010/74858758-dba74500-536b-11ea-9cf7-33c640dcaf83.png)

**Comment by rohit645** [comment]
I am working on this feature.

**Comment by Angamanga** [comment]
@Obadha2 Could you do QA in Steve Buscemi?
1. Set a default zoom and location in general->settings
2. Go to map-view
3. Zoom and move the map around
4. Click on the home-icon above the zoom-controls
- [ ] The map should be zoomed and located just as the default zoom and location was set

**Comment by Obadha2** [comment]
QA'd, passes. :+1:
