### ISSUE TITLE
Number of selected user(s) remains same even after deletion.

### ISSUE THREAD

**Issue by noone0212** [ushahidi/platform#3853]
**Describe the bug**
The number of user(s) selected remains same even after deleting one or more users until the page is manually refreshed.

**Where was the bug observed**
Local environment with Vagrant.

**To Reproduce**
1. Setup local host with vagrant.
2. Log in as 'admin'.
3. Go to 'Settings' and scroll down to click on 'Users'.
4. Select any user  and delete it.
5. The selected number of users remain same even after deletion.

**Expected behavior**
The number of selected users shown must be updated accordingly.

**Screenshots**
![Screenshot from 2020-02-25 22-50-16](https://user-images.githubusercontent.com/46659112/75270972-78ad2680-5821-11ea-817a-5f56e19d4460.png)

**Comment by ritwizsinha** [comment]
I am working on this, please direct me to the relevant files

**Comment by rowasc** [comment]
@Obadha2 can you check this out in steve? Thanks !

**Comment by Obadha2** [comment]
QA'd, passes. 👍
