### ISSUE TITLE
Settings view platform-client has no icons.  

### ISSUE THREAD

**Issue by rohit645** [ushahidi/platform#3856]
**Description of the feature.**
Currently, the settings view of platform-client has no icons, which makes it look a bit odious.
 
**Describe the solution you'd like**
Icons already available in the platform library can be used to enhance the settings view.

**Screenshot of the settings view**
![Screenshot from 2020-03-01 03-25-15](https://user-images.githubusercontent.com/33249010/75615637-4fb3cb00-5b6c-11ea-89ad-bf66daf1ac68.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-152

**Comment by Erioldoesdesign** [comment]
Okay so! Here's a mock-up via an Adobe XD link: https://xd.adobe.com/view/775decf1-1a0a-4168-5df0-9c6ccb5331df-016c/

I've added in some pixel dimensions in the mock-up on the first setting menu item for guidance. These might not be exactly reflective of the live code sizes but approximations!

the grey circle is hex colour #888888 (as per colour in our Pattern librayhttp://github.ushahidi.org/dotcom-pattern-library/assets/html/1_basics/#pl-pattern-colors) 40px by 40px in the mockup and no icon is larger than 25px either height or width.

I've tried to only use icons in the OpenIonic library here:
https://ionicons.com/

We pretty standardly use Ionic icons as long as there is one that covers what we need. Also, they're all SVG so can be easily re-coloured and sized with code.

Here are the icons mapped:

General  = Ionic icon 'options'
Surveys = Ionic icon 'list'
Data sources = Ionic icon 'server'
Import = Ionic icon 'arrow-down-outline'
Configure HDX API and Username (a feature flagged setting) = HDX logo I'll upload after this comment.
Export = Ionic icon 'arrow-up-outline'
Users = Ionic icon 'people'
Roles = Ionic icon 'ribbon'
Categories = Ionic icon 'pricetags'
Webhooks = Ionic icon 'construct'
Plans = Ushahidi logo I'll upload after this comment.

Folks, let me know what you think but I think these, in circles, look nice, clean, well-balanced and helpful in the menu space.

You should also consider making the icon a click through link as well as the text e.g. 'Survey' text clicks through to survey setting page. Or, you can consider making the whole menu 'section' (the rectangle) a clickable are.

I would recommend testing this if you merge the added icons or waiting to see if anyone complains via customer support channels. In general, icons should help users identify sections easier.

**Comment by Erioldoesdesign** [comment]
Argh. Github doesn't support SVG file uploads. SVG icons not in Ionic are here: https://drive.google.com/drive/folders/1xezd2eBTODHVUsg3RjKhfg_nNvosy4dr?usp=sharing

**Comment by Angamanga** [comment]
@Erioldoesdesign Thank you for the mock-up :) Is there any chance we can use any of our existing icons in the Pattern-library instead? I don't think we use the iconic-icons in the platform so I would prefer the pl-ones... They are here: http://preview.ushahidi.com/platform-pattern-library/master/assets/html/1_basics/#pl-pattern-icons

**Comment by Erioldoesdesign** [comment]
@Angamanga ah sorry I thought we used the ionic icons but we actually use the "Open Iconic" library that we've added to the PL.

Looks like there are icons that map o the ones I've used but the ushahidi logo and the HDX logo would need uploading to PL?

**Comment by Angamanga** [comment]
@Erioldoesdesign Thank you, I think we used Ionic for TenFour but not Pattern Library? 

@rohit645 I will ping you once I have sorted out the logos to the pattern-library. Do you want guidance in finding another issue in the meantime?

**Comment by rohit645** [comment]
Sorry, I was a little bit busy these days. I am already on ushahidi/platform#3215 . I would love to discuss any possible solutions to this issue. I will revert back to you soon.

**Comment by Erioldoesdesign** [comment]
Icons from open iconic are mapped on the prototype: https://xd.adobe.com/view/775decf1-1a0a-4168-5df0-9c6ccb5331df-016c/

General = icon 'dashboard'
Surveys = icon 'list'
Data sources = icon 'layers'
Import = icon 'arrow-thick-bottom'
Configure HDX API and Username (a feature flagged setting) = HDX logo
Export = icon 'arrow-thick-top'
Users = icon 'people'
Roles = icon 'badge'
Categories = icon 'tags'
Webhooks = icon 'wrench'
Plans = Ushahidi logo

I would say that these open iconic icons aren't...great in both terms of icon variety and also the look of them! Perhaps something to update in the PL some day haha!
