### ISSUE TITLE
Load More button gets freezed and do not show all posts.

### ISSUE THREAD

**Issue by rohit645** [ushahidi/platform#3861]
** Steps to Reproduce**
1. Go your local environment of platform-client.
2. go to the data view. Posts should be (x of y where y > 20 to observe the bug).
3. **Do not click on loadmore button**
4. Go ahead and delete one post.
5. after deletion it shows x-1 of y posts(it should be x-1 of y-1).
6. if you now click on loadmore button, it should (y-1 of y posts) and loadmore button should go right away but it still appears and same happens on clicking it again (all posts are never shown).

**Expected behavior**
if initially it was like x of y posts
then on deleting one post it should be (x-1) of (y-1) posts.
after deletion of one post and loadmore button has been it should be y-1 of y -1 post.

**Comment by individual-it** [comment]
I'm currently working on this, but I cannot assign me myself

**Comment by rowasc** [comment]
https://github.com/ushahidi/platform/issues/3326 @rohit645 is this the same bug described here? 

cc @individual-it

**Comment by individual-it** [comment]
@rowasc that is part of it and will be solved together. Here its about the "load-more" function not working correctly.

**Comment by rohit645** [comment]
These are basically two issues that are sort of linked with each other in some way.
[a] Deletion of posts only after load more button is clicked and the number of posts > 20.
[b] Deletion of posts takes place before load more button is clicked and a number of posts > 20.

I have solved [a] part of it in https://github.com/ushahidi/platform-client/pull/1443.

It is the load more button that is creating this problem. Also if you tried to reproduce this issue you should have observed that load more button appears again when it is pressed (It should go right away). On clicking it again, it appears again.

I think the reason for this behavior is the counts of posts.length and totalItems is not being updated correctly in the case (when deletion occurs without clicking loadmore button).
You can find relevant files here: `app/main/posts/views/post-view-data.html L92` 
![Screenshot from 2020-03-12 11-15-33](https://user-images.githubusercontent.com/33249010/76491162-12e0b180-6453-11ea-9003-7ae06277fbe4.png)

posts.length should become equal to totalItems.

**Comment by rohit645** [comment]
@rowasc Do we really need this button? Is it going to load 1st 20 posts, then second 20 posts and so on...?

**Comment by individual-it** [comment]
here my approach https://github.com/ushahidi/platform-client/pull/1454
it seems to fix both problems but not  if there are exactly 41 posts before deletion and 40 after

I will add more tests, to confirm all the cases

**Comment by individual-it** [comment]
the issue with the load-more buttn has nothing to do with deleting the post. e.g. having 80 posts, clicking the first time on "load-more" sets off this request:
`http://172.17.0.1/api/v3/posts?has_location=all&limit=20&offset=20&order=desc&order_unlocked_on_top=true&orderby=created&reactToFilters=true&source%5B%5D=sms&source%5B%5D=twitter&source%5B%5D=web&source%5B%5D=email&status%5B%5D=published&status%5B%5D=draft` 

clicking it the second time this one
`http://172.17.0.1/api/v3/posts?has_location=all&limit=20&offset=80&order=desc&order_unlocked_on_top=true&orderby=created&reactToFilters=true&source%5B%5D=sms&source%5B%5D=twitter&source%5B%5D=web&source%5B%5D=email&status%5B%5D=published&status%5B%5D=draft`

the offset should be 40 and not 80

**Comment by individual-it** [comment]
my offset calculation was rubbish, now ushahidi/platform-client#1454 seem to fix both issues

**Comment by rowasc** [comment]
@Obadha2 can you check this out in steve? Thanks !

**Comment by Obadha2** [comment]
QA'd, passes. 👍
