### ISSUE TITLE
Warn users if they are offline

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#389]
Warn users if they are offline
- When we detect a user is offline, show a "You are offline" sticky warning 

- When we detect a user is online after having been offline, display a "You are back online" alert/message to let them know

----------

- out of scope: caching their actions to execute them later  (or alternatively, blocking form submissions when users are offline at least) https://github.com/ushahidi/platform/issues/3556

Original context from Jess
> Should the site be doing some sort of “pinging” to display how good the connection between the client and the server is? Internet was flakey during testing but I wasn’t getting any errors. If there is a deployment in remote areas this might be useful.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-746

**Comment by jshorland** [comment]
Can you input on this from a technical perspective, @rjmackay

**Comment by rjmackay** [comment]
Technically possible to both handle some basic operations while offline, and ping the server to check status. But its a huge jump in complexity I don't think we should dig into until everything else is a bit more stable

**Comment by rowasc** [comment]
@Angamanga does this sound reasonable to you as a very small step towards handling connectivity a little ? I think this might be feasible as a community / OSS task

**Comment by rowasc** [comment]
@Erioldoesdesign would the "alerts" system work for this? What we use to show errors
<img width="1438" alt="Screen Shot 2019-06-08 at 22 18 21" src="https://user-images.githubusercontent.com/2434401/59153881-5aa55900-8a3b-11e9-80bd-1d7ab69555e0.png">

**Comment by Erioldoesdesign** [comment]
@rowasc Yep - alerts style makes sense but we should inform users of what they can do next...

"You can continue to make changes while offline and as soon as you get online again, we'll ask you if you want to send changes to be completed"

Though my main question is, what things can a user do offline? if they actually can't do much (edit surveys, create new surveys, structure posts etc.) then we should inform them of the things they *can* do and then ask that they find a connection asap if they want to complete actions that we can't facilitate offline.

**Comment by rowasc** [comment]
yea. Right now they can't do much, except... get connected again and continue .  So I think the message would be something like you said ( "You can continue to make changes while offline and as soon as you get online again, we'll ask you if you want to send changes to be completed") . 

We should totally  handle connectivity as part of the larger tech strategy tho, offline submission + syncing the data with the backend when they go back online is huge for low connectivity areas.

**Comment by Angamanga** [comment]
@rowasc I think this would work as a community-task? Just the notification-part of it?

**Comment by rowasc** [comment]
@Angamanga yea absolutely, adding.

**Comment by codifyit** [comment]
Hi @rowasc What is the codebase for this issue? frontend or backend?

**Comment by codifyit** [comment]
Hi @rowasc and @Angamanga, are we looking to do something like this:
![image](https://user-images.githubusercontent.com/72559719/96417621-fab3ea80-120a-11eb-9035-86ea54b454b9.png)
![image](https://user-images.githubusercontent.com/72559719/96417728-1dde9a00-120b-11eb-8c72-a2218da4ea1f.png)
?
Or do we want to make it a bit fancier like with DOM and CSS?
Also, currently, I am doing this with addeventlistener and navigator.onLine, do we want to implement it with Service Workers? Although, it will definitely be a lil more complex and I'd have to read up on it a bit (also, SW could further be used for caching etc--referring to the comments above) but again, I would have to read up on it and learn about it more as I don't have much experience with it.
Please give your feedback
Thanks,
Roha

**Comment by Erioldoesdesign** [comment]
Just a UX two cents, if a message window like this isn't styled like the product then at best users are confused and think things are buggy and at worst, they might think it's a scary virus/ad/malware and be nervous to click ok.

Definitely pro this being CSS'd and styled like the product :)

**Comment by codifyit** [comment]
@Erioldoesdesign Appreciate your input :) Will try to make it better!

**Comment by helen-ndip** [comment]
> @Erioldoesdesign Appreciate your input :) Will try to make it better!

I think the previous conversations above have the desired alert. The codebase already has an alert system so it will better to use it.

**Comment by rowasc** [comment]
>I think the previous conversations above have the desired alert. The codebase already has an alert system so it will better to use it so as to make things consistent.
Yep, exactly.

**Comment by codifyit** [comment]
@helen-ndip thanks 👍 
@rowasc alright.

**Comment by codifyit** [comment]
@rowasc I am having trouble using the class alert with my code. I have also commented on gitter. Can you please help me?

**Comment by rowasc** [comment]
@codifyit I'm not sure I follow. Can you show me an example of the code that's giving you trouble when you add the alert class?

**Comment by codifyit** [comment]
@rowasc I am not familiar with Angular JS so I  just kind of tried to follow the code that was already written there. So here is an example:
 <div class="alert" role="alert" >
				<script type="text/javascript">
					window.addEventListener('online', updateStatus);
					window.addEventListener('offline', updateStatus);
					function updateStatus(event) {
						if(navigator.onLine){
							// alert('You are back online');
							<p>You are back online</p>
						} else{
							// alert('You are offline');
							<p>you are offline</p>
						}
					}
				</script>
            </div>
Also, I have been trying to study the code and I am not entirely sure in which container should I display this message

**Comment by codifyit** [comment]
@rowasc I am not that familar with Angular JS so I just kinda followed how the code was written and tried to replicate it. Here is an example:
                           <div class="alert" role="alert" >
				<script type="text/javascript">
					window.addEventListener('online', updateStatus);
					window.addEventListener('offline', updateStatus);
					function updateStatus(event) {
						if(navigator.onLine){
                                                  <p>You are back online</p>
						   } else{
                                                  <p>you are offline</p>
						}
                                       	}
				</script>
                            </div>
Also, I am not entirely sure which container i should be using to display my message

**Comment by rowasc** [comment]
Ah alright. Ok no worries. 
So there's a couple of parts to this, hopefully this rough guidelines will help
- You'll need to bind the connection checker to the app.run in the app.js code. You may want to follow something like this https://stackoverflow.com/questions/16242389/how-to-check-internet-connection-in-angularjs but move it to a separate file, like we do in our .run() code in app.js for interceptors for instance. And I think instead of $window.offline, the "accepted" way to do this in AngularJS is to use             $rootScope.$on('offline', function() and             $rootScope.$on('offline', function() like it's done here 
https://gist.github.com/amcdnl/e19281647e37882dcc22 (that's a good example of a module that does this btw)

- We'll need to use the Notify.notify functionality to show an alert when the offline broadcast happens. You can check out how we do export or post save notifications for instance (Search for "Notify.notify" in the codebase)
Here's an example  of the general syntax
```
        Notify.notify('<p translate="notify.export.canceled_job"></p>');
```

**Comment by codifyit** [comment]
Hi @rowasc thanks a lot for the clarification. I tried to use the notify functionlity earlier but I guess as I wasn't doing the offline broadcast, it didn't work. 
I am on it, I am going to try and implement it like you described with Angular and get back to you.
In the meanwhile though, can I please work on one of the more straightforward issues like adding roles to the elements https://github.com/ushahidi/platform/issues/4108
I can work on one of the remaining ones in the list which are not taken yet. I have commented on 4108. I would appreciate it. Want to secure a contribution.
Thanks,
Roha
