### ISSUE TITLE
Language selection shows white text on white background

### ISSUE THREAD

**Issue by pitus** [ushahidi/platform#3892]
Hi, the Language selection drop-down on the sidebar uses white text on white background so some people may not realize there's text in there to choose from ...

Also, why is there no Polish language available? I've seen PL at Github with valid strings. I need this for Poland so it's critical to have it available in Polish language. How can I help make it available?

Aha! Link: https://ushahiditeam.aha.io/features/PROD-146

**Comment by bimbolabuari** [comment]
@ rowasc and @Angamanga can i work on this please?

**Comment by Angamanga** [comment]
Closing this in favour of https://github.com/ushahidi/platform/issues/4106
