### ISSUE TITLE
Link to Android platform 3.x results in a 404

### ISSUE THREAD

**Issue by pitus** [ushahidi/platform#3893]
Hi,

I was looking for the Android app source code and found [this page](https://github.com/ushahidi/Ushahidi_Android). It says, this version is deprecated and works only with 2.x and that you're working on version compatible with 3.x but the link points to https://github.com/ushahidi/platform-android/ which doesn't exist - error 404.

Where is the 3.x Android source code?

**Comment by tuxpiper** [comment]
Hi! The source code is here: https://github.com/ushahidi/platform-mobile-app .

Fixing that README now :+1:
