### ISSUE TITLE
EDITing an entry while not providing required data, results in a stuck edit form.

### ISSUE THREAD

**Issue by pitus** [ushahidi/platform#3894]
**Describe the bug**
Trying to create a test Survey but there's a bug with its editing.
When a field is required and the user didn't select it, then clicked Save, they're ... not going to be happy as they just lost all of their data entered in the Surver :(
The form gets stuck in "Saving..." mode and Chrome DevTools show the following error:
status: 422
message: "Failed to validate posts entity:↵attribute Powiązany z... is required↵Stage "Czy jest nadal zapotrzebowanie" is required before publishing"

**Where was the bug observed**
https://korona-pl.ushahidi.io/posts/2

**To Reproduce**
1. Create a Survey with a required "Related Post" field type.
2. Submit a Survey with no value in the field
3. Edit the Survey
4. Hit Save while leaving the required Related Post empty
5. The Save button will remain in an animated Saving... state forever
6. See error - displayed on the screen as well as in the Chrome Tools

**Expected behavior**
When an error like that happens (server-side validation) and a message is shown to the user, the failing field should be indicated clearly and the Saving... button should be re-activated, allowing the user to make a correction and attempt to Save again. Otherwise they'll lose all the info already entered into the Edit Form.

**Is there a workaround? What is it.**
Didn't find any work-around at this point.

**Screenshots**
![image](https://user-images.githubusercontent.com/9009360/77267285-70ba9800-6ca2-11ea-96fb-e642d520d83a.png)

**URL / Environment where this happened**
https://korona-pl.ushahidi.io/posts/2

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**
it's not

**Desktop Hardware Details (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Chrome
 - Version 80.0.3987.122 (Official Build) (64-bit)

**Smartphone Hardware Details (please complete the following information):**
web-based problem

**Additional context**
I may have created the Survey first with that field not being required, hence I was able to create/submit it initially ... then changed the Survey making the field Required - the Survey editor should test if there are some entries in the database with the field value missing and warn me at that point... Perhaps that's why Editing the post later while forgetting to select required field results in an unexpected error and a locked UI.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-145

**Comment by individual-it** [comment]
I could not reproduce the mentioned issue, but something similar:
1. create a survey with an integer field
2. create a post for that survey
3. edit the post and enter a floating point number into that field
4. click save (it should not let you save the form it in the first place)

the save button is blocked for a while, but comes back again
