### ISSUE TITLE
Improve warnings for Survey deletion

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3896]
**Describe the issue* 

When someone is trying to delete a survey, we show this warning 
![Annotation 2020-03-24 113342](https://user-images.githubusercontent.com/2434401/77437530-883d7200-6dc3-11ea-940e-6b891c7afcc5.png)
The warning tells people that related posts will be deleted, but it's easy enough to ignore/not see it.  
We want to improve this feature to make it safer for users to use the survey admin system.

**Potential solutions**
- The modal should include an input that asks you to write the survey's name. 
- Change the DELETE button to read "YES, DELETE THIS SURVEY AND ALL RELATED POSTS"
- Make the text that explains the impact 2px bigger (or something that makes sense, at @Angamanga  discretion)

**Comment by Angamanga** [comment]
I vote for solution 1 + 2!

**Comment by Angamanga** [comment]
No, all 3 actually!

**Comment by rowasc** [comment]
🌮 aweesome

**Comment by Angamanga** [comment]
Spec:
1.  Change the html for the confirm-delete-box to include an input-box for the user to type the name of the survey (or possibly a new box after the user clicks delete).
2. Adjust the function for the "confirmDelete"  to check that the name of the survey is typed in correctly before deleting.
3. Change the text in the warning-box + the button to be more clear.
