### ISSUE TITLE
Share button should not be visibile on post creation screen

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3897]
**Describe the bug**

I see the " Share " button next to " Send " yellow button, but that should not be available on post creation. 

![Annotation 2020-03-24 132821](https://user-images.githubusercontent.com/2434401/77451386-59c79300-6dd3-11ea-9686-a958353c31e4.png)

**Where was the bug observed**
https://uruguayayuda.ushahidi.io
It happens in my other deployments too (ie rominacsvsms)

**To Reproduce**
1. Go to create a post
2. look at the top bar
3. You see a "share" button

**Expected behavior**
1. Go to create a post
2. look at the top bar
3. You DO NOT see a "share" button

Aha! Link: https://ushahiditeam.aha.io/features/PROD-143

**Comment by rowasc** [comment]
@Obadha2 can you check this out in steve? Thanks !

**Comment by Obadha2** [comment]
@rowasc I see this. The link to be shared opens a survey to be responded to.
I'm thinking this is needed when you want to share a link for someone to respond to a survey. Are we sure this is not (correctly)expected behavior?

**Comment by rowasc** [comment]
Ugh, that's... a really good point. I didn't think of the need to share a "respond to survey" becuase I'd normally just copy the link myself 🙈 
Ok I'm going to revert this, because it's likely someone needs it and we would be removing an accessible way to share it.

**Comment by Angamanga** [comment]
@rowasc It sounds like the decision here is to keep the share-button on post-creation-screen? Can I close this issue?

**Comment by Sunairaa** [comment]
Hey, @Angamanga  is this issue still available?

**Comment by rowasc** [comment]
Yep @Angamanga Walter is right. Clsoing
