### ISSUE TITLE
in Firefox column titles are not shown during import step 2

### ISSUE THREAD

**Issue by individual-it** [ushahidi/platform#3903]
**Describe the bug**
Firefox does not show the names of the columns when trying to import a CSV

**Where was the bug observed**
local development installation

**To Reproduce**
1. open plaform-client using the FF browser
2. Log in as administrator
3. Click on 'Settings'->"Import"
4. choose a file and survey
5. click on "Continue"
6. open the dropdown of any survey field

**Expected behavior**
the CVS columns should be shown

**Is there a workaround? What is it.**
use an other browser :-(

**Screenshots**
![image](https://user-images.githubusercontent.com/2425577/77733420-f5a10b00-702e-11ea-9c77-6a8d49954867.png)

![image](https://user-images.githubusercontent.com/2425577/77733430-f9349200-702e-11ea-8081-56e27aac2e8c.png)

**URL / Environment where this happened**
[e.g http://qa.ushahidi.io/post/create]

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**

**Desktop Hardware Details (please complete the following information):**
 - OS: Ubutu
 - Browser Firefox
 - Version 74

**Additional context**
The issue is, that Firefox does not use the `label` attribute of the `<option>` tag see https://www.w3schools.com/TAGS/att_option_label.asp

**Comment by individual-it** [comment]
fix in https://github.com/ushahidi/platform-client/pull/1477

**Comment by rowasc** [comment]
Duplicate of https://github.com/ushahidi/platform/issues/2603 

Thanks @individual-it , we'll check it as soon as possible.

**Comment by individual-it** [comment]
closing as duplicate
