### ISSUE TITLE
Move validation of video-url to post-validation service

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3904]
**Describe the bug**
Validation of the video-url happens in the video-directive upon blur. Even if an url that is not valid (youtube or vimeo) is added post can still be saved, but it does not save the url. It is easy for the user to miss this, so it would be better to move the validation to the save-validation instead. Here the user would be notified that its not a valid url and that they need to add a valid one (or remove the url if the field is not required).

**Where was the bug observed**
Production, QA, local env.

**To Reproduce**
1. Add a post to a survey with a video-field
2. Add a random, non-youtube/non-vimeo-url to the video-box.
3. Hit save
4. You will see a error-notification that is it not a valid url
5. The post will still save, without the url added.

**Expected behavior**
- You will see a error-notification
- The post will not save until the field is empty or have a valid url

**Is there a workaround? What is it.**
You can go back and edit the post and add a correct url

Aha! Link: https://ushahiditeam.aha.io/features/PROD-138

**Comment by brymut** [comment]
More than happy to have a look at this this week.

**Comment by Angamanga** [comment]
@brymut Please go ahead 🎉 Reach out if you need any further guidance!
