### ISSUE TITLE
Secondary toolbar and add-post-button look untidy while editing post.

### ISSUE THREAD

**Issue by noone0212** [ushahidi/platform#3905]
**Describe the bug**
- Secondary toolbar and add-post-button look untidy while editing post.

**Where was the bug observed**
- Local environment with vagrant.

**To Reproduce**
- Login into the deployment.
- Go to Data.
- Select any post to edit.
- Scroll down to end of page.

**Expected behavior**
- Disabling add-post-button while Editing post makes it look tidy.

**Screenshots**
![Screenshot from 2020-03-31 13-32-54](https://user-images.githubusercontent.com/46659112/78004094-467a7180-7357-11ea-8b2c-c95ff397725e.png)

**Comment by Erioldoesdesign** [comment]
So you'd like to disable the circle + button when editing a post?

**Comment by noone0212** [comment]
Yes, I think of disabling it. I have done [here](https://github.com/ushahidi/platform-client/pull/1479).

**Comment by rowasc** [comment]
@Obadha2 can you test? THanks !

**Comment by Obadha2** [comment]
QA'd, passes. 👍
