### ISSUE TITLE
Making buttons more attractive.

### ISSUE THREAD

**Issue by noone0212** [ushahidi/platform#3906]
**Current Scenario**
At many places, there are two buttons which look different in terms of padding like shown.

**Suggested Solution**
Adding padding to not padded ones, makes them look more attractive.

**Screenshot**
![Screenshot from 2020-03-31 17-33-25](https://user-images.githubusercontent.com/46659112/78024958-d976d400-7376-11ea-82b8-806b81f11d9f.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-137

**Comment by TunrayoIlawole** [comment]
Hi @rowasc Can i work on this?

**Comment by rowasc** [comment]
hi @TunrayoIlawole no there's already a PR for it. Do you have another ticket assigned? (I can't check but I think I assigned one earlier today) . LMK if not
