### ISSUE TITLE
Private toggle button on the title and description field should not be displayed as an option

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#3909]
**Describe the bug**
The private toggle button on the title and description fields are not working and should not be there in the first place since these are the two fields that are needed on postcards when displayed on the map. 

**Where was the bug observed**
Production

**To Reproduce**

1. Go to settings
2. Click on a survey
4. Click on the title/description field.
5. The UI makes it appear that users can opt to have the decision to make the fields private when this is not actually the case.

**Expected behavior**

The "make response private" button should not be displayed 

**Screenshots**
<img width="480" alt="Surveys_-_Heba" src="https://user-images.githubusercontent.com/20906968/78222184-764b8580-74cd-11ea-8de9-3c9df15229d7.png">

**Comment by rohit645** [comment]
@Angamanga can I work on this issue?

**Comment by rowasc** [comment]
@rohit645 YES 🎉
