### ISSUE TITLE
Not So Good API Request validation

### ISSUE THREAD

**Issue by anje123** [ushahidi/platform#3913]
**Describe the bug**
Based on the API Documentation https://docs.ushahidi.com/platform-developer-documentation/tech-stack/api-documentation, the datatype like string, numeric, object where given but the  Ushahidi platform validation does not accurately follow it, in a case where when I send a post request to the
/api/v3/posts endpoint, I can insert a numeric value in a field that requires a string value, without no  error response sent back 

**Where was the bug observed**
All Endpoint that requires an input value e.g /api/v3/posts 
**To Reproduce**
1. Go to ushahidi platform API docs
1. get authenticated by using the bearer auth  token 
2. send an invalid post request to /api/v3/posts endpoint, using POSTMAN as suggested previously

**Screenshoot**
![Screenshot from 2020-04-06 11-17-06](https://user-images.githubusercontent.com/31329500/78572504-77f3b100-781f-11ea-92bb-aa4b665220cc.png)

**Expected behavior**
you get a 200 ok response when you are supposed to get a 400 or 422 error response

**Is there a workaround? What is it.**
After some checking, I noticed the Ushahidi platform uses the ushahidi/kohana-validation which does not have a function that handles does validations, so I think the API validation is still a little bit vulnerable

**Desktop Hardware Details (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser postman

Aha! Link: https://ushahiditeam.aha.io/features/PROD-134

**Comment by tuxpiper** [comment]
Thank you for the detailed report @anje123 !

We will be handling some of these with https://github.com/ushahidi/platform/pull/3811 , using this issue as anchor .

I think we will be seeing general improvements to validations as we move on to the next major version of API, which will drop kohana for good. .

@all-contributors please add @anje123 for bug
