### ISSUE TITLE
Default location zoom when adding post

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#392]
When "add a post" page opens, the map should automatically centre on your current location/country

**Comment by jshorland** [comment]
Security issues with this

**Comment by sophshep** [comment]
But we should make the "my location" select more prominent in this view:

![image](https://cloud.githubusercontent.com/assets/527589/10545075/68919434-73ec-11e5-8f35-55944bdb7962.png)

If you missed it as I did the first few times, it's under the zoom buttons

**Comment by rjmackay** [comment]
- We can grab user location automatically.. most browsers will ask them for permissions.
- Design tweaks for a more obvious 'find my location' would be good..

**Comment by sophshep** [comment]
I'm going to close this in favor of #783, where @brandonrosage is planning on rethinking how this location picker works and should be displayed.
