### ISSUE TITLE
Unable to publish post if there are two location fields, one of the fields being required.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3922]
**Describe the bug**
If a survey has more than one location field, and one of the location fields is a required field, a post submitted to this post can't be published.

**Where was the bug observed**
Deployment - https://test-deployment.steve-buscemi.ush.zone/views/map

**To Reproduce**
1. Go to deployment.
2. Create survey with two location fields, make one of the fields as required.
3. Go to Data view, and add a post to this survey.
4. Fill in both location fields.
5. Save this post.
6. Change the status of this post to Published.
7. Publishing fails with error (see attached screenshot)

**Expected behavior**
Posts should be publishable once all required fields are provided.

**Is there a workaround? What is it.**
None.

**Screenshots**
<img width="1750" alt="Screenshot 2020-04-09 at 12 27 54 PM" src="https://user-images.githubusercontent.com/38259840/78890771-e4b0ba80-7a6e-11ea-9bba-34a60ee5790c.png">

**URL / Environment where this happened**
https://test-deployment.steve-buscemi.ush.zone/posts/6089

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 80.0.3987.163

**Comment by rowasc** [comment]
@Obadha2 Why isn't this a blocker? is it a regression or not?

**Comment by rowasc** [comment]
I just checked, this *IS* a regression, since I cannot make it happen in production, or maybe I'm doign something wrong. 
@tuxpiper @Obadha2 please let me know why this was not seen as a blocker/if I'm missing something?

**Comment by tuxpiper** [comment]
mm bummer..

It was my estimation that it wouldn't be a regression, given that it was a newly introduced test and how wonky the behavior is in other places when the form has two location fields.

On the other hand, I think we may be pushing the envelope here, compared to the typical use of platform. The code is not well prepared for handling the case of 2 locations, but we haven't gotten bug reports other than from our own testing.

**Comment by rowasc** [comment]
@tuxpiper not sure what you mean pushing the envelope? (sorry!) 
And yes support is bad for multi location, but preventing publishing is badder 🤔 
@Obadha2 really curious to hear if this is something you verified in production to make this call because it may just be that I'm having trouble with it. Please let me know.

**Comment by Obadha2** [comment]
@rowasc this isn't happening in prod, so it's new. I think we decided this wasn't a blocker since we saw the odds of having more than one location field in one survey as minimal so we thought this wouldn't block or get in the way of regular use of the platform.

**Comment by rowasc** [comment]
ok thanks @Obadha2 
@tuxpiper can you work on a fix and let us know so we can release without the regression? 😬 
Thanks

**Comment by tuxpiper** [comment]
*warming up gross hack generator cannon*
*aiming cannon to already gross codebase*
no problem, just leave it to me :+1:

**Comment by tuxpiper** [comment]
@rowasc fix PR posted : #3937

**Comment by tuxpiper** [comment]
note that things like fetching geojson will be slow again , when the form contains 2 location fields

**Comment by Obadha2** [comment]
QA'd, passes. 👍
