### ISSUE TITLE
Mapbox geocoder support

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3927]
**Which user group(s) are the primary audience for this feature/enhancement.**
Any user looking up map locations by place name / landmarks

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Mapbox offers a geocoding service which possibly may offer superior results to Nominatim,  because it incorporates several other sources of data.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Aha! Link: https://ushahiditeam.aha.io/features/PROD-130

**Comment by rowasc** [comment]
This would be something configurable, I assume? 
Ideally for SaaS we should be able to enable this for specific deployments, and of course OSS deployers can pick their own.

**Comment by aoduor** [comment]
Related perhaps? (lmk if not, I can create a separate issue for it <3)

Erica, from Map Kibera flagged a need to use their own custom base maps too.

**Comment by rowasc** [comment]
Ah, no this is different. You created an issue for it already like 5 years ago :/  but I will bring it up again soon 
https://github.com/ushahidi/platform/issues?q=is%3Aissue+is%3Aopen+layers

**Comment by rowasc** [comment]
Tagged an issue with Canadian postal codes and Irish ones as well it seems.
The other day I was preparing a doc related to this and also found a couple of other providers. It'd be nice to abstract it away and see if the provider itself would be something users could change in their settings?
