### ISSUE TITLE
Ability to change survey field types post-survey creation

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3930]
**Which user group(s) are the primary audience for this feature/enhancement.**
Likely all deployers

**Is your feature request related to a problem? Please describe.**
Had a great chat with Erica Hagen, who flagged a frustration with survey fields after they've been set up. Currently, once you've set up a survey field, say "text field", you can't come back and change the field type to "description" etc. You'd need to delete the field and set up a new one

**Describe the solution you'd like**
I'm not sure there's an easy solution to this, but worth flagging as something to think about for deployers.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-128

**Comment by rowasc** [comment]
Yea. The thing with this is that the usecase where it's most useful (ie once you already have responses) is also the most problematic, because a large portion of your data may no longer be valid for the new type. 
I'm not entirely sure how we could make this happen without adding a lot of complexity but keeping in my mind 🤔

**Comment by rowasc** [comment]
@CeciliaHinga did you ever hear other requests for this? It's not something I've heard before so I'd like to collect some data if we have it

**Comment by rowasc** [comment]
also @aoduor could you explain the user flow a bit more? When are they most needing this? Is is just while they are creating the surveys the first time and make small field type mistakes? or are they coming back later and trying to do that? 
Would it be useful if we only allow it as long as there is no survey data?

**Comment by Angamanga** [comment]
Tricky to implement. Works for fields without any posts/data yet.
