### ISSUE TITLE
The link to create a new Twitter-app is wrong

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3932]
**Describe the bug**
The link to Twitter is wrong in datasources->Twitter.

**Where was the bug observed**
.io

**To Reproduce**
1. Go to 'settings->datasources->Twitter'
2. Click on the link "Create your Twitter application here"
![Screenshot 2020-04-14 at 10 55 07](https://user-images.githubusercontent.com/8624777/79205614-76894080-7e3e-11ea-8d96-606ad1e40043.png)
3. You will get directed to an empty page on Twitter.

**Expected behavior**
You should get directed to the correct page on Twitter (Either https://developer.twitter.com/ or https://developer.twitter.com/en/apps/create).

Please note: This has to be changed in the Platform-API repo: https://github.com/ushahidi/platform/blob/develop/src/App/DataSource/Twitter/Twitter.php#L79

**Comment by noone0212** [comment]
May I work on this issue?

**Comment by Angamanga** [comment]
@noone0212 Absolutely! Thank you :)
