### ISSUE TITLE
Buttons when searching and selecting related posts is just a black box

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3933]
**Describe the bug**
The buttons when searching and selecting related posts are just a black box that does not make sense:

![Screenshot 2020-04-14 at 11 09 51](https://user-images.githubusercontent.com/8624777/79207156-9faad080-7e40-11ea-9922-5a65a5702233.png)
![Screenshot 2020-04-14 at 11 09 45](https://user-images.githubusercontent.com/8624777/79207160-a0436700-7e40-11ea-8d3c-bf9fa29cd795.png)

**Where was the bug observed**
.io
**To Reproduce**
1. Add a post to a survey with the field "Related posts"
2. Type in something in the search-field (the search looks in "Title" and "Description" of existing, *published* posts)
3. Look at the list

**Expected behavior**
The buttons should not be black, there should be a + sign when selecting a post and a cross-sign for removing a post

**Is there a workaround? What is it.**
Just click on the buttons and hope for the best 😬

**Hints for implementation 💡 **
The code for the buttons lives here:
- https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/modify/relation.html#L2
- https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/modify/relation.html#L23

Here we want to use icons instead of empty buttons, in line 2, we want a trash icon and on line 23 a checkmark.The icons we use are svgs and are imported like this:

```
<svg class="iconic">
    <use xlink:href="/img/iconic-sprite.svg#add-name-of-icon"></use>
</svg>
```
Add "trash" instead of add-name-of-icon for line 2 and "check" for line 23. Add this in the button element and you should see the icon! 

We also want to change the type of button we use. This is done with classes.
For the trash-button, change the class "button-secondary" to "button-destructive". You can remove the rest of the classes, they are not used anymore. 

For the check-mark-button, change the class "button-secondary" to "button-alpha". You can remove the rest of the classes here as well.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-126

**Comment by renujain31** [comment]
Hey @Angamanga , Can I work on this one! I am new to open source and want to contribute in the project as a part of my outreachy application.

**Comment by Angamanga** [comment]
Hi @renujain31 and welcome 🎉 ! I realised after adding this issue that its already solved and waiting for release. I am in the process of adding new first-timers-only issues, I suggest you start with this one instead: https://github.com/ushahidi/platform/issues/4078

**Comment by renujain31** [comment]
Okay @Angamanga! Thanks for the issue. I would start working on that!
