### ISSUE TITLE
Links to related posts does not work

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3934]
**Describe the bug** When clicking on a linked related post in a post, the link does not work. [https://user-images.githubusercontent.com/8624777/79207651-40998b80-7e41-11ea-974b-d260dfcf6ef6.png](https://user-images.githubusercontent.com/8624777/79207651-40998b80-7e41-11ea-974b-d260dfcf6ef6.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-125

**Comment by jordanmiracle** [comment]
I've forked this and am working on it.

**Comment by Obadha2** [comment]
(Where) Is this deployed @rowasc

**Comment by rowasc** [comment]
@Obadha2 it should be in steve (check codeship to make sure it landed )

**Comment by Obadha2** [comment]
@rowasc this passes QA.

**Comment by rowasc** [comment]
Thanks!
