### ISSUE TITLE
Search feature on Users works only intermittently.

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#3936]
**Describe the bug**
The search feature on users page does not work on all search instances. On performing a search, on some occasion it works and on some occasion, it does not. All randomly. 

**Where was the bug observed**
Test deployment - steve buscemi. 
users page

**To Reproduce**
1. Log into a deployment as an admin.
3. Navigate to the users page.
4. In the search bar, enter text to search in the list of users.
5. Hit Enter to perform search.
6. Perform the search several times. Step 4 and 5 over and over. 
7. You'll notice the search function works in some instances, in some instances it does not work.
8. When it does not work, the entire list of users is shown instead.
9. So on performing a search, one of two things happen. Either the right results are shown, or the entire list of users is shown.

**Expected behavior**
On performing a search, only the correct search results should be shown every time.

**Is there a workaround? What is it.**
Keep performing a search till the correct results are shown.

**URL / Environment where this happened**
https://test-deployment.steve-buscemi.ush.zone/settings/users

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS 
 - Browser: Chrome
 - Version: 81.0.4044.92 (Official Build) (64-bit)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-124

**Comment by rowasc** [comment]
>Perform the search several times. Step 4 and 5 over and over.
Are you performing *the same search* every time? ie same search criteria?

**Comment by Obadha2** [comment]
Same, and both.
Randomly.

**Comment by rowasc** [comment]
For anyone trying to fix this issue
- Go to users
- Enter a search term that matches a user (ie if you have a user with the email "romina@ushahidi.com" then search for "romina")
- Hit enter/return key
- You will get all the results rather than just the one you wanted. 

This happens because the request is going twice, one with no criteria (q="") and another with your search criteria (q=romina)

**Comment by rowasc** [comment]
Completely unsure of why exactly but the $scope.$watch(filters  is being triggered twice in this scenario.
