### ISSUE TITLE
Unabe to edit a survey's description field. Field broken.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3942]
**Describe the bug**
The description field for fields in a survey is uneditable. Additionally, format options for heading can't be dismissed, and hyperlink option is too far left.

**Where was the bug observed**
Creating and/or Editing survey fields - https://test-deployment.steve-buscemi.ush.zone/settings/surveys/create

**To Reproduce**
1. Go to survey creation page.
2. Add a field.
3. Click on the optional description field to edit it.
4. Note that the field cannot be clicked into to enable editing.
5. Click on *H* to bring up header options. Nothing happens no selecting any one of the options.
6. Click on link option. Note that the link fields are out of focus.

**Expected behavior**
Description field should be editable. Clicking on the field enables it for editing. 

**Is there a workaround? What is it.**
None

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version 81.0.4044.92 (Official Build) (64-bit)

**Comment by MemeDeveloper** [comment]
**Additional Info** 

e.g. https://SUBDOMAIN.ushahidi.io/settings/surveys/edit/6

I see today two errors in console. Chrome browser on PC:

**New today** 
```
console.js:35 Error: [ngModel:datefmt] Expected `2020-04-16T23:00:00.000Z` to be a date
https://errors.angularjs.org/1.7.9/ngModel/datefmt?p0=2020-04-16T23%3A00%3A00.000Z
    at angular.js:138
    at Array.<anonymous> (angular.js:26701)
    at Object.$$format (angular.js:31075)
    at Object.$processModelValue (angular.js:31055)
    at Object.$$setModelValue (angular.js:31087)
    at angular.js:31126
    at o.$digest (angular.js:19134)
    at o.$apply (angular.js:19503)
    at angular.js:13346
    at g (angular.js:13603)
    at XMLHttpRequest.f.onload (angular.js:13508)
    at XMLHttpRequest.e (raven.js:376) undefined
e.<computed> @ console.js:35
```

**Noticed when noticed this bug last week** 
`[object%20Module]:1 Manifest: Line: 1, column: 1, Syntax error.`

Also I think this bug appeared last week sometime certainly this was working previously. 

Hope that helps

**Comment by MemeDeveloper** [comment]
Fixed for us here. Thanks.
