### ISSUE TITLE
Checkbox selections do not persist on submitted survey responses - mobile.

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#3949]
**Describe the bug**
On android mobile application, when you open a response submitted to a survey, if there are checkbox fields and there have been selections on the checkboxes, the checkboxes appear as no options have been selected.

**Where was the bug observed**
- Android mobile application, edit survey responses.

**To Reproduce**
1. Go to android mobile application.
2. Log in as member/admin to your deployment.
3. Click on View Responses to view submitted responses.
4. Click on pencil icon to open response for editing.
5. The response has to be for a survey that has checkbox options.
6. Note that checkbox options that had been selected are all unselected.
7. All other text fields have their data persist.
8. Also note that in edit mode, a survey response can be submitted even if a checkbox field was marked as required, but no option is selected.

**Expected behavior**
All data in all fields should persist if a field is opened for editing.

**Is there a workaround? What is it.**
None.

**Smartphone Hardware Details**
 - Device: Samsung S10+
 - OS: Android Version Version 10
 - Ushahidi Mobile Application Version 1.13

Aha! Link: https://ushahiditeam.aha.io/features/PROD-121

**Comment by rowasc** [comment]
@Obadha2 do we have any data to see if this was a regression? trying to figure out if serverside or clientside , will debug this week

**Comment by Obadha2** [comment]
@rowasc no, unfortunately. Probably because AFAIK mobile(android) hasn't been touched in a while.
