### ISSUE TITLE
Required field indicators on "add post" form

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#395]
Add indicators for required fields on the ‘add post’ form e.g. red asterisk symbol

**Comment by rjmackay** [comment]
I think there's something in the pattern library for this.. if not, improvise ;)

**Comment by willdoran** [comment]
there is infact a required class, I'll add it and update it to colour red, it's for the label entity - is it preferable to attach it to the input?

**Comment by willdoran** [comment]
Ok, this is pushed and @middle8media very kindly pushed the colour change into pattern library.
