### ISSUE TITLE
Poorly visible font/background on hint field for toggling featured option on Collections.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3956]
**Describe the bug**
On the collection creation/edit form, the hint field has poor visibility. See attached screenshot.

**Where was the bug observed**
Edit or create collections - featured option - https://walterqa.ushahidi.io/collections/5/map

**To Reproduce**
1. Go to a deployment.
2. Log in as as admin (or privileged member)
3. Click on 'Collections.'
4. Click on Create new to open form to create a collection.
5. Hover your mouse/pointer over featured field.
6. Hint that appears has poor visibility on the text.

**Expected behavior**
The field and text should be clearly visible and easily readable.

**Is there a workaround? What is it.**
Move your eyes closer to the screen, while squinting, to be able to read the text. :) 

**Screenshots**
<img width="525" alt="Screenshot 2020-04-24 at 12 35 20 PM" src="https://user-images.githubusercontent.com/38259840/80198438-bc0cf100-8628-11ea-8419-fc1f8dec04f4.png">

**URL / Environment where this happened**
https://walterqa.ushahidi.io/collections/5/map
 - Happens on both prod and test(steve-buscemi)

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 81.0.4044.113 (Official Build) (64-bit)

**Comment by noone0212** [comment]
May I work in this?

**Comment by rowasc** [comment]
That'd be awesome yea ! thanks @noone0212

**Comment by Obadha2** [comment]
QA'd, passes. :+1:
