### ISSUE TITLE
Unable to delete address set up for notifications.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3959]
**Describe the bug** Attempts to delete addresses (emails and phone numbers) set up for notifications for a profile fails.

**Where was the bug observed** Test deployment on prod environment - [https://walterqa.ushahidi.io/settings](https://walterqa.ushahidi.io/settings)

**To Reproduce** 1. Go to your deployment. 2. Log in as admin. 3. Click on your favicon on the left sidebar(above the logout button) 4. Click on Notifications tab. 5. On an account, click on the drop-down arrow to reveal options for the already existing notifications accounts. 6. Click on Remove account. 7. Click Delete on the confirmation dialogue. 8. The Save&Close button is greyed out, nothing else happens. The contact persists.

**Expected behavior** When you remove a contact from notifications, it should not be there anymore. The process should complete successfully, without any errors.

**Is there a workaround? What is it.** None.

**URL / Environment where this happened** [https://walterqa.ushahidi.io/settings](https://walterqa.ushahidi.io/settings)

**Logs** ` TypeError: a.deleteEntity is not a function at Function.a.delete (contact.js:62) at notifications.directive.js:111 at angular.js:17948 at angular.js:17996 at o.$digest (angular.js:19114) at o.$apply (angular.js:19503) at HTMLButtonElement.<anonymous> (angular.js:28958) at Re (angular.js:3826) at HTMLButtonElement.t (angular.js:3814) at HTMLButtonElement.t (raven.js:376) "Possibly unhandled rejection: {}" `

**Desktop Hardware Details (please complete the following information):** - OS: iOS - Browser: Chrome - Version 81.0.4044.113 (Official Build) (64-bit)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-118

**Comment by rowasc** [comment]
ah gross. Tagging  community to see if someone has the bandwidth :( 
Thanks for finding this

**Comment by rajat641** [comment]
Hi @rowasc , I can help in fixing this up. Please let me know if I can work on it.

**Comment by ritesh-pandey** [comment]
I would like to work on it.
