### ISSUE TITLE
Date field gets default value for non-required fields.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3961]
**Describe the bug**
Date fields have a default value that persists and is saved when a response to a survey is submitted. 

**Where was the bug observed**
Production - https://walterqa.ushahidi.io/posts/19/edit

**To Reproduce**
1. Go to a deployment.
2. Navigate to a survey that has an unrequired date field.
3. Note that the date field has a default value that is the day for the current date.
4. Save this response to the survey.
5. Note that the unrequired date field has the default value persist.

**Expected behavior**
The unrequired date field should have the option of not having a default value.

**Is there a workaround?**
Yes. When creating the unrequired field, provide a default value. This default value could be any random strings.
When you go to submit a response, the date field will be blank instead of having the day's date as a default value. Saving as is will have this field saved as blank.

**URL / Environment where this happened**
https://walterqa.ushahidi.io/posts/19/edit

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version 81.0.4044.113 (Official Build) (64-bit)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-117

**Comment by tuxpiper** [comment]
@all-contributors please add @AngadSethi for code

**Comment by AngadSethi** [comment]
Thank you @tuxpiper!

**Comment by tuxpiper** [comment]
Fix reverted by ushahidi/platform-client#1613

**Comment by tuxpiper** [comment]
@Obadha2  as far as I understand, this was never fixed as the only fix that was submitted was rejected. Let me know if I'm wrong.

**Comment by Obadha2** [comment]
@tuxpiper this doesn't happen anymore. we can close this.

**Comment by tuxpiper** [comment]
Oh great :+1: thank you!
