### ISSUE TITLE
The checkbox options are not displayed on the survey form when you add duplicate options

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#3962]
**Describe the bug**

When a user adds a checkbox as a field type then add field options that are identical, save and submit to the survey, all checkbox options do not appear on the survey form. If you remove the duplicate, Save, and add to the survey again, the checkbox options are displayed on the form.

**Where was the bug observed**
Production

**To Reproduce**
1. Go to settings
2. Click on surveys
3. Click on an existing survey, then 'Add field'
4. Scroll down and add the checkbox(es) field type
5. Enter the necessary information then add duplicate field options.
6. Click on Add $ Close.
7. Save and add to the survey.
8. On the survey form, you will only see the title of the checkbox field type but not the field options.

**Expected behavior**
When a user adds duplicate field options and tries to save the checkbox field type, they should get an error message of the existing duplicates.

**Is there a workaround? What is it.**
If they realize the error, users can delete the duplicate field option and save the field type again.

**Screenshots**
<img width="607" alt="Create_Post_-_test254" src="https://user-images.githubusercontent.com/20906968/81160363-a38ac800-8f92-11ea-90ae-124bdbda5350.png">

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS
 - Browser chrome

Aha! Link: https://ushahiditeam.aha.io/features/PROD-116

**Comment by rowasc** [comment]
closing in favor of #3994  (where we are fixing this!)
