### ISSUE TITLE
Post submission / admin review confirmation

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#397]
Whenever I publish my report, I should get a notification that it will be reviewed by an admin before being made public; this is not the case currently

- Admins should see "Your post is saved" + link to post
- Non admins/people who can't publish posts should see "Your post is saved and will be reviewed by a moderator" or something similar.

**Comment by willdoran** [comment]
I can add this under  #746 - which I think needs some discussion before it can proceed.

**Comment by rjmackay** [comment]
For a quick solution to this issue we should
- Show 'post will be reviewed by the admin' to users without the 'change status' permission (same check used for showing the publish to X UI)
- Other users should get 'your post is here...' message
Does that make sense @willdoran ?

**Comment by rjmackay** [comment]
@willdoran is this done? in progress? abandoned?

**Comment by willdoran** [comment]
This is done and in PR [129](https://github.com/ushahidi/platform-client/pull/129)
