### ISSUE TITLE
Deleted Surveys are labeled as "unknown" on the sort and filter page

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#3974]
**Describe the bug**
When you delete a survey, it shows that it has been deleted but once you go to filter data by surveys the existing surveys are displayed, as well as a survey labeled as "unknown". This unknown survey is the deleted one.

**Where was the bug observed**
Production

**To Reproduce**
1. Go to settings, then surveys
2. Click on the (...) icon that is adjacent to the survey you want to delete.
3. A pop up message will appear showing that the survey has been successfully deleted.
4. Go to data/map view and click on sort and filter
5. Scroll down to filter by survey. The existing surveys are displayed together with a survey displayed as "unknown".

**Expected behavior**
Once a survey has been deleted all traces of it should be deleted as well, it should not be displayed as "unknown"

**Is there a workaround? What is it.**
No

**Screenshots**
<img width="240" alt="Posts_-_test254" src="https://user-images.githubusercontent.com/20906968/82429382-765f0f00-9a94-11ea-84d4-690874b22574.png">

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS
 - Browser: chrome

Aha! Link: https://ushahiditeam.aha.io/features/PROD-109

**Comment by rowasc** [comment]
Are you seeing the survey contents in that unkwnown filter? or are you just
seeing that filter? Unknown is showing the  unstructured SMS/Email data
that isn't linked to a survey typically, so it's a little odd.

**Comment by CeciliaHinga** [comment]
No you cannot see the survey contents, you can only see that filter.
