### ISSUE TITLE
API link fields curr, next, and prev lose filtering

### ISSUE THREAD

**Issue by bb** [ushahidi/platform#3977]
**Describe the bug**

In the API endpoint `/api/v3/posts`, the response fields `curr`, `next` and `prev` lose filtering information from the query. E.g. when filtered for `status[]=draft` (i.e. not published), I expect the curr URL to keep this information. Also, the `next` URL should keep it, so I could e.g. write a client which could browse through the API by just looking at the 'next' field and proceed to that URL; e.g. for paging.

E.g. the output of https://quakemap.api.ushahidi.io/api/v3/posts?created_after_by_id=537&has_location=all&order=desc&order_unlocked_on_top=true&orderby=created&source%5B%5D=sms&source%5B%5D=twitter&source%5B%5D=web&source%5B%5D=email&status%5B%5D=draft contains no results (as I filtered only for drafts and the following item 538 is published). and has `curr":"https:\/\/quakemap.api.ushahidi.io\/api\/v3\/posts?orderby=created&order=desc&offset=0"`... however, https://quakemap.api.ushahidi.io/api/v3/posts?orderby=created&order=desc&offset=0 is a completely different result (seems to be everything).

**Where was the bug observed**

In Quakemap: 
https://quakemap.api.ushahidi.io/api/v3/posts?created_after_by_id=537&has_location=all&order=desc&order_unlocked_on_top=true&orderby=created&source%5B%5D=sms&source%5B%5D=twitter&source%5B%5D=web&source%5B%5D=email&status%5B%5D=draft

**To Reproduce**
1. Go to 'https://quakemap.api.ushahidi.io/api/v3/posts?created_after_by_id=537&has_location=all&order=desc&order_unlocked_on_top=true&orderby=created&source%5B%5D=sms&source%5B%5D=twitter&source%5B%5D=web&source%5B%5D=email&status%5B%5D=draft' (no need to login, click or scroll).
2. Observe `"count":0` right at the beginning.
3. Copy the URL from the `curr` field; in my case `https://quakemap.api.ushahidi.io/api/v3/posts?orderby=created&order=desc&offset=0` and open it in a new browser tab. Notice that all the slashes `/` are escaped by `\` which needs to be removed. _This might be yet another bug as escaping slashes is clearly not necessary in JSON._
4. Observe `"count":534 (or something different if data was added or removed in the meantime, but most likely not 0 as before).

**Expected behavior**

Requesting the URL from `curr` should return exactly the same results in the same order as the current result. The query URL might be syntactically changed, e.g. query parameters which have the default value removed, parameters reordered, etc. -- but the response should be the same.

Analogue for `prev` and `next`: Expect to just increment or decrement the `offset` by `limit`; otherwise **keep filtering**. The offset modification seems to work fine, seen here: https://quakemap.api.ushahidi.io/api/v3/posts?limit=10&offset=20&has_location=all&order=desc&order_unlocked_on_top=true&orderby=created&source%5B%5D=sms&source%5B%5D=twitter&source%5B%5D=web&source%5B%5D=email

Notice `offset=20`; while prev has offset=10 and next has offset=30. 👍 

**Is there a workaround? What is it.**

Completely ignore the curr, next, and prev fields and build the queries manually (or by URL template). In this case, the fields might as well be removed completely.

**URL / Environment where this happened**
https://quakemap.api.ushahidi.io/api/v3/posts?created_after_by_id=537&has_location=all&order=desc&order_unlocked_on_top=true&orderby=created&source%5B%5D=sms&source%5B%5D=twitter&source%5B%5D=web&source%5B%5D=email&status%5B%5D=draft

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**
nope, just platform api

**Desktop Hardware Details (please complete the following information):**
 - OS: Any
 - Browser: Any browser, also wget, curl, ...
 - Version: any

**Smartphone Hardware Details (please complete the following information):**
not relevant

**Additional context**

While most likely out of scope here, the [json:api specification](https://jsonapi.org/) has a field `links` which contains `self` (which corresponds to `curr` here), also `next` and `prev` (same here),  and additionally `first` and `last` (not available here). Even when not following json:api here, it might serve as an inspiration.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-107

**Comment by AngadSethi** [comment]
@rowasc Please review the pull request whenever you get a chance. Thanks!
