### ISSUE TITLE
Upload file size configuration possibility 

### ISSUE THREAD

**Issue by lupa18** [ushahidi/platform#3988]
**Which user group(s) are the primary audience for this feature/enhancement.**
self hosted

**Is your feature request related to a problem? Please describe.**
When I try to upload a file, Ushahidi says max upload size is 1MB. But I checked /etc/php/7.2/cli/php.ini and upload_max_filesize = 2M
Then, I created a phpinfo.php file and ran php phpinfo.php and that 2M value is correct. 
I also checked and modified config/media.php file but nothing.

**Describe the solution you'd like**
Is there any possible to fix this problem or add the ability to configure it in the admin section?

**Describe alternatives you've considered**
Noting right now

**Additional context**
I installed Ushahidi using docker.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-104

**Comment by ptandler** [comment]
Good idea to pass this value from the backend.
I'm not sure if there might be the need for someone to configure a different image upload size compared to what is possible in the php config, for some reason, e.g. to save space.

**Comment by ptandler** [comment]
Related to #3781

**Comment by ptandler** [comment]
Currently, the max upload filesize is hard coded in the frontend in `legacy/app/common/directives/file-upload.directive.js`:

```js
                function validateFile(container) {
                    if ($scope.validation === 'image') {
                        var mimeReg = /[\/.](gif|jpg|jpeg|png)$/i;
                        var mimeCheck = mimeReg.test(container.type);
                        var sizeCheck = container.size < 1048576;
                        return mimeCheck && sizeCheck;
                    }
                    return true;
                }
```

The first step would be to make the configurable on the client side, until the backend provides this configuration.

In the ideal world an admin should be able to configure the max upload file size in the backend UI and the value there is checked to be not larger than `upload_max_filesize` configured in php. (That could be step 3)
