### ISSUE TITLE
Field on Survey not visible to end users when filling the survey.

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#3989]
**Describe the bug**
A deployment has a number of surveys in it. The surveys have a common field used as a consent field. This field is not visible to the end user when filling in the survey.

**Where was the bug observed**
 https://raicescampesinas.ushahidi.io/views/map 
Surveys Educacion and Conflicto in the above deployment.

**To Reproduce**
1. Navigate to the first survey.
2. Note that this survey has a first field that is radio buttons.
3. Navigate into either survey Education or Conflicto.
4. Note that these two surveys have the first field with radio buttons missing.

- These fields are visible when the survey is opened in edit mode. 

**Expected behavior**
All fields present on the survey should be available to the end user.

**Is there a workaround? What is it.**
None.

**URL / Environment where this happened**
- Prod

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS Version 10.15.5
 - Browser: Chrome 
 - Version: Version 83.0.4103.97 (Official Build) (64-bit)

Link to where issue is first reported.
https://app.intercom.com/a/apps/hl5rfiga/inbox/inbox/conversation/27260198806

Aha! Link: https://ushahiditeam.aha.io/features/PROD-103

**Comment by Angamanga** [comment]
@Obadha2 @CeciliaHinga For this one, I don't see the options for the fields the affected surveys when looking at the response from the backend. Can we ask the user to double-check that the options are actually there in the survey-configuration?
