### ISSUE TITLE
Translations - Category name does not translate to match Survey language selected.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3995]
**Describe the bug**
When another language is selected to view a survey in, the Category name does not change to match the selected language. The category name stays in the default language set even when translations are available for the selected language.

**Where was the bug observed**
https://test-deployment.steve-buscemi.ush.zone/posts/create/50

**To Reproduce** 
1. Go to a survey that has a category field in filling/response mode.
2. Ensure the category name has translations available.
3. Select another language that's available for the survey.
4. Note that while other options and field change to match selected language, the Category name stays as the default option.

**Expected behavior**
When you change language to a different one selected for a survey, where available, all fields should change to match the selected language.

**Is there a workaround? What is it.**
None

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS
 - Browser: Chome
 - Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by rowasc** [comment]
Ok I think this one should be fixed now. LMK

**Comment by Obadha2** [comment]
Fixed, verified. 👍
