### ISSUE TITLE
Categories - Category created from fill-in survey page feature is weird.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3997]
**Describe the bug**
As an admin you can create a category from the fill-in survey page. This feature is unnecessary in this page because of two factors:
- after creating a category on this page, you have to go to edit-survey mode to add a category to the survey. This makes the option to add a category from the fill-in survey page redundant.
- after successful creation, user is not notified. On trying to re-create the category, an sql error notifies the user that category already exists.

**Is your feature request related to a problem? Please describe.**
- This feature is a bit confusing in this particular location, and it can be better placed elsewhere.

**Describe the solution you'd like**
- Remove the option to create a category from the fill-in survey page. This feature is better placed in the Category page, or edit survey mode.

**Screenshots**
<img width="1325" alt="Screenshot 2020-07-02 at 11 26 01 AM" src="https://user-images.githubusercontent.com/38259840/86335176-d4b40b80-bc56-11ea-9ce8-6a68fbd678c9.png">
- Error message notifying user category exists already

Aha! Link: https://ushahiditeam.aha.io/features/PROD-47

**Comment by rowasc** [comment]
Yea. I tend to agree that this feature here is extremely confusing. It's way out of the context of what the user is actually doing. I wonder how we came to adding it tho. @aoduor this is a request for historical data or info of some kind if you have it. Do you have any insights on why this feature was ever needed (the "Add category while creating a post" thing)  ?

**Comment by rowasc** [comment]
@CeciliaHinga @Nthiga pinging you too in case you have OPINIONS or DATA or FACTS :D

**Comment by rowasc** [comment]
I just removed it (discussed in the last community call ) ./  LMK what you think . 
cc @Angamanga
