### ISSUE TITLE
Author user related columns missing from CSV export

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3998]
**Describe the bug**
When exporting deployments posts, the resulting CSV doesn't contain all the information about the author of the post.

**Where was the bug observed**
Any current deployment

**To Reproduce**
1. Ensure you've got Web / Mobile app posts in the deployment, reported by registered users.
2. Produce CSV export
3. The posts authors names and / or emails are missing.

**Expected behavior**
The CSV should contain any/some/all of these:

* authors names 
* authors email
* authors role (?)

**Is there a workaround? What is it.**
n/a

**Screenshots**
n/a

**URL / Environment where this happened**
n/a

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**
n/a

**Desktop Hardware Details (please complete the following information):**
 n/a

**Smartphone Hardware Details (please complete the following information):**
n/a

**Additional context**
To clarify, the CSV *does* contain Contact and Contact ID columns, but those are only relevant for posts received via a SMS, email or twitter datasource. This issue is referring to posts created by submission from the Web, Mobile App or some other party via the REST API.

It looks like this could be solved by adding the relevant fields here: https://github.com/ushahidi/platform/blob/develop/src/App/Repository/Form/AttributeRepository.php#L296

Aha! Link: https://ushahiditeam.aha.io/features/PROD-98

**Comment by rowasc** [comment]
ah. User ID and Email should be sufficient, but role may actually be useful to determine issues so I think we could add it. 
The main reason for user_id here is that it may help identify info if someone changes their email, I think?

**Comment by CeciliaHinga** [comment]
Related issue https://github.com/ushahidi/platform/issues/4152
