### ISSUE TITLE
A blank date and time field type on a survey form

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#3999]
**Which user group(s) are the primary audience for this feature/enhancement.**
Include deployment names if possible

Ushahidi.io users

**Is your feature request related to a problem? Please describe.**

A required date/time field type on a survey automatically displays the date and time in real time, instead of it being blank on the survey form that is to be submitted. If the users do not change the date from the one displayed to the required one based on the project, the post is still submitted since the field is not blank and the data collected becomes irrelevant.

**Describe the solution you'd like**

When one creates a required date/time field type, the expected outcome should be a blank field where one can manually add date/time, this way the user will be prompted to set a date before submission if they fail to do so.

**Additional context**
This is what we currently have
<img width="278" alt="Create_Post_-_test254" src="https://user-images.githubusercontent.com/20906968/87025641-57067780-c1e3-11ea-8b81-0d726dd04a4f.png">
This is the suggestion
<img width="278" alt="Create_Post_-_test254" src="https://user-images.githubusercontent.com/20906968/87025983-c41a0d00-c1e3-11ea-8e70-bebe747f4774.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-97

**Comment by bimbolabuari** [comment]
@Angamanga @rowasc, Please I would love to contribute to this issue!

**Comment by Angamanga** [comment]
Closing in favour of https://github.com/ushahidi/platform/issues/3961
