### ISSUE TITLE
Type and status color/icon differentiation

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#400]
The part for type and status on posts, should have colour codes to show different types of post e.g. red for warning; icons or coloured text can be used
￼

**Comment by jshorland** [comment]
needs to go into broader issue for categories

**Comment by rjmackay** [comment]
what? "The part for type and status on posts" <- screenshot? what are we talking about here?
Categories have customised icons / color already so this sounds like something that already exists.
