### ISSUE TITLE
Surveys - Response to a survey can be submitted with required fields not filled.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4000]
**Describe the bug**
A response to a survey can be successfully saved even when there are required fields that have not been filled. Only Title and Description fields when not filled stop the successful saving of the response. This should happen for every required field, not only Title and Description fields.

**Where was the bug observed**
Steve-buscemi - https://test-deployment.steve-buscemi.ush.zone/views/map

**To Reproduce**
1. Go to a survey that has required fields.
2. Without filling in Title and/or Description fields, try saving the response.
3. Note that the attempt won't be successful and user is notified to fill in all required fields.
4. Fill in Title and Description fields, but leave out additional required fields.
5. Note that the response is saved successfully even with the required fields not having been filled.

**Expected behavior**
Where there are required fields in a survey, they should all be filled to complete a response that can then be submitted/saved.

**Is there a workaround? What is it.**
None.

**URL / Environment where this happened**
https://test-deployment.steve-buscemi.ush.zone/views/map

**Desktop Hardware Details (please complete the following information):**
- OS: iOS
- Browser: Chome
- Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by rowasc** [comment]
This one should be OK now :) and I think #4001 should be solved together with this one if I got it rightin testing

**Comment by Obadha2** [comment]
QA'd, passes. 👍
