### ISSUE TITLE
Image URL for CSV export is not full path

### ISSUE THREAD

**Issue by adisadit** [ushahidi/platform#4002]
**Describe the bug**
I'm trying to export the Ushahidi data in here: https://handwashing-station.ushahidi.io/ as a CSV. One of the questions require the user to upload a photo.

During my export, the photo location URL didn't appear correctly, which I'm not able to display it in QGIS for example.

I believe some of the fix already done last month as I noticed in here: https://github.com/ushahidi/platform/pull/3985

But, I think the bug still appears in our deployment.

**Where was the bug observed**
https://handwashing-station.ushahidi.io/ 

**To Reproduce**
1. Go to 'https://handwashing-station.ushahidi.io/ '
2. Log in as 'Admin' 
3. Click on 'Export and tag data'
4. Scroll down to 'Export selected field'
5. See error

**Expected behavior**
When the user exports the data, they get the full URL of photo location

**Is there a workaround? What is it.**
My workaround is by view the photo manually to see where is the full url that image located. For example in here:
![image](https://user-images.githubusercontent.com/2520159/87393779-dd9ec880-c5d8-11ea-976f-7cfc9c38caee.png)

After I get the URL, I open the CSV file and concatenate the URL with the current image location:
![image](https://user-images.githubusercontent.com/2520159/87394048-5c940100-c5d9-11ea-9f67-ab8322ef48fa.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/2520159/87394060-61f14b80-c5d9-11ea-8280-7802e91406e7.png)

**URL / Environment where this happened**
[e.g http://qa.ushahidi.io/post/create]

**Desktop Hardware Details (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [78.02]

**Smartphone Hardware Details (please complete the following information):**

**Additional context**

Aha! Link: https://ushahiditeam.aha.io/features/PROD-96

**Comment by tuxpiper** [comment]
Same as #3481 .

This has been fixed in a recent release.
