### ISSUE TITLE
When a field validation fails, display a hint to explain how to fill it in

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#4016]
- Show the user that there was a problem.
- Explain how to fill in the field correctly.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-8

**Comment by jay1310** [comment]
Hello, I just want a clarification for the issue.
Is it for login form only whose link is provided?

**Comment by Obadha2** [comment]
Suggested improvements to messages shown for various fields that are provided invalid values:
 - Decimal field:
    - Actual Error Message: The number must be a number.
    - Suggested Error Message: Provided value is not a valid decimal number.
 - Integer Field: 
    - Actual Error Message: The number must be an integer.
    - Suggested Error Message: Provided value is not a valid integer.
 - Date Field:
    - Actual Error Message: The date is not a valid date.
    - Suggested Error Message: Provided value is is not a valid date.
 - Select Field
    - Actual Error Message: The selected select is invalid.
    - Suggested Error Message: The selected option is invalid.
 - Checkbox Field
    - Actual Error Message: The selected checkboxes.0 is invalid.
    - Suggested Error Message: The selected options are invalid.

**Comment by tuxpiper** [comment]
@Obadha2 this is ready for checking again
