### ISSUE TITLE
Create release build

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#4019]
[https://www.notion.so/ushahidiorg/Release-bundle-platform-release-32cd3fffcdd441ad8e4a90a1a4a033b5](https://www.notion.so/ushahidiorg/Release-bundle-platform-release-32cd3fffcdd441ad8e4a90a1a4a033b5)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-33

**Comment by tuxpiper** [comment]
Done as noted here: https://github.com/ushahidi/platform-release/releases/tag/v4.6.0
