### ISSUE TITLE
Missing save and configuring buttons on the saved search feature

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4024]
**Describe the bug**
When you sort and filter and try to save the search, you cannot save the saved search because there are a bunch of configuring and save button missing

**Where was the bug observed**
ushahidi.io 

**To Reproduce**
1. Log in to your ushahidi.io account
2. Click on sort and filter on map or data view
3. Filter your data accordingly
4. Click on save search
5. No way to save it after naming and giving it a description

**Expected behavior**
After creating a saved search you should be able to configure and save it.

**Is there a workaround? What is it.**
No

**Screenshots**
What we have.
<img width="484" alt="Posts_-_test254" src="https://user-images.githubusercontent.com/20906968/88073121-81124f00-cb7e-11ea-892e-07c4069d4da1.png">
What we should have
<img width="304" alt="7_1_Saved_Searches_-_Ushahidi_Platform_User_Manual" src="https://user-images.githubusercontent.com/20906968/88073171-912a2e80-cb7e-11ea-9eda-24f7b685d8dd.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-39

**Comment by Obadha2** [comment]
Saved searches not deletable. Can only be modified. They live forever. @Angamanga @rowasc

**Comment by rowasc** [comment]
@Obadha2 is this a pre-existing issue? Does it happen in production too? Please specify.

**Comment by Obadha2** [comment]
@rowasc since the issue of not being able to save a search exists on prod, can't really say if this is happening on production because I have to save first which currently can't happen on prod. My above observation is in steve-buscemi. 
A saved search can only be modified but there's no option for deleting it.

**Comment by Angamanga** [comment]
@Obadha2 @rowasc I think this is a design-flaw. You can delete a saved search if you click the "..." in the mode-context bar here: https://annatest1000.ushahidi.io/savedsearches/4/map but not in the saved search-edit modal :/.

**Comment by Obadha2** [comment]
Aha okay 
I'll check that out.

Talking of design flaws @Angamanga, clicking on `Cancel` and `Save and Close` buttons on search-edit modal dismisses the modal and the filters drop-down. I assume it should dismiss just the modal but take you back to Sort&Filters options?

**Comment by Angamanga** [comment]
@Obadha2 True, I think that can be included in new issues I will create for the search and filter-improvements (discussed here: https://github.com/ushahidi/platform/issues/3946#issuecomment-667918979)

**Comment by Angamanga** [comment]
Waiting for release
