### ISSUE TITLE
Not sending email

### ISSUE THREAD

**Issue by lupa18** [ushahidi/platform#4025]
**Describe the bug**
Platform is not sending emails

**Where was the bug observed**
https://elavizor.tedic.org

**To Reproduce**
1. Go to "Log in" -> "Forgot your password?"
2. Put your previously created account's email
3. Click on "Reset my password"
4. Nothing happens

**Expected behavior**
A reset email should arrive. 

**Is there a workaround? What is it.**
Not sure. 

**URL / Environment where this happened**
https://elavizor.tedic.org

**Desktop Hardware Details (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 78*

**Additional context**

I configured smtp email with its credentials (tested twice and correct) using env variables with Docker. I checked them inside container and are right.  

The, I reviewed server logs and even setting 'debug mode' to true, the only log I got is: 
```
"POST /api/v3/passwordreset HTTP/1.1" 500 221 "https://elavizor.tedic.org/views/map" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"
```

I also reviewed other issues in this repo (open and closed) and can't find a solution. 

I would appreciate any help !
thanks in advance!

Aha! Link: https://ushahiditeam.aha.io/features/PROD-40

**Comment by rowasc** [comment]
hey @lupa18 do you have any logs from storage/logs/lumen.log ? Those may shed some light into what's going on, if you haven't checked those specific ones yet

**Comment by lupa18** [comment]
Hello @rowasc ! thanks for your help ! 
It gives this error:

```
lumen.ERROR: Swift_TransportException: Connection could not be established with host smtp.mayfirst.org :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname in /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:269
```
Complete log [here](https://bin.disroot.org/?5e3cf321783ad1ef#6FTuLeBKWHoAweawqTK2gWKjRa8XBgf2X7MrB8HJNcgG). 

thanks again!

**Comment by lupa18** [comment]
Hey @rowasc ! I thanks to your advice I could found my configuration error. Was a parameter error when setting email details. 

Now, email came in English. Do you know how can I fix it to come in Spanish?

**Comment by rowasc** [comment]
Ah, good to hear. Do you mean the forgot password email came in english? I just checked resources/views/emails/forgot-password.php and it seems we're missing translations for them :/ would definitely appreciate a PR if that's something you're interesting in helping out with.

**Comment by lupa18** [comment]
thanks!
