### ISSUE TITLE
Search broken on Ushahidi.io

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#4027]
**Describe the bug** When I try to use the search function on [https://groundswell.ushahidi.io](https://groundswell.ushahidi.io), a couple of things happen 1. I can't tell if the _apply_ button works or not. At first glance, it looks inactive, but when I hover over it, it looks grey, with a random _cancel_ icon on my cursor. See screenshots below.

A: [https://user-images.githubusercontent.com/721918/88531773-0cbb2e00-d00c-11ea-81d4-55b1afd18cdc.png](https://user-images.githubusercontent.com/721918/88531773-0cbb2e00-d00c-11ea-81d4-55b1afd18cdc.png) B: [https://user-images.githubusercontent.com/721918/88531799-1775c300-d00c-11ea-832d-188d63d173df.png](https://user-images.githubusercontent.com/721918/88531799-1775c300-d00c-11ea-832d-188d63d173df.png)

1. I can search once with it running "successfully". I typed "London" on the search bar, and it seems to automatically start searching and returns some values, but the only reason I know this is because, when I look at the menu bar, I see number of posts changed from it's original value, and the map tries to zoom in. HOWEVER, the long search bar is still open. Also, important to note that at this point, I haven't tried to press "Apply".
2. Once I hit Apply, and I try to put in any new search terms, it just doesn't work anymore. The system is non responsive to my actions.

**Where was the bug observed** [https://groundswell.ushahidi.io/views/map](https://groundswell.ushahidi.io/views/map)

**To Reproduce** Steps to reproduce the behaviour: 1. Go to [https://groundswell.ushahidi.io](https://groundswell.ushahidi.io) 2. You don't have to be logged in 3. Click on "Search" 4. Try and search by term or location 5. Hit Apply

**Expected behavior** I expect 1. That as soon as I hit apply, I get an indication of successful search 2. That the apply button works

**Is there a workaround? What is it.** On further investigation, it seems search happens WITHOUT hitting "Apply", which is not intuitive to me as a user. Might be worth getting rid of that button altogether

**Screenshots** Added them above <3.

**URL / Environment where this happened** Production. Live

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**

**Desktop Hardware Details (please complete the following information):** - OS: MacOS - Browser: Chrome - Version: Version 84.0.4147.89

**Additional context** There's a bunch of UX issues as well. 1. Our groundswell users are confused about whether the search bar is for. They've typically been using it to search location, yet it returns values of text in the description rather than post location. It's not intuitive. 2. The search bar occupies the WHOLE page. Obscures search results. And it gets longer as the user adds more things like categories, etc.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-42

**Comment by aoduor** [comment]
@CeciliaHinga have you also received bug reports on the same from other users?

**Comment by Angamanga** [comment]
Issues related to fix above ux-issues:
https://github.com/ushahidi/platform/issues/4050
https://github.com/ushahidi/platform/issues/4051
https://github.com/ushahidi/platform/issues/4052

**Comment by tuxpiper** [comment]
@aoduor  we will tentatively close this one with the next release along with the other related issues @Angamanga mentioned.

There are some really not very specific bits in the additional context, I hope we will not miss anything important there.
