### ISSUE TITLE
Embeds from platform not responsive

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#4030]
**Describe the bug**
We've built platform to be responsive on all devices. In cases where someone embeds their deployment on an external website, it would seem that the embed doesn't adjust to size of the device. 

**Where was the bug observed**
https://groundswell.ushahidi.io
https://groundswellproject.net/peace-associates

**Expected behavior**
I'd expect the behaviour to be similar to how the main deployment is.

**Comment by tuxpiper** [comment]
I think I recall this was solved by indicating that in order for the embeds to be response, the iframe needs to be created with non-fix dimensions.

Tentatively closing .
