### ISSUE TITLE
Fix filter dropdown behaviour

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4031]
When I click outside of the filter-dropdown, and new filters has been selected but without clicking on apply, the dropdown closes without applying the filters, but in the filter-dropdown and in the filter counter, the filters looks like they are being applied. Improvement needs to be figured out. Some ideas as discussed in https://github.com/ushahidi/platform/issues/3946:

- Make some visual change that hint, like "you have not applied this filters" when you close the dropdown. 
- A small "Do you want to apply the new filters" pop-up that shows up when someone closes the filter screen without applying them (like closing the edit-mode without saving) 
- Another alternative would be to "hint" that filters aren't applying in a less forceful way than a popup, maybe in the bar itself. 
- Update the counter on apply. I think that provides better feedback that the filters are not really active until you apply them actually.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-54

**Comment by CeciliaHinga** [comment]
I would go with the 3rd alternative, hint that filters are not applied on the bar themselves, this way they would know which actual filters they chose when they began the whole process. If they would like to change those before application, then they will know which exact filters to change.
