### ISSUE TITLE
Wrong Date and Time displayed once a post has been submitted

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4036]
**Describe the bug**
When one enters a certain date and time on the date and time field type, it changes once the postcard has been submitted and you get a different date and time from the one you entered. While testing this, I have had different results.

**Results**
- I enter the date and time on my postcard, once the response has been submitted the date is reverted back to the day before and the time is 3hrs behind.
- When i do it again with a different date and submit it, i get the correct date but wrong time(3hrs behind)
- When i edit the second result (point 2 above☝️) , the date changes to the day before and you get the wrong time. 
- When i edit again for the second time, i get the right date and wrong time.

The only thing i am 100% sure about is, the time is reverted back 3 hrs all the time. That is consistent

**Where was the bug observed**
Production, ushahidi.io

**To Reproduce**
1. Click on the + icon to submit a response to a survey that contains date and time as a field response.
2. Enter the date and time
3. Click on submit
5. To edit, click the edit button or the three dotted icon on a postcard and change the date and time.
6. Click save
7. See error

**Expected behavior**
The date and time displayed should be the one entered by a user upon submission with information about the timezone.

**Reason of this bug**
The times are in fact saved in UTC but does not include timezone and are displayed in UTC without the timezone-information.

**Is there a workaround? What is it.**
No

**Screenshots**
Date and time entered
<img width="184" alt="Create_Post_-_test254" src="https://user-images.githubusercontent.com/20906968/90005630-27460600-dca0-11ea-9944-31a4fc54a52a.png">
Date and time displayed
<img width="213" alt="test_-_test254" src="https://user-images.githubusercontent.com/20906968/90005661-3462f500-dca0-11ea-9e97-b4d49eea8b5a.png">

**Desktop Hardware Details (please complete the following information):**
 - OS: [iOS]
 - Browser [Brave]
 - Version [1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)]

Aha! Link: https://ushahiditeam.aha.io/features/PROD-60

**Comment by Angamanga** [comment]
Closing in favour of https://github.com/ushahidi/platform/issues/4162
