### ISSUE TITLE
Private data visible without logging in

### ISSUE THREAD

**Issue by dexwakhu** [ushahidi/platform#404]
If you click on any of the links: All posts, Published posts, Unstructured posts etc some data is displayed for a second before you are redirected to the log in page.

**Comment by rjmackay** [comment]
Is there any actual content? or does it just render an empty list/map/whatever before redirecting?
The API won't return anything without auth.. so its highly unlikely to be actually leaking private info

**Comment by rjmackay** [comment]
https://s3.amazonaws.com/uploads.hipchat.com/95412/718736/JT316jHWssARoDO/VID_20150820_095157.mp4

**Comment by rjmackay** [comment]
Possibly related to #747

**Comment by jshorland** [comment]
Need to retest. Assigning to myself.

**Comment by jshorland** [comment]
I don't see this happening anymore. Closing.
