### ISSUE TITLE
Remove default value for fields that doesn't use it

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4044]
**Describe the bug**
There is an input field for default-values for all field-types but not all fields can use a default value. This is confusing to the users and causes bugs. 
TODO:
- Check which fields that use the default values
- Remove the possibility to set default value for the fields that don't

Aha! Link: https://ushahiditeam.aha.io/features/PROD-68

**Comment by TunrayoIlawole** [comment]
Hi @Angamanga Can i work on this?

**Comment by Ifycode** [comment]
Hi @Angamanga I want to try work on this if i'm assigned.

**Comment by Ifycode** [comment]
Hi @Angamanga I'm not able to access the aha link to check out this issue https://ushahiditeam.aha.io/features/PROD-68. Can I help with how to access it?

**Comment by Ifycode** [comment]
And then can i also be assigned?

**Comment by hyounes4560** [comment]
@Angamanga Can you assign me this task? Thanks

**Comment by rowasc** [comment]
@lfycode Please go ahead. I'm assigning it to you (first-come first serve :) ) . Ignore the Aha links, it's an internal thing, sorry

**Comment by Ifycode** [comment]
Ok. Thanks. Please @rowasc @Angamanga by default value, you mean placeholder and value attributes on input fields right?

**Comment by hyounes4560** [comment]
@rowasc I apologize but @Ifycode is already working on another task! Is it okay that I can help her in this at least??? Thanks @Angamanga

**Comment by Ifycode** [comment]
> Ok. Thanks. Please @rowasc @Angamanga by default value, you mean placeholder and value attributes on input fields?
> Or do you mean the type attribute with value number, text etc?

@rowasc @Angamanga I found this short article that I think clarifies this for me https://html.com/attributes/input-value/

**Comment by Angamanga** [comment]
@Ifycode The default values are values you can add yourself when setting up the survey, if you go to Settings->surveys->create a new survey and add a "Field". In the box that appears, some of the field-types have "Default values". 

<img width="498" alt="Screenshot 2020-10-14 at 10 10 54" src="https://user-images.githubusercontent.com/8624777/95961639-97d6e380-0e05-11eb-9799-9e3ef109317c.png">

The value added there is added to the post if no other value is entered to that field by the user. However, the default value is not used by all field-types, even though this box is visible when adding the field. If you test to add default value to the different field-types and then save the post, you will see which fields that are not using the default values. For these field-types, the default-value input box should be hidden.

I hope this makes sense and helps you on the way.

@hyounes4560 Have you found another issue? If not, I will be adding more today!

**Comment by Ifycode** [comment]
OK. Thanks. Will go through and update you soon @Angamanga

**Comment by Ifycode** [comment]
Hi @Angamanga @rowasc I'm back again. Here are my obesrvations about this tasks:

**Observations:**
Fields that have the default value input found in settings > surveys > create a new survey > add field grouped below with observations stated.

**Default values that show on created post:**
- Short Text
- Long Text
- Select
- Radio Buttons
- Check Boxes
- Mark Down

**Default values that **only** work when the right values are entered (Ask mentors before removing):**
- Number (decimal) e.g. 1
- Number (Integer) e.g 1
- Date e.g 16 October, 2020
- Date & Time e.g 16 October, 2020 7:14 pm
- Embed video e.g https://www.youtube.com/watch?v=vpQDkEgO-kA

Haven't been able to assess this yet (Ask mentors):
- Related post

**Default values that don't work at all in post created:**
- Location

**Comment by Ifycode** [comment]
> Haven't been able to assess this yet (Ask mentors):
> 
> * Related post
> 

I haven't been able to test for related posts because it rejects what ever I type in both when using default value and when not using default value. I typed in text and even number, it keeps giving me errors.

![related-post](https://user-images.githubusercontent.com/45185388/96297705-22564900-0fa6-11eb-8c89-852ab33e5419.PNG)

I don't understand what it means by "valid post id". Can I get a sample post id or what exactly is it asking for?

**Comment by Ifycode** [comment]
> **Default values that **only** work when the right values are entered (Ask mentors before removing):**
> 
> * Number (decimal) e.g. 1
> * Number (Integer) e.g 1
> * Date e.g 16 October, 2020 (or 2020-10-16)
> * Date & Time e.g 16 October, 2020 7:14 pm (or 2020-10-16 7:14 pm)
> * Embed video e.g https://www.youtube.com/watch?v=vpQDkEgO-kA

About these ones, I have 2 suggestions:
- Removal
- Add a placeholder showing the right type of values for the user as listed above and use form validation to prevent user from continuing if right type of values are not entered.

**Question 2:**

Which of the above do you suggest or advice?

**Comment by Ifycode** [comment]
I have made a pull request that removes default value for location, since that's the only one i'm sure of. Want to be sure about the other ones I just talked about. Please help with answers to questions 1 & 2 above as it would help clarify what to do with them.  @Angamanga @rowasc

**Comment by Ifycode** [comment]
> I have made a pull request that removes default value for location, since that's the only one i'm sure of. Want to be sure about the other ones I just talked about. Please help with answers to **questions 1 & 2** above as it would help clarify what to do with them @Angamanga @rowasc

Hi @Angamanga @rowasc I'm still on the related post issue and Question 1 & 2

**Comment by rowasc** [comment]
Question 1 - related post -  should not allow a default value. In terms of using it when sending a post, you should search for the title of post that's related through the related post survey (ie Form A has a related post field called "B".  Field B allows relations with Form C, D. You should be able to find posts by title that are in Form C and D, and hit enter to search)
 Question 2: add a placeholder and label as you suggest, and input validation.

**Comment by Ifycode** [comment]
Ok @rowasc i'll do as you have suggested and send the PR.

**Comment by rowasc** [comment]
Awesome thanks!

**Comment by Ifycode** [comment]
@Angamanga am I permitted to take on this issue again? If so, I would love to attempt it again, starting afresh this time.

**Comment by Angamanga** [comment]
@Ifycode Hm, could you send a screenshot? Where did you test? When I test in production it seems to work still:
<img width="631" alt="Screenshot 2021-04-19 at 09 18 57" src="https://user-images.githubusercontent.com/8624777/115196503-47ac4700-a0f0-11eb-90da-bcc70559539a.png">

**Comment by Ifycode** [comment]
Ok @Angamanga. I'm testing it in the develop branch. Yes the title & description works (I forgot to check these earlier - sorry about this). But others like short test, long test, location, etc., these don't work. Using short text and long text as example in the screenshot. I gave short text and long text default values of "default short text" and "default long text" respectively, but the default values never get displayed:

![u-1](https://user-images.githubusercontent.com/45185388/115321605-a85b7400-a130-11eb-8d40-a456aa6c0c65.PNG)
![u-2](https://user-images.githubusercontent.com/45185388/115321622-ab566480-a130-11eb-9935-2c0f2b9b52ec.PNG)
![u-3](https://user-images.githubusercontent.com/45185388/115321625-adb8be80-a130-11eb-8896-cbeb0678309c.PNG)

I'm looking at it based on how I was asked to fix it earlier in this issue's comment thread and the conclusion which I documented [here in the last PR submitted for it](https://github.com/ushahidi/platform-client/pull/1600#issue-509489351) - where: 
* Those which show on post creation were left untouched 
* Placeholder and form validation were to be added for those whose default values that only work well when the right values are entered .
* Those with default values that don't work or show up at all in post created were to be removed.

This is what I was trying to say earlier. Now, other default values (except title & description) don't show up in the post, which wasn't the case before... So does this mean default value for all these ones that don't show up in post should now be removed totally?

**Comment by Ifycode** [comment]
I made a mistake @Angamanga, sorry about this. I'm testing all over again and this time properly, I'll soon add a comment here once I'm done.

**Comment by Angamanga** [comment]
@Ifycode Hm, interesting. I think this is a regression due to the new changes to the structure. Could you add your findings as a new issue?

**Comment by Ifycode** [comment]
Alright @Angamanga. Adding it as a new issue then.

**Comment by Angamanga** [comment]
@Ifycode Thank you! Do you want to continue working on this issue?

**Comment by Ifycode** [comment]
Yes @Angamanga I would love to attempt it again, starting afresh this time with a new PR.

**Comment by Angamanga** [comment]
@Ifycode Thank you!

**Comment by Ifycode** [comment]
Ok, thank you. Will start work on it then.
