### ISSUE TITLE
Display survey in the user-selected language

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#4045]
- If the survey is available in multiple languages, let the user decide which one they wish to use before responding to it.
- If the survey is available in just one language, display it.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-3

**Comment by rowasc** [comment]
This could be selected throughn the URL and sent by the trigger @Angamanga to check in with Antony about this?

**Comment by tuxpiper** [comment]
@Angamanga  was this for the https://github.com/ushahidi/platform-brck-survey repo?

If so, can we close it?
