### ISSUE TITLE
Sort&Filter works intermittently - clearing cache and hard reload needed after every search.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4049]
**Describe the bug**
First time logging in and attempting the Sort&Filter feature, it'll work. A second time will work, too. After that, the Sort&Filter feature won't work, user has to clear cache and hard reload for the feature to work.

**Where was the bug observed**
Happens in both test environment and production.

**To Reproduce**
1. Go to a deployment that has data.
2. Navigate to data view.
3. Note the number/order of posts.
4. Click on Sort&Filter to reveal filtering options.
5. Make selections to filter the data.
6. Click Apply and note selected options taking effect.
7. Click on Sort&Filter to reveal filtering options again.
8. Click Restore Defaults to dismiss and filtering options applied.
9. Note all data is now presented.
10. Click on Sort&Filter to reveal filtering options again.
11. Make selections to Filter through data.
12. Click Apply and note that this time, filtering does not happen.
13. At this point user has to clear cache and hard reload the page for Filtering to work.

**Expected behavior**
Sort&Filter should work at all times.

**Is there a workaround? What is it.**
Clearing cache and hard reloading the page gets filtering working again.

**URL / Environment where this happened**
This is happening in both prod and test environments.
https://test-deployment.steve-buscemi.ush.zone/views/data
https://isooko.ushahidi.io/views/data

**Desktop Hardware Details (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Browser: Chrome
 - Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by Angamanga** [comment]
Closing since related to reverted changes.
