### ISSUE TITLE
Header copy needs to link to the homepage

### ISSUE THREAD

**Issue by ehersman** [ushahidi/platform#405]
When on a subpage for a v3 site, the name of the deployment in the header should be clickable and take you back to the home page.  I shouldn't just have to click on the "home" link. 

![screen shot 2015-08-19 at 7 44 52 pm](https://cloud.githubusercontent.com/assets/83717/9362712/d23aaee4-46aa-11e5-9692-84fd431847f7.png)

**Comment by rjmackay** [comment]
Needs styling work first.
@middle8media or @sophshep could we have the Deployment name <h1> styled to override the default link styles? Right now if I wrap it with an <a> it turns blue.

**Comment by sophshep** [comment]
Just pushed a fix so that the style stays the same when the `<h1>` is wrapped in an `<a>`
