### ISSUE TITLE
vagrant provision fails due to puppet options

### ISSUE THREAD

**Issue by rasmi** [ushahidi/platform#406]
Following the vagrant guide [here](https://wiki.ushahidi.com/display/WIKI/Installing+Ushahidi+3.x#InstallingUshahidi3.x-UsingtheVagrantvirtualmachine), `vagrant provision` fails. This happens due to the `--templatedir` and `--manifestdir` options, which are deprecated in recent versions of puppet (>=3.6?). Any ideas on a fix?

**Comment by haisum** [comment]
I am facing same issue. Vagrant failed with following message:

```
==> default: Error: Could not parse application options: invalid option: --templatedir
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by rjmackay** [comment]
I'll have a look and update our config for this soon

**Comment by rjmackay** [comment]
So the temporary fix is to ssh into the box and downgrade puppet.. I'll push an update soon with updates the config, however I had to rework a lot of the config to work with a never puppet version

**Comment by rjmackay** [comment]
@rasmi @haisum please test out the updates in #653 if you can
