### ISSUE TITLE
Labels for private fields are visible when not logged in

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4060]
**Describe the bug**
If a field has private responses, the labels for that field is still visible.

**Where was the bug observed**
.io and in local development

**To Reproduce**
1. Create a survey with a field marked as private
2. Add a post and publish the post
3. Log out
4. Go to the post
5. You see the labels but no replies

**Expected behavior**
The fields should not be visible at all (or there should be a note that the response is hidden. Something to indicate to the user that they should not expect something there.)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-90

**Comment by LilyLME** [comment]
@Angamanga @rowasc please can I work on this?

**Comment by Angamanga** [comment]
@rowasc Are you working on this?

**Comment by rowasc** [comment]
@Angamanga eeeeee no :/ I meant to work on them then got sidetracked. @LilyLME go ahead! assigning
Thanks

**Comment by rowasc** [comment]
@LilyLME go ahead! assigning
Thanks
