### ISSUE TITLE
GMail Data Source - Date selected in date field does not persist.

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#4062]
**Describe the bug**
Date that is selected in the date picker on the date field when filling in a GMail Data Source does not persist. Save button appears to persist the date, but when you navigate away and then back, there's no selected date.

**Where was the bug observed**
Test deployment - https://gmail.staging.ush.zone/settings/datasources

**To Reproduce**
1. Log into deployment as an authorised user.
2. Navigate to Data Sources -> Gmail.
3. Enable the Gmail data source.
4. In date field, click on caledar icon to bring up calendar for date selection.
5.Select date.
6. Click Save to persist changes.
7. Navigate to a different page.
8. Go back to Gmail data source page.
9. Note that the date field does not have a value. Email value entered persists.

**Expected behavior**
Date value that was entered/picked should persist once entered and saved.

**Is there a workaround? What is it.**
None.

**Screenshots**
![Screenshot from 2020-08-27 00-27-07](https://user-images.githubusercontent.com/38259840/91358775-121eba80-e7fc-11ea-88f4-ddda22ae2f26.png)

**Desktop Hardware Details (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version 84.0.4147.135 (Official Build) (64-bit)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-89

**Comment by tuxpiper** [comment]
@Obadha2 this should be ready to take another look at now

**Comment by Obadha2** [comment]
QA'd, passes. :+1:
