### ISSUE TITLE
GMail Data Source - Unable to disconnect gmail account.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4067]
**Describe the bug**
Attempts to disconnect gmail account fail with error message: Undefined index: access_token.

**Where was the bug observed**
https://gmail.staging.ush.zone/settings/datasources

**To Reproduce**
1. Go to deployment that has gmail account connected.
2. Log in as an admin.
3. Navigate to Gmail under Data Sources.
4. Click on Disconnect Your Gmail Account.
5. This fails. See error at the bottom of the page.

**Expected behavior**
Attempts to disconnect gmail account should be successful.

**Is there a workaround? What is it.**
It seems to be able to disconnect gmail account, you have to remove the email account. A workaround is change the email account then disconnecting it will work.

**URL / Environment where this happened**
https://gmail.staging.ush.zone/settings/datasources

**Screenshots**
![Screenshot from 2020-09-01 11-41-03](https://user-images.githubusercontent.com/38259840/91827842-0c840300-ec48-11ea-83f3-c3edcb274693.png)

**Desktop Hardware Details (please complete the following information):**
 - OS: Ubuntu 
 - Browser: Chrome
 - Version 85.0.4183.83 (Official Build) (64-bit)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-86

**Comment by tuxpiper** [comment]
any clue what could be causing this @webong ?

**Comment by Obadha2** [comment]
@webong  @tuxpiper this isn't happening anymore. I changed the email address and then I was able to disconnect the old email. I'll double-check to see if I can cause it to happen again. Will update if I find anything.
