### ISSUE TITLE
Add developer documentation about webhooks

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4070]
Draft here:

https://app.gitbook.com/@ushahidi/s/platform-developer-documentation/~/drafts/-MF6aubj4fKtFO6rbGZ7/@drafts

Aha! Link: https://ushahiditeam.aha.io/features/PROD-785

**Comment by tuxpiper** [comment]
@rowasc Could you please review the doc draft above? It would be good to merge if it looks good to you.

**Comment by rowasc** [comment]
@tuxpiper this is great. I left a couple of comments only because I got confused reading the first section. Thanks!

**Comment by tuxpiper** [comment]
Changes accepted and merged to develop :+1:
