### ISSUE TITLE
[Automation] Run our "experiment" test scripts 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#4071]
- When a pull request is created, the test suite should run.
- When a test suite runs, and it succeeds, it should notify back to GitHub and allow merging.
- When a test suite fails it should notify of the failure and block the merge.
- There should be a way to see why it failed (logs).
- There should be a way to trigger a manual test run.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-787

**Comment by tuxpiper** [comment]
We've got CI integration with the Cypress dashboard now via Github Actions 👍
