### ISSUE TITLE
Timezone configuration support

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#4074]
Ushahidi Platform does not support setting up your timezone through an admin interface of any kind. This would be useful especially  in Ushahidi.io where users could be anywhere and they (generally) share resources. 

Minimum needs
- General settings "Timezone" field 
Second phase
- Posts should also allow you to see timezones used
- Posts should allow you to change the timezone for your post

Aha! Link: https://ushahiditeam.aha.io/features/PROD-790

**Comment by rowasc** [comment]
@CeciliaHinga is this something you have seen come up through intercom? People wanting more granular support for timezones?

**Comment by CeciliaHinga** [comment]
@rowasc No, I do not think i have received such a request
