### ISSUE TITLE
Check if the user have permissions before making request to users-endpoint

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4075]
**Describe the bug**
If a user isn't logged in or has the wrong permissions, there is an error in the console when visiting a view with the filters-bar in it:
<img width="234" alt="Screenshot 2020-09-15 at 11 19 46" src="https://user-images.githubusercontent.com/8624777/93197779-5b539180-f74c-11ea-9528-03433741313a.png">

**Where was the bug observed**
.io
local develop-environment

**To Reproduce**
As a not logged in user, go to map-view or data-view. Look at the console and notice the error

**Expected behavior**
No requests should be done to those endpoints if the user has not got the correct permissions.

**Hints for fixing this issue 💡 💡**
Hint 1 💡 : The error happens in the FilterTransformers service: https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/views/filters/filter-transformers.service.js#L13.

Hint 2 💡 : A check is needed to see if the user is logged in and have the correct permissions before making the requests to Role-endpoint and Users Endpoint. The correct permission is "Manage Users". See example here how this is checked in other parts of the application: https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/common/post-metadata.service.js#L29. The other requests can be done no matter what the permission is.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-791

**Comment by Angamanga** [comment]
Solving this issue will likely solve this one as well: https://github.com/ushahidi/platform/issues/2794

**Comment by renujain31** [comment]
Found this linked at #2794. Can I give this a shot?

**Comment by Angamanga** [comment]
@renujain31 Yep, thank you!  👍
