### ISSUE TITLE
Warnings about non-unique ids in the console

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4076]
**Describe the bug**
When going to any view that has the filter-toolbar, there is a warning in the console complaining about non-unique ids:
<img width="240" alt="Screenshot 2020-09-15 at 12 52 13" src="https://user-images.githubusercontent.com/8624777/93202019-4a0d8380-f752-11ea-8bb7-9d62727dfd8a.png">.

**Hints to solving the issue**
This happens because we are hiding some elements that are only used in the embedded version of the platform. While this is ok in most occasions, this time we are dealing with a form with ids and we need to properly remove the element from the DOM instead of just hiding it from the view.

Hint 1 💡 : The problematic code is here: https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/views/post-toolbar.html#L7 and here:  https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/views/post-toolbar.html#L22.

Hint 2 💡  : Check for embeds is done like this: https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/layout-class.directive.js#L16

Hint 3 💡 : `ng-if` can be used to stop things to be added to the DOM

Hint 4 💡 : Embeds can be tested by adding this embed-code: `<iframe width="560" height="315" src="http://localhost:3000/views/data" frameborder="0" allowfullscreen></iframe>` in a simple index.html file and open it in the browser

**Where was the bug observed**
.io
local development environment

Aha! Link: https://ushahiditeam.aha.io/features/PROD-792

**Comment by GabrielFalcom** [comment]
I would like to contribute to this issue.

**Comment by GabrielFalcom** [comment]
I just submitted a pull request for the issue. If something is not right, please let me know.
