### ISSUE TITLE
Roles that have permission to manage posts cannot edit posts submitted via SMS or Emails

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4077]
**Describe the bug**
The admin is the only role that can edit posts submitted via all datasources platform offers. Any role that has permission to manage posts cannot edit posts submitted via emails or sms

**Where was the bug observed**
Production

**To Reproduce**

1. Log in as a member with permission to manage posts
2. Click on data view
3. Click on a post submitted via sms or email , then click on the (...) icon or edit at the upper right corner of the post 
4. You will get an "access denied" message 

**Expected behavior**
Any role that has permission to manage posts should be able to do so.

**Is there a workaround? What is it.**
No

**Screenshots**
<img width="373" alt="Post_Details_-_test254" src="https://user-images.githubusercontent.com/20906968/94158280-e5a59f00-fe8a-11ea-9447-4a553ba2a4c8.png">

**URL / Environment where this happened**
ushahidi.io

**Desktop Hardware Details (please complete the following information):**
 -  iOS
 - Browser chrome
 - Version Version 85.0.4183.102 (Official Build) (64-bit)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-803

**Comment by hariclerry** [comment]
Hello @rowasc  and @CeciliaHinga, I'm an outreachy applicant. Can I work on fixing this bug?

**Comment by rowasc** [comment]
@hariclerry I just assigned a different ticket. If you want to work on this one after that, LMK. Keep in mind this is a backend issue so you should be comfortable with PHP / backend development to contribute to it.
Thanks!

**Comment by tuxpiper** [comment]
I believe we have recently fixed this with #4454 

@Mh-Asmi the contact access issue seems to had been happening for some time already
