### ISSUE TITLE
Add information that posts need to be published in related post field

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4078]
##TODO
When searching for posts in the related-posts field, the search is only happening on published posts. Add a information-text above the search-box informing the user about this.

##How to reproduce
1. Add a number of posts to a survey
2. Let a few stay "Under review", and publish some by clicking the '...' and select "Publish" on the post-card in the data-view:
<img width="249" alt="Screenshot 2020-09-30 at 11 39 23" src="https://user-images.githubusercontent.com/8624777/94669582-b91dd700-0311-11eb-9865-4af7d5de2353.png">

3. Create a survey in settings->Surveys->Add new survey
4. Click on add a "New field", select "Related posts"
5. Select the survey to which you just added the posts as surveys to include
6. Save the survey
7. Add a new post to this survey by clicking the + sign in the map or data-view
8. Add a search that would match one of the posts in review
9. Search-result is empty
10. Add a search that would match one of the published posts
11. See the posts appear in the search-view

##Hints on how to solve
We want to add a text telling the user that the search only happens on published posts. The code where we want to add this is here:

https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/modify/relation.html#L2

We want to add a small info-note, and we do that with the syntax `<p><em>TEXT HERE</em></p>`.

The text should be:
"Please note, the posts to relate to needs to be published, posts that are "Under review" will not appear in the search-results"

The Ushahidi Platform is multi-language and therefore, all strings are stored in a specific file, so by adding the string to the file with the key "related_post_info" we will make it available for translations:
https://github.com/ushahidi/platform-client/blob/develop/app/common/locales/en.json#L268

Then go back to relation.html and add `translate="app.related_post_info"` as an attribute for the `<em>`-tag. Your string will now be available for translators to translate once your code is approved and merged 👏 👏 .

Aha! Link: https://ushahiditeam.aha.io/features/PROD-834

**Comment by renujain31** [comment]
Hey! Can this issue be assigned to me. Thanks!

**Comment by BatoolMM** [comment]
Hi, can I also help in resolving this issue with @renujain31, please?

**Comment by Angamanga** [comment]
@BatoolMM Welcome! 🎉  I have added more first-timer-issues today, I suggest take a look at this one to start with: https://github.com/ushahidi/platform/issues/2394.
