### ISSUE TITLE
Go through labelling in all forms and improve accessibility

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4079]
## Overview
In the Ushahidi Platform, we use a lot of forms, for adding posts, for signing up users, for adjusting settings, and so on. Not always have we done so with accessibility in mind, so we need to go through all forms available and make  sure it is clear what element a label is attached to and adjust where needed.

There are two ways labels are handled in the platform, depending on the markup of the form:

```
<label for="description">Describe what happened</label>
<input id="description" type="text" />
```
and 

```
<label>Describe what happened
     <input id="description" type="text" />
</label>
```

For each form-control, make sure the <label> element is either using the for-attribute to associate the form-control or is encapsulating the form-control like the second example.

The codebase for platform is huge and therefore, we have divided the forms to separate issues so the task does not become too overwhelming. To work on this, grab one of the issues in the list below:

**Authentication**
https://github.com/ushahidi/platform/issues/4080

**Creating and editing posts**
https://github.com/ushahidi/platform/issues/4081

**Collections and saved searches**
https://github.com/ushahidi/platform/issues/4083

**Categories, data export and users**
https://github.com/ushahidi/platform/issues/4086

Aha! Link: https://ushahiditeam.aha.io/features/PROD-835

**Comment by amycruz97** [comment]
is this issue still open

**Comment by amycruz97** [comment]
can i take this

**Comment by rowasc** [comment]
Hey @amycruz97 yes, please go ahead! Thanks

**Comment by amycruz97** [comment]
pls where is the instruction on how to set it up in our local environment

**Comment by Angamanga** [comment]
@amycruz97 The docs with instructions can be found here: https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives#platform-api-backend-install-guides and here: https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives#platform-api-backend-install-guides.

**Comment by hyounes4560** [comment]
@Angamanga @rowasc is it okay to contribute to this as well? Thanks

**Comment by amycruz97** [comment]
ok thanks working on it

**Comment by Sunairaa** [comment]
Hey @Angamanga is this issue still available? can I work on it from windows Os?

**Comment by rowasc** [comment]
@Sunairaa hey, no, this isn't available as @amycruz97 is working on it (see comment above)
Please check for unclaimed tickets in the https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22 list :) 
Thanks!

**Comment by amycruz97** [comment]
Good day i have submitted a pull request. But the bot is saying i havent signed our Contributor License Agreement, yet.
please where can i find it

**Comment by amycruz97** [comment]
Good day

**Comment by rowasc** [comment]
Awesome @amycruz97 I just commented.
