### ISSUE TITLE
Check and fix labels for saved searches and collections

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4083]
There are two ways labels are handled in the platform, depending on the markup of the form:

```
<label for="username">Username</label>
<input id="username" type="text" />
```
and

```
<label>Username
     <input id="username" type="text" />
</label>
```

Go through the following forms and make sure the element is either using the for-attribute to associate the form-control or is encapsulating the form-control like the second example:

**Collections**
Create a collection:
The form is found when clicking on the collection-icon in the mode-bar:
<img width="78" alt="Screenshot 2020-10-05 at 11 55 25" src="https://user-images.githubusercontent.com/8624777/95065876-ebf51000-0701-11eb-8f30-a840066cb8c0.png">

and then click on "Create new"
<img width="312" alt="Screenshot 2020-10-05 at 11 57 37" src="https://user-images.githubusercontent.com/8624777/95066424-adac2080-0702-11eb-82d6-f4e39be12871.png">

The form: 
<img width="495" alt="Screenshot 2020-10-05 at 12 04 42" src="https://user-images.githubusercontent.com/8624777/95066656-f9f76080-0702-11eb-8d2b-a45f1042bf4f.png">

Edit a collection:
The form is found when clicking on the collection-icon in the mode-bar:
<img width="78" alt="Screenshot 2020-10-05 at 11 55 25" src="https://user-images.githubusercontent.com/8624777/95065876-ebf51000-0701-11eb-8f30-a840066cb8c0.png">

Select a collection in the list
<img width="500" alt="Screenshot 2020-10-05 at 12 00 03" src="https://user-images.githubusercontent.com/8624777/95066172-51490100-0702-11eb-839d-655248a9de1e.png">

Go to map-view and click on "edit":
<img width="342" alt="Screenshot 2020-10-05 at 12 00 32" src="https://user-images.githubusercontent.com/8624777/95066733-14313e80-0703-11eb-8e78-41000102ee07.png">

The form:
<img width="483" alt="Screenshot 2020-10-05 at 12 05 45" src="https://user-images.githubusercontent.com/8624777/95066759-1dbaa680-0703-11eb-91ee-87bd7fa062e3.png">

The files for above forms are found here:
- https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/collections/editor.html
- https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/collections/listing.html

**Saved searches**
The form is found when logged in as an admin, clicking on the filter-dropdown and selecting a filter:
<img width="679" alt="Screenshot 2020-10-05 at 12 08 36" src="https://user-images.githubusercontent.com/8624777/95067205-be10cb00-0703-11eb-83a3-a8c05d9cff20.png">

Click on the "Save search" button and the form appears:
<img width="494" alt="Screenshot 2020-10-05 at 12 11 06" src="https://user-images.githubusercontent.com/8624777/95067265-dbde3000-0703-11eb-827c-5aa7e77842c5.png">

For editing a saved search, click on the filter-dropdown and select a saved search in the dropdown, then click "edit":
<img width="427" alt="Screenshot 2020-10-05 at 12 11 55" src="https://user-images.githubusercontent.com/8624777/95067358-04662a00-0704-11eb-92d4-5cd91d207cc5.png">

The template for the form is found here:
- https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/savedsearches/savedsearch-editor.html

If no adjustments is needed, just comment in this issue that you have worked through the issues and checked, if any adjustment is needed, make the necessary changes and create a PR 🎉   If changes are needed, make sure the form still looks the same as before and that is has no effect on the visual appearance of the form.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-839

**Comment by jaiwanth-v** [comment]
Hi @Angamanga ,I would like to work on this issue? Could you please assign it to me? Thanks.

**Comment by jaiwanth-v** [comment]
Hi @Angamanga, I would like to work on this issue. Could you please assign it to me? Thanks.

**Comment by Red-0111** [comment]
I would also like to contribute plz assign I will try my best

**Comment by Angamanga** [comment]
@jaiwanth-v Please go ahead! Thank you for your interest! @Red-0111 I have assigned you to this issue: https://github.com/ushahidi/platform/issues/4081

**Comment by Red-0111** [comment]
@Angamanga thanks will try my best

**Comment by calcem** [comment]
Hi do you still need help with this issue? If so, I would love to help out.

**Comment by Angamanga** [comment]
@calcem Hi and thank you for your interest! Please go ahead 🎉

**Comment by kamzzy** [comment]
hello am an Outreachy intern, I would like to know if you can assign me a task here

**Comment by kamzzy** [comment]
Hello, am an Outreachy applicant, I would like to know if I can be assigned a task

**Comment by codedladiesinnovate** [comment]
Hi, I'm Amadikwa Joy N, an Outreachy applicant. I would like to work on this project. Should I go ahead?

**Comment by UdokaVrede** [comment]
Hi Joy, please check the account you are using

**Comment by treasurechristain** [comment]
Thanks @UdokaVrede for notifying me

**Comment by Sunairaa** [comment]
Hey @Angamanga is this issue still available? if yes can I would like to work on it?

**Comment by LavellTheDev** [comment]
@Angamanga Can I take a crack at this?

**Comment by BrandonOdiwuor** [comment]
Hello @Angamanga, is this issue still available?

**Comment by Angamanga** [comment]
@BrandonOdiwuor Sorry this is fixed. Check the "community-task" label for more issues.
