### ISSUE TITLE
Check and fix labels for Settings->Categories, Data export and Users

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4086]
There are two ways labels are handled in the platform, depending on the markup of the form:

```
<label for="username">Username</label>
<input id="username" type="text" />
```
and

```
<label>Username
     <input id="username" type="text" />
</label>
```

Go through the following forms and make sure the element is either using the for-attribute to associate the form-control or is encapsulating the form-control like the second example:

**Categories**
The code is found here:

https://github.com/ushahidi/platform-client/blob/develop/app/settings/categories/categories-edit.html

You find the view by logging in as an admin, then click on Settings and select "Categories", then click the "+" icon:

<img width="134" alt="Screenshot 2020-10-06 at 14 11 25" src="https://user-images.githubusercontent.com/8624777/95200067-0ef4f200-07de-11eb-9d2e-29bb5da5e6d4.png">

**Data export**
The code is found here: 
https://github.com/ushahidi/platform-client/blob/develop/app/settings/data-export/data-export.html

You find the view by logging in as an admin, then click on Settings and select "Export and tag data". Then click on "Select fields".

**Users**
The code is found here: 
https://github.com/ushahidi/platform-client/blob/develop/app/settings/users/users-edit.html

You find the view by logging in as an admin, click on Settings and select "Users", then click the "+" icon.

If no adjustments is needed, just comment in this issue that you have worked through the issues and checked, if any adjustment is needed, make the necessary changes and create a PR 🎉   If changes are needed, make sure the form still looks the same as before and that is has no effect on the visual appearance of the form.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-840

**Comment by JaniPaasiluoto** [comment]
I could take this if still available?

**Comment by TunrayoIlawole** [comment]
Hey @Angamanga Can i work on this one?

**Comment by itolimaesther** [comment]
@Angamanga  am an outreachy applicant. Can I work on this issue

**Comment by stacytonui** [comment]
Hello, Outreachy Applicant here, can i work on this?

**Comment by AishaSaman** [comment]
Hey @Angamanga, I am an Outreachy Applicant and willing to work on this issue, Please assign this to me, Thanks

**Comment by Shreets** [comment]
Hi @Angamanga, I am an Outreachy Internship Applicant. I would love to work on this issue. Thank you.

**Comment by Angamanga** [comment]
@JaniPaasiluoto @TunrayoIlawole @itolimaesther @stacytonui @AishaSaman @Shreets There is already a pullrequest waiting for review so I suggest you hold on to not do unnecessary work :) Please check this link if you find something else to work on: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22

**Comment by kamzzy** [comment]
hello, am an Outreachy applicant, please can I be assigned this

**Comment by kamzzy** [comment]
hello, am an Outreachy applicant, please can I be assigned this

**Comment by kamzzy** [comment]
hello, am an Outreachy applicant, please can I be assigned this

**Comment by kamzzy** [comment]
hello, am an Outreachy applicant, please can I be assigned this

**Comment by imaliesiera** [comment]
Hello @Angamanga . I'd like to work on this. Is it still open?

**Comment by hyounes4560** [comment]
Hi, I am an Outreachy Applicant, can I work on this? @Angamanga

**Comment by Angamanga** [comment]
@kamzzy @hyounes4560  There is already a pullrequest waiting for review so I suggest you hold on to not do unnecessary work :) Please check this link if you find something else to work on: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22

**Comment by treasurechristain** [comment]
I can work on This if its still available. I'm Amadikwa Joy N. from Outreachy

**Comment by LizzyKate** [comment]
I can work on This if its still available. I am an Outreachy applicant

**Comment by Angamanga** [comment]
@treasurechristain @LizzyKate There is already a pull request open for this issue, please check here for other issues: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22

**Comment by rowasc** [comment]
@Obadha2 you mentioned this failed QA (the https://github.com/ushahidi/platform-client/pull/1552 PR) could you add the failures here so @fabiomus can continue? 
Thanks

**Comment by Obadha2** [comment]
@rowasc @fabiomus details for the failures are listed on the PR [here](https://github.com/ushahidi/platform-client/pull/1562), including screenshots.

**Comment by Obadha2** [comment]
This failed QA because:
 - User creation page has Display name and Email Address text fields missing. 
<img width="1032" alt="95717906-5bc14880-0c76-11eb-9214-340384dec6a6" src="https://user-images.githubusercontent.com/38259840/97158451-8210d900-178a-11eb-943b-2c54983b849c.png">

 - Category creation page has Category Name and Description text fields missing.
<img width="1119" alt="95718102-a773f200-0c76-11eb-877f-2c89838240f4" src="https://user-images.githubusercontent.com/38259840/97158479-8b9a4100-178a-11eb-851e-c95bf4377223.png">
