### ISSUE TITLE
Check and fix labels on General settings, Roles and Webhooks

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4087]
There are two ways labels are handled in the platform, depending on the markup of the form:

```
<label for="username">Username</label>
<input id="username" type="text" />
```
and

```
<label>Username
     <input id="username" type="text" />
</label>
```

Go through the following forms and make sure the element is either using the for-attribute to associate the form-control or is encapsulating the form-control like the second example:

**General settings**
The code is found here: 
https://github.com/ushahidi/platform-client/blob/develop/app/settings/site/settings-editor.html

You find the view by loggin in as an admin, click on "Settings" in the left-hand mode-bar and then on "General" in the settings-list.

**Roles**
The is found here:
https://github.com/ushahidi/platform-client/blob/develop/app/settings/roles/roles-edit.html

You find the view by loggin in as an admin, click on "Settings" in the left-hand mode-bar and then on "Roles" in the settings-list. In the roles-view, click on the "+" icon.

**Webhooks**
The code is found here:
https://github.com/ushahidi/platform-client/blob/develop/app/settings/webhooks/webhooks-edit.html

You find the view by loggin in as an admin, click on "Settings" in the left-hand mode-bar and then on "Webhooks" in the settings-list. In the webhooks-view, click on the "+" icon.

If no adjustments is needed, just comment in this issue that you have worked through the issues and checked, if any adjustment is needed, make the necessary changes and create a PR 🎉   If changes are needed, make sure the form still looks the same as before and that is has no effect on the visual appearance of the form.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-841

**Comment by ray3du** [comment]
Hey @Angamanga  am a first-timer can I be assigned to this.

**Comment by JaniPaasiluoto** [comment]
@Angamanga I could work with this, if @ray3du skips.

**Comment by nibble0101** [comment]
@Angamanga I am interested in this too.

**Comment by Angamanga** [comment]
@JaniPaasiluoto and @nibble0101 Thank you for your interest! I am going to add more first-timer issues today, please check later in the day and there will be more to choose from 🎉!

**Comment by TunrayoIlawole** [comment]
Hey @Angamanga I'm a first timer. Can i please work on this?

**Comment by bimbolabuari** [comment]
Hello @Angamanga I am an Outreachy Internship Applicant, Please Can i work on this issue?

**Comment by stacytonui** [comment]
Hey @Angamanga Outreachy applicant, can I please work on this?

**Comment by muchirijane** [comment]
Hey @Angamanga, I am an Outreachy applicant, could I please work on this issue?

**Comment by lape15** [comment]
@Angamanga  please can i work on this

**Comment by s8mcmahon** [comment]
@Angamanga I am an Outreachy applicant, can I please work on this issue?

**Comment by mariehposa** [comment]
Hi @Angamanga, I'm an Outreachy applicant, I would like to work on this issue.

**Comment by GitWrld** [comment]
do i have to work on all of them or just one? are they all in one category?

**Comment by Shreets** [comment]
Hi @Angamanga, I am an Outreachy Internship Applicant. I would love to work on this issue.

**Comment by Angamanga** [comment]
@ray3du Thank you for your interest! Please go ahead and work on this issue. @Shreets @GitWrld @mariehposa @s8mcmahon @lape15 @muchirijane @stacytonui @bimbolabuari @TunrayoIlawole @JaniPaasiluoto @nibble0101 Please check out this link if you can find something else you are interested in: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22 We are adding more issues continuously but due to the large interest in Outreachy this year we are lagging behind. Please bear with us :)

**Comment by ray3du** [comment]
Thank you @Angamanga, working on it.

**Comment by muchirijane** [comment]
@Angamanga, I totally understand. Let me check for others.

**Comment by A-DML** [comment]
Morning @Angamanga  I will like to work with you and this task for my Outreachy internship contribution.

**Comment by hyounes4560** [comment]
Hello, Outreachy Applicant here, can I work on this? @Angamanga

**Comment by Dev-Som** [comment]
Hello @Angamanga I'm a first timer. Can I please work on this?

**Comment by Angamanga** [comment]
@hyounes4560 @Dev-Som There is already someone working on this issue so in this case no. Please check out this link if you can find something else you are interested in: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22 We are adding more issues continuously but due to the large interest in Outreachy this year we are lagging behind. Please bear with us :)
