### ISSUE TITLE
Check and fix labels on survey-creation

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4089]
There are two ways labels are handled in the platform, depending on the markup of the form:

```
<label for="username">Username</label>
<input id="username" type="text" />
```
and

```
<label>Username
     <input id="username" type="text" />
</label>
```

Go through the following forms and make sure the element is either using the for-attribute to associate the form-control or is encapsulating the form-control like the second example:

**Survey-creation**
This is quite a complex view, split down in several templates. I suggest you start reading through our user-docs about surveys here: https://docs.ushahidi.com/ushahidi-platform-user-manual/3.-configuring-your-deployment/3.3-surveys

You find the code to the templates here:
https://github.com/ushahidi/platform-client/tree/develop/app/settings/surveys

To see the view, log in as an admin, go to Settings->click on Surveys and then on "Create a new survey".
To see the field-forms, click on "Title" and "Description" and also "Add new field" and select the different field-types.

To see the task-form, click on "Add new task".

For the targeted surveys, click on "Send a targeted survey via sms" in the left hand modebar:
![Screenshot 2020-10-08 at 08 47 09](https://user-images.githubusercontent.com/8624777/95424503-0669fc00-0943-11eb-91c0-aceda128311e.png)

If no adjustments is needed, just comment in this issue that you have worked through the issues and checked, if any adjustment is needed, make the necessary changes and create a PR 🎉   If changes are needed, make sure the form still looks the same as before and that is has no effect on the visual appearance of the form.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-843

**Comment by renujain31** [comment]
Hey, As I am also working on a similar issue for the survey forms can this also be assigned to me? Thanks!

**Comment by helen-ndip** [comment]
@renujain31 @Angamanga  its my first time to contribute can I work on this issue?

**Comment by Angamanga** [comment]
@renujain31 I have assigned you to this issue: https://github.com/ushahidi/platform/issues/3994 @helen-ndip Please go ahead with this issue 🎉

**Comment by helen-ndip** [comment]
> @renujain31 I have assigned you to this issue: #3994 @helen-ndip Please go ahead with this issue 🎉

ok thanks

**Comment by Ifycode** [comment]
Hi @Angamanga, I'm an outreachy applicant. Can I still contribute on this issue?

**Comment by Dev-Som** [comment]
Hi @Angamanga  I am an outreachy applicant, Can I work on this?

**Comment by Angamanga** [comment]
@Ifycode @Dev-Som There is already someone working on this issue so in this case no. Please check out this link if you can find something else you are interested in: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22 We are adding more issues continuously but due to the large interest in Outreachy this year we are lagging behind. Please bear with us :)

**Comment by Ifycode** [comment]
Ok. Thank you for your response.

**Comment by tuxpiper** [comment]
@all-contributors please add @helen-ndip for code
