### ISSUE TITLE
Behavior when navigating links in the mode-bar with the tab key

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform#4095]
Expected behaviour:

As a user, I expect that pressing the tab key should take me the next link in the mode-bar and in the order that the links are visually arranged. With visible outline around the link elements to know what link i'm currently on.
![tabbing-modebar](https://user-images.githubusercontent.com/45185388/95636340-bcb50a80-0a43-11eb-8d18-c6a1a7e4acf1.PNG)
![tabbing-modebar-2](https://user-images.githubusercontent.com/45185388/95637883-ce001600-0a47-11eb-9a35-dfd2878118fc.PNG)

Actual behaviour:
- Link for map, data, activity, settings follow the right order when you tab through for both laptop and smaller devices. However in smaller screen width, the outline for these links are somewhat hidden, which may not make visually impaired user know what link they're currently on.

- These other links are skipped: collection, user and logout.

Steps to reproduce the behaviour:
- Open up https://yourOwnPageName.ushahidi.io/views/map or http://localhost:3000/views/map
- Try navigating the links with the tab key

Aha! Link: https://ushahiditeam.aha.io/features/PROD-849

**Comment by Ifycode** [comment]
@Angamanga I found this while trying to navigate the page, I haven't been assigned any task. Is this approved and can I try my hands on this?

**Comment by rowasc** [comment]
@Ifycode Hey thanks for this report. Yes, please go ahead , assigned to you ! 

cc @Angamanga I didn't find any other ticket reporting this issue so I've approved this one.

**Comment by Ifycode** [comment]
Yay! Thank you @rowasc

**Comment by Ifycode** [comment]
@Angamanga @rowasc I've submitted 2 pull requests for this task. Please help review.

**Comment by rowasc** [comment]
Great. We're aware, thanks. We're working through PRs .
Thanks

**Comment by Ifycode** [comment]
Ok @rowasc. Thanks for the response. I found this other issue while working on this project.

**Comment by tuxpiper** [comment]
@all-contributors please add @Ifycode for code
