### ISSUE TITLE
Change the alt-text on the user-avatar

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4100]
## Description
When logged in, there is an image in the modebar showing the user-avatar:
<img width="50" alt="Screenshot 2020-10-13 at 15 19 33" src="https://user-images.githubusercontent.com/8624777/95865993-a078dc80-0d67-11eb-8d30-825c5ce5e901.png">

## Todo:
- The alt-text for this icon is the user-name, change this to say "Account-settings".
- Below the image there is a span, which shows the tooltip. Here is also the user-name used. Change this to "Account-settings" as well. This needs to be translated, the correct string for this is found here: https://github.com/ushahidi/platform-client/blob/develop/app/common/locales/en.json#L564
 HINT! Use the same method as the "Log out" button to translate the text: https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/mode-bar/mode-bar.html#L70

Aha! Link: https://ushahiditeam.aha.io/features/PROD-852

**Comment by Angamanga** [comment]
@sunairaa Assigning this issue to you!

**Comment by Sunairaa** [comment]
Hey, Thanks @Angamanga for assigning this issue to me..

**Comment by Sunairaa** [comment]
Hey, @rowasc  @Angamanga do I need to login on this link https://ushahiditeam.aha.io/features/PROD-852 if yes? then what are credentials?

**Comment by rowasc** [comment]
Hey @Sunairaa no need. 
Thanks

**Comment by hyounes4560** [comment]
> @rowasc i have done with my task but when I am going to push my code I am getting error `fatal: unable to access 'https://github.com/ushahidi/platform-client.git/': The requested URL returned error: 403 can you please help me out? `

@Sunairaa did you fork, create a branch and then created PR for your code?

**Comment by Sunairaa** [comment]
> > @rowasc i have done with my task but when I am going to push my code I am getting error `fatal: unable to access 'https://github.com/ushahidi/platform-client.git/': The requested URL returned error: 403 can you please help me out? `
> 
> @Sunairaa did you fork, create a branch and then created PR for your code?

yes I forked code yesterday.. then today I use these command before starting work 
```
$ git pull
$ git checkout -b <branch-name>
```
then made some changes - (issue assigned)
```
$ git add <file-path>
$ git commit -m "commit message"
$ git push --set-upstream origin <branch-name>
```
after that, i got above fatal!

**Comment by Sunairaa** [comment]
I made PR https://github.com/ushahidi/platform-client/pull/1566 . @rowasc @Angamanga kindly check my work 👍

**Comment by Sunairaa** [comment]
while doing this task i found some UI issues:

1. logo text is breaking (not shown completely) on my screen.
![image](https://user-images.githubusercontent.com/66335481/95927324-4120c980-0d73-11eb-8160-848bd396e576.png)


2. language dropdown options text was not visible when I select particular language like currently there is only English option so when I hover on so I can see text otherwise text was not visible.
![image](https://user-images.githubusercontent.com/66335481/95927373-5e559800-0d73-11eb-8ad6-33dbc94f9f61.png)
![image](https://user-images.githubusercontent.com/66335481/95927402-6e6d7780-0d73-11eb-8985-48cc1ca68094.png)

can I be assigned to fix these issues?

**Comment by Aqsa48** [comment]
@Sunairaa Hey,

Create issues for that , Once issues are created that can be resolved later.

**Comment by Angamanga** [comment]
@Sunairaa It would be super helpful if you could submit new issues for above findings! Thank you 🙏

**Comment by Sunairaa** [comment]
@Angamanga yeah sure I will create a issue!

**Comment by tuxpiper** [comment]
@all-contributors please add @Sunairaa for code
