### ISSUE TITLE
Go through all image-tags and add alt-texts

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4101]
To improve accessibility, all images need an alt-text:

The codebase for platform is huge and therefore, we have divided the elements to separate issues so the task does not become too overwhelming. To work on this, grab one of the issues in the list below:

**Modebar:**
https://github.com/ushahidi/platform/issues/4100

**Deployment logo:**
https://github.com/ushahidi/platform/issues/4102

Aha! Link: https://ushahiditeam.aha.io/features/PROD-853

**Comment by Isaac-Tait** [comment]
I would like to start working on this 🤓

**Comment by hyounes4560** [comment]
Hi @Angamanga @rowasc Can I work on this one? Thanks

**Comment by Sunairaa** [comment]
Hey @Angamanga i have done with #4100.. now can I work on issue #4102 Deplyment logo.

**Comment by treasurechristain** [comment]
@Angamanga I'm Amadikwa Joy N. An outreachy Applicant. Can I work on this issue please.

**Comment by bimbolabuari** [comment]
Hi @Angamanga @rowasc Can I work on this one? Thanks

**Comment by Angamanga** [comment]
@hyounes4560 Please go ahead. @Sunairaa @treasurechristain @bimbolabuari Sorry this one is taken. Look out for more issues as we add them.

**Comment by Angamanga** [comment]
@hyounes4560 Ah wait this one is the collection-issue for the alt-texts, don't work on this. Look out for more issues here, I will add new ones today.
