### ISSUE TITLE
Documentation: The different methods/options of installing the changed styles into platform-client locally for testing are not written in one place

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform#4105]
**Expected arrangement:**

Discovered this issue with the documentation while working on Issue ushahidi/platform#4095 which required me to make changes to (both platform-client and) platform-pattern-library. As the mentioned issue was my first contribution to ushahidi's large code base, I expected that the documentation guide would group related/similar installation options together. In this case, the different methods of installing the changed styles from platform-pattern-library into platform-client locally should have been discussed on the same page. It took me a while to figure out that they are just alternatives and not different sets of instructions entirely.

**Actual arrangement:**

The different methods of installing the changed styles into platform-client locally during development are scattered in different parts of the documentation. 

**Methods and where to find them:**
- Copy and paste method: Find it inside [development and code > setup guides >setting up the pattern library for development](https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/setting-up-the-pattern-library-for-development) under the heading _But how do I test my new styles in the platform?_
- npm install method 1: Find it inside [front-end development > changing UI styles: Introduction to the pattern library > using the changed styles in platform-client](https://docs.ushahidi.com/platform-developer-documentation/front-end-development/changing-ui-styles-introduction-to-the-pattern-library/using-the-changed-styles-in-platform-client).
- npm install method 2: Find it inside [front-end development > changing UI styles: Introduction to the pattern library > how to apply to the platform](https://docs.ushahidi.com/platform-developer-documentation/front-end-development/changing-ui-styles-introduction-to-the-pattern-library/how-to-apply-to-the-platform) under the heading _test your changes on a local client_.

**Suggestions:**
- Document all methods in one page and add the link to any other page that needs to mention local installation of changed styles. 
- The last method (npm install method 2) doesn't work when I tried it out and i'm thinking what is written there isn't correct, I wouldn't know maybe someone else try it out if it would work. If truly it doesn't work, it'll be good to remove it.
- This issue is written specifically to point out installation options related to platform-pattern-library that should have been grouped together. An Issue with a more general heading could be raised where outreachy applicants and other contributors can add comments. In the comments they can state the items or options that they noticed belong together but that are scattered in different parts of the documentation, repetitions and contradictions in the documentation which may have caused confusion while installing any of ushahidi's platforms.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-857

**Comment by Ifycode** [comment]
@rowasc @Angamanga I found another issue.

**Comment by Angamanga** [comment]
@Ifycode Thank you for checking our docs and suggestions! I will review and change shortly!

**Comment by Ifycode** [comment]
OK. Thank you @Angamanga
