### ISSUE TITLE
Language drop down contains white text on white background, not visible.

### ISSUE THREAD

**Issue by helen-ndip** [ushahidi/platform#4106]
**How to reproduce issue**
When user opens the platform-client on the browser then select language from the sidebar.

**What I expect**
I expected to see all possible languages when I click on the drop down.

**What actually happened**
The language text is white over a white background making it invisible except when user hovers over it before it becomes visible with a blue text color.

**Image**
The arrow in the image below should be pointing to 'English' but it is not visible
![image](https://user-images.githubusercontent.com/72542706/95939338-c045ea00-0dd3-11eb-8b47-9cf7cc468965.png)

**Comment by helen-ndip** [comment]
@rowasc @Angamanga  Can I please work on this. I would like to change the text to the default select color of the application.

**Comment by Dev-Som** [comment]
@Angamanga I please work on this?

**Comment by Angamanga** [comment]
@helen-ndip Please go ahead. I think I remember this is a browser-specific thing. I think you likely need to fix this in the pattern-library. Check the docs here if you haven't already:  https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/setting-up-the-pattern-library-for-development

**Comment by helen-ndip** [comment]
@rowasc  @Angamanga  I created a pull request for this here [https://github.com/ushahidi/platform-pattern-library/pull/255](https://github.com/ushahidi/platform-pattern-library/pull/255)
