### ISSUE TITLE
`undefined` variable shows on page after logout

### ISSUE THREAD

**Issue by helen-ndip** [ushahidi/platform#4107]
**How to reproduce issue**
- platform-client on the browser
- Log in and select 'Activity' or 'Settings' from the side menu.
- Log out.
- Refresh the page

**What I expect**
I expect to see the exact view I had before logging in.

**What actually happened**
I am successfully logged out but I see and undefined variable on the screen.

**Image**
![undefine](https://user-images.githubusercontent.com/72542706/95940556-8a563500-0dd6-11eb-9cc5-8b5c0185fadb.jpg)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-859

**Comment by helen-ndip** [comment]
@rowasc @Angamanga  can I send a pull request for this. I added checks to make sure the value is set before displaying.

**Comment by Dev-Som** [comment]
@Angamanga Can I work on the issue here?

**Comment by Angamanga** [comment]
@helen-ndip Please go ahead! @Dev-Som Please look here for other issues: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22

**Comment by helen-ndip** [comment]
> @helen-ndip Please go ahead! @Dev-Som Please look here for other issues: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22

ok
