### ISSUE TITLE
Add button role to improve accessibility in common/notifications and user-profile

### ISSUE THREAD

**Issue by renujain31** [ushahidi/platform#4112]
# Description:
Standardizing the appearance of buttons enhances the user's recognition of the widgets as buttons. We can add buttons by using `role=button` in the HTML element and thus can increase the accessibility of platform.

# Todo:
Go through the files in these folder: 
1. [platform-client/app/common/notifications](https://github.com/ushahidi/platform-client/tree/develop/app/common/notifications)
2. [platform-client/app/common/user-profile](https://github.com/ushahidi/platform-client/tree/develop/app/common/user-profile)

Search for any buttons in the codebase of platform-client which are not button-elements and add `role=button` in the html element with that class. An easy way to search that might be by searching for `class="button` Make sure that you do not make any changes to the UI of platform.

**Comment by onyeepeace** [comment]
@renujain31 I'll like to work on this

**Comment by amycruz97** [comment]
can i work on this
