### ISSUE TITLE
Add button role to improve accessibility in app/main

### ISSUE THREAD

**Issue by renujain31** [ushahidi/platform#4113]
# Description:
Standardizing the appearance of buttons enhances the user's recognition of the widgets as buttons. We can add buttons by using `role=button` in the HTML element and thus can increase the accessibility of platform.

# Todo:
Go through the files in these folder:  [platform-client/app/main](https://github.com/ushahidi/platform-client/tree/develop/app/main)

Search for any buttons in the codebase of platform-client which are not button-elements and add `role=button` in the html element with that class. An easy way to search that might be by searching for `class="button` Make sure that you do not make any changes to the UI of platform.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-865

**Comment by muchirijane** [comment]
Hey @Angamanga, Can I work on this issue.

**Comment by Angamanga** [comment]
@renujain31 Do we need to add role="button" for the button-elements? I think that is only used for elements that behaves like buttons but are not button-elements. We DO have some of these in the platform, so searching for class="button would probably return those places.

**Comment by renujain31** [comment]
Oh yes! I agree. I completely forgot about that. I am sorry!

**Comment by Angamanga** [comment]
@renujain31 Thank you for updating the description <3 Are you working on this or can I assign @muchirijane?

**Comment by renujain31** [comment]
Hey you can assign this to @muchirijane

**Comment by Angamanga** [comment]
@muchirijane Assigning you to this issue!

**Comment by muchirijane** [comment]
@Angamanga Thank you, let me work on it. 💯

**Comment by siggrid** [comment]
@Angamanga @renujain31 

Not sure, if it has to be a new issue. Besides `role=button`, `tabindex=0` must be applied to elements that behave like a button, but are not actually a `<button>` element (e.g. `<span class=”button” ng-click=””>`), except for links with href attribute (`<a href=””>`)
Using `tabindex=0` we will insert those elements into tab order. Therefore elements will receive focus when pressing Tab key.

**Comment by renujain31** [comment]
Hey, ya @siggrid that's a good suggestion. I would add that in the description. Thanks!

**Comment by Angamanga** [comment]
@siggrid @renujain31 Definitely. I think that fits as a new issue, would anyone of you like to add it? 🙏

**Comment by renujain31** [comment]
Hey, Ya I can add that!
