### ISSUE TITLE
Add button role to improve accessibility in app/settings

### ISSUE THREAD

**Issue by renujain31** [ushahidi/platform#4114]
# Description:
Standardizing the appearance of buttons enhances the user's recognition of the widgets as buttons. We can add buttons by using `role=button` in the HTML element and thus can increase the accessibility of platform.

# Todo:
Go through the files in these folder:  [platform-client/app/settings](https://github.com/ushahidi/platform-client/tree/develop/app/settings)

Search for any buttons in the codebase of platform-client which are not button-elements and add `role=button` in the html element with that class. An easy way to search that might be by searching for `class="button` Make sure that you do not make any changes to the UI of platform.

**Comment by Ifycode** [comment]
@Angamanga can I do this too?

**Comment by Sunairaa** [comment]
Hey @Angamanga is this issue still available? i would love to work on it.

**Comment by Kennygrace** [comment]
@Angamanga  I would like to take this up

**Comment by rowasc** [comment]
@onyeepeace this seems to be the issue you worked on https://github.com/ushahidi/platform-client/pull/1580 would you mind commenting here so I can assign it to you? Otherwise GitHub seems to not let me do that.

**Comment by onyeepeace** [comment]
@rowasc Yes, I worked on this. This https://github.com/ushahidi/platform-client/pull/1580 is the link to the PR.
