### ISSUE TITLE
Add alt-text to empty image alt attributes

### ISSUE THREAD

**Issue by onyeepeace** [ushahidi/platform#4117]
## Description
To improve accessibility, all images need an alt-text.
I have noticed some icons and logos don't have an alt-text

## TODO:
Find all img-elements with empty alt-text and add an alt-text. Make sure that you do not make any changes to the UI of platform.

**Comment by Sunairaa** [comment]
@Angamanga can i work on this issue?

**Comment by Kennygrace** [comment]
@Angamanga I would like to work on this issue
