### ISSUE TITLE
Make Logo text responsive for larger screen

### ISSUE THREAD

**Issue by Sunairaa** [ushahidi/platform#4118]
### Desciption
Header -> logo text is not showing properly when we have a screen size of more than 1024.

**Problem**
![image](https://user-images.githubusercontent.com/66335481/96039252-3ae72780-0e1d-11eb-88d0-9b65befd5e74.png)
**Expected Output**
![image](https://user-images.githubusercontent.com/66335481/96041450-b5657680-0e20-11eb-96ab-bbf8c79ae785.png)

### TODO
Resize logo text so it should appear properly. this can be done by making some CSS changes.

### Note
I have noticed the class of logo text is used in a few other files so we need to work carefully while working on this issue so that we can't disturb other things.

**Comment by Sunairaa** [comment]
Hello, @Angamanga @rowasc I have found this issue and it's solution can I work on it?

**Comment by Angamanga** [comment]
@Sunairaa Yes, please go ahead. You may need to make changes in the Pattern Library for this one.

**Comment by Sunairaa** [comment]
> @Sunairaa Yes, please go ahead. You may need to make changes in the Pattern Library for this one.

Okayy thank you @Angamanga

**Comment by Sunairaa** [comment]
Hey @Angamanga I have done with this task https://github.com/ushahidi/platform-pattern-library/pull/247

**Comment by Angamanga** [comment]
@Sunairaa Thank you! I will review shortly!

**Comment by Sunairaa** [comment]
> @Sunairaa Thank you! I will review shortly!

You're welcome 👍 @Angamanga assign me another issue
