### ISSUE TITLE
Enhance dropdown options

### ISSUE THREAD

**Issue by Sunairaa** [ushahidi/platform#4120]
### Description
Language dropdown is not showing properly, options are not visible when unselected.

**Problem**
![image](https://user-images.githubusercontent.com/66335481/96047493-104f9b80-0e2a-11eb-9043-91c4fed21261.png)

**Expected Output**
![image](https://user-images.githubusercontent.com/66335481/96047448-f7df8100-0e29-11eb-8917-01d1ceb7d19d.png)

### TODO
This issue could be solved by adding some CSS code on dropdown options.

**Comment by Sunairaa** [comment]
Hello, Dear @Angamanga @rowasc, i found this issue and its solution. can I work on this issue?

**Comment by Ifycode** [comment]
Same as #4106

**Comment by Sunairaa** [comment]
Hey @Ifycode i just noticed now! even I just saw something already created PR too on platform-pattern-library repo.. so I think I should close this issue!
