### ISSUE TITLE
Check and fix labels on new posts

### ISSUE THREAD

**Issue by bimbolabuari** [ushahidi/platform#4121]
## Description

Some labels are not associated with their respective input elements in the create post field. 
Clicking on an associated label activates its respective input by changing the focus to it and other accessibility advantages.

### To Reproduce

1. Log in as admin
2. Click on "Data" in the left-hand mode-bar list
3. In the post-view, click on the "+" icon.
4. Create a new survey 
5. Click on any input label

**Current behavior**
When some of the label element is clicked, the focus is not changed to their respective input 

**Expected behavior**
When an associated input is clicked, the focus is changed

### Proposed Solution

Go through the label field and make sure the element is using the for-attribute to associate the respective input element.

**Screenshots**
![issue-ushahidi-create-post](https://user-images.githubusercontent.com/66112760/96254759-b7a90b80-0fad-11eb-9904-f11da3b996fd.png)

### Additional Context

Add more fields to the create post view by going to Settings > Surveys > Click on an existing survey or create a new one > Click on the add field button to add a new field. This way, we can test for the label association of other fields.

**Comment by AishaSaman** [comment]
Assign me this issue I am an Outreachy Internship Applicant

**Comment by Sunairaa** [comment]
Hey, @Angamanga I am an outreachy candidate, can I work on this issue?

**Comment by bimbolabuari** [comment]
Hi @sunairaa @AishaSaman, I am already working on this issue. Thanks :slightly_smiling_face:

**Comment by Sunairaa** [comment]
Were you assigned by @Angamanga?

**Comment by bimbolabuari** [comment]
Hi @Sunairaa, No, I am not assigned yet, however, I created this issue while I am trying to work on #2746 and I have opened a pull request here https://github.com/ushahidi/platform-client/pull/1581.

I am sure how this works, but I think you can also open another pull request, let's wait for @Angamanga respond

**Comment by Sunairaa** [comment]
> Hi @Sunairaa, No, I am not assigned yet, however, I created this issue while I am trying to work on #2746 and I have opened a pull request here [ushahidi/platform-client#1581](https://github.com/ushahidi/platform-client/pull/1581).
> 
> I am sure how this works, but I think you can also open another pull request, let's wait for @Angamanga respond

okay @bimbolabuari Good Luck 👍

**Comment by Angamanga** [comment]
@bimbolabuari This issue is overlapping with this one: https://github.com/ushahidi/platform/issues/4081. Closing this and assigning you on that one instead.
