### ISSUE TITLE
Associated the labels to their respective inputs

### ISSUE THREAD

**Issue by muchirijane** [ushahidi/platform#4123]
### Description 
The search and date inputs on the search page lack labels. 

<img src="https://i.ibb.co/r58KgLL/Fire-Shot-Capture-009-Posts-Ushahidi-Write-Speak-Code2019-localhost.png" alt="Fire-Shot-Capture-009-Posts-Ushahidi-Write-Speak-Code2019-localhost" border="0">

### TODO
Ensure the inputs have the label tag for accessibility.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-875

**Comment by muchirijane** [comment]
Hey @Angamanga, could I work on this issue?

**Comment by hariclerry** [comment]
Hey @Angamanga and @rowasc,  can I work on this issue too?

**Comment by KarenEfereyan** [comment]
A pull request on this already
