### ISSUE TITLE
Add img role in all svg images to improve accessibility.

### ISSUE THREAD

**Issue by renujain31** [ushahidi/platform#4130]
# Description:
When using embedded SVG images, it is a good idea to set role="img" on the outer <svg> element and give it a label. 
This will cause screen readers to just consider it as a single entity and describe it using the label, rather than trying to read out all the child nodes.

# Todo:

Search for `<svg class="iconic"` in the *.html files of platform-client codebase and replace it with `<svg class="iconic" role="img"`. It involves changes at approximately 260 lines and 79 files so make sure that the UI is not affected.

**Comment by AishaSaman** [comment]
I would like to take this. If it's available

**Comment by amycruz97** [comment]
can i work on this pls

**Comment by bukolabisuga** [comment]
Hi @Angamanga I'd love to work on this. Thank you!

**Comment by KarenEfereyan** [comment]
@renujain31 can I work on this? I'm an outreachy applicant!

**Comment by treasurechristain** [comment]
@Angamanga please let me work on this issue. I'm Amadikwa Joy N. an outreachy applicant

**Comment by rowasc** [comment]
@AishaSaman @amycruz97  you already have a ticket assigned. Let us know (in the corresponding ticket) if you are blocked. Thanks.
@bukolabisuga please go ahead with this one. Good luck.

**Comment by bukolabisuga** [comment]
Thanks so much @rowasc , I've raised a PR for this issue here : https://github.com/ushahidi/platform-client/pull/1593

**Comment by KarenEfereyan** [comment]
> Thanks so much @rowasc , I've raised a PR for this issue here : [ushahidi/platform-client#1593](https://github.com/ushahidi/platform-client/pull/1593)

This woman ehn😂😂😂

**Comment by rowasc** [comment]
@KarenEfereyan I have no idea what you intend with this comment, can you explain? 
Thanks!

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan I have no idea what you intend with this comment, can you explain?
> Thanks!

She sent in the PR minutes after she was assigned. It was so fast. That's what i mean

**Comment by tuxpiper** [comment]
@all-contributors please add @bukolabisuga for code
