### ISSUE TITLE
Focus is not trapped inside the modals - keyboard input 

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform#4131]
Found this issue while solving issue #4095. After fixing links skipped by the tab key and able to click on the links using the enter key as noted in [4095 pull request](https://github.com/ushahidi/platform-client/pull/1564#issuecomment-713254498). Some links take you to a different page, some other links just open up a modal. 

**Describe the bug:**

The issue is for links/buttons that open up a modal e.g. collections, user and ushahidi support links etc. After tabbing through the mode-bar and clicking on any of the 3 links mentioned and the modal opens up, the tab key doesn't continue with the content/elements in the modal. Instead, you will see through the transparent background that the tab key continues it's operation like the modal never popped up. Keyboard input users can therefore not access it's content. Screen shot of the affected modals on click with enter key from the mode bar.

![trapping-focus3](https://user-images.githubusercontent.com/45185388/96670803-228f7500-1315-11eb-8dba-b7ba4141a677.PNG)
![trapping-focus1](https://user-images.githubusercontent.com/45185388/96670801-1f948480-1315-11eb-85d4-1d59d611f14b.PNG)
![trapping-focus2](https://user-images.githubusercontent.com/45185388/96670802-215e4800-1315-11eb-984c-a83fa300f05c.PNG)

**Steps to reproduce behaviour:**

- Login in to your account
- Use tab key to navigate the modebar till you get to collections (try for user and ushahidi support links too later).
- Press enter key to open up modal
- continue navigating with tab key

**Extra note:**
- The screenshots above shows portions of portion of the site where I'm currently working on tabkey/keybord input issues since that is where I discovered them from, **_but this pretty much happens wherever a modal pops up on the entire site._**

Aha! Link: https://ushahiditeam.aha.io/features/PROD-880

**Comment by Ifycode** [comment]
@Angamanga @rowasc I found this issue which is more like a continuation for the modebar issue. Please can you take a look at it? #4095 has to be completed first to see this one... I also dropped a comment in the changes I was asked to make in that pull request. Please let me know your thoughts.

**Comment by Angamanga** [comment]
@Ifycode This kind of issues are exactly what we want to work on during the internship-period. Thank you for filing it!

**Comment by Ifycode** [comment]
😊 ok @angamanga.
