### ISSUE TITLE
Add visually-hidden class to Pattern library to make visually hidden content accessible to screen reader users

### ISSUE THREAD

**Issue by siggrid** [ushahidi/platform#4133]
**Which user group(s) are the primary audience for this feature/enhancement.**

People who use screen reader to interact with platform

**Is your feature request related to a problem? Please describe.**

When image(non-text) buttons are used, we need to make sure that button’s purpose is clear to screen reader users. 
In the platform `<span class=”hidden”>Button text</span>` provides an explanation about what the button does.
However, when navigating through the page with a screen reader, button is announced without any additional text.
Current css-class `hidden` completely hides the element with a description and makes that information inaccessible to any user.

For example, button that adds a new post.

<img width="350" alt="button current description" src="https://user-images.githubusercontent.com/52042098/96758275-3dc6b700-13df-11eb-8abc-45343ce493eb.png">

**Describe the solution you'd like**

Add `visually-hidden` class to _helpers.scss file in Pattern library. Apply `visually-hidden` class instead of `hidden` to an element, that describes button purpose.

<img width="350" alt="Screenshot 2020-10-21 at 20 24 04" src="https://user-images.githubusercontent.com/52042098/96758987-1f14f000-13e0-11eb-9a4c-670821457edd.png">

**HTML template**
```
<button class="button">
  <svg class="iconic">
  </svg>
  <span class="visually-hidden">Button text</span>
</button>
```

**Further improvements**: provide more specific description (e.g. "Add post" instead of "Add")

**Describe alternatives you've considered**

Add attribute aria-label with a description  to `<button>` element

**HTML template**
```
<button class="button" aria-label="Button text">
  <svg class="iconic">
  </svg>
</button>
```

**Comment by siggrid** [comment]
@Angamanga @rowasc Please have a look at the suggestions above. This may be divided into individual issues(adding css-class, replacing css-class, providing meaningful description) when approved.

**Comment by amycruz97** [comment]
can i work on this

**Comment by siggrid** [comment]
> can i work on this

Hey @amycruz97  You may need to hold back till mentors approve this issue as valid and assign you, because I don’t have permission to do that.

**Comment by Angamanga** [comment]
@siggrid Thank you for filing this! I think this issue can be divided into two different issues, or even more if it turns out it needs changes on many places (one issue for the pattern-library and then 1 or more to use the class in the platform-client + make sure the content actually makes sense)

**Comment by siggrid** [comment]
Hi @Angamanga 
Submitted a PR to the Pattern Library. Added a new helper class “visually-hidden”. 
Then checked the codebase templates - there are approximately 40 html files in Platform client, where “hidden” class is used for hiding text content.

**Comment by tuxpiper** [comment]
@all-contributors please add @siggrid for code
