### ISSUE TITLE
Filter modal footer has an absolute positioning 

### ISSUE THREAD

**Issue by onyeepeace** [ushahidi/platform#4137]
**Feature description**
The way the filter modal footer is positioned looks confusing as it sits on top of other elements when selecting filter options for search result. It will be better if the footer stays at the bottom of the filter options so it is easier for a user to understand that they have gotten to the end of the filter options.

**Actual behaviour**
Filter modal footer has an absolute positioning that makes it stay on top of other elements will selecting filters for search result.

**Steps to reproduce the behaviour/error**
Go to the Ushahidi platform client, click on filters and scroll down. You will see something like this

![ezgif com-gif-maker](https://user-images.githubusercontent.com/53520853/97308494-367d2e80-1861-11eb-9854-0a511ee47639.gif)

**Describe the solution you'd like**
The filter modal footer should have a relative positioning so it stays at the bottom of the filter options.
Below is what it will look like after making the changes.

![Posts-Ushahidi-WriteSpeakCode201](https://user-images.githubusercontent.com/53520853/97309672-9f18db00-1862-11eb-976f-b9c1a159356c.gif)

The proposed changes will also relate to issue #1994 which I have already made a pull request to.

**Comment by onyeepeace** [comment]
@rowasc @Angamanga Let me know what you think of this change. I could make the changes after your feedback. Thanks.

**Comment by Angamanga** [comment]
@onyeepeace It sounds like a useful and good change! I know its in the last minute for the Outreachy deadline but if you have time, please go ahead 👍

**Comment by onyeepeace** [comment]
@Angamanga Thank you. I will work on it right away.

**Comment by onyeepeace** [comment]
@Angamanga @rowasc The changes have been made. I hope you can review soon. Thanks.
