### ISSUE TITLE
Inclusion of the Author's name in an exported CSV file

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4152]
**Which user group(s) are the primary audience for this feature/enhancement.**
Include deployment names if possible
eirusa.ushahidi.io

**Is your feature request related to a problem? Please describe.**
When you export the data via a CSV file, the names of the people who submitted the posts are not indicated in the exported file. 

**Describe the solution you'd like**
Inclusion of the authors' names in the exported CSV file but due to the sensitivity of that information, it should only be possible for roles that have permission to do so.

**Comment by CeciliaHinga** [comment]
@rowasc Is the request clear enough?

**Comment by bkplaravel2018** [comment]
Please guide me, what is the process of this issue ?
