### ISSUE TITLE
The map is located in the bottom of posts

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4161]
**Describe the bug**
When adding a post with location, the map is located in the bottom of the post-detail in data-view, no matter what priority it has. When creating/editing the post, the position is correct.

**Where was the bug observed**
In develop and production. Not on the v5 branch

**To Reproduce**
1. Create a post with a location field and other fields below it
2. Go to data-view and look at the post, the map is displayed in the bottom of the post
3. Click on edit
4. The map is in its correct position

**Expected behavior**
The map should be in its correct position when looking at a post.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-904

**Comment by Sunairaa** [comment]
Hey @Angamanga can I work on this issue?

**Comment by himil-vasava** [comment]
Hi @Angamanga , can I work on this issue?
I have already found the code which is creating this situation.
https://github.com/ushahidi/platform-client/blob/b1937f2268a2662e83cd60a6f05d452d687ebd7e/app/main/posts/detail/post-detail-data.html#L37-L54

**Comment by Angamanga** [comment]
Hi @himil-vasava! Thank you for your interest in contributing! Give me a few days to update our docs and instructions, we have had some changes to our branches and this might be fixed.

**Comment by himil-vasava** [comment]
Okay, @Angamanga could you please point me to some other issues on which I could work on?
