### ISSUE TITLE
Unable to select dates on Date Picker in Sort & Filter page. 

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4169]
**Describe the bug**
Selecting a date on Date picker modal under Date Range field in Sort & Filter modal won't work. This seems to be broken in three ways:
1. On selecting a date, the date picker modal persists and does not get auto-dismissed.
2. Once a date has been clicked on to be selected, clicking outside the modal has the calendar jumping around.
3. Even when the date picker is dismissed, the dates shown as selected are wrong and are not the dates that were selected.

**Where was the bug observed**
Develop and Prod

**To Reproduce**
1. Go to a data page.
2. Click on Sort & Filter
3. Scroll down to Date Range field.
4. Click on Start Date field. Date Picker is launched.
**this is where the weirdness starts**
**Issue 1:** On clicking on the Start Date field to launch the date picker, both Start Date field and End Date field can be seen to be populated with the day's date. End Date field should remain blank until it is clicked on.
6. Select a date.
**Issue 2:** Selected date is only highlighted momentarily. The day's date which is selected by default when the date picker is launched then stays highlighted.
**Issue 3:** Date Picker should be dismissed on date being clicked on. It persists.
7. Click on your selected date again. Now it will stay highlighted.
8. Click outside date picker a few times to dismiss it.
9. Click on Sort&Filter dropdown and scroll down to Date Range field.
**Issue 4:** Both Start date and End date fields have a value which is the same date selected for Start date field. Only Start date field should have a value which we selected. End Date field should not have a value.

**Expected behavior**
Issue 1:
End date field should remain blank until it is directly and intentionally interacted with.
Issue 2:
Selected date should stay highlighted.
Issue 3:
Date picker should be auto-dismissed once a date has been selected.
Issue 4:
End Date field should always not have a value, unless a value is directly and intentionally selected.

**Is there a workaround? What is it.**
Clicking outside the date picker modal a few times dismisses it.

**Link to recorded issue**
https://www.loom.com/share/13af7b55bac1423aa0039f40e48b625f

**URL / Environment where this happened**
https://walterqa.ushahidi.io/views/data

**Desktop Hardware Details (please complete the following information):**
 - OS: Mac Os Version 10.15.7
 - Browser: Chrome
 - Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by Angamanga** [comment]
@rowasc @Obadha2 Can this be closed now?

**Comment by tuxpiper** [comment]
Since we are releasing the fix, assuming we are good here
