### ISSUE TITLE
Success email header incorrectly justified

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#4170]
The link address and Ushahidi are not centered correctly on the success email http://mustang.robbiemackay.com/assets/html/5_layouts/email-deployment-new.html
<img width="1272" alt="screen shot 2016-05-06 at 11 12 32 am" src="https://cloud.githubusercontent.com/assets/1618793/15082229/8135691e-137b-11e6-854f-39b452ac25e6.png">

**Comment by tuxpiper** [comment]
@all-contributors please add @Firenz for code
