### ISSUE TITLE
List of issues found in v5-main

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4177]
- [x] Field name edit-text fields are missing.
<img width="386" alt="Screen Shot 2020-12-02 at 2 15 52 PM" src="https://user-images.githubusercontent.com/38259840/100990684-390b2c00-3563-11eb-967c-ab959bb7767e.png">

 - [x] Share and Submit button should be at the bottom of the survey being filled as well as the top of the page. Only present at the top of the page.

 - [x] Post on card, the time submitted is seen as 3 hours ago. It should match the time on the preview pane on the left.
<img width="1063" alt="Screen Shot 2020-12-02 at 8 01 24 PM" src="https://user-images.githubusercontent.com/38259840/100990726-41636700-3563-11eb-9ba2-3118ffcf86d8.png">

- [x] If a decimal value is provided in an integer field, user can submit response successfully. User should be alerted of incorrect format and submission should fail. Submitted post has the decimal value missing, there's no value.

- [x] Radio and checkbox options can have duplicate values in Translated languages.

- [x] Clicking on a post from twitter doesn't open the list on the details column on the right to show more information.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-911

**Comment by Angamanga** [comment]
@Obadha2 I have just merged the fix for the edit-field so it can be tested in a bit when its deployed.

**Comment by rowasc** [comment]
@Obadha2  > If a decimal value is provided in an integer field, user can submit response successfully. User should be alerted of incorrect format and submission should fail. Submitted post has the decimal value missing, there's no value.
Should be fixed now. Thank you !

**Comment by rowasc** [comment]
@Obadha2 I just pushed something that should help with the duplicates issue, but it's a bit rough around the edges. Would really appreciate feedback on how usable it turned out from your POV (I mean, besides "does it work :D " )

**Comment by Obadha2** [comment]
> @Obadha2 I just pushed something that should help with the duplicates issue, but it's a bit rough around the edges. Would really appreciate feedback on how usable it turned out from your POV (I mean, besides "does it work :D " )

Hmm. well it does work. An enhancement would be having duplicate fields highlighted, but this works! Marking as resolved.

**Comment by Obadha2** [comment]
Closing this as there are no known pending issues on v5.
