### ISSUE TITLE
Add E2E tests to Github actions

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4178]
**Description**
As we start adding E2E tests for the Platform Client, we want to run the tests when pushing to the Platform Client repository. Right now, the tests lives in their own repository (https://github.com/ushahidi/experimental-e2e-testing). We need to:
1. Create a folder structure for the E2E-tests and clean up existing repository 
2. Write or copy a script for github actions to import the repository and run the test
3. Initiate an instance of the platform-api and client so the tests have somewhere to run
4. Figure out if/what data we want to seed the database with in order to run the tests properly
5. Figure out a process for how to change the seed-data if needed

**Comment by tuxpiper** [comment]
Done :+1:
