### ISSUE TITLE
2.4.3 Focus order and 3.2.3 Consistent Navigation

### ISSUE THREAD

**Issue by renujain31** [ushahidi/platform#4184]
When users tab through surveys and forms, the content should appear in a logical order.

Also, keep the navigation menu placement and order consistent throughout the platform. To ensure this, header and footer menus should stay consistent. Consistency involves placement and order of links, search bars, and skip navigation links

Related issues: #4138 #4150

**Comment by Angamanga** [comment]
Todo: Go through what parts still needs work, then specify that in this issue

**Comment by tuxpiper** [comment]
@Angamanga as far as I understand from the last comment, this is not fully closed. Let me know if I'm wrong.
