### ISSUE TITLE
Sections in "Saved searches" modal and "Collections" modal are not reached via tabbing

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4193]
**Describe the bug**
"Who can see this?",~~ "Featured" and "Default viewing mode"~~ is not reached from tabbing in Saved searches modal and Collections modal.

**To Reproduce**
1. Go to collections or saved-searches modal (you need to click your way here right now)
2. Tab in the window
3. "Who can see this?", ~~"Featured" and "Default viewing mode"~~ is not reached

**Expected behavior**
The sections should receive focus when tabbing

**Is there a workaround? What is it.**
Not via tabbing, but it works when clicking

**Screenshots**
<img width="615" alt="Screenshot 2021-01-21 at 19 10 22" src="https://user-images.githubusercontent.com/8624777/105393196-5af86500-5c1c-11eb-9da9-a038484c7334.png">

**Comment by Angamanga** [comment]
"Who can see this"- section remains to fix.

**Comment by Angamanga** [comment]
@emmanuelhashy Assigning you to this issue!

**Comment by emmanuelhashy** [comment]
Hi @Angamanga, I'd like to work on this issue. Assign it to me.
