### ISSUE TITLE
The order of fields on the survey editor page is different from the order of fields on the survey submission page

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4197]
**Describe the bug**
Once you add fields to a survey and save it, the fields on the survey editor page confusingly rearrange themselves in a different order from the initial one you had saved them in when you click on the same survey to edit. But the initial order will be observed in the survey form on the 'add post' submission page. [See steps to reproduce for better explanation]

**Where was the bug observed**
Production

**To Reproduce**
1. . Go to a survey and add a specific order of fields.
2. save
3. Go to '+' on map view.
4. Click on the survey you added fields, you will find the order of fields are in the correct position you created and saved them.
4.  Go back to the same survey on the editor page, the surveys are in a different order.
5. save
6. Go to the "add a post" submission page, the fields are still in the order they were initially created in.

**Expected behavior**
The positioning of the fields on the survey editor page should not automatically rearrange themselves if not manually done so.
 

**Screenshots**
Survey Editor Page
<img width="1026" alt="Surveys_-_test254" src="https://user-images.githubusercontent.com/20906968/105862386-c7021100-6000-11eb-8cc4-8999d06612fa.png">
Create Post submission page
<img width="505" alt="Create_Post_-_test254" src="https://user-images.githubusercontent.com/20906968/105862542-f153ce80-6000-11eb-8ce0-2ea9d556b687.png">

**Desktop Hardware Details (please complete the following information):**
 - OS
 - Browser: chrome

**Additional context**
It makes editing a survey form confusing

**Comment by Angamanga** [comment]
This should be fixed by https://github.com/ushahidi/platform-client/pull/1652
