### ISSUE TITLE
ISOOKO - Issues arising from BRCK Devices and platform integration.

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#4208]
**Device OF52 & E11F**
1. Random automatic redirection to facebook groups at the end of the video doesn't happen.
   **Expected Behavior:** At the end of the video, user should be redirected to either one of two facebook groups randomly.
   **Actual Behavior:** At the end of video, no redirection happens. Nothing happens.
- [x] Resolved

2. More than needed tiles on homepage.
    **Actual Behavior:** The homepage has 4 tiles with videos. Three of the tiles have the title "Inspiring for Change" and one labeled "How to Join Online......" 
    **Expected Behavior:** The homepage should have only needed tiles. Remove two of the "Inspiring for Change" tiles so that there's only two left, one named "Inspiring for Change" and the other named "How to Join Online...."
- [x] Resolved

3. Smartphone connects directly to internet without opening browser for signing in.
**Expected Behavior:** On connecting to the MOJA network, user should be prompted to sign in to connect to internet and browser should launch and user directed to Moja's homepage. From here they will view the videos and access the surveys.
**Actual Behavior:** Smartphone connects directly to internet. To access content user will have to enter URL into browser.
- [ ] Resolved

**Comment by tuxpiper** [comment]
@Obadha2  Can we close it?
