### ISSUE TITLE
Required Integer field won't accept 0(zero) as a value.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4210]
**Describe the bug**
On a survey, integer field that is set as a required field won't accept zero as a value. Attempts to save if a required integer field has the value zero fail.

**Where was the bug observed**
Prod environment

**To Reproduce**
1. Go to a survey that has an integer field that is a required field in submission mode.
2. Fill in all other required fields.
3. Provide the value 0 on the required integer field.
4. Click Submit to save this response 
5. Submission fails with error message (See attached screenshot)

**Screenshots**
<img width="1308" alt="Screen Shot 2021-02-23 at 12 46 58 PM" src="https://user-images.githubusercontent.com/38259840/108826823-e37c7380-75d5-11eb-97a4-f72730e04bf3.png">

**Expected behavior**
Post submission should be successfully with zero as a valid value.

**Is there a workaround? What is it.**
Have the integer as an unrequired value.

**Desktop Hardware Details (please complete the following information):**
 - OS: MacOs
 - Browser Chrome 
 - Version 88.0.4324.182 (Official Build) (x86_64)

**Comment by tuxpiper** [comment]
Fixed by #4209
