### ISSUE TITLE
Survey Photos viewable on social media Link Shares

### ISSUE THREAD

**Issue by Disasterpetrescue** [ushahidi/platform#4216]
Greetings,
Using this program in conjunction with social media it is helpful if a photo appears when a Ushahidi link is shared to Facebook. Currently I share the link to a survey response containing information and my audience feels it is potential spam due to not being familiar with ushahidi brand name. 

I am broadcasting to my home country the USA and my audience would be more inclined to click the links if they had a photo viewable before clicking. I collect information on missing and found animals in disasters as well as other information. If a link to a specific missing cat were shared to Facebook, it is best if a photo within that survey response were to populate with that shared link. 

When there is no photo in the survey response, then a photo of the map would be ideal. I can provide visual examples if needed or interested for further understanding. Thank you for always doing a beautiful job on this program. I can see its full potential and after getting everything just right, I am hopeful to finally do a full build and launch this year. 

I look forward to continuing assisting with this remarkable open source program. 

Regards,

Desiree McAlear
Disaster Pet Rescue Animals in Disasters Inc 
Federal 501c3 
USA

https://disasterpetrescue.ushahidi.io/views/map

**Comment by evanessa234** [comment]
Hi @Angamanga can I work on this?

**Comment by Angamanga** [comment]
Hi @evanessa234! Please start with the tasks in https://github.com/ushahidi/platform/discussions/4213 before starting to work on an issue 🎉

**Comment by evanessa234** [comment]
Hey @Angamanga! I have completes all the tasks mentioned in #4213. Can I be assigned this issue now please?

**Comment by Angamanga** [comment]
@evanessa234 Absolutely! Please go ahead!

**Comment by evanessa234** [comment]
hi @Angamanga, I was assigned issue 3 days back. As per guidelines in #4213, we are asked to submit PR within 3 days even if the solution isn't completed. As this was my first contribution for this project I was familiarizing myself with the codebase and hence sorry for the delay. Shall I make a PR despite the solution not complete?

**Comment by Angamanga** [comment]
@evanessa234 That is fine, no problem :)
