### ISSUE TITLE
Unable to submit or edit posts on mobile saved offline with wrong location data.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4220]
**Describe the bug**
A user can submit a response to a survey while offline and it is saved successfully, but this saved response cannot be submitted when the user goes online.

**Where was the bug observed**
Prod - https://yetuinitiative.ushahidi.io/views/map 

**To Reproduce**
1. While offline, and with SIM card removed (so that location services are unavailable ) launch the Ushahidi mobile application.
2. Open a survey that has a required location field.
3. Note that the location field will present fields that the user can type into. 
![Screenshot_20210308-183023](https://user-images.githubusercontent.com/38259840/110342924-00d12900-803d-11eb-93f3-853dc867bab9.jpg)
4. Fill in Street and City fields by typing values into these fields.
5. Submit this response. It will be saved successfully.
6. Go online.
7. Click View Responses to open Responses.
8. Response that was submitted while offline will be in Pending status. 
9. Swipe down on page to initiate submitting process.
10. Submission fails with error message "Problem posting response." (See screenshot)

**Expected behavior**
- A saved response should be openable for editing.
- It should be possible to submit responses that were saved while offline.

**Is there a workaround? What is it.**
None. If a submission has been made with manually filled in location info, then this submission can't be submitted, neither can it be edited to be corrected. It has to be deleted.

**Screenshots**
![Screenshot_20210308-180538](https://user-images.githubusercontent.com/38259840/110344228-5528d880-803e-11eb-83e7-a69e0026baa5.jpg)

**Smartphone Hardware Details (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android 10
- Ushahidi Android Application
 - Version: 1.13

**Comment by Angamanga** [comment]
Just found a related issue here: https://github.com/ushahidi/platform/issues/4186

**Comment by tuxpiper** [comment]
To be fixed by https://github.com/ushahidi/platform-mobile-app/pull/6  (on mobile release 1.14)

**Comment by Angamanga** [comment]
@tuxpiper Wasn't this fixed? Can I close it?

**Comment by tuxpiper** [comment]
Yes, actually it is. Let's close it, thank you 🙏
