### ISSUE TITLE
Field Descriptions are not rendered correctly on mobile.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4224]
**Describe the bug**
Fields that have descriptions, the descriptions are shown together with html tags. 

**Where was the bug observed**
https://isooko.ushahidi.io/views/map
mojawifi.com/moja-survey/?survey=28&host=isooko

Also seen on this survey when it is viewed on a mobile device - https://disasterpetrescue.ushahidi.io/views/map

**To Reproduce**
1. Go to  mojawifi.com/moja-survey/?survey=28&host=isooko - this is how the survey is rendered on the MOJA network.
2. Note the html tags together with the field's description.

**Expected behavior**
Field descriptions should be shown correctly, without html tags visible.

**Is there a workaround? What is it.**
None.

**Screenshots**
![image](https://user-images.githubusercontent.com/38259840/111311865-c2a4bc80-866f-11eb-8ff1-8e4146240c2e.png)

**Desktop Hardware Details (please complete the following information):**
 - BRCK Device
 - MOJA Network

**Comment by Angamanga** [comment]
Fixed for ISOOKO but remains on mobile-app

**Comment by Obadha2** [comment]
Fixed. 
Passes QA. 👍
