### ISSUE TITLE
Title and Description fields are provided as EditView Fields rather than TextView Fields on mobile.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4225]
**Describe the bug**
The title and description fields have text fields that can be editable when viewed on the MOJA network. This should not be the case, the fields should only be viewable as text fields.

**Where was the bug observed**
https://isooko.ushahidi.io/views/map

**To Reproduce**
1. Go to a survey on the ISOOKO deployment on the MOJA network.
2. The Title and Description fields should not be rendered as editText fields but only as viewText Fields.
3. Note that they have textfields that can be edited.

**Expected behavior**
Title and Description fields should only be viewable as viewText and not editText fields as seen in screenshot. 
![Screenshot_20210316-135030](https://user-images.githubusercontent.com/38259840/111317628-62187e00-8675-11eb-8fa0-62234cc36e6e.jpg)

**Is there a workaround? What is it.**
None.

**Screenshots**
Actual behavior
![Screenshot_20210316-135547](https://user-images.githubusercontent.com/38259840/111317792-870cf100-8675-11eb-9dbb-e007ffe44ad4.jpg)

**Comment by Angamanga** [comment]
Fixed, closing
