### ISSUE TITLE
Default value translations shouldn’t be offered for integer, decimal, datetime types

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4228]
**Describe the bug**
In the translation-editor for integer, decimal, datetime/date, a field for default value translations is visible. It should not be since its not something we translate.

**To Reproduce**
As logged in admin:
1. Go to Settings->Surveys->Create a new survey
2. Add a new integer, decimal or datetime/date field
3. Add a default value for the field
4. Add a new language
5. Go to the translation-editor and click on the new field
6. There is a field for translating the default value.
<img width="455" alt="Screenshot 2021-03-25 at 09 06 18" src="https://user-images.githubusercontent.com/8624777/112439427-5ef25180-8d49-11eb-87e2-b872bb07fda2.png">

**Hints 💡 **
- The code that shows the default-field is found here: https://github.com/ushahidi/platform-client/blob/develop/app/settings/surveys/field-translation-editor.html#L51
- We only want to show the default-field when "field.type" or "field.input" is "text"

**Comment by Ingi-Hong** [comment]
Hi Anna, 

I'm a first timer and would love to tackle this. I'm a bit confused about the issue though - from my understanding the entire box and "Default value (optional):" part should not be visible?

**Comment by sunny775** [comment]
Hi @Angamanga  👋🏻 I am an Outreachy applicant, and I'd love to take on this issue. Can you assing me please
