### ISSUE TITLE
Newly created surveys is not visible in the import list

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4231]
**Describe the bug**
When I create a survey and then go to import posts in settings->import, my new survey is not visible in the list of surveys to select.

**To Reproduce**
As logged in
1. Go to settings->surveys
2. Create a new survey
3. Save and go to settings->import
4. Click on the "Import to survey"-dropdown
5. The new survey is not in the list
6. 
**Expected behavior**
The survey should be in the list.

**Hints 💡 💡 **

- The code that belongs to the import-feature is found in this folder: https://github.com/ushahidi/platform-client/tree/develop/app/settings/data-import
- For your awareness: "Surveys" are called "Forms" in this directive.
- There are different methods to fetch the forms from the backend. The form-endpoint service, where you can see the different methods, is found here:  https://github.com/ushahidi/platform-client/blob/develop/app/common/services/endpoints/form.js

**Comment by holladayian** [comment]
I would like to take this one!

**Comment by Angamanga** [comment]
Hi @holladayian! The application-period starts at 4pm UTC today. Please follow the instructions in this discussion to get started before selecting an issue: https://github.com/ushahidi/platform/discussions/4213

**Comment by emmanuelhashy** [comment]
Hi @angamanga, I have fulfiled all the pre-requisite for selecting issue #4213. Also, I have found my way around this and I would like to work on this issue. Can you assign it to me?

**Comment by emmanuelhashy** [comment]
Hi @Angamanga, I have fulfilled all the prerequisite for contributing to this project. I'd like to work on this issue. Assign it to me, please!

**Comment by Angamanga** [comment]
@emmanuelhashy This is a first-timers-only issue with many hints to introduce someone to the code; since you already have shown you find your way around the code-base, could you find another issue to work on? You also mentioned you found bugs you would like to add as new issues, if you would like to do that, it would be a great contribution! Thank you 👍

**Comment by emmanuelhashy** [comment]
Alright, Anna. I will do that right away. Also, you are yet to review my
first PR
https://github.com/ushahidi/platform-client/pull/1659#partial-pull-merging.
Hope to hear from you soon.

**Comment by Angamanga** [comment]
@emmanuelhashy I have reviewed the PR 👍

**Comment by emmanuelhashy** [comment]
@angamanga I have seen the review. Thanks

**Comment by ghulamghousdev** [comment]
@Angamanga  I would like to work on this bug. Can you assign it to me?

**Comment by Angamanga** [comment]
@ghulamghousdev Thank you for your interest in contributing! This issue is intended for applicants for Outreachy and GSoC, are you an applicant? If so, you need to follow the steps here before you start working on an issue:https://github.com/ushahidi/platform/discussions/4213

**Comment by ghulamghousdev** [comment]
@Angamanga I have completed the steps. Yes, I'm an Outreachy and GSoC applicant.

**Comment by Angamanga** [comment]
@ghulamghousdev Excellent! Please go ahead with this issue!

**Comment by Angamanga** [comment]
@ghulamghousdev How are you getting on? Let me know if you need any guidance!

**Comment by ghulamghousdev** [comment]
Hey @Angamanga,
I couldn't able to submit the proposal. So that is why you can assign this issue to someone else. Sorry

**Comment by Angamanga** [comment]
@ghulamghousdev Ok, thanks for letting me know!

**Comment by emmanuelhashy** [comment]
Hi @Angamanga can you assign this issue to me since no one is working on it?

**Comment by Angamanga** [comment]
@emmanuelhashy yes, absolutely! Please go ahead!

**Comment by emmanuelhashy** [comment]
@Angamanga  Alright!
