### ISSUE TITLE
When selecting a parent category, the current category that is being edited should not be on the list of parent category selections.

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4233]
**Describe the bug**
When editing a category, the current category should not be in the list of possible parent categories.

https://user-images.githubusercontent.com/8624777/112445596-99f78380-8d4f-11eb-9c4f-40d95e4b07b7.mov

**To Reproduce**
As logged in admin
1. Go to settings->categories
2. Select a category that's not a parent already
3.Click on the dropdown "This category is child to nothing"
![Uploading Screenshot 2021-03-25 at 09.52.36.png…]()
4. See the category that is being edited as one of the options.

**Expected behavior**
The category that is being edited should not be in the list of possible parents.

**Comment by helen-ndip** [comment]
Hi @Angamanga  can I work on this?

**Comment by Angamanga** [comment]
@helen-ndip Please finish the PR you are working with before moving on to next. I have made a comment on the PR this morning (so sorry for keeping you waiting, I thought I had commented on Friday).
