### ISSUE TITLE
Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform#4236]
**Describe the issue**
According to report generated from lighthouse for ushahidi deployment, text does not remain visible during web font load which is one of the reasons for lag in performance.

**Task**
Ensure that text remains visible during webfont load.
Resource: [web.dev's font display article](https://web.dev/font-display/)

**Steps to reproduce**
* Open up localhost:3000/views/map to see text appearance whenever page loads.
* More at [web.dev's avoid invisible text article](https://web.dev/avoid-invisible-text/)

**Comment by max-keviv** [comment]
@Ifycode can you please give steps for the production of the mention issue

**Comment by Ifycode** [comment]
@max-keviv I have added it now. Although, just incase it's still not so noticeable, I added link to an article that will help better explain the issue.
