### ISSUE TITLE
Issues Arising from Donations Feature - Grant4TheWeb

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4240]
All issues and minor suggested adjustments on Donations Feature.
**1.** Links on the settings page don't lead anywhere. Nothing happens on clicking them.
 - On Donations page, there are a few links that don't open any pages when clicked on.
 - [x] `Uphold.com` link
 - [x] `here` link
 - On Donations modal
 - [x] `How can I donate` link
 - [x] Fixed

**2.** Required fields on Settings page are not marked as such.
Expected Behaviour
- All fields that are required fields should be indicated as requried.
- [x] Fixed

**3.** Save happens when required fields are missing.
Expected Behaviour
- Save should not happen successfully when a required field has not been given a value.
- [x] Fixed

**4.** Changes made on Donation Title and Donation Description fields on settings don't reflect on Donate modal.
Expected Behaviour
- Any changes made on Donation Title and Donation Description Fields should persist when saved.
- [x] Fixed

**5.** Placeholder value in Wallet Field can be a bit confusing when user Deletes Wallet.
Expected Behaviour
- A more descriptive placeholder value that doesn't make it look like there's a valid value that has been provided in the field.
- [x] Fixed

**Comment by tuxpiper** [comment]
Looks like this may be closed. Pinging @Obadha2 for confirmation
