### ISSUE TITLE
Default values no longer working in 7 fields - survey

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform#4245]
**Describe the bug**

A. Default values which used to show when creating new survey posts now no longer work. These 6 fields are affected: 
* Short Text
* Long Text
* Select
* Radio Buttons
* Check Boxes
* Mark Down

B. Embed video: Before, default value for embed video field used to show only if the correct value is entered - this was [the previous bug](https://github.com/ushahidi/platform/issues/4044#issuecomment-710407684). Now, it doesn't work at all too.

**Where was the bug observed**

localhost:3000/settings/surveys/create

**Steps to reproduce the behavior**
* Login and go to settings > surveys and click on `New survey` button.
* Scroll towards the bottom of the page and click on the `Add field` button.
* Click on any of the fields mentioned above, a modal will pop open.
* Scroll towards the bottom of the modal to find [the input field for default value](https://github.com/ushahidi/platform/issues/4044#issuecomment-708239637).
* Type into the input field and click on `add & close` to close modal.
* Click save, click on the `add to survey` popup at the bottom of the page and click on submit. 

**Screenshots**

Screenshots below show example of how the input fields don't get populated with the default value typed in earlier. Nothing also appears in the post created after submitting.

![u-2](https://user-images.githubusercontent.com/45185388/115619094-64609e80-a2eb-11eb-8b6d-cb9bd845527b.PNG)

![u-3](https://user-images.githubusercontent.com/45185388/115619100-662a6200-a2eb-11eb-844f-c3f3438a4700.PNG)

**Expected behavior**

The behaviour should be the same as before i.e. default values entered by user should show up in post created.

**Additional context**
* [Previous bug comment](https://github.com/ushahidi/platform/issues/4044#issuecomment-710407684)
* [New bug report update/comment](https://github.com/ushahidi/platform/issues/4044#issuecomment-822915377).

**Comment by Ifycode** [comment]
Hi @Angamanga can I go ahead with trying this out, to see why they no more work?

**Comment by Angamanga** [comment]
@Ifycode Please go ahead :)

**Comment by Ifycode** [comment]
Alright. Thank you.

**Comment by Angamanga** [comment]
@Saumay1 Assigning this to you

**Comment by andrew21-mch** [comment]
hi @Saumay1, are you still working on this

**Comment by Saumay1** [comment]
Hi @andrew21-mch, I couldn't work on this, if you would like to work on this then please continue.

**Comment by andrew21-mch** [comment]
Hi @Angamanga I have tried reading the past discussion but seem not to understand what exactly is expected, I will be grateful if you can throw more light on this issue
