### ISSUE TITLE
Remove/Uninstall Listed Unused Dependencies:

### ISSUE THREAD

**Issue by evanessa234** [ushahidi/platform#4247]
**Description:** 
The dependencies value is used to specify any other modules that a given module (represented by the package. json ) requires to work. They are often just forgotten when a dependency is removed for some reason. However, the presence of unused dependencies in a project can cut down the performance of an app significantly. You can unknowingly add tons of unnecessary lines of code, leading to a larger bundle size. Dependencies listed below are unused and hence can be removed.

**How to reproduce?**
- Found in “develop” branch
- Listed using ```npx depcheck``` command
- Verified manually

_**Below is the verified list of unused dependencies in platform-client.**_ 
(these are only present in package.json and nowhere else in the project)

**Unused dependencies**
* moment-timezone
* socket.io-client
 
**Unused devDependencies**
* @uirouter/visualizer
* babel-register
* babel-runtime
* fs-walk
* jasmine-core
* json-loader
* node-fetch
* node-libs-browser
* phantomjs-prebuilt
* raw-loader
* style-loader

**Solution Hint:** npm uninstall \<package-name\>

**Comment by tuxpiper** [comment]
I'm pretty sure this was released :)
