### ISSUE TITLE
Change how upload and deletion of images to Surveys.

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#4249]
**Which user group(s) are the primary audience for this feature/enhancement.**
Respondents uploading content to surveys with images.

**Is your feature request related to a problem? Please describe.**
As currently is, where a survey has an image field, uploading of images happens right after a user selects the image from the file picker.
Also, an image is deleted once a user clicks on the Delete button on an uploaded image. This can be a problem especially in edit mode where a user clicks the Delete image and an image is removed, then the user wants to cancel the deletion. At this point if a user clicks Cancel to dismiss any changes to the survey response, they will be unable to recover the deleted image.

**Describe the solution you'd like**
Image actions (upload, delete) should come into effect once the user confirms either cancelling or saving their changes on the survey.

**Comment by tawandamoyo** [comment]
Hi, can I work on this?

**Comment by yuktea** [comment]
I would like to work on this please

**Comment by Saumay1** [comment]
Hi @Angamanga!
May I work on this?

**Comment by Angamanga** [comment]
@Saumay1 I assigned you to this one: https://github.com/ushahidi/platform/issues/4245, do you rather work on this one instead?

**Comment by andrew21-mch** [comment]
Hi @Angamanga noticed this has not been asigned yet
can i work on it

here is a link to the update i have some far

**Comment by andrew21-mch** [comment]
Thanks @Angamanga, here is a link to what i have so far, it might not be as good but I will be happy to receive corrections 😄 
https://github.com/ushahidi/platform-client/pull/1782
