### ISSUE TITLE
Wrong documentation link on Ushahidi's Doc support Page in a deployment

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4253]
**Describe the bug**
The link on the Ushahidi Doc support module redirects you to our website support section to access the documentation.

**Where was the bug observed**
ushahidi.io

**To Reproduce**
1. Click on the Ushahidi logo to access all the Ushahidi support links
2. Click on Documentation
3. You will be redirected to https://www.ushahidi.com/support

**Expected behavior**
You should be redirected to https://docs.ushahidi.com/ushahidi-platform-user-manual/

**Comment by andrew21-mch** [comment]
Hi @CeciliaHinga , will you mind if I find out how to fix this?

**Comment by andrew21-mch** [comment]
Hi @Angamanga and @CeciliaHinga , i think this pull request fixes the issue https://github.com/ushahidi/platform-client/pull/1776

**Comment by Angamanga** [comment]
@andrew21-mch Thank you for your contribution. I will review this one, could you also please follow the instructions here and add screenshots of your setup: https://github.com/ushahidi/platform/discussions/4213? Thank you.
