### ISSUE TITLE
Bug in Adding Translation Feature?

### ISSUE THREAD

**Issue by hcmakilan** [ushahidi/platform#4254]
I have been trying to insert translations of the survey we posted in our project, but it seems there's a bug in the feature because every time I save the translation, it just remains on "saving" the changes.
![image](https://user-images.githubusercontent.com/77382640/117758683-0e7d7780-b255-11eb-8f19-6415c08e1760.png)

Once I refresh, they translation does not appear, it seems like it reset on it's own.

**Comment by tuxpiper** [comment]
Thank you, @hcmakilan! 

https://github.com/ushahidi/platform-client/pull/1669 should have fixed this
