### ISSUE TITLE
SMS are not displayed on the map 

### ISSUE THREAD

**Issue by niang77** [ushahidi/platform#4255]
Hello
I have configured my SMS frontline and the url and APIs are working fine.
But if I send a text message it does not appear on the map.
thank you for helping me

**Comment by CeciliaHinga** [comment]
Hello Niang77, have you set your deployment as private?

**Comment by niang77** [comment]
hello Ceciliahinga
how do we check if it's private or public?

**Comment by niang77** [comment]
ha okay i see 
the deployment is public

**Comment by CeciliaHinga** [comment]
Can we move this conversation to support@ushahidi.com? It will be easier for us to dig deeper into what the issue might be. Thanks
