### ISSUE TITLE
Identify and confirm heavy dependencies present 

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4258]
#### Task
Identify and confirm heavy dependencies present and see if it is that they need to be replaced or just specific modules need to be imported in the code base.

#### Related issues or PR
* https://github.com/ushahidi/platform-client/pull/1676
* #429

**Comment by Ifycode** [comment]
#### Save these resource(s) here: 

* https://tsh.io/blog/reduce-node-modules-for-better-performance/
