### ISSUE TITLE
Posts with certain script types (e.g Gujarati language) display an error when being submitted

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4262]
**Describe the bug**
When one creates a post using the Gujarati or Punjabi language, the post is not successfully created when submitted, displaying an error at the bottom of the screen.

**Where was the bug observed**
Ushahidi.io

**To Reproduce**

1. Go to map/data view
2. Click on add new post (+)
3. Select the survey you want to fill
4. Enter the information required in Gujarati or Punjabi language on the title and description fields
5 Click on submit, see error  "**title fields.title does not match the required format..... slug Slug is required.**" 

**Expected behavior**
The Ushahidi Platform can store any language/script added to the Unicode standard. Meaning, posts with the above languages should be successfully submitted without displaying any error.

**Is there a workaround? What is it?**
I haven't discovered any yet

**Screenshots**
<img width="863" alt="Create_Post_-_test254" src="https://user-images.githubusercontent.com/20906968/120812783-fb10b400-c555-11eb-903c-6bde17934ab1.png">

**Comment by tuxpiper** [comment]
The problem with the slug is addressed now, but the "title fields.title does not match the required format" validation is still failing

**Comment by tuxpiper** [comment]
Maybe this is not a problem with newer versions of Lumen. Should give it a try.
