### ISSUE TITLE
"Disable Monetization" checkbox in deployment settings is confusing

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4278]
As seen in Settings > Donation ...

![Screenshot 2021-06-10 at 14 32 36](https://user-images.githubusercontent.com/467393/121525581-cccd2180-c9f8-11eb-95f6-bfa778988274.png)

the concept of clicking a checkbox to disable something has proven to be not intuitive.

It's also not using the same design language as other similar controls in settings, i.e. in data sources:

![Screenshot 2021-06-10 at 14 34 43](https://user-images.githubusercontent.com/467393/121525861-1f0e4280-c9f9-11eb-91b0-877791bfc4f3.png)

**Comment by Angamanga** [comment]
@tuxpiper @webong We could use a button instead here:
<img width="639" alt="Screenshot 2021-06-24 at 09 36 10" src="https://user-images.githubusercontent.com/8624777/123221866-aa92d380-d4cf-11eb-8f24-7c478553e778.png">

Some questions:
- Should we still store the data about the wallet etc when monetization is disabled?
- Would a info-box saying something like "Monetization is currently disabled" together with a green button where the user can enable it again work for after the user has clicked disabled?

**Comment by tuxpiper** [comment]
Would this button have an "Enable Monetization" counterpart shown when Monetization is disabled?

> Should we still store the data about the wallet etc when monetization is disabled?
Yes, I think we should. It's not private / sensitive data and it's more likely that people will not want to re-write all of it.

> Would a info-box saying something like "Monetization is currently disabled" together with a green button where the user can enable it again work for after the user has clicked disabled?
Ah right, so that was what I wanted to hint with my question :) Yea, in the case of having this button, I think it would be necessary to have the green counterpart. The info box would make good feedback, imho.

Also, adding @CeciliaHinga for her insights.

**Comment by Angamanga** [comment]
@tuxpiper @webong @CeciliaHinga 
I came up with this: 
<img width="619" alt="Screenshot 2021-06-24 at 18 15 59" src="https://user-images.githubusercontent.com/8624777/123297941-5102c700-d518-11eb-9b12-274d51008593.png">
<img width="841" alt="Screenshot 2021-06-24 at 18 16 07" src="https://user-images.githubusercontent.com/8624777/123297922-4c3e1300-d518-11eb-824d-0f3a9812f684.png">

Follow up question. Previously, with a checkbox, we did not save the new setting until clicking "save". With this kind of button, I *think* the user expects the setting to be saved immediately, upon clicking the button. Is everyone ok with that change (saving all settings when clicking "disable/enable monetization"?)

**Comment by Angamanga** [comment]
Another thing: IF we go with saving the settings when clicking the button, what do we want the button to do if the form is invalid? Disable the button? Or make it clickable and add a message after click saying go back and check your input? (I clickable + message)

**Comment by tuxpiper** [comment]
> Another thing: IF we go with saving the settings when clicking the button, what do we want the button to do if the form is invalid? Disable the button? Or make it clickable and add a message after click saying go back and check your input? (I clickable + message)

I agree with clickable + message 👍 let me know if assistance is needed with the validation rules

**Comment by CeciliaHinga** [comment]
I agree,  clickable+message.  Disabling the button does not convey what the issue is
