### ISSUE TITLE
 Translated surveys/posts submitted via USSD cannot be translated into another language on the Ushahidi platform

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4282]
**Describe the bug**
You cannot translate submitted posts via USSD into another language because the default language that they are in is not specified. 

**Where was the bug observed**
ushahidi.io

**To Reproduce**
1. Fill in a translated survey via USSD
2. Submit post
3. Log into your deployment as an admin
4. Edit the newly submitted post via USSD
5. The default language the post is in is missing on the left-hand corner side of the post.
6. Click on "add translation" You will see the message "You need to specify a default language before adding a new translation." which is missing as mentioned above, making it impossible to translate the post. 

**Expected behavior**
The default language the post is in should be specified on the post to enable translation.

**Is there a workaround? What is it?**
No

**Screenshots**
Post via the web
<img width="887" alt="Posts_-_test254" src="https://user-images.githubusercontent.com/20906968/121539377-4cb1b680-ca0e-11eb-9c5a-934d99905dbe.png">
Post via USSD
<img width="883" alt="Posts_-_test254" src="https://user-images.githubusercontent.com/20906968/121539482-6652fe00-ca0e-11eb-8e20-934e713766c6.png">
Error
<img width="491" alt="Posts_-_test254" src="https://user-images.githubusercontent.com/20906968/121539560-72d75680-ca0e-11eb-9487-48b060da688f.png">

**Comment by tuxpiper** [comment]
note: let's check if this has something to do with the language of the post when it gets created from the ussd-engine
