### ISSUE TITLE
Upgrade to webpack 5

### ISSUE THREAD

**Issue by Ifycode** [ushahidi/platform#4287]
Task:
Upgrade webpack for legacy code in feature/migration branch to webpack 5

**Comment by Ifycode** [comment]
Hi @Angamanga, I will like to start work on this sometime this week. I'm feeling a bit more confident to take on this task this time around, based on I've tried one or two things with webpack 5 these past few months. Can I be assigned to this issue/task? 😁

**Comment by Angamanga** [comment]
@Ifycode Please go ahead and try it out :) 🎉  Let me know if you need any help!

**Comment by Ifycode** [comment]
Alright, thank you @Angamanga 😃
