### ISSUE TITLE
Heroku deploy button returns "No app.json located in the repo URL provided." error

### ISSUE THREAD

**Issue by bradleytaftsmith** [ushahidi/platform#4288]
### Description
When clicking the "Deploy to Heroku" button on `readme.md` for Ushahidi Platform...

---

<img width="505" alt="Screen Shot 2021-06-18 at 12 31 33 PM" src="https://user-images.githubusercontent.com/2123567/122597597-353b8480-d031-11eb-93fc-c1627b86e932.png">

---

I am taken to Heroku where I receive the error in the title:

---

<img width="917" alt="Screen Shot 2021-06-18 at 12 34 37 PM" src="https://user-images.githubusercontent.com/2123567/122597699-6451f600-d031-11eb-9bda-ec9578f7df5c.png">

---

### Expected Behavior
app deploys as expected in Heroku, or solution to issue is addressed in documentation

### Screenshots
See above

**URL / Environment where this happened**
https://github.com/ushahidi/platform

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**

### Desktop Hardware Details
 - OS: macOS 10.15.7
 - Browser: Brave
 - Version 1.23.75 Chromium 90.0.4430.93 (Official Build)

**Comment by ps-19** [comment]
Issue Resolved!
