### ISSUE TITLE
Post-lock is not working

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4291]
**Describe the bug**
When someone is editing a post, the post should be unavailable for other people to edit and a message saying that the post is being edited should appear. This is not the case anymore. I can see a lock-icon in the data-list, but when I select the post, I can still edit it.
**Where was the bug observed**
.io

**To Reproduce**
Log in as 2 different users in 2 different browsers.
1. Go to data-view in one of the browsers, select a post and start editing
2. Go to the same post in the other browser, you will see a lock on the post in the list to the left, but clicking "edit" will still open up the post for editing.

**Expected behavior**
A message saying the post is being edited should appear to the second user and it should not be possible to edit the post.

**Additional context**
Probably regression due to translations/v5

**Comment by tuxpiper** [comment]
Seems to be the same as #4428
