### ISSUE TITLE
Reports submitted via the same Gmail account are displayed as both posts and responses to the author in a deployment

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4295]
**Describe the bug**
When a user submits reports via the same Gmail account, the data is captured as both a post and a reply to the author on other prior posts submitted by the same user via the same Gmail account, making the whole thing very confusing.

**Where was the bug observed**
Staging

**To Reproduce**
1.  Submit a post via 'x' Gmail account to the connected Gmail account in your deployment.
2. Go to your deployment, confirm the post has been successfully collected.
3. Submit another post via the same Gmail account
4. Go to your deployment.
5. The second message will be displayed as a post and a response to the author on the first post that was sent.

**Expected behavior**
A submitted report should be displayed as a post and a reply to the author as a response in a post( see screenshots to understand)

**Is there a workaround? What is it?**
Not sure there is any

**Screenshots**
<img width="1275" alt="Posts_-_Ushahidi" src="https://user-images.githubusercontent.com/20906968/124801281-57089700-df5f-11eb-845b-00e13d418202.png">

**URL / Environment where this happened**
https://gmail.staging.ush.zone/

**Comment by tuxpiper** [comment]
Thank you @CeciliaHinga :+1: 

Before making it part of the GMail feature, please let's clarify if this is specific only to GMail or actually relevant to any message data source.
