### ISSUE TITLE
Web Monetization: there should be validation of the wallet address

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4306]
**Describe the bug**
There is no validation on what is provided to the "Wallet Address" input field of the Donation feature configuration.

As a result, deployers may be misled to believe they have correctly configured their wallet, but in reality, the interledger protocol doesn't have the necessary information to operate, and web monetization is not initialized in visitors' browsers. The deployer receives no donations.

**Where was the bug observed**
Deployments with donation feature enabled in staging and production.

**To Reproduce**
1. Log in as an admin
2. Go to Settings > Donation
3. Under "Wallet Address" enter any text
4. Click on "Enable Monetization"
 
**Expected behavior**
The client and the server should check that users' input conforms to the Interledger Protocol specification [Payment Pointer syntax](https://interledger.org/rfcs/0026-payment-pointers/#payment-pointer-syntax)

**Is there a workaround? What is it?**
n/a

**Screenshots**
![2021-09-03 12 43 37](https://user-images.githubusercontent.com/467393/131997805-3ecb8a2e-5837-436a-a3e9-ef743ee90014.gif)

**URL / Environment where this happened**
ushahidi.io - production

**Comment by helen-ndip** [comment]
@Angamanga @tuxpiper can I work on this ?

**Comment by Angamanga** [comment]
@helen-ndip I have assigned you to https://github.com/ushahidi/ussd-engine/issues/48

**Comment by Angamanga** [comment]
@yuktea Assigning this to you!
