### ISSUE TITLE
Add pa11y for local dev environment

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4311]
To make sure we continue improving accessibility we need to do some adjustments to our dev-environment and CI.
- Add https://github.com/pa11y/pa11y to a npm-script for local development
- Add a github-action with pa11y to measure the impact a new PR has on accessibility.

Resources:
https://github.com/pa11y/pa11y

**Comment by Chiemezuo** [comment]
This goes quite well with the discussion from earlier today. I think it's a nice start. Permission to do a follow-up?
