### ISSUE TITLE
Dismiss the error message notification/footer that appears on submitting survey.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4384]
**Which user group(s) are the primary audience for this feature/enhancement.**
Across all deployments, and users submitting responses to surveys.

**Describe the solution you'd like**
When a user navigates to a new page, notifications from previous pages or actions(for instance, error messages when submitting response to a survey) should not persist. They should be auto-closed or dismissed.

**Describe alternatives you've considered**
Auto-close the notification on navigating to new page, or after a set time period lapses.

**Screenshot:**
<img width="1587" alt="Screen Shot 2021-11-22 at 10 06 35 AM" src="https://user-images.githubusercontent.com/38259840/142819428-fc8b5d0a-d636-47e7-871e-824ac4b0ec57.png">

**Comment by helen-ndip** [comment]
hi @Angamanga  I will like to work on this issue.

**Comment by Angamanga** [comment]
@helen-ndip I assigned you to this one already https://github.com/ushahidi/ussd-engine/issues/48. I see you added a pr for this, is it ready for review?

**Comment by Angamanga** [comment]
Thank you @helen-ndip 🙏
