### ISSUE TITLE
The post-creation year is wrong when receiving a post from the v5-endpoint "/posts"

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4388]
**Describe the bug**
When receiving a post from the endpoint `v5/posts/{id}`, the year in the "created" date is given in the wrong format:
(returns a value like: `created: 0247-12-02T16:38:46+0000"`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to data-view, select a post
2. Click on "Edit" and look at the box "Under review" and "Post-date"
3. Click on "Post date"
4. Note the "Created at" date which has the wrong year:
![Screenshot 2021-12-02 at 20 21 09](https://user-images.githubusercontent.com/8624777/144488735-1323c87c-8dd9-45fa-a457-6f39fccb6677.png)
The same year is returned in the v5-endpoint. In the v3-endpoint, the year is correct.

**Comment by andrew21-mch** [comment]
Hi @Angamanga, i tried to test this on my local environment and discovered that i had the correct date of post, i don't know if this was fixed already?
![view](https://user-images.githubusercontent.com/58951422/161398436-aca352ad-e3ec-44aa-a1d0-36e76f6c9acc.png)

**Comment by Angamanga** [comment]
@andrew21-mch Interesting. Some changes to date-times has recently been made so it looks like this one is working correctly now. Thank you for noticing. Closing this.
