### ISSUE TITLE
required node version must be === 10, not >= 10 --> otherwise npm install aborts with "npm ERR! ERESOLVE unable to resolve dependency tree" While resolving: @ushahidi/legacy@4.4.1 Found: chart.js@3.7.0

### ISSUE THREAD

**Issue by ptandler** [ushahidi/platform#4390]
**Describe the bug**
I just started to setup the platform-client, [freshly cloned from github](https://github.com/ushahidi/platform-client/). The docs say I should start with [`npm run install:all`](https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/setting-up-the-platform-client#installing-dependencies).

During legacy's `npm install` it throws:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @ushahidi/legacy@4.4.1
npm ERR! Found: chart.js@3.7.0
npm ERR! node_modules/chart.js
npm ERR!   chart.js@"^3.5.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer chart.js@">= 2.8.0 < 3" from chartjs-adapter-dayjs@1.0.0
npm ERR! node_modules/chartjs-adapter-dayjs
npm ERR!   chartjs-adapter-dayjs@"^1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Could this be [related to the node version](https://stackoverflow.com/a/67710793/1480587) I use?

```
❯ node --version
v16.13.1
❯ npm --version
8.3.0
❯ git log
commit b6eaa7dc0da90418ac3c06bf4bc9b2ff6df77b56 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 803ce98b bcf21d95
Author: Obadha2 <38259840+Obadha2@users.noreply.github.com>
Date:   Mon Dec 6 13:23:39 2021 +0300
```

**Desktop Hardware Details (please complete the following information):**
```
❯ inxi -S
System:    Kernel: 5.11.0-44-generic x86_64 bits: 64 Desktop: Cinnamon 5.2.7 Distro: Linux Mint 20.3 Una 
```

**Comment by ptandler** [comment]
yep, seems to be the node version:

```
❯ nvm use lts/fermium
Now using node v14.18.2 (npm v6.14.15)
❯ npm i
[...]
added 2036 packages from 2658 contributors and audited 2045 packages in 102.893s
```

works :-)

**Comment by ptandler** [comment]
https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/setting-up-the-platform-client#installation-steps
mentions

> Pre-requisite: Install Node V10.x or higher (you might want to use NVM for this) before continuing.

while https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/xampp#setting-up-the-platform-client says

> At the time of this writing, only versions 6.x and 8.x of node.js have been tested, but 10.x is the default version family offered for download.

BTW (a little off topic): you could recommend using https://github.com/coreybutler/nvm-windows to manage node version on windows.

**Comment by ptandler** [comment]
Maybe a follow-up issue during `npm run serve`:

```
[0] [0] [0] ✖ ｢wdm｣: 
[0] [0] [0] ERROR in ./sass/vendor.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js?sourceMap!./sass/vendor.scss)
[0] [0] [0] Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
[0] [0] [0] Error: Missing binding /home/ptandler/src/IKU/ushahidi/platform-client/legacy/node_modules/node-sass/vendor/linux-x64-64/binding.node
[0] [0] [0] Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 10.x
[0] [0] [0] 
[0] [0] [0] Found bindings for the following environments:
[0] [0] [0]   - Linux 64-bit with Node.js 14.x
[0] [0] [0] 
[0] [0] [0] This usually happens because your environment has changed since running `npm install`.
[0] [0] [0] Run `npm rebuild node-sass` to download the binding for your current environment.
```

`npm rebuild node-sass` did not fix it.

Ah, there is another message:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'ushahidi-platform-sdk@0.5.0',
npm WARN EBADENGINE   required: { node: '>= 10 <13' },
npm WARN EBADENGINE   current: { node: 'v14.18.2', npm: '8.3.0' }
npm WARN EBADENGINE }
```

**Comment by CeciliaHinga** [comment]
@webong please assist

**Comment by andrew21-mch** [comment]
Hi @ptandler i am stock at the same point trying to setup the developement environment for front-end client
this is what is get

```
Run `npm audit` for details.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @ushahidi/legacy@4.4.1
npm ERR! Found: chart.js@3.7.1
npm ERR! node_modules/chart.js
npm ERR!   chart.js@"^3.5.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer chart.js@">= 2.8.0 < 3" from chartjs-adapter-dayjs@1.0.0
npm ERR! node_modules/chartjs-adapter-dayjs
npm ERR!   chartjs-adapter-dayjs@"^1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/andy/.npm/eresolve-report.txt for a full report.
```

**Comment by ptandler** [comment]
@andrew21-mch did you try to switch to node v10? This solved it for me.

I really recommend using nvm (or alike). With nvm you can put a [`.nvmrc` in the client project directory](https://github.com/ptandler/platform-client/blob/staging/.nvmrc) in the client project directory and nvm will adjust the node version when you change directories.

```
lts/dubnium
```

However, for the pattern library I was successful with [node v14](https://github.com/ptandler/platform-pattern-library/blob/pet-dev/.nvmrc).

**Comment by andrew21-mch** [comment]
Thanks I solved it, just had to switch to node12
I had 2 versions,

**Comment by helen-ndip** [comment]
@ptandler node 12 fixed it for me too

**Comment by tuxpiper** [comment]
Fixed with https://github.com/ushahidi/platform-client/commit/f79286d3209ea1686a43ec3cb5c31e6024577299
