### ISSUE TITLE
Enhancement on location search 

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4427]
**Describe the bug**
It is hard to find some locations/landmarks on the map, and the automatically suggested locations might not be in the country/area of interest. In this case, if the person submitting the post is not in the area where the event of the situation is happening, they cannot use the "use your current location" feature since they are relying on the information provided, making it hard to find the exact address on the map in the deployments.

Most people will not know how to search for specific coordinates.

**Where was the bug observed**
any ushahidi.io deployment

**To Reproduce**
1. Go to deployment.ushahidi.io/posts/create
2. On the location field, enter the location of a particular village/area
3. You will automatically get suggested locations with the same area name. If the location you wanted is not there,  you will have to manually look for the exact area on the map, which takes a lot of time.

**Expected behavior**
It should be easy to find locations on the map. 

**Is there a workaround? What is it.**
If you are familiar with the address/ landmark and its location on the map, you can manually place the pin by dragging it to the exact point on the map.

**URL / Environment where this happened**
production

**Desktop Hardware Details (please complete the following information):**
 - OS:  iOS]
 - Browser ; brave

**Comment by tuxpiper** [comment]
@CeciliaHinga 

Can we get some examples of villages/areas that were attempted? We need to check if this is a matter of them being very popular names of similar landmarks present globally, or if they were just missing from the geolocation databases that we have access to.
