### ISSUE TITLE
Some of Images Under Reported Incidents are Not Displaying

### ISSUE THREAD

**Issue by Maaz2655** [ushahidi/platform#4445]
Once user Click on incident for Preview Detail View, images are not displaying, it seems to be broken or unloaded images for some reason.

But when you open image by Right Click on copy and past in browser, it is open successfully.

![image](https://user-images.githubusercontent.com/109206042/178679356-a0ae238e-20ee-4e14-9862-7805745bd3be.png)

**Comment by tuxpiper** [comment]
Sorry for the inconvenience, this was a temporary glitch.

It has since been addressed:
![Screenshot 2022-07-22 at 21 04 46](https://user-images.githubusercontent.com/467393/180506733-2c377c20-6837-4ca6-99c5-3296177a288f.png)
