### ISSUE TITLE
Text color is not visible for links added to the deployment description

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4450]
**Which user group(s) are the primary audience for this feature/enhancement.**
Include deployment names if possible
All  users

**Is your feature request related to a problem? Please describe.**
Text for links is hardly visible on the deployment description (under the logo). 
![2022-07-20 19 48 08](https://user-images.githubusercontent.com/467393/180049786-48914c3d-6999-4c0e-ac17-4b5b8a513a16.gif)

**Describe the solution you'd like**
We could use Ushahidi's usual gold/yellow and white when hovering over ( #efb631 )

**Describe alternatives you've considered**
But any properly contrasting colors would already be an improvement anyway.

**Additional context**

**Comment by Ifycode** [comment]
All right @tuxpiper

**Comment by Ifycode** [comment]
@tuxpiper There is a class already called "tool" (with color - #FFC334), which I saw is used for links in the mode context area. I used that for consistency.

**Comment by tuxpiper** [comment]
@AmTryingMyBest  this is ready for QA as well :+1:

**Comment by Ifycode** [comment]
Reopening based on this comment: https://ushahidi.slack.com/archives/CFC4WQG4V/p1663199744090879 where previous fix did not address the description in the activity view.
