### ISSUE TITLE
Provide new "Delete Posts" and "Delete Own Posts" permissions

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4453]
**Which user group(s) are the primary audience for this feature/enhancement.**
Deployers with large teams that could use more fine-grained permissions. i.e. Uchaguzi

**Is your feature request related to a problem? Please describe.**
Due to being an operation that is difficult to reverse, it makes sense to want to have separate permission for deleting posts.

**Describe the solution you'd like**
- We should have two additional possible permissions to assign ("Delete Posts") and ("Delete Own Posts")
![Screenshot 2022-07-22 at 20 25 56](https://user-images.githubusercontent.com/467393/180501793-1ee179b5-26f6-4e72-8b64-f346f1cf3832.png)

- The current "Manage Posts" and "Edit their own posts" permissions should lose their power to allow deleting posts

- When this solution is deployed, any roles that have "Manage Posts" permission assigned, should also get the new "Delete Posts" permission
- When this solution is deployed, any roles that have "Edit their own posts" permission assigned, should also get the new "Delete their own posts" permission

**Comment by Mh-Asmi** [comment]
-  this PR  [#4452](https://github.com/ushahidi/platform/pull/4452) creates the new delete permissions
- there is a small fix on the client side that is needed to close this task , 
    in file `legacy\app\map\post-card\post-actions.html` in line `33` replace 
    `<li ng-show="post.allowed_privileges.indexOf('update') !== -1 && postIsUnlocked()">`
   with
   `<li ng-show="post.allowed_privileges.indexOf('delete') !== -1 && postIsUnlocked()">`

**Comment by tuxpiper** [comment]
@Mh-Asmi  There was a small error in the migration (it was looking for the "Manage Users" permission, instead of "Manage Posts") and that was line 53 of legacy\app\map\post-card\post-actions.html  . A couple small things :)

**Comment by tuxpiper** [comment]
@AmTryingMyBest this is ready for QA, the corresponding client PR is ushahidi/platform-client#1810

**Comment by AmTryingMyBest** [comment]
QA'd, passes. 👍

**Comment by tuxpiper** [comment]
@Mh-Asmi @Ifycode Could one of you please work on updating https://docs.ushahidi.com/ushahidi-platform-user-manual/4.-managing-people-on-your-deployment/4.1-roles#4.1.1-add-role  to add this permission?

**Comment by Ifycode** [comment]
Ah almost forgot about this. The thing is that I still have to check out the delete permissions work. I will do so and update the doc, and let you know when I have done it.
> @Mh-Asmi @Ifycode Could one of you please work on updating https://docs.ushahidi.com/ushahidi-platform-user-manual/4.-managing-people-on-your-deployment/4.1-roles#4.1.1-add-role to add this permission?
