### ISSUE TITLE
Updating post categories alone do not work correctly for some users (draft in progress)

### ISSUE THREAD

**Issue by Mh-Asmi** [ushahidi/platform#4462]
**Describe the bug**
some Uchaguzi users of the geolocated team had an issue when they try to update the geolocated from "Needs geolaction" to other options 
when they try to save, the action does not complete and return a message "you don't change any value"
Important: this does not happen for all users

**To Reproduce**
1. Go to 'https://uchaguzi.or.ke/'
2. Log in as a user from geolocated team 
3. Click on the data view
4. Click on the post edit
5. Scroll down to Geolocated 
6. Change the Geolocated value
7. Click save

**Expected behavior**
save the post without any problem

**Screenshots**

**URL / Environment where this happened**
https://uchaguzi.or.ke/

**Desktop Hardware Details (please complete the following information):**
 - OS: [ iOS]
 - Browser [chrome, safari]
 - Version [...]

**Comment by webong** [comment]
Looking at this issue, it's very likely to be a validation problem occurring in the platform api. So a survey happens to have at least one stage. If it's

What's likely happening here is that the validation logic for editing posts only checks if the **main stage** has been updated ignoring the other stages (tasks).
