### ISSUE TITLE
Tasks details not visible to guests

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4463]
**Describe the bug**
As a guest (not logged-in user) I should be able to see the "Task" data details for published posts.

**Where was the bug observed**
https://uchaguzi.or.ke

**To Reproduce**
1. Go to https://uchaguzi.or.ke/posts/46553
2. No task data available

<img width="1113" alt="Screenshot 2022-08-09 at 19 10 10" src="https://user-images.githubusercontent.com/467393/183703097-77343d14-d396-41d7-ab24-91a9a9cd6ad6.png">

3. Now log in
4. Task data becomes visible

<img width="1113" alt="Screenshot 2022-08-09 at 19 13 14" src="https://user-images.githubusercontent.com/467393/183703691-315de405-073a-4d78-a81d-4753608113a4.png">

**Expected behavior**
As long as we are  talking about published data, and the task has been configured to be published when visible. Non logged-in users should be able to see the data

**Is there a workaround? What is it.**
Not really, only by disabling the "Task is for internal use" switch, which may not be desirable.

<img width="1002" alt="Screenshot 2022-08-09 at 19 26 44" src="https://user-images.githubusercontent.com/467393/183706867-4ee4523e-b5a6-4bb8-8891-4620730a44bc.png">

Disabling "Task is for internal use" makes the Tasks available for submission (on post creation) and also visible for viewing publicly -- (as long as the second option is also checked).

Disabling "Task is for internal use" and "Show this task to everyone when published" , makes it possible to fill the task fields when submitting a post, but *hides* the task information from guests when the post is published.

So as it stands, it looks like Enabling the "Task for internal use" switch is making the "Show to everyone when published" switch ineffective.

**URL / Environment where this happened**
https://uchaguzi.or.ke

**Additional context**

**Comment by Mh-Asmi** [comment]
in V3, to get the task of a survey we were using the API
`api/v3/stages?form_id=%id%&post_status=%status%`

- in case the post_status is published this API will return the tasks that meet the condition 
        `show_when_published = 1`
- in case the post_status is not published this API will return  the task that meets the two conditions
        `show_when_published = 1 and task_is_internal_only=0`

in V5, to get the task of a survey we are using the API
`api\v5\survey`
this API doesn't accept post_status as a query parameter. therefore regardless of the post status, this API returns only the tasks that meet the two conditions 
        `show_when_published = 1 and task_is_internal_only=0`

**Comment by Ifycode** [comment]
Both guests (user who are not logged in) and logged-in users who can only edit their own posts are affected.
