### ISSUE TITLE
"Save" button not showing for everyone (draft in progress)

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4464]
**Describe the bug**
For some new users, the save button does not appear, when the administrator upgrades their permission without logging out of those users

**To Reproduce**
1. Go to 'https://uchaguzi.or.ke/'
2. Signup as a new user
3. Login using the new account
4. Ask an admin to upgrade your permission, and give you permission to edit the posts 
5. Click on 'Data view'
6. Click on any post
7. Click on the three dots , and choose Edit this post
8. You will not see the save button 
9. logout 
10. login again with the new user account 
11. repeated the steps top edit post 
12. you will see the save button

**Expected behavior**
See the save button even with the need to logout and login again.

**URL / Environment where this happened**
https://uchaguzi.or.ke/

**Comment by tuxpiper** [comment]
@Mh-Asmi  I think you had more details about how to reproduce this one. Can you please update the description accordingly?

**Comment by tuxpiper** [comment]
<img width="971" alt="Screenshot 2022-08-08 at 13 41 27" src="https://user-images.githubusercontent.com/467393/183400463-c5ee4f07-b6ba-497a-b641-7c83bd0468ea.png">

as a workaround, one can use the three dot menu

**Comment by Mh-Asmi** [comment]
> @Mh-Asmi I think you had more details about how to reproduce this one. Can you please update the description accordingly?

I have updated the description of this issue
