### ISSUE TITLE
140 chars limits disables send button on message reply

### ISSUE THREAD

**Issue by webong** [ushahidi/platform#4467]
**Describe the bug**
The client application doesn’t allow sending SMS replies longer than 160 characters, even if the provider (Africa’s Talking) allows it.
UPDATE: however, we may not want to enable more than 160 characters, as there is no warranty in the order of delivery for the chunks.
 
**To Reproduce**

Go to 'https://uchaguzi.or.ke/'
Log in as a user from geolocated team
Click on the data view
Click on the post edit
Scroll down to "Send a new message" and click
Enter more than 140 characters into the textbox
Try to click save.

**Screenshots**
https://user-images.githubusercontent.com/30173059/183409403-7f2f5788-df75-40db-b710-46d669228f4a.mp4

**URL / Environment where this happened**
https://uchaguzi.or.ke/

**Comment by tuxpiper** [comment]
Setting as a P0 , as this is hindering Structuring work

cc: @JosephUshahidi @CeciliaHinga

**Comment by tuxpiper** [comment]
We've got a PR submitted for this
