### ISSUE TITLE
Post list display only published posts by default when no status is specified

### ISSUE THREAD

**Issue by Mh-Asmi** [ushahidi/platform#4468]
**Describe the bug**
the list of posts will show only published posts when apply the filter with no specific status 

**To Reproduce**
1. Go to 'https://uchaguzi.or.ke/'
2. Log in as a user 
3. Click on 'Sort & filter'
4. Scroll down to 'Status'
5. Unselect all options 
6. Click on 'Apply'
7. You will see that all posts shown are published, although there may be other posts from another statuses that meet the filtering conditions

**Expected behavior**
Show all posts that meet the filter conditions regardless of their status

**URL / Environment where this happened**
https://uchaguzi.or.ke/

**Comment by nimishmedatwal** [comment]
I would like to work on this

**Comment by tuxpiper** [comment]
Hi @nimishmedatwal . Thank you for interest 🙏  Unfortunately in this case, we have a number of rather old issues that have since been addressed in the new version we released late last year.

This is one of them, I have just verified it and it has been fixed since.
