### ISSUE TITLE
`docker compose up` not work in v5.3.1, ushahidi-platform-1/ushahidi-platform_tasks-1 exited with code 1

### ISSUE THREAD

**Issue by kiang** [ushahidi/platform#4517]
**Describe the bug**
The two containers 'ushahidi-platform-1/ushahidi-platform_tasks-1` can't run using `docker compose up`

**Where was the bug observed**
Before the service running

**To Reproduce**
1. Download v5.3.1 release and extract it
2. Install the latest docker following https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
3. Execute command `sudo docker compose up`

**Expected behavior**
Run the container and can be access from browser.

**Desktop Hardware Details (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - Docker version 23.0.0, build e92dd87

**Comment by kiang** [comment]
error messages:
```
ushahidi-mysql-1           | 2023-02-03T02:26:02.647858Z 3 [Note] Got an error reading communication packets
ushahidi-mysql-1           | 2023-02-03T02:26:02.648107Z 2 [Note] Got an error reading communication packets
ushahidi-platform_tasks-1  | truncate: cannot open 'storage/logs/lumen.log' for writing: No such file or directory
ushahidi-platform-1        | truncate: cannot open 'storage/logs/lumen.log' for writing: No such file or directory
ushahidi-platform-1 exited with code 1
ushahidi-platform_tasks-1 exited with code 1
```

**Comment by lupa18** [comment]
I did the same and works. Why do you call docker-compose with sudo?

Main problems using this configuration comes with a wrong .env file. 

Could you paste your .env file?

I also have problems there at storage but will publish another issue.
