### ISSUE TITLE
The same street is not found in the OpenStreetMap used in Ushahidi but is available in the main OpenStreetMap of its wwebsite!

### ISSUE THREAD

**Issue by cypherinfo** [ushahidi/platform#4519]
Hello, I've used Ushahidi for my new project: https://ma.ushahidi.io/views/map, and I was attempting to add a  report on the map, but the name of that street was not found.
The same street name is available on the main website of OpenStreetMap.
It is: **via N. Piccinni, Bari, Italy**
Below the images taken from Ushahidi and OpenStreetMap for the same street.
![ushahidi](https://user-images.githubusercontent.com/922409/218341269-be2fb745-1cb3-443d-a15d-5443e83de40a.png)
![openstreetmap](https://user-images.githubusercontent.com/922409/218341282-12080aff-c460-4647-bc5d-4e5e62e25fe2.png)

**Comment by tuxpiper** [comment]
That's an issue with rendering choices made by the default Mapbox style. We will forward the comment to Mapbox to see if they can address it, but ultimately "fixing the map" is up to them. 

If you prefer the rendering by vanilla OpenStreetMap, we would suggest switching to the "Humanitarian" map base layer ("Default base layer") in the general preferences of the deployment.

We will gladly consider adding more map layer options if you suggest them, as long as they are publicly available and potentially useful for most deployers.

**Comment by cypherinfo** [comment]
Thank you for your availability to add one publicly available layer.
I'd suggest adding the Bing Roadmap; it is featured on https://openlayers.org/
It is beneficial for many deployments.
