### ISSUE TITLE
via Piccinni Bari Italy not found when adding a post! It is the Apulia region capital!

### ISSUE THREAD

**Issue by cypherinfo** [ushahidi/platform#4520]
**Describe the bug**
The city is not found when I enter the street, city, and country in the location field to add a post to my distribution. The one I entered is the regional capital of Puglia, Italy, i.e., Bari. The cities that are suggested are all related to other Apulian cities.  

**Where was the bug observed**
Deployment and page UR: https://ma.ushahidi.io/posts/create/1

**To Reproduce**
In Settings>General>Default base layer>"Humanitarian" 
1. Go to Map (icon)
2. Log in as 'admin' giuseppe.calamita@gmail.com
3. Click on the '+' button
4. Write in the Location field: "via Piccinni Bari Italy"

**Expected behavior**
I expect to see a marker on the map's street related to the city in the Location field.

**Screenshots**
![lacking Bari](https://user-images.githubusercontent.com/922409/218465985-8651526e-d7af-40f1-9079-d28345b55e4d.png)

**URL / Environment where this happened**
https://ma.ushahidi.io/posts/create/

**Desktop Hardware Details (please complete the following information):**
 - OS: windows 10 pro
 - Browser Chrome
 - Version 110.0.5481.78 64 bit

Thank you for your availability to add one publicly available layer.
I'd suggest adding the Bing Roadmap; it is featured on https://openlayers.org/
It is beneficial for many deployments.

**Comment by CeciliaHinga** [comment]
Hi @cypherinfo, thank you for the suggestion. Our dev team will review it. As Tuxpiper mentioned, we will forward this to Mapbox. 

In the meantime, as an alternative solution, I would advise creating another text field that will help people enter the exact location in text form, as shown below
<img width="956" alt="Create_Post_-_Uchaguzi_🔊" src="https://user-images.githubusercontent.com/20906968/218495222-c28e8987-5e13-45cd-a551-6a4d52e9cefc.png">

For people who are capable of finding the coordinates, they can search the coordinates of the areas and enter them as latitude and longitude.

**Comment by tuxpiper** [comment]
@cypherinfo I think the street you are looking for is, in fact, findable. The results of the geocoding service that performs the queries are highly dependent on the input provided.

<img width="735" alt="Screenshot 2023-02-13 at 18 09 16" src="https://user-images.githubusercontent.com/467393/218525202-3c5ad846-64a9-4ae1-b739-0c20d126c000.png">
<img width="770" alt="Screenshot 2023-02-13 at 18 09 28" src="https://user-images.githubusercontent.com/467393/218525223-ae9e66d4-0d8b-42b3-ab0a-6bb407f0bb90.png">

Understandably, we can't have a software development goal about making a concrete street findable, even more so when we can't control the databases that enable these searches.

Our goal in this project should be to enable choices and keep things transparent.

I think that as a result of this issue, we should have these software development issues below: 

1. Harmonizing the choice of map layer with the choice of geocoding service. Mapbox layers should imply Mapbox geocoding. OSM layers should imply Nominatim search. Bing should imply Microsoft. Etc.
2. Allowing end-users to provide their own API keys for the mapping service of their choice. In some cases, such as famously Google Maps, providing this key will be necessary for enabling that layer.
3. Adding Bing maps and street search, see if the pricing structure requires the user to provide an API key

**Comment by cypherinfo** [comment]
Thank you for your continuous effort at improvement and for your willingness.
Mine is st the view of an end user. As such, I expect an intuitive response from the platform.
If the platform is designed for cartographers, it is okay.
I fear that it will shrink the circle of those who may be interested in using it.

**Comment by tuxpiper** [comment]
@cypherinfo yes, that's understood; we'll keep working on improvements.

One of the main problems with user experience around maps is that there's no one provider that gives the best experience in the whole world. Different providers tend to work better for specific places/countries. What just works in Italy, may not be so smooth in the Philippines. That's why providing choice is critical for our global audience.

**Comment by cypherinfo** [comment]
I am curious to know if somebody who is translating in Italian is already active. I'm available to join that group if existing or starting on my own the translation.

**Comment by tuxpiper** [comment]
Hi @cypherinfo , please check the transifex project here: https://explore.transifex.com/ushahidi/ushahidi-v3/  . There seems to be a partially complete Italian translation contribution. We'd be delighted if you would like to complete it 🙏

**Comment by cypherinfo** [comment]
Thank you (I am honored) for appointing me as coordinator of the Italian translation of Ushaidi 3.0.
I sent a message to all the translators on the team; after my overview, I found a lot to translate.
Being an online UN volunteer, the Italian translation seems the most suitable "task" for the UN volunteer site https://app.unv.org, where NGOs, nonprofits, and professionals (volunteers) meet.
The entire process is free for both parties. After registration, an organization can post an ad (indicating the period and number of volunteers needed) to search for the online volunteers it needs for its assignment (translation).
At the end of the stipulated period deserving volunteers can be issued certificates confirming their commitment.
Below are links to the website and the information needed:
https://toolkit.unv.org/hosting/request-un-volunteers
https://toolkit.unv.org/document-library/unv-offer-and-value-proposition
https://toolkit.unv.org/sites/default/files/2021-04/Roles_and_Responsabilities_of_Host_Entity_EN.pdf

**Comment by cypherinfo** [comment]
A big thank you all :)
