### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by shazadanjum2** [ushahidi/platform#4521]
I recreived this issue when i run **composer migrate**  
61 tables create and after that this error occour

In PdoAdapter.php line 338:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that
   corresponds to your MariaDB server version for the right syntax to use near 'JSON NOT NULL, PRIMARY KEY (`id`),  K
  EY (`import_id`,`source_table`,`row_id`),  ' at line 1

**Comment by Angamanga** [comment]
@tuxpiper Do you know if this issue has been resolved?
