### ISSUE TITLE
[USH-266] Users unable to log into a Private deployment.

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#4549]
**Describe the bug**
Users unable to log into a private deployment

**Where was the bug observed**
Private deployment, on logging in

**To Reproduce**

1. Go to a private deployment
2. Log in
3. Login seems to work, but only momentarily as user is redirected to the homepage with the login button visible

**Expected behavior**
On logging into a private deployment, a user should be redirected to an appropriate page away from the Access Denied page. They should not be required to manually navigate away from this page after logging in.

**Is there a workaround? What is it.**
None on the new platform

**Screenshots**

[https://user-images.githubusercontent.com/38259840/227458886-cfe21877-31cc-4b17-a7dc-a71293335a60.mov](https://user-images.githubusercontent.com/38259840/227458886-cfe21877-31cc-4b17-a7dc-a71293335a60.mov)

<sub>From [SyncLinear.com](https://synclinear.com) | [USH-266](https://linear.app/ushahidi/issue/USH-266/users-unable-to-log-into-a-private-deployment)</sub>

**Comment by tuxpiper** [comment]
Link to report conversation: https://app.intercom.com/a/inbox/hl5rfiga/inbox/shared/all/conversation/27442008854

**Comment by tuxpiper** [comment]
@walter @olehsol could you please check this again on [https://mzima-private.staging.ush.zone/map](https://mzima-private.staging.ush.zone/map) and see if the issue needs updates?

@barbara.cichon @cecilia @tim did you all talk about private deployments at all? Do we have designs for them? (i.e. what casual guests should see in the screen when they try to access a deployment that's locked down)

**Comment by tuxpiper** [comment]
I think maybe there should be some specific communication that the administrator of the deployment has decided that the access shall not be public and restricted to members only. What do you think @tim @cecilia  ?

**Comment by tuxpiper** [comment]
I'm not sure about the actual demand for it, as I have not heard anyone wanting it. But maybe some folks would actually find it useful.

**Comment by tuxpiper** [comment]
This has gone back to needing fixing. Releasing my assignment.

cc: @evanfournier

**Comment by AyushSinghRawat-hub** [comment]
is this still open

**Comment by AyushSinghRawat-hub** [comment]
can you assign it to me
