### ISSUE TITLE
Export data pending

### ISSUE THREAD

**Issue by michellejacobufrn** [ushahidi/platform#4621]
Hi, I've been trying to download my database without success. All my downloads are pending. Could you help me?

**Comment by AmTryingMyBest** [comment]
Hi @michellejacobufrn 

What deployment are you attempting to get downloads from?

**Comment by AmTryingMyBest** [comment]
Does a "Got It" button appear for you on the bottom of the screen when you click the "Export All Data" button?

**Comment by tuxpiper** [comment]
If you are self hosting, please make sure that you are also running the background tasks ( `artisan queue:listen` background process ) . If you don't want to install another service to manage the queue (i.e. redis), it can also be set up in other ways. Please consult the Laravel documentation for reference.

**Comment by michellejacobufrn** [comment]
> 

The button that appears is labeled as 'Export selected fields'.

**Comment by michellejacobufrn** [comment]
> If you are self hosting, please make sure that you are also running the background tasks ( `artisan queue:listen` background process ) . If you don't want to install another service to manage the queue (i.e. redis), it can also be set up in other ways. Please consult the Laravel documentation for reference.

I'm not self hosting :/

**Comment by tuxpiper** [comment]
> > If you are self hosting, please make sure that you are also running the background tasks ( `artisan queue:listen` background process ) . If you don't want to install another service to manage the queue (i.e. redis), it can also be set up in other ways. Please consult the Laravel documentation for reference.
> 
> I'm not self hosting :/

In that case, could you please drop us a line via the messenger icon on the bottom right corner of the screen? You should see it after logging in. In that way, we would know exactly what deployment we are hosting for you and would be able to give you better support.

<img width="289" alt="image" src="https://github.com/ushahidi/platform/assets/467393/0bfe3fac-20b8-45bf-9ba6-0eb7b9e84339">

Please, if you remember to close this issue once you have been able to do that, it would help us keep things a bit tidier.

**Comment by tuxpiper** [comment]
Probable hosting issue, being handled in support.
