### ISSUE TITLE
SVG icons blocked as unsafe / CORS issue in production

### ISSUE THREAD

**Issue by lukeantbits** [ushahidi/platform#4690]
Environment is Docker platform-release on Ubuntu / Digital Ocean droplet 

I successfully deployed Ushahidi a few months ago, however have recently noticed SVG icons are not loading with the following error description

`Unsafe attempt to load URL data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxkZWZzPgo8c3ltYm9sIGlkPSJhY2NvdW50LWxvZ2luIiB2aWV3Qm94PSIwIDAgOCA4Ij4KICA8cGF0aCBkPSJNMyAwdjFoNHY1aC00djFoNXYtN2gtNXptMSAydjFoLTR2MWg0djFsMi0xLjUtMi0xLjV6Ij48L3BhdGg+Cjwvc3ltYm9sPgo8c3ltYm9sIGlkPSJhY2NvdW50LWxvZ291dCIgdmlld0JveD0iMCAwIDggOCI+CiAgPHBhdGggZD0iTTMgMHYxaDR2NWgtNHYxaDV2LTdoLTV6bS0xIDJsLTIgMS41IDIgMS41di0xaDR2LTFoLTR2LTF6Ij48L3BhdGg+Cjwvc3ltYm9sPgo8c3ltYm9sIGlkPSJhY3Rpb24tcmVkbyIgdmlld0JveD0iMCAwI...UM2Ljk1MzExIDQuMzE0MzcgNy4wNTg5MyA0LjExNjM4IDcuMjE0MzMgMy45NjA5OUM3LjM2OTcyIDMuODA1NiA3LjU2NzcgMy42OTk3OCA3Ljc4MzIzIDMuNjU2OTFDNy45OTg3NyAzLjYxNDAzIDguMjIyMTggMy42MzYwNCA4LjQyNTIgMy43MjAxM0M4LjYyODIzIDMuODA0MjMgOC44MDE3NyAzLjk0NjY1IDguOTIzODYgNC4xMjkzN0M5LjA0NTk1IDQuMzEyMDkgOS4xMTExMSA0LjUyNjkxIDkuMTExMTEgNC43NDY2N0M5LjExMTExIDUuMDQxMzUgOC45OTQwNSA1LjMyMzk3IDguNzg1NjcgNS41MzIzNEM4LjU3NzMgNS43NDA3MSA4LjI5NDY5IDUuODU3NzggOCA1Ljg1Nzc4WiIgZmlsbD0iIzFEQURFQiIvPgo8L3N5bWJvbD4KPC9kZWZzPgo8L3N2Zz4KCg==#map-marker from frame with URL https://admin.dataonthemove-beta.net/views/data. Domains, protocols and ports must match.`

Have attempted in vain to troubleshoot! When running the same Docker image locally via the desktop client icons load without issue, also appears to be serving png assets locally instead of SVGs

**Comment by Angamanga** [comment]
@tuxpiper Could you check if this is still an issue
