### ISSUE TITLE
build_env.sh references a non-existent release

### ISSUE THREAD

**Issue by this-statement-is-false** [ushahidi/platform#4691]
The file:
https://github.com/ushahidi/platform-release/blob/main/build_env.sh

references a non-existent release of the api:
api_version=v2023.42.5

Steps to reproduce:
* git clone https://github.com/ushahidi/platform-release.git
* cd platform-release
* docker-compose up

The the output shows:
api_url=https://github.com/ushahidi/platform/releases/download/v2023.42.5/ushahidi-platform-bundle-v2023.42.5.tar.gz

This url does not exist.

Also note that release candidate 2 does not exist either:
https://github.com/ushahidi/platform-release/releases/download/v6.0.0-rc.1/ushahidi-platform-release-v6.0.0-rc.2.tar.gz

**Comment by tuxpiper** [comment]
Thank you, we will look into this and address it soon 🙏

**Comment by this-statement-is-false** [comment]
Hi there, just checking if you need any more info about this issue?

**Comment by tuxpiper** [comment]
Thank you @this-statement-is-false , the issue was clear. We have just published a new release and reconciled the versions in the platform-release repository.

Cheers!
