### ISSUE TITLE
Date Range Selector

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4704]
The selected date range should be visible to users. The entire screen is yet to be implemented as a fresh design, but the date range should be hot-fixed because a user has requested following Mzima Release.

![Screenshot 2023-11-03 161826.png](https://uploads.linear.app/f1df6e34-3bca-4ade-bb48-e6a457e64091/6d9f4c19-ccf8-45f7-a232-2171b416318c/eadeaa08-b66b-442a-85f7-a0bb232b5c74)

Design: 

[filters - Ushahidi (Figma)](https://www.figma.com/file/c0LFvzuib8E3FHmp6Of8MS/Ushahidi?type=design&node-id=7488-105014&mode=design&t=iG0vWo4YOFOwDeDj-4)

---
Created automatically from USH-974 (https://linear.app/ushahidi/issue/USH-974/date-range-selector)

**Comment by Angamanga** [comment]
This issue is done
