### ISSUE TITLE
Uploaded images display on the website but not in the app (for self-hosted)

### ISSUE THREAD

**Issue by this-statement-is-false** [ushahidi/platform#4712]
I have installed the latest version of the Ushahidi platform:

git clone https://github.com/ushahidi/platform-release.git
cd platform-release

I copied my ssl cert into the tls-certs directory and updated docker-compose.tls.yml, then ran:

docker-compose -f docker-compose.tls.yml up -d

I can access the server from my Chrome browser on my Windows laptop and also my Android phone.
It all works well.

However, if I try to access the server via the latest Ushahidi Android phone app, I see my posts but the uploaded images are not displayed.
I do not know if this is an issue with the phone app or the server.

I also notice that I cannot use the Android app to create a new post. After tapping the Submit button, nothing happens and the app continues to display the form to enter the data.

**Comment by this-statement-is-false** [comment]
Hi there, I am just checking if this has been resolved. Is there anywhere I can follow this issue. I see it has been transferred from ushahidi/platform-release, but I don't know where it has been transferred to. I see that the linear bot commented on the issue, but if I follow this link, it asks me to create a workspace.

**Comment by tuxpiper** [comment]
The issue has been assigned to @wisdom with priority "High" (our second highest priority). This means that it's likely that it will be sorted out within 2-4 weeks (as we've got some other urgent issues that are being worked on).
@wisdom please provide updates on this thread.

**Comment by tuxpiper** [comment]
> Hi there, I am just checking if this has been resolved. Is there anywhere I can follow this issue. I see it has been transferred from ushahidi/platform-release, but I don't know where it has been transferred to. I see that the linear bot commented on the issue, but if I follow this link, it asks me to create a workspace.

@this-statement-is-false:
Linear is the tool we use to arrange our sprints internally, the issue being there means that is an active concern of the team. This is an appropriate place to follow the issue, we'll be using the Linear to GitHub integration to provide updates as we progress.

**Comment by tuxpiper** [comment]
Just  wanted to give an update here, that we have bumped this up to urgent priority

**Comment by Angamanga** [comment]
@tuxpiper @ushahidlee Is this issue done?

**Comment by tuxpiper** [comment]
🤔  I think it may be done, but I remember it was confusing to get proper updates about it as it kept getting bungled up with other issues.<br><br>I would advise to check it again
