### ISSUE TITLE
Mobile client: UI drafting error

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4721]
Founded should be changed to found on the Add Deployment screen and any other relevant search output screens

![Screenshot_20231017-161832.jpg](https://uploads.linear.app/f1df6e34-3bca-4ade-bb48-e6a457e64091/f51b2eac-b640-4c51-bf63-cc931bac07b7/7a9ddf5d-abf2-489f-b06d-edbcdeaedb4f)

---
Created automatically from USH-931 (https://linear.app/ushahidi/issue/USH-931/mobile-client-ui-drafting-error)

**Comment by Angamanga** [comment]
Done
