### ISSUE TITLE
Improve text description of number of posts in collection

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4727]
![Screenshot_20231229-195645](https://github.com/ushahidi/platform/assets/8624777/b9d1b92c-5386-41f8-b631-96d3054cfde6)

---
Created automatically from USH-1153 (https://linear.app/ushahidi/issue/USH-1153/improve-text-description-of-number-of-posts-in-collection)

**Comment by jatinder14** [comment]
please assign this issue to me @tuxpiper @Angamanga

**Comment by Angamanga** [comment]
@jatinder14 Welcome to Ushahidi! In order to start an issue, you need to follow the steps in this discussion: https://github.com/ushahidi/platform/discussions/4713 Have you set up your developer environment yet?

**Comment by jatinder14** [comment]
hi @Angamanga  the setupe is done
![image](https://github.com/ushahidi/platform/assets/89455433/fdaf2252-567a-43a7-aae4-960dfcb7bfd4)

could you please tell me what improvement is required here like Count is wrong I guess ?
Am I Right @tuxpiper ?

**Comment by RWUBAKWANAYO** [comment]
Hi @Angamanga , as an Outreachy applicant, I've completed the setup of the project locally. I'd like to work on this issue, could you please assign it to me?



![Image](https://github.com/ushahidi/platform/assets/68381641/c01ddfc6-d51a-48ea-8158-f33d425334ae)
![Image](https://github.com/ushahidi/platform/assets/68381641/6ee3e6ef-3779-4baf-9b83-44d7f5ea616a)

**Comment by Bilalshaikh15** [comment]
@tuxpiper can you please describe the issue in brief.

**Comment by Angamanga** [comment]
@jatinder14 You also need to setup the platform-client, the repository is found here: https://github.com/ushahidi/platform-client-mzima. @RWUBAKWANAYO Please go ahead! @Bilalshaikh15 I have added 2 issues that are open for everyone to start working on straight away, these are https://github.com/ushahidi/platform/issues/4749 and https://github.com/ushahidi/platform/issues/4750.

**Comment by crocmons** [comment]
Hello, I want to work on this issue. Could you please assign me this task? @tuxpiper @Angamanga I have successfully set up my developer environment.

![Screenshot (649)](https://github.com/ushahidi/platform/assets/106610322/ac4f75cc-52ca-432e-8cae-0147c68e7970)
