### ISSUE TITLE
update Language Input Under Post Title in Post Edit Modal In The Map View (Mobile Version)

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4731]
![Screenshot from 2023-08-31 11-36-28](https://github.com/ushahidi/platform/assets/8624777/662bed94-6d0c-4db8-aed5-f50d6742b8b0)

![Uploading Screenshot 2024-03-02 at 09.39.56.png…]()

---
Created automatically from USH-942 (https://linear.app/ushahidi/issue/USH-942/update-language-input-under-post-title-in-post-edit-modal-in-the-map)

**Comment by nimishmedatwal** [comment]
I am interested in working on this issue can you please assign this to me?
