### ISSUE TITLE
Mobile Offline - Let's tell the user they can't login because they are offline.

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4733]
A toast that says "Offline" or "network unavailable" or something. 

https://github.com/ushahidi/platform/assets/8624777/86b78f8a-8892-4c84-9ba0-f758d4bbd6e7

---
Created automatically from USH-815 (https://linear.app/ushahidi/issue/USH-815/mobile-offline-lets-tell-the-user-they-cant-login-because-they-are)

**Comment by VilmaScript** [comment]
Can I work on this ?

**Comment by VilmaScript** [comment]
Please can I work on this ?

**Comment by Angamanga** [comment]
@VilmaScript Welcome to Ushahidi! In order to start an issue, you need to follow the steps in this discussion: https://github.com/ushahidi/platform/discussions/4713 Have you set up your developer environment yet?

**Comment by Remi-dee** [comment]
Hi @Angamanga, i have setup my developer Environment and i would like to work on this issue

**Comment by Angamanga** [comment]
@Remi-dee If you are still interested, please go ahead :)
