### ISSUE TITLE
Change placeholder text where all filter parameters are cleared

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4735]
In the Data View page, when a user hits clear button, all Surveys are unselected and no posts are shown. 

The text on the page says "There are no posts yet!" which may be inaccurate. Posts do exist, only no parameters are selected to show matching posts. Can we change the message to say something else a bit more accurate like "select survey to show posts" or "no surveys selected" 
![Screenshot 2023-09-13 at 13 57 14](https://github.com/ushahidi/platform/assets/8624777/987bd67c-a106-4c8a-920d-d94faf266a3f)

---
Created automatically from USH-836 (https://linear.app/ushahidi/issue/USH-836/change-placeholder-text-where-all-filter-parameters-are-cleared)

**Comment by Mekebib-Ergudo** [comment]
Hello there, my name is Makebib and I'm participating in the Outreachy program during the contribution phase. I'm interested in taking on this project.

**Comment by mhdamaan79** [comment]
I would like to work on this issue. Please assign it to me. I'm an Outreachy applicant for May 2024.

**Comment by Angamanga** [comment]
@Mekebib-Ergudo Welcome to Ushahidi! In order to start an issue, you need to follow the steps in this discussion: https://github.com/ushahidi/platform/discussions/4713 Have you set up your developer environment yet?

**Comment by jatinder14** [comment]
@Angamanga @tuxpiper  I have fixed this issue . 
the changes are as
![image](https://github.com/ushahidi/platform/assets/89455433/3576926d-5599-49d1-8fbc-b15ecae37212)

**Comment by Felysilver** [comment]
> select survey to show posts

@jatinder14 thanks for working on this. How about considering "Select a survey to show posts"

**Comment by jatinder14** [comment]
yes Sure that sounds more good I will add it.

**Comment by jatinder14** [comment]
@Angamanga  please check https://github.com/ushahidi/platform-client-mzima/pull/815
The PR
