### ISSUE TITLE
Reword error message when creating a survey

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4736]
I added a "+" character when creating a Survey in the Survey name field. The error message that came up was "please recheck the your inputs"
**Expected Behavior**

Highlight field with issue

Correct the wording to be grammatically correct, and descriptive. We want to tell the user a field has invalid characters or input.

https://github.com/ushahidi/platform/assets/8624777/5c82a9a7-2b44-4bd3-9bf2-8c8cf25bfce8

---
Created automatically from USH-878 (https://linear.app/ushahidi/issue/USH-878/reword-error-message-when-creating-a-survey)

**Comment by blessingpeters** [comment]
Hello @Angamanga  I'm Blessing Peter, an outreachy Applicant. Can I work on this issue please.

**Comment by Angamanga** [comment]
@blessingpeters Welcome to Ushahidi! In order to start an issue, you need to follow the steps in this discussion: https://github.com/ushahidi/platform/discussions/4713 Have you set up your developer environment yet?

**Comment by blessingpeters** [comment]
Yes. my development environment is ready.
here's proof:


![Image](https://github.com/ushahidi/platform/assets/68845318/ddf95384-4bca-4524-9518-2bf7d9251238)

**Comment by Angamanga** [comment]
@blessingpeters Well done! Please go ahead with this issue and let me know if something is unclear 👍

**Comment by blessingpeters** [comment]
sure thing! Thanks @Angamanga

**Comment by blessingpeters** [comment]
@Angamanga This PR for this issue is ready for review. 
[#4748](https://github.com/ushahidi/platform/pull/4748)
