### ISSUE TITLE
"Sorting" onboarding modal is absent for Arabic translation

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4738]
**Attachment:**
<img width="1680" alt="Screenshot 2023-08-01 at 16 40 10" src="https://github.com/ushahidi/platform/assets/8624777/c1887eac-9e65-4071-b953-38c9297fc88a">

---
Created automatically from USH-653 (https://linear.app/ushahidi/issue/USH-653/filtering-onboarding-modal-is-absent-for-arabic-translation)

**Comment by Chiemezuo** [comment]
This looks a bit tough, but I could tackle it with the right guidance and pointers on what to look out for.

**Comment by Felysilver** [comment]
@Angamanga could you please asign this to me. Thanks!

**Comment by Aquilaafuadajo** [comment]
hmm... I see the problem here. Because the language is Arabic, the layout shifts and the tour is no longer visible
@Angamanga please I'd love to work on this

**Comment by Felysilver** [comment]
Hi @Angamanga , @tuxpiper I have made a fix to this through this PR https://github.com/ushahidi/platform-client-mzima/pull/821 would be glad for a review. Thanks!
