### ISSUE TITLE
Add a notification that when a survey is deleted, all collected data from the Survey is lost

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4740]
A confirmation modal comes up when deleting a Survey. Add the text "Deleting this survey will remove it and all collected data from the database….." to the modal to clarify for the user that all data associated with the survey will be deleted.
![Screenshot 2024-02-23 at 15 22 36](https://github.com/ushahidi/platform/assets/8624777/1a463b23-d9aa-47f0-9391-798ac6f5ace9)

---
Created automatically from USH-1165 (https://linear.app/ushahidi/issue/USH-1165/add-a-notification-that-when-a-survey-is-deleted-all-collected-data)

**Comment by Felysilver** [comment]
Hi @tuxpiper I working on this

**Comment by Felysilver** [comment]
@Angamanga I humbly have this pr ready for review. Thanks!

**Comment by mo-gbolahan** [comment]
Hello @Angamanga, i am an Outreachy applicant and i've got my developer environment up and running. I'd like to work on this issue

![Image](https://github.com/ushahidi/platform/assets/31252159/f9c572b1-80ec-4168-a7b5-417c1868ca89)

**Comment by felabel** [comment]
@Angamanga I’m and applicant, done with my setup and ready to contribute. Could you please assign this to me ?
