### ISSUE TITLE
Could we change this to not say something generic like "Getting Data" and have something like "Fetching Surveys..." instead?

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4745]
**Description**
Change the text when creating a new post in mobile app

0. Prerequisite: Open mobile app, select a deployment
1. In map-view, tap on the yellow + sign

**Expected behaviour**
The text while the application is loading the data for the survey-dropdown should say "Fetching surveys..."

**Actual behaviour**
The text is saying "Getting data"

****
https://github.com/ushahidi/platform/assets/8624777/242acf4f-0684-48a2-99e8-4a0882701521

This happens on opening page containing surveys.

---
Created automatically from USH-794 (https://linear.app/ushahidi/issue/USH-794/could-we-change-this-to-not-say-something-generic-like-getting-data)

**Comment by codewithmide** [comment]
Can I fix this? I'm from Outreachy

**Comment by Bilalshaikh15** [comment]
please assign it to me. i am woking on it.

**Comment by Bilalshaikh15** [comment]
https://github.com/ushahidi/platform-client-mzima/pull/812
fixed raised a PR

**Comment by crocmons** [comment]
please assign me this task, @tuxpiper I want to resolve this issue

**Comment by tuxpiper** [comment]
> please assign me this task, @tuxpiper I want to resolve this issue

@Angamanga to your attention

**Comment by Angamanga** [comment]
@codewithmide Welcome to Ushahidi! In order to start an issue, you need to follow the steps in this discussion: https://github.com/ushahidi/platform/discussions/4713 Have you set up your developer environment yet?

@Bilalshaikh15 Thank you for your PR 👍 . @crocmons I have added 2 issues that are open for everyone to start working on straight away, these are https://github.com/ushahidi/platform/issues/4749 and https://github.com/ushahidi/platform/issues/4750.

**Comment by crocmons** [comment]
> @codewithmide Welcome to Ushahidi! In order to start an issue, you need to follow the steps in this discussion: #4713 Have you set up your developer environment yet?
> 
> @Bilalshaikh15 Thank you for your PR 👍 . @crocmons I have added 2 issues that are open for everyone to start working on straight away, these are #4749 and #4750.

Yeah, sure, I'll try to contribute to those issues. Thank you so much, @Angamanga  ...
