### ISSUE TITLE
Collections: Add validation message when exceeding maximum amount of characters in "Description" field

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4746]
**Reproduction of the issue**
1. Prerequisite: Logged in user
2. Click on "Collections" in the left hand side navigation bar
3. Click in the button "Add collection"
4. Start writing in the field called "Description"

**Expected behaviour**
There is a validation-message when the text in the Description-field exceeds the maximum amount of characters:
<img width="824" alt="Screenshot 2024-03-02 at 08 48 35" src="https://github.com/ushahidi/platform/assets/8624777/d928de00-1624-4c87-8cd5-a12f0f2090bd">

**Actual behaviour**
There is no message and nothing happens when I click "Save"

<img width="1141" alt="Screenshot 2023-08-18 at 18 04 06" src="https://github.com/ushahidi/platform/assets/8624777/f054a48a-9392-4b31-ba51-53ae249c67d7">

---
Created automatically from USH-761 (https://linear.app/ushahidi/issue/USH-761/collections-add-validation-message-when-exceeding-maximum-amount-of)

**Comment by Angamanga** [comment]
Created automatically from USH-761 (https://linear.app/ushahidi/issue/USH-761/collections-add-validation-message-when-exceeding-maximum-amount-of)

**Comment by akankshat05** [comment]
can I work on this?

**Comment by mhdamaan79** [comment]
I'd love to work on this! I'm an Outreachy May 2024 applicant.

**Comment by Angamanga** [comment]
@mhdamaan79  Welcome to Ushahidi! In order to start an issue, you need to follow the steps in this discussion: https://github.com/ushahidi/platform/discussions/4713 Have you set up your developer environment yet?

**Comment by mhdamaan79** [comment]
😃 Yes @Angamanga, I've completed my setup (https://github.com/ushahidi/platform/discussions/4713#discussioncomment-8672169). Ready to start working on the issue!

**Comment by Angamanga** [comment]
@mhdamaan79 Please go ahead with this issue! @akankshat05 In order to start an issue, you need to follow the steps in this discussion: https://github.com/ushahidi/platform/discussions/4713 Have you set up your developer environment yet? Once you have done that, ping me on another issue and I'll assign you!

**Comment by Bilalshaikh15** [comment]
@Angamanga please assign it to me if someone isn't able to do it.

**Comment by Appleeyes** [comment]
Can i work on this

**Comment by isiagi** [comment]
Hello, @Angamanga I have the setup ready too. I am an outreachy applicant.
I am ready for this issue too.

**Comment by mhdamaan79** [comment]
Hey @Angamanga, I've raised a pull request to address this issue [#4746 ](https://github.com/ushahidi/platform/issues/4746). You can find it here [#824](https://github.com/ushahidi/platform-client-mzima/pull/824) Take a look and let me know if there's anything else needed or if you have any feedback.
