### ISSUE TITLE
No Error Response on the website when creating a new category fails

### ISSUE THREAD

**Issue by felabel** [ushahidi/platform#4751]
To replicate;
Go to settings/categories through the side bar
Create a new category and save, if the process fails

Expected Result - There should be an error response so the user knows what is wrong
Actual result - on error, nothing happens on the UI, user is left confused on next steps.

<img width="792" alt="Screenshot 2024-03-06 at 05 47 14" src="https://github.com/ushahidi/platform/assets/63490084/84767689-667a-4afb-82a1-8bdb68c81eb2">

**Comment by Angamanga** [comment]
Thank you for adding this issue @felabel 🙏

**Comment by felabel** [comment]
@Angamanga please let me know if this is enough

To replicate;
1. Go to settings/categories through the side bar
2. Create a new category and save
3. if the process fails (this process failing scope assumes that there might be an error from the backend, server issues or API related issues) What I did was to cause a typo error in the API request and noticed the error handling defect
4. This would also cover if there is an network error

Expected Result - There should be an error response so the user knows what is wrong
Actual result - on error, nothing happens on the UI, user is left confused on next steps.
