### ISSUE TITLE
404 error appears when entering route for post in Under review status as unauthorized user

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4755]
**Description:**  When unauthorized user/user without Manage Post permission enters route to posts with “Under review”/“Archived” (from admin for example), the error with 404 status appears instead of 403 status.

**Attachment:**

<img width="1680" alt="Screenshot 2023-08-17 at 14 04 24" src="https://github.com/ushahidi/platform/assets/467393/3ce77402-f987-4691-8b7e-6916211b9f56">

---
Created automatically from USH-753 (https://linear.app/ushahidi/issue/USH-753/404-error-appears-when-entering-route-for-post-in-under-review-status)

**Comment by Bilalshaikh15** [comment]
@tuxpiper cant see the attachment can you please reupload it.

**Comment by tuxpiper** [comment]
@Bilalshaikh15 sorry about that, and thank you for the notice. I've re-uploaded the image.
