### ISSUE TITLE
[Outreachy Task Submission] Feature/ Design issue in Blog page

### ISSUE THREAD

**Issue by SakshiVar** [ushahidi/platform#4767]
**Which user group(s) are the primary audience for this feature/enhancement.**
People who go through website on daily basis and reads the blog post.

**Is your feature request related to a problem? Please describe.**
Design issue ---There is no proper alignment in between horizontal scrollbar and the tags in the blog page.

![image](https://github.com/ushahidi/platform/assets/112648026/6a400649-651a-4719-9e66-6ec91ed746e1)

![Screenshot 2024-03-07 174822](https://github.com/ushahidi/platform/assets/112648026/a5b1dfe5-b9aa-44d2-ad97-84e68d7b372a)
**Describe the solution you'd like**
We can remove that horizontal scrollbar and add a button namely "show more"  or an icon. On clicking ,it will expand and show all the tags.

@Angamanga ,Please assign this issue to me under Outreachy 2024 , I'm working on it.

**Comment by Angamanga** [comment]
@SakshiVar Thank you for this issue! The scope of the task is to look at The Ushahidi Platform client, not our company webpage. If you haven't already, the setup can be found here: https://docs.ushahidi.com/platform-developer-documentation/v/set-up-the-developer-environment-for-ushahidi/. Also look through my pinned messages in Discord on how to get around the API-setup in case you run into problems setting it up.
