### ISSUE TITLE
Clear button immediately dismisses the the drop-down. 

### ISSUE THREAD

**Issue by Felysilver** [ushahidi/platform#4768]
Clear button immediately dismisses the drop-down. The user might want to clear the inputs(selections) in the drop-down in order to make a different input. This prevents then from changing selections easily.

[clear.webm](https://github.com/ushahidi/platform/assets/162261453/5860061e-c001-4966-9899-410da24f605d)

**Comment by mhdamaan79** [comment]
Hey @Angamanga, I'd love to work on this. Please assign it to me.
