### ISSUE TITLE
[Outreachy Task Submission] Readability and Accessibility Improvement: Onboarding Final Note.

### ISSUE THREAD

**Issue by Remi-dee** [ushahidi/platform#4770]
### Description
The final note in the onboarding has a minor grammatical improvement for smoother readability, contributing to enhanced accessibility. 

### Current State
![onboardtest](https://github.com/ushahidi/platform/assets/96704300/598be457-4626-4769-9175-28d575481e6b)

The current state of the text includes a small grammatical inconsistency, and the phrase "Help&Support" is used instead of "Help & Support."

### Suggested Change
"How exciting! Now that you know the most important features, you're ready to start using the Ushahidi platform.

Remember, in case of any questions, don't hesitate to reach out to our team through Help & Support."

**Comment by MugoBrian** [comment]
Hello @Remi-dee . Do you mean "Help & Support" instead of "Help & Supports"?
