### ISSUE TITLE
[Outreachy Task Submission] Language Dropdown Icon Malfunction After Language Switch

### ISSUE THREAD

**Issue by mhdamaan79** [ushahidi/platform#4772]
**Describe the bug**
Upon attempting to switch languages using the Language dropdown menu, I encountered a bug where the dropdown icon fails to function correctly. Specifically, after selecting a different language from the dropdown menu, the icon representing the dropdown menu remains stuck in the upward position. This issue persists for languages such as Bulgarian (Bulgaria), Chinese (Taiwan), French (France), and Portuguese (Brazil), where the dropdown icon disappears altogether after language selection.

**To Reproduce**

1. Navigate to http://localhost:4200/map
2. Click on the Language Dropdown menu.
3. Attempt to switch the language to another option.
4. Observe that the dropdown icon does not revert to its default downward position after language selection, or in some cases, disappears entirely.

**Expected behavior**
The expected behavior is that when a user selects a different language from the dropdown menu, the dropdown icon should revert to its default downward position, indicating that the dropdown menu is closed. Currently, the dropdown icon remains stuck in the upward position even after language selection, requiring the user to click twice on the language dropdown to restore the icon to its normal downward position.

**Please refer to the Image and Video for a comprehensive view of the issue:**
**Video**
https://github.com/ushahidi/platform/assets/118375524/9838bd8a-7475-4c99-aece-a7e71724f581

**Screenshots**
![ulim](https://github.com/ushahidi/platform/assets/118375524/421aa998-c7e1-42b0-bed4-f1b40766aefe)
![ulim](https://github.com/ushahidi/platform/assets/118375524/05d9694f-3724-42b4-bf47-a52614d917e4)

This issue significantly impacts the user experience and should be addressed promptly to ensure smooth navigation and functionality within the application.

I'm keen on resolving this and will submit a PR shortly. Please assign and add the **Outreachy Task Submission** Label to this issue.

**Comment by Felysilver** [comment]
_Thanks for raising that @mhdamaan79 its really should fix issue ticket._ 
[drop-down.webm](https://github.com/ushahidi/platform/assets/162261453/2ec27a5e-325e-44bb-b11e-4774e526884d)
_Success on fixing it_

**Comment by mhdamaan79** [comment]
Hey @Angamanga, I've raised a PR ([ushahidi/platform-client-mzima/pull/841](https://github.com/ushahidi/platform-client-mzima/pull/841)) and would appreciate your feedback on it. Could you please review it? Thank you!
