### ISSUE TITLE
[Outreachy Task Submission] Accessibility Issue - Improve the "object Object" Error Toast Notification

### ISSUE THREAD

**Issue by crocmons** [ushahidi/platform#4778]
### Issue Description:
When navigating to the specified [URL](https://ilmasalsabil.ushahidi.io/settings/data-import) and attempting to import a CSV file, if the operation fails due to a large file, an error toast notification is displayed. **However, the current notification message only says 'object object,' which is unclear and uninformative for the user.** As an Outreachy applicant, I aim to address this issue by crafting a more meaningful error notification toast message that provides users with clear guidance on the encountered error.

### Steps to Reproduce:
1. Navigate to [URL](https://ilmasalsabil.ushahidi.io/settings/data-import).
2. Attempt to import a CSV file.
3. Encounter a failure due to the large file size.
4. Observe the displayed error notification message.

### Expected Behavior:
The error notification message should provide clear and informative guidance to the user regarding the encountered error, specifically addressing the issue of the large file size.

### Actual Behavior:
The error notification message displays 'object object,' which lacks clarity and does not inform the user about the nature of the error.

### Additional Information:
- Screenshot: ![Screenshot](https://github.com/ushahidi/platform/assets/106610322/cbd2acbe-b120-477b-a4b4-59b87c13b977)

- This issue is related to improving user experience and accessibility by enhancing error messaging.
- Outreachy Task Submission Label: #4750

**Comment by pxiy-a** [comment]
is this issue still open?Can i work on it?

**Comment by crocmons** [comment]
> is this issue still open?Can i work on it?

no, I'm working on this issue.. kindly take other one # @pxiy-a
