### ISSUE TITLE
[Outreachy Task Submission] Make Categories Section Fully Accessible (Screen Readers and Keyboard Navigation)

### ISSUE THREAD

**Issue by Aquilaafuadajo** [ushahidi/platform#4779]
**Description**
Currently, the Categories section is not fully accessible. The following are the accessibility issues identified with this section: 
- Focused category item doesn't respond to enter keyboard event
- remove routerLink from h4 so the text don't receive additional focus when tabbing
- On Bulk actions, checkboxes do not respond to enter keyboard event
- Add Translation checkboxes do not respond to enter keyboard event

**Comment by pxiy-a** [comment]
is this issue still open?Can i work on it.
