### ISSUE TITLE
[Outreachy Task Submission] Buttons do not have an accessible name

### ISSUE THREAD

**Issue by mo-gbolahan** [ushahidi/platform#4805]
![Screenshot (8)](https://github.com/ushahidi/platform/assets/31252159/700ea178-5ad7-4cc1-b27c-950518837fb0)

The button circled in blue lacks an accessible name, posing difficulty for individuals with visual impairments to discern its function.

**Comment by kivenalaric** [comment]
@Angamanga please can you assign me this if no one is already working on it or ready to.

**Comment by MundiaNderi** [comment]
@Angamanga I've already worked on all these buttons last week and raised a PR for it: https://github.com/ushahidi/platform-client-mzima/pull/830
