### ISSUE TITLE
Tooling-task - open to everyone!

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4808]
There are many different tools that helps evaluate accessibility in an existing codebase and these can be of great help for developers working on code.

The task for you now is to look for different command line tools that is out there that would suit our codebase, pick one and try it out. Add it to our codebase and then submit a PR with your code and the following information:

1. As part of the title, write [Outreachy Testing Task]
2. Add a description about what tool you added and a short evaluation:
    1. Why did you select this tool?
    2. How do you like it?
    3. Does the output make sense to you?
    4. Was it easy or really hard to implement?
    5. Do you “trust” the output or do you think it miss something?
    6. Any other comments or insights you would like to share

**Comment by Mekebib-Ergudo** [comment]
Hey there, I can work on this task happily!!

**Comment by kivuvarosekivuvan** [comment]
@Mekebib-Ergudo It's open to everyone as the name states **"Tooling-task - open to everyone!"**

**Comment by lillian-busingye** [comment]
[ [Outreachy Testing Task]Add axe Accessibility Linter as an accessibility testing tool #944]https://github.com/ushahidi/platform-client-mzima/pull/944
