### ISSUE TITLE
[Outreachy Task Submission] - Text Color Visibility Issue: Share Button Text Not Clear Enough on Mobile View

### ISSUE THREAD

**Issue by JO-YE** [ushahidi/platform#4809]
## Describe the bug:
- **Affected Element**: Share button on mobile view.
- **Observed Behavior**: The text color in the share button appears too light, making it difficult to read or not clearly visible against the background.
- **Platform and View**: This issue occurs specifically in the mobile view of the application.
- **Context**: The share button is located within a container with a certain background color, which affects the contrast with the text color.

## To Reproduce
1. Go to https://racheal.ushahidi.io/map 
2. Minimize to mobile view
3. click on the menu( 3 horizontal lines at the top right)
4. the ***share button*** container is located at the bottom center

## Screenshot
![text colour not visible enough](https://github.com/ushahidi/platform/assets/111038087/799059b8-4a2f-4b84-a297-bac94dd4692b)

## Expected Behavior: The text color in the share button should be darker or more visible, ensuring clear readability against the background.

**Comment by RWUBAKWANAYO** [comment]
Hi @Angamanga , as an Outreachy applicant, I've completed the setup of the project locally. I'd like to work on this issue, could you please assign it to me?



![Image](https://github.com/ushahidi/platform/assets/68381641/c01ddfc6-d51a-48ea-8158-f33d425334ae)
![Image](https://github.com/ushahidi/platform/assets/68381641/6ee3e6ef-3779-4baf-9b83-44d7f5ea616a)

**Comment by JO-YE** [comment]
yes, it has been updated. Thanks

**Comment by Angamanga** [comment]
@JO-YE @MugoBrian Thanks for confirming! Closing this issue 👍
