### ISSUE TITLE
[Outreachy Task Submission] Language Dropdown Icon Missing for the Other Languages

### ISSUE THREAD

**Issue by kivuvarosekivuvan** [ushahidi/platform#4812]
**User group that are the primary audience for this feature enhancement.**
- This feature primarily caters to users who wish to customize the platform's language according to their preferences.

-  However, at present, the language selection dropdown icon is not accessible for Bulgarian, Chinese, French, Persian and Portuguese Language. When switching to these languages, the dropdown icon is not currently available.

![Group 4 (2)](https://github.com/ushahidi/platform/assets/124133577/166dcc00-7636-4b7d-af4b-933ab4aa1398)

![Group 3 (1)](https://github.com/ushahidi/platform/assets/124133577/b9bf223c-bca3-4eec-b575-d0a6170ef81f)

**Why this feature is important.**
- Implementing this language dropdown icon, users will have a positive impact by improving accessibility and they are able to understand that they can switch to different languages.

**Describe the solution you'd like**
- To ensure that the dropdown icon remains available even after switching to above named languages.

**Describe alternatives you've considered**
-  Creating separate language-specific dropdown icons: we could make separate dropdown icons for each language. This way, each language would have its own icon, making it easier for users to find and select their preferred language.

**Comment by MugoBrian** [comment]
Hello @kivuvarosekivuvan , this issue affects some of the languages but not all. 
Just a pointer, the languages with two-letter abbreviations have the arrow down/up icon but more than it is being pushed to the right hence not visible to the user.

Kindly confirm this.

**Comment by kivuvarosekivuvan** [comment]
@MugoBrian Yes, I have clearly stated that on the issue and also specified the languages being affected
