### ISSUE TITLE
[Outreachy-WhatsApp] Develop a basic test case to ensure the functionality and reliability of the proposed features.

### ISSUE THREAD

**Issue by dukedanny** [ushahidi/platform#4848]
**This pre-task involves developing a basic test case to ensure the functionality and reliability of one of your proposed functionalities in the WhatsApp integration:**

The initial test case you're developing focuses on the proposed features and their functionalities.  Since you're familiarizing yourself with the project at this stage, a black-box testing approach using available documentation and discussions is perfectly suitable.

- Choose a specific feature from the project discussion (e.g., sending and receiving data via WhatsApp).

- Design a test case scenario outlining the expected inputs, outputs, and behavior of the functionality.

- Implement the test case using relevant tools and libraries (i.e., Ushahidi uses Cypress as our preferred testing framework).

- Execute the test case and document the results, including any successes or failures.

**Deliverables:**

- Provide a clear description of the chosen functionality and the test case scenario [Comment out this description in your code submission]

- Share the implemented test case code using [GitHub Gists ](https://gist.github.com/)and paste the link as a comment to this issue.

**Due Date:**

26th March 2024

**Comment by ademolaomosanya** [comment]
This a nice task 
will give it my best
Thanks @dukedanny

**Comment by jatinder14** [comment]
I am working on it

**Comment by Tanyadw** [comment]
I am currently working on this task, and want to assure that I will give it my best effort. I am eager to learn and explore throughout this process and look forward to contributing positively. Thanks @dukedanny

**Comment by shailpujan88** [comment]
I am approaching this task with utmost dedication, eager to learn and grow with every challenge. I look forward to making a positive contribution and am committed to giving it my all.Thanks @dukedanny

**Comment by crocmons** [comment]
Hello @dukedanny, I completed this pre-task and it successfully works. Here is my task submission github gist link  - https://gist.github.com/crocmons/a1504e35c60f7635b9b0689d67967910

**Comment by larrytamnjong** [comment]
Hello @dukedanny , here is the link to my GitHub gist for this task: https://gist.github.com/larrytamnjong/4774179f4486ab7a624cc499d7c9b08c

### Tamnjong Larry Tabeh

**Comment by anushk4** [comment]
Hello @dukedanny 
I have completed the week 2 tasks. The GitHub link has been attached
https://gist.github.com/anushk4/7c5bf1575944a1c7c3bd69d47b5a32d3

I have also attached the resources used, test case scenario and result, and the challenges I faced while implementing this, in the comments of the gist.

**Comment by anjalichaturvedi** [comment]
Hello @dukedanny,
Completed and uploaded another pre-task with description commented out + both the screenshots attached. You can find it: https://gist.github.com/anjalichaturvedi/dd19eb4820406754e76b568b8c88e2c1

**Comment by crocmons** [comment]
> Here is the **"WhatsApp send message via Infobip"** feature tested by using **cypress** framework. @dukedanny
> 
> ![Screenshot (98)](https://private-user-images.githubusercontent.com/89455433/316287289-19b77a6d-dbae-46b3-8da4-ae8883afad5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNjY1NjEsIm5iZiI6MTcxMTI2NjI2MSwicGF0aCI6Ii84OTQ1NTQzMy8zMTYyODcyODktMTliNzdhNmQtZGJhZS00NmIzLThkYTQtYWU4ODgzYWZhZDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA3NDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NWNkZGRiZWQ5OWMxNTY5NjZhMzEyYWUwM2JlYTRlMjlhMTI4YTc3ZjM0NzJlOGFjZjg3YzhlZWQxNzIyMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TtAg8BQ4IKQoA0_um8IVJt0Y27v2Tv0XMB83tcq06Zw)
> 
> **gist link** - https://gist.github.com/jatinder14/2064e7756777ff5b96db041146fda431
> 
> and **video recording** for whole process is - https://drive.google.com/file/d/1vueeC3lkekqTuLe2AWy605XTD9BWIDsY/view?usp=sharing

@jatinder14 why you copy the same template from mine?

**Comment by crocmons** [comment]
> Here is the **"WhatsApp send message via Infobip"** feature tested by using **cypress** framework. @dukedanny
> 
> ![Screenshot (98)](https://private-user-images.githubusercontent.com/89455433/316287289-19b77a6d-dbae-46b3-8da4-ae8883afad5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNjY1NjEsIm5iZiI6MTcxMTI2NjI2MSwicGF0aCI6Ii84OTQ1NTQzMy8zMTYyODcyODktMTliNzdhNmQtZGJhZS00NmIzLThkYTQtYWU4ODgzYWZhZDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA3NDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NWNkZGRiZWQ5OWMxNTY5NjZhMzEyYWUwM2JlYTRlMjlhMTI4YTc3ZjM0NzJlOGFjZjg3YzhlZWQxNzIyMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TtAg8BQ4IKQoA0_um8IVJt0Y27v2Tv0XMB83tcq06Zw)
> 
> **gist link** - https://gist.github.com/jatinder14/2064e7756777ff5b96db041146fda431
> 
> and **video recording** for whole process is - https://drive.google.com/file/d/1vueeC3lkekqTuLe2AWy605XTD9BWIDsY/view?usp=sharing

Hi @jatinder14 why you copy the same template from mine? kindly choose another template

**Comment by xadina02** [comment]
Hello @dukedanny
I have completed the task 2 and below is the link to the Github Gist
https://gist.github.com/xadina02/d23c5aeb7fde894d03366f24970b01e0
All related files and the result screenshot are provided, equally with clear description of scenarios.
Thank you and the Ushahidi team for the opportunity to contribute. I lam eager for more such tasks!

**Comment by shalini1008** [comment]
Hello @dukedanny  , here is the link to my GitHub gist for this black box testing task:
link of gist: https://gist.github.com/shalini1008/b2a9eeb2f017c043639fb87671ad970a

**Comment by azigabriel65** [comment]
hello mine is here https://gist.github.com/azigabriel65/b50858e71ee235f7b665817ab0fa096f

**Comment by xfy0012** [comment]
hello @dukedanny here is the link to my github gist for this black box testing https://gist.github.com/xfy0012/94f4b9d3b1bbad0e1eb07f1626f4ad8a

**Comment by Jlp06** [comment]
Hello @dukedanny 
Here is the link to my GitHub gist: https://gist.github.com/Jlp06/c73709ce1ee8c5327b08d1fd220e0f55
I have also attached the screenshots and video recordings of the testing.

**Comment by haruharu1017** [comment]
hi @dukedanny, i am Anastasia
Here is the link to my github gist: https://gist.github.com/haruharu1017/138c3044b963ca1205d92b4523640d95
I have already uploaded my description and test code. Below is my screenshot of tests. 


![Image](https://github.com/ushahidi/platform/assets/149924384/225adad4-2ef6-444c-b1ac-0d3bf563439c)


![Image](https://github.com/ushahidi/platform/assets/149924384/49b2dcb2-3329-42b1-a04a-d87775d153a8)

**Comment by Zortura** [comment]
Hi @dukedanny this is my submission for this pre-task. Its a little late because I had a medical crisis and fortunately I'm better now. It definitely will be perfected with time but I'd like to just drop this first.
Github gist link- https://gist.github.com/Zortura/92d31745ff5a01c8b531d2a2917a08e2
Cypress test Video Demonstration - https://drive.google.com/file/d/1GmCbgQ0m0jTDxZorLY6xdPw00GUkz-Db/view?usp=drive_link
