### ISSUE TITLE
[Outreachy Task Submission] Collection's page list items not Opening for Logged out Users

### ISSUE THREAD

**Issue by Chiemezuo** [ushahidi/platform#4851]
# Introduction
To truly test Accessibility for all users, I've been comparing experiences for logged-in users vs non-logged-in users. I noticed that in the `Collections` page, none of the list items when clicked actually shows information on the page.

## Where was the bug observed
I discovered it in the `collections` page, but as a user that isn't logged in.
A sample URL would be something like "https://test.ushahidi.io/map/collection/657" or with localhost: "localhost:4200/map/collection/657"

## To Reproduce
1. Go to your deployment homepage.
2. Log out if logged in.
3. Click on the `collections` navigation.
4. When the modal opens up, click on any of the items in it.
5. Notice it leads to a page refresh. Also, notice that you do not see anything other than a blank map
6. Login.
7. Perform steps 3 & 4.
8. Notice that after the page triggers, the information on your screen will match the collection that was clicked on.

## Expected behavior
Since non-logged-in users can seemingly create collections, they should also be able to view entries that belong to certain collections that are not private.

## Desktop Hardware Details:
 - OS: Windows 11
 - Browser: Chrome version 122.0.6261.129

**Comment by Chiemezuo** [comment]
@MugoBrian I'm not entirely sure what they had in mind, so I can't tell if it's a bug of a feature.
I generally lean towards displaying only what is accessible to users.

**Comment by MugoBrian** [comment]
You can do some experiments, check the permissions in the role, the logic for displaying the collection, the authentication logic also. Feel free to play around.
