### ISSUE TITLE
 [Outreachy Task Submission] Accessibility Issue: Fix Keyboard Navigation for all Add Field Modal

### ISSUE THREAD

**Issue by blessdamy** [ushahidi/platform#4875]
**Description**:
       When the Add Field Modal is opened, navigating past the "Add field description (optional)" input seems impossible using the keyboard ("Tab" key).

**Expected Behavior**:
       When the Add Field Modal is opened, navigating past the "Add field description (optional)" input with the "Tab key" should move the cursor to the next content, which is the toggle for "Required".

**Actual Behavior**:
       When the Add Field Modal is opened, the "Tab key" inserts multiple space characters in the input field and stays there. It does not move to the next content, which is the toggle for "Required"

![Iss4](https://github.com/ushahidi/platform/assets/111387281/ab575bbb-a418-4ebe-93e4-d520e95291dd)

**Comment by blessdamy** [comment]
Hi @Angamanga 

Here is the issue I spoke about

**Comment by Angamanga** [comment]
@blessdamy I see, this is something called a "focus-trap", where the user gets stuck. The editor we use is a third-party library called "Quill-editor", https://github.com/KillerCodeMonkey/ngx-quill and https://quilljs.com/. If I was to approach this issue, I would start looking at the documentation for that and see if they have any pointers, or if someone else has ran into the same problems (I am sure there are :) )

**Comment by blessdamy** [comment]
Thank you @Angamanga 

Wow, I just learnt what  "focus-trap" is, thank you:)
I will do well to go through both documentations and drop a feedback.
