### ISSUE TITLE
[Outreachy Task Submission] Navigation hitches in "help & support" screen

### ISSUE THREAD

**Issue by Chiemezuo** [ushahidi/platform#4877]
# Introduction
This is a navigation issue I found in the `help & support` modal of the site that will most likely be inconvenient for screen readers and users with alternative forms of navigation. When a user clicks on a link in the `help & support` modal, it opens a new tab. On its own, this can be inconvenient. However, the bigger problem is that the modal opens after an item in it has been clicked. This would mean that a user would have to navigate from scratch if they wanted to click on something else within that modal.

## To Reproduce
1. Go to your deployment page (or your `localhost:4200` homepage).
2. Log in.
3. Click on `help & support`.
4. When the modal pops up, click on any of the listed items there.
5. You will notice that it redirects you to a different page, but on a new tab. Go back or close this current tab.
6. You will find yourself back on the tab you opened your deployment in, but you will notice that the modal is no longer there.
7. You will also notice that you have to repeat step 3 to make the modal open again.

## Expected behavior
The expected behavior is that the modal shouldn't close even after a redirect on a different tab.

## Workaround
The workaround would be to remove the mechanism that makes the modal close when an item is triggered.

## Desktop Hardware Details:
 - OS: Windows
 - Browser: Chrome
 - Version: 122.0.6261.129

**Comment by Angamanga** [comment]
@Timonize What is the behaviour we want to have for the support-modal really? Close the modal after clicking one of the support-links or keep it open?
