### ISSUE TITLE
[Outreachy Task Submission]: Instant validation error for current email input in profile settings(mobile)

### ISSUE THREAD

**Issue by RWUBAKWANAYO** [ushahidi/platform#4892]
### Description:
This issue addresses the validation error behavior in the profile settings when editing the email. Currently, the validation error for the current email input appears instantly without any user interaction triggering the error.

### To Reproduce:
1. Launch the mobile application using `npm run mobile:serve`.
2. Select a deployment or create a new one.
3. Log in to the application.
4. Click on the profile icon at the bottom navbar.
5. Within the popup, click on "Profile Information."
6. Within the popup, click on "Change Email."
7. The error message "The entered email does not match the current email. Please make sure to enter the correct email address." is immediately displayed on the current email input.

### Expected Behavior:
The error message should only appear when the user interacts with the validated input or attempts to submit the form without filling in the required input.

### Desktop Hardware Details:
- Operating System: iOS
- Browser: Chrome
- Browser Version: 122

### Additional Context:

https://github.com/ushahidi/platform/assets/68381641/93ced215-eb0e-4aff-8b10-e29fabd76a83

@Angamanga, could you please assist in adding the Outreachy Task Submission Label to this issue? I'm planning to work on resolving it.

**Comment by Angamanga** [comment]
@Angamanga In QA
