### ISSUE TITLE
[Outreachy Task Submission] Profile Update Not Reflecting in Home Screen

### ISSUE THREAD

**Issue by crocmons** [ushahidi/platform#4901]
**Issue:**
When a user or admin logs in and attempts to change/update their username and email by accessing the "Account Settings" through the profile dropdown menu, the changes made in the settings modal are not reflected in the profile icon dropdown menu on the home screen. Despite clicking the "Save" button after updating the information, the changes do not update on the home screen.

**Steps to Reproduce:**
1. Log in as a user or admin.
2. Click on the profile icon to access the dropdown menu.
3. Select "Account Settings" from the dropdown menu.
4. Update the username and email in the settings modal.
5. Click on the "Save" button.
6. Navigate back to the home screen and observe the profile icon.

**Expected Behavior:**
After updating the username and email in the account settings modal and clicking on "Save", the changes should reflect immediately in the profile icon dropdown on the home screen. The username and email displayed in the profile dropdown menu should be consistent with the updated information.

**Actual Behavior:**
Despite saving the changes in the account settings modal, the updated username and email are not reflected in the profile icon on the home screen. The profile dropdown menu continues to display the previous username and email.

**Potential Causes:**
1. Synchronization issue between the account settings modal and the home screen profile dropdown.
2. Error in the update function that fails to update changes to the frontend.
3. I guess this is because the backend server is not properly updating user information in the database.

**Screenshots**:
![Screenshot - 2024-03-29T155406 432](https://github.com/ushahidi/platform/assets/106610322/349d9151-c0b9-4a3b-9a4c-a49ddc9916f6)

[screencast-127.0.0.1_4200-2024.03.29-06_53_01.webm](https://github.com/ushahidi/platform/assets/106610322/b613536f-4b80-44cd-865e-17f6be6681da)

# Proposed Solution:
1. Investigate the code responsible for updating user information in the account settings.
2. Verify the data flow from the backend to the frontend to ensure consistency.
3. Implement a mechanism to trigger a refresh/update of the profile icon on the home screen upon successful saving of changes in the account settings.
4. Conduct thorough testing to confirm that changes made in the account settings reflect accurately across the application.

**Additional Information:**
As an Outreachy applicant, I am eager to contribute to resolving this issue and improving the user experience and accessibility of the application. I will delve into the codebase, identify the root cause of the problem, and propose a solution following best practices. I look forward to collaborating with the team to address this issue effectively.

@Angamanga @Ifycode kindly look at this issue ...

**Comment by Angamanga** [comment]
@davidlosada I think we could add this issue to next sprint.

**Comment by Angamanga** [comment]
@crocmons Thank you for adding this well described issue 🙏
