### ISSUE TITLE
[Outreachy Task Submission] Remove Extra Focus From Add Buttons On Keyboard Navigation

### ISSUE THREAD

**Issue by Aquilaafuadajo** [ushahidi/platform#4902]
**Description**
Currently the add new buttons behave weirdly when navigating using just keyboard. The button has to be tabbed twice before it responds to the enter event. 

**Why does this happen?**
This happens because the mizima-client-buttons in this cases are router links and router links come with their own focus when tabbed into, so this focus + the buttons default focus results in tabbing twice before the button responds to the enter event.

**Fix**
Set tabindex to -1 on mizima-client-buttons when it's being used as a router link to prevent this extra focus.

**Comment by MugoBrian** [comment]
No need I have seen the steps in the PR.
