### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kahenya** [ushahidi/platform#594]
Using this source package (https://github.com/ushahidi/platform/releases/download/v3.0.0/Ushahidi-Platform-v3.0.0.tar.gz), and following instructions down to the last letter, I've been getting this error, since launch day. Have tried two different machines, and I keep ending up here. I've been able to do an update using %bin/update successfully, but it outputs the same error message at the bottom. Am I doing something wrong? Also note, I haven't been able to run the git build successfully at all, no idea why.

Thanks.

Debian Jessie 8, nginx 1.6.2, php5-fpm 

{
    "errors": [
        {
            "message": "Class 'Database_' not found",
            "code": "Fatal Error",
            "class": "ErrorException",
            "file": "/var/www/xxxxxxxxxxxx/html/platform/vendor/ohanzee/database/src/Database.php",
            "line": 76,
            "trace": [
                {
                    "function": "shutdown_handler",
                    "class": "Kohana_Core",
                    "type": "::",
                    "args": []
                }
            ]
        }
    ]
}

**Comment by rjmackay** [comment]
How are you configuring the database? using .env?
It looks like you haven't configured the `DB_TYPE`
in .env you should have `DB_TYPE=MySQLi`

**Comment by kahenya** [comment]
Errrr, you have lost me a bit. This is what I have in my database.php file.


if (getenv("CLEARDB_DATABASE_URL")) {
	$url = parse_url(getenv("CLEARDB_DATABASE_URL"));
	// Push url parts into env
	putenv("DB_HOST=" . $url["localhost"]);
	putenv("DB_USER=" . $url["root"]);
	putenv("DB_PASS=" . $url["password"]);
	putenv("DB_NAME=" . substr($url["dbname"], 1));
	// Assuming ClearDB is always MySQLi
	// @todo parse $url['scheme'] instead
	putenv("DB_TYPE=" . "MySQLi");
}

**Comment by rjmackay** [comment]
Right.. which instructions have you been following?
Did you run vagrant? or create a `.env` manually?

**Comment by kahenya** [comment]
Manually. 

Though, I'm not sure I get the .env story. I followed the instructions on the Ushahidi wiki and that's what I kept getting.

**Comment by rjmackay** [comment]
Oh. Install instructions moved here: docs.ushahidi.org/install/
Let me go remove the outdated wiki ones.

If you can link me to exactly which wiki ones you used I can help debug from where you are?
You need to have either created a `.env` file which contains something like
```
DB_HOST=localhost
DB_NAME=username
DB_PASS=password
DB_TYPE=MySQLi
DB_USER=ushahidi
```
or an file in `application/config/environments/development/database.php` which sets all your database values.

**Comment by kahenya** [comment]
OK. Will give feedback on this when I get to my machine in the AM. If sorted, will close. 

Thanks.

**Comment by kahenya** [comment]
No luck.

A new error has arisen.

{
    "errors": [
        {
            "message": "Class 'mysqli' not found",
            "code": "Fatal Error",
            "class": "ErrorException",
            "file": "/var/www/overlap.co.ke/html/platform/application/classes/Database/MySQLi.php",
            "line": 52,
            "trace": [
                {
                    "function": "shutdown_handler",
                    "class": "Kohana_Core",
                    "type": "::",
                    "args": []
                }
            ]
        }
    ]
}

First struck out running bin/update

**Comment by rjmackay** [comment]
That sounds like you're missing the mysqli extension to php? 
If you run `php -m` is mysql in the list of modules?

**Comment by kahenya** [comment]
Silly me. I had to get a fresh machine that I have just deployed, and completely forgot to install that.

Now, I'm at gulp build. I've build my .env file and put in BACKEND_URL=http://mydomain.tld/

npm install was full of horrors that look like this

gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/xxxxxxxxx/html/platform-client/npm-debug.log
npm ERR! not ok code 0


Which probably explains why gulp build does this.

/usr/bin/env: node: No such file or directory

**Comment by kahenya** [comment]
I'm putting this aside for now. 

Thanks for the help.

Cheers.

**Comment by rjmackay** [comment]
Alright thanks. I think I've been fighting the same issue with npm builds.. If you're running on linux you may need some build tools for the npm install to succeed, you might also need an nodejs build from nodesource or npm. Debian ships an old nodejs package so thats likely the issue.

Trying installing node 0.12 from here: https://github.com/nodesource/distributions
and make sure you have the `build-essential` package installed (on debian)

Once I figure out exactly the requirements I'll document those.
