### ISSUE TITLE
Create deployment worker

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#636]
How do we run migrations on deployment creation?

Process:
- Cloud app add a job to queue
- Worker picks up the job
- Worker runs migrations
- ? Set initial config?
- ? Create admin user ?
- Worker pushes a callback to cloud API
- Cloud UX: polls cloud api to check for status
- Cloud app: sends email to user when deployed

Also tracked here: https://phabricator.ushahidi.com/T1705

**Comment by rjmackay** [comment]
Need to chat with Zack about the message queue (I think we're using RabbitMQ) and figure out what the message format looks like.. the rest is really up to us to build as we like.

**Comment by rjmackay** [comment]
@zhalloran sounds like you might already be doing some of this? Can you document where you're building up to and what it would make sense for Jason to jump in on from the platform side?
or if you're covering this entirely and Jason can move on to the next task..

**Comment by zhalloran** [comment]
@rjmackay Outside of new functionality to allow for feature management, I don't think there's anything on the platform side of the house to manage, except...if you could update the migration scripts to allow for passing command line variables for database name and other per-deployment information, that would be helpful. If that functionality is already there, even better.

**Comment by rjmackay** [comment]
You can pass database config etc through environment variables (we use that for heroku builds).
```
DB_HOST=localhost
DB_NAME=username
DB_PASS=password
DB_TYPE=MySQLi
DB_USER=ushahidi
```

**Comment by rjmackay** [comment]
@zhalloran You can now create a user from the CLI.. 
```
bin/ushahidi user create --username joe --email joe@ushahidi.com --role admin --password passwd123
```
is that sufficient to use with the create deployment worker?

**Comment by zhalloran** [comment]
@rjmackay We would need to be able to specify the deployment database as well. Otherwise it's no good. We can't rely on environmental variables.

**Comment by rjmackay** [comment]
right. Whats stopping us just passing environment vars in as you run that command?

**Comment by zhalloran** [comment]
From what I can tell, that command doesn't support passing environmental variables. It get's the db connection from the Kohana instance itself. We want to be able to dynamically set the db independent of the kohana env. Of the top of your head, do you know where the code for salting and hashing the password is? I think I'll just push directly into the database.

**Comment by rjmackay** [comment]
Kohana grabs the DB stuff from the environment so environment params should still work just fine.

If you really need to push directly into the DB you can find User saving code in application/classes/Ushahidi/Repository/User.php and password hashing in application/classes/Ushahidi/Hasher/Password.php .. though it just uses `password_hash` to do the work of hashing.

**Comment by rjmackay** [comment]
```
password_hash($password, PASSWORD_BRCYPT, ['cost' => 15]);
```

**Comment by zhalloran** [comment]
@rjmackay Thanks! Just to clarify, each deployment has it's own virtual environment. The dotenv environment is no good for our purposes. In our hosted environment, environmental variables will be determined dynamically via requests parameters/query results.

**Comment by rjmackay** [comment]
I'm not really sure what you're asking/confirming?
- The .env file should serve to define db params for the central DB only
- For web requests, the db params will get overridden with the deployments db params
- For CLI tasks you should either be able to set the environment vars to point to a  deployments db ie.
```
DB_NAME=abc123 ./bin/ushahidi ...
```
or you can pass in a fake host ie
```
HOST=domain.ushahidi.io ./bin/ushahidi ...
```

**Comment by zhalloran** [comment]
Oh, right. *facepalm*. Thx.

**Comment by zhalloran** [comment]
First draft implemented here: https://github.com/ushahidi/platform-cloud-ansible/commit/bcbdf64efeb8e8df7f015c754ce3ffd09a4fc5d3
