### ISSUE TITLE
Create admin user for new deployment

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#637]
- Possibly part of #636
- Need CLI script for creating a new admin user (useful for OSS deployers anyway)
- Create deployment needs to create a single 'owner' user

**Comment by rjmackay** [comment]
@jasonmule can you grab this? add a task similar to dataproviders or import that allows creating new users ie.
`bin/ushahidi user create --username fred --email fred@ushahidi.com --role admin --password blah`
Does that make sense?

**Comment by jasonmule** [comment]
Yup. Will go ahead and create a minion task for this.
