### ISSUE TITLE
Limit deployment features based on teir

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#638]
- API needs to disable some features if they’re disabled in the config
- Client should hide these features if they’re disabled
- Should be able to query config API and find out *which* features are disabled
- Feature limits will be set in a `feature` config

Current features that should be able to be limited are:
- Views: which views are available /enabled
- Data sources + notification channels ie. Email, SMSSync, etc
- User roles: starter plan only has a single admin, can create new members.
- CSV Upload fields: Can map to custom fields, can only map to title, description (date?)

**Comment by rjmackay** [comment]
Reassigning to Will - lets see who gets to it first though :)

**Comment by hollycorbett** [comment]
I'm back! On this now.

**Comment by hollycorbett** [comment]
Okay @rjmackay, @zhalloran - thoughts/comments welcomed.  The config options thing is clear enough (figure I'll just put it in its own group_name in the config table) - I can get started on that while we debate :)

I can see three obvious potential ways of managing the backend:
1 - using the use-cases pattern
2 - using the acl pattern
3 - a separate piece of infrastructure 
	- a "filter" through which the API endpoints are passed and validated on a method-by-method basis... presumably run in before() of Api.php - after _parse_request but perhaps before "_check_access" (if not in it) - _check_deployment (or whatever is a good name?)

I think the third is best - mostly just cause it feels 'clearer' and like it should be a separate layer to the access.  But whichever :)

On fail, would return a 405 with 'invalid method' for the views, and for data/users/csv I guess a 405 with a more customized error message like 'your deployment does not allow creation/configuration of...'

SEEEWWWWW.... that would mean restricting:

Features

Views (is this all we mean):
 - map - /posts/:id/geojson
 - list - /posts/:id
 - chart - /posts/:id/stats
 - timeline - /posts/:id/stats
 (hrm... are chart and timeline separate features to control access to? obv we can change the display for the frontend but for now its the same data, just queried slightly differently - perhaps we should separate these into two different request paths as a precedent for future work if nothing else?)

Data Sources: here I think this will end up meaning changing the access to settings (i.e. unable to configure the sources)
 - /dataproviders/:id (OPTIONS?)
 - /config/:id (PUT) - where ID is 'data-provider'

Users
 - one admin v many and create new members - /users/:id (PUT) - would need parsed request to control access
 aside - curiously UserEndpoint.save() does not exist, but gets called in setting-users-create-controller.js

CSV Upload
- kinda in the dark about this one - is there a diff/spec I should be looking at to figure out how this is likely to fall out?


As to handling the frontend;

For views: I think it makes sense to query a config/deployment or DeploymentOptions endpoint to only try and load views we have access to.
Datasources can be knocked out of the settings nav menu based on the deploymentoptions endpoint info as above (would it be so wrong to be lazy and put that info in $rootscope?)
"Add User" button can be disappeared, and "change role" dropdown also - presumably if there are only admins and members, and there can only be one admin for some deployments, then the button is pointless.
CSV - see above comments on CSV :)

**Comment by rjmackay** [comment]
- Theres an existing `features` config group. All the settings in it are now defunct so rip those out and use that group
- This should probably be handled in the Authorizer layer if we can - just because the sensible server response when something is denied is a HTTP 403. However we also need to make sure we return a message the client can use to differentiate : deployment doesn't have this feature vs  user doesn't have this features
  - We can probably build it into a trait thats reused by multiple authorizer's though.
- 405 is specifically for using the wrong HTTP verb - so thats not right here.

For each limit:
- Views - these are client side only, so the client should just check which features are enabled before showing these views. We don't need to limit anything on the backend. We should have a feature toggle for each view, easier to tweak later.
- Data sources: This should limit what can be enabled in the data sources view. That is pushed to /config/dataproviders. We should have a feature toggle for each provider, easier to tweak later.
  - A future task might be to update the /dataprovider API too and flag which providers are allowed or not
- Users - I'd skip this for the first iteration: start with things that are all or nothing, not limited by number.
- CSV upload - ignore that till it implemented

Focus on getting a minimal version of this functioning then we can plan for the next iteration.

Note: 
- Endpoint .save and .delete() always exist by default

**Comment by hollycorbett** [comment]
Okay :) cool cool
