### ISSUE TITLE
Map & Scrolling on Mobile Issue

### ISSUE THREAD

**Issue by dkobia** [ushahidi/platform#644]
@middle8media @brandonrosage was wondering how best to have a scrolling zone for the single report view where one gets to that long map. As you know with a long map, its easy to get stuck on scrolling within the map -- see attached. Maybe its just having more padding?

![screenshot_2015-08-24-08-29-29](https://cloud.githubusercontent.com/assets/184092/9440703/13038472-4a3f-11e5-8cc6-cfd4b3cbc6cc.png)

**Comment by brianherbert** [comment]
How about disabling zooming with the mouse when in responsive view and have controls for that? That used to be best practice but I'm not sure what's cool anymore.






On Mon, Aug 24, 2015 at 6:32 AM -0700, "David Kobia" <notifications@github.com> wrote:












@middle8media @brandonrosage was wondering how best to have a scrolling zone for the single report view where one gets to that long map. As you know with a long map, its easy to get stuck on scrolling within the map -- see attached. Maybe its just having more padding?

**Comment by middle8media** [comment]
@brianherbert that could work on desktop, but we need to think about mobile touch as well.

**Comment by brianherbert** [comment]
@middle8media That's what I'm referring to, add map controls and disable mouse scroll zooming.

**Comment by middle8media** [comment]
I supposed "disable mouse scrolling" is the same as "disable touch scrolling"

**Comment by brianherbert** [comment]
That's correct

**Comment by middle8media** [comment]
@rjmackay I am wondering the best way to solve this issue and I am sure you have ideas.

Leaflet has http://leafletjs.com/reference.html#map-dragging. This would solve this issue, but would prevent mouse/touch dragging

**Comment by sophshep** [comment]
I think it's important to have it be draggable on larger screens - and potentially even small screens too. The least complicated solution would just to always have a margin to the right of the map that a user can use to scroll. (<-- what kobia already said :stuck_out_tongue: )

**Comment by middle8media** [comment]
@sophshep yeah, if it is draggable on small screens then this issue is still present.

right margin would be a fix

**Comment by sophshep** [comment]
Putting `overflow: hidden` on `#map` is another simple way of making it un-draggable. Then we could easily remove that for larger screens via media queries.

My preference is to have the margin though, because some people may want to drag around within the map on a small screen.

**Comment by brianherbert** [comment]
How does this look on older iPhones / cheaper Android phones where people might want to see the map? Is it possible to allow them to toggle a full screen view (would be a separate feature)?

**Comment by middle8media** [comment]
pinging @rjmackay

**Comment by rjmackay** [comment]
> Putting overflow: hidden on #map is another simple way of making it un-draggable. Then we could easily remove that for larger screens via media queries.

That will have no effect, `overflow: hidden` is the default for a leaflet map.

I think margin is the workable solution here. I'm not clear if this is an issue on all our maps, or just the post detail page? Probably both.

Or to change the layout so there's no need to scroll down (ie. move anything below the map or make it sticky)

**Comment by sophshep** [comment]
Let's go with the margin. Even if we move content above the map, the user could get stuck on the map and not be able to scroll up again. @middle8media can you update?

**Comment by middle8media** [comment]
reopening this so class change in `pattern-library/5_layouts/home-map.html` and css in `assets/sass/4_blocks/_map.scss` can go into the client.

**Comment by middle8media** [comment]
screenshot of the solution

![screen shot on 2015-10-01 at 16-24-16](https://cloud.githubusercontent.com/assets/1033332/10232894/519049e0-6859-11e5-915c-ab6b619a4137.png)

**Comment by rjmackay** [comment]
@willdoran @jasonmule can one of you review this? Need to update markup in the client to match the pattern library I think

**Comment by middle8media** [comment]
yes @rjmackay that is correct.

**Comment by rjmackay** [comment]
@middle8media Can you ensure this is fixed in the client to? Not sure if the markup was ever updated.
