### ISSUE TITLE
Main nav close on click of main content

### ISSUE THREAD

**Issue by middle8media** [ushahidi/platform#649]
The main off canvas nav should close if the dark area to the right is selected. This is a common practice to get back to the main content.

**Comment by middle8media** [comment]
fixed via 2e8db3ab206f0c5d909b0acae6579afb2e0e47ab

**Comment by rjmackay** [comment]
@middle8media if you fix something in the PL.. but its not reflected in the client can you assign to me rather than closing? Otherwise there's a high chance the issue isn't fixed in the next release

**Comment by middle8media** [comment]
Yes. Of course. Sorry about that.
