### ISSUE TITLE
Document recommended methods for installing nodejs on linux

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#651]
Nodejs build issues seen in our ansible scripts and #594

I think we should recommend installing from nvm or nodesource (https://github.com/nodesource/distributions)

Also debian builds need to have `build-essential` installed. Fedora builds need `gcc-c++` and `make` installed.

**Comment by rjmackay** [comment]
@willdoran are you running builds on linux? Whats you're current setup?

**Comment by willdoran** [comment]
I am on linux but I'm using vagrant Nodejs linux in stall is relatively straightforward BUT you have to create a symlink between nodejs and node in /usr/bin - you have to do that step manually, at least on ubuntu strains. Not sure about deb.

**Comment by rjmackay** [comment]
Which nodejs version are you running? installed via apt?

**Comment by willdoran** [comment]
v0.10.25 installed from the linux 64 bit distro source
