### ISSUE TITLE
Misaligned buttons in map popup

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#652]
Map popups http://github.ushahidi.org/platform-pattern-library/assets/html/3_modules/#pl-pattern-post-popup have misaligned action buttons: ﻿https://www.dropbox.com/s/xoziy7v2gh4bsau/Screenshot%202015-08-26%2013.48.01.png?dl=0

**Comment by middle8media** [comment]
https://github.com/ushahidi/platform-pattern-library/commit/6917d84c177d01c20592b4f2434feddeecc36bcb

**Comment by rjmackay** [comment]
Excellent. I'll close this out.. theres another task for building those map popups
