### ISSUE TITLE
Default bg pattern

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#655]
for if a user has not uploaded a background image, this shoudl tile instead of being the solid color. http://github.ushahidi.org/dotcom-pattern-library/assets/img/map-bg.png

I *think* this is done in the platform, but need to update the PL

**Comment by sophshep** [comment]
I've updated the PL, however for this to work properly, the div `.hero-image` can't exist in the code. 

To see what I mean, go to the pattern library and delete that div in the inspector. 

@rjmackay does this work to translate to the client? So that div shouldn't exist until a user has uploaded a custom image.

**Comment by rjmackay** [comment]
Currently the client switches the header image:
- if the header is set we show it
- if not we show the default header
```
                         <img ng-show="site.image_header" ng-src="{{site.image_header}}" alt="" />
                         <img ng-show="!site.image_header" src="img/default-header-bg.png" alt="" />
```

What should we be doing? Can you link to examples of each state in the PL?
Be aware that you might be seeing broken image headers on the demo site because of a problem with image uploads.

**Comment by sophshep** [comment]
Currently in the PL, the default bg img is being served by the CSS as a repeating background. (Go to http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/home-map.html & delete the hero img div in the inspector to see this):
![image](https://cloud.githubusercontent.com/assets/527589/9619123/4b9a08d0-50d2-11e5-9720-3de8c08d106e.png)

Then if a user has uploaded an image, it should be within `.hero-overlay`, which gives it the CSS to stretch on the screen and puts an overlay of semi-transparent color on it. 

So the behavior, if possible, should be:

* if the header is set, it's 
```
<div class="hero-overlay">
    <img ng-show="site.image_header" ng-src="{{site.image_header}}" alt="" />
</div>
```

* if not, that div shouldn't exist and the CSS will take care of the rest

**Comment by rjmackay** [comment]
got it, thanks
