### ISSUE TITLE
Confirm Dialogue Pattern Needed

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#656]
for example, to pop up when a user is trying to delete a post to say "are you sure you want to delete this?"

I think we can extend the Modal.

**Comment by rjmackay** [comment]
@sophshep are you migrating these over from Phab? If so can you make sure you link the original Phab issue, and add the github ID to the phab issue.

**Comment by sophshep** [comment]
I've extended the modal to show how this can be used for a confirm dialogue: http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/modal-delete.html

We can also use the confirmation message for dialogues that don't require action from the user: http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/confirmation.html
