### ISSUE TITLE
Re-code Post Summary

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#657]
This could be done cleaner - rethink different screen sizes, images sizes, etc.

**Comment by rjmackay** [comment]
Maybe tackle #659 with this too?

**Comment by sophshep** [comment]
@rjmackay I've cleaned this up, but the markup has changed a bit. Leaving it open and assigning to you to in case you need to see that change & update client accordingly.

**Comment by rjmackay** [comment]
@willdoran if you get through the other bugs, theres this too

**Comment by jshorland** [comment]
Assigning to @willdoran

**Comment by rjmackay** [comment]
Maybe this is the same as #818?
