### ISSUE TITLE
Post summary needs an indicator that a post is published or not

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#659]

**Comment by sophshep** [comment]
Assigning to @rjmackay to get into client

**Comment by jshorland** [comment]
Assign to @sophshep. Language needs to be re-thought around this.

**Comment by rjmackay** [comment]
Worth noting we need to show published/draft status on the post detail pages too

**Comment by rjmackay** [comment]
I think this is resolved by showing who the post is visible to now.

**Comment by rjmackay** [comment]
cc @willdoran can you close this once post summary is updated?
