### ISSUE TITLE
Complete API documentation

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#663]
Complete API documentation in Swagger

**Comment by tuxpiper** [comment]
@rjmackay I was thinking about making some progress here. Should we consider RAML too? It seems to be getting backing from big players (i.e. Paypal)

**Comment by rjmackay** [comment]
We're using API Blueprint on https://github.com/ushahidi/rollcall - so lets match that

**Comment by tuxpiper** [comment]
FWIW here are the priorities for a mobile app developer that came to us looking for assistance

(1)  Register
(2)  Login; 
(3)  Get all posts; 
(4)  Post a report; 
(5)  Get All Post types;
(6)  Get All Post Categories   
(7)  Get Notifications (How you get notifications & What you get notified about)
(8)  Get Maps (posts)
(9)  Get User Info
(10)  Update Password      
(11)  Save User Info Changes
(12)  Get End-user Licence Agreement (EULA)  [not sure what this would be exactly]
(13)  Is there anything for video/ photo uploads?

**Comment by tuxpiper** [comment]
Comments from @willdoran 

actually a good way to see how the apis work is to work from these tests: (edited)

[4:09] 
https://github.com/ushahidi/platform/tree/master/application/tests/features
 
GitHub
ushahidi/platform
platform - Ushahidi Platform v3 API

[4:10] 
for example this describes an OAuth login

[4:10] 
https://github.com/ushahidi/platform/blob/master/application/tests/features/api.oauth.feature
 
GitHub
ushahidi/platform
platform - Ushahidi Platform v3 API

[4:10] 
You can also see these behaviours within the client but they are not collected in a single place

**Comment by rowasc** [comment]
Closing as we took a different approach with gitbooks at the moment
