### ISSUE TITLE
Add more Ush branding to cloud signup flow

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#669]
This page http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/cloud-new-deployment.html

May be jarring users since it looks so unbranded compared to the homepage. What if a user goes straight to this URL without first seeing the home page?

cc/ @brandonrosage @zhalloran

**Comment by rjmackay** [comment]
I actually like the idea that we could link directly to a 'create deployment' page from within docs, etc. So adding some minimal branding could be ideal.
