### ISSUE TITLE
Add 'deploying' layout for waiting around 

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#671]
Add a layout for the 'your deployment is getting built' holding screen on cloud.
Needs to show deployment status, somewhere we can put errors. And a link in case it stalls.

@zhalloran anything else this should have?

**Comment by rjmackay** [comment]
cc @sophshep

**Comment by brandonrosage** [comment]
I've added some markup within the Tour to show what the last panel would look like in the case that the deployment wasn't yet ready: https://github.com/ushahidi/platform-pattern-library/blob/gh-pages/pattern-library/5_layouts/tour.html#L265-L280

Working on a 'Home' screen now that communicates this, as well, in case they visit their deployment URL manually.

**Comment by brandonrosage** [comment]
I've added a "Home - Building" layout that samples how a tour-like, static page would stand in for the deployment until it was finished building: http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/home-loading.html

Note that I've added the `tour.js` [custom script](https://github.com/ushahidi/platform-pattern-library/blob/gh-pages/assets/js/custom/tour.js) to the Platform Pattern Library to capture all the scripting necessary to power any interactions that borrow from the 'Tour' convention.
