### ISSUE TITLE
Change deployment description not working

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#677]
I tried to update the deployment description on the settings > general page. It seemed to work (did not give me any errors) however my change is not reflected in the header.

**Comment by rjmackay** [comment]
Does it reflect if you reload the page?

**Comment by sophshep** [comment]
Ah, that did the trick. A success message (on my list to design) will help to show that it has registered, but if we could have it reflect without a reload that would be great.

**Comment by rjmackay** [comment]
Yup. Its definitely still a bug.. just wanted to be sure what the issue was.
At worst we should trigger the reload on save..
