### ISSUE TITLE
Ability to add info / instructions text to a post type

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#680]
V2 had a text box on the submit report page (see the pink box here https://www.takebackthetech.net/mapit/reports/submit https://www.dropbox.com/s/bqsisijm0xh3wuv/Screenshot%202015-09-02%2011.36.30.png?dl=0)

I think this is still useful in V3, and should probably be defined per-post type.

**Comment by rjmackay** [comment]
@sophshep related to #307 ... do you think we still need this?

**Comment by sophshep** [comment]
This is something we already have in the pattern library, I think. If you go to http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-type-structure.html and then edit one of the fields, there is the ability to add instructions to the field.

**Comment by rjmackay** [comment]
@sophshep the existing pattern is for instructions on an individual field, not on the entire post type, or step.

**Comment by sophshep** [comment]
Ah ha. @brandonrosage and I are working on redesigning this whole flow. I've added this to our google doc so that it gets into the new designs.
