### ISSUE TITLE
Try out Read the docs for cloud

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#685]
We want to get our existing Jekyll content into read the docs so we can test it out.

**Comment by rjmackay** [comment]
@brianherbert do you have time to look at this?
Our docs are currently in github.com/ushahidi/docs.ushahidi.com we want to take that same markdown in read the docs. I'll have a 10 min look at read the docs today, but beyond that I won't have time till next week. Would be great if you could pick this up?

**Comment by rjmackay** [comment]
cc @sophshep

**Comment by rjmackay** [comment]
Ok so I managed to run a rough import here: http://ushahidi.readthedocs.org/
I've also found an old project created by @rrbaker I'll try and get deleted.

**Comment by willdoran** [comment]
Ok, so thus far, I've:
- forked the sphinx_rtd_theme, here: https://github.com/ushahidi/ushahidi_sphinx_rtd_theme
it needs to be cleaned up slightly before it will build but the existing built theme in ushahidi_sphinx_rtd_theme does work
- I've added the theme as a submodule to the docs.ushahidi.com repo and wired it to build
- The build is failing on readthedocs so I've opened a ticket describing the issue.

I'll pick this up again tomorrow.
