### ISSUE TITLE
Dependencies error when build the client

### ISSUE THREAD

**Issue by redhumus** [ushahidi/platform#687]
Hi, I'm leading redhumus.org and have two deployments wiith ushahidi  (http://land.redhumus.org and http://respondiente.redhumus.org   . Now I'm installing usahidi V3. But I have an issue when trying to build gulp
I'm at this step http://docs.ushahidi.org/install/installing-on-linux.html#building-the-client

I'm on a web server running a  GNU Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux

My NodeJS version: v0.12.7
My NPM version: 2.11.3

Here the error when I enter  npm install -g gulp 

root@miservidor:/rutaalweb/plataformaushahidiV3/platform-client# npm install -g gulp/usr/bin/gulp -> /usr/lib/node_modules/gulp/bin/gulp.js
gulp@3.9.0 /usr/lib/node_modules/gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.5
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── tildify@1.1.0 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── semver@4.3.6
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── orchestrator@0.3.7 (sequencify@0.0.7, stream-consume@0.1.0, end-of-stream@0.1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, beeper@1.1.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.3, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
root@miservidor:/rutaalweb/plataformaushahidiV3/platform-client# npm install
npm WARN peerDependencies The peer dependency jasmine-core@* included from karma-jasmine will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency phantomjs@>=1.9 included from karma-phantomjs-launcher will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt-cli@0.1.13 included from angular-gravatar will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@0.3.8
\

#
# Fatal error in ../deps/v8/src/heap/incremental-marking.cc, line 488
# CHECK(success) failed
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::internal::IncrementalMarking::StartMarking(v8::internal::IncrementalMarking::CompactionFlag)
 3: v8::internal::IncrementalMarking::Start(v8::internal::IncrementalMarking::CompactionFlag)
 4: v8::internal::FreeList::Allocate(int)
 5: v8::internal::PagedSpace::AllocateRaw(int)
 6: ??
 7: v8::internal::Heap::AllocateFixedArrayWithFiller(int, v8::internal::PretenureFlag, v8::internal::Object*)
 8: v8::internal::Heap::AllocateJSObjectFromMap(v8::internal::Map*, v8::internal::PretenureFlag, bool, v8::internal::AllocationSite*)
 9: v8::internal::Heap::AllocateJSObject(v8::internal::JSFunction*, v8::internal::PretenureFlag, v8::internal::AllocationSite*)
10: v8::internal::Factory::NewJSObject(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::PretenureFlag)
11: v8::internal::JsonParser<false>::ParseJsonObject()
12: v8::internal::JsonParser<false>::ParseJsonValue()
13: v8::internal::JsonParser<false>::ParseJsonArray()
14: v8::internal::JsonParser<false>::ParseJsonValue()
15: v8::internal::JsonParser<false>::ParseJsonObject()
16: v8::internal::JsonParser<false>::ParseJsonValue()
17: v8::internal::JsonParser<false>::ParseJsonObject()
18: v8::internal::JsonParser<false>::ParseJsonValue()
19: v8::internal::JsonParser<false>::ParseJsonObject()
20: v8::internal::JsonParser<false>::ParseJsonValue()
21: v8::internal::JsonParser<false>::ParseJson()
22: v8::internal::Runtime_ParseJson(int, v8::internal::Object**, v8::internal::Isolate*)
23: ??
Instrucción ilegal

**Comment by rjmackay** [comment]
Hi Luis,
Can you try installing the `build-essential` debian package?
Then
remove the node_modules directory in platform-client, run `npm install` again and then `gulp build`

Let me know if that makes any difference?

**Comment by redhumus** [comment]
Hi Robbie,

I have build-essential yet and

this is the output: of nmp install    :(

root@miserver:/routetomy/platform-client# ls -la
total 160
drwxr-xr-x 10 www-data www-data  4096 sep  4 23:11 .
drwxr-xr-x 16 www-data www-data  4096 sep  4 23:07 ..
drwxr-xr-x  7 www-data www-data  4096 sep  4 23:07 app
-rw-r--r--  1 www-data www-data   671 sep  4 23:07 app.json
-rw-r--r--  1 www-data www-data    96 sep  4 23:07 .arcconfig
-rw-r--r--  1 www-data www-data   311 sep  4 23:07 .arclint
drwxr-xr-x  2 www-data www-data  4096 sep  4 23:07 bin
-rw-r--r--  1 www-data www-data   100 sep  4 23:07 .buildpacks
-rw-r--r--  1 www-data www-data   167 sep  4 23:07 .editorconfig
-rw-r--r--  1 www-data www-data    39 sep  4 23:11 .env
-rw-r--r--  1 www-data www-data    95 sep  4 23:07 fig.yml
drwxr-xr-x  8 www-data www-data  4096 sep  4 23:07 .git
-rwxr-xr-x  1 www-data www-data   131 sep  4 23:07 .gitignore
drwxr-xr-x  2 www-data www-data  4096 sep  4 23:07 gulp
-rw-r--r--  1 www-data www-data 13449 sep  4 23:07 gulpfile.js
-rw-r--r--  1 www-data www-data   368 sep  4 23:07 .jscsrc
-rw-r--r--  1 www-data www-data    56 sep  4 23:07 .jshintignore
-rw-r--r--  1 www-data www-data   604 sep  4 23:07 .jshintrc
-rw-r--r--  1 www-data www-data 34520 sep  4 23:07 LICENSE-AGPL
-rw-r--r--  1 www-data www-data  2318 sep  4 23:07 LICENSE.md
drwxr-xr-x  3 www-data www-data  4096 sep  4 23:07 mocked_backend
-rw-r--r--  1 www-data www-data  3321 sep  4 23:07 package.json
-rw-r--r--  1 www-data www-data    13 sep  4 23:07 Procfile
-rw-r--r--  1 www-data www-data  6491 sep  4 23:07 README.md
drwxr-xr-x  3 www-data www-data  4096 sep  4 23:07 sass
drwxr-xr-x  3 www-data www-data  4096 sep  4 23:07 server
drwxr-xr-x  4 www-data www-data  4096 sep  4 23:07 test
-rw-r--r--  1 www-data www-data  1323 sep  4 23:07 .travis.yml
root@miserver:/routetomy/platform-client# npm install
npm WARN peerDependencies The peer dependency jasmine-core@* included from karma-jasmine will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency phantomjs@>=1.9 included from karma-phantomjs-launcher will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt-cli@0.1.13 included from angular-gravatar will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN peerDependencies The peer dependency bootstrap@^3.x included from angular-ui-bootstrap will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abortado
root@miserver:/routetomy/platform-client# /platform-client# npm install
\
npm WARN optional dep failed, continuing fsevents@0.3.8
-
> ws@0.4.32 install /routetomy/platform-client/node_modules/angular-bootstrap-colorpicker/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

**Comment by rjmackay** [comment]
@redhumus sorry about the slow response. i think the key error is at the end
` FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory`

Are you running this locally or on a server? Either way npm is running out of memory trying to install everything. The only thing you can really do is increase the memory on the machine its running on, or close some other processes while the build runs.

Depending on your needs, the other option is to grab a pre-built client here: https://github.com/ushahidi/platform-client/releases/download/v3.0.0/platform-client-v3.0.0.tar.gz
That contains just the `server/www` part of the client repo, but with the JS prebuilt. To use it
- extract it into the docroot of a vhost
- Grab the .htaccess file from here: https://github.com/ushahidi/platform-client/blob/master/server/rewrite.htaccess and copy that to .htaccess in the same location
- edit config.js and point backend_url to your API server

**Comment by rjmackay** [comment]
Closing this out. @redhumus reopen if you have any more info you can add
