### ISSUE TITLE
Create a Timeline view in Pattern Library

### ISSUE THREAD

**Issue by middle8media** [ushahidi/platform#693]
ushahidi/platform#434

**Comment by rjmackay** [comment]
I'm not clear if this is done in the PL or not?

**Comment by middle8media** [comment]
This needs to be created in the PL, it currently does not exist.

**Comment by middle8media** [comment]
@rjmackay @vbhv 

Just wanted to confirm and get on the same page with this.

Should I create http://demo.platform.ushahidi.com/views/timeline in PL?

It would match http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/home-map.html and http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/home-list.html

@vbhv mentioned we are moving away from nvd3 and going with dc.js, so I am wondering how/if to proceed.

**Comment by vbhv** [comment]
@middle8media 
I think it would be most helpful to implement the layout and Ux patterns in PL and leave out the charting component. I like what Sophie did with activity view and that was about the right amount of pattern detail required to build a page. So you can use a placeholder image for the charting component and everything else can be in the PL – i.e, layout, controls, and other PL blocks. Example: Activity Page in PL http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/activity.html
Does that sound appropriate to you?

**Comment by middle8media** [comment]
Thanks @vbhv I will proceed accordingly.

**Comment by middle8media** [comment]
completed issue via https://github.com/ushahidi/platform-pattern-library/commit/3f313dd64d6d94d916236f858c1bed7df9be4387

**Comment by middle8media** [comment]
new html and css needs to be implemented in the client

**Comment by sophshep** [comment]
Hey @middle8media - this is missing some functionality, such as the checkbox and dropdown. And I don't think we need pagination on this view.

@vbhv could you attach the UX mockup we did when you were in austin to this issue? Then we'll build for that.

**Comment by vbhv** [comment]
Github won't let me attach PDFs so below is the link to the file on basecamp. The wireframes don't indicate a checkbox - it was added later to allow user to visualise cumulative counts. I think the best representation of this view is actually the client implementation itself :) @ http://demo.platform.ushahidi.com/views/timeline with the exception of the misaligned checkbox filed in #434 

https://basecamp.com/1931265/projects/1216937/messages/44717057?enlarge=169548443#attachment_169548443

**Comment by middle8media** [comment]
this should be live and good to go.

http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/home-timeline.html

**Comment by rjmackay** [comment]
This is broken in Firefox https://www.dropbox.com/s/js2jozpj7m9mp4r/Screenshot%202015-09-22%2010.26.05.png?dl=0
