### ISSUE TITLE
Amended name field for 'Location' as second field in post type doesn't display in completed post display

### ISSUE THREAD

**Issue by adambard1** [ushahidi/platform#694]
> Created one step post type where first field is datetime and second field is location.
> Changed field name for datetime to "When?" and field name for location to "Where?".
> Left default for datetime, changed default for location to New York, USA.
> Saved.
> +Add post (chose this new post type)
> filled out post information. Field names are as amended above when filling out post.
> Saved post
> Post then shows, first field is named "When?" but the second field shows "Location" as field name.
> ![fieldname_changed](https://cloud.githubusercontent.com/assets/13530245/9747114/dd641ff4-5649-11e5-8d98-b89323e8eb44.jpg)
> ![fieldname_reverts](https://cloud.githubusercontent.com/assets/13530245/9747115/dd732dbe-5649-11e5-9523-b6c33cb7efe5.jpg)

**Comment by rjmackay** [comment]
@adambard1 is the issue that we're not show 'Where did this happen' on the label? or that we're not showing that marker at all?

Related to #351 .. we need to change the map popups to use the field names or something sane.

**Comment by adambard1** [comment]
Hi Robbie,

I don't understand your question re 'Where did this happen' and labels and 
makers, sorry. I named the second step in a newly created post type 
"Where?", as shown in the previously attached image. When that post type is 
used and completed, the second step appears named as "Location", not 
'Where?".  I had changed the name of the first step in the post as well (to 
"When?"), and this change is reflected on the completed post, which visit 
what I would expect to happen for the second step.

**Comment by rjmackay** [comment]
@adambard1 locations are always a special case at the moment. If you add multiple location fields we didn't want to end up show lots of different maps, rather one map but we need to add a key or some easy way to see the field labels on the map. It'd probably be less confusing if I remove the 'Location' label entirely too.. since a map is obviously about locations.

**Comment by adambard1** [comment]
@rjmackay Actually, you have touched on a query/bug I'd posted about multiple location steps - to show a route - where the location pin labels only show the post step name, instead of the address of the marker, which would probably be useful (in nearly all cases, actually).

This wasn't a multiple location field issue, simple one about continuity of offering us the option to name steps in posts, but then not seeing those names translated to the final post (where your default field/step name appears).
