### ISSUE TITLE
Confusing validation errors when creating tags

### ISSUE THREAD

**Issue by adambard1** [ushahidi/platform#695]
Working on test app hosted on Heroku. Created a few categories OK, went to save another and was logged out somehow - window crashed so couldn't capture error message which was something to do with revoked access.
Reopened app, went to recreate category during crash and was given error message that category already exists, however it is not listed anywhere, including in the categories list.
Have logged out and logged in a few times, keep getting the same error msg when creating this category.
![add category error](https://cloud.githubusercontent.com/assets/13530245/9796716/8f3e37e2-57c5-11e5-8272-652d54a43c29.jpg)
![current categories](https://cloud.githubusercontent.com/assets/13530245/9796717/8f4a8cfe-57c5-11e5-915c-3a23410e69be.jpg)

**Comment by adambard1** [comment]
Restarted computer after being logged off for half an hour. Problem solved, classification added, no error message. Might be something to look into or could just leave it if it can't be reproduced.

**Comment by rjmackay** [comment]
At the least we should be showing the slug field and prepopulating like we do with form attribute keys.
