### ISSUE TITLE
.htaccess has wrong redirection rule

### ISSUE THREAD

**Issue by sanel** [ushahidi/platform#696]
Hi guys,

Just tested 3.0.0 and everything works, except _.htaccess_ rewrite rule. Even with current setup, I'm getting _No input file specified_, so after some fiddling, I ended up with correct rule:

```
RewriteRule .* index.php?/$0 [PT]
```

I'm running it on CentOS 6.7 with Apache 2.2.15.

Best,
Sanel

**Comment by rjmackay** [comment]
@sanel how are you running PHP? Using php-fpm or mod php?

Our example .htaccess definitely works on some setups so it'd be useful to narrow down why it doesn't work for you.

**Comment by sanel** [comment]
I'm using php fastcgi instead of fpm. Also, I've got it from here: http://stackoverflow.com/questions/1557258/htaccess-problem-no-input-file-specified so I'm not sure is this fpm/mod_php specific issue.
