### ISSUE TITLE
Rewrite dataproviders

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#697]
- Rewrite dataprovider classes so they don't rely on kohana
- Abstract platform details to our provider repo. ie. enabled/disabled, available/unavailable
- Move config to POST/PUT to dataprovider api
- Provider classes should simply be services for sending/receiving messages
- Providers that need a callback should probably share a controller and an interface for receiving all data sent, parsing it and returning a message to be saved

**Comment by rjmackay** [comment]
cc @willdoran anything else to add to this? notes on what works/doesn't currently?

**Comment by jshorland** [comment]
Moving backward into backlog and removnig the milestone.

**Comment by jshorland** [comment]
Moving forward and highlighting. let's get this done this quarter! @willdoran this will be the next next thing we'll need to work on (after mobile app banners)

**Comment by rowasc** [comment]
Closing, lumen was released
