### ISSUE TITLE
Can't scroll to bottom of the page on touchscreen phones

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#700]
When scrolling down on the main page of an Ushahidi deployment on a touchscreen phone you can only scroll as far as the map, at which point you begin scrolling the map down, but not the page. As a user this means that I can't see anything below the map: I scroll (with frustration) until I get to Antarctica and that's the end of the road. 

Tested on iOS with the Safari Browser using demo.platform.ushahidi.com.

**Comment by sophshep** [comment]
@middle8media It used to not do this, I think it is a setting within leaflet. Could you take a look?

**Comment by middle8media** [comment]
duplicate of #644
