### ISSUE TITLE
Duplicate name field validation error?

### ISSUE THREAD

**Issue by adambard1** [ushahidi/platform#701]
Creating 'route' post type with multiple locations. Made each step a new location and wish to add a datetime filed as second field in each step.
After creating first step all is ok as attached. Have called diatetime "Where & When?"
On adding the datetime to second step, naming it "Where & When?" and hitting save and close am met with a validation error, as attached.
Cannot add this datetime to any step with that name within this post type so am assuming this might be a local duplication of field name issue. However, it does make sense to call fields by the same name in different steps, especially if the fields are repeating previous steps, so might this be resolved if it is a duplicate naming issue?
thanks!

![first_step_field_validated](https://cloud.githubusercontent.com/assets/13530245/9856667/1e1a6a96-5ae4-11e5-8208-459d428198c1.jpg)
![second step field validation error](https://cloud.githubusercontent.com/assets/13530245/9856668/1e26144a-5ae4-11e5-9728-57c66d8e5f49.jpg)

**Comment by rjmackay** [comment]
Need to figure out a way to auto generate unique keys for new attributes, but keep them human readable
