### ISSUE TITLE
Prompt user for email if existing email is invalid

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#703]
When migrating from username we've set email = username if the user didn't have an email in the db. For these users we should prompt them to add an email at next login.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-729

**Comment by rowasc** [comment]
Note: If this is required for the v2 migration (need to review) we should base the solution on the adminUserSetup flow in authenticationEvents since the UI is already built for this

**Comment by rowasc** [comment]
Closing since we do this through adminUserSeupt.
