### ISSUE TITLE
Replace Kohana Validation with better validation lib

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#710]
- Potentially Laravel Validation lib, or some other standalone validator.
- Implement existing validation interfaces
- Generate errors that can be tied to form fields in the client
- Need to be able to handle validating nested arrays better, particularly reporting errors for things like post values.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-728

**Comment by rowasc** [comment]
Note:  The heavier work of getting validators out of kohana is done in the v4-lumen version since Robbie added the ability to use multiple validator engines, so if I'm not mistaken, we need to start using Laravel validation instead in new work? tagging tech-debt to review
