### ISSUE TITLE
Replace kohana db with a standalone DB library

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#712]
Needs to support:
- Mysql
- Postgis
- Mssql (nice to have)
- SQLite (for testing) + spatialite?

Need a query builder, and dbal.. but migrations stay with phinx, and no ORM.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-727

**Comment by rowasc** [comment]
Pending move to Lumen DB https://github.com/ushahidi/platform/pull/1663
