### ISSUE TITLE
Pricing page on tour flow requires scroll

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#713]
Can we make this fit onto a single screen no scroll?

**Comment by rjmackay** [comment]
cc @brandonrosage

**Comment by brandonrosage** [comment]
[I updated this view](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/tour.html#plans) to match @sophshep's work on [dotcom's "Plans" page](http://github.ushahidi.org/dotcom-pattern-library/assets/html/5_layouts/pricing.html), which has increased the amount of content that's visible without scrolling.

The update, however, also includes zero-rated and self-hosted callouts. So there is still plenty to scroll. 

Given all the screen sizes we must support, I don't think it's reasonable to expect that all of the "Plans" content will fit in a single screen for everyone. But it seems like a reasonable amount of information density (if not _too much__) in its current iteration.
