### ISSUE TITLE
Validation error when adding guest user

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#714]
1. Logged in to deployment
2. navigated to settings --> users
3. clicked "add user"
4. filled out all details (display name, email, password, role = guest)
5. clicked "save user"
6. Error message popped up stating "validation error: user.role.exists"
![screen shot 2015-09-18 at 2 03 30 pm](https://cloud.githubusercontent.com/assets/3224856/9958043/4aec52be-5e0e-11e5-8287-e7188d0ca080.png)

**Comment by rjmackay** [comment]
Guest is a 'no role' role.. maybe we just shouldn't be showing it in the list at all? or maybe we should be sending an empty role. I'm not sure.

**Comment by willdoran** [comment]
@rjmackay what is the purpose of the guest role? It doesn't seem to be accounted for in terms of rights.

I can very easily remove it, depending on what you prefer. Sending an empty role might be confusing for the validation.

**Comment by rjmackay** [comment]
I think this is just left over from an older idea about how we handled roles. We should remove it..

**Comment by rjmackay** [comment]
Just be sure to check everywhere we use the role helper and make sure nothing breaks :)

**Comment by willdoran** [comment]
@rjmackay,
