### ISSUE TITLE
Icon name dropdown is a single file list of icons that goes on forever

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#715]
1. Navigated to Categories --> add category
2. clicked "icon name" drop down arrow
3. single column list of icons appeared and scrolling is crazy long

![screen shot 2015-09-18 at 2 12 07 pm](https://cloud.githubusercontent.com/assets/3224856/9958128/89d145f6-5e0f-11e5-8b16-382b4efc5c49.png)

**Comment by rjmackay** [comment]
@willdoran can you fix / improve this? If you need design help then reassign to Seth with some instructions

**Comment by willdoran** [comment]
Hi @middle8media,

What would the best way to display the icon set be? I think placing them in a rectangular box might be simplest. The iconpicker is managed by:

app/common/directives/iconpicker.js
templates/iconpicker/iconpicker.html

and uses the dropdown menu. Whats the best way to adapt the css?
