### ISSUE TITLE
"add to collection" button in list view won't open drop down

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#717]
1. Navigated to list view as logged in admin
2. selected post
3. clicked "options" at bottom of post
3. clicked "add to collections"
4. drop down box would appear to open, then immediately close

Note: The bulk action "add to collections" button at the top right corner of the list view works properly.

![screen shot 2015-09-18 at 2 41 09 pm](https://cloud.githubusercontent.com/assets/3224856/9958512/5f38c748-5e13-11e5-99c2-689e5471a4ca.png)

**Comment by jasonmule** [comment]
For some reason, I am not able to reproduce this.
