### ISSUE TITLE
Update 'Create new deployment' screen with interaction improvements

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#718]
I've made some improvements to the ['Create new deployment' page](http://github.ushahidi.org/dotcom-pattern-library/assets/html/5_layouts/create-deployment.html), namely to the education around what each field means. The updates, however, include new JavaScript and CSS. So let me highlight what's new, so implementation is as easy and quick as possible:

* _HTML_: Naturally, [the structure of the form](https://github.com/ushahidi/dotcom-pattern-library/blob/gh-pages/pattern-library/5_layouts/create-deployment.html#L57-L131) changes quite a bit to allow us to separate various segments of the form.
* _CSS_: If you're simply referencing the dotcom styles.css, the updates will be immediately available to you. If not, the dotcom-pattern-library revised a few existing `.scss` files and added `_slide.scss` to support the new patterns.
* _JavaScript_: There are two new custom JavaScript files that are compiled into the dotcom `app.js`, as well as [some inline JavaScript](https://github.com/ushahidi/dotcom-pattern-library/blob/gh-pages/pattern-library/5_layouts/create-deployment.html#L140-L148) intended only for the "Create new deployment" page. The new JavaScript files are [form.js](https://github.com/ushahidi/dotcom-pattern-library/blob/gh-pages/assets/js/custom/form.js) and [slide.js](https://github.com/ushahidi/dotcom-pattern-library/blob/gh-pages/assets/js/custom/slide.js).

The notable improvements these changes bring to the page are:

* Auto-populating the "Deployment URL" based on their Deployment name" input.
* Generating a graphic preview of their deployment on large screens.
* Separating "Your deployment" and "Your account" into separate "slides" on large screens.
* Adding descriptions to most fields to educate new users about our terms (e.g. deployment)

**Comment by rjmackay** [comment]
So splitting the create page into 2 slides makes validation a pain.. we have to switch slides to depending on which fields had errors. If multiple steps have errors they can only see some, not all of the errors at once.

Also still need some validation styles.. unless those exist and I'm just missing them?

**Comment by brandonrosage** [comment]
[Lots of improvements for you here](http://github.ushahidi.org/dotcom-pattern-library/assets/html/5_layouts/create-deployment.html).

**1. Form validation styles**

I've included styles that support simple additions to the markup for form validation. They assume system feedback happens within the context of a form field -- not the entire form itself. That said, the pattern supports attaching feedback to the submit button, where you can summarize all the fields that need the user's attention.

Here's some examples:


![Success](http://d.pr/i/18Uv3+)
**['Success' feedback on a form field](https://github.com/ushahidi/dotcom-pattern-library/blob/gh-pages/pattern-library/5_layouts/create-deployment.html#L77-L86)**. Note that the form field container includes the class name `success` and that we've [prepended a paragraph](https://github.com/ushahidi/dotcom-pattern-library/blob/gh-pages/pattern-library/5_layouts/create-deployment.html#L83) to the form field's description area with the class name `form-field-feedback`.


![Error](http://d.pr/i/192xj+)
**['Error' feedback on a form field](https://github.com/ushahidi/dotcom-pattern-library/blob/gh-pages/pattern-library/5_layouts/create-deployment.html#L114-L122)**. Same convention as "success," but with the class name `error` applied to the form field container, instead of `success`.


![Error](http://d.pr/i/1e8XQ+)
**['Error' feedback on the form's submit button](https://github.com/ushahidi/dotcom-pattern-library/blob/gh-pages/pattern-library/5_layouts/create-deployment.html#L131-L144)**, summarizing all the field's demanding the user's attention. Note that we treat the markup around the submit button precisely the same way as an input field.

**2. More dynamic slide interactions**

In the aforementioned scenario, where a we list each of the fields that require the user's attention, we've designed this so that the user has a navigation tool for jumping directly to the appropriate field. In the event that the field isn't visible because it lives within a hidden "slide," we've developed a convention for making these links smart, provided that they're wrapped in an anchor tag, using the following convention:

```
<a href="#inputid" data-slide="field">Field label</a>
```
_[Example](https://github.com/ushahidi/dotcom-pattern-library/blob/gh-pages/pattern-library/5_layouts/create-deployment.html#L139)_

Our _[slide.js](https://github.com/ushahidi/dotcom-pattern-library/blob/gh-pages/assets/js/custom/slide.js)_ script handles click events on all elements with the `data-slide` attribute, and navigates the slides dynamically. The improvements we've made to this script most recently [focus on handling links directly to specified form fields](https://github.com/ushahidi/dotcom-pattern-library/blob/gh-pages/assets/js/custom/slide.js#L1-L31).

So utilizing our work on _slide.js_ is critical.

cc/ @sophshep @middle8media

**Comment by rjmackay** [comment]
Replace by https://github.com/ushahidi/platform-cloud-interface/issues/89
