### ISSUE TITLE
Hanging after intro

### ISSUE THREAD

**Issue by castrillo** [ushahidi/platform#722]
I was trying to complete the user testing survey but after then intro when I arrived at the Nice! We hope you enjoy your new deployment screen it hung and would not let me continue.
I then closed the browser and reopened it again but the deployment would not load.
My deployment is http://betalondon.ushahidi.io/.

**Comment by rjmackay** [comment]
@castrillo when you say it hung.. can you tell me a bit more? 
You clicked 'Done' and it just loaded forever? Did it appear to be loading the correct URL?
