### ISSUE TITLE
Saved posts not appearing

### ISSUE THREAD

**Issue by castrillo** [ushahidi/platform#723]
When completing the Ushahidi user testing survey I created and saved two posts but I could not see these when going to the http://betalondon.ushahidi.io/views/list view.
Is there somewhere else I should look?

**Comment by rjmackay** [comment]
Did you publish the posts? Are you logged in?
If you're not logged in and the posts are still unpublished you won't see them. Posts to anyone but an admin user until they've been published

**Comment by rjmackay** [comment]
Closing in favour of #397
