### ISSUE TITLE
Blank Add a post page

### ISSUE THREAD

**Issue by abelb** [ushahidi/platform#724]
I tried to create a post and was able to add title, location and description but it wouldn't save. 

Somehow clicked on this link: http://www.openstreetmap.org/copyright

When i hit back button, I got this screen and could not add post type.

<img width="948" alt="screen shot 2015-09-22 at 7 21 59 am" src="https://cloud.githubusercontent.com/assets/108173/10021058/ee247922-60fa-11e5-8a85-bed878ea0846.png">

Add a post button would not work - getting these errors in console

<img width="1342" alt="screen shot 2015-09-22 at 7 25 02 am" src="https://cloud.githubusercontent.com/assets/108173/10021091/1ee91e96-60fb-11e5-92c5-e2f8a419cab4.png">

Got totally stuck and no add post button would work - had to close browser window - in new browser window was able to add post.

**Comment by rjmackay** [comment]
@willdoran Can you triage and figure out what went wrong here?

**Comment by willdoran** [comment]
Hi @adelb,

Would you confirm some things for me so I can reproduce the issue?

1. What Post type were you using? Was it 'Test Form', 'Missing People' or your own custom one?
2. Is the following flow correct, 
-Click add post
-Select post type
-Enter title, description, location 
   - was the location entered through the map?

-Was the next point where you clicked Save or where 'http://www.openstreetmap.org/copyright' got accidentally clicked?

Thanks very much for your feedback!

Will

**Comment by AdelB** [comment]
Hello,

I am sorry but I am not concerned by this issue.

Unfortunately I am not the @adelb you want to reach.

Have a nice day.

**Comment by rjmackay** [comment]
cc @abelb ^ see Will's comment above :)

**Comment by abelb** [comment]
ok so... When i first got on the site to login I already had some errors inthe console

![screen shot 2015-09-25 at 10 28 08 am](https://cloud.githubusercontent.com/assets/108173/10107535/aacd9f1e-6370-11e5-9224-7550c27e1e31.png)

I logged in and saw these errors:
![screen shot 2015-09-25 at 10 28 28 am](https://cloud.githubusercontent.com/assets/108173/10107547/bb0cb11c-6370-11e5-8991-3a8fcaf2c0e7.png)

I started to add a post and before i saved, I clicked on the open street map copyright link. I t took me to that page, I hit back button in browser. And then saw this:

![screen shot 2015-09-25 at 10 34 37 am](https://cloud.githubusercontent.com/assets/108173/10107603/0f08b70c-6371-11e5-90e7-f2b9ca9e3c5b.png)

with these errors in the console
![screen shot 2015-09-25 at 10 34 13 am](https://cloud.githubusercontent.com/assets/108173/10107608/15d84386-6371-11e5-82a7-0024e6e9aeb9.png)

**Comment by willdoran** [comment]
@abelb Ok, thanks, I'll try and reproduce it and update you!

**Comment by willdoran** [comment]
@abelb I'm having trouble reproducing, is this still occurring for you?

**Comment by abelb** [comment]
yes it is fixed!
