### ISSUE TITLE
Handle hitting quota in the client

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#726]
Direct user to upgrade when they hit quotas (if they're an admin)

**Comment by rjmackay** [comment]
The main this here is to make sure we handle it nicely. Direct the admin to upgrade when they hit quota..

**Comment by willdoran** [comment]
So at the moment, because the limits are handled in the validator - long term ideally somewhere else - I think the most straightforward solution is to intercept the quotas at that point and rather than displaying the error we can broadcast that error to an limits handler if the user is admin.
