### ISSUE TITLE
Update Ushahidi.io Nav to Ushahidi.com nav

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#740]

**Comment by rjmackay** [comment]
Done. @middle8media please double check ushahidi.io/create then close this?

**Comment by caharding** [comment]
Logo is not correct, should be gold @middle8media can you provide

**Comment by middle8media** [comment]
here is the correct logo - https://github.com/ushahidi/dotcom-craft-cms/blob/master/public/img/ushahidi-wordmark.svg

**Comment by middle8media** [comment]
actually I need to change the css, will update in a second.

@rjmackay remove the `.post-launch` class from `<h1 class="logo post-launch"><a href="/">Ushahidi</a></h1>`

**Comment by rjmackay** [comment]
... read this too late. Updated image, changed css.. finally realised I missed a class!
Thanks!

**Comment by middle8media** [comment]
just remove `post-launch` class and bring in new css and you will be up to date.
