### ISSUE TITLE
System Feedback

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#746]
There should be feedback almost any time a user takes a significant action. Such as:

* adding a new post
* adding a post to a collection
* Changing a user role

This feedback should use the confirmation message pattern: http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/confirmation.html

cc/ @brandonrosage

**Comment by willdoran** [comment]
I'll go through and make sure this is added across the interactions.

**Comment by willdoran** [comment]
Should also cover

    Show error icon/message when a 'completed' stage becomes invalid (during edit)
    Show error icon/message when post can't be saved as published because of invalid fields
    Denote required fields
    Note required stages
    Clearer completed/incomplete button?

**Comment by jshorland** [comment]
note from Angela on a duplicate issue: At the moment, when you click save, or post something - the user doesn't get any feedback or a prompt to confirm that "You've successfully saved/posted" or something. I just saved my settings and if it weren't for my keen eye on the slight page reload, i wouldn't be clear of my save action was successful or not - we should add these in.

**Comment by aoduor** [comment]
Great to see this added in. Wondering if we could take the next step and either
* Refresh the page,
* Redirect to somewhere else OR
* Close window where i've just completed/saved/posted something?

ATM, i get the "Saved" prompt at the top of the page, and on closing it, i remain on the same page with the same content in the fields i'm adding/editing

**Comment by rjmackay** [comment]
hrm. I think it depends. On creation it makes sense to redirect.. if you're editing its nice to be able to save and stay on the same page.
