### ISSUE TITLE
Redirects to Log-in

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#747]
When viewing a deployment that I'm not logged into, it prompts me to log in when I navigate to a new page. (such as clicking to view list on Quake Map)

A user should only be prompted to log-in if it is necessary to the action the are trying to take. Otherwise, they should be able to explore the site without being asked to log in.

cc/ @brandonrosage

**Comment by rjmackay** [comment]
Just noticed one of the issues is trying to load tags for a post when those tags aren't visible to the current user.
- We shouldn't let that fail bounce us to login
- We also shouldn't be exposing private tags on a post if you can't see them

**Comment by willdoran** [comment]
I'm seeing a similar error with collections but this appears to be related to a notifications rights error.

**Comment by willdoran** [comment]
I need to refine the query for posts so that it only returns entities that the user is authorised for at the moment it's a small hole in how the data is gathered and then retrieved by the client.
