### ISSUE TITLE
Never-ending Save button after post edit

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#748]
When I edited a post and hit "save" the cog kept spinning for an extended period of time. There was no confirmation that my changes had been made.

**Comment by JoinJoin** [comment]
I can confirm. 
Leaving the page saves the changes.

**Comment by sophshep** [comment]
This also happens when updating and saving data sources

**Comment by jasonmule** [comment]
@sophshep I managed to reproduce the issue with dataproviders so I am not sure if this is related to #770
