### ISSUE TITLE
Map Settings: Remove default zoom and lat/lng?

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#749]
Instead of offering controls for the map view's default zoom, lat, and lng, can we simply always have the map center and zoom to the data set in context? This would ensure consistency and offer better system feedback when filtering -- the map would move around as they manipulated their data set.

I think we'll be on a good path for all views if we build them to be inherently responsive to the data set users define -- not simply the "Home" data set.

Is there a worthy use case for defining the default zoom, lat, and lng?

**Comment by sophshep** [comment]
If not, can we work out some UI around setting the center of the map? I wanted to center my default map on the US but had to google what the Lat/Long of that was. If would be more user-friendly to be able to zoom, click, & drag the map to what I want to have as default, and then have a "save this view as default" button.

**Comment by Shadrock** [comment]
I'd suggest leaving some option for setting the map center: what if all a majority of my posts are coming from a place that I don't want to focus on? Strange, but might happen. Or what if, over time, I really want a visitors first view to be of a particular subset of my data to underscore something about the data? I do very much like the "click & drag" method Sophie mentions here.

**Comment by brandonrosage** [comment]
@Shadrock My underlying concern here is that the UX for manipulating "views" is inconsistent. When users interact with filters and view controls (e.g. zoom, panning), their changes to the dataset are honored. 

For example, if they narrow the dataset to posts in a certain region, from the category "injury," the map sure-as-hell better pan and zoom to that region, and only show posts that match that category.

Likewise, if we're delivering them the "All posts" dataset, I think we're confusing the function of "views" by not honoring those parameters. If the user arrives at "All posts," and a chunk of the deployment's posts aren't included, then what are we doing?

So, first, I'll take a stab at answering your questions, along with a suggested solution...

> what if a majority of my posts are coming from a place that I don't want to focus on?

**Saved Searches** were created to serve exactly this need -- to create dynamic subsets of data so you can focus what _you_ want to focus on. If you'd rather focus on data more narrow than "All posts," you define that subset and save it.

> Or what if, over time, I really want a visitors first view to be of a particular subset of my data to underscore something about the data?

If this is a real need (which I have no doubt about), I think the solution is to expand the deployment's general settings to include the ability to not only define its default "view," but also define it's default "Saved Search." This would allow the deployment's owners to do exactly what you're referring to.

If this became wildly popular, I think we could extend it to user-level settings, where they could say that they wanted a given Saved Search to be _their_ Home view.

@sophshep There's certainly some UX details to work out here. But I think, generally, it's a sound approach.

Finally, some of my love affair with a consistent approach to visualizing data is with an eye to our intention to take "views" to another level -- where two views can be used at the same time, and where they become much more interactive, to the point that you can use them to filter data. 

For example, in a future version of "Map" view, imagine a user zooms the map to a specific region. I'd argue that it'd be incredibly valuable for that action to then apply that location filter to the dataset. The change would be reflected in the summary of filters applied. And if they flipped into "list" view, the dataset would be remain filtered to that region. In effect, the "map" view would be the fastest, most user-friendly UI for filtering the data by region.

**Comment by rjmackay** [comment]
UI for managing views really isn't built yet. We only have map settings..
where we should have 'view settings' with each of the views list,
enabled/disabled and configured. Need to figure out where this falls in our
priorities.. there are lots of clean ups needed to match the PL properly.

On Mon, Oct 5, 2015 at 11:11 AM, Brandon Rosage <notifications@github.com>
wrote:

> @Shadrock <https://github.com/Shadrock> My underlying concern here is
> that the UX for manipulating "views" is inconsistent. When users interact
> with filters and view controls (e.g. zoom, panning), their changes to the
> dataset are honored.
>
> For example, if they narrow the dataset to posts in a certain region, from
> the category "injury," the map sure-as-hell better pan and zoom to that
> region, and only show posts that match that category.
>
> Likewise, if we're delivering them the "All posts" dataset, I think we're
> confusing the function of "views" by not honoring those parameters. If the
> user arrives at "All posts," and a chunk of the deployment's posts aren't
> included, then what are we doing?
>
> So, first, I'll take a stab at answering your questions, along with a
> suggested solution...
>
> what if a majority of my posts are coming from a place that I don't want
> to focus on?
>
> *Saved Searches* were created to serve exactly this need -- to create
> dynamic subsets of data so you can focus what *you* want to focus on. If
> you'd rather focus on data more narrow than "All posts," you define that
> subset and save it.
>
> Or what if, over time, I really want a visitors first view to be of a
> particular subset of my data to underscore something about the data?
>
> If this is a real need (which I have no doubt about), I think the solution
> is to expand the deployment's general settings to include the ability to
> not only define its default "view," but also define it's default "Saved
> Search." This would allow the deployment's owners to do exactly what you're
> referring to.
>
> If this became wildly popular, I think we could extend it to user-level
> settings, where they could say that they wanted a given Saved Search to be
> *their* Home view.
>
> @sophshep <https://github.com/sophshep> There's certainly some UX details
> to work out here. But I think, generally, it's a sound approach.
>
> Finally, some of my love affair with a consistent approach to visualizing
> data is with an eye to our intention to take "views" to another level --
> where two views can be used at the same time, and where they become much
> more interactive, to the point that you can use them to filter data.
>
> For example, in a future version of "Map" view, imagine a user zooms the
> map to a specific region. I'd argue that it'd be incredibly valuable for
> that action to then apply that location filter to the dataset. The change
> would be reflected in the summary of filters applied. And if they flipped
> into "list" view, the dataset would be remain filtered to that region. In
> effect, the "map" view would be the fastest, most user-friendly UI for
> filtering the data by region.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/issues/749#issuecomment-145564109>.
>



-- 
Robbie Mackay

Senior Software Developer
Ushahidi Inc
m: +64 27 576 2243
e: robbie@ushahidi.com
skype: robbie.mackay

**Comment by rowasc** [comment]
Since we use the zoom level and lat Lon feature a lot currently (ie comrades) and should not be removed entirely, I'm setting this as a reference  point for 
#664 
#608 
#600 
We allow users to set a default location and zoom level and use location bounds to center the map , *but there is still a lot of work to be done* regarding how we manage zoom levels in map views, saved searches, collections, etc so this is still relevant info to be aware of.
