### ISSUE TITLE
Error when creating Saved Search

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#750]
I tried to create a saved search within a date range, it gave me an error.

![image](https://cloud.githubusercontent.com/assets/527589/10253707/740eba1e-6904-11e5-88b6-389611681670.png)

**Comment by willdoran** [comment]
I can reproduce this, I'll fix it now

**Comment by willdoran** [comment]
There was an incorrect check so the savedsearch wasn't getting properly set before sending. I've updated it now. I'm going to push it to master, @rjmackay should it go in cloud too?
