### ISSUE TITLE
Editing existing Post Type throws error for free 'Mapper' users

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#751]
When attempting to rename the single Post Type my Mapper account allows, the deployment threw me an error, seemingly assuming that I was creating a new Post Type: http://d.pr/i/18reU

As a Mapper, I should be able to edit the name and description of my Post Type without issue.

**Comment by willdoran** [comment]
I've reproduced this and fixed it. The limit check has been moved to create only not update for forms
