### ISSUE TITLE
Create new deployment: Requires me to log in

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#753]
When creating a new deployment, I enter my email, password, etc. I go through the tour. And it says my deployment is ready. I arrive at the deployment, but as a visitor -- no admin functionality. I still have to log in.

Ideally, the user would arrive logged in.

If that's not technically possible, they should at least be delivered to a dedicated "Hey, log in now." screen -- not an empty deployment. We can design a special screen for this, if needed.

cc/ @sophshep

**Comment by rjmackay** [comment]
We can redirect them to /login on their deployment. 
It might be possible to auto log them in.. but I don't think we've probably got other things to fix first.
