### ISSUE TITLE
No way of removing a post from a collection

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#754]
Once a post is added to a collection, there's no way of removing it. 

Possibly need to rethink behavior around adding things to collections. Could it work like Google+? 

![image](https://cloud.githubusercontent.com/assets/527589/10254072/0f2793de-6907-11e5-8f87-a8205297ee37.png)

cc/ @brandonrosage

**Comment by brandonrosage** [comment]
@sophshep Any objection to me mocking this up in the PL this week? If you want it, take it. But I think it should get pieced together relatively soon. It's a nasty UX at the moment.

**Comment by sophshep** [comment]
Go for it. I think we should just kind of copy the Google+ interaction - but let me know if you want to talk any of it through or need help with design or code.

**Comment by brandonrosage** [comment]
@sophshep Here's a mockup in the PL for a "custom fielder" pattern: http://github.ushahidi.org/platform-pattern-library/assets/html/2_fragments/#pl-pattern-forms

Without JavaScropt, it's just treated as a basic `<fieldset>`:

![Screen, without JS](http://d.pr/i/1aHUa+)

With JavaScript, it treats the `<legend>` as a button that looks like a `<select>` control, and puts the rest of the fieldset's content inside a dropdown:

![Screen, with JS](http://d.pr/i/169jY+)

**Comment by sophshep** [comment]
This looks perfect - love the "create collection" functionality too. It looks like when it's inline, it breaks a little:

![image](https://cloud.githubusercontent.com/assets/527589/10293200/20443e52-6b68-11e5-9ab4-afc0bcb8b65b.png)


Let's test it in layouts, then send it on over to dev team.

**Comment by brandonrosage** [comment]
Working on a fix to that. I'm halfway there. But I'm afraid it's going to call for a global revision to how we handle toggling. The change itself is minor, but it'd involve touching more than one pattern/layout.

**Comment by rjmackay** [comment]
This looks really good. We had some API issues that prevented implementing
removing posts in the first place. But having a pattern will make this much
easier too..

Would it make sense to share this pattern with things like publishing
posts/collects/etc to particular roles too?

On Mon, Oct 5, 2015 at 4:52 PM, Brandon Rosage <notifications@github.com>
wrote:

> Working on a fix to that. I'm halfway there. But I'm afraid it's going to
> call for a global revision to how we handle toggling. The change itself is
> minor, but it'd involve touching more than one pattern/layout.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/issues/754#issuecomment-145665234>.
>



-- 
Robbie Mackay

Senior Software Developer
Ushahidi Inc
m: +64 27 576 2243
e: robbie@ushahidi.com
skype: robbie.mackay

**Comment by sophshep** [comment]
2 things:

1. we should add a "remove from collection" button in the bulk editing in the list view of a collection
2. I'll replace pattern for permissions of who can see a post on the create post page with this

**Comment by brandonrosage** [comment]
@rjmackay The individual 'custom fieldset' fragment pattern, as well as the global 'toggle' pattern that supports it, are ready for implementation. Both are very-well documented in the Pattern Library's [Issue No. 6](https://github.com/ushahidi/platform-pattern-library/issues/6).

Here's a screenshot of the 'custom fieldset' pattern, for example.
![Custom fieldset](https://cloud.githubusercontent.com/assets/1136279/10322257/958c07a0-6c42-11e5-8bf5-41eea735f64b.png)

As you and I discussed, we've staged them in the Pattern Library, in a branch called [toggle-pattern](https://github.com/ushahidi/platform-pattern-library/tree/toggle-pattern). Do let me know how I can document or help implement this into the web client.

**Comment by sophshep** [comment]
In addition, the "Delete" button in the list-actions bar should become a "remove from collection" button when a user is viewing a collection, so that they have bulk editing capabilities.

![image](https://cloud.githubusercontent.com/assets/527589/10648772/194b593c-7806-11e5-9c70-1cdf67f6eeac.png)

**Comment by rjmackay** [comment]
@willdoran this needs implementing in the client. Probably some API work too to make it easier to find which collections a post is in..

**Comment by brandonrosage** [comment]
I've polished the pattern for this control with an ideal set of controls:

* A selectable list of Collections available to the user, which has a scrollable max-height in the event that the list is long.
* A control for creating (and selecting) a new Collection on the fly.
* A control for searching the list of available Collections.

![Custom fieldset](https://cloud.githubusercontent.com/assets/1136279/10895222/ae6336ae-8178-11e5-85a2-cec753588d43.png)

The sample pattern is in [Modules > Forms > Custom fieldset, with controls](http://github.ushahidi.org/platform-pattern-library/assets/html/3_modules/#pl-pattern-forms).
