### ISSUE TITLE
Site Language shows all langs, not just those actually translated

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#762]
In the general settings, should the language dropdown only show languages that v3 has been translated into? Currently it shows all languages.

![image](https://cloud.githubusercontent.com/assets/527589/10431233/a83ff754-70c9-11e5-817f-d660d94179de.png)

**Comment by sophshep** [comment]
By changing the language here to a RTL language, it should update the layouts accordingly.

**Comment by lupa18** [comment]
@sophshep changing language in settings, doesn't affect site. I tried deleting cache and offline browser info and nothing. 

![seleccion_038](https://cloud.githubusercontent.com/assets/463429/12493610/8a578c58-c064-11e5-99d5-f4d9cf83f19a.jpg)

I'm using origin/master from this repo

**Comment by aoduor** [comment]
Hey folks - one more thing to add in here. Would be great to generate this list only from the available languages on transifex here automatically:

https://www.transifex.com/ushahidi/ushahidi-v3/

**Comment by rjmackay** [comment]
@aoduor Jason's changes grab the languages from transifex if they're over 70% translated.. is that what you meant?
