### ISSUE TITLE
No place for new user to define display name

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#765]
When I sign up as a new user on an existing deployment (at deploymentname.ushahidi.io/register), it has me enter my email and password, but not a display name.

Then, as an admin, I can't see who just signed up:

![image](https://cloud.githubusercontent.com/assets/527589/10432795/3e1c785c-70d3-11e5-88b7-7a40feb7ec08.png)

**Comment by willdoran** [comment]
Ok I've added this as 
https://github.com/ushahidi/platform-client/pull/28 for client
and
https://github.com/ushahidi/platform/pull/786 for platform
if it fits I'll merge them into master
