### ISSUE TITLE
Map Settings Base Layer not updating

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#766]
When I change my mag settings base layer in my map settings, they do not update on the Map View. 

The map does update correctly on the map settings page:
![image](https://cloud.githubusercontent.com/assets/527589/10433066/d8daa0b6-70d4-11e5-9a7d-2f321248f1bd.png)

But not on the map view:
![image](https://cloud.githubusercontent.com/assets/527589/10433338/a575ce1a-70d6-11e5-85f6-95888b4700df.png)

**Comment by jshorland** [comment]
I'm pretty sure this was fixed, but now there is issue #956 which is P0
