### ISSUE TITLE
Mustang: Add full featured Post Pop-up

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#771]
A user should have the ability to edit or add a post to a collection directly from the post pop-up in the map view. It currently displays like this in the client:

![image](https://cloud.githubusercontent.com/assets/527589/10521757/2759b0ba-7337-11e5-9f68-59e2be326d9b.png)

It should display like this, with the date, edit button, and add to collection select.

<img width="339" alt="screenshot 2016-05-04 15 38 36" src="https://cloud.githubusercontent.com/assets/7965/15004701/6a45f71e-120e-11e6-8307-9214d2191bcf.png">
<img width="357" alt="screenshot 2016-05-04 15 39 12" src="https://cloud.githubusercontent.com/assets/7965/15004702/6a46817a-120e-11e6-8fdd-b3454e2ba918.png">

Pattern library shows the expected [popup pattern](http://github.ushahidi.org/platform-pattern-library/assets/html/3_modules/#pl-pattern-post-popup)

**Comment by jshorland** [comment]
Fails test. 

Pattern is not matched. see screen shot.

**Comment by rjmackay** [comment]
This is consistent with the current pattern library as in production. Updating the dropdown to match recent PL changes is out of scope for this. Closing.
