### ISSUE TITLE
Page after creating a new post type

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#772]
Currently, a user is directed to the "edit structure step" page directly after creating a new post type:

![image](https://cloud.githubusercontent.com/assets/527589/10523011/c720efc2-733d-11e5-88c8-62c10513880a.png)

Instead, they should be directed to the post steps setting first:

![image](https://cloud.githubusercontent.com/assets/527589/10523171/a4ffa6b2-733e-11e5-9883-9734e09292bf.png)

**Comment by rjmackay** [comment]
This was intentional to try and get users started settings up their post type quickly.
I think having to think about steps first is just going to confuse a lot of people who haven't even figure out what a step is yet. 
cc @jshorland
