### ISSUE TITLE
New Field Labels

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#773]
We should rethink what each of the field types are called. For example, I don't think a layperson (non web designer/dev) knows what a "Radio Button" is vs. a "Checkbox" vs. a "select"

![image](https://cloud.githubusercontent.com/assets/527589/10525361/ee2c6e32-7349-11e5-9f04-86ed3e5e4dab.png)

cc/ @brandonrosage

**Comment by rjmackay** [comment]
:+1: super happy to have some non-developer input on stuff like this. There are a few places like this we just rushed through to get to launch.

**Comment by sophshep** [comment]
Here are what the options should be. Some of them have a description.

-------
### Short Text
A sentence or less

-------
### Long Text
Multiple sentences or paragraphs

-------
### Number
*note for dev: should have radio button within the settings to decide on if it should be an integer (default) or decimal*

-------
### Location

-------
### Date

-------
### Time

-------
### Radio Button(s)
Allows the user to choose only one of a predefined set of options.

-------
### Checkbox(es)
Allows the user to choose one or more of a predefined set of options.

-------
### Related Post Type

**Comment by rjmackay** [comment]
> Related Post Type
I don't think thats accurate. The contents of the field is a "Related Post" .. not a post type.

> Time
We don't have this.. We have date + time which is a different thing. I suspect we should have both. If you're recording the time of an event you don't want to record date and time like separate things, you can't to record a datetime (at least from a data point of view)

**Comment by rjmackay** [comment]
Any thoughts on the layout of the type chooser? the current grid is super awkward and doesn't work well on smaller screens.

**Comment by sophshep** [comment]
Assigning back to myself to create a basic layout example in the PL

**Comment by brandonrosage** [comment]
I've created a very basic fragment-level pattern for "list items," which provides styles for `<li class="list-item">` and `<dt class="list-item"></dt><dd></dd>` HTML patterns for problems like this, where we need a simple list of content (selectable or not). We can expand on it, as needed.

![list items](https://cloud.githubusercontent.com/assets/1136279/10641603/8245a0d6-77df-11e5-8132-0ac70d5a8192.png)


Samples are here: http://github.ushahidi.org/platform-pattern-library/assets/html/2_fragments/#pl-pattern-list-items

**Comment by sophshep** [comment]
Love this, because it will also work best on a small screen and won't have the uneven heights issue of the current layout. @rjmackay do you have enough here or do you need a mockup?

**Comment by rjmackay** [comment]
I think this is good.. @willdoran another UI issue to look at this week

**Comment by sophshep** [comment]
Let's put this on hold until @brandonrosage & I finish up the new "create post" flow, which should be finished this week. I don't want anyone to have to do repeat work! I'll put the "PL to Client" tag on it when it's ready.

**Comment by rjmackay** [comment]
@willdoran did we iterate this when updating the post type editor?

**Comment by willdoran** [comment]
This went into the post type choice step but we haven't changed the type selection box. Not sure a list would be ideal in the modal dialog.

**Comment by aoduor** [comment]
Hey folks, just adding in my voice here. What's our intended course of action for this :)?

**Comment by rjmackay** [comment]
Right now this isn't flagged in a current sprint. We'll resolve if/when it is.. @jshorland should this go into Sprint 6?

**Comment by jshorland** [comment]
we should hold off putting this in until we have new patterns. Makes more sense to implement with new patterns once than implement twice at this point.

**Comment by aoduor** [comment]
Makes sense! :)

Thanks @jshorland and @rjmackay

Handheld Sent,

Angela Oduor Lungati,
Director of Community Engagement,
Ushahidi | www.ushahidi.com
