### ISSUE TITLE
Add social sharing

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#778]
Add sharing buttons to:
1. deployment
2. collection
3. individual posts

**Comment by derDieDasJojo** [comment]
1up

**Comment by jshorland** [comment]
Related: #490 

Needs:
1. deployment
2. collection
3. saved search
4. individual post
5. add post to survey (form)

Patterns are built

**Comment by jshorland** [comment]
@brandonrosage do you mind reviewing this and making sure we have all designs covered?

**Comment by brandonrosage** [comment]
Looks like we're all set. I have them all demonstrated currently in the `f-sharing` branch of the PL. I'll merge into the appropriate sprint branch when it's queued.

**Comment by rjmackay** [comment]
@jshorland I should flag that the issues in #490 still stand: because of the way the client is built, facebook/twitter/etc are unable to provide a useful preview for a deployment. I think we should look into fixing that, however it is a larger technical challenge so probably a separate task.

**Comment by rjmackay** [comment]
I think this is done? @jshorland ??
