### ISSUE TITLE
New Category with symbol Error

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#780]
When i have a symbol (in my case `>`) in the category description, it gives me an error

![image](https://cloud.githubusercontent.com/assets/527589/10583460/b9fd52a0-7652-11e5-85b0-480665b2a858.png)

**Comment by willdoran** [comment]
@sophshep Yep, so the regex for this is /^[\pL\pN\pP ]++$/uD so it matches letter, punctuation and numbers - should we improve the error message or does the regex need to change?

**Comment by sophshep** [comment]
What's the downside of allowing symbols here?

**Comment by willdoran** [comment]
It might have been legacy to protect against injection or to avoid html/js being inserted. I'll double check that it's ok but it should be possible to allow symbols @jasonmule @rjmackay what do you think?

**Comment by sophshep** [comment]
If we don't allow the symbols, could we update the error to say "You can't have symbols in your category description". It took me a while to realize why I was getting the error.

**Comment by willdoran** [comment]
Yep I can certainly do that!

**Comment by willdoran** [comment]
Ok I've created a pull request for it

https://github.com/ushahidi/platform/pull/785

once it's test pass I can merge it. @sophshep 
are the messages ok?
https://github.com/ushahidi/platform/pull/785/files

**Comment by sophshep** [comment]
Can you make it say "The category name..." rather than "tag name"? Otherwise, all good! Thanks.

**Comment by willdoran** [comment]
Yep done!
