### ISSUE TITLE
Design/build location picker for all 'location' fields

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#783]

**Comment by brandonrosage** [comment]
I've improved the location picker so that its search control behaves more like the global 'searchbar' and so that the input doubles as the location field's **_value_**.

![location field](https://cloud.githubusercontent.com/assets/1136279/16629849/313ff244-437d-11e6-9616-6b70950eabb4.png)

The assumption here is that, when a user types anything into the input, it provides buttons to "Search" or "Use your current location," as well as a brief list of search results for addresses and nearby venues. Selecting "Search" would fill the "results" list with a more complete list of results, if they didn't already see something that matched.

Whatever they leave in that field, either via selecting a search result or manually typing lat and long, will be captured as the value they're passing along to the post.

cc/ @rjmackay @jshorland

**Comment by rjmackay** [comment]
Close in favor of #1327
