### ISSUE TITLE
UX: Make error messages a little more visible

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#789]
Would be great if we changed the color of error messages to something more vivid e.g Red.

I was trying to create a new deployment with a used domain name and didn't realise there was an error message displaying on the top of the page in black :).
 ![screenshot](http://i.imgur.com/Gb0Xo7A.png)

**Comment by rjmackay** [comment]
This will be resolved by https://github.com/ushahidi/platform-cloud-interface/issues/89
