### ISSUE TITLE
Unable to load deployment on Ushahidi.io

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#790]
Related to #789.

So, i tried creating angela.ushahidi.io - with an email address that already has an existing deployment on it - and was oblivious to the error messages being shown up there - and it would seem the deployment got registered either way.

https://angela.ushahidi.io throws an error when trying to load on mobile and on web

![screenshot](http://i.imgur.com/Y49O1Jn.png)

**Comment by rjmackay** [comment]
Any *.ushahidi.io domain will still respond.. but the API won't.
Looking at angela.api.ushahidi.io ... I don't think this was registered.
Rather the domain is reserved.. probably from angela.crowdmap.com. I can free it up for you if you'd like?
