### ISSUE TITLE
Handling unviewable associated errors causing 403

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#793]
In the case that - for example a post - has an associated entity that is unviewable by the current user - for example a tag - the client will receive a 403 when it requests the tag. This causes the client to bounce the user to the login page.

This occurs because, while the post is cleared to be viewed it's associated entity may not be. At present only the tag ids are returned when a group of posts are viewed for example as a collection or as a list. The platform does not check at this point whether or not the tag is viewable by the current user.

The short temr solution has been to selectively ignore errors for certain entity types - notifications, tags etc.

There are a couple of options so far to address this:
1. Rework the at the sql level to ensure that only viewable entities are returned by the query - this is unpleasant as it will cause complex sql statements and may hit weird behaviour in sql and joins/sub-queries
2. Return the entire entity for each of the associated objects and parse the entities to remove any unviewable ones. This fits with the current behaviour of parsing the posts themselves to remove unviewable entities. It is also more straightforward however it requires a change on both the client and platform. It will also increase the amount of data sent in one time to the client, though with caching this may not be exceptionally bad.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-724

**Comment by rowasc** [comment]
Referencing #2392 since this will be important to review when hydrating forms and posts we'll need to make sure we handle this correctly and this is useful context.
