### ISSUE TITLE
Change Post Type limit messaging on "Mapper"

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#794]
At the moment, it says "You have reached the limit of post types for your plan. To get more simply upgrade your plan."

That would imply that an attempt has been made to increase their post types(which they can't) :D.. I know, nit picky but, I would prefer something along the lines of 

"Your current plan limits you to one post type. To get more post types, simply upgrade your plan"

:D :D

**Comment by rjmackay** [comment]
@jshorland assigning to you for testing with other limits.
