### ISSUE TITLE
Make SMSsync/FrontlineSMS available to mappers

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#800]
Should be included in free tier because
1). anyone in rural areas will need it
2). many mappers will need to apply for a zero rated application only for this feature
3). it's zero cost to us as long as integration and SMS costs remain on the user side.

@sophshep @brandonrosage @middle8media -- we'll need to coordinate un-limiting this feature with updating the plans page to have mapper include "SMS" included under the "mapper" plan. We should make clear in the detailed plans page that you only get SMSsync/frontline as a gateway in the mapper, and nexmo / twilio in surveyor. 

@rjmackay I see no real reason why we wouldn't give them frontline SMS in addition to SMSsync, as those both work in most countries, and it gives them an alternative option in case they can't get one working. Any opposition on your end?

**Comment by aoduor** [comment]
I'm in total agreement with this. TOTAL!

Handheld Sent,

Angela Oduor Lungati,
Director of Community Engagement,
Ushahidi | www.ushahidi.com

**Comment by rjmackay** [comment]
Closed in favor of private issue above ^
