### ISSUE TITLE
Add Date/Time and Categories to default basic post type

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#802]
Circling back from a discussion on v3 platform hipchat - I think these are essential fields that a deployer is likely to forget to add in the process of setting up their post type.

**Comment by rjmackay** [comment]
- Categories is already part of EVERY post type
- Date / time .. really depends on the post type. Some post types are NOT events so don't have an explicit date+time.
- When migrating from V2 we'll create a post type that matches V2.. I don't think the default on a blank V3 install needs to match V2 necessarily

Assigning to Brandon for consideration while thinking about steps/post types.

**Comment by aoduor** [comment]
Yes, maybe not all post types are you events, however I still see the need to have it up there up front and leave the user to decide whether they need it or not at least for the basic post type( so make it deletable). 

Handheld Sent,

Angela Oduor Lungati,
Director of Community Engagement,
Ushahidi | www.ushahidi.com

**Comment by rjmackay** [comment]
Closing in favour of https://github.com/ushahidi/platform/issues/752
