### ISSUE TITLE
Broken formatting on field type edit page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#803]
See below

![screenshot](http://i.imgur.com/9EEDKMa.png)

**Comment by rjmackay** [comment]
@brandonrosage @middle8media is there something we can do about this as a general issue?
Lots of the forms ended up like this after the RTL changes.
I can just add .clearfix classes everywhere.. but thats a pretty ugly solution. Labels and input following after radios and checkboxes should **just work**. Could we add a pattern for combining all the different form elements in one form and ensure it works without extra markup/classes?

**Comment by brandonrosage** [comment]
I got this. I'll work out a bulletproof form field pattern.

**Comment by middle8media** [comment]
Thanks Brandon, I know it will be bullet proof.

> On Oct 27 2015, at 6:16 pm, Brandon Rosage &lt;notifications@github.com&gt;
wrote:  

>

> I got this. I'll work out a bulletproof form field pattern.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/ushahid
i/platform/issues/803#issuecomment-151661756).![](https://github.com/notificat
ions/beacon/AA_EdMpZoZ4HVgYRE_1axn5NMQ-UNFIjks5o_-9KgaJpZM4GWd4Y.gif)

**Comment by aoduor** [comment]
Thanks for your attention on this, guys!

Handheld Sent,

Angela Oduor Lungati,
Director of Community Engagement,
Ushahidi | www.ushahidi.com

**Comment by brandonrosage** [comment]
I've staged a solution for more bulletproof form structure in the Pattern Library. 

I've documented all of it in Fragments (which includes patterns for [self-contained form fields](http://github.ushahidi.org/platform-pattern-library/assets/html/2_fragments/#pl-pattern-forms), like a label and input) and in Modules (which offers [a demonstration of a form with multiple form fields](http://github.ushahidi.org/platform-pattern-library/assets/html/3_modules/#pl-pattern-forms)).

I've assembled in such a way that doesn't totally deprecate the previous solution. That markup will continue to render as it has. This `.form-field` pattern I've added just cleans things up -- when you use it.

That said, part of the commit tidies up button patterns in such a way that it calls for changing the "Add Post" button(s) that are in the header and main navigation. To date, the pattern for that button has looked like this:

```
<a class="button button-create">
   <span>Add Post</span>
</a>
```

Going forward, it should look like this:

```
<a class="button button-primary">
   <span class="icon-left fa-plus">Add Post</span>
</a>
```

If @sophshep or @middle8media object to this revision, please pipe up. But that's where I steered form elements.

@sophshep + @middle8media: Can you review [these changes](https://github.com/ushahidi/platform-pattern-library) and let me know if they're good to go from the PL to @rjmackay for integration?

**Comment by middle8media** [comment]
Thanks @brandonrosage, everything looks good to me except the absence of the `@include icon` mixin.

Unless I am missing something shouldn't it be ...

```html
<a class="button button-primary">
   <span>Add Post</span>
</a>
```

```css
.button-primary {
    // styles
    
    .span {
        @include icon($before, plus)
    }

}
```

**Comment by sophshep** [comment]
I noticed the checkboxes break in a RTL layout:

![image](https://cloud.githubusercontent.com/assets/527589/10883804/07b6cc8c-813a-11e5-8c50-8e7a8c77e9fd.png)

As does the custom fieldset:

![image](https://cloud.githubusercontent.com/assets/527589/10883951/f27266e6-813a-11e5-9e75-99f2945051d2.png)

We are also defining other form elements on the Basics page, but their markup differs from the stuff you added. We should make sure they're all consistent (and probably defined in the same place). I originally thought that the single elements (ie field, checkbox, etc) would be defined on Basics, and then multiple form elements would be on Fragments - but that's up to you. Currently we're defining form things on basics, fragments, and modules.

**Comment by sophshep** [comment]
We should also go through all of the layouts to make sure they are updated with the new patterns (like here: http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/create-post.html) 

Brandon- feel free to make a task for me to do this if you've had enough of forms yet!

**Comment by brandonrosage** [comment]
@sophshep I've made revisions to address your notes. Thanks for catching that! All better?

@middle8media I have some follow-up explanation coming for you regarding icons. Until then, I'll just say it was intentional to create a pattern that didn't require us to create a new class name that's _unique to the fragment_ for every different icon. We already have class names that define the icon. I think we should the existing ones, and then dictate just their presentation (positioning) at the fragment level, if necessary.

**Comment by middle8media** [comment]
@brandonrosage I figured you did, just wanted to bring it up.

**Comment by sophshep** [comment]
All looks good to me!

**Comment by sophshep** [comment]
Though there is still redundancies in the pattern library. I'd suggest we just delete all the form elements from the basics page: http://github.ushahidi.org/platform-pattern-library/assets/html/1_basics/#pl-pattern-forms

**Comment by rjmackay** [comment]
@middle8media @brandonrosage can someone confirm if this is fixed??

**Comment by rjmackay** [comment]
Stale issue. Closing
