### ISSUE TITLE
Bypass 'Select post type' when adding posts on deployments with one post type

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#809]
The flow from the "Add Post" button should be as follows:

* Select 'Add Post" button
* If the deployment has more than one post type, present the 'Select post type' view so they can select the appropriate one. Otherwise, take them directly to the 'Add Post' view for the deployment's lone post type.

Two related notes:

* The 'Add Post' view for a given post type should have a unique URL, like `/posts/add/post-type-name`. Not simply `/posts/create`.
* The `<title>` tag for the 'Add Post" view(s) is currently prepended with "Create Post." That should read "Add Post," to be consistent with the page title rendered on the page within the browser window.

**Comment by rjmackay** [comment]
@jshorland this seems like its worth getting done soon? .. easy to do, but fairly big impact.

**Comment by jshorland** [comment]
Agreed. Let's get try to get it in to our V3.1 release

**Comment by rjmackay** [comment]
@willdoran did this happen? Can you update the status?
