### ISSUE TITLE
Changing 'Site Language' has no affect on the deployment's language

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#811]
Sostene Cyr, who recently created [a 'Mapper' deployment](https://bw-siriri.ushahidi.io/views/map), reported that they're trying to change their deployment's language settings to French, and it fails.

I've been able to replicate the problem on a test deployment. When I hit "Save," the deployment responds very briefly, but nothing changes. No language change or anything.

![site language](https://cloud.githubusercontent.com/assets/1136279/10944890/dbb5c9dc-82e0-11e5-8ea0-204384e08ecc.png)

**Comment by sophshep** [comment]
Repeat issue of #762
