### ISSUE TITLE
Both the map buttons and Leaflet label at the bottom right appear in front of the parallax.

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#814]
Repair in css override, check z-index set correctly relative to parallax.

<img width="935" alt="screen shot 2015-11-09 at 22 01 39" src="https://cloud.githubusercontent.com/assets/2694405/11054148/17a904aa-8736-11e5-9c2f-fdd7079ae288.png">

**Comment by rjmackay** [comment]
Think this is fixed? @willdoran can you confirm?

**Comment by willdoran** [comment]
It's fixed by the next merge.
