### ISSUE TITLE
Collecting retrospective (past) data 

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#819]
Question from user on intercom:

I am interested in how Ushahidi can be used to track the details of events that have passed. More specifically, I am interested in how it might be used to track the recent student protests in South Africa with a focus on what was said on social media.

I think this is a use case for:
- researchers
- media/news orgs
- ongoing conflicts, environmental and humanitarian issues

Aha! Link: https://ushahiditeam.aha.io/features/PROD-721

**Comment by rjmackay** [comment]
As mentioned in chat:
- We only pull recent tweets.
- We could try for older from the API.. but twitter does weird things with their older messages.
- Without using a service like Gnip you can't reliably dig much deeper on twitter (AFAIK)

**Comment by jshorland** [comment]
This strays too far from "real-time" data collection and response in product vision. We can keep this low priority until we've perfected the real-time part.
