### ISSUE TITLE
Implement Intercom.io

### ISSUE THREAD

**Issue by middle8media** [ushahidi/platform#821]
@rjmackay 

https://github.com/ushahidi/dotcom-craft-cms/blob/master/craft/templates/_layout.html#L82-L88

**Comment by caharding** [comment]
Any updates here? I think it will be really helpful to be able to separate logged in users support from acquisition stuff. A lot of folks coming to .com for support who prob would so so in app if it were an option.

**Comment by caharding** [comment]
Also is there a way to install this on the Open Source platform so that just admins can send us support queries? If not we should prob find a way for people to register as Ushahidi developers to get support on Open Source issues.

**Comment by rjmackay** [comment]
This needs to be implemented in multiple places:
- On ushahidi.io/create and /tour
- On individual deployments
- *maybe* on OSS deployments. Though there are privacy issues to consider (we should offer an opt out)

**Comment by rjmackay** [comment]
One concern: does intercom track individual users? (vs aggregate??) Need to investigate privacy.

**Comment by willdoran** [comment]
Intercom does track individual users, it collects at the least ip, user-agent:
https://docs.intercom.io/pricing-and-terms/privacy

If the user shares name or email address with us through intercom that information is also stored.

The information they store is considered to be shareable with "third party's". So to an extent the browsing habits may be sold on. It's a relatively smart business plan if they have enough sites using intercom there is a decent chance they will be able to see ip patterns of behaviour across different domains. They will also see browsing habits, user behaviour and metrics to improve their own product.

The data is stored in the US, or at least may pass through US servers which might be a concern for certain types of users.

Their policy stipulates that they sell/share only aggregate information - not personally identifiable. It is arguable that it doesn't matter what form they sell the data in as properly anonymising data is a hard problem and they do not publish the method they use for this process.

**Comment by caharding** [comment]
Could we dive deeper into the potential challenges we see? I feel as though
we have tools for remaining completely anonymous (open source) and that we
can educate people that if there data is super sensitive they should self
host. From a user support perspective, we'll really struggle to support our
users, grow our user base, and understand feature usage without some sort
of user event tracking. Can we strike a compromise to meet the needs of
both our normal users and those with very sensitive privacy challenges?
Intercom is used by a lot of tools we use like Waffle board. I think there
is a way to make this work.

On Thu, Jan 21, 2016 at 9:44 AM, will <notifications@github.com> wrote:

> Intercom does track individual users, it collects at the least ip,
> user-agent:
> https://docs.intercom.io/pricing-and-terms/privacy
>
> If the user shares name or email address with us through intercom that
> information is also stored.
>
> The information they store is considered to be shareable with "third
> party's". So to an extent the browsing habits may be sold on. It's a
> relatively smart business plan if they have enough sites using intercom
> there is a decent chance they will be able to see ip patterns of behaviour
> across different domains. They will also see browsing habits, user
> behaviour and metrics to improve their own product.
>
> The data is stored in the US, or at least may pass through US servers
> which might be a concern for certain types of users.
>
> Their policy stipulates that they sell/share only aggregate information -
> not personally identifiable. It is arguable that it doesn't matter what
> form they sell the data in as properly anonymising data is a hard problem
> and they do not publish the method they use for this process.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/issues/821#issuecomment-173650441>.
>



-- 
Charlie Harding
Product Director

**Comment by willdoran** [comment]
I didn't mean to imply a bias in either direction - I only mean to state what the third party group states. I don't see there as being an issue in using intercom for our purposes so long as our privacy statement incorporates/cover the privacy statements of our third party tools.

I think @rjmackay suggested a configuration option for the open source release. I'm not sure to what extent that is necessary for the cloud release. And I would definitely agree that having a section on the implications - in as unbiased a manner as possible - of sharing personally identifiable information is a great idea.

**Comment by caharding** [comment]
Sorry Will, while writing I was thinking of a conversation that came up on
the retreat where I felt resistance to event tracking. I appreciate the
balanced approach. I'd like for Robbie to way in.

On Fri, Jan 29, 2016 at 11:01 AM, will <notifications@github.com> wrote:

> I didn't mean to imply a bias in either direction - I only mean to state
> what the third party group states. I don't see there as being an issue in
> using intercom for our purposes so long as our privacy statement
> incorporates/cover the privacy statements of our third party tools.
>
> I think @rjmackay <https://github.com/rjmackay> suggested a configuration
> option for the open source release. I'm not sure to what extent that is
> necessary for the cloud release. And I would definitely agree that having a
> section on the implications - in as unbiased a manner as possible - of
> sharing personally identifiable information is a great idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/issues/821#issuecomment-176914097>.
>



-- 
Charlie Harding
Product Director

**Comment by rjmackay** [comment]
We discussed a bit with the team. I'd suggest we roll this out to our cloud/.io customers with an potential to "opt out" if needed. We should ensure our privacy policy reflects the info that intercom collects.
For open source - I would leave intercom disabled by default for now.

Looking at the features intercom provides it seems like they're tracking less that I thought, and much of the detail will be defined by what events we choose to send their API. Though for privacy purposes we have to assume once we include their JS, they can track anything they like.

**Comment by jshorland** [comment]
I think the opt-out option should be OSS for now. 


Jess Shorland
Product manager
jess@ushahidi.com

**Comment by caharding** [comment]
Robbie, can you review the privacy policy one more time to make sure it
reflects the kind of JS event tracking Intercom is doing? Opt-out through
OSS seems the easiest path right now. Not sure if Intercom has an opt-out
function.

On Fri, Feb 5, 2016 at 10:05 AM, Jess Shorland <notifications@github.com>
wrote:

> I think the opt-out option should be OSS for now.
>
>
> Jess Shorland
> Product manager
> jess@ushahidi.com
>
>
>
> > On Feb 4, 2016, at 10:30 PM, Robbie Mackay <notifications@github.com>
> wrote:
> >
> > We discussed a bit with the team. I'd suggest we roll this out to our
> cloud/.io customers with an potential to "opt out" if needed. We should
> ensure our privacy policy reflects the info that intercom collects.
> > For open source - I would leave intercom disabled by default for now.
> >
> > Looking at the features intercom provides it seems like they're tracking
> less that I thought, and much of the detail will be defined by what events
> we choose to send their API. Though for privacy purposes we have to assume
> once we include their JS, they can track anything they like.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/ushahidi/platform/issues/821#issuecomment-180175417>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/issues/821#issuecomment-180473181>.
>



-- 
Charlie Harding
Product Director

**Comment by willdoran** [comment]
This has been created and setup to work with intercom for cloud. It passes more details about the user and makes the session active only while the user is logged in.
