### ISSUE TITLE
Set up cron jobs/scheduler for users to manage frequency of incoming data from SMS/Email/Twitter etc

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#824]
Right now, looks like this runs in the background, but would be really useful for users to manage frequency with which data comes in from different sources they've set. Sharing a screenshot from v2 just for context :).

![screenshot](http://i.imgur.com/SiKhvg4.png)

**Comment by rjmackay** [comment]
You need to set up cronjobs for these right now. You can set the frequency of the cron job as needed.
I'm not going to build this into platform UI. Its an implementation detail that users should never have to think about.
cc @jshorland in case you disagree?

**Comment by aoduor** [comment]
Piggy backing on this one more time. 

While I understand the resistance to build this into the platform UI, its a bit frustrating not having the option to manually pull a plug and pull in items from my data sources.

Case in point - @natmanning set up a deployment to pull in tweets, having followed instructions to the tee, and the deployment wasn't pulling in tweets, and we don't know why.

It would be great to be able to set this frequency myself, as a user, OR get communication on how frequently this happens, or an indication of failure/success to pull in tweets.

**Comment by rjmackay** [comment]
>  its a bit frustrating not having the option to manually pull a plug and pull in items from my data sources.

That sounds like a completely different problem. ie. we need a "Test provider" button when configuring data sources.. and we need logging of errors.

**Comment by rjmackay** [comment]
Logged a new issue ^
