### ISSUE TITLE
Update post views for post with steps based on pattern library

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#828]
http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-detail-with-steps.html

**Comment by rjmackay** [comment]
Double checking - was this a task for the current sprint?

**Comment by jasonmule** [comment]
This should probably be merged wih #808

**Comment by willdoran** [comment]
Yep and it's actually already in 829 :)

**Comment by rjmackay** [comment]
Alright. I'll clear the size and close it out :) Do #829 and #808 overlap?

**Comment by willdoran** [comment]
Slightly, I've merged from master into 829 when 808 went in.
