### ISSUE TITLE
Wrong post type styling in add new post

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#833]
Steps to reproduce:

1. Go to quakemap.ushahidi.io
2. Click "add post"
3. See screenshot

![screen shot 2015-11-20 at 10 31 57](https://cloud.githubusercontent.com/assets/3224856/11294192/a4f2458a-8f72-11e5-97ed-322b0ba66bfa.png)

**Comment by willdoran** [comment]
This is fixed in the posts UI updates. I think I can land it today and then it will look like the pattern library layout:
http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-add-select.html
