### ISSUE TITLE
Discoverability of open source deployments

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#834]
Is there a way to add an option on open source to make their deployment discoverable?

**Comment by aoduor** [comment]
+1 on this!! This is so so so important!

On Fri, Nov 20, 2015 at 10:39 AM, Jess Shorland <notifications@github.com>
wrote:

> Is there a way to add an option on open source to make their deployment
> discoverable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/issues/834>.
>



-- 
-- 
Angela Oduor Lungati.
Ushahidi Inc <http://ushahidi.com/>.
Platforms: Ushahidi <http://download.ushahidi.com/> | Crowdmap
<https://crowdmap.com/> | CrisisNET <http://crisis.net/> | SwiftRiver
<https://wiki.ushahidi.com/display/WIKI/SwiftRiver>
Mobile: iOS <http://bit.ly/ushahidi_ios_app> | Android
<http://bit.ly/Ushahidi_android_app> | SMSSync
<http://smssync.ushahidi.com/>
Skype: ngelzy
Twitter: @AngieNicoleOD <https://twitter.com/AngieNicoleOD>

**Comment by Shadrock** [comment]
This is an important feature that goes hand-in-hand with the idea that Ushahidi can help connect to other online communities and tools. I'm not sure if it's relevant in anyway, but the [old Crowdmap](https://crowdmap.com/) had a search feature on the homepage and [Brian had done some work tutorials on publicly listing deployments](https://www.youtube.com/watch?v=aCDO5DyNt0Q).

**Comment by willdoran** [comment]
@jshorland  Is this the right place to comment?

This sounds super awesome. It would be nice to have category tags and geography, in theory we could use a deployment to map deployments that mark themselves as discoverable.

We could add a discoverable setting to settings and push an alert for it via intercom or indeed on login post the update. It might be nice generally to have a dialog pop in when an admin logs in post an update with a quick description of cool new features we've added and a link off to the docs so they can start using them.

If we want to break discoverable settings down we could offer 4 options:
- User geo data from your public posts to make your deployment discoverable
- Share your public tags to our discoverable tag cloud
- Set your geography on a map
- Add tags you wish to be discoverable under

We can pull the above into our deployment of discoverable deployments.

**Comment by jshorland** [comment]
Closing in favor of #892
