### ISSUE TITLE
No save button on "add collection

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#835]
Steps to reproduce: 
1. Login to demo.platform.ushahidi.com, email: info@ushahidi.com, pass: testing
2. Click "add collection" button on the lower left hand menu
3. See screen shot
![screen shot 2015-11-20 at 11 15 04](https://cloud.githubusercontent.com/assets/3224856/11294916/5291aa00-8f78-11e5-9e0a-a941e4b2cd62.png)

**Comment by willdoran** [comment]
This one is super weird...I shall fix it now!

**Comment by willdoran** [comment]
Ok so this is broken by PL changes, which seem to effect buttons that inherit from the navigation menu. I think I can fix it by moving the modal.

**Comment by willdoran** [comment]
ok fixed.
