### ISSUE TITLE
FrontlineSMS integration with V3; docs and API URL

### ISSUE THREAD

**Issue by ptkn** [ushahidi/platform#836]
https://wiki.ushahidi.com/display/WIKI/Connecting+FrontlineCloud+to+Ushahidi is the old docs.  They work(ed) for v2 and now they are missing a couple of things for v3.  
 - There are some text changes needed wrt Frontline subscriptions
 - This doc probably needs to be on support.ushahidi.com?
 - Some inline pointers in the Data Sources page on the app is necessary in Jess and my opinion
 - What is the target URL that Frontline should post the SMS content to? Something like https://<<YOUR-ID>>.ushahidi.io/posts/create is needed for the docs. 

I'm testing on https://frontlinecloud.ushahidi.io

**Comment by aoduor** [comment]
Thanks for flagging this for us @ptkn :).

cc @rjmackay @jshorland just flagging this for us internally to fix - until we get this in, we're not able to work with frontlineSMS on platform

**Comment by rjmackay** [comment]
@jshorland Do you want to queue pull this into the data sources sprint to complete the documentation?

**Comment by rjmackay** [comment]
Pretty sure this was resolved.
