### ISSUE TITLE
Unnecessary lines in Recent Activity Timeline

### ISSUE THREAD

**Issue by pierreverbakel** [ushahidi/platform#837]
The Timeline Column on the right that is shown when selecting 'Activity' shows for every item 
'New Post' as the first line. Since all posts are new typically it costs a lot of screenspace since 1 line per item. I would suggest to remove that one and use colors in the background of the box if the idea is to indicate that the Post is recent. The current setup is quite generous concerning the space and the size of the fonts. For me everything could be more compact. But flavours of taste could differ. 
Hope this helps.

**Comment by rjmackay** [comment]
@brandonrosage @middle8media UI feedback. Don't know if this needs immediate action really.

**Comment by jshorland** [comment]
Closing. No longer an issue with Mustang.
