### ISSUE TITLE
Date Time selector gets covered by the Map Image when entering a field

### ISSUE THREAD

**Issue by pierreverbakel** [ushahidi/platform#839]
When entering the Value for the Date and Time of a Report the visual block gets covered by the Map field under it. It seems that the selector is not a the right HTML layer level

**Comment by willdoran** [comment]
This is still occurring. @middle8media could you take a look?

**Comment by middle8media** [comment]
screenshot of error for reference. I will get on this asap.

![image](https://cloud.githubusercontent.com/assets/1033332/13828031/e8d6145a-eb95-11e5-9b21-023ac97b2988.png)

**Comment by middle8media** [comment]
This is good to go.
