### ISSUE TITLE
User CSV import

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#855]
A client project is asking to import some users.. I suspect this will become a common use case. So lets make it easy.

**Comment by rjmackay** [comment]
@jshorland assigned to you for triage / prioritization

**Comment by jshorland** [comment]
yeah, this is pretty low for me compared to everything else. How many users are we talking?

**Comment by rjmackay** [comment]
Maybe just leave it in the backlog until a client needs it?

**Comment by jshorland** [comment]
yep.

**Comment by willdoran** [comment]
I would favour ldap/AD over this

**Comment by rowasc** [comment]
hrm. I'm closing this until/unless we get a request to work on something like this again. While it would be great to have, it's not something we will really be able to tackle in the next year unless we get a specific enterprise request or a grant needs it, in which case we will create a more detailed issue.
