### ISSUE TITLE
Unable to mark structure as complete when location field is required

### ISSUE THREAD

**Issue by puffadder** [ushahidi/platform#860]
I have filled all the necessary fields with proper values but I'm unable to mark structure as complete. This is preventing me from publishing my post.

Attaching a screenshot for reference.
![ushahidi_screenshot](https://cloud.githubusercontent.com/assets/16331045/11861203/d8158f4e-a4a3-11e5-9462-863fa88ad04e.jpg)

**Comment by lupa18** [comment]
I guess this is for setting location as mandatory. I experimented the same issue. 
You use the map, but the form not realize that you fill anything, so it believe that it's incomplete. 

I have the same problem here. 

Workaround: edit basic post type and mark location field as not mandatory :-/

**Comment by puffadder** [comment]
Yes, that seems to be the problem!

If I make location not mandatory, I am able to mark the structure as complete.

Thanks for the suggestion!

**Comment by willdoran** [comment]
This should be fixed in the current release :)
