### ISSUE TITLE
Collections button in left side of main page is not working

### ISSUE THREAD

**Issue by lupa18** [ushahidi/platform#867]
I tried first with own installation and then with a deploy: https://pruebalup.ushahidi.io
Browser: Firefox 43.0 (Linux 64)

You click in "New collection" and nothing happens

![seleccion_032](https://cloud.githubusercontent.com/assets/463429/12266658/1d698a58-b923-11e5-95f7-618e02b809ef.jpg)

**Comment by willdoran** [comment]
This is working in the latest master, I think we need to do a new release and update soon.

**Comment by lupa18** [comment]
Ok, but I'm using master branch :-/

**Comment by willdoran** [comment]
Ah, interesting. Do you get any javascript console errors? In firefox you can access the console via:

Tools->Web developer->Web console

You'll need to refresh the page, if you get errors would you mind posting a screen shot. 

What version of linux are you using? Is it Ubuntu and if so what build?

Thanks!

**Comment by lupa18** [comment]
I installed from https://hub.docker.com/r/quantumobject/docker-ushahidi-platform/ it means Ubuntu 15.04 and from git master branch of Ushahidi platform. 

Here log: http://pastebin.com/C22CQ1gu

It seem to be a problem gettting collections from api/v3

**Comment by willdoran** [comment]
Ok, cool, I'll take a look and see if I can reproduce it locally.

**Comment by willdoran** [comment]
It seems as though the client is not able to access any of the resource for the platform located at:

https://devel.tedic.org/api/v3/

It's getting a 403 for the data it's trying to pull from the backend.

It looks like an apache permission issue. 

@rjmackay @jasonmule have you seen this occur with docker?

**Comment by lupa18** [comment]
Any thing I put after "/" give us 404 ... apache configuration problem ?

**Comment by rjmackay** [comment]
I'm still seeing this issue on `develop` .. on the QA site. Will investigate further
