### ISSUE TITLE
Add disclaimer for monthly recurring payments on all payments pages

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#869]
There was confusion about recurring payments from a user. We need to have this clearly stated on the payments page to avoid any confusion.

The disclaimer should read: 

"You'll be charged (plan cost)/month plus taxes, if any, on a recurring basis. You can change your plan at any time on your plans page, or cancel your subscription by contacting us (with link to contact us). By clicking "continue", you agree to authorize this recurring charge.

**Comment by willdoran** [comment]
Does this work visually for the placement of the disclaimer?
<img width="1280" alt="screen shot 2016-01-27 at 16 49 39" src="https://cloud.githubusercontent.com/assets/2694405/12629466/13269730-c516-11e5-84ea-7765c4cfa2dc.png">

**Comment by jshorland** [comment]
Can we make the text a bit smaller?

Jess Shorland
Product manager
jess@ushahidi.com

**Comment by willdoran** [comment]
Yep, I can make it the same size as the  required fields message

**Comment by jshorland** [comment]
Great!


Jess Shorland
Product manager
jess@ushahidi.com
