### ISSUE TITLE
Figure out creation process for TechSoup approved applicants

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#870]
Once Tech Soup approves a free plan for an applicant, they send a confirmation email informing them of how to create an account and deployment. They should never be asked to provide card details or apply again once they've been approved.

- Tech soup will provide a link in the email that sends them to a creation page specifically for approved grassroots applicants. This link will include a unique token.
- [ ] Task to create batches of 100+ tokens for zero rated deployments (saved as CSV)
- [ ] Modify sign up page to accept discount token
- [ ] Transition away from Recurly to [Chargebee?]  - enable creating deployment w/o credit card

**Comment by rjmackay** [comment]
Replaced by https://github.com/ushahidi/platform-cloud-interface/issues/102
