### ISSUE TITLE
Get grassroots applications into spreadsheet automatically.

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#871]
Currently, applications come in through helpscout and then Angela and I move the info into a spreadsheet for easier review and aggregation. I would like to streamline this. I believe we lose design customization in google forms. Is that correct? 

An alternative solution would be to see if we can link Wufoo responses to a spreadsheet automatically. Assigned to @brandonrosage to answer the design question, but also pinging @willdoran and @jasonmule to help if possible.

**Comment by rjmackay** [comment]
Done

**Comment by rjmackay** [comment]
Done. I've used zapier to push from the current form directly into google sheets. No design change at all
