### ISSUE TITLE
Task 1: Role API

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#872]
- [ ] Add spec test covering Role API
- [ ] Add role endpoint to platform
- [ ] Add role repository with CRUDS operations

**Comment by willdoran** [comment]
@jasonmule, I think Role should have both icon and colour properties similar to tag, is that possible?

**Comment by rjmackay** [comment]
>  Role should have both icon and colour properties similar to tag
That seems overkill. Can we just skip that unless someone requests it later?

**Comment by willdoran** [comment]
Yep, we can leave it
