### ISSUE TITLE
Deployment discoverability tool v2 for both hosted and OSS

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#892]
A tool for discovering deployments of various types/categories

Purposefully vague right now.

**Comment by jshorland** [comment]
https://app.intercom.io/a/apps/hl5rfiga/inbox/unassigned/conversations/6186400032
https://app.intercom.io/a/apps/hl5rfiga/inbox/unassigned/conversations/6191198202

Two users who need to discover deployments around them

**Comment by jshorland** [comment]
Rough notes: https://docs.google.com/document/d/1a0DsSj1AGFzD-FqPViI4kxunUMBZXKQfAlCnBH-ttMY/edit

Epic scope: https://docs.google.com/document/d/1MoVVo8-jXDHeqT0MajGzBJAc4dOS_Ir4cCvj4W-GNVA/edit

cc: @willdoran @Shadrock

**Comment by jshorland** [comment]
From @Shadrock: This is an important feature that goes hand-in-hand with the idea that Ushahidi can help connect to other online communities and tools. I'm not sure if it's relevant in anyway, but the old Crowdmap had a search feature on the homepage and Brian had done some work tutorials on publicly listing deployments.

**Comment by jshorland** [comment]
From @willdoran: @jshorland Is this the right place to comment?

This sounds super awesome. It would be nice to have category tags and geography, in theory we could use a deployment to map deployments that mark themselves as discoverable.

We could add a discoverable setting to settings and push an alert for it via intercom or indeed on login post the update. It might be nice generally to have a dialog pop in when an admin logs in post an update with a quick description of cool new features we've added and a link off to the docs so they can start using them.

If we want to break discoverable settings down we could offer 4 options:

User geo data from your public posts to make your deployment discoverable
Share your public tags to our discoverable tag cloud
Set your geography on a map
Add tags you wish to be discoverable under
We can pull the above into our deployment of discoverable deployments.

**Comment by jshorland** [comment]
@willdoran we *could* do what crisisnet was supposed to eventually do: ushahidi.org

**Comment by Shadrock** [comment]
I love, love, love the .org idea. I've been thinking about it a lot lately. It would also make a sensible place to put programs, etc...

**Comment by jshorland** [comment]
Shhhh we're going to secretly delight our team.

**Comment by jshorland** [comment]
v1 is at ushahidi.com/discover

**Comment by rjmackay** [comment]
@rowasc @jrtricafort Closing this out since it exists on ushahidi.com
