### ISSUE TITLE
Missing delete button on post detail view and individual posts in list

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#893]
- Pretty sure we had a delete button on post detail view. Could you reinstate this?
- Similarly I think it'd be useful to have a delete button on individual posts in the post list?

**Comment by middle8media** [comment]
@rjmackay I am assuming you mean adding a "Delete" button along with the yellow "Edit", "Share" and "Collections"?

There is a delete above. Which means user would select the post via checkbox then delete.

![image](https://cloud.githubusercontent.com/assets/1033332/13012307/beb80782-d178-11e5-9cce-fed99f2d1cfe.png)

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/fb0216d8bdc86f89b4259e1bfc8f690e9c3e5ab6
