### ISSUE TITLE
CSV error message confusing for non technical people

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#905]
Selected a .docx 

See screenshot for error message

The wording should read something like:

"File type not supported. Please upload a .csv file less than xx"

![screen shot 2016-02-15 at 11 19 59 pm](https://cloud.githubusercontent.com/assets/3224856/13067186/8b7322ce-d43b-11e5-88fb-4477a888b5f7.png)

**Comment by willdoran** [comment]
Ok I think this is done.
