### ISSUE TITLE
After clicking "save role" should redirect back to main roles page

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#906]
Steps:

1. navigated to roles
2. clicked "add role"
3. filled in relevant information
4. clicked "save"
5. saw success message appear at top of screen

Expectation: 
Either 
1. redirect to main roles screen or
2. option to save and add another

**Comment by willdoran** [comment]
So at the moment, the page redirects to the edit page for the newly created role. I will change it to send the user back to the roles page.

I could add the save and add another function pretty easily BUT it should really be added for all entities such as user, category etc. Do you want me to go ahead and do that?

There is one UI question, should there be two buttons side by side?
[Save] [Save and add another]

**Comment by willdoran** [comment]
Ok actually, adding the save and add another is super simple code wise BUT I need UI input. @middle8media when we get your platform up would you be able to help me make the button I'm creating...eh...look not awful :)
