### ISSUE TITLE
Location Search does not grab businesses

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#908]
Action: I tried to make a post on the QA deployment and when prompted to "Enter A Location" and Search, I searched for a local business in LA "Old Style Guitars" but nothing was found

Expected result: When I search for a business or location, it gives me a list of options (like Crowdmap did)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-714

**Comment by willdoran** [comment]
The search works correctly for a department store in Dublin but "Old Style guitars" doesn't work for me either. I'll check if there is an issue when there are multiple issues.

**Comment by rjmackay** [comment]
This isn't something we explicitly tried to support.. I'd guess its pure luck that this works for some locations already. I think its a matter of what is in the OSM database right now .. Old Style Guitars isn't.

Jess - assigning to you for triage in a future sprint.

**Comment by caharding** [comment]
Ideally we can integrate whatever locations we had in Crowdmap at some
point in the future. You may need to change the UI so it doesn't create
this expectation in the short term.

On Wed, Feb 17, 2016 at 3:03 PM, Robbie Mackay <notifications@github.com>
wrote:

> This isn't something we explicitly tried to support.. I'd guess its pure
> luck that this works for some locations already. I think its a matter of
> what is in the OSM database right now .. Old Style Guitars isn't.
>
> Jess - assigning to you for triage in a future sprint.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/issues/908#issuecomment-185449700>.
>



-- 
Charlie Harding
Product Director

**Comment by CR0CKER** [comment]
I've also been under the impression that business that are on OSM already should be found by the search function. Especially if the surveys are related to existing business, i.e. marking businesses that are "safe spaces", this would be extremely useful. Any plans to make this happen?
