### ISSUE TITLE
Add guidelines for CSV file upload 

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#910]
to include:
- max size of file
- how to match structure to post type
- how to format location in CSV file so platform supports it

Brief instructions should be included in /data-upload screen.
![screen shot 2016-02-16 at 3 57 49 pm](https://cloud.githubusercontent.com/assets/3224856/13090852/2822b03c-d4c6-11e5-95c4-73f1e27522be.png)

**Comment by willdoran** [comment]
@jshorland for the second point
how to match structure to post type

Do you mean how they should layout the csv in terms of columns? The tool will let them match whatever columns they choose against post type fields.

**Comment by jshorland** [comment]
Oh, fantastic. Ignore second point then. I'll test that out.

**Comment by willdoran** [comment]
Ok, cool, I'm adding the other two as items under the initial explanation.
