### ISSUE TITLE
CSV Upload Error Message is blank

### ISSUE THREAD

**Issue by sebm90** [ushahidi/platform#912]
![image](https://cloud.githubusercontent.com/assets/5349387/13109484/cbc8d316-d579-11e5-887a-0bc7eed45b83.png)

Happened when I uploaded a CSV file that doesn't meet the guidelines. It would be helpful if the alert box explained why the error occurred.

**Comment by rjmackay** [comment]
Do we know **what** the 500 error was here? We shouldn't be throwing a 500 error regardless so theres more than just an error reporting bug here.

**Comment by willdoran** [comment]
I think this was caused by the dir permission issue related to the header image upload as there was an error on application logs.
