### ISSUE TITLE
Duplicate icons in front-end

### ISSUE THREAD

**Issue by sebm90** [ushahidi/platform#913]
![image](https://cloud.githubusercontent.com/assets/5349387/13109532/1a0160f2-d57a-11e5-8576-bf4a5c881051.png)

On http://qa.ushahidi.com/settings/forms, mousing over the delete button causes two trash icons to appear.

**Comment by jshorland** [comment]
Adding on to this as I experienced the issue as well on Post types screen.

![screen shot 2016-02-17 at 8 32 10 am](https://cloud.githubusercontent.com/assets/3224856/13110952/0c8e0f48-d551-11e5-9ef5-e1365a0c92ce.png)

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-client/commit/d5ebc5e2a808db1ee6d9e1c5af870a19e626ea12

waiting to be merged via https://github.com/ushahidi/platform-client/pull/88
