### ISSUE TITLE
Page Title doesn't change when switching to "Roles settings" Page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#918]
Steps to reproduce
* Click on settings
* Click on any menu item except roles
* THEN click on roles

Expected outcome
* On switching navigation from one settings page to the other, page title should change to reflect "Role Settings" page

Actual Outcome
* e.g I'm switching from viewing the "Users" page. Page title remained "Managing Users", despite the fact that I'm on the roles settings page. 

This has happened every single time i'm switching from one page to the roles settings page. Using Google Chrome.

**Comment by willdoran** [comment]
Fixed! thanks
