### ISSUE TITLE
Forced to update password field when editing a user

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#919]
So, they will likely be times an admin is editing certain details about a user, but may not necessarily want to change the password.

I tried editing a single user, and only wanted to change the name and role, and when I clicked on save(without updating the password field) - and the "Save button" was NOT responsive. On updating the password field, i was successfully able to edit this user.

Recommendations
* If we're going to force users to update the password field, let's update our error messaging around it
* Would be great NOT to have to update a user password everytime i'm editing a single user :)

**Comment by willdoran** [comment]
@jshorland @rjmackay could you comment? We can stop forcing users to update the password when updating a user quite easily but may be there is a historical reason I'm not aware of for why we do this

**Comment by rjmackay** [comment]
This is absolutely a bug. This wasn't the previous behaviour.. in fact we hide the password field initially so its obvious you can skip it.

**Comment by willdoran** [comment]
I've changed the behaviour so that a password update is not required when editing a user. On the edit user page, the password field is hidden initial. The user can click a text link 'Update Password' which then reveals the input box.

**Comment by willdoran** [comment]
This was merged into the last release.
