### ISSUE TITLE
Unable to create a new saved search

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#920]
A couple of screenshots to explain my issue.
![screenshot1](http://i.imgur.com/SqVjywD.png)
With this first screenshot, I'm logged in as a user with a custom role that only allows me to manage posts
![screenshot2](http://i.imgur.com/0e7XwWJ.png)
With this second screenshot, I'm logged in as the admin

In both cases, I'm unable to create a new saved search :(

**Comment by willdoran** [comment]
We tracked this and it's most likely a privilege issue. @jasonmule is going to resolve it!

**Comment by aoduor** [comment]
privilege issue even for an admin @willdoran? Oiyoyoi... Alrighty, will wait :)

**Comment by willdoran** [comment]
@aoduor For user I can update but not save, will fix that.
For admin I can do both on my local and on qa. Would you terribly retesting in case I'm missing something?

**Comment by aoduor** [comment]
Just tried it again, no luck. Mind sharing your screenshot so that I can compare?

**Comment by aoduor** [comment]
Ok, so this works out for admin users. :D.
