### ISSUE TITLE
Custom User Role saves without selecting permissions

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#921]
Steps to reproduce
- Click on Roles
- Then click on add new role
- Fill out name and description
- Leave permissions options unchecked

Expected outcome
- I should get an error message prompting me to select at least one option OR there should be a "None" option selected by default that would just allow for member access i guess?

Actual outcome
- The form submitted and saved with no error message passed to me

![wailing](http://38.media.tumblr.com/ccf52ac03ad74320e34e9c86facaa8c5/tumblr_ml4hr6nKnQ1qjemo2o1_250.gif)

**Comment by willdoran** [comment]
We actually don't check if permissions are set. I think technically you can have a role with no permissions, all you can do is read stuff that is available to everyone. I think that's a valid use case but would need @jshorland @rjmackay input.

It's an easy change to prevent the pending sobbing epidemic :)

**Comment by rjmackay** [comment]
- I think role w/ no permissions is valid. On a private deployment you might want that so you can give people minimal access.
- Is a role with no permissions identical to a member? Can you delete the member role? in which case this is needed to recreate it.

**Comment by willdoran** [comment]
You can delete the member role but not the admin role.

**Comment by rjmackay** [comment]
Maybe the best solution is just to add a confirm dialog when saving a role with no permissions??

**Comment by jshorland** [comment]
Add confirm dialog when adding without permissions is a good solution. There are many valid cases for not adding any of the permissions we have currently.
