### ISSUE TITLE
Bulk Deletion of Custom Roles?

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#923]
This is more of a question and for us to brainstorm.

What do you guys think about adding the ability to bulk delete roles?

**Comment by rjmackay** [comment]
Seems like a really minor usecase - when would you want to delete many roles?

**Comment by jshorland** [comment]
@rjmackay can you grab stats on:
1. Average number of roles per deployment
2. Range of number of roles across all deployments
3. number of deployments with > 5 user roles
