### ISSUE TITLE
Communicate to user which geographic database is being used.

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#929]
When a user adds a post - if they use the location search - no real information is given about which database is being queried. This is important because certain databases will contain information that others do not. It appears that this deployment is using OpenStreetMap (OSM). I tested this by entering a highly specific business that was created in OSM. There is information at the bottom right of the map that tells which rendering is being used (OSM) and which imagery is available (Mapquest)... but this could be different from the database. For example, is the Mapquest database being used? Or is it the Mapquest one? It may be that I'm just reading this wrong... but I find it confusing. 

![create_post_geo_database](https://cloud.githubusercontent.com/assets/4574998/13131794/eab2b156-d5bb-11e5-9afd-83040e161b35.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-711

**Comment by aoduor** [comment]
@rjmackay @jshorland I'm bumping this up your radar as well. Is this something we can get done fairly quickly?

**Comment by jshorland** [comment]
- As someone searching for a location in the location picker as I either submit a new post or edit a post's location, I want to know which geographic database is being used in case I need to search a different DB for my exact location.

cc: @justinscherer we will need to figure out how we better and where we communicate this to the user.
