### ISSUE TITLE
CSV Import Guidance needs editing

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#930]
This is still quite confusing. The guidance about geographic information looks like I need to script something... I doubt most users were understand this. I would suggest either using standard geographic terminology or ley terms such as "column". 
![csv_import_guidance](https://cloud.githubusercontent.com/assets/4574998/13132130/4d4bb2de-d5be-11e5-8e68-b938d09e2594.png)

**Comment by aoduor** [comment]
Yeah, i'm a little confused here too.

**Comment by aoduor** [comment]
Another recommendation, it might be worth actually giving what a sample csv upload file would look like to the user on this instruction page, maybe have that dynamically switch based on post type selected by a user.

See below( akin to v2)

![upload](http://i.imgur.com/FSbj3z4.png)

**Comment by rjmackay** [comment]
Can I close this out? We've redone the way we handle lat/lons so its more clear.

**Comment by aoduor** [comment]
I think we can.
