### ISSUE TITLE
Uploaded .csv does not display

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#931]
I might be missing something... but I uploaded a .csv (downloaded from the RNI deployment: http://rni.ushahidi.com/reports/download) which seemed to go just fine but never displayed in any way.

**Comment by aoduor** [comment]
I'm not sure csv files from v2 work, unless the columns match the structure of your post type 

Handheld Sent,

Angela Oduor Lungati,
Director of Community Engagement,
Ushahidi | www.ushahidi.com

**Comment by aoduor** [comment]
I take that back. You can upload ANY csv file, and then you'll get redirected to a page that asks you to map your CSV columns to post fields of the post type you had earlier selected. I think we can close this one, yes @rjmackay?
