### ISSUE TITLE
CSV Data upload failed, but user notification says it was successful

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#932]
I created a test CSV upload file using MS Excel for Mac(don't give me no stinky eye :D) for basic post type with the following columns(purposely leaving out categories AND not setting location to lat/lon columns as instructed on the page)
* Title
* Description
* Location

On upload, I got a message saying "File upload successful", yet it failed

![icry](https://49.media.tumblr.com/tumblr_mbqk0s3ar01riae2mo1_500.gif)

**Comment by rjmackay** [comment]
Fixed - this was a bug in the client.
ushahidi/platform-client#92
