### ISSUE TITLE
Improve Validation before attempting to upload CSV file

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#935]
I purposely did not select a post type before selecting the file I would like to upload, and again, I got a prompt telling me my file upload was successful. 

![whhy](http://i.imgur.com/I6jHU1s.jpg)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-709

**Comment by rjmackay** [comment]
Minimal validation care of ushahidi/platform-client@50fdbc7

**Comment by rjmackay** [comment]
I think we need to improve this still - but much lower priority
