### ISSUE TITLE
Consider Geocoding of locations in CSV files

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#936]
As it stands now, per instructions on the data import page, users have to specify lat/lon values. While in cases where we're simply using a CSV file downloaded from another v3 deployment, as it stands now, users are manually creating CSV files to upload. Assume a user has 100-500 posts they're trying to upload, they would have to check for lat/lon information for all these 100/500 posts. It would be easier for them to provide a location name, and the have us work in the background to determine lat/lon information.

This has been implemented in v2.

**Comment by jshorland** [comment]
Closing in favor of #1246
