### ISSUE TITLE
Questions on CSV Upload

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#938]
1. Does a user need to set Column Headers? If yes, are these case sensitive?
2. Does the order of the columns affect upload?
3. How are we handling duplicate posts?

**Comment by rjmackay** [comment]
Does a user need to set Column Headers? If yes, are these case sensitive?

Yes they need to have headers, however these headers can be whatever you like

    Does the order of the columns affect upload?

No

    How are we handling duplicate posts?
We're not at the moment

**Comment by aoduor** [comment]
Thanks @rjmackay :)
