### ISSUE TITLE
Add 'configure posts' step to CSV import

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#945]
CSV import needs a second step to configure fixed values. This was designed but not implemented
http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-import-values.html

- [x] Add option to publish posts imported via CSV during import process
- [x] Add option to set categories on imported posts
- [x] Assign value to unused post fields
- Skip the 'verified' toggle as it should be part of the 'unused post fields' if it exists

Currently we're only allowing for mapping of CSV columns to post fields, but would also be great to add the option to set posts as published, or set categories.

**Comment by jshorland** [comment]
I second this.


Jess Shorland
Product manager
jess@ushahidi.com
