### ISSUE TITLE
CSV import fails on Mac OS9 line endings

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#947]

**Comment by rjmackay** [comment]
![manage users qa deployment](https://cloud.githubusercontent.com/assets/7965/13144048/e45163ba-d6ac-11e5-84ea-13078c936603.png)

**Comment by jshorland** [comment]
Also received this error from a .csv saved on microsoft for mac: The Array Must Contain Unique Values

**Comment by willdoran** [comment]
That's interesting. I believe we need to set
auto_detect_line_endings=1

**Comment by willdoran** [comment]
I think we can do that in
https://github.com/ushahidi/platform/blob/e834389e2443d0598e9be477540fbf22d814c09f/application/bootstrap.php

is that correct @zhalloran @rjmackay

**Comment by rjmackay** [comment]
@willdoran makes sense. Can you test it out and PR?

**Comment by rjmackay** [comment]
@rowasc this might be worth checking while you're hacking on other CSV issues?

**Comment by rowasc** [comment]
@rjmackay will do.

**Comment by rowasc** [comment]
This was done and tested. @jshorland @willdoran . Closing. (Feel free to reopen is this is wrong! )
