### ISSUE TITLE
No validation during CSV/Post field matching process

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#951]
I successfully imported a CSV file, but "Forgot" to match CSV columns to post fields, and when I clicked "Import", a blank record was imported into my instance.

**Comment by willdoran** [comment]
Technically, only required fields need to be set and we have a validation check for that but I agree there is no reason to import empty entities. I've added a check with an alert saying that at least one field must be assigned to proceed.

**Comment by willdoran** [comment]
This is done and will be merged into develop.
