### ISSUE TITLE
Non descript alert passed to user when creating a user whose password doesn't meet set rules

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#952]
I tried creating a psssword with 5 characters for a new user, as expected, i was unable to successfully create the user. 

The password field was highlighted in red, and the I got a blank alert as shown below:-

![blankalert](http://i.imgur.com/d5yVYJb.png)

While I know that the password field is the problem because it's highlighted, we need to add a proper error message to pass to the user.

Also, quick question, what rules are we using for password fields?

**Comment by willdoran** [comment]
I'll take a look at the blank error message now.

The current requirements for password are:

minlength="7"
maxlength="72"

We're not forcing anything else at the moment.

**Comment by willdoran** [comment]
@aoduor I'm seeing an error message that says:

Validation Error
password must not be empty

It should include the min and max length. Would you mind rechecking that you get the blank error message when you try to save with a password of 5 characters?

**Comment by rjmackay** [comment]
Thats very weird. Those blank errors should only be happening with API 500 errors right now and 1. we should ever have a 500 for a normal usecase (ie. validation fail) 2. we can expose messages from the 500s by fixing Access-Control headers on the API too

**Comment by aoduor** [comment]
Just verifying that this is still happening for me at the moment.

**Comment by aoduor** [comment]
Also, another question, do we have any other requirements apart from # of characters :)? @willdoran

**Comment by willdoran** [comment]
I think that's it, we should probably add a password "strength" checker
