### ISSUE TITLE
On log in screen, clarify that you can user either email address/username to log in

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#955]
As it stands now, the UI asks for "Email address" and password, while we can actually use usernames and passwords to log in. 

For clarity's sake, maybe we should clarify that you can use EITHER your email address OR a username?

**Comment by rjmackay** [comment]
This isn't correct. Users don't HAVE a username. 
The only case where email isn't really email is on the first login with admin / admin. Thats only because I haven't figured out a better solution yet. However for all cloud deployers, they can only ever log in with an email.
