### ISSUE TITLE
Unable to place marker on location

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#957]
Via intercom

"My deployment is:

https://cyclonewinston.ushahidi.io/views/map

I have been locating information from filtered tweets but sometimes the interface wont let me add a location to the map. It mostly happens when I can’t find the location using the search tool and I manually scroll and zoom to the desired location. Once I have the location centred on the map I can no longer just click on it to place the marker. I think it’s because the pan tool has been used and it isn’t switching across to the place marker tool. Maybe you could suggest buttons to change from panning to placing a marker for future improvements.

Thanks for your help,"

**Comment by rjmackay** [comment]
@aoduor can you figure out steps to reproduce this at all? I can't make it happen..

**Comment by CJBann** [comment]
This happens on both Internet Explorer and Chrome browsers when editing a post to add a location. If you zoom into the map to the point where the land becomes plain white and pan around a bit, then try and place a marker. Eventually after panning and zooming you can no longer add a marker. If you zoom out enough you will be able to place the marker again, but then zoom in and it doesn't work.

**Comment by rjmackay** [comment]
@jshorland assigning to you for testing/confirmation.

**Comment by jshorland** [comment]
@rjmackay where should i test?

**Comment by jshorland** [comment]
Passes QA on qa.ushahididev.com. Closing, reopen if i was supposed to test elsewhere
