### ISSUE TITLE
Post types not showing in filters

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#959]
Post types:
on filtering navigation bar, it doesn’t differentiate between post types, just says “all types” and “unstructured”

![screen shot 2016-02-29 at 11 27 55 am](https://cloud.githubusercontent.com/assets/3224856/13406446/8840a35e-def1-11e5-9b82-878647296388.png)

**Comment by willdoran** [comment]
I think this is actually two issues:

1. Unstructured is being displayed
2. filters are not being updated when categories or post types are added.

**Comment by willdoran** [comment]
Ok this should be fixed by [104](https://github.com/ushahidi/platform-client/pull/104)
