### ISSUE TITLE
Map editor is on default location, not marker location+zoom

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#960]
In individual post edit view, the map view under "location" is centered on the map settings default location and zoom. It should be on the lat/lon of the post that has been uploaded via CSV.

**Comment by rjmackay** [comment]
This *might* happen on normal posts, not just CSV

**Comment by jasonmule** [comment]
Could not reproduce this. Could you confirm if this is still happening?

**Comment by rjmackay** [comment]
@jshorland assigned back to you to QA

**Comment by jshorland** [comment]
This is still occurring for me with CSV import through chrome web browser on qatesting.ushahididev.com

Steps to reproduce in CSV import:

1. Login with email: jess@ushahidi.com, password: password
2. check map settings. 
3. default zoom = 2, default lat = -1.3048035, default lon = 36.8473969
4. import.  
5. Select "basic post type" and upload CSV file here: https://docs.google.com/spreadsheets/d/1XNWgZeOlpPmmQrq01uUDpZQT2cDa8JRLt1Okj172vmo/edit#gid=0
6. map policy_id = title, lat = lat, lon = lon, construction = description
7. finish import
8. on list view, select first post in list and click "edit"
9. Scroll to map view in post

Expected outcome:
Map auto zoomed to see map marker

Actual outcome: 
Map is centered and zoomed as dictated by "default settings" set by admin
![screen shot 2016-04-12 at 9 58 17 am](https://cloud.githubusercontent.com/assets/3224856/14464763/dbd26f46-0095-11e6-8487-211d47b15900.png)

I can't reproduce with add posts via web because the user adding posts selects a location on the map vs. importing a lat/lon.

**Comment by rjmackay** [comment]
Suspect this happens for all posts, not just CSV imported

**Comment by jshorland** [comment]
Passed testing. Post detail now centers and auto zooms to location of post.
