### ISSUE TITLE
Blank General Settings Page

### ISSUE THREAD

**Issue by FIU-Editor** [ushahidi/platform#963]
The page for General Settings is blank. We did not have this issue with Ushahidi v3.1, so what could have caused this?

![blank general settings](https://cloud.githubusercontent.com/assets/17600339/13471460/affd5f52-e07e-11e5-8321-7ac20521453c.PNG)

**Comment by willdoran** [comment]
Hi what tag version are you using for the client?

**Comment by FIU-Editor** [comment]
I'm working with the open-source version, so I suppose the master branch.

**Comment by rjmackay** [comment]
I think this might be resolved on the latest version now. Can you update your code and let me know if that fixes this issue?
