### ISSUE TITLE
Extra, Non-deletable Step in Post Type & Lack of Step Options

### ISSUE THREAD

**Issue by FIU-Editor** [ushahidi/platform#964]
When adding a post, there is an impassable step by the name of "Post" with nothing but a long text box "description" field, before the step that was added manually. This is of great concern because it may impede the ability of users to input data in our deployment.

![post types step issue](https://cloud.githubusercontent.com/assets/17600339/13471807/2eb497a6-e080-11e5-94b1-50bbba326b97.png)

In addition, there has been no discernible way to delete or name steps. Was this feature unavailable in versions 3.0 and 3.1 as well, or has it been moved elsewhere?

Thank you.

**Comment by willdoran** [comment]
@FIU-Editor Hi there,

Are you working from the master branch?
The first aspect will be fixed in the next patch. I'm adding issues for the update/delete of steps. We'll have that fixed as soon as possible.

**Comment by willdoran** [comment]
@middle8media 
Can we add UI to the pattern library to cover step name edit and step delete? And I can implement them in the client.

**Comment by middle8media** [comment]
@willdoran this should be good to go

**Comment by willdoran** [comment]
@middle8media perfect thanks I'll add it in.

**Comment by middle8media** [comment]
actually, making a quick fix now

**Comment by middle8media** [comment]
good to go now. @willdoran let me know how it goes.

**Comment by willdoran** [comment]
@FIU-Editor this is in this [pull](https://github.com/ushahidi/platform-client/pull/107) once it's through our tests I'll merge it to master and let you know! 

Thanks for reporting the bug!

**Comment by FIU-Editor** [comment]
Thank you for your help!

**Comment by willdoran** [comment]
@FIU-Editor Ok great, I will hopefully be integrating the fixes into master today. I will update here once it's done!

**Comment by jshorland** [comment]
Was this finished @willdoran and can we close?

**Comment by willdoran** [comment]
Yep, this is in develop and will go into the next release.
