### ISSUE TITLE
Missing API Endpoints Resulting in Login Failures

### ISSUE THREAD

**Issue by aeroheart-c6** [ushahidi/platform#969]
### The Setup

Tried to deploy Ushahidi 3.x on an Apache server. I managed to fix the links and everything so the client is now able to redirect to different parts of the app, and also reference the api url properly.

This frontend installation has a base url under `/monitoring-v3`. And the platform is based under: `/monitoring-v3/platform`
### Logging in

Initially, when logging in, the API endpoint returns an error of invalid scopes. Namely, these are:
- roles
- permissions
- csv

Which are mysteriously not added in the database when `install.php` was first executed. So I added them in manually (which I'm not sure if it was the right thing to do)
### Expected behaviour

Logging in should have yielded no problems now.
### Actual behaviour

The frontend client tries to reach a /api/v3/roles endpoint which is a non-existent endpoint in the platform API.

Could I have setup the project wrongly? Locally I have it setup in Nginx (on the production server, it was in Apache). So If you need the server settings, just tell me if you need more information.

**Comment by rjmackay** [comment]
A few things to start with:
- install.php doesn't do any install, it just checks if requirements are there.
- You need to run migrations with phinx by running `bin/phinx -c application/phinx.php`

But it sounds likely you've just got mismatched versions of the API and client. Those scopes and endpoints were added with a recent release make sure you have the latest code for both platform and platform-client.. then run migrations again and see if that fixes the missing scopes and endpoints.

**Comment by aeroheart-c6** [comment]
Hi, thanks for the response. I currently reset my copy of the repositories to `v3.2.1-rc.1`.

I have to ask, I assume that's `bin/phinx migrate -c application/phinx.php` right? Because I'm currently having problems with `bin/phinx migrate -c application/phinx.php`. It's giving off a `invalid default value for 'end_time' error. I'm attaching a screen shot of the red box generated by phinx:

![screen shot 2016-03-10 at 8 10 06 pm](https://cloud.githubusercontent.com/assets/734243/13669108/40a6e4fa-e6fc-11e5-983b-01840ffa44b8.png)

**Comment by aeroheart-c6** [comment]
Update: It was a MySQL sql_mode issue. Just removed the NO_ZERO_DATE option in the strict mode and the migrations worked fine.

Also, after the migration, I was able to login into the site already. Thanks!

**Comment by aeroheart-c6** [comment]
As an addition, wouldn't it be a nice thing to have an option to be able to easily deploy ushahidi with a fixed url prefix rather than assuming it's always in the root `/` url?
