### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#980]
Add two factor authentication to API

Aha! Link: https://ushahiditeam.aha.io/features/PROD-705

**Comment by willdoran** [comment]
If we are ok with the user installing google authenticator we can go this direction:
https://github.com/antonioribeiro/google2fa
http://www.slideshare.net/allandenot/two-factor-authentication-with-laravel-and-google-authenticator

We could also go the yubikey direction:
https://github.com/bitbeans/Yubikey

Are there other nicer services we could use?

**Comment by rjmackay** [comment]
@jshorland this has been waiting around for months? do we want to finish it off and deploy it? or shall I icebox it?

**Comment by jshorland** [comment]
One of those issues that slipped through the cracks. Let's finish this up and get it out. On phone but please put it in appropriate column?

**Comment by rjmackay** [comment]
Putting back to waiting for sprint. We can pick it up and fix anything thats changed in the next sprint

**Comment by jshorland** [comment]
Moving this up in priority given our need to increase our security.

**Comment by rjmackay** [comment]
Iceboxing this for now

**Comment by timmwille** [comment]
I'm very curious what the status is about this one?
