### ISSUE TITLE
Responder client having trouble with email integration

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#984]
Deployment url: guyanaelectiontracker.ushahidi.io (soon to be switched to votelikeaboss.ushahidi.io)

note from client: 

I've been having some issues with capturing posts via email in the platform. Basically, I've configured the email data source as required and tested the function but to no avail. I am able to see the emails sent to the specific email address via an external client but not within Ushahidi. 

Can you please advise if there have been any reported issues of such with other instances of the platform and if there may be a fix or something I'm missing?

1. I've advised him to make sure two factor authentication is OFF in his email client
2. Is this at all affected by the fix @jasonmule has been working on? If so, is it possible to get a timeline to deploy?

**Comment by rjmackay** [comment]
Can you get in touch with the deployer and check if they're having better luck now?

**Comment by jshorland** [comment]
Checking in with him today, will update soon.

**Comment by jshorland** [comment]
Update: Hi Jess, 

Thanks for providing the update. I've checked the platform and we are indeed experiencing an influx of emails. However, it seems as if the same emails are being repeated on each page. Might there be an explanation and fix for this? 

Thanks again for your guidance.

**Comment by rjmackay** [comment]
@willdoran @jasonmule could one of you look into this?

**Comment by jasonmule** [comment]
I am not able to reproduce this. Is the email account set up to remove emails deleted through IMAP?

**Comment by jshorland** [comment]
What's the status of this? Are we going to delete all of his email posts?

**Comment by rjmackay** [comment]
Not sure what we have/haven't done here.. I can see 5376 emails in the messages table. But none of them have posts associated??

**Comment by jshorland** [comment]
Do these appear as “unstructured posts” in the deployment itself? 


Jess Shorland
Product manager
jess@ushahidi.com

**Comment by rjmackay** [comment]
No without a post associated they won't see then at all
