### ISSUE TITLE
Date Range picker overlaps the input and displays off screen on small screens

### ISSUE THREAD

**Issue by middle8media** [ushahidi/platform#985]
### Expected behaviour
the date picker should not overlap the input, nor should it display off screen

### Actual behaviour
![upload_thumb](https://cloud.githubusercontent.com/assets/1033332/13827482/1f47c7a2-eb93-11e5-92fa-d6d39516fe52.png)

![image](https://cloud.githubusercontent.com/assets/1033332/13827505/31e2d834-eb93-11e5-8dfc-ff1e2c479a35.png)

### Steps to reproduce the behaviour/error
on large and small screens ...
Click "Search and Filter"
Select a "Date Range"

**Comment by rjmackay** [comment]
This should be fixed by mustang
