### ISSUE TITLE
Intercom not grabbing deployment name and URL

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#987]
### Expected behaviour
In intercom you can see the deployment name and URL

### Actual behaviour
These events aren't working...

### Steps to reproduce the behaviour/error
View users on Intercom, you will see that we don't have their info

**Comment by willdoran** [comment]
This behaviour is in the branch but has not been pushed to the staging deployment. I will arrange that it be pushed now.

**Comment by willdoran** [comment]
This is resolved! Thanks!
