### ISSUE TITLE
Categories should be able to be assigned as child to parent post type(s)

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#991]
### Expected behaviour
When I create a category as an admin, I want to match it to an appropriate post type(s) in a child/parent relationship so it will only be seen when contributors are adding posts of that particular post type(s). Categories should be able to map to multiple post types. 

### Actual behaviour
Currently, all categories appear under every post type when adding posts (though, only the selected audiences can see them)

### Steps to reproduce the behaviour/error
1. Log into deployment as user who has access to category management in a deployment with multiple post types
2. Navigate to "add category"
3. Add and save new category
4. Navigate to "add post"
5. See all categories listed no matter which post type you choose

**Comment by rjmackay** [comment]
I'm not sure about this one.. it adds a huge amount of complexity.
If you want a category as a child of a post type.. why not just add a
custom field to that post type instead?
Part of the point of categories is that they're universal..


On Wed, Mar 23, 2016 at 7:29 AM, Jess Shorland <notifications@github.com>
wrote:

> Expected behaviour
>
> When I create a category as an admin, I want to match it to an appropriate
> post type(s) in a child/parent relationship so it will only be seen when
> contributors are adding posts of that particular post type(s).
> Actual behaviour
>
> Currently, all categories appear under every post type when adding posts
> (though, only the selected audiences can see them)
> Steps to reproduce the behaviour/error
>
>    1. Log into deployment as user who has access to category management
>    in a deployment with multiple post types
>    2. Navigate to "add category"
>    3. Add and save new category
>    4. Navigate to "add post"
>    5. See all categories listed no matter which post type you choose
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/issues/991>
>



-- 
Robbie Mackay

Head of engineering
Ushahidi Inc
m: +64 27 576 2243
e: robbie@ushahidi.com
skype: robbie.mackay

**Comment by jshorland** [comment]
Closing this issue based on category research and feedback on this basecamp thread: https://basecamp.com/1931265/projects/1216937/messages/56706215#comment_406789758
