### ISSUE TITLE
mysqli_real_escape_string with php 5.5 getting error with Kohana MVC framework

### ISSUE THREAD

**Issue by msankar1991** [ushahidi/platform#996]
With php 5.5 we need to use for this method only 

```
mysqli_real_escape_string($link, $_POST["data"]);
```

$link - Will acts as database connection.

https://github.com/ushahidi/platform/tree/master/application/classes/Database

So here how I need to get database connection in controller or model file for filtering the data for form values with kohana framework structure.

**Comment by rjmackay** [comment]
Sorry I'm not at all sure what you're asking? What are you trying to do?
You shouldn't be manually calling mysqli functions at all as they're all handled within the Kohana DB libraries..
