### ISSUE TITLE
On hosted deployements, 'Documentation' link in footer points to a non-accessible docs site

### ISSUE THREAD

**Issue by ihatehandles** [ushahidi/platform#998]
### Expected behaviour

User is supposed to be taken to https://www.ushahidi.com/support

### Actual behaviour

User is taken to http://docs.ushahidi.com/, which redirects to https://www.ushahidi.com/

### Steps to reproduce the behaviour/error

Log in to your hosted deploy, and click on the Documentation link in the footer

**Comment by rjmackay** [comment]
I think this is fixed in develop but needs to be deployed.

On Mon, Mar 28, 2016 at 10:08 PM, Sam <notifications@github.com> wrote:

> Expected behaviour
>
> User is supposed to be taken to https://www.ushahidi.com/support
> Actual behaviour
>
> User is taken to http://docs.ushahidi.com/, which redirects to
> https://www.ushahidi.com/
> Steps to reproduce the behaviour/error
>
> Log in to your hosted deploy, and click on the Documentation link in the
> footer
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/issues/998>
>



-- 
Robbie Mackay

Head of engineering
Ushahidi Inc
m: +64 27 576 2243
e: robbie@ushahidi.com
skype: robbie.mackay

**Comment by ihatehandles** [comment]
Noted
